### ISSUE TITLE
Initial Push for Core Boostrap 4 Components

### ISSUE THREAD

**Issue by BobbieBarker** [ng-bootstrap/ng-bootstrap#1]
This issue is to keep track of our over all work and progress towards providing angular 2 components for the core bootstrap 4 javascript components. 

- [x] Accordion #17
- [x] Alert #2 
- [x] Buttons #14
- [x] Carousel #12 
- [x] Collapse #11 
- [x] Datepicker #20 
- [x] Dropdown #4 
- [x] Modal #3 
- [x] Pagination #22 
- [x] Popover #9 
- [x] Progressbar #25
- [x] Rating #26
- [ ] ScrollSpy #5 
- [x] Tab #7 
- [x] Timepicker #24 
- [x] Tooltip #8 
- [x] Typeahead #21

**Comment by arg20** [comment]
I wanna contribute guys. If I lock myself up, really work on my angular 2, go through all your code to learn your coding standards, will you be patient & merciful on my first PR?

**Comment by Foxandxss** [comment]
Feel free to discuss stuff you want to work before you try any PR so you don't waste your time.

The problem we have right now is that we are waiting for angular core team to make some movements, we are discussing lot of patterns to implement certain things... All of this makes a bit harder the external collaboration.

Also, don't trust our actual code as the best way to do X because we are still iterating some patterns. For example, accordion is completely broken and needs to change quite a bit.

All being said, welcome and feel free to comment on the issues / pr we have open :)

**Comment by arg20** [comment]
Thanks @Foxandxss, muy bueno tu blog! I'll make sure to pitch in if I can.

**Comment by pkozlowski-opensource** [comment]
So, we've got initial / basic implementation of all the core components except of: buttons, carousel, tooltip/popovers, modal, scroll-spy.

Work started on all the mentioned components and the status is:
* buttons: blocked on ng2 forms API change
* carousel: blocked on RC.2 release that has required fixes
* tooltip/popovers: in progress, no blockers
* modal: in progress, no blockers
* scroll-spy: we've got a PR, needs review, potentially design

All the animation work is blocked on rc.2 release.

**Comment by pkozlowski-opensource** [comment]
Update: buttons just landed via 44adfd7d53367f6ff48f9046ee448912662f35d4

**Comment by pkozlowski-opensource** [comment]
Update: carousel just landed via 2dc5228972e013450552b11013d362f08eeeefb9

**Comment by pkozlowski-opensource** [comment]
Update: tooltips just landed via e768a548a68db1a6662cad2cac36886f21f9ea5c

**Comment by pkozlowski-opensource** [comment]
Update: popovers just landed via 91ba7898d28ec8b461bd10489746bc9c9a9e253e

**Comment by pkozlowski-opensource** [comment]
Update: initial version of timepicker just landed via 6fcaea568e64c713f7607b4d846c52218362029d and f4388994bcf90d69e0356077b81164189ffd92bd.

**Comment by pkozlowski-opensource** [comment]
Update: typeahead just landed via 0fc6c000dcaccdf2eeb341dbec32a35bd54c04c3

**Comment by pkozlowski-opensource** [comment]
Update: modal just landed via 3ef99c5e82357e4f72a58b3db79136ee883a9e33 and will be part of alpha.3. 

Datepicker schould land this week and will be part of alpha.4.

**Comment by pkozlowski-opensource** [comment]
Update: datepicker just landed via 9e8c5c00f4c9cd65dc13a934642806b892da6688

**Comment by pkozlowski-opensource** [comment]
With datepicker landing the only remaining missing directive is scrollspy and we've got already an issue to track it. As such we can close this catch-all issue now.

It was a long ride but we are close to be feature-complete now!
