### ISSUE TITLE
Document supported browsers

### ISSUE THREAD

**Issue by mgol** [ng-bootstrap/ng-bootstrap#1000]
### Bug description:
The site and, optionally, the GitHub README should specify browsers/platforms supported by the library.
Examples:
Angular 2: https://angular.io/docs/ts/latest/guide/browser-support.html
Angular 1: https://docs.angularjs.org/misc/faq#what-browsers-does-angular-work-with-
jQuery: https://jquery.com/browser-support/

### Link to minimally-working plunker that reproduces the issue:
N/A

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: N/A

ng-bootstrap: N/A

Bootstrap: N/A

**Comment by pkozlowski-opensource** [comment]
@mgol the intention is to support the same set of browsers as Angular 2 and we've got automated tests to prove this: https://github.com/ng-bootstrap/ng-bootstrap#ng-bootstrap---angular-2-directives-specific-to-bootstrap-4

We've got also this: https://github.com/ng-bootstrap/ng-bootstrap#supported-browsers

Do you feel like more info is needed? If so, what kind and where you would like to see it?

**Comment by mgol** [comment]
Ah, sorry, somehow I missed that. IMO it'd be good to have that on the site as well, though.

BTW: In the context of not the Edge app but its browser engine the EdgeHTML engine version is used instead of the app version; most resources (including the Angular 2 docs) follow this rule (even though they usually write "Edge", they use the engine version). So it shouldn't say `Edge (20+)`, but `Edge (13+)` (the latest is v14).
