### ISSUE TITLE
Popover component needs isolated component to make binding working

### ISSUE THREAD

**Issue by pankajparkar** [ng-bootstrap/ng-bootstrap#1001]
I was trying to use `Popover` component inside my `abc` component directly, but I found that binding doesn't work in this case. The code shown on demo page seems to work because they had used `ng-bootstrap` components inside `isolated-component`.

Like on demo page for [**Popover**](https://ng-bootstrap.github.io/#/components/popover) usage they created `ngbd-popover-tplcontent` and used popover in it and it has been used inside `my-app` component [Plunkr here](http://plnkr.co/edit/jM5xUqyCPKNBpF1RKN2w?p=preview). 

My App

```
@Component({
  selector: 'my-app',
  template: `
    <div class="container-fluid">
    <hr>
    <p>
      This is a demo plnkr forked from the <strong>ng-bootstrap</strong> project: Angular 2 powered Bootstrap.
    </p>
    <hr>
    <p>
      Popovers can contain any arbitrary HTML, Angular bindings and even directives!
    </p>

    <template #popContent>
      Hello, <b>{{name}}</b>!
      <input type="text" (change)="test()">
    </template>
    <button type="button" class="btn btn-secondary" [ngbPopover]="popContent" popoverTitle="Fancy content">
      I've got markup and bindings in my popover!
    </button>
  </div>
  `
})
export class App {
  name = 'World';
  test(){
    console.log("Got Called");
  }
}
```

First of all I wanted to explain my requirement, I want to call some function from my component based on input change inside `Popover`. But somehow my function isn't getting called.

[**Problem Plunkr**](http://plnkr.co/edit/tf3sPUTMhX7F04IShhXy?p=preview)

In above plunkr I had reproduced the problem what I'm facing. Basically I'm expecting to get `test` function get called on input value change but unfortunately I got below error.

> VM1193 core.umd.js:3462EXCEPTION: Error in ./App class App - inline template:17:34 caused by: self.parent.parent.context.test is not a functionErrorHandler.handleError @ VM1193 core.umd.js:3462next @ VM1193 core.umd.js:6924schedulerFn @ VM1193 core.umd.js:6172SafeSubscriber.__tryOrUnsub @ VM1205 Subscriber.js:223SafeSubscriber.next @ VM1205 Subscriber.js:172Subscriber._next @ VM1205 Subscriber.js:125Subscriber.next @ VM1205 Subscriber.js:89Subject.next @ VM1201 Subject.js:55EventEmitter.emit @ VM1193 core.umd.js:6164onError @ VM1193 core.umd.js:6388onHandleError @ VM1193 core.umd.js:6263ZoneDelegate.handleError @ zone.js:236Zone.runGuarded @ zone.js:131NgZoneImpl.runInnerGuarded @ VM1193 core.umd.js:6271NgZone.runGuarded @ VM1193 core.umd.js:6504outsideHandler @ VM1192 platform-browser.umd.js:1990ZoneDelegate.invokeTask @ zone.js:265Zone.runTask @ zone.js:154ZoneTask.invoke @ zone.js:335
VM1193 core.umd.js:3464ORIGINAL EXCEPTION: self.parent.parent.context.test is not a functionErrorHandler.handleError @ VM1193 core.umd.js:3464next @ VM1193 core.umd.js:6924schedulerFn @ VM1193 core.umd.js:6172SafeSubscriber.__tryOrUnsub @ VM1205 Subscriber.js:223SafeSubscriber.next @ VM1205 Subscriber.js:172Subscriber._next @ VM1205 Subscriber.js:125Subscriber.next @ VM1205 Subscriber.js:89Subject.next @ VM1201 Subject.js:55EventEmitter.emit @ VM1193 core.umd.js:6164onError @ VM1193 core.umd.js:6388onHandleError @ VM1193 core.umd.js:6263ZoneDelegate.handleError @ zone.js:236Zone.runGuarded @ zone.js:131NgZoneImpl.runInnerGuarded @ VM1193 core.umd.js:6271NgZone.runGuarded @ VM1193 core.umd.js:6504outsideHandler @ VM1192 platform-browser.umd.js:1990ZoneDelegate.invokeTask @ zone.js:265Zone.runTask @ zone.js:154ZoneTask.invoke @ zone.js:335
VM1193 core.umd.js:3467ORIGINAL STACKTRACE:ErrorHandler.handleError @ VM1193 core.umd.js:3467next @ VM1193 core.umd.js:6924schedulerFn @ VM1193 core.umd.js:6172SafeSubscriber.__tryOrUnsub @ VM1205 Subscriber.js:223SafeSubscriber.next @ VM1205 Subscriber.js:172Subscriber._next @ VM1205 Subscriber.js:125Subscriber.next @ VM1205 Subscriber.js:89Subject.next @ VM1201 Subject.js:55EventEmitter.emit @ VM1193 core.umd.js:6164onError @ VM1193 core.umd.js:6388onHandleError @ VM1193 core.umd.js:6263ZoneDelegate.handleError @ zone.js:236Zone.runGuarded @ zone.js:131NgZoneImpl.runInnerGuarded @ VM1193 core.umd.js:6271NgZone.runGuarded @ VM1193 core.umd.js:6504outsideHandler @ VM1192 platform-browser.umd.js:1990ZoneDelegate.invokeTask @ zone.js:265Zone.runTask @ zone.js:154ZoneTask.invoke @ zone.js:335
VM1193 core.umd.js:3468TypeError: self.parent.parent.context.test is not a function
    at _View_App2._handle_change_0_0 (VM2440 App.ngfactory.js:261)
    at eval (VM1193 core.umd.js:9698)
    at eval (VM1192 platform-browser.umd.js:1877)
    at eval (VM1192 platform-browser.umd.js:1990)
    at ZoneDelegate.invoke (zone.js:232)
    at Object.onInvoke (VM1193 core.umd.js:6242)
    at ZoneDelegate.invoke (zone.js:231)
    at Zone.runGuarded (zone.js:128)
    at NgZoneImpl.runInnerGuarded (VM1193 core.umd.js:6271)
    at NgZone.runGuarded (VM1193 core.umd.js:6504)ErrorHandler.handleError @ VM1193 core.umd.js:3468next @ VM1193 core.umd.js:6924schedulerFn @ VM1193 core.umd.js:6172SafeSubscriber.__tryOrUnsub @ VM1205 Subscriber.js:223SafeSubscriber.next @ VM1205 Subscriber.js:172Subscriber._next @ VM1205 Subscriber.js:125Subscriber.next @ VM1205 Subscriber.js:89Subject.next @ VM1201 Subject.js:55EventEmitter.emit @ VM1193 core.umd.js:6164onError @ VM1193 core.umd.js:6388onHandleError @ VM1193 core.umd.js:6263ZoneDelegate.handleError @ zone.js:236Zone.runGuarded @ zone.js:131NgZoneImpl.runInnerGuarded @ VM1193 core.umd.js:6271NgZone.runGuarded @ VM1193 core.umd.js:6504outsideHandler @ VM1192 platform-browser.umd.js:1990ZoneDelegate.invokeTask @ zone.js:265Zone.runTask @ zone.js:154ZoneTask.invoke @ zone.js:335
VM1193 core.umd.js:3471ERROR CONTEXT:ErrorHandler.handleError @ VM1193 core.umd.js:3471next @ VM1193 core.umd.js:6924schedulerFn @ VM1193 core.umd.js:6172SafeSubscriber.__tryOrUnsub @ VM1205 Subscriber.js:223SafeSubscriber.next @ VM1205 Subscriber.js:172Subscriber._next @ VM1205 Subscriber.js:125Subscriber.next @ VM1205 Subscriber.js:89Subject.next @ VM1201 Subject.js:55EventEmitter.emit @ VM1193 core.umd.js:6164onError @ VM1193 core.umd.js:6388onHandleError @ VM1193 core.umd.js:6263ZoneDelegate.handleError @ zone.js:236Zone.runGuarded @ zone.js:131NgZoneImpl.runInnerGuarded @ VM1193 core.umd.js:6271NgZone.runGuarded @ VM1193 core.umd.js:6504outsideHandler @ VM1192 platform-browser.umd.js:1990ZoneDelegate.invokeTask @ zone.js:265Zone.runTask @ zone.js:154ZoneTask.invoke @ zone.js:335
VM1193 core.umd.js:3472DebugContext {_view: _View_App2, _nodeIndex: 0, _tplRow: 17, _tplCol: 34}ErrorHandler.handleError @ VM1193 core.umd.js:3472next @ VM1193 core.umd.js:6924schedulerFn @ VM1193 core.umd.js:6172SafeSubscriber.__tryOrUnsub @ VM1205 Subscriber.js:223SafeSubscriber.next @ VM1205 Subscriber.js:172Subscriber._next @ VM1205 Subscriber.js:125Subscriber.next @ VM1205 Subscriber.js:89Subject.next @ VM1201 Subject.js:55EventEmitter.emit @ VM1193 core.umd.js:6164onError @ VM1193 core.umd.js:6388onHandleError @ VM1193 core.umd.js:6263ZoneDelegate.handleError @ zone.js:236Zone.runGuarded @ zone.js:131NgZoneImpl.runInnerGuarded @ VM1193 core.umd.js:6271NgZone.runGuarded @ VM1193 core.umd.js:6504outsideHandler @ VM1192 platform-browser.umd.js:1990ZoneDelegate.invokeTask @ zone.js:265Zone.runTask @ zone.js:154ZoneTask.invoke @ zone.js:335
zone.js:158Uncaught ViewWrappedError {_nativeError: Error: Error in ./App class App - inline template:17:34 caused by: self.parent.parent.context.test i…, originalError: TypeError: self.parent.parent.context.test is not a function
    at _View_App2._handle_change_0_0 (A…, context: DebugContext, longStack: "TypeError: self.parent.parent.context.test is not …/@angular/core@2.0.0/bundles/core.umd.js:6504:77)"}

Angular: 2.1.0
ng-bootstrap: 1.0.11
Bootstrap: v4.alpha5

**Comment by pkozlowski-opensource** [comment]
It is very strange but it seems like your plunker got corrupted for some reason (try changing something in it and you will see that page is not updated). I've moved your code to a new plunker and everything seems to work as expected: http://plnkr.co/edit/WDuyia4uqrpIQvGz21Ue?p=preview

Could you please confirm? I might as well miss some crucial detail here....

**Comment by pankajparkar** [comment]
Wiil check and confirm once I'm in front of machine.

**Comment by pankajparkar** [comment]
@pkozlowski-opensource OMG! Its working now. May be I'm missing something this time to reproduce it(I did this thing in plnkr & in my project as well). Let it be here is updated [working plunkr](http://plnkr.co/edit/hseII5yANASiHLTvxod7?p=preview). 

Small question: May I know why change event on `input` is getting fired when I do click outside of input box(on `blur`)?

**Comment by pkozlowski-opensource** [comment]
> OMG! Its working now.

Happy to hear this. Guess we can close this one for now (feel free to open a new issue if you bump into this thing again and can reproduce).

> Small question: May I know why change event on input is getting fired when I do click outside of input box(on blur)?

Sorry, not sure what you mean....

**Comment by pankajparkar** [comment]
@pkozlowski-opensource Thanks :)

If you open a plnkr which I had added in last comment, there I have popover with below template

    <template #popContent>
      Hello, <b>{{name}}</b>!
      <input type="text" (change)="test()">
    </template>

As you can see when you type something inside a field, it should call `test` method of `Component`, but it isn't getting called on input `change`. When I blur out field that time only `test` event is getting called. Even I tried changing `(change)` event to `(keyup)` but that haven't gotten any change in behaviour. Could you please tell me why it isn't working correctly?

**Comment by pkozlowski-opensource** [comment]
> As you can see when you type something inside a field

This is not how the `change` event works - it gets executed only when you change input's value _and_ blur it. If you want to invoke something on each value change you could use `input` event: http://plnkr.co/edit/p67dVY6BgIti3rVbod6i?p=preview

In any case this is not specific to this library.

**Comment by pankajparkar** [comment]
Apologies for silly doubt, I was comparing it with A1 `ng-change` event, Thanks for your help 👍

**Comment by jaythakur** [comment]
Hi All,

I want to create a unique component for all my popover. I want to pass dynamic data only. How can I open the popover?

**Comment by pankajparkar** [comment]
You can refer to [ngbPopover](https://ng-bootstrap.github.io/#/components/popover/examples#tplcontent) option to pass on html content to be displayed on popover. Thereafter consider creating your own component  by referring [this stackbltiz](https://stackblitz.com/angular/brroqxkppyxk)

**Comment by jaythakur** [comment]
Thanks for your reply.

But I want to show Components as content for ngbpopover as same as ngbmodal. I have done for NgbModal but facing problem for NgbPopover.

please reply if anyone has an answer.

Example - https://ng-bootstrap.github.io/#/components/modal/examples

Thanks in advance

**Comment by pankajparkar** [comment]
This can be easily achievable by using creating custom component with Content Projection (`ng-contet` or `ng-slot` directive). 
If you need more information, you can consider open question on stackoverflow regarding the same. Share that question link here, if possible.
