### ISSUE TITLE
I can Open Modal whit Component By Code?

### ISSUE THREAD

**Issue by franko21c** [ng-bootstrap/ng-bootstrap#1004]
"@ng-bootstrap/ng-bootstrap": "1.0.0-alpha.11",
  "@angular":"2.1.0"

Modal Custom Component 

import {Component, Input} from '@angular/core';

import {NgbModal, NgbActiveModal} from '@ng-bootstrap/ng-bootstrap';

@Component({
    selector: 'ngbd-modal-content',
    template: 'template/modalMessage.html'
})
export class ModalMessage {
    @Input() type   : string; // success| info|warning|danger|primary
    @Input() button : string;// onlyClose | YesNo | Submit //TODO
    @Input() title  :string;
    @Input() message: string;

    constructor(public activeModal: NgbActiveModal) { }
}
_________________________________________________________
import {Component, ViewChild, Output, EventEmitter} from '@angular/core';
import {NgbModal, ModalDismissReasons, NgbModalRef} from '@ng-bootstrap/ng-bootstrap';
import {ModalMessage} from 'App/Core/ModalMessage/component/modalMessage.component'

@Component({
    templateUrl: 'App/template/codeAnalysis.html'
   
})
export class CustomComponent{
constructor(modalService: NgbModal) {

}

  openModalInfo(type, title, message) {
        const modalRef = this.modalService.open(ModalMessage);
        modalRef.componentInstance.type = type;
        modalRef.componentInstance.button = 'close';
        modalRef.componentInstance.title = title;
        modalRef.componentInstance.message = message;
    }

EventClick(type, title, message){
  this.openModalInfo(type, title, message);
}

**Comment by jnizet** [comment]
Please follow the issue template. 

This question should most probably be posted on StackOverflow. But even then, if you don't specify 

 - what you're trying to achieve, 
 - what you expect to happen, 
 - what happens instead, 

and if you don't post a plunkr reproducing the problem as explicitly requested in the issue template, your issue/question is not actionable, and will thus be closed.
