### ISSUE TITLE
Autoclose in dropdown does not work when dropdown is inside a modal

### ISSUE THREAD

**Issue by ASHFAQPATWARI** [ng-bootstrap/ng-bootstrap#1011]
### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.1.0

ng-bootstrap: 1.0.0-alpha.11

Bootstrap: 4.0.0-alpha.5

**Comment by pkozlowski-opensource** [comment]
Thnx for reporting. This is indeed a bug in our modal implementation and I've just sent a PR to fix it (see #1013). This fix will be part of the next (alpha.12) release.

**Comment by kjartanvalur** [comment]
@pkozlowski-opensource 
Thanks!

**Comment by Watertight-skaat** [comment]
For anyone who might be looking, I experienced this issue again in the react-bootrap library
