### ISSUE TITLE
Dropdown append to body

### ISSUE THREAD

**Issue by marcalj** [ng-bootstrap/ng-bootstrap#1012]
### Bug description:
Support for dropdown append-to-body.

### Use case
In a list inside an overflowed element, the dropdown is shown "inside" the main element, and you cannot seen it completely.

![image](https://cloud.githubusercontent.com/assets/63667/20058281/76cc7286-a4f0-11e6-86b4-b93e7fce5636.png)

Working with ng1 version:
![image](https://cloud.githubusercontent.com/assets/63667/20058295/88e6347a-a4f0-11e6-88a3-eba735254b91.png)

Thanks!

**Comment by marcalj** [comment]
Coming from this issue: https://github.com/ng-bootstrap/ng-bootstrap/issues/584#issuecomment-258015148

@scttcper

**Comment by PEsteves8** [comment]
I also need something like this. Any progress on it?

**Comment by bharding777** [comment]
would really love this feature - constantly getting caught with dropdowns under other elements....

**Comment by phillip-haydon** [comment]
Really needing this feature :(

**Comment by codeMonkeysBe** [comment]
I need this feature as well. Can I help with the implementation of this?

**Comment by clarkj** [comment]
My most common use case for dropdown-append-to-body is for building dropdown links in navbars.  Does anyone know a workaround for that?

**Comment by ryanohearn** [comment]
I really need this feature. Any word on when this will be addressed?

**Comment by Alukar** [comment]
+1

**Comment by nponna** [comment]
+1

**Comment by OzoTek** [comment]
Does anyone have a workaround for that?

**Comment by kotmatpockuh** [comment]
+1

**Comment by RonNewcomb** [comment]
+1

**Comment by alesce** [comment]
+1

**Comment by iwebd** [comment]
+1

**Comment by nathan059** [comment]
+1

**Comment by joedjc** [comment]
+1

**Comment by OClyde** [comment]
+1

**Comment by maarten-vandevelde** [comment]
+1

**Comment by Asharma86** [comment]
This is a very important feature for this component. Stacking context is big concern and a problem very hard to solve when working with complex data-grids and such. I loved it how I was able to use the your popover with such ease. If you could use the same utility here it will be awesome!

@pkozlowski-opensource +1

**Comment by florentsuc** [comment]
+1

**Comment by mbstuart** [comment]
@pkozlowski-opensource, I have been working on adding this feature for use at my work. Would you be interested in a PR for my solution to this?

**Comment by bluecaret** [comment]
+1

**Comment by JoelRodrigues** [comment]
+1

**Comment by amitmiran** [comment]
+1

**Comment by amitmiran** [comment]
+1

**Comment by TheNuttyMaker** [comment]
+1

**Comment by edgargonzalez525** [comment]
+1

**Comment by rkolec** [comment]
+1

**Comment by natcohen** [comment]
There was already a similar bug in bootstrap alpha, maybe it can help: https://github.com/twbs/bootstrap/issues/23429

@pkozlowski-opensource Is there any fix planned?

**Comment by FrciSmrci** [comment]
+1

**Comment by FrciSmrci** [comment]
+1

**Comment by TENDesign** [comment]
has anyone even come up with a home-grown solution for this issue?

**Comment by mcorcuera** [comment]
We have come up with a custom directive to reposition the ngbDropdown menu under the body element instead.

Here is the directive code:

```typescript
import { Directive, ContentChild, AfterContentInit, ElementRef, OnDestroy,
  Inject, forwardRef } from '@angular/core';
import { NgbDropdownMenu, NgbDropdown } from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown';
import { positionElements } from '@ng-bootstrap/ng-bootstrap/util/positioning';
import { Subscription } from 'rxjs/Subscription';

@Directive({
  selector: '[ngbDropdown][ngbDropdownReposition]',
})
export class DropdownPositionDirective implements AfterContentInit, OnDestroy {

  @ContentChild(NgbDropdownMenu) private menu: NgbDropdownMenu;
  @ContentChild(NgbDropdownMenu, {read: ElementRef}) private menuRef: ElementRef;


  private oldParent: HTMLElement | null;
  private menuWrapper: HTMLElement;
  private onChangeSubscription: Subscription;

  constructor(
    @Inject(forwardRef(() => NgbDropdown)) private dropdown: NgbDropdown,
    private elementRef: ElementRef,
  ) {
    this.onChangeSubscription = this.dropdown.openChange.subscribe((open: boolean) => {
      if (!open) {
        setTimeout(() => this.removeMenuFromBody(), 0);
      } else {
        if (!this.isInBody()) {
          this.appendMenuToBody();
        }
      }
    });
  }

  ngAfterContentInit() {
    this.oldParent = (<HTMLElement> this.menuRef.nativeElement).parentElement;
    this.createWrapper();
    this.menu.position = (triggerEl: HTMLElement, placement: string) => {
      this.setWrapperWidth();
      this.menu.applyPlacement(
        positionElements(triggerEl, this.menuWrapper, placement, true));
    };
  }

  ngOnDestroy() {
    this.removeMenuFromBody();
    if (this.onChangeSubscription) {
      this.onChangeSubscription.unsubscribe();
    }
  }

  private isInBody() {
    return this.menuWrapper.parentNode === document.body;
  }

  private removeMenuFromBody() {
    if (this.isInBody()) {
      if (this.oldParent) {
        this.oldParent.appendChild(this.menuWrapper);
      }
    }
  }

  private appendMenuToBody() {
    window.document.body.appendChild(this.menuWrapper);
  }

  private createWrapper() {
    this.menuWrapper = document.createElement('div');
    this.menuWrapper.style.position = 'absolute';
    this.menuWrapper.style.zIndex = '1000';

    this.menuWrapper.addEventListener('keyup', (event: KeyboardEvent) => {
      if (event.keyCode === 27) {
        this.dropdown.closeFromOutsideEsc();
      }
    });
    this.menuWrapper.appendChild(this.menuRef.nativeElement);
  }

  private setWrapperWidth() {
    const parentEl = <HTMLElement> this.elementRef.nativeElement;
    this.menuWrapper.style.width = parentEl.clientWidth + 'px';
  }
}
```

And use it like this:

```html
<div ngbDropdown ngbDropdownReposition>
 <!-- Rest of the dropdown code -->
</div>
```

Hope it helps :)

**Comment by pojntfx** [comment]
@mcorcuera Thanks so much for this, works perfectly, used it to fix a bootstrap dropdown when using two sticky navbars, I only had to change the z-index to something =>1020 and voilà!

**Comment by shyamal890** [comment]
@pkozlowski-opensource Can you please update us on the status of this feature? Is there something blocking this feature from being implemented?

**Comment by shyamal890** [comment]
@mcorcuera the solution isn't working in some scenarios where `placement position` is changed from default.

**Comment by shyamal890** [comment]
@Foxandxss Can you please have a look at this issue. Is the second most requested feature in this plugin.

**Comment by Foxandxss** [comment]
I am not actively working in the project right now. Isn't there a PR? If not, people could create one

**Comment by Asharma86** [comment]
@mcorcuera - Really appreciate your help on this! Cheers!

**Comment by jingzhang** [comment]
Brilliant @mcorcuera !!

I tweaked it a little to work with auto placement. Here's the modified version:

`
import {
  Directive, ContentChild, AfterContentInit, ElementRef, OnDestroy,
  Inject, forwardRef
} from '@angular/core';
import { NgbDropdownMenu, NgbDropdown } from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown';
import { positionElements } from '@ng-bootstrap/ng-bootstrap/util/positioning';
import { Subscription } from 'rxjs/Subscription';

@Directive({
  selector: '[ngbDropdown][ngbDropdownReposition]',
})
export class DropdownPositionDirective implements AfterContentInit, OnDestroy {

  @ContentChild(NgbDropdownMenu) private menu: NgbDropdownMenu;
  @ContentChild(NgbDropdownMenu, {read: ElementRef}) private menuRef: ElementRef;


  private oldParent: HTMLElement | null;
  private menuWrapper: HTMLElement;
  private readonly onChangeSubscription: Subscription;

  constructor(
    @Inject(forwardRef(() => NgbDropdown)) private dropdown: NgbDropdown,
    private elementRef: ElementRef,
  ) {
    this.onChangeSubscription = this.dropdown.openChange.subscribe((open: boolean) => {
      if (!open) {
        setTimeout(() => this.removeMenuFromBody(), 0);
      }
    });
  }

  ngAfterContentInit() {
    this.oldParent = (<HTMLElement> this.menuRef.nativeElement).parentElement;
    this.createWrapper();
    this.menu.position = (triggerEl: HTMLElement, placement: string) => {
      this.setWrapperWidth();

      if (!this.isInBody()) {
        this.appendMenuToBody();
      }

      positionElements(triggerEl, this.menuWrapper, placement, true);
      this.menu.applyPlacement(positionElements(triggerEl, this.menuRef.nativeElement, placement));
    };
  }

  ngOnDestroy() {
    this.removeMenuFromBody();
    if (this.onChangeSubscription) {
      this.onChangeSubscription.unsubscribe();
    }
  }

  private isInBody() {
    return this.menuWrapper.parentNode === document.body;
  }

  private removeMenuFromBody() {
    if (this.isInBody()) {
      if (this.oldParent) {
        this.oldParent.appendChild(this.menuWrapper);
      }
    }
  }

  private appendMenuToBody() {
    window.document.body.appendChild(this.menuWrapper);
  }

  private createWrapper() {
    this.menuWrapper = document.createElement('div');
    this.menuWrapper.style.position = 'absolute';
    this.menuWrapper.style.zIndex = '1030';

    this.menuWrapper.addEventListener('keyup', (event: KeyboardEvent) => {
      if (event.keyCode === 27) {
        this.dropdown.closeFromOutsideEsc();
      }
    });
    this.menuWrapper.appendChild(this.menuRef.nativeElement);
  }

  private setWrapperWidth() {
    const parentEl = <HTMLElement> this.elementRef.nativeElement;
    this.menuWrapper.style.width = parentEl.clientWidth + 'px';
  }
}

`

**Comment by adamk33n3r** [comment]
@jingzhang I can't get that code to work. The content child of `NgbDropdownMenu` is `undefined`. I suspect this is because `dropdown/dropdown.js` isn't typescript so there is no typing information for Angular to use. But I'm curious why it seems to work for you and others

**Comment by matiishyn** [comment]
any progress on this?

**Comment by jingzhang** [comment]
@adamk33n3r Sorry for the late reply. I was away on vacation. For me the import works just fine. I don't remember doing anything special.

Does you installation contain this file? 
/node_modules/@ng-bootstrap/ng-bootstrap/dropdown/dropdown.d.ts

If not, have you tried reinstalling ng-bootstrap?

**Comment by adamk33n3r** [comment]
@jingzhang Yes I have that file. It "imports" correctly. It's just that it's not compiling it to es5. It gets put into my bundle as es6 with imports and in Chrome it errors.

**Comment by jingzhang** [comment]
@adamk33n3r without seeing the actual code it's hard to guess the issue. But I think my project is also complied into es6 (not sure if the correct way to call it. I'm not really an expert in typescript). 

BTW, my project was created with angular CLI, if yours wasn't, maybe it has something to do with the error.

Sorry I couldn't be of much help.

**Comment by lostip** [comment]
@adamk33n3r RE: 
> "The content child of NgbDropdownMenu is undefined"

check if you have properly added `NgbDropdownModule` to your module `imports`

**Comment by certainlyakey** [comment]
I am having trouble with the @jingzhang solution on ng-bootstrap 3.0.0. I've copied the code as a new directive, imported this directive in the `app.module.ts` and put it there in the `declarations` section. l also have tried to fix some path issues arising on build in terminal. However the browser (Chrome) displays a `No provider for NgbDropdown` error.  What could be the problem?

```
import {
  Directive, ContentChild, AfterContentInit, ElementRef, OnDestroy,
  Inject, forwardRef
} from '@angular/core';
import { NgbDropdownMenu, NgbDropdown } from '@ng-bootstrap/ng-bootstrap/esm5/dropdown/dropdown';
import { positionElements } from '@ng-bootstrap/ng-bootstrap/esm5/util/positioning';
import { Subscription } from 'rxjs/Subscription';

@Directive({
  selector: '[ngbDropdown][ngbDropdownReposition]',
})
export class HcNgbDropdownRepositionDirective implements AfterContentInit, OnDestroy {

  @ContentChild(NgbDropdownMenu) private menu: NgbDropdownMenu;
  @ContentChild(NgbDropdownMenu, {read: ElementRef}) private menuRef: ElementRef;


  private oldParent: HTMLElement | null;
  private menuWrapper: HTMLElement;
  private readonly onChangeSubscription: Subscription;

  constructor(
    @Inject(forwardRef(() => NgbDropdown)) private dropdown: NgbDropdown,
    private elementRef: ElementRef
  ) {
    this.onChangeSubscription = this.dropdown.openChange.subscribe((open: boolean) => {
      if (!open) {
        setTimeout(() => this.removeMenuFromBody(), 0);
      }
    });
  }

  ngAfterContentInit() {
    this.oldParent = (<HTMLElement> this.menuRef.nativeElement).parentElement;
    this.createWrapper();
    this.menu.position = (triggerEl: HTMLElement, placement: string) => {
      this.setWrapperWidth();

      if (!this.isInBody()) {
        this.appendMenuToBody();
      }

      positionElements(triggerEl, this.menuWrapper, placement, true);
      this.menu.applyPlacement(positionElements(triggerEl, this.menuRef.nativeElement, placement));
    };
  }

  ngOnDestroy() {
    this.removeMenuFromBody();
    if (this.onChangeSubscription) {
      this.onChangeSubscription.unsubscribe();
    }
  }

  private isInBody() {
    return this.menuWrapper.parentNode === document.body;
  }

  private removeMenuFromBody() {
    if (this.isInBody()) {
      if (this.oldParent) {
        this.oldParent.appendChild(this.menuWrapper);
      }
    }
  }

  private appendMenuToBody() {
    window.document.body.appendChild(this.menuWrapper);
  }

  private createWrapper() {
    this.menuWrapper = document.createElement('div');
    this.menuWrapper.style.position = 'absolute';
    this.menuWrapper.style.zIndex = '1030';

    this.menuWrapper.addEventListener('keyup', (event: KeyboardEvent) => {
      if (event.keyCode === 27) {
        this.dropdown.closeFromOutsideEsc();
      }
    });
    this.menuWrapper.appendChild(this.menuRef.nativeElement);
  }

  private setWrapperWidth() {
    const parentEl = <HTMLElement> this.elementRef.nativeElement;
    this.menuWrapper.style.width = parentEl.clientWidth + 'px';
  }
}

```

**Comment by jingzhang** [comment]
@certainlyakey are you sure you upgraded to 3.0.0? Because *dropdown.closeFromOutsideEsc()* method no longer exists in this version (you can just remove the event listener on menuWrapper)

**Comment by certainlyakey** [comment]
Yes, `npm list @ng-bootstrap/ng-bootstrap` confirms that the version installed is 3.0.0. I have removed the listener just in case, it didn't help much.

**Comment by jingzhang** [comment]
OK, that's strange. I asked because with closeFromOutsideEsc in the code it shouldn't even compile. Anyway, I suspect it's due to the way you worked around the path issues. I see this at the top of your code:

```ts
import { NgbDropdownMenu, NgbDropdown } from '@ng-bootstrap/ng-bootstrap/esm5/dropdown/dropdown';
import { positionElements } from '@ng-bootstrap/ng-bootstrap/esm5/util/positioning';
```

I had similar import issues after upgrading to 3.0.0. What I did was:

```ts
import { NgbDropdown, ɵl as NgbDropdownMenu } from '@ng-bootstrap/ng-bootstrap';
import { positionElements } from '../ngb/positioning';
```

Notice that you need to make a local copy of the positioning service, because it's no longer exported in 3.0.0. You can grab it from here: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/util/positioning.ts I saved it at /src/app/ngb/positioning.ts, hence the path above

**Comment by certainlyakey** [comment]
Thanks @jingzhang! It works now. Apparently there were some problems with import paths indeed which strangely weren't reported by Typescript on build. 

I've made an only change of modifying a single line in `positionElements` method in the positioning service that comes from ng-bootstrap (see [the changed ](https://gist.github.com/certainlyakey/d939b4332370d712a653488bf26326b2#file-positioning-ts-L108)). There was a problem with dropdowns incorrectly offset by the height of the host element. The `top` position for the target element inside its wrapper should not be the same as for the wrapper itself (since the target is positioned relative to the wrapper, and the wrapper is positioned relative to body).

Thanks again for the help!

**Comment by jingzhang** [comment]
NP @certainlyakey And thanks for sharing the fix 👍  I didn't notice that

**Comment by Nness** [comment]
In release 3.1, `NgbDropdownMenu` is export as ep.

```
// ng-bootstrap.d.ts
export { NgbDropdownAnchor as ɵq, NgbDropdownMenu as ɵp, NgbDropdownToggle as ɵr } from './dropdown/dropdown';
```

Code should change to
import { NgbDropdown, ɵp as NgbDropdownMenu } from '@ng-bootstrap/ng-bootstrap';

**Comment by bluecaret** [comment]
This workaround breaks tab navigation and accessibility. We still very much need an official solution. Can't believe this is still not a thing.

**Comment by EvaSky** [comment]
We use bootstrap 3.2 and use custom directive. Maybe it'll help someone.

```
import { Directive, forwardRef, Inject, OnDestroy } from '@angular/core';
import { NgbDropdown } from '@ng-bootstrap/ng-bootstrap';
import { Subscription } from 'rxjs';
import { positionElements } from '../positioning';

@Directive({
    selector: '[ngbDropdown][appDropdownAppendToBody]'
})
export class DropdownAppendToBodyDirective implements OnDestroy {

    private onChangeSubscription: Subscription;

    constructor(@Inject(forwardRef(() => NgbDropdown)) private dropdown: NgbDropdown) {

        this.onChangeSubscription = this.dropdown.openChange.subscribe((open: boolean) => {
            this.dropdown['_menu'].position = (triggerEl: HTMLElement, placement: string) => {
                if (!this.isInBody()) {
                    this.appendMenuToBody();
                }
                positionElements(triggerEl, this.dropdown['_menu']['_elementRef'].nativeElement, placement, true);
            };

            if (open) {
                if (!this.isInBody()) {
                    this.appendMenuToBody();
                }
            } else {
                setTimeout(() => this.removeMenuFromBody());
            }
        });
    }

    ngOnDestroy() {
        this.removeMenuFromBody();
        if (this.onChangeSubscription) {
            this.onChangeSubscription.unsubscribe();
        }
    }

    private isInBody() {
        return this.dropdown['_menu']['_elementRef'].nativeElement.parentNode === document.body;
    }

    private removeMenuFromBody() {
        if (this.isInBody()) {
            window.document.body.removeChild(this.dropdown['_menu']['_elementRef'].nativeElement);
        }
    }

    private appendMenuToBody() {
        window.document.body.appendChild(this.dropdown['_menu']['_elementRef'].nativeElement);
    }
}
```

```
<div ngbDropdown appDropdownAppendToBody  [placement]="['bottom-right', 'top-right']">
    <button ngbDropdownToggle></button>
    <div ngbDropdownMenu>
        ..
    </div>
</div>
```

We had to move positioning.ts to out app because it wasn't compiled.

**Comment by theCrius** [comment]
Using bootstrap 4 and related ngBootstrap, still no support for this. Maybe make this an higher priority after 2 years of this issue being open?

**Comment by jer0Me** [comment]
> We use bootstrap 3.2 and use custom directive. Maybe it'll help someone.
> 
> ```
> import { Directive, forwardRef, Inject, OnDestroy } from '@angular/core';
> import { NgbDropdown } from '@ng-bootstrap/ng-bootstrap';
> import { Subscription } from 'rxjs';
> import { positionElements } from '../positioning';
> 
> @Directive({
>     selector: '[ngbDropdown][appDropdownAppendToBody]'
> })
> export class DropdownAppendToBodyDirective implements OnDestroy {
> 
>     private onChangeSubscription: Subscription;
> 
>     constructor(@Inject(forwardRef(() => NgbDropdown)) private dropdown: NgbDropdown) {
> 
>         this.onChangeSubscription = this.dropdown.openChange.subscribe((open: boolean) => {
>             this.dropdown['_menu'].position = (triggerEl: HTMLElement, placement: string) => {
>                 if (!this.isInBody()) {
>                     this.appendMenuToBody();
>                 }
>                 positionElements(triggerEl, this.dropdown['_menu']['_elementRef'].nativeElement, placement, true);
>             };
> 
>             if (open) {
>                 if (!this.isInBody()) {
>                     this.appendMenuToBody();
>                 }
>             } else {
>                 setTimeout(() => this.removeMenuFromBody());
>             }
>         });
>     }
> 
>     ngOnDestroy() {
>         this.removeMenuFromBody();
>         if (this.onChangeSubscription) {
>             this.onChangeSubscription.unsubscribe();
>         }
>     }
> 
>     private isInBody() {
>         return this.dropdown['_menu']['_elementRef'].nativeElement.parentNode === document.body;
>     }
> 
>     private removeMenuFromBody() {
>         if (this.isInBody()) {
>             window.document.body.removeChild(this.dropdown['_menu']['_elementRef'].nativeElement);
>         }
>     }
> 
>     private appendMenuToBody() {
>         window.document.body.appendChild(this.dropdown['_menu']['_elementRef'].nativeElement);
>     }
> }
> ```
> ```
> <div ngbDropdown appDropdownAppendToBody  [placement]="['bottom-right', 'top-right']">
>     <button ngbDropdownToggle></button>
>     <div ngbDropdownMenu>
>         ..
>     </div>
> </div>
> ```
> We had to move positioning.ts to out app because it wasn't compiled.

I just copied your the code and everything works fine. Good job

**Comment by lasantha57** [comment]
I guess same exists for the ngb-datepicker as well
![untitled](https://user-images.githubusercontent.com/6893358/47545262-decc2580-d91d-11e8-9848-b4b306634121.jpeg)

**Comment by umdstu** [comment]
Most angular 2+ components I've seen/used have an `appendToBody=true/false` option that appends the dropdown to the body and fixes all of this. The old ui-bootstrap has this. Why isn't this an option?

**Comment by Maximaximum** [comment]
Quite a pity that this issue hasn't yet received an official fix :(

**Comment by fbasso** [comment]
Regarding the ngb-datepicker, the attribute container="body" can be used on the input. 
See https://ng-bootstrap.github.io/#/components/datepicker/api

**Comment by skorunka** [comment]
Facing some issue when parent div overflow is set to `auto`(or similar).

**Comment by lexeek** [comment]
Any progress with this issue?

**Comment by Apee** [comment]
Any progress... ?

**Comment by arajay** [comment]
@EvaSky workaround is working for me. if you don't update from version 2 the positioning util is not private and you can import it. otherwise you have to make a copy in your app (which sucks)

**Comment by Maximaximum** [comment]
Very pity that this issue does not seem to be of any priority to the team :(

**Comment by mikhailbartashevich** [comment]
Agree it's very pitty, please add this input
