### ISSUE TITLE
Cannot programmatically select tab.

### ISSUE THREAD

**Issue by Mathou54** [ng-bootstrap/ng-bootstrap#1016]
I try to select a tab with typescript. It throw an error saying that filter is called on undefined.

http://plnkr.co/edit/nRXU6d3KTM91W1tzaDkj?p=preview

The only fix I found is to add setTimout a the select('bar') call.

**Comment by pkozlowski-opensource** [comment]
The problem is that you are calling the `select` method _wayyyy_ too early (that is, before tabs are built). We should improve the error message but we can't make it "work" the way you expect (tabs are fully initialized only in the `ngAfterViewInit` hook but at this point you can't mutate model as it would break uni-directional data flow).

The god news, though, that you can use the `activeId` property of the tabset itself to sepcify a tab to be initially selected: http://plnkr.co/edit/nRXU6d3KTM91W1tzaDkj?p=preview - would this be sufficient for your use-case?

**Comment by Mathou54** [comment]
Indeed with the ngAfterViewInit it works. No I need to do it via typescript in order to catch an url parameter and display the right tab.

Here is the working plnkr: http://plnkr.co/edit/nRXU6d3KTM91W1tzaDkj?p=preview, if needed for documentation.

**Comment by justforuse** [comment]
It not work when I use ngFor in ng-tab
Here is the code(I use Pug to generate HTML):
```
ngb-tabset(#t="ngbTabset")
    ngb-tab(*ngFor="let item of data" id="{{item.value}}")
        template(ngbTabTitle)
            a([routerLink]='["../", item.value]' routerLinkActive='active' innerHTML="{{item.name}}") 
        template(ngbTabContent) {{item.value}}
```

and the component.ts:
```
export class AppComponent implements AfterViewInit{
    @ViewChild('t') ngbTabSet;    
    ngAfterViewInit() {
        console.log('view init..');
        this.route.params
            .subscribe((params: Params) => {
                console.log(params);
                //it's length was 0 at first
                this.ngbTabSet.select(params['system']);
            })
    }
}
```

The length of ngTabSet is 0 at first. So you cannot select the specific tab.

Is there any way to solve this problem? Thanks a lot.

**Comment by pkozlowski-opensource** [comment]
@justforuse please ask support questions on StackOverflow, here is why: https://github.com/ng-bootstrap/ng-bootstrap#getting-help

We are monitoring the [ng-bootstrap tag](http://stackoverflow.com/questions/tagged/ng-bootstrap) and happy to help. Just make sure that you've got a minimal reproduce scenario in a plunker or similar - very hard to help without a live reproduce scenario.

**Comment by justforuse** [comment]
@pkozlowski-opensource  I found my problem, Because the tabs data is an observable data, so I add *ngIf to its parent element to make sure the data is reached, thanks to your advice

**Comment by gauribane** [comment]
in component.ts
activeIdString:any="1"
ngOnInit(){
if(window.history.state.hasOwnProperty('tabId'))
//it sets tabid=3
      this.activeIdString=window.history.state.tabId;
}
In Html
<ngb-tabset  #tabset="ngbTabset"   [activeId]="activeIdString">
</ngb-tabset>

**Comment by gauribane** [comment]
Working fine
https://stackblitz.com/edit/angular-ettpha?embed=1&file=app/tabset-basic.ts
