### ISSUE TITLE
Dropdown - autoclose on outside click option

### ISSUE THREAD

**Issue by MrCroft** [ng-bootstrap/ng-bootstrap#1022]
### Feature request

It would be a useful addition to have another autoClose option: `onOutsideClick` (or another meaningful name), so we can keep the dropdown open as long as we click somewhere inside it.

**Comment by forrestab** [comment]
Since this project uses Typescript and Typescript supports enums, you all may want to consider changing `autoClose` to accept an `enum` instead of a `boolean`.

**Comment by pkozlowski-opensource** [comment]
> so we can keep the dropdown open as long as we click somewhere inside it.

This can be easily achieved by stopping propagation of click events triggered on menu item elements.

**Comment by pkozlowski-opensource** [comment]
> This can be easily achieved by stopping propagation of click events triggered on menu item elements.

Scratch this - it won't work properly with multiple dropdowns...

**Comment by pkozlowski-opensource** [comment]
> Since this project uses Typescript and Typescript supports enums, you all may want to consider changing autoClose to accept an enum instead of a boolean.

@forrestab enums are not ideal since you would have to expose an enum on a component's instance. In practice to achieve the following:

```
<div ngbDropdown [autoClose]="CloseEnum.INSIDE">
...
</div>
```

You would have to have `CloseEnum` on the component's instance which is too much pain in practice, IMO. How about the following API:

```
@Input() autoClose: boolean | 'inside' | 'outside';
```

**Comment by mattscu** [comment]
The document click listener currently runs in the zone

```typescript
'(document:click)': 'closeFromOutsideClick($event)'
```
This means each click will trigger an angular change detection.
If you have one dropdown thats not a problem. If you have dropdowns in a large table it will become a performance problem. You should replace this with ngZone.runOutsideAngular() and do the change detection manually only if required

**Comment by pkozlowski-opensource** [comment]
@matthiasscudlik you are right, we are planning to change it. The issue is already tracked via #900
