### ISSUE TITLE
Feature request: Popover - add css class

### ISSUE THREAD

**Issue by rolandoldengarm** [ng-bootstrap/ng-bootstrap#1024]
The popover has by default the class "popover in popover-{{direction}}"
This is not configurable, I would like to be able to add a class.

**Comment by pkozlowski-opensource** [comment]
> I would like to be able to add a class

Would you mind sharing a real-life use-case? We are very conservative about extending APIs so I would like to see if your need can't be covered by other, more flexible means (for example you can target the `<ngb-popover-window>` element if you would like to style [popover windows](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/popover/popover.ts)).

**Comment by rolandoldengarm** [comment]
the popover class by default is max 276 pixels. I need wider wider popovers in certain scenarios. So right now the only option is to override the .popover class, but that applies to any popover.
I would like to add a class to be able to set width on one popover only.

**Comment by pkozlowski-opensource** [comment]
Isn't it sth you can do in pure CSS? http://plnkr.co/edit/qJy83oAoRhC8GI8adqOl?p=preview 
In the above plunker I can change width for the entire component but could obviously narrow down the selector to target a particular popover. Wouldn't this be sufficient for you?

**Comment by rolandoldengarm** [comment]
@pkozlowski-opensource That looks what I want! I need to look into shadow DOM. In SCSS, :host >>> .popover is not supported, only :host > .popover . 
I can't find any documentation about >>> . How would that work in SCSS?

**Comment by alex321** [comment]
@rolandoldengarm  You can also use /deep/ which is the equivalent of `>>>`. I am not sure whether the `>>>` is fully supported as I had the same issue.

**Comment by pkozlowski-opensource** [comment]
We should be good here without changes to the library.

**Comment by Sibiraj-S** [comment]
@pkozlowski-opensource what if there are multiple popovers in a page and wanted to apply styles to one of the popovers.  Using general CSS will affect all popovers. So having an option to add the class will be a good option.

The solution given above stands valid If we wanted to use the same styling across all popovers.

**Comment by JavanXD** [comment]
I also support this feature request to add a css class one of my popovers:
![grafik](https://user-images.githubusercontent.com/4342160/32335255-b761a24a-bfec-11e7-81fc-87692bff81c0.png)
```css
.popover.error-pop {
	border-color: #dc3545;
	box-shadow: 0 0 0 0.2rem rgba(220, 53, 69, 0.25);
}
```

At the moment i was able to inject my `error-pop` class with the placement, but this is just a bad hack
```html
<button type="button" class="btn btn-sm btn-outline-success fa fa-check"
				placement="bottom error-pop" [ngbPopover]="popError" #p="ngbPopover" (clickOutside)="p.close()"></button>
```

**Comment by gregory-sokolov** [comment]
@JavanXD seems that still needed this feature.

What if you have popover container set as 'body' and it is attached to DOM with no parent elements?
The popover parent is in the first red Angular App block while the popover is in the second one on the bottom and it has no parents.

![popover](https://user-images.githubusercontent.com/34014511/33336029-d06deba2-d47f-11e7-90c2-f6f3c3f082f6.png)

The hack with placement indeed adds provided class to the popover, but it breaks the placement itself. 
`<div  [ngbPopover]="productListContent" #productList="ngbPopover" placement="right dc-products" container="body"
                  <div class="badge badge-default">New</div>
                </div>`

**Comment by johanna-bodnyk** [comment]
Agreed that this would be a useful feature. Like others here I need to apply custom styling to some but not all popovers on my page. I worked around it by specifying a particular element as the container but it seems a bit hacky -- IMO there should be a way to target a particular popover regardless of its position in the DOM.

**Comment by harsimerkaur** [comment]
@JavanXD I liked your idea but now my popover does not behave responsive. Anyone has solution to this. Adding too many media queries is tedious.

**Comment by rockyromano** [comment]
I'm really not finding any solution to this issue, especially when container is body. We need the ability to apply classes so that we can style some, but not all, popovers.

**Comment by migueldelprado** [comment]
As workaround, you can override the property max-with and then set the desired width inside the template.

.popover {
    max-width: none !important;
}

<span class="btn-link"
      #infoPopup="ngbPopover"
      [ngbPopover]="projectPopup"
      container="body"
      triggers="manual"
      placement="right-bottom"
      (mouseover)="openWithTimeout(infoPopup)">
    ....
</span>


<ng-template #projectPopup>
    <div class="m-0 p-2" style="width: 500px">
.....
</ng-template>

**Comment by fedefabre** [comment]
Hi everyone!

I fix it using /deep/ property:

styles.less:
```
:host{
 /deep/ .popover-body{
   background: red;
 }
}
```
html:

```
<button class="btn btn-action" [ngbPopover]="addUser" #addUserPopover="ngbPopover"
  placement="bottom-right" [autoClose]="false" triggers="manual" (click)="addUserPopover.open()">

<ng-template #addUser>

  <section id="addUserPopover">
    <header>
      <h2>Add user to population</h2>
    </header>
    <footer>
      <button class="btn btn-cancel pull-left">Cancel</button>
      <button class="btn btn-action pull-right">Apply</button>
    </footer>
  </section>

</ng-template>
```

result:
![result](https://user-images.githubusercontent.com/29164856/46421248-5af49400-c6f7-11e8-9428-d2cc5b266482.PNG)

**Comment by ericsnap** [comment]
@fedefabre that is fine for now, but the `/deep/` selector is being [deprecated](https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep) and it clearly states _not_ to use it anymore. 
Really wished there was an Angular-compatible way to do this.

**Comment by karanbhalla** [comment]
I agree with @harsimerkaur . The popover is no longer responsive and the css attributes like max-width don't work either.

**Comment by AndriDev** [comment]
Use popoverClass. PS Have not time to investigate docs, can't find, but it works
In some ts/js event do
    mouseEnter(popover) {
            popover.popoverClass = 'desk-user';
            //popover.open();
    }

html
                            <div class="desk-text-wrapper" #po="ngbPopover" (mouseenter)="mouseEnter(po)" (mouseleave)="po.close()" [ngbPopover]="popContent" placement="right">
                                your label
                            </div>
        <ng-template #popContent>
            your popover content
        </ng-template>
