### ISSUE TITLE
Dropdown Select

### ISSUE THREAD

**Issue by irshadmalek11** [ng-bootstrap/ng-bootstrap#1026]
How would I use dropdown

So when I select value from dropdown, it does not show for e.g. in below example provided

https://ng-bootstrap.github.io/#/components/dropdown

if I click on dropdown where value is by default "Toogle Dropdown" and select value "Action 1" it does not show. It always shows "Toggle Dropdown"
Is it suposed to be like that ? or do I need to do some extra work for that? I think I am missing here something.
how would I get value of that drop down in my angular component when I submit ?

please advice.

**Comment by pkozlowski-opensource** [comment]
Dropdown component is for creating menus it is _not_ a select component. What we've got is equivalent of http://v4-alpha.getbootstrap.com/components/dropdowns/

I think that you are confused about the role of the dropdown component in Bootstrap. Maybe you are looking for https://ng-bootstrap.github.io/#/components/typeahead instead?

In any case this sounds like a general support question and as such doesn't belong here: https://github.com/ng-bootstrap/ng-bootstrap#getting-help

**Comment by guslalo** [comment]
con esto puedes usar ng-bootstrap con estilos 
https://github.com/ng-select/ng-select
