### ISSUE TITLE
type definition file error 1.0.0-alpha.12

### ISSUE THREAD

**Issue by scttcper** [ng-bootstrap/ng-bootstrap#1027]
I'm seeing `/// <reference types="core-js" />` in 1.0.0-alpha.12 from modal-ref.d.ts

```
ERROR in [default] ./node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-ref.d.ts:1:0
Cannot find type definition file for 'core-js'.
```

**Comment by pkozlowski-opensource** [comment]
@scttcper are you sung TS 1.8 by any chance?

@Foxandxss could this by side effect of migration to types?

**Comment by scttcper** [comment]
I'm using angular-cli latest beta 19-3. Comes with ts ~2.0.3

**Comment by pkozlowski-opensource** [comment]
@scttcper we've recently migrated to `@types` (https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/) so this is probably a side effect of it.

We need to investigate to understand what is going on exactly but in the meantime you can go back to alpha.11....

**Comment by scttcper** [comment]
@pkozlowski-opensource 
i think you'll have to drop @types/core-js
It will throw errors for promises, ect.. but you can silence those by adding `"lib": ["es6", "dom"]` to the tsconfig.

Might also need
```
"types": ["node"]
``` 
but i'm not sure.

**Comment by pkozlowski-opensource** [comment]
@scttcper you are correct, we've just figured it out. We are going to fix it and cut a new release in a few hours.

**Comment by pkozlowski-opensource** [comment]
alpha.13 with the fix should be on npm now.
