### ISSUE TITLE
Timepicker: 12 PM is displayed as 00 AM when meridian option is true.

### ISSUE THREAD

**Issue by yehudag** [ng-bootstrap/ng-bootstrap#1031]
### Bug description:
Visit the demo page for timepicker: [https://ng-bootstrap.github.io/#/components/timepicker](https://ng-bootstrap.github.io/#/components/timepicker)
If the meridian option is true, timepicker will display 12:mm pm as 00:mm AM. The underlying hour value itself is actually correct at 12 , as displayed in the json pipe below.

**Comment by pkozlowski-opensource** [comment]
> timepicker will display 12:mm pm as 00:mm AM

What would be the difference between, say 12:10 PM and 00:10 AM in the context of datepicker that doesn't have notation of days (we are tracking only hours)?

I believe that it works as expected, but happy to change my opinion if someone can convince me otherwise...

**Comment by pkozlowski-opensource** [comment]
Oh, actually, I see what you mean, here is a plunker: http://plnkr.co/edit/1ez1f5iqzsJtDynM2MUd?p=preview

Yes, this is a bug.

**Comment by yehudag** [comment]
I did some digging, it won't be to difficult to fix. I'm happy to open a PR.

**Comment by pkozlowski-opensource** [comment]
> I'm happy to open a PR.

This would be awesome! Just please make sure to add relevant test(s). Thnx!

**Comment by yehudag** [comment]
I haven't really contributed much before , but I'll review the Contributing guide.
