### ISSUE TITLE
Feature request : allow multiple and range date selection in datepicker

### ISSUE THREAD

**Issue by Eagleseb** [ng-bootstrap/ng-bootstrap#1037]
Hi folks, it would be great if datepicker could support multiple date selection and range selection like this one: [ng2-datepicker](https://www.npmjs.com/package/ng2-datepicker).

Thanks !

**Comment by pkozlowski-opensource** [comment]
Duplicate of #753. In short - it is in the works, should land soon. Also check long-term plans for datepicker: #862

**Comment by avineet1993** [comment]
how can we change multipledate seperator in ng2-datepicker?
