### ISSUE TITLE
Custom Extend tooltip functionality.

### ISSUE THREAD

**Issue by narainsagar** [ng-bootstrap/ng-bootstrap#1043]
Hello, First of all. Thanks for this great project..

In my project I have my own dynamic form-builder and tooltips assigned to the fields.. I'm using your tooltip module i.e., `ng-bootstrap/ng-bootstrap/src/tooltip` in my app.

### description:

In my project I want to extend your tooltip functionality to override the tooltip positioning's dynamically as i mentioned above that i have my own dynamic-form-builder and tooltips assigned to fields. 

So, For now I have just extended your `NgbTooltip` class i.e., `ng-bootstrap/ng-bootstrap/src/tooltip` and overriden it's `open()` function to re-adjust positions according my needs.

```
export class CustomNgbTooltip extends NgbTooltip {

   constructor() {
     super();
   }

   adjustPositions() { // do my own stuff with tooltip here.
        if(this.isOpen()) {
            let element = this.elementRef.nativeElement.nextElementSibling;
            // do my own stuff on the tooltip here..
            console.log('left', element.style.left);
            element.style.left = '400px';
            console.log('left', element.style.left);
        }
    }

    open() {
        console.log('open() called..');
        super.open();
        this.adjustPositions();
    }

}
```

However in your *1.0.0-alpha.3* release i was doing like the same as i did in plunkr demo and it was working fine.. but when i upgraded to *1.0.0-alpha.13* release version and re-adjusted the extended class it doesn't seems to work. Seems like it's messing up with something,  maybe with your `positioning` stuff..

### Sample Plunkr here: https://embed.plnkr.co/N48s2PrnAmT5KPliQ2VA/

I don't know it is a good approach to extend any third party lib or not.. so kindly suggest me any possible nicer way to extend your functionality..

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.1.0

ng-bootstrap: 1.0.0-alpha.13

Bootstrap: 3.3.7

Cheers,
Narain Sagar

**Comment by pkozlowski-opensource** [comment]
I'm sorry but at this point we are not offering any official way of extending our directives. We _might_ investigate this in the future but currently our directives were not designed for subclassing (not to mention that inheritance doesn't really work in Angular itself today).

You particular issue might be solved by #992 which we are going to implement in the future.

Going to close this one as we are not going to introduce extension flex points till the Angular subclassing story is clarified.
