### ISSUE TITLE
NgbModal Simplify the ngb-modal header template 

### ISSUE THREAD

**Issue by ktriek** [ng-bootstrap/ng-bootstrap#1044]
Simplify the modal header to take parameters instead of writing the header html code. 
```
<ngb-modal 
         title="Modal Title" 
         [headerClass]="default|primart|success|danger"
         [dismissible]="true|false">
    <div class="modal-body">
        Modal body 
    </div>
   <div class="modal-footer">
        <button type="button" class="btn btn-primary" >Close</button>
    </div>
</ngb-modal>
```

**Comment by pkozlowski-opensource** [comment]
I don't think this is the right approach as it would severely limit flexibility (all of the sudden titles could only contain text and no longer HTML and / or Angular 2 components / directives). 

The good news is that you can easily create a component on your side that would encapsulate whatever repeated HTML parts you've got. It would be trivial to create a, say `<my-modal-header title="Modal Title">` and use is everywhere you want to have defaults.

I'm going to close this one for now as I don't think we want to go down the path of the proposed API and equally good solutions exists in the user-land.
