### ISSUE TITLE
demo server task fails with errors

### ISSUE THREAD

**Issue by mcgraphix** [ng-bootstrap/ng-bootstrap#1047]
### Bug description:
When cloning repo and running gulp demo-server it fails with the following errors. It seems like this might be related to the version of webpack

````
ERROR in multi polyfills
Module not found: Error: Can't resolve 'ts' in '/Users/mckeowr/Documents/git/ng-bootstrap'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' prefix when using loaders.
                 You need to specify 'ts-loader' instead of 'ts'.
 @ multi polyfills

ERROR in multi vendor
Module not found: Error: Can't resolve 'ts' in '/Users/mckeowr/Documents/git/ng-bootstrap'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' prefix when using loaders.
                 You need to specify 'ts-loader' instead of 'ts'.
 @ multi vendor

ERROR in multi app
Module not found: Error: Can't resolve 'ts' in '/Users/mckeowr/Documents/git/ng-bootstrap'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' prefix when using loaders.
                 You need to specify 'ts-loader' instead of 'ts'.
 @ multi app

ERROR in   Error: Child compilation failed:
  Entry module not found: Error: Can't resolve 'raw' in '/Users/mckeowr/Document  s/git/ng-bootstrap'
  BREAKING CHANGE: It's no longer allowed to omit the '-loader' prefix when usin  g loaders.
                   You need to specify 'raw-loader' instead of 'raw'.:
  Error: Can't resolve 'raw' in '/Users/mckeowr/Documents/git/ng-bootstrap'
  BREAKING CHANGE: It's no longer allowed to omit the '-loader' prefix when usin  g loaders.
                   You need to specify 'raw-loader' instead of 'raw'.
````

Mac 10.11.6
Node 5.7.1
Npm 3.6.0

**Comment by deeg** [comment]
Looks to be related to #1045. 

I was not having this issue, and then I did a fresh checkout and npm install, and started running into the issue. It must be an issue with one of the dev dependencies which isn't locked down to a specific version.

I did some brief searching, but haven't had time to look into it further yet.

**Comment by deeg** [comment]
It has to do with [breaking changes from webpack](https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.26) and [webpack dev server](https://github.com/webpack/webpack-dev-server/releases/tag/v2.1.0-beta.11)

For now hardcoding to version 2.1.0-beta.25 & 2.1.0-beta.10 does the trick until someone has time to fix the breaking changes.

We may want to consider locking down all version numbers so things like this don't happen, and systematically updating when we have time.
