### ISSUE TITLE
Scroll problem - after 2 or more modals be opened

### ISSUE THREAD

**Issue by liuxue0905** [ng-bootstrap/ng-bootstrap#1051]
1. A page p1 contains many things can scroll verticall, 
2. Open modal No.1 (contains many things best), we try scroll, this modal is scrolled.
3. Open modal No.2 from modal No.1.
4. Close modal No.2, back to modal No.1.
5. Now, modal No.1, try scroll.
=> we will notice that: 
modal No.1 can not be scrolled anymore, the page p1 behind modal No.1 scrolled.

**Comment by pkozlowski-opensource** [comment]
We are not supporting multiple modals (modals opened from each other) and as such we won't investigate / fix any issues that are linked to multiple modals. We _might_ support stacked modals in the feature (#643) but this is not the case today. Please note that stacked modals are not supported in Bootstrap either.
