### ISSUE TITLE
ngbTooltip: add new option "delay"

### ISSUE THREAD

**Issue by Coleim** [ng-bootstrap/ng-bootstrap#1052]
Hello,

In bootstrap 4, it seems that we have the possibility to add a delay on the tooltip display.
`<div data-toggle="tooltip" data-placement="top" title="Tooltip on top" data-delay='{"show":"5000", "hide":"3000"}'></div>`

But I think this feature is not available with ngbTooltip.
Is it possible to add it ?

#### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 2.1.1
ng-bootstrap: 1.0.0-alpha.3
Bootstrap: 4.0.0-alpha.5

Thanks

**Comment by monkatar** [comment]
Based on the docs "tooltipPopupDelay" was available for use at some point but has since been tagged as deprecated without a replacement. It doesn't seem to work correctly anyway, so I would advise against using it.
Any updates on the state of the feature request?

**Comment by KissBalazs** [comment]
I think some of us are still interested in this feature - any updates or known solutions for this feature maybe?

One possible workaround I did is that you could do this with mouse events + html bind manually, but with dynamically generated divs it is quite ugly to manage.

**Comment by dagangalarneau** [comment]
Here's my workaround, using pure CSS:

.tooltip > div {
  animation-name: delayedFadeIn;
  animation-duration: 1s;           /* Adjust this duration */
}

@keyframes delayedFadeIn {
  0% {opacity: 0;}
  75% {opacity: 0;}              /* Set this to 99% for no fade-in. */
  100% {opacity: 1;}
}

**Comment by KissBalazs** [comment]
@dagangalarneau really nice solution, thank you very much!
