### ISSUE TITLE
NgbDatepicker navigation doesn't work properly when minDate is used

### ISSUE THREAD

**Issue by davidalee** [ng-bootstrap/ng-bootstrap#1057]
### Bug description:
When setting `minDate` with `NgbDatepicker`, the month navigation allows you to select a previous month but does not update the calendar view so that you are in the same month you were before even though the month dropdown has updated.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/pVafoM7up5e1KrCyLdy9

I've set `minDate` in the plunker to 11/20/2016. From the month dropdown, select any month prior to November and you'll notice that while the month dropdown updates to the month you just selected, the view itself does not update.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.0.0

ng-bootstrap: 1.0.0-alpha.13

Bootstrap: v4 alpha

**Comment by PEsteves8** [comment]
In your plunkr, if you advance a few months and go back using the arrows, you can't go past december. There's also that.

Before they added the multiple datepickers, I implemented my own navigation logic.  And I remember having those problems. I ended up having to add a bunch of logic to actually disable the select options that would be part of disabled dates.
