### ISSUE TITLE
Circular progress

### ISSUE THREAD

**Issue by natcohen** [ng-bootstrap/ng-bootstrap#1058]
Any plan to add such feature? I know it's not in the angular 1's version but it's extremely useful when we don't have a progress measure...

If it's not planned, what do you recommend to use?

**Comment by pkozlowski-opensource** [comment]
Sorry, no plans to implement it as not part of the Bootstrap: http://v4-alpha.getbootstrap.com/components/progress/. Might re-consider if there is a popular Bootstrap-based CSS.

> If it's not planned, what do you recommend to use?

Can't recommend anything, really.
