### ISSUE TITLE
Datepicker: Spinner icon over Month and year text

### ISSUE THREAD

**Issue by Palacios95** [ng-bootstrap/ng-bootstrap#1061]
### Bug description:

The spinner icon on the ngb-datepicker is over the month and year text.

Below is actually a plunk created by the ng-bootstrap team that shows this error.

##Plunk: 

http://plnkr.co/edit/bZDUvT8NUHO4CrtG9SQ9?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.1.1

ng-bootstrap: 1.0.0 alpha 11 (Alpha 13 has an issue with the modal which does not let me use it. I will create another issue for it)

Bootstrap: v4.0.0-alpha.5

**Comment by pkozlowski-opensource** [comment]
Related to #706

**Comment by Palacios95** [comment]
Is there any temporary workaround for this that your recommend?

**Comment by pkozlowski-opensource** [comment]
> Is there any temporary workaround for this that your recommend?

Not tons of workarounds since this is a native `<select>` element and as such we've got limited control over its display. One way would be to disable navigation completely...

**Comment by deeg** [comment]
By spinner icon do you mean the arrows of the select dropdown which are over the text of the selected value?

It seems they have to do with the width and padding settings on the select elements. You could try playing with that CSS temporarily until it is fixed within the styles of this library.

**Comment by Palacios95** [comment]
I've tried that to no avail, but i'll keep tinkering with it if I have any
extra time on my hands.

Thanks!

**Comment by priesett** [comment]
I ran into the same issue, and my workaround was to add the btn class to them.  It seems something causes chrome to ignore the -webkit-appearance: none; rule.

**Comment by maxokorokov** [comment]
Honestly I think these selects should be replaced by the ng-bootstrap dropdowns

- Pros are that is would look better and the same across all browsers. Now IE looks horrendous
- Cons are obviously that we'll loose all the native functionality

**Comment by priesett** [comment]
For what it's worth, I've been looking around at styles from btn, and it looks like adding 

background-image: none;

to custom-select should resolve this specific issue (at least as I'm seeing it). I haven't double-checked yet as I'm working on something else at the moment, but it's working in the inspector.

**Comment by Matmo10** [comment]
This is the issue being discussed here right? ![img](http://www.i.imgur.com/oqPpLP9.png)

**Comment by maxokorokov** [comment]
This should be fixed when #1205 with different default look lands

**Comment by Matmo10** [comment]
I didn't want to open an issue just for this, but why doesn't `Signature: navigateTo(date: { year: number; month: number; })` also accept a day? Is there no way to programmatically select a day? 

Also is there any way to use this reactively? I want to string together some actions when a date is selected, but the only way I can seem to do that is by using a typescript "setter" to hijack the model changes process. Am I missing something here?

I really wasn't sure where to ask this 🤕

**Comment by maxokorokov** [comment]
Hey, @Matmo10. You should use stackoverflow for this kind of questions as described in ["getting help"](https://github.com/ng-bootstrap/ng-bootstrap#getting-help).

Navigation and selection are decoupled. Meaning selection happens via the `ngModel` binding,  and currently displayed month is switched via 'navigateTo()' or 'startDate'.

You can use the usual `(ngModelChange)="onChange($event)"` to be notified of selection.

If you have any further questions, let's move the discussion to SO.
