### ISSUE TITLE
NgbDatepicker: infinite loop when using Date object with datepicker toggle

### ISSUE THREAD

**Issue by jacqueslareau** [ng-bootstrap/ng-bootstrap#1062]
### Bug description:

Browser crash/full cpu/infinite loop when setting model as new Date() and toggling the datepicker popup.

CAREFUL : See plunkr and click the button for the toggle, will have to restart script/tab/browser.

Checked on Firefox and Chrome.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/z4FuG5CXzalen5BFV9Cc?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.2.1

ng-bootstrap: 1.0.0-alpha.13

Bootstrap: v4-alpha

**Comment by CrustyJew** [comment]
I just encountered this same issue a different way, by providing a year with no month and it causes the same loop. I've submitted a pull request (#1063) that resolves this issue by defaulting the month to 1.

**Comment by Thommas** [comment]
Just got this issue.

It's really surprising ! I just copy pasta the documentation and end up with my Google Chrome freezed. Quite dangerous.

A fix would be welcome.

**Comment by leonardoampuero** [comment]
I had that problem, I was setting the default date wrongly.

  ngOnInit() {
    const now = new Date();
    const since = moment().subtract(14,'d').toDate();

    this.model.fechaHasta = {year: now.getFullYear(), month: now.getMonth() + 1, day: now.getDate()};
    this.model.fechaDesde = {year: since.getFullYear(), month: since.getMonth() + 1, day: since.getDate()};
  }
