### ISSUE TITLE
Styling the popover impossible -> .popover-content inaccessible

### ISSUE THREAD

**Issue by yanis84** [ng-bootstrap/ng-bootstrap#1066]
Hello,

I have used ng-bootstrap to have a popover appear. I encounter an issue as I want to style it.

In this image:
<img src="http://res.cloudinary.com/jimmythebot/image/upload/v1479608000/Bildschirmfoto_2016-11-20_um_03.04.16_g46lyf.png" style="height:200px;width:auto;" />

You can see a padding linked to .popover-content that makes setting a background color not very nice... And I cannot manage to access it!

Thanks for the support and the great job!

**Comment by pkozlowski-opensource** [comment]
You need to use

```css
:host >>> .popover-content {
      ...
}
```

See https://github.com/ng-bootstrap/ng-bootstrap/issues/1024#issuecomment-259806457 for more details.
