### ISSUE TITLE
Dynamic Content (component) inside Tab/Accordion Content

### ISSUE THREAD

**Issue by mohammedzamakhan** [ng-bootstrap/ng-bootstrap#1069]
### Bug description:
Can't have dynamic content in tab/accordion

### Link to minimally-working plunker that reproduces the issue:
https://plnkr.co/edit/gVHk4vvzIungMfIJVD4l?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.2.1

ng-bootstrap: Latest

Bootstrap: v4

**Comment by pkozlowski-opensource** [comment]
This is not something specific to ng-bootstrap, you can see exactly the same behavior with any Angular component: https://plnkr.co/edit/vsmc4116zQqhAabRJmij?p=preview

Please note that what you are trying to do is to insert something into a view container that is completely replaced with the `TestComponent`'s template content. It looks very fishy and in fact I would expect Angular to throw (as the view container you are trying to use doesn't exist any more at the time of insertion).

I'm not sure what you are trying to do exactly (I must say that the plunker you've linked is rather confusing to me) so it is hard to offer alternatives.

**Comment by mohammedzamakhan** [comment]
If you have ng-content it works fine in Angular: https://plnkr.co/edit/xf5kZNCj9sOeK3EyLN18?p=preview

It doesn't seems to be angular issue to me.

**Comment by pkozlowski-opensource** [comment]
> If you have ng-content it works fine in Angular

Sure, but components are not _forced_ to have `<ng-content>`. I will discuss this issue with Misko and Tobias but my point holds: I can reproduce your exact issue without ng-bootstrap. Tabs / Accordions are _not_ using `<ng-content>` as it is not powerful / dynamic enough to properly handle those components.

**Comment by mohammedzamakhan** [comment]
If I can't do 
```html
<template ngbTabContent #field></template>
``` 
or 
```html
<template ngbTabContent>
    <template #field></template>
</template>
```

There should be a way to put dynamic content inside ngbTabContent

We had a bug on ng2-formly, where the person wanted to use `formly` with `ng-bootstrap` and he did the first in order to get a fields dynamically inside the `ngbTabContent`
https://plnkr.co/edit/LjbRLPrbh0GI7kp7DiLf?p=info

**Comment by mohammedzamakhan** [comment]
Any updates @pkozlowski-opensource ??

**Comment by azarus** [comment]
Hellllooo? I really don't want to be demanding but any updates on anything here? I have the same issue except i would like to use **ngb-accordion**

**Comment by geetee24** [comment]
@mohammedzamakhan 

Your plunkr at https://plnkr.co/edit/z31ngGCEwykcCqPuBOjM?p=preview 

is broken.  Can you possibly get it to work again?  So that I can get dynmic content?

**Comment by geetee24** [comment]
@mohammedzamakhan 

I want my content of my tab to self adjust when the data model backing it changes.  Could  formly do that? I know zero about formly.  Thanks.

**Comment by mohammedzamakhan** [comment]
@geetee24 it should be able to handle it

**Comment by mohammedzamakhan** [comment]
https://ng2.angular-formly.com/guides/ng-bootstrap-tabs.html
