### ISSUE TITLE
[Rating] selects a new rating is not working

### ISSUE THREAD

**Issue by aitboudad** [ng-bootstrap/ng-bootstrap#1072]
### Bug description:
When I try to select a value, the model doesn't change value

https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/rating/rating.ts#L167

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/qxPsjxRxPrOST9I4jviB?p=preview
https://ng-bootstrap.github.io/#/components/rating

**Comment by pkozlowski-opensource** [comment]
Wow, looks like a pretty severe regression, thnx for reporting.... @maxokorokov could you please have a look?

**Comment by pkozlowski-opensource** [comment]
I can confirm that this is a regression introduced in da0b6a0f586f1fc15dc1760826f48162d2b79985 - the sad part is that existing test didn't catch it... We will fix it for alpha.14 and update tests.
