### ISSUE TITLE
NGB-TIMEPICKER 12 PM error

### ISSUE THREAD

**Issue by MFalbo** [ng-bootstrap/ng-bootstrap#1076]
### Link to minimally-working plunker that reproduces the issue:

This is can be reproduced in the ng-bootstrap documentation.
https://ng-bootstrap.github.io/#/components/timepicker meridian demo

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.0.1

ng-bootstrap: 1.0.0-alpha.13

Bootstrap: 3.3.7

**Comment by pkozlowski-opensource** [comment]
See https://github.com/ng-bootstrap/ng-bootstrap/issues/1071#issuecomment-262184581
