### ISSUE TITLE
Progress Bar custom color

### ISSUE THREAD

**Issue by ialex90** [ng-bootstrap/ng-bootstrap#1078]
Hi there,

It's not an issue itself, more like a suggestion, I think it's not possible to change the color of the progress bar component, only having those 4 options (success, info, warning, danger).

From my point of view, it doesn't make sense don't allow to customize the color, it doesn't seem to be a complex feature to develop but it might be.

I think, using template it would be possible, as I've been working with popover template and I could customize colors and things. If not, a fast and useful fix could be to add and attribute to accept color in hexadecimal pattern.

What do you think about it?
Thanks for the great work!

**Comment by pkozlowski-opensource** [comment]
I think that you can do it with pure CSS today without any changes to Bootststrap's CSS and / or this library: http://plnkr.co/edit/U0pqCfaVUfctbdqnZmI5?p=preview

**Comment by pkozlowski-opensource** [comment]
Closing as per above comment.

**Comment by ialex90** [comment]
Hi @pkozlowski-opensource just to give you me feedback.

First, the code you sent, it does not work in all browsers, just on webkit engines, does not work on Firefox, on IE neither Edge.

Second, I am not asking you to fix the problem for me, I know how to do it with CSS but tell me, what is the advantage of a framework? no writing that much code, isn't it? what you just told me is do it with CSS because it's possible. As far as I know, this framework is not needed, cause all you have under the hood is CSS and JS at the end, Can't I do it by myself? with that thought, Do I really need bootstrap framework? Can't I do it by myself? yes I can, but that's the point of a framework, write less and have standar components/behaviors to cover often cases.

If you think that having only 4 colors for the progress bar is enough and people won't potentially want to change the color of them because they will just use those 4, it's alright, I can or can't agree but ok, but the reason you said that you can do it with CSS is not a news.

Last, I am not a contributor, you are, so you decide what to do with the framework that you guys are building, that was just a suggestion, if you don't think is good to implement, that's fair enough.

Thanks! :)

**Comment by pkozlowski-opensource** [comment]
> If you think that having only 4 colors for the progress bar is enough and people won't potentially want to change the color of them because they will just use those 4, it's alright, I can or can't agree but ok, but the reason you said that you can do it with CSS is not a news.

We are on-par with Boostrap itself here so you could ask the same question to the upstream project. Using pure Bootstrap itself you would have to add _exactly_ the same code as I've linked in the plunker. 

Other point: passing colors as hex is not great really as you would have to potentially repeat the same code over and over again and CSS class is the way to go here. This is what I was suggesting.

I hear what you are saying but we need to constantly evaluate user requests vs. code it adds and API surface it results in. If you believe that this feature request is important enough to justify more code & larger API feel free to send a PR - if it doesn't add too much code we might consider merging it.

**Comment by ialex90** [comment]
> If not, a fast and useful fix could be to add and attribute to accept color in hexadecimal pattern.

> Other point: passing colors as hex is not great really as you would have to potentially repeat the same code over and over again and CSS class is the way to go here. This is what I was suggesting.

Well, the point is I'm not telling you how to implement it, I'm telling you that I think it's useful to have it as it's really poor the combination of colors and I think it makes sense.

I can send a pull request after think best way to implement it, but if you/your team consider that this feature is not needed, I won't do it, otherwise I'll do it

**Comment by pkozlowski-opensource** [comment]
> I can send a pull request after think best way to implement it, but if you/your team consider that this feature is not needed, I won't do it, otherwise I'll do it

I can see value in custom colors so if you can come up with a PR that doesn't add too much code and API surface we would certainly consider it. But of course I can't guarantee that we will merge it since it will depend on the PR content.

**Comment by ialex90** [comment]
Yeah that totally makes sense, it depends of the code and the way, but if you are going to consider it, definitely worth it,
Thanks!
