### ISSUE TITLE
Treeview, Splitter, Grid and Listbox component request.

### ISSUE THREAD

**Issue by juniur** [ng-bootstrap/ng-bootstrap#1079]
Treeview- can you add this component in your components with a microsoft type explorer features, can support JSON format.
Splitter - a component in between for these components like Treeview and Listbox and support horizontal and vertical.
Grid - an excel look alike with the these features, basic features, can have tree, sort, drilldown, can support JSON format and etc.
Listbox - windows like features of listbox, can support JSON.

**Comment by pkozlowski-opensource** [comment]
Thnx for the suggestion but we've got no intention of adding mentioned directives / components to this project. Those are not part of the original Bootstrap components and would represent significant amount of effort for which we don't have resources right now.

Those components would be good candidates for a separate project(s). Maybe you could start one?
