### ISSUE TITLE
Nested modal is not working from version 1.0.0-alpha.11

### ISSUE THREAD

**Issue by ypalaniappan** [ng-bootstrap/ng-bootstrap#1080]
Nested modal is not working from version 1.0.0-alpha.11 to 1.0.0-alpha.13(latest version)
For Example please refer below plunker:
http://plnkr.co/edit/hYl7oTnRp9awIwFF5vrt?p=preview

Nested modal binding inside parent modal, instead of opening outside of modal.

**Comment by pkozlowski-opensource** [comment]
We are not supporting nested modals, see: #643. As such we won't investigate / fix any issues till we've got official support (if we decide to add it). Please note that nested modals are not supported in the original Bootstrap library as those tend to result in the bad UX.
