### ISSUE TITLE
Click and blur trigger not working on a templateRef tooltip.

### ISSUE THREAD

**Issue by scarmarco** [ng-bootstrap/ng-bootstrap#1085]
### Bug description:

There is a bug with tooltip triggers when I do a `triggers="click:blur"` on a "template tooltip" it doesn't close on blur, it actually doesn't event close on click, only does if I leave `click` trigger alone.

This is the original code:

**button**: 

```
<div class="col-md-1">
	<i class="fa fa-retweet social-icon" aria-hidden="true" [ngbTooltip]="retweetTip" placement="right" container="body" triggers="click:blur"></i>
</div>
```

**tooltip**:

```
<template #retweetTip>
	<div style="width: 220px; height: 100px; background: white;">
		<div style="height: 50%"><span style="color: black; font-size: 140%">¿Que desea hacer?</span></div>
		<div style="height: 50%">
			<button class="social-button social-confirm">Retweet</button>
			<button class="social-button social-confirm">Citar</button>
	 		<button class="social-button social-confirm">Editar</button>
		</div>
	</div>

</template>
```

**Proof**: https://gyazo.com/37378081c8bdaffbef6d305a3b7a177a

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.1.1
 
ng-bootstrap: 1.0.0-alpha.13

Bootstrap: 4.0.0-alpha.4

**Comment by pkozlowski-opensource** [comment]
I don't think that `<i>` / `<div>` elements support `blur` event (and for sure not if those are not focusable => without tabindex set). Try to catch `blur` event on `<i>` in pure Angular 2 / JS and send a plunker. If it works in Angular 2 I can look into it but not without a plunker. Here is why:   https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment]
I've noted above by default `<i>` elements are not focusable (so can't react on `focus` / `blur`) events: http://plnkr.co/edit/F9G4DoVqYqzsFMEyia7C?p=preview

You _might_ add `tabindex="0"` to the `<i>` element to make it focusable and then `blur` will be fired: http://plnkr.co/edit/00G02J3GtyKVGy0Ks7RA?p=preview

Closing as a support request not specific to ng-bootstrap.

**Comment by scarmarco** [comment]
Thanks, will try with tabindex.
