### ISSUE TITLE
Can't use reactive form with rating

### ISSUE THREAD

**Issue by natcohen** [ng-bootstrap/ng-bootstrap#1087]
For some reason I can't make the ratings work with reactive form (and the `formControlName`).

I've tried [the following](http://plnkr.co/edit/Pg6HcQyRAdARy5xfrnT1?p=preview) without success. Is it a bug or should we use reactive forms differently with this component (in this case we should add to the documentation)? 

HTML:
```
<ngb-rating [(rate)]="currentRate" formControlName='answer'>
  <template let-fill="fill">
    <span class="star" [class.filled]="fill === 100">&#9733;</span>
  </template>
</ngb-rating>
```

**Comment by maxokorokov** [comment]
The rating doesn't implement the `ControlValueAccessor`, so can't be easily used with forms the way you want it and the way other components are used. So I guess we should:

- Make rating work with forms by implementing the `ControlValueAccessor`
- Probably replace `rate` with `ngModel`

**Comment by natcohen** [comment]
@maxokorokov Then yes, we should implement `ControlValueAccessor`...
