### ISSUE TITLE
Hide Tab Buttons (Headers)

### ISSUE THREAD

**Issue by rollis** [ng-bootstrap/ng-bootstrap#1093]
### Bug description: Feature request

If one wants to display existing Tabs in mobile view, he or she may want to use dropdown to list available tabs. 
To interchange Tab Buttons / Dropdown based on the platform (desktop or mobile) without duplicating tab contents,
it would be nice to have option to hide Tab Headers, so that dropdown menu can be added to change tabs using active IDs.

If there's better way to achieve this with current implementation, sorry please let me know.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.2.0

ng-bootstrap: 1.0.0-alpha.13

Bootstrap:

**Comment by pkozlowski-opensource** [comment]
I can mark it as a feature request but my first reaction is this: if we hide navigation there is not much left from the tabset logic really and as such I'm not sure it makes sense to use this widget at all. 

Going to keep it open but TBH I'm not sure what would be the best course of action here. Still, this is an interesting use-case.

**Comment by rollis** [comment]
Thanks for the reply.
Do you think it makes sense for Tab component have option to choose displaying in normal tab Dropdown ? or is it too much since it's very restricted use-case?

**Comment by pkozlowski-opensource** [comment]
Sorry, after thinking about it some more my feeling is that what you are proposing is no more a tabset widget but rather a new type of widget. As we are not adding new widgets to this project at this point I'm going to close this one as won't fix.
