### ISSUE TITLE
Timepicker feature request: allow for setting the underlying input control size

### ISSUE THREAD

**Issue by yehudag** [ng-bootstrap/ng-bootstrap#1094]
### Bug description:
This is a feature request. I am working on a form where smaller form controls would be preferable.  Currently there is now way to set the height size of the Timepicker inputs. 

In BS3 we were able to control the sizing of controls by adding the class `form-group-lg/sm`  on the parent element. Bootstrap 4, removed that option: we must now add the class `form-control-lg/sm` on the form-control itself. [https://v4-alpha.getbootstrap.com/components/forms/#control-sizing](https://v4-alpha.getbootstrap.com/components/forms/#control-sizing)

### Link to minimally-working plunker that reproduces the issue:
Just a link to the demo site showing that there is no such option. 
[https://ng-bootstrap.github.io/#/components/timepicker](https://ng-bootstrap.github.io/#/components/timepicker)

Angular:
NA
ng-bootstrap:
1.0.0-alpha.14
Bootstrap:
4.0.0-alpha.5

**Comment by yehudag** [comment]
I can open a pull request to add this functionality. The solution I'm pondering requires adding an `@Input()` property to the timepicker api. Will adding a member to the public api get merged?

**Comment by pkozlowski-opensource** [comment]
@yehudag sorry for the late response. A new `@Input` is totally fine, no issue here. I just don't know what would be the impact on the existing timepicker template - that is - how much you would have to modify it to support different sizes. If you can find a way a supporting multiple sizes without exploding size of the existing template than a PR would be more than welcomed!
