### ISSUE TITLE
rename lib name

### ISSUE THREAD

**Issue by istiti** [ng-bootstrap/ng-bootstrap#1099]
I heard calling lib with **ng-** prefix is anti pattern cause it's reserved for core directives.
Okay not mandatory but angular team recommend use your own prefix. What do you think ? 
Ideas:

- valor-bootstrap
- vs-bootstrap

💃

**Comment by pkozlowski-opensource** [comment]
Thnx for the suggestion but we will pass on it - almost every library in the Angular ecosystem is using ng- prefix today.

Also not sure sure why you are bringing `valor` or `vs` prefix here - this library is created by open source maintainers (same people behind http://angular-ui.github.io/bootstrap/) and we don't have any affiliation to any particular user or company name (and we want it stay this way!).

**Comment by istiti** [comment]
please apologize was on different tabs ! **My wrong**
