### ISSUE TITLE
Datepicker in a popup causing modal dialog to close

### ISSUE THREAD

**Issue by vivaunix** [ng-bootstrap/ng-bootstrap#1103]
Placing "Datepicker in a popup" into "modal dialog" causing modal dialog to close when the date is selected.

Angular: 2.2.0
ng-bootstrap: 1.0.0-alpha.13
bootstrap: 4.0.0-alpha.5

**Comment by pkozlowski-opensource** [comment]
See https://github.com/ng-bootstrap/ng-bootstrap/issues/1100#issuecomment-263860084

tl;dr; upgrade to ng-bootstrap: 1.0.0-alpha.14

**Comment by vivaunix** [comment]
Search for an hour and could not find.
Thank you!
