### ISSUE TITLE
Bug: Cannot read property 'Observable' of undefined

### ISSUE THREAD

**Issue by aligneddev** [ng-bootstrap/ng-bootstrap#1104]
### Bug description:
I added in ng-bootstrap and started getting this error.

`VM325:9 Uncaught TypeError: Cannot read property 'Observable' of undefined(…)webpackUniversalModuleDefinition @ VM325:9(anonymous function) @ VM325:10module.exports @ scripts.bundle.js:28476 @ scripts.bundle.js:6__webpack_require__ @ inline.bundle.js:53826 @ scripts.bundle.js:37__webpack_require__ @ inline.bundle.js:53webpackJsonpCallback @ inline.bundle.js:24(anonymous function) @ scripts.bundle.js:1
main.bundle.js:420`

### Link to minimally-working plunker that reproduces the issue:
Please see my GitHub branch: https://github.com/aligneddev/JQueryToAurelia/tree/angular
This commit does not have this error 4a049710ba900f5aef8d11141491607e45e49cc2.
This commit [fcf8260c8b560f665fc4a34b49dd47f1700c3945 ](https://github.com/aligneddev/JQueryToAurelia/commit/fcf8260c8b560f665fc4a34b49dd47f1700c3945)'bring in bootstrap - couldn't get js include without observable of undefined error' introduced the error.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular 2.2 - CLI

ng-bootstrap: "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.14",

Bootstrap:

**Comment by pkozlowski-opensource** [comment]
I'm sorry, we can't debug you full setup. If you can reproduce the problem in a plunker (as requested in the issue template) than we are going to investigate & fix (if there is anything to fix).

**Comment by aligneddev** [comment]
Ok, I'll see if I can reproduce in a plunk. The one main difference will be that I'm using the Angular CLI and therefore web pack.

**Comment by aligneddev** [comment]
Fabio Antunes on StackOverflow pointed out my error.
http://stackoverflow.com/questions/40915311/angular-2-2-and-ng-bootstrap-cannot-read-property-observable-of-undefined/40917221#40917221

I created a blog post. You can use this if you'd like when you add docs and an example for the CLI. http://aligneddev.net/blog/2016/Ng-Bootstrap-with-Angular-CLI/
