### ISSUE TITLE
Tooltip only on hover

### ISSUE THREAD

**Issue by bialad** [ng-bootstrap/ng-bootstrap#1110]
I'm having some UX issues when using tooltips with touchscreens, and usually tooltips are not a good design pattern when using touch at all.

Most sites are used for both non-touch and touch. As such, I'm asking for a way to only open tooltips on hover. Is there a way to disable interaction on click, the demo only shows a way to disable hover interaction. 

I'd rather not disable tooltips on touch devices, since many have both mouse and touch.

**Comment by mohammedzamakhan** [comment]
I have seen websites like github for example ( desktop version) on mobiles, if you click a link which has a tooltip it opens on click and on second click does the click event.

**Comment by pkozlowski-opensource** [comment]
If you've got special needs when it comes to tooltip triggers just use ` triggers="manual"` and then manually open / close tooltips according to events you want to register to. This is documented on https://ng-bootstrap.github.io/#/components/tooltip and we've got specific example for this use-case: http://plnkr.co/edit/ldnvRSmRsHbjjx5C6cxG?p=preview

Closing as a support request: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
