### ISSUE TITLE
Dropdown: Use other event than the click event

### ISSUE THREAD

**Issue by dotcs** [ng-bootstrap/ng-bootstrap#1115]
### Bug description:
Component: dropdown

It should be possible to specify the event that is used to toggle the menu. Currently it's hard coded to use the [click event](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/dropdown/dropdown.ts#L113). I think it should be possible to use the same directives for context menus which would require to listen to the the `contextmenu` event instead of the `click` event.

Unfortunately I'm not sure how to do this best, because it's not decided within the component but the host. If we can discuss what would be the best way to do it, I could create a PR.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.1.2
ng-bootstrap: 1.0.0-alpha.14
Bootstrap: 4.0.0-alpha.4

**Comment by wesleycho** [comment]
It is possible to manually bind event listeners using `Renderer` - one could get the element through usage of `ElementRef`. Be warned though, manually managing this logic is quite a bit of work.
