### ISSUE TITLE
Open dropdown when mouse over?

### ISSUE THREAD

**Issue by kolkov** [ng-bootstrap/ng-bootstrap#1117]
Is it possible to open dropdown without click natively?
I'm talking about mouse over event firstly...
if it is not provided, is it possible to add such possibility?

**Comment by pkozlowski-opensource** [comment]
It is not clear what you are asking for. It _might_ be that manual triggers are what you are looking for: http://plnkr.co/edit/Rp7FTObiqNluUAH5yJJ6?p=preview (documented on our demo page:
https://ng-bootstrap.github.io/#/components/dropdown).

Hard to say more based on the info provided....

**Comment by kolkov** [comment]
I did not find the properties in which the menu should be opened.
I thought that I myself can specify an event for which the menu will be opened.
And this property will be built.

**Comment by kolkov** [comment]
This didn't work for me.
```
 <button class="btn btn-outline-success" (onmouseover)="$event.stopPropagation(); myDrop.open();">Open from outside</button>
  <button class="btn btn-outline-danger" (click)="$event.stopPropagation(); myDrop.close();">Close from outside</button>
```

**Comment by pkozlowski-opensource** [comment]
> This didn't work for me.

Could you elaborate? BTW, I think that event _name_ is `mouseover` and _NOT_ `onmouseover`

**Comment by kolkov** [comment]
Thanks! This worked!
`on-mouseover="$event.stopPropagation(); myDrop.open();"`

**Comment by kolkov** [comment]
One question more... How to close dropdown when mouse out from dropdown? Not from main button?

**Comment by UshaSanjeevam** [comment]
Thanks a lot it's worked me too.
I'm trying to open the ng drop down, In a text box search event..

Thanks Pawel :)
