### ISSUE TITLE
Typeahead: Support for max-height. 

### ISSUE THREAD

**Issue by jesben** [ng-bootstrap/ng-bootstrap#1121]
Hi 

It would be really nice if Typeahead could support "maxHeight" as input

Problem is, if I use below style, Key.ArrowDown and Key.ArrowUp do not scroll in dropdown!?

`.xxx .dropdown-menu {
    max-height: 250px;
    overflow-y: auto;
}`

**Comment by pkozlowski-opensource** [comment]
I believe that you are essentially looking for the same thing as described in #1119 so going to close this one as a duplicate. Feel free to provide more info in #1119 if needed.
