### ISSUE TITLE
center modal vertically option

### ISSUE THREAD

**Issue by mhmo91** [ng-bootstrap/ng-bootstrap#1124]
Add new configuration option to the open api to make the modal vertically centered
please check UIKIT framework style of doing this
https://getuikit.com/docs/modal.html

I'm suggesting to add an option called "center" type boolean, if it's set to true to vertically center the modal in the page

thanks!

**Comment by pkozlowski-opensource** [comment]
Thnx for the suggestion but we are going to pass on it this time: Bootstrap doesn't have this option. If you want this to happen please open an issue in Bootstrap's project.

**Comment by aendu** [comment]
The reason beeing valid, i don't like the current implementation with style="display: block" inside the module. This makes it realy hard to apply a simple display: flex. 

In the end, i ended up having to use !important :-(
```
.modal-open .modal {
  display: flex !important;
  align-items: center !important;
  .modal-dialog {
    flex-grow: 1;
  }
}

```

**Comment by paustint** [comment]
@pkozlowski-opensource - actually, [this option was introduced in bootstrap](https://getbootstrap.com/docs/4.0/components/modal/#vertically-centered).  Would it be possible to put this feature on the list for #2062?

**Comment by pkozlowski-opensource** [comment]
@paustint I'm going to re-open this one instead.

**Comment by kirilmitev** [comment]
Hey, I see that #2062 has been closed, but I still cannot find a way to vertically center modals. I tried with:

`this.modalService.open( this.deleteModal, { windowClass: 'modal-dialog-centered' } );`

The 'modal-dialog-centered' class gets set on the <ngb-modal-window>-element (where the 'modal' class is), but bootstrap states: 

> Add .modal-dialog-centered to .modal-dialog to vertically center the modal.

So I think the 'modal-dialog-centered' class should be on the div-element with the 'modal-dialog' class
Could somebody please chime in here?

**Comment by trickeyone** [comment]
Per the Bootstrap v4 documentation, having a dialog vertically centered is supported. https://getbootstrap.com/docs/4.0/components/modal/#vertically-centered

It could be achieved by allowing the `NgbModalOptions` to accept a new value of for `size` to also accept "dialog-centered". Since the template is:
```
<div [class]="'modal-dialog' + (size ? ' modal-' + size : '')"
```

**Comment by john-rossell-gpan** [comment]
Just bumped into this issue.

A new 'dialogClass' parameter would be a good addition; this could be as simple as just renaming the existing 'size' param.

**Comment by ramtinsoltani** [comment]
I'm also waiting for this to be implemented since it's introduced in the new Bootstrap. Any progress?

**Comment by VoroshilovMax** [comment]
Hi! Somebody found solution how to send modal window to the center ?

**Comment by crownofapollo** [comment]
Not the best solution because it's not typesafe, but as a workaround for now per @trickeyone 's suggestion above, I have implemented it using the following:

```
      let options: any = {
        size: "dialog-centered"
      };
      
      let modal = this.modalService
        .open(this.modal, options);
```

**Comment by mhmo91** [comment]
Guys, just use angular material components.... no point here!

**Comment by MichaelaLents** [comment]
This is an addition/follow up to @crownofapollo. To avoid the typesafe-ty issue but still get the element to center, I implemented the following: 
```
    const centerStyle = 'display: -webkit-box; display: -ms-flexbox; display: flex; -webkit-box-align: center; -ms-flex-align: center; align-items: center; min-height: calc(100% - (.5rem * 2));';

    this.modalReference = this.modalService.open(content);
    this.modalReference._windowCmptRef.instance._elRef.nativeElement.children[0].setAttribute('style', centerStyle);
```

It is very hacky but works for now.

**Comment by MohamedChaabouni** [comment]
@MichaelaLents worked for me for now but it's very hacky =_= hope they add a the feature of adding custom class to the modal dialog

**Comment by kirilmitev** [comment]
@pkozlowski-opensource  I'm not getting your code (from 00e79c4) when I install 1.0.4 with npm. Why is that?

**Comment by pkozlowski-opensource** [comment]
> I'm not getting your code (from 00e79c4) when I install 1.0.4 with npm. Why is that?

@kirilmitev because it wasn't released yet. We can't release features as part of the bug-fix release as we follow [semver](https://semver.org/).

The commit in question will be part of the next (1.1.0) release.

**Comment by shabbir-dhangot** [comment]
@pkozlowski-opensource when 1.1.0 is planned? Any date ?

**Comment by mungpara** [comment]
use centered option to set vertically 
this.modalService.open(content, {centered: true});

**Comment by danday74** [comment]
what version is centered true available in?

**Comment by mungpara** [comment]
> what version is centered true available in?

current version.

**Comment by maxokorokov** [comment]
@danday74 https://ng-bootstrap.github.io/#/components/modal/api#NgbModalOptions → 1.1.0
