### ISSUE TITLE
Bootstrap 4 List Group component

### ISSUE THREAD

**Issue by varghesep** [ng-bootstrap/ng-bootstrap#1132]
Bootstrap 4 has a component called [list-group](http://v4-alpha.getbootstrap.com/components/list-group/). When will this be available in ng-bootstrap?

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: Angular 2

ng-bootstrap: current version

Bootstrap: Bootstrap 4

**Comment by pkozlowski-opensource** [comment]
I don't see any JS behaviour that would justify wrapping list groups markup as a Angular 2 component. As such I don't think we want to add this to the ng-bootstrap project.

Happy to re-consider if you have API to propose, can justify its existence and willing to craft a PR.

**Comment by varghesep** [comment]
There is JS behavior associated with the List Group. [Highlighting ](http://v4-alpha.getbootstrap.com/components/list-group/#anchors-and-buttons)the selected item is one behavior. Returning the selected item is another useful behavior.

**Comment by Dan203** [comment]
I too would like to see this. The API would be to treat the list group like a multiline list control. Allowing it to automatically set the clicked on item to .active and keep track of the selected item. Could also offer multi-select using Ctrl/Option and Shift logic just an OS control.
