### ISSUE TITLE
ngb-pagination should expose collectionSize on NgbPaginationConfig

### ISSUE THREAD

**Issue by rightisleft** [ng-bootstrap/ng-bootstrap#1137]
Right now the attribute 'collectionSize' is only available through a setter. It should be exposed inside NgbPaginationConfig.

**Comment by pkozlowski-opensource** [comment]
What would be the reason / use-case? Do you have many (most) paginations with the same collection size???

**Comment by pkozlowski-opensource** [comment]
Will close this one for now since I don't see why / how this option would be useful in global config. Happy to re-consider when / if you can come back with more info.
