### ISSUE TITLE
Disabled buttons corner cases

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#1143]
While investigating button-related issues I could spot some corner cases around the `disabled` state handling:
* it is possible to enable an individual button even if the entire group is disabled
* switching group from `disabled` => `enabled` re-enables all buttons, even the ones that are explicitly disabled.

We should probably re-think `disabled` state propagation from a group to individual buttons (keep both buttons and group state and calculate final states based on the 2).

**Comment by alex321** [comment]
@pkozlowski-opensource Thanks #1141, I think I've got this in a few lines. Just need to write 1 or 2 tests and I'll create a PR (probably now but if not then tomorrow).
