### ISSUE TITLE
ng-bootstrap getting started error

### ISSUE THREAD

**Issue by wegnerthorsten** [ng-bootstrap/ng-bootstrap#1146]
I followed the Quickstart from angular 2 and ng-bootstrap and i doesn't changed anything. The browser throw follow exception:
(SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 2.3.0
ng-bootstrap: 1.0.0-alpha.15
Bootstrap: don't include

**Comment by pkozlowski-opensource** [comment]
Please use an appropriate channel for support requests: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help

It is next to impossible to help you wihout having access to your local environement. 404 to our bundle file means that you either not installed the npm package correctly or your web server is not configured properly.

You can check plunkers from our demo page (https://ng-bootstrap.github.io/#/components/), fork them and compare your setup to the one in the demo plunker. Here is an example of a working plunk from our demo page: http://plnkr.co/edit/FPPwxvMSAtUTSb9m4JTf?p=preview

Closing as we are not handling support requests here and there is not enough info to help you in a meaningful way.
