### ISSUE TITLE
Using modal content component as "normal" component

### ISSUE THREAD

**Issue by apreg** [ng-bootstrap/ng-bootstrap#1149]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Link to minimally-working plunker that reproduces the issue: http://plnkr.co/edit/kKniklF5DEbD8DeiW5uI?p=preview (check console ;) )

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.2.4

ng-bootstrap: 1.0.0-alpha.15

Bootstrap: I don't use it :)

**Comment by pkozlowski-opensource** [comment]
`NgbActiveModal` is _only_ available for injection in components opened as a modal window. We can't provide one in non-context modal as... there is no active modal.

If you want to use your component in both modal and non-modal context you can't inject `NgbActiveModal` (but you still might want to pass it as input for example).

Closing as invalid.

**Comment by apreg** [comment]
Could you elaborate more on the solution based on @Input? If I understood correctly I cannot do anything but instantiate the content-component, set `NgbActiveModal` on it then pass it to `modalService.open`.

**Comment by chaiwa-berian** [comment]
ng-bootstrap is great but support is really poor! Struggling with the similar problems but they no good community for support! No gitter, slack, and here no support tickets are allowed! :-1:

**Comment by zwheui** [comment]
@apreg 

I meet the same issue now, I find one solution

```
  @Input() activeModal: NgbActiveModal;

  constructor(
    private injector: Injector,
    // public activeModal: NgbActiveModal,
    ) {
    if (true) {
      this.activeModal = <NgbActiveModal>this.injector.get(NgbActiveModal);
    }
  }

```
