### ISSUE TITLE
[bug] NgbRadio disabled

### ISSUE THREAD

**Issue by tsm91** [ng-bootstrap/ng-bootstrap#1151]
`NgbRadio`'s disabled attribute has no effect https://ng-bootstrap.github.io/#/components/buttons

**Comment by pkozlowski-opensource** [comment]
Please provide a reproduce using plunker: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

**Comment by tsm91** [comment]
Sorry i dont know how to install dependecies inside of plunkr and how to configure System.js because i never use it.

Base on the example: https://ng-bootstrap.github.io/#/components/buttons 

```ts
<div [(ngModel)]="model" ngbRadioGroup name="radioBasic">
  <label class="btn btn-primary">
    <input type="radio" [value]="1"> Left (pre-checked)
  </label>
  <label class="btn btn-primary">
    <input type="radio" value="middle" [disabled]="true"> Middle
  </label>
  <label class="btn btn-primary">
    <input type="radio" [value]="false" disabled> Right
  </label>
</div>
```

**Comment by pkozlowski-opensource** [comment]
You can fork plunker from our demo page. Here is one I can get after 1 click, nothing to configure: http://plnkr.co/edit/LEA5w0v8zLQItjLzL33g?p=preview

**Comment by tsm91** [comment]
> Please provide a reproduce using plunker: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

Woah, sorry i didnt realized they are all in plunker and because i didnt read the docs.

The issue is on my side, it works fine: http://plnkr.co/edit/dLHubsGdDhgOcJrfIcOW

**Comment by pkozlowski-opensource** [comment]
This is _precisely_ why we insist on having a minimal plunker with the reproduce scenario :-)

Glad it works for you now.

**Comment by tsm91** [comment]
Yes i understand now :dancer: 

I copied and pasted the plunkr example with reactive forms and for some reason the label never gets the `disabled` class https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/buttons/radio.ts#L58-L60 in my local dev environment

ss: http://i.imgur.com/Ny0tBFJ.png 

even if i put the `disabled` class manually on the label it gets removed

double checked and use the newest versions from both `bootstrap` and `ng-bootstrap`

anyways, will try to figure out what is going on

**Comment by alex321** [comment]
@tsm Double check that you have the latest version as there have been a few bug fixes related to radio buttons disabled state recently.

**Comment by tsm91** [comment]
@alex321 bingo! :dancer: I was using `alpha.14` and there is an `alpha.15`!

https://ng-bootstrap.github.io/#/home shows the correct version
http://plnkr.co/edit/LEA5w0v8zLQItjLzL33g?p=preview uses the correct version
however https://www.npmjs.com/package/@ng-bootstrap/ng-bootstrap shows `1.0.0-alpha.14 is the latest of 15 releases`

It is weird because there has been an `alpha.15` release on npm, otherwise i could not install it, but the npm site shows the current version is `alpha.14`.

**Comment by pkozlowski-opensource** [comment]
@tsm91 not sure what is going on with the npm website but it is clearly wrong. Running `npm info '@ng-bootstrap/ng-bootstrap'` returns proper results (alpha.15 is well visible as a release and marked as the latest)....

**Comment by tbfx** [comment]
Radios seem not to write back values into model using latest Angular. I'd happily provide a plunker, if somebody could provide a template using webpack with -aot.
