### ISSUE TITLE
Datepicker: Doesn't work with dynamic forms

### ISSUE THREAD

**Issue by mseitz6** [ng-bootstrap/ng-bootstrap#1152]
I am trying to dynamically add your datepicker to a page but the functionality breaks when there is more than one datepicker on the page. This is because the template id cannot be dynamically set in Angular2. To combat this I tried using @ViewChild but I was not able to import the **NgbDatepicker** or **NgbInputDatepicker** directives. Do you have an idea about how I can dynamically add more than one of your datepickers on a page?

Plunker: https://plnkr.co/edit/8KnKICJdDQtSEqkjIEUy?p=preview

**Comment by pkozlowski-opensource** [comment]
> I am trying to dynamically add your datepicker 

What do you mean by "dynamically" here? Could you please modify your plunker to reflect what you are trying to do?

**Comment by prasadnarayana1996** [comment]
I need an answer for the above Question
Like in my case I'm getting array of  data like temp=[date1,date2]
I want to load the date picker by looping the array, and I want the toggle option to work for both date1 and  date2.
For that, I need 2 template variables like #d and #d1 but I couldn't do that dynamically.
Please help me with this.
