### ISSUE TITLE
Table's updating after closing modal window in Angular2

### ISSUE THREAD

**Issue by alan345** [ng-bootstrap/ng-bootstrap#1160]
Angular:2.4.1
ng-bootstrap:1.0.0-alpha.14

Hello, I am using a modal (class NgbdModalContent) to insert data in a table (class CompanieComponent). Once data is created (thanks to the modal), I close the modal. Then how can I refresh the initial table?

If I add the initial component (CompanieComponent) in the constructor of the modal component (NgbdModalContent), I get an error. (circular error)
<img width="733" alt="screen shot 2016-12-23 at 5 00 03 pm" src="https://cloud.githubusercontent.com/assets/15246526/21464440/4f973998-c931-11e6-962c-301ce224a16c.png">

Thanks for your help

```
export class NgbdModalContent {
   constructor(
      private companieComponent: CompanieComponent, // Error when I inject the initial component
   ) {}
   save() {
    // save Data
    this.companieComponent.refreshTable(); // Refresh data after new data saved, but it's not working
   }
}


export class CompanieComponent {
   onOpenModal(){
      const modalRef = this.modalService.open(NgbdModalContent);
   }

   refreshTable() {
      // refresh Table
   }

}
```

**Comment by tjaartvanderWalt** [comment]
@alan345 can you create a minimal plunker to replicate your issue? You can fork [this plunker](https://ng-bootstrap.github.io/app/components/modal/demos/basic/plnkr.html) to get you started.

**Comment by alan345** [comment]
Thanks @tjaartvanderWalt for your help. Please find plnkr.
I have commented rows 16&28 in file modal-basic.ts
http://plnkr.co/edit/JqplbTuk1FYfslc3dZy0?p=preview

The question is: How can reach function "refreshTable()" in the modal?

Thanks Again

**Comment by jnizet** [comment]
Instead of calling `c('Close click')`, call `c(theDataCreatedByTheModal)`.

In the parent component, use 

    this.modalService.open(content).result.then((theDataCreatedByTheModal) => {
      this.refreshData(theDataCreatedInTheModal);
    }

**Comment by alan345** [comment]
Thanks a lot @jnizet ! I close this issue!
