### ISSUE TITLE
[ngbTabset] add option to hide inactive tabs instead of destroying them

### ISSUE THREAD

**Issue by Eugeny** [ng-bootstrap/ng-bootstrap#1161]
Feature proposal: add a NgbTabset subclass where the template would bind to `visibility` instead of `*ngIf` so that inactive tab contents won't get destroyed when switching.

This makes sense for tabs that contain components which are expensive to re-instantiate or contain state that gets lost, for example a video player.

**Comment by mattlewis92** [comment]
Cont from #1167 - sorry about the duplicate!

@pkozlowski-opensource how come you're on the fence about this feature request? Are there any better solutions you can see to allow routing in tabs?

**Comment by thbt** [comment]
It also makes sense regarding accessibility, according to the WAI-ARIA spec : 
> When a tabbed interface is initialized, one tab panel is displayed and its associated tab is styled to indicate that it is active. When the user activates one of the other tab elements, the previously displayed tab panel is hidden, the tab panel associated with the activated tab becomes visible, and the tab is considered "active".

**Comment by jw61** [comment]
Definite up-vote for this feature! I have a requirement for users to enter different types of data on different tabs. If they change tab they lose everything they've entered, but I can't force the user to correct any validation errors before they're allowed to change tabs.

**Comment by Thommas** [comment]
We also need this feature.

How can we help ?

**Comment by jiayihu** [comment]
I'd like to make a PR if there is confirm that this behaviour is something acceptable for the team of `ng-bootstrap`. Destroying components/DOM is causing some issues whenever the content of the tab/panel is something not trivial, such as a form, because you loose the state.

**Comment by AlexKhymenko** [comment]
Super useful. I have use case when you should add green or red circle depending if form inside of tab valid or not. Can't do it on initial load if there is no component :-)
