### ISSUE TITLE
Carousel Cycle Interval alive

### ISSUE THREAD

**Issue by aralroca** [ng-bootstrap/ng-bootstrap#1163]
Is not an issue, is a doubt.

In Carousel. I want that the cycle interval will alive if the mouse is entered... How can I implement this 😅  ?

Thank you so much! 🙂

**Comment by pkozlowski-opensource** [comment]
We don't have such option currently but I can mark it as a feature request.

**Comment by aralroca** [comment]
Oh cool!  Is it possible to contribute via PR? Maybe I can help 🙂

**Comment by pkozlowski-opensource** [comment]
@aralroca PRs are always welcomed provided that those contain tests, documentation update etc. Thnx!

**Comment by wesleycho** [comment]
Question about this - how should this be implemented? One would have to have a feature flag I think since this would be a breaking change. Is there any other ways we could implement this that would minimize the amount of configuration needed?

**Comment by pkozlowski-opensource** [comment]
Yep, this would have to be a new option / input.

**Comment by jodhman** [comment]
Is there no temporary fix?
I can't seem to find a viable option.

**Comment by DheerajVislavath** [comment]
Any temporary fix to disable mouse events ?
