### ISSUE TITLE
Rating control starts

### ISSUE THREAD

**Issue by rodneyjoyce** [ng-bootstrap/ng-bootstrap#1164]
Hello,
WRT the Rating Control:  There seems to be a style issue on Android devices (Chrome browser).

It works fine on iOS browsers and desktop browers.

### Bug description:
Rated stars are not styled

You can see the problem here (screenshot taken on Android Galaxy S6 device)
http://screencast.com/t/cCQu1sbCh

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.2.1
ng-bootstrap:  ^1.0.0-alpha.15
Bootstrap: 4.0.0-alpha.5

**Comment by pkozlowski-opensource** [comment]
I'm sorry but there is not enough info here to help. Please provide adequate reproduce scenario as requested in the issue template: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug - otherwise this one is not actionable and will be closed.

**Comment by pkozlowski-opensource** [comment]
Going to close this one as we don't have sufficient info to proceed.
