### ISSUE TITLE
[Dropdowns] Split button dropdowns

### ISSUE THREAD

**Issue by richardsengers** [ng-bootstrap/ng-bootstrap#1165]
Any plans for a split button dropdown?
http://v4-alpha.getbootstrap.com/components/dropdowns/#split-button-dropdowns

Kind regards

**Comment by pkozlowski-opensource** [comment]
There is nothing particular to implement for this on our side, split buttons work out of the box with the current markup and directives: http://plnkr.co/edit/0ixE0ofp0t3CcEwQvRdd?p=preview

**Comment by richardsengers** [comment]
Thank you very much for the example. 
I don't know what I did wrong then. I thought I've tried it, but was getting 2 buttons instead of a split button. But  your example works out of the box! Thanks
