### ISSUE TITLE
Open property does not work when creating dynamic dropdowns.

### ISSUE THREAD

**Issue by chawderartin** [ng-bootstrap/ng-bootstrap#1169]
### Link to minimally-working plunker that reproduces the issue: 
http://plnkr.co/edit/WfzZ8G4mfBnuxNxh04zG

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2xxx

ng-bootstrap: v1.0.0-alpha.15

Bootstrap: v4.0.0-alpha.5

**Comment by pkozlowski-opensource** [comment]
`[open]` works as expected - it is just that a newly created dropdown is imediatelly closeed by a bubbling `click` event. You can either stop propagation of it (http://plnkr.co/edit/gK9rUxsGEKAtUHcu6mY6?p=preview) or use the `[autoClose]="false"` option.

Closing as a support request.

**Comment by chawderartin** [comment]
Thank s alot for fast response and good service!!
