### ISSUE TITLE
Dropdown menu cropped and not automatically adjusted to left/right 

### ISSUE THREAD

**Issue by sinedied** [ng-bootstrap/ng-bootstrap#1171]
### Bug description:

When using the predecessor `ui-bootstrap` dropdown component, the dropdown menu would automatically switch to being on the left or right if needed to avoid being cropped.

This is not the case with the current `ng-bootstrap` dropdown component, as seen in the provided plunker: when the dropdown is floated the right, the menu is cropped and goes off-screen instead of being switch to the right.

This is problematic in responsive scenario, like when using a right-floated dropdown in a responsive navbar with a collapse: the dropdown menu should be attached to the right when in "desktop mode" and the dropdown is floated to the right, and it should be on the left when the dropdown is not floated (in the collapsed menu). The scenario was working without additional code in Bootstrap 3 with ui-bootstrap.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/Jb2MzMSjOXt2M6UJkwq9?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.4.1

ng-bootstrap: 1.0.0-alpha.15

Bootstrap: 4.0.0-alpha.5

**Comment by nixallover** [comment]
This might be related to an issue that I'm seeing as well. I just updated from ng-bootstrap 1.0.0-alpha.13 to 1.0.0-alpha.18 and it seems that the dropdown is no longer visible, which also seems like it's the case in this plunkr.

**Comment by salacis** [comment]
Thats still a thing in alpha 6.

**Comment by pkozlowski-opensource** [comment]
This will be fixed by #1814
