### ISSUE TITLE
When I try to install your package. Can you help me?

### ISSUE THREAD

**Issue by stojankukrika** [ng-bootstrap/ng-bootstrap#1175]
ERROR in D:\xampp\htdocs\anvel\node_modules@ng-bootstrap\ng-bootstrap\buttons\radio.d.ts
(11,14): error TS1005: '=' expected.

ERROR in D:\xampp\htdocs\anvel\node_modules@ng-bootstrap\ng-bootstrap\buttons\radio.d.ts
(11,22): error TS1005: ';' expected.

ERROR in D:\xampp\htdocs\anvel\node_modules@ng-bootstrap\ng-bootstrap\buttons\radio.d.ts
(11,14): error TS2304: Cannot find name 'disabled'.

**Comment by pkozlowski-opensource** [comment]
@stojankukrika it is TypeScript version issue. It looks like you are using TS 1.8 and e24f4c611ea9396358c7c7ec89d76c2ee1a061d8 introduced a breaking change that requires TS 2.0...

We are going to fix it and restore TS 1.8 compatibility but till it is done you've got 2 options:
* upgrade to TS 2.0.x
* downgrade ng-bootstrap package version to 1.0.0-alpha.15
