### ISSUE TITLE
Support for Bootstrap alpha 6. Dropdown now open with class `Show` instead of `Open`

### ISSUE THREAD

**Issue by ASHFAQPATWARI** [ng-bootstrap/ng-bootstrap#1180]
### Bug description:

Dropdown does not work with bootstrap v4 - alpha 6.

`Open` class on dropdown needs to changed to `show`

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/RpzceTvZq90NJ9zN7ZWp?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.4.1

ng-bootstrap: alpha-16

Bootstrap: v4 - alpha 6

**Comment by ASHFAQPATWARI** [comment]
@jnizet Modals are also not working for the same reason.

**Comment by pkozlowski-opensource** [comment]
This will be solved as part of #1178
