### ISSUE TITLE
Typeahead not testable using protractor/selenium

### ISSUE THREAD

**Issue by thetrav** [ng-bootstrap/ng-bootstrap#1201]
### Bug description:
```
element(by.id('search-input')).sendKeys("ex");
```
watching the browser (chrome) the above does not display suggestions, and does not update the model.

attempting to work around with
```
browser.executeScript("$('.search-input').val('"+example+"');");
```
also fails, as the angular model is not updated.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.2.4

ng-bootstrap: 1.0.0-alpha.15

Bootstrap: 3.3.6

chomedriver: 2.26 

chrome: 55.0.2883.95

protractor: 4.0.14

**Comment by wesleycho** [comment]
I have verified that this is not a bug - here is a simple reproduction that it works as expected: https://github.com/wesleycho/typeahead-protractor

Closing as a non-issue.
