### ISSUE TITLE
Going fast over rating shows a different result than selected

### ISSUE THREAD

**Issue by natcohen** [ng-bootstrap/ng-bootstrap#1204]
### Bug description:
Going over a rating very quickly without clicking turn on/off starts that are not selected

### Link to minimally-working plunker that reproduces the issue:

![2017-01-10_11-40-02](https://cloud.githubusercontent.com/assets/7813574/21803254/9aa09320-d729-11e6-8ac9-6f67ad0c8a98.gif)

### Version of Angular, ng-bootstrap, and Bootstrap:

Tested on the official website, using Chrome 55 on Windows 10

EDIT: It seems to be related to the size of the stars... I couldn't reproduce the problem with the default black small stars

**Comment by maxokorokov** [comment]
Confirm in Chrome 55 on MacOS
Can't reproduce in FF, Safari on MacOS and IE11 in Win8.1

**Comment by danielpriplata** [comment]
Hello,

I can reproduce this in IE11, FF 50.1.0 and Chrome 55 on Win 7.

**Comment by emvau** [comment]
Same here. Chrome 56.0.2924.87 (64-bit) Win10.
