### ISSUE TITLE
Modal Example on Website Missing ngbModalContainer

### ISSUE THREAD

**Issue by jehugaleahsa** [ng-bootstrap/ng-bootstrap#1209]
### Bug description:

Not sure if this is where I should post this. I noticed your modal examples on the website give you a "heads up" to include the **ngbModalContainer** attribute on the outer template. However, none of the example HTML actually includes this attribute.

Thought I'd let someone know.

**Comment by pkozlowski-opensource** [comment]
We can't include it into example fragments as there can be only one ngbModalContainer per page. In any case a forked plunker has it.

The best part though is that we are going to remove the need for the ngbModalContainer _very_ soon (that will require migration to Angular 2.4.x) so I'm going to close this issue as:
* we can't technically do it today
* container is going away

Thnx for the head ups though!
