### ISSUE TITLE
Some modules are missing in version 1.0.0-alpha.18

### ISSUE THREAD

**Issue by david-bulte** [ng-bootstrap/ng-bootstrap#1218]
### Bug description:

After upgrading to version 1.0.0-alpha.18 my build stopped working and I noticed some of the modules are missing, i.e. accordeon, modal, timepicker

Here's my build output:

ERROR in ./~/@ng-bootstrap/ng-bootstrap/accordion/accordion.module.js
Module build failed: Error: ENOENT: no such file or directory, open 'c:\system9\sourcesWEB\MYNEXUZ\MyNexuz\node_modules\
@ng-bootstrap\ng-bootstrap\accordion\accordion.module.js'
    at Error (native)
 @ ./~/@ng-bootstrap/ng-bootstrap/index.js 2:0-66 18:0-142
 @ ./src/app/shared/shared.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/@ng-bootstrap/ng-bootstrap/buttons/radio.module.js
Module build failed: Error: ENOENT: no such file or directory, open 'c:\system9\sourcesWEB\MYNEXUZ\MyNexuz\node_modules\
@ng-bootstrap\ng-bootstrap\buttons\radio.module.js'
    at Error (native)
 @ ./~/@ng-bootstrap/ng-bootstrap/index.js 4:0-58 20:0-73
 @ ./src/app/shared/shared.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/@ng-bootstrap/ng-bootstrap/typeahead/highlight.js
Module build failed: Error: ENOENT: no such file or directory, open 'c:\system9\sourcesWEB\MYNEXUZ\MyNexuz\node_modules\
@ng-bootstrap\ng-bootstrap\typeahead\highlight.js'
    at Error (native)
 @ ./~/@ng-bootstrap/ng-bootstrap/typeahead/typeahead.module.js 3:0-43 7:0-43
 @ ./~/@ng-bootstrap/ng-bootstrap/index.js
 @ ./src/app/shared/shared.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.4.0

ng-bootstrap: version 1.0.0-alpha.18

Bootstrap: alpha-6

**Comment by pkozlowski-opensource** [comment]
The mentioned files are part of the npm distribution and you are the first user reporting a similar problem even if the release was out for more than a week. As such I would suspect a corrupted  npm download or build issue.

If you can put together a _minimal_ reproduce scenario (GitHub repo) we might look into it but for now I would suspsect build issue on your side.

**Comment by david-bulte** [comment]
It's working now and I haven't changed a thing. Must have been something npm related then? Sorry...

**Comment by pkozlowski-opensource** [comment]
Thnx for coming back with the info.
