### ISSUE TITLE
lazy loading is not working with entryComponents

### ISSUE THREAD

**Issue by MickL** [ng-bootstrap/ng-bootstrap#1220]
### Bug description:
Following "Components as content" [demo](https://ng-bootstrap.github.io/#/components/modal) for modals is working fine. But if the component is in a submodule lazy loaded it is not working.

It says:
`No component factory found for NgbdModalContent. Did you add it to @NgModule.entryComponents?`

If the module is loaded in root AppModule its working fine.

I found a workaround:

1. Import `NgbModule.forRoot()` should be in the loaded submodule, not in root module
2. `<template ngbModalContainer></template>` should also be part of the submodule. Otherwise it says `Error: No provider for NgbModal!`

The problem is that i need only one instance of NgbModule inside of my root AppModule. Also the template should be part of root `app.component.html`. But then the factory is not found in the loaded submodule.

Additonally i found similiar issues at angular material2. They solved it by getting rid of forRoot() import (`NgbModule.forRoot()`). Im not sure if this helps.

Issues:
https://github.com/angular/material2/issues/2517
https://github.com/angular/material2/issues/1765

### Version of Angular, ng-bootstrap, and Bootstrap:
latest

**Comment by pkozlowski-opensource** [comment]
I believe that the latest version should work correctly with lazy loaded modules. Please provide a minimal reproduce in plunker as requested in the issue template: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

Without a reproduce scenario this issue is not actionable.

**Comment by MickL** [comment]
Here is the Plunker.

Inside a module which is imported its working fine:
http://plnkr.co/edit/YaJFCIAvqPNcG9TacVDY

But if the module is loaded lazy it isnt working (No component factory found):
http://plnkr.co/edit/Q7UPR8KrX4lH4xJqfmWa

**Comment by pkozlowski-opensource** [comment]
You need to also import `NgbModule` in your lazy loaded module as described in the README / getting started doc: https://github.com/ng-bootstrap/ng-bootstrap#installation.

Here is a working plunker: http://plnkr.co/edit/brAsh56DzVpVEMFK0hrP?p=preview 

Closing as works as expected.

**Comment by MickL** [comment]
Thanks so much!
