### ISSUE TITLE
Datepicker popup: invalid maxDate will not invalidate form

### ISSUE THREAD

**Issue by readme42** [ng-bootstrap/ng-bootstrap#1222]
### Bug description:
Datepicker popup: If a date after maxDate is entered manually, the form will be valid by mistake. 

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/5sb1RN6AoJRbdiV32nke?p=preview

### Version of ng-bootstrap and Bootstrap:

ng-bootstrap: ng-bootstrap@1.0.0-alpha.18
Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
Woooooops, you are right, we've missed this one! Should be fixed pretty soon, thnx for reporting.

**Comment by readme42** [comment]
Great to hear this :) 

Haven't checked it, but maybe minDate is also affected.

**Comment by pkozlowski-opensource** [comment]
Yes, 'minDate' and invalid dates are affected as well.

**Comment by pkozlowski-opensource** [comment]
I did a bit of poking around and what we are missing today is proper implementation of the `Validator` interface. There are few corner cases I need to test before opening a PR so a fix will take a couple more days.

**Comment by readme42** [comment]
No Problem. We are migrating from ui-bootstrap which contains the same bug ;)

**Comment by pkozlowski-opensource** [comment]
For anyone tracking this issue, here is a design doc for the validation of datepickers: https://docs.google.com/document/d/1NmyKQjpmva62-Y8A-nfzJjD3p09fb-Q-UtS39HzFjTo/edit?usp=sharing

Feel free to comment / provide your input.

**Comment by dmytroyarmak** [comment]
@pkozlowski-opensource I've added some comments to the design doc
