### ISSUE TITLE
Wikipedia Example Typeahead - EXCEPTION: No provider for ConnectionBackend!

### ISSUE THREAD

**Issue by choopage** [ng-bootstrap/ng-bootstrap#1228]
### Bug description: EXCEPTION: No provider for ConnectionBackend!
![screen shot 2017-01-19 at 2 13 55 pm](https://cloud.githubusercontent.com/assets/6467136/22095733/2affcef2-de52-11e6-8ba0-fa988c17eee8.png)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.3.1

ng-bootstrap: 1.0.0-alpha.18

Bootstrap:

**Comment by choopage** [comment]
I encountered this bug with the following steps briefly:

1. Provisioned a new angular-cli project

2. Installed ng-bootstrap from npm

3. Followed the example for Wikipedia Search https://ng-bootstrap.github.io/#/components/typeahead

I did nothing more than the above. And I get this error.

**Comment by pkozlowski-opensource** [comment]
You seem to be missing import for the `JsonpModule` in your application module. Here is a working plunker forked from our demo page (https://ng-bootstrap.github.io/#/components/typeahead): http://plnkr.co/edit/KS51D0LeSaUykEmq7YR2?p=preview - you can compare setup of this plunker with your application.

Closing as this seems to be a support request and we are not handling those here: https://github.com/ng-bootstrap/ng-bootstrap#getting-help
