### ISSUE TITLE
Invalid Date and Model on datepicker-popup

### ISSUE THREAD

**Issue by akab** [ng-bootstrap/ng-bootstrap#1230]
**versions**: Angular2, Bootstrap4, ng-bootstrap1.0(alpha18)
Hi,
I'm currently using the datepicker in my project and I've discovered the following two issues regarding the date inserted in the input box and the model saved.
The plunker the is the one in the datepicker docs:
https://ng-bootstrap.github.io/app/components/datepicker/demos/popup/plnkr.html

**1.**  There is no validation on the inserted date, as demonstrated also in the following screenshot
<img width="579" alt="screen shot 2017-01-19 at 14 30 21" src="https://cloud.githubusercontent.com/assets/4540276/22108583/1e53fe10-de54-11e6-80bc-a70fae7afcf6.png">

**2.** When the number of digits of the inserted day/month/day exceeds its limit the number is castrated to the last two digits, but the model is saved anyway:
<img width="580" alt="screen shot 2017-01-19 at 14 40 26" src="https://cloud.githubusercontent.com/assets/4540276/22108885/87dcb34e-de55-11e6-8a9f-9b0139f329fc.png">
Not only, once the year is "broken" the only way to reset the date correctly is to clear the input field.
I'm aware of maxDate input, but has you can see from the picture the year exceeds the default value of 10 year from now.

Please let me know,
Thank you in advance

**Comment by pkozlowski-opensource** [comment]
This is similar to #1222 and #1225 - the 2 mentioned issues are touching the validation story. The good news is that we are just working on proper validation support in a datepicker.

I'm going to keep this issue open so the mentioned use-cases are part of the default validators.

**Comment by akab** [comment]
ok, thank you!

**Comment by pkozlowski-opensource** [comment]
For anyone tracking this issue, here is a design doc for the validation of datepickers: https://docs.google.com/document/d/1NmyKQjpmva62-Y8A-nfzJjD3p09fb-Q-UtS39HzFjTo/edit?usp=sharing

Feel free to comment / provide your input.
