### ISSUE TITLE
Feature: Add input to ngbRadioGroup for allowing vertical group

### ISSUE THREAD

**Issue by adamk33n3r** [ng-bootstrap/ng-bootstrap#1231]
It would be nice to specify whether we want it to be a `.btn-group` or a `btn-vertical-group` :smile:

**Comment by pkozlowski-opensource** [comment]
Why not. PRs welcomed - this should be rather simple change.

**Comment by dmytroyarmak** [comment]
@pkozlowski-opensource What do you think would be better?
1. Ask developer to specify class on [ngbRadioGroup] manually (don't set host's class on ngbRadioGroup element at all)
2a. Add "orientation" parameter that should be "horizontal" (default) or "vertical"
2b. Add "vertical" parameter that should be true or false (default)

**Comment by pkozlowski-opensource** [comment]
@dmytroyarmak my preference would go to (1) or (2a). Not sure which of the 2 is better. 

Here are pros / cons for (1):
* (+) don't need new API
* (+) doesn't use binding 
* (-) requires more typing for the typical case
* (-) breaking change (we don't care too much as this is still alpha)

If you take (2a) pros / cons are pretty much reversed as compared to (1)....

What would be your pick?

**Comment by dmytroyarmak** [comment]
@pkozlowski-opensource 
I think it's better to do (2a) to not introduce breaking change

**Comment by pkozlowski-opensource** [comment]
> I think it's better to do (2a) to not introduce breaking change

@dmytroyarmak let's do it! Fancy putting together a PR?

**Comment by dmytroyarmak** [comment]
@pkozlowski-opensource yeah, I'll do a PR later today.

**Comment by pkozlowski-opensource** [comment]
Update: I've decided to rather go with the option (1) from https://github.com/ng-bootstrap/ng-bootstrap/issues/1231#issuecomment-274074412

In addition to the mentioned "pros" it will keep radio and checkboxes implementation consistent.
