### ISSUE TITLE
Unnecessary ellipsis between sibling page numbers for rotating pagination

### ISSUE THREAD

**Issue by dmytroyarmak** [ng-bootstrap/ng-bootstrap#1232]
### Bug description:

In some cases, when using rotation pagination component renders unnecessary ellipsis between sibling page numbers.
For example for:
- page numbers: 7
- current page: 5
- max pages: 3

The result will be (incorrect):
```
['« Previous', '1', '-...', '4', '+5', '6', '-...',  '7', '» Next']
```
instead of (correct)
```
['« Previous', '1', '-...', '4', '+5', '6', '7', '» Next']
```

The same problem happens on the 3rd page.

### Link to minimally-working plunker that reproduces the issue:

[http://plnkr.co/edit/Jr28Ft?p=preview](http://plnkr.co/edit/Jr28Ft?p=preview)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.0.0

ng-bootstrap: 1.0.0-alpha.18

Bootstrap: 4.0.0-alpha.6

**Comment by dmytroyarmak** [comment]
I have a fix already that I'm going to create a PR for.

**Comment by pkozlowski-opensource** [comment]
Sounds like #1166. I had a brief look at your PR at it seems fine. Will do a proper review & merge tomorrow.

Thnx for stepping in and contributing - much appreciated!

**Comment by pkozlowski-opensource** [comment]
Merged, thnx!
