### ISSUE TITLE
Scrolling missing from opening second Modal

### ISSUE THREAD

**Issue by SachinSharmaEarthport** [ng-bootstrap/ng-bootstrap#1236]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

This may have been reported before, so if so sorry about that.  I am using modals in my application with NgbModal.  I click on a button to open a modal and that is fine.  On this modal I have a button which will open another modal which is large and needs to be scrolled.  When I open this second modal I am unable to scroll down it and I can see the scrollbar is missing.  See the screenshot below.

![image](https://cloud.githubusercontent.com/assets/24301036/22149207/6c88127c-df0a-11e6-9434-d16134e4a424.png)

I am using the following code to open this second modal:

```
            <edit-rule-modal-component [selectedStatementRule]="rule" [includeButtonIcon]="false"
            (click)="activeModal.close('Close click')"></edit-rule-modal-component>
```

As shown in the code the active modal is closed.  If I remove this click event so the active modal is not closed then i do not get this issue and the scrollbars appear as expected as shown below.

![image](https://cloud.githubusercontent.com/assets/24301036/22149496/06889f9e-df0c-11e6-9cae-359c7838df82.png)

Is there a fix or workaround to this please?

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:2.4.1

ng-bootstrap: 1.0.0-alpha.18

Bootstrap: 4.0.0-alpha.5

**Comment by pkozlowski-opensource** [comment]
* you are using incompatible Bootstrap and ng-bootstrap versions, see: 
* you didn't provide a minimal plunk even if clearly requested in the issue template
* you are asking a support question even if the issue template clearly redirect support questions to dedicated support channels:

> Please remember, the issues forum is NOT for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

Closing given all the above. If you still believe that there is a bug in ng-bootstrap please open a new issue following our submission guidelines: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug
