### ISSUE TITLE
DropdownToggle should prevent default event

### ISSUE THREAD

**Issue by fredgate** [ng-bootstrap/ng-bootstrap#1241]
### Bug description:
In an application using angular 2 with the router, the dropdown toggle directive causes a page reload if it is used on a HTML `a` element with a `href="#"`.
It would be nice if the ngbDropdownToggle could prevent the default event.

Here is a plunker that reproduces the problem :
http://plnkr.co/edit/lE6Teh6W2hKtPFSUf2xa?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 2
ng-bootstrap: 1.0.0 alpha 18
Bootstrap: 4 alpha 6

**Comment by dmytroyarmak** [comment]
Looks like it's related to issue  #142

**Comment by pkozlowski-opensource** [comment]
> Looks like it's related to issue #142

Yes, it is. In this particular example a dropdown works like a menu and semantically it is _not_ a link but rather a button (and for sure not an anchor with an empty `href`). As you are creating a menu you should simply use `<button>` elements, especially that Bootstrap 4 fully supports it: http://v4-alpha.getbootstrap.com/components/dropdowns/#menu-items

Also note that `<button>` elements are our markup of choice on the demo page: https://ng-bootstrap.github.io/#/components/dropdown

Closing as a support request / won't fix.

**Comment by raghav-khunger** [comment]
I gave the possible solution which can be used on anchor tag for preventing default:
https://stackoverflow.com/a/58953392/148657
