### ISSUE TITLE
Accessibility review and corrections

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#1248]
Let's start reviewing and improving our accessibility story. Here is a (very rough) list of tasks:
* [x] compare our markup with the Bootstrap (exact HTML structure, aria attributes etc.)
* [x] review focus management
* [x] add keyboard navigation
* [x] test with popular browser + screen reader combo (ideally with users using screen readers on a daily basis)

**Comment by pkozlowski-opensource** [comment]
As a reference here is a good entry for accessible tooltips: https://sarasoueidan.com/blog/accessible-tooltips/

**Comment by thbt** [comment]
I wrote a first draft of the current accessibility issues in ng-bootstrap, you can find it here : [google doc](https://docs.google.com/document/d/1IXnWLJE14zymBb2hy28X6yk9BOyt80N4jMhQ9A6qfUs)
Don't hesitate to comment or edit it !

**Comment by jfinci1** [comment]
@pkozlowski-opensource Seems like that link no longer works.

**Comment by pkozlowski-opensource** [comment]
@jfinci1 the doc link works for me perfectly fine, please try again.

**Comment by pkozlowski-opensource** [comment]
@thbt did the awesome work on the initial pass on the accessibility. If you inspect the doc linked above you will notice that all the components were thoroughly reviewed (comparing our markup with the one proposed by Bootstrap), pages tested with different screen readers, audits run etc. As the result of this first pass @thbt fixed many issues both in widgets implementations and on our demo page. This alone represents several weeks of work and ~30 different commits! Thank you!

But the work done here goes beyond fixing issues in this library - we've opened many upstream issues, both to the Bootstrap team (see: https://github.com/twbs/bootstrap/issues/21867, https://github.com/twbs/bootstrap/issues/22009, https://github.com/twbs/bootstrap/issues/22040, https://github.com/twbs/bootstrap/issues/22284) and the NVDA screen reader (see: https://github.com/nvaccess/nvda/issues/6906, https://github.com/nvaccess/nvda/issues/7072). There are still few open issues left on the upstream projects and we are going to follow up with both teams.

Of course there is always more work to be done and we are going to track the remaining issues using the [accessibility label](https://github.com/ng-bootstrap/ng-bootstrap/issues?q=is%3Aissue+is%3Aopen+label%3A%22type%3A+accessibility%22). 

Despite all this work we know that accessibility is hard and we are eager to learn from anyone that can provide feedback on the current state of the accessibility support. We would be especially grateful for feedback from people using screen readers on the daily basic and / or accessibility experts.
