### ISSUE TITLE
Tooltip doesn't go away on disabled button

### ISSUE THREAD

**Issue by irshadmalek11** [ng-bootstrap/ng-bootstrap#1250]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Link to minimally-working plunker that reproduces the issue:
This is minimal plnkr where it just shows tooltip when button is disabled and if you take mouse out of the button
http://plnkr.co/edit/61i3VijZULrovza8bhSP

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.4.1

ng-bootstrap: 1.0.0-alpha.18

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
Mouse events don't fire on disabled elements (ex.: http://stackoverflow.com/questions/3100319/event-on-a-disabled-input) so we can't do anything on the library side to detect such situation. But you can always close a tooltip manually if you've got a very specific use-case as in your plunk: http://plnkr.co/edit/75P69nN39WIXfCHUEBRJ?p=preview 

Closing as a support request.

**Comment by maxkorz** [comment]
@pkozlowski-opensource it is possible to detect attribute change with [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver).

Take a look at this repo: https://stackblitz.com/edit/angular-fg6f9y

You can implement MutationObserver in the ngbTooltip and hide tooltip when attribute `disabled` changes to `true`.
