### ISSUE TITLE
NgbTypeAhead - HTML required parameter issue

### ISSUE THREAD

**Issue by sanjayjha** [ng-bootstrap/ng-bootstrap#1255]
### Bug description:
I am using required parameter with ngbtypeahead in the following way:
  <input type="text"  minlength="5"
                           required ngControl="sanction.hospital"
                           name="sanctionHospital" class="ng-invalid"
                           (focus)="onFocus($event, idx)"
                           [(ngModel)]="sanction.hospital"
                           [ngbTypeahead]="searchHospital"
                           [readonly]="!editing || (idx != selectedIndex)"
                           [resultFormatter]="hospitalFormatter" [inputFormatter]="hospitalFormatter"
                           />

So when I load form this text don't honor required / minlength parameter. As I type something then it start showing red border which I have in my css. 

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
Angular 2.4.0.
ng-bootstrap:
ng-bootstrap ^1.0.0-alpha.18
Bootstrap:
Bootstrap 3.3.6

**Comment by pkozlowski-opensource** [comment]
Please follow our issue submission guidelines (https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug). If this is a support question please ask it using a dedicated channel: https://github.com/ng-bootstrap/ng-bootstrap#getting-help


Without a minimal reproduce scenario in a plunker this issue is not actionable and will be closed.

**Comment by sanjayjha** [comment]
I will provide Plunker. But do we have any minlength property for typeahead?

**Comment by pkozlowski-opensource** [comment]
> But do we have any minlength property for typeahead?

Nope, as it wouldn't make sense since:
* you are in charge of constructing the observable chain so you can determine when the input matches;
* what would minlength mean with the variety of results that could be returned from typeahead? What if it returns an object?

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't heard back / don't have reproduce scenario.
