### ISSUE TITLE
Datepicker: Should attempt to position itself such that it is entirely visible within the viewport

### ISSUE THREAD

**Issue by jfinci1** [ng-bootstrap/ng-bootstrap#1257]
This is an example of a date input field at the bottom of the viewport and the date picker dropdown cutting off almost in its entirety. (also please do ignore the non-default border on the month and year dropdown- I have some conflicting css I need to fix :) )

![image](https://cloud.githubusercontent.com/assets/5992006/22302116/6eeb5124-e2fb-11e6-99c5-f0e72425387e.png)

Would we be interested in having the dropdown attempt to determine where the best location to render would be? (Top, bottom, left, right, etc)

**Comment by stephanoapiolaza** [comment]
anyone has fixed?
