### ISSUE TITLE
Tooltips not positioned properly when running hybrid ng1/ng2 app

### ISSUE THREAD

**Issue by emise** [ng-bootstrap/ng-bootstrap#1263]
### Bug description:
As can be seen from the plunker, tooltips are not attached at the right place. I didn't run into this problem while running a pure Angular 2 app, only when it's a hybrid 1/2 app.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/ysDNCSbtndD4BrQhWq8g?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 1.4.11 and 2.4.0

ng-bootstrap: 1.0.0-alpha.18

Bootstrap: 4.0.0-alpha.6

**Comment by marcalj** [comment]
Same problem here!

**Comment by katesowles** [comment]
Same problem here.

**Comment by 3du4** [comment]
Same problem here.
When hovering over, the css values keep changing.
