### ISSUE TITLE
Modal Components are not destroyed

### ISSUE THREAD

**Issue by adamkleingit** [ng-bootstrap/ng-bootstrap#1264]
### Bug description:
Hi
We open a modal and close it several times, but the component tree shows it is not destroyed. Visible with Augury extension:
![screen shot 2017-01-26 at 5 18 40 pm](https://cloud.githubusercontent.com/assets/889418/22336632/910a6a24-e3eb-11e6-9655-a48577c8f6c6.png)

### Link to minimally-working plunker that reproduces the issue:
Cannot open Augury on Plunkr preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
2.4.4

ng-bootstrap:
1.0.0-alpha.19

Bootstrap:
3.3.5

**Comment by pkozlowski-opensource** [comment]
Hi there! We still need a plunker (or similar) to see the exact scenario - I will take care of putting it into a page where I can open Augury if needed (but I don't think it will be necessary as it should be enough to check that DOM elements are not there - we've got already tests to confirm that components are properly destroyed. So yeh, I still want to see a minimal reproduce scenario to make sure that we are fixing the right thing (if there is anything to fix).

BTW, you've noted Bootstrap 3.3.5 while we only support BS 4 here (not that it should matter for this particular issues, just head ups).

**Comment by pkozlowski-opensource** [comment]
So actually you can easily run Plunker content with Augury by using "Previewing in windowed mode", ex.: http://run.plnkr.co/O6KQX35BqWQEYodP/ (original plunk: http://plnkr.co/edit/lXNqv7c3rjkaPj1WZz4y?p=preview). I can see the issue with the above plunk.

The funny thing is that if you look at the console you can see that the `ngOnDestroy` method is called correctly, At this point the issue can be one of:
* Augury gets confused by dynamically created modules somehow (bug on Augury side);
* There are some data structures not destroyed correctly on our side and this is why Augury is confused (bug on our / Angular side).

Needs more investigation.

**Comment by cswanson0** [comment]
I have been struggling with this issue most of the day and it appears that when you pass an actual component to the .open(anyComponent) that component is not getting properly disposed.

Originally, my container was in the root module but I was opening a modal from a sub module.

When I moved the container down one level into the sub module, on close the component passed in was still not disposed of, but if I left the module and entered another one and came back, the component was destroyed.

Still investigating...

**Comment by nishesj** [comment]
Can it be its happening only on debug mode? Does this happen when enableProdMode is called?

**Comment by cswanson0** [comment]
Same with enableProdMode called.

**Comment by pkozlowski-opensource** [comment]
For anyone tracking this issue: we've got a modal service refactoring in-flight that makes it easier to use (no need for the `ngbModalContainer` directive any more) and fixes this issue as well. The mentioned refactoring should land next week and will be part of the next release (alpha.21).

**Comment by lucasklaassen** [comment]
@pkozlowski-opensource is there documentation for this?
