### ISSUE TITLE
How to wrap component which uses ng-content

### ISSUE THREAD

**Issue by jiayihu** [ng-bootstrap/ng-bootstrap#1265]
### Bug description:

It's not possible currently to wrap any component of the library which uses `ng-content`/transclusion. This seems be caused by `@ContentChildren` which can't query 2+ levels of transcluded content.

So the following does not work:

```typescript
@Component({
  selector: 'my-accordion',
  template: `
    <ngb-accordion>
      <ng-content></ng-content>
    </ngb-accordion>
  `
})
export default class MyAccordionComponent {}
```

And used as `<my-accordion><ngb-panel>Hello world<ngb-pabel></my-accordion>` because `ngb-panel` can't be queried by `ngb-accordion`. Maybe using `{ descendants: true }` with `@ContentChildren(NgbPanel)` could solve this issue.

How would you suggest to wrap components? 

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.4.5

ng-bootstrap: 1.0.0-alpha.19

Bootstrap: Bootstrap 4 alpha6

**Comment by pkozlowski-opensource** [comment]
Sorry, but it is not clear at all what you are trying to do and what is not working... Please provide more context and a minimal plunker of what you are trying to attempt.

**Comment by jiayihu** [comment]
I'm basically trying to wrap this lib's components in my own library. For example I'd like:
`<my-accordion><my-panel>Hello World</my-panel><my-accordion>` to behave exactly like `<ngb-accordion><ngb-panel>Hello World</ngb-panel><ngb-accordion>`. 

The problem is that `NgbAccordion` uses `@ContentChildren(NgbPanel)` to get the panels and it's always `undefined` for me. From its point of view it's receiving ```
<ng-content> // This ng-content is defined in NgbAccordion template
  <ng-content>Hello world</ng-content> // this ng-content is defined in MyAccordion template
</ng-content>
```

I'd like to setup a plunker, but I don't know how to add `ng-bootstrap`. Could you setup a minimal plunker which I (and other people) can clone and edit to reproduce the issue?

**Comment by pkozlowski-opensource** [comment]
@jiayihu you can fork plunkers from our demo site: https://ng-bootstrap.github.io/#/components/accordion - each demo has a button to create a plunk from it.

Having said the above you seem to be building on top / extending ng-bootstrap and while we want to support your use-cases we expect more involvement. You will have to _understand_ and _clearly explain_ what you want to change in this library for your use. In a way we expect you to act as a contributor here if you are building on top.

As I've said previously I'm really having hard time following what you are trying to do exactly so I would suggest exploring more code of this library, distilling your problems and sending us PRs if you see things to be changed.

Going to close this for now as I don't see actions we could take right now on our end.

**Comment by azarus** [comment]
@pkozlowski-opensource he wanted to create a custom component using ngb-accordion.

Using ng-content inside an ngb-accordion doesn't work.
`<ngb-accordion [closeOthers]="true" activeIds="static-1">
	<ng-content></ng-content>
</ngb-accordion>`

So if you want to create your custom component that wraps ngb-accordion it not possible.
```
<my-accordion>
<my-accordion-panel>Accordion Title</my-accordion-panel>
<my-accordion-panel>Accordion Title</my-accordion-panel>
</my-accordion
```
This seemed to be a workaround for me since **uib-accordion-header** & **uib-accordion-content** is not supported in ngb. But this approach doesn't work either so i am lost right now.

**Comment by ratoaq2** [comment]
I have the very same use case. I want to wrap some 3rd party components to be reused in my application where these 3rd party components are encapsulated and the rest of the application doesn't rely directly on them. What I need to create is one level of indirection and it seems it's not possible (or it's not clear on how to achieve this) if the 3rd party component has ng-content in it.

**Comment by filipefmelo** [comment]
Same use case here. Trying to wrap ng-bootstrap components and not being able to work with ng-accordion. Please provide solution or workaround.

**Comment by klemenoslaj** [comment]
Guys I think this is definitely not the problem of `ng-bootstrap`, it is a problem of Angular platform.
Angular does not support `ContentChildren` queries deeper than one level (_your wrapper component is second level_), and it is so by the design.

A great explanation can be found here: https://github.com/angular/angular/issues/20810#issuecomment-401341413

**Comment by filipefmelo** [comment]
@klemenoslaj this is already known. What Bootstrap could do is re-write some components to enables them to be wrapped.

**Comment by t-gawel-samsung** [comment]
Actually there is an ugly hack to make it possible with accordion.

In your wrapping component add:

```
  @ViewChild(NgbAccordion) accordionRef:NgbAccordion;
  @ContentChildren(NgbPanel) panels: QueryList<NgbPanel>;

  ngAfterViewChecked() {
    this.accordionRef.panels = panels;
    this.accordionRef.ngAfterContentChecked();
  }
```

While in your wrapper's template you do not need pass `<ng-content>` down: 
`<ngb-accordion [closeOthers]="true" activeIds="static-1"></ngb-accordion>`

Of course this will only work as long as you know what is expected to be in ng-content (E.g. NgbPanel in NgbAccordion).

In my own components which I expect to be wrapped I add possibility to pass the ng-content templates by input for wrapping purposes.

```
  @ContentChildren(CustomCellDirective)
  @Input()
  set customCells(list: QueryList<CustomCellDirective> | Array<CustomCellDirective>) {
     // ...
```

**Comment by moccaplusplus** [comment]
Actually there is an ugly hack to make it possible with accordion.

In your wrapping component add:

```
  @ViewChild(NgbAccordion) accordionRef:NgbAccordion;
  @ContentChildren(NgbPanel) panels: QueryList<NgbPanel>;

  ngAfterViewChecked() {
    this.accordionRef.panels = panels;
    this.accordionRef.ngAfterContentChecked();
  }
```

While in your wrapper's template you do not need pass `<ng-content>` down: 
`<ngb-accordion [closeOthers]="true" activeIds="static-1"></ngb-accordion>`

Of course this will only work as long as you know what is expected to be in ng-content (E.g. NgbPanel in NgbAccordion).

In my own components which I expect to be wrapped I add possibility to pass the ng-content templates by input for wrapping purposes.

```
  @ContentChildren(CustomCellDirective)
  @Input()
  set customCells(list: QueryList<CustomCellDirective> | Array<CustomCellDirective>) {
     // ...
```

**Comment by pdelekta** [comment]
I am using Angular 19 and also have issues with wrapping `ngbAccordionItem` with `ng-content`. Now Angular supports nested content child queries by `descendants: true` option (https://angular.dev/api/core/ContentChildren#description). Maybe it's worth to try?
