### ISSUE TITLE
NGB Pagination emiting wrong value 

### ISSUE THREAD

**Issue by rightisleft** [ng-bootstrap/ng-bootstrap#1266]
I'm running the latest angular-cli beta-26 with ng-bootstrap alpha.10 

```
<ngb-pagination (pageChange)="onPager($event)" [rotate]="true" [ellipses]="false"
                                            [maxSize]="10" [collectionSize]="15" [pageSize]="1"
                                            [(page)]="pageIndex"></ngb-pagination>


  next() {
    this.pageIndex = 5
  }

  onPager(event: number): void {
    debugger;
    console.log("Pager event Is: ", event)
    this.gotoTopic(event - 1);
  }

```

when i change the value of this.pageIndex, onPager() gets called with a value of whatever collectionSize is set to. In this case its 15. If i change the collectionSize value to 30, and call next(), onPager will receive 30.

**Comment by pkozlowski-opensource** [comment]
Plunker, please: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment]
BTW ng-bootstrap alpha.10 is 3 months old and there were 9 subsequent releases since then. Make sure that you are testing with the latest version when preparing a plunk (you can fork one from our demo page)

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't heard back / don't have reproduce scenario and a rather old version of the library was used. Happy to reopen when we do have reproduce scenario.
