### ISSUE TITLE
chrome hung up when set default value for datepicker

### ISSUE THREAD

**Issue by nofear87** [ng-bootstrap/ng-bootstrap#1275]
```
<input class="form-control" placeholder="YYYY-MM-DD" navigation="arrows" name="firstCertDate" ngbDatepicker #vfcD="ngbDatepicker" [(ngModel)]="updatedProject.startDate" ngModel>
<div class="input-group-addon" (click)="vfcD.toggle()" >
   <i class="fa fa-calendar-o"></i>
</div>
```

Date format is { "year": "2017"; "month": "03"; "day":"02"}
It's displayed correctly in input field, but when I click on the input group addon to toggle the calendar view chrome hung up. Console is clean. Any ideas?

**Comment by pkozlowski-opensource** [comment]
> Any ideas?

Not without a plunker: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment]
Also make sure that you are on the latest version (1.0.0-alpha.19 atm) as there were some commits that tightened up error messages and behavior for corner cases.

**Comment by nofear87** [comment]
Thanks! I solved it by using parseInt() for the ngbdatestruct parts.
