### ISSUE TITLE
rateChange fires on ngbRating when element is pristine

### ISSUE THREAD

**Issue by SanderElias** [ng-bootstrap/ng-bootstrap#1282]
### Bug description:
when you using the rating the rateChange event fires when the element is still pristime

### Link to minimally-working plunker that reproduces the issue:
[link](http://plnkr.co/edit/6SvNvxza3opm1PL8STeq?p=preview)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.4.5
ng-bootstrap: latest
Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
I can confirm that this is a valid bug. The root cause here is that we are not accounting for the initial change detection. The fix should consist of detecting initial CD and not propagating event in this case.

**Comment by arkisoul** [comment]
Hello, I know that this issue has been closed a while ago. But, I am facing similar kind of issue.
### Issue brief
When using the rating directive the rateChange event fires when the element is still pristine. The current rating state is coming from the server which get initialized in component's ngOninit function.

### Version of Angular, Bootstrap and ng-bootstrap:
Angular: ^6.0.0
Bootstrap: 4.1.1
ng-bootstrap: ^2.0.0
