### ISSUE TITLE
Rating can't be set to zero.

### ISSUE THREAD

**Issue by SanderElias** [ng-bootstrap/ng-bootstrap#1284]
### Bug description:
when using ngbRating, once set, the value can't be set back to 0 by the user.

### Link to minimally-working plunker that reproduces the issue:
[plunk showcase](http://plnkr.co/edit/DGKkZ8qsXrrRqacFne9u?p=preview)

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 2.3+
ng-bootstrap: current
Bootstrap: current

**Comment by pkozlowski-opensource** [comment]
Well, this one is tricky... Actually you _can_ select `0` (just try by providing model or changing it using keyboard). But how a user should select "nothing" using mouse?

I've checked a couple of other rating impls (ex. http://dreyescat.github.io/bootstrap-rating/) and they "suffer" from the same problem. In my view selecting selections of `0` would mean dropping functionality where rating is selected on click (and do selection on mouse-over).

Do you have any suggestions on how to solve it in the user-friendly way?

**Comment by SanderElias** [comment]
Aside from making a small margin/border on the edge that catches the click/hover, no not really. 
I can imagine that such a border is not an option from styling viewpoint. If that's the case, just close this one.

**Comment by wesleycho** [comment]
The UX for some sites is if you click the current value, it will reset to 0 - maybe it makes sense to make something like that configurable?

**Comment by maxokorokov** [comment]
I've just checked several sites like Amazon, Booking, etc.
They allow to cancel rating by re-clicking on current value. 
Though Amazon, for instance, enhances the UX by changing star colors when hovering (they all become blue) and when selected (they are golden):

Empty
<img width="274" alt="screen shot 2017-02-09 at 12 13 21" src="https://cloud.githubusercontent.com/assets/8074436/22781050/3c5141de-eec1-11e6-8a69-a2ca23d7fbd6.png">

Hovered
<img width="312" alt="screen shot 2017-02-09 at 12 12 59" src="https://cloud.githubusercontent.com/assets/8074436/22781061/43bb6530-eec1-11e6-96f6-7f837184771b.png">

Selected
<img width="301" alt="screen shot 2017-02-09 at 12 13 14" src="https://cloud.githubusercontent.com/assets/8074436/22781067/4b111f3c-eec1-11e6-8fc2-d5e22c7ff15a.png">

So my vote goes for:
- Not enable this behaviour by default
- Hide behind a flag (`[optional]` or `[resettable]` or some better name)
- Once the flag is active clicking on currently selected rating will reset to 0

P.S. I'm not sure we can customize the view between hovered and selected states currently, which would be nice also: adding a `hovered: boolean` flag maybe to the star template context

**Comment by benhalverson** [comment]
I was also wondering about this.
I need a rating component from 0 - 3 with custom icons.

<img width="382" alt="screen shot 2017-04-10 at 8 47 22 pm" src="https://cloud.githubusercontent.com/assets/7907232/24892132/1113049c-1e2f-11e7-91a9-01c8a777e08e.png">
<img width="696" alt="screen shot 2017-04-10 at 8 46 03 pm" src="https://cloud.githubusercontent.com/assets/7907232/24892135/15c4d902-1e2f-11e7-8243-daa9072ef398.png">

**Comment by ypcaptain96** [comment]
This feature seems to be bugged again, since we cannot set rating to zero on clicking the value again.
This can be tested on the demo site.

**Comment by maxokorokov** [comment]
@ypcaptain96, if you look at the PR, it adds the `[resettable]` input → https://github.com/ng-bootstrap/ng-bootstrap/pull/1515. Resetting to 0 is not a default behavior, but opt-in, you should add `[resettable]="true"`

Here is the Rating API → https://ng-bootstrap.github.io/#/components/rating/api#NgbRating
