### ISSUE TITLE
ngbModal - cannot prevent ESC key event if/when needed

### ISSUE THREAD

**Issue by armandoxxx** [ng-bootstrap/ng-bootstrap#1287]
There is a problem with ESC key event. 

In my case I need ESC key event to be prevented by application logic. 

check this demo [app.ts] :
http://plnkr.co/edit/4uwarleCjOGZP6DiuUe3?p=preview

Modal closes althought the event is prevented.

**Comment by pkozlowski-opensource** [comment]
What you are trying to do in the plunker won't work for sure as you are trying to stop propagation on the document element... which means that the event _already_ propagated to this level - so it is too late.

You've got several other options and IMO the best way of going about this thing would be to use the `keyboard: false` option, register your own listener to the ESC keypress and close or not modal based on your application logic. 

It is hard to suggest more without knowing / fully understanding what you are trying to achieve, thought.

**Comment by armandoxxx** [comment]
top idea ... totally forgot to disable it in config  and enable by myself . thank you ..

**Comment by pkozlowski-opensource** [comment]
Closing as a support request that got sorted out.
