### ISSUE TITLE
Fix the tailing point on the installation instruction

### ISSUE THREAD

**Issue by sleroy** [ng-bootstrap/ng-bootstrap#1289]
### Bug description:

Not sure it is a bug .. anyway I was silly enough to copy/paste the NPM installation instruction to put the lib into my angularJS project and I received :

`npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/home/sleroy/tools/node-v6.9.5-linux-x64/bin/node" "/home/sleroy/tools/node-v6.9.5-linux-x64/bin/npm" "install" "--save" "@ng-bootstrap/ng-bootstrap."
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Not found : @ng-bootstrap/ng-bootstrap.
npm ERR! 404 
npm ERR! 404  '@ng-bootstrap/ng-bootstrap.' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sleroy/git/blog-angularjs/npm-debug.log
`
Well, the solution was obvious, there is a tailing point at the end of the instruction, I did not see it at first.
npm install --save @ng-bootstrap/ng-bootstrap (.)

Could you remove it from the installation instruction :-) ?

**Comment by GuerrillaCoder** [comment]
Thanks, this one got me also.
