### ISSUE TITLE
[Feature Request] - Multiselect

### ISSUE THREAD

**Issue by rafaelss95** [ng-bootstrap/ng-bootstrap#1290]
I want to suggest the possibility of creation of a new component called **multiselect**.

**Ex:**

Maybe something like this -> http://code.promactinfo.com/md2/#/multiselect.

or 

http://softsimon.github.io/angular-2-dropdown-multiselect/#

**Comment by byunru** [comment]
suggest a listbox which support 
1) cutomizable item template
2) allow multi-select with Ctrl selection, or Shift selection

**Comment by pkozlowski-opensource** [comment]
The closest thing we are consider doing is #532. The aim of this project is not to support every possible control but focus on standard Bootstrap ones + most commonly needed (datepicker, typeahead etc.).

Thnx for the suggestion, but we are going to pass on this one.
