### ISSUE TITLE
Datepicker year+month+day=string? 

### ISSUE THREAD

**Issue by Kalaijagdai** [ng-bootstrap/ng-bootstrap#1292]
**## when the sending server**
view_date:{year: 2017, month: 2, day: 8}
      day:8
      month:2
      year:2017
**I need**
view_date:2017-2-8!!

**Comment by dmytroyarmak** [comment]
@Kalaijagdai `{year: ..., month: ..., day: ...}` structure (`NgbDateStruct`) is the default format for the date picker to store selected value. If you need to send it as a "2017-2-8" string you can do it in your service by converting `NgbDateStruct` into a string manually or by injecting `NgbDateParserFormatter` service and using its `format` method (it will output the same string as is shown in the input field after selecting a value).

**Comment by pkozlowski-opensource** [comment]
Duplicate #754
