### ISSUE TITLE
Pagination sorting feature request

### ISSUE THREAD

**Issue by Ks89** [ng-bootstrap/ng-bootstrap#1298]
Hello everyone, there is a way to sort paginated lists with your pagination component?
I didn't find any input param, so I suppose that it is not possibile. For this reason, I propose to implement this feature.

### Bug description:

I tried to implement a sorting pipe by myself, but to be able to see sorted data, I have to change page and go back. 
I suppose that this is not an issue, but a missing feature, so I don't post a demo.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.4.5

ng-bootstrap: 1.0.0-alpha.19

Bootstrap: 4.0.0 alpha 5

Thank u,
Ks89

**Comment by Ks89** [comment]
I forgot to say: "I implemented sorting with two pipes, the first one for sorting and the second one for pagination"

**Comment by dmytroyarmak** [comment]
@Ks89 Unfortunately, sorting and even pagination of lists (show different items when page is changed) is not a responsibility of `NgbPagination` component. 

This component only shows for a user a list of page numbers and handling selecting of a page by emitting `pageChange` event.

Handling of `pageChange` and showing items of a particular page (including sorting) is a responsibility of a developer that is using this component.

**Comment by Ks89** [comment]
Yes, I understand.
I implemented this feature exactly in that way.

However, a pipe version could be really useful, for instance:
*ngFor="let el of elements | sort:asc | paginate:from:to"

Obviously, this is only a personal opinion. Feel free to attack my idea :)

**Comment by alex321** [comment]
@Ks89 This hardly makes sense. Pipes are just functions whereas the pagination is a component with html content, etc. 

Regarding sorting: As @dmytroyarmak has mentioned already, this is not the responsibility of the pagination component. As an aside, I would also be careful when using pipes to implement sorting as that might severely hinder performance - more detailed info can be found at https://angular.io/docs/ts/latest/guide/pipes.html#!#no-filter-pipe .

**Comment by Ks89** [comment]
Yes I know, it was only a crazy idea :)

Understood, thank you for the link to angular docs. Really interesting.

Closed :)
