### ISSUE TITLE
timepicker: support change size of the chevrons 

### ISSUE THREAD

**Issue by peterhe2000** [ng-bootstrap/ng-bootstrap#1300]
Hi. Is it possible to change size of the chevrons?

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.4.5

ng-bootstrap: 1.0.0-alpha.20

Bootstrap: 4.0.0-alpha.6

**Comment by dmytroyarmak** [comment]
@peterhe2000 Please use StackOverflow for general help questions: https://github.com/ng-bootstrap/ng-bootstrap#getting-help

**Comment by pkozlowski-opensource** [comment]
@dmytroyarmak I think that the issue here is that chevrons are not scalling properly with the size option. We should convert them to svg and scale properly. This would be a good issue if you are looking for one :-)

**Comment by dmytroyarmak** [comment]
@pkozlowski-opensource Yeah, they are always the same will all "size" options. 
We can also do it in a little bit different way - we can for different "size" attributes change class on buttons with chevron to `btn-sm`, `btn-lg` or no additional class. Changes of the button will cause increasing or decreasing of font size and it will make chevron bigger or smaller.
What do you think about this approach?

**Comment by pkozlowski-opensource** [comment]
@dmytroyarmak if sticking different class names on buttons does the trick, then yes, please open a PR. Thnx!
