### ISSUE TITLE
NgModule suggestion, also "No Provider for NgbDropdown" bug

### ISSUE THREAD

**Issue by dhardtke** [ng-bootstrap/ng-bootstrap#1303]
### Bug description:
First of all, thanks for your library. We switched from ng2-bootstrap and so far we like this one better ;)

Okay, so you guys recommend Users to import the `NgbModule` inside our `AppModule` - why?

Okay, you don't have to import any other module from ng-bootstrap in components that are declared in `AppModule`. That's about it.

We in our project like to **only** include modules that are actually used. We are using webpack to build everything. So with importing `NgbModule` the app.js grows in size **a lot**.

Right now we are doing something like this:
```
import {NgbDropdownModule} from "@ng-bootstrap/ng-bootstrap/dropdown/dropdown.module";
```

It would be nice to be able to do something like this:
```
import {NgbDropdownModule} from "@ng-bootstrap/ng-bootstrap/dropdown";
```
(So there'd be an index.js exporting all members of NgbDropdown).

---
Also, there is a bug:
https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/dropdown/dropdown.module.ts#L10
When including `NgbDropdownModule` we get __No Provider for NgbDropdown__ as Exception since NgbDropdown isn't included in the `providers` array and therefore we must include it in our `AppModule`'s `providers` array.

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 2.4.5

ng-bootstrap: 1.0.0.alpha.20

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
@dhardtke thnx for the warm words. Could you please reproduce in a plunker the issue with providers that you are mentioning here? Please note that you need to use the MgbDropdownModule.forRoot() when importing in the app module.

**Comment by dhardtke** [comment]
Sure: http://plnkr.co/edit/gC8C6Mee2UlSKAhOslQv?p=preview

**Comment by alex321** [comment]
@dhardtke The only problem I see in your plunk is that you should be doing 
`import { NgbDropdownModule } from '@ng-bootstrap/ng-bootstrap'; `
**instead of** 
`import { NgbDropdownModule } from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown.module'`

Then everything works as expected. Let me know whether that resolves your issue.

**Comment by dhardtke** [comment]
This is exactly what I don't want to do. Otherwise, my compiled module gets bloated and includes all the other parts that the index.js of ng-bootstrap includes.

Also, my issue is not only about the missing providers declaration, but also about the fact that I seriously doubt it is a good idea to advice people to import the whole NgbModule in their AppModule, when they only need a few modules (and not everything NgBootstrap has to offer)

**Comment by jnizet** [comment]
I'm far from being an expert on these matters, but last time I checked, at least when compiling my application with the AOT compiler (using angular-cli), only the components from ng-bootstrap that I actually used in the application were included in the bundle, even though everything was imported from the root NgbModule.

**Comment by alex321** [comment]
@dhardtke I see what you are after now. Here's an updated plunker for your use case that does exactly what you wanted (you can see also that only the dropdown is loaded).

http://plnkr.co/edit/tMdJ1Us9pRVM3OB2MTCX?p=preview

The plunker that you have provided has a 500 error as you are getting the bundle, etc. and the path you have provided is wrong. Let me know whether there is anything amiss in this one.

**Comment by dhardtke** [comment]
@alex321 Yes, just like that. Now I am curious why I still have to manually provide the NgDropdown class.

Anyway: My suggestion is, removing the recommendation to add the NgbModule to the AppModule, and instead let users import each module they want in their sub modules. That way they get rid of some overhead of code they don't need.

Also, like I said before: It would be nice if one could simply do `import {NgbModalModule} from "@ng-bootstrap/ng-bootstrap/modal`, instead of `import {NgbModalModule} from "@ng-bootstrap/ng-bootstrap/modal/modal.module`

**Comment by alex321** [comment]
@dhardtke 
1.You do not need to provide it - as you can see I haven't added it to providers or anything else and it is working as expected. So I suspect there is something amiss on your side.

2. Regarding the second statement - I think it is quite low priority. As **jnizet** has mentioned though, I imagine that there must be a way to import from **@ng-bootstrap/ng-bootstrap** and have only the other modules loaded.

@pkozlowski-opensource Could you please comment whether AOT or anything else would do that?

**Comment by pkozlowski-opensource** [comment]
So we used to have an index.html file for each and ecery module but some people complaned that it was making SystemJS configuration harder. We could explore this more.

**Comment by dhardtke** [comment]
Fair enough: I just tested using the "@ng-bootstrap/ng-bootstrap" imports again and it seems to only include the modules in my bundles (created using webpack) that I imported.

Perfect!

**Comment by ffabreti** [comment]
The above solution from [dhardtke](https://github.com/ng-bootstrap/ng-bootstrap/issues/1303#issuecomment-289223233) is wrong.
It may work at the beginning, but you may see "stranger things" like  clicking on one dropdown opens other dropdown.

**Comment by dhardtke** [comment]
No, I did not notice such thing. Why would the way we load modules imply such behavior?

**Comment by shehzadkhan463** [comment]
I am facing a similar issue. I have used ng-bootstrap@1.1.1 and angular@5.2.x both for my web application and the reusable component's library (includes core and shared modules). Everything works great with the development but for the prod with aot build it throws an error in the console saying 'No Provider NgbAlertConfig'. Earlier this error was experienced for NgModal, NgModalStack, NgDropdownConfig which was fixed by adding them in the providers array of the components from which the error was triggered. i understand this is not at all the right solution. Please advise
