### ISSUE TITLE
Add ability to target popover triangle 

### ISSUE THREAD

**Issue by rightisleft** [ng-bootstrap/ng-bootstrap#1305]
When trying to change the entire color of a popover, you can only target the content and not the arrow.

Expected: Should be able to change background color of all elements.

code:

:host >>> .popover {
    color: #666;
    border-radius: 0;
    font-weight: 600;
    background-color: red;
}

:host >>> .popover-content {
    background-color: red;
}

Output:

The arrow is still white.

**Comment by pkozlowski-opensource** [comment]
Check what Bootstrap does in their css - they are targetting a pseudo-element and you shoul do the same in your custom css.

Closing as a support request that is css specific and has nothing to do with this library.
