### ISSUE TITLE
Incorrect background image for validation styles

### ISSUE THREAD

**Issue by wardr** [ng-bootstrap/ng-bootstrap#1307]
When using the .has-danger and .has-success classes (i.e. Bootstrap 4 form validation classes), the background images, such as the "x" for .has-danger show the incorrect icon.

![validator-bug](https://cloud.githubusercontent.com/assets/9736842/22792573/74d5ac82-eeaa-11e6-8d9a-e9e14ace7d39.png)

Versions in use: 

* Angular 2.3.1
* ng-bootstrap: 1.0.0-alpha.20
* bootstrap v4.0.0-alpha.6

**Comment by alex321** [comment]
@wardr Could you please submit a minimal reproduction using https://plnkr.co/ ? The samples at https://ng-bootstrap.github.io/#/components already contain starting plunkers that you can use. 
It just saves developer time rather and prevents stabbing at the dark.

**Comment by pkozlowski-opensource** [comment]
This sounds like a css issue so I'm not sure how this is related to this library. In any case this is not actionable without a plunker - please provide one or this issue will be closed.

**Comment by pkozlowski-opensource** [comment]
Closing as I don't think it is related to this library and we don't have reproduce scenario.
