### ISSUE TITLE
Datepicker does not bind to [(ngModel)] start up value properly.

### ISSUE THREAD

**Issue by peterhe2000** [ng-bootstrap/ng-bootstrap#1308]
I have set up a plunker to replicate this issue:
https://embed.plnkr.co/RpFKkaeIrYd5XmZLzG8o/

As soon as i give a start up value model = { "year": "2017", "month": "2", "day": "25" } in datepicker-popup.ts, the datepicker is freezed and you click the calendar icon datepicker is not going to show up.

Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.4.5

ng-bootstrap: 1.0.0-alpha.20

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
you should use numbers as year, month and day value, not strings. Will keep this issue open so we can have proper error message in the broken input as in your case.

**Comment by peterhe2000** [comment]
Oops. My bad. Thx.
