### ISSUE TITLE
Modal size 

### ISSUE THREAD

**Issue by Pakooo** [ng-bootstrap/ng-bootstrap#1309]
I have one simple question is the Modal component going to have different sizes like " xs ,md and xl" that are in media query?

**Comment by pkozlowski-opensource** [comment]
It does already, check the "size" option: https://ng-bootstrap.github.io/#/components/modal

**Comment by squadwuschel** [comment]
@pkozlowski-opensource yes but you forgot one size you only have only Type: "sm" | "lg" avaiable but bootstrap support "sm" | "md" | "lg" as size options. you need to add "md" to your size options Array.

**Comment by pkozlowski-opensource** [comment]
"md" is the default one, so if you ommit the size option you are going to get "md", no? Not sure if it makes sense to have an explicit option for this.

**Comment by squadwuschel** [comment]
then it would be nice if you could extend the help by adding a hint to the default value when no size is set.

**Comment by Pakooo** [comment]
Yes but I have a Modal that "lg" is small and I need little bigger size like "xl".

**Comment by pkozlowski-opensource** [comment]
Bootstrap itself only provides 2 sizes that are already supported by this library: http://v4-alpha.getbootstrap.com/components/modal/#optional-sizes

If you need bigger size then you can customize Bootstrap's css or open an issue on the bootstrap side so more sizing options are supported. In any case there is nothing imediatelly actionable on the ng-bootstrap side.

**Comment by Pakooo** [comment]
I am sorry for that I was looking at http://v4-alpha.getbootstrap.com/layout/overview/#responsive-breakpoints and I was thinking for something else. I apologize again.

**Comment by intellix** [comment]
@Pakooo you can hack it's type to accept additional sizes that you add yourself like so:
```
this.modalService.open(PaymentModalComponent, {
  size: 'xl' as 'lg',
});
```

**Comment by kthotav** [comment]
How do I use the size option in code. I don't see any documentation on how to use the ngModalOptions ?

**Comment by devner007** [comment]
@kthotav You can use the size option in the following manner:

```
this.modalService.open(content, {
      size: 'lg',
    });
```

**Comment by squadwuschel** [comment]
@Pakooo you can set the "windowClass" property

    windowClass: 'modal-xxl' 

and add your own style like

    .modal-xxl .modal-lg {
        max-width: 90%;
    }

**Comment by lqm229026** [comment]
@squadwuschel 
where should I put the style code?
I have append my modal to an container component using the 'container' option like this
```
open(myModalComponent,{
  container: '.container-component',
  windowClass: '.my-modal'
});
```

I want to define some style for myModalComponet such as the 'max-width' property. I have put the style code in the scss file of the container componet like this
```
.container-componet {
  .my-modal .modal-dialog {
    max-width: 1000px;
  }
}
```
while it did not work for me. Did I do something wrong?

**Comment by venkatpallantla** [comment]
Is it possible to have modal pop to be 90% width, with out using custom CSS. why are trying to completely avoid the CSS.  Is there a way to achieve this through ngbootstrap ?

**Comment by sulhome** [comment]
@lqm229026 check the third example "Modal with custom class" on this page:
[https://ng-bootstrap.github.io/#/components/modal/examples](https://ng-bootstrap.github.io/#/components/modal/examples)

**Comment by javahaxxor** [comment]
I couldn't get sizing to work without setting ViewEncapsulation.None
Using @squadwuschel 's example. My setup is the following: Angular 5 app > ticket component > ticketinfo ngb-modal which I'm trying to set to 80% screen width. in ticket component I set the styles array to:

 ```
@media screen {
        .modal-adaptive .modal-lg {
            width: 80% !important;
            max-width: calc(80%);
        }
}
```

and then 
`this.modalService.open(TicketInfoComponent, { size: 'lg', windowClass: 'modal-adaptive' });`

this doesn't work unless I do the following:
```
@Component({
    moduleId: module.id,
    selector: 'ticket',
    template: require('./ticket.component.html'),
    encapsulation: ViewEncapsulation.None,
    styles: [`
    @media screen {
        .modal-adaptive .modal-lg {
            width: 80% !important;
            max-width: calc(80%);
        }
}})
```

**Comment by atifmajeed** [comment]
Thanks @javahaxxor, I needed a bigger modal to shows a table and your solution worked. Is there a way to make these modals movable?

**Comment by zsj1029** [comment]
when i use mobile just like iphone
size 
include custom class and css width 
its still always show the big style

**Comment by bkoukoori** [comment]
I was able to set the modal width, but I want a fixed height for my modal, please can anyone help me out. Thanks.

**Comment by atifmajeed** [comment]
@bkoukoori you can try setting max-height in pixels.

.modal-adaptive .modal-lg {
  height: 600px !important;
  max-height: 600px;
}

**Comment by seby598** [comment]
Using `encapsulation: ViewEncapsulation.None` is not really a solution. Because then the styling would be applied to the entire app and it will also change the other modals. For me that was a problem.

**Comment by leonardonicolassimes** [comment]
> @Pakooo you can set the "windowClass" property
> 
> ```
> size: 'lg',
> windowClass: 'modal-xxl' 
> ```
> and add your own style like
> 
> ```
> .modal-xxl .modal-lg {
>     max-width: 90%;
> }
> ```

Muchas gracias!! Anduvo excelente ese código!
