### ISSUE TITLE
Is bootstrap@4.0.0-alpha.5 css still supported? 

### ISSUE THREAD

**Issue by Matmo10** [ng-bootstrap/ng-bootstrap#1311]
Also, was a new version of ng-bootstrap published under the same version tag?

I ask because I have "1.0.0-alpha.20" working with bootstrap@4.0.0-alpha.5 on some jenkins machines that use yarn, and I can only assume that they are using a previously cached version. 

But after clearing all my local yarn and npm caches, when I use this same combination of version numbers, [things do not work](http://stackoverflow.com/questions/42172334/angular-2-ng-bootstrap-styles-are-botched). 

If you try [this plunkr](http://plnkr.co/edit/uw2PdlGVv5DtERMNNcP9?p=preview) with bootstrap@4.0.0-alpha.6, you will see that the NgbModal works, but if you change the bootstrap version to 4.0.0-alpha.5 it will not appear at all anymore. 

How can I stay informed of when external dependency requirements change in the future? Thanks.

**Comment by pkozlowski-opensource** [comment]
All the info s in the changelog: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#100-alpha18-2017-01-09
