### ISSUE TITLE
bug(rating): no way to stop event propagation

### ISSUE THREAD

**Issue by shibulijack** [ng-bootstrap/ng-bootstrap#1313]
### Bug description:
When the rating component is included in a clickable div, there is no way to effectively stop the event propagation without binding to (click) event. But if we do so, we don't get the modified rating since (rate) gets fired later.

### Sample code

html:
```
<div class="wrapper" id="clickable">
<!-- contains various elements -->
....
<ngb-rating [(rate)]="ticket.user.score" (click)="onRatingChange($event, ticket.user.score)">
<template let-fill="fill">
   <span class="rate-icon" [ngClass]="{'icon-favorite': fill === 100, 'icon-favorite_border': fill !== 100}"></span>
</template>
</ngb-rating>
....
</div>
```

ts:
```
onRatingChange($event, score) {
    $event.stopPropagation();
    console.log(score); //score doesn't reflect the updated value
  }
```

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.3.1
ng-bootstrap: 1.0.0-alpha.15
Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
It is not clear what is your exact problem as we are not using click events enywhere in the rating component. Please provide a minimal reproduce scenario using plunker - otherwise it is not actionable and will be closed.

**Comment by pkozlowski-opensource** [comment]
Closing as we don't have reproduce scenario. Happy to re-open when you got a plunker.
