### ISSUE TITLE
Dependency injection fails with DatePicker that supports i18n

### ISSUE THREAD

**Issue by mircowidmer** [ng-bootstrap/ng-bootstrap#1314]
The I18n date picker component does not work as expected.

In the i18n version of the date picker component (https://github.com/ng-bootstrap/ng-bootstrap/blob/1.0.0-alpha.8/demo/src/app/components/datepicker/demos/i18n/datepicker-i18n.ts) the injectable **private _i18n: I18n** within the class **CustomDatepickerI18n** is not injected. It is always undefined and therefore calls of getWeekdayName() fails with an undefined error. Interesting is, that the dependency injection seems to work in the class **NgbdDatepickerI18n** because in the constructor, the value of _i18n is not undefined. An upgrade to Angular 2.3.1 helps to fix this issue but it's currently not possible in my case.

Is there a workaround to make sure, that within the constructor of CustomDatepickerI18n the injected Injectable (in the demo I18n, in a real world case another TranslationService) is not undefined?

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 2.1.0
ng-bootstrap: 1.0.0-alpha.8
Bootstrap: 4.0.0-alpha.4

**Comment by pkozlowski-opensource** [comment]
Please provide a minimal reproduce scenario using plunker or similar - otherwise it is not actionable and will be closed. Also you seem to be using several months old version of ng-bootstrap: please test with the latest version when reporting issues.

**Comment by pkozlowski-opensource** [comment]
Closing as the bug was reported against the very old version of this library and we don't have reproduce scenario. Happy to re-open when / if you can provide a plunker demonstratimg the issue with the latest version of ng-bootstrap.
