### ISSUE TITLE
Add `in` class for modal window. 

### ISSUE THREAD

**Issue by batonmedia** [ng-bootstrap/ng-bootstrap#1315]
Originally Bootstrap has `modal fade in` classes for a modal window.
Without `in` class modal window stays in transparent state after opening.
It's necessary to add `in` class to that list for correct performance.

Please fix [this line](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/modal/modal-window.ts#L18)
```'[class]': '"modal fade show in" + (windowClass ? " " + windowClass : "")',```

Temporary solution:
```
let modalOptions: NgbModalOptions = {
  windowClass: 'in',
};
const modal: NgbModalRef = this.modalService.open(content, modalOptions);
```

**Comment by pkozlowski-opensource** [comment]
Bootstrap alpha.6 uses "show" instead of "in". You need to update your Bootstrap CSS version or downgrade ng-bootstrap version: check changelog for more details.

Also check our demo page where things work perfectly fine.

Closing as a support ticket.
