### ISSUE TITLE
Protractor times out when Carousel is present

### ISSUE THREAD

**Issue by giggio** [ng-bootstrap/ng-bootstrap#1319]
### Bug description:

Protractor times out when Carousel is present.
You will get this message:

````
Timed out waiting for asynchronous Angular tasks to finish after 11 seconds.
````

### Link to minimally-working plunker that reproduces the issue:

You can use any of your carousel plunkers. Simply run protractor against it, and it will timeout.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.4.3

ng-bootstrap: 1.0.0-alpha16

Bootstrap: 4.0.0-alpha.5

Protractor: 5.0.0

**Comment by giggio** [comment]
It seems earlier versions had similar problems with Angular 1. See https://github.com/angular-ui/bootstrap/issues/2454

**Comment by wesleycho** [comment]
My gut feeling here is that this is a Protractor issue, not an ng-bootstrap issue.

**Comment by Ks89** [comment]
It's happening to me with Angular Test Bed when I'm building the carousel using a *ngFor | async to iterate over a Json array (image + text + description) received after an async call to a server. I found this problem replacing template with ng-template and upgrading ng-bootstrap to alpha 25.

If you need more info or a demo project feel free to ask, but I need some days to create it, because I'm quite busy these days.

**Comment by wesleycho** [comment]
I took a look at this, and this appears to be inconsistent. Here is an app generated by Angular CLI that illustrates this: https://github.com/wesleycho/carousel-protractor .

What seems to happen is that actions are blocked until the page navigation is complete, but in the meantime the carousel is already running.

**Comment by ivarvolt** [comment]
Protractor hangs when there are intervals used.
So I had the same problem. Right now my workaround is:

set carouselConfig.interval = 0;  
(Seems if I dont define it, some default is used? if its 0 then interval wont be started.)

To have the carousel interval functionality in component:
  @ViewChild(NgbCarousel)
  private carousel: NgbCarousel;

In ngOnInit I have code:
    this.ngZone.runOutsideAngular(()=>{
      setInterval(() => {
        this.ngZone.run( () => {
          this.carousel.next();
        });
      },3000);
    });
