### ISSUE TITLE
Binding to (click) inside Popover Template?

### ISSUE THREAD

**Issue by mb2140** [ng-bootstrap/ng-bootstrap#1324]
I don't see this mentioned anywhere in the documentation so I thought I'd leave this as a feature request.  I'm trying to bind to a (click) event within the template of a popover:

```
<template #remove>
 <div style="width: 250px;">
Are you sure you want to delete this? - 
<a href="javascript:void(0)" style="color: #ed6f00;" (click)="delete(item)">Yes I'm sure</a>
</div>
</template>
```

When I click the 'delete' button I get this error:

self.parentView.parentView.parentView.context.delete is not a function

Need a way to access the parent context from within the popup.

**Comment by pkozlowski-opensource** [comment]
It should work out of the box, I suspect that something else is going on in your code. please provide a minimal plunker with a reproduce scenario, otherwise this one is not actionable and will be closed: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment]
Closing as we don't have a plunker and haven't heard from the issue author.
