### ISSUE TITLE
Modal Feature Request - allow updating component instance

### ISSUE THREAD

**Issue by brcpar** [ng-bootstrap/ng-bootstrap#1330]
Right now, to have a multi-step modal, you would need to either:
1. have a single template with all steps conditionally shown
2. close/open a modal with each step
3. write separate component factory injection for each step using a common component

Ideally, it would be great to have a function or other mechanism in place to either swap out the NgBModalRef.componentInstance which is currently a getter only property.  Alternatively, having a function that essentially reinitializes the same modal instance with a new component could also work.

The problem I'm trying to solve is if I have multiple steps going through a modal, I'd like to have a single modal window handle rendering each step as necessary.  Currently, there is not a way to update the current component instance once it it is set.

**Comment by pkozlowski-opensource** [comment]
Thnx for the suggestion but this is too specific for a general library like ng-bootstrap an shouls be rather handled on the user side.

**Comment by jrmcdona** [comment]
@brcpar Did you figure out how to update the modal once is set?   Trying to do something similar with passing some objects/strings that change.  But the modal isn't detecting the changes, so far.   Not sure how to accomplish it!

**Comment by brcpar** [comment]
@jrmcdona You can't modify the instance once it has been set.  Inspecting the source, there's not a great way to do it without investing good work which we frankly didn't have time to even think about.  Instead, we just created a single view which mainly served as just a parent component to all of our steps.  That parent component would conditionally show the appropriate step.

I do feel this was dismissed a little hastily as I think being able to reuse a modal instance is a much more common thing than given credit, but I understand time is the most scare resource and it must be managed properly.

One idea you could try is adding a method to your component that updates the values of the object/string you are interested in and call this method directly when a change needs to occur since you get a reference to this instance after opening the modal.  Hope this helps.
