### ISSUE TITLE
carousel expose an event of index change

### ISSUE THREAD

**Issue by byunru** [ng-bootstrap/ng-bootstrap#1331]
suggest expose the carousel event for carousel when been navigated to a new image

**Comment by pkozlowski-opensource** [comment]
Could you share your real-life use-case where such event would be helpful? This would allow us to properly prioritize this feature request.

**Comment by pkozlowski-opensource** [comment]
I'm going to close this one as we haven't heard back from @byunru and I'm not keen on extending API surface without a concrete use-case.

**Comment by byunru** [comment]
pkozlowski, sorry, I didn't get notice of this.
the scenario is when I click left/right arrow button,  the content outside of the carousel need to updated accordingly based on which image currently show.
I guess that expose an event only need few lines of code + document.

Thanks.

**Comment by pkozlowski-opensource** [comment]
@byunru feel free to send a PR if you care about adding this functionality. Thnx!

**Comment by lauraiurb** [comment]
I have a situation that I need that functionality, I'm using carousel with charts.
The first chart is ok but the other charts does not show if I don't reload it when is in the active slide. So I need that event for refresh the charts.
I will use ngx-bootstrap because I found th way to get the slide index with "activeSlide"

**Comment by pkozlowski-opensource** [comment]
@lauraiurb huh? We've added the `(slide)` event in #1406 like... almost a year ago... Check documentation for `NgbSlideEvent` and note that you can access all information about the current and next slide: https://ng-bootstrap.github.io/#/components/carousel/api

**Comment by lauraiurb** [comment]
@pkozlowski-opensource 
Ohhh, I understand now, I read it before but i didn't get it. Thanks a lot! I will use it

**Comment by mafia99** [comment]
Hi I am new to angular so I have no Idea how to use this slide event. would be great if I can see a working example.

**Comment by Krunal-Gosalia** [comment]
Even I would like to see working example of it. If someone can post - it will be really helpful.

**Comment by 4i-helpynet** [comment]
Hi all

EXAMPLE:

1: in .html:  
<ngb-carousel *ngIf="images" (slide)="onSlide($event)"> 

2: in .ts
public onSlide(slideData) {
	  console.log('SLIDE:',slideData);
// your JS here
}

**Comment by KDSGYT** [comment]
Thank you so much for the help....
