### ISSUE TITLE
Dynamically created [routerLink] inside alert's message

### ISSUE THREAD

**Issue by lukaszwilk** [ng-bootstrap/ng-bootstrap#1339]
### Bug description:

Currently I can't add routerLink directive into alert's message that is generated dynamically from component and binded using [innerHTML]. I believe that this is very common scenario and we should be able to include those dynamically created links as parts of messages.

From what I investigated directives and components are not created for HTML that are added using [innerHTML]. This HTML is not process by Angular in any way. I saw that there are a some ways to do it using ngComponentOutlet or older method with ViewContainerRef.createComponent.

Do you plan to support it out of the box? Or is there some clean way of doing it that I'm missing here?

### Link to minimally-working plunker that reproduces the issue:

[http://plnkr.co/edit/zsOiKToQ2i32l4J55ry4](http://plnkr.co/edit/zsOiKToQ2i32l4J55ry4)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.3.1

ng-bootstrap: 1.0.0-alpha.20 

Bootstrap: 4.0.0-alpha.6

**Comment by jnizet** [comment]
Doing that would need to compile the dynamic HTML at runtime, in the browser.

That would in turn require the angular HTML compiler to be available at runtime. 

But that is exactly what the Angular design wants to avoid, by pre-compiling all the templates at build time, using the AOT compiler, and thus be able to not embed the angular compiler in the application.

You'll need to find another design, not including dynamic HTML. Everything should work fine if you embed your HTML directly in your template, or in the template of another component displayed by your template.

**Comment by lukaszwilk** [comment]
Yeah, but embedding reduces freedom on making fully dynamic messages based on application state. Anyway you've made a very valid point, about which I completely forgot during search for a solution. I will need to rethink design of those messages.
