### ISSUE TITLE
typeahead: constant re-rendering with result formatter

### ISSUE THREAD

**Issue by PerfectPixel** [ng-bootstrap/ng-bootstrap#1340]
### Bug description:
Using a result formatter function, that function is constantly called if you move your mouse. This is basically the same as described in closed issue #526.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/l6tAXC09fGKpkN9Wk59u?p=preview

Have a look into the browser console. It'll print a `formatter called` each time the formatter is called. If you move the mouse up and down the drop down, a lot of formatter calls are fired.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: v2.4.8

ng-bootstrap: v1.0.0-alpha.20

Bootstrap: v4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
This is _not_ the same issue as #526 at all (#526 was about re-creating all DOM elements). What you are seeing here is the standard Angular behavior where a function being part of a binding will be called on each and every change detection cycle (we [are subscribing](https://github.com/ng-bootstrap/ng-bootstrap/blob/d7722ade75895d5775788b5282ee7a682a038404/src/typeahead/typeahead-window.ts#L30) to `mouseenter` to properly handle `active` class).

What you see here is how Angular works - we can't do much about it here in this library. Just make sure that your formatter function is small, fast and doesn't have side effects - with all this you should be fine.
