### ISSUE TITLE
ngbDatepicker overflow=auto

### ISSUE THREAD

**Issue by sv0505** [ng-bootstrap/ng-bootstrap#1346]
When ngbDatepicker inside container with overflow=auto, it showed inside container instead over top.

http://plnkr.co/edit/Qtx9I3cXlekuFsS01fHB?p=preview

```
<div class="form-group" style="height: 200px; width: 500px; background-color: aqua; overflow: auto">
    <div class="input-group">
      <input class="form-control" placeholder="yyyy-mm-dd"
             name="dp" [(ngModel)]="model" ngbDatepicker #d="ngbDatepicker">
      <div class="input-group-addon" (click)="d.toggle()" >
        <img src="img/calendar-icon.svg" style="width: 1.2rem; height: 1rem; cursor: pointer;"/>
      </div>
    </div>
  </div>
```

**Comment by pkozlowski-opensource** [comment]
We would have to add a feature like `appendToBody` to support this scenario properly. Marking as a feature request.

**Comment by pkozlowski-opensource** [comment]
This is the same as #1380 so I'm going to close this one as a duplicate. Going to keep #1380 since it has more detailed description and a plunker that illustrates the issue.

Please subscribe to #1380 for updates.
