### ISSUE TITLE
New feature request - Slider

### ISSUE THREAD

**Issue by natcohen** [ng-bootstrap/ng-bootstrap#1350]
Maybe it's out of scope and I should post that on bootstrap directly (sorry in advance) but is it possible to add a slider? Bootstrap has been built with "mobile first" in mind so I'm very surprised there are no slider or toggle (which are key components!)

**Comment by pkozlowski-opensource** [comment]
> Maybe it's out of scope and I should post that on bootstrap directly 

Yes, we should start this discussion on Bootstrap side. If Bootstrap guys determine that there is a need for a new control / CSS _and_ custom JS is needed to make those "live" than we can add support for those new elements on the ng-bootstrap side. But the first step should be on Bootstrap's side.

Closing till things are sorted out on the CSS side.

**Comment by natcohen** [comment]
@pkozlowski-opensource Should I post the issue on bootstrap github or it's not necessary?

**Comment by pkozlowski-opensource** [comment]
> Should I post the issue on bootstrap github or it's not necessary?

Well, if you need and care about this addition you should.
