### ISSUE TITLE
ease in and out caoursel

### ISSUE THREAD

**Issue by AhadCove** [ng-bootstrap/ng-bootstrap#1351]
I can't find any information on how to modify how the carousel changes slide. Typically I would like to have it either fade in and out or slide to the left

**Comment by pkozlowski-opensource** [comment]
Duplicate of #295 - we don't support animations just yet.

**Comment by BaronChen** [comment]
Just in case you need a work around, check this: http://stackoverflow.com/questions/42567906/animation-for-carousel-with-ng-boostrap-and-angular-2

**Comment by AhadCove** [comment]
Thank you, this is exactly what I was looking for
