### ISSUE TITLE
 Backdrop adds to the parent

### ISSUE THREAD

**Issue by omprakash9** [ng-bootstrap/ng-bootstrap#1352]
### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.4.5

ng-bootstrap: 1.0.0-alpha.16

Bootstrap: 4.0.0-alpha.4

**Comment by pkozlowski-opensource** [comment]
See and #643 and https://github.com/ng-bootstrap/ng-bootstrap#getting-help
