### ISSUE TITLE
Feature request: datatable

### ISSUE THREAD

**Issue by beaverusiv** [ng-bootstrap/ng-bootstrap#1353]
As far as I can tell there is nothing like a datatable currently? I was wondering if this was something that could possibly be added to the project? I will be implementing one for a project I'm working on and it would be nice to know to either wait until one is ready or if I should make sure I can clean my one for inclusion here.

**Comment by pkozlowski-opensource** [comment]
Thnx for the suggestion but we are not planning on adding any datatable components as part of this project.

**Comment by brunoviek** [comment]
any table with filtering to suggest?

**Comment by PierreRochard** [comment]
@brunoviek I wish they would reconsider. But you can check out PrimeNG's
