### ISSUE TITLE
[Dropdown in a form] Enter keypress open dropdown

### ISSUE THREAD

**Issue by theomathieubhvr** [ng-bootstrap/ng-bootstrap#1355]
### Bug description:
Hey,

When i create a ngbDropdown into a form, if another input field is focused and I press enter, the dropdown is opened. The form should be submitted.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/0NQGN2ppCSxsa8T42cbP?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.4.6

ng-bootstrap: 1.0.0-alpha.20

Bootstrap: 4.0.0-alpha.6

Thanks !

**Comment by pkozlowski-opensource** [comment]
It is because a default type of a `<button>` is `submit` in all browsers apart from IE. You need to specify `type="button"` if you don't want to have random buttons act as submit buttons: http://plnkr.co/edit/BgfM8OgmnHtQ4ti2jeuN?p=preview

Closing as a support request.
