### ISSUE TITLE
ngb-carousel Slide event

### ISSUE THREAD

**Issue by shabbir-dhangot** [ng-bootstrap/ng-bootstrap#1356]
### Bug description:
ngb-carousel Slide event. I am trying to get it with 
`<ngb-carousel [interval]="slideInterval" (on-carousel-change)="onSlideChanged()">` But not working

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
2.3.1
ng-bootstrap:
1 alpha 20
Bootstrap:
4 beta 6

**Comment by pkozlowski-opensource** [comment]
See #1331
