### ISSUE TITLE
Disable carousel autoplay?

### ISSUE THREAD

**Issue by fishgills** [ng-bootstrap/ng-bootstrap#1359]
I'd like a way to disable a carousel autoplay either through configuration or directive options. Is this already possible?

**Comment by jnizet** [comment]
You can just set the interval of the carousel (or its config service) to 0.

**Comment by SammyRigan** [comment]
Just add **data-interval="false"** to the ngb-carousel tag in the template like so.

`<ngb-carousel data-interval="false"></ngb-carousel>`

**Comment by ester-k** [comment]
<ngb-carousel interval="false"></ngb-carousel>

not data-interval

**Comment by ester-k** [comment]
write : interval="false"

**Comment by basilio** [comment]
for version 13.0.0

` [interval]="0"`

because interval only accept number
