### ISSUE TITLE
Dismiss NgbModel Manually

### ISSUE THREAD

**Issue by shabbir-dhangot** [ng-bootstrap/ng-bootstrap#1360]
### Bug description:

Dismiss NgbModal manually.  I am not able to dismiss it. 

Angular:
2.3.1
ng-bootstrap:
1.0.0. alpha 20
Bootstrap:
v4 alpha 6

**Comment by pkozlowski-opensource** [comment]
https://github.com/ng-bootstrap/ng-bootstrap#getting-help
