### ISSUE TITLE
typeahead: first selection unresponsive

### ISSUE THREAD

**Issue by PerfectPixel** [ng-bootstrap/ng-bootstrap#1361]
### Bug description:
With Angular 4 RC2 selecting an element is unresponsive if clicking on the element's text. Clicking on the padding around the text, the dropdown works as expected. Moving to another element after clicking on an unresponsive element works and all elements become responsive. Also leaving the dropdown with the mouse and reentering makes all elements responsive again. Clicking very slowly or waiting does not help.

The error does not occur every time, sometimes the dropdown is completely responsive.

The error does not necessarily affect the first element in the dropdown, but may affect any other element.

Looking at the dev tools, you'll notice that all elements are redrawn on click and the result formatter is called.

Reverting to Angular 2.4.9 resolves the issue.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/732iJnG0H2OS1EeChel5?p=preview

### Video

![typeahead](https://cloud.githubusercontent.com/assets/2388847/23751989/df40f2fe-04d3-11e7-888f-4e3c3231c59c.gif)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.0-rc.2

ng-bootstrap: 1.0.0-alpha.20

Bootstrap: 4.0.0-alpha.6

Browsers: Safari 10.0.3 & Chrome 56 (Firefox works)

**Comment by Adnan-Ahmethodzic** [comment]
Clicks are being registered as 'mouseenter' events, maybe some render loop of the first selection?

**Comment by maxokorokov** [comment]
By the way I can't reproduce the issue if I change to 4.0.0 in the plunker

**Comment by PerfectPixel** [comment]
I can confirm that I do not experience this issue in the final 4.0.0 anymore. Looks like an 4.0.0-rc.2 regression.
