### ISSUE TITLE
Checkbox buttons does not work

### ISSUE THREAD

**Issue by ialex90** [ng-bootstrap/ng-bootstrap#1365]
Hi there,

I didn't want to open this ticket but I see myself forced to do it.

I am using the checkbox buttons and they don't work. I copied the code (TS) and the markup (HTML) and it doesn't change the values of the ngModel.

I am pretty sure is something either out of my scope or something missing from my side, but I am almost sure that is out of my scope (framework internal issue)

I am very sorry if this is not correct, but it does not change the model values. The versions used is     
"@ng-bootstrap/ng-bootstrap": "1.0.0-alpha.20"

I have attached an image to show the error.

I can not replicate this on the plunk sticked to the Documentation because in there, it works.

http://imgur.com/a/fxDm7

Sorry for the inconveniences, let me know If i can help to detect/fix this problem,

Thanks

**Comment by pkozlowski-opensource** [comment]
We do _not_ have implementation of check-box widget! We just show how you can have ones working _without_ any custom directives. As such there is nothing we can "fix". Maybe the only thing would be to "fix" documentation but we can only do so when we know what is going on...

Here is a plunker forked from our documentation page: http://plnkr.co/edit/0vrH1gqWooqKhzrLx8hp?p=preview - compare this plunker with your setup. Maybe you are including Bootstrap's JavaScript (which is unnecessary and can have side effects)?

Once again, we can't help much without a minimal reproduce scenario....

**Comment by ialex90** [comment]
I am not adding bootstrap js. Anyway, I will do my implementation, removing the data toggle and playing with css.

I understand what you say, I honestly thought this might be helpful for me and someone else but not gonna lose more time on it and just fix it by css.

**Comment by ialex90** [comment]
Hi @pkozlowski-opensource, sorry to open the ticket again, just to make sure you get this message. You can close it if you consider it necessary.

Regarding to this issue, I am facing a problem copying and pasting the sample from the documentation for a date picker component, and it does not work, it looks corrupted but no error on console.

My solution is going to alpha 16 and the problem is gone. I am just leaving this comment for you to know/test or someone else what I experienced.

If it helps, this is my package.json before I went to alpha 16 version of this framework:

```
{
  "dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/router": "3.4.8",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-alpha.20", // Happening the same to alpha.21
    "angular-cli": "1.0.0-beta.28.3",
    "animate.css": "3.5.2",
    "automapper-ts": "1.8.1",
    "awesome-typescript-loader": "3.0.8",
    "bootstrap": "4.0.0-alpha.5",
    "chart.js": "2.5.0",
    "core-js": "2.4.1",
    "font-awesome": "^4.7.0",
    "jquery": "3.1.1",
    "karma-phantomjs-launcher": "1.0.2",
    "ng2-adal": "^0.2.8",
    "ng2-charts": "1.5.0",
    "ng2-pagination": "1.0.1",
    "reflect-metadata": "0.1.8",
    "rxjs": "5.2.0",
    "signalr": "2.2.1",
    "systemjs": "0.19.39",
    "ts-helpers": "1.1.1",
    "typescript": "2.2.1",
    "typings": "2.1.0",
    "underscore": "1.8.3",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@types/core-js": "0.9.35",
    "@types/jasmine": "2.5.41",
    "@types/underscore": "1.7.36",
    "codelyzer": "3.0.0-beta.3",
    "del": "2.2.1",
    "gulp": "3.9.1",
    "gulp-fail": "1.0.5",
    "gulp-sass": "2.3.2",
    "gulp-zip": "3.0.2",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.0.2",
    "karma-remap-istanbul": "0.2.1",
    "protractor": "4.0.13",
    "ts-node": "1.2.1",
    "tslint": "4.5.1"
  }
}
```

**Comment by pkozlowski-opensource** [comment]
> I am just leaving this comment for you to know/test or someone else what I experienced.

@ialex90 I'm sorry but we can't do much with this info... If you need help / think that you've found a bug you  need to prepare a minimal reproduce scenario using plunker or similar. Here is why:  https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help

I'm going to close this one since:
* I can't see anything actionable here;
* this ticket starts to be about many things (started with buttons, now datepicker) but without the details. 

Please open a new issue when you've got a reproduce scenario in a plunker. Thnx!
