### ISSUE TITLE
Angular 4.0.0 RC.3 breaking change 

### ISSUE THREAD

**Issue by spock123** [ng-bootstrap/ng-bootstrap#1367]
Hey guys,
- RC.3 of Angular 4.0.0 is out and it looks like there are some breaking changes introduced:

```
rename RendererV2 to Renderer2
rename RendererTypeV2 to RendererType2
rename RendererFactoryV2 to RendererFactory2
```

This creates errors when compiling with ng-bootstrap alpha-20:

```
ERROR in [at-loader] compiled/node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory.ts:13:42 
    TS2694: Namespace '"/Users/spock/project/dba/dba-frontend/node_modules/@angular/core/typings/core"' has no exported member 'RendererTypeV2'.

ERROR in [at-loader] compiled/node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory.ts:101:40 
    TS2694: Namespace '"/Users/spock/project/dba/dba-frontend/node_modules/@angular/core/typings/core"' has no exported member 'RendererTypeV2'.

ERROR in [at-loader] compiled/node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker-day-view.ngfactory.ts:11:54 
    TS2694: Namespace '"/Users/spock/project/dba/dba-frontend/node_modules/@angular/core/typings/core"' has no exported member 'RendererTypeV2'.

ERROR in [at-loader] compiled/node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker-day-view.ngfactory.ts:28:52 
    TS2694: Namespace '"/Users/spock/project/dba/dba-frontend/node_modules/@angular/core/typings/core"' has no exported member 'RendererTypeV2'.

```

**Comment by spock123** [comment]
I'm sorry - I think was went too fast there - will try to clear things up.. it's not an ng-bootstrap issue I think.. closing for now..

**Comment by spock123** [comment]
Update - FYI - it was my build that was the problem.
My previously compiled code did somehow not get cleared before I compiled RC3 code.

Please accept my apologies :)

**Comment by fgcui1204** [comment]
hello @spock123 , How do you resolve this problem. I get the same issue
```
ERROR in /zipkin-ui/node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead.d.ts
(1,99): error TS2305: Module '"/zipkin-ui/node_modules/@angular/core/index"' has no exported member 'Renderer2'.
```

**Comment by spock123** [comment]
Hi @fgcui1204 
Yes I cleared my npm cache (npm cache clean), removed node_modules, removed my aot compile folder.

Then reinstalled

Let me know if you get it to work

**Comment by lukiffer** [comment]
@spock123 Thank you so much! I literally spent the last 2 hours Googling obscure NgModuleInjector errors trying to figure this out, only to read your reply and realize my AOT folder wasn't being cleaned.

**Comment by spock123** [comment]
@lukiffer Sounds great! Good to know, cheers
