### ISSUE TITLE
Tooltips not positioned properly

### ISSUE THREAD

**Issue by marcinmajkowski** [ng-bootstrap/ng-bootstrap#1371]
### Bug description:

Tooltips are not positioned properly in some cases, e.g. when attached to short elements inside narrow containers, when attached to right-aligned elements etc.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/qcOWQRRBRLNdKlFQyCBw?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.3.1

ng-bootstrap: 1.0.0-alpha.20

Bootstrap: 4.0.0-alpha.6

**Comment by adammedford** [comment]
As a temporary fix, I've found setting container to body generally fixes this issue.
