### ISSUE TITLE
feat (datepicker): add option to highlight system date

### ISSUE THREAD

**Issue by sousarka** [ng-bootstrap/ng-bootstrap#1375]
Is it possible to add an option to pass system date to DayTemplateContext. It can be used to highlight the system date if needed.

**Comment by pkozlowski-opensource** [comment]
Don't think it is necessary as templates "see" variables from the enclosing component (component in which template a `<template>` tag is present.

But TBH I'm not sure what is your exact use case so hard to say more given the very minimal info here...

**Comment by sousarka** [comment]
@pkozlowski-opensource . You're correct. I was trying to use a generic custom template for the entire application and trying to highlight system date for all in a generic way.
