### ISSUE TITLE
How to make the modal can be dragged.

### ISSUE THREAD

**Issue by Csirme** [ng-bootstrap/ng-bootstrap#1378]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:2.4

ng-bootstrap:

Bootstrap:

i want to know ...thanks

**Comment by wesleycho** [comment]
@pkozlowski-opensource is this a feature we could consider supporting by allowing users to hook in custom directives? The way we use the component ref seems to suggest this would be an impossible feature for a user to use with our modals. This is mainly due to the fact that the NgbModalWindow is a component with a template.

In order to support something like this, we would need to allow users to provide their own custom implementation of a component that works like NgbModalWindow. Is this worth considering adding support for in the library? This doesn't sound unreasonable to me, although it's a non-trivial amount of work.

**Comment by AlexKhymenko** [comment]
@wesleycho Any progress on this issue?

**Comment by elsticky** [comment]
Also would like support for this :)

**Comment by nikitalpopov** [comment]
Is there any way to make modals draggable with [@angular/cdk](https://material.angular.io/cdk/drag-drop/overview)? To achieve this I should add `cdkDrag` inside element with `class='modal-content'` but I have no clue how to do this when I call NgbModal service:  
```const modalRef = this.modalService.open(SomeModalComponent);```
[NgbModalOptions](https://ng-bootstrap.github.io/#/components/modal/api#NgbModalOptions) provides functionality to add class only but not attribute directive.

**Comment by borisBelloc** [comment]
I try to make ngb-Modal draggable since two day and can't find any solution 👎 

Google sent me here because i had the same question as nikitalpopov;

> NgbModalOptions provides functionality to add class only but not attribute directive.

Any body got any idea how to do it ?

**Comment by ranoy** [comment]
doable wih @angular/cdk and add following directives to root div of component/ng-template:
<div cdkDrag cdkDragRootElement=".modal-content" cdkDragBoundary=".modal">
 .... modal content
</div>

**Comment by GregoireLgt** [comment]
> doable wih @angular/cdk and add following directives to root div of component/ng-template:
> 
> .... modal content

@ranoy Hi, when i do this, the body of the modal is draggable, but not the rest (header and background are not remain at the same place)

**Comment by ranoy** [comment]
@GregoireLgt 
May be you need to move the directives to the container div of the whole content . I have something like this which works fine 
<div class="base-dialog" cdkDrag cdkDragRootElement=".modal-content" cdkDragBoundary=".modal">
  <div class="modal-header">
    <h4 class="modal-title">{{title}}</h4>
    <button type="button" class="close btn btn-icon-action" aria-label="Close"
      (click)="activeModal.dismiss('Cross click')">
      <span aria-hidden="true" class="apticons apticons-close"></span>
    </button>
  </div>
  <div class="modal-body">
    
  </div>
  <div class="modal-footer">
    
  </div>
</div>
