### ISSUE TITLE
container Option for NgbInputDatepicker

### ISSUE THREAD

**Issue by ramiusGitHub** [ng-bootstrap/ng-bootstrap#1380]
### Bug description:

The popup of the Datepicker is (partially) hidden if the surrounding container is too small and has overflow: hidden. Is it possible to add an "append-to-body" or "container" option like NgbTooltip has?

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/uVdkPs6jHQQvw0kFHywi?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.4.0

ng-bootstrap: 1.0.0-alpha.19

Bootstrap: 4.0.0-alpha.6

**Comment by MehdiSaeedifar** [comment]
Any progress?

**Comment by dansoper** [comment]
This would also be useful for me, as I have a problem with datepicker and overflow.

**Comment by rameshrathinappa** [comment]
Waiting for 1.0.0-beta.6 version to see the datepicker popup appending to body. 👍

**Comment by pkozlowski-opensource** [comment]
It should be relatively small code change, similar to the one we did for typeahead: https://github.com/ng-bootstrap/ng-bootstrap/commit/bc3fd614adbb1e0863bd8c39535ad17d2901ea58

**Comment by ibraheemalkilanny** [comment]
So the solution is to use `container='body'` ??

**Comment by saiyaff** [comment]
`<input type="text" ngbDatepicker container="body" (dateSelect)="onDateSelect($event)" />`
Setting the container to the body doesn't fire the dateSelect event when the date is selected over a mouseclick. Any solution?

**Comment by MarFelix** [comment]
Me funciono `container="body"`
