### ISSUE TITLE
AOT compilation fails

### ISSUE THREAD

**Issue by alex88** [ng-bootstrap/ng-bootstrap#1381]
I'm trying to build a project with angular AOT and ng-boostrap, however ng-bootstrap throws these errors during compilation

```
ERROR in Could not resolve "./src/app/app.module" from "./src/app/app.module".

ERROR in ./$$_gendir/~/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory.ts
Module parse failed: /Users/alex/Sites/project-api/frontend/$$_gendir/node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory.ts Unexpected token (23:27)
You may need an appropriate loader to handle this file type.
| import * as import13 from '@angular/common/src/directives/ng_if';
| export class Wrapper_NgbAlert {
|   /*private*/ _eventHandler:Function;
|   context:import0.NgbAlert;
|   /*private*/ _changed:boolean;
 @ ./$$_gendir/src/app/app.module.ngfactory.ts 82:15-106
 @ ./src/main.ts
```

other libraries seems to not have any issue, I'm also trying to see why it actually tries to compile ts code from an external library, which shouldn't right?

**Comment by alex88** [comment]
Nvm I've probably fixed it

**Comment by alienlike** [comment]
@alex88 I'm having the same issue. How did you fix yours?

**Comment by alex88** [comment]
@alienlike i don't really remember, maybe changed some webpack settings to make typescript compiler exclude node modules folder
