### ISSUE TITLE
diable past date according to today's date. Possible?

### ISSUE THREAD

**Issue by peterhe2000** [ng-bootstrap/ng-bootstrap#1388]
Is there a way to disable past date according to today's date?

Angular:2.4.10

ng-bootstrap:1.0.0-alpha.21

Bootstrap:4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
Sure, just implement `markDisabled`: https://ng-bootstrap.github.io/#/components/datepicker

Anyway, this question doesn't belong here so closing: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
