### ISSUE TITLE
Modal not working with *ngIf

### ISSUE THREAD

**Issue by xonuzofa** [ng-bootstrap/ng-bootstrap#1394]
### Bug description:

Does not work when used with *ngIf, only works with hidden.  What I mean by does not work is that it shows the backdrop but the modal does not pop up.  It is at the bottom of the page with nothing in the title or body.  The modal-container in html element inspector does not contain the classes "modal fade show".

component.html:

    <button [hidden]="file.status !== 'Retrieved'" type="button" class="btn btn-danger" (click)="delete(i)">Delete</button> //Works

    <button *ngIf="file.status === 'Retrieved'" type="button" class="btn btn-danger" (click)="delete(i)">Delete</button> //Does not work

component.ts:

    delete(index: number) {
        this.dialogService.confirm('Are you sure you want to delete this file?').then(confirm => {
            // Do db stuff
        }, cancel => {});
    }

dialogservice.ts:

    confirm(msg: string) {
        const modalRef = this.modalService.open(DialogConfirmContent);
        modalRef.componentInstance.title = "Confirm";
        modalRef.componentInstance.body = msg;
        return modalRef.result;
    }

**Comment by pkozlowski-opensource** [comment]
I'm sorry but it is not clear what your problem might be given its current description. Please follow the issue template and provide a minimal reproduction scenario in a plunker or similar. Without additional info this is not actionable and will be closed. More info in: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment]
I'm going to close this one as we don't have sufficient info to understand / reproduce and we haven't heard back from the opener. Happy to re-open when / if we've got a reproduce scenario.

**Comment by tawfiek** [comment]
I have the same  issue my modal is works fine unitl I add a div with *ngIf directive  
`<div class="alert alert-danger"  *ngIf="myCondtion" role="alert">this field is required </div>`
it appear in the bottom of the page

**Comment by daniellittledev** [comment]
Some info that might help, I encountered this issue and was able to resolve it by ensuring the value was a boolean.

The code change for me was from:

`*ngIf="a.b.show"`

to:

`*ngIf="!!(a.b&& a.b.show)"`

**Comment by Devendra0110** [comment]
For me adding brackets was enough.
