### ISSUE TITLE
Ratings on iOS need to be double tapped to change the rate value. The first tap is considered hover

### ISSUE THREAD

**Issue by sarahsga** [ng-bootstrap/ng-bootstrap#1395]
### Bug description:
Component: Rating
Platform: iOS 
Bug: Rating icons need to be double tapped to trigger a click event on them. Commonly known as "[iOS double tap issue](https://css-tricks.com/annoying-mobile-double-tap-link-issue/)". The first tap is interpreted as hover in Apple mobile devices. 

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/?p=preview
Please run the above code on an iOS device. The first tap on the star will not change the value of rate (because it will be interpreted as hover). Tap the same star again, and the rate will change.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: ^2.3.1

ng-bootstrap: ^1.0.0-alpha.20

Bootstrap: ^4.0.0-alpha.6

**Comment by brejw** [comment]
@sarahsga I run the same problem, do you have solution?
