### ISSUE TITLE
[ngbPopover]="list.length > 0 ? popContent: null" displays tooltip arrow when the length is 0

### ISSUE THREAD

**Issue by anrepppp** [ng-bootstrap/ng-bootstrap#1399]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.4.5

ng-bootstrap: 1.0.0-alpha.16

Bootstrap: 4.0.0-alpha.4

**Comment by pkozlowski-opensource** [comment]
Please provide a minimal reproduce scenario in a plunker as requested in the issue template, otherwise it is not actionable and will be closed.

**Comment by anrepppp** [comment]
Looks the i need to upgrade 
ng-bootstrap to 1.0.o-alpha.21
and Bootstrap: 4.0.0-alpha.4.
