### ISSUE TITLE
AoT compilation fails with modal-backdrop ngfactory

### ISSUE THREAD

**Issue by orestisioakeimidis** [ng-bootstrap/ng-bootstrap#1403]
Hi,

I am getting this error when trying to use AoT compilation.

`aot/node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-backdrop.ngfactory.ts (82,11): 'parentRenderNode' is declared but never used.`

I am using the `@ngtools/webpack - 1.3.0` for the compilation process.

Any idea why is this happening?

Angular: **2.4.10**
ng-bootstrap: **1.0.0-alpha.22**
Bootstrap: **4.0.0-alpha.6**

Thanks in advance!

**Comment by pkozlowski-opensource** [comment]
Hard to say as we've got our demo page working just fine with AOT. Could you please prepare a minimal reproduce repo?

**Comment by pkozlowski-opensource** [comment]
BTW, are you sure that `@ngtools/webpack` is compatible with Angular: 2.4.10? I've got it working just fine here with ngtools 1.2.3: https://github.com/pkozlowski-opensource/core/tree/aot_2_4_10

Given that it works on our side and that the component in question is very simple we can't progress without a minimal reproduce scenario. In any case I think it is more of the setup / angular issue as once again, the backdrop component is minimal: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/modal/modal-backdrop.ts

**Comment by orestisioakeimidis** [comment]
It is probably a configuration issue which I have to dive into. Thanks for your input! I am closing this issue...
