### ISSUE TITLE
ng-bootstrap for Javascript

### ISSUE THREAD

**Issue by Weestdudochnicht** [ng-bootstrap/ng-bootstrap#1411]
would it be possible to use ng-bootstrap with Javascript or is it allready possible?

**Comment by pkozlowski-opensource** [comment]
Not sure what you mean. Could you elaborate?

**Comment by Weestdudochnicht** [comment]
HI,
my Problem is that i write my angular app in javascript. bevor i used UI Bootstrap and bootsrap 3.*. now i upgraded on Bootstrap 4 and i wanna useng-Bootstrap, but my Problem here is that u wrote it with TypeScript and i dont know how to import it into my application. So i asked for a javascript version of ng-Bootstrap.

**Comment by pkozlowski-opensource** [comment]
You can use ng-bootstrap with JavaScript perfectly fine as we distribute this library in both ES6 and ES5 format (bundle). The exact way of importing / using this library will depend on your particular setup (transpiler / packager) and describing it is beyond the scope of the issue tracker, see: https://github.com/ng-bootstrap/ng-bootstrap#getting-help

Having said all the above we are not documenting anything else than TS as we believe that using TS gives you superior experience with Angular 2+ and we want to promote TS usage while discourage JS.
