### ISSUE TITLE
Angular4 upgrade- Template warning

### ISSUE THREAD

**Issue by rodneyjoyce** [ng-bootstrap/ng-bootstrap#1413]
Hi, everything works great after upgrading to ng4, however there are some warnings as the code still uses template.

### Bug description:
After ng4 upgrade I now get the warning:  "The <template> element is deprecated. Use <ng-template> instead. 

### Version of Angular, ng-bootstrap, and Bootstrap:
ng4.0.0
ng-bootstrap  v1.0.0-alpha.22

**Comment by willyelm** [comment]
I have created a pull request #1414, you can use my fork meanwhile instead.

**Comment by pkozlowski-opensource** [comment]
See https://github.com/ng-bootstrap/ng-bootstrap/issues/1337#issuecomment-288971917

**Comment by rodneyjoyce** [comment]
Thanks
