### ISSUE TITLE
Modal not showing on Angular 2.4 and 4.

### ISSUE THREAD

**Issue by eestein** [ng-bootstrap/ng-bootstrap#1420]
### Bug description:

Modal is not showing anymore after re-targeting web app to `angular 4` and `@angular/cli@1.0.0`.

I was just going to look for another lib (since this one technically does not support my bootstrap version), but when I read this https://github.com/ng-bootstrap/ng-bootstrap/issues/1209 I decided to post here. Maybe it's a bug or something changed. Anyway, this code was working:

```typescript
let modal: NgbModalRef = this.modalService.open(this.config.createModal);
let modalInstance: BaseModal = modal.componentInstance as BaseModal;
```

where `this.config.createModal` is a component. Even though this lib does not officially support bootstrap 3, it was working fine for quite some time. But now it looks like the modal was opened but it's not displayed. The body class `modal-open` is added:

![screen shot 2017-03-30 at 08 48 31](https://cloud.githubusercontent.com/assets/2049255/24502801/b0dc6b84-1525-11e7-8016-f9b1a2bce454.jpg)

The scrollbar disappears and the component's (modal's component) onInit method is hit. So I'm assuming is something related only to the visual component not being displayed.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.0 (though I tried with 2.4 as well)

ng-bootstrap: 1.0.0-alpha.22

Bootstrap: 3.3.7

**Comment by pkozlowski-opensource** [comment]
@eestein your "issue" has nothing to do with Angular version - ng-bootstrap works perfectly fine with Angular 2.x and 4.x. But you are using Bootstrap 3.3.7 and we are _very_ clear about supporting Bootstrap 4.x only. I know that this might be something you are not thrilled to hear but here is our current reasoning:  https://github.com/ng-bootstrap/ng-bootstrap/wiki/Why-Bootstrap-4-only%3F

We are open to discussing Bootstrap 3 support but at the same time want to be very clear that at this point:
* we don't know of a good technical solution for maintaining 2 versions of templates for a given component;
* we don't have free cycles to take on this work.

Happy to add Bootstrap 3 if there is a good technical solution and people from the community step in.

**Comment by eestein** [comment]
@pkozlowski-opensource sure, that's why I said I know it's not supported. The thing is, it worked before and it stopped working now. I was using the same bootstrap version, 3.3.7 and it was working. It was only after updating my libs that it stopped... but that I'll give you, it might have not been angular, might've been another lib that after updated messed with the modal, but I assure you it was working before :)

Thanks anyway.

**Comment by pkozlowski-opensource** [comment]
It might have worked before but Bootstrap 4 renamed a couple of CSS class names in alpha.6 and we've followed with the updates on the ng-bootstrap side. But then again, even if it "worked", it was just by accident.

Also a word of warning - evaluate libraries that claim support for multiple Bootstrap versions - in some cases it is done in a very hacky way where you essentially get code for _both_ versions even if you use just one... Not great for perf, obviously....

**Comment by eestein** [comment]
@pkozlowski-opensource 

>But then again, even if it "worked", it was just by accident.

I truly believe that, it doesn't change the fact it did and now I'm downgrading version by version to find out which one did   🤣 🤣  (I wanna continue using it, since you seem to have the only lib that provides support for modal service - something I need)

> Also a word of warning - evaluate libraries that claim support for multiple Bootstrap versions - in some cases it is done in a very hacky way where you essentially get code for both versions even if you use just one... Not great for perf, obviously....

yeah... I don't wanna move away, but until the template I use supports BS4 I'm kinda stuck :/

Thanks for your time man :)

**Comment by pkozlowski-opensource** [comment]
You might try alpha.17 as this is the last version before we've switched to Bootstrap 4 alpha.6: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#100-alpha17-2017-01-09

**Comment by eestein** [comment]
awesome! I will, thanks! :)

**Comment by eestein** [comment]
@pkozlowski-opensource OH YEAH :D   

![screen shot 2017-03-30 at 14 32 47](https://cloud.githubusercontent.com/assets/2049255/24517752/cfe81b4c-1555-11e7-88f5-1b9880b15bb0.jpg)


thank you kind sir, that was the one!!! It's working again 🍾

**Comment by eestein** [comment]
![screen shot 2017-03-30 at 14 34 23](https://cloud.githubusercontent.com/assets/2049255/24517794/0365aa3e-1556-11e7-9285-bc8fcd28ef61.jpg)

**Comment by dexterBEN** [comment]
Good Morning i know this is a old post but i faced the same issue and don't no how to upgrade my bootstrap version to alpha 6.

English is not my mother tongue be comprehensive.

**Comment by eestein** [comment]
@dexterBEN hey, you need to change your bootstrap version to v3.3.7 and the ng-bootstrap to alpha.17.  

In order to do so, open your packages.json file and remove the symbols "[^|~]" before changing the version. If anything, post your pacakges.json here.

Good luck!

**Comment by dexterBEN** [comment]
Good morning, thanks for your answer, this is the JSON`"dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@kube-deployer/types": "^1.0.0-beta.2",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0",
    "@ngx-translate/core": "^9.0.0",
    "bootstrap": "^4.0.0",
    "core-js": "^2.0.0",
    "intl": "^1.0.0",
    "reflect-metadata": "^0.1.12",
    "rxjs": "^5.0.0",
    "ts-helpers": "^1.0.0",
    "whatwg-fetch": "^2.0.0",
    "zone.js": "^0.8.0"
  },`

**Comment by eestein** [comment]
Try changing `"bootstrap": "^4.0.0"` for `"bootstrap": "3.3.7"` and "@ng-bootstrap/ng-bootstrap": "^1.0.0" to `"@ng-bootstrap/ng-bootstrap": "1.0.0-alpha.17"`. 

BUT!

Bootstrap 4.1 is already final and ng-bootstrap seems to be working perfectly fine with v4. Since you ARE using v4 already it might be better to try leaving `"bootstrap": "^4.0.0"` the way it is and changing "@ng-bootstrap/ng-bootstrap": "^1.0.0" to `"@ng-bootstrap/ng-bootstrap": "^2.0.0"`

**Comment by dexterBEN** [comment]
Thanks i'm trying right now

**Comment by dexterBEN** [comment]
I'm trying the two options you proposed but i don't have any result, besides no error in browser console.

Just when i triggered the modal, i can see this activation but the card don't display, like this:

![image](https://user-images.githubusercontent.com/33292824/40487046-44e50c0e-5f63-11e8-85cf-d9a9f75c39d3.png)

**Comment by dexterBEN** [comment]
As you can see below the screen become black, in order to activate the modal, but dont display the card or content

**Comment by eestein** [comment]
@dexterBEN it might be nice to check your console errors, I can see 4 there.
