### ISSUE TITLE
some demos are broken in plnkr

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#1422]
### Bug description:

When launching the "Self-Closing Alert" demo in plnkr, it fails with the following error:

```
TypeError: this._success.debounceTime is not a function
```

When launching the "Progress bars with current value labels" demo in plnkr, it fails with the following error:

```
ZoneAwareError. Error: (SystemJS) Unexpected value 'undefined' declared by the module 'AppModule' 
```

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/OT2BUpJ0qhRh2Lr0cZ99?p=preview
http://plnkr.co/edit/oItY6M1mLGQ6fbk0FKhC?p=preview

(but they've just been obtained by clicking on the Plnkr icons in the demos, and saving the plnkr).

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.3.1

ng-bootstrap: 1.0.0-alpha.22

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
Good catch @jnizet ! Fancy a PR?

**Comment by jnizet** [comment]
I can fix the self-closing demo easily (it's just a missing import). But I have no clue why the progress bar demo fails.

**Comment by pkozlowski-opensource** [comment]
> But I have no clue why the progress bar demo fails.

It is the demo class name: there is a difference in the class name - imports are generated automatically for plunkers so we need to rename the demo class.

**Comment by jnizet** [comment]
Thanks. I found that, too. Implementing a fix.
