### ISSUE TITLE
collapse component: When using @angular/cli css shows class="collapse show"

### ISSUE THREAD

**Issue by javaspeak** [ng-bootstrap/ng-bootstrap#1428]
### Bug description:

I am integrating the collapse component into an @angular/cli created project following the instructions in the demo. 

When I run the project by using "ng serve",  I see:

     app works!
     Toggle button

But I do not see the text:

     You can collapse this card by clicking Toggle

When I inspect the html I see:

    ...
    <div id="collapseExample" class="collapse show" aria-expanded="true">
        <div class="card">
     ... e.t.c

Notice above that class="collapse show".

Instead it should just have "show" in it.

### Link to minimally-working plunker that reproduces the issue:

As I am using @angular/cli I cannot add my example to plunker.  I apologise for that.

(By the way I have successfully integrated other components like alert, accordion, button, carousel - this leads me to think that the problem is not because I forgot to edit a file - for example I did not forget to add the following to my .angular-cli.json:

    "styles": [
        "styles.css",
        "../node_modules/bootstrap/dist/css/bootstrap.css"
      ],

As I am using an @angular/cli project I have removed the node_modules directory and zipped the project.  See attached  ngb-collapse.zip 

Make sure you have @angular/cli installed globally:

    sudo npm install -g @angular/cli
   
Then you can unzip the attached ngb-collapse and run: 

      npm install bootstrap@4.0.0-alpha.4
      npm install
      npm install --save @ng-bootstrap/ng-bootstrap
      ng serve

Then you can navigate to:

     http://localhost:4200/

And you will see the text:

     app works!
    
and a Toggle button, but you will not see the text:

    "You can collapse this card by clicking Toggle"

The reason for the text not showing is a css problem as described above in the bug description.

[ngb-collapse.zip](https://github.com/ng-bootstrap/ng-bootstrap/files/889560/ngb-collapse.zip)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:  2.4.0

ng-bootstrap:    @ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.22

Bootstrap:    bootstrap@4.0.0-alpha.4

**Comment by pkozlowski-opensource** [comment]
You need to use the latest  bootstrap@4.0.0-alpha.6. Also we can't investigate issues without an associated plunker - you should be able to create one, cli or not. You can start with this one (forked from our demo page):  http://plnkr.co/edit/JTlT16SFvGF25K36ZubX?p=preview

**Comment by pkozlowski-opensource** [comment]
> Instead it should just have "show" in it.

Why are you saying this?

**Comment by pkozlowski-opensource** [comment]
Going to close this one as I believe that this is an issue with the Bootstrap CSS version used. If you believe that this a bug on our side please provide a plunker with a minimal reproduce scenario.
