### ISSUE TITLE
Allow or add option to bind user-defined class to Popover host

### ISSUE THREAD

**Issue by manju-reddys** [ng-bootstrap/ng-bootstrap#1441]
### Bug description:

Currently there is not way to add a user-defined class to the popover host.

Allowing to add user-defined class make life easier to customize (styling) the popover content as needed otherwise it will be patch work to to change the popover appearance.

We can style the popover content but not the popover itself. Its not a good idea to alter the popover globally so allowing to bind the custom class make life easy. 

### Link to minimally-working plunker that reproduces the issue:
[Plunker](http://plnkr.co/edit/ZVh3vSwb5DBfuA2IFyiY?p=preview)

### Version of Angular, ng-bootstrap, and Bootstrap: 

Angular: V-4

ng-bootstrap: 1.0.0-alpha.22

Bootstrap: 4.0.0-alpha.6

![custom-view](https://cloud.githubusercontent.com/assets/1906881/24726430/38f1286c-1a07-11e7-99fc-aa4872ca6881.PNG)

**Comment by goshoo** [comment]
I'm also interested in this feature. I need to modify popover's width (CSS "max-width" parameter).

**Comment by shyamal890** [comment]
+1

**Comment by pierre-hilt** [comment]
Hello, it could be very great to have this kind of options for all components with a window.

Modal, typeahead, popover...
