### ISSUE TITLE
Add days to navigate output 

### ISSUE THREAD

**Issue by ahmadyaqob** [ng-bootstrap/ng-bootstrap#1444]
### Bug description:
I am trying to make 2 calendars the behavior should be disabling the days before pick-up date in drop-of date calendar.

I tried to pass the current date by navigate output and set that value in the minDate drop-of date,everything looks fine but i need to pass the day through navigate output is there anyway to do this?

### Link to minimally-working plunker that reproduces the issue:

[Plunker](http://plnkr.co/edit/Zsq8FFWtoonZNCG33NKQ?p=preview)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
Plunk: 2.0.0
Local Project: 2.4.9

ng-bootstrap:
Plunk: Alpha 11
Local Project: Alpha 21

Bootstrap:
4-alpha.6

**Comment by pkozlowski-opensource** [comment]
Actually, this is super-simple, just bind pickup date to the `minDate` property of the return date picker: http://plnkr.co/edit/fCT0VPKkfsuNjmwemGqt?p=preview

Please use a dedicated support channel for questions like this in the feature: https://github.com/ng-bootstrap/ng-bootstrap#getting-help
