### ISSUE TITLE
Strategy for multiple release tracks

### ISSUE THREAD

**Issue by wesleycho** [ng-bootstrap/ng-bootstrap#1458]
One serious limiting factor in UI Bootstrap was the inability to support multiple release tracks, i.e. supporting Angular 1.2 and supporting Angular 1.5 via different releases (i.e. supporting older versions in a version 1.x track and newer releases in 2.x for example). This is mainly important for the ability to still release good bug fixes into an older release to help ease developer usage.

Thoughts?

**Comment by pkozlowski-opensource** [comment]
Here is my thinking:
-  we should focus on releasing 1.0
- as soon as we do so we should align our release train with the Angular ones
- it would mean, among other things, having a LTS-like version where we could cherry-pick "critical" fixes

**Comment by jnizet** [comment]
I'm not going to provide a solution, but will try to elaborate a little.

Supporting two versions can "easily" be done by having two branches in github. To me, the principal problems are:

- which version number to choose for both branches. AFAIK, the semver spec doesn't have an answer here. Suppose we have a 4.0 version for Angular 4. If Angular 5 come out and we release a new version with breaking changes to support Angular 5, we should release a 5.0 version. But then, if we still want to support Angular 4, and make breaking changes in the 4.x branch, we're also supposed to increase the major version number. Except by using a different name for the library, I don't see how we can solve this problem and still respect semver (which, I hope, i the goal).
- how to provide documentation for multiple releases. Currently, we have a unique documentation page, that only displays the latest version documentation. Even if we keep a single track, it would be nice, as ui-bootstrap did, to still have the documentation online for previous versions. If we have multiple tracks, to support multiple versions of angular, we should make the supported version  extremely clear in the documentation of each release. And I'm not even talking about bootstrap itself, which could also introduce breaking changes and force us to introduce breaking changes in ng-bootstrap, too.

**Comment by pkozlowski-opensource** [comment]
@jnizet my thinking is that we should simply align with the Angular release cycle. In practice this means, given your examples:

> Suppose we have a 4.0 version for Angular 4. If Angular 5 come out and we release a new version with breaking changes to support Angular 5, we should release a 5.0 version. But then, if we still want to support Angular 4, and make breaking changes in the 4.x branch, we're also supposed to increase the major version number

It simply means that we should defer / not do breaking changes in 4.x. I know this might not be ideal but having sem ver guarantees comes with constraints. 

> how to provide documentation for multiple releases. Currently, we have a unique documentation page, that only displays the latest version documentation. Even if we keep a single track, it would be nice, as ui-bootstrap did, to still have the documentation online for previous versions

Yes, this is must. We need to have multiple versions of the docs anyway. For now we didn't care much sine it is still alpha but yes, we need to do it post 1.0, for sure.

**Comment by Foxandxss** [comment]
We should not align with Angular release cycles because that limits us on the number of breaking changes. I can see a 6 months release for Angular, it is super big, etc etc but for bootstrap I don't think we should stick to a 6 month release schedule.
