### ISSUE TITLE
Calendars need to be split up into separate modules

### ISSUE THREAD

**Issue by wesleycho** [ng-bootstrap/ng-bootstrap#1462]
In order to better facilitate tree shaking, the datepicker module needs to be split up into separate modules, and/or create a better system for plugging in the various calendars. Currently if the user includes the `NgbDatepickerModule`, one gets every calendar type, even if it is not something desired to be used for the user's application.

**Comment by pkozlowski-opensource** [comment]
@wesleycho AFAIK all additional calendars would be tree-shaken as we don't add them to providers anywhere.  

> Currently if the user includes the NgbDatepickerModule, one gets every calendar type, even if it is not something desired to be used for the user's application.

To be precise, users get it as part of the npm module, but I don't think those are part of the runtime bundle. Did you check that non-gregorian calendars are retained in your runtime bundle? They should not.

I'm not saying we shouldn't move optional calendars to a separate repo / npm module. Just saying that if those are not retained during runtime, we don't have urgency, IMO.

**Comment by wesleycho** [comment]
I did not check, perhaps I am mistaken on my understanding how the tree shaking works.

Let me take a little time to verify.

**Comment by tomalex0** [comment]
As part of my application i'm only using  ng-modal , but while building code i see all modules added as part of  vendor files.

The version i'm using is `@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.15` , is their any workaround ?

http://stackoverflow.com/questions/43429897/webpack2-angular2-tree-shaking

**Comment by wesleycho** [comment]
The reason is because you are importing NgbModule - just import the modules you need, i.e. NgbModaModule for the moda feature

**Comment by tomalex0** [comment]
is this needed
https://github.com/ng-bootstrap/ng-bootstrap/blob/master/demo/src/app/app.module.ts#L22

```
imports: [
    BrowserModule,
    routing,
    NgbModule.forRoot(),
    NgbdDemoModule,
    NgbdSharedModule
  ],
```
If i'm only using  `NgbModaModule `

**Comment by pkozlowski-opensource** [comment]
@tomalex0 your questions are support ones and don't have _anything_ to do with the issue being discussed here. As such I'm going to delete your entries (and this comment) as irrelevant. But I've answered your question on StackOverflow: http://stackoverflow.com/a/43434332/1418796

**Comment by maxokorokov** [comment]
So after a quick test on a clean project with angular cli 1.3 and ng-bootstrap beta 2, looks like calendars (`NgbCalendarHijri` and `NgbCalendarIslamicCivil`) are not tree shaken.

All I'm doing is adding `<ngb-datepicker></ngb-datepicker>` in the root component and adding ng-bootstrap module dependency.

Tried including both `NgbModule.forRoot()`, `NgbDatepickerModule.forRoot()` and importing from `@ng-bootstrap/ng-bootstrap` and from `@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module`

---

The only place calendars are used in ng-bootstrap is in `NgbDatepickerModule` like this:

```typescript
import {NgbCalendarIslamicCivil} from './hijri/ngb-calendar-islamic-civil';

export {NgbCalendarIslamicCivil} from './hijri/ngb-calendar-islamic-civil';
```

I'm not sure if it is the expected behavior or not

**Comment by pkozlowski-opensource** [comment]
@maxokorokov thnx for testing this. I will take over investigation on this topic as IMO just having an import / export should not retain `NgbCalendarIslamicCivil`.

**Comment by maxokorokov** [comment]
I think this can be closed with Angular 6 / CLI and tree-shakeable services, today you're getting in the bundle only what you're using.
