### ISSUE TITLE
[Advice] Tabs fill and justify

### ISSUE THREAD

**Issue by justforuse** [ng-bootstrap/ng-bootstrap#1472]
Not bug, just my advice.

For now, bootstrap4 has already supported tabs fill and justify, Here is the link: http://v4-alpha.getbootstrap.com/components/navs/#fill-and-justify

And you can just add `.nav-fill` class on `ngb-tabset` to make tabs justified, Here is the plnkr:
http://plnkr.co/edit/4q7RdiwhTMPtbjnq9leW?p=preview  , it performs well.

Maybe it's better to add 'fill' or other words to `NgbTabsetConfig.justify`, while it only support 'start', 'end' and 'center'

Thanks a lot

**Comment by pkozlowski-opensource** [comment]
Related #1239

**Comment by Adondriel** [comment]
Just, info for anyone else using the Tabs, if you set a tab's [id] value to an object, it ACTUALLY WORKS on the tab change event.(Might be nice to add this info to the documentation) I was blown away when I figured this out.

**Comment by justforuse** [comment]
@Adondriel  sorry I don't get it.. is this related to this issue? what does tab's [id] do?
