### ISSUE TITLE
Typeahead should be re-triggered when user focuses back on the query

### ISSUE THREAD

**Issue by saikatbhadra** [ng-bootstrap/ng-bootstrap#1488]
### Bug description:

For many websites I surveyed (Yelp, Airbnb, Twitter, etc.) suggestions for the typeahead are re-triggered when the user focuses back on the input box. However, I don't see away of doing this with typeahead without changing the code. I am proposing having an option where on the focus event the typeahead re-triggers the suggestions.

I can write a PR to do this if the community decides we want this feature. I have done this on my own fork by writing a function called `resendQuery()` which is triggered by the `focus` event:

```
  host: {
    '(blur)': 'handleBlur()',
    '[class.open]': 'isPopupOpen()',
    '(focus)': 'resendQuery()',
    '(keydown)': 'handleKeyDown($event)',
    'autocomplete': 'off',
    'autocapitalize': 'off',
    'autocorrect': 'off'
  },
```

This query re-emits the query to _userInputStream like so:
```
  resendQuery() {
    if (this._userInput) {
      this._userInputStream.next(this._userInput);
    }
  }
```

I've created a Subject called _userInputStream which subscribed and re-emits any value from `_valueChanges` and also re-emits when the focus is returned. This observable is then subscribed by _subscribeToUserInput.

Essentially I've changed the observable to re-emit when focus is returned to the query. I'd like this to be a feature.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/XSJLmqnPei2ZObg3KVIT?p=preview

- In search type `te` and you will get some location suggestions
- Click somewhere else to blur, notice that the suggestions go away
- Then click back to return focus to the search box. The suggestions do not appear; I would like to have a configurable option to allow this.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.3.1

ng-bootstrap: 1.0.0-alpha.20

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
We are already tracking this in #698 so closing as a duplicate.
