### ISSUE TITLE
ngbPopover is not reference-able within <template>

### ISSUE THREAD

**Issue by tosehee75** [ng-bootstrap/ng-bootstrap#1493]
<template #itemPrice>
                <div [(ngModel)]="model" ngbRadioGroup name="radioBasic" class="d-flex">
                  <label class="btn btn-secondary btn-sm">
                    <input type="radio" value="amount" [(ngModel)]="item.discountType">$
                  </label>
                  <label class="btn btn-secondary btn-sm">
                    <input type="radio" value="percentage" [(ngModel)]="item.discountType" [checked]="true">%
                  </label>
                  <input type="text" class="input-group-addon form-control form-control-sm" placeholder="0.00" [ngModel]="item.discountValue" #discountValue
                         (keyup.enter)="applyDiscount(item, itemPricePopover, discountValue.value)">
                </div>
                <span *ngIf="item.failed" class="help-block text-danger">Discount not allowed</span>
                <div class="d-flex justify-content-between">
                  <button *ngIf="!item.discountedPrice || item.discountedPrice === 0 || item.discountedPrice === '0'" class="btn btn-secondary btn-sm" type="button" (click)="itemPricePopover.close()">
                    Cancel
                  </button>
                  <button *ngIf="item.discountedPrice && item.discountedPrice > 0" class="btn btn-secondary btn-sm" type="button" (click)="applyDiscount(item, itemPricePopover, '0')">Remove</button>
                  <button class="btn btn-primary btn-sm" type="button" (click)="applyDiscount(item, itemPricePopover, discountValue.value)">Apply</button>
                </div>
              </template>
              <span *ngIf="editable; else readOnlyLine" class="link-info link-style" placement="left" [ngbPopover]="itemPrice" popoverTitle="Item Discount" #itemPricePopover="ngbPopover" (shown)="assignDefaultDiscountType(item)">
                  {{item.unitPrice - item.discountedPrice | currency:'USD':true}}
              </span>

In above, itemPricePopover is undefined within `<template>`. It used to work fine until I recently upgraded to the latest angular 4..

any thoughts?

Above snippets is invoked within ngFor, so I don't want to have @ViewChild.

**Comment by pkozlowski-opensource** [comment]
Please provide a minimal reproduce scenario using plunker, otherwise it is not actionable: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by tosehee75** [comment]
Sorry. I have done created plunker in the past... I will have to spend some time to figure that out.

Thanks.

As for above, I just want to make sure one thing.  itemPricePopover can be referenced in `<template>` right?

If that's how it works, it might be a bug in my code... and I want to look into it further. However, if that's not supported, then I need to refactor the code..

I just want to make sure that above is a supported as I can't find the demo or documents that shows my use-case.

**Comment by tosehee75** [comment]
Never mind. Sorry for trouble.

For some reason, if I remove *ngIf="editable" from the above, every thing just works..

No clue why.. I refactored the code so the ngIf is in its own line.
