### ISSUE TITLE
feature requests :Material Design 

### ISSUE THREAD

**Issue by BeliliFahem** [ng-bootstrap/ng-bootstrap#1495]
**feature requests** : why you dont adopt the Material Design Guidelines to make AngularUI.

**Comment by jnizet** [comment]
The whole point of this library is to use the [bootstrap design](https://v4-alpha.getbootstrap.com/) inside angular applications.

If you want to use material, you can use [angular-material](https://material.angular.io/).

**Comment by BeliliFahem** [comment]
https://material.angular.io/ is poor comapring for example to UI https://gwtmaterialdesign.github.io/gwt-material-demo/

**Comment by jnizet** [comment]
If you think something precise should be improved in angular-material, and it's not on their roadmap yet, then ask for it to angular-material, which is *the* angular library that implements material design. Asking it here is useless.

**Comment by ArunMj** [comment]
@BeliliFahem  https://mdbootstrap.com/angular  is what you are looking for.
