### ISSUE TITLE
Dropdowns not auto-closing due to wrong zone

### ISSUE THREAD

**Issue by Eugeny** [ng-bootstrap/ng-bootstrap#1506]
### Bug description:

`autoClose` does not work immediately because the `closeFromOutsideClick` handler runs in the `<root>` zone. This is reproducible at https://ng-bootstrap.github.io/#/components/dropdown

**Comment by pkozlowski-opensource** [comment]
@Eugeny could you please elaborate? What do you mean by "does not work immediately"? Could you please fork a plunk from our demo page and clearly state:
* steps to reproduce
* current vs. expected behavior

I know that it might seem obvious _for you_ what the problem is but more context will get us to the resolution faster. Thnx!

**Comment by Eugeny** [comment]
@pkozlowski-opensource sorry for the lacking description :)

I've investigated this further and it seems to only happen in Chrome, in my app and the ng-bootstrap website, but not in Plunker.

Here's a correct trace from Plunker, where the `document:click` HostBinding is handled through Zone.js:
![selection_326](https://cloud.githubusercontent.com/assets/161476/25232017/3dc7844c-25da-11e7-8646-301e3a083cb8.png)

Here's a wrong trace from your webpage, where event is handled outside Zone.js:
![selection_327](https://cloud.githubusercontent.com/assets/161476/25232041/5647af60-25da-11e7-988c-9a5f40aa5bd2.png)

I initially thought that this was related to AoT, since your website uses it, but my app does not, and it still happens.

I'm going to investigate this further now.

**Comment by pkozlowski-opensource** [comment]
@Eugeny this might be also linked to a particular Angular version (demo site is still using 2.3.1)

**Comment by Eugeny** [comment]
I've already tried 4.0.0 and the latest 4.1.0 beta. Unfortunately my knowledge of Angular JIT compiler is nowhere good enough to dig through the code. When the event handlers get attached in `dom_events.ts`, it's still happening inside the Angular zone. When the events fire, they do so outside of Zone.js

Strangely enough, the same code works in Firefox. I'm using Chrome 57.0.2987.133 (Official Build) (64-bit)

I don't think I'll be able to find out more unless someone else does. If not, feel free to close this until further notice.

**Comment by pkozlowski-opensource** [comment]
@Eugeny could you at least try to explain what is the visual / behavior difference that you are seeing? I'm clicking at the demo page and for the World I can't see anything wrong... (using Chrome 59.0.3063.4). Maybe record a video / screen-cast? Other ideas:
* check zone versions
* try in the incognito mode to make sure that you are not using any chrome extensions that would interfere with the page

In any case yeh, we will need more info as currently I can't even see the issue so don't know what to look for / pay attention to.

**Comment by Eugeny** [comment]
@pkozlowski-opensource you were right! This was the [Anti-Adblock Killer](https://greasyfork.org/scripts/735-anti-adblock-killer-reek/code/Anti-Adblock%20Killer%20%7C%20Reek.user.js) userscript in my browser. Thank you so much for pointing me in the right direction. (The behaviour difference was that the dropdown wouldn't visually auto-close when clicking outside of it until the next change detection run).
