### ISSUE TITLE
DatePicker "eats" a day when parsing from model to Date then back to model again

### ISSUE THREAD

**Issue by moshmage** [ng-bootstrap/ng-bootstrap#1508]
### Bug description:
When using `NgbDateParserFormatter` to parse the date from a timestamp to iso string, the calendar 
sets the actual date *to a day before*

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/88wXfUYWQyRvTY5xAbHA?p=preview (select today using the buttons, watch the variables)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
"@angular/core": "^4.0.0",

ng-bootstrap:
"@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.20",

Bootstrap:
"bootstrap": "4.0.0-alpha.6",

**Comment by pkozlowski-opensource** [comment]
@moshmage what "eats" a day is data manipulation / conversion that you are using, specifically this code: `new Date(this.dateModel).toISOString();`. Check this plunk: http://plnkr.co/edit/7BznYBGYlc6XWxkYTEcn?p=preview

Please note that the `NgbDateISOParserFormatter` only parses _dates_ from string, that is, it only looks into / understands this part: `2017-04-19`. It is not aware nor concerned with times and time zones. Once again, this is a _datepicker_ not the absolute time picker.

**Comment by moshmage** [comment]
@pkozlowski-opensource how would I be able to convert the chosen date from the calendar to a timestamp and then back to a calendar date again, then?

> Please note that the NgbDateISOParserFormatter only parses dates from string, that is, it only looks into / understands this part: 2017-04-19. 

This fine and true, the thing is: We picked "2017-04-20" and the converted date goes back to "19" - I get that timezones and summer-time are not the scope of it, though how/why is the Parser picking the 19th as the day when the convertion from the picked date is the 20th? (honest doubt here)

**Comment by moshmage** [comment]
@pkozlowski-opensource my bad. completly forgot to account for the `getTimezoneOffset` - thanks for the nudge
