### ISSUE TITLE
Rating doesn't set the form to touched with reactive forms

### ISSUE THREAD

**Issue by natcohen** [ng-bootstrap/ng-bootstrap#1514]
### Link to minimally-working plunker that reproduces the issue:
Change the star rating and click on test (it should display true)

http://plnkr.co/edit/c0kxRrT0lHP53nVBYgeZ?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.3

ng-bootstrap: 1.0.0 alpha 24

Bootstrap: v4 alpha 6

**Comment by pkozlowski-opensource** [comment]
Yup, omission on our part. Good catch, thnx!

**Comment by pkozlowski-opensource** [comment]
We just need to figure out what `touched` means in the context of the rating widget :-)

**Comment by natcohen** [comment]
@pkozlowski-opensource I wouldn't think too much on this one... when the value changes!

**Comment by pkozlowski-opensource** [comment]
> I wouldn't think too much on this one... when the value changes!

This would be rather "changed" (dirty). According to https://angular.io/docs/ts/latest/guide/forms.html for `ng-touched`:

> The control has been visited

So the question is: what "visiting" rating means? For sure click / blur but not sure if anything else...

**Comment by natcohen** [comment]
@pkozlowski-opensource Good point...
