### ISSUE TITLE
ngbTabset templateRef issue

### ISSUE THREAD

**Issue by BotanMan** [ng-bootstrap/ng-bootstrap#1516]
Usage

```
<ngb-tabset>
  <ngb-tab title="Simple">
    <ng-template>
      <p>Raw deni....erican apparel, butcher voluptate nisi qui.</p>
    </ng-template>
  </ngb-tab>
</ngb-tabset>
```

Get error:
```
core.es5.js:1084 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'templateRef' of undefined
TypeError: Cannot read property 'templateRef' of undefined
    at Object.View_NgbTabset_4.co [as updateDirectives] (NgbTabset.html:20)
```

it's the line:
```
<ng-template [ngTemplateOutlet]="tab.contentTpl.templateRef"></ng-template>
```

Packages versions
`"@ng-bootstrap/ng-bootstrap": "1.0.0-alpha.25"`
`"@angular/x: 4.0.1`

**Comment by joshabelman** [comment]
How did you resolve this issue?

**Comment by ShakurOo** [comment]
Same issue here.

**Comment by colthreepv** [comment]
Similar issue here, I fixed it changing `<template>` to `<ng-template>` in my project templates.

**Comment by BotanMan** [comment]
@ShakurOo @colthreepv 
For me it was fixed itself when I updated to last angular version (4.0.3) and rebuild application

**Comment by acSpock** [comment]
not understanding why this is closed. Is there a fix for this?

using alpha.25 with angular 4.0.3 and getting this error
