### ISSUE TITLE
NgbTypeaheadModule triggers deprecation warning in browser console

### ISSUE THREAD

**Issue by dhniels** [ng-bootstrap/ng-bootstrap#1517]
Warning triggered from NgbTypeaheadModule:

![screen shot 2017-04-25 at 2 26 50 pm](https://cloud.githubusercontent.com/assets/7034022/25406855/6b98c5d6-29c5-11e7-8695-156b95c0e46f.png)

Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("[WARNING ->]<template ngFor [ngForOf]="parts" let-part let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightClas"): ng:///NgbTypeaheadModule/NgbHighlight.html@0:0

Angular: 4.0.3

ng-bootstrap: 1.0.0-alpha.21

Bootstrap: v4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
This is already solved in 1.0.0-alpha.25. Please updated and see https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#100-alpha25-2017-04-25
