### ISSUE TITLE
latest Bootstrap and ng-bootstrap alpha .25 breaks accordion view

### ISSUE THREAD

**Issue by Lexsonn** [ng-bootstrap/ng-bootstrap#1519]
### Bug description:
Accordion does not display when using Angular 4 and ng-boostrap 1.0.0-alpha.25

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.3

ng-bootstrap: 1.0.0-alpha.25

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
Works for me here: https://ng-bootstrap.github.io/#/components/accordion

Please provide a minimal reproduce scenario in a plunker, otherwise this is not actionable: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug
