### ISSUE TITLE
datepicker global config with dayTemplate doesn't work in alpha.25

### ISSUE THREAD

**Issue by sousarka** [ng-bootstrap/ng-bootstrap#1520]
### Bug description:

since 1.0 alpha.25 datepicker global config has a dayTemplate attribute. But setting the dayTemplate globally doesn't change the dayview template.

I've defined a custom dayTemplate where the selected date will be displayed with class "bg-danger" (defined by bootstrap), but the selected date still gets the "bg-primary" class.

### Link to minimally-working plunker that reproduces the issue:
[http://plnkr.co/edit/61W2RD993m4syIh7wUOF?p=preview](http://plnkr.co/edit/61W2RD993m4syIh7wUOF?p=preview)
### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.3

ng-bootstrap: 1.0 alpha.25

Bootstrap: 4.0 alpha.6

**Comment by pkozlowski-opensource** [comment]
This is a documentation mistake, it is not supposed / can't work like this. I know what you are after and we are already tracking it via #1084.

What we are going to do in this issue is to update documentation which is incorrect and then track the feature request in #1084.
