### ISSUE TITLE
Scrollbar not working if open modal in modal

### ISSUE THREAD

**Issue by pekubu** [ng-bootstrap/ng-bootstrap#1522]
Scrollbar not working if open modal in modal.
I opened a large modal with a scrollbar, from that modal, I opened a small modal and closed it, the big modal would lose the scrollbar.
plz help me

**Comment by pkozlowski-opensource** [comment]
https://github.com/ng-bootstrap/ng-bootstrap#getting-help

**Comment by retallicka** [comment]
@pekubu I also have the same issue. Did you find any way to fix it?

**Comment by retallicka** [comment]
I did some digging and just adding
`.modal { overflow: auto !important; }`
fixed it, hope it works for you

**Comment by clabough** [comment]
can also be limited to `.modal { overflow-y: auto !important; }`

**Comment by E-DOR18** [comment]
I'm dealing with the same issue, I'm using bootstrapp 4.2.1 and Angular 6. I already tried `.modal { overflow-y: auto !important; }` but it didn't work for me.

**Comment by E-DOR18** [comment]
> @E-DOR18 What are the CSS property values for .modal when viewing your modal? Is it visible to the public that you could share?

When openning the large modal (first), the overflow property is auto, also when opening the second modal over the large, however when I close the second one, overflow goes hidden for the first modal. I fix it by adding the `overflow-y: auto !important;` directly in the style attribute of the modal html tag.

**Comment by clabough** [comment]
@E-DOR18 So is it working for you now?  If you added `.modal { overflow-y: auto !important; }` to the stylesheet that affects both modals, it should retain the scrollbar.

**Comment by Lifesoftware** [comment]
.modal { overflow-y: auto} Work for me

**Comment by hosein-xz** [comment]
> I did some digging and just adding
> `.modal { overflow: auto !important; }`
> fixed it, hope it works for you

it worked for me too. thanks

**Comment by jishnu-ramachandran** [comment]
> I did some digging and just adding
> `.modal { overflow: auto !important; }`
> fixed it, hope it works for you

This worked for me too...

**Comment by Nikidhan** [comment]
when i open the first modal using the button, the scrollbar is disable but if i open the same modal from the href in that modal the scrollbar suddenly enable. can anyone help me?

**Comment by nrmz** [comment]
its

> .modal { overflow-y: auto} Work for me

this worked form me... thanks

**Comment by SamTheSame1** [comment]
In my case it did not work properly for me
`<div class = "modal-dialog modal-dialog-centered modal-dialog-scrollable">`
And I could not scroll down
After removing the **`modal-dialog-scrollable`** I was able to scroll and everything works fine if it helped then I was happy to help

**Comment by kapitanpulido** [comment]
> I did some digging and just adding `.modal { overflow: auto !important; }` fixed it, hope it works for you

worked perfectly! `[hearted]`

**Comment by kshivambaranwal** [comment]
I looked into it, and adding
.modal { overflow: auto !important; }
resolved the issue. Hopefully, it works for you too!
