### ISSUE TITLE
AOT build failed for modal example when using let-d or let-c variables.

### ISSUE THREAD

**Issue by asadsahi** [ng-bootstrap/ng-bootstrap#1523]
I think screenshot is quite self explanatory. When trying to do aot build with angular-cli, getting following error and angular-language-services is giving red lines in template as well. any idea to fix this?

![image](https://cloud.githubusercontent.com/assets/3470892/25488359/b7718f98-2b5e-11e7-9ee1-dad187498db5.png)

**Comment by asadsahi** [comment]
Apologies, problem was with some other function in file. I hope error message improves in future to let us know exact file number. In this case line number don't match.

**Comment by Liero** [comment]
Hi, I'm still getting simmilar error: 

> [Angular] Member 'd' is not callable. 

The same lines are highlighted by the editor, see  [angular/vscode-ng-language-service/#234](https://github.com/angular/vscode-ng-language-service/issues/234)

![image](https://user-images.githubusercontent.com/3494407/36477795-d0ebe1b8-1702-11e8-967f-fbaeaf0fded7.png)

**Comment by andrewjsaid** [comment]
@Liero this looks like the same issue described here - angular/angular#16643
