### ISSUE TITLE
ngbTooltip: let-" is only supported on template elements.

### ISSUE THREAD

**Issue by Duraimurugan** [ng-bootstrap/ng-bootstrap#1525]
### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.3.1

ng-bootstrap: ^1.0.0-alpha.22

Bootstrap: ^3.3.7

angular-cli: 1.0.0-beta.24
I am running into template parse errors when using ngbTooltip when using with <template> tag as shown in demo

**HTML Template**
```
<template #tipContent>{{licenorsTooltip}}</template>
    <button type="button" [ngbTooltip]="tipContent" #tooltipLicensors="ngbTooltip" triggers="manual" [placement]="bottom" class="licensor-btn" 
    (click)="toggleSelect()" on-mouseover='toolTipOver()' on-mouseleave="toolTipLeave()">
        <span class="pull-left">{{licensorHeader}}</span>
        <span class="caret pull-right"></span>
    </button>
```

**Errors thrown in browser console:**
zone.js:522 Unhandled Promise rejection: Template parse errors:
"let-" is only supported on template elements. ("<ng-template ngFor [ngForOf]="parts" [ERROR ->]let-part let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightClass}}">{{part}}</span><ng-template ["): NgbHighlight@0:37
"let-" is only supported on template elements. ("<ng-template ngFor [ngForOf]="parts" let-part [ERROR ->]let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightClass}}">{{part}}</span><ng-template [ngIf]="!i"): NgbHighlight@0:46
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("rOf]="parts" let-part let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightClass}}">{{part}}</span>[ERROR ->]<ng-template [ngIf]="!isOdd">{{part}}</ng-template></ng-template>"): NgbHighlight@0:124
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<ng-template ngFor [ngForOf]="parts" let-part let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightC"): NgbHighlight@0:0 ; Zone: <root> ; Task: Promise.then ; Value:

**Comment by pkozlowski-opensource** [comment]
Couple of things:
* we don't support Bootstrap 3.x, only 4.0.0-alpha.6 (although 3.x might work just fine for certain cases)
* I don't think that you are using version of the library / Angular that you've reported here - please provide a minimal reproduce scenario using plunker, otherwise this is not actionable and will be closed: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment]
Closing since we haven't heard back with a plunker that would help us reproduce / understand / fix the issue.

**Comment by blur0224** [comment]
@Duraimurugan Did you find a resolution to this error?  I recently updated my node modules and started getting this exact error.  I've played around with the versions and haven't been able to get a different error, except when I commented out the template comments and it gave a similar error for the NgbTypeaheadWindow module.

Angular: ~2.4.0
ng-bootstrap: ^1.0.0-alpha.25
Bootstrap: ^4.0.0-alpha.6
angular-cli: ^1.0.0-rc.1

I'll work on a plunkr but I don't know if I'll be able to reproduce the error.  I'm new to angular 2.

**Comment by pkozlowski-opensource** [comment]
@blur0224 you need at least Angular 4.0.3 with `ng-bootstrap: ^1.0.0-alpha.25` - I'm surprised that you've even managed to install it with Angular 2.4.x since we've got explicit dependency on ^4.0.3...

Also check  changelog: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#100-alpha25-2017-04-25

**Comment by blur0224** [comment]
Thanks  @pkozlowski-opensource 

I had been using an older version of bootstrap but updated to the latest to see if it changed the error.  There was a warning during installation about the angular version, but not an error.

I had based the project on the Hero's tutorial and didn't realize how out of date the version of Angular was.  Updating to the latest version of angular and it's dependencies cleared up the error.

**Comment by jdinh-mackevision** [comment]
Is there an ng-bootstrap version that will still work with Angular 2.4?
