### ISSUE TITLE
angular 4.1issue

### ISSUE THREAD

**Issue by dilotec-2015** [ng-bootstrap/ng-bootstrap#1527]
with angular 4.1 get an error:
Cannot read property 'templateRef' of undefined

**Comment by pkozlowski-opensource** [comment]
Please provide a minimal reproduce scenario using plunker, otherwise it is not actionable: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

**Comment by wesleycho** [comment]
One thing that may help with this problem if you upgraded is to change all `<template>` usage to `<ng-template>` - other than that, a Plunker would be very useful to help :) .

**Comment by marcuslind90** [comment]
I have the same issue after upgrading to Angular 4.1 when using tabsets.

**Comment by jhhobbs** [comment]
Ran into this as well with Angular v4.0.0 and ng-bootstrap v1.0.0-alpha.23.  As @wesleycho noted, you may have to use <template> or <ng-template> depending on versions.  Not on the latest version myself and so, inversely, I was able to resolve this issue using <template> instead of <ng-template>.

http://plnkr.co/edit/hlq7KCNvHvF0HzySQWbJ?p=preview

**Comment by pkozlowski-opensource** [comment]
Closing as we don't have any reproduce scenario from the original author and looking at the comments there is no evidence that there is anything actionable on our side.

**Comment by Thommas** [comment]
I found the same issue.
If you put an ngIf that eventually evaluates to false on the ng-template, you will get this error.
Solution is obviously to put the ngIf on a <section> inside the ng-template.
Hope it can help.

**Comment by cguilhermef** [comment]
The problems is that documentation doesn't talk about 'id' attribute in ngb-tab. 
```
<ngb-tabset>
  <ngb-tab title="Simple">
    <ng-template ngbTabContent>
      <p>Raw denim you probably haven't heard of them jean shorts Austin. Na, r(...)</p>
    </ng-template>
  </ngb-tab>
```

But you need to define the 'id' and 'title':
```
<ngb-tabset>
  <ngb-tab title="Simple" id="1">
    <ng-template ngbTabContent>
      <p>Raw denim you probably haven't heard of them jean shorts Austin. aliqua, retro synth(...)</p>
    </ng-template>
  </ngb-tab>
```

**Comment by pkozlowski-opensource** [comment]
> The problems is that documentation doesn't talk about 'id' attribute in ngb-tab.

@cguilhermef what do you mean? Both `title` and `id` are documented here:  https://ng-bootstrap.github.io/#/components/tabs#NgbTab

What other documentation you are missing? 

> But you need to define the 'id' and 'title':

`id` is optional - it will be auto-generated if not provided.

In any case I've got the impression that the discussion here focuses on multiple different issues and it is not clear what we are talking about any more. There is little point in commenting on closed issues. If you believe that there is anything else to fix in this library please open a new issue with a clear problem description and a minimal reproduce scenario in a plunker.

**Comment by cguilhermef** [comment]
@pkozlowski-opensource sorry by mistakes. But, when I saw

> Cannot read property 'templateRef' of undefined

in my console, the soluction to my issue was to set 'id' attribute.

**Comment by Kurara** [comment]
Hello. I have the problem of ng-template for alert component. Here it is the scenario: stackblitz.com/edit/angular-s4mmq4
