### ISSUE TITLE
Change background color tooltip

### ISSUE THREAD

**Issue by nansCabanac** [ng-bootstrap/ng-bootstrap#1539]
Hello,

"@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.23"
"@angular/compiler": "^4.0.0",

By default tooltip background is black, i try to change the color to white.
I can change inner color if i set `style="color:white;"` on `<table>` in the `<template>` but the background of parent component stay black.
 
I can change background color with chrome "develop tools", but it's not work when i use overwrite class  css in my component.

This is my css : 
`.tooltip-inner {
	background :white ;
         // OR background :white !important ;		
} 
#ngb-tooltip-1{
	background :white ;
        // OR background :white !important ;
}
ngb-tooltip-window {
	background :white ;
         // OR background :white !important ;
}
.tooltip{
	background :white ;
        // OR background :white !important ;
}`

And the code 
```
<div>	
    <div  class="row justify-content-start">
        <div [ngbTooltip]="tipContent" > <p>text </p></div>
    </div>
</div>
<template #tipContent ><table `class="table"><tr><td>test</td></tr></table></template>
```
(Bad english sorry =) )
Thanks

**Comment by pkozlowski-opensource** [comment]
See an answer to a similar support question (it talks about a carousel but the principles and the technical solution is the same): http://stackoverflow.com/a/43615746/1418796

Please don't use the issue tracker for general support requests like this one: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help - but rest assured that we are happy to help on SO if you ask question and provide a minimal reproduce scenario using plunker or similar.

**Comment by mrjohnr** [comment]
Hi.It is possible to have a working sample on  [examples page](https://ng-bootstrap.github.io/#/components/tooltip/examples)? thanks

**Comment by keivansahebdelfard** [comment]
```
:host >>> .tooltip-inner {
  background: #5e86af !important;
}

:host >>> .bs-tooltip-top .arrow::before,
:host >>> .bs-tooltip-auto[x-placement^="top"] .arrow::before {
  border-top-color: #5e86af !important;
}
```

**Comment by bobbyg603** [comment]
Changed slightly over the years, here's what worked for us in styles.css. Note, we were trying to change this tooltip in a modal, and ng-deep didn't seem to work so we wrapped the container in a `.blue-tooltip` class to increase specificity.

```scss
.tooltip-inner {
  background-color: #003166;
}

.tooltip-arrow::before {
  border-top-color: #003166;
}
```
