### ISSUE TITLE
How to detect change events from datepicker within custom component?

### ISSUE THREAD

**Issue by zchartman** [ng-bootstrap/ng-bootstrap#1541]
I am trying to create a simple custom component for forms that contains both ngbDatepicker and Timepicker inputs.

How can I detect changes to those inputs? I've tried passing change events on the inputs like this: 
`<input class="form-control" placeholder="yyyy-mm-dd" name="dp" [(ngModel)]="date" ngbDatepicker #d="ngbDatepicker" (change)="onChange($event)">
` 
and 
`<ngb-timepicker [(ngModel)]="time" (change)="onChange($event)" [meridian]="meridian"></ngb-timepicker>`

I've also tried using
`ngOnChanges(changes: SimpleChange){...}`

But the change event is never detected.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.1.2

ng-bootstrap: 4.1.2

Bootstrap: 4.1.2

**Comment by wesleycho** [comment]
Couldn't you use the `ngModelChange` output?

**Comment by zchartman** [comment]
@wesleycho Yep, that works. Thanks!

**Comment by gangfang** [comment]
@wesleycho `ngModelChange` only trigger when hour or minute field loses focus.

Is there any way to invoke `ngModelChange` on (keyup)?

User of form may leave the model `null` if they keep cursor on either (hour or minute) input field.

**Comment by vucongthanh92** [comment]
how do you custome ngx-datepicker when user choose date ?

**Comment by hanatharesh2712** [comment]
> @wesleycho `ngModelChange` only trigger when hour or minute field loses focus.
> 
> Is there any way to invoke `ngModelChange` on `(keyup)`?
> 
> User of form may leave the model `null` if they keep cursor on either (hour or minute) input field.

Did you get any solution for this? Thanks in advance!

**Comment by fayaz668** [comment]
> @wesleycho `ngModelChange` only trigger when hour or minute field loses focus.
> 
> Is there any way to invoke `ngModelChange` on `(keyup)`?
> 
> User of form may leave the model `null` if they keep cursor on either (hour or minute) input field.

any updates ??

**Comment by ahmadamjad09** [comment]
I am getting the same issue, here is my code
<input
          [ngxMatDatetimePicker]="picker"
          [min]="today_date"
          (dateChange)="ngvalueChanges($event.value)" 
        />
        <ngx-mat-datetime-picker #picker [showSpinners]="true" [enableMeridian]="true">
        </ngx-mat-datetime-picker>
