### ISSUE TITLE
Organize table of contents in README

### ISSUE THREAD

**Issue by wesleycho** [ng-bootstrap/ng-bootstrap#1547]
Currently the readme is a flat list of items - this can be improved for usability with a table of contents in the beginning where users can click the link to the appropriate section of the readme with the information the user's are looking for.

See https://github.com/preboot/angular-webpack/blob/master/README.md for an example of one such table of contents.

**Comment by thbt** [comment]
By the way this was generated using the [markdown-toc](https://marketplace.visualstudio.com/items?itemName=AlanWalk.markdown-toc) extension for VS Code :)
