### ISSUE TITLE
markDisabled does not support instance method

### ISSUE THREAD

**Issue by jma** [ng-bootstrap/ng-bootstrap#1552]
I'm not sure that is a bug or not, but try to access to `this` in the `markDisabled` callback failed:

```TypeScript
  isWeekend(date: NgbDateStruct) {
    const d = new Date(date.year, date.month - 1, date.day);
    return d.getDay() === 0 || d.getDay() === 6;
  }

  isDisabled(date: NgbDateStruct, current: {month: number}) {
    const d = new Date(date.year, date.month - 1, date.day);
    return this.isWeekend(date); // this is undefined
  }
```

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/sPAZc5vKszJZ0PsRQqIO?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.3

ng-bootstrap: 1.0.0-alpha.26

Bootstrap:4.0.0-alpha.6

Thanks in advance.

**Comment by wesleycho** [comment]
I'm not sure anything can be done about this on the library side - if I remember right, this is sort of related to Angular itself and how it works with binding functions.

Your best bet would be to work around this by defining a function like
```ts
isDisabled = (date: NgbDateStruct, current: {month: number}) => {
    const d = new Date(date.year, date.month - 1, date.day);
    return this.isWeekend(date); // this is undefined
}
```
The benefit of this is that it preserves the context of `this` regardless of how Angular handles bound functions.

**Comment by pkozlowski-opensource** [comment]
Agree with @wesleycho - there is nothing we can do as we don't have access to the containing component instance when the function in question is invoked.

**Comment by jma** [comment]
Many thanks for your answer. That's perfect.

**Comment by rsaenen** [comment]
Hi,
I has the same issue, I couldn't use `this`.
A quick fix is to attach the function `isWeekend()` to the `window`, but it's ugly as... :)

**Comment by SEVCO** [comment]
**in template** 
[markDisabled]="isDisabled(allowedDates)"


**in component**

    isDisabled(dates: NgbDateStruct[]) {
        return (date: NgbDateStruct) => {
            return dates.filter(d => d.year === date.year && d.month == d.month && d.day === d.day)[0] ? true : false;
        }
    }

**Comment by SEVCO** [comment]
**in template:**
[markDisabled]="isDisabled(allowedDays)"

**in component**
    isDisabled(dates: NgbDateStruct[]) {
        return (pickerDate: NgbDateStruct, currentMonth) => {
            return !dates.find(dayAllowed => dayAllowed.year == pickerDate.year && dayAllowed.month == pickerDate.month && dayAllowed.day == pickerDate.day);
        }
    }
