### ISSUE TITLE
[NgbTypeahead] Support term highlighting in result templates

### ISSUE THREAD

**Issue by alexandrepayette** [ng-bootstrap/ng-bootstrap#1553]
Hi,

I wanted to create a custom result template for an instance of `ngb-typeahead` in my project but I also wanted to keep the default highlighting behavior. I looked though the default template and it uses a component called `ngb-highlight` to handling this behavior. Unfortunately, it is not exported by the typeahead module so there is no way to use it directly without duplicating the code into my own project. Is it possible to export this component in the module as well?

This is a small change so I could easily do a PR for it if needed.

**Comment by pkozlowski-opensource** [comment]
@alexandrepayette yes, please send a PR. We didn't export the `ngb-highlight` directive initially since we weren't sure if people will need it or not.

**Comment by daniyal4747** [comment]
Is there any working example of how to use highlight with result template?

**Comment by akilmakda** [comment]
@daniyal4747  below is the working example.

```
<ng-template #rt let-r="result" let-t="term">
                  <ngb-highlight [result]="r.text" [term]="model"></ngb-highlight>
</ng-template>
```
