### ISSUE TITLE
feature(NgbPopover): Add input for transmin content on temlete.

### ISSUE THREAD

**Issue by kotproger** [ng-bootstrap/ng-bootstrap#1556]
Hello! There was a need to dynamically create pop-ups with a template, so it's not possible to use "**@ViewChild**" and "**popover.open (context)**". Instead, I changed the component code by adding the input parameter "popoverData" and modifying the function:

```
NgbPopover.prototype.open = function (context) {
	if (!this._windowRef) {
		//my code
		if(context)
			context.popoverData = this.popoverData;
		else    
			context = {popoverData: this.popoverData};
		//
		this._windowRef = this._popupService.open(this.ngbPopover, context);
		this._windowRef.instance.placement = this.placement;
		this._windowRef.instance.title = this.popoverTitle;
		if (this.container === 'body') {
			window.document.querySelector(this.container).appendChild(this._windowRef.location.nativeElement);
		}
		// we need to manually invoke change detection since events registered via
		// Renderer::listen() are not picked up by change detection with the OnPush strategy
		this._windowRef.changeDetectorRef.markForCheck();
		this.shown.emit();
	}
};
```

The usage looks like this:
```
import {Component} from '@angular/core';

@Component({
  selector: 'popover-tpl-content',
  template: `<ng-template #popContent let-params="popoverData">
    <label >{{params.text}}</label>
</ng-template>
<button *ngFor="let btn of buttons" class="btn btn-outline-primary"  [ngbPopover]="popContent"  [popoverTitle]="btn.title"  container="body" triggers="click outsideClick " [popoverData]="btn">{{btn.title}}</button>`
})

export class NgbdPopoverTplcontent {
  buttons=[{
	title: 'test1',
	tixt: 'test_text1'
  },{
	title: 'test2',
	tixt: 'test_text2'
  },{
	title: 'test3',
	tixt: 'test_text3'
  },{
	title: 'test4',
	tixt: 'test_text4'
  }];
}
```

Maybe you should introduce something like this for everyone?
### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.1

ng-bootstrap:1.0.0-alpha.26

Bootstrap:4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
> There was a need to dynamically create pop-ups with a template, so it's not possible to use "@ViewChild" and "popover.open (context)"

Not sure what you mean... Please share a reproduce scenario. IMO you should be able use context for your use-case. As such I don't see why we would be adding code you are proposing here.

Please share a plunker illustrating that context alone doesn't work.

**Comment by kotproger** [comment]
I just provided my implementation as an example of what I need - to transfer the content as a parameter, and not by calling the method open.
Such a functional facilitates work in cases of dynamic creation of elements. Example: 
[link](http://plnkr.co/edit/ZPo8VMqPfQ3lYCdcdRJy?p=preview)

Otherwise I would have to use a similar solution:
[link](http://stackoverflow.com/questions/40165294/access-multiple-viewchildren-using-viewchild)

**Comment by wesleycho** [comment]
One can use `@ViewChildren` or `@ContentChildren`. IMO, this is not a compelling case to make this change in the library for and adds bloat.

**Comment by kotproger** [comment]
> One can use @ViewChildren or @ContentChildren. IMO, this is not a compelling case to make this change in the library for and adds bloat.

And what then argues the implementation of the transfer of the template through the input parameters, and the transfer of the context is a separate function. Is this logical for you?

**Comment by pkozlowski-opensource** [comment]
@kotproger you can create a separate `<ng-template>` for each item being iterated over and then each template can have separate data, context etc.: http://plnkr.co/edit/o4UGc6dvlRk9Gd35QWn8?p=preview

I must say that I'm having a bit of hard time following your exact scenario as your plunker makes reference to  `popoverData` but  `popoverData` is not part of your data model... It would _really_ help if you could illustrate your _exact_ use-case.

In any case I hope that the plunker I've provided shows an alternative way of achieving what you need.

**Comment by kotproger** [comment]
Yes, this solution is generally suitable. Thanks for the example. It would be nice to complement demo examples with similar solutions.

**Comment by pkozlowski-opensource** [comment]
Glad it worked for you @kotproger
