### ISSUE TITLE
Move tab titles below tab content

### ISSUE THREAD

**Issue by batnyu** [ng-bootstrap/ng-bootstrap#1557]
It would be nice to be able to choose the placement of the tab titles for Tabs (above or below the tabs content).

**Comment by pkozlowski-opensource** [comment]
I don't think that Bootstrap's CSS support such option: https://v4-alpha.getbootstrap.com/components/navs/#tabs

We can't add it here if there is no corresponding CSS on the Bootstrap side. Please open a feature request in https://github.com/twbs/bootstrap/notifications
