### ISSUE TITLE
pause method does not work in carousel

### ISSUE THREAD

**Issue by chrisbenseler** [ng-bootstrap/ng-bootstrap#1560]
Bug description: pause method does not work in carousel

Error can be seen in this plunker:
http://plnkr.co/edit/trn2UQvWPqKJOeAXAmPP?p=preview

I added a button that calls a method in the component, the method calls pause() from an instance of NgbCarousel (that I got from ViewChild). The carousel keeps navigating to the nexts items.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.1.3

ng-bootstrap: 1.0.0-alpha.26

Bootstrap: 4.0.0-alpha.6

**Comment by wesleycho** [comment]
That Plunker works for me.

**Comment by chrisbenseler** [comment]
I figured out what is happening: click on the pause button than hover the mouse over the slider/carousel and move it out. The slider will restart to cycle.

**Comment by danielronnkvist** [comment]
@chrisbenseler I believe the carousel works as intended. You're only [pausing](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/carousel/carousel.ts#L130) the carousel. Perhaps an option to disable the [mouse events](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/carousel/carousel.ts#L39-L40) would let you get the result that you're after? Just as the keyboard option, a mouse option operate in the same way.

**Comment by wesleycho** [comment]
Indeed, this seems to be as intended: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/carousel/carousel.ts#L39-L40

I would recommend setting the interval to 0 if the intention to freeze it completely.

**Comment by wesleycho** [comment]
Going to close this as intended behavior

**Comment by chrisbenseler** [comment]
@wesleycho thanks for the explanation. I thought that using .pause() method would pause it until the cycle() method would be called again. If setting the interval to 0 works (I didin't test it yet), it will ne enough.
:-)
