### ISSUE TITLE
Carousel: can't add/remove slides after initialization

### ISSUE THREAD

**Issue by chrisbenseler** [ng-bootstrap/ng-bootstrap#1562]
If I have a template that uses carousel, like this:

```
<ngb-carousel>
  <ng-template ngbSlide *ngFor="let r of resources">
      <img src="{{ r.fileurl }}" alt="{{ r.name }}">
    </ng-template>
</ngb-carousel>
```

the carousel is initialized at the first time with the values from the 'resources' array. But if I change this array (adding or removing), the slides update in some weird way: the slides list from the object updated, but no image is shown.

**Comment by tproenca** [comment]
I'm having exactly this problem? Any news about it?

**Comment by impankratov** [comment]
@tproenca and for others who had problems with this:
```
<ngb-carousel>
  <!-- Outer template for ngForOf -->
  <ng-template ngFor let-item [ngForOf]="items">
    <!-- Inner template for NgbCarousel -->
    <ng-template ngbSlide>
      <div class="custom-class">
        Your content
      </div>
    </ng-template>
  </ng-template>
</ngb-carousel>
```
