### ISSUE TITLE
Dialog service for Open a dialog directly from any other component

### ISSUE THREAD

**Issue by Prashant3108** [ng-bootstrap/ng-bootstrap#1563]
Dialog service for Open a dialog directly from any other component

**Comment by wesleycho** [comment]
Can you be more detailed? There is already a [modal service](https://ng-bootstrap.github.io/#/components/modal) that can be used anywhere, whether a service or a component.

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a plunker reproducing the problem and describing the difference between the expected and current behaviour.
