### ISSUE TITLE
Is there any way to work ng-bootstrap/ng-bootstrap with bootstrap 3 ?

### ISSUE THREAD

**Issue by Prashant3108** [ng-bootstrap/ng-bootstrap#1568]
I have tried to use this in my project which is using Bootstrap 3 , it was not working, because css was conflicting with bootstrap 3 classes.

**Comment by pkozlowski-opensource** [comment]
Nope. Here is why: https://github.com/ng-bootstrap/ng-bootstrap/wiki/Why-Bootstrap-4-only%3F
