### ISSUE TITLE
Modal and Angular Router Integration

### ISSUE THREAD

**Issue by mohammedzamakhan** [ng-bootstrap/ng-bootstrap#1572]
### Bug description:

I want to know whether we can integrate Modal with the router, suppose I am on people route, and I want to create a new person, I will click on Add Person button and it takes me to the route /people/new/1, which should take me to the first step in the modal (where I have multiple steps). Is this something achievable? We used to be able to do this in Angular 1.x with ui-router. 

Want to know whether this is possible in using @angular/router and ng-bootstrap or not

Thanks

**Comment by pkozlowski-opensource** [comment]
I can't see why it wouldn't be possible. Did you try to make it work? Did you bump into any issues? 

In any case this is a support request so doesn't belong here, see: https://github.com/ng-bootstrap/ng-bootstrap#getting-help

If you've got specific problems open a new issue following our bug report template: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug
