### ISSUE TITLE
DropDown grouping

### ISSUE THREAD

**Issue by ashleydf** [ng-bootstrap/ng-bootstrap#1575]
Is there a way to create group labels inside a drop down with items in group displayed below.

A simple example would be: a dropdown that consists of fruit and vegetables.
There would be a header label named: Fruit, followed by a list of fruit.
Then  a header label of vegetables: followed by list of vegetables.
I know this is possible using AngularJS and the groupBY tag in options,  is this possible within NgDropDown?

![angularjs_dd_example](https://cloud.githubusercontent.com/assets/14944323/26418578/96d02966-4071-11e7-82b1-70bbcec38a52.png)

**Comment by pkozlowski-opensource** [comment]
Sorry, but it is not clear what you are asking for. Your example is for AngularJS (this project is for Angular) and uses a select box while you are talking about dropdowns... 

If you _happen_ to want dropdowns with grouping I don't think that Bootstrap itself has any specific CSS / HTML structure for this: https://v4-alpha.getbootstrap.com/components/dropdowns/. Having said this, you've got full control over markup and CSS classes used by dropdowns so I can imagine that you could easily create a similar visual experience with a bit of custom CSS.

Closing as a support request.
