### ISSUE TITLE
Collapsable/Expandable Side Nav

### ISSUE THREAD

**Issue by JordanGS** [ng-bootstrap/ng-bootstrap#1576]
Bootstrap 4 with ng-boostrap and Angular 2

Sample Code: https://codepen.io/j_holtslander/pen/XmpMEp

Currently using java script, would be amazing if it could be done with ng-bootstrap instead.

**Comment by pkozlowski-opensource** [comment]
This is a support question that was already answered on SO: https://stackoverflow.com/questions/44166895/how-do-i-create-a-fixed-nav-with-ng-bootstrap
