### ISSUE TITLE
TimePicker iOS placeholder is being cut off.

### ISSUE THREAD

**Issue by jvanallen93** [ng-bootstrap/ng-bootstrap#1578]
### Bug description:
In iPad Air 2 (10.3.1) - Safari and iPhone 6 (10.3.1) - Safari, the placeholder text is being cut off.
Might be solved by either making a new input to adjust the size of the input box or just setting the size to 3.
### Link to minimally-working plunker that reproduces the issue:
https://ng-bootstrap.github.io/app/components/timepicker/demos/basic/plnkr.html
Test this in the devices mentioned above.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
4.0.0
ng-bootstrap:
1.0.0-alpha.26
Bootstrap:
4.0.0 alpha-6

**Comment by pkozlowski-opensource** [comment]
Related discussion in https://github.com/ng-bootstrap/ng-bootstrap/pull/1283

**Comment by pkozlowski-opensource** [comment]
@joshvanal could you please try to reproduce this with pure Bootstrap CSS? I don't think it has anything to do with this library, we are just using standard Bootstrap markup here.

**Comment by subtainishfaq7175** [comment]
I am faceing same issue

**Comment by pkozlowski-opensource** [comment]
Fixed in e65d5cf
