### ISSUE TITLE
ngbTooltip is not working in children route

### ISSUE THREAD

**Issue by kapilkarda** [ng-bootstrap/ng-bootstrap#1583]
I am trying to use ngbTooltip in my angular2 application, it works fine with the root templates but when i try to use it in childrouting templates its not working, i am using webpack-cli anglar2.

thanks in advance.

**Comment by pkozlowski-opensource** [comment]
Please fill in issue template and provide a minimal reproduce scenario in a plunker: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

Also please note that:
* you have to import the NgbModule in child route modules (or any module, for that matter)
* you should not use `.forRoot()` in any module other than the root application one

In any case this is not actionable without a minimal reproduce scenario in a plunker.

**Comment by pkozlowski-opensource** [comment]
Closing as we don't have any reproduce scenario and we haven't heard back from the opener.

**Comment by MetaiR** [comment]
I have the same problem here

**Comment by n8all3n** [comment]
I am getting the same problem as well...I have NgbModule imported into my child module, and am not using forRoot

**Comment by pkozlowski-opensource** [comment]
@MetaiR @n8all3n how can you know that you are "getting the same problem" - there was no reproduce scenario provided in the original issue report?

If you see problems please open a new issue following our submission template:  https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug. Please make sure to attach a minimal, runnable reproduce scenario (plunker, stackblitz).

**Comment by ghaschel** [comment]
I have the same problem as well...

**Comment by DancingAppsDays** [comment]
Yeah running to this issue compoenent in routeroutlet of appcomponent works, but if a compoenent is inside a routeroutlet in that compoenent, then that ngbTooltip doest appear,

Even tried to make a standalone compoenent importing ngbmodule and tolltip in child component instead of appmodule but didnt work,

the only way it woked is by making the actual child component inside standaalone and importing ngbtooltip
