### ISSUE TITLE
typeahead: trigger char

### ISSUE THREAD

**Issue by dennis82m** [ng-bootstrap/ng-bootstrap#1585]
Is there already a way of only triggering typeahead when entering a certain char... this would enable the "@mention" usecase?!

**Comment by pkozlowski-opensource** [comment]
Of course - you've got full control over search results in your observable chain.

In any case this is a support request and as such doesn't belong here: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
