### ISSUE TITLE
[Feature Request] Customize content of Carousel Indicators

### ISSUE THREAD

**Issue by jspizziri** [ng-bootstrap/ng-bootstrap#1587]
It would be good to have the ability to [customize the content of carousel indicators](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/carousel/carousel.ts#L46). An example use-case is if it's desired to put words indicating the slide. Theoretically this could be avoided by building a custom carousel indicators outside of `NgbCarousel` however that would depend on https://github.com/ng-bootstrap/ng-bootstrap/pull/1406, but even in that case it seems like a lot of overhead.

Thanks!

**Comment by tosrisri** [comment]
You can't style it by using CSS or SCSS. You can achieve it by modifying the template string, here's how:
Goto node_modules > @ng-boostrap > ng-bootstrap > carousel > carousel.js
give inline style to the <li> element like below:
...
template: "\n    <ol class=\"carousel-indicators\" *ngIf=\"showNavigationIndicators\">\n      <li style=\"background-color:black\"  *ngFor=\"let slide of slides\" [id]=\"slide.id\" [class.active]=\"slide.id === activeId\"\n  ...

You are done.

![Screen Shot 2020-07-08 at 10 14 07 PM](https://user-images.githubusercontent.com/30029505/86946689-609ec980-c168-11ea-8846-98be9f958fd9.png)
Here's the output
![Screen Shot 2020-07-08 at 10 14 45 PM](https://user-images.githubusercontent.com/30029505/86946758-7ad8a780-c168-11ea-8b9a-beb889e957e7.png)

**Comment by tayambamwanza** [comment]
> You can't style it by using CSS or SCSS. You can achieve it by modifying the template string, here's how:
> Goto node_modules > @ng-boostrap > ng-bootstrap > carousel > carousel.js
> give inline style to the
> 
> * element like below:
>   ...
>   template: "\n    <ol class="carousel-indicators" *ngIf="showNavigationIndicators">\n      <li style="background-color:black"  *ngFor="let slide of slides" [id]="slide.id" [class.active]="slide.id === activeId"\n  ...
>   You are done.
>   ![Screen Shot 2020-07-08 at 10 14 07 PM](https://user-images.githubusercontent.com/30029505/86946689-609ec980-c168-11ea-8846-98be9f958fd9.png)
>   Here's the output
>   ![Screen Shot 2020-07-08 at 10 14 45 PM](https://user-images.githubusercontent.com/30029505/86946758-7ad8a780-c168-11ea-8b9a-beb889e957e7.png)

Hi, I'm attempting to change the color of the indicators. I saw you suggested editing the files in node_modules, would that not be wiped away anytime npm install is run though?
