### ISSUE TITLE
The datepicker input is invalid when the input is cleared

### ISSUE THREAD

**Issue by kpwbo** [ng-bootstrap/ng-bootstrap#1588]
### Bug description:

The directive ngbDatepicker makes the input field invalid when the input is cleared.

To reproduce in the plunker:
1) Note that the field is initially valid (model is null).
2) Select a date using the date picker.
3) Clear the field (and click outside the field).
4) Note that the field is now invalid (model is empty string).

A solution would be to set the model to null instead of an empty string when the input is cleared.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/sTh2BvFPwyLjsSSQ9gKW?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.3

ng-bootstrap: 1.0.0-alpha.26

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
We've got 2 options:
* treat empty strings as null 
* bind null to model when a user is typing in an empty string

I'm going to mark this as a bug since there are many users bumping into this one.

**Comment by nelsonkyshin** [comment]
Following with interest. I haven't found a way to differentiate between an invalid input and an empty value. Not good for user feedback

**Comment by rahulz-wasnik** [comment]
@kpwbo 

Had the same problem. I was using reactive forms and when creating the control for dob i was initially doing something like 

this.myForm = new FormGroup({
  dob: new FormControl('')
});

Changed this to...

this.myForm = new FormGroup({
  dob: new FormControl()
});

Removing '' solved the issue. I guess it treats the empty string as a value which obviously is an invalid date causing dob..errors.ngbDate.invalid to be true.
