### ISSUE TITLE
Accordion refresh the page in Firefox when  $event.stopPropagation() is called

### ISSUE THREAD

**Issue by Adriansillo** [ng-bootstrap/ng-bootstrap#1589]
Hello guys im trying to stop accordion collaps clicking on a checkbox, i use $event.stopPropagation()  when the checkbox is clicked. It works fine in Chrome and IE but in Firefox the page refresh 

Is anyone in the same problem?

here is the plunker http://plnkr.co/edit/iXHGRQheu5yOAPeun5VZ?p=preview

<template ngbPanelTitle>
      <span>&#9733; <b>Fancy</b> title &#9733;</span>
      <input type="checkbox" (click)="clicked($event)">
</template>

clicked(event:Event) {
    //event.preventDefault();
    console.log("Clicked");
    event.stopPropagation();
  }

**Comment by pkozlowski-opensource** [comment]
What you are trying to do would put `<input>` element inside a link (`<a>`) tag. This is not a valid HTML and as such you can't expect any reasonable behaviour from any browser.

Please not that we are planning to add more flexibility in terms of what is possible in the accordion / tabset heading, but we are not there yet. More info in #465 and #717
