### ISSUE TITLE
TypeError: Invalid event target when pre-rendering nbgTypeahead in ASP.NET Core

### ISSUE THREAD

**Issue by georgiosd** [ng-bootstrap/ng-bootstrap#1593]
Unfortunately I can only offer a repro in a zip file and not plunkr but this error seems to occur when putting the simple typeahead example on a ASP.NET core project with ng 4.1.2. Going back to 4.0.3 doesn't compile the app at all.

This seems to be related to the RxJS calls in `search()`. If I just return an empty observable, it will compile. If I then modify the file and it gets reloaded with HMR, it works fine. If I restart the app, boom, crash.

Any ideas?

**Comment by georgiosd** [comment]
Btw: I tried the sample example typeahead example with 4.1.3 and it works fine so I don't think it's because of the upgrade.

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we are not in the position to debug your (or anyone's else) setup.... But we are ready to fix anything in this project that would prevent people working with their particular setup!

I'm afraid that you will have to dig into it more on your side. Don't hesitate to come back to us if you feel like there is anything to fix on the ng-bootstrap side. Good luck!

**Comment by georgiosd** [comment]
I get it, but I'm not sure that makes a whole load of sense.

I'm a new angular2 user, trying SSR and ng-bootstrap chokes. Debugging either the SSR or ng-bootstrap is way beyond my knowledge level. 

No worries, I switched to ngx-bootstrap which seems to work with SSR.
