### ISSUE TITLE
Proposal. Forms validations directive

### ISSUE THREAD

**Issue by anjmao** [ng-bootstrap/ng-bootstrap#1594]
In order to add validation error state we `has-danger`, `form-control-danger` and `form-control-feedback` css classes on different html elements
```html
<div class="form-group has-danger">
   <label class="form-control-label" for="title">Title</label>
   <input type="text" class="form-control form-control-danger" formControlName="title" id="title">
   <div class="form-control-feedback">Title is required</div>
</div>
```

With angular it looks something like this
```html
<div class="form-group" [ngClass]="{'has-danger': adForm.controls.title.invalid && adForm.controls.title.touched}">
   <label class="form-control-label" for="title">Title</label>
   <input type="text" class="form-control" [ngClass]="{'form-control-danger': adForm.controls.title.invalid && adForm.controls.title.touched}" formControlName="title" id="title">
   <div *ngIf="adForm.controls.title.invalid && adForm.controls.title.touched" class="form-control-feedback">Title is required</div>
</div>
```
 
I'm thinking about writing few directives to automatically handle all these css classes states so it can look as simple as this:
```html
<div ngbFormGroup>
   <label for="title">Title</label>
   <input type="text" ngbFormControl formControlName="title" id="title">
   <div ngbFormControlFeedback>Title is required</div>
</div>
```

**Comment by jnizet** [comment]
I proposed something similar a few weeks ago, just relying on standard bootstrap markup, on the slack channel: http://plnkr.co/edit/fqJ5ESxzH1gKX7rq446O?p=preview

**Comment by Anjmao** [comment]
I like your proposal, it's very simple 👍

**Comment by dhardtke** [comment]
The problem with jnizet's proposal is that it lacks the appropriate ".form-control-danger" class on the ".form-control" itself so the validation icon is shown.

**Comment by Juchar** [comment]
Just for other people stumbling across this, I was in the same situation and had to update the approach of @jnizet for the new bootstrap version:

```
import {ContentChild, Directive, HostBinding} from "@angular/core";
import {NgControl} from "@angular/forms";

@Directive({
  selector: '.form-group:not([ngbNoFormControlValidation]),[ngbFormControlValidation]'
})
export class NgbFormControlValidation {

  @ContentChild(NgControl)
  ngControl: NgControl;

  @HostBinding('class.is-invalid')
  @HostBinding('class.was-validated')
  get isInvalid() {
    return this.ngControl && this.ngControl.dirty && this.ngControl.invalid;
  }
}
```

**Note:**
This does not take into account the "is-valid" state where green borders are added as I don't need this right now.

**Comment by lonix1** [comment]
[ng-bootstrap-form-validation](https://www.npmjs.com/package/ng-bootstrap-form-validation) library does this automatically
