### ISSUE TITLE
Docs - for ngb-pagination

### ISSUE THREAD

**Issue by Sibiraj-S** [ng-bootstrap/ng-bootstrap#1597]
I feel that documentation( for implementation )  is not enough. It will be nice to have a better example in plunker with some dummy data. 

any starters will have trouble in understanding that.

**Comment by pkozlowski-opensource** [comment]
We've got toons of examples on https://ng-bootstrap.github.io/#/components/pagination and you can open any example in a plunker.

If you feel like there is anything missing in particular please provide more details.

**Comment by Sibiraj-S** [comment]
The script and everything was fine ..but a question arises...how do i use it in html?

 let me share a stackoverflow question i came across 

`https://stackoverflow.com/questions/41223400/how-to-implement-bootstrap-4-for-angular-2-ngb-pagination`

Someone who is pretty new or starters will have no idea how to implement.. thats why I asked​. In addition to the plunker you provided.if some practical implementation provided will avoid such confusions.

**Comment by wesleycho** [comment]
I'm not sure where the confusion is - the docs are pretty straightforward...

**Comment by Sibiraj-S** [comment]
I am sure that docs are straight forward. Can you check the stackoverflow question i referred.

Practical implementation is missing, thats what I think

**Comment by wesleycho** [comment]
I disagree - I checked out the SO question, and IMO that appeared to be a particular developer's issue, not the docs. This is a rabbit hole that I don't think should be gone down, and would bloat the documentation up dramatically, which decreases readability due to noise.

**Comment by beaverusiv** [comment]
@Sibiraj-S are you talking about implementing the logic you'd put in `pageChange`? If so, that is far too project-specific and out of the scope of what the NgbPagination component does. For example mine is this:

```
this.urlParamService.addParameters(this.parameterPrefix, { pageNum: (event - 1) });
this.tableLoad = this.tableSource.take(1).subscribe((r) => this.rows = this.parseRows(r));
```

Nothing there that would be applicable to anyone else.

**Comment by Sibiraj-S** [comment]
Thanks, @beaverusiv. 

@wesleycho. I felt that some examples, as mentioned by @beaverusiv can be added to any plunk in your docs. explaining `pageChange` events. If what I said is project specific. No problem then.

**Comment by pkozlowski-opensource** [comment]
Yeh, as others commented out already this is too project-specific. Will pass on this. Thnx for the suggestion though.

**Comment by pepBR** [comment]
When someone have to go look for more info outside the documentation it means it's not enough. I agree with @Sibiraj-S.

**Comment by itsbw** [comment]
I agree with Sibiraj-S - there is a lack of documentation!
It is not clear from the doc how to register to the event.

**Comment by xoco70** [comment]
I agree with Sibiraj-S, I am beginning with Angular 6, and have no clue how to links butons next, previous, etc. with  the data available in my webservice. 

Maybe a generic example would give me an idea of how it works, and help me start :)

**Comment by IntreXonReborn** [comment]
It's not explained anywhere on how to implement and display elements in each page.
