### ISSUE TITLE
feature(modal): Hook to prevent dismissal

### ISSUE THREAD

**Issue by christarczon** [ng-bootstrap/ng-bootstrap#1598]
I'd like a way to be notified when the user attempts to dismiss the modal using the Escape key or by clicking the backdrop. The use case is that they've filled in a form in the modal and I need to confirm they want to lose their changes.

My initial thought would be to add a beforeDismiss callback in NgbModalOptions that can return false to prevent the dismiss event. I can work on a PR if this sounds plausible.

**Comment by pkozlowski-opensource** [comment]
Yeh, I understand the use-case and it is valid. I'm not sure about the proposed API, though. Could you think of other alternatives and comment back here?

**Comment by intellix** [comment]
Maybe copy Router API for CanDeactivate? https://angular.io/docs/ts/latest/guide/router.html#!#can-deactivate-guard

**Comment by JWess** [comment]
@christarczon I have the exact same use-case: I have a form in a modal and I need to confirm they want to lose their changes, but I only want to show the confirmation if the form is dirty. Since `beforeDismiss()` must be supplied via the modal config, I can't think of any way of knowing if the form is dirty or not. Did you solve this problem?

**Comment by christarczon** [comment]
@JWess I can't believe this was a year ago! No I never implemented with beforeDismiss, our design was changed.

_Disclaimer: Haven't tested this, it's mostly off the top of my head_

You'll need to have a reference to the form using ViewChild.

`<form #modalForm="ngForm">`

`@ViewChild('modalForm')`
`modalForm: NgForm;`

Modal from template:
`this.modal.open(template, {`
`  beforeDismiss: () => {`
`    if (this.modalForm.dirty) {`
`      return confirm('Do you want to lose your changes?');`
`    }`
`  }`
`});`

Modal from component:
`const modalRef = this.modal.open(MyComponent, {`
`  beforeDismiss: () => {`
`    if (modalRef.componentInstance.modalForm.dirty) {`
`      return confirm('Do you want to lose your changes?');`
`    }`
`  }`
`});`

If you don't want to use the native confirm() you'll have to always return false then manually close the modal if they say OK.
