### ISSUE TITLE
Add possibility to check if modalRef is shown

### ISSUE THREAD

**Issue by kotmatpockuh** [ng-bootstrap/ng-bootstrap#1600]
### Bug description:
Pure bootstrap has event listener to check when modal is shown. NgbModal - no :(
But I think, this is a good idea (for example in some bad UI cases i need to hide other modals, and i need to check whether current modal is shown or hidden)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.1

ng-bootstrap: 1.0.0-alpha.26

Bootstrap:

**Comment by pkozlowski-opensource** [comment]
> for example in some bad UI cases i need to hide other modals, and i need to check whether current modal is shown or hidden

@kotmatpockuh could you please elaborate (ideally with a minimal example in a plunker) on what you are trying to do, exactly? It is not very clear for me what exact use-case you are trying to tackle.

Having more info and real-life use-cases would help us to prioritise this item.

**Comment by kotmatpockuh** [comment]
@pkozlowski-opensource  for example: i have to show to modals at the same time (yeah, a weird case, but...) - and to hide one of two modals, i have to check whether there are any open modals right now or not. Is it a little bit more clear now?

**Comment by pkozlowski-opensource** [comment]
>  i have to check whether there are any open modals right now or not

Would a method on [NgbModal service](https://ng-bootstrap.github.io/#/components/modal/api), sth like `ngbModalService.hasOpenModals()` would work for you?

Or are you after checking things on each and individual modal? (In this case a method on `NgbModalRef`, sth like modalRef.isOpen() would make more sense)

**Comment by kotmatpockuh** [comment]
Checking `hasOpenModals` is fine.

**Comment by kotmatpockuh** [comment]
no need in checking every modal)
