### ISSUE TITLE
Modal plunker demo doesn't open in IE11 and gives console errors

### ISSUE THREAD

**Issue by markkesty** [ng-bootstrap/ng-bootstrap#1606]
### Bug description:

Loading the plunker demo in IE11 from your website (https://ng-bootstrap.github.io/#/components/modal)

gives the following console error and does not open: 
(SystemJS) Unable to get property 'apply' of undefined or null reference

In addition, on my own website, the modal works beautifully on Chrome, but if I open it on IE, I get "Object doesn't support property or method 'getRootNode'"

### Link to minimally-working plunker that reproduces the issue:

It's the demo modal on your own site: https://ng-bootstrap.github.io/#/components/modal

### Version of Angular, ng-bootstrap, and Bootstrap:

As per your demo page

**Comment by pkozlowski-opensource** [comment]
Yes, seems like we are missing a reference to [core-js]() in the generated `index.html` for our plunkers. 

It should be very easy change in https://github.com/ng-bootstrap/ng-bootstrap/blob/4d1b3967c2f9aaec3776ce2d391d1bb19bc6410d/misc/plunk-gen.js#L100 - community help would be highly appreciated!
