### ISSUE TITLE
ngCarousel: need info (non on internet) on how to call select() 

### ISSUE THREAD

**Issue by geetee24** [ng-bootstrap/ng-bootstrap#1608]
Please provide documentation for how to programmatically get a handle to the current ngCarousel  and then call its select method...

Found nothing on the internet

**Comment by pkozlowski-opensource** [comment]
You need to:
* export the carousel component as a variable in a template, ex.: `<ngb-carousel #myCarousel="ngbCarousel">`
* give slides you want to select id, ex.: `<ng-template ngbSlide id="mySecondSlide">`
* select a desired slide by using the exported carousel instance and slide id, ex.: `<button (click)="myCarousel.select('mySecondSlide')">Select second slide</button>`

Here is a working plunker: http://plnkr.co/edit/mS0phEdxnBJMzyfkKoiZ?p=preview

All those things are either documented on https://ng-bootstrap.github.io/#/components/carousel or a basic Angular constructs. As this is a support request, please don't open those here on GitHub but use an appropriate support channel instead: https://github.com/ng-bootstrap/ng-bootstrap#getting-help

**Comment by jbeckton** [comment]
calling select() does not work if you call it from code inside your component.

`<ngb-carousel #carousel="ngbCarousel">`

`@ViewChild('carousel', { static: true })  private carousel!: NgbCarousel;`

`this.carousel.select('packageNumber-${state.selectedPackageNumber}', NgbSlideEventSource.INDICATOR);`
