### ISSUE TITLE
How can i inject the dropdown object from html to javascript in a component

### ISSUE THREAD

**Issue by Mike-Zhu** [ng-bootstrap/ng-bootstrap#1613]
like the object #myDrop="ngbDropdown",
if i want to inject to my component object,
how to do this？

**Comment by pkozlowski-opensource** [comment]
I'm sorry but it is not clear _at all_ what is your question... Please use an appropriate channel to ask for help: https://github.com/ng-bootstrap/ng-bootstrap#getting-help
