### ISSUE TITLE
[Feature Request] Pagination component with JavaScript disabled

### ISSUE THREAD

**Issue by atarix83** [ng-bootstrap/ng-bootstrap#1616]
When I'm using a pagination component It would be good to make it work even if JavsScript in web browser is disabled.
In case of using server side rendering without JavaScript enabled, pagination component is properly rendered but it doesn't allow to change page. It would be useful if I could manipulate `href` in `<a>` of the pagination controls, or it would be useful to have a simple set of “next” and “previous” links only on the server side rendering.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.2.3

ng-bootstrap: 1.0.0-alpha.18

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
I'm sorry, but working without JS on is beyond the scope of this project. Closing as won't fix.

**Comment by tdonohue** [comment]
Hi @pkozlowski-opensource, just a quick question regarding this ticket (from our team).  This issue is directly related to support for Angular Universal, as the pagination component doesn't fully work with Universal's server side rendering (when JS is disabled). Per your ticket #858, we were assuming that ng-bootstrap plans to fully support Universal. Is this no longer the case?

**Comment by pkozlowski-opensource** [comment]
@tdonohue ok, so:
* it wasn't clear that it is about Universal (when using it JS is not disabled in a browser, obviously)
* we still need a _minimal_ reproduce scenario

Happy to re-open when you've got reproduce scenario

**Comment by atarix83** [comment]
@pkozlowski-opensource  and @tdonohue : 

I found that the issue can be reproduced even if browser javascript support is enabled.
 
Indeed with Angular Universal on page load, if you try to change pagination page (by clicking on a number page link or next/prev link) during server view to client view transition, the result is that page is reload always at the first page (this effect is most visible if you start from a pagination page different by the first).
