### ISSUE TITLE
routerLink and queryParams

### ISSUE THREAD

**Issue by arswarog** [ng-bootstrap/ng-bootstrap#1617]
Feature request:

I'm need to change routerLink and queryParams in many elements in your beautiful work!

Please add routerLink and queryParams in ngbTabTitle

PS. Sorry for my bad English

**Comment by pkozlowski-opensource** [comment]
https://github.com/ng-bootstrap/ng-bootstrap#getting-help

Also check https://stackoverflow.com/questions/44534620/how-can-attach-a-route-to-the-display-of-an-ng-accordion-panel

Not sure we can help more here based on the info provided...
