### ISSUE TITLE
Round Progress Bar inside of Bootstrap Modal in IE11 prevents modal from closing properly

### ISSUE THREAD

**Issue by markkesty** [ng-bootstrap/ng-bootstrap#1618]
I have a bit of an esoteric bug with your modal which involves placing a third-party component, (https://github.com/crisbeto/angular-svg-round-progressbar) inside the button which opens the modal. (This is an actual use case for my web application. I realize that this is an issue which crosses two separate components, but there shouldn't be a limitation with the modal on what can or cannot be placed inside its button. It should open and close properly no matter what is there).

The ng-bootstrap modal works just fine in IE11 if there is no round-progress bar embedded in the modal button. However, if I put the round-progress-bar in the modal button, the modal opens but when you close the modal, the background remains and the screen is non-reactive.

The console gives the following error: ERROR TypeError: Unable to get property 'apply' of undefined or null reference

Here is a plunker which demonstrates the problem. Try clicking on the round progress bar to open the modal and then close it (in IE11, of course)

http://plnkr.co/edit/HMJr7J8fRjF7OhAYXjHu?p=preview

Angular: 4.2.0

ng-bootstrap:  4.2.0

Bootstrap: 4.2.0

**Comment by markkesty** [comment]
The workaround is to position an empty button over the round progress bar.

**Comment by pkozlowski-opensource** [comment]
@markkesty your issue sounds like the one described in #1627 - would you mind trying a work-around from #1627 and see if it fixes the issue for you?

**Comment by zuloo** [comment]
my workaround in #1627 is to add `document.body.focus();` before actually opening the modal.

**Comment by markkesty** [comment]
I inserted the workaround into the plunker above (line 15 of the code) and it does indeed fix the issue. Thanks!

**Comment by pkozlowski-opensource** [comment]
I'm going to close this one as a duplicate of #1627
