### ISSUE TITLE
which version can support angular2.0 not angular4.0

### ISSUE THREAD

**Issue by scott17090025902** [ng-bootstrap/ng-bootstrap#1620]
which version can support angular2.0 not angular4.0

**Comment by pkozlowski-opensource** [comment]
1.0.0-alpha.24 - see https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#100-alpha25-2017-04-25

Please ask those type support requests using a dedicated channel: https://github.com/ng-bootstrap/ng-bootstrap#getting-help
