### ISSUE TITLE
Test not valid for Typeahead component

### ISSUE THREAD

**Issue by MaherSoua** [ng-bootstrap/ng-bootstrap#1622]
### In the spec file or Typeahead component :
ng-bootstrap/src/typeahead/typeahead.spec.ts
In the function expectWindowResults it should test fi the window is open, but the test is checking if the function exist : 

function expectWindowResults(element, expectedResults: string[]) {
  const window = getWindow(element);
  expect(**getWindow**).not.toBeNull();
  expectResults(window, expectedResults);
}

than the test is always ok, the element argument is useless, and we can't check with the input triggered event if the test is 'ok' or 'ko'.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.1.3

ng-bootstrap: 1.0.0-alpha.26

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
You are right! Would you mind sending a PR with a fix?

**Comment by MaherSoua** [comment]
Yes of course, be with pleasure.

On Jun 19, 2017 20:52, "Pawel Kozlowski" <notifications@github.com> wrote:

You are right! Would you mind sending a PR with a fix?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ng-bootstrap/ng-bootstrap/issues/1622#issuecomment-309532517>,
or mute the thread
