### ISSUE TITLE
Unable to NPM install, "no such package available"

### ISSUE THREAD

**Issue by sparkbuzz** [ng-bootstrap/ng-bootstrap#1624]
### Bug description:

I'm trying to install the ng-bootstrap NPM package using the following command line command:

```npm install --save @ng-bootstrap/ng-bootstrap```

but getting the following error output:

```npm ERR! Darwin 16.6.0
npm ERR! argv "/Users/.../.nvm/versions/node/v6.10.0/bin/node" "/Users/.../.nvm/versions/node/v6.10.0/bin/npm" "install" "@ng-bootstrap/ng-bootstrap@1.0.0-alpha.26"
npm ERR! node v6.10.0
npm ERR! npm  v4.3.0
npm ERR! code E404

npm ERR! 404 no such package available : @ng-bootstrap/ng-bootstrap
npm ERR! 404
npm ERR! 404  '@ng-bootstrap/ng-bootstrap' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/.../.npm/_logs/2017-06-20T14_41_59_075Z-debug.log
```

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.0

ng-bootstrap: Alpha 26

Bootstrap: 4 Alpha 6

**Comment by pkozlowski-opensource** [comment]
Must be something specific to your npm configuration as the package is well present here: https://www.npmjs.com/package/@ng-bootstrap/ng-bootstrap

Run `npm info '@ng-bootstrap/ng-bootstrap'` and see what it gives you - if no proper package info is returned than this is definitively your npm issue (private npm repo that filters out packages?)

**Comment by sparkbuzz** [comment]
Thanks for the feedback. I will try to isolate from my setup and see if I can get it working.

**Comment by sparkbuzz** [comment]
Ok, so upon further investigation, this was exactly the case @pkozlowski-opensource . When I started working here, someone had me edit the .npmrc file and added some configuration to private repos as such:

`@ourstuff:registry=http://npm.ourcompany.net`

After adding

`@ng-bootstrap:registry=https://registry.npmjs.org`

ng-bootstrap was able to install perfectly. I don't like the above solution, it feels wrong, so will Google around on the right way to achieve this.

Thanks for the assistance!

**Comment by pkozlowski-opensource** [comment]
Glad it worked for you!

**Comment by segux** [comment]
> Ok, so upon further investigation, this was exactly the case @pkozlowski-opensource . When I started working here, someone had me edit the .npmrc file and added some configuration to private repos as such:
> 
> `@ourstuff:registry=http://npm.ourcompany.net`
> 
> After adding
> 
> `@ng-bootstrap:registry=https://registry.npmjs.org`
> 
> ng-bootstrap was able to install perfectly. I don't like the above solution, it feels wrong, so will Google around on the right way to achieve this.
> 
> Thanks for the assistance!

Did you noticed about other solution? i think is a ugly mode to solve scoped packages
