### ISSUE TITLE
modal-window.ngOnDestroy() tries to apply focus unconditionaly

### ISSUE THREAD

**Issue by zuloo** [ng-bootstrap/ng-bootstrap#1627]
### Bug description:

if the modal was opened when an element was active, that does not support the focus method (i.e. SVGSVGElement in some IE versions), dismissing and closing the modal ends in an Exception, leaving the Backdrop opened and the app unusable.

I could only confirm this issue in some IE versions used within a corporation I work for, so no plunker for now -  the dirty workaround is to focus document.body before opening the modal for now.

checking if this._elWithFocus actually has the focus method would solve the issue.
```
ngOnDestroy() {
  if ( this._elWithFocus && CHECKHERE && document.body.contains(this._elWithFocus)) {
    this._elWithFocus['focus'].apply(this._elWithFocus, []);
  } else {
    document.body['focus'].apply(document.body, []);
  }

  this._elWithFocus = null;
  this._renderer.removeClass(document.body, 'modal-open');
}
```

CHECKHERE could be `this._elWithFocus.focus`

**Comment by pkozlowski-opensource** [comment]
Sounds very much like #1618

**Comment by zuloo** [comment]
indeed, it sounds like the same error message i got. And since the progress bar is SVG based it seems plausible.

**Comment by pkozlowski-opensource** [comment]
Plunker with the reproduce scenario: http://plnkr.co/edit/HMJr7J8fRjF7OhAYXjHu?p=preview (taken from #1618)

**Comment by pkozlowski-opensource** [comment]
Changes to be done in https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/modal/modal-window.ts#L70-L74
