### ISSUE TITLE
ngbDropdown not close when window resized and mouse right click

### ISSUE THREAD

**Issue by Yura13** [ng-bootstrap/ng-bootstrap#1635]
### Bug description:
Dropdown doesn't close when a window is resized or mouse right click emit.
Please add hostlisteners to ngbDropdown (window:resize and document:contextmenu) for closing dropdown.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
4.2.2
ng-bootstrap:
1.0.0-alpha.26
Bootstrap:
4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
I'm sorry but adding listener to `window:resize` would be horrible from the performance point of view. If you believe that this is needed in your application than you can register this event listener on your side and manually open / close dropdowns (using the `close` method from https://ng-bootstrap.github.io/#/components/dropdown)

Closing as won't fix.

**Comment by Yura13** [comment]
What do think about closing after event 'document:contextmenu'?
