### ISSUE TITLE
Previous clicked page emitted on pagination in typescript

### ISSUE THREAD

**Issue by samnadarajan** [ng-bootstrap/ng-bootstrap#1640]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
When clicking on any page I can see the current page displayed in the template just fine, however, I need the current page in typescript. When I bind the directive to a click event and send back the page, the page that is shown contains the previously clicked page # instead of the page # that I clicked on.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/gjc9oBuK5QQrQcQh50EY?p=preview

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.1.3

ng-bootstrap: 1.0.0-alpha.24

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
`(click)` event fires too early (before model gets updated). Use the `pageChange` event instead: http://plnkr.co/edit/WDroZF8KGbHQYCGCB38l?p=preview

Closing as a support request.
