### ISSUE TITLE
Make NgbDropdown Module self-contained.

### ISSUE THREAD

**Issue by AnimaMundi** [ng-bootstrap/ng-bootstrap#1652]
### Bug description:

This is more of a feature request than a bug, but I would like to be able to import the NgbDropdownModule on its own without having to import any other dependencies. At the moment, I also need to import NgbDropdownConfig and add that to the providers array in my module. I think NgbDropdownConfig should be added to the providers in NgbDropdownModule so that the module can stand on it's own.

Standalone modules are great for optimising techniques such as tree shaking and code splitting. I don't want to have to import all of ng-bootstrap into my bootstrap module if I don't actually need it. Making this change would make importing the module easier because there is less configuration and more understandable for less advanced users who might not know what to do if they get the error "no provider for NgbDropdownConfig".

### Link to minimally-working plunker that reproduces the issue:

There is no issue to reproduce.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.0

ng-bootstrap: 1.0.0-alpha.26

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
You can do it today, just import [NgbDropdownModule.forRoot()](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/index.ts#L44) in your Angular module. 

Config provider is already part of this module: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/dropdown/dropdown.module.ts#L10-L13

Did you try the above and hit any roadblocks?

**Comment by AnimaMundi** [comment]
No roadblocks, this is perfect, thanks! So I guess then that the issue turns into one of documentation so others can discover this very useful piece of information easily.

**Comment by thienedits** [comment]
I tried importing just NgbModalModule.forRoot(), however when I look at the produced vendor.bundle.js file It seems to include all other Ngb components as well. I'm seeing code for NgbCarousel, NgbRadio, etc.

**Comment by thienedits** [comment]
I used source-map-explorer and ng-bootstrap is indeed loading everything.

https://medium.com/@armno/til-analyzing-angular-apps-bundle-size-with-sourcemaps-explorer-f688e8a2386c
