### ISSUE TITLE
TypeAhead is broken - cant select a row in search result if click on the actual text

### ISSUE THREAD

**Issue by geetee24** [ng-bootstrap/ng-bootstrap#1659]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
TypeAhead is broken - cant select a row in search result if click on the actual text.  If however you click on the non text area in the blue row, it will actually select the row and generate the select event. see it also broken in the demo. See attached JPG showing issue.
![img0000](https://user-images.githubusercontent.com/6679119/27940847-2e5c4922-6282-11e7-9048-61c443d06fb9.jpg)

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not

_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.

ng-bootstrap: latest

Bootstrap:

**Comment by pkozlowski-opensource** [comment]
Likely a regression introduced in 5cfd9e43a3a9d06a29fefce4e468075c9b58effa

**Comment by geetee24** [comment]
Thank you.  Any idea when it can be fixed for the typeahead is not usable to our customers in its current state.

**Comment by Yura13** [comment]
I have the same issue. Cannot select by clicking on text in highlighted row. If press key Enter on highlighted row, everything works well.

**Comment by geetee24** [comment]
It posted the bug a week ago and got no action......  Now our product is stalled, for we cant deploy it with this breaking UI behavior and hate to have to find another component.

**Comment by pkozlowski-opensource** [comment]
@geetee24 you can always use alpha.26 instead of importing the latest alpha.27 which has the regression...

**Comment by geetee24** [comment]
Thank you. When do you think 28 will come out along with its fix?

**Comment by Tim-SE** [comment]
We have this problem also.  I tracked it down to the ngOutletContext change from 5cfd9e4.  If I revert just that one line of code and revert the code back to:
`[ngOutletContext]="{result: result, term: term, formatter: formatter}"></ng-template>`

Then it works.

**Comment by mlaval** [comment]
LGTM, I'll have another look at closure-compiler once the fix in Angular is released

**Comment by geetee24** [comment]
@mlaval 

Are you saying that you'll fix my issue? Is there a rough due date?  Thanks.

**Comment by pkozlowski-opensource** [comment]
@geetee24 it is fixed in `1.0.0-alpha.28` that just got released.
