### ISSUE TITLE
ngModel not work

### ISSUE THREAD

**Issue by ehdwns980416** [ng-bootstrap/ng-bootstrap#1662]
I want to use radio buttons. but I can't get model value..

This is my code: 

```ts
        <div class="form-group row">
          <label class="col-sm-2 form-control-label">gender</label>
          <div class="col-sm-10 btn-group" [(ngModel)]="gender" ngbRadioGroup name="gender" ngDefaultControl>
            <label class="btn btn-primary">
              <input type="radio" value="M" name="gender"> Male
            </label>
            <label class="btn btn-primary">
              <input type="radio" value="F" name="gender"> Female
            </label>
          </div>
          <em>gender: {{gender}}</em>
        </div>
```

**Comment by scttcper** [comment]
your ngModel has to be on the input elements https://angular.io/api/forms/NgModel

**Comment by scttcper** [comment]
ngModel must be on the input elements like in the examples https://ng-bootstrap.github.io/#/components/buttons

**Comment by pkozlowski-opensource** [comment]
https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

**Comment by ehdwns980416** [comment]
@scttcper in that example they use ngModel in div elements.
https://ng-bootstrap.github.io/#/components/buttons/examples

**Comment by alobban** [comment]
The template form or reactive form styles aren't working. Getting Typeerror

**Comment by pkozlowski-opensource** [comment]
@alobban there is _really_ not much we can do without a reproduce scenario _plus_ commenting on the closed issue won't get your much attention... 

If you believe that something is not working as expected please open a new issue following our issue template (remember to provide a minimal reproduce scenario in a plunker).

**Comment by cgaravito** [comment]
@alobban You are using the old version of ng-bootstrap. The problem is that no found the module NgbRadio, because the your version don't have.
