### ISSUE TITLE
(ng-bootstrap Datepicker)How to modify year type from AD(Anno Domini) to BE(Buddhist) type. 

### ISSUE THREAD

**Issue by pandaboycom** [ng-bootstrap/ng-bootstrap#1663]
Hello,
 I have a problem to modify  year type from AD(Anno Domini) to BE(Buddhist) type,
I want to something example or something hints.
thank you.

**Comment by pkozlowski-opensource** [comment]
You would have to provide a custom implementation of a [NgbCalendar](https://github.com/ng-bootstrap/ng-bootstrap/blob/0c03671c52500f13387deeaf31f815372d364c26/src/datepicker/ngb-calendar.ts#L20-L34), similar to the ones we've got for [Gregorian](https://github.com/ng-bootstrap/ng-bootstrap/blob/0c03671c52500f13387deeaf31f815372d364c26/src/datepicker/ngb-calendar.ts#L37-L101) and [Hijri](https://github.com/ng-bootstrap/ng-bootstrap/blob/0c03671c52500f13387deeaf31f815372d364c26/src/datepicker/hijri/ngb-calendar-hijri.ts) calendars (more calendar implementations are pending in open PRs).

If you end up writing custom implementation of the calendar you need, please think of opening a PR - we would gladly accept it!
