### ISSUE TITLE
Any plan to add support for navbars (and responsive behaviour)?

### ISSUE THREAD

**Issue by chrisbenseler** [ng-bootstrap/ng-bootstrap#1664]
Bootstrap has the [Navbar component](https://v4-alpha.getbootstrap.com/components/navbar/).
Is there any plan to add this component to the ng-bootstrap?

**Comment by scttcper** [comment]
Bootstrap navbar is css except for "collapse plugin" which ng-bootstrap has https://ng-bootstrap.github.io/#/components/collapse

**Comment by pkozlowski-opensource** [comment]
@scttcper is totally right - there is no need for any additional widgets - all is needed is just Bootstrap's CSS and the collapse directive. The proof - you can see responsive navbar on our [demo site](https://ng-bootstrap.github.io/#/home) done with just CSS + collapse.

Other relevant reading:
* #738
* https://github.com/ng-bootstrap/ng-bootstrap/wiki/What-qualifies-as-a-ng-bootstrap-directive-or--component%3F
