### ISSUE TITLE
this._toggleElement.contains is not a function issue

### ISSUE THREAD

**Issue by varghesep** [ng-bootstrap/ng-bootstrap#1665]
### How to reproduces the issue:

In my Angular app, I have a ```NgbDropdown```. I can click the dropdown and see the dropdown. Then it hangs there and throw the error message ```TypeError: this._toggleElement.contains is not a function``` and after a while the browser becomes unresponsive and crashes.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.2.5

ng-bootstrap: 1.0.0-alpha.27 

Bootstrap: Bootstrap 4.0.0-alpha.6

More details is in [StackOverflow](https://stackoverflow.com/questions/44971575/how-to-fix-ng-bootstrap-error-this-toggleelement-contains-is-not-a-function).

**Comment by pkozlowski-opensource** [comment]
Same root cause as in #1666
