### ISSUE TITLE
Add Hebrew calendar support to datepicker

### ISSUE THREAD

**Issue by semion1956** [ng-bootstrap/ng-bootstrap#1667]
### Currently datepicker doesn't support Hebrew calendar. As continue to #656, we need to add this feature.

The Hebrew or Jewish calendar is a lunisolar calendar. The Hebrew lunar year is about eleven days shorter than the solar year and uses the 19-year cycle to bring it into line with the solar year, with the addition of an intercalary month every two or three years, for a total of seven times per 19 years.

 In Israel, Hebrew calendar used not only for religious purposes but frequently - as an official calendar for civil purposes. As a rule, dates are shown in *right-to-left direction* and with *hebrew numerals* instead of europian digits.

**Comment by tomerm** [comment]
Suggested implementation was added via #1668

**Comment by tomerm** [comment]
This is how the calendar looks like: 
![image](https://user-images.githubusercontent.com/5329257/27992931-130ea656-64a8-11e7-9bc7-ac339bcf6be0.png)

**Comment by mendeza** [comment]
@semion1956 @tomerm 
Out of curiosity, for site-wide/app-wide Hebrew RTL have you rolled your own CSS or used some open source library? My team hand-rolled an RTL version of BS3 CSS a couple years ago (initially for Arabic, but equally applicable to Hebrew of course), but we have yet to repeat the exercise for BS4.

**Comment by pkozlowski-opensource** [comment]
This just got fixed via #2606
