### ISSUE TITLE
typeahead selectItem not working in Chrome

### ISSUE THREAD

**Issue by akr-optimus** [ng-bootstrap/ng-bootstrap#1677]
I am using the @ng-bootstrap/ng-bootstrap@1.0.0-alpha.28. Tried replacing the 'click' with 'mousedown'. Still doesn't work. Chrome Version: Version 57.0.2987.133 (64-bit). Also tried using 'pointerdown' as read about Chrome moving away from mouse* events to pointer* events (https://developers.google.com/web/updates/2016/10/pointer-events) but still didn't work

**Comment by pkozlowski-opensource** [comment]
Please provide a minimal reproduce scenario: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by akr-optimus** [comment]
I was creating a plunkr to reproduce the issue but couldn't. Strangely the issue persisted in my application. So I explicitly imported `import {NgbTypeahead} from "@ng-bootstrap/ng-bootstrap";` into my component. And it started working. We can close this issue.

**Comment by idrakimuhamad** [comment]
Sorry to bug a closed issue, but I got something similar with typeahead which doesn't happen previously. We're using version 1.0.0-alpha.27 and the typeahead suggestion doesn't trigger the (selectItem) when clicking on the suggestion. However, if I hover away from the button/suggestion and come back again and click it -- it just work. So I wasn't sure what's the issue. Could my internal CSS double crossing it. Just thought I'd add up to this. And adding @akr-optimus suggestion doesn't actually solved it.

**Comment by pkozlowski-opensource** [comment]
@akr-optimus try `1.0.0-alpha.28` - you might be hitting a bug that was introduced in `1.0.0-alpha.27` and fixed in 0c19153432f0c851b1708b74458f105bb4846e73 (part of `1.0.0-alpha.28` )

**Comment by idrakimuhamad** [comment]
@pkozlowski-opensource man! You saved my life. Yes it indeed solve the issue. Cheers!
