### ISSUE TITLE
ngb-carousel is not responsive.

### ISSUE THREAD

**Issue by saostad** [ng-bootstrap/ng-bootstrap#1683]
in desktop view everything is good but in other viewports height is fix and width is good.

```
<div class="row slideshow">
  <div class="col-md-12">
    <ngb-carousel *ngIf="medias">
      <ng-template ngbSlide *ngFor="let item of medias" >
        <img class="img-fluid mx-auto d-block" src="" alt="Random first slide">
        <div class="carousel-caption">
          <h1>"title"</h1>
          <p>text</p>
        </div>
      </ng-template>      
    </ngb-carousel>
  </div>
</div>
```

Angular: 4.0.0

ng-bootstrap: 1.0.0-alpha.26

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
I'm sorry, but it is not clear what you are saying... Moreover you issue (if there is any) most probably steams from Bootstrap's CSS as we are _exactly_ following the Bootstrap's markup / CSS.

This is not actionable with the info provided, please follow our issue template: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug. We need more info / plunker to take it further.

**Comment by saostad** [comment]
I am expecting when the page is in mobile size it reduce carousel's height same as width, but You Right this is a problem from bootstrap! 
same behavior in bootstrap v4
`https://v4-alpha.getbootstrap.com/components/carousel/`

**Comment by pkozlowski-opensource** [comment]
> You Right this is a problem from bootstrap!

Please open the issue in the Bootstrap's repository, then. We can't do much without having proper CSS.
