### ISSUE TITLE
Feature request: Add configuration and input disabled to dropdown

### ISSUE THREAD

**Issue by gregbown** [ng-bootstrap/ng-bootstrap#1689]
In some situations a UI feature may need to be disabled.  Currently the only way to disable the dropdown is to set it to display: none through a class binding. Of course design wants us to just be set opacity 0.3 to indicate it is disabled, but then you would be able to open it, sigh...

Any work around is welcome, however; a disabled setting would a useful feature.  It would seem fairly easy to implement having the property disabled = false by default and then adding
`if (!this._open && !this.disabled) {...`

Thank you

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4+

ng-bootstrap: 1+

Bootstrap: 4+

**Comment by gregbown** [comment]
Here is a work around that allows displaying the drop-down while disabling.  If the public variable myDropdown.disabled is set to true the desired outcome is achieved.
In template
`[ngClass]="{'disabled': myDropdown.disabled}"`
In css
`.disabled {
    opacity: .3;
    pointer-events: none;
  }
`

**Comment by pkozlowski-opensource** [comment]
@gregbown why not simply setting `disabled` property on a button that acts as a trigger for dropdowns? It is as simple as doing `<button class="btn btn-outline-primary" id="dropdownBasic1" ngbDropdownToggle [disabled]="true">Toggle dropdown</button>` and seems to achieve exactly what you need: http://plnkr.co/edit/W8pZDbEciT6ZQc5hlFAt?p=preview

Would it work for you?

**Comment by pkozlowski-opensource** [comment]
Going to close this one based on https://github.com/ng-bootstrap/ng-bootstrap/issues/1689#issuecomment-319631671 but feel free to comment back here is you believe that more changes are needed to the existing dropdown implementation. We might re-open / re-consider based on the provided input.
