### ISSUE TITLE
Carousel: restart timer when bound interval changes

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#1690]
Based on https://stackoverflow.com/a/45162091/1418796

**Comment by dmytroyarmak** [comment]
I would like to fix this bug

**Comment by pkozlowski-opensource** [comment]
Go for it @dmytroyarmak ! Here is an article that might help you preparing a PR: https://github.com/ng-bootstrap/ng-bootstrap/wiki/How-to-get-a-PR-merged-fast%3F
