### ISSUE TITLE
New feature for Modal: listener to close event 

### ISSUE THREAD

**Issue by chrisbenseler** [ng-bootstrap/ng-bootstrap#1693]
A modal can be created and opened:

`const modal = this.modalService.open(SomeComponent);`

and with the 'modal' reference, it is possible to close the modal
`modal.close();`

but if there is a backdrop, the modal can be closed by the user/visitor clicking on it (or outside the modal), then the modal is closed but it's not possible to get this 'event'. I didn't find any solution for this reading the [API doc](https://ng-bootstrap.github.io/#/components/modal/api).

My proposal is to add some kind of event listener, like:

`modal.on('close', someCallbackFunction)`

or as a promise
`modal.closed().then( someHandler )`

**Comment by pkozlowski-opensource** [comment]
You can do this today: 

```javascript
const modal = this.modalService.open(SomeComponent);
modal. result.then(() => { console.log('When user closes'); }, () => { console.log('Backdrop click')})
```

In other words, the `result` promise is _rejected_ when a user clicks on backdrop, uses the `ESC` key.

**Comment by chrisbenseler** [comment]
Thanks @pkozlowski-opensource that worked like a charm.
