### ISSUE TITLE
Question regarding unit test of async typehead

### ISSUE THREAD

**Issue by SlimDogs** [ng-bootstrap/ng-bootstrap#1695]
Hi,

It's not an Issue and I'm sorry if it's wrong place to paste it, but maybe someone will be able to help me there.

I am using typeahead component which is doing async call to get the suggestions. It's almost same as provided in one of your examples: http://plnkr.co/edit/?p=preview

'src/typeahead-http.ts' contains method search. I have spend few hours already trying to write a unit test for that but still no success... Here is one of my tries:

```
  it('Should get suggestions', async(() => {
    jasmine.clock().install();
    spyOn(_service, 'search');
    component.search(Observable.of('123test'));
    jasmine.clock().tick(1000);
    console.log('Test is running finishing step...');

    expect(_service.search).toHaveBeenCalledWith('123test');
    jasmine.clock().uninstall();
  }));
```

Any suggestions? It would be really helpful if you examples would contain unit tests too.

**Comment by pkozlowski-opensource** [comment]
@SlimDogs I'm sorry, but this is _really_ not the place for the support questions, see: https://github.com/ng-bootstrap/ng-bootstrap#getting-help

Even if I would like to help you here it is impossible with the current description:
* it is not complete enough / doesn't give enough context
* there is no plunker (you've got a link to an empty plunker).

I would suggest asking on [StackOverflow](https://stackoverflow.com/questions/tagged/ng-bootstrap) with a more detailed description _and_ a _minimal_ plunk showing your test and code. We are monitoring the [ng-bootstrap tag](https://stackoverflow.com/questions/tagged/ng-bootstrap) on SO and actually answering questions there (at least ones that we can actually understand...)
