### ISSUE TITLE
Improve example Documentation for Typeahead to make sense

### ISSUE THREAD

**Issue by IAMtheIAM** [ng-bootstrap/ng-bootstrap#1698]
I'm creating a typeahead that remotely calls an api every time someone types in the input, with a small delay after typing.

This code is from the [bootstrap 4 typeahead example docs (Wikipedia example)][1] makes no sense to me with all the `.call` and `_do` functions.

Angular Component
```
    search = (text$: Observable<string>) =>
      _do.call(
         switchMap.call(
            _do.call(distinctUntilChanged.call(
               debounceTime.call(text$, 300)),
               () => this.searching = true),
               (term) => _catch.call(
                  _do.call(this._service.search(term),
                  () => this.searchFailed = false),
                  () => {
                  this.searchFailed = true;
                  return of.call([]);
            })),
         () => this.searching = false);
```

HTML
```
          <md-input-container>
            <input mdInput [ngbTypeahead]="search"
               [(ngModel)]="model"
               [formControl]="lookupSubscriberControl"
               type="text"
               placeholder="Search by Name">
            <button type="submit" mdSuffix class="material-icons">search</button>
         </md-input-container>
```
1) What does this do in English? Right now I do not understand how to read this in normal terms and therefore cannot rewrite it for my needs.
 
2) Can someone help me rewrite this in a more readable format? Such as using the chained sequence of promises, or anything else that makes more sense. 

  [1]: https://ng-bootstrap.github.io/#/components/typeahead/examples

**Comment by paulpdaniels** [comment]
I just added an answer to make this more legible on the associated SO question. But I agree these examples are *really* tortured looking.

I'd be willing to put up a PR to write these in standard format unless there is an objection from any of the maintainers as to why that style was chosen over the fluent syntax.

**Comment by paulpdaniels** [comment]
Looking at the commit for the change [here](https://github.com/ng-bootstrap/ng-bootstrap/commit/afad0ff20add5016fde49e18b746029858bf6224), the reason message given was to fix the closure compiler.  @mlaval don't mean to single you out, but could you shed some light on what the closure compiler didn't like about the `import rxjs/add/operator/` syntax? RxJS ships with Angular so I'm surprised that it doesn't support the most common form of import.

**Comment by mlaval** [comment]
@paulpdaniels These changes were made to work around a bug in the closure compiler itself: https://github.com/google/closure-compiler/issues/2247
I agree that it hurts readability of the RxJS operators, but not sure if a better work around can be found

**Comment by IAMtheIAM** [comment]
@paulpdaniels Thanks for your help, it was most beneficial and solved my issue. But I do agree that the docs should be improved for others in the future.

**Comment by pkozlowski-opensource** [comment]
I agree that in the current form the example is _very_ hard to read... I'm going to revert the change that introduced `.call(...)` as we care about this _library_ working with the closure compiler. We don't build demo with closure so we don't need to keep it closure-compatible. On top of this `.call` are needed only because of an issue in the closure compiler itself...

**Comment by IAMtheIAM** [comment]
@pkozlowski-opensource  Awesome, thanks for doing that.
