### ISSUE TITLE
Typeahead autocomplete component does not set "this.searching" flag after deleting input

### ISSUE THREAD

**Issue by IAMtheIAM** [ng-bootstrap/ng-bootstrap#1701]
On the [bootstrap 4 typeahead example docs (Wikipedia example)]( https://ng-bootstrap.github.io/#/components/typeahead/examples) example, when typing input, the word "searching" appears, then disappears as soon as a response is received. 

However, when deleting the text previously input, the searching flag reappears, and stays on indefinitely. It seems like the final `.do(() => this.searching = false)` call is being ignored, possible the observable is being canceled if there is no input?

The flag should be set to "false" when text input is deleted so the "searching" indicator does not appear. I tried messing with the code to get it working but could not get it.

**Comment by IAMtheIAM** [comment]
I found a solution. The flag needs to be set in the API method call. For example
```
   _callApi = (url: string, term: string) => {
      term = term.trim();

      // Don't call api if input is blank / deleted
      if (term === '' || term.length === 0) {
         this.searching = false; // flag set here
         return of.call([]);

      } else {
         return this.dataService.get(url + term);
      }
   }
```

Also its useful to trim the string of empty whitespace before processing it, and check the string length, in case a user inputs excessive spaces which would generate an API call each time.

**Comment by pkozlowski-opensource** [comment]
@IAMtheIAM it turned out that there was something fishy going on on our demo due to #1612. I've just reverted parts of #1612 in #1709 and now our demo is fine (you won't see it yet on the deployed site as we only push new changes to the demo site while cutting a release).

Thnx for reporting the issue!

**Comment by IAMtheIAM** [comment]
great, I will watch for the changes in the next push!
