### ISSUE TITLE
NgbCalendarIslamicCivil missing in 0.29

### ISSUE THREAD

**Issue by piernik** [ng-bootstrap/ng-bootstrap#1707]
I think You forget to include `NgbCalendarIslamicCivil` files in 29 alpha.

**Comment by pkozlowski-opensource** [comment]
Why are you saying so? It is here, well part of the npm distribution: https://unpkg.com/@ng-bootstrap/ng-bootstrap@1.0.0-alpha.29/datepicker/hijri/ngb-calendar-islamic-civil.js

**Comment by piernik** [comment]
Wierd - when I updated folder is there. Sorry for bother.
