### ISSUE TITLE
Datepicker navigation by keyboard

### ISSUE THREAD

**Issue by Yura13** [ng-bootstrap/ng-bootstrap#1708]
Currently, datepicker doesn't support navigation by press arrows and selecting a date by press enter.

**Comment by pkozlowski-opensource** [comment]
What do you mean? It _does_ support the mentioned keyboard navigation, see http://plnkr.co/edit/G8aOFqOGjZtvvnSzvDQE?p=preview 

Please follow submission guidelines when opening new issues: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment]
Closing for now. Happy to re-open when you've got more info and a reproduce scenario in a plunker.

**Comment by Yura13** [comment]
Here is the example in plunker: 
http://plnkr.co/edit/0LCfDA?p=preview

Datepicker is open after click on button or input, but when trying to navigate by keyboard does not provide any result.

Navigation by keyboard works only if you click somewhere on opened datepicker(for example you can click on - Mo, Tu, We, Th, Fr, Sa, Su; do not click on dropdowns, buttons, dates). And it is confused and not useful.

**Comment by pkozlowski-opensource** [comment]
Oh, you mean datepicker in popup! I guess it is a matter of bringing focus to the datepicker calendar when it gets opened.

**Comment by maxokorokov** [comment]
@Yura13, true. If you do the shift-tab after opening the popup - it will focus the datepicker. I also think we should simply bring focus to it after opening.

**Comment by maxokorokov** [comment]
Opened a PR to focus the datepicker by default when opening inside the popup.
Further discussion focus/keyboard handling improvements should move to #1716
