### ISSUE TITLE
Datepicker's input model not clearing if typing text

### ISSUE THREAD

**Issue by Yura13** [ng-bootstrap/ng-bootstrap#1710]
### Bug description:
Model should not consist text.
Steps:
1. Typing some text
![image](https://user-images.githubusercontent.com/17030431/28684226-4ba6245e-730c-11e7-923a-2181e4cc012d.png)

2. After input is lost focus, input is empty, but the model not clearing
![image](https://user-images.githubusercontent.com/17030431/28684233-543de28c-730c-11e7-86e2-ec2e841fdabd.png)

**Comment by pkozlowski-opensource** [comment]
> Model should not consist text.

I guess what you are trying to say is: "invalid input shouldn't be propagated to the model". Unfortunately this is _not_ how things work with Angular validators - you _have to_ propagate invalid values to model for validation to work. You can test with built-in validators (ex. RegExp).

Also check design for the datepicker validation: https://github.com/ng-bootstrap/ng-bootstrap/issues/1222#issuecomment-274771269

>  After input is lost focus, input is empty, but the model not clearing

I agree that this is confusing. We should not clear input here and keep it consistent with the model.

**Comment by pkozlowski-opensource** [comment]
Given the above the only thing we can do in this issue is to keep model and input's value consistent, that is, don't clear input's value when the model is invalid.

**Comment by Yura13** [comment]
What do you think if add validation in method writeValue() of NgbInputDatepicker directive?
I guess it can solve this problem.

**Comment by pkozlowski-opensource** [comment]
> What do you think if add validation in method writeValue() of NgbInputDatepicker directive?
I guess it can solve this problem.

I'm not sure what you are trying to say here... Angular's validation and control's behaviour follows very specific rules and we can't simply change inners working of the validation pipeline. Going against default validation behaviour in Angular would mean that people are confused and datapeicker wouldn't play nice in standard Angular forms. I would suggest diving into how NgModel, custom controls and validation work to better understand why datepicker behaves as it does, but in the nutshell: invalid entries _are_ propagated as model values. 

You might want to have a look at the PR #1725 which makes existing behaviour more reasonable (hopefully) and should fix this issue.

**Comment by Yura13** [comment]
@pkozlowski-opensource thanks, I understood your point.

**Comment by blaur** [comment]
There is no way to introduce a concept like text masking (like with angular2-text-mask)? From a usability point of view it is not acceptable for us not to dictate what a user can enter. We would get too many support tickets just for this, at least for our segment.
