### ISSUE TITLE
Bootstrap-sass module deleted after npm installing ng-bootstrap

### ISSUE THREAD

**Issue by shabanadouani** [ng-bootstrap/ng-bootstrap#1711]
### Bug description:
When I npm installed ng-bootstrap, it deleted bootstrap-sass module from node_modules

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 4.0.0
ng-bootstrap: 1.0.0-alpha.29
Bootstrap: bootstrap-sass 3.3.7

**Comment by pkozlowski-opensource** [comment]
This would be rather a bug in npm then, as we definitively _not_ delete anything. If you still believe that this is problem on the ng-bootstrap side please follow issue submission guidelines: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug
