### ISSUE TITLE
data is not persistent when switch between tabs

### ISSUE THREAD

**Issue by ankita199** [ng-bootstrap/ng-bootstrap#1715]

**Comment by pkozlowski-opensource** [comment]
You can prevent tabs from destroying by using the `[destroyOnHide]="false"` option: https://ng-bootstrap.github.io/#/components/tabs/api

Please use an appropriate channel to ask support questions: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
