### ISSUE TITLE
When clicking outside a popover, it does not close

### ISSUE THREAD

**Issue by MikeBeaton** [ng-bootstrap/ng-bootstrap#1719]
In [the ng-bootstrap popover demos](https://ng-bootstrap.github.io/#/components/popover/examples), when I click outside a pop-over which has appeared, it does not close. (I can only close it by reclicking the button which opened it.)

I hope I am not missing an intentional design decision or some other issue here. I would have expected popovers to close when I click outside them. (Is this reasonable? Or - less preferably from this developer's point of view - could it be at least a configurable option?)

I saw that this is also mentioned in @samuelsiau 's comment on #1679 .

**Comment by pkozlowski-opensource** [comment]
> I hope I am not missing an intentional design decision or some other issue here. I would have expected popovers to close when I click outside them. 

By default those are _not_ closing in the Bootstrap 4 impl: https://v4-alpha.getbootstrap.com/components/popovers/

> Is this reasonable? Or - less preferably from this developer's point of view - could it be at least a configurable option?

This is a feature request already tracked in #933. Closing as a duplicate.
