### ISSUE TITLE
NgbPagination is Displaying 1 page too many

### ISSUE THREAD

**Issue by alobban** [ng-bootstrap/ng-bootstrap#1722]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
Pagination pages aren't calculating properly. My collection size is 42 and should only be displaying **4** pages if the default is **10**. Instead it is displaying 5 pages.

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 
4.2.6

ng-bootstrap:
1.0.0-alpha.28

Bootstrap:
4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
> Pagination pages aren't calculating properly. My collection size is 42 and should only be displaying 4 pages if the default is 10. Instead it is displaying 5 pages.

I would say that it works as expected! You would have _5_ pages with the following no of items:
* 10
* 10
* 10
* 10
* 2

Closing as invalid.
