### ISSUE TITLE
Inner Accordion

### ISSUE THREAD

**Issue by ehsaanwelcome** [ng-bootstrap/ng-bootstrap#1728]
### working plunker link: 
http://plnkr.co/edit/yWan1rOnsTf4iIwpe05I?p=preview

### Bug description:
child accordion in ngb-panel does not work 

### how to produce:
expand 'first group'
click 'new property'
now click either 'first property' or collapse 'first group'
**parent panel template will get replace by child panel template** 

Angular: 4.0.3
ng-bootstrap: alpha 29
Bootstrap: alpha 6

**Comment by pkozlowski-opensource** [comment]
Duplicate of #1433 - this is a bug in Angular. Check #1433 for a work-around.
