### ISSUE TITLE
Export NgbDate as part of the library

### ISSUE THREAD

**Issue by nikmartin** [ng-bootstrap/ng-bootstrap#1729]
### Bug description: 
Several examples inline the functions before, after, equals, etc. These are all defined in the NgbDate class and used internally, but not exported. If these were exported they would be very useful to users of ngDatepicker

Angular: 4.1.1

ng-bootstrap: 1.0.0-alpha.30

**Comment by maxokorokov** [comment]
This should be partially addressed when #1753

**Comment by msosa** [comment]
I removed the export from my PR since the implementation ended up not using NgbDate

**Comment by maxokorokov** [comment]
I don't think we'll expose `NgbDate`, but please see #1979, #1977 and recently merged #1966
