### ISSUE TITLE
Webpack AoT build fails

### ISSUE THREAD

**Issue by alienlike** [ng-bootstrap/ng-bootstrap#1730]
### Bug description:

Webpack AoT build fails when ng-bootstrap is in the mix. Several errors like the following appear:

```
ERROR in ./$$_gendir/~/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory.ts
Module parse failed: <PATH>\$$_gendir\node_modules\@ng-bootstrap\ng-bootstrap\alert\alert.ngfactory.ts Unexpected token (13:21)
You may need an appropriate loader to handle this file type.
| import * as i2 from '@ng-bootstrap/ng-bootstrap/alert/alert';
| import * as i3 from '@ng-bootstrap/ng-bootstrap/alert/alert-config';
| const styles_NgbAlert:any[] = ([] as any[]);
| export const RenderType_NgbAlert:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_NgbAlert,
|     data:{}});
 @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts 10:0-103
 @ ./ClientApp/boot.server.ts
```

Removing all references to ng-bootstrap resolves the build failure.

Solution proposed in #1381 has no effect. My `tsconfig.json`:

```
{
  "compilerOptions": {
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5",
    "sourceMap": true,
    "noImplicitAny": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "skipDefaultLibCheck": true,
    "skipLibCheck": true,
    "lib": [ "es6", "dom" ],
    "types": [ "webpack-env" ]
  },
  "exclude": [ "bin", "node_modules" ],
  "atom": { "rewriteTsconfig": false }
}
```

### Version info

Angular: 4.3.3

ngtools/webpack: 1.5.5

Webpack: 2.7.0

ng-bootstrap: 1.0.0-alpha.30

Bootstrap: 4.0.0-alpha.6

OS: Win 10

**Comment by alienlike** [comment]
@pkozlowski-opensource I took a look at your demo site source code, but the webpack config is so different from mine that I wasn't able to glean much. I'm using an ASP.Net Core template provided by Microsoft, but it's very "alpha." I've already spent ~15 hours looking at this, so I think I'll just try again in a few months and hope that things work better after the open source community has a chance to refine things. Thanks.

**Comment by pkozlowski-opensource** [comment]
I would _highly_ suggest using angular-cli where things should work out of the box.

**Comment by alienlike** [comment]
Reopening this because it's becoming more urgent that I find a solution. I've created a repo to reproduce the issue: https://github.com/alienlike/NgBootstrapAoT. To set this up, I created a brand new project using the Angular template provided by VS 2017 Preview 2. Then I simply added Bootstrap 4 and ng-bootstrap to the project. This causes the AoT build to begin failing.

**Comment by alienlike** [comment]
I've just found the solution! It requires a small tweak to the webpack config provided by the VS2017 template. This will be resolved in the next release of the Microsoft SDK.

https://github.com/aspnet/JavaScriptServices/issues/1168#issuecomment-320026397
