### ISSUE TITLE
NgbModule cannot be resolved using Systemjs 0.20.x and ES6 as build target

### ISSUE THREAD

**Issue by ZuSe** [ng-bootstrap/ng-bootstrap#1735]
### Bug description:
When I try to inject the NgbModule in my app.module.ts I get the following error:

> (index):87 TypeError: Cannot read property 'forRoot' of undefined
>     at Object.execute (http://localhost:5555/app/app.module.js!transpiled:148:49)
>     at declarativeExecute (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1502127164107:1136:13)
>     at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1502127164107:1068:13)
>     at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1502127164107:1052:17)
>     at ensureEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1502127164107:1000:13)
>     at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1502127164107:613:14
>     at ZoneDelegate.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1502127164109:391:26)
>     at Zone.run (http://localhost:5555/node_modules/zone.js/dist/zone.js?1502127164109:141:43)
>     at http://localhost:5555/node_modules/zone.js/dist/zone.js?1502127164109:831:57
>     at ZoneDelegate.invokeTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1502127164109:424:31) Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues

This is because NgbModule is imported as undefined.
I am using the bundle file as described in the docs and defined it in my project.conf.ts (SystemBuilder Config):

```            {
                name: '@ng-bootstrap/ng-bootstrap',
                path: `${this.NPM_BASE}@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js`
            },
```

And imported it like this:
```
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
..
@NgModule({
    imports: [
        ...
        NgbModule.forRoot(),
```

The tsconfig looks like this:

> 
> {
>   "compilerOptions": {
>     "target": "es2015",
>     "module": "es2015",
>     "moduleResolution": "node",
>     "declaration": false,
>     "removeComments": true,
>     "noLib": false,
>     "lib": ["es2016", "dom"],
>     "emitDecoratorMetadata": true,
>     "experimentalDecorators": true,
>     "sourceMap": true,
>     "pretty": true,
>     "allowUnreachableCode": false,
>     "allowUnusedLabels": false,
>     "noImplicitAny": false,
>     "noImplicitReturns": true,
>     "noImplicitUseStrict": false,
>     "noFallthroughCasesInSwitch": true,
>     "allowSyntheticDefaultImports": true,
>     "typeRoots": [
>       "../../node_modules/@types",
>       "../../node_modules",
>       "assets/declarations"
>     ],
>     "types": [
>       "node",
>       "jasmine",
>       "systemjs"
>     ]
>   },
>   "compileOnSave": false,
>   "exclude": [
>     "app/main-prod.ts"
>   ]
> }
> 

However, when I change my tsconfig to target es5 with commonjs the project can start.
I would like to tell you why the bundle does not work with the es6 build but I had no further time for debugging the lib. Just hope some of you guys whats getting wrong at bundle creation :)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.3.3
SystemJS: 0.20.14
TypeScript: 2.4.2
ng-bootstrap: alpha-30
Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
I don't think it makes sense to use umd bundles when targeting es2015 - you would be loosing all the benefits. 

> I would like to tell you why the bundle does not work with the es6 build but I had no further time for debugging the lib.

Still, we would need a _minimal_ reproduce scenario if you believe that our bundles are at fault.

> Just hope some of you guys whats getting wrong at bundle creation :)

I don't think there is anything wrong with the umd bundles created by ng-bootstrap. Those simply shouldn't be used when targeting es2015.

I'm going to close this issue as we don't have anything here that would allow us to investigate. Also I don't believe that there is anything wrong with the npm package we publish. Obviously I might be wrong so if you still believe that published artifacts are not right please open a new issue following our issue template (we need a reproduce scenario).
