### ISSUE TITLE
Datepicker: can't set initual value using input & form control name

### ISSUE THREAD

**Issue by chrisbenseler** [ng-bootstrap/ng-bootstrap#1736]
I can't set the initial value of a datepicker that is bound to an input.
Sample code:

```
//.html
<form [formGroup]="form" class="form-default">
	<input type="text" class="form-control" formControlName="publishdate" ngbDatepicker #datepicker="ngbDatepicker">
</form>
<div class="input-group-addon" (click)="datepicker.toggle()"></div>
// ts
this.content.publishdate = new Date();
this.form.patchValue(this.content);
```

The input is not filled with the value from 'content.publishdate' and the datepicker when opened (through datepicker.toggle()) does not have the value from today.
Is this correct? I didn't find anythin in the [docs](https://ng-bootstrap.github.io/#/components/datepicker/examples) about this.

**Comment by pkozlowski-opensource** [comment]
You need to specify `publishdate` as an object (structure) with the `year`, `month` and `day` properties. Specifying `new Date()` won't work. See http://plnkr.co/edit/kj2TIP2b1DfTtWkuHFGA?p=preview and check https://ng-bootstrap.github.io/#/components/datepicker/examples for more examples.

Closing as a support request.

**Comment by Zerokk** [comment]
For me, that solution doesn't work. 

I'm using this component in a dynamic form, in which I've got a list of properties that I iterate, and return a column key, input type, etc... then, when the input type is "datepicker", I show the component:

```
        <div class="input-group" *ngIf="table?.getInputType(col.colKey) == 'datepicker'">
          <input class="form-control"  [(ngModel)]="table?.modalRefObj[col.colKey]" ngbDatepicker
        #d="ngbDatepicker">
          <div class="input-group-append">
            <button class="btn btn-outline-secondary" (click)="d.toggle()" type="button">
              <i class="fa fa-calendar" style="width: 0.85 rem; height: 0.5rem; cursor: pointer;"></i>
            </button>
          </div>
        </div>
```

The model object has the year, month and day structure. It is correctly filled with the date info, but when I see the page, the datepicker doesn't show anything; it appears completely blank.

Why does this happen?

**Comment by MuhammadAsifAdnan** [comment]
Same problem facing here.

**Comment by irvinlee** [comment]
I encountered the same problem. I fixed it by making sure that I'm passing in integers instead of strings fixed the problem:

`this.form.get('birthDate').setValue({
        year: parseInt(birthDate.format('YYYY'), 10),
        month: parseInt(birthDate.format('M'), 10),
        day: parseInt(birthDate.format('D'), 10)
      });`

**Comment by rajaramtt** [comment]
I was faced the same problem resolved using below code snippet 

```
import { Component, OnInit, EventEmitter } from '@angular/core';
import { FormBuilder, Validators, FormArray, FormGroup } from '@angular/forms';
import { DatePipe } from '@angular/common';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css']
})
export class ProfileComponent implements OnInit {

 profileForm: FormGroup;

constructor(
    private fb: FormBuilder,
    private userService: UserService,
    private datePipe: DatePipe) { }

ngOnInit() {

   this.intilizeForm();

    this.userService.clientInfo(123).subscribe(userInfo => {
    const birthYear =  Number(this.datePipe.transform(userInfo.dob, 'yyyy'));
    const birthMonth =  Number(this.datePipe.transform(userInfo.dob, 'MM'));
    const birthDay =  Number(this.datePipe.transform(userInfo.dob, 'dd'));
    this.profileForm.controls.userInfo['controls'].dob.setValue({
      year: birthYear,
      month: birthMonth,
      day: birthDay
    });
    });
}

  intilizeForm(): void {
  // Here also we can set the intial value Like dob:[ {year:1989 ,month:06, day: 10  }, ..... 
    this.profileForm = this.fb.group({
      userInfo: this.fb.group({
        dob: ['', [Validators.required]],
      }),
    });

  }

```

**Comment by jagdishmastek** [comment]
> I have faced the same problem and resolved using below code snippet
> 
> ```
> import { Component, OnInit, EventEmitter } from '@angular/core';
> import { FormBuilder, Validators, FormArray, FormGroup } from '@angular/forms';
> import { DatePipe } from '@angular/common';
> 
> @Component({
>   selector: 'app-profile',
>   templateUrl: './profile.component.html',
>   styleUrls: ['./profile.component.css']
> })
> export class ProfileComponent implements OnInit {
> 
>  profileForm: FormGroup;
> 
> constructor(
>     private fb: FormBuilder,
>     private userService: UserService,
>     private datePipe: DatePipe) { }
> 
> ngOnInit() {
> 
>    this.intilizeForm();
> 
>     this.userService.clientInfo(123).subscribe(userInfo => {
>     const birthYear =  Number(this.datePipe.transform(userInfo.dob, 'yyyy'));
>     const birthMonth =  Number(this.datePipe.transform(userInfo.dob, 'MM'));
>     const birthDay =  Number(this.datePipe.transform(userInfo.dob, 'dd'));
>     this.profileForm.controls.userInfo['controls'].dob.setValue({
>       year: birthYear,
>       month: birthMonth,
>       day: birthDay
>     });
>     });
> }
> 
>   intilizeForm(): void {
>   // Here also we can set the intial value Like dob:[ {year:1989 ,month:06, day: 10  }, ..... 
>     this.profileForm = this.fb.group({
>       userInfo: this.fb.group({
>         dob: ['', [Validators.required]],
>       }),
>     });
> 
>   }
> ```
Hi Raj,

Please add providers  [DatePipe] in @Component decorator. Below are the sample 
@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css'],
  providers: [DatePipe]
})

**Comment by tushar0708** [comment]
please try by adding providers: [{provide: NgbDateAdapter, useClass: NgbDateNativeAdapter}] in component decorator.

**Comment by dbrezoev** [comment]
Hi,
I resolved the issue by using `[value]=formControl.value | dateFormat` for the input tag.
