### ISSUE TITLE
Error in ./MoveDetailComponent class MoveDetailComponent - inline template:30:32 caused by: Cannot set property 'survey_move_dateModel' of undefined

### ISSUE THREAD

**Issue by harry122** [ng-bootstrap/ng-bootstrap#1737]
index.html

 <div class="editaddressmove">
        
        <div class="addressedit">
          <div class="movecontentleft">
            <p><strong>Pick Up Date</strong>:

              <template [ngIf]="survey.survey_move_date!=''">
                {{survey.survey_move_date | date:'dd MMM, y'}}
              </template>
            </p>
          </div>
          <div class="iconedit">
            <a class="fancybox" (click)="openPickUpCalender()" *ngIf="!seedLoader">
              <img src="../../../../images/edit-icn.png" >
            </a>

          </div>
        </div>

movedetailcomponent.ts

  private stringToPickupObject(survey_move_date:string){
    if(survey_move_date!='' && survey_move_date!=null){
      let pkpDate:any =new Date(survey_move_date);
      return {year:pkpDate.getFullYear() , month:pkpDate.getMonth()+1, day:pkpDate.getDate()};
    }
  }

  openPickUpCalender() {
    const modalRef: any = this.modalService.open(PickUpModalComponent, {size: 'sm'});
    // this.survey.survey_move_date='2017-01-02'
    modalRef.componentInstance.survey_move_dateModel = this.stringToPickupObject(this.survey.survey_move_date);
    modalRef.componentInstance.survey_move_date = this.survey.survey_move_date;
    modalRef.componentInstance.stateId = this.survey.survey_source_address.address_state_id;
    modalRef.componentInstance.holidays = this.holidays;

    modalRef.result.then((survey_move_date:any) => {
      this.survey.survey_move_date = survey_move_date;
    }, (reason:any) => {
    //   console.log('Date not selected')
    })
  }

pickupmodel.component.ts

import {Component, Input} from '@angular/core';

import {
    NgbModal, ModalDismissReasons, NgbActiveModal, NgbDatepickerConfig,
    NgbDateStruct
} from '@ng-bootstrap/ng-bootstrap';
import {FormGroup, FormBuilder} from "@angular/forms";

@Component({
    selector: 'pickup-modal',
    template: `<div class="modal-header">
          <button type="button" class="close" aria-label="Close" (click)="activeModal.close(null)">
            <span aria-hidden="true">&times;</span>
          </button>
      <h1 class="modal-title"><span>Move Date</span></h1>
    </div>
    
    <div class="modal-body">
     <ngb-datepicker #dp [(ngModel)]="survey_move_dateModel" name="move_date" #moveDate="ngbDatepicker"  
                            (ngModelChange)="onPickupDateChange($event)"
                            (navigate)="date = $event.next" [markDisabled]="isDisabled"></ngb-datepicker>
                           
     </div> 
     <div class="modal-footer">
     <button class="btn-default" (click)="activeModal.close(survey_move_date)">Done</button> 
</div>
     
`
})
export class PickUpModalComponent {

    @Input()survey_move_dateModel: any;
    @Input()survey_move_date: any;
    @Input()stateId: number;
    @Input()holidays: any[];

    constructor(private pickupDateConfig: NgbDatepickerConfig, private fb: FormBuilder, private activeModal:NgbActiveModal) {
        let currentDate: any = new Date();
        let minDate: any = new Date();
        let maxDate: any = new Date();

        if (currentDate.getHours() > 12) {
            minDate.setDate(currentDate.getDate() + 2);
            maxDate.setDate(currentDate.getDate() + 92);
            pickupDateConfig.minDate = {year: minDate.getFullYear(), month: minDate.getMonth() + 1, day: minDate.getDate()};
            pickupDateConfig.maxDate = {year: maxDate.getFullYear(), month: maxDate.getMonth() + 1, day: maxDate.getDate()};
        } else {
            minDate.setDate(currentDate.getDate() + 1);
            maxDate.setDate(currentDate.getDate() + 91);
            pickupDateConfig.minDate = {year: minDate.getFullYear(), month: minDate.getMonth() + 1, day: minDate.getDate()};
            pickupDateConfig.maxDate = {year: maxDate.getFullYear(), month: maxDate.getMonth() + 1, day: maxDate.getDate()};
        }

        // pickupDateConfig.outsideDays = 'hidden';
        this.onPickupDateChange(this.survey_move_dateModel);
    }

    private onPickupDateChange(pickupDate: any) {
        if (pickupDate != null && typeof pickupDate == 'object') {
            this.survey_move_date = pickupDate.year + '-' + pickupDate.month + '-' + pickupDate.day;
        }
    }

**Comment by pkozlowski-opensource** [comment]
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug
