### ISSUE TITLE
Feature: Can activeIds of Accordion be made two-way binding?

### ISSUE THREAD

**Issue by laserus** [ng-bootstrap/ng-bootstrap#1738]
### Feature/Bug description:
Let's say I have two nested accordions. I want to toggle external/internal accordions based on some button or any other third element.

Now I have toggle function for each accordion. But internal accordion is possbily does not exist yet (it is inside corresponding ng-template). Thus I cannot toggle it immediately, I need to save its state somewhere (e.g. activeIds and keep it until it created). If the internal accordion is created and open, then this internal state wouldn't help, I need to find it's element in template and run function toggle on top of it. All of this based on documentation.

So, it would be much better and useful to have two way biding for opened accordions (especially given this variable exists -- activeIds, but it treated only as initialization time setup). So checked only once at init.

### Version of Angular, ng-bootstrap, and Bootstrap:
All latest or anything during past 3 months.

**Comment by pkozlowski-opensource** [comment]
You can use `panelChange' [event](https://ng-bootstrap.github.io/#/components/accordion/api#NgbPanelChangeEvent) to effectively have 2-way data binding.  Would it work for you?

Having "true" 2-way data binding is problematic for accordions with `[closeOthers]="false"` as there is no one id but potentially multiple active ids.

Having said all this I'm not 100% sure that I fully understand your use-case so having a plunker with your _exact_ use-case would help.

**Comment by pkozlowski-opensource** [comment]
I'm going to close this issue as the `panelChange` event is a preferred solution and we haven't heard back from @laserus

**Comment by laserus** [comment]
@pkozlowski-opensource it is OK, I will need to make a plunker, but I do not have time for that. "panelChange" is not a solution, as panelChange is about current accordion, while we have a hierarchy of accordions (as I said one inside another). And some out-of-box double binding will help immediately. 

For now, we just repeated Angular1 ng-init directive, so whenever internal accordions are initiated we can open/close items we know (with jQuery). It is not so good, but working solution for now.

**Comment by pkozlowski-opensource** [comment]
>  I will need to make a plunker

Yeh, please do when you've got time.
