### ISSUE TITLE
Documentation: Add "do not use plain Bootstrap JS files"

### ISSUE THREAD

**Issue by jdhines** [ng-bootstrap/ng-bootstrap#1749]
The Getting Started page gives all the info needed to use ng-bootstrap from a fresh app, but some people may only start using it on a work-in-progress application, and have Bootstrap 3 running.

Could just use a warning there on that page (and/or on the Radio Button page, which is where I ran into this issue), to *NOT* use the Bootstrap proper's JS files, as it results in certain conflicts and things not working as they should (in the case of radio buttons, flowing only to the template, but not back to the model).

I've been working on an internal application that already had the Bootstrap JS files imported, and wasn't getting any errors in the console with ng-bootstrap's radio controls, but they weren't working, and I've spent about 2 days trying to figure out why.

**Comment by pkozlowski-opensource** [comment]
@jdhines could you please review if the warning from #1757 would be enough in your case?

**Comment by jdhines** [comment]
Yes, I think that would do it! So it's jQuery files too? In other words, don't use both ng-bootstrap and jQuery in a project?

**Comment by pkozlowski-opensource** [comment]
> So it's jQuery files too? In other words, don't use both ng-bootstrap and jQuery in a project?

There is nothing that should break in ng-bootstrap if you include jQuery. But ng-bootstrap has no dependency on jQuery and doesn't need it. So only include jQuery if you need it for whatever reason. But ng-bootstrap doesn't need it.
