### ISSUE TITLE
Remove modal-content component from entryComponents

### ISSUE THREAD

**Issue by tamtakoe** [ng-bootstrap/ng-bootstrap#1751]
Components as content example

> In this case remember to add content component as an entryComponents section of your NgModule.

It is bad practice force the user to think about unnecessary things. Angular router doesn't force user to use entryComponents, ngx-bootstrap works also without it.

Angular: 4.3.1
ng-bootstrap: 1.0.0-beta
Bootstrap: 4.0.0-beta

**Comment by pkozlowski-opensource** [comment]
> It is bad practice force the user to think about unnecessary things. 

Totally agree! But I believe that in this case case it is Angular who imposes this, not ng-bootstrap.

> Angular router doesn't force user to use entryComponents, 

Sure, but it requires you to specify components in the router config. So in the end of the day you _must_ list all dynamically created components _somewhere_.

> ngx-bootstrap works also without it.

Interesting. The only way of achieving this that I'm aware of would be to either lazy-load the entire module with the component (this is what router does but would be an overkill for modals, IMO) _or_ by compiling a component (that would require shipping a compiler). 

Having said this I would _love_ to have it easier on users! If you can demonstrate in a plunker that indeed other libraries are able to do without `entryComponents` I'm going to do necessary changes straight away! So please, link an example backing up your claims.

On my side I'm going to confirm with Misko / Tobias on what is technically possible.

**Comment by tamtakoe** [comment]
ngx-router also needs entryComponents. I read documentation one more time. It is there. It is my mistake.

> this is what router does but would be an overkill for modals, IMO

I'm not sure. One modal can be just component in the popup, other one is separate window with own route. Modals with photo or video of the most of social networks have own url. More than half functionality can be in modals.

Maybe it makes sense to use this way:
```js
const modals: Modals = [
  { name: 'login',  component: LoginComponent },
  { name: 'confirm', component: ConfirmComponent }
];
 
@NgModule({
  imports: [
    ModalModule.forRoot(modals)
  ],
  ...
})
```
or use for example like this
```js
const modalRef = this.modalService.open('login');
//or
this.modal.navigate(['login']);
```
Also it can be integrated with router (especially with state oriented ui-router)
It is not more difficult than current version with entryComponents but it is more disciplined way witch force user to create more reusable modals

Off-topic: There is also doesn't clear for me what is Angular lazy-loading. I will read more about it :-) I really wanted to have this feature in the Angular 1 and I used some hacks for this. Next I had some experiment which showed that in real situations [lazy-loading increases page loading time](https://github.com/tamtakoe/node-arjs-builder/blob/master/docs/intro.md) (you will periodically waiting for new modules, but weight of business code is less then half of all code). It means that using entryComponents could be recommended if you want to use lazy-loading. In other situation you can use simple way for work with modals

**Comment by pkozlowski-opensource** [comment]
After thinking about it a bit more we are going to stick with `entryComponents` for now as this is Angular-way of specifying dynamic components. The good news is that with ivy version of Angular we might relax need for `entryComponents` and remove the need for them altogether.
