### ISSUE TITLE
Feature Request: Adding Cards

### ISSUE THREAD

**Issue by Zzortell** [ng-bootstrap/ng-bootstrap#1756]
Hi everyone,

This library seems great. However, I'm hesitating to use it because there is no support new Bootstrap 4 features like [cards](https://getbootstrap.com/docs/4.0/components/card/).

More generally, this library seems to be stuck with Bootstrap 3 features. What about making scss styling available for example?

**Comment by pkozlowski-opensource** [comment]
> This library seems great.

Glad you like it!

> However, I'm hesitating to use it because there is no support new Bootstrap 4 features like cards.

We've discussed _extensively_ the idea of adding cards in #50 and we've decided against it. The main reasoning was (and still is) that abstracting it away wouldn't bring anything and would limit user options instead. Additional details could be found here:  https://github.com/ng-bootstrap/ng-bootstrap/wiki/What-qualifies-as-a-ng-bootstrap-directive-or--component%3F

We are very careful to only add features that provide enough value to pay for its existence (cost of creating and maintaining new directive, cost of new APIs and having people to learn those, cost of limiting people options etc.). So far cards didn't pass this test but we are happy to re-visit if you've got additional arguments. 

> More generally, this library seems to be stuck with Bootstrap 3 features.

This is an interesting opinion given that library supported and was built on top Of Bootstrap 4 from the day one. Could you be more specific? What particular features you are missing from Bootstrap 4 (keeping https://github.com/ng-bootstrap/ng-bootstrap/wiki/What-qualifies-as-a-ng-bootstrap-directive-or--component%3F in mind)?

> What about making scss styling available for example?

Not sure I understand... Would you mind elaborating / providing concrete examples?

**Comment by Zzortell** [comment]
Good morning! Thank you very much for your quick answer.

I have now a better understanding of your approach: the aim of this library is not replacing Bootstrap CSS but rather taking advantage of Angular to help writing some repetitive markup and data-binding.

What made me say your are stuck with Bootstrap 3 is mainly this fact:

> If you compare a list of components on the official Bootstrap 4 documentation site with the list on the ng-bootstrap demo site you will notice that those 2 list don't match.

And the fact you have components like Accordion that existed in Bootstrap 3 but not in Bootstrap 4. I understand now why.

Moreover, what made me say _"What about making scss styling available for example?"_ was the fact that you always speak about "Bootstrap CSS". So I thought that ng-bootstrap was shipped with a compiled version of Bootstrap. But in fact it's not the case as I can see sass and autoprefixer in the [dependencies](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/package.json#L102).

I think you should inform new users about the philosophy of the project and provide this link https://github.com/ng-bootstrap/ng-bootstrap/wiki/What-qualifies-as-a-ng-bootstrap-directive-or--component%3F in the README, as it will make new user understand how to use the library and what is the part of plain Bootstrap in the code they will write.

For example:

> Welcome to the Angular version of the Angular UI Bootstrap library. This library is being built from scratch by the ui-bootstrap team. We are using TypeScript and targeting the Bootstrap 4 CSS framework.
>
> The aim of this library is to ship main Bootstrap components into Angular components and directives to both benefit Angular's power and enable you to write **simpler and cleaner markup**. Thus, not all Bootstrap components have been made Angular components as Angular doesn't provide leverage for these components. Conversely, we took advantage of both Bootstrap and Angular to make some usefull, additional components as a [datepicker](https://ng-bootstrap.github.io/#/components/datepicker/api). You can learn more about our philosophy in this article: [What qualifies as a ng bootstrap directive or component](https://github.com/ng-bootstrap/ng-bootstrap/wiki/What-qualifies-as-a-ng-bootstrap-directive-or--component%3F).
>
> As with Bootstrap 4, this library is a work in progress. Please check out our list of issues to see all the things we are implementing. Feel free to make comments there.

I will give a try to this library in my new project. Thanks!

**Comment by pkozlowski-opensource** [comment]
> In a word, this is not an implementation of Bootstrap in Angular, but a helper library.

Yes. To be more precise it is re-implementation of Bootstrap's in Angular. ng-bootstrap takes advantage / builds on top of Bootstrap CSS and is not replacing it.

> And the fact you have components like Accordion that existed in Bootstrap 3 but not in Bootstrap 4

Accordions still exist in Bootstrap 4: https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example

> So I thought that ng-bootstrap was shipped with a compiled version of Bootstrap. 

No, it is not. It even doesn't have npm dependency on Bootstrap's CSS so you are free to build / include it as you want (npm, CDN, custom build etc.)

> But in fact it's not the case as I can see sass and autoprefixer in the dependencies.

sass is only for our demo page. It is not relevant to the orginal Bootstrap CSS. Once again, you are free to build and include Bootstrap CSS as you see fit.

> hink you should inform new users about the philosophy of the project and provide this link https://github.com/ng-bootstrap/ng-bootstrap/wiki/What-qualifies-as-a-ng-bootstrap-directive-or--component%3F in the README, as it will make new user understand how to use the library and what is the part of plain Bootstrap in the code they will write.

Thnx for the suggestion, I'm going to link it from the issue #825 where we track demo page improvements (https://github.com/ng-bootstrap/ng-bootstrap/issues/825#issuecomment-323374276)

Going to close this issue as I hope that things got clarified. We are going to track  documentation update in #825

**Comment by Zzortell** [comment]
Yes I saw later bootstrap was in dev-dependencies, my bad ^^

Thank you for your help!
Hope I helped :)
