### ISSUE TITLE
Feature request: Possibility to hide items instead of using *ngIf

### ISSUE THREAD

**Issue by mexanichp** [ng-bootstrap/ng-bootstrap#1760]
### Issue description:

Hi,
I'm using ng-bootstrap with [angular-universal](https://github.com/MarkPieszak/aspnetcore-angular2-universal) which gives a lot of opportunities to implement well-designed SEO. 

I faced with a problem when ng-bootstrap components are using *ngIf conditional in their templates. 
This caused pre-rendering within the server without additional "ngIf=false" content. 

I tried to copy-paste existing accordion component and swap out `ngIf` to `[hidden]={!conditional}` and this gives me an opportunity to render "hidden" content as well (which is good for search engines to have all of the content listed).
There are some screenshots how it works with `[hidden]` attribute applied to ngAccordion card-body:

#### View source

![image](https://user-images.githubusercontent.com/14793229/29463639-1353dd94-843c-11e7-8cb4-07f534e9459d.png)

So my question is can we someway make *ngIf and [hidden] statements usage dynamic? I'm a newbie at the architecture of ng-bootstrap so at first, want to ask community is this even possible to implement? If so I would like to do it.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.3.5

ng-bootstrap: 1.0.0-beta.1

Bootstrap: 4.0.0-beta

**Comment by pkozlowski-opensource** [comment]
Related: #1607 and #1370

**Comment by mexanichp** [comment]
@pkozlowski-opensource I'm not sure this one is related only to the accordion component, I believe there should be changed all components which use *ngIf for content hide, your thoughts?

**Comment by pkozlowski-opensource** [comment]
>  I believe there should be changed all components which use *ngIf for content hide, your thoughts?

This would be overkill, IMO and would negatively impact performance of apps that don't use SSR / don't need the whole content initially. 

What other components give you headache?

**Comment by mexanichp** [comment]
@pkozlowski-opensource the only one additional is Tabset

**Comment by mexanichp** [comment]
On my thoughts, there should be something like this, where flag allows angular to render content, but css styles hide it


     <div id="{{panel.id}}" role="tabpanel" [attr.aria-labelledby]="panel.id + '-header'" 
          class="card-body collapse {{isOpen(panel.id) ? 'show' : null}}" 
          *ngIf="serverRender || isOpen(panel.id)">
            <ng-template [ngTemplateOutlet]="panel.contentTpl.templateRef"></ng-template>
     </div>

**Comment by pkozlowski-opensource** [comment]
> the only one additional is Tabset

But tabset already supports `destroyOnHide` - you can use this option to have the whole DOM ready and only hidden by CSS.

> On my thoughts, there should be something like this, where flag allows angular to render content

Maybe, but this is beyond the scope of this library. Feel free to open the discussion in the Angular repository.

Going to close this issue as the only practical issues seems to be for tabset and accordions. Tabset already supports  `destroyOnHide` and we are going to add the option for accordions via #1370
