### ISSUE TITLE
destroyOnHide should not create all items at load time

### ISSUE THREAD

**Issue by achimha** [ng-bootstrap/ng-bootstrap#1761]
### Bug description:

Tabset's (and soon accordion's) `destroyOnHide` attribute basically replaces `*ngIf` with `[hidden]` so that elements don't get recreated every time you show them.

This has one side effect that is probably undesired in most situations. The elements are now immediately created with the tabset/accordion and not when the tab is first selected or the accordion first opened.

It could be solved in a backwards compatible way by adding another attribute like `lazyCreate` or the whole `destroyOnHide` semantics could be replaced for something more suitable.

**Comment by pkozlowski-opensource** [comment]
Seems like you've opened an identical issue while ago: #1584 :-) Closing as a duplicate.
