### ISSUE TITLE
A very strange question that automatically triggers scrolling

### ISSUE THREAD

**Issue by ryanypm** [ng-bootstrap/ng-bootstrap#1762]
### Bug description:
my coed
```
<input class="form-control time" placeholder="date" name="dpstart" [displayMonths]="1" readonly (click)="dstart.toggle()" [navigation]="select" ngbDatepicker #dstart="ngbDatepicker">

```
![aaa](https://user-images.githubusercontent.com/7519919/29511091-94c4d594-8690-11e7-8708-83c1e0922ced.gif)

When I annotate the following code is normal
![image](https://user-images.githubusercontent.com/7519919/29510881-f639a58a-868f-11e7-8d04-35aabddf25a7.png)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:4.0.0

ng-bootstrap:1.0.0-alpha.30

Bootstrap:4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
Please provide a minimal reproduce scenario in a plunker, as requested in the issue template. It is not actionable otherwise as noted in https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't heard back with the reproduce scenario.
