### ISSUE TITLE
Feature request: ui-select for Bootstrap 4

### ISSUE THREAD

**Issue by muizabdul29** [ng-bootstrap/ng-bootstrap#1763]
The title says it all. Are there any plans for this? Thank you!

**Comment by pkozlowski-opensource** [comment]
We are considering it (see https://github.com/ng-bootstrap/ng-bootstrap/wiki/Roadmap) but no particular plans for now (and for sure not before releasing 1.0).

Opening up this library for things like ui-select would mean breaking this library into sub-repositories, having multiple documentation sites etc. So this is not a jump we can take overnight.

I'm going to close this issue as I don't see it actionable in the short term. We want to provide more widgets outside of Bootstrap 4 core but it would require more infrastructure work beforehand.

**Comment by muizabdul29** [comment]
Ok, thank you.
