### ISSUE TITLE
Typeahead Popup Position - drop down off screen (outside view port)

### ISSUE THREAD

**Issue by SauceCode84** [ng-bootstrap/ng-bootstrap#1767]
I'm using the typeahead control, which is positioned in the top right, in the navbar.
Everything is working correctly, but the drop down is displayed partially off screen when triggered.

I've looked through the source code for the typeahead control and it is using the PopupService and Positioning util in order to achieve this positioning for the popup.

Is there some way of configuring/specifying that when a popup is displayed off screen (outside the view port) that the calculation for the positioning takes this into consideration?

### Version of Angular, ng-bootstrap, and Bootstrap:
**Angular**: 4.3.4
**ng-bootstrap**: 1.0.0-beta.1
**Bootstrap**: 4.0.0-beta

**Comment by pkozlowski-opensource** [comment]
Nope, we are not taking viewport into account when calculating position as of today. The good news, though, is that is working on a PR that is going to add viewport-awerness to the positioning service. We should have it ready in the coming days.

To enable this in typeaheads we would also need add / expose the `placement ` input so it is not hard-coded here: https://github.com/ng-bootstrap/ng-bootstrap/blob/e32fb243334aef6b789b85f2e2500ad265d186df/src/typeahead/typeahead.ts#L169

@SauceCode84 would you be up to sending a PR that adds the `placement` `@Input` to the typeahead? You could use https://github.com/ng-bootstrap/ng-bootstrap/commit/3e22a63f80a1cb6c36f203b84ce66d4ac41425a6 as inspiration. This would help us to have the feature you are after.

**Comment by collindutter** [comment]
I see that the placement input has been exposed, and I'm able to position the typeahead using it, but it still doesn't appear to be viewport conscious for me. Am I missing something?
