### ISSUE TITLE
Can't make Accordion and table work together

### ISSUE THREAD

**Issue by NikasZalias** [ng-bootstrap/ng-bootstrap#1768]
So I'm trying to make my custom table where I can click part of row and then the additional field shows up. The best way to explain what I want is to show you.. The view should look something like this:

![image](https://user-images.githubusercontent.com/10243209/29608813-f16acc2c-87fd-11e7-8483-d1a61048f9d2.png)

So my table code looks like this:

![image](https://user-images.githubusercontent.com/10243209/29609379-b3dffd80-87ff-11e7-8665-745187c2e37a.png)

and the result view I'm getting:

![image](https://user-images.githubusercontent.com/10243209/29609247-3a432c4a-87ff-11e7-93aa-2ee23d725668.png)

Could someone just help me combine accordion and table code, so it would work??

**Comment by pkozlowski-opensource** [comment]
Please use an appropriate forum for asking support questions: https://github.com/ng-bootstrap/ng-bootstrap#getting-help
