### ISSUE TITLE
multiple Datepickers on page are not working.

### ISSUE THREAD

**Issue by pkmark2** [ng-bootstrap/ng-bootstrap#1769]

**Comment by pkozlowski-opensource** [comment]
I'm sorry but there is _nothing_ we can do about the issue like this. Please follow our issue template if you believe that there is a bug in our implementation: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

I can't reproduce here: http://plnkr.co/edit/2uoT2OnI9RaqwcSxfLRD?p=preview
