### ISSUE TITLE
Any actions in component loading process makes: error ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by mixalbl4-127** [ng-bootstrap/ng-bootstrap#1774]
For example: http://plnkr.co/edit/9iTmp8WoC8jJv4pTMNeS?p=preview
```
  ngAfterViewInit(){
    this.d.manualDateChange('2017-10-10', true)
  }
```
it makes ExpressionChangedAfterItHasBeenCheckedError.
With modal box (modal component) opening same situation, I can't open modal in "constructor, onInit, etc.", it works only with:
`<button (click)="d.manualDateChange('2017-10-10', true)">`
but how to open modal in component init or set current date in dataPicker? I think with other ng-bootstrap components same situation with it :(

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.3.3

ng-bootstrap: v1.0.0-beta.2

Bootstrap: 4.0.0-beta

**Comment by pkozlowski-opensource** [comment]
> ngAfterViewInit(){
    this.d.manualDateChange('2017-10-10', true)
  }

This is not how things work in Angular, not at all! You can't change model values in `ngAfterViewInit`. Also note that `manualDateChange` is _not_ part of our public API and is not documented (https://ng-bootstrap.github.io/#/components/datepicker/api) - as such it is not meant to be called by users of a datepicker.


If you want to intialize value of a form control just do it when creating this control: 

```
constructor(){
    this.regForm = new FormGroup({
      'birthday': new FormControl({year: 2017, month: 10, day: 10}, [
        Validators.required
      ])
    });
  }
```

See working example here: http://plnkr.co/edit/9iTmp8WoC8jJv4pTMNeS?p=preview

Closing as invalid.

**Comment by pkozlowski-opensource** [comment]
BTW, didn't understand the part about modals. If you've got another issue with modal please open a separate bug report. Otherwise we are mixing several things together and it is not clear what the original problem we are dealing with.
