### ISSUE TITLE
Tooltip alignment incorrect

### ISSUE THREAD

**Issue by bluecaret** [ng-bootstrap/ng-bootstrap#1777]
### Bug description:
Alignment of Tooltips and Tooltip Arrows are incorrect

### Link to minimally-working plunker that reproduces the issue:

You can see it within the examples that ng-bootstrap provides:
https://ng-bootstrap.github.io/#/components/tooltip/examples

I've highlighted where the issue is in the following image:
![image](https://user-images.githubusercontent.com/9217636/29692754-8e45defe-88e6-11e7-8afe-2c24fd3b2786.png)

You can see that both the alignment of the tooltip is not completely centered vertically with the button (same applies for tooltips in all directions)

Also, the arrow is not centered exactly in relation to the tooltip either.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.3.6

ng-bootstrap: 4.0.0.beta.2

Bootstrap: 4.0.0.beta

**Comment by pkozlowski-opensource** [comment]
I'm seeing the same issue on the Bootstrap's demo page (https://getbootstrap.com/docs/4.0/components/tooltips/) so this would be a problem in Bootstrap's CSS.

Could you please open an issue in the Bootstrap's repository and link it back here? Thnx!

**Comment by pkozlowski-opensource** [comment]
<img width="1348" alt="screen shot 2017-08-25 at 07 13 32" src="https://user-images.githubusercontent.com/973550/29700497-4bb6c132-8965-11e7-8ae3-c6f1673f14f1.png">

**Comment by pkozlowski-opensource** [comment]
I've opened https://github.com/twbs/bootstrap/issues/23793 to track this on the Bootstrap's side

**Comment by pkozlowski-opensource** [comment]
It is fixed now with ng-bootstrap `1.0.0-beta.9` and bootstrap CSS `4.0.0-beta.3`
