### ISSUE TITLE
Dropdowns in .btn-group don't automatically close

### ISSUE THREAD

**Issue by mauricew** [ng-bootstrap/ng-bootstrap#1785]
### Bug description:
I'd like to have a .btn-group containing a few regular buttons next to a dropdown. I can do this successfully when wrapping the directive in an ng-container instead of a div, but then nothing happens upon any action that would normally close the dropdown (inside or outside).

This may also be a requirement for [split buttons](https://getbootstrap.com/docs/4.0/components/dropdowns/#split-button-dropdowns).

### Demo
https://plnkr.co/edit/AmFw1WXiDXVQQVw7vu6W?p=preview

### Library versions

Angular: 4.3.3

ng-bootstrap: 1.0.0-beta.2

Bootstrap: 4.0.0-beta

**Comment by pkozlowski-opensource** [comment]
You should be putting the `ngbDropdown` directive on the `<div>` with the `btn-group` class like so: https://plnkr.co/edit/Wo39TXt22L91MDXchGdj?p=preview

Split buttons are also working perfectly fine, as illustrated in the above plunker.

**Comment by pkozlowski-opensource** [comment]
I will keep this one open to update demo with examples.
