### ISSUE TITLE
ngOutletContext is depricated and has been removed from Angular 5.0.0-beta.5

### ISSUE THREAD

**Issue by gregbown** [ng-bootstrap/ng-bootstrap#1791]
### Bug description:
The ngOutletContext is removed from Angular 5.0.0-beta.5 and causes AOT build errors due to its use in date picker, rating and type ahead

From [Angular CHANGELOG](https://github.com/angular/angular/blob/master/CHANGELOG.md)
**common**: NgTemplateOutlet#**ngOutletContext** has been **removed** as it was deprecated since **v4**. Use NgTemplateOutlet#ngTemplateOutletContext instead.

As an interim fix I edited these [
typeahead-window.js,
typeahead-window.metadata.json,
datepicker-month-view.js,
datepicker-month-view.metadata.json,
rating.js,
rating.metadata.json
]

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: Angular 5.0.0-beta.5

ng-bootstrap: 1.0.0-beta.2

Bootstrap: 4

**Comment by pkozlowski-opensource** [comment]
Wooooops, you are right. I was _sure_ that we've updated all the deprecated API calls already, but seems like we've missed this one. Thnx for reporting.

I've just sent a PR to correct the issue (#1792) - the fix will be part of the next release.

**Comment by pkozlowski-opensource** [comment]
It is fixed in master now, I will cut a patch release later today. Once again, thnx for reporting!
