### ISSUE TITLE
include Popper.js for proper popover placement on edges

### ISSUE THREAD

**Issue by OClyde** [ng-bootstrap/ng-bootstrap#1794]
### Bug description:
In the alpha bootstrap itself had the same issue when using tether: When you place a popover close to the edge of the browser window, it won't react to it but will simply be positioned as usual and be cut off at a certain point.

By using Popper, this problem has been resolved, but unfortunately not for ngBootstrap. There has been some discussion on this before: 
https://github.com/ng-bootstrap/ng-bootstrap/issues/1679#issuecomment-321749832

In there it has been stated that the overhead of Popper is too much to take it in. But leaving it out means for those edge cases (which, at least as I assume, do occur regularly in responsive development scenarios) that popovers are unusable. 

So I'd propose to, if it shouldn't be a required dependency, to make it an optional one.

### Link to minimally-working plunker that reproduces the issue:
If you open the plunker used in the examples section directly the problem does show already:
https://ng-bootstrap.github.io/app/components/popover/demos/visibility/plnkr.html

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 4.3.3
ng-bootstrap: 1.0.0-beta.2
Bootstrap: v4.0.0-beta

Thanks for advance for your time & your efforts!

**Comment by pkozlowski-opensource** [comment]
We are not planning to add popper.js as a dependency for ng-bootstrap for several reasons:
* it has an API that is very DOM-centric and IMO not good fit for Angular
* it would be additional dependency that would increase code size and cause grief to users (just look what happened when Bootstrap added popper.js as dependency - simple search on GH issues or Stackoverflow shows amount of wested hours).

What we are going to do instead is to fix all the "edge cases" and this is what we are doing right now, see #1772 and #1782. Please check the existing issues and the mentioned PRs - if you believe that you've got a use-case that is not covered by existing tickets, open a new one and we will fix it.

Closing this one as not actionable. I'm happy to re-visit idea of using 3rd party library for positioning is someone can prepare a PR that wouldn't have breaking changes and the issues I've mentioned above.

**Comment by Kepro** [comment]
missing popper! attached to body on scroll is still on the same position...
