### ISSUE TITLE
feature request: pagination alignment

### ISSUE THREAD

**Issue by yuhj86** [ng-bootstrap/ng-bootstrap#1795]
Right now, i have to write  custom css for pagination alignment.

```
ngb-pagination /deep/ .pagination {
  justify-content: center;
}
```

ref: https://getbootstrap.com/docs/4.0/components/pagination/#alignment

**Comment by pkozlowski-opensource** [comment]
You can do this easily using [flex utils]() from Bootstrap, just add `class="d-flex justify-content-center"` to the `<ngb-pagination>` tag: http://plnkr.co/edit/gZvgkpXvRuYQdb7UogfC?p=preview

Not sure what would be an added value of having ng-bootstrap specific mechanism here... Maybe we should add this as an example to the demo page? 

@yuhj86 is the suggested solution (adding `class="d-flex justify-content-center"`) sufficient for you (this is what Bootstrap suggests anyway!)? Do you think it would be beneficial to dd this case to our demo page?

**Comment by pkozlowski-opensource** [comment]
Closing as IMO there is nothing to be "fixed" here and we haven't heard back from @yuhj86
