### ISSUE TITLE
Modal: adding a background-color to modal-header results in square corners

### ISSUE THREAD

**Issue by hfournier** [ng-bootstrap/ng-bootstrap#1807]
Bug description: If you set a background-color on the modal-header &lt;div&gt;, you get square corners at the top of the modal window. The background-color covers the rounded corners. Adding "overflow: hidden" to the parent modal-content fixes the issue.

Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/KUeARKL8lMu0d8qp0Vve?p=preview

Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.3.6

ng-bootstrap: 1.0.0-beta.3

Bootstrap: 4.0.0-beta

**Comment by pkozlowski-opensource** [comment]
This has nothing to do with this library but is rather a Bootstrap CSS related question (I'm pretty sure that you can reproduce without ng-bootstrap). Anyway, I _think_ that you can achieve the desired result with `<div class="modal-header bg-danger" style="border-radius: 0.3rem 0.3rem 0 0">`: http://plnkr.co/edit/jGMxNxVrYbQCX11uPouN?p=preview

Closing as a support question not related to this library.
