### ISSUE TITLE
Clear typeheaded input if not-editable or "clearOnBlur" param to true

### ISSUE THREAD

**Issue by FriOne** [ng-bootstrap/ng-bootstrap#1808]
### Feature description:
When users put something to a typhead input and blur from it (no items or they just not selected any), ngModel is null, but visually input has value. In case when not `editable` param is qual to `false` input should be cleared. Or at least there should be a possibility to make this automatically without clearing it by hand(e.g `clearOnBlur` param).

### Version of Angular, ng-bootstrap:

Angular: 4

ng-bootstrap: 4 beta 3

**Comment by pkozlowski-opensource** [comment]
Duplicate of #1276
