### ISSUE TITLE
Popover support append to div by class name or id

### ISSUE THREAD

**Issue by aguantlat** [ng-bootstrap/ng-bootstrap#1810]
### Version of Angular, ng-bootstrap

Angular:  4.3.6

ng-bootstrap: 1.0.0-alpha.29

**Comment by pkozlowski-opensource** [comment]
What is your exact use-case for using containers other than `body`? AFAIK most people use `container="body"` to get popups out of the "default" DOM place (next to triggering element) to avoid issues like clipping etc. In this sense it doesn't matter what the exact container is (as long as popup is not attached as a sibiling of a triggering element). 

Could you please provide more details regarding your use case, ideally with a plunker?

**Comment by pkozlowski-opensource** [comment]
I'm going to close this issue as we haven't heard back from @aguantlat and I'm not sure what the exact, practical use-case could be. Happy to re-open when / if we've got more info.
