### ISSUE TITLE
Leading zeroes

### ISSUE THREAD

**Issue by nasht00** [ng-bootstrap/ng-bootstrap#1822]
In NgbDateStruct, `month` and `day` are values without leading zeroes.

In `ngb-date-struct.ts` you wrote: "we use ISO 8601", yet Wikipedia says

> Each date and time value has a fixed number of digits that must be padded with leading zeros.

**Comment by pkozlowski-opensource** [comment]
> In NgbDateStruct, month and day are values without leading zeroes.

Those are numbers, not strings. You can add "leading zeros" to numbers in JS.
We definitively don't want to change numbers to strings at this point. 

> In ngb-date-struct.ts you wrote: "we use ISO 8601"

Yeh, I can see how it could be confusing, we should probably remove references to ISO 8601 as it deals with strings. Would you be up to sending a PR?
