### ISSUE TITLE
Tooltips not aligned correctly when element is floated

### ISSUE THREAD

**Issue by bluecaret** [ng-bootstrap/ng-bootstrap#1824]
### Bug description:

Elements with "float: right" break the alignment of the tooltip.
![image](https://user-images.githubusercontent.com/9217636/30130169-2e48791e-92fd-11e7-8a4d-d01f0db9d4ef.png)

### Link to minimally-working plunker that reproduces the issue:

Plunker
http://plnkr.co/edit/xHkwL33XzHwokw8D8VjA?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4

ng-bootstrap: 1.0.0.beta.3

Bootstrap: 4.0.0.beta

**Comment by pkozlowski-opensource** [comment]
It seems like this is already fixed in master with all the work we did on positioning recently. I'm planning to cut a new release today and after it is done I'm going to confirm with your plunker.

**Comment by pkozlowski-opensource** [comment]
Yup, this got fixed in just-released `1.0.0-beta.4`: http://plnkr.co/edit/mM97AIeJAYh4lS5TlhdJ?p=preview
