### ISSUE TITLE
Any plans for navbar?

### ISSUE THREAD

**Issue by doxasoft** [ng-bootstrap/ng-bootstrap#1828]
I haven't find any issue about adding navbar component. Is there any plan to do so?

It counts only on small resolutions and it's not hard to make the collapsed navigation show and hide but may it worth to create a component/directive for it.

**Comment by pkozlowski-opensource** [comment]
Nope, still no plans to do so, see rationale in #1664

**Comment by doxasoft** [comment]
Thanks for the quick answer. :)

**Comment by igorlino** [comment]
For whoever needs it, the precise working example is under:

https://github.com/ng-bootstrap/ng-bootstrap/blob/master/demo/src/app/app.component.html
