### ISSUE TITLE
feature(datepicker): popup disabled state

### ISSUE THREAD

**Issue by maxkorz** [ng-bootstrap/ng-bootstrap#1829]
### Bug description:
Datepicker popup can't be set to "disabled" state.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/tXfSAQl13kIPCeV4n8lR?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.3.6 

ng-bootstrap: 1.0.0-beta.2

Bootstrap: 4.0.0-beta

**Comment by pkozlowski-opensource** [comment]
`<input>` field and triggering `<button>` are 2 separate controls. You can disable them individually. If you want prevent people from typing into the field, just disable the field. If you want to disable a button - disable a button. If you wan to disable both - disable both: http://plnkr.co/edit/O8sJZ1gp1yBW651e70IO?p=preview

Closing as it works as expected.

**Comment by maxkorz** [comment]
@pkozlowski-opensource I don't want to disable the button, I want to disable `<input>` field and allow to see [disabled calendar](http://plnkr.co/edit/EGirnlWoZJfHPVZN1s4U?p=preview) by clicking on the `<button>`

**Comment by pkozlowski-opensource** [comment]
@maxkorz if you are up to sending a PR with a fix the code change would be around those lines:
* memorize disabled state in an instance variable: https://github.com/ng-bootstrap/ng-bootstrap/blob/0f92c80e7260c65e4464b6e66229804409d439f2/src/datepicker/datepicker-input.ts#L160-L165

* propagate memorized value when a popup gets opened: https://github.com/ng-bootstrap/ng-bootstrap/blob/0f92c80e7260c65e4464b6e66229804409d439f2/src/datepicker/datepicker-input.ts#L275-L284

**Comment by maxkorz** [comment]
@pkozlowski-opensource Thank you, perhaps I will send a PR when I have time (If someone else doesn't send a PR sooner)

**Comment by maxokorokov** [comment]
Do you think we should handle both cases with and without form control for this one?

- `<input ngbDatepicker  [(ngModel)]="text" disabled />` → yes
- `<input ngbDatepicker disabled />` → should we disable datepicker in this case?

@mschoudry and @chenyuzhcy, you might be interested in this question as you've opened same-looking PRs for this one

**Comment by chenyuzhcy** [comment]
@maxokorokov I think we should disable the second case

**Comment by mschoudry** [comment]
@maxokorokov I agree with @chenyuzhcy.  The datepicker should be disabled for second case aswell.

I am still trying to figure out if somehow disabled state can be accessed from the framework, rather than set/get using direct dom element and also trying not to replicate what has already been done by [NgModel](https://github.com/angular/angular/blob/4.4.5/packages/forms/src/directives/ng_model.ts#L217)
