### ISSUE TITLE
container Option for NgbDropdown

### ISSUE THREAD

**Issue by nathan059** [ng-bootstrap/ng-bootstrap#1831]
**Bug description:**

The Dropdown popup is hidden if the surrounding container is too small and has overflow: hidden. Is it possible to add an "append-to-body" or "container" option like NgbTooltip has?

**Link to minimally-working plunker that reproduces the issue:**

[http://plnkr.co/edit/0AabqSRzBQuCmgzGXOGz?p=preview](http://plnkr.co/edit/0AabqSRzBQuCmgzGXOGz?p=preview)

**Version of Angular, ng-bootstrap, and Bootstrap:**

Angular: 4.3.6

ng-bootstrap: 1.0.0-beta.4

Bootstrap: 4.0.0-beta

**Comment by nathan059** [comment]
Similar to #1380 but Dropdown vs DatePicker

**Comment by pkozlowski-opensource** [comment]
Duplicate of #1012. Please vote on the existing issues instead of opening new ones. We use number of thumbs-up votes on issues to drive our [roadmap](https://github.com/ng-bootstrap/ng-bootstrap/wiki/Roadmap)
