### ISSUE TITLE
ngbTooltip needs to work when lowercase

### ISSUE THREAD

**Issue by bluecaret** [ng-bootstrap/ng-bootstrap#1837]
### Bug description:

I'm trying to set a tooltip in a directive using HostBinding which gives me this:
@HostBinding('attr.ngbTooltip')

The issue here is the HostBinding lowercases all attributes, and since ngbTooltip requires it to be camelCase I am unable to make this work.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4

ng-bootstrap: 1.0.0 beta 4

Bootstrap: 1.0.0 beta

**Comment by pkozlowski-opensource** [comment]
Sadly, this is not how things work in Angular. In simple words, you can't dynamically add directives by having a selector in host matching a directive. In other words, host bindings are _not_ scanned / processed for directives / components. 

So, changing a selector on our side would't make your use-case work... I'm going to close this one as a technical limitation of Angular - feel free to open a feature request in the Angular repo (although I think that there are issues like this already, so please search before)
