### ISSUE TITLE
Pagination. Default current page is 1 but documentation says 0

### ISSUE THREAD

**Issue by tamtakoe** [ng-bootstrap/ng-bootstrap#1841]
Because of default current page is 1 you can't ignore first loading. Furthermore you can't override it because any incorrect value is transformed to 1

```
if (page) {
 this.load(page); //always exist
}
```
Second question is why paginator calls `pageChange` callback with default page number after page was loaded?

http://plnkr.co/edit/VGeIFzcKzGeQV8MNGQus?p=preview

----
ng-bootstrap: v1.0.0-beta.4

**Comment by pkozlowski-opensource** [comment]
I think that your main problem is that you are setting the `collectionSize` without setting `page`. If data comes dynamically (ex. collection comes from the server) you should set _both_ values dynamically. 

In other words, the pagination should be hidden or have no pages at all till the collection size is known. 

Having said all the above I'm not clear from your description what is the practical use-case so hard to offer more info... 

> Second question is why paginator calls pageChange callback with default page number after page was loaded?

in this case page changes from `undefined` to `1`.

**Comment by drewgreenwell** [comment]
Is this really a bug or just a documentation update? It seems like any invalid input to page should be set to 1. I'm anxious to get some of the other fixes in this milestone and would be willing to help out if something needs to be done, but this really doesn't seem like it warrants a bug in the framework.

**Comment by maxokorokov** [comment]
Docs need to be updated, the page can clearly can never be zero, only 1 from a user perspective. 
Plus the following case shouldn't fire at all IMO:

```html
<!-- page stays undefined → OK -->
<ngb-pagination (pageChange)="page = $event"></ngb-pagination>

<!-- page = 1 → OK -->
<ngb-pagination [collectionSize]="20" (pageChange)="page = $event"></ngb-pagination>

<!-- page = 1 → should not fire as collection size is not set-->
<ngb-pagination [page]="5" (pageChange)="page = $event"></ngb-pagination>
```

Will open a PR with updates
