### ISSUE TITLE
Lazy loaded module with modal is not working.

### ISSUE THREAD

**Issue by pushpendersingh1** [ng-bootstrap/ng-bootstrap#1842]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

I am using modal as entryComponent in my lazy loaded module. But iam gettting this error.

No component factory found for DashDashComponent. Did you add it to @NgModule.entryComponents?.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.3.0
ng-bootstrap: 1.0.0-beta.4
Bootstrap: 4.0.0-beta

###
My lazyloaded module is imported in rootModule.
I imported NgbModule.forRoot() in rootModule 
I also imported NgbModule in my Lazy loaded Module without  .forRoot & also with .forRoot,
I also declared my modalContent in entryComponent and declartion of lazy loaded module.

But everything is in vein.
Please help, i am stuck .

**Comment by pkozlowski-opensource** [comment]
> Please help, i am stuck .

Please provide a plunker with a reproduce scenario. Unfortunately we can't help with a problem that we can't see :-/ Here is why: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment]
> I also imported NgbModule in my Lazy loaded Module without .forRoot & also with .forRoot,

You definitively need only `NgbModule` (without `.forRoot()`) in the lazy-loaded module.

**Comment by pushpendersingh1** [comment]
Hi,
After 2 days, I finally found the solution as i need to pass injector from lazy-loaded component to modalService, sorry but i was not able to find in docs easily. Maybe a more description / knowledge(from my side) is required.
below code works for me.

const modalRef = this.modalService.open(DashDashComponent,{injector: this.injector});

**Comment by pkozlowski-opensource** [comment]
@pushpendersingh1 I'm glad this is resolved for you but I'm still surprised that the injector is needed in your case. If you could provide a plunker with a minimal reproduce scenario I would take a look at it.

**Comment by jeyathilak** [comment]
@pushpendersingh1 - if you could create a plunker example of how you solved it, would be greatly appreciated. I couldn't get the modal to open as a pop-up. It is appearing inline with the base component. Thank you!

**Comment by pushpendersingh1** [comment]
Please find the plnkr with issue,
[http://plnkr.co/edit/Zru5A62yruOmf3kRI3UE?p=preview]
. It was not the issue i pointed out.
I created a custom class for animating modal, that was causing issue.
I solved by adding to providers of NgbdModalComponent.

**Comment by Liero** [comment]
Please, reopen this issue. It is not solved

**Comment by pushpendersingh1** [comment]
ok

**Comment by pushpendersingh1** [comment]
@Liero  Please check this one, [](http://plnkr.co/edit/uSlaQTJYog5qM8So5qlj?p=preview) you need to add CustomModalService to providers of the component which opens up the modal.

**Comment by Liero** [comment]
It does not work, when CustomModalService and ModalContent are in different module

**Comment by jeyathilak** [comment]
yes I second @Liero I ended up not using it and implemented a custom one.

**Comment by sir-captainmorgan21** [comment]
@jeyathilak @Liero  see https://github.com/ng-bootstrap/ng-bootstrap/issues/1861
