### ISSUE TITLE
Dropdown position issue when resize window

### ISSUE THREAD

**Issue by ysds** [ng-bootstrap/ng-bootstrap#1847]
https://ng-bootstrap.github.io/#/components/dropdown/examples

![modal](https://user-images.githubusercontent.com/4065765/30422456-f54b8cb2-997a-11e7-972a-0be98b0b9eac.gif)

**Comment by pkozlowski-opensource** [comment]
@mschoudry would you mind having a look? I can reproduce it on my side as well.

**Comment by ysds** [comment]
Probably ngbDropdown requires `position: relateive` or `dropdown` class.

**Comment by pkozlowski-opensource** [comment]
> Probably ngbDropdown requires position: relateive or dropdown/dropup class.

Yep! Thnx @ysds
