### ISSUE TITLE
Datepicker btn-link style on v4-dev latest bootstrap.css

### ISSUE THREAD

**Issue by ysds** [ng-bootstrap/ng-bootstrap#1851]
btn-link's border color has removed after v4 beta bootstrap.

Related commit: https://github.com/twbs/bootstrap/pull/22951

It causes styling issue of the datepicker navigation buttons.

![image](https://user-images.githubusercontent.com/4065765/30429498-bc3f9b1c-9992-11e7-8a5f-690c67793028.png)

Demo: http://plnkr.co/edit/SnBlUTLZZa4l0jO87xjm?p=preview

Could you add `btn` class to the button. Thank you.

**Comment by sirhcybe** [comment]
How long till this gets released? My team is waiting on it to upgrade to Bootstrap beta.2.

**Comment by maxokorokov** [comment]
@sirhcybe, as soon as @pkozlowski-opensource does the release, so pretty soon :) I think there is nothing blocking now

**Comment by sirhcybe** [comment]
@maxokorokov @pkozlowski-opensource My team is approaching our release date in 2 weeks and it would be helpful to know if beta.6 will be released by then or not.

**Comment by jacroe** [comment]
@sirhcybe [beta.6](https://github.com/ng-bootstrap/ng-bootstrap/releases/tag/1.0.0-beta.6) just dropped. And I can confirm that it does include the fix for this issue.
