### ISSUE TITLE
TypeAhead's dropdown is closed when clicking on the input

### ISSUE THREAD

**Issue by ymeine** [ng-bootstrap/ng-bootstrap#1853]
### Bug description

When using the TypeAhead, when the dropdown is open, clicking on the input closes it.

Even though it could be seen as a feature, this is not necessarily intuitive nor wanted. If this behavior is considered acceptable and wanted (as default or not) we should at least provide an alternative where the dropdown doesn't close when clicking on the input.

For reference, at the time of writing those websites keep the dropdown open: 

- [Google](https://www.google.fr/)
- [Booking.com](https://www.booking.com/)
- [Amazon.com](https://www.amazon.com/)
- ...

### Link to minimally-working plunker that reproduces the issue

I just used the first one from the [documentation page](https://ng-bootstrap.github.io/#/components/typeahead/examples): https://ng-bootstrap.github.io/app/components/typeahead/demos/basic/plnkr.html

Here is the frozen plunkr: [Example usage of the typeahead widget from https://ng-bootstrap.github.io - Plunker](http://embed.plnkr.co/yQEbXluwIjbgfaeMMKbw/).

### Version of Angular, ng-bootstrap, and Bootstrap

- Angular: 4.0.3
- ng-bootstrap: 1.0.0-beta.4
- Bootstrap: 4.0.0-beta

**Comment by pkozlowski-opensource** [comment]
Yep, as discussed offline, we should change the current behaviour. PRs welcomed!
