### ISSUE TITLE
FIY Warning: Can't resolve all parameters for NgbModalRef  This will become an error in Angular v5.x

### ISSUE THREAD

**Issue by dmlb** [ng-bootstrap/ng-bootstrap#1854]
## CLI ng serve Deprecation Warning: 

Warning: Can't resolve all parameters for NgbModalRef in /node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-ref.d.ts: ([object Object], [object Object], [object Object], ?). 
This will become an error in Angular v5.x

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.3.4

angular/cli : 1.3.0

ng-bootstrap: 1.0.0-beta.4

Bootstrap: n/a

**Comment by pkozlowski-opensource** [comment]
See: https://github.com/ng-bootstrap/ng-bootstrap/issues/1840#issuecomment-328529567

tl;dr; already fixed in master, will be part of the next release.

**Comment by pkozlowski-opensource** [comment]
FYI, just released 1.0.0-beta.5 that removes the mentioned warning.
