### ISSUE TITLE
Unable to run server side rendering with angular/cli in production mode

### ISSUE THREAD

**Issue by asgerjensen** [ng-bootstrap/ng-bootstrap#1866]
### Bug description:
I try to use ng-bootstrap with @angular/cli for server side rendering.

The following scenarios work (build and run):
- non-ssr, `ng build`
- non-ssr, `ng build --prod`
- non-ssr, `ng build --prod --aot`
- ssr, `ng build`

however
- ssr, `ng build --prod` or `ng build --prod --aot` will compile, but not run.

The following error is raised by node, when running 
```
/Users/akj/gitwork/universal-test/node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.js:1
(function (exports, require, module, __filename, __dirname) { import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy, } from '@angular/core';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.2RxQ (/Users/akj/gitwork/universal-test/dist/main.bundle.js:1:8718)
    at e (/Users/akj/gitwork/universal-test/dist/main.bundle.js:1:211)
```

The error seems to indicate, that the bundles for ng-bootstrap are not available in the format that angular/cli expects it to be. 
Rumor has it, that it can be fixed by whitelisting the ng-bootstrap library in @angular/cli, for webpack transpiling, but they are reluctant to offer that as a configuration option, as 3rd party vendors should apparently adhere to this package specification:
https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit#heading=h.k0mh3o8u5hx

I have no idea if this is the issue or not.

### Link to minimally-working plunker that reproduces the issue:
Since this is not a browser side issue, I have instead created a minimal @angular/cli project, set up for SSR (only), that illustrates the issue

https://github.com/asgerjensen/ngbootstrap-universal-issues

To see output from non --prod (i.e. the one that actually works)
```
npm install
ng build  --output-hashing=false
node index.js
```

To reproduce the issue run
```
npm install
ng build --prod --aot --output-hashing=false
node index-aot.js
```

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.4.3

ng-bootstrap: 1.0.0-beta.4

Bootstrap:

**Comment by dimitriy-k** [comment]
just created similar issue 1 min before you https://github.com/ng-bootstrap/ng-bootstrap/issues/1865

**Comment by pkozlowski-opensource** [comment]
Thnx for the bug report, we are going to tackle it in #858. Closing as a duplicate.

**Comment by brnrajoriya** [comment]
Facing the same issue.
