### ISSUE TITLE
tooltip - manual trigger

### ISSUE THREAD

**Issue by sousarka** [ng-bootstrap/ng-bootstrap#1870]
### Bug description:
With manual trigger tooltip doesnt show up for the 1st  time. In the plunkr, the tooltip is supposed to come up  for any non numeric character entered (tooltip text is changed manually with a keyup event on the input). 
For example, when "a" is typed, tooltip doesn't show up. But when any other character is typed after "a", the tooltip shows up.. 

[http://plnkr.co/edit/eO3r9qiFY9MrlPs8Wumj?p=preview](http://plnkr.co/edit/eO3r9qiFY9MrlPs8Wumj?p=preview)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.3

ng-bootstrap: 1.0.0-beta.5

Bootstrap: 4.0.0-beta

**Comment by mschoudry** [comment]
Hi,
tooltip does not open if the tooltip content is empty. You are setting the tooltip content with binding, which is updated asynchronously. On the first keyup the content of tooltip is still empty when you call open, and is updated afterwards; so nothing shows up on first keyup.

To make your solution work, you can use either of following two approaches:
1. do not use binding and update the ngbTooltip content directly. 
	i. 	[ngbTooltip]="filterLineNumValidationMsg" ==> ngbTooltip (remove binding in html)
	ii. this.filterLineNumValidationMsg = "" ==> this.tooltip.ngbTooltip = ""
	iii.this.filterLineNumValidationMsg = "Value must be integer" ==> this.tooltip.ngbTooltip = "Value must be integer"

2. use setTimeout to open the tooltip
	this.tooltip.open() => setTimeout(()=> this.tooltip.open());

Regards,

**Comment by pkozlowski-opensource** [comment]
Thnx @mschoudry for the great investigation! Closing as a support request.
