### ISSUE TITLE
Advanced placement support

### ISSUE THREAD

**Issue by pzero24** [ng-bootstrap/ng-bootstrap#1871]
### Bug description:
Currently placement only supports top, bottom, left and right. However, ng bootstrap for AngularJS would support a combination of two: top left, top right, bottom left, and bottom-right. There was also support for auto placements, which means it will change automatically to make sure the content fits the screen.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/Pq2LOXE1asMwFaX4ukGR?p=preview
Just make sure to size the window small enough to see the clipping of content off the screen.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
2+

ng-bootstrap:
Any even up to latest 1.0.0-beta.1

Bootstrap:
4.0.0-beta

**Comment by pkozlowski-opensource** [comment]
All those things are already supported in the latest ng-bootstrap release, see https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md. Are you having issues with a particular placement?

**Comment by pzero24** [comment]
No, I was just confused by the documentation is all. Well done.
