### ISSUE TITLE
Proposal: Add a feature to configure/customize the components set

### ISSUE THREAD

**Issue by IvanDobrovolsky** [ng-bootstrap/ng-bootstrap#1872]
### Feature description

For most projects not all the components will be used. It'd be very nice to have a possibility to customize the set of components which is included into the final build. This is a significant performance improvement.
Like this https://getbootstrap.com/docs/3.3/customize/

**Comment by pkozlowski-opensource** [comment]
You can already import only components that you need. For example, to use only alerts you would import and use, say `NgbAlertModule` like so:

```javascript
import {NgbAlertModule} from '@ng-bootstrap/ng-bootstrap/alert/alert.module';

...

@NgModule({
  declarations: [AppComponent, ...],
  imports: [NgbAlertModule.forRoot(), ...],
  bootstrap: [AppComponent]
})
export class AppModule {
}
```
