### ISSUE TITLE
Dropdown: Allow multiple ngbDropdownToggles elements

### ISSUE THREAD

**Issue by martinsik** [ng-bootstrap/ng-bootstrap#1874]
### Bug description:

Component: Dropdown

The current `ngbDropdown` implementation allows using only one `ngbDropdownToggle` because `NgbDropdown` is using `ContentChild` https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/dropdown/dropdown.ts#L93.

I think it would be useful to support multiple `ngbDropdownToggle`s as well.

### Link to minimally-working plunker that reproduces the issue:

```
<div ngbDropdown class="d-inline-block">
  <button class="btn btn-outline-primary" ngbDropdownToggle>Toggle dropdown</button>
  <a href="#" ngbDropdownToggle>Another button</a>
  <div ngbDropdownMenu>
    <button class="dropdown-item">Action - 1</button>
    <button class="dropdown-item">Another Action</button>
    <button class="dropdown-item">Something else is here</button>
  </div>
</div>
```

Note that there are two `ngbDropdownToggle`s.

Plnkr demo: http://plnkr.co/edit/QLtL8vxCYbq811T88j9M?p=preview

Only the first `ngbDropdownToggle` will be active. This can be easily tested by switching the order of the two `ngbDropdownToggle`s.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.3

ng-bootstrap: 1.0.0-beta.5

Bootstrap: 4.0.0-beta

**Comment by pkozlowski-opensource** [comment]
> I think it would be useful to support multiple ngbDropdownToggles as well.

Could you expand on this and provide a real-life use-case? At the moment I'm having hard time seeing why / how it could be useful...

**Comment by martinsik** [comment]
@pkozlowski-opensource In general this is useful everywhere where you want to use dropdown in any different use-case than just a button + dropdown.

For example you have a list of users and you want to open a context menu when you click on username or avatar. Right now this isn't possible. You can trigger the dropdown only by clicking username or only by clicking avatar but never both.

**Comment by martinsik** [comment]
I just realized it probably is doable by manually opening the dropdown which is described at https://ng-bootstrap.github.io/#/components/dropdown/examples in the "Manual triggers" section.

**Comment by pkozlowski-opensource** [comment]
> I just realized it probably is doable by manually opening the dropdown which is described at https://ng-bootstrap.github.io/#/components/dropdown/examples in the "Manual triggers" section.

Yes. Plus we will relax need for a one trigger in #1926. Let's track further work on this in #1926
