### ISSUE TITLE
Tooltip not hidding when scroll in IE

### ISSUE THREAD

**Issue by SamuelHerrera** [ng-bootstrap/ng-bootstrap#1878]
When over a item with tooltip and then scroll with the mouse wheel, the tooltip scrolls too and not disapear,... exactly like this bug: https://github.com/twbs/bootstrap/issues/14211

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/5kYD1hoyTnKzCg4uKHqw?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.3

ng-bootstrap: 1.0.0 beta.1

Bootstrap: 4.0.0-beta

**Comment by mschoudry** [comment]
This does not seem to be a ng-bootstrap problem. These are browser traits.
Do following tests, with simple html tooltip, in IE and Chrome. 
### **On Chrome:** 
1.    open [plunker sample](http://plnkr.co/edit/iVh1yckcidTU9KOgOc1z?p=preview) 
2. 	click on the page 
3. 	hover over tootip and scroll down using mouse wheel without moving the mouse
4. 	**_tooltip goes away_**
5. 	Now open developers panel
6. 	click on the developer panel
7. 	hover over tooltip and scroll down using mosue wheel without moving the mouse
8. 	**_tooltip does not go away_**

### **On IE:**
1. 	open [the same plunker sample](http://plnkr.co/edit/iVh1yckcidTU9KOgOc1z?p=preview)  
2. 	hover over tootip and scroll down using mouse wheel without moving the mouse
3. 	**_tooltip does not go away_**

PS: example is from (https://www.w3schools.com/css/tryit.asp?filename=trycss_tooltip)

Regards,

**Comment by pkozlowski-opensource** [comment]
@mschoudry thnx for the investigation! I'm going to close this issue based on the info provided as it seems to be a bug in IE and not something we could fix on our end.
