### ISSUE TITLE
Tabset not adjusting to size of window

### ISSUE THREAD

**Issue by maxifried** [ng-bootstrap/ng-bootstrap#1882]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
Hello this is my first issue that i am submitting.. im having a problem with the tabsets...they dont adjust to the size of the window, so in smartphones i cant see some of the tabs to select them.. here is a link of a stackoverflow question that i did, there u have some pictures and code to understand better. thanks !
### Link to minimally-working plunker that reproduces the issue:
https://stackoverflow.com/questions/46532132/ng-boostrap-tabset-not-adjusting-to-windows-size
You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2

ng-bootstrap:

Bootstrap: 4

**Comment by pkozlowski-opensource** [comment]
This was fixed in 73ba757fedb34be79809d6acf242232a011b050b long time ago. Check our "Nav justification" demo for possible options that allow you to control how tabs are displayed: https://ng-bootstrap.github.io/#/components/tabs/examples
