### ISSUE TITLE
ng bootstrap dropdown with nested checkbox

### ISSUE THREAD

**Issue by winnemucca** [ng-bootstrap/ng-bootstrap#1886]
### Bug description:
 Access to adding a nested checkbox in dropdown.  Maybe I am wrong and this is a simple css fix, but it sure seems impossible to add a checkbox.  Not using jQuery.  This must be a  known issue right? 
### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
 4.3
ng-bootstrap:
^1.0.0-beta.1",
Bootstrap:
 4 beta

**Comment by icfantv** [comment]
@winnemucca, it's not clear what you've done to try and reproduce the issue, nor have you given us a working plunker to demonstrate the issue.  In the future, please be mindful of this.

I was able to get a checkbox to render very easily by adding the following HTML to the existing set of `<button>` elements in a plunker from [the first dropdown demo](https://ng-bootstrap.github.io/app/components/dropdown/demos/basic/plnkr.html):

```
<button class="dropdown-item">
  <input type="checkbox"/> Test Checkbox
</button>
```

Which will render:
![screen shot 2017-10-04 at 5 00 40 pm](https://user-images.githubusercontent.com/370054/31205328-9c79f0c8-a925-11e7-8d93-35fa42ef69f5.png)
