### ISSUE TITLE
Update `engines` in package.json

### ISSUE THREAD

**Issue by Eugeny** [ng-bootstrap/ng-bootstrap#1890]
Please either remove or adjust the maximal Node version as Node 7 is obviously supported.
This prevents the package from being installed via Yarn.

**Comment by bastienmoulia** [comment]
Node 6 was the LTS, but normally today (according https://github.com/nodejs/Release#release-schedule1) the LTS should be Node 8.

The switch to Node 8 also mean NPM 5 should be used instead of NPM 3 with all that implies (package-lock.json).

**Comment by pkozlowski-opensource** [comment]
@Eugeny what do you mean by:
> This prevents the package from being installed via Yarn.

The package we are publishing has no restrictions on node / npm whatsoever:
https://unpkg.com/@ng-bootstrap/ng-bootstrap@1.0.0-beta.5/package.json

I agree that we should bump node / npm range _at some point_ but it should only matter for ng-bootstrap developers and shouldn't have impact on users. Users should not install anything from this repo.

@bastienmoulia I agree that we might switch to yarn, there is an issue tracking this already: #872
For now we are keeping the same node / npm range as [angular itself](https://github.com/angular/angular/blob/master/package.json#L10-L14) (as several of the ng-bootstrap contributors are also Angular contributors). 

I'm going to close this one based on the above comment. Happy to re-consider when / if new info surfaces.
