### ISSUE TITLE
Data-tables feature request

### ISSUE THREAD

**Issue by SeaBear622** [ng-bootstrap/ng-bootstrap#1892]
Love this library, but I have to use [angular-4-data-table-bootstrap-4](https://www.npmjs.com/package/angular-4-data-table-bootstrap-4) for my tables.  I use it for sorting and pagination.

It would be awesome if this functionality was supported in ng-bootstrap.  That way I can reduce the number of dependencies and I know it will still be supported in the future.

Please implement this feature!

**Comment by pkozlowski-opensource** [comment]
Sorry, we've got no particular plans to add data table support for now.

**Comment by nni123** [comment]
wow really..datagrid is a lifeline in most of SPA apps unless you are targeting different user base. 

You don't have file upload and guessing from above response has no plan to implement. 

I am not going to consider your library without both components since you have no plans to implement.

**Comment by westlakem** [comment]
I have to say, I'm also very surprised that you don't have basic "table" functionality.  That's almost a requirement in any application

**Comment by georgechr** [comment]
Library needs this feature, at the moment material has the edge

**Comment by Ghislain1** [comment]
I agreed with @georgechr:  table is missing on this library
