### ISSUE TITLE
NgbTab [hidden] option

### ISSUE THREAD

**Issue by my-poi** [ng-bootstrap/ng-bootstrap#1893]
Please add:

**'hidden': [{ type: Input },],**

`NgbTab.propDecorators = {
    'id': [{ type: Input },],
    'title': [{ type: Input },],
    'disabled': [{ type: Input },],
    'hidden': [{ type: Input },],
    'contentTpl': [{ type: ContentChild, args: [NgbTabContent,] },],
    'titleTpl': [{ type: ContentChild, args: [NgbTabTitle,] },],
};`

**[ngStyle]=\"{'display': tab.hidden ? 'none' : 'block'}\"**

`NgbTabset.decorators = [
    { type: Component, args: [{
                selector: 'ngb-tabset',
                exportAs: 'ngbTabset',
                template: "\n    <ul [class]=\"'nav nav-' + type + (orientation == 'horizontal'?  ' ' + justifyClass : ' flex-column')\" role=\"tablist\">\n      <li class=\"nav-item\" *ngFor=\"let tab of tabs\" [ngStyle]=\"{'display': tab.hidden ? 'none' : 'block'}\">\n        <a [id]=\"tab.id\" class=\"nav-link\" [class.active]=\"tab.id === activeId\" [class.disabled]=\"tab.disabled\"\n          href (click)=\"!!select(tab.id)\" role=\"tab\" [attr.tabindex]=\"(tab.disabled ? '-1': undefined)\"\n          [attr.aria-controls]=\"(!destroyOnHide || tab.id === activeId ? tab.id + '-panel' : null)\"\n          [attr.aria-expanded]=\"tab.id === activeId\" [attr.aria-disabled]=\"tab.disabled\">\n          {{tab.title}}<ng-template [ngTemplateOutlet]=\"tab.titleTpl?.templateRef\"></ng-template>\n        </a>\n      </li>\n    </ul>\n    <div class=\"tab-content\">\n      <ng-template ngFor let-tab [ngForOf]=\"tabs\">\n        <div\n          class=\"tab-pane {{tab.id === activeId ? 'active' : null}}\"\n          *ngIf=\"!destroyOnHide || tab.id === activeId\"\n          role=\"tabpanel\"\n          [attr.aria-labelledby]=\"tab.id\" id=\"{{tab.id}}-panel\"\n          [attr.aria-expanded]=\"tab.id === activeId\">\n          <ng-template [ngTemplateOutlet]=\"tab.contentTpl.templateRef\"></ng-template>\n        </div>\n      </ng-template>\n    </div>\n  "
            },] },
];`

Maciej

**Comment by maxokorokov** [comment]
Hi,
is there a reason that you can't hide tabs using `<ngb-tab title="Hidden" *ngIf='false'>`? 
Also, could you please format your code, so it would be readable?

**Comment by my-poi** [comment]
Hello, I am building a stateless SPA application. All items are loaded on startup, but not all are displayed.

[GitHub](https://github.com/my-poi/optio/blob/master/optio.web/src/app/app.component.html)
[Demo](https://optio.xyz/)

Currently I have tabset src in the project and I modified:

app.module.ts

```javascript
import { NgbTabsetModule } from './modules/tabset/tabset.module';

  imports: [
    NgbTabsetModule.forRoot()
```

tabset.ts

```javascript
   /**
   * Allows toggling disabled state of a given state. Disabled tabs can't be selected.
   */
  @Input() disabled = false;
  @Input() hidden = false;
  @ContentChild(NgbTabContent) contentTpl: NgbTabContent;
  @ContentChild(NgbTabTitle) titleTpl: NgbTabTitle;
```

```javascript
/**
 * A component that makes it easy to create tabbed interface.
 */
@Component({
  selector: 'ngb-tabset',
  exportAs: 'ngbTabset',
  template: `
    <ul [class]="'nav nav-' + type + (orientation == 'horizontal'?  ' ' + justifyClass : ' flex-column')" role="tablist">
      <li class="nav-item" *ngFor="let tab of tabs" [ngStyle]="{'display': tab.hidden ? 'none' : 'block'}">
        <a [id]="tab.id" class="nav-link" [class.active]="tab.id === activeId" [class.disabled]="tab.disabled"
          href (click)="!!select(tab.id)" role="tab" [attr.tabindex]="(tab.disabled ? '-1': undefined)"
          [attr.aria-controls]="(!destroyOnHide || tab.id === activeId ? tab.id + '-panel' : null)"
          [attr.aria-expanded]="tab.id === activeId" [attr.aria-disabled]="tab.disabled">
          {{tab.title}}<ng-template [ngTemplateOutlet]="tab.titleTpl?.templateRef"></ng-template>
        </a>
      </li>
    </ul>
```

Regards,
Maciej

**Comment by maxokorokov** [comment]
Still, won't using `ngIf` be enough? I suppose it's better than setting style to `display: none`
http://plnkr.co/edit/mX8QuXyczShD9zXLizw9?p=preview

**Comment by my-poi** [comment]
NgIf create new elements, and I do not need this.
Thank you for your interest in my request.
Maciej

**Comment by julianbragachi** [comment]
@maxokorokov Also If we use NgFor to create the tabs we won't be able to use ngIf (angular doesn't allow more than one structural directive in the same element)

**Comment by maxokorokov** [comment]
@julianbragachi, check the plunker, you could use `ng-template` or `ng-containter`

**Comment by pkozlowski-opensource** [comment]
> NgIf create new elements, and I do not need this.

You can use `<ng-template [ngIf]="exp">` and in this case no additional DOM elements are created.

Closing as `ngIf` is the way to go here.

**Comment by rere252** [comment]
I have an use case where I need to dynamically hide and restore the tab. Since *ngIf is a structural directive the tab is removed from DOM when set to 'false'. This means it's state is also deleted and this is a problem when the tab becomes visible again. Could adding the [hidden] option be reconsidered?

**Comment by johaven** [comment]
+1

**Comment by charlestati** [comment]
The `hidden` attribute is needed on `ngTab` to use the `select` method:

`(click)="t.select('tab-selectbyid2')"` won't work if the tab is removed from the DOM with `*ngIf`

**Comment by Anj21** [comment]
> Please add:
> 
> **'hidden': [{ type: Input },],**
> 
> `NgbTab.propDecorators = { 'id': [{ type: Input },], 'title': [{ type: Input },], 'disabled': [{ type: Input },], 'hidden': [{ type: Input },], 'contentTpl': [{ type: ContentChild, args: [NgbTabContent,] },], 'titleTpl': [{ type: ContentChild, args: [NgbTabTitle,] },], };`
> 
> **[ngStyle]="{'display': tab.hidden ? 'none' : 'block'}"**
> 
> `NgbTabset.decorators = [ { type: Component, args: [{ selector: 'ngb-tabset', exportAs: 'ngbTabset', template: "\n <ul [class]=\"'nav nav-' + type + (orientation == 'horizontal'? ' ' + justifyClass : ' flex-column')\" role=\"tablist\">\n <li class=\"nav-item\" *ngFor=\"let tab of tabs\" [ngStyle]=\"{'display': tab.hidden ? 'none' : 'block'}\">\n <a [id]=\"tab.id\" class=\"nav-link\" [class.active]=\"tab.id === activeId\" [class.disabled]=\"tab.disabled\"\n href (click)=\"!!select(tab.id)\" role=\"tab\" [attr.tabindex]=\"(tab.disabled ? '-1': undefined)\"\n [attr.aria-controls]=\"(!destroyOnHide || tab.id === activeId ? tab.id + '-panel' : null)\"\n [attr.aria-expanded]=\"tab.id === activeId\" [attr.aria-disabled]=\"tab.disabled\">\n {{tab.title}}<ng-template [ngTemplateOutlet]=\"tab.titleTpl?.templateRef\"></ng-template>\n </a>\n </li>\n </ul>\n <div class=\"tab-content\">\n <ng-template ngFor let-tab [ngForOf]=\"tabs\">\n <div\n class=\"tab-pane {{tab.id === activeId ? 'active' : null}}\"\n *ngIf=\"!destroyOnHide || tab.id === activeId\"\n role=\"tabpanel\"\n [attr.aria-labelledby]=\"tab.id\" id=\"{{tab.id}}-panel\"\n [attr.aria-expanded]=\"tab.id === activeId\">\n <ng-template [ngTemplateOutlet]=\"tab.contentTpl.templateRef\"></ng-template>\n </div>\n </ng-template>\n </div>\n " },] }, ];`
> 
> Maciej

In angular inside my node moudles of bootstrap, in tabset.d.ts file, i don't have such type of declration, so where i need to add this, please let me know.

**Comment by Anj21** [comment]
> Please add:
> 
> **'hidden': [{ type: Input },],**
> 
> `NgbTab.propDecorators = { 'id': [{ type: Input },], 'title': [{ type: Input },], 'disabled': [{ type: Input },], 'hidden': [{ type: Input },], 'contentTpl': [{ type: ContentChild, args: [NgbTabContent,] },], 'titleTpl': [{ type: ContentChild, args: [NgbTabTitle,] },], };`
> 
> **[ngStyle]="{'display': tab.hidden ? 'none' : 'block'}"**
> 
> `NgbTabset.decorators = [ { type: Component, args: [{ selector: 'ngb-tabset', exportAs: 'ngbTabset', template: "\n <ul [class]=\"'nav nav-' + type + (orientation == 'horizontal'? ' ' + justifyClass : ' flex-column')\" role=\"tablist\">\n <li class=\"nav-item\" *ngFor=\"let tab of tabs\" [ngStyle]=\"{'display': tab.hidden ? 'none' : 'block'}\">\n <a [id]=\"tab.id\" class=\"nav-link\" [class.active]=\"tab.id === activeId\" [class.disabled]=\"tab.disabled\"\n href (click)=\"!!select(tab.id)\" role=\"tab\" [attr.tabindex]=\"(tab.disabled ? '-1': undefined)\"\n [attr.aria-controls]=\"(!destroyOnHide || tab.id === activeId ? tab.id + '-panel' : null)\"\n [attr.aria-expanded]=\"tab.id === activeId\" [attr.aria-disabled]=\"tab.disabled\">\n {{tab.title}}<ng-template [ngTemplateOutlet]=\"tab.titleTpl?.templateRef\"></ng-template>\n </a>\n </li>\n </ul>\n <div class=\"tab-content\">\n <ng-template ngFor let-tab [ngForOf]=\"tabs\">\n <div\n class=\"tab-pane {{tab.id === activeId ? 'active' : null}}\"\n *ngIf=\"!destroyOnHide || tab.id === activeId\"\n role=\"tabpanel\"\n [attr.aria-labelledby]=\"tab.id\" id=\"{{tab.id}}-panel\"\n [attr.aria-expanded]=\"tab.id === activeId\">\n <ng-template [ngTemplateOutlet]=\"tab.contentTpl.templateRef\"></ng-template>\n </div>\n </ng-template>\n </div>\n " },] }, ];`
> 
> Maciej

I have an use case where I need to dynamically hide and restore the tab. Since *ngIf is a structural directive the tab is removed from DOM when set to 'false'. This means it's state is also deleted and this is a problem when the tab becomes visible again. Could adding the [hidden] option be reconsidered?
