### ISSUE TITLE
ngb-accordion or ngb-panel type has no effect

### ISSUE THREAD

**Issue by FrancoisM** [ng-bootstrap/ng-bootstrap#1897]
I expect the following to show a success style but it doesn't.
I have bootstrap v4 installed.
(Note that when I open the plunkers in the doc I can't get them to work. Adding the ng-bootstrap package fails.)

```
<ngb-accordion class="col-md-12" type="success">
    <ngb-panel>
        <ng-template ngbPanelTitle>
            title
        </ng-template>
        <ng-template ngbPanelContent>               
            blah blah
        </ng-template>
    </ngb-panel>
</ngb-accordion>
```

**Comment by pkozlowski-opensource** [comment]
I've got a perfectly working plunker here: http://plnkr.co/edit/Cnas1aOupptPQhfGZ0dx?p=preview - I've just forked it from our demo page (https://ng-bootstrap.github.io/#/components/accordion/examples)

**Comment by FrancoisM** [comment]
Tks for plunker it works (I may have done something wrong the first time). However the point is on "type" not working.

**Comment by pkozlowski-opensource** [comment]
> However the point is on "type" not working.

Not sure what you mean... Please provide a minimal reproduce scenario in a plunker, as requested in the issue template.

**Comment by FrancoisM** [comment]
I'm new to plunker so I haven't found yet how to modify the plunker you sent and give you the link.
But if you take the plunker you sent and replace the html with the one of my question, you'll notice that the panel is not of type "success" of bootstrap.

**Comment by pkozlowski-opensource** [comment]
Oh, I see. Here is a reproduce scenario: http://plnkr.co/edit/Cnas1aOupptPQhfGZ0dx?p=preview

**Comment by maxokorokov** [comment]
`card-warning`, `card-success`, etc styles are not working anymore. Customization is done via utility classes: https://getbootstrap.com/docs/4.0/components/card/#card-styles

Accordion has `@Input() type;` that is not working anymore (it was already broken with `beta.1`)

From `accordion.ts` template:
```html
<div role="tab" [class]="'card-header ' + (panel.type ? 'card-'+panel.type: type ? 'card-'+type : '')">
  <!-- ... -->
</div>
```

Now you can separately customize text, say with `text-white`, background with `bg-primary` and border with `border-primary`.

**Comment by bbalvanera** [comment]
I'm new to the ng-bootstrap code but isn't it possible to just update the template to use `'bg-'+type :` and it will continue working right?

**Comment by maxokorokov** [comment]
@bbalvanera, yes, that would do I guess, it just has 3 separate things now: background colour, text colour and border colour. Previously there was only one - card type.

**Comment by vsagarreddy** [comment]
Can any one tell me how to use  **isOpen**  flag

**Comment by maxokorokov** [comment]
Ok, this was changed between `alpha.6` → `beta` transition of the bootstrap

Previously the possible styles were → `success | info | warning | danger` and the only thing it changed was the background colour of the tab header:

Ex. for `type=danger`

![screen shot 2018-03-16 at 17 19 10](https://user-images.githubusercontent.com/8074436/37532064-3c56fa80-293e-11e8-99c5-1be5e00be0fa.png)

---

I'll open a PR that will use current background colour values as type → `primary | secondary | success | danger | warning | info | light | dark ` and make cards look like current version of bootstrap suggests:

Ex. for `type=danger`

![screen shot 2018-03-16 at 17 24 18](https://user-images.githubusercontent.com/8074436/37532497-7a2a7a5c-293f-11e8-97ee-b759651e5ed9.png)

I think styling of header/body separately and border colour should be discussed as separate features outside of this issue.
