### ISSUE TITLE
can not assign null to **toDate**

### ISSUE THREAD

**Issue by ibagaric** [ng-bootstrap/ng-bootstrap#1903]
In datepicker I can not assign null to **toDate** bacause toDate has type **NgbDateStruct**

`export interface NgbDateStruct {
    year: number;
    month: number;
    day: number;
}`

example in date picker range:

`    onDateChange(date: NgbDateStruct) {
        if (!this.fromDate && !this.toDate) {
            this.fromDate = date;
        } else if (this.fromDate && !this.toDate && after(date, this.fromDate)) {
            this.toDate = date;
        } else {
            this.toDate = null;
            this.fromDate = date;
        }
    }`

**Comment by maxokorokov** [comment]
It looks like it has nothing to do with datepicker itself, but with the way you're trying to use it. Also you can perfectly fine do the following: `let date: NgbDateStruct = null;`, so I don't see any problem.

- this is a support request and as such doesn't belong here: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
- we can't help much without a reproduce scenario in a plunker.

Please try to reproduce your problem in a plunker and ask further questions on StackOverflow. Thnx!

**Comment by ibagaric** [comment]
If you update typescript to the latest version, 2.5.3., it will not let you assign like this.

This is datepicker range plunker with only updated typescript to 2.5.3:
http://plnkr.co/edit/qnlnomMxv1UnIYUYRHsL?p=preview 

I solve a problem by assign toDate type <any>null

**Comment by maxokorokov** [comment]
Then looks like a duplicate of #1544 if I'm not mistaken
