### ISSUE TITLE
Modify the source code can't worked when build,I want to know why?

### ISSUE THREAD

**Issue by Lsy-kg** [ng-bootstrap/ng-bootstrap#1907]
For some reason, I modify ng-bootstrap/pagination/pagination.js code(button text) in node_modules folder. It works well when ng serve -o , but when I use ng build --prod --env=prod , my modify can't become effective, why? It bothers me for a long time，please help me, thanks!

**Comment by pkozlowski-opensource** [comment]
https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
