### ISSUE TITLE
CSS rules applied in different order in dev and production

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#1912]
I see a problem with the order CSS rules are applied depending on the browser and environment on the demo site. We have `component styles` and `bootstrap.css` for widgets.

**In development mode:**

- component syles
- bootstrap.css

<img width="368" alt="screen shot 2017-10-23 at 14 18 03" src="https://user-images.githubusercontent.com/8074436/31888858-ec41dbe8-b7fd-11e7-8df2-ba5094ee7fee.png">

Rules:

<img width="344" alt="screen shot 2017-10-23 at 14 22 19" src="https://user-images.githubusercontent.com/8074436/31888884-0c03c18a-b7fe-11e7-9692-d5926a1d2c56.png">

**In production its inversed:**

- bootstrap.css
- component styles

<img width="460" alt="screen shot 2017-10-23 at 14 17 23" src="https://user-images.githubusercontent.com/8074436/31888855-ea8ac1d4-b7fd-11e7-9ca1-c367307555b4.png">

Rules:

<img width="348" alt="screen shot 2017-10-23 at 14 21 56" src="https://user-images.githubusercontent.com/8074436/31888883-0a5b39bc-b7fe-11e7-86fd-bc2b31004742.png">

On top of this it happens in Chrome and Firefox. In Safari the order is always the correct one.

**Comment by pkozlowski-opensource** [comment]
@maxokorokov what are the practical implications of different order? I mean, why do we care?

**Comment by pkozlowski-opensource** [comment]
Should be fixed with  20ba716
