### ISSUE TITLE
NgbAccordion - destroyOnHide - doesn't seem to work correctly

### ISSUE THREAD

**Issue by sourcedump** [ng-bootstrap/ng-bootstrap#1915]
Hello everyone,
if I set the 'destroyOnHide' option to the boolean 'false', the accordion don't close the panels anymore.
If you use one of your link in Plunker (eg: [this](https://ng-bootstrap.github.io/app/components/accordion/demos/toggle/plnkr.html)) and put `[destroyOnHide]="false"` on the first line of the 'src/accordion-toggle.html' file you can see the effect.

Here the versions of the libraries that I'm using:

- Angular: 4.4.5
- ng-bootstrap: v1.0.0-beta.5
- Bootstrap: v4.0.0-beta

Thank you!

**Comment by maxokorokov** [comment]
Looks like it doesn't work to me too. Here is the link the plunkr that simply adds `[displayOnHide]="false"`
http://plnkr.co/edit/IFv7b0VIn2zcqoJKclZX?p=preview

**Comment by skrzepij** [comment]
Same issue here. 
Any ideas how to workaround this bug?

**Comment by atarix83** [comment]
I have the same issue too.
There is a fix?

**Comment by DenverDrew** [comment]
I am also having this same issue.
Any ETA on a fix?

**Comment by maxokorokov** [comment]
You could take a look at #1940

**Comment by sourcedump** [comment]
I've tried the solution in #1940 and it works for me
