### ISSUE TITLE
Unhandled Promise rejection: Template parse errors: 'ngb-timepicker' is not a known element:

### ISSUE THREAD

**Issue by hslamba95** [ng-bootstrap/ng-bootstrap#1916]
As just mentioned in your documentation to define the ng-bootstrap, i just installed in angular-seed project with Angular4 , Bootstrap4. I had included NgbModule.forRoot() in app.module and NgbModule in my another module where i am using the ng-bootstrap component. But still while using the time picker component it gives me this error : 

Unhandled Promise rejection: Template parse errors:
'ngb-timepicker' is not a known element:
1. If 'ngb-timepicker' is an Angular component, then verify that it is part of this module.
2. If 'ngb-timepicker' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("3" style="padding-left: 0px;">
                <label class="font-h5">From:</label>
                [ERROR ->]<ngb-timepicker [(ngModel)]="time"></ngb-timepicker>
                <hr>
                <pre>Select"): ng:///app/dashboard/home/task-view.component.html@63:16 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:

**Comment by maxokorokov** [comment]
Please see https://github.com/ng-bootstrap/ng-bootstrap/issues/914
And https://github.com/ng-bootstrap/ng-bootstrap#getting-help
