### ISSUE TITLE
[Bug] Datepicker does't react well to always changing minDate and maxDate

### ISSUE THREAD

**Issue by SimonLuckenuik** [ng-bootstrap/ng-bootstrap#1918]
### Bug description:
The attached plunker contains 3 different calendars. Each calendar has minDate and maxDate attached to a different property of the model (maxDate1 for Calendar1, ....)

Calendar 1 and Calendar 2 are working as expected.
Calendar 3 is not working correctly, the only difference is that the implementation of the typescript getter which is returning the value directly from the implementation of the setter (different value at each get), rather than a fixed value. Somehow it seems to reset the state of the calendar, so we get stuck on the same month even if trying to change it by selecting a year or using the chevron.

### Expected behavior
I would expect the datepicker to compare the received min/max value (even if different date instance) and work as expected if value is the same.

### Link to minimally-working plunker that reproduces the issue:
https://embed.plnkr.co/TMhKYxBiae9pQ7TLF6Ds/

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 4.4.6
ng-bootstrap: 1.0.0-beta.5
Bootstrap: 4.0.0-beta

**Comment by maxokorokov** [comment]
It was most likely fixed in #2219 shipped with `1.0.2`
Anyway the current version works fine for me: https://stackblitz.com/edit/angular-szkzg3
Sorry for a huge delay.
