### ISSUE TITLE
Bootstrap 3 components in ng-bootstrap

### ISSUE THREAD

**Issue by ankitjs** [ng-bootstrap/ng-bootstrap#1921]
How can i use ng-bootstrap with bootstrap 3 instead of bootstrap 4. I can't use bootstrap 4 in my project due to some reason. Is there a way around?

**Comment by renilbabu03** [comment]
Yes.. I too had such an issue... I was wondering if there was a way around

**Comment by pkozlowski-opensource** [comment]
See https://github.com/ng-bootstrap/ng-bootstrap/wiki/Why-Bootstrap-4-only%3F
