### ISSUE TITLE
NgbDropdownToggle is not optional

### ISSUE THREAD

**Issue by jonathanfroy** [ng-bootstrap/ng-bootstrap#1926]
Angular: 4.4.6
ng-bootstrap: 1.0.0-beta.5
Bootstrap: 4.0.0-beta.2

Documentation states that NgbDropdownToggle directive is optional, yet instantiating an NgbDropdown without an NgbDropdownToggle within it leads to poorly positioned drop-down.

Quick glance at the source code suggests positioning of menu element is skipped when NgbDropdown._toggle is undefined. See [dropdown.ts](https://github.com/ng-bootstrap/ng-bootstrap/blob/1.0.0-beta.5/src/dropdown/dropdown.ts), line 195.

**Comment by mschoudry** [comment]
I think documentation should be updated, NgbDropdownToggle directive should not be optional. for now there is no other way to set the location of the menu to be displayed, a part from NgbDropdownToggle anchor.

**Comment by jonathanfroy** [comment]
It would be convenient to have a base directive, say, NgbDropdownAnchor, to designate an element as the positioning anchor for the drop-down, but without the functionality for toggling on click. For instance, one could want to toggle on focus in/out. So NgbDropdownToggle would be optional, as one among a number of possible anchoring directives, but any one anchoring directive would be required in every drop-down.

**Comment by pkozlowski-opensource** [comment]
@jonathanfroy I like your proposal. Would like to get a stab at a PR implementing it?

**Comment by jonathanfroy** [comment]
I'd love to, but I must admit that right now, I can't figure out how to make this extensible. How could the ContentChild query inside NgbDropdown target a base directive, e.g. NgbDropdownAnchor, or any derivative thereof? And it is clear that NgbDropdownToggle would have to become one such derivative, so it keeps working as is in existing apps. Any pointers on directive inheritance?

**Comment by pkozlowski-opensource** [comment]
@jonathanfroy I've opened #2082 to implement the idea you've proposed. Would be great to have your feedback!
