### ISSUE TITLE
Popover body is not displaying after extending NgbPopover

### ISSUE THREAD

**Issue by alec-implicitdesign** [ng-bootstrap/ng-bootstrap#1929]
I've somewhat successfully extended ngbPopover to allow some code to be executed after popovers open and close, however the body in the corresponding ng-template is not displaying.  Is this a bug or am I missing something? 

```
@Directive({  
    selector:'[customPopover]',
    exportAs:'customPopover'
}) 
export class CustomPopover extends NgbPopover {

    @Input()
    customPopover: string;

    open() {
        super.open();
        // custom code
    }

    close() {
        super.close();
        // custom code
    }
}

```

I am trying to use it somewhat like the following, but when the popover is opened, the ng-template is not showing in the body:

```
<ng-template #vTemplate>
    This template is not showing!!!
</ng-template>

<input #qtyInput
    popoverTitle="Warning!"
    [customPopover]="vTemplate"
    #validationPopover="customPopover"
    placement="bottom"
    triggers="manual">
```

**Comment by pkozlowski-opensource** [comment]
https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
