### ISSUE TITLE
Collapse Breaks Row Layout

### ISSUE THREAD

**Issue by thatcort** [ng-bootstrap/ng-bootstrap#1932]
Using ngbCollapse on a row element causes the row to use CSS display block instead of flex. This causes columns in the row to layout incorrectly

E.g. In the following example the right column will appear below the left one, instead of beside it.

<div class="row" [nbgCollapse]="isCollapsed">
  <div class="col">Left column</div>
  <div class="col">Right column</div>
</div>

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/CdVxQBWe6rTFdG4yswOt

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.4.6

ng-bootstrap: 1.0.0-beta.5

Bootstrap:

**Comment by pkozlowski-opensource** [comment]
This would be a problem with Bootstrap's CSS as just adding CSS classes needed by collapse makes the problem appear: http://plnkr.co/edit/YWpplJoLgcXfaIyUM7pt?p=preview

You can report this in the Bootstrap repository or work-around it by moving collapse above a row: http://plnkr.co/edit/UXRSj20Ma6wwraMMTOLq?p=preview

Closing as we can't do much about it in this project...
