### ISSUE TITLE
Something wrong with closeable alerts (TypeError)

### ISSUE THREAD

**Issue by thibaultvanluchene** [ng-bootstrap/ng-bootstrap#1937]
Getting this Error when trying to close alert: 
```ERROR TypeError: _co.closeAlert is not a function at Object.eval [as handleEvent]```

Tried it in a fresh project, so I think it's a genuine issue here.

Versions:
"ng-bootstrap/ng-bootstrap": "^1.0.0-beta.5",
"angular/cli": "1.5.0",
"typescript": "~2.4.2"

AppModule: 
```import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import {NgbModule} from '@ng-bootstrap/ng-bootstrap';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    NgbModule.forRoot(),
    BrowserModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by pkozlowski-opensource** [comment]
We need a minimal reproduce scenario in a plunker as requested in the issue template: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

It is not actionable without a reproduce scenario.
