### ISSUE TITLE
Using @angular/cdk for ng-bootstrap

### ISSUE THREAD

**Issue by mohammedzamakhan** [ng-bootstrap/ng-bootstrap#1942]
Should this project use @angular/cdk for accessibility, overlay, bidirectionality etc.

**Comment by pkozlowski-opensource** [comment]
We've got no plans to depend on `@angular/cdk` for now as it would have far-reaching consequences that would limit our options (fixing bugs, independent release cycle etc.).

We might re-consider in the future.

**Comment by piernik** [comment]
I think it's time to reconsider. CDK and it's overlay module has great positioning, good focus trap, and also keybindings.
