### ISSUE TITLE
Alternate method for selecting tab

### ISSUE THREAD

**Issue by jscharett** [ng-bootstrap/ng-bootstrap#1949]
Looking at the current API for manually selecting a tab in a tab set, it requires you to specify an id for each tab.  As noted, the id must be unique to the document.  It is for this reason that the use of id's is problematic as they don't scale well with larger apps.  It would be preferable to provide other options such as:

- select tab my title, where title is the tabs' displayed text
- select tab by name, where name is a attribute of ngtab
- select tab by index, where index is the index of the tab

**Comment by bastienmoulia** [comment]
The title and name can't be used as id for a tab because they can be used for accessibility purpose.

The id set for the tab is quite unique because it start with `ngb-tab-` and has an incremented number at the end.

**Comment by pkozlowski-opensource** [comment]
@jscharett as @bastienmoulia pointed out `id`s are generated automatically if you don't specify one. The generated ones are guaranteed to be  unique.

Now, if you need a specific id for the selection purpose, you can just assign this one id. So in this sense it is not like you need to make all the `id`s in the entire world - just the ones you need for selection purposes.
