### ISSUE TITLE
Modals incorrectly dismissed by mouse release

### ISSUE THREAD

**Issue by sdarnell** [ng-bootstrap/ng-bootstrap#1950]
### Bug description:
When you have a modal dialog that includes text which is expected to be copied with the mouse, users (inc. me) often somewhat imprecisely select the text and end up with the mouse outside of the modal dialog. They then release the mouse button used to select the text.

With ng-bootstrap modals this results in the unexpected behaviour of the whole modal gets dismissed.

I think the ideal solution would probably be to not listen for (click) in NgbModalWindow, and instead listen for (mousedown) events.
https://github.com/ng-bootstrap/ng-bootstrap/blob/0c03671c52500f13387deeaf31f815372d364c26/src/modal/modal-window.ts#L23

As a work-around I can disable the background click detection (option 'backdrop'), but it would be nice to still support that.

### Link to minimally-working plunker that reproduces the issue:

You can see the issue with [modal](https://ng-bootstrap.github.io/#/components/modal/examples)

Launch the first modal, then select all of the text ('One fine body…') and end with the mouse just outside the modal before you release the mouse button.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.4.6

ng-bootstrap: 1.0.0-beta.5

Bootstrap: 4.0.0-beta.2

Browsers:
 Microsoft Edge 40.15063.674.0 (Win)
 Microsoft IE 11.674 (Win)
 Chrome Version 61.0.3163.100 (Win)
 Chrome  61.0.3163.100 (Mac)

 Firefox 56.0 Mac does not exhibit the problem
 Safari 11.0.1 Mac does not exhibit the problem

**Comment by bastienmoulia** [comment]
For touchscreen the `touchstart` event should be used instead of `mousedown`.

**Comment by lucasklaassen** [comment]
Any updates on this or fixes? It would be sweet to detect if the mouse click+release occurs outside of the modal, instead of starting within the modal and releasing outside of it.

The main use case I've seen is when a user is selecting text within an input field and then releases their mouse outside of the modal, which closes it.

**Comment by Stajor** [comment]
Any updates?
Same problem with "@ng-bootstrap/ng-bootstrap": "5.0.0-rc.1"

**Comment by pbarranis** [comment]
@Stajor There's a PR for this, but it needs work.  See the link above to @lucasklaassen 's PR #3181

**Comment by wizcas** [comment]
Please DO fix this issue. It's really really annoying.

**Comment by shyamal890** [comment]
This is seriously very annoying. Hope its addressed as soon as possible.

**Comment by sarahm7** [comment]
Any chance the fix can be implemented for the 4.x.x version? We're at Angular 7 and there are no plans to migrate soon to 8 due to external plugin issues. Hope you can help.
