### ISSUE TITLE
popover: Keep open when hovering on it (the popover itself)

### ISSUE THREAD

**Issue by jasonhjohnson** [ng-bootstrap/ng-bootstrap#1953]
Is it possible to keep the popover open while it's being hovered on?

**Comment by mschoudry** [comment]
look at **Custom and manual triggers** section in [docs](https://ng-bootstrap.github.io/#/components/popover/examples) 

Regards,

**Comment by jasonhjohnson** [comment]
Yes I’m using that, however the popover disappears whenever you try to hover over it. It won’t stay open unless I’m hovered over the element that triggers the popover.

**Comment by pkozlowski-opensource** [comment]
@jasonhjohnson you can have different triggers for open / close. I guess you wont to have sth like `mousenter` for open and say, `click` for close.

Anyway, this is a support request that  doesn't belong here:  https://github.com/ng-bootstrap/ng-bootstrap#getting-help
