### ISSUE TITLE
Feature Request: Combobox

### ISSUE THREAD

**Issue by Juchar** [ng-bootstrap/ng-bootstrap#1954]
### Feature description:
It would be great to have some combobox component.

The combobox would be useful as alternative for dropdowns with a lot of values.
The user would be able to use autocomplete functionalities while typing.

Currently there is a typeahead, which is great, but not applicable in cases you need to show the possible values to a user without him knowing what those look like.

### Samples:

https://github.com/danielfarrell/bootstrap-combobox
http://bootstrap-combobox-test.herokuapp.com/

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
4.2.4

ng-bootstrap:
1.0.0-beta.5

Bootstrap:
4.0

**Comment by pkozlowski-opensource** [comment]
We are not planning on adding anything beyond #532

**Comment by Juchar** [comment]
I do not completely understand how the tag box could replace a combobox? Could you elaborate a little bit further?

**Comment by pkozlowski-opensource** [comment]
> I do not completely understand how the tag box could replace a combobox? Could you elaborate a little bit further?

I'm not saying it can replace it, I'm saying that we are not planning on doing anything else. So it might happen that, sadly, we are not going to cover your use-case...
