### ISSUE TITLE
bootstrap 4 beta 2 css

### ISSUE THREAD

**Issue by SEphir0nX** [ng-bootstrap/ng-bootstrap#1955]
I'm using netbean IDE 8.2 with wamp server

Both bootstrap.css and bootstrap.min.css have the same issues

**issue 1:** unexpected token error found
:root {
  --blue: #007bff;
  --indigo: #6610f2;

**issue 2 (line 5492):** unexpected token LPAREN/ WS/ RPAREN found
@supports ((-webkit-transform-style**:** preserve-3d) or (transform-style: preserve-3d)) {
  .carousel-item-next.carousel-item-left,
  .carousel-item-prev.carousel-item-right {
    -webkit-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0);
     }
**};**
I'm not using scss to install boostrap, I just need to copy-paste js/css files inside my project

**Comment by pkozlowski-opensource** [comment]
This has nothing to do with this project as we are not modifying / transforming Bootstrap's CSS in any way. If you believe that the Bootstrap produces flawed bundles than please report it in https://github.com/twbs/bootstrap
