### ISSUE TITLE
Progressbar value change animation - not working with a fresh Angular CLI project

### ISSUE THREAD

**Issue by ZackDeRose** [ng-bootstrap/ng-bootstrap#1956]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

> 
> Cloned plunker properly animates a change in value: http://plnkr.co/edit/uATH13299EY7X8VEo8SU
> 
> New Angular CLI (1.0.1) project does not properly animate a change in value: https://github.com/ZackDeRose/ng-bootstrap-progress-bar-test
> 
> ![progress-bar-animation-issue](https://user-images.githubusercontent.com/3788405/32696991-cb2415ec-c753-11e7-9899-0a7afa09982a.gif)

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

> Issue is that I'm unable to match behavior to the cloned plunker provided in description, despite matching the plunker's config.js packages.
>
> plunker's config.js:
> ```
> var ver = {
>     ng: '4.0.3'
>   };
>   
>   System.config({
>   //use typescript for compilation
>   transpiler: 'typescript',
>   //typescript compiler options
>   typescriptOptions: {
>     emitDecoratorMetadata: true
>   },
>   paths: {
>     'npm:': 'https://unpkg.com/'
>   },
>   map: {
> 
>     'app': './src',
> 
>     '@angular/core': 'npm:@angular/core@' + ver.ng + '/bundles/core.umd.js',
>     '@angular/common': 'npm:@angular/common@' + ver.ng + '/bundles/common.umd.js',
>     '@angular/compiler': 'npm:@angular/compiler@' + ver.ng + '/bundles/compiler.umd.js',
>     '@angular/platform-browser': 'npm:@angular/platform-browser@' + ver.ng + '/bundles/platform-browser.umd.js',
>     '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic@' + ver.ng + '/bundles/platform-browser-dynamic.umd.js',
>     '@angular/http': 'npm:@angular/http@' + ver.ng + '/bundles/http.umd.js',
>     '@angular/router': 'npm:@angular/router@' + ver.ng + '/bundles/router.umd.js',
>     '@angular/forms': 'npm:@angular/forms@' + ver.ng + '/bundles/forms.umd.js',
> 
>     'rxjs': 'npm:rxjs@^5.0.1',
>     'typescript': 'npm:typescript@2.1.5/lib/typescript.js',
> 
>     '@ng-bootstrap/ng-bootstrap': 'npm:@ng-bootstrap/ng-bootstrap@1.0.0-beta.5/bundles/ng-bootstrap.js'
>   },
>   packages: {
>     app: {
>       main: './main.ts',
>       defaultExtension: 'ts'
>     },
>     rxjs: {
>       defaultExtension: 'js'
>     }
>   }
> });
> ```
> Angular CLI's package.json:
> ```
> {
>   "name": "ng-bootstrap-progress-bar-test",
>   "version": "0.0.0",
>   "license": "MIT",
>   "scripts": {
>     "ng": "ng",
>     "start": "ng serve",
>     "build": "ng build",
>     "test": "ng test",
>     "lint": "ng lint",
>     "e2e": "ng e2e"
>   },
>   "private": true,
>   "dependencies": {
>     "@angular/common": "^4.0.3",
>     "@angular/compiler": "^4.0.3",
>     "@angular/core": "^4.0.3",
>     "@angular/forms": "^4.0.3",
>     "@angular/http": "^4.0.3",
>     "@angular/platform-browser": "^4.0.3",
>     "@angular/platform-browser-dynamic": "^4.0.3",
>     "@angular/router": "^4.0.3",
>     "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.5",
>     "core-js": "^2.4.1",
>     "rxjs": "^5.0.1",
>     "zone.js": "^0.8.4"
>   },
>   "devDependencies": {
>     "@angular/cli": "1.0.1",
>     "@angular/compiler-cli": "^4.0.0",
>     "@types/jasmine": "2.5.38",
>     "@types/node": "~6.0.60",
>     "codelyzer": "~2.0.0",
>     "jasmine-core": "~2.5.2",
>     "jasmine-spec-reporter": "~3.2.0",
>     "karma": "~1.4.1",
>     "karma-chrome-launcher": "~2.0.0",
>     "karma-cli": "~1.0.1",
>     "karma-jasmine": "~1.1.0",
>     "karma-jasmine-html-reporter": "^0.2.2",
>     "karma-coverage-istanbul-reporter": "^0.2.0",
>     "protractor": "~5.1.0",
>     "ts-node": "~2.0.0",
>     "tslint": "~4.5.0",
>     "typescript": "~2.2.0"
>   }
> }
> ```

### Version of Angular, ng-bootstrap, and Bootstrap:

> Angular: 4.0.3
> 
> ng-bootstrap: 1.0.0-beta.5
> 
> Bootstrap: 4.0.0-beta.2

**Comment by pkozlowski-opensource** [comment]
It has nothing to do with CLI - the difference is in the Bootstrap version used - you are using 4.0.0-beta.2 while we are on an earlier beta. Here is a reproduce scenario in a plunker: http://plnkr.co/edit/X8EVLlfzmR7ZHgEp8tXZ?p=preview

**Comment by maxokorokov** [comment]
It has also nothing to do with ng-bootstrap, it was a regression in Bootstrap beta.2, will be fixed in the next version of Bootstrap: see https://github.com/twbs/bootstrap/pull/24694

**Comment by pkozlowski-opensource** [comment]
Oh, awesome, thnx for tracking it down @maxokorokov - I'm going to close it then as we can't do anything about it here.
