### ISSUE TITLE
Styling issues with split button/dropdown

### ISSUE THREAD

**Issue by ajsnyde** [ng-bootstrap/ng-bootstrap#1957]
### Bug description:
When creating mixed dropdowns and buttons as seen in this [example](https://ng-bootstrap.github.io/#/components/dropdown/examples), there are styling issues when having the dropdown before the buttons. It seems that the rounded edges for the dropdown only appear on the right. I'm not sure if this functionality is intentionally limited in this way.
### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/Sw7Br05uiduHJcmjUUjb?p=preview
### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 4.0+

ng-bootstrap:1.0.0-beta.5

Bootstrap:4.0.0-beta.2

**Comment by pkozlowski-opensource** [comment]
Hmm, seems like a nested `.btn-group` is needed in this case according to: 
http://getbootstrap.com/docs/4.0/components/button-group/#nesting

See it working here: http://plnkr.co/edit/yBgdSIKCtdhzTOqXkSwk?p=preview

Would you be up to sending us a PR to fix our demo? Thous would be very helpful!

**Comment by ajsnyde** [comment]
I may or may not get back to this soon. I'm on a bit of a hiatus.
