### ISSUE TITLE
Modal throws error when not supplying a second argument to modalRef.result.then()

### ISSUE THREAD

**Issue by pablo-martinez** [ng-bootstrap/ng-bootstrap#1959]
### Bug description:

The reproduction of this error is very simple, it occurs when not supplying the onrejected parameter of the modal.result.then() method, which is optional. It also throws when `null` is provided as the argument, but it doesn't throw if we supply an empty callback:

```
modalRef.result.then((result) => {
  console.log(`Closed with: ${result}`);
}, () => { });
```

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/SeFd6r7aEJEZnfVoRl9f?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: ^5.0.0

ng-bootstrap: ^1.0.0-beta.5

Bootstrap: ^4.0.0-beta.2

**Comment by pkozlowski-opensource** [comment]
I'm afraid that there is nothing we can do in this library to prevent this error logged by a _browser_. The error comes from the JS engine, try this in your favourite browser's console: `Promise.reject('bah!').then(() => {})`

I'm going to close this for now as I don't see how we could "fix" it. if anyone has an idea for a technical solution I would love to hear & implement!
