### ISSUE TITLE
_userinput is undefined if the type ahead is triggered by a button

### ISSUE THREAD

**Issue by sherifamgadnabih** [ng-bootstrap/ng-bootstrap#1960]
if you try to trigger the type ahead with a button and press anywhere outside the textbox , the textbox value will be undefined because the _userinput variable is only initialized on the change event of the textbox

**Comment by pkozlowski-opensource** [comment]
I'm sorry but bug reports without a reproduce scenario are not actionable. Please open a new issue following our issue template: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug
