### ISSUE TITLE
feat(dropdown): Adjust position when at the edge of window

### ISSUE THREAD

**Issue by m-spyratos** [ng-bootstrap/ng-bootstrap#1961]
### Feature description:

On Bootstrap's page for [dropdowns](https://getbootstrap.com/docs/4.0/components/dropdowns/), when there is not enough space at the bottom of the page for the dropdown to appear, then the dropdown opens upwards. This feature is missing from Ng Bootstrap.

### Link to minimally-working plunker that reproduces the issue:

- Ng-Bootstrap dropdown: [http://plnkr.co/edit/t0IpBFEmHehrD254YaCD?p=preview](http://plnkr.co/edit/t0IpBFEmHehrD254YaCD?p=preview)
- Bootstrap dropdown: [https://plnkr.co/edit/FsELdhmB6kxgIJRiceBv?p=preview](https://plnkr.co/edit/FsELdhmB6kxgIJRiceBv?p=preview)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4+

ng-bootstrap: 1.0.0-beta.5

Bootstrap: 4.0.0-beta.2

**Comment by pkozlowski-opensource** [comment]
> On Bootstrap's page for dropdowns, when there is not enough space at the bottom of the page for the dropdown to appear, then the dropdown opens upwards. This feature is missing from Ng Bootstrap.

You can specify `placement` constraints in ng-bootstrap to achieve the same effect.
Ex.: `<div ngbDropdown [placement]="['bottom-left', 'top-left']">`
Demo: http://plnkr.co/edit/FqcejGab8NnrqYhfqR1o?p=preview

Closing as a support request.

**Comment by blogcraft** [comment]
Im sorry, I  don't get it, in the demo link you set it to 'top-left' but it renders top-right, am I missing something?

**Comment by alan-bio** [comment]
This shouldn't be closed. It's a feature request and should also handle any case of the dropdown rendering outside of the browser window.
