### ISSUE TITLE
Enable Fixed Heights on ngb-tabset

### ISSUE THREAD

**Issue by andlewis** [ng-bootstrap/ng-bootstrap#1962]
Currently ngb-tabset sizes to the height of the current tab. CSS fixes for the (non ng) Bootstrap Tabset don't seem to work.

**Comment by pkozlowski-opensource** [comment]
> CSS fixes for the (non ng) Bootstrap Tabset don't seem to work.

Could you please elaborate on this? What fixes did you try? What doesn't work, exactly?

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't heard back from @andlewis and we there is not enough info here to make this issue actionable. Please open a new issue following GH template if you still believe that we should make changes in this library.
