### ISSUE TITLE
Dismiss all option in modal service

### ISSUE THREAD

**Issue by jcimoch** [ng-bootstrap/ng-bootstrap#1963]
### Feature request:
I think there should be an option to dismiss all instances. 
For example let's imagine that we have http interceptor which redirects on 401 http error code to login page. From interceptor prespective we don't have infromation about current modal reference. After redirection modal stays opened. It would be nice to be able to close all instances without explicit reference to modal template. 

If I'm missing something, and that feature already exists please point me to docs, cause I coulnd't find it.

**Comment by kukac7** [comment]
`$uibModalStack.dismissAll();`

**Comment by kukac7** [comment]
https://stackoverflow.com/questions/40382319/how-to-programatically-close-ng-bootstrap-modal

**Comment by jcimoch** [comment]
This doesn't solve the problem. I still need NgbModalRef  to be able to close it.

**Comment by pmcochrane** [comment]
This would be a nice feature to have. My reason for needing this is that if the user is automatically logged/timed out then modals are left open on screen although the page has rerouted to the login screen.

If the modalService could cache all the NgbModalRef's on a call to open (& also clear them when the modal is closed/dismissed) then can we get a function on the modalService to closeAllActiveModals?

My current workaround is having to wrap every call in my app that opens a modal to also store the NgbModalRef in another app wide service array. Then I have a function to attempt to close all modals in the array when the user is logged out.

**Comment by jaredmartinez** [comment]
+1

**Comment by jcimoch** [comment]
Is this feature planned for some release?

**Comment by tiboprea** [comment]
+1
