### ISSUE TITLE
NgbTypeAhead not set value

### ISSUE THREAD

**Issue by m4rkss** [ng-bootstrap/ng-bootstrap#1964]
I´m can´t to set initail value in ngbtypeahead control, this control is in a component child

parent.html
`<autocomplete [parent]="formParent" [tpControl]="tpControl" ></autocomplete>`
parent.ts:
```
ngOnInit(): void {
        this.formParent= this.fb.group({
            tpControl: ['', [Validators.required, Validators.minLength(6)]],
        });
    }
```

I try this options:
`this.formParent.patchValue({ tpControl: 'sadasdas' });`
`this.formParent.controls['tpControl'].setValue("Value initial");`

It seems the value is setted in control but doesn´t appear in html input
Any idea?

Thanks in advance

**Comment by pkozlowski-opensource** [comment]
https://github.com/ng-bootstrap/ng-bootstrap#getting-help
