### ISSUE TITLE
Feature: accordion functions to collapse or expand and also collapse or expand all

### ISSUE THREAD

**Issue by Thorski** [ng-bootstrap/ng-bootstrap#1970]
Feature Request for ngbAccordion:

Add functions to collapse/hide or expand/show a pane
Add function to collapse/hide all panes
Add function returning if a pane is collapsed/hidden or expanded/shown.

I have a situation where it has been hard for me to keep track of which accordions are expanded/shown and which are closed/hidden.   All I have available is the toggle() function.   It would be very nice to have the above functions.

Thank you.

**Comment by pkozlowski-opensource** [comment]
Makes sense. Would you like to send a PR for this?

**Comment by Thorski** [comment]
Ok, I will try.

**Comment by Thorski** [comment]
Is it possible to get my PR into a build or what do I need to do?

Thanks.

**Comment by alignsoft** [comment]
This would be incredibly useful.
