### ISSUE TITLE
Release latest version?

### ISSUE THREAD

**Issue by SmartPickles** [ng-bootstrap/ng-bootstrap#1981]
Hello,

I'm having issues with the current version released on NPM (that is 1.0.0-beta.5), e.g destroyOnHide not working. Those issues are fixed on the github repo, but I can't find a way to install ng-boostrap from the repo. The only solution I found was to install from the npm repo and then modify the files in my node_modules folder - which is not a good solution at all.

Is there any solution for me other than waiting for a new release?

Thanks

**Comment by pkozlowski-opensource** [comment]
> Is there any solution for me other than waiting for a new release?

Sure, you could build version of this library from this repo and use in your project. We are planning a next release for this Friday.
