### ISSUE TITLE
placement not working for split button . 

### ISSUE THREAD

**Issue by nishantk9870** [ng-bootstrap/ng-bootstrap#1986]
### Bug description: Placement not working for the split button. 

placement ="left-bottom" takes only left as placement

Plunker : http://plnkr.co/edit/IgcOcb2YDVjKhtYfg6sW?p=preview 
Angular:4.0.3

ng-bootstrap: beta.5

Bootstrap: beta.2

**Comment by pkozlowski-opensource** [comment]
I guess you've meant to use `bottom-left`: http://plnkr.co/edit/VR4oRthwn15xszxKqo2r?p=preview
