### ISSUE TITLE
No option to trigger tooltip on input focus

### ISSUE THREAD

**Issue by arun-maddheshia** [ng-bootstrap/ng-bootstrap#1997]
Why not there an option of trigger like in jQuery method. 

`tooltip-trigger="focus"`

**Comment by pkozlowski-opensource** [comment]
Huh? We've been supporting this like, forever... http://plnkr.co/edit/q4Aqro4JvvzkQTwCzKge?p=preview

**Comment by arun-maddheshia** [comment]
oopss! my mistake.

Is any way to show tooltip with id like we do in jQuery. $('#id').tooltip('show'); I don't want to use ViewChild as I have numbers of dynamic element.

**Comment by sdarnell** [comment]
FYI I don't think it is clear from the docs. I'd suggest adding a bit more info. For example it took a bit of trial and error for me to get a tooltip to appear on either focus (for keyboard users) or hover (mouse users). I needed triggers to be `triggers="hover focus:blur"`
