### ISSUE TITLE
Issue with NgbDateAdapter when used with a Datepicker on an input

### ISSUE THREAD

**Issue by msosa** [ng-bootstrap/ng-bootstrap#2002]
### Bug description:

Using NgbDateAdapter with anything other than the original NgbDateStruct will not work with a datepicker on an input. It looks like this was missed in my previous PR and when selecting a date from the popup it will show as blank on the input even though the model gets updated. I have something sort of working but having issues with dealing with any type of invalid input and it just causes it to crash. If i take out the second ternary here in datepicker-input on the function manualDateChange, it does end up fixing the crashing error after all my other changes. Not sure if that is the right solution though.

```typescript
 this._onChange(this._model ? this._model.toStruct() : (value === '' ? null : value));
```

 If it helps I can open up a PR with the potential fix

### Link to minimally-working plunker that reproduces the issue:

As this is not yet released I cannot make a plunker

### Version of Angular, ng-bootstrap, and Bootstrap:
ng-bootstrap: master branch

**Comment by maxokorokov** [comment]
Indeed, we kinda forgot about the `ngbInputDatepicker`...
