### ISSUE TITLE
Datepicker open on keydown.enter inside Form

### ISSUE THREAD

**Issue by conalryan** [ng-bootstrap/ng-bootstrap#2005]
### Bug description:
If you place the Datepicker inside form tags, pressing enter on any input field will open the Datepicker.

### Link to minimally-working plunker that reproduces the issue:
https://plnkr.co/edit/JAg2ox2S3qvXgapD9q9I?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular:
5.0.4

ng-bootstrap:
1.0.0-beta.5

Bootstrap:
4.0.0-beta.2

### Workaround:
Put (keydown.enter)="$event.preventDefault()" on the input.  But I really don't want to put this on every single input.

**Comment by pkozlowski-opensource** [comment]
You need to add proper type to your button `<button class="input-group-addon" (click)="fd.toggle();" type="button">` - it is submit by default: https://plnkr.co/edit/Da7RkxSz94XRnerhyUtR?p=preview

Our demo site has already correct examples: https://ng-bootstrap.github.io/#/components/datepicker/examples
