### ISSUE TITLE
Prevent body from scrolling when a modal is open

### ISSUE THREAD

**Issue by sergeu90** [ng-bootstrap/ng-bootstrap#2009]
Hello everyone.You forgot a part of bootstrap code for fix scroll bar issue 
https://github.com/twbs/bootstrap/blob/v4-dev/js/src/modal.js#L136
https://github.com/twbs/bootstrap/blob/v4-dev/js/src/modal.js#L137

**Comment by pkozlowski-opensource** [comment]
I believe that this is a duplicate of #641. If you trying to report a different issue, please provide more details. Closing for now.
