### ISSUE TITLE
ng-bootstrap pagination is not shrinking in the small screens

### ISSUE THREAD

**Issue by MuthiahPrabhakaran** [ng-bootstrap/ng-bootstrap#2011]
Hi Team,

ng-bootstrap pagination is not shrinking in the small screen. 
I'm using Angular 4 and latest version of ng-bootstrap. This issue is not related to my project. 

Take the ng-bootstrap pagination page(https://ng-bootstrap.github.io/#/components/pagination/examples), change the browser display to mobile display (through developer tools) and check.

**Comment by bastienmoulia** [comment]
Hi, 

You can try to change the **maxSize** parameter when the screen is resized.

A quick exemple: http://plnkr.co/edit/w5RL2wFKQCC1BaYXLLIY?p=preview 

But without this workaround I don't know how to do that in a smart way.

**Comment by pkozlowski-opensource** [comment]
Yeh, I'm not sure what you mean by "shrinking" but if you are after showing variable number of pages depending on the screen size, this is not something we support as:
* it would require to listen to viewport size change events and it would penalise (perf) users that don't need this feature;
* we would have to decide on an arbitrary number of pages to display and this wouldn't be flexible.

I'm going to close this issue based on the above but feel free to provide more info if I've misunderstood your request.

**Comment by MuthiahPrabhakaran** [comment]
Hi bastienmoulia, 

Thanks for the solution. I was googling similar kind of solution.
