### ISSUE TITLE
Upgrade dependencies to Angular v5

### ISSUE THREAD

**Issue by trickeyone** [ng-bootstrap/ng-bootstrap#2019]
Are there plans to upgrade to Angular v5? As of the writing of this, Angular's current stable build is v5.1.0.

There are other components that we use and we'd like to upgrade to Angular v5, but @ng-bootstrap is still dependent to Angular v4.

Thanks in advance for any info!

**Comment by bastienmoulia** [comment]
Angular 5 is planned for the next release, and should work with Angular 5.1 too, but I don't know when it will be available.

**Comment by pkozlowski-opensource** [comment]
> Are there plans to upgrade to Angular v5

Upgrade code is in master, we will be cutting a release today.

**Comment by titocr** [comment]
just to note: we have a project on angular 4 with an ng-bootstrap dependency of "^1.0.0-beta.5". This morning, 'npm install' gives us the warning "npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-beta.7 requires a peer of @angular/core@^5.0.2 but none was installed." Changing that semver to "1.0.0-beta.6" gets us going. 

(I know we need to put package.lock into use, but wanted to note this here if anyone else stubbles on this.)

**Comment by trickeyone** [comment]
@titocr If you don't have the package-lock.json, then you should remove the caret (^) from the version in your package.json. That will make sure it only uses the 1.0.0-beta.5 version.
