### ISSUE TITLE
npm install fails due to problem with accordion's metadata

### ISSUE THREAD

**Issue by stas-kh** [ng-bootstrap/ng-bootstrap#2022]
### Bug description:
`npm install` fails due to errors

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular:
\@angular-common: "^4.4.6"

ng-bootstrap:
\@ng-bootstrap/ng-bootstrap: "1.0.0-beta.7"

Bootstrap:
"bootstrap": "^4.0.0-beta"
"bootstrap-sass": "^3.3.7"

![error-in-console](https://user-images.githubusercontent.com/10476834/33763493-5742bb3a-dc19-11e7-8200-85ef2344b618.png)

Has anyone noticed the same?

**Comment by Hopchenko** [comment]
+++

**Comment by pkozlowski-opensource** [comment]
`@ng-bootstrap/ng-bootstrap: "1.0.0-beta.7"` requires Angular `^5.0.2`, see: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#100-beta7-2017-12-08

**Comment by stas-kh** [comment]
Thanks for the clarification.

I just missed the message in changelog.

**Comment by pkozlowski-opensource** [comment]
Closing based on https://github.com/ng-bootstrap/ng-bootstrap/issues/2022#issuecomment-350239547
