### ISSUE TITLE
Metadata version mismatch for module - found version 4, expected 3

### ISSUE THREAD

**Issue by sgoud1390** [ng-bootstrap/ng-bootstrap#2026]
### Version of Angular, ng-bootstrap, and Bootstrap:

angular/cli: 1.2.6
angular/compiler: 4.4.6
@ng-bootstrap/ng-bootstrap: [^1.0.0-beta.5]
ng-bootstrap: 1.6.3 
bootstrap: 3.3.7 

Here's the command that's being run and failing at: 
node_modules/.bin/ngc -p tsconfig-aot.json

Error: Metadata version mismatch for module /opt/myApp/ci-tools/workspace/User-Tier-A-NG_master-tierA/node_modules/@ng-bootstrap/ng-bootstrap/accordion/accordion-config.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (/opt/myApp/ci-tools/workspace/User-Tier-A-NG_master-tierA/node_modules/@angular/compiler/bundles/compiler.umd.js:25616:34)
    at StaticSymbolResolver._createSymbolsOf (/opt/myApp/ci-tools/workspace/User-Tier-A-NG_master-tierA/node_modules/@angular/compiler/bundles/compiler.umd.js:25404:46)
    at StaticSymbolResolver.getSymbolsOf (/opt/myApp/ci-tools/workspace/User-Tier-A-NG_master-tierA/node_modules/@angular/compiler/bundles/compiler.umd.js:25385:14)
    at /opt/myApp/ci-tools/workspace/User-Tier-A-NG_master-tierA/node_modules/@angular/compiler/bundles/compiler.umd.js:24241:30
    at Array.forEach (native)
    at extractProgramSymbols (/opt/myApp/ci-tools/workspace/User-Tier-A-NG_master-tierA/node_modules/@angular/compiler/bundles/compiler.umd.js:24240:79)
    at AotCompiler.analyzeModulesAsync (/opt/myApp/ci-tools/workspace/User-Tier-A-NG_master-tierA/node_modules/@angular/compiler/bundles/compiler.umd.js:23796:47)
    at CodeGenerator.codegen (/opt/myApp/ci-tools/workspace/User-Tier-A-NG_master-tierA/node_modules/@angular/compiler-cli/src/codegen.js:32:14)
    at codegen (/opt/myApp/ci-tools/workspace/User-Tier-A-NG_master-tierA/node_modules/@angular/compiler-cli/src/main.js:13:81)
    at Object.main (/opt/myApp/ci-tools/workspace/User-Tier-A-NG_master-tierA/node_modules/@angular/tsc-wrapped/src/main.js:106:16)
Compilation failed
[Pipeline] echo
ERROR: Caught Exception in stage.
ERROR: Pipeline will not proceed.

**Comment by sgoud1390** [comment]
I enforced my @ng-bootstrap/ng-bootstrap to point to [1.0.0-beta.6] and it worked. (from [^1.0.0-beta.5])

**Comment by pkozlowski-opensource** [comment]
See https://github.com/ng-bootstrap/ng-bootstrap/issues/2022#issuecomment-350239547

**Comment by renjit00** [comment]
ionic-app-script task: "build"
 Error: Metadata version mismatch for module
            /Users/
found version 4, expected 3 . when build through ionic cordova build prod how can i resolve this build issue ,please advise 


{
  "name": "",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/compiler-cli": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@ionic-native/app-availability": "^4.3.1",
    "@ionic-native/call-number": "^4.15.0",
    "@ionic-native/camera": "^4.2.1",
    "@ionic-native/contacts": "^4.15.0",
    "@ionic-native/core": "^3.12.1",
    "@ionic-native/device": "^3.12.1",
    "@ionic-native/document-viewer": "^4.15.0",
    "@ionic-native/email-composer": "^4.2.1",
    "@ionic-native/file": "^4.15.0",
    "@ionic-native/file-transfer": "^4.2.1",
    "@ionic-native/fingerprint-aio": "^4.16.0",
    "@ionic-native/http": "^3.12.1",
    "@ionic-native/in-app-browser": "^4.1.0",
    "@ionic-native/network": "^3.13.1",
    "@ionic-native/pedometer": "^4.5.2",
    "@ionic-native/splash-screen": "3.12.1",
    "@ionic-native/status-bar": "3.12.1",
    "@ionic-native/video-player": "^4.1.0",
    "@ionic/storage": "^2.0.1",
    "call-number": "^1.0.1",
    "com.moust.cordova.videoplayer": "https://github.com/moust/cordova-plugin-videoplayer.git",
    "cordova-android": "~6.3.0",
    "cordova-android-support-gradle-release": "^1.4.3",
    "cordova-ios": "^4.4.0",
    "cordova-plugin-add-swift-support": "^1.7.2",
    "cordova-plugin-appavailability": "^0.4.2",
    "cordova-plugin-camera": "^2.4.1",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-console": "^1.0.5",
    "cordova-plugin-crosswalk-webview": "^2.3.0",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-document-viewer": "^0.9.10",
    "cordova-plugin-email-composer": "~0.8.10",
    "cordova-plugin-file": "^4.3.3",
    "cordova-plugin-file-transfer": "^1.6.3",
    "cordova-plugin-filechooser": "^1.0.1",
    "cordova-plugin-http": "^1.2.0",
    "cordova-plugin-inappbrowser": "^1.7.1",
    "cordova-plugin-network-information": "^1.3.3",
    "cordova-plugin-pedometer": "^0.4.1",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-statusbar": "^2.2.2",
    "cordova-plugin-video-player": "git+https://github.com/moust/cordova-plugin-videoplayer.git",
    "cordova-plugin-whitelist": "^1.3.1",
    "cordova-sqlite-storage": "^2.0.4",
    "ionic-angular": "3.5.0",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionic-select-searchable": "^2.7.2",
    "ionicons": "3.0.0",
    "moment": "^2.18.1",
    "rxjs": "5.4.0",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.12",
    "@ionic/cli-plugin-cordova": "1.4.0",
    "@ionic/cli-plugin-ionic-angular": "1.3.1",
    "typescript": "2.3.4"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-console": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-whitelist": {},
      "ionic-plugin-keyboard": {},
      "cordova-plugin-http": {},
      "cordova-plugin-network-information": {},
      "cordova-sqlite-storage": {},
      "cordova-plugin-inappbrowser": {},
      "com.moust.cordova.videoplayer": {},
      "cordova-plugin-crosswalk-webview": {
        "XWALK_VERSION": "23+",
        "XWALK_LITEVERSION": "xwalk_core_library_canary:17+",
        "XWALK_COMMANDLINE": "--disable-pull-to-refresh-effect",
        "XWALK_MODE": "embedded",
        "XWALK_MULTIPLEAPK": "true"
      },
      "cordova-plugin-camera": {
        "CAMERA_USAGE_DESCRIPTION": " ",
        "PHOTOLIBRARY_USAGE_DESCRIPTION": " "
      },
      "cordova-plugin-pedometer": {},
      "cordova-plugin-file": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-appavailability": {},
      "cordova-plugin-filechooser": {},
      "cordova-plugin-email-composer": {},
      "cordova-android-support-gradle-release": {
        "ANDROID_SUPPORT_VERSION": "27.+"
      },
      "cordova-plugin-document-viewer": {},
      "cordova-plugin-contacts": {},
      "mx.ferreyra.callnumber": {},
      "cordova-plugin-fingerprint-aio": {
        "FACEID_USAGE_DESCRIPTION": "Login now.."
      }
    },
    "platforms": [
      "ios",
      "android"
    ]
  }
}
