### ISSUE TITLE
ng-build fails after last update

### ISSUE THREAD

**Issue by ortichon** [ng-bootstrap/ng-bootstrap#2029]
### Bug description: ng-build fails after last patch update

I've installed version 1.0.0-beta.5 few weeks earlier, and set it to update patches (^1.0.0-beta.5)
Last Thursday night we run successful build, but today it failed with the following error:

```
ERROR in Error: Metadata version mismatch for module C:/********/node_modules/@ng-bootstrap/ng-bootstrap/index.d.ts, found version 4, expected 3, resolving symbol ......
```

revert to version 1.0.0-beta.5 solved this issue.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.2.4

ng-bootstrap: 1.0.0-beta.7

Bootstrap: 4.0.0-beta

**Comment by bastienmoulia** [comment]
ng-bootstrap@1.0.0-beta7 is for angular@5. 
You can try ng-bootstrap@1.0.0-beta6 with angular@4.

**Comment by pkozlowski-opensource** [comment]
Yep, @bastienmoulia is right. Also see https://github.com/ng-bootstrap/ng-bootstrap/issues/2022#issuecomment-350239547
