### ISSUE TITLE
Beta 7  kills karma when used with angular 4 due to wrong semantic versioning 

### ISSUE THREAD

**Issue by PanosParalakis** [ng-bootstrap/ng-bootstrap#2031]
Hi all,
I think you should change the way you are versioning beta releases as release 1.0.0-beta.7 is using angular 5. 

When  for example is defined as: `"@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.5",` 
inside package.json with an angular 4 app, then errors are thrown (eg kills karma/phantomJs).

Solution for me was to use a fixed version to 1.0.0-beta.5. 
Maybe it is a good idea to try to support latest two angular versions at any time.

Thank you!

**Comment by chriscoffee** [comment]
> Hi all,
I think you should change the way you are versioning beta releases as release 1.0.0-beta.7 is using angular 5.
>When for example is defined as: "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.5",
inside package.json with an angular 4 app, then errors are thrown (eg kills karma/phantomJs).
>Solution for me was to use a fixed version to 1.0.0-beta.5.
Maybe it is a good idea to try to support latest two angular versions at any time.
>Thank you!

To expand on @PanosParalakis's point. We recieve the following output when running `ng test --single-run --code-coverage`

```Error: Metadata version mismatch for module ../node_modules/@ng-bootstrap/ng-bootstrap/index.d.ts, found version 4, expected 3, resolving symbol AppModule in ../src/app/app.module.ts, resolving symbol AppModule in ../src/app/app.module.ts, resolving symbol AppModule in ../src/app/app.module.ts```

I have attached the `package.json` file along with the `package-lock.json` for your reference

[package.zip](https://github.com/ng-bootstrap/ng-bootstrap/files/1551449/package.zip)

As Panos highlighted, the slight minor version difference caused our local Angular 4.x.x use to be out with the required 5.x.x version required by `1.0.0-beta.7`

**Comment by pkozlowski-opensource** [comment]
From https://semver.org/:

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

In other words a pre-release beta is not required to strictly follow semver. We will be super-strict with all the rules as soon as we hit 1.0.0 (and this depends on Bootstrap 4 going final). For now I would suggest pinning a version of any pre-release software and / or use lockfiles (good practice anyway, not only for this library).

I understand that we are causing troubles for people who don't have their packages locked and _assume_ that pre-release software follows semver. Sorry for this, but given all the other options we've decided to update Angular version anyway. The good news is that bumping up Angular version in your project should be a fairly painless process and there are many benefits from being on Angular 5.x.

**Comment by PanosParalakis** [comment]
Thanks for your reply! Everything you mentioned is fair and understandable except the fact that we are using lock files and still we 've hit the conflig. Again thanks!
