### ISSUE TITLE
Allow date-picker range selection to pick one day 

### ISSUE THREAD

**Issue by TheGlockZentix** [ng-bootstrap/ng-bootstrap#2032]
Hi!

Shouldn't you be able to select one day only in the date-picker range selection mode?

For example: if I select 12 December and click on that date one more time it should filter on just 12 December.

**Comment by TheGlockZentix** [comment]
Manage to do this be editing the sample code.

**Comment by Santoshah** [comment]
How do I make range date picker open in click event. I am only able to open 2 month calender but the range selector I am not able to apply it. Can you help me with demo please ..

**Comment by mixalistzikas** [comment]
@TheGlockZentix Can we have your edited sample code please? I'm trying to do the same thing. Thank you

**Comment by TheGlockZentix** [comment]
@mixalistzikas 
Hi! Here is a plunker of how I did it using momentjs. The magic is in the method "isAfterOrSame()" in DateRangePickerComponent. 

http://plnkr.co/edit/CXktHE9GEtJWDSAw8Twy?p=preview

**Comment by Santoshah** [comment]
@TheGlockZentix why I am getting this error? can you help me on this. 

http://prntscr.com/i1d51k

**Comment by Santoshah** [comment]
Your code at app.ts is not satisfying. The semicolon should be replaced by comma. It is throwing error. I know know how it is working. I cannot make it work. plz help. @TheGlockZentix 

`    filters:any = {
      from: "2018-01-10";
      to: "2018-01-16";
    }
    `

**Comment by digo9** [comment]
Hi! I just added this else if statement to the existing date selection method and it works fine for me:

`else if (this.fromDate && !this.toDate && equals(date, this.fromDate)) {
      this.toDate = this.fromDate;
}`

http://plnkr.co/edit/m6wr7pfR7mhCaYlpGLEg?p=preview
