### ISSUE TITLE
No option to close modal from a component

### ISSUE THREAD

**Issue by arun-maddheshia** [ng-bootstrap/ng-bootstrap#2036]
I have a component inside a modal, I am trying to close the modal from that component but not working

```
<ng-template #uploadModal let-c="close" let-d="dismiss">
    <app-upload-modal></app-upload-modal>
</ng-template>
```
trying to close by `this.modalReference.close();`

**Comment by pkozlowski-opensource** [comment]
Please follow our template for new issues, otherwise it is not actionable and will be closed: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

Most importantly, we need a _minimal_ plunker with a reproduce scenario.

**Comment by pkozlowski-opensource** [comment]
I'm sorry, but is really not clear what you are asking for, and we haven't heard back. I'm going to close this issue. Please open a new issue following our template if you still facing problems.
