### ISSUE TITLE
Ng-bootstrap contolds are not working with ngModel

### ISSUE THREAD

**Issue by HRSamy** [ng-bootstrap/ng-bootstrap#2037]
I'm new to angular 4 and bootstrap beta 2 and trying to use ngbtooltip to show tool tip text. Tooltip on the label is working fine when only input does not have [(ngModel)]. As soon as I used [(ngModel)] in input text control, tooltip is showing only for the first label and other labels does not. In the below code, if I remove ngModel, all labels tooltips are shown as expected.
`<div class="col-lg-12 col-md-12 col-sm-12 ">
  <div class="col-lg-12 col-md-12 col-sm-12  container accordion" id="accordion">
    <div id="collapseDealSummary" class="col-lg-12 col-md-12 col-sm-12  card-block collapse show row">
      
      <div class="col-lg-12 col-md-12 col-sm-12 card-body row">
        <div class="col-lg-6 col-md-12 col-sm-12">
          <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="row">
              <div class="col-lg-6 col-md-6 col-sm-6 form-group pull-left mx-0 px-1" placement="top" triggers="hover" ngbTooltip="Tooltip on for label 1">
                <label>label 1<span>*</span></label>
                <input type="text" class="form-control" id="txtid" name="txtid" [(ngModel)]="Label1Value" />
              </div>
              <div class="col-lg-6 col-md-6 col-sm-6 form-group pull-left mx-0 px-1" placement="top" triggers="hover" ngbTooltip="Tooltip on for label 2">
                <label>label 2<span>*</span></label>
              </div>
              <div class="col-lg-6 col-md-6 col-sm-6 form-group pull-left mx-0 px-1">
                <label placement="top" triggers="hover" ngbTooltip="Tooltip on for label 3">label 3<span>*</span></label>
              </div>
              <div class="col-lg-6 col-md-6 col-sm-6 form-group pull-left mx-0 px-1">
                <label placement="top" triggers="hover" ngbTooltip="Tooltip on for label [4">label](url) 4<span>*</span></label>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>`
Ref Link:
[](https://stackoverflow.com/questions/47776882/ng-bootstrap-ngbtooltip-not-working-with-ngmodel)

**Comment by pkozlowski-opensource** [comment]
@HRSamy I'm sorry but this is not actionable as is, see:
* https://github.com/ng-bootstrap/ng-bootstrap#getting-help
* https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

Please follow our issue template and provide a minimal reproduce scenario using plunker, otherwise it is not actionable and will be closed.

**Comment by pkozlowski-opensource** [comment]
Closing as we don't have enough info and we haven't heard back from @HRSamy
