### ISSUE TITLE
fullTemplateTypeCheck compatibility

### ISSUE THREAD

**Issue by cexbrayat** [ng-bootstrap/ng-bootstrap#2038]
### Bug description:

Angular 5 introduced a new compiler option called `fullTemplateTypeCheck`. Angular itself has some issues with it, but it's on its way to be resolved, partly by using the brand new `$any()` function from 5.2 (beta.0 as I write this).

`ng-bootstrap` also may have some issues with this new option. When activated on a project that uses `ng-bootstrap`, `ngc` raises:

```
node_modules/@ng-bootstrap/ng-bootstrap/carousel/carousel.d.ts.NgbCarousel.html(4,11): : Property '_getSlideEventDirection' is private and only accessible within class 'NgbCarousel'.
node_modules/@ng-bootstrap/ng-bootstrap/pagination/pagination.d.ts.NgbPagination.html(17,9): : Property 'isEllipsis' does not exist on type 'NgbPagination'. Did you mean 'ellipses'?
node_modules/@ng-bootstrap/ng-bootstrap/pagination/pagination.d.ts.NgbPagination.html(18,12): : Property 'isEllipsis' does not exist on type 'NgbPagination'. Did you mean 'ellipses'?
node_modules/@ng-bootstrap/ng-bootstrap/pagination/pagination.d.ts.NgbPagination.html(19,12): : Property 'isEllipsis' does not exist on type 'NgbPagination'. Did you mean 'ellipses'?
```

The first error concerns the carousel.
`_getSlideEventDirection` is a private method but is used in the template: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/carousel/carousel.ts#L50

Two ways to solve this:
- either make the method not private
- or use `$any(this)._getSlideEventDirection` in the template (but that supposes Angular 5.2)

The other errors are all concerning the pagination.
`isEllipsis` is an internal field used in the template several times: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/pagination/pagination.ts#L132

Probably two ways to solve this also:
- either remove the internal annotation
- or use `$any(this).isEllipsis` in the template.

I can open PRs if you tell me what you would prefer/think is better.

### Link to minimally-working plunker that reproduces the issue:

As this concerns compilation, I built a small repro in a Github repository: https://github.com/cexbrayat/ngb-full-template-type-check

To reproduce:

    yarn
    yarn ngc

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.0-beta.0

ng-bootstrap: 1.0.0-beta.7

**Comment by pkozlowski-opensource** [comment]
> The first error concerns the carousel._getSlideEventDirection is a private method but is used in the template

Wow, this is definitively wrong! Would you mind sending a PR for this? I'm not sure why we are using it in a template, but if we have to we should rename it (remove `_`) and make public.

> isEllipsis is an internal field used in the template several times

We should definitively remove the `@internal` annotation, it is a left-over from earlier attempts to use this annotation to mark members that should not be exposed as a public API to the external world.

Fancy another PR to remove this annotation?

Thnx for bringing those issues up!

**Comment by cexbrayat** [comment]
@pkozlowski-opensource 👍 I submitted 2 PRs (hopefully) fixing this issue:

- #2040 for the carousel
- #2041 for the pagination

**Comment by cexbrayat** [comment]
@pkozlowski-opensource Happy to say that the issues are now gone in `1.0.0-beta.8` ✨

**Comment by pkozlowski-opensource** [comment]
Awesome, thnx for you help @cexbrayat !
