### ISSUE TITLE
Beautification and ordering of links for the project's Wiki sidebar menu

### ISSUE THREAD

**Issue by adriantanasa** [ng-bootstrap/ng-bootstrap#2042]
Not sure if this is the proper channel, however the default navigation for the Wiki page could benefit from some updates that will come from a custom github wiki sidebar (including ordering of pages):

I've build an example at: https://github.com/adriantanasa/ng-bootstrap/wiki

The forked wiki repository there has also a template that can be used with **github-wiki-sidebar** npm module to automatically update the sidebar menu after adding other pages.

https://raw.githubusercontent.com/wiki/adriantanasa/ng-bootstrap/options.json

If this is accepted as a valid work item, someone with push access for the wiki repository could easily update to have a similar result.

**Comment by pkozlowski-opensource** [comment]
Thnx for suggestions, I've re-organized pages roughly around your suggestions: https://github.com/ng-bootstrap/ng-bootstrap/wiki

Also restricted edit rights to contributors only.
