### ISSUE TITLE
Request: Please add event to detect Typeahead selection/choice by user

### ISSUE THREAD

**Issue by king612** [ng-bootstrap/ng-bootstrap#2043]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
Not a bug.  Request: Please add event to detect Typeahead selection.   Since ng-bootstrap generates the dropdown dynamically, there doesn't appear to be a way to detect when the user makes a selection other than watching for changes to the bound model.  Desired feature would be to generate an event that could be listened for with the chosen item, which preferable would be an object (not just a string) so that it could have a display value and an underlying value.

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
5.x

ng-bootstrap:
beta

Bootstrap:
4 beta

**Comment by pkozlowski-opensource** [comment]
What do you miss from the existing `selectItem` output, that, from our docs:

> An event emitted when a match is selected. Event payload is of type NgbTypeaheadSelectItemEvent.

https://ng-bootstrap.github.io/#/components/typeahead/api

**Comment by king612** [comment]
Oh my apologies. I missed that in the docs. 

Thanks!

John
