### ISSUE TITLE
bug(popover): Arrow placement for "left-top" and "right-top" is incorrect

### ISSUE THREAD

**Issue by mijelin** [ng-bootstrap/ng-bootstrap#2044]
### Bug description:
When specifying the "left-top" or "right-top" placements for a popover, the arrow is misaligned:
![image](https://user-images.githubusercontent.com/7971973/34063425-db14b958-e1a6-11e7-863e-13e8cac7c597.png)

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/anT5QTj8NYTpFI213JUk?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.0.2

ng-bootstrap: 1.0.0-beta.8

Bootstrap: 4.0.0-beta.2

**Comment by pkozlowski-opensource** [comment]
This seems to be fixed in beta.3 of Bootstrap CSS: http://plnkr.co/edit/anT5QTj8NYTpFI213JUk?p=preview

I will do some more testing and cut a new release of ng-bootstrap today that is compatible with Bootstrap CSS beta.3

**Comment by pkozlowski-opensource** [comment]
ng-bootstrap beta.9 was released with full compatibility with beta.3 of Bootstrap CSS so this issue is fixed now.
