### ISSUE TITLE
Open model of child component from parent component

### ISSUE THREAD

**Issue by newkillerbeast2017** [ng-bootstrap/ng-bootstrap#2045]
I am not entirely sure if this is a bug or a new feature request. Assuming I had a home component and a footer component. The footer component has a modal and is included in multiple places(as a child component) and I wanted to open the modal from the home component(parent). I find I cannot open the modal. Here is something I tried:

home.component.html:

`    <a (click)="open(terms)">terms &amp; conditions</a>`

home.component.ts:

```
    open(content) {
      this.modalService.open(content).result.then((result) => {
      }, (reason) => {
      });
    }
```

footer.component.html:

```
    <ng-template #terms let-c="close" let-d="dismiss">
      <div class="modal-header">
        <h4 class="modal-title">Terms &amp; Conditions</h4>
        <button (click)="d('Cross click')" type="button" class="close" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Test
      </div>
      <div class="modal-footer">
        Test
      </div>
    </ng-template>
```
I tried this but nothing opens nor do I get an error. Is this already supported?

**Note**: I am not referring to the [component as content](https://ng-bootstrap.github.io/#/components/modal/examples) example but rather calling a modal from a parent when the modal is present in the child.

**Comment by jnizet** [comment]
`#terms` defines a template-local variable. This variable is only visible from the footer tempate. Not from the home template. Component as content is most probably the cleanest way to do what you want.
