### ISSUE TITLE
serial number will start from 1 when we click on page second button or next button

### ISSUE THREAD

**Issue by OmkarJadhav21** [ng-bootstrap/ng-bootstrap#2047]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
4.3.5
![e-billing 2](https://user-images.githubusercontent.com/30443734/34109613-2fdb8d88-e42a-11e7-8d34-9cc822a90a41.png)
![e-billing 1](https://user-images.githubusercontent.com/30443734/34109626-36a9eb78-e42a-11e7-980e-dac32d8748bf.png)
Bootstrap:
4

**Comment by pkozlowski-opensource** [comment]
I'm sorry but it is not clear at all what the problem is / what you are asking for. If you need help using ng-bootstrap, please ask support questions using a dedicated support channel: https://github.com/ng-bootstrap/ng-bootstrap#getting-help

If you believe that there is a bug in our library, please provide a minimal reproduce scenario: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by OmkarJadhav21** [comment]
See both the sereen shots.Observe in second screenshot the serial number will start from 1 instead of starting from 11.

**Comment by pkozlowski-opensource** [comment]
I'm sorry, we can't help with / debug screenshots. Please follow our issue template when reporting bugs (most importantly, we need a minimal reproduce scenario using plunker or similar) and use dedicated support forums to ask support questions.
