### ISSUE TITLE
[Bug] mutually invalid minDate and maxDate cause "ExpressionChangedAfterItHasBeenCheckedError" error in ngClass

### ISSUE THREAD

**Issue by maxkorz** [ng-bootstrap/ng-bootstrap#2054]
### Bug description:

The attached plunker contains 2 different calendars.
startDate has `[maxDate]` set to value of endDate
endDate has `[minDate]` set to value of startDate.

When I make value of endDate invalid, ngClass throws `ExpressionChangedAfterItHasBeenCheckedError` error.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/tb0NeOqoL94E8XBKgIDV?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.1.1
ng-bootstrap: 1.0.0-beta.7
Bootstrap: 4.0.0-beta.2

**Comment by maxkorz** [comment]
According to [this article](https://blog.angularindepth.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4), wrapping `minDate`/`maxDate` validators to `Promise.resolve(null)` could solve the issue.

**Comment by pkozlowski-opensource** [comment]
I believe that this is a duplicate of #1982

**Comment by pkozlowski-opensource** [comment]
Closing as duplicate of  #1982
