### ISSUE TITLE
missing Buttons with dropdowns

### ISSUE THREAD

**Issue by AltRoot17** [ng-bootstrap/ng-bootstrap#2055]
Sir, Please try to make Buttons with dropdowns option  ,  I mean like this look ate bootsrap-4 sample  , and go to **Buttons with dropdowns**  https://getbootstrap.com/docs/4.0/components/input-group/

**Comment by bastienmoulia** [comment]
There is already plenty of that: https://ng-bootstrap.github.io/#/components/dropdown/examples

**Comment by pkozlowski-opensource** [comment]
Agree with @bastienmoulia - we should have pretty much everything covered. What do you miss exactly, @AltRoot17 ?

**Comment by AltRoot17** [comment]
@bastienmoulia  @pkozlowski-opensource  Sir, I updated my question, may be I'm wrong   this, because I m beginner for the Angular ,I m try to find your example , but I don't see  like this **Buttons with dropdowns**

**Comment by bastienmoulia** [comment]
@AltRoot17: You can do that: http://plnkr.co/edit/mV6tridL2laHdY17Hp87?p=preview

@pkozlowski-opensource: The focus of the dropdown button has a shadow-box hidden by the input, is it normal or should I open an issue ?

**Comment by AltRoot17** [comment]
@bastienmoulia  Thanks for the guide sir ,

**Comment by pkozlowski-opensource** [comment]
@bastienmoulia thnx so much for helping out with the issues / code - this is _very_ appreciated!
