### ISSUE TITLE
@ng-bootstrap\ng-bootstrap throws error while starting application with universal rendering

### ISSUE THREAD

**Issue by yogender-kumar** [ng-bootstrap/ng-bootstrap#2059]
### Bug description:
I have followed all the steps mentioned in https://ng-bootstrap.github.io/#/getting-started. It is working fine with JIT but getting error with Universal rendering. Attached is the error screenshot

![ng-bootstrap_universal-rendering_error](https://user-images.githubusercontent.com/5797285/34350904-595f6e98-ea3f-11e7-8bc0-d86f62a6d23d.png)

### Version of Angular, ng-bootstrap, and Bootstrap:
angular/cli: 1.6.1
angular/core: 5.1.1
typescript: 2.4.2
ng-bootstrap: 1.0.0-beta.8
bootstrap: 4.0.0-beta

**Comment by pkozlowski-opensource** [comment]
Duplicate of #858
