### ISSUE TITLE
Bug: Custom date adapter

### ISSUE THREAD

**Issue by franciscomemoli** [ng-bootstrap/ng-bootstrap#2060]
The custom adapter is calling it self until it die, giving "ERROR RangeError: Maximum call stack size exceeded"
I can reproduce it on the demo examples (https://ng-bootstrap.github.io/#/components/datepicker/examples) and 
http://plnkr.co/edit/?p=preview

The problem is toModel changes the variable and fromModel too, so the onChange is called indefinitely.
No workaround for the moment, any suggestion?

**Comment by nicoabie** [comment]
@pkozlowski-opensource it was an issue with the provided NativeDateAdapter example.
Fixed the example and added a couple of tests. Thanks in advance for the review.

@franciscomemoli update the following method fran ;)
```javascript
toModel(date: NgbDateStruct): Date {
    return date ? new Date(date.year, date.month - 1, date.day) : null;
}
```

**Comment by franciscomemoli** [comment]
Solved! thank you!!

**Comment by nicoabie** [comment]
@franciscomemoli de nada, mandale un saludo a manu jajaja
