### ISSUE TITLE
ngb-alert: message is overlapping the text, if the alert is in a fixed position

### ISSUE THREAD

**Issue by gergely-kovacs** [ng-bootstrap/ng-bootstrap#2064]
### Bug description:
If we want the alerts to be in a fixed position, and take up only as much space as necessary,
then the message will overlap with the closing symbol (x).

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/OtQxRZU8IMuoFKqHfFo4?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:
* angular: ^5.0.2
* nb-bootstrap: ^1.0.0-beta.5
* bootstrap: ^4.0.0-beta.2

Can you come up with something to support that use-case, or add an extra alert type for it, please?

**Comment by pkozlowski-opensource** [comment]
This is a problem with Bootstrap CSS and seems to be fixed in beta.3 of Bootstrap: http://plnkr.co/edit/VkOAtomBRRaNJTWo6mal?p=preview

I'm going to close this issue here as:
* it is a Bootstrap CSS issue and already fixed in beta.3
* we are cutting a release updating to beta.3 today
