### ISSUE TITLE
Datepicker i18n could now be automatic

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#2065]
### Bug description:

The day and month names displayed by the datepicker are currently hardcoded to English in a service (NgbDatepickerI18nDefault), and it's possible to provide a different implementation of that service to customize these names.

Since we now rely on Angular 5.x, and since Angular 5.x now comes with an i18n API, we could replace the default implementation of this service and get the day and month names from the API.

Advantages:
 - the names would be consistent with the ones used by the standard i18n pipes, and any other library using the i18n API
 - the datepicker would honor the configured locale automatically (provided the locale data have been provided with registerLocaleData, as it's necessary for the i18n of the pipes)
 - there is no need to provide a custom NgbDatepickerI18n implementation anymore to change the names
 - A single implementation can be used for all locales
 - It's still possible, by keeping our NgbDatepickerI18n service, and only changing the default implementation, to customize as it was done before, and we thus introduce no backward incompatibility in the API

Drawbacks:
 - I don't see any

I'm ready to work on a PR if it's OK with you.

**Comment by pkozlowski-opensource** [comment]
YES! This is something we've discussed with @maxokorokov and this would be a way to go indeed. We were just waiting for Angular 5.x.

Technically it would be a breaking change but I guess this is a reasonable one. 

> I'm ready to work on a PR if it's OK with you.

Please do!
