### ISSUE TITLE
Position of tooltip is slightly shifted

### ISSUE THREAD

**Issue by kubica** [ng-bootstrap/ng-bootstrap#2067]
### Bug description:

This issue is similar to [https://github.com/ng-bootstrap/ng-bootstrap/issues/1845](https://github.com/ng-bootstrap/ng-bootstrap/issues/1845). The tooltip arrow is not shown at the middle of the element (see picture).

![Alternativer Text](https://i.imgur.com/G6G6uKW.png)

Same problem for `placement="right"` etc.

### Link to minimally-working plunker that reproduces the issue:

[http://plnkr.co/edit/EPGCNPOGN0EAKXUCwAU3?p=preview](http://plnkr.co/edit/EPGCNPOGN0EAKXUCwAU3?p=preview)

### Workaround

```
.bs-tooltip-top .arrow, .bs-tooltip-bottom .arrow {
    margin-left: -2px;
}
.bs-tooltip-left .arrow, .bs-tooltip-right .arrow {
    margin-top: -2px;
}
```
### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.0.2

ng-bootstrap: 1.0.0-beta.8

Bootstrap: 4.0.0-beta.2

**Comment by bastienmoulia** [comment]
Actually there is in the CSS of the tooltip arrow
``` css
left: 50%;
```
And we can use
``` css
left: calc(50% - 2.5px);
```
