### ISSUE TITLE
Multiline tooltip at right edge gets resized on click

### ISSUE THREAD

**Issue by tzunghaor** [ng-bootstrap/ng-bootstrap#2069]
### Bug description:

I have a button with a tooltip so far right, that the tooltip reaches the right edge of the window / position:relative container.
Clicking the button calls a method (irrelevant what it does, in the plunkr example it does nothing), and then unexpectedly the tooltip becomes narrower.
(I experienced something similar with popovers too.)

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/dUKdE9lmtJ8fBbINagz4?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.0.2

ng-bootstrap: 1.0.0-beta.8

Bootstrap: 4.0.0-beta

**Comment by milasevicius** [comment]
Setting `container="body"` seems to solve this issue

**Comment by tzunghaor** [comment]
@milasevicius - `container="body"` seems to solve it in the plunker for the centered button, but not for the button on the right.

**Comment by maxokorokov** [comment]
This should be fixed in `4.0.3`, but please see this → https://github.com/ng-bootstrap/ng-bootstrap/pull/2972#issuecomment-460647837. Feel free to reopen if you're still having issues.
