### ISSUE TITLE
Navbar always collapsed

### ISSUE THREAD

**Issue by woeterman94** [ng-bootstrap/ng-bootstrap#2073]
### Bug description:
My navigation bar is not working. It shows like this on all devices. Also the menu to open it is not working.

![image](https://user-images.githubusercontent.com/5755057/34618237-6a9d41a6-f23e-11e7-951e-161b54f01903.png)

I did include bootstrap in my css. And I registered ng-bootstrap in my main module.

`     "styles": [
        "../node_modules/bootstrap/dist/css/bootstrap.min.css",
        "styles.css"
      ],`

`import {NgbModule} from '@ng-bootstrap/ng-bootstrap';`

My code

```
`<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
```

Am I missing something here?

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.0.0

ng-bootstrap: 1.0.0-beta.8

Bootstrap: 4.0.0-beta.3

**Comment by pkozlowski-opensource** [comment]
We'v got this setup working perfectly fine on our demo page (https://ng-bootstrap.github.io/#/home), you can see the exact code here: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/demo/src/app/app.component.html

We are not addressing support requests here, see: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
