### ISSUE TITLE
Keyboard navigation for dropdown, tabs and modals

### ISSUE THREAD

**Issue by AntonLebiodkin** [ng-bootstrap/ng-bootstrap#2077]
Hi, guys! 
I appreciate a lot your work at ng-bootstrap. It helps out team a lot.

I want to ask about accessibility support.
Will keyboard navigation feature for dropdowns, tabs and modals be available in ng-bootstrap like in ui-bootstrap?
For example focus traps when dropdown or modal is open,
arrow navigation in dropdowns and also putting back focus on dropdown toggler when it was closed with ESC button.

Thanks for your attention!

**Comment by pkozlowski-opensource** [comment]
The short answer is - YES, we are working towards full keyboard support. I believe that we've got all the remaining captured in the accessibility-specific issues - you can find those here: https://github.com/ng-bootstrap/ng-bootstrap/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+accessibility%22

If you believe that there are items _not_ captured by the existing issues please open a small, focused issues (per-component) with as much details as you can provide (exact navigation / keyboard support expected etc.).
