### ISSUE TITLE
Modal - Closing a modal which contains a router-outlet does not deactivate the outlet

### ISSUE THREAD

**Issue by Tcharl** [ng-bootstrap/ng-bootstrap#2084]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

Opening a modal containing a router-outlet and closing it does not call deactivate on the outlet, even if we set null on the outlet. So reopening it will throw an error

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug
Will do it ASAP

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.1

ng-bootstrap: 1.0.6-alpha

Bootstrap: 4.0.0-Beta2

**Comment by pkozlowski-opensource** [comment]
> Will do it ASAP

Please do, we can't move forward on issues without a minimal reproduce scenario in a plunker or similar.

**Comment by Tcharl** [comment]
Hi,

Can't reproduce with a [simple plunkr](https://embed.plnkr.co/3TJ3ic/), I will see if I reproduce it later within my project and investigate more (I removed the modal for my current task when encountering the issue).
However, this plunkr can always be integrated as an iTest ;-).
