### ISSUE TITLE
Support datepickerMode - 'year'

### ISSUE THREAD

**Issue by GetTaxSolutions** [ng-bootstrap/ng-bootstrap#2092]
Is it datepickerMode 'year' supported in this component? this mode give me ability to select easily data. It is helpful for birthday select for example. 
This mode was implemented in Angular 1.x ui components here:
https://angular-ui.github.io/bootstrap/

I have example here: [https://gettaxsolutions.com/refund/australia/tax-file-number-tfn/support-form](https://gettaxsolutions.com/refund/australia/tax-file-number-tfn/support-form) when try to select Birthfay date.

I have to migrate the old component to the new one and found your project here. Is that mode supported? And id Not are you planning to do it?

Thank you
Gettaxsolutions Ltd

**Comment by maxokorokov** [comment]
Hi @GetTaxSolutions, it's not planned currently. 
However this was reported previously (please see #1811), so we might consider doing it later this year
