### ISSUE TITLE
Datepicker not correctly displayed in Internet Explorer 10(not emulated mode)

### ISSUE THREAD

**Issue by Yura13** [ng-bootstrap/ng-bootstrap#2094]
### Bug description:
Datepicker is not correctly displayed in native(**not emulated mode**) Internet Explorer 10.

### Link to minimally-working plunker that reproduces the issue:
If open this link https://ng-bootstrap.github.io/#/components/datepicker/examples you will see the next:

![image](https://user-images.githubusercontent.com/17030431/35093906-5c5afa1c-fc4c-11e7-8811-a578326ff74a.png)

**Comment by BrummbQ** [comment]
I can confirm this issue

**Comment by ExFlo** [comment]
Hi
Solution found, I am submitting a pullrequest for this.
BR
