### ISSUE TITLE
How to insert ngbDatePicker value to an API

### ISSUE THREAD

**Issue by leofiore99** [ng-bootstrap/ng-bootstrap#2096]
When I submit my form, my model has a object with ngbDateStruct format (day, month and year).

My API doesn't accept this format to insert. It just accept date objects, ou format like (yyyy-mm-dd).

How can I perform this to work?

Thanks!

**Comment by pkozlowski-opensource** [comment]
check "Custom date adapter" demo at https://ng-bootstrap.github.io/#/components/datepicker/examples

**Comment by leofiore99** [comment]
Thanks! But the custom date adapter example in the documentation contain an error... If you open the console and select a date on the input, will see. It stay calling fromModel and toModel with no stop, until get an limit error. Have you seen this before?
