### ISSUE TITLE
How to populate ngbDatePicker with an API value

### ISSUE THREAD

**Issue by leofiore99** [ng-bootstrap/ng-bootstrap#2097]
My API return a string value from datetimes fields, like this: "2017-12-07 11:43:07.2012944"

So, when I will edit an object, the datetime input should bring me the date registered in database through the ngModel. But, the datetime can't populate the input with the date, because the format that my API brings.

What can I do in this case?
Thanks!

**Comment by maxokorokov** [comment]
Hey, I can't understand unfortunately what you're trying to do.

Please see my comment here: https://github.com/ng-bootstrap/ng-bootstrap/issues/754#issuecomment-346086127
Also, maybe #2072 would help

I've also opened an issue to create a documentation overview of the datepicker: #2102

Also, If you are unsure if this is a bug or not than please use an appropriate support channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help

**Comment by leofiore99** [comment]
The datepicker* can't populate the input with the string that my database return, you know? Can you help me?

**Comment by MuhammadAsifAdnan** [comment]
this shit is terrible. @leofiore99 You got any solution bro? facing the same problem here.

**Comment by MuhammadAsifAdnan** [comment]
@newaeonweb thanks. i figured it out.

**Comment by brunano21** [comment]
@MuhammadAsifAdnan how?

**Comment by MuhammadAsifAdnan** [comment]
@brunano21 checkout newaeonweb's answer above.
