### ISSUE TITLE
Datepicker highlights first day of month on mousedown

### ISSUE THREAD

**Issue by bkmorimoto** [ng-bootstrap/ng-bootstrap#2099]
### Bug description:
On the initial selection of a date (as long as its not the first day of the month): on mousedown the first day of the month will highlight (.btn-light.active). Any subsequent date changes will not cause any highlighting issues.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/vOdg7tnsG5hVqPyIPh2K?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 5.1.3
ng-bootstrap: 1.0.0-beta.9
Bootstrap: 4.0.0-beta.3

**Comment by maxokorokov** [comment]
Please see the #2000
