### ISSUE TITLE
Typeahead

### ISSUE THREAD

**Issue by wesleycho** [ng-bootstrap/ng-bootstrap#21]
A clean & simpler typeahead

**Comment by icfantv** [comment]
Possibly with the concept of a virtual repeater like Material used for ng1 to prevent the DOM from potentially having hundreds of items.

**Comment by wz2b** [comment]
Being able to specify a source that's an Observable would be great.  Being able to somehow command  it to refresh its list would be good as well.

**Comment by icfantv** [comment]
@wz2b that's the intention.  we've started this conversation.  thanks.

**Comment by balteo** [comment]
What is the status for the typeahead? Is an implementation planned?

**Comment by pkozlowski-opensource** [comment]
> What is the status for the typeahead? Is an implementation planned?

It is work in progress. Normally I shy away from giving any time estimates but with the current state of affairs being rather good (all the design considerations sorted out) we are no more than a week away from landing things in master.

**Comment by balteo** [comment]
Thanks for the update and the good news.

Le 17 juil. 2016 12:09, "Pawel Kozlowski" <notifications@github.com> a
écrit :
