### ISSUE TITLE
AOT error Cannot determine the module for class NgbRadio in @ng-bootstrap/ng-bootstrap/buttons/radio.d.ts! Add NgbRadio to the NgModule to fix it.

### ISSUE THREAD

**Issue by keymaker19** [ng-bootstrap/ng-bootstrap#2100]
### Bug description:
AOT error Cannot determine the module for class NgbRadio in @ng-bootstrap/ng-bootstrap/buttons/radio.d.ts! Add NgbRadio to the NgModule to fix it.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
5.0.0
ng-bootstrap:
1.0.0-beta.9
Bootstrap:
^4.0.0

**Comment by pkozlowski-opensource** [comment]
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug
