### ISSUE TITLE
ngbRadioGroup with i18n labels not working

### ISSUE THREAD

**Issue by armandoxxx** [ng-bootstrap/ng-bootstrap#2101]
There is a problem with radio groups in 

> `
> "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.9",
    "bootstrap": "^4.0.0-beta.3",
    "core-js": "^2.5.3",
    "lodash": "^4.17.4",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.20"
  },
> `
> 

### Translated labels not working
`       <div class="btn-group btn-group-toggle"
             ngbRadioGroup
             [formControlName]="radioGroup"
             name="radioGroup">
          <label ngbButtonLabel class="btn btn-checkbox" [class.error]="submitted && !radioGroup.valid" i18n="@@radioValue1Label">
            <input ngbButton type="radio" [value]="1">Radio value 1
          </label>
          <label ngbButtonLabel class="btn btn-checkbox" [class.error]="submitted && !radioGroup.valid" i18n="@@radioValue2Label">
            <input ngbButton type="radio" [value]="2">Radio value 2
          </label>
          <label ngbButtonLabel class="btn btn-checkbox" [class.error]="submitted && !radioGroup.valid" i18n="@@radioValue3Label">
            <input ngbButton type="radio" [value]="3">Radio value 3
          </label>
        </div>`

### Non-translated labels: working
`        <div class="btn-group btn-group-toggle"
             ngbRadioGroup
             [formControlName]="radioGroup"
             name="radioGroup">
          <label ngbButtonLabel class="btn btn-checkbox" [class.error]="submitted && !radioGroup.valid" >
            <input ngbButton type="radio" [value]="1">Radio value 1
          </label>
          <label ngbButtonLabel class="btn btn-checkbox" [class.error]="submitted && !radioGroup.valid" >
            <input ngbButton type="radio" [value]="2">Radio value 2
          </label>
          <label ngbButtonLabel class="btn btn-checkbox" [class.error]="submitted && !radioGroup.valid" >
            <input ngbButton type="radio" [value]="3">Radio value 3
          </label>
        </div>
`

So workaround is to put text in span tag and write custom css to fix positioning. 

### Translated labels with wrapped span tags: working
`       <div class="btn-group btn-group-toggle"
             ngbRadioGroup
             [formControlName]="radioGroup"
             name="radioGroup">
          <label ngbButtonLabel class="btn btn-checkbox" [class.error]="submitted && !radioGroup.valid" >
            <input ngbButton type="radio" [value]="1"><span i18n="@@radioValue1Label">Radio value 1</span>
          </label>
          <label ngbButtonLabel class="btn btn-checkbox" [class.error]="submitted && !radioGroup.valid" i18n="@@radioValue2Label">
            <input ngbButton type="radio" [value]="2"><span i18n="@@radioValue1Label">Radio value 2</span>
          </label>
          <label ngbButtonLabel class="btn btn-checkbox" [class.error]="submitted && !radioGroup.valid" i18n="@@radioValue3Label">
            <input ngbButton type="radio" [value]="3"><span i18n="@@radioValue1Label">Radio value 3</span>
          </label>
        </div>`

**Comment by armandoxxx** [comment]
Let me try and simplify this.

if you put i18n attribute in label, to translate text of label, radiogroup stops working. Example below or full radio group code from OP with title "Translated labels not working" 
`<label i18n="@@someLabel"> ...</label>`

if you put another <span>, tag inside same label, and remove the i18n from label, like code below,  radiogroup works BUT one must implement custom CSS customization to show the text on proper place.
Check OP "Non-translated labels: working" and "Translated labels with wrapped span tags: working" titles for working code
`<label ><input type="radio"><span i18n="@@someLabel"></span></label>`

I'm sorry did not find proper ngb plunker to make one :( 

regards
Armando

**Comment by pkozlowski-opensource** [comment]
> radiogroup stops working

It is still not clear _what_ exactly is not working... Do you see any errors in the console? Dispaly is broken? Model not bound? I'm sorry, but it is not clear at all from your description...

> I did not find proper ngb plunker to make one. Sorry for that

We need a way to reproduce - we can't act on bugs that we can't see....

**Comment by armandoxxx** [comment]
forget it .. I can't make you plunker and you cant reproduce ... sorry to bother you. close it ...

**Comment by pkozlowski-opensource** [comment]
> forget it .. I can't make you plunker and you cant reproduce ... sorry to bother you. close it ...

I'm sorry, but we _really_ can't fix problems we can't see... It doesn't have to be plunker - you could create a minimal repository and publish it on GitHub.

I'm going to close this issue for now, please open a new issue if / when you've got a reproduce scenario.
