### ISSUE TITLE
datepicker: overview is missing

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#2102]
Several issues are raised recently on how to use advanced features of the datepicker: formatters, date adapters, range selection, i18n, etc.

Clearly the demos are not enough and the guide with design/features/code snippets is required (ex. as "Overview" for Material components: https://material.angular.io/components/autocomplete/overview)

At least the following subjects come to mind:
- Multiple month view
- Limiting navigation (min/max dates)
- Disabling date ranges
- Customisation
- Range selection
- i18n
- Using different date models
- Alternative calendar implementations
- Formatting date input value

**Comment by kotmatpockuh** [comment]
Hi. Any plans now? (date of doc)

**Comment by maxokorokov** [comment]
Closed in #2481
