### ISSUE TITLE
collapse is not implemented similarly to the bootstrap jquery collapse

### ISSUE THREAD

**Issue by shcarrico** [ng-bootstrap/ng-bootstrap#2104]
Bootstrap collapse as implemented with jQuery adds an interim `collapsing` class to key a CSS transition defined in Bootstrap `_transitions.scss` which is removed by subscribing to the native `transitionend` [event](https://developer.mozilla.org/en-US/docs/Web/Events/transitionend). This implementation does not replicate the original Bootstrap implementation as it does not handle transition at all. Will issue #295 address this via a similar fashion, or is the intention to make use of Angular animations to implement similar functionality for all animated components?

Source for this library: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/collapse/collapse.ts

Source for BS jQuery collapse plugin: https://github.com/twbs/bootstrap/blob/v4-dev/js/src/collapse.js

Angular: 4

ng-bootstrap: latest

Bootstrap: 4

**Comment by pkozlowski-opensource** [comment]
>  is the intention to make use of Angular animations to implement similar functionality for all animated components?

Intention is to use Angular animations for all components, including collapse, see #295

**Comment by blogcraft** [comment]
There are no animations with ngbootstrap by default, how can we enable them?
