### ISSUE TITLE
Feat. Id and For Directive for Forms / Custom Checkboxes or Radios

### ISSUE THREAD

**Issue by f-aubert** [ng-bootstrap/ng-bootstrap#2106]
### Feat description:
When using Bootstrap Custom Checkboxes or Radios (https://getbootstrap.com/docs/4.0/components/forms/#checkboxes-and-radios-1), it is necessary to provide a unique id attribute for the input and then refer it in the label using 'for' attribute; else they are not clickable...
It would be nice to have ng directives, in ng-bootstrap maybe?, to ease the generation of this id/for pair, especially in case of reactive form where it could be automatically set to the full path of the control. Currently we have to manually build such an unique string, which may be hacky, in case of reusable components.
What do you think? Is it doable? Is it worth it?

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.0

ng-bootstrap: 1.0.0-beta.9 

Bootstrap: 4.0.0-beta.3

**Comment by pkozlowski-opensource** [comment]
> it is necessary to provide a unique id attribute for the input and then refer it in the label using 'for' attribute; else they are not clickable...

This is _not_ the case with radio / check-box buttons implementation from ng-bootstrap, see:
https://ng-bootstrap.github.io/#/components/buttons/examples

Why do think you need those `id`s?

**Comment by f-aubert** [comment]
Thx for the feedback. I do think sometimes you really want something that look like a Checkbox with a Tick, and not simply a button that changes background when selected. Hence I would enjoy being able to use the bootstrap input as offered in vanilla bootstrap such as following, inside of a *ngFor,

```
<div class="custom-control custom-checkbox d-print-none">
  <input class="custom-control-input" [id]="type + i + 'parallel'" name="parallel"  formControlName="parallel" type="checkbox"/>
  <label class="custom-control-label" [for]="type + i + 'parallel'"></label>
</div> 
```
To ensure that the id is unique, I must concat multiple values, and I was wondering if there is something to do with a ngBootstrap directive to make it easier. If you still think it is 'out of scope' then disregards this feat. wish.

**Comment by pkozlowski-opensource** [comment]
> To ensure that the id is unique, I must concat multiple values, and I was wondering if there is something to do with a ngBootstrap directive to make it easier. 

Nope, we don't have any particular directive to generate unique ids as for cases of the components / directives supported here we are using a simple system that you can easily see in, say: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/accordion/accordion.ts#L18-L52

> If you still think it is 'out of scope' then disregards this feat. wish.

You could probably write a simple directive setting an id based on the above idea. But we are not planning to add such facilities here, so closing this issue.
