### ISSUE TITLE
Global variable for use in UMD bundles not available.

### ISSUE THREAD

**Issue by CarstenLeue** [ng-bootstrap/ng-bootstrap#2107]
### Bug description:

When building an Angular library based on the Angular Package Format (APF) v5.0 (https://goo.gl/jB3GVv) I need to specify the name of a global variable that represents the bootstrap library. This step is required in the rollup config of the build process.

I cannot find the name of this global variable for the ng-bootstrap library. Is it available but not documented? 

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.0

ng-bootstrap: 1.0.0-beta.9

Bootstrap: n/a

Related to https://github.com/filipesilva/angular-quickstart-lib/issues/40

**Comment by pkozlowski-opensource** [comment]
It should be `ngb`: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/gulpfile.js#L80

**Comment by pkozlowski-opensource** [comment]
Haven't heard back from @CarstenLeue so closing this one.
