### ISSUE TITLE
[request]: typeahead documentation with real API call

### ISSUE THREAD

**Issue by borriej** [ng-bootstrap/ng-bootstrap#2108]
Hi,

Is it possible to extend the typeahead doc's with a async RXJS example on the service (to a server)?

**Comment by pkozlowski-opensource** [comment]
We've got it already, check "Wikipedia search" at https://ng-bootstrap.github.io/#/components/typeahead/examples

is there anything else in particular that you are missing from this example?

**Comment by borriej** [comment]
Im running into issues with Typehead saying:

```
TypeError: Cannot read property 'lift' of undefined
```

```
"@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.5",
"rxjs": "^5.5.2" ,
"@angular/core": "^5.0.0",
```

So I've been reeding through https://github.com/ng-bootstrap/ng-bootstrap/issues/1885 and http://plnkr.co/edit/a0y3cGYIESXimTKCOxBX?p=preview 

But can't seem to find a working piece of Search function. 

Question i have
* Can i use RxJS ^5.5?
* Do i need to use return, or not?
* Should I use curly brackets, or not?

**Comment by pkozlowski-opensource** [comment]
@borriej I'm sorry, but it is very hard to help without a reproduce scenario illustrating what you are trying to do... If you believe that our code is buggy please try to modify our plunker to expose the issue: http://plnkr.co/edit/fEkiqSnOTp3iVx0wxebk?p=preview

If you are not sure how to use the widget, please try to reproduce your use-case in a plunker and ask a support question using a dedicated channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help

It is really hard to answer your questions without seeing a minimal reproduce scenario...

**Comment by borriej** [comment]
@pkozlowski-opensource I understand, i tried to make a plunkr yesterday, but did'nt succeed yet. Will try again tomorrow

**Comment by pkozlowski-opensource** [comment]
> i tried to make a plunkr yesterday, but didn't succeed yet. Will try again tomorrow

Sure. I'm going to close this issue for now, but happy to re-open when you've got a plunker with a reproduce scenario.
