### ISSUE TITLE
Missing license file in npm release

### ISSUE THREAD

**Issue by readme42** [ng-bootstrap/ng-bootstrap#2111]
When installing this library via npm, the [license file](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/LICENSE) is missing. This makes automated license generation complicated. Could you add the file to upcoming npm releases?

**Comment by pkozlowski-opensource** [comment]
@readme42 are you saying that we should distribute `LICENSE` file as part of our npm package? If so,  #2114 should take care of this

**Comment by readme42** [comment]
@pkozlowski-opensource thats exactly what i mean. Thanks a lot!
