### ISSUE TITLE
Export typeahead testing functions

### ISSUE THREAD

**Issue by nicoabie** [ng-bootstrap/ng-bootstrap#2120]
### Bug description: It would be handy for devs that test their applications to be able to import some of the functions that are used inside the library for testing.

As I was testing a view that uses the typeahead component I had to copy and paste from the spec source the following functions:

`function expectWindowResults(element, expectedResults: string[])`

`function changeInput(element: any, value: string)`

I think it would be great if those are exported by the library.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.0.0

ng-bootstrap: 1.0.0-beta.9

Bootstrap: 4.0.0-beta.3

**Comment by pkozlowski-opensource** [comment]
> I think it would be great if those are exported by the library.

Sorry, no plans to open this up in any foreseeable future. We are just cutting 1.0 and can't afford opening-up test-related APIs atm. Copy & paste is your best option.

**Comment by nicoabie** [comment]
Thanks for the time @pkozlowski-opensource 
Let me know if I can help with anything regarding 1.0
