### ISSUE TITLE
Bug: Cyclic dependencies while opening modal from service with App_Initializer

### ISSUE THREAD

**Issue by shyamal890** [ng-bootstrap/ng-bootstrap#2122]
It seems having `NgbModal` reference in service is causing cyclic dependency error with `App_Initializer`.

Checkout this plunker: http://plnkr.co/edit/FIj4tMjUikbGHIHhf7ko?p=preview

Remove the following code from the plunker and the modal would be displayed as expected from the service. 
```
  {
        provide: APP_INITIALIZER,
        useFactory: initializeServiceFactory,
        deps: [InitializeService],
        multi: true
    }
```

**Comment by shyamal890** [comment]
`ToastrService` too has the same issue.

**Comment by pkozlowski-opensource** [comment]
All the services that open dynamic dialogs need to inject `ApplicationRef` - there are no other APIs to add dynamically created views to the change detection system...

`APP_INITIALIZER` is _very_ early in the Angular app lifecycle, I'm not sure we can make it work with the current APIs in `@angular/core, to be investigated.

**Comment by shyamal890** [comment]
I am currently using `injector` to inject `ToastrService` and `NgbModal` in constructor of the service. Wonder if this is good temporary fix for the issue.

**Comment by pkozlowski-opensource** [comment]
> Wonder if this is good temporary fix for the issue.

Yes, this is what I would suggest as a work-around.

**Comment by shyamal890** [comment]
Would you suggest initiating inside `setTimeout` or it would be alright without it?

**Comment by wKoza** [comment]
In the main, it's better @shyamal890 .

This 'bug' is not in relation with ng-boostrap but with Angular. `APP_INITIALIZER` is very perfectible.

**Comment by pkozlowski-opensource** [comment]
I don't think we can make it work from `APP_INITIALIZER` in the current Angular - it is very early in the initialisation process and all the modal-required infrastructure is not ready yet.
