### ISSUE TITLE
Template inside ngTabContent not working

### ISSUE THREAD

**Issue by shabbir-dhangot** [ng-bootstrap/ng-bootstrap#2126]
### Bug description:
Template inside ngTabContent not working.

     <ngb-tabset (tabChange)="beforeChange($event)" [activeId]="activeTab">
          <ngb-tab id="tab1">
            <ng-template ngbTabTitle>
              <label class="tab-title">Tab 1</label>
            </ng-template>
            <ng-template ngbTabContent>
                  <app-search></app-search>  <-- Issue here
            </ng-template>
          </ngb-tab>
          ......
     </ngb-tabset>

In my app there are two different search page. one standalone and other with tab. I want to load content that is there on the template inside tab. I don't want to rewrite whole code here. 

Problem : 
Its not loading inside tab. its replacing all content and load.

My Question :
How can I load template inside Tab.

Angular:
4+
ng-bootstrap:
1.0.0-alpha.29 (For some reason using old one)
Bootstrap:
4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
I'm sorry, but it is not clear what you are asking for here / what is the problem. 

If you need general support please use an appropriate channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help

If you believe that there is a bug in this library, please open a new issue following our issue template: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

**Comment by shabbir-dhangot** [comment]
I am asking for support. 

I am having two type of search page. One is standalone search page and one with tab of different kind of search.

For tab I am trying to use same component and using selector of standalone page.

    <ng-template ngbTabContent>
              <app-search></app-search>  <-- Issue here
        </ng-template>

It is not working when I am giving selector of that component.

**Comment by shabbir-dhangot** [comment]
@pkozlowski-opensource  What should I do to reuse any component into tab?
