### ISSUE TITLE
Not setting selected value as button text in for dropdown

### ISSUE THREAD

**Issue by Kalpesh300** [ng-bootstrap/ng-bootstrap#2127]
I am using this module in my angular 5 project.
Below is my dropdown html:
Here, method statusFilterClicked changes value of statusSelected property in my typescript file.
This statusSelected value is binded to button text by interpolation. 
But the problem is it is not getting reflected on the view.
   `<div ngbDropdown class="d-inline-block">
          <button class="btn btn-outline-primary normal-text h3" id="dropdownBasic1" ngbDropdownToggle>{{statusSelected}}</button>`
          `<div ngbDropdownMenu  aria-labelledby="dropdownBasic1" (click)="statusFilterClicked($event)">`
           ` <button class="dropdown-item normal-text h3">All</button>`
`            <button class="dropdown-item normal-text h3">Active</button>`
 `           <button class="dropdown-item normal-text h3">Archived</button>`
         ` </div>`
`        </div>`

**Comment by pkozlowski-opensource** [comment]
I'm sorry, but it is not clear what you are asking for here / what is the problem. 

If you need general support please use an appropriate channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help

If you believe that there is a bug in this library, please open a new issue following our issue template: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug
