### ISSUE TITLE
Typeahead and datepicker are not working when build with ng build --prod

### ISSUE THREAD

**Issue by carlos-algms** [ng-bootstrap/ng-bootstrap#2129]
**Typeahead** is selecting the first line that mouse hover in.
**Datepicker** is not changing months

Build command: 
`ng build --prod`

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.1.2

ng-bootstrap: ^1.0.0-beta.8

Bootstrap: ^4.0.0-beta.2

Here is a plunker with the bundled version of the app:
https://plnkr.co/edit/U95JL0

**Comment by pkozlowski-opensource** [comment]
> Typeahead is selecting the first line that mouse hover in.

This is a default behaviour, you can use the `focusFirst` to change this default: https://ng-bootstrap.github.io/#/components/typeahead/api

> Datepicker is not changing months

Sorry, not sure what you mean... 

> Here is a plunker with the bundled version of the app:

I'm sorry, but this is _not_ how you provide a reproduce scenario... We need a minimal, runnable example, see: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

We've got examples working at https://ng-bootstrap.github.io/#/components/datepicker/examples - you can fork a minimal plunker for each example and use it as a starting point for bug reports.

I'm going to close this isusse as:
* it mixes support requests and bug reports for several widgets (please create small, focused issues)
* it is not clear what is the problem with datepicker and we've got no reproduce scenario.

Please open a new issue, following the issue template if you still got problems with the datepicker.
