### ISSUE TITLE
how to capture the selected item in the typeahead

### ISSUE THREAD

**Issue by cullsin** [ng-bootstrap/ng-bootstrap#2130]
Hi, 
Can you suggest me how do I get the selected Item in the typeahead? I want to pass it on to other components. ngModelChange is not working.

  <input id="typeahead-http" type="text" class="form-control" [class.is-invalid]="searchFailed" 
  	(ngModelChange)="onCapture()" [(ngModel)]="model" [ngbTypeahead]="search" placeholder="reference" />
Thanks,
Raja K

**Comment by pkozlowski-opensource** [comment]
* use `selectItem` event: https://ng-bootstrap.github.io/#/components/typeahead/api
* use a dedicated support channel for support requests: https://github.com/ng-bootstrap/ng-bootstrap#getting-help

Closing as a support request.
