### ISSUE TITLE
Feature Request: Enable tooltip conditionally

### ISSUE THREAD

**Issue by shyamal890** [ng-bootstrap/ng-bootstrap#2131]
`ui-boostrap` supported `tooltip-enable` option through which you can enable tooltip conditionally. This is very much required for any complex application.

**Usecase:**
- Inform user that he doesn't have permission to access the `div` given his access level. `tooltip-enable` would evaluate the underlying function to determine the access level.
- Manual triggers are too complex for this usecase.

**Comment by pkozlowski-opensource** [comment]
> Manual triggers are too complex for this usecase.

Could you elaborate, ideally with a plunker illustrating what you are trying to do?
Also relevant discussion in: https://github.com/ng-bootstrap/ng-bootstrap/issues/2033

**Comment by pkozlowski-opensource** [comment]
Generally speaking I believe that manual triggers + a custom directive is the most flexible way to go. Happy to change my mind based on real-life use-cases.

**Comment by shyamal890** [comment]
Checkout this plunker: http://plnkr.co/edit/avi4waT0FrpwN4vmgAdG?p=preview

Current code needs:

```
  (mouseenter)="isDisabled() && t.open()"
  (mouseleave)="t.close()"
  #t="ngbTooltip" 
  triggers="manual"
```

Which can be replaced by simply:

`[isDisabled] = "isDisabled()"`

Imagine 100s of tooltip in an app. Wouldn't the last code be easier for the developer?

**Comment by skbelalmd** [comment]
Checkout this plunker: http://plnkr.co/edit/CSMT8u?p=preview

You can pass different values based on your condition. If you want to disable tooltip, simply pass an empty string.

**Comment by pkozlowski-opensource** [comment]
This is now possible with the `disableTooltip` option that was added in `1.1.0` through e05a99fa6c1bff05e3d03ffb28580a5ba27b94c7.

Closing as already implemented: https://ng-bootstrap.github.io/#/components/tooltip/api
