### ISSUE TITLE
Can't resolve './hijri/ngb-calendar-islamic-civil'

### ISSUE THREAD

**Issue by frankps** [ng-bootstrap/ng-bootstrap#2133]
After upgrading to version  1.0, I got suddenly the error:

ERROR in ./node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module.js
Module not found: Error: **Can't resolve './hijri/ngb-calendar-islamic-civil'** in 'C:\Code\Dvit\AirCare\air-care-ang\node_modules\@ng-bootstrap\ng-bootstrap\datepicker'
resolve './hijri/ngb-calendar-islamic-civil' in 'C:\Code\Dvit\AirCare\air-care-ang\node_modules\@ng-bootstrap\ng-bootstrap\datepicker'

Any idea?

**Comment by pkozlowski-opensource** [comment]
The file in question is well deployed to `npm` (ex.: https://unpkg.com/@ng-bootstrap/ng-bootstrap@1.0.0/datepicker/hijri/ngb-calendar-islamic-civil.js) , so I can think of 2 potential issues:
* downloaded npm package is somehow broken on your end (remove `node_modules` and try to re-install);
* you are not using Angular 5.x


A couple of questions:
* what version of Angular are you using?
* what version of ng-bootstrap you were using previously that was still OK for you?

We've got it working with AOT (see "Alternative calendars" at https://ng-bootstrap.github.io/#/components/datepicker/examples) so I'm surprised that it fails for you. I would bet that you are still on Angular 4.x?

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't heard back

**Comment by matpag** [comment]
This happened to me too.
We are using Angular 5.2.9 and this error came out when I upgraded ng-bootstrap from version 1.0.1 to 1.0.2 in `package.json`, then running `ng serve` was causing the compile error.
We are not using the datepicker in our project so the module is not imported anywhere, only a forced refresh of node_modules folder solved the problem.

**Comment by sandraandonov88** [comment]
@pkozlowski-opensource - So we can not use the package with angular 4?

**Comment by nimbus58** [comment]
Hello,
Same here:
```
"@angular/core": "6.0.6",
"@ng-bootstrap/ng-bootstrap": "^2.0.0
```",
No problems with ng serve but breaks with a simple: `ng build --prod`

**Comment by VincentFillon** [comment]
Hi,
Same here with angular 6 and ng-b 2.2.0
Nothing new ?
