### ISSUE TITLE
It's impossible to set custom date format on input

### ISSUE THREAD

**Issue by kotmatpockuh** [ng-bootstrap/ng-bootstrap#2137]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
I can't change input format, while for example I've changed date formatter, like here: https://github.com/ng-bootstrap/ng-bootstrap/issues/2072#issuecomment-361937961
And when I enter 02.03.2018 - it's assuming that my input is wrong - I can only select date in DatePicker

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/S3GSp4yWQSV0NwWRYmUY?p=preview

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
5

ng-bootstrap:
1.0.0-beta.9

Bootstrap:
4.0.0

**Comment by astashko** [comment]
You forgot to change delimiter from '-' to '.' in parse.

**Comment by kotmatpockuh** [comment]
@astashko  where exactly?

**Comment by astashko** [comment]
@kotmatpockuh app.ts, line 15 change .split('-') to .split('.')

**Comment by kotmatpockuh** [comment]
@astashko right you are.
thanks

**Comment by aadii104** [comment]
@kotmatpockuh 
how did you change ur date format to dd.mm.yyyy?

**Comment by kotmatpockuh** [comment]
@aadii104  http://plnkr.co/edit/6iVFDkW04EKviaeXAYE7?p=preview

**Comment by aadii104** [comment]
thanks @kotmatpockuh any help on this one?
https://github.com/ng-bootstrap/ng-bootstrap/issues/2276

**Comment by kotmatpockuh** [comment]
@saigalamatya what do you mean?
just put a focus into input and type :)
