### ISSUE TITLE
Select multiple dates in one calendar like http://dubrox.github.io/Multiple-Dates-Picker-for-jQuery-UI/

### ISSUE THREAD

**Issue by xyrintech** [ng-bootstrap/ng-bootstrap#2138]

**Comment by xyrintech** [comment]
Is this feature available?

**Comment by maxokorokov** [comment]
You could it by using the `(select)` output of the datepicker or `(ngModelChange)`
Please check the `Range Selection` demo: https://ng-bootstrap.github.io/#/components/datepicker/examples

Also #2181 and #1984 might be relevant
