### ISSUE TITLE
NgbTooltipWindow error when using server-side rendering

### ISSUE THREAD

**Issue by mathieubruguier** [ng-bootstrap/ng-bootstrap#2139]
### Bug description:

I get the following error when using tooltips with server-side rendering:
`Error: No component factory found for NgbTooltipWindow. Did you add it to @NgModule.entryComponents?`

I tried adding `NgbTooltipWindow` to both server-side and client-side modules but the error remains.

### Version of Angular and ng-bootstrap:

**Angular**: 5.2.2
**ng-bootstrap**: 1.0.0

It would make sense to disable tooltips for the server-side, but I'm not sure how to do that, and I figured I might as well report the error just in case.
I'm following [this guide](https://angular.io/guide/universal) for server-side rendering.
Thank you for your help.

**Comment by abyrne85** [comment]
I'm having the same issue

**Comment by Stajor** [comment]
Same issue for me. Any updates?

**Comment by pkozlowski-opensource** [comment]
This, most likely, happens because of this line: https://github.com/ng-bootstrap/ng-bootstrap/blob/02f6f7a75858a294b6568fc245a59ff866c9d8fb/src/util/popup.ts#L24

It seems like trying to resolve a component in a constructor breaks ssr. Additional info in #2180
