### ISSUE TITLE
ng-bootstrap doesn't work without adding css file to index.html

### ISSUE THREAD

**Issue by chrisgeek** [ng-bootstrap/ng-bootstrap#2141]
The doc on using ng-bootstrap on github fails to mention that a cdn call must be made in the index.html file else ng-bootstarp won't work.
my cdn call below

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
It doesn't work when this line is removed from index.html.

**Comment by ffd114** [comment]
They did mention the required dependencies are:
- Angular
- Bootstrap CSS

So we can install Bootstrap from node then add them on `.angular-cli.json` or global `styles.css`. I myself include them on global `styles.css` by putting it like here:

`@import '~bootstrap/dist/css/bootstrap.css';`

**Comment by cloudgate313** [comment]
Hello, I am having an issue where the styles for the modal are not applied unless you refresh the app.  

- @import '~bootstrap/scss/bootstrap.scss'; globally in syles.scss

-  "@ng-bootstrap/ng-bootstrap": "1.0.0",

- "bootstrap": "4.0.0",

- "@angular/compiler": "5.2.4",

**Comment by pkozlowski-opensource** [comment]
We've it documented at https://ng-bootstrap.github.io/#/getting-started

**Comment by adamk33n3r** [comment]
@johannesmik #1. It says "After installing the above dependencies...". If you look above the dependencies are `Angular` and `Bootstrap CSS`.

**Comment by johannesmik** [comment]
@adamk33n3r Yes, Step 1 mentions installation of `Bootstrap CSS`. And at the linked Bootstrap 4.0 site one can also find npm and gem commands to install bootstrap.

But, Step 1 doesn't mention including `Bootstrap CSS` in your project, and that's what this issue is about. There's no point in the guide where it says something along the lines: "...and then include the bootstrap.css to your styles.css like this...".

It might be obvious to advanced users but it confuses / slows down beginners.

**Comment by adamk33n3r** [comment]
I feel like that is the job of Bootstrap to give examples on how to 'install' it. There is a plethora of ways one can have bootstrap css loaded in their browser.

**Comment by johannesmik** [comment]
I don't think it's a question of whether its an 'advanced' activity or not, as this is a completely subjective opinion. For me, it's rather a question of whether the activity (loading bootstrap in your browser) is necessary for using ng-bootstrap. If it's necessary, then it should also be noted in the getting-started guide.

My proposal would be to add this sentence in the getting-started guide, section "Should I add bootstrap.js or bootstrap.min.js to my project?" : ".... However, you should add and include bootstrap.css into your project."

**Comment by pkozlowski-opensource** [comment]
@johannesmik @adamk33n3r could we move this discussion to #2203 which is an issue that is:
* still open;
* it is about improving installation instruction.

Commenting on closed issues is likely not get enough attention from people that should be paying attention :-)

**Comment by Bridgeway** [comment]
It's blatently obvious that bootstrap css should be required when using ng-bootstrap unless for some reason they haven't already built it in. Bootstrap is bootstrap whether its css or other stuff.

**Comment by levarberry** [comment]
Problem could be solved but just adding more information to make sure you include the .css.    Honestly the rest of the documentation is "Blatantly" obvious on how to use the package...   This part isn't as such.  As some NPM packages include the base requirements for you.

So continue to argue a point .. just to be lazy.... or . make people's life easier and just include the 1 extra sentence.

**Comment by andzejsw** [comment]
Well that is bad, cause i wanted also override bootstrap variables. And because of that, i am importing on styles only bootstrap.scss file.

**Comment by zoltan-nz** [comment]
Great job and nice library. Thanks for your hard work guys.

+1 for adding the css/scss package installation to the documentation. As mentioned earlier quite a lot of Bootstrap related package in JavaScript ecosystem automatically add Bootstrap 4 scss packages, so it is not so obvious. ;) I suppose a dedicated schematics would solve this problem automatically.

```
$ yarn add bootstrap
$ echo '@import "~bootstrap";' >> src/styles.scss
$ yarn add @ng-bootstrap/ng-bootstrap
```
