### ISSUE TITLE
markDisabled and firstDayOfWeek are not a known property of input.

### ISSUE THREAD

**Issue by fishgills** [ng-bootstrap/ng-bootstrap#2143]
### Bug description:

Adding `markDisabled` throws an error about it not being a known property. Not much more to say, pretty straightforward issue. :)

### Link to minimally-working plunker that reproduces the issue:

Plunker only contains the markDisabled but I'm getting the same error with firstDayOfWeek.

Here's a plunker with it broken. The only change added was the `[markDisabled]` property and the matching `isWeekend` method to the component.

http://plnkr.co/edit/upttdlnlsyoTu771tiii?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.2

ng-bootstrap: 1.0.0

Bootstrap: 4.0.0

**Comment by maxokorokov** [comment]
You've put `markDisabled` on a div:

```html
<div class="input-group-append" [markDisabled]="isWeekend">
```

It's working fine: http://plnkr.co/edit/WKeeYIW8uUM07fWOnuTG?p=preview
