### ISSUE TITLE
Customize Carousel

### ISSUE THREAD

**Issue by Saulolxx** [ng-bootstrap/ng-bootstrap#2153]
I can not make customizations in the carousel guidelines, I would remove the indicator and by a progress bar that accompanies the transitional period of the carousel, as in this example, can anyone give me a hand?

https://codepen.io/bsngr/pen/rbyas

**Comment by pkozlowski-opensource** [comment]
https://github.com/ng-bootstrap/ng-bootstrap#getting-help
