### ISSUE TITLE
Tabset component - should set context for each tab so that child components can know display current status

### ISSUE THREAD

**Issue by davidsekar** [ng-bootstrap/ng-bootstrap#2154]
### Feature description:
In Tabset component, when destroyOnHide = false.
It initializes all the tabs simultaneously, which works as expected.... But, incase there are 5 tabs with AJAX calls in it. Then the user may expect the active tab to be load data first and delay data loading for all other tabs.

So it will be pretty helpful if the context can be set for `ng-template` so that the child components within the tabdirective can know that it is part of active tab or not.  

```
<ngb-tabset>
  <ngb-tab title="Simple" *ngFor="let tab of tabs">
    <ng-template ngbTabContent let-isActive="isActive">
      <my-component [isActiveTab]="isActive"></my-component>
    </ng-template>
  </ngb-tab>
  <ngb-tab>
```

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular:
ng-bootstrap:1.0
Bootstrap:4

**Comment by pkozlowski-opensource** [comment]
Makes sense, marking as a feature request.

**Comment by OssprO** [comment]
Any news on this?

**Comment by Rajivkumar87** [comment]
I am using ngb Tabs with angular 6. I want to change the selected tab from code behind. below is my code.

<ngb-tabset #t="ngbTabset" (tabChange)="beforeChange($event)" justify="center">
          <ngb-tab *ngFor="let tab of tabs" [title]="tab.tabName" [disabled]="tab.disabled" [id]="tab.tabId">
            <ng-template ngbTabContent>
              <imp-name [data]="nameData" *ngIf="selectedTab===1"></imp-name>            
            </ng-template>
          </ngb-tab>
        </ngb-tabset>

In .ts file I am referring the tab with #t as shown below, 
  t: NgbTabset;

  ngOnInit() {
   this.t.select("2");
}
I am trying to make tab 2 active as its id is 2.

**Comment by maxokorokov** [comment]
Since version `5.2.0` there is a new `NgbNav` set of directives that fix this issue. `NgbNav` is meant to replace the `NgbTabset` component (completely deprecated in version `6.0.0`) as a more flexible alternative.

More specifically check https://ng-bootstrap.github.io/#/components/nav/api#NgbNavContentContext and related demo.

I suggest you migrate to it → https://ng-bootstrap.github.io/#/components/nav/overview
