### ISSUE TITLE
Documentation isuue: the datepicker and timepicker does'nt show how to encapsulate for reuse

### ISSUE THREAD

**Issue by meir-ohayon** [ng-bootstrap/ng-bootstrap#2155]
Common usage of datepicker and timepicker entitles to encapsulate them in components of its own rather than use them directly - in this use case it can be reuse several times (in the same component or across different components) without the need to reconfigure/re-code each time. 

The current documentation does not cover this common scenario (by the way the alert is also component that I can think as natural candidate for encapsulation,- but in alert, in contrary to datepicker and timepicker, there is not a model object that you need to communicate with, so in alert case encapsulation does not implies any complexity that need to be documented).

I made a [post](https://meir-ohayon.github.io/angular/2018/02/07/angular-ViewChild-and-ViewChildren-by-example.html) that explains how to use ng-bootstrap datepicker and timepicker as encapsulated reusable components. Permission granted to use it in this package documentation if you find it useful (all or part), just credit me in this case as contributor (you can also link to my post if you wish).

**Comment by maxokorokov** [comment]
Thanks for the idea @meir-ohayon,

I think it is a problem not related to this library, as it can be applied to any Angular components.
However, I'll see if we should mention this in #2102, for example

Cheers!
