### ISSUE TITLE
Tooltip on mobile devices with blur trigger not closeable 

### ISSUE THREAD

**Issue by joachimprinzbach** [ng-bootstrap/ng-bootstrap#2156]
### Bug description:
When using the "click:blur" trigger in a tooltip, it is closing nicely on desktop, but not on mobile devices (tested with iPad (iOS 11.2.5) and iPhone X (iOS 11.2.5) with both Safari and Chrome).
### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/1OR9N5gXENpd7N4Rxc6D?p=preview 
(This is the official tooltip plunker. The one directly in the docs does not work either: https://ng-bootstrap.github.io/#/components/tooltip/examples)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.2

ng-bootstrap: 1.0.0-beta.9

Bootstrap: 4.0.0-beta

**Comment by pkozlowski-opensource** [comment]
How are you triggering `blur` on those devices? From my testing on iOS it closes tooltips correctly if I focus another element on the same page. Could you please provide more info?

**Comment by pkozlowski-opensource** [comment]
Closing as I haven't heard back from @joachimprinzbach

**Comment by Hesesses** [comment]
If the tooltip is placed on div, it will never close:
http://plnkr.co/edit/ohu8FJ8UrDMsBoAEo5uR?p=preview

is this a bug or expected behaviour?

**Comment by Hesesses** [comment]
@pkozlowski-opensource ?
