### ISSUE TITLE
Ngb Tabset Orientation doesn't work for Angular 4

### ISSUE THREAD

**Issue by AmineBena17** [ng-bootstrap/ng-bootstrap#2157]
### Bug description:
Orientation doesn't working 
Hello,

i'm trying to implement a vertical tabset on my application in angular 2, i already define the orientation in <ngb-tabset> but nothing was changed.

My code :
`  <ngb-tabset [orientation]="currentOrientation">
    <ngb-tab title="Simple">
      <ng-template ngbTabContent >
        <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth
          master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh
          dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum
          iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
      </ng-template>
    </ngb-tab>
    <ngb-tab>
      <ng-template ngbTabTitle><b>Fancy</b> title</ng-template>
      <ng-template ngbTabContent>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid.
        <p>Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table
          craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl
          craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl
          cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit. Keytar helvetica VHS salvia
          yr, vero magna velit sapiente labore stumptown. Vegan fanny pack odio cillum wes anderson 8-bit, sustainable jean
          shorts beard ut DIY ethical culpa terry richardson biodiesel. Art party scenester stumptown, tumblr butcher vero
          sint qui sapiente accusamus tattooed echo park.</p>
      </ng-template>
    </ngb-tab>
  </ngb-tabset>
`
my component : 
`Hello,

i'm trying to implement a vertical tabset on my application in angular 2, i already define the orientation in <ngb-tabset> but nothing was changed.

My code :
`  <ngb-tabset [orientation]="currentOrientation">
    <ngb-tab title="Simple">
      <ng-template ngbTabContent >
        <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth
          master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh
          dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum
          iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
      </ng-template>
    </ngb-tab>
    <ngb-tab>
      <ng-template ngbTabTitle><b>Fancy</b> title</ng-template>
      <ng-template ngbTabContent>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid.
        <p>Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table
          craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl
          craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl
          cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit. Keytar helvetica VHS salvia
          yr, vero magna velit sapiente labore stumptown. Vegan fanny pack odio cillum wes anderson 8-bit, sustainable jean
          shorts beard ut DIY ethical culpa terry richardson biodiesel. Art party scenester stumptown, tumblr butcher vero
          sint qui sapiente accusamus tattooed echo park.</p>
      </ng-template>
    </ngb-tab>
  </ngb-tabset>
`
my component : 
`import {Component} from '@angular/core';

@Component({
  selector: 'connect-online-forms',
  template: require('./online-forms.component.html'),
  styles: [`
    :host {
      display: flex;
      height: 100%;
      flex-direction: column;
    }
  `]
})

export class OnlineFormsComponent {
  private currentOrientation = 'vertical';
}`

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4

ng-bootstrap: 1.0.0-beta.9

Bootstrap: 3

**Comment by serzhikkk** [comment]
I also have this error. Please, fix it!

**Comment by bastienmoulia** [comment]
Please make a plunker with your code.

I don't think bug related to Angular < 5 or Bootstrap < 4 will be fixed.

**Comment by AmineBena17** [comment]
i think it's not working with Bootstrap 3, so i did it with a simple CSS class.
thanks ;)
