### ISSUE TITLE
Custom date adapter cannot pass tsc "strictNullChecks"

### ISSUE THREAD

**Issue by changhuixu** [ng-bootstrap/ng-bootstrap#2161]
https://github.com/ng-bootstrap/ng-bootstrap/blob/827e83e540fe5dcb740ca93474f85afe071de426/demo/src/app/components/datepicker/demos/adapter/datepicker-adapter.ts#L10

 error TS2322: Type 'null' is not assignable to type 'NgbDateStruct'.

**Comment by Trapulo** [comment]
I also noticed

**Comment by maxokorokov** [comment]
Yeah, we're not strict null check compliant.

Duplicate of #1544
