### ISSUE TITLE
Timepicker not correctly displayed in Internet Explorer 10 (not emulated mode)

### ISSUE THREAD

**Issue by Yura13** [ng-bootstrap/ng-bootstrap#2163]
### Bug description:
Timepicker is not correctly displayed in native(**not emulated mode**) Internet Explorer 10.

### Link to minimally-working plunker that reproduces the issue:
Screen made from https://ng-bootstrap.github.io/#/components/timepicker/examples:
![image](https://user-images.githubusercontent.com/17030431/36198799-4331c536-1180-11e8-85c5-3a49efd35c58.png)

**Comment by bastienmoulia** [comment]
It looks like the css prefix for flexbox for IE10 is missing.
