### ISSUE TITLE
ng bootstrap doesn't support tree shaking

### ISSUE THREAD

**Issue by mboughaba** [ng-bootstrap/ng-bootstrap#2168]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.0

ng-bootstrap: 1.0.0

Bootstrap: 4.0.0

Hello

I created an angular app which depends on ng bootsrap.
I included only NgbButtonsModule however after analyzing the source map file on the production aot bundle I can still see that all components are still bundled inside the main bundle.

This involves compilation with prod and sm flags so a pluncker wouldn't help much.

Cheers,

**Comment by dhardtke** [comment]
Have you tried using deep imports?

E.g., instead of `import {NgbModal} from "ng-bootstrap";`

you should do something like

`import {NgbModal} from "ng-bootstrap/modal";`

(untested, but should work).

**Comment by maxokorokov** [comment]
Don't see any issues, works fine with CLI `1.7.1`, NG `5.2.6` on an empty CLI project:

```ts
// app.module.ts
import { NgbButtonsModule } from '@ng-bootstrap/ng-bootstrap'

imports: [
    BrowserModule,
    FormsModule,
    NgbButtonsModule.forRoot()
  ]
```

Getting 2K as the result:

<img width="633" alt="screen shot 2018-02-22 at 16 06 03" src="https://user-images.githubusercontent.com/8074436/36546131-e3b3f1ee-17ea-11e8-8554-ff306ced9409.png">

**Comment by maxokorokov** [comment]
FYI, importing `NgbModule.forRoot()` gives this:

<img width="918" alt="screen shot 2018-02-22 at 16 15 36" src="https://user-images.githubusercontent.com/8074436/36546513-ea3b0ede-17eb-11e8-95ff-c9f74318eefc.png">

**Comment by trumbitta** [comment]
So should we import every single module we use in the application in the `app.module.ts`?

Care to give a working StackBlitz with an application organized into feature modules?

**Comment by mboughaba** [comment]
Yes, I can confirm tree shaking works if we import single Ngb modules instead, however all the providers needed for special components such as `NgbAlert` won't get imported and then you end up importing the whole thing again 😕

**Comment by maxokorokov** [comment]
@mboughaba, @trumbitta you could either import everything, or module by module. 

If you want only the alert, then import `NgbAlertModule.forRoot()` in your main module and `NgbAlertModule` in all others where you use alert.

If you want everything, similarly import `NgbModule.forRoot()` and `NgbModule`
