### ISSUE TITLE
NgbDateStruct Compile Warning

### ISSUE THREAD

**Issue by jspizziri** [ng-bootstrap/ng-bootstrap#2174]
### Bug description:
`NgbDateStruct` isn't exported from the compiled `index.js` file, this results in compile time warnings whenever `NgbDateStruct` is imported. Ex:

```
// src/app/foo/foo.component.ts
import { Component } from '@angular/core';
import { NgbDateStruct } from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'app-foo',
  template: require('./foo.component.pug')(),
  styleUrls: ['./foo.component.scss'],
})
export class FooComponent {
    ...
}
```

```
WARNING in ./src/app/foo/foo.component.ts
92:54-67 "export 'NgbDateStruct' was not found in '@ng-bootstrap/ng-bootstrap'
 @ ./src/app/foo/foo.component.ts
 @ ./src/app/cycle/cycle.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts
```

While this doesn't cause issues during application execution, it's incredibly annoying to see at build time all the time.

### Link to minimally-working plunker that reproduces the issue:

This issue is at compile time, not at runtime. You can also see clearly that it's going to happen if you execute the following at the root of a project ng-bootstrap's installed on `cat ./node_modules/\@ng-bootstrap/ng-bootstrap/index.js`, you'll see that there's not `NgbDateStruct` being exported.

### Version of Angular, ng-bootstrap, and Bootstrap:

- Angular: `5.2.0`
- ng-bootstrap: `1.0.0`
- Bootstrap: `4.0.0`

**Comment by cristianmartinez** [comment]
Hey @jspizziri, are you using the `@angular/cli`?, in case you do, I tried to replicate but everything worked perfectly, maybe I'm missing something?

**Comment by jspizziri** [comment]
@cristianmartinez , yes I used `@angular/cli` and ejected webpack config.

**Comment by maxokorokov** [comment]
Can't reproduce with cli `1.7.1` and ng `5.2.6` and `ng eject`

And well, `NgbDateStruct` is an interface, and from what I undesrtand, it shouldn't be in the `index.js`, so that's normal. It is however present in the `index.d.ts`

You must have something else on top of standard configuration

**Comment by jspizziri** [comment]
@maxokorokov & @cristianmartinez ,

Thanks for taking a look. I'll try to create a repo where the issue is duplicated. If I don't do so in a timely manner I won't hold it against you for closing the issue. I'll update it once I have more insight for you.

Thanks!

**Comment by jspizziri** [comment]
I've done a little more digging, I believe the issue I'm experiencing is this one:

https://github.com/angular/angular-cli/issues/2034

**Comment by maxokorokov** [comment]
@jspizziri thanks for investigating, so I don't think we can do anything at this point. Feel free to reopen if you have solutions/ideas.
