### ISSUE TITLE
My code does not work since version 4.0 alpha 6

### ISSUE THREAD

**Issue by hijuuijj** [ng-bootstrap/ng-bootstrap#2175]
I have a problem with my CSS and Bootstrap 4.0 alpha 6 ; the dropdown feature doesn't work anymore.
However I have no problems with version 4.0 alpha 5... what's wrong in my CSS?

`.dropdown {
    position: relative;
    display: inline-block;
}

.dropdown-menu {
  position: absolute;
  top: 100%;
  left: 0;
  z-index: 1000;
  display: none;
  float: left;
  min-width: 10rem;
  padding: 0.5rem 0;
  margin: 0.125rem 0 0;
  font-size: 1rem;
  color: #212529;
  text-align: left;
  list-style: none;
  background-color: #fff;
  background-clip: padding-box;
  border: 1px solid rgba(0, 0, 0, 0.15);
  border-radius: 0.25rem;
}

.dropdown-menu>li>a {
display:block;
padding:3px 20px;
clear:both;
font-weight:400;
line-height:1.42857143;
color:#333;
white-space:nowrap
}

.dropdown-menu>li>a:focus,.dropdown-menu>li>a:hover {
color:#262626;
text-decoration:none;
background-color:#f5f5f5
}

.open>.dropdown-menu {
display:block
}`

Thank you.

**Comment by maxokorokov** [comment]
Is this related to ng-bootstrap at all?

If you believe that we've got a bug in this library than please provide a minimal reproduce scenario in a plunker: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

If you are unsure if this is a bug or not than please use an appropriate support channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
