### ISSUE TITLE
background shakes when use model window

### ISSUE THREAD

**Issue by LostOnEast** [ng-bootstrap/ng-bootstrap#2179]
we can see this on
https://ng-bootstrap.github.io/#/components/modal/examples

when click launch btn background shifted by several pixels

Angular: 5.0.0

ng-bootstrap: 1.0.0

Bootstrap: 4.0.0

**Comment by bastienmoulia** [comment]
@LostOnEast When the modal is open, the scroll bar of the page disappears so the content moves.

**Comment by pkozlowski-opensource** [comment]
Duplicate of #641
