### ISSUE TITLE
How to Close modal window with content from other component on click button in modal?

### ISSUE THREAD

**Issue by zverkos** [ng-bootstrap/ng-bootstrap#2183]
How to Close modal window with content from other component on click button in modal?
thx a lot

**Comment by maxokorokov** [comment]
If you believe that we've got a bug in this library than please provide a minimal reproduce scenario in a plunker: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

If you are unsure if this is a bug or not than please use an appropriate support channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
