### ISSUE TITLE
Suddenly removing inputed text to typeahead. Only for specified config NgbdTypeaheadConfig 

### ISSUE THREAD

**Issue by robzii17** [ng-bootstrap/ng-bootstrap#2185]
### Bug description:
For specific NgbdTypeaheadConfig when you try type any word from suggestion this word is auto remove before end typing this.

This is specific config:

    config.showHint = true;
    config.focusFirst = false;

(if you remove config.focusFirst = false; line this work properly).
### Link to minimally-working plunker that reproduces the issue:

I added only one line "config.focusFirst = false;" in src/typeahead-config.ts
to demo  "Global configuration of typeaheads"
Reproduces plunker:
https://plnkr.co/edit/EkTG0qW3OjBtQFGnYsq9?p=preview

Oryginal demo:
https://ng-bootstrap.github.io/app/components/typeahead/demos/config/plnkr.html

**Scenario**
Open reproduces plunker and try type for example: Alabama. 
(Word must be from suggestion states[] from src/typeahead-config.ts )
During type this word this will be remove.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
5.0.2

ng-bootstrap:
1.0.0

Bootstrap:
4.0.0

**Comment by pkozlowski-opensource** [comment]
This is a valid bug, thnx for reporting. Just sent #2198 to address this issue, should be part of a next release.

**Comment by robzii17** [comment]
Hello,
For version 1.01 and 1.02 this bug is valid.
For Mentioned typeahead config hint is doesen't display. :(
