### ISSUE TITLE
Conditional popovers

### ISSUE THREAD

**Issue by bedag-moo** [ng-bootstrap/ng-bootstrap#2188]
In #737, ngbTooltip was amended to only show a tooltip if the content is not falsy. 

I'd like ngbPopover to behave the same way (currently, it shows an empty popover in this case).

### Usecase ###

I'd like to show a different (or no) popover depending on the state of the element being hovered over. I had this working for a tooltip:

      <div [ngbTooltip]="helpKey || invalid ? tooltip : null" placement="bottom"
          triggers="hover focusin:focusout">

but the same approach with a popover

      <div [ngbPopover]="helpKey || invalid ? tooltip : null" placement="bottom"
          triggers="hover focusin:focusout">

shows an empty popover if passed null. 

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5

ng-bootstrap: 1.0.0

Bootstrap: 4

**Comment by bedag-moo** [comment]
Workaround:

      <div [ngbPopover]="popoverTemplate" placement="bottom"
           #popover="ngbPopover" container="body" triggers="manual"
           (focusin)="(helpKey || invalid) && popover.open()" (focusout)="popover.close()" 
           (mouseenter)="(helpKey || invalid) && popover.open()" (mouseleave)="popover.close()" >

**Comment by pkozlowski-opensource** [comment]
We should add proper support for disabled popovers / tooltips. Marking as a feature request.

**Comment by anbaran** [comment]
In which version is this fixed? Because I use 1.1.2 (for Angular 5) and I still observe the failure behavior i.e. popover shows up even if content is empty

**Comment by debender495** [comment]
how to enter the popover on hover through an element , do some thing on the popover (click a link) and then leave on mouseleave

**Comment by saiyaff** [comment]
> In which version is this fixed? Because I use 1.1.2 (for Angular 5) and I still observe the failure behavior i.e. popover shows up even if content is empty

In the newest version, there's a property called `disablePopover` that'd come handy.
Check on https://ng-bootstrap.github.io/#/components/popover/api
