### ISSUE TITLE
SSR Error: No component factory found for NgbTypeaheadWindow.

### ISSUE THREAD

**Issue by Stajor** [ng-bootstrap/ng-bootstrap#2190]
### Bug description:
On SSR with universal I get an error
```
Error: No component factory found for NgbTypeaheadWindow. Did you add it to @NgModule.entryComponents?
```

App module
```
...
  imports: [
    NgbModule.forRoot(),
    ...
  ],
...
```

Lazy loading module
```
...
imports: [
    ...
    NgbModule
  ]
...
```

Template
```
<input class="form-control" id="search" formControlName="search" [ngbTypeahead]="search.bind(this)" />
```
### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.6

ng-bootstrap: 1.0.0

**Comment by pkozlowski-opensource** [comment]
This, most likely, happens because of this line: https://github.com/ng-bootstrap/ng-bootstrap/blob/02f6f7a75858a294b6568fc245a59ff866c9d8fb/src/util/popup.ts#L24

It seems like trying to resolve a component in a constructor breaks ssr. Additional info in #2180

**Comment by EcoFreak** [comment]
Was this bug fixed?
I'm having troubles using a modal that is in a lazy loaded module.
