### ISSUE TITLE
Modal is not opening, however the overlay is getting added

### ISSUE THREAD

**Issue by ersurajnegi** [ng-bootstrap/ng-bootstrap#2191]
Modal is not opening properly.
below is the screen shot:
![image](https://user-images.githubusercontent.com/16935216/36656849-2594412e-1af0-11e8-9fb2-cc51df6ba0ff.png)

this is my package.json
"dependencies": {
        "@angular/animations": "^5.2.0",
        "@angular/common": "^5.2.0",
        "@angular/compiler": "^5.2.0",
        "@angular/core": "^5.2.0",
        "@angular/forms": "^5.2.0",
        "@angular/http": "^5.2.0",
        "@angular/platform-browser": "^5.2.0",
        "@angular/platform-browser-dynamic": "^5.2.0",
        "@angular/router": "^5.2.0",
        "@ng-bootstrap/ng-bootstrap": "^1.0.0",
        "angular4-slimscroll": "^1.0.5",
        "bootstrap": "^4.0.0",
        "core-js": "^2.4.1",
        "rxjs": "^5.5.6",
        "zone.js": "^0.8.19"
    },

**Comment by ersurajnegi** [comment]
have found below things which is causing the issue:
for my app when modal is opened there is no classes related to modal in the dom element. check below 
![image](https://user-images.githubusercontent.com/16935216/36657550-1689022a-1af3-11e8-8239-5faca737dcea.png)


while is demo in your hosted example, dom element is as below:
![image](https://user-images.githubusercontent.com/16935216/36657581-2ea717b6-1af3-11e8-8e4e-117c0f3c99bc.png)

Any idea why this is happening?

**Comment by pkozlowski-opensource** [comment]
@ersurajnegi we need a reproduce scenario in a plunker or similar, otherwise it is not actionable and will be closed, see: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment]
Closing as I haven't hard back from @ersurajnegi and we don't have any reproduce scenario.
