### ISSUE TITLE
New components Toast and Spinner with Bootstrap 4.2

### ISSUE THREAD

**Issue by bastienmoulia** [ng-bootstrap/ng-bootstrap#2201]
Should we consider to include components for Toast and maybe Spinner (like a modal) as Bootstrap 4.1 should integrate them?

See https://github.com/twbs/bootstrap/pull/22980 and https://github.com/twbs/bootstrap/pull/22960

**Comment by pkozlowski-opensource** [comment]
@bastienmoulia totally! I can see how JS / logic will be needed for Toast.
Not sure about spinners , though - isn't it only CSS? 

In any case, yes - we want to have those! Feel free to start prototyping if you feel like doing so!

**Comment by mauricew** [comment]
I decided to get started with an [initial implementation](/mauricew/ng-bootstrap/tree/boom-toasted) and [have modified docs up](http://ngb-toast.owlexterminators.com/#/components/toast/examples). The Bootstrap implementation isn't done yet (there's no toast-dismissible class) and this is new territory for conventions to be established, so it certainly needs work.

**Comment by Foxandxss** [comment]
Lovely that they are adding new components. I love toasts

**Comment by bastienmoulia** [comment]
@mauricew: I came to the same conclusion, the best thing to do is to work first on the toast implementation in bootstrap.

**Comment by pkozlowski-opensource** [comment]
So, it looks like those components are still work in progress on the Bootstrap side, adding links here for the reference:
* issue: https://github.com/twbs/bootstrap/issues/21769
* pr (wip): https://github.com/twbs/bootstrap/pull/22980

**Comment by kukac7** [comment]
toast is coming 😱 https://github.com/twbs/bootstrap/pull/22980#issuecomment-417582472

**Comment by benouat** [comment]
Closing as Bootstrap `4.3.1` has landed with #3220 

Closes #2945
