### ISSUE TITLE
Opening calendar from a button click that allows for date range selection

### ISSUE THREAD

**Issue by bschmitz9** [ng-bootstrap/ng-bootstrap#2202]
I am trying to add functionality for the datepicker to allow for filtering of a list of items based on the date range selected. 

I am looking to incorporate the following functionlity:

1. Have a button that says "Filter". No input.
2. User can click on that button which then opens the calendar showing 2 months - the current and next.
3. User can then select a date range.
4. The selected date range then becomes the label of the button showing the user what he or she selected. 

Is this possible? It breaks completely when I try to add the calendar on the button....?

`<button class="form-control" #dp ngModel (click)="d.toggle()" (ngModelChange)="onDateChange($event)" [displayMonths]="2" [dayTemplate]="t" ngbDatepicker #d="ngbDatepicker">
  Click Me
</button>

<ng-template #t let-date="date" let-focused="focused">
  <span class="custom-day"
        [class.focused]="focused"
        [class.range]="isFrom(date) || isTo(date) || isInside(date) || isHovered(date)"
        [class.faded]="isHovered(date) || isInside(date)"
        (mouseenter)="hoveredDate = date"
        (mouseleave)="hoveredDate = null">
    {{ date.day }}
  </span>
</ng-template>`

Is functionality possible..can someone please tell me what I'm missing here?

Thanks

**Comment by pkozlowski-opensource** [comment]
* we've got a range selection example here: https://ng-bootstrap.github.io/#/components/datepicker/examples
* please direct support questions to an appropriate channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
