### ISSUE TITLE
Focus and blur for Datepicker

### ISSUE THREAD

**Issue by ar53n** [ng-bootstrap/ng-bootstrap#2206]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

Hello, @ have one problem I want to add the possibility of DatePicker. When I clicked on input on focus event should be open NgbDatePicker. But also I want close DatePicker on blur. Separately its work good but together it does not work.
When you debug this component all work right.

### Link to minimally-working plunker that reproduces the issue:

See plunker and console errors http://plnkr.co/edit/Tamh8Eim9IFAkKubRxQP?p=preview

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5

ng-bootstrap: 1.0.0-beta.8

Bootstrap: 4.0.0-alpha.5

**Comment by maxokorokov** [comment]
Hey, @ar53n, it would work, if you remove the `(blur)` handler and leave only the `(focus)`

Current behaviour is that datepicker is focused automatically when opened, so your input will lose focus after calling `d.open()`. It will also close automatically after you've selected a date.

Now that I think of it might be kind of confusing. Are you trying to achieve something different?

**Comment by brunano21** [comment]
@maxokorokov with regards to the above is it possible to close the calendar popup if the user clicked away from the popup and the input? And the same if the user pressed Esc key or Tab move s the focus somewhere else .

**Comment by pkozlowski-opensource** [comment]
> EDIT: just saw this feature request #783

Right, the rest of it will be handled in #783. Closing as a duplicate.

**Comment by mrmashal** [comment]
I just tried the suggested solution and found that we need to also add a `[restoreFocus]="false"` to the input to prevent an infinite loop.

**Comment by julitroalves** [comment]
This way resolved for me:

`          <input
              (focus)="d.open()"
              restoreFocus="false"
              container="body"
              ngbDatepicker
              #d="ngbDatepicker"
            />
            `
