### ISSUE TITLE
Support for detect if popup is overflowing?

### ISSUE THREAD

**Issue by monti84** [ng-bootstrap/ng-bootstrap#2207]
Hey, there are any option for detecting if popup going to offscreen? Or at least dont use inline styling for the position of the popup window, so we dont have to use !important for override the popup positioning with css.
http://embed.plnkr.co/wlMEzZIuUuuqgA7dwcHM/

**Comment by pkozlowski-opensource** [comment]
Yes, use the 'placement' option:
* https://ng-bootstrap.github.io/#/components/datepicker/api
* https://plnkr.co/edit/AlyrmUylMn6SE0yIcbAU?p=preview

In the future please ask those type of support questions using a dedicated channel: https://github.com/ng-bootstrap/ng-bootstrap#getting-help
