### ISSUE TITLE
Carousel: images are left aligned and don't fill full width

### ISSUE THREAD

**Issue by dalu** [ng-bootstrap/ng-bootstrap#2211]
### Bug description:

Carousel images are left aligned and don't fill full width

### Link to minimally-working plunker that reproduces the issue:

This is the default functionality of this component

https://ng-bootstrap.github.io/app/components/carousel/demos/basic/plnkr.html

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
```
Angular CLI: 1.7.3
Node: 9.8.0
OS: linux x64
Angular: 5.2.8
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

ng-bootstrap:

1.0.1

Bootstrap:

4.0.0

**Comment by pkozlowski-opensource** [comment]
There is nothing specific to ng-boostrap here - pure Bootstrap CSS.

You can easily center your carousel with a bit of [flex utilities](https://getbootstrap.com/docs/4.0/utilities/flex/), ex.: http://plnkr.co/edit/8mC9gYVCB5x7wEkrCOpC?p=preview

Or make your carousel responsive, which is a totally different topics (but still involving just CSS).

In any case you don't want to scale / stretch images as it would result in terrible quality.

Closing as a support request.
