### ISSUE TITLE
BUG: Tooltip binding fails for dynamic content

### ISSUE THREAD

**Issue by shyamal890** [ng-bootstrap/ng-bootstrap#2215]
### Bug description:
Using dynamic content for tooltip with `ng-template` gives error with property binding being undefined.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/6BUmrZZzLRfOntT9PJYD?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.0.0

ng-bootstrap: 1.0.1

Bootstrap: 4.0.0

**Comment by pkozlowski-opensource** [comment]
This is not how things in Angular, I'm afraid. What you can access in a `<ng-template>` element are:
* lexical scope
* variables explicitly passed in as a context

In other words you can't reference variables defined _in_ a loop _outside_ of this loop. Same as in JS.
 
What you can do, though, is to move the `<ng-template>` _inside_ the `ngFor` loop like so:
http://plnkr.co/edit/lz1ahbQEkvEv8jfQQJAU?p=preview

Closing as invalid
