### ISSUE TITLE
chore: API extraction script missing features

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#222]
* [x] - extract input types from setters
* [x] - extract info about _public_ members that are: not input / outputs, not lifecycle hooks. There should be a flag to hide a given member from a doc as a "template private"

**Comment by pkozlowski-opensource** [comment]
Implementation note: we need a way of distinguishing between things that are "template private" (methods to be used in a template only) and "public" (ones that can be invoked by people having reference to an exported directive instance).

**Comment by Foxandxss** [comment]
Technically the stuff behind `private` keyword are the private things.

**Comment by maxokorokov** [comment]
Another use case to (possibly) support: default value in a private variable + accessor

```javascript
class Pagination {
  private _page = 0;
  
  /**
  * Comment goes here, but what's the default value?...
  */
  @Input() set page(value: number | string) { this.page = toInteger(value); }
}
```

**Comment by pkozlowski-opensource** [comment]
We also need start extracting APIs from regular classes / interfaces as it will be needed for:
* services (ex. `NgbModal`)
* configuration classes
* other parts of the API we are exposing to our users

**Comment by pkozlowski-opensource** [comment]
I think that we are done here, generally speaking. There are still some improvements that we could do, I will open small, more focused issues.
