### ISSUE TITLE
[ngbTabset] not set the activeId on a default item

### ISSUE THREAD

**Issue by AmineBena17** [ng-bootstrap/ng-bootstrap#2226]
### Bug description:

i'm trying to set the default active element on ngbTabset to have a list without a selected item, but the activeId is setted by default on the first element.  

### Version of Angular, ng-bootstrap, and Bootstrap:
HTML : 
```html
<ngb-tabset>
        <ngb-tab *ngFor="let item of _onlineFormList; let i=index" id="tab{{i}}">
          <ng-template ngbTabTitle>
            <div (click)="getFormContent(item.id)">
              <span>{{item.title}}</span>
            </div>
          </ng-template>
          <ng-template ngbTabContent>
           //
          </ng-template>
</ngb-tabset>
```

Angular: Angular 5

ng-bootstrap: 1.0.0-beta.3

**Comment by pkozlowski-opensource** [comment]
I'm not sure I understand... for tabset you _must_ have at least tab selected - there is no concept of "no selected tab" in tabset... unless I'm misunderstanding what you are asking for...

Could you please clarify what you are trying to do exactly, what visual input you would expect etc.?

**Comment by AmineBena17** [comment]
thank you for your response,
when i load my tablist, I do not want to have a default item selected.

**Comment by pkozlowski-opensource** [comment]
> when i load my tablist, I do not want to have a default item selected.

Once again, as far as I understand tabsets available in Bootstrap (https://getbootstrap.com/docs/4.0/components/navs/#tabs) there _must_ be at least one tab selected. 

Could you prepare a plunker with just Bootstrap HTML and CSS to illustrate what type of display you are trying to achieve?

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't heard back

**Comment by gauribane** [comment]
demonstrating the functionality. 
https://stackblitz.com/edit/angular-ettpha?embed=1&file=app/tabset-basic.ts
