### ISSUE TITLE
Modal stays open when clicking the back button

### ISSUE THREAD

**Issue by westerncj** [ng-bootstrap/ng-bootstrap#2228]
How do you close the Modal when the browsers back button is clicked? Currently it stays open.

Angular: Angular 5
ng-bootstrap: 1.0.0-beta.3

**Comment by pkozlowski-opensource** [comment]
We are not planning on adding any router interaction to modals. The reason for this is that different users want to have different modal <-> router interactions:
* some people want all modals to be closed when a route change (like in your case);
* some people want prevent route change if a modal is opened.

We can't decide for our users so we decided to not have arbitrary logic and have users code preferred  modal <-> router interactions on their end.

Closing as won't fix.

**Comment by westerncj** [comment]
Just for reference. Here is a way to close the modal when the back button is clicked.

```
import { PlatformLocation } from '@angular/common';

  constructor(
    private modalService: NgbModal,
    private location: PlatformLocation
  ) {
    // closes modal when back button is clicked
    location.onPopState(() => this.close());
  }
```

**Comment by kukac7** [comment]
@westerncj [demo link](https://stackblitz.com/edit/angular-8tsnwb), thanks!

**Comment by nikhilavula** [comment]
But how to keep it open when back button is clicked.

**Comment by dariusblajan** [comment]
@nikhilavula to my knowledge you don't need to do anything, it stays open by default.

**Comment by alham28** [comment]
Just add this code

import { PlatformLocation } from '@angular/common';  
...

constructor( 
    private platformLocation: PlatformLocation ,
    private modalService: NgbModal
)
  {
    platformLocation.onPopState(() => this.modalService.dismissAll());
  }

**Comment by skelesp** [comment]
> We are not planning on adding any router interaction to modals. The reason for this is that different users want to have different modal <-> router interactions:
> 
> * some people want all modals to be closed when a route change (like in your case);
> * some people want prevent route change if a modal is opened.
> 
> We can't decide for our users so we decided to not have arbitrary logic and have users code preferred modal <-> router interactions on their end.
> 
> Closing as won't fix.

Is this still a won't fix? The explanation is a bit easy... If there are 2 options for users, you could make behaviour configurable. Now there's only one possible behaviour and in case of modals, it's not the most user friendly option to keep it open when back is pressed (especially on mobile).

So maybe you could reconsider this one, two years later...

**Comment by junaidmehmood67** [comment]
Chat gpt will solve this
