### ISSUE TITLE
Plan for Dropdown append to body

### ISSUE THREAD

**Issue by shyamal890** [ng-bootstrap/ng-bootstrap#2232]
This feature request https://github.com/ng-bootstrap/ng-bootstrap/issues/1012 has received the most Thumbs Up and comments in the library. However, there hasn't been any update regarding the plan or even if the feature would even be implemented in the first place.

Would someone please enlighten us on whether this would be addressed in short term or the wait time for the same is around 2-3 months. 

This would be helpful to us inorder to understand if we should be looking for an alternative for `dropdown` component.

**Comment by pkozlowski-opensource** [comment]
This is definitively on our roadmap. Having said this we never communicate (and never will) any firm dates for a particular issue resolution.

The only thing I can say is that it is a high priority.

**Comment by shyamal890** [comment]
Can you please update us on the current plans for the feature?
