### ISSUE TITLE
Popover inside another popover is having arrow issue

### ISSUE THREAD

**Issue by shabbir-dhangot** [ng-bootstrap/ng-bootstrap#2234]
### Bug description:

Popover inside another popover is having arrow issue. This issue is observed after updated to latest version.

It was working previously as there is no arrow class. 

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/ev22rh6Ouve3baxHDam3?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5

ng-bootstrap: latest

Bootstrap: latest

**Comment by shabbir-dhangot** [comment]
@pkozlowski-opensource Any Update on this?

**Comment by msosa** [comment]
a potential workaround is to add `container="body"` to the 2nd tooltip. It seems to work with your plunker

http://plnkr.co/edit/ouDOvKcT4FU8FrYdIsGO?p=preview

**Comment by shabbir-dhangot** [comment]
@msosa your workaround is not working. I already tried. 

![screenshot from 2018-08-20 17-17-07](https://user-images.githubusercontent.com/8267282/44338841-e7772a00-a49c-11e8-8d6a-805fb3009948.png)


@pkozlowski-opensource Any plan to take this up?

**Comment by maxokorokov** [comment]
Setting `autoClose="outside"` on the first popover and `container="body"` on the second gives me this the correct display with the fix in #3006 and master branch. Will be released in `4.0.2`

![screen shot 2019-02-07 at 11 21 49](https://user-images.githubusercontent.com/8074436/52405002-9a2e5980-2aca-11e9-98a1-a0e0733d4ea2.png)
