### ISSUE TITLE
ngbDaterangePicker with tempate driven form not gives value in ngForm object

### ISSUE THREAD

**Issue by nirali-ga** [ng-bootstrap/ng-bootstrap#2235]

**Comment by pkozlowski-opensource** [comment]
Please follow our issue template when reporting problems: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment]
Closing as we don't have any actionable details and we haven't heard back from the opener.
