### ISSUE TITLE
TimePicker Bug, undefined changeHour(), doesn't work by default

### ISSUE THREAD

**Issue by preto89** [ng-bootstrap/ng-bootstrap#2236]
### TimePicker Bug, undefined changeHour(), doesn't work by default
I've just created a "ng new app-timer" and implemented ng-bootstrap on it.
I've imported correclty the modules but had to add NO_ERRORS_SCHEMA to it, but it still does not work, I've created a clean new app, with nothing rather than ng-bootstrap, and the code for timepicker,  every time  I change Hour or minutes by clicking the arrows I get the error below 

 **ERROR TypeError: Cannot read property 'changeHour' of undefined
at NgbTimepicker.changeHour (timepicker.js:38)**

> app.module.ts

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import {NgbModule} from '@ng-bootstrap/ng-bootstrap';
import { AppComponent } from './app.component';



@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule, NgbModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent], schemas: [NO_ERRORS_SCHEMA]
})
export class AppModule { }
```

> app.component.ts
```
import { Component, OnInit } from '@angular/core';
import { NgbTimeStruct } from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})

export class AppComponent  {
  time: NgbTimeStruct = {hour: 13, minute: 30, second: 0};
}

```

> app.component.html

```
<div>
  <ngb-timepicker [(ngModel)]="time"></ngb-timepicker>
</div>
```

### Version of Angular, ng-bootstrap, and Bootstrap:

**Angular**: 5.2.0

**ng-bootstrap**: 1.0.1 or 1.0.2 (tryied both)

**Bootstrap**: 4.0.0 or 4.0.0-beta.2 or 4.0.0-beta.3 (tryied all)

**Comment by maxokorokov** [comment]
Could you please provide a stackblitz or a plunker for reproduction? 
Pick pick one of the demos as a start, ex:

![screen shot 2018-03-20 at 15 45 03](https://user-images.githubusercontent.com/8074436/37661831-f3041c3a-2c55-11e8-8915-44c1e758fae5.png)


Please follow our issue template when reporting problems: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

**Comment by preto89** [comment]
I've fixed the problem, it was something related with the NO_ERRORS_SCHEMA definition, I removed the schema, and imported FormsModule from Angular, and for some reason it worked, be aware that FormsModule might be a required import...

**Comment by maxokorokov** [comment]
Glad to hear, @preto89

**Comment by rohanv98** [comment]
for me after  imported FormsModule from Angular also showing same error

**Comment by khaled1211** [comment]
ah no it's the same error with FormsModule?!!!why?

**Comment by ManGeelato** [comment]
I have got the same error, I have both FormsModule and ReactiveForms Module imported, then meridian is set to false but still I get the error, The arrow buttons don't work and the AM/PM button is not responsive
