### ISSUE TITLE
Problem in Modal when use webworker

### ISSUE THREAD

**Issue by Insidexa** [ng-bootstrap/ng-bootstrap#2239]
### Bug description:
Code to open modal
```
let modal: NgbModalRef = null;
    switch (this.item.type) {
      case TYPE_NUMBER:
        modal = this.NgbModal.open(NumberModalComponent);
        break;
      case TYPE_STRING:
        modal = this.NgbModal.open(StringModalComponent);
        break;
      case TYPE_ARRAY:
        modal = this.NgbModal.open(ArrayModalComponent);
        break;
    }
```
Error stacktrace
```
ERROR TypeError: Cannot read property 'body' of null
    at NgbModalStack../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-stack.js.NgbModalStack.open (webworker.bundle.js:87811)
    at NgbModal../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal.js.NgbModal.open (webworker.bundle.js:88020)
```

In webworker.bundle.js
`var containerEl = Object(__WEBPACK_IMPORTED_MODULE_3__util_util__["b" /* isDefined */])(options.container) ? this._document.querySelector(options.container) : this._document.body;`

In the last on branch condition `this._document.body`

In construct `this._document = document;` document null value injected

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: ^5.2.0

ng-bootstrap: ^1.0.1

Bootstrap: ^4.0.0 ( only css used )

**Comment by pkozlowski-opensource** [comment]
We are currently not supporting usage of ng-bootstrap components in a WebWorker as we need access to the DOM. See more discussion in #1666
