### ISSUE TITLE
Are Grid components going to be implemented at some point?

### ISSUE THREAD

**Issue by jorandradefig** [ng-bootstrap/ng-bootstrap#2244]
I've been using `Angular` for a few years and all the time I've been implementing the Grid components with classes. When I started using `React` and `Vue` last year, I noticed their implementations of `bootstrap` ([reactstrap](https://reactstrap.github.io/), [bootstrap-vue](https://bootstrap-vue.js.org/)) use the grid as components itself and that gives you a little more free time (since it is faster to implement grids).

So I'm here asking if that same idea is going to be implemented in `ng-bootstrap` at some point, and if there's nobody doing it I would like to contribute with it.

**Comment by pkozlowski-opensource** [comment]
We are not actively working on any grid implementation at the moment, as we had hard time coming up with the API that would be useful and flexible enough. As the additional background, here is how we think about components to add here:
* https://github.com/ng-bootstrap/ng-bootstrap/wiki/What-qualifies-as-a-ng-bootstrap-directive-or--component%3F
* and more specifically: https://github.com/ng-bootstrap/ng-bootstrap/wiki/What-qualifies-as-a-ng-bootstrap-directive-or--component%3F#and-all-the-rest

I'm going to close this issue as not immediately actionable.  Don't hesitate to continue the discussion in here if you would have a proposal for a grid API.
