### ISSUE TITLE
timepicker: time increase with minutesStep does not work

### ISSUE THREAD

**Issue by tibistibi** [ng-bootstrap/ng-bootstrap#2259]
### Bug description:
when i have my time picker with minutesStep like this:

    <ngb-timepicker [(ngModel)]="time" minuteStep="15"></ngb-timepicker>

clicking the increase button will increase the hours instead of the minutes. decrease seems to work.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/tpUxqHrh83e79rmEbueb?p=preview

### Version of Angular, ng-bootstrap:

Angular:
5.0.2
ng-bootstrap:
1.0.4

**Comment by pkozlowski-opensource** [comment]
It is because you were binding a _string_ to the `minuteStep` property, instead of a _number_: here is a fixed plunk: http://plnkr.co/edit/1tJgwUUYusHb3GcHdEuv?p=preview
