### ISSUE TITLE
Accordion: Action error when using same id in nested accordions 

### ISSUE THREAD

**Issue by Numalama** [ng-bootstrap/ng-bootstrap#2261]
Based on [#2250](https://github.com/ng-bootstrap/ng-bootstrap/issues/2250)
### Bug description:

I work in a nested accordion (parent and children).

I would like to have same id for all children (for css customisation).

When I click on one child, all the children react (they all open up) (cause they have the same id?!)

And if I randomize the id in the loop, it's works fine.

EXAMPLE:

```
<!-- Work Fine -->
<ngb-panel *ngFor=" let child of laptop.children; let j = index" id="child{{j}}">
<!-- Don't Work Fine -->
<ngb-panel *ngFor=" let child of laptop.children; let j = index" id="child">
```
### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/IzXW91woqAt7wQDZ3anC?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.5
ng-bootstrap: 1.0.3

Best Regard

**Comment by maxokorokov** [comment]
We'll pass on this one, id's must be unique for the document. You should use CSS classes in your case for styling

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id

Our documentation also states that ids are of type string and unique

**Comment by pkozlowski-opensource** [comment]
Having unique panel `id`s for a given accordion is also mandatory for proper accessibility support.
