### ISSUE TITLE
@since tag not displayed for directives in the API documentation

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#2269]
Ex.:
* code: https://github.com/ng-bootstrap/ng-bootstrap/blob/58eeb406ecaca819a5a7ee8a0df0e05454b1ab5e/src/dropdown/dropdown.ts#L52-L72
* demo: https://ng-bootstrap.github.io/#/components/dropdown/api#NgbDropdownAnchor

**Comment by maxokorokov** [comment]
@pkozlowski-opensource will take a look. Also you should have put `1.1.0`, not `1.0.0` for new features in the last release...

**Comment by pkozlowski-opensource** [comment]
>  Also you should have put 1.1.0, not 1.0.0 for new features in the last release...

Oh, good catch @maxokorokov - just fixed it, thnx!

**Comment by maxokorokov** [comment]
It turns out I completely forgot to add `since` display to directives, services, etc... Only deprecation :)
