### ISSUE TITLE
Locking angular dependency to the patch version

### ISSUE THREAD

**Issue by jdhines** [ng-bootstrap/ng-bootstrap#2271]
### Bug description:
Is it not bad practice to lock down the angular dependency to a patch version? I have an issue where I'm using a package created internally in my company that pulls in Angular 5.0.0 (and a bunch of other packages to make for a reusable all-in-one app development package), and I can't change the version, but ng-bootstrap since 1.0.0-beta.7 requires at least 5.0.2 as a peer dependency.

From the [npm docs](https://nodejs.org/en/blog/npm/peer-dependencies/#using-peer-dependencies):

> One piece of advice: peer dependency requirements, unlike those for regular dependencies, should be lenient. You should not lock your peer dependencies down to specific patch versions. 

Maybe I just don't know enough about package management (likely) to resolve this, but I don't see how I can resolve this peer dependency when I'm locked down to version 5.0.0 of Angular.

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 5.0.0
ng-bootstrap: 1.1.0

**Comment by pkozlowski-opensource** [comment]
First of all, we are not "locking" anything - our package.json states `"@angular/core": "^5.0.2"` which basically mean that we will work with _any_ Angular version that is:
* grater than `5.0.2`
* doesn't have breaking changes (`^` modifier)

> but ng-bootstrap since 1.0.0-beta.7 requires at least 5.0.2 as a peer dependency.

This is correct. We need _at least_ `5.0.2` as there were bugs in `5.0.0` and `5.0.1` that were breaking some of the ng-bootstrap functionality.

> One piece of advice: peer dependency requirements, unlike those for regular dependencies, should be lenient. You should not lock your peer dependencies down to specific patch versions.

We are _very_ lenient here - we are saying that we can work with _any_ Angular version from `5.0.2` till `6.0.0`. If your company's package specifies peer dependency on `5.0.0` _only_ than this would be very restrictive.

I'm going to close this issue as I believe that  our package.json is correct and I don't see what we could change. Happy to provide more info if needed.

**Comment by jdhines** [comment]
Thanks for the info; I agree on closing.
