### ISSUE TITLE
[Carousel] Hide indicators and navigation arrows if only one slide

### ISSUE THREAD

**Issue by wilhelmhb** [ng-bootstrap/ng-bootstrap#2274]
### Feature description:
Allow the user to hide the navigation items when the carousel contains only one slide

I have a carousel that can contain 1 or more slides. It feels weird to display navigation items when navigation is impossible.

**Comment by wilhelmhb** [comment]
The tests seems to fail only due to Microsoft Edge and nbg-datepicker.
I can't test on the first one, and haven't touched the second.
@pkozlowski-opensource: do you have any hint as to where the issue could be ?

**Comment by giampierobono** [comment]
Should the carousel disable the navigation arrows automatically in case of only one slide or the dev himself should be able to hide them if he wants?

**Comment by pkozlowski-opensource** [comment]
> Should the carousel disable the navigation arrows automatically in case of only one slide or the dev himself should be able to hide them if he wants?

Valid point @giampierobono - I think it would be more flexible is a dev is explicitly setting "no navigation controls" property.

**Comment by giampierobono** [comment]
@pkozlowski-opensource I totally agree. In this way the component will keep the default (or previous) behavior, allowing this small customization.

**Comment by wilhelmhb** [comment]
@pkozlowski-opensource @giampierobono I wanted to avoid changing the current behavior (I don't want people to wonder why things are not displayed as before), so I added a parameter for the dev to choose the behavior ;)
