### ISSUE TITLE
Auto format date manual input

### ISSUE THREAD

**Issue by sebius8780** [ng-bootstrap/ng-bootstrap#2276]
Hello team !

I've search and didn't find a way to be able to help the user enter a date manually on date-picker like you have the date format like : dd/MM/yyyy

The user enters 25 and automatically the input add the '/'.
I tried to find a hook between string to date conversion ( I know about the uibparser but not really sure it should be used for this ).

I have seen in the code source that hook might already been there, but not available for us to play with ?

Thanks for the help !

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 1.6.8

ng-bootstrap: 2.5

**Comment by aadii104** [comment]
I am also looking for something same functionality.
please help!

**Comment by maxokorokov** [comment]
This is the project for Angular 2+
Please look at https://github.com/angular-ui/bootstrap for Angular 1.6

**Comment by sebius8780** [comment]
woupps ... sorry !

**Comment by aadii104** [comment]
@sebius8780 could you please the code for the date input for the need you stated in your question/request?

**Comment by vbodanki** [comment]
I am on latest version of ng-bootstrap 3.2. I am having similar issue with manual input entry. I added NgbDateParserFormatter adapter to format date to mm/dd/yyyy. It works great with mouse selection, but manual valid date entry is making input control ng-invalid & ng-dirty.  Please help me with the solution.

version of angular/cli :    6.2.1

Here is ParserFormatter:
```
import { NgbDateParserFormatter, NgbDateStruct } from '@ng-bootstrap/ng-bootstrap';
import { Injectable } from '@angular/core';
import { isNumber, toInteger, padNumber } from 'app/shared/classes/utilities/number';

@Injectable()
export class NgbDateCustomParserFormatter extends NgbDateParserFormatter {
  parse(value: string): NgbDateStruct {
    if (value) {      
      const dateParts = value.trim().split('-');
      if (dateParts.length === 1 && isNumber(dateParts[0])) {
        return { month: null, day: toInteger(dateParts[0]), year: null };
      } else if (dateParts.length === 2 && isNumber(dateParts[0]) && isNumber(dateParts[1])) {
        return { month: toInteger(dateParts[1]), day: toInteger(dateParts[0]), year: null };
      } else if (dateParts.length === 3 && isNumber(dateParts[0]) && isNumber(dateParts[1]) && isNumber(dateParts[2])) {
        return { month: toInteger(dateParts[1]), day: toInteger(dateParts[0]), year: toInteger(dateParts[2]) };
      }
    }
    return null;
  }

  format(date: NgbDateStruct): string {
    return date ? `${isNumber(date.month) ? padNumber(date.month) : ''}/${isNumber(date.day) ? padNumber(date.day) : ''}/${date.year}` : '';
  }
}

```

.ts code:

```
 this.form.controls['saleDate'].valueChanges
      .pipe(
        filter(date => !!date),
        distinctUntilChanged(),
        takeUntil(this._isDestroyed$)
      )
      .subscribe(
        (calendarDate: Moment) => {
          if (!calendarDate) {
            return;
          }

          if (moment.isMoment(calendarDate) && calendarDate.isValid()) {
            this.saleDateChange$.next(calendarDate);
          }
        },
        () => {}
      );
```
