### ISSUE TITLE
Datepicker: (dateSelect) not firing

### ISSUE THREAD

**Issue by ryu323** [ng-bootstrap/ng-bootstrap#2278]
### Bug description:

Regarding:
https://ng-bootstrap.github.io/#/components/datepicker/api#NgbInputDatepicker

Not sure if I'm missing something, but (dateSelect) does not seem to fire when a date is selected from the datepicker.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/tPNBc3ROOD2Cna7no6Ro?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.9

ng-bootstrap: 1.1.0

Bootstrap: 4.0.0

**Comment by maxokorokov** [comment]
Thanks, this is the case when all unit tests are fine, but integration is missing...

Both `(ngModelChange)` and `(selectDate)` are emitted, but looks like input datepicker first gets the model change and kills the datepicker before receiving the select event. Will see how to fix soon.
