### ISSUE TITLE
Accordion: maintaining active panel index

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#228]
In the spirit of [a solution discussed for tabs](https://github.com/ng-bootstrap/core/issues/215#issuecomment-227084987) we should decide on the best course of action for accordion. 

Normally we should use the same mechanism as for tabs but the problem is that we might have multiple active panels (in accordion that supports multiple open panels at once).

**Comment by wesleycho** [comment]
I think for the accordion, it could make sense to have a getter that returns an array of the panel states
