### ISSUE TITLE
Bug: RangePicker end date not set on click

### ISSUE THREAD

**Issue by shyamal890** [ng-bootstrap/ng-bootstrap#2280]
### Bug description:
If a date in range picker mode is double clicked, the expectation is that both the `start date` and the `end date` would be set to the day clicked. Only the `start date` is set.

### Link to minimally-working plunker that reproduces the issue:
https://stackblitz.com/angular/xamnxlaknpgb?file=app%2Fdatepicker-range.ts
- Select the same date twice, `start date` will set but not the `due date`.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.5

ng-bootstrap: 1.1.0

Bootstrap: 4

**Comment by pkozlowski-opensource** [comment]
@maxokorokov I've just checked and indeed some date-range pickers behave this way. In fact it is more flexible than this: for example https://www.booking.com selects a range of 1 night (2 days) on double-click. So double-click behaviour should be probably configurable. Maybe we should pass some flag to date selection event?

Marking as a feature request.

**Comment by maxokorokov** [comment]
I need some clarification, please.
It seems to me that what you're talking about has nothing to do with the library, but the demo, if I'm correct.

Changing 
```js
else if (this.fromDate && !this.toDate && after(date, this.fromDate))
``` 
to 
```js
else if (this.fromDate && !this.toDate && (after(date, this.fromDate) || equals(date,this.fromDate))
```
 in the `onDateSelection()` method would do the trick?

**Comment by shyamal890** [comment]
@maxokorokov  Hmm, actually (select) works as expected but there's an issue with `ngModel` and `ngModelChange`.

Checkout this stackblitz example: https://stackblitz.com/edit/ng-bootstrap-rangepicker-double

**Comment by maxokorokov** [comment]
@shyamal890, well that's normal, because the model doesn't change. That's why you have `(select)` event, it would be triggered regardless.
