### ISSUE TITLE
Tootltip Position

### ISSUE THREAD

**Issue by rjpatil** [ng-bootstrap/ng-bootstrap#2282]
i am using ngbTooltip in angular 2 project in Tab section "mat-tab-group " in body content.
So that tootltip is goes behind of other div.

**Comment by pkozlowski-opensource** [comment]
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't heard back with the reproduce scenario.
