### ISSUE TITLE
Datepicker should allow formatting of the date with the Angular DatePipe

### ISSUE THREAD

**Issue by Arackow** [ng-bootstrap/ng-bootstrap#2292]
The Datepicker should use the Angular DatePipe formatter to allow for custom formats displayed in the input box. Custom date formats are very important to anyone doing i18n work since not everyone reads dates the same. Even outside of i18n, not everyone wants a date format in yyyy-mm-dd.

I found a workaround for the time being but it is extending the NgbDateParserFormatter and not very elegant.

Angular: 5.2.2

ng-bootstrap: 1.1.1

Bootstrap: 4.0.0

**Comment by pkozlowski-opensource** [comment]
pipe only works _one_ way (model -> string) why we also need to support other direction (string -> model). So a pipe alone is not enough and this is why we've got `NgbDateParserFormatter` which is the way to go.

Sorry to hear that you don't find it "not very elegant" - care to elaborate with more concrete concerns?

In any case, pipe is not enough, so I'm going to close this one for now. Happy to re-open if / when you can suggest how a pipe alone could address the concerns I've raised.

**Comment by Arackow** [comment]
I'm sorry if I came off as a jerk yesterday... wasn't my intention.

By the datePipe, I meant more like a property on the element itself, lets call it "displayFormat" for the sake of this conversation. displayFormat would take a string that mimics the datePipe formats Angular uses. In the background it does the parser and formatting automatically so that you can still get the ngbDateStruct out of it but the display it ends up showing the user would be something different in general.

So as an example: 
```
<form class="form-inline">
  <div class="form-group">
    <div class="input-group">
      <input class="form-control"
             name="dp" [(ngModel)]="model" ngbDatepicker #d="ngbDatepicker"
             dateFormat="dd-MMM-yyyy">
      <div class="input-group-append">
        <button class="btn btn-outline-secondary" (click)="d.toggle()" type="button">
          <img src="img/calendar-icon.svg" style="width: 1.2rem; height: 1rem; cursor: pointer;"/>
        </button>
      </div>
    </div>
  </div>
</form>
```

Under the hood the component should be smart enough to take the date from an NgbDateStruct (ex: `{day: 01, month: 01, year: 2018}` and reformat it following the rules here: https://angular.io/api/common/DatePipe (ex: `01-Jan-2018`)

if the user wants to do something extra that isnt supported there, then sure the idea of the NgbDateParserFormatter is awesome.... but I would think this would be a good default usage of the NgbDateParserFormatter. I might not fully grasp the work involved to do something like that but i've used a bunch of datepickers in the past, and they all allow some basic initialization option for the display format.

Again sorry if you thought I was rude before.

**Comment by wallaceturner** [comment]
my 2 cents... it could definitely be made a little easier. Its a lot of work to change the format when you want to include the month name instead of the number.
I understand the point about parsing it back however you could in theory support all the formats that angular can already parse from strings out of the box.

**Comment by brazorf** [comment]
Im still new to Angular2+ so i'm not sure whether this is a good approach or not. However,  this is how i'm doing this:

```html
{{ yourDate | ngbDate | date }}
```

where ngbDate is this Pipe here:

```typescript
@Pipe({name: 'ngbDate'})
export class NgbDatePipe implements PipeTransform {
    transform(value: NgbDate): Date {
        return new Date(value.year, value.month, value.day);
    }
}
```

Hope it helps.

**Comment by clau007** [comment]
> Im still new to Angular2+ so i'm not sure whether this is a good approach or not. However, this is how i'm doing this:
> 
> ```
> {{ yourDate | ngbDate | date }}
> ```
> 
> where ngbDate is this Pipe here:
> 
> ```ts
> @Pipe({name: 'ngbDate'})
> export class NgbDatePipe implements PipeTransform {
>     transform(value: NgbDate): Date {
>         return new Date(value.year, value.month, value.day);
>     }
> }
> ```
> 
> Hope it helps.

Sidenote: you should use value.month - 1, since javascript counts months from 0 to 11, lol.
