### ISSUE TITLE
Feature Request: Range Picker

### ISSUE THREAD

**Issue by shyamal890** [ng-bootstrap/ng-bootstrap#2295]
Bootstrap in version 4.1.1 released range picker. Would be great component addition to ng-bootstrap.

**Comment by pkozlowski-opensource** [comment]
Provided that you are talking about https://getbootstrap.com/docs/4.1/components/forms/#range-inputs I'm not sure what Angular-specific behaviour we could add here. From what I can tell this is just `<input type="range">` (already supported in Angular) and some CSS.

In the spirit of  https://github.com/ng-bootstrap/ng-bootstrap/wiki/What-qualifies-as-a-ng-bootstrap-directive-or--component%3F I'm not sure what added value ng-bootstrap could bring here... Care to elaborate?

**Comment by pkozlowski-opensource** [comment]
Closing based on https://github.com/ng-bootstrap/ng-bootstrap/issues/2295#issuecomment-380230801
