### ISSUE TITLE
Upgrade to Boostrap 4.1 -> dropup position bug

### ISSUE THREAD

**Issue by bastienmoulia** [ng-bootstrap/ng-bootstrap#2297]
### Bug description:

I try to use ng-bootstrap with the last version of Bootstrap (4.1) and I've found a bug with the dropup.
The css changed [here](https://github.com/twbs/bootstrap/blob/14f712601edf87aa4e2e65243775682b1270124e/scss/_dropdown.scss#L46) and the dropup position is not correct. I don't try for left/right. Dropdown is OK.

### Link to minimally-working stackblitz that reproduces the issue:

https://stackblitz.com/edit/ngb-bootstrap41-dropup

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5 and 6

ng-bootstrap: 1.1.1 and last commit bc79f9b548308947dc9730efee75ca9ea0085a66

Bootstrap: 4.1

**Comment by pkozlowski-opensource** [comment]
This seem to be an offending rule: 

```
.dropup .dropdown-menu {
    ...
    bottom: 100%;
   ...
```

Not sure what would be the best fix, atm...

**Comment by pkozlowski-opensource** [comment]
Not sure if the equivalent of what Bootstrap does would do the trick?

```
// When enabled Popper.js, reset basic dropdown position
// stylelint-disable no-duplicate-selectors
.dropdown-menu {
  &[x-placement^="top"],
  &[x-placement^="right"],
  &[x-placement^="bottom"],
  &[x-placement^="left"] {
    right: auto;
    bottom: auto;
  }
}```

**Comment by pkozlowski-opensource** [comment]
@bastienmoulia here is a proposal for a fix: #2313 - review / comments would be appreciated.

**Comment by ivanpadavan** [comment]
Just removing inline style `top: 20%` makes it work perfectly

**Comment by bastienmoulia** [comment]
@pkozlowski-opensource It's working!
