### ISSUE TITLE
ng bootstrap typehead pass additional parameters

### ISSUE THREAD

**Issue by HRSamy** [ng-bootstrap/ng-bootstrap#2298]
### Bug description:
I'm not able to pass parameters in ngbTypeahead method. Please refer the link provided below. This query is been open for sometime. Is there any way to reach out help forum

### Link to minimally-working plunker that reproduces the issue:
Please refer :https://stackoverflow.com/questions/48450974/angular-4-ng-bootstrap-typehead-pass-additional-parameters

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:4

ng-bootstrap:1.0.0

Bootstrap:4.0.0-beta.2

**Comment by pkozlowski-opensource** [comment]
You can use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind to create a new function with additional arguments bound

Closing as a suport request.
