### ISSUE TITLE
Change all method from private to protected to allow inheritance

### ISSUE THREAD

**Issue by Serginho** [ng-bootstrap/ng-bootstrap#2300]
### Bug description:
Sometimes we want to extend any of classes to modify the behavior, in my case i need to add an event beforeClose in the modal component, but I run into all methods are private.

It's very easy to do it, it don't make breaking changes and make you library more flexible.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.9

ng-bootstrap: 1.1.1

Bootstrap: 4.0.0-beta.2

**Comment by pkozlowski-opensource** [comment]
We are definitively _not_ going to change all the private methods for protected. Protected fields _are_ part of the class contract so all of the sudden _all_ our fields would be part of the public contract. This would explode our contract surface and would make it next to impossible to do any refactorings.

Designing for extensibility _is_ designing a public API and we are not taking this tasks lightly. If you've got a concrete use-case where you think that a given method should be protected, please open a separate issue clearly describing your use-case. Then we can consider enlarging the API on the case-by-case basis.

In any case we are _not_ going to do blind private -> protected fields conversion, please open more focused issues with a precise use-case.
