### ISSUE TITLE
ngbTypeahead focus first issue  - once highlighted item index changed, it's not focusing on first item after search

### ISSUE THREAD

**Issue by patelshabana** [ng-bootstrap/ng-bootstrap#2303]
Typeahead is not focusing on the first item 

![image](https://user-images.githubusercontent.com/38217813/38639039-127050c6-3d9e-11e8-8c23-b24a06e93919.png)

when we mouseover/keydown on typeahead item, it changes the current index.  After changing  the focus, it's not focusing on default first item. Can someone please check this issue?

![image](https://user-images.githubusercontent.com/38217813/38638962-dd6d1396-3d9d-11e8-9f5d-cbd821c06d46.png)

**Comment by pkozlowski-opensource** [comment]
> Can someone please check this issue?

Sure, as long as you follow our issue template: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

As a very minimum we need a minimal reproduce scenario in a plunker or similar, otherwise it is not actionable and will be closed.

**Comment by patelshabana** [comment]
you can reproduce this issue from bootstrap demo page itself. That's why I uploaded images from bootstrap site. 

https://ng-bootstrap.github.io/app/components/typeahead/demos/basic/plnkr.html

**Comment by pkozlowski-opensource** [comment]
Oh, I see! This is a valid bug, thnx for reporting!

**Comment by patelshabana** [comment]
May I know when it will get resolve?

**Comment by pkozlowski-opensource** [comment]
@patelshabana it was fixed in 1.1.2 (just released)

**Comment by patelshabana** [comment]
@pkozlowski-opensource Thanks!
