### ISSUE TITLE
Typeahead crashes on v2.0.0-alpha.0 TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by WindSaber** [ng-bootstrap/ng-bootstrap#2309]
### Bug description:
Today I install this amazing library, but when I tried to use typeahead I got next error at browser console:
```
CapturarComponent.html:17 ERROR TypeError: Object(...) is not a function
    at new NgbTypeahead (typeahead.js:52)
    at createClass (core.js:12449)
    at createDirectiveInstance (core.js:12284)
    at createViewNodes (core.js:13742)
    at createEmbeddedView (core.js:13619)
    at callWithDebugContext (core.js:15056)
    at Object.debugCreateEmbeddedView [as createEmbeddedView] (core.js:14368)
    at TemplateRef_.createEmbeddedView (core.js:11694)
    at ViewContainerRef_.createEmbeddedView (core.js:11406)
    at NgTemplateOutlet.ngOnChanges (common.js:3482)
```

### Link to minimally-working plunker that reproduces the issue:
Plunker demo was not possible due to when I tried to reproduce the issue I realized that my local version was v2.0.0-alpha.0 and the plunker one is v1.1.1
![image](https://user-images.githubusercontent.com/3753174/38695578-5003da98-3e52-11e8-897d-6fef8882360c.png)

By the way,  installed this library by using:
`npm install --save @ng-bootstrap/ng-bootstrap`
And I got an alpha version? Was that purposely? Wouldn't be better to fix documentation to download stable or unstable versions?

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular 5.2.0
ng-bootstrap: v2.0.0-alpha.0
Bootstrap:4.1.0

**Comment by WindSaber** [comment]
Just to discard another problem.
I unisntalled v2.0.0-alpha.0 and installed v1.1.1, the result was succesful

**Comment by pkozlowski-opensource** [comment]
`v2.0.0-alpha.0` is not meant to be used just yet as it needs specific versions of Angular 6.rc.x and RxJS 6.x. So unless you use _exact_ package versions [that we are using](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/package.json#L49-L52), things won't work.

In short:  `v2.0.0-alpha.0` is highly experimental and won't work with Angular 5.x. Stick with v1.1.1 for now, we will be releasing 2.0.0 when Angular 6.0.0 is out.

**Comment by WindSaber** [comment]
@pkozlowski-opensource  That makes sense to me, what (in my opinion) should be expected is to **indicate this on documentation** in order to prevent compatibility problems.

I didn't manually download v2.0.0, I just follow indications:

![image](https://user-images.githubusercontent.com/3753174/38698372-6a9541f0-3e5a-11e8-973a-167bb747b432.png)

**Comment by pkozlowski-opensource** [comment]
Normally you should have gotten message from npm / yarn warning about incompatible versions.

**Comment by bastienmoulia** [comment]
The `v2.0.0-alpha.0`should be published on NPM with another tag than `latest`, like `next` to avoid download it with `npm install @ng-bootstrap/ng-bootstrap`.

**Comment by pkozlowski-opensource** [comment]
@bastienmoulia you are right - will cut a new release with proper next / last pointers later today. Thnx!

**Comment by pkozlowski-opensource** [comment]
It should be fixed on npm now
