### ISSUE TITLE
Typeahead - Setting a default value

### ISSUE THREAD

**Issue by abelardolg** [ng-bootstrap/ng-bootstrap#2326]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
I can't pass any default value

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:  5.2.10

ng-bootstrap: 1.1.2

Bootstrap: 4.1.0

**Comment by pkozlowski-opensource** [comment]
> I can't pass any default value

Well, this is hardly a description we could act upon, please follow our issue template.

**Comment by abelardolg** [comment]
I would like to pass a value to set it as the default value to this component. 

You can see it here:
[https://github.com/abelardolg/typeaheadBootstrap](url)

**Comment by abelardolg** [comment]
What plunkr do you need if I can't reproduce this issue????
I'm requesting a new feature, not I'm informing you about a bug.

**Comment by pkozlowski-opensource** [comment]
> What plunkr do you need if I can't reproduce this issue????
I'm requesting a new feature, I'm not informing you about a bug.

It is not clear _at all_ from your issue that it is a feature vs. a bug. And it is not clear to me:
* what new feature you are requesting;
* what do you mean by "default value"

Please, help us to help you - we need a _clear_ and _detailed_ description of what you are trying to achieve and what you are missing.

**Comment by abelardolg** [comment]
The new feature I am requesting is the possibility to pass via parameter a value to set as default value of this component. 

For example:
<app-mytest
[items]="items"
[valor]="'1'" <- Default value I would like to pass
[numMaximoItems]="5"
[showListOnFocus]="true"
[isRequired]="true"
(valorAlUsuario)="valorUsuario($event)"></app-mytest>

Inside the app-mytest I declared a @Input() valor to set as default value to this component:
app-mytest:
<input
    #instance
    [(ngModel)]="model"
    id="typeahead-basic1"
    type="text"
    [showHint]="true"
    class="form-control"
    [ngbTypeahead]="search2"
    [resultFormatter]="formatter"
    [inputFormatter]="inputFormat"
  (focus)="open($event)"
  (blur)="valorAEnviar()"
  (selectItem)="selectedItem($event)"/>


A default value is an item of the list which appears previously selected when the component is showed

**Comment by pkozlowski-opensource** [comment]
You can set a _model_ value (I guess this is what you mean by "default"), check this example: https://stackblitz.com/edit/angular-6iuqug?file=app/typeahead-basic.ts

> A default value is an item of the list which appears previously selected when the component is showed on init.

This is not how we intend the typeahead to work. What you are proposing would make sense in select-like components, but not in the general autocomplete one.

**Comment by abelardolg** [comment]
Well, I see a typeahead as an input-select component. As select which is, you can select a value and put it as selected value in the input field.
Thanks for your time. :) 👍

**Comment by pkozlowski-opensource** [comment]
Closing based on https://github.com/ng-bootstrap/ng-bootstrap/issues/2326#issuecomment-382775784 - no intention to support for this scenario for now.

**Comment by manufabri91** [comment]
@pkozlowski-opensource I need to set value programmatically to the typeahead since in our scenario the modal that contains the typeaheads works both as add and edit. So, in case of an edit the field will already have a previous value, which the user occasionally will need to change. Any chance to add this feature?

**Comment by 25to8** [comment]
@manufabri91, for reactive forms, you can use the `setValue` method of your control with Typehead directive. Maybe that what you need.

**This case works for me**
_In component template_
`
<input
    id="typeahead-focus"
    type="text"
    container="body"
    [editable]="true"
    [formControl]="control" // or [controlName]="control-id"
    [ngbTypeahead]="searchEntries"
    [inputFormatter]="inputFormatter"
    [resultFormatter]="resultFormatter"
    (selectItem)="updateFilter($event)"
    #instance="ngbTypeahead">
`

_In component class_
`
this.control.setValue(['value', 'label']);
// or
this.reactiveFormGroup.get('control-id').setValue('new value')
`

**Comment by asad-c** [comment]
>  [formControl]="control" // or [controlName]="control-id"

Could you please post your ts file as I'm unable to get this to work.

**Comment by asad-c** [comment]
I figured out how to get this working with a reactive form. My issue was that calling setValue() on the reactive form control didn't seem to be working because I had an input formatter. I was passing a simple string to setValue() but the input formatter was expecting an object with specific properties. Once I called setValue with the correct object format it worked.

**Comment by antal-horvath** [comment]
Wow, thanks for the comment @asad-c. This was unexpected to me.
