### ISSUE TITLE
Typeahead - Arrow down key should show the complete list

### ISSUE THREAD

**Issue by abelardolg** [ng-bootstrap/ng-bootstrap#2329]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

[x] Requesting new feature

### New feature description:
When I press the arrow down key, the list of items should be displayed

### Link to minimally-working plunker that reproduces the issue:
You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

At your examples:
https://ng-bootstrap.github.io/#/components/typeahead/examples
focus on typeahead and press arrow down key. The list doesn't appear.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.10

ng-bootstrap: the latest version

Bootstrap: 4.0.0

**Comment by abelardolg** [comment]
I know how to open upon focus event:
`(focus)="open($event)"`
but I don't know how to invoke this action with no have the $event parameter.
Some idea?

**Comment by pkozlowski-opensource** [comment]
>  I don't know how to invoke this action with no have the $event parameter.

Keydown and focus and are both DOM events so there is no difference here - access to the `$event` would be exactly the same.

We are going to make this scenario a bit simpler to handle in #2318. Closing as already supported with simplifications coming in #2318
