### ISSUE TITLE
TimePicker - input type number

### ISSUE THREAD

**Issue by andrepaulo** [ng-bootstrap/ng-bootstrap#2334]
Hi,

As timepicker should never accept characters, if I'm not mistaken, why not set the input being used to [type="number"], so we could use the advantage of browsers to block non-numerical characters input?

Is it a feasible request?

**Comment by LoneyGG** [comment]
@andrepaulo is right, it make sno sense having it as a type=number

**Comment by metodribic** [comment]
@pkozlowski-opensource Can you explain why would this be a breaking change?

**Comment by denkomanceski** [comment]
Any progress on this? It really ruins the UX on mobile.. the user needs to switch the keyboard to number twice (once for hour, once for minute)

**Comment by premalatha-bv** [comment]
Any update on this?

**Comment by w-veltman** [comment]
Is there any update on this?

**Comment by kottartillsalu** [comment]
Any news on this?

**Comment by maxokorokov** [comment]
While we have to support IE, we can't do `<input type="number">`. It also has some problems in Firefox

As a compromise #3247 adds numeric keyboard on mobile and limits input to numbers only
