### ISSUE TITLE
Dropdown and tooltip make IE and Edge freeze

### ISSUE THREAD

**Issue by cmckni3** [ng-bootstrap/ng-bootstrap#2342]
### Bug description:

Clicking a dropdown or hovering over a tooltip element causes IE and Edge to freeze with 100% CPU usage.

### Link to minimally-working plunker that reproduces the issue:

TODO: Stackblitz reproduction

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.9

ng-bootstrap: 1.1.2

Bootstrap: 4.0.0

**Comment by cmckni3** [comment]
Will reproduce in Stackblitz if/when I can

**Comment by pkozlowski-opensource** [comment]
@divdavem could you please check if this happens on our demo page with IE / Edge? I'm surprised since we haven't heard any similar issue reports and I would expect that more people would raise issues if things are completely broken on IE / Edge. 

@cmckni3 we need a minimal reproduce scenario for the reasons outlined here: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by divdavem** [comment]
@pkozlowski-opensource I have just tried on our demo page for [dropdowns](https://ng-bootstrap.github.io/#/components/dropdown/examples) and [tooltips](https://ng-bootstrap.github.io/#/components/tooltip/examples) with IE 11 (11.1029.15063.0) and Edge (Microsoft Edge 40.15063.674.0, Microsoft EdgeHTML 15.15063) on Windows 10, but I was not able to reproduce the issue.
Those sample pages work fine, which is good, but it does not help to solve this issue. We need a precise reproduce scenario to be able to investigate.

**Comment by pkozlowski-opensource** [comment]
@divdavem thnx so much.

@cmckni3 we haven't heard back from you with a reproduce scenario and based on the [above comment](https://github.com/ng-bootstrap/ng-bootstrap/issues/2342#issuecomment-386278681) we can't reproduce locally. Given this we can progress on this report so I'm going to close this issue now as we need to "see" bugs before we can fix those:  https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

Happy to re-open if / when you've can provide a minimal reproduce scenario.

**Comment by ThomasHandwerker** [comment]
I had the same problem in my Angular application using ng-bootstrap (v2.0.0). The IE11 is freezing when dropdown open is triggered or when mouse hover on popovers.

I tried the official demo site and everything was working fine. I created a small minimal Angular application with all my third-party dependencies. Everything was working fine.

Finally I realised that we use some custom "polyfills" for IE11 (see `polyfills.ts` in your Angular app).
We use the `intersection-observer` package ([link](https://www.npmjs.com/package/intersection-observer)) which causes the described problems in IE11.

@cmckni3 This might help you investigating your problems.

**Comment by cmckni3** [comment]
That’s the symptoms but I’m not using observers or the observer polyfill. Using theES6, ES7, and animation polyfills.

**Comment by dominikg** [comment]
@pkozlowski-opensource 

possibly related issue: 
ag-grid/ag-grid-angular#221

the issue has a stackblitz that freeze firefox 60.0.2 on my mac when opening the dropdown
https://angular-ng-bootstrap-ag-grid-fail.stackblitz.io
https://stackblitz.com/edit/angular-ng-bootstrap-ag-grid-fail

**Comment by dominikg** [comment]
I had a closer look and in my case it seems to boil down to an infinite loop of
zone onstable -> dom manipuation -> mutation observer -> zone unstable -> zone onstable -> dom manipulation
a minimal reproduction of the loop without ng-bootstrap / ag-grid can be found here

https://stackblitz.com/edit/angular-4abdwy

In my case the MutationObserver is added by ag-grid, the dom manipulation in zone onstable happens in [dropdown.ts] (https://github.com/ng-bootstrap/ng-bootstrap/blob/67a568d86a94ee31d74be8062522b86a6900d849/src/dropdown/dropdown.ts#L148)

Some Ideas to improve/resolve this on ng-bootstraps side:

NgZone.onstable 
- should only be subscribed to after the element that should be positioned dynamically has been rendered first
- should be unsubscribed from when the element is no longer rendered (or invisible)
- handlers subscribed to onstable should avoid causing another onstable. So dom changes should be minimized to those that lead to an actual rendering change (in case of dropdown, don't remove/add dropdown or dropup class unless value of placement actually changed) and util/positioning should not set targetelement.style.top/left unless the new values actually differ from the current ones 

This should leave the dom untouched after the dropdown has opened, so MutationObserver does not observe anything and ngzone stays stable.

**Comment by Burn-E99** [comment]
I am here to second the issue of IE getting stuck in an infinite loop while using the ng-bootstrap dropdown.  This probably is very closely related to @dominikg's findings as I am also using ag-grid and ng-bootstrap.  I found that this loop can not only happen on the dropdown menu, but also happens on the popovers.  This issue may also be causing the datepicker to open/select slowly, but I cannot tell if that is ng-bootstrap or wonderful IE that is making it run sluggish.

@pkozlowski-opensource Any insight on if/(hopefully) when this will get fixed, as this is a major breaking bug for my app since it must be able to run in IE.

**Comment by pkozlowski-opensource** [comment]
@Burn-E99 we are not planning to "fix" anything as we don't believe that ng-bootstrap is a culprit here _and_ a solution exists on the ag-grid / polyffil side - see discussion in #2522. In any case let's use #2522 for any further discussion related to the topic.

**Comment by cmckni3** [comment]
Well, my issue didn't involve `ag-grid`. Happened in a vanilla [Bootstrap](https://getbootstrap.com/) navbar dropdown and vanilla Bootstrap tooltip.

For me, the tough part is reproducing it because:

1. I develop on Mac
2. stackblitz runs the code through ng cli (was experiencing the issue in production-like environments, i.e. builds generated by `ng build --prod`)
