### ISSUE TITLE
Logo design for bootstrap

### ISSUE THREAD

**Issue by harunbadilli** [ng-bootstrap/ng-bootstrap#2350]
I designed a logo for bootstrap. I think it is a more simple and stylish design with the new look. In this way, I designed a logo that is much more animated than a Monotype logo. With your consent, I will send you your logo in the color and size you want.

![1](https://user-images.githubusercontent.com/34319922/39473644-820ac276-4d58-11e8-85f8-593efaeed34e.png)
![2](https://user-images.githubusercontent.com/34319922/39473645-823c99cc-4d58-11e8-8b8a-dfc29ecfb907.png)
![3](https://user-images.githubusercontent.com/34319922/39473646-82767980-4d58-11e8-90a9-696182b80751.png)

**Comment by mohammedzamakhan** [comment]
I think it should be the merge of bootstrap stack and angular logo

![bootstrap-stack](https://user-images.githubusercontent.com/2327532/39481401-fa7d2992-4d30-11e8-886d-c4a3ee88147f.png)

 and

![angular_solidblack](https://user-images.githubusercontent.com/2327532/39481454-22633b0e-4d31-11e8-8906-2b6eed566c7f.png)

**Comment by velvok** [comment]
Agreed. It could be something like a bootstrap stack but in a shape of Angular shield instead of bootstrap's rhombus. Like a stack of shields. And the letter "A" on top of course. Would keep bootstrap color so that a final logo inherits 2 things from Angular (shape and letter) and 2 things from Bootstrap (stack and color)

**Comment by benouat** [comment]
@velvok Something like that ?

![image](https://user-images.githubusercontent.com/1152740/39566683-b20c5254-4ebc-11e8-9c12-3f3a6e3981e6.png)

**Comment by pkozlowski-opensource** [comment]
@benouat I love direction of your proposal! It looks good and have 2 nice properties:
* it is _clearly_ a combination of Bootstrap and Angular worlds
* the new logo is sufficiently different from the old one to warrant change yet similar enough so we are not loosing project's identity!

**Comment by pkozlowski-opensource** [comment]
Thnx for the inspiration @harunbadilli and @mohammedzamakhan - we've decided to go with @benouat  proposal and website redesign!
