### ISSUE TITLE
Popover:  it should be shifted or flipped when it reaches the viewport margins

### ISSUE THREAD

**Issue by ktriek** [ng-bootstrap/ng-bootstrap#2351]
### Bug description:
The popover should be always visible in the viewport. it should be shifted or flipped when it reaches the viewport margins.
Should we consider using Popper.js since there are a lot of issues related to the popover position?

#### Expected behavior(Bootstrap/Popper.js)
![image](https://user-images.githubusercontent.com/4461059/39472655-bc92c83e-4d18-11e8-973d-6a9430039fb6.png)

#### Issue(NgBootstrap)
![image](https://user-images.githubusercontent.com/4461059/39472672-d206fd98-4d18-11e8-99d8-a8203309d117.png)

### Link to minimally-working plunker that reproduces the issue:
 [https://ng-bootstrap.github.io/#/components/popover/examples](https://ng-bootstrap.github.io/#/components/popover/examples) 
You can resize the browser window to see the issue.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
5.x
ng-bootstrap:
1.1.2
Bootstrap:
4.1.1

**Comment by pkozlowski-opensource** [comment]
I believe that we've got all the mechanism to achieve this already in place. More specifically, you can:
* specify a list of placements to tests, ex.: `[placement]="['top', 'top-left'"`
* specify placement `auto` (to be chosen automatically based on available space) 
* combine the two approaches, ex.: `[placement]="['top', 'top-left', 'auto']"`

See: https://stackblitz.com/edit/angular-3ebbc7?file=app/popover-basic.html

Closing as already supported.
