### ISSUE TITLE
Show placehoders as default for zero values in timepicker.

### ISSUE THREAD

**Issue by sushmit-oodles** [ng-bootstrap/ng-bootstrap#2352]
i am using timepicker. is it possible to show HH MM placeholders when initial values are set to zero for both hour and minute ?

**Comment by pkozlowski-opensource** [comment]
Nope, sorry, this won't work as `00:00` is a valid time, so displaying HH MM placeholders would be _very_ confusing to end users. I'm going to close this one as we are not planning to add support for this in ng-bootstrap.

**Comment by sushmit-oodles** [comment]
Well i needed this functionality cause i am using timpickers in a form. initially placeholders are shown when page loads now, lets say user submits form without even touching the timepicker so the values i am getting from timepicker is undefined for both hour and minutes properties in object. 
Now lets say user does change the time he knows that first input is for hours and second one is for minutes by looking at the placeholders easily. now he submits the form and values are stored in database, then if the users visits the same page again in future the timepicker's input fields will be prefilled after fetching the data from database which will be the values entered last time when form was submitted. Now lets say the time entered last time was 12:12 which will show up in input fields prefilled as 12:12 instead of HH:MM placeholders, the problem is that now user has no idea what format the time picker is expecting is it HH:MM or MM:SS ?
