### ISSUE TITLE
Popover's "open" function not working programatically 

### ISSUE THREAD

**Issue by sparkeplug** [ng-bootstrap/ng-bootstrap#2354]
Hi,

I am trying to implement the popover functionality in my project. But as explained in the documentation i tried to invoke the popover using the built in OPEN function. 

But the following error is throwed in the console.

       "ERROR TypeError: Cannot read property 'createComponent' of null"

The issue is reproduced in the below URL.

https://stackblitz.com/edit/ng-bootstrap-popover-issue

Angular: 5.0,2

ng-bootstrap: 1.1.2

Bootstrap: 4.0.0

**Comment by pkozlowski-opensource** [comment]
This is not how it is intended to be used - you can only use programatic `open` function on popovers defined in a template. You can't just inject `NgbPopover` and expect it to open - there is just too much context missing without a template (ex. anchor element for positioning).  

Closing as invalid.
