### ISSUE TITLE
Modal opening listener

### ISSUE THREAD

**Issue by m-sureshraj** [ng-bootstrap/ng-bootstrap#2356]
I have a scenario where I want to initialize a plugin after modal get's opened but from the docs, I didn't find any API to listen for the modal opening event. So to tackle this scenario I moved the plugin initialization part into a separate angular component. (inside ```ngOnInit```). 

I want to know if there is a way to listen for the modal opening event? Thanks.

**Comment by pkozlowski-opensource** [comment]
There is no need for the "modal opening listener", as:
* modal opening is synchronous
* modal opening happens in your code (while calling the `open({...})` method on the `NgbModal` service.

As such a modal is open after the `open({...})` method returns. Isn't this working for you?

**Comment by m-sureshraj** [comment]
@pkozlowski-opensource Thanks for your quick feedback. 

> modal opening is synchronous 
I didn't know that. In this case I can initialize the plugin  after opening ```open({...})``` the modal.
I think it would be great if we list above points in the docs page modal section. Thanks.

**Comment by pkozlowski-opensource** [comment]
> I think it would be great if we list above points in the docs page modal section.

The signature of the `open` method doesn't have any indications of being asynchronous (no callbacks, not returning promise etc.) so not sure if we want to indicate it specifically (we would have to have a mention on each and every method if we can't extract this info from a signature).

If you still believe that a particular docs would be helpful please PR us with the exact wording you would like to see. Thnx!
