### ISSUE TITLE
NgbTimepicker onChange

### ISSUE THREAD

**Issue by Stajor** [ng-bootstrap/ng-bootstrap#2367]
Change request.

Please add output for change event to timepicker

Angular: any
ng-bootstrap: any
Bootstrap: any

**Comment by pkozlowski-opensource** [comment]
You can use `ngModelChange` event to be notified on the selection change: https://stackblitz.com/edit/angular-k6sv29?file=app/timepicker-basic.html

I don't think we need anything more here so I'm going to close this issue for now. Feel free to comment if anything else is missing here.

**Comment by john-hynes** [comment]
I have a timepicker in a modal and the ngModelChange event is always out of step. The first time I change the time the ngModelChange event is not fired. The second time I make a change, the event is fired but it tells me of the first change. Subsequent changes are always out of step.

The datepicker in a modal has the same issue, however I can work around that by using the dateSelect event that gives me the correct date.

**Comment by mquispe1185** [comment]
> I have a timepicker in a modal and the ngModelChange event is always out of step. The first time I change the time the ngModelChange event is not fired. The second time I make a change, the event is fired but it tells me of the first change. Subsequent changes are always out of step.
> 
> The datepicker in a modal has the same issue, however I can work around that by using the dateSelect event that gives me the correct date.
I have the same problem using ngModelChange, IS ALWAYS OUT OF STEP (and my function gets diferrence in minutes between two times, so it mus be exact), how do you solve this issue?

**Comment by krishnamhn009** [comment]
is there any work around for this issue? how did you solve issue? @Stajor
