### ISSUE TITLE
Enable Tabs to Be Selected by Hovering Them

### ISSUE THREAD

**Issue by HEBOS** [ng-bootstrap/ng-bootstrap#2374]
Hi,

These days, people have no patience to wait for anything. 
The current architecture of ngb-tabs supports tabs to be selected, only by using click.
However, it would be more feasible for me to change the default behavior to enable tab to be selected by hovering it using the mouse.

As I can see from your API page, current architecture doesn't support this (see https://ng-bootstrap.github.io/#/components/tabs/api).

I would like to see NgbTabset with a new property (**selection: {"click", "hover"}**), so anyone could choose his own preferred behavior.

Thank you

**Comment by pkozlowski-opensource** [comment]
Thnx for the suggestion but we are going to pass on it. Bootstrap itself doesn't support and IMO for a good reason - with this proposal just moving a mouse across a tabset would activate a tab, destroying & re-creating components, running animations etc.
