### ISSUE TITLE
Feature: Expose progress-bar background color attribute for dynamic styling.

### ISSUE THREAD

**Issue by aujang** [ng-bootstrap/ng-bootstrap#2376]
At the moment, the only way to change the color of the progress bar is to use a predefined Bootstrap type (info, warn, danger, etc.) or to use static styling (background-color: #XXXXXX) on the progress-bar class via CSS.

This prevents users from utilizing ng-style to dynamically style the progress-bar color via $scope variables. If you could expose this attribute of progress-bar in the directive (similar to how value and type are exposed) we could bind it to a scope variable in the <uib-progressbar> markup.

Thanks!

**Comment by pkozlowski-opensource** [comment]
I'm sorry but it is not clear for me what you are asking for. Moreover you are mentioning `$scope` which would indicate that you are talking about a different library (ng-bootstrap here works with Angular 5+).

Could you please clarify / provide more info?

**Comment by pkozlowski-opensource** [comment]
> First, I am using AngularJS 1.6.6,

@aujang this library is _not_ for AngularJS 1.x, it only works for Angular >= 4. And we are _not_ developing / maintaining `<uib-progressbar>` here but rather `<ngb-progressbar>`.

Closing as it seems that this issue doesn't belong to this repo.

**Comment by aujang** [comment]
Apologies; I thought I had gone to the github repo for uib-bootstrap, not ng-bootstrap. I will post this feature request there.
