### ISSUE TITLE
When there is a modal open, and a user press back in the browser. The modal is still appearing

### ISSUE THREAD

**Issue by fpmirabile** [ng-bootstrap/ng-bootstrap#2382]
### Bug description:
When you press back on any browser, the modals still open

### Link to minimally-working plunker that reproduces the issue:
I don't have time right now for a plunker, sorry tonight I can try to create one

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.0

ng-bootstrap: 1.1.2

Bootstrap: 4.0

**Comment by pkozlowski-opensource** [comment]
I'm fairly positive that this is a duplicate of #2228

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't heard back.
