### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by IConstructor** [ng-bootstrap/ng-bootstrap#2386]
I am facing the following console error which appears when I am trying to go to next/prev months with a help of keyboard arrows.
RROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'focused: true'. Current value: 'focused: false'.
    at viewDebugError (core.js:9775)
    at expressionChangedAfterItHasBeenCheckedError (core.js:9753)
    at checkBindingNoChanges (core.js:9920)
    at checkNoChangesNodeInline (core.js:13974)
    at checkNoChangesNode (core.js:13942)
    at debugCheckNoChangesNode (core.js:14771)
    at debugCheckDirectivesFn (core.js:14673)
    at Object.eval [as updateDirectives] (NgbDatepicker.html:3)

Bootstrap version 4, Angular 5. ng-bootstrap - 2
plunker - http://plnkr.co/edit/yzCMpNMb15oOQf5tJCn6

Do you have any assumptions why this is happening and whether it can be fixed?

**Comment by pkozlowski-opensource** [comment]
We need a minimal reproduce scenario to be able to progress on this one: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment]
@IConstructor I'm sorry but we really can't help without a reproduce scenario so I've got no choice but to close this issue. Happy to re-open when / if you've got a reproduce scenario...

**Comment by IConstructor** [comment]
I figured out the issue disappears when I remove from providers Browser Animation Module. However, still not sure how these intersect.

**Comment by IConstructor** [comment]
I have a plunker link where it is reproducible http://plnkr.co/edit/yzCMpNMb15oOQf5tJCn6
