### ISSUE TITLE
Startdate is not working

### ISSUE THREAD

**Issue by SerdarN92** [ng-bootstrap/ng-bootstrap#2387]
### Bug description: Setting Startdate - Datepicker default is still today

I try to put a startdate over the NgbDatepickerConfig .. but the Datepicker still picking the current day.

I try it like that:

datePickerConfig.startDate = {year: 1993, month: 6 };

But its not working.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.0.0

ng-bootstrap: 2.0.0

Bootstrap: 4

**Comment by pkozlowski-opensource** [comment]
We need a minimal reproduce scenario to make it actionable: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't heard back

**Comment by SerdarN92** [comment]
Sorry @pkozlowski-opensource i forgot to answer you. Its now working. Was a mistake from my side.
