### ISSUE TITLE
Typeahead treats 0 as a null value

### ISSUE THREAD

**Issue by razzildinho** [ng-bootstrap/ng-bootstrap#2389]
### Bug description:
If 0 (zero) is passed as a model value to the typeahead formatter it is returned as a string rather than being formatted. In my example the formatting function checks whether an object with an id matching the input exists in an array and if so returns the object name. `0` is a valid input but as `0` is falsy the typeahead `_formatItemForInput` function returns the input as a string.

### Link to minimally-working plunker that reproduces the issue:
[http://plnkr.co/edit/NHCHep7OuiceRi0rRdAa?p=preview](http://plnkr.co/edit/NHCHep7OuiceRi0rRdAa?p=preview)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.0.2

ng-bootstrap: 1.1.2

Bootstrap: 4.0.0

**Comment by pkozlowski-opensource** [comment]
Oh, right! This should be an easy fix here: https://github.com/ng-bootstrap/ng-bootstrap/blob/39d458d7930c9b49ec676e703267b62facd4c98d/src/typeahead/typeahead.ts#L334

Would you be up to sending a PR? We would merge it if it comes with a test, follows our guidelines etc. Relevant reading: https://github.com/ng-bootstrap/ng-bootstrap/wiki/Contributions%3A-How-to-get-a-PR-merged-fast%3F

**Comment by pkozlowski-opensource** [comment]
Never mind, I've sent #2399 to fix this issue.

**Comment by razzildinho** [comment]
@pkozlowski-opensource Fast work, was going to have a look this evening but you beat me to it. Looks good.
