### ISSUE TITLE
NgbDatepicker: Focus-trap error when used in a FormArray

### ISSUE THREAD

**Issue by philmerrell** [ng-bootstrap/ng-bootstrap#2390]
### Bug description:
When using NgbDatepicker inside a FormArray, opening multiple datepickers causes: `Uncaught RangeError: Maximum call stack size exceeded` in console, referring to focus-trap.js. If enough datepickers are opened, it will crash/lock the browser.

### Link to minimally-working plunker that reproduces the issue:
[Demo](https://stackblitz.com/github/philmerrell/ngbdatepicker-formarray-issue)

- Open browser console (not the stackblitz console)
- Open multiple simultaneous instances of a datepicker

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
6.0.2

ng-bootstrap:
2.0.0

Bootstrap:
4.1.1

**Comment by benouat** [comment]
@pkozlowski-opensource I don't think it is related to #2372.

I will investigate, and for sure improve the focustrap tests suite with this use case.

**Comment by benouat** [comment]
This one seems more related to focustrap not being multi instances compliant.

I would assume here that as soon as 2 focustrap are opened at the same time, they will try to keep focus from each other infinitely, hence the _RangError_.

I need to think about how to fix this properly, nonetheless, it clearly shows, once again, that we are missing on our widgets some `clickoutside` feature.
What I mean here, is that, in term of usability, we should never have 2 datepickers opened at the same time. Opening the second one should trigger a `clickoutise`on the first one  that would close it.

@pkozlowski-opensource @maxokorokov what do you think about that one ?
