### ISSUE TITLE
RxJs 6 merge static method support (Typeahead)

### ISSUE THREAD

**Issue by danieldiazastudillo** [ng-bootstrap/ng-bootstrap#2394]
### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 6.0.2
ng-bootstrap: 2.0.0
Bootstrap: 4.1.1
RxJS: 6.0.0
Angular-CLI: 6.0.3

When linting project with `ng lint` throws **warning** with text `merge is deprecated: Deprecated in favor of static merge`. In fact, this is suggested in RxJS6 migration guide. Specifically, warning is raised by arrow function in **Typeahead** as suggested in ng-bootstrap Wikipedia Search Results example. From now on, `merge` is no longer pipeable and must be used as static method:

![image](https://user-images.githubusercontent.com/14895873/40378333-3fac99da-5dc1-11e8-8349-e45d421ec58b.png)

Maybe some changes or just a warning in ng-bootstrap documentation would be ideal for users already using Angular 6 projects.

**Comment by pkozlowski-opensource** [comment]
@danieldiazastudillo sure, care to send us a PR? But the way, could you please add a link to RxJS docs / changeleog where the operator version of `merge` was deprecated for the static one?

**Comment by pkozlowski-opensource** [comment]
@danieldiazastudillo sorry, I can see it here: https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md

A PR with a change would be welcomed!

**Comment by chuckmah** [comment]
I ended up doing something like this
```

 search = (text$: Observable<string>) => {
    const textDebounced$ = text$.pipe(debounceTime(200), distinctUntilChanged());
    const focus$ = this.focus$;
    const click$ = this.click$.pipe(filter(() => !this.instance.isPopupOpen()));
    const autocomplete$ = merge(textDebounced$, focus$, click$);

    return autocomplete$.pipe(
      map(
        term =>
          term === ''
            ? this.items
            : this.items.filter(v => v.toUpperCase().indexOf(term.toUpperCase()) > -1).slice(0, 10)
        // tslint:disable-next-line:semicolon
      )
    );
  };
```
