### ISSUE TITLE
Center alignment is not good when tooltip too long 

### ISSUE THREAD

**Issue by DreamLi1314** [ng-bootstrap/ng-bootstrap#2396]
Please see attached screenshot.
![tip](https://user-images.githubusercontent.com/23147720/40415550-b68c682c-5ead-11e8-8888-3ebf0a4f97dc.jpg)

**Comment by pkozlowski-opensource** [comment]
We need a minimal reproduce scenario, a screenshot is _not_ enough: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

**Comment by DreamLi1314** [comment]
I made a simple example to reproduce this problem.
See:
    Source:  [https://stackblitz.com/edit/angular-7sfb8l](https://stackblitz.com/edit/angular-7sfb8l)
    Demonstration: [https://angular-7sfb8l.stackblitz.io](https://angular-7sfb8l.stackblitz.io)
    
I think it should provide a property for the user to configure the alignment of the Tooltip.

**Comment by DreamLi1314** [comment]
I can override the tooltip-inner to fix this problems, but i think has a property to controller is good.
like is:
`.tooltip-inner {`
`    text-align: left !important;`
`}`

**Comment by pkozlowski-opensource** [comment]
This alignment comes from Bootstrap CSS (it is part of the `tooltip-inner` CSS class). So if this is to be made configurable it would have to be fixed in the Bootstrap CSS first. Currently there is nothing we can do about it in ng-bootstrap.

**Comment by DreamLi1314** [comment]
OK, That seems to only cover css like I did above to avoid this problem.

Thanks, Pawel Kozlowski.
