### ISSUE TITLE
can‘t opne modal in angular 6

### ISSUE THREAD

**Issue by z778856** [ng-bootstrap/ng-bootstrap#2403]
I use ng bootstrap like https://ng-bootstrap.github.io/#/components/modal/examples
but when i use  this.modalService.open  trigger onLeave(zone) , modal is hide
"dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/router": "^6.0.0",
    "@ng-bootstrap/ng-bootstrap": "^2.0.0",
    "angular-in-memory-web-api": "~0.5.0",
    "core-js": "^2.5.4",
    "rxjs": "^6.1.0",
    "rxjs-compat": "^6.1.0",
    "zone.js": "^0.8.26"
  },

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we really can't help without a minimal reproduce scenario: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

**Comment by z778856** [comment]
thank you pkozlowski
 I use bootstrap modal instead of ng-boot modal
