### ISSUE TITLE
Performance: Tooltip positioning code causes performance degradation

### ISSUE THREAD

**Issue by shyamal890** [ng-bootstrap/ng-bootstrap#2405]
### Bug description:

For some reason ngbTooltip positioning code is taking a lot of time and causes performance degradation. Here'a a chrome devtool screenshot:

![image](https://user-images.githubusercontent.com/6606965/40490786-239fd3b8-5f8a-11e8-9fb4-7c355d0e4f9e.png)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.0.1

ng-bootstrap: 2.0.0

Bootstrap: 4+

**Comment by pkozlowski-opensource** [comment]
What I can see from this screen is that positioning elements take 0.2 ms (0.3% of all operations - look at self time).

Given that _usually_ you've got just one tooltip opened _and_ most of the time there is none opened I wonder how this can cause "performance degradation" in a real-life application... The only way this could happen would be if your entire application is made of several tooltips open all the time...

Hard to say more without understanding your exact use-case. We would need a reproduce scenario to be able to progress on this one. But generally speaking keep in mind that positioning tooltip / popovers _is_ expensive as it requires reading from the DOM. So an application with many, many tooltips could see this problem. But this is not a common case.

Anyway, can't say / act more based on the info provided.

**Comment by shyamal890** [comment]
I will try and re-create in stackblitz soon.

**Comment by pkozlowski-opensource** [comment]
> I will try and re-create in stackblitz soon.

Closing as we haven't heard back. Happy to re-open if / when you've got more info.
