### ISSUE TITLE
ReferenceError: Document is not defined

### ISSUE THREAD

**Issue by hadirsa** [ng-bootstrap/ng-bootstrap#2406]
I have an Angular 6 SSR app and i have added ng-bootstrap, but on SSR build and run i get error bellow
### Bug description:

```
ReferenceError: Document is not defined
    at NgbFocusTrapFactory.ctorParameters (J:\Java\workstation\front\.server\server.js:2221:48333)
    at ReflectionCapabilities._ownParameters (J:\Java\workstation\front\.server\server.js:76:1668)
    at ReflectionCapabilities.parameters (J:\Java\workstation\front\.server\server.js:76:2482)
    at JitReflector.parameters (J:\Java\workstation\front\.server\server.js:3226:919)
    at CompileMetadataResolver._getDependenciesMetadata (J:\Java\workstation\front\.server\server.js:2665:25829)
    at CompileMetadataResolver._getTypeMetadata (J:\Java\workstation\front\.server\server.js:2665:23935)
    at CompileMetadataResolver._getInjectableTypeMetadata (J:\Java\workstation\front\.server\server.js:2665:31300)
    at CompileMetadataResolver.getProviderMetadata (J:\Java\workstation\front\.server\server.js:2665:31593)
    at J:\Java\workstation\front\.server\server.js:2665:29171
    at Array.forEach (<anonymous>)
```

### Version of Angular, ng-bootstrap, and Bootstrap:

```
webpack : ^4.0.0
angular": 6.0.0-rc.6, 
ng-bootstrap: ^2.0.0
```

Why i get this error?

**Comment by Trapulo** [comment]
so what is the angular 6.x version that is compatible with ng-bootstrap 2?

**Comment by hadirsa** [comment]
@Trapulo I use **angular 6.0.0-rc.14** in my project.

**Comment by hadirsa** [comment]
My bad. Sorry about close. i reopened it

**Comment by zestan12** [comment]
can someone help me I'm seriously suffering I'm tired of this error
nativescript angular preview problem tns preview
ReferenceError: document is not defined
Bug description:
LOG from device Galaxy Grand Prime Pro: ERROR ReferenceError: document is not defined
LOG from device Galaxy Grand Prime Pro: ERROR CONTEXT {
LOG from device Galaxy Grand Prime Pro: "def": {
LOG from device Galaxy Grand Prime Pro: "nodeMatchedQueries": 0,
LOG from device Galaxy Grand Prime Pro: "flags": 0,
LOG from device Galaxy Grand Prime Pro: "rootNodeFlags": 33554433,
LOG from device Galaxy Grand Prime Pro: "nodeIndex": 0,
LOG from device Galaxy Grand Prime Pro: {
LOG from device Galaxy Grand Prime Pro: "nodes": [
LOG from device Galaxy Grand Prime Pro: "nodeFlags": 33603585,
LOG from device Galaxy Grand Prime Pro: "renderParent": null,
LOG from device Galaxy Grand Prime Pro: "parent": null,
LOG from device Galaxy Grand Prime Pro: "view": {
LOG from device Galaxy Grand Prime Pro: "bindingIndex": 0,
LOG from device Galaxy Grand Prime Pro: "outputIndex": 0,
LOG from device Galaxy Grand Prime Pro: "checkIndex": 0,
LOG from device Galaxy Grand Prime Pro: "flags": 33554433,
LOG from device Galaxy Grand Prime Pro: "directChildFlags": 49152,
LOG from device Galaxy Grand Prime Pro: "childFlags": 49152,
LOG from device Galaxy Grand Prime Pro: "childMatchedQueries": 0,
LOG from device Galaxy Grand Prime Pro: "matchedQueries": {},
LOG from device Galaxy Grand Prime Pro: "matchedQueryIds": 0,
LOG from device Galaxy Grand Prime Pro: "ngContentIndex": null,
LOG from device Galaxy Grand Prime Pro: "references": {},
LOG from device Galaxy Grand Prime Pro: "childCount": 1,
LOG from device Galaxy Grand Prime Pro: "bindings": [],
LOG from device Galaxy Grand Prime Pro: "bindingFlags": 0,
LOG from device Galaxy Grand Prime Pro: "element": {
LOG from device Galaxy Grand Prime Pro: "outputs": [],
LOG from device Galaxy Grand Prime Pro: "ns": "",
LOG from device Galaxy Grand Prime Pro: "name": "ns-app",
LOG from device Galaxy Grand Prime Pro: "attrs": [],
LOG from device Galaxy Grand Prime Pro: "template": null,
LOG from device Galaxy Grand Prime Pro: "componentProvider": {
LOG from device Galaxy Grand Prime Pro: "nodeIndex": 1,
LOG from device Galaxy Grand Prime Pro: "parent": "[Circular]",
LOG from device Galaxy Grand Prime Pro: "renderParent": "[Circular]",
LOG from device Galaxy Grand Prime Pro: "bindingIndex": 0,
LOG from device Galaxy Grand Prime Pro: ...
