### ISSUE TITLE
FR: image picker select form component/directive

### ISSUE THREAD

**Issue by dalu** [ng-bootstrap/ng-bootstrap#2411]
### Bug description:

An image picker directive or component is missing
What is an image picker?
A form select that displays images, when you click on one or more images, this or they are selected.

### Link to minimally-working plunker that reproduces the issue:

http://jsfiddle.net/huanlin/mgvrc/

**Comment by pkozlowski-opensource** [comment]
It is not part of the Bootstrap CSS and as such it is out of scope of this project. Sorry, going to pass on this suggestion.

**Comment by dalu** [comment]
Neither is datepicker or timepicker

**Comment by dalu** [comment]
And neither is rating yet you still have those components.
