### ISSUE TITLE
Feature request: implement ng update

### ISSUE THREAD

**Issue by tdeschryver** [ng-bootstrap/ng-bootstrap#2413]
Hi,

I was wondering if you'd be interested in creating an `ng-update` hook.
This would have the benefit that if a user upgrades to angular 6 with the `ng update` command, the `ng-bootstrap` package would also be upgraded.

I could create submit a PR for this if you'd like.

**Comment by pkozlowski-opensource** [comment]
Yes, sure, we want to increase support for schematics. Could we please move this discussion to https://github.com/ng-bootstrap/schematics where schematics live?

I'm going to close this issue in here, please re-open it in the mentioned repo.
