### ISSUE TITLE
Error: StaticInjectorError(AppModule)[NgbDropdownMenu -> NgbDropdown]

### ISSUE THREAD

**Issue by AlexandreBeato** [ng-bootstrap/ng-bootstrap#2415]
Hello, i'm having a trouble when using Dropdown button. The console shows to me:

**Error: StaticInjectorError(AppModule)[NgbDropdownMenu -> NgbDropdown]** 

The only thing i'm using is documentation code:

`<button class="btn btn-outline-primary" id="dropdownBasic1" ngbDropdownToggle>Toggle dropdown</button><div ngbDropdownMenu aria-labelledby="dropdownBasic1"><button class="dropdown-item">Action - 1</button><button class="dropdown-item">Another Action</button><button class="dropdown-item">Something else is here</button></div>`

And in my _app.module_ i'm importing **NgbModule** correctly.

Am I doing something wrong? Or really it's a bug?

**Comment by AlexandreBeato** [comment]
Just add **NgbDropdown** in the **providers** and will be solved. But i can't see that on DOCS, please add.

**Comment by pkozlowski-opensource** [comment]
> Just add NgbDropdown in the providers and will be solved. But i can't see that on DOCS, please add.

Having `NgbDropdown` n the providers should _not_ be needed, there must be something else going on in your app. Please provide a minimal reproduce scenario (plunker, stackblitz) so we can understand what is going on. But again, we don't want to update docs as there should be no need for a provider.
