### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by MaddyDahiya** [ng-bootstrap/ng-bootstrap#2417]
While try to install ng-bootstrao for Angular5 Project using Angular-cli version 6, got an error below -
D:\Angular>npm install --save @ng-bootstrap/ng-bootstrap
npm ERR! code E418
npm ERR! 418 I'm a teapot: @ng-bootstrap/ng-bootstrap@latest

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\ABC\AppData\Roaming\npm-cache_logs\2018-05-29T03
_18_26_712Z-debug.log

**Comment by maxokorokov** [comment]
Hey, it's not an ng-bootstrap issue, please see https://github.com/npm/npm/issues/20791 for example
