### ISSUE TITLE
How to change modal height?

### ISSUE THREAD

**Issue by Zerokk** [ng-bootstrap/ng-bootstrap#2420]
Fast question!

Is there a way to customize the modal's height? I tried applying some min-height to a windowClass I provided, but it seem not to do anything at all.

**Comment by mendeza** [comment]
There's an example in the docs: https://ng-bootstrap.github.io/#/components/modal/examples#options
Your custom windowClass `.foo` becomes a hook for modifying the child class `.modal-content`:
```
.foo .modal-content {
  min-height: 400px;
 }
```

**Comment by pkozlowski-opensource** [comment]
@mendeza thnx for helping out with the issues, much appreciated!
@Zerokk please ask support questions like this one using a dedicated channel in the future: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help

**Comment by Zerokk** [comment]
@mendeza @pkozlowski-opensource 

I already tried this but it's not changing the modal's height :/

```
.xlModal > .modal-dialog {
    max-width: 50% !important;
    min-width: 50% !important;   
    min-height: 600px !important;
    height: 600px !important;
}
```
