### ISSUE TITLE
How to disable default mouse events ?

### ISSUE THREAD

**Issue by DheerajVislavath** [ng-bootstrap/ng-bootstrap#2422]
I am using ng-bootstrap carousel, In which the carousel slideshow pauses when I hover and cycles when I leave. How can I disable this default mouse event behavior ?

**Comment by pkozlowski-opensource** [comment]
We don't such feature right now, but we are already tracking it in #1163 - closing as a duplicate. It should be very easy to implement - feel free to send a PR

**Comment by DheerajVislavath** [comment]
Sure, Please try to add this feature in your next release. Thank you.
