### ISSUE TITLE
position error

### ISSUE THREAD

**Issue by JimWang1995** [ng-bootstrap/ng-bootstrap#2423]
![Image text](https://raw.githubusercontent.com/JimWang1995/pic/master/1.png)

![Image text](https://raw.githubusercontent.com/JimWang1995/pic/master/2.png)

**Comment by pkozlowski-opensource** [comment]
We need a minimal reproduce scenario to be able to progress on this one: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't hard back with the reproduce scenario from the author of this issue.

**Comment by JimWang1995** [comment]
The reason may be that the type of input I use is hidden or its display is none.
I change the type and set  "opacity: 0; " to solved the problem.
