### ISSUE TITLE
collapse - auto scroll up page after collapse

### ISSUE THREAD

**Issue by hosseinGanjyar** [ng-bootstrap/ng-bootstrap#2424]
This is a **_feature_** :
When I using *ngFor for show n records, I collapsed more than 3 records and expanded mor than 3 records if user click over button **_show more_**. Now when user clicked **_show more_** and then user scroll down to end of this records, after collapse that page not scroll to this element and page is in down position.
I want after collapse element, page auto scroll up to it element that expanded/collapsed.

**Comment by pkozlowski-opensource** [comment]
I'm sorry but it is not clear from your description what you are trying to do exactly... Maybe you should try to reproduce it in a stackblitz forked from our demo page? (https://ng-bootstrap.github.io/#/components/collapse/examples)

In any case I my current thinking is that we don't want to have any automatic scrolling as:
* this is not the desired default behaviour
* users can access collapsible elements and invoke scroll on it

Hard to say more without fully understanding your use-case / what you are trying to achieve.

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't heard back from the author of this issue.
