### ISSUE TITLE
Datepicker date format

### ISSUE THREAD

**Issue by IConstructor** [ng-bootstrap/ng-bootstrap#2426]
Hello I am using the datepicker's directive on my input field. Is it possible to change the date's format into mm-dd-yyyy instead of standard yyyy-mm-dd?

**Comment by benouat** [comment]
Internally datepicker is using `NgbDateParserFormatter` to perform this translation (both parsing & formatting)

https://ng-bootstrap.github.io/#/components/datepicker/api#NgbDateParserFormatter

> Abstract type serving as a DI token for the service parsing and formatting dates for the NgbInputDatepicker directive. A default implementation using the ISO 8601 format is provided, but you can provide another implementation to use an alternative format.

You can just provide at application level (or any component level) your own DateParserFormatter using whatever format you want.
In you application module

```typescript
import { MyOwnDateParserFormatter} from ' .... ';

@NgModule({
  ...
  providers: [
    { provide: NgbDateParserFormatter, useClass: MyOwnDateParserFormatter }
  ]
  ...
})
```

Have a look at our default implementation here: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/datepicker/ngb-date-parser-formatter.ts

and its declaration in datepicker module https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/datepicker/datepicker.module.ts#L50

**Comment by pkozlowski-opensource** [comment]
Thnx @benouat - much appreciated. We are going to document it better via #2102. Closing as a support request / duplicate.
