### ISSUE TITLE
Compatibility with angular 5

### ISSUE THREAD

**Issue by gabrielcs23** [ng-bootstrap/ng-bootstrap#2435]
### Bug description:
Don't know the rigth place to post it, here or StackOverflow. I keep getting error using TypeAhead when updated to ng-bootstrap 2 while using angular 5.
On ng-bootstrap install page it is said "_tested with 5.0.2_" under _Dependencies_ but looks like ng-bootstrap 2 requires angular 6 as peer dependencies.
Is that right? I need to upgrade to angular 6 in order to use ng-bootstrap 2? In that case the [install page](https://ng-bootstrap.github.io/#/getting-started) is incorrect

### Link to minimally-working plunker that reproduces the issue:

https://plnkr.co/edit/uQ2QVBhjH6SZV66RYgCF?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
5.2.0
ng-bootstrap:
2.0.0
Bootstrap:
4

**Comment by pkozlowski-opensource** [comment]
If you want to use Angular 5 than you will have to stick with ng-bootstrap 1.1.1  (last version compatible with Angular 5). If you want to use ng-bootstrap 2.x you will have to migrate to Angular 6 (recommended).

More info in https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md

Closing as a support request.
