### ISSUE TITLE
NgbTypeahead does not display suggestions within `ng-template`

### ISSUE THREAD

**Issue by shantanoo-desai** [ng-bootstrap/ng-bootstrap#2437]
### Bug description:

`<ng-template>` does not render for `ngbTypeAhead` module. Hence, no suggestions are available for display.

My Application tries to put a search bar within Bootstrap's `card` and should provide autocomplete suggestion as mentioned in the examples for __Template for Results__.

#### Layout

![grafik](https://user-images.githubusercontent.com/12070966/41052696-cb3a8e2c-69b9-11e8-9638-d537f1a153e0.png)

#### component.html
```
              <div class="card">
                    <div class="card-header">Available Properties</div>
                    <div class="card-block">
                        <div class="input-group">
                            <label for="typeahead-template" class="input-group-addon"><span>Search</span></label>
                            <input id="typeahead-template"
                                   type="text"
                                   class="form-control"
                                   [(ngModel)]="searchModel"
                                   [ngbTypeahead]="search" [resultTemplate]="rt" [inputFormatter]="formatter"/>

                            <ng-template #rt let-r="result" let-t="term">
                                    {{ r.translatedProperty}}
                            </ng-template>
                        </div>
                        <br>
                        <br>
                    <select size="10" class="form-control mr-4">
                           <!-- code removed for brevity-->
                    </select>
                </div>
```

#### component.ts

```
export class ExplorativeSearchSemanticComponent implements OnChanges {
    public propertyResults: any[] = [];
    public searchModel = {};

   // Autocompletion Implementation from NG-BOOTSTRAP
    public search = (text$: Observable<string>) =>
        text$.pipe(
            debounceTime(200),
            map((term: string) => term === '' ? []
                : this.propertyResults.filter(v => v.translatedProperty.toLowerCase()
                    .indexOf(term.toLowerCase()) > -1).slice(0, 10))
    );
    public formatter = (x: {translatedProperty: string}) => x.translatedProperty;
    
     ngOnChanges() {
        // triggered when a button in the UI is pressed
       // call API and store info in `propertyResults`
       this.propertyResults = response from API;
     }
}
```

### Behaviour
when the user enters in the search bar here no suggestion template is rendered

![grafik](https://user-images.githubusercontent.com/12070966/41053204-2d59359e-69bb-11e8-93e2-3f8107f5cd56.png)

When the user presses <kbd>Tab</kbd> key the autocomplete is achieved

![grafik](https://user-images.githubusercontent.com/12070966/41053281-5fa66b20-69bb-11e8-8b9f-8760f7ace4cf.png)

### Link to minimally-working plunker that reproduces the issue:
On the contrary, I first created a [StackBlitz](https://stackblitz.com/edit/ng-bootstrap-workflow-test) which provides the desired result and then used the code in my application. The code on stackblitz works perfect but it doesn't in my application.

### Checks 

Browser: Mozilla FireFox 60.0.1

The inspector provides the following when anything is typed within the search bar:
![grafik](https://user-images.githubusercontent.com/12070966/41053407-b24d1626-69bb-11e8-8567-2ab997d960b5.png)

`ngb-typeahead-window` is grayed out.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:  `5.2.x`

ng-bootstrap: `1.1.x`

Bootstrap: `4.0-alpha.6`

**Comment by pkozlowski-opensource** [comment]
>  On the contrary, I first created a StackBlitz which provides the desired result and then used the code in my application. The code on stackblitz works perfect but it doesn't in my application.

I'm sorry but it would suggest that something else is going in your application. We can't investigate / fix bugs that we can't reproduce: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

We don't have access to your application and can't (and wouldn't) debug it. You best chance of getting this issue resolved is to try to narrow down the issue to the point where you can reproduce outside of your application. Otherwise there is no ground for suspecting that the problem is on ng-bootstrap side.

**Comment by shantanoo-desai** [comment]
@pkozlowski-opensource 
Well on the contrary I tried to include the example code in my component and it proves to be the same
![grafik](https://user-images.githubusercontent.com/12070966/41054061-9ed5802c-69bd-11e8-8818-a8d2c4277d74.png)

Only when I hit <kbd>Tab</kbd> is the result completed 

![grafik](https://user-images.githubusercontent.com/12070966/41054110-bec7663e-69bd-11e8-80bf-ac18e19c9133.png)

**Comment by pkozlowski-opensource** [comment]
> Only when I hit Tab is the result completed

This is normal and expected behaviour. If you don't want string to be propagated to the model as a user types you could use the `[editable]="false"` option: https://ng-bootstrap.github.io/#/components/typeahead/api

Does it help?

**Comment by shantanoo-desai** [comment]
@pkozlowski-opensource I think autocomplete is okay for now. I understand the need to provide a plunkr or stackblitz example here. But the component I am working on is a part of a large platform. I don't think it would be wise to reproduce a plunkr of the platform.

**Comment by shantanoo-desai** [comment]
Closing the Issue as the platform now uses `Bootstrap 4.1.1` and the suggestion template is displayed.
