### ISSUE TITLE
2.1.0 AOT error

### ISSUE THREAD

**Issue by achimha** [ng-bootstrap/ng-bootstrap#2444]
Building my app with angular-cli and ng-bootstrap 2.1.0 yields

```
ERROR in ./node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module.js
Module not found: Error: Can't resolve './ngb-date-adapter' in 'myproject/node_modules/@ng-bootstrap/ng-bootstrap/datepicker'
```

**Comment by pkozlowski-opensource** [comment]
This sounds odd. What is Angular / CLI version used for your app?

**Comment by achimha** [comment]
```
Angular CLI: 6.0.8
Node: 8.11.2
OS: linux x64
Angular: 6.0.4
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
````

Going back to 2.0.0 makes the error go away.

**Comment by psenechal** [comment]
I encountered the same issue with Angular 6.0.4 and CLI 6.0.7, so it's not the new version of CLI that just came out.

**Comment by maxokorokov** [comment]
@psenechal that is strange indeed, because in `2.1.0` inside `./node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module.js` it's actually

```ts
import { NgbDateAdapter, NgbDateStructAdapter } from './adapters/ngb-date-adapter';
```

Looks like installation/update issue to me, see no problems on clean install

**Comment by changhuixu** [comment]
Got same error... revert back to 2.0.0 till this issue is resolved.

**Comment by psenechal** [comment]
I’ll try cleaning and installing without ng-bootstrap, then installing and building tomorrow to see how it goes. I did delete my node_modules and install everything all together and still got the issue. So maybe doing an install without it, then installing it separately will work. I’ll post my package.json as well to see if maybe there is some common dependency that might be causing the issue. Never had a problem with ng-bootstrap before so I think you’re right and it’s just a build/environment issue.

**Comment by psenechal** [comment]
I completely removed my node_modules folder and reinstalled everything...no errors this time at all. All is well. Thanks!

**Comment by pkozlowski-opensource** [comment]
@xetys we would need a reproduce scenario / sample repository where we can see this issue. I'm not sure how we could progress on this without being able to reproduce the issue...

**Comment by jasedwards** [comment]
FYI, deleting node_modules, running npm cache clean --force and then npm install fixed it for me

**Comment by mirsaeedi** [comment]
Thank God I found this thread. I had the same problem. Deleting the node folder mitigated the problem for me.

**Comment by takumi-hoppler** [comment]
Hey guys, I'm having the same issue on ng-bootstrap v3.2. 

```
Angular CLI: 6.2.1
Node: 6.14.4
OS: linux x64
Angular: 6.1.7
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
```
I'm getting module not found error in all of ng-bootstrap module (accordion, alert, typeahead, etc.)
I've tried deleting my node_modules folder and clearing npm cache but the problem persist.

Am I the only one having this problem?

**Comment by takumi-hoppler** [comment]
> Hey guys, I'm having the same issue on ng-bootstrap v3.2.
> 
> ```
> Angular CLI: 6.2.1
> Node: 6.14.4
> OS: linux x64
> Angular: 6.1.7
> ... animations, common, compiler, compiler-cli, core, forms
> ... http, platform-browser, platform-browser-dynamic
> ... platform-server, router, service-worker
> ```
> 
> I'm getting module not found error in all of ng-bootstrap module (accordion, alert, typeahead, etc.)
> I've tried deleting my node_modules folder and clearing npm cache but the problem persist.
> 
> Am I the only one having this problem?

Sorry, it seems that the problem is on my end. For some reason, my angular-cli is not generating dist/server.

**Comment by abyrne85** [comment]
@takumi-hoppler Did you discover the source of the problem?  I'm having the same issue

**Comment by takumi-hoppler** [comment]
@abyrne85 Yep. The problem was with my ssr config. 

Try going through https://angular.io/guide/universal again.

**Comment by bike2live** [comment]
Having the same issue with ng-bootstrap v4.0.3, angular 7.2.6. Did an npm cache clean -f, blew away the node_modules folder, then npm install. Still the same issue.
```
Angular CLI: 7.3.3
Node: 11.10.0
OS: darwin x64
Angular: 7.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.2
@angular-devkit/build-angular     0.13.2
@angular-devkit/build-optimizer   0.13.2
@angular-devkit/build-webpack     0.13.2
@angular-devkit/core              7.3.2
@angular-devkit/schematics        7.3.3
@angular/cdk                      7.3.3
@angular/cli                      7.3.3
@angular/material                 7.3.3
@ngtools/webpack                  7.3.2
@schematics/angular               7.3.3
@schematics/update                0.13.3
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.5
```

**Comment by TheProgrammator** [comment]
Currently also facing this issue. Rimraffed node_modules, npm i, issue remains.

**Comment by timostamm** [comment]
Same here, angular 7.2.16, tried with ng-bootstrap 3.3.1 / 4.0.2 / 4.2.1.

Fixed by changing import 

```typescript
import {NgbDate} from "@ng-bootstrap/ng-bootstrap/datepicker/ngb-date";
```

to 

```typescript
import {NgbDate} from "@ng-bootstrap/ng-bootstrap";
```

**Comment by caleb-tinyeye** [comment]
> Same here, angular 7.2.16, tried with ng-bootstrap 3.3.1 / 4.0.2 / 4.2.1.
> 
> Fixed by changing import
> 
> ```ts
> import {NgbDate} from "@ng-bootstrap/ng-bootstrap/datepicker/ngb-date";
> ```
> 
> to
> 
> ```ts
> import {NgbDate} from "@ng-bootstrap/ng-bootstrap";
> ```

This solved the same issue for me
