### ISSUE TITLE
Animation Effects

### ISSUE THREAD

**Issue by elainebyrne** [ng-bootstrap/ng-bootstrap#2447]
Hi,

I'm torn between ngBootstrap and Material for my Angular 6 project. 

The lack of animation in ngBootstrap is what concerns me. Non of the default bootstrap animations are working and there's no tutorial to implement the same either. I see some discussions which are over about 1 year old.

Without such animations/transition effects, ngBootstrap feels unpolished and incomplete. Any idea if anyone is actively working on this?

**Comment by pkozlowski-opensource** [comment]
Animations are our top priority item as soon as we are done with accessibility (aria tags, keyboard navigation, focus management) items.

Closing this one as we've got already tracking issues open. But just to be clear: we will support full Bootstrap animations and this is our top priority item.

**Comment by elainebyrne** [comment]
Thanks for all the efforts you guys are putting in. Any timeline on this?

**Comment by smplyjr** [comment]
Any update with this? @pkozlowski-opensource can you give the issue number/link? So we will look there for the status instead. Thanks
