### ISSUE TITLE
datepicker.module.d.ts cannot find module hijri

### ISSUE THREAD

**Issue by alonstar** [ng-bootstrap/ng-bootstrap#2449]
I'm using v 2.1.0 in Angular 6, and build error.
I found there is no "hijri" directory in the node_modules\@ng-bootstrap\ng-bootstrap\datepicker 

ERROR in 
node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module.d.ts(5,41): error TS2307: Cannot find module './hijri/ngb-calendar-islamic-civil'.
node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module.d.ts(6,44): error TS2307: Cannot find module './hijri/ngb-calendar-islamic-umalqura'.

**Comment by pkozlowski-opensource** [comment]
The mentioned files are well deployed to npm, see:
* https://unpkg.com/@ng-bootstrap/ng-bootstrap@2.1.0/datepicker/hijri/ngb-calendar-islamic-civil
* https://unpkg.com/@ng-bootstrap/ng-bootstrap@2.1.0/datepicker/hijri/ngb-calendar-islamic-umalqura

If you don't see those files in your local installation than it probably means that a npm package was now downloaded / saved to the local disk correctly. Try to wipe out your `node_modules` folder and re-install.

**Comment by alonstar** [comment]
@pkozlowski-opensource  thanks, it works.
