### ISSUE TITLE
Auto Positioning of Tool Tip 

### ISSUE THREAD

**Issue by AveekChatterjee7** [ng-bootstrap/ng-bootstrap#2450]
### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6

ng-bootstrap: 2

Bootstrap: 4

**Comment by pkozlowski-opensource** [comment]
I'm sorry, but it is not clear what you are asking for. We've got already extensive support for positioning options, check the `placement` option in our docs: https://ng-bootstrap.github.io/#/components/tooltip/api

If the existing options don't work for you please open a new issue clearly describing your use-case. We can't act on issues / feature requests we can't understand...
