### ISSUE TITLE
Modal is not vertically centered in IE11 with NgbModalOptions.centered option

### ISSUE THREAD

**Issue by edgilman** [ng-bootstrap/ng-bootstrap#2456]
### Bug description: 

Modal is not vertically centered in IE11 browser when opened with NgbModalOptions.centered option.

### Link to minimally-working plunker that reproduces the issue:

See Modal with options | Modal vertically centered example in
https://ng-bootstrap.github.io/#/components/modal/examples

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.0

ng-bootstrap: 1.1.0

Bootstrap: 4.0.0

**Comment by pkozlowski-opensource** [comment]
@divdavem could you PTAL?

**Comment by divdavem** [comment]
I had a look and I can confirm the issue.
Here is the corresponding issue in bootstrap: https://github.com/twbs/bootstrap/issues/25569
It can be reproduced on their demo site too: https://getbootstrap.com/docs/4.1/components/modal/#vertically-centered

**Comment by pkozlowski-opensource** [comment]
Thnx for the investigation @divdavem - in this case I'm afraid we've got no other choice but to wait for Bootstrap to apply the fix (there is a PR in flight: https://github.com/twbs/bootstrap/issues/25569)

**Comment by pkozlowski-opensource** [comment]
This was already fixed on Bootstrap side, will be part of v4.1.3 release. Closing here as we can't act on this issue in this project. Please update your Bootstrap version when it is released.
