### ISSUE TITLE
(tabset, feature): Ability to control active tab via activeId or some @Input property

### ISSUE THREAD

**Issue by AbakumovAlexandr** [ng-bootstrap/ng-bootstrap#2461]
### Feature description:
Currently, to change active tab programmatically we have to call `NgbTabset`'s `select()` method. `activeId` property does not work for this purpose.

This causes issues in certain scenarios. For example, in a "truly" reactive app, we have to not only manually `subscribe()` to update the active tab instead of using data binding, we also have to call `select()` on the next JS event cycle (see the demo below). I'm not sure about the latter, but the former makes API not very reactive and Angular-friendly.

Also, we have to write extra code in a component (and in some cases in a template as well) just to get access to `NgbTabset` instance like this:
```
  @ViewChild(NgbTabset)
  private tabset: NgbTabset;
```

Conversely, Material [MatTabGroup](https://material.angular.io/components/tabs/api#MatTabGroup) has this feature (`selectedIndex` property) and could be a good example here.

### Link to minimally-working plunker that reproduces the issue:
[Stackblitz](https://stackblitz.com/edit/ng-bootstrap-tabset-reactive-tab-select?file=app/app.component.ts)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.0.2

ng-bootstrap: 2.0.0

Bootstrap: 4.1.1

**Comment by pkozlowski-opensource** [comment]
Using data binding for this types of APIs has one fundamental issue in Angular - it doesn't allow you to select the same tab twice. Let me explain the scenario:
* data binding for `activeId` changes to, say `tab-1`;
* user clicks on another tab (so now active tab is, say `tab-3`;
* you want to select `tab-1` again - BAM - it doesn't work since Angular change detection works on binding level and for Angular value of `activeId` didn't change (internal model _derived_ from `activeId` changed but not the `activeId` binding itself!

We _could_ use 2-way binding (`[(activeId)]="exp"` but it would  have following drawbacks:
* one couldn't use "static" values (ex. `atvieId="my-tab"`;
* users would be getting wired errors when not using 2-way data binding (ex. `[activeId]="exp"`)
 
Explicit methods like `select(...)` is the only way I know to solve it elegantly. Happy to discuss other options / other API ideas, if you've got suggestions.

**Comment by AbakumovAlexandr** [comment]
@pkozlowski-opensource , ss you've mentioned, the alternative solution might be a two-way bind-able `[(activeId)]` property like in aforementioned `MatTabGroup`.

In this case:

1. Regarding "static" values, for me it looks more like a specific use case which is limited by the current Angular template syntax and which should not affect the generalized idea of communicating with a template and child components via the data-bindings only. Moreover, one could easily workaround this with a property in the component. But the other way around is not so easy and, what is more important in my opinion, not so ideologically correct. Or, we can add a marker directive `activeTab` for this use case.
2. As to the attempt to use a one-way binding on the two-way bind-able property, what might be use cases for this? If I understand correctly, this is only when you want to initialize the active tab once based on some logic. But again, it's simple to workaround.

Please let me know if missed some deeper details in your concerns.

**Comment by AbakumovAlexandr** [comment]
I've just updated my [Stackblitz](https://stackblitz.com/edit/ng-bootstrap-tabset-reactive-tab-select) with the proof that when `ChangeDetectionStrategy` is `OnPush`:
      this.tabs.subscribe((tabs: ITab[]): void => {
          // Does not change the tab
          this.tabset.select(tabs[tabs.length - 1].id.toString());
          
          // Only this one works and only if ChangeDetectionStrategy is NOT OnPush.
          // NOTHING works if ChangeDetectionStrategy is OnPush.
          // setTimeout(() => this.tabset.select(tabs[tabs.length - 1].id.toString()));

          // The following does NOT work regardless of ChangeDetectionStrategy
          // this.changeDetector.markForCheck();
          // this.changeDetector.detectChanges();
          // this.application.tick();
          // this.zone.run(() => this.tabset.select(tabs[tabs.length - 1].id.toString()));
        });
This basically means that there is no way to change an active tab from the subscription to the same `Observable` used for posting tab collection changes.

If I understand correctly, this directly relates to the fact that we have to change active tab via the method call instead of `NgbTabset`'s `@Inpit`.

**Comment by benouat** [comment]
You can actually achieve what you want to do in a much more simple way 👍 

Here is a stackblitz: https://ng-bootstrap-tabset-reactive-tab-select-phepks.stackblitz.io

There is no need here to use `changeDetectorRef`, nor `applicationRef`.
You just need to do 3 things (step 2 is not even an action!) :

1. Make sure to create the proper data structure associated to the tab you want to generate
2. Wait for changeDetection to be executed, so that the `ngFor` on the tabset is executed.
3. Select the proper tab

In order to properly achieve the transition from step 2 to step 3 you need to execute the `this.tabset.select( ... )` after the changeDetection.
To do that, you could:

+ Use `setTimeout(... , 0)` which basically will execute the callback beginning of next tick
+ Use `zone.onStable` that hooks itself at the end of the microtask execution, ie. just before going to next tick.

Personally I would rather prefer the second one using `zone` as it is much clearer to me as compare to the magical fallback of `setTimeout`. It's definitely more Angular oriented, hence more verbose also...

**Comment by pkozlowski-opensource** [comment]
> If I understand correctly, this directly relates to the fact that we have to change active tab via the method call instead of NgbTabset's @Input.

@AbakumovAlexandr nope, that has nothing to do with a method vs. input - this is a basic timing issue. When selecting a tab we need to make sure that `id` being selected exists. Hence it needs to happen _after_ tabset checked its content. 

I'm not sure if the `ngbTabset` fits in what you are trying to achieve - you are basically trying to drive _everything_ from the model while `ngbTabset` gets part of its input from template (tabset content). Seem like we've got slightly opposing goals.   

What I would suggest is this: try to roll out your own tabset (it is rather simple widget, really), see how it goes and compare your version with what we've got. If you see any chance of making the existing and your model work together, than open a PR. How does it sound?

**Comment by AbakumovAlexandr** [comment]
@benouat, thank you for the workaround! I completely agree that `zone.onStable` is much cleaner than `setTimeout()` magic.

Meanwhile, I ought to to ask this question :) What do you, guys, think about implementing this stuff in `NgbTabset` itself? I mean users of `NgbTabset` should know little about its internals and if you've chosen to go `select()` _method_ way, users expect that calling it should do the job regardless of when they've called it.

**Comment by AbakumovAlexandr** [comment]
@pkozlowski-opensource , thank you! Yes, I'm driving  a lot of stuff from the model and it seems natural in the Angular and reactive approach world. So I'm a little bit confused `NgbTabset` has opposing goal and doesn't stick to Angular Material counterpart API to some reasonable extent. I haven't found your policy on this and this issue is to kind of collect your thought on moving NGB towards this direction.

Sure, if you're confirming current behavior is what it is supposed to be, I'll adopt `NgbTabset` in my project (as I already did with `NgbModal`, to name one),  and see whether my changes would be beneficial enough to open a PR.

**Comment by benouat** [comment]
> What do you, guys, think about implementing this stuff in NgbTabset itself?

I don't see any clear way of doing that with the implementation we currently have. To properly have such a feature, I am afraid we would need a complete different tabset widget.

> So I'm a little bit confused NgbTabset has opposing goal and doesn't stick to Angular Material counterpart API

We decided to implement `ngb-tabset` in a way which is clearly not a model-driven one.
As @pkozlowski-opensource mentioned, we could have done it differently, you could also try to experiment in another direction.
Regarding Angular Material, I don't understand your point here, the 2 projects are not related at all. NG-Bootstrap does rely on Angular, but not on Material. Both projects have different visions here. Our goal is not to align our APIs.

---

@AbakumovAlexandr I hope the picture is more clear on your side, in terms of explanations, so maybe you could close the issue ?

cc @pkozlowski-opensource

**Comment by AbakumovAlexandr** [comment]
@benouat : sure and thank you for the explanations!

Just to expand on my point on aligning with Angular Material.

Angular Material is promoted as the default UI framework for Angular-based apps and developed directly by the Angular team (AFAIK). It's aligned with the latest Angular best practices (including API decisions) and probably could be considered (currently or in the very close future) as a standard for Angular UI components (at least from business app devs; usually, they start developing Angular apps with Material).

When they start using NGB, another UI framework with involvement of core Angular team members, it's confusing why API is so different especially approach-wise. This creates unnecessary issues when switching from Material to NGB. In this specific case, for example, since it's not a model driven component (model driven or reactive components is probably the central feature of Angular itself),  creates the need to implement and maintain our own components, thus, preventing NGB from covering rather simple use cases covered by Material.

Hope it clarifies my point.

**Comment by pkozlowski-opensource** [comment]
@AbakumovAlexandr I hear you. I understand what you want in terms of being more "model / event" driven. I need to think about this one more so I'm going to re-open this issue.

In this particular case I think that neither Material nor Bootstrap has "perfect" API. The difference you see probably steams from the fact that no one found the "holly grail" and we just went with API designs with different tradeoffs. So API differences are normal and expected (not to mention the fact that we don't always agree on everything in the Angular team - but we keep exploring options!).

**Comment by AbakumovAlexandr** [comment]
@pkozlowski-opensource , thank you for looking into this!

I really believe that the great Angular framework should utilize model-driven approach at first whenever possible. Also, I totally support the idea of having an alternative (like the `select()` method we currently have), so use cases with any approach could be covered.

**Comment by pkozlowski-opensource** [comment]
@AbakumovAlexandr right. So what we want, conceptually speaking, is a _stream_ of active ids (bindings alone doesn't work for the reasons described previously).

Something along the lines of `[activeIds]="observableExp$"`. This needs more thinking but IMO this is what we need conceptually... WDYT?

**Comment by AbakumovAlexandr** [comment]
@pkozlowski-opensource , do I understand correctly you proposing to have the following `NgbTabset` API related to a selected tab?

- `activeIds: Observable<string>` you've mentioned
- `activeId` property for initially selected tab
- `tabChange` event
- `select()` method

**Comment by pkozlowski-opensource** [comment]
@AbakumovAlexandr yeh. Don't take it as a well-thought-out proposal, though :-) Just toying with the ideas here! And trying to get feedback if the proposed thing would for you?

**Comment by AbakumovAlexandr** [comment]
@pkozlowski-opensource sure, just trying to summarize the proposal to better understand it :) Yes, this technically would work for me, but I'm thinking about the API in general.

For me, having two properties `activeId` and `activeIds` would look confusing without diving deeper into the docs for the rationale. From my perspective,  it's more natural to have a two way `activeId` property to cover the main use case (being model-driven) and separate the specific use case of static initial tab ID in template into a different entity like `initialActiveId` if it's a really popular use case.

Also, `activeIds: Observable<string>` would not push changes of the active tab ID the other way around to the same property where it comes from. So it lacks an ability to have the same single property which you update from your code to change the tab and check it if you need to get currently active tab including the case when it has been changed by a user and that change has been conveniently pushed to the property you. In my opinion, it would simplify the life significantly :)

**Comment by Nitishkeshri88** [comment]
Here is a stackblitz: https://ng-bootstrap-tabset-reactive-tab-select-phepks.stackblitz.io

could please share your code what changes you have made for this.
stackblitz: https://ng-bootstrap-tabset-reactive-tab-select-phepks.stackblitz.io

**Comment by robinsm** [comment]
@benouat, as this issue still seems unresolved...

Could you please open up your stackblitz at the following location: https://ng-bootstrap-tabset-reactive-tab-select-phepks.stackblitz.io

It seems you have overcome the issue simply but nobody is able to see the code/editor on stackblitz to apply your solution.

**Comment by benouat** [comment]
@robinsm sorry for that 😞 
Here it is -> https://stackblitz.com/edit/ng-bootstrap-tabset-reactive-tab-select-phepks

**Comment by robinsm** [comment]
@benouat thanks for the link.  I got one step closer... I guess.  The correct tab is selected ... but only after I tab out of a  text input or vertically scroll within the viewport.  Strangely, the same behaviour in both Chrome and Firefox.

**Comment by gauribane** [comment]
Working link
demonstrating the functionality. 
https://stackblitz.com/edit/angular-ettpha?embed=1&file=app/tabset-basic.ts

**Comment by maxokorokov** [comment]
Since version `5.2.0` there is a new `NgbNav` set of directives that fix this issue. `NgbNav` is meant to replace the `NgbTabset` component (completely deprecated in version `6.0.0`) as a more flexible alternative.

I suggest you migrate to it → https://ng-bootstrap.github.io/#/components/nav/overview
