### ISSUE TITLE
How to set the date range?

### ISSUE THREAD

**Issue by JimWang1995** [ng-bootstrap/ng-bootstrap#2466]
if I want users to choose a date between 1800 and 1820 , how to set?

**Comment by pkozlowski-opensource** [comment]
Not sure what you are asking for, exactly - there is not enough info / context here. If you:
* need support please ask using a dedicated channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
* if you believe that there is a bug on our side please open a new issue following our issue template: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug
