### ISSUE TITLE
"modal-open" should not be remove when 2 modals are opened and one is closed

### ISSUE THREAD

**Issue by bastienmoulia** [ng-bootstrap/ng-bootstrap#2468]
### Bug description:

When I open a first modal with a long content I show the scrollbar.
But when another one is open above it and close, the scrollbar disappear.
This is because the class `modal-open` is removed from the `<body>` at each close, and not for the last modal.

### Link to minimally-working plunker that reproduces the issue:

https://stackblitz.com/edit/angular-razkfp

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.0.0

ng-bootstrap: 2.1.1

Bootstrap: 4.0.0

**Comment by pkozlowski-opensource** [comment]
Sorry, we are not supporting stacked modals right now, considering it in #643. Closing as a duplicate as there is much more to do than just take care of the "modal-open" CSS class to fully support multiple modals at once.

**Comment by bastienmoulia** [comment]
ok, will find an other way :)

**Comment by bastienmoulia** [comment]
FYI I fork this repo and made a copy of the modal here: https://www.npmjs.com/package/ng-bootstrap-modal-stack
(still in progress)
