### ISSUE TITLE
Islamic Calendars Days are not in Arabic

### ISSUE THREAD

**Issue by MaiGhoneem** [ng-bootstrap/ng-bootstrap#2475]
Hi,
in Islamic Calendars days numbers are not in Arabic, is there way to convert those numbers to Arabic numbers

**Comment by pkozlowski-opensource** [comment]
You can always provide a custom template for a day view and display things as you like. I'm afraid that we are not expert enough in Arabic numbers / Islamic Calendars to offer more help at this point.

Would a custom day template work for you?
https://ng-bootstrap.github.io/#/components/datepicker/examples#customday

**Comment by pkozlowski-opensource** [comment]
I'm going to close this one as we haven't heard back. Hopefully a custom day template is a workable solution for you.
