### ISSUE TITLE
Timepicker arrows should have option to reverse functionality

### ISSUE THREAD

**Issue by dalu** [ng-bootstrap/ng-bootstrap#2477]
### Bug description:

The timepicker is counter-intuitive. Pressing up should reduce the numbers, pressing down should increase the numbers. There should be the option to reverse what arrows do.

### Link to minimally-working plunker that reproduces the issue:

https://ng-bootstrap.github.io/#/components/timepicker/examples

**Comment by pkozlowski-opensource** [comment]
> The timepicker is counter-intuitive. Pressing up should reduce the numbers, pressing down should increase the numbers

Oh, interesting. Actually, I would find reversing those super-counter-intuitive :-)
Can you share any examples of timepickers (or any other widgets) that work the way you describe?

> There should be the option to reverse what arrows do.

Right, maybe.  But I would here more reasoning / see other examples of widgets first.

**Comment by dalu** [comment]
You can view an example at https://contested.de/
However you'll need to create an account to be able to see the "Plan New Raid" component.

There should also be a combined component of Datepicker and Timepicker that actually returns `ISODate`.

An added optional functionality is no big deal
```
if (reverse) {
time.hour--;
} else {
time.hour++;
}
```

Purgatory, very rude

**Comment by pkozlowski-opensource** [comment]
> You can view an example at https://contested.de/
However you'll need to create an account to be able to see the "Plan New Raid" component.

I'm sure you could extract it in a stackblitz or at least provide a screenshot? But really what I was after are examples of other time-picker widgets (using whatever framework / technology) that behaves as you suggest. I'm trying to understand how common this use-case is (I understand it is important for you but I'm trying to determine it fit for the community at large).

> There should also be a combined component of Datepicker and Timepicker that actually returns ISODate.

This is already tracked in: #2086 

> An added optional functionality is no big deal

It is not big deal in terms of implementation, I agree. But every new feature is kind of big deal as it introduces new API that needs to be documented and maintained, has performance impact (new binding, code size) and - most importantly - increases mental load on our users (larger API surface). So we are not taking new APIs light. This is why I'm trying to determine how common / important a given feature is for the community at large before jumping to implementation (even if it is very simple).

> Purgatory, very rude

I'm sorry, this is definitely not the intention. The reality of things is that we are getting many issues that are not being followed up by a person opening it. This milestone is a way of tracking issues where we need more info. What would you suggest as a different name?

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't heard back. Happy to continue discussing if new info surfaces.
