### ISSUE TITLE
ngbDropdown autoclose ability to select multiple in a list at once and close on outside click

### ISSUE THREAD

**Issue by mm739521** [ng-bootstrap/ng-bootstrap#2480]
After reviewing the documentation the ngbDropdown has an autoclose option that has the options of `boolean | "outside" and "inside`.

I want the ability to be able to have autoclose set to false and use the outside option as well.  When I have the autoclose set to "outside", the dropdown closes everytime you select one.

Is there any hack I could do to achieve both the autoclosing to be false and the closing on clicking on the outside?

**Comment by pkozlowski-opensource** [comment]
I'm sorry but it is not clear for me what you are trying to achieve and what doesn't work. Please provide a minmal plunker / stackblitz with what you are trying to achieve - otherwise it is not actionable.

**Comment by pkozlowski-opensource** [comment]
Going to close this one as we haven't heard back.
