### ISSUE TITLE
[FR] Set NgbModalOptions Globally

### ISSUE THREAD

**Issue by Halfist** [ng-bootstrap/ng-bootstrap#2487]
### Feature request description:

It would be nice to have an ability to set `NgbModalOptions` globally, as it is currently implemented for `NgbTooltipConfig`, for example: https://stackoverflow.com/a/44660183/1611569.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.0.0

ng-bootstrap: 2.1.2

Bootstrap: 4.1.1

**Comment by Halfist** [comment]
Sorry for such newbie question, but where can I see in which version I'll be able to use the changes?

**Comment by pkozlowski-opensource** [comment]
> but where can I see in which version I'll be able to use the changes?

You can't see the version yet as it was just merged into master. It will probably make it into next feature release (`3.1.0`) - planned to be cut tomorrow.

**Comment by Halfist** [comment]
@pkozlowski-opensource, could you please explain me how to use `NgbModalConfig`? I can't find the example on https://ng-bootstrap.github.io/#/components/modal/api#NgbModalConfig. I expect it to work somehow like this:

```
NgbModule.forRoot({
    backdrop: 'static'
})
```

And one more question. Since I updated to 3.1.0, my IDE warns me that `NgbModule.forRoot()` is deprecated. However, on [this demo](https://stackblitz.com/angular/bexeelqmrmy?file=app%2Fapp.module.ts) I see exactly the same. The question is, should I just remove `.forRoot()`?

**Comment by Yura13** [comment]
Properties of NgbModalConfig should have the same types as in NgbModalOptions.

   NgbModalOptions has property:
     backdrop?: boolean | 'static';
   NgbModalConfig has property:
     backdrop: boolean;

**Comment by Halfist** [comment]
Is anybody able to fix this minor issue?
