### ISSUE TITLE
Ng-bootstrap timepicker.module has no exported member 'NgbTimeAdapter'

### ISSUE THREAD

**Issue by sajeetharan** [ng-bootstrap/ng-bootstrap#2488]
I updated @ng-bootstrap to the latest version 2.2.0 and I started receiving this error in my Angular project. The error seems to come from the 'timepicker' component but it was working perfectly fine in the previous version.

Module '"/node_modules/@ng-bootstrap/ng-bootstrap/timepicker/timepicker.module"' has no exported member 'NgbTimeAdapter'.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:  6.0.3

ng-bootstrap: 2.2.0

**Comment by maxokorokov** [comment]
@sajeetharan please see #2444. 
It must be some cache of your build/package manager.

Works fine for me and `/node_modules/@ng-bootstrap/ng-bootstrap/timepicker/timepicker.module.js` contains:

```typescript
export { NgbTimeAdapter } from './ngb-time-adapter';
```

It's not the first time we get this. Could you please describe your update process?

- cli or not cli?
- package manager?

**Comment by adriandeveloper** [comment]
I have this exact same issue.  

Angular version 6.0.6
NgBootstrapp version 2.1.1

The documentation says I should be able to use NgbTimeAdapter but I get the following


> node_modules/@ng-bootstrap/ng-bootstrap/index has no exported member `NgbTimeAdapter'

Checked and it doesn't. But documentation suggests otherwise.

https://ng-bootstrap.github.io/#/components/timepicker/examples#adapter

Was this not added for a reason or is the documentation wrong?

**Comment by adriandeveloper** [comment]
Ok. I'll talk with my team and get it updated and I'll report back today.

**Comment by dotNetAthlete** [comment]
I have the same issue with NgbDate,
I've got ng-bootstrap 2.2.2

**Comment by pkozlowski-opensource** [comment]
@dotNetAthlete nope, your issue is _not_ the same - `NgbDate` is only available from 3.0.0, see https://ng-bootstrap.github.io/#/components/datepicker/api#NgbDate

**Comment by dotNetAthlete** [comment]
It's a shame that that version information isn't given in the examples page:
https://ng-bootstrap.github.io/#/components/datepicker/examples

By the time you've tried to implement - gone off to stackblitz etc, you've then wasted hours of development time !
