### ISSUE TITLE
z-index issue for ngbPopover

### ISSUE THREAD

**Issue by xyrintech** [ng-bootstrap/ng-bootstrap#2489]
Angular6
ng-bootstrap: 2.2.0

using ngbPopover inside ngx-datatable hides the ngbPopover data. Please check 
![ngbpopover](https://user-images.githubusercontent.com/7784136/42135958-ad81ddb6-7d70-11e8-8c22-38c432a1c44d.png)

**Comment by benouat** [comment]
As it is written on https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug would you mind trying to reproduce it in a minimal stackblitz/plunkr ?

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't heard back with the reproduce scenario.
