### ISSUE TITLE
Need to click twice to open modal in FF

### ISSUE THREAD

**Issue by raysunqi** [ng-bootstrap/ng-bootstrap#2499]
### Bug description:
Fire a modal.open using a component inside a ngrx effect (@Injectable) in Firefox(I am using v61)
my modal is a component <reset-password-modal>

The page render a black line
`<ngb-modal-backdrop></ngb-modal-backdrop>
<ngb-modal-window role="dialog" tabindex="-1"><div role="document"><div class="modal-content"><reset-password-modal _nghost-c5=""></reset-password-modal></div></div></ngb-modal-window>`

click the screen once and the modal shows up.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:6.0.0

ng-bootstrap:2.2

Bootstrap:4.1.1

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we need a minimal reproduce scenario is plunker / stackblitz to be able to progress on this one: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't heard back with the reproduce scenario...

**Comment by zeeshany1996** [comment]
when  double click button open modal  then close modal it throw error
i am using ngb-Modal ("ngb-modal": "^2.0.3") 

Error: Uncaught (in promise): NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
