### ISSUE TITLE
[TypeAhead] Blur happens before selectItem

### ISSUE THREAD

**Issue by wilhelmhb** [ng-bootstrap/ng-bootstrap#2504]
### Bug description:
When selecting a proposal with a cursor, the input field looses the focus. This triggers a blur event, while the value is not set yet.
I have a use case where I add a layer of computation on blur, and this behavior is very confusing.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/If566V0cTjXMdCfWiIZ7?p=preview
Enter "jo", then *click* a proposal... If you *press Enter* instead of clicking, the blur event is not triggered at all.

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 5.2.10 and 6.0.0

ng-bootstrap: 1.1.2 and 2.2.0

Bootstrap: 4.0.0 and 4.1.1

**Comment by pkozlowski-opensource** [comment]
> When selecting a proposal with a cursor, the input field looses the focus. This triggers a blur event, while the value is not set yet.

This is normal and expected. This is the sequence of events:
* input has focus
* you type something in the input field - results are shown
* you _move_ a mouse and _click_ on an item - the input looses focus
* items gets selected in response to `click` event - the  `selectItem` fires

This is natural and expected flow of events: selecting an item with a click means getting focus out of a text fields. You might want to re-evaluate where you place the " layer of computation" as we can't change the sequence of events.

Hard to say more without understanding the exact use-case so I'm going to close this issue for now. Happy to continue discussion if / when you can provide more info about your use-case.
