### ISSUE TITLE
Popover issue inside the datatable

### ISSUE THREAD

**Issue by xyrintech** [ng-bootstrap/ng-bootstrap#2513]
### Bug description:
Popover hides when used in ngx-datatable, please see the screenshot below

![rank issue](https://user-images.githubusercontent.com/7784136/42528455-1fb0fca8-8499-11e8-8590-490dc818b593.png)

### Link to minimally-working plunker that reproduces the issue:
I understand you need a demo for this to reproduce but if possible then kindly see if the above screenshot resolves the purpose. If you still need a demo then I will setup one for you. 

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.x
ng-bootstrap: ^2.0.0
Bootstrap:4.0.0

**Comment by maxokorokov** [comment]
@xyrintech also try checking your CSS styles (positioning, z-indexes, etc.), attaching popover to the body with `container='body'` (see demo examples and API for this). 

But we can't heal (if there is anything to heal) using a photograph :)

**Comment by xyrintech** [comment]
This container thing solves this, thanks for looking into this.
