### ISSUE TITLE
Cannot apply CSS to modal-content for NgbModal

### ISSUE THREAD

**Issue by andrewryan1906** [ng-bootstrap/ng-bootstrap#2515]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

When I try to apply CSS to the **modal-content** DIV, it does not apply. I can appy to modal-header/modal-body, but not modal-content. I am trying to round the corners of the modal popup box.

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.2

ng-bootstrap: 2.0.0

Bootstrap: 4

**Comment by pkozlowski-opensource** [comment]
You _might_ be looking for the `windowClass` option to the `.open(...)` method: https://ng-bootstrap.github.io/#/components/modal/api#NgbModalOptions

But this is just a guess, it is not clear what you are trying to do and what is not working. Try to provide more context and ask a support question using a dedicated channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
