### ISSUE TITLE
select several days, no range of days in datepicker

### ISSUE THREAD

**Issue by luisitocaiza17** [ng-bootstrap/ng-bootstrap#2517]
How can I select several days in the calendar (no date range, example: July 1, July 10, July 25)
I do not find documentation of how to do it, I need help please

![imagen](https://user-images.githubusercontent.com/6414432/42610007-0c9b0d22-8555-11e8-8beb-3d088db64b9b.png)

**Comment by maxokorokov** [comment]
Please use an appropriate support channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help

However, check the [source code of the demo](https://github.com/ng-bootstrap/ng-bootstrap/blob/83930cd84190a077f0305b4f450b1485546bd874/demo/src/app/components/datepicker/overview/demo/datepicker-overview-demo.component.ts#L45-L46):
- you need `(dateSelect)` and a custom `[dayTemplate]`
- you need a `Set` of dates in your model
- when you select a date, add it to your `Set`
- when you render the template, check if it's inside of your `Set` to render it differently
