### ISSUE TITLE
demo site: scrolling to fragment doesn't work

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#2529]
Currently scrolling to fragments in the router doesn't work: ex. https://ng-bootstrap.github.io/#/components/buttons/examples#radio will not scroll to the radio example

Angular fix for this should land in 6.1 with `ViewPortScroller`

To be fixed after #2520 lands

**Comment by pkozlowski-opensource** [comment]
Fixed in fd76e4b0f4ff3379f509cc8cc11dc467174bbdb6, will be deployed today.
