### ISSUE TITLE
Typeahead checks if falsy but tries to get .length of potentially null value and that throws an error 

### ISSUE THREAD

**Issue by matjazonline** [ng-bootstrap/ng-bootstrap#2530]
### Bug description:
The issue is at 'const count = results.length;' typeahead.ts:360 when 'results' value is null.
The workaround is to pass empty array to items observable, but at the top of this method null is expected: 'if (!results || results.length === 0) {'

Console error:

global-error-handler.ts:37 client error:  TypeError: Cannot read property 'length' of null
    at SafeSubscriber._next (typeahead.js:238)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:195)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next (Subscriber.js:133)
    at ...

**Comment by pkozlowski-opensource** [comment]
Here is a reproduction scenario: https://stackblitz.com/edit/angular-metn4u?file=app/typeahead-basic.ts

We do assume that empty results should be denoted by `[]` but maybe we should protect against null / undefined / not an array...
