### ISSUE TITLE
NgbTypeahead  fromEvent does not exist in rxjs

### ISSUE THREAD

**Issue by GrayYoung** [ng-bootstrap/ng-bootstrap#2538]
I am using angualr 5, rxjs 5.5.11, ng-bootstrap 2.0.0. If I add [ngbTypeahead] on a html element, I will get the error below：

ERROR TypeError: rxjs_1.fromEvent is not a function at new NgbTypeahead (typeahead.js:66)

fromEvent exist in rxjs_1.Observable, but not rxjs_1.

**Comment by pkozlowski-opensource** [comment]
> I am using angualr 5, rxjs 5.5.11, ng-bootstrap 2.0.0.

To use ng-bootstrap 2.0.0 you _must_ use Angular 6.x and a compatible RxJS version. (https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#200-2018-05-04)
You should have gotten warning from npm / yarn.

Either upgrade your Angular / RxJS versions (recommend) or use version of ng-bootstrap compatible with Angular 5 (https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#111-2018-04-06)
