### ISSUE TITLE
alert: remove superfluous <div> tag

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#2544]
As of today `<ngb-alert>` doesn't set Bootstrap classes on a host but [adds a `<div>` inside](https://github.com/ng-bootstrap/ng-bootstrap/blob/e0c005082f11f811ecc6e723e27ec029eb29770a/src/alert/alert.ts#L18). This is an issue for animations and prevents people from properly styling the alert's host (see https://stackoverflow.com/questions/51450796/apply-classes-to-sub-elements-of-components/51451075 and #2542 as an example). 

We should remove [this `<div>`](https://github.com/ng-bootstrap/ng-bootstrap/blob/e0c005082f11f811ecc6e723e27ec029eb29770a/src/alert/alert.ts#L18) and set classes (and `role="alert"` directly on the host).

**Comment by pkozlowski-opensource** [comment]
Note to self: we might need to set `display: block` as well (if Bootstrap classes don't do this).

**Comment by maxokorokov** [comment]
@pkozlowski-opensource, opened a PR to see what it gives. On the one hand more logic because of dynamic css class names, on the other hand it's possible to add a class directly...
