### ISSUE TITLE
Pagination event doesn't work on ie11

### ISSUE THREAD

**Issue by Tchougbe** [ng-bootstrap/ng-bootstrap#2545]
### Bug description:

I'm using component "Pagination" in my project like this: 

```
    <ngb-pagination [collectionSize]="40"
                    (pageChange)="pageChanged($event)"
                    [(page)]="page" aria-label="Default pagination" [maxSize]="5" [pageSize]="8"></ngb-pagination>

```
It's works well unless under ie11. When user change page, no event is fired so I never go through my function "pageChanged". I look at event listeners for this element in the console , nothing is show. 

I try to reproduce it in a plunker (by forking one from your demo) but i can't make it with this version of ng-bootstrap (1.0.0) .
Is there any way to make my project works without updating ng-bootstrap and angular ? 

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.7

ng-bootstrap: 1.0.0

Bootstrap: 4.0.0

**Comment by pkozlowski-opensource** [comment]
`1.0.0` is a 6-month-old version so we are unlikely to patch it. Please provide a minimal reproduce scenario with the latest Angular / ng-bootstrap so we can confirm the issue.

**Comment by Tchougbe** [comment]
Hi,

Thanks for your reply.
In fact, it was not an issue , I add polyfills es6 to my project and it's resolve the problem.
