### ISSUE TITLE
Tooltip using ng-bootstrap on SVG elements not showing

### ISSUE THREAD

**Issue by vishalbedre** [ng-bootstrap/ng-bootstrap#2546]
Hi All,
I created circle using D3.js. I used ng-bootstrap for Tooltip but It is not showing on svg element.

`g.append("g").selectAll("circle").data(this.RecordDaily).enter().append("circle")
                               .attr("r", 5).attr("fill", "purple")
                               .attr("cx", function (d) { return x(parseTime(d.moy)); })
                               .attr("cy", function (d, i) { return y(d.session); })
                               .attr("data-toggle", "tooltip").attr("title", function (d) { return d.session })
                               .attr("ngbTooltip",  function (d) { return d.session })
                               .attr("placement",  "top")`

**Comment by pkozlowski-opensource** [comment]
This is not how Angular works - directives are not matched on dynamically inserted nodes. This is not specific to ng-bootstrap and there is nothing in this project we can do about it.

Closing as a support request.
