### ISSUE TITLE
PreventDefault on modal 'escape' event when modal closed

### ISSUE THREAD

**Issue by ProfessorBleedy** [ng-bootstrap/ng-bootstrap#2556]
Currently when "Escape" is used to close a modal, the event is consumed by the modal but keeps bubbling up to the parent and above. 

In the old Angular-ui/bootstrap there had been a fix in place where this event once consumed by the modal would call $event.preventDefault() which we were able to look for downstream, and act accordingly. 

There is a scenario in my app where on a View the user is able to open a sub window which should persist. The user can also open an ng-bootstrap modal over all this. but hitting 'escape' closes both windows rather than just the bootstrap modal, because the event bubbles. 

The fix is pretty straightforward unless there is a reason to not include this functionality i'm happy to submit a PR for this. 

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.10

ng-bootstrap: 1.1.2

Bootstrap: 4.1.1

**Comment by pkozlowski-opensource** [comment]
Not sure what you mean by "the event is consumed by the modal" - we just listen to this even an close modal if ESC key press is detected.

If I understand correctly, you would like us to call `preventDefault()` on the DOM keyboard event (`ESC` key)?  To be honest I'm 50/50 on this - I can see how it could be helpful in your case but I'm not sure if this is an acceptable practice...

Couldn't you listen to modal's dismiss from ESC (https://github.com/ng-bootstrap/ng-bootstrap/blob/25b5bee6ffb81ab8abeefc27e43901ad4e279f7a/src/modal/modal-window.ts#L61) and base your logic on this?

**Comment by pkozlowski-opensource** [comment]
Closing for now as we haven't heard back. Happy to continue the discussion, though.

**Comment by superbazza** [comment]
Same issue. Its not clear to me how I can work around it with the current api.

The ESC press event that dismisses the dialog is propagated to other listeners.
There is no way (that I can think of) for the other listeners to ignore this particular escape-press .. because  even if they have access to the modal state, the model is closed before the event is propagated.

Unless someone has some suggestions?

>> Couldn't you listen to modal's dismiss from ESC and base your logic on this?
Not sure I understand what you mean - can you expand?

**Comment by superbazza** [comment]
Would be nice to have an option to swallow (ie preventDefault()) on ESC event
