### ISSUE TITLE
(regression from 2.2.0): ngbDropdownMenu does not disappear when clicked if ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by AbakumovAlexandr** [ng-bootstrap/ng-bootstrap#2559]
### Bug description:
When using `ngbDropdownMenu` in a `ChangeDetectionStrategy.OnPush` component, it stopped disappearing after a user clicks on it. It worked fine in the version 2.2.0.

### Link to minimally-working plunker that reproduces the issue:
https://stackblitz.com/edit/ng-bs-menu-item-not-disappear-test

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 6.1.0
ng-bootstrap: 2.2.1
Bootstrap: 4.1.2

**Comment by maxokorokov** [comment]
Thanks for reporting, cause is missing `cd.detectChanges()` after popup closing. Will open a PR

**Comment by AbakumovAlexandr** [comment]
@maxokorokov , thanks for fixing it!

One question, please (hopefully, it's not dumb :). Looking at the latest `dropdown.ts`, I've noticed this:
```
  ngOnDestroy() {
    this._closed$.next();
    this._zoneSubscription.unsubscribe();
  }

```Why can't we just do the following instead of `this._zoneSubscription.unsubscribe();` as is with other subscriptions throughout the `dropdown.ts`?
```
        _ngZone.onStable.pipe(takeUntil(this._closed$)).subscribe(() => this._ngZone.run(() => {
          this.close();
          this._changeDetector.markForCheck();
}));

```

**Comment by maxokorokov** [comment]
@AbakumovAlexandr we certainly could and probably should ;)

**Comment by AbakumovAlexandr** [comment]
@maxokorokov , Cool :) I was just curious if there is something special about this subscription which prevents from doing it. Thank you!
