### ISSUE TITLE
NgbDatepicker to months and years only

### ISSUE THREAD

**Issue by HRSamy** [ng-bootstrap/ng-bootstrap#2563]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
I'm using NgbDatepicker with angular 4.  I understand this control is meant for "date" picker. But I have a requirement to show months in the popup. Would that be possible to customize NgbDatepicker  to show months for an selected year?

Thanks

Angular: 4

ng-bootstrap: 

Bootstrap:

**Comment by pkozlowski-opensource** [comment]
>  Would that be possible to customize NgbDatepicker to show months for an selected year?

We don't have such functionality yet but it is already tracked as a feature request in #1811
Closing as a duplicate of #1811

**Comment by gmengi** [comment]
i'm looking for only month & year picker in version of angular 5.
