### ISSUE TITLE
CSS Variables: allow styling of ng-Bootstrap by their host angular components css file

### ISSUE THREAD

**Issue by redevill** [ng-bootstrap/ng-bootstrap#2564]
### Feature Request description:
Styling ng-Bootstrap widgets can be a challenge. 
Especially with /deep/ ::shadow being deprecated. 
By using CSS variables in the bootstrap styling, consumers of the widgets (i.e. Other angular components, with ViewEncapsulation enabled) could then specify override values for these CSS variables. 

Just think, in the local CSS for your component, you could specify a CSS variable value for the background color of the ngb-accordion, and it would set it 'accordingly' ;0

See Excerpt below:
https://developers.google.com/web/updates/2016/02/css-variables-why-should-you-care?hl=en
"This technique is especially useful for theming Web Components that use Shadow DOM, as custom properties can traverse shadow boundaries. A Web Component author can create an initial design using fallback values, and expose theming “hooks” in the form of custom properties."

**Comment by redevill** [comment]
Changing the encapsulation mode would, I believe, allow for external changes. But this is akin to using all global variables, and make it quite difficult to keep Global styles from unintended affects.

**Comment by jessycormier** [comment]
In my opinion I think this is what I would want and expect when using a style framework like Bootstrap :) This way 'themes' can easily downloaded and applied for example.

would it be possible to have it programmatically change the encapsulation?

**Comment by strizzwald** [comment]
Should this be closed? I cannot follow @CharlyRipp's approach, I've checked the  `@ng-bootstrap` node module and the `SCSS` is not copied into the library. What do we do in this case?

ng-bootstrap version: `11.0.0-beta.1`

**Comment by redevill** [comment]
It has been a couple of years since I first logged this issue. I am now using a higher version of ng-bootstrap in a project that uses scss. I have not explicitly checked that the accordion background can be changed with the newer version setup. I will try and do that, and get back.

**Comment by strizzwald** [comment]
Thanks @redevill. I have tried this with the latest version of ng-bootstrap. There are no `scss` theming variables  that can be overridden. I've resorted to installing both `ng-bootstrap` and `bootstrap` node modules to override the variables. Obviously not great, but I couldn't find any other solutions.

**Comment by redevill** [comment]
Does not look like anything has changed in the last almost 5 years. It still can't be styled, and the powers at be close these issues without a thought. 

The reason I opened this Feature request was to give a legit method by which this need could be addressed, and not the bogus "View Encapsulation Turned off" which is NOT a solution. Equivalent to saying you must use Global variables only! - Ridiculous.

this has been an issue back to 2016 - https://github.com/ng-bootstrap/ng-bootstrap/issues/1107
Consider using another Library - https://valor-software.com/ngx-bootstrap/#/documentation
