### ISSUE TITLE
Dropdown doesn't close on outside click

### ISSUE THREAD

**Issue by maxkorz** [ng-bootstrap/ng-bootstrap#2567]
### Bug description:
[Dropdown](https://ng-bootstrap.github.io/#/components/dropdown/examples) doesn't close on outside click when `changeDetection` is set to `ChangeDetectionStrategy.OnPush,`

### Link to minimally-working plunker that reproduces the issue:
https://stackblitz.com/edit/angular-f6xbnu?file=app/dropdown-basic.ts

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 6.1.0
ng-bootstrap: 2.2.1
Bootstrap: 4.0.0

**Comment by maxkorz** [comment]
dup https://github.com/ng-bootstrap/ng-bootstrap/issues/2559

**Comment by pkozlowski-opensource** [comment]
Yep, sorry, we are going to release `2.2.2` with a fix tomorrow.
