### ISSUE TITLE
Put in place plunkers infrastructure for demos

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#257]

**Comment by pkozlowski-opensource** [comment]
If we can't have it ready for the alpha.0 release we should remove plunker's icon from the example box.

**Comment by pkozlowski-opensource** [comment]
@Foxandxss so for plunkers we will need non-highlighted version of our code and currently I can think of the following options:
1.  Load raw files and do higlighting on the client side (pros: no need to load higlighted version, cons: need to load prism and spend time higlighting on the client side)
2.  Load both higlighted and raw version (pros: no need to load prism, no processing on the client-side, cons: need to load snippets in 2 forms)

I'm slightly leaning towards loading higlighted and non-higlighted version (option 2). Thoughts?

**Comment by Foxandxss** [comment]
I don't see what you mean. We don't need highlight nor anything for plunker, just the real files on their folders.
