### ISSUE TITLE
No way for crawl bots to navigate using pagination control, even on a Angular Universal SSR pages

### ISSUE THREAD

**Issue by ChrisDevinePimss** [ng-bootstrap/ng-bootstrap#2580]
### Bug/Feature description:

When using the Pagination component with Angular Universal, there is noway for a search bot/web crawler to know to use the pagination control. 

Would be nice when being server side rendered if it used <anchor> tags with HRefs inside to navigate to the next page. 

This would make SEO a lot easier and enable crawl bots to properly index all the content

### Link to minimally-working plunker that reproduces the issue:

Unable to reproduce in plunkr as this is server side rendered issue.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6 

ng-bootstrap: 4

Bootstrap: 4

**Comment by pkozlowski-opensource** [comment]
> Would be nice when being server side rendered if it used tags with HRefs inside to navigate to the next page.

How would you do it? That is, what would you expect in the `href`?

Generally speaking this pagination control is meant to paginate through results on the client-side so I'm not sure how this could work with SSR.

Could you elaborate on your exact use-case?

**Comment by ChrisDevinePimss** [comment]
**How would you do it? That is, what would you expect in the href?**
Thats the hard part i suppose but i suppose a link to the same page but with next page of results. 

The way i currently do this (bit hacky).

i have anchor tag that is only present on the page that is generated (so the bots will get it). This then contains a anchor tag with necessary query parameters to populate the page correctly, when a bot navigates to the link. 

Now this works and fixes the bot issue but its less then desirable way to do it.

Now i am unsure how we could incorporate this behaviour in a generic way for the Pagination control, as it would require Pagination data, as well as any filter/sort data. I am hoping people smarter than me may be able to brainstorm on the issue.

**Generally speaking this pagination control is meant to paginate through results on the client-side**

Again true but this would enhance the functionality to also make it work with crawl bots.

Example if i had a list of products in a paged view, only the products on the first page would be indexed by a crawl bot. Meaning all other pages do not. 

**My Opinion**
The pagination control works great client side and for users but lacks usability for crawl bots. Meaning some adopters may suffer getting there websites indexed and SEO would be rather a lot of extra work

**Comment by ChrisDevinePimss** [comment]
The way i would do it, may be very wrong so feel free to shoot it down but what if there was an extra button in the pagination control, generated on server side rendered page only. 

You could then have an input in the pagination control that we could pass a URL to this button. The url passed should be one that navigates to the next page. 

This button should be a anchor with a href to bots and not appear once the angular app replaces the page. 

I know this seems shoddy but its a starting point to develop from :)

**Comment by pkozlowski-opensource** [comment]
After pondering this for a while I don't have any great idea on how to make it in the generic way. The issue with the proposed additional button + URL is that it might be sufficient for your case but then there will be users that will say, hey, I want to have 2 buttons (ex. prev and next results). Or all buttons. It all would depend on what users are pre-generating on the server side and we can't guess it.

I'm going to close it for now as I really don't see any API that would be more helpful as compared to what you are doing already. We can definitely keep the discussion going on here and if anyone comes up with a good solution / API, we can re-open.

**Comment by vdg437** [comment]
Any updates on this?

**Comment by Routhinator** [comment]
My 2 cents here, because this is desperately needed, would be to have an optional configuration for 'static links' that uses a page query/url param and value, allowing the developer implementing the pagination to configure the param. And then leave it to the developer to conditionally apply this configuration to the pagination in their component when SSR renders the site.
