### ISSUE TITLE
ChangeDetectionStrategy.OnPush on ngbCarousel not working

### ISSUE THREAD

**Issue by Jonas-Args** [ng-bootstrap/ng-bootstrap#2597]
when I implement ChangeDetectionStrategy.OnPush ngbcarousel doesn't work with atuomatic intervals

**Comment by pkozlowski-opensource** [comment]
Confirmed, here is a reproduce scenario: https://stackblitz.com/edit/angular-uykamz?file=app/carousel-basic.ts

We should do `markForCheck()` when interval fires.
