### ISSUE TITLE
RadioButton uncheckable

### ISSUE THREAD

**Issue by Zwergenpunk** [ng-bootstrap/ng-bootstrap#2598]
I did not find any issue about that, so I thought I open one:

I would like to have the feature of uncheckable radio buttons like in [ui-bootstrap](https://angular-ui.github.io/bootstrap/#!#buttons)

Is the feature planned, dissmissed or did just nobody thought about it ;) ?

**Comment by pkozlowski-opensource** [comment]
No, we don't have it yet, marking as a feature request.

**Comment by Zwergenpunk** [comment]
Hey,

I had some time tonight and implemented the uncheckable buttons. 
Unfortunatelly I cannot get the commit done. 

I know that is the best place to discuss that, but I have no other idea ;).

The validate-commit.js has no third argument and so the git commit validation throws an exception.
I tried with commiting with a normal message (-m) and commiting with the message in a file (-F)

Can someone explain what I'm doing wrong?
