### ISSUE TITLE
Tree shaking doesn't work with 3.0.0 release

### ISSUE THREAD

**Issue by maxkorz** [ng-bootstrap/ng-bootstrap#2605]
1. `ng new ng-bootstrap-bug && cd ./ng-bootstrap-bug`
2. `npm i @ng-bootstrap/ng-bootstrap`
3. `npm i --save-dev webpack-bundle-analyzer`
4. Follow [Getting Started instructions](https://ng-bootstrap.github.io/#/getting-started) - Import main module:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    NgbModule,
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
5. Analyze bundle: `ng build --stats-json && npx webpack-bundle-analyzer dist/ng-bootstrap-bug/stats.json`
Result: 902kb
![image](https://user-images.githubusercontent.com/25089646/44032478-e2691826-9f0f-11e8-9767-af87fdf47c43.png)
6. Follow instructions to decrease bundle size: `...only import modules with components you need, ex. pagination and alert. The resulting bundle will be smaller in this case.`
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { NgbPaginationModule, NgbAlertModule } from '@ng-bootstrap/ng-bootstrap';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    NgbPaginationModule,
    NgbAlertModule
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
7. Analyze bundle: `ng build --stats-json && npx webpack-bundle-analyzer dist/ng-bootstrap-bug/stats.json`
Result: 902kb
![image](https://user-images.githubusercontent.com/25089646/44032616-4eddc74a-9f10-11e8-86af-88187d7205c6.png)
8. Downgrade to version 2.2.2: `npm i @ng-bootstrap/ng-bootstrap@2.2.2`
9. Analyze bundle: `ng build --stats-json && npx webpack-bundle-analyzer dist/ng-bootstrap-bug/stats.json`
Result: 293kb (still not perfect, I did not import DatePicker and Typeahead, but I can still see them in the bundle, but 293kb is not 902kb)
![image](https://user-images.githubusercontent.com/25089646/44032724-a95decd6-9f10-11e8-8b09-555465559585.png)

**Comment by pkozlowski-opensource** [comment]
Those are not production builds, right? Did you do tests with production builds (AoT and build optimiser)?

**Comment by maxokorokov** [comment]
@maxkorz, concerning the bundle size, please check what you're getting in the end. Also check with source-map explorer. I think the numbers you're seeing are not final and they're actually improved by about ~30Kb. 

Ex. built with `cli 6.1.3`.

```ts
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    NgbModule,
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

ng-bootstrap@2.2.2

```ts
➜  ng-bootstrap-bug git:(master) ✗ ng build --stats-json --prod --source-map true                                                         
Date: 2018-08-13T13:00:49.004Z
Hash: 1009bcf431b29ade8a77
Time: 36211ms
chunk {0} runtime.a66f828dca56eeb90e02.js, runtime.a66f828dca56eeb90e02.js.map (runtime) 1.11 kB [entry] [rendered]
chunk {1} styles.cdd3d4a4da4b3f2362bc.css, styles.cdd3d4a4da4b3f2362bc.css.map (styles) 59 bytes [initial] [rendered]
chunk {2} polyfills.4f7c913f053a853649ef.js, polyfills.4f7c913f053a853649ef.js.map (polyfills) 59.6 kB [initial] [rendered]
chunk {3} main.0dafdc8267cdec25420e.js, main.0dafdc8267cdec25420e.js.map (main) 283 kB [initial] [rendered]
```

![screen shot 2018-08-13 at 15 25 25](https://user-images.githubusercontent.com/8074436/44034357-34ab00c0-9f0d-11e8-804e-12ee08a2bc8f.png)


ng-bootstrap@3.0.0

```ts
➜  ng-bootstrap-bug git:(master) ✗ ng build --stats-json --prod --source-map true
Date: 2018-08-13T13:09:04.376Z
Hash: 0980283cfc76ea9ece46
Time: 75809ms
chunk {0} runtime.a66f828dca56eeb90e02.js, runtime.a66f828dca56eeb90e02.js.map (runtime) 1.11 kB [entry] [rendered]
chunk {1} styles.cdd3d4a4da4b3f2362bc.css, styles.cdd3d4a4da4b3f2362bc.css.map (styles) 59 bytes [initial] [rendered]
chunk {2} polyfills.4f7c913f053a853649ef.js, polyfills.4f7c913f053a853649ef.js.map (polyfills) 59.6 kB [initial] [rendered]
chunk {3} main.59aa312009bff2a16222.js, main.59aa312009bff2a16222.js.map (main) 250 kB [initial] [rendered]
```

![screen shot 2018-08-13 at 15 25 16](https://user-images.githubusercontent.com/8074436/44034372-3bc8c004-9f0d-11e8-8470-578c9ab6c8e2.png)

**Comment by pkozlowski-opensource** [comment]
@maxokorokov could you please also add a test for a single module (ex.:  `import { NgbPaginationModule } from '@ng-bootstrap/ng-bootstrap'`)

**Comment by maxokorokov** [comment]
For the case when you're including only `NgbAlertModule` and `NgbPaginationModule`:

ng-bootstrap@3.0.0

```ts
➜  ng-bootstrap-bug git:(master) ✗ ng build --stats-json --prod --source-map true                                        
Date: 2018-08-13T13:28:34.656Z
Hash: e421459181ffb3dcbff7
Time: 42597ms
chunk {0} runtime.a66f828dca56eeb90e02.js, runtime.a66f828dca56eeb90e02.js.map (runtime) 1.11 kB [entry] [rendered]
chunk {1} styles.cdd3d4a4da4b3f2362bc.css, styles.cdd3d4a4da4b3f2362bc.css.map (styles) 59 bytes [initial] [rendered]
chunk {2} polyfills.4f7c913f053a853649ef.js, polyfills.4f7c913f053a853649ef.js.map (polyfills) 59.6 kB [initial] [rendered]
chunk {3} main.c148563c9508cdb5a033.js, main.c148563c9508cdb5a033.js.map (main) 176 kB [initial] [rendered]
```

![screen shot 2018-08-13 at 15 34 06](https://user-images.githubusercontent.com/8074436/44034858-71af57cc-9f0e-11e8-972b-7f432563ad77.png)

**Comment by maxokorokov** [comment]
Please note though, that I'm **not using** any of the components in the examples, just adding module dependencies. What is left from ng-bootstrap is mostly things declared in `entryComponents`.

**Comment by maxkorz** [comment]
Hmm... True,

Version 2.2.2
`import { NgbModule } from '@ng-bootstrap/ng-bootstrap';`
```
chunk {3} main.c138ace030bebf5ba39a.js (main) 282 kB [initial] [rendered]
```

`import { NgbPaginationModule, NgbAlertModule } from '@ng-bootstrap/ng-bootstrap';`
```
chunk {3} main.0333e97bcad267d40298.js (main) 176 kB [initial] [rendered]
```

```
import { NgbPaginationModule } from '@ng-bootstrap/ng-bootstrap/pagination/pagination.module';
import { NgbAlertModule } from '@ng-bootstrap/ng-bootstrap/alert/alert.module';
```
```
chunk {3} main.0333e97bcad267d40298.js (main) 176 kB [initial] [rendered]
```

Version 3.0.0
`import { NgbModule } from '@ng-bootstrap/ng-bootstrap';`
```
chunk {3} main.5ccb21d4bd3dff339fa7.js (main) 250 kB [initial] [rendered]
```

`import { NgbPaginationModule, NgbAlertModule } from '@ng-bootstrap/ng-bootstrap';`
```
chunk {3} main.e2a0d3bf12311ec6fec4.js (main) 176 kB [initial] [rendered]
```

False alarm then? `webpack-bundle-analyzer` displays wrong info?

**Comment by maxokorokov** [comment]
@maxkorz I think that it displays stats before `UglifyJS` removes unused code

If you hover the `main.ts`, you'll also see `parsed` and `gzipped` code which is closer to reality, but I've no idea how it is calculated

![screen shot 2018-08-13 at 15 46 15](https://user-images.githubusercontent.com/8074436/44035702-5e31bc92-9f10-11e8-87bb-a8b0a4460c3e.png)

**Comment by maxokorokov** [comment]
No pb, thanks for looking into new release

**Comment by maxokorokov** [comment]
Amending numbers for the ng-bootstrap `4.0.1` here for reference:

Cli `7.1` and ng-bootstrap `4.0.1` I'm getting:

```ts
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    NgbModule,
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

```ts
Date: 2018-12-18T11:07:44.841Z
Hash: 3f01ad2b4b5a333a2533
Time: 38746ms
chunk {0} runtime.ec2944dd8b20ec099bf3.js, runtime.ec2944dd8b20ec099bf3.js.map (runtime) 1.46 kB [entry] [rendered]
chunk {1} main.e7dfcd073cb6f4238616.js, main.e7dfcd073cb6f4238616.js.map (main) 252 kB [initial] [rendered]
chunk {2} polyfills.e09b5fecb7879f659f76.js, polyfills.e09b5fecb7879f659f76.js.map (polyfills) 37.5 kB [initial] [rendered]
chunk {3} styles.23474c25f308bf4c5816.css, styles.23474c25f308bf4c5816.css.map (styles) 59 bytes [initial] [rendered]
```

![screen shot 2018-12-18 at 12 08 54](https://user-images.githubusercontent.com/8074436/50150524-803c7b80-02be-11e9-9b7f-e5f98842c8e0.png)


---

When including only two modules  `NgbAlertModule` and `NgbPaginationModule`:

```ts
import {NgbAlertModule, NgbPaginationModule} from '@ng-bootstrap/ng-bootstrap';

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    NgbAlertModule,
    NgbPaginationModule
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

```ts
Date: 2018-12-18T11:09:16.465Z
Hash: 9846a0347d2fea1107b8
Time: 36590ms
chunk {0} runtime.ec2944dd8b20ec099bf3.js, runtime.ec2944dd8b20ec099bf3.js.map (runtime) 1.46 kB [entry] [rendered]
chunk {1} main.88fe051e509d25fd751a.js, main.88fe051e509d25fd751a.js.map (main) 179 kB [initial] [rendered]
chunk {2} polyfills.e09b5fecb7879f659f76.js, polyfills.e09b5fecb7879f659f76.js.map (polyfills) 37.5 kB [initial] [rendered]
chunk {3} styles.23474c25f308bf4c5816.css, styles.23474c25f308bf4c5816.css.map (styles) 59 bytes [initial] [rendered]
```

![screen shot 2018-12-18 at 12 10 19](https://user-images.githubusercontent.com/8074436/50150590-b974eb80-02be-11e9-95b2-ff9869915bbc.png)
