### ISSUE TITLE
Datepicker: Highlight and font hover boundaries

### ISSUE THREAD

**Issue by softwareishappiness** [ng-bootstrap/ng-bootstrap#2613]
I have a Datepicker that has highlight and font over boundary conflict or issue. I am unsure which. Please see screen shot.

![ng-bootstrap_issue](https://user-images.githubusercontent.com/4998003/44119385-0c959854-9fe7-11e8-9943-c6addd829975.png)

If I click outside of the Datepicker then the highlight "snaps" back to what I expect. It's impossible to inspect using Chrome tools since this behavior is tied to mouse event(s).

![ng-bootstrap_issue_](https://user-images.githubusercontent.com/4998003/44120754-6013251a-9feb-11e8-966a-7371ac31913c.png)

Is the CSS for this component "scoped" or limited to itself? This occurs in Chrome, FF and Edge

```
    <!-- Begin: Date Component -->
      <div *ngIf="showDate" class="input-group" style="width: 170px">
          <input class="form-control" placeholder="yyyy-mm-dd"
                 name="{{ name + 'Date' }}" [(ngModel)]="dateValue"
                 (dateSelect)="onDateChange($event, question, answers[2])" 
                 ngbDatepicker #d="ngbDatepicker">
          <div class="input-group-append">
              <button class="btn btn-outline-secondary" (click)="d.toggle()" type="button">
                  <img id="calendar-icon"
                       src="//ms.dev.softwareishappiness.com/static/survey/img/calendar-icon.svg"
                       style="width: 1.2rem; height: 1rem; cursor: pointer;"/>
              </button>
          </div>
      </div>
      <!-- End: Date Component -->
```

**Comment by pkozlowski-opensource** [comment]
Sorry, but it is impossible to help just based on the provided screenshots and code snippet - we will need a minimal reproduce scenario using stackblitz as requested in the issue template: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

>  It's impossible to inspect using Chrome tools since this behavior is tied to mouse event(s).

You can try setting `autoClose` to `false` so there is less interaction with mouse events.

In any case we need a minimal reproduce scenario to be able to help. We are also missing crucial info like version of software used, any custom CSS etc. This is why we are insisting on a minmal reproduce scenario: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

**Comment by softwareishappiness** [comment]
Thanks for the quick feedback. I will try the setting your suggested and reply back via Stackblitz if necessary.

**Comment by pkozlowski-opensource** [comment]
Haven't heard back so going to close this one for now. Happy to re-open when you've got a reproduce scenario.
