### ISSUE TITLE
Source-code of  "@ng-bootstrap/ng-bootstrap": "1.1.0"

### ISSUE THREAD

**Issue by kedar9444** [ng-bootstrap/ng-bootstrap#2615]
#Question : How to get source code for earlier version of ng-bootstrap?
i.e "@ng-bootstrap/ng-bootstrap": "1.1.0"

**Comment by pkozlowski-opensource** [comment]
It is tagged here: https://github.com/ng-bootstrap/ng-bootstrap/releases/tag/1.1.0

From there you can either download source code bundle or just browse it on GitHub: https://github.com/ng-bootstrap/ng-bootstrap/tree/1.1.0

**Comment by kedar9444** [comment]
@pkozlowski-opensource  opensource thanks a ton.

**Comment by kedar9444** [comment]
@pkozlowski-opensource: 
not able to serve the project on ng serve getting following error.
`paritked@WL309055 MINGW64 /c/Work/ng-bootstrap/1
$ ng serve
This command can only be run inside of a CLI project.
`

 **angular-cli.json** file is missing for tag 1.1.0, and **package.json** don't have details related angular cli version. is it missing or i am checking it on wrong place?

**Comment by pkozlowski-opensource** [comment]
`1.1.0` was _not_ using CLI

**Comment by kedar9444** [comment]
@pkozlowski-opensource : Then how to run the application on local, since i need to modify the library for **WCAG compliance** and want to create a **custom npm package** of **version 1.1.0**. can you **help/ guide** me on this?

**Comment by kedar9444** [comment]
@pkozlowski-opensource: will i get any support for this?
