### ISSUE TITLE
NgbDateNativeAdapter provided in app.module sems not be considered

### ISSUE THREAD

**Issue by MichaelPruefer** [ng-bootstrap/ng-bootstrap#2618]
### Bug description:
When providing the NgbDateNativeAdapter in app.module.ts with 
`typescript
providers: [
    { provide: NgbDateAdapter, useClass: NgbDateNativeAdapter }
  ]
`

my model value is bound to a NgbDateStruct-Value representing the selected date. 
I expected it to be a "native" date, as transformed by NgbDateNativeAdapter.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/lkfKKxk63EjuoVWJrpiT?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.1.3

ng-bootstrap: 3.0.0

Bootstrap: 4.1.3

**Comment by omardoma** [comment]
The adapter does not work if you provide it in the AppModule and then use the DatePicker in a Lazy Loaded Feature module, I had to provide the adapter in the Feature module itself, in order that it can work.

**Comment by omardoma** [comment]
It used to work before v3.0.0

**Comment by pkozlowski-opensource** [comment]
We can confirm it as a bug / regression in 3.0.0 - will fix in next release (to be cut early next week). Thnx for reporting!

**Comment by omardoma** [comment]
Great, you are welcome, and keep up the good work!
