### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by xyrintech** [ng-bootstrap/ng-bootstrap#2637]
Is there any option to execute a function on panel click and and it returns true then it open the accordion?
OR
Is there anyway we can add a checkbox on accordion panel and prevent changing the accordion expand or collapse?

**Comment by pkozlowski-opensource** [comment]
> Is there any option to execute a function on panel click and and it returns true then it open the accordion?

Not quite, but you can get the effect by listening to the `panelChange` event and call `preventDefault()` to veto open / close.

> Is there anyway we can add a checkbox on accordion panel and prevent changing the accordion expand or collapse?

We don't have great story for this, see #717

Closing as a duplicate / support request.
