### ISSUE TITLE
Popover dynamic placement

### ISSUE THREAD

**Issue by vijan87** [ng-bootstrap/ng-bootstrap#2641]
Hi team
how can i set the popover position to dynamic. for e.g. in case if i don't have space to the top popup should display to the bottom.
i can only set the placement as placement="top", placement="bottom"

**Comment by pkozlowski-opensource** [comment]
This is already supported, you can:
* specify `"auto"` as a placement option;
* specify a set of constraints to be tested, ex.: `[placement]="['top', 'bottom', 'auto']"`

This is all documented here: https://ng-bootstrap.github.io/#/components/popover/api#NgbPopover
