### ISSUE TITLE
how to run version (tag) 1.1.0 repository code on local 

### ISSUE THREAD

**Issue by kedar9444** [ng-bootstrap/ng-bootstrap#2647]
How to run version (tag) 1.1.0 repository code on local ?

**Comment by pkozlowski-opensource** [comment]
`gulp demo-server` : https://github.com/ng-bootstrap/ng-bootstrap/blob/1.1.0/gulpfile.js#L277-L279

@kedar9444 I'm sorry but your questions are more about _developing_ ng-bootstrap - we would expect that people building / modifying the library do a _bit_ of poking around: https://github.com/ng-bootstrap/ng-bootstrap/blob/1.1.0/DEVELOPER.md
