### ISSUE TITLE
(proposal): Explicitly define Datepicker validation error API

### ISSUE THREAD

**Issue by AbakumovAlexandr** [ng-bootstrap/ng-bootstrap#2652]
### Feature description:
Right now the only way to know how to handle `Datepicker`'s validation errors is to investigate [this method](https://github.com/ng-bootstrap/ng-bootstrap/blob/86f1283a3d9e3f8d543ed833e93f83014035bb78/src/datepicker/datepicker-input.ts#L211):
```
  validate(c: AbstractControl): {[key: string]: any} {
    const value = c.value;

    if (value === null || value === undefined) {
      return null;
    }

    const ngbDate = this._fromDateStruct(this._dateAdapter.fromModel(value));

    if (!this._calendar.isValid(ngbDate)) {
      return {'ngbDate': {invalid: c.value}};
    }

    if (this.minDate && ngbDate.before(NgbDate.from(this.minDate))) {
      return {'ngbDate': {requiredBefore: this.minDate}};
    }

    if (this.maxDate && ngbDate.after(NgbDate.from(this.maxDate))) {
      return {'ngbDate': {requiredAfter: this.maxDate}};
    }
}
```

Also, there seems to be no docs on it. So, consumers are not exactly sure if it supposed to be a public API and that it's safe to rely on this shape of error object:
```
{
    ngbDate: {
        invalid?: string,
        requiredBefore?: NgbDateStruct,
        requiredAfter?: NgbDateStruct,
    }
}
```
Defining this (or similar) type of validation error explicitly and adding it to a public API and/or to docs would resolve this uncertainty.

### Version of ng-bootstrap:

ng-bootstrap: 3.1.0

**Comment by pkozlowski-opensource** [comment]
Should be documented as part of #2654. Let's centralise the discussion in #2654 - closing as a duplicate.
