### ISSUE TITLE
bug(timepicker) chevron icon doesn't look right with font-size 14px on html

### ISSUE THREAD

**Issue by maxkorz** [ng-bootstrap/ng-bootstrap#2663]
### Bug description:
When I set `font-size: 14px` on html and size of timepicker is `small`, chevron icon doesn't look right:
![image](https://user-images.githubusercontent.com/25089646/44818222-ed81af00-abf0-11e8-8a8f-42ccb485b89e.png)

Is there any particular reason why width and height of the chevron don't match?
![image](https://user-images.githubusercontent.com/25089646/44818564-21a99f80-abf2-11e8-8cb6-25379a04089d.png)
When I set the same size for both width and height, the icon looks fine with any root font-size

### Link to minimally-working plunker that reproduces the issue:
https://stackblitz.com/edit/angular-xspxt3?file=app/timepicker-basic.html

### Version of Angular, ng-bootstrap, and Bootstrap:

ng-bootstrap: 3.1.0

**Comment by pkozlowski-opensource** [comment]
> Is there any particular reason why width and height of the chevron don't match?

Not that I recall... Would you mind sending a PR that brings those to the same values so we can see how it looks?
