### ISSUE TITLE
Not imported modules appear in Webpack bundle

### ISSUE THREAD

**Issue by DzmVasileusky** [ng-bootstrap/ng-bootstrap#2671]
### Bug description:
There are components from not included modules in the app bundle.
I have only imports of 
```
import { NgbDropdownModule, NgbModalModule } from '@ng-bootstrap/ng-bootstrap';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';
import { NgbModal, NgbModalRef } from '@ng-bootstrap/ng-bootstrap';
import { NgbDropdown } from '@ng-bootstrap/ng-bootstrap';
```

But in the bundle I have found ngb-progressbar, ngb-timepicker etc.

Example of importing by modules from https://ng-bootstrap.github.io/#/getting-started
seems to be wrong.

### Link to minimally-working plunker that reproduces the issue:
No plunker because it's bundle building issue

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.1.2

ng-bootstrap: 2.2.2

Bootstrap: 3.3.x

**Comment by pkozlowski-opensource** [comment]
> No plunker because it's bundle building issue

Could you prepare a minmal GitHub repository then? We've tested this extensively and not used things go away in the production (aot + build optimiser) builds based on our testing.

**Comment by pkozlowski-opensource** [comment]
BTW:

> ng-bootstrap: 2.2.2

You should be testing with the latest ng-bootstrap (3.2.0 atm)

> Bootstrap: 3.3.x

We support only Bootstrap 4+, so...

**Comment by DzmVasileusky** [comment]
Thanks for the answer. 
I think there is some problems in my webpack configuration. 
AOT seems not working properly

**Comment by abyrne85** [comment]
@DzmVasileusky Did you find a solution to this issue?

**Comment by DzmVasileusky** [comment]
@abyrne85 
Use angular CLI instead of custom build I guess :)
But to be serious It seems that AOT plugin for webpack is broken or needs some special conditions to work. 
You can try this plugin on some simple project with simple config and then extend it step by step to find out what exactly breaks AOT.
