### ISSUE TITLE
popover link in loop problem

### ISSUE THREAD

**Issue by vaydich** [ng-bootstrap/ng-bootstrap#2673]
Hi.

I'm trying to use popover in loop.
`<ng-template #popContent let-greeting="greeting">{{ greeting }}</ng-template>
      <a *ngFor="let author of authors"
         placement="top"
         [ngbPopover]="popContent" 
         triggers="manual" 
         #p="ngbPopover" 
         (click)="toggleWithGreeting($event, p, author.id)" 
         class="instrument-link dashed-link light-grey">
        {{ author.first_name + ' ' + author.second_name }}
      </a>`

but it's rendering in wrong placement because each iteration i make the same id - #p

Is there any way to make it dynamically?

**Comment by pkozlowski-opensource** [comment]
> but it's rendering in wrong placement because each iteration i make the same id - #p

local vars (like `#p` are scoped to a view so it shouldn't be a problem to have them duplicated. We need a minimal reproduce scenario in a stakblitz to be able to say more: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by maxokorokov** [comment]
Closing as haven't heard for more than a week. Feel free to reopen and provide the info @pkozlowski-opensource suggested.
