### ISSUE TITLE
Hebrew Calendar

### ISSUE THREAD

**Issue by urish** [ng-bootstrap/ng-bootstrap#2682]
Following up on the request from Twitter, here are some notes:

1. It's very uncommon to have a Hebrew calendar without Gregorian calendar dates displayed alongside. In fact, in a quick search, I couldn't find any example doing so. (see references below). I suggest to add the Gregorian dates as well, otherwise this calendar will not be very useful.

2. Day names are better written as words, as it is much more common:
ראשון (Sunday)
שני
שלישי
רביעי
חמישי
שישי
שבת (Saturday)

If you decided to use the letter notation due to short space, I'd remove the apostrophe. 

3. Some dates have the quotes misaligned - basically, everything between 11 (י"א) and 19 (י"ט). When you have two letters, quotes are always in the middle.

Some examples I found online:

https://www.kipa.co.il/לוח-שנה/
https://www.uzit.co.il/newcalendar/CalendarWithTimes.aspx
https://calendar.walla.co.il
http://xn--5dbhgjl2b4b.com

Thank you!

**Comment by pkozlowski-opensource** [comment]
Just got fixed in cf0d4b434bec794fe39311d09bd3794719e55a78
