### ISSUE TITLE
don't allow to select date range in between blocked dates ? so is this possible.any suggestions please??

### ISSUE THREAD

**Issue by hemanth-sp** [ng-bootstrap/ng-bootstrap#2685]

**Comment by maxokorokov** [comment]
- if you believe that we've got a bug in this library than please provide a minimal reproduce scenario in a stackblitz or plunker: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug
- if you are unsure if this is a bug or not than please use an appropriate support channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
