### ISSUE TITLE
No endDate input for date-range selector

### ISSUE THREAD

**Issue by Rosscotini** [ng-bootstrap/ng-bootstrap#2690]
I've noticed that there is no endDate input for the date-range selector. I am able to set the startDate but cannot provide the endDate so I cannot set the selected range within the date-picker. Is there any solution to this. I looked at the example: https://ng-bootstrap.github.io/#/components/datepicker/examples#range but cannot see where the start/end dates are set within the template. Please advise

**Comment by maxokorokov** [comment]
@Rosscotini if you look at the docs, `startDate` is used to provide a month that is opened by the datepicker initially. You should use `minDate` and `maxDate` to limit navigation range (if I understand correctly your problem).

Also, if you are unsure if this is a bug or not than please use an appropriate support channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
