### ISSUE TITLE
iOS 11 Safari, Modal Backdrop is not respected and also scrolls the page

### ISSUE THREAD

**Issue by omardoma** [ng-bootstrap/ng-bootstrap#2691]
### Bug description:
On iPhone 6S+, iOS 11, using Safari, if the Modal overflows the screen and needs to scroll, while scrolling, the page also scrolls making scrolling the modal very hard.

It works correctly on all supported Desktop browsers and also Android is fine, so the issue only occurs on iOS.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.1.7

ng-bootstrap: 3.2.0

Bootstrap: 4.1.3

**Comment by maxokorokov** [comment]
Looks like a Bootstrap issue to me, maybe related to https://github.com/twbs/bootstrap/issues/24737, but not sure. Needs investigation.

**Comment by omardoma** [comment]
After some research, I believe its a bootstrap issue not the Angular implementation so I am closing the issue, thanks for redirecting me to where to research.
