### ISSUE TITLE
popover issue 

### ISSUE THREAD

**Issue by xyrintech** [ng-bootstrap/ng-bootstrap#2694]
### Bug description:
The popover do not show up if it includes large data. Attached is the screenshot. [
![screen shot 2018-09-07 at 10 53 17 pm](https://user-images.githubusercontent.com/7784136/45233697-26a4d800-b2f1-11e8-92c3-1135cad2ef0b.png)
](url)

If you notice the popover is not visible and out of screen on left. 
### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.x

ng-bootstrap:^2.0.0

Bootstrap:4

**Comment by maxokorokov** [comment]
- if you believe that we've got a bug in this library than please provide a minimal reproduce scenario in a stackblitz or plunker: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug
- if you are unsure if this is a bug or not than please use an appropriate support channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't heard back with the reproduce scenario.
