### ISSUE TITLE
Typeahead has no event for "No Matching Records"

### ISSUE THREAD

**Issue by Bridgeway** [ng-bootstrap/ng-bootstrap#2696]
I'm using this component with success in Angular 6, - it appears to be stable.

I need to handle the point at which "No Matching Records" is shown below the input element, so I can carry out some action.

Also any help in simplifying the typescript:

```ts
empFormatMatches = (value: any) => value.EmployeeName;
searchEmployee = (text$: Observable<string>) =>
          text$.pipe(
            debounceTime(200),
            distinctUntilChanged(),
            tap(() => this.searching = true),
            switchMap(term => term.length < 2 ? [] :
              this.engageService.search(term).pipe(
                tap(() => this.searchFailed = false),
                catchError(() => {
                  this.searchFailed = true;
                  return of([]);
                }))
              ),
              tap(() => this.searching = false)        
          ); // end text$.pipe()
```
...and in the service: 

```ts
search (searchTerm: string) {
        return this.http.get(environment.engageServiceUrl + 'Engage/GetEmployees?search=' + searchTerm + '&sid=' + this.loginSessionId + '&token=false')   
            .map(this.extractData);
    }

    private extractData(res: Response) {
        let body = res;
        return body || { };
    }
```

...and the html:

```html
<input (keyup)="onKey($event)" type="text" class="form-control" formControlName="caller" [ngbTypeahead]="searchEmployee"
            placeholder="Employees" [inputFormatter]="empFormatMatches" [resultFormatter]="empFormatMatches">
      </div>
```

**Comment by maxokorokov** [comment]
I'm sorry, but I don't understand what you're trying to do and it doesn't look like a problem with the library to me.

```ts
this.engageService.search(term).pipe(  
  tap(results => {
    /** here is the point when you know you have no results **/
  })
)
```

Please consider the following:

- if you believe that we've got a bug in this library than please provide a minimal reproduce scenario in a stackblitz or plunker: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug
- if you are unsure if this is a bug or not than please use an appropriate support channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
