### ISSUE TITLE
ngbInputDatepicker closes using ESC (Escape) key when [autoClose]="false"

### ISSUE THREAD

**Issue by danielcollettepb** [ng-bootstrap/ng-bootstrap#2704]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
ngbInputDatepicker closes using ESC (Escape) key when [autoClose]="false"

### Link to minimally-working plunker that reproduces the issue:
https://stackblitz.com/edit/angular-msseh1

The autoClose input is set to false, pressing the ESC (escape) key closes the datepicker. The documentation states in the screenshot below that the escape key should not close the datepicker when autoClose is false.
```
<div class="input-group">
      <input class="form-control" placeholder="yyyy-mm-dd"
             name="dp" [displayMonths]="displayMonths" [navigation]="navigation" [outsideDays]="outsideDays"
             [showWeekNumbers]="showWeekNumbers" ngbDatepicker #d="ngbDatepicker" [autoClose]="false">
      <div class="input-group-append">
        <button class="btn btn-outline-secondary calendar" (click)="d.toggle()" type="button"></button>
      </div>
    </div>
```

![image](https://user-images.githubusercontent.com/6116867/45367368-17eb4900-b5af-11e8-8b97-67e009a199cc.png)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.1.0

ng-bootstrap: 3.2.0

Bootstrap: 4

**Comment by maxokorokov** [comment]
Thanks, indeed, this was missed somehow.
Works fine for dropdown, popover and tooltip though.
