### ISSUE TITLE
How do I restrict Datepicker Popup to 1-month only?

### ISSUE THREAD

**Issue by lenichols** [ng-bootstrap/ng-bootstrap#2706]
I have a datepicker popup that drops down to project both the past and future date ro select to filter a table. What I want to do is restrict users to only choose up to 1 day (actually 25 days)...  How would I do this?

DatepickerPopupTo     and    DatePickerPopupFrom

**Comment by maxokorokov** [comment]
I'm sorry, but I don't understand your problem. `[minDate]`and `[maxDate]` inputs on the datepicker might help to limit dates available for selection, `[markDisabled]` will help to mark certain dates as disabled.

- if you believe that we've got a bug in this library than please provide a minimal reproduce scenario in a stackblitz or plunker: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug
- if you are unsure if this is a bug or not than please use an appropriate support channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help

**Comment by pkozlowski-opensource** [comment]
Closing for now based on https://github.com/ng-bootstrap/ng-bootstrap/issues/2706#issuecomment-420638797 and the fact that we haven't heard back from @lenichols
