### ISSUE TITLE
Typeahead dropdown not closed automatically when long clicking another typeahead and hovering an option

### ISSUE THREAD

**Issue by m-da** [ng-bootstrap/ng-bootstrap#2711]
### Bug description:

You need to have 2 typeaheads that are set to expand on focus, like the "Open on focus" from the demo page: https://ng-bootstrap.github.io/#/components/typeahead/examples#focus

Click on the 1st one, it will expand the list of options, then click AND HOLD on the 2nd one, it will expand the list of options, move your mouse to hover any option of the 2nd one, then release the click. Both typeaheads are now open at the same time, and you can hover any option of both. Clicking anywhere will close both of them. Works with any number of typeaheads that open on focus (3 on my plunkr below).

![2018-09-13 10_33_57-plunker](https://user-images.githubusercontent.com/43234178/45476934-91667100-b740-11e8-92e9-59a47a411bc6.png)

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/x8m6PzxW1MN2eZHr9NBC

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.1.0

ng-bootstrap: 3.2.0

Bootstrap: 4.0.0

**Comment by maxokorokov** [comment]
Sorry for letting this slip through, the workaround here would be adding

```html
<input #t="ngbTypeahead" (blur)="t.dismissPopup()" />
```

A better fix would be using `mouseup` instead of `click`. Will open a PR to fix this and perf issues caused by using `(document)` handler when there are many typeaheads on the page.
