### ISSUE TITLE
Modals sometime flickers

### ISSUE THREAD

**Issue by iseessel** [ng-bootstrap/ng-bootstrap#2714]
"@ng-bootstrap/ng-bootstrap": "^1.1.2",

I will create a plunker sometime soon, but I have found that my modals sometimes quickly appear on the left side of the page, without a modal-background and then jump to their correct position.

What I have found is the div structure is added milliseconds before the classes for them are added, thus the styling flickers. 

First: 
![screen shot 2018-09-13 at 3 13 25 pm](https://user-images.githubusercontent.com/25669348/45510264-b7ebd280-b767-11e8-9370-db7afab278e1.png)

Slightly after: 
![screen shot 2018-09-13 at 3 12 33 pm](https://user-images.githubusercontent.com/25669348/45510250-adc9d400-b767-11e8-9f2e-413c1e7a0788.png)

I have fixed with a workaround I'm not super happy with at all

```
div[role=document] {
  visibility: hidden;
}

.modal-dialog{
  visibility: visible !important;
}
```

**Comment by pkozlowski-opensource** [comment]
> I will create a plunker sometime soon

Yes, please, we can't act on issues that we can't reproduce.

**Comment by pkozlowski-opensource** [comment]
Going to close it for now as we haven't heard back with the reproduce scenario. Happy to re-open when we've got a minimal plunker / stackblitz
