### ISSUE TITLE
hide indicators when array.length is 1 using Angular5 with ng-bootstrap 1.0.4

### ISSUE THREAD

**Issue by sahilkatia** [ng-bootstrap/ng-bootstrap#2717]
How can I hide the navigation indicators when there is one slide only.

I was trying to use ngClass with showNavigationIndicators but I realize with 1.0.4 version, we can't use [showNavigationIndicators].

**Comment by pkozlowski-opensource** [comment]
This functionality is only available from ng-bootstrap 2.2.0, you will have to upgrade.
