### ISSUE TITLE
NgbTypeahead required validation with reactive form works incorrectly

### ISSUE THREAD

**Issue by vladimir-shirmanov** [ng-bootstrap/ng-bootstrap#2719]
### Bug description:

In markup I have this code 

```html
<div class="first-group-margin form-group">
      <label for="recipient">{{ 'To' | translate }}:</label>
      <input id="recipient" type="text" class="tatoo-form-control" name="recipient" [ngbTypeahead]="search"
        [resultFormatter]="autocompleteFormatter" [inputFormatter]="autocompleteFormatter" [class.is-invalid]="recipient.invalid && recipient.touched"
        formControlName="recipient" [editable]="false" placeholder="{{ 'Placeholder.UserRecipient' | translate }}"
        autocomplete="false" (selectItem)="changeEvent($event)">
      <div class="alert-absolute alert alert-danger mt-2" *ngIf="recipient.touched && recipient.invalid">
        <span *ngIf="recipient.errors['required']">{{'Validation.BlankRecipient' | translate}}</span>
      </div>
</div>
```

and when I select value from dropdown the input field is 'blinking red' because change event occures earlier then typeahead select item event I think. So my form control become invalid for a while

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.0.2

ng-bootstrap: 2.0.0

Bootstrap: 4.1.1

**Comment by pkozlowski-opensource** [comment]
We need a minimal, live reproduce scenario for this issue to be actionable: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by vladimir-shirmanov** [comment]
here plunkr working demo
http://plnkr.co/edit/42AB4yXBsiuGDuFCC0C5

**Comment by maxokorokov** [comment]
Problem happens only with mouse click. Clicking an not releasing mouse button triggers `(blur)` handler that calls `onTouched()`:

![blur](https://user-images.githubusercontent.com/8074436/45688236-20b0c180-bb51-11e8-8083-e89871955e07.gif)


https://github.com/ng-bootstrap/ng-bootstrap/blob/5dd4e1e7227bcb1779d38f4510ca99ec06f5621a/src/typeahead/typeahead.ts#L235-L240

**Comment by dotNetAthlete** [comment]
I read that you could not use ng bootstrap controls in conjunction with reactive forms - obviously that's wrong !!!!

**Comment by dotNetAthlete** [comment]
> here plunkr working demo
> http://plnkr.co/edit/42AB4yXBsiuGDuFCC0C5

OMG - I've been looking for this functionality for weeks - hopefully I can get this to work with ngbTypeahead in Angular 7.0.2 !?
