### ISSUE TITLE
ngbDropdown + formControlName not working

### ISSUE THREAD

**Issue by ankita199** [ng-bootstrap/ng-bootstrap#2725]
Hi,

I have multiple ngdropdown in my code. and i am trying i am using angular reactive-forms. but it is not working. Is ngb-dropdown not working with reactive forms?

**Comment by pkozlowski-opensource** [comment]
`ngb-dropdown` has nothing to do with forms, reactive or not. I _think_ that you are trying to use as a select component but it is not - its purpose is to provide menu-like features.

Closing as invalid.
