### ISSUE TITLE
Typeahead not working with Validator.required reactiveforms

### ISSUE THREAD

**Issue by dotNetAthlete** [ng-bootstrap/ng-bootstrap#2726]
I can only enter a value which matches one of the search results.

How do I allow the user to enter their own text (and not just select from the results ?)
How do I capture and customise the "No Matching Records" popping up, is there an event I can handle for that ?

Angular 6
Bootstrap 4

**Comment by pkozlowski-opensource** [comment]
> I can only enter a value which matches one of the search results.

This is not the case with ngbTypeahead implementation as can be seen in a stackblitz forked from our [demo page](https://ng-bootstrap.github.io/#/components/typeahead/examples): https://stackblitz.com/edit/angular-ggdjww?file=main.ts

> How do I capture and customise the "No Matching Records" popping up, is there an event I can handle for that ?

There is nothing like "No Matching Records" popping up in our impl, this is probably coming from the user land.

**Comment by pkozlowski-opensource** [comment]
We will need a minimal reproduce scenario since, based on the information provided, it seems like you are dealing with some customisation of ng-bootstrap. We systematically ask for minimal reproduce scenario anyway in our issue template: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug - without it we can't act on issue reports.

**Comment by dotNetAthlete** [comment]
Sorry, here is the code:

(in my component.ts)

`empFormatMatches = (value: any) => value.EmployeeName;

        searchEmployee = (text$: Observable<string>) =>
          text$.pipe(
            debounceTime(200),
            distinctUntilChanged(),
            tap(() => this.searching = true),
            switchMap(term => term.length < 2 ? [] :
              this.engageService.GetEmployee(term).pipe(
                tap(() => this.searchFailed = false),
                catchError(() => {
                  this.searchFailed = true;
                  return of([]);
                }))
              ),
              tap(() => this.searching = false)        
          ); // end text$.pipe()`


Yes, the text "No Matching Records" is coming from my API.
(In my service.ts)

`GetEmployee(searchTerm: string) {
        return this.http.get(environment.engageServiceUrl + 'Engage/GetEmployees?search=' + searchTerm + '&sid=' + this.loginSessionId + '&token=false')   
            .map(this.extractData);
    }`

(and the template)

`<div class="form-group search">
      <span class="fa fa-search"></span>
      <input (blur)="onBlur($event)" (selectItem)="onSelectChange($event)" type="text" class="form-control" formControlName="caller" [ngbTypeahead]="searchEmployee" placeholder="Caller..." [inputFormatter]="empFormatMatches" [resultFormatter]="empFormatMatches">      
    </div>`

**Comment by pkozlowski-opensource** [comment]
@dotNetAthlete I'm sorry but we _really_ need a _minimal_ and _runnable_ reproduce scenario (with clear steps to reproduce) in a stackblitz. You can fork one from our demo pages to have a starting point.

We really need to _see_ the bug to be able to confirm it and fix. Please take time to read our reasoning: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

**Comment by dotNetAthlete** [comment]
I really don't have much knowledge of things like forking, stackblitz, plunkr, I just have to get an Angular 6 application working for work!  :(

**Comment by pkozlowski-opensource** [comment]
> I really don't have much knowledge of things like forking, stackblitz, plunkr, I just have to get an Angular 6 application working for work! :(

I'm really sorry but we can't help much with issues that are not well isolated. Still suggesting to learn about stackblitz as this is very useful tool in general. The best part is that you can work mini examples from our [demo page](https://ng-bootstrap.github.io/#/components/typeahead/examples), ex.: https://stackblitz.com/angular/ymnbrelyvar

Going to close this one, feel free to open another issue when you've got a minimal reproduce scenario.
