### ISSUE TITLE
Improve modal focus handling with NgbAutoFocus directive and first element focus

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#2728]
- Allow users to set the initial focus inside the modal with `NgbAutoFocus` directive. 

```html
<!-- will be focused after the modal opens -->
<input type="text" ngbAutoFocus />
``` 

- If there is no `ngbAutoFocus` in the modal, focus first focusable element by default. Allow user to cancel this behaviour and focus nothing by doing 

```ts
modal.open(content, {focusFirst: false})
```

- add a demo for focus handling in a separate PR

---
Not sure if this is a breaking change and not sure if we need `ngbAutoFocus` as a directive or a simple attribute would do.

**Comment by benouat** [comment]
I'll work on that one.

**Comment by peterblazejewicz** [comment]
hi folks, just wondering why the custom (and new) directive instead of using native `autofocus`?
(I know that part, it does not work in first place, dynamic content behaviour, etc). But in the guts of the pending PR plain selector is being using:
```js
const elementToFocus = this._elRef.nativeElement.querySelector(`[ngbAutofocus]`) as HTMLElement;
```
https://github.com/ng-bootstrap/ng-bootstrap/pull/2737/files#diff-8fb1cd1cc4cf9a5207c30f1474b6c8b9R67

and I think this does not differ much from:

```js
const elementToFocus = this._elRef.nativeElement.querySelector(`[autofocus]`) as HTMLElement;
```

Thanks!

**Comment by benouat** [comment]
@peterblazejewicz we decided not to use the native `[autofocus]` attribute mostly for 2 reasons:

1. As you said, it does not work in first place, dynamic content behaviour, etc...
2. Using it would be confusing for people not aware of point 1. They would think it is natively working, which is not true.

The feature is provided by ng-bootstrap, hence the `ngb` prefix, no one can be fooled.
As a sidenote, material is using the same technique with a plain attribute, and theirs is name `cdkFocusInitial`

**Comment by kedar9444** [comment]
@maxokorokov  : modal.open(content, {focusFirst: false}) is this feature removed from V4, because i am not able to see `focusFirst` property in NgbModalOptions. if yes how to achieve a situation where i don't want to set any default focus but should be able to close the modal with `ESC` key.

**Comment by janwidmer** [comment]
if anyone is interested in a solution, we found a workaround by adding the ngbAutoFocus directive on an element, which is within the Overlay Child ref, but not within the modal markup itself. Then the focus is kept on the element, where it was before:

```
<ng-template #modal>
  <div [attr.ngbAutofocus]="disableAutoFocus ? true : null"></div>
  <div *ngIf="showModalHeader" class="modal-header">
    <div class="c-modal__header">
      <ng-content select="[header]"></ng-content>
      <button
        type="button"
        class="c-modal__close c-modal__close--header"
        aria-label="{{ 'common.close' | cxTranslate }}"
        (click)="closeModal('close-button')"
      >
        <e-icon [icon]="IconKeys.CLOSE"></e-icon>
      </button>
    </div>
  </div>

  <div class="modal-body">
    <div [class.container]="size === 'cover'">
      <ng-content></ng-content>
    </div>
  </div>

  <div class="modal-footer">
    <div>
      <!-- was required because of Bootstrap child selector -->
      <div *ngIf="showModalFooter" class="c-modal__footer" [class.container]="size === 'cover'">
        <ng-content select="[footer]"></ng-content>
      </div>
    </div>
  </div>
</ng-template>
```

Inspired by this stackblitz: https://stackblitz.com/edit/angular-kvffsp
