### ISSUE TITLE
NgbTimeAdapter with angular 5

### ISSUE THREAD

**Issue by me-amit** [ng-bootstrap/ng-bootstrap#2741]
How I can use NgbTimeAdapter  with angular 5 , I have gone through the issues below mentioning its available in next version of ng-bootstrap. 

https://github.com/ng-bootstrap/ng-bootstrap/issues/2488

Is there any way I can use it with  angular 5 version. 

https://stackoverflow.com/questions/52479182/ng-bootstrap-ngbtimeadapter-with-angular-5

**Comment by pkozlowski-opensource** [comment]
> How I can use NgbTimeAdapter with angular 5 , I have gone through the issues below mentioning its available in next version of ng-bootstrap.

You can't. The mentioned feature is available from ng-bootstrap 2.2.0 and this one requires Angular 6+.
You will have to update your dependencies (Angular, ng-bootstrap) to use this new feature - keeping your dependencies up to day is a good thing!
