### ISSUE TITLE
Do not close dropdown on click - ngbDropdownMenu

### ISSUE THREAD

**Issue by xyrintech** [ng-bootstrap/ng-bootstrap#2747]
Is there anyway we can avoid closing dropdown on click of menu item for ngbDropdownMenu?

**Comment by pkozlowski-opensource** [comment]
Sure, check the documentation for the `autoClose` property: https://ng-bootstrap.github.io/#/components/dropdown/api

Closing as a support request.

**Comment by boltex** [comment]
this cannot prevent for a single item, only for all items on that menu
