### ISSUE TITLE
'ion-page' is not a known element

### ISSUE THREAD

**Issue by ChenXuFeng** [ng-bootstrap/ng-bootstrap#2754]
Ionic:
   ionic (Ionic CLI)          : 4.1.2 (/usr/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:
   cordova (Cordova CLI) : not installed
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:
   NodeJS : v10.11.0 (/usr/bin/node)
   npm    : 6.4.1
   OS     : Linux 4.15

**I installed ionic-cli according to the official documentation and created a new "ionic-project". When I added the <ion-page></ion-page> tag to app.component.html, I was prompted: 'ion-page' is not a known element.
Which module do I need to import?**

**Comment by pkozlowski-opensource** [comment]
Wrong repo - this project has nothing to do with ionic.
