### ISSUE TITLE
Typescript 3.1.1 build error

### ISSUE THREAD

**Issue by BrainMaxxx** [ng-bootstrap/ng-bootstrap#2755]
Angular: 7.0.0-rc.0
Typescript: 3.1.1
ng-bootstrap: 3.2.2

New version of typescript causes prod build error:

ERROR in node_modules\@ng-bootstrap\ng-bootstrap\ng-bootstrap.d.ts.ɵh.html(3,67): : An expression of type 'void' cannot be tested for truthiness
node_modules\@ng-bootstrap\ng-bootstrap\ng-bootstrap.d.ts.ɵh.html(25,67): : An expression of type 'void' cannot be tested for truthiness

**Comment by adamfoley** [comment]
Just came across this one myself.  Don't know if it will be of any help, but the problem appears to happen during AOT compile as building without `--prod` or `--aot` switches still works, including `--optimization`

**Comment by adamfoley** [comment]
Cloned a copy to include as a separate project, `angular-cli@7.0.0-rc.0` *does not* like `!!` appearing in a few templates.  Example: This: ` (click)="!!selectPage(page-1)"` binding in `pagination.ts`.  Not sure what the double exclamation even does?

**Comment by Ks89** [comment]
I have the same issue. I can't build

**Comment by RicardoPary** [comment]
I have the same problem

**Comment by honsq90** [comment]
same problem

**Comment by BrainMaxxx** [comment]
> Cloned a copy to include as a separate project, `angular-cli@7.0.0-rc.0` _does not_ like `!!` appearing in a few templates. Example: This: `(click)="!!selectPage(page-1)"` binding in `pagination.ts`. Not sure what the double exclamation even does?
> 
> -edit-
> Here's a temporary fix: In `ng-bootstrap.metadata.json` of the npm package, replace all occurrences of `(click)=\"!!` with `(click)=\"`. No idea if it breaks things, but at least gets around the build error.

This solution works, thanks!

**Comment by pkozlowski-opensource** [comment]
@BrainMaxxx ng-bootstrap: 3.x doesn't support Angular 7.x - you should have gotten warning from your package manager as the peer dependency doesn't much. We will be releasing Angular 7.x / Typescript 3.1.1 version in the coming days but this will require us to bump up ng-bootstrap version to 4.0.0 (or higher).

**Comment by BrainMaxxx** [comment]
Got it! Thanks for your work!

ср, 3 окт. 2018 г., 18:04 Pawel Kozlowski <notifications@github.com>:

**Comment by maxokorokov** [comment]
This is fixed in 3.3.0, but it doesn't mean we officially support Angular 7 or TS 3.1.1 though :)

**Comment by adamfoley** [comment]
> This is fixed in 3.3.0, but it doesn't mean we officially support Angular 7 or TS 3.1.1 though :)

Understood and thanks for the prompt fix.

**Comment by suresh2018** [comment]
prod build shows this issue

![image](https://user-images.githubusercontent.com/30258184/47429046-b8d64200-d7b2-11e8-8776-a245f39ff7e8.png)

**Comment by FurtunaDaniel** [comment]
@suresh2018  I have same error too.

**Comment by RUPALAVECINO** [comment]
Vuelvan a instalar npm install --save @ng-bootstrap/ng-bootstrap

**Comment by AnatoliyMovchan** [comment]
@RUPALAVECINO thx

**Comment by sk8027** [comment]
for Angular 7, "@ng-bootstrap/ng-bootstrap": "^4.0.0",  worked for me and issue resolved

**Comment by challasrivani** [comment]
for Angular 7, I have tried to use "@ng-bootstrap/ng-bootstrap": "^4.0.0",But it still gives me the same error.. build command I am using is 
"yarn ng build --progress=false --aot --prod --named-chunks --c=production && gulp libs".

**Comment by karthikvss** [comment]
> for Angular 7, "@ng-bootstrap/ng-bootstrap": "^4.0.0", worked for me and issue resolved

Thanks a ton, it worked for me !!! 👍

**Comment by dangquang1020** [comment]
After upgrade to  "@ng-bootstrap/ng-bootstrap": "^4.0.0", I got many warning message on production build: 

![image](https://user-images.githubusercontent.com/12976768/49418352-552d3480-f7b4-11e8-837c-7e1e556dbd2b.png)

**Comment by lapongua** [comment]
It builds for me If I remove **f.form.valid** from my <form>

```
<form [formGroup]="reactiveFormGroup" #f="ngForm" (ngSubmit)="submit()" autocomplete="off" novalidate>

<form [formGroup]="reactiveFormGroup" #f="ngForm" (ngSubmit)="submit() **&& f.form.valid**" 
 autocomplete="off" novalidate>
```

**Comment by kernyden** [comment]
@pkozlowski-opensource @maxokorokov  the same issue with version 2.1.2 ng-bootstrap and angular 7. How we can fix it without update to actual version? (because of https://github.com/ng-bootstrap/ng-bootstrap/issues/2757)

**Comment by Crypt0Graphic** [comment]
Manually set "@ng-bootstrap/ng-bootstrap" to "^4.0.0". Delete node_modules folder and reinstall with "npm i". I solved  right now. My package.json is like that:

![screen shot 2019-02-26 at 21 27 34](https://user-images.githubusercontent.com/9743846/53437119-da1f9700-3a0d-11e9-9e1d-e359da90c782.png)

**Comment by BLecha** [comment]
well for me worked     "@ng-bootstrap/ng-bootstrap": "4.1.0",
 
in angular7

**Comment by BLecha** [comment]
@Crypt0Graphic one does not need to delete node_modules its enough just to run npm install!

**Comment by ashish9342** [comment]
`npm install --save @ng-bootstrap/ng-bootstrap@latest` this should solve the error

**Comment by ansbilalgit** [comment]
> Manually set "@ng-bootstrap/ng-bootstrap" to "^4.0.0". Delete node_modules folder and reinstall with "npm i". I solved right now. My package.json is like that:
> 
> ![screen shot 2019-02-26 at 21 27 34](https://user-images.githubusercontent.com/9743846/53437119-da1f9700-3a0d-11e9-9e1d-e359da90c782.png)

I am trying your solution but getting following error:
 

> No matching version found for ng-bootstrap@^4.0.0

**Comment by developer1011** [comment]
"@ng-bootstrap/ng-bootstrap": "^4.1.1" worked for me in Angular 7

**Comment by lanka-senanayaka** [comment]
> Manually set "@ng-bootstrap/ng-bootstrap" to "^4.0.0". Delete node_modules folder and reinstall with "npm i". I solved right now. My package.json is like that:
> 
> ![screen shot 2019-02-26 at 21 27 34](https://user-images.githubusercontent.com/9743846/53437119-da1f9700-3a0d-11e9-9e1d-e359da90c782.png)

Worked for me thanks.

**Comment by muhammadarifinnursalim** [comment]
I got the same problem and I have tried this method:
1. delete your module node folder then
2. delete your package-lock.json file
3. run npm install
4. run ng serve -o

This works for me, I hope you do too :)

**Comment by ipsAn** [comment]
> I got the same problem and I have tried this method:
> 
> 1. delete your node module folder then
> 2. delete your package-lock.json file
> 3. run npm install
> 4. run ng serve -o
> 
> This works for me, I hope you do too :)

don't work for me :c

**Comment by hydrogen2oxygen** [comment]
The error sadly still exist if you build with yarn. But npm works.

**Comment by thomasm1** [comment]
THANKS Crypt0graphic ..finally can make a build!!     .._.Manually set "@ng-bootstrap/ng-bootstrap" to "^4.0.0". Delete node_modules folder and reinstall with "npm i". I solved right now._

**Comment by prashant7276** [comment]
I have the same issue for angular 4, any one can tell me how to fix it.

**Comment by hydrogen2oxygen** [comment]
> 
> I have the same issue for angular 4, any one can tell me how to fix it.

With Angular 9 I abandoned yarn build in favor of the new improved ng build. Indeed you don't need yarn anymore in Angular >= 9.x.
