### ISSUE TITLE
SPFx AOT cannot pass context

### ISSUE THREAD

**Issue by jamason** [ng-bootstrap/ng-bootstrap#2759]
log message is that context is undefined.
What is correct way to pass context?

**main.ts** 

import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

if (environment.production) {
  enableProdMode();
}

// platformBrowserDynamic().bootstrapModule(AppModule)
//   .catch(err => console.log(err));

window['MyAngularWebPartContext'] = this.context;
window["MyAngularWebPartProperties"] = this.properties;
import { AppModuleNgFactory } from './app/app.module.ngfactory';
window['webPartContext'] = this.context;

platformBrowserDynamic().bootstrapModuleFactory(AppModuleNgFactory, {ngZone: 'noop'}).catch(err => console.log(err));

**app.component.ts**
...
import { WebPartContext } from '@microsoft/sp-webpart-base';
import {IWebPartContext} from '@microsoft/sp-webpart-base';
public ctx: WebPartContext;
.....
public ngOnInit(): void {
    this.ctx = window["MyAngularWebPartContext"];
    console.log("ctx ", this.ctx);

**Comment by maxokorokov** [comment]
Looks like you're logging bug for the wrong project. 
Don't see anything ng-bootstrap related here
