### ISSUE TITLE
Update for Angular 7 support

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#2764]
* [x] update documentation extraction script to support TS 3.1.x
* [x] (warning) tslint version with CLI 7 marks `keyEvent.which` as deprecated
* [x] (warning) demo: tslint version with CLI 7 marks `addListener` as deprecated
* [x] update documentation with supported versions in `README.md` and `getting-started.component.ts`
* [ ] required tsickle 0.33.0 gives a peer-depencency warning after installation with CLI 7.0.0 and TS 3.1.1

**Comment by maxokorokov** [comment]
Opened #2791 to test, CI works fine, demos look fine

**Comment by changhuixu** [comment]
After update to Angular v7,

```
npm WARN @ng-bootstrap/ng-bootstrap@3.3.0 requires a peer of @angular/common@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@3.3.0 requires a peer of @angular/core@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@3.3.0 requires a peer of @angular/forms@^6.1.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by maxokorokov** [comment]
@changhuixu by saying that `3.x.x` should work fine, I meant that there are no breaking changes / development required in the library to support Angular 7. Warnings is a different thing.

We'll release `4.0.0` shortly with official support for Angular 7.0.0, rxjs 6.3.0 and TS 3.1.1 that will remove all warnings in question.

**Comment by danielleroux** [comment]
@maxokorokov Did you mean that you will allow both angular versions 6.1.0 and 7.0.0?
```json
...
"@angular/core": "6.1.0 || 7.0.0",
...
```

**Comment by jamesnvk** [comment]
I'm currently receiving this error when trying to upgrade to angular 7:

```
$ng update @angular/cli @angular/core
                  Package "@ng-bootstrap/ng-bootstrap" has an incompatible peer dependency to "@angular/forms" (requires "^5.0.2" (extended), would install "7.0.0").
                  Package "@ng-bootstrap/ng-bootstrap" has an incompatible peer dependency to "@angular/core" (requires "^5.0.2" (extended), would install "7.0.0").
                  Package "@ng-bootstrap/ng-bootstrap" has an incompatible peer dependency to "@angular/common" (requires "^5.0.2" (extended), would install "7.0.0").
Incompatible peer dependencies found. See above.
```

**Comment by daddyschmack** [comment]
What if you do it in the opposite order?

**Comment by pkozlowski-opensource** [comment]
Just released Angular 7 compatible version - aca4cbe

**Comment by samuelt1** [comment]
@jamesnvk Your solution does not help because ng-bootstrap does not yet support angular 7. There is a pull request for that

**Comment by muhammadarifinnursalim** [comment]
I got the same problem and I have tried this method:

delete your node module folder then
delete your package-lock.json file
run npm install
run ng serve -o
This works for me, I hope you do too :
