### ISSUE TITLE
Checkbox loses check mark in certains conditions

### ISSUE THREAD

**Issue by WizardPC** [ng-bootstrap/ng-bootstrap#2768]
### Bug description:
Buttons checkbox loses check mark in certains conditions

When used in a component with controlValueAccessor and the attributes "ngbButtonLabel"/"ngbButton" the check mark disappear after an ngIf.

But if you remove the attributes "ngbButtonLabel"/"ngbButton" it works.

### Use case:

I have counters for rooms. If i click on the checkbox i set room to 1, and if room > 0 i check the checkbox.

ps : i don't do the all thing in stackblitz, just the necessary for reproduction.
![usecase](https://user-images.githubusercontent.com/11718892/46596573-5f48f480-cadd-11e8-8fec-3d539238ba17.PNG)

### Link to minimally-working StackBlitz that reproduces the issue:

[https://stackblitz.com/edit/angular-8agu8a](https://stackblitz.com/edit/angular-8agu8a)

### Versions of Angular, ng-bootstrap and Bootstrap:

See SB

**Comment by benouat** [comment]
@WizardPC I just add a quick look at your stackblitz and I think that you're missing one part of the 2 way data binding for it to work properly

```html
<label class="btn-primary" ngbButtonLabel>
      <input type="checkbox" ngbButton [checked]="checked"> Checkbox
</label>
```

You need to listen to `(change)` on the checkbox, and react accordingly. You have the `[]` binding on checked, you're missing the `()`

Could you investigate in this direction ?

**Comment by WizardPC** [comment]
@benouat i update the first post with my use case and the stackblitz with the issue and the workaround.

I'm not sure why i need the two way databinding in this case...? See my capture below

**STEP 1**
![issue_1](https://user-images.githubusercontent.com/11718892/46597359-19416000-cae0-11e8-9881-44facbea27d3.PNG)

**STEP 2**
![issue_2](https://user-images.githubusercontent.com/11718892/46597360-19416000-cae0-11e8-95fd-573df3a27ade.PNG)

**STEP 3**
![issue_3](https://user-images.githubusercontent.com/11718892/46597361-19416000-cae0-11e8-9b3c-1563f56972d3.PNG)

**STEP 4**
![issue_4](https://user-images.githubusercontent.com/11718892/46597362-19416000-cae0-11e8-88f9-2f7fe775fea9.PNG)

**Comment by pkozlowski-opensource** [comment]
@WizardPC you are trying to drive checked state from 2 places - Angular forms (reactive forms) and `checked` property (template driven). Not only you are mixing 2 mechanisms (Angular forms and direct binding to a property) but _also_ mixing reactive and template-driven approach. This can't end up well as you see in your example.

I'm not sure how we could help here as the whole scenario is not clear to me. Maybe start by clearly describing what you are trying to do, functionally speaking, so we can suggest the best approach?

**Comment by WizardPC** [comment]
@pkozlowski-opensource exactly, i'm **not** tryinng to drive checked state from 2 places.

From your documentation, you use the form to bind directly the state of the checkbox, but it's not my case. I bind an hidden value (the counter) wich is set by the buttons +/-.

**Comment by pkozlowski-opensource** [comment]
> From your documentation, you use the form to bind directly the state of the checkbox, but it's not my case.

Then I don't understand why you are using `ngbButtonLabel` / `ngbButton ` directives as those _are_ meant to reflect state of a _form_. If this is not your case you should not be using those directives...

**Comment by WizardPC** [comment]
Can you just explain me why it's happend after an *ngIf ? Why not directly when i increment the counter ?
