### ISSUE TITLE
Window class in (global) NgbModalConfig 

### ISSUE THREAD

**Issue by jarodsmk** [ng-bootstrap/ng-bootstrap#2770]
I've been working on theming an enterprise level system where a theme is swapped out at run time by means of changing an NgClass on the 'body' of the application.

Since NgbModals are rendered outside of the 'body' of the application, they aren't targeted by the theming, and since it's a system wide styling that's applied, would this not be a good use case for the implementation of a windowClass param in the global NgbModalConfig, on top of the per-modal NgbModalOptions.windowClass?

Thoughts?

**Comment by pkozlowski-opensource** [comment]
Did you try the [container](https://ng-bootstrap.github.io/#/components/modal/api#NgbModalOptions) option? It allows you to attach modals to any arbitrary place in the DOM.

**Comment by jarodsmk** [comment]
@pkozlowski-opensource - 
Currently the two solutions I have are to either:
- add a windowClass onto every call of a modal system wide which would apply the styling we need, or;
- change the container on every modal system wide to ensure they're rendered lower down in the DOM to get targeted by said styling

In that case too, would it not make sense to add a global configuration, by default and unless stated on the modal instance itself, to set the classes/containers of the modals system wide?

**Comment by jarodsmk** [comment]
@pkozlowski-opensource - no worries, and thanks for taking the time to check in on it as well :)

As an example, in my service I tried adding this:

```
   public static globalConfig: NgbModalConfig = {
        container: '#element',
    };

    public static globalOptions: NgbModalOptions = {
        container: '#element',
    };
```

Within the first definition of globalConfig, tslint gave:

[ts]
Type '{ container: string; }' is not assignable to type 'NgbModalConfig'.
  Object literal may only specify known properties, and 'container' does not exist in type 'NgbModalConfig'.

**Comment by pkozlowski-opensource** [comment]
Oh, I see. We should add undefined fields in this case, I guess. Will play with it.

**Comment by jarodsmk** [comment]
Ok cool, so I'm not going crazy :P 

Thanks for the assistance man.

**Comment by benouat** [comment]
@jarodsmk might be a stupid try at it (mostly because I read this issue quite quickly...)
but I would personally use that instead:

```typescript
public static globalConfig: NgbModalOptions = {container: 'foo'};
```

`NgbModalConfig` is just a class we use to propagate configurable options, options that themselves are defined on an interface `NgbModalOptions`. The Config class is mostly used on DI. Typing an object with the Option interface would be more used in any (or all) `modalService.open( ... )`

Quick refresher here from the source

https://github.com/ng-bootstrap/ng-bootstrap/blob/a76d7fe4981b93667a9936d40a0a40a804a7ab72/src/modal/modal-config.ts#L75-L78

**Comment by benouat** [comment]
@jarodsmk after having a deeper look at it, please do take into consideration my above comment here.
This would definitely solved your issue. I think that you mostly get confused between our 2 classes that as I mentioned have different purpose.

Closing for now as we don't have anything special to fix.

**Comment by bhupesh9898** [comment]
> @pkozlowski-opensource -
> Currently the two solutions I have are to either:
> 
> * add a windowClass onto every call of a modal system wide which would apply the styling we need, or;
> * change the container on every modal system wide to ensure they're rendered lower down in the DOM to get targeted by said styling
> 
> In that case too, would it not make sense to add a global configuration, by default and unless stated on the modal instance itself, to set the classes/containers of the modals system wide?

Perfect , windowClass  works and we can give our custom CSS.
