### ISSUE TITLE
Datepicker next/prev month arrows lose focus

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#2780]
In some browsers (ex. Firefox and Safari on Mac OS), clicking on the `previous month` or `next month` buttons loses focus and brings it to the `<body>`.

Steps to reproduce:
- open https://stackblitz.com/edit/angular-dlxsfr
- open popup → today becomes focused
- click on `next month` → focus is lost

Notes:
- works fine in Chrome
- if `next month` is already focused, clicking on it doesn't lose focus

**Comment by Korla** [comment]
Hi, I am wondering about this. Why was it removed from the milestone? Would you accept a PR which fixes this issue?

**Comment by maxokorokov** [comment]
@Korla, sure, it would be nice to fix it. If I remember correctly this really varies from OS and on Windows should work fine. 

I think `<button>` simply can't be focused on click in mentioned browsers, but needs investigation
