### ISSUE TITLE
Increase size of datepicker 

### ISSUE THREAD

**Issue by Markzhou2207** [ng-bootstrap/ng-bootstrap#2781]
Is there a way to increase the size of the datepicker, I've only managed to increase the outside frame or the size of the font but not the size of the grid the dates sit on.

**Comment by maxokorokov** [comment]
@Markzhou2207 you can change cell sizes, ex. like this: https://stackblitz.com/edit/angular-zcfddm

Please you appropriate support channel for future requests: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
