### ISSUE TITLE
ERROR TypeError: Cannot read property 'slice' of undefined  

### ISSUE THREAD

**Issue by krushnachandra** [ng-bootstrap/ng-bootstrap#2782]
When I am not getting the list for the Typeahead from api backend that time while typing it is giving this error

**Comment by pkozlowski-opensource** [comment]
Sorry, we need a minimal reproduce scenario, otherwise it is not actionable: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

Also make sure that you are testing with the latest version of this library.

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't heard back with the reproduce scenario.
