### ISSUE TITLE
Add click event for carousel on prev/next arrows

### ISSUE THREAD

**Issue by dejooo13** [ng-bootstrap/ng-bootstrap#2788]
Hi, i wan't to add click events on prev/next arrows in carousel (i want to make API call)? Is there a way to do so? Thanks in advance.

**Comment by pkozlowski-opensource** [comment]
You can't add arbitrary events, but you can use the `slide` event to be notified when a slide gets changed: https://ng-bootstrap.github.io/#/components/carousel/api

Hope this will work for you.

**Comment by pkozlowski-opensource** [comment]
Closing as a support request.
