### ISSUE TITLE
Typeahead is not focused after selecting an item by click

### ISSUE THREAD

**Issue by fbasso** [ng-bootstrap/ng-bootstrap#2792]
...but it is after selecting an item by [enter]

This issue is easily reproductible on the demo site : https://ng-bootstrap.github.io/#/components/typeahead/examples#focus

**Comment by lucasklaassen** [comment]
@tobihagemann This definitely broke my project too. It triggers the input which fires another search with the selected item as the query.

**Comment by tobihagemann** [comment]
Should we open a new issue for this?

**Comment by pkozlowski-opensource** [comment]
@lucasklaassen @tobihagemann yes, please open a new issue with a minimal reproduce scenario. Thnx!
