### ISSUE TITLE
hooking events withing rxjs typeahead structure...

### ISSUE THREAD

**Issue by dotNetAthlete** [ng-bootstrap/ng-bootstrap#2804]
I'm getting the following error when trying to use console.log to understand how the ngbtypeahead works:
console.log('this.engageService.GetEmployee ', this.searching); gives:

[ts] ';' expected on the dot between console and log and 'Identifier expected' on the console log first parameter.  Here is the full code inside my angular 6 component class:

`formatMatches = (value: any) => value.EmployeeName;

        searchEmployee = (text$: Observable<string>) =>
          text$.pipe(
            debounceTime(200),
            distinctUntilChanged(),
            tap(() => this.searching = true),
            switchMap(term => term.length < 2 ? [] :
              this.engageService.GetEmployee(term).pipe(
                tap(() => this.searchFailed = false),
                catchError(() => {
                  this.searchFailed = true;
                  return of([]);
                }))
              ),
              tap(() => this.searching = false)        
          ); // end text$.pipe()

          console.log('this.engageService.GetEmployee ', this.searching);`

How do I monitor this.searchFailed and this.searching ?

**Comment by benouat** [comment]
If you simply reuse code provided from one of our demo, and just tried to write a `console.log()` in here, it is totally normal that this code is generating this error.

You are inside an ES6 class definition, you just can't write arbitrary code like that...

```typescript
export class NgbdTypeaheadHttp {
  model: any;
  searching = false;
  searchFailed = false;

  constructor(private _service: WikipediaService) {}

  search = (text$: Observable<string>) =>
    text$.pipe(
      debounceTime(300),
      distinctUntilChanged(),
      tap(() => this.searching = true),
      switchMap(term => term.length < 2 ? [] :
        this._service.search(term).pipe(
          tap(() => this.searchFailed = false),
          catchError(() => {
            this.searchFailed = true;
            return of([]);
          }))
      ),
      tap(() => this.searching = false)
    )
  
    // You can't  write that code here inside a class definition. Only member properties, and method definition could be written here.
    console.log('my log in here', this.searching);
}
```

if you do want to hook yourself into this observable code, simply use `tap` operator ([documentation here](https://www.learnrxjs.io/operators/utility/do.html))

Closing as it is not an ngBootstrap issue.

**Comment by dotNetAthlete** [comment]
Fantastic thanks. using tap has really helped !
