### ISSUE TITLE
chore(site): rename core to ng-bootstrap

### ISSUE THREAD

**Issue by icfantv** [ng-bootstrap/ng-bootstrap#281]
in keeping with the angular naming conventions, we should rename the core repo to `ng-bootstrap` as it is far more descriptive than simply `core`.

**Comment by sendilkumarn** [comment]
Think that would be correct

**Comment by wesleycho** [comment]
Are we going to name this `ng-bootstrap/ng-bootstrap` then?

**Comment by pkozlowski-opensource** [comment]
> Are we going to name this ng-bootstrap/ng-bootstrap then

I'm for it. But I don't know:
* what others think?
* what are the consequences (are there links we care about not-breaking)?

**Comment by Foxandxss** [comment]
I don't really care, both are nice.

**Comment by icfantv** [comment]
what about @bootstrap?

**Comment by Foxandxss** [comment]
We are not bootstrap, that namespace belongs to Twitter.

**Comment by wesleycho** [comment]
@bootstrap is too generic.

**Comment by icfantv** [comment]
I say we arm-wrestle them for it...

**Comment by pkozlowski-opensource** [comment]
So, it looks like renaming a repo is fairly consequence-less as GitHub is setting automatic redirects: 
* https://github.com/blog/1508-repository-redirects-are-here
* https://help.github.com/articles/renaming-a-repository/ 

So people having old links will still land in our repo. As such my vote goes to renaming this repo to `ng-bootstrap` before the final release.

**Comment by pkozlowski-opensource** [comment]
This is done now.
