### ISSUE TITLE
ngbModal after open focus on close button

### ISSUE THREAD

**Issue by 13bit** [ng-bootstrap/ng-bootstrap#2814]
### Bug description:
When I open modal window I see focus on close button.

### Demo:
[stackblitz](https://stackblitz.com/angular/pmajproyyoq)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 6.1.9

ng-bootstrap: 3.3.0

Bootstrap: 4.0.0

**Comment by pkozlowski-opensource** [comment]
> When I open modal window I see focus on close button.

Great, this is the intended behaviour! What would you expect otherwise?

**Comment by pkozlowski-opensource** [comment]
As commented, we need to move focus to within modal for accessibility reasons / proper keyboard navigation. By default we focus the first focusable element _within_ modal, which in your case is a close button. If you want to focus another element within modal you can add the `ngbAutofocus` attribute to it. Check https://ng-bootstrap.github.io/#/components/modal/examples#focus for more info.

**Comment by KalenGibbons** [comment]
I have to agree with @13bit.  Not all modal windows should require a focused element.  I have a window that provides a list of links to the user, and after upgrading from version 2.x the first link in the list is now highlighted.  This does not make sense, I do not want to force the user's attention to one part of the window over another. A focused element indicates a prioritized action to the user, and this is not always desired.

It should be the developer's option to apply focus to one element or another using the ngbAutofocus attribute, it shouldn't be mandatory.

**Comment by UniQP** [comment]
I also agree that opening a modal without focusing an element should be possible.

Does focusing the modal itself solve the accessibility issues?

**Comment by benouat** [comment]
> Does focusing the modal itself solve the accessibility issues?

@UniQP nope

---

> But When I open modal and see focus on close button looks like not good UI.

@13bit One of the first thing that blind users need to know when landing on a modal is how to exit this modal.

---

> It should be the developer's option to apply focus to one element or another using the ngbAutofocus attribute, it shouldn't be mandatory.

@KalenGibbons this is exactly what this is about. The behaviour is not mandatory at all, it's just the default one which is configurable with usage of `ngbAutofocus`.

**Comment by qqaimh** [comment]
显得不圆润

**Comment by canbax** [comment]
I think not focusing on any element at the beginning is more fair. I also think it is easier for both of users and developers of this library.

**Comment by justingolden21** [comment]
I think that for accessibility, the close button should be the default item focused. However, the option to change this should be available for developers.

I actually got to this thread by the opposite case: my close buttons don't focus when the modal opens. I'm on Bootstrap 4.3.1, and when a button to open a modal is clicked, that button stays focused. This is fine default behavior, however, I cannot figure out how to change it.

I currently have this event listener set in the onload function, per the [docs](https://getbootstrap.com/docs/4.3/components/modal/):

`	
$('.modal').on('shown.bs.modal', ()=> {
	$(this).children('.modal-dialog').children('.modal-content').children('.modal-header').children('.close').focus();
	});`

**Comment by JUzlo** [comment]
k,

**Comment by adamcbuckley** [comment]
The Bootstrap 5 example does not auto-focus the close button https://getbootstrap.com/docs/5.1/components/modal/#live-demo
