### ISSUE TITLE
it is not possible to reset input value for typeahead component

### ISSUE THREAD

**Issue by mdelprado86** [ng-bootstrap/ng-bootstrap#2816]
### Bug description:

For the typeahead component, it is not possible to clear the model after the results list appears. If the results list doesn't appear, the model can be cleared from a button without problem

### Steps to reproduce:
- open [https://stackblitz.com/edit/angular-rybwwn-w3w4ca](https://stackblitz.com/edit/angular-rybwwn-w3w4ca)
- introduce text "aaa"
- click on button "Clear"
- the input is cleared
- introduce text "ala"
- click on button "Clear"
- the input is not cleared

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 6.1.0

ng-bootstrap: 3.3.0

Bootstrap: 4.0

**Comment by angelika** [comment]
Does anybody know a possible workaround for this? I don't care how dirty it is, I just need it to work :D

**Comment by wannadream** [comment]
Try this:
```
clear(){
    setTimeout(()=>{
      this.model = '';
    }, 200);
  }
```
https://stackblitz.com/edit/angular-rybwwn-vzxdf1

Looks like when you clicked on 'Clear' button, 'onBlur' event was not handled right before 'clear()'.
