### ISSUE TITLE
Request: TimePicker should use Angular's i18n data to get meridian names

### ISSUE THREAD

**Issue by reduckted** [ng-bootstrap/ng-bootstrap#2822]
### Feature Request:

Angular's i18n data [contains the strings for AM and PM](https://github.com/angular/angular/blob/6737e91974c2f5d3bcbed68235cd9ff1730773b3/packages/common/src/i18n/locale_data_api.ts#L152-L165). The TimePicker currently [hard-codes the strings to "AM" and "PM"](https://github.com/ng-bootstrap/ng-bootstrap/blob/dac43f4b271fcf3724f3aec4d2dc1822f0bf3f8e/src/timepicker/timepicker.ts#L85-L86) (though it does supply an i18n attribute). 

The DatePicker uses Angular's locale data for day names and month names via the `NgbDatepickerI18n` service. The TimePicker should also use Angular's locale data via its own i18n service.

I'm more than happy to submit a PR if you agree with this idea. 😄 

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 6+
ng-bootstrap: 3.3.1
Bootstrap: N/A

**Comment by pkozlowski-opensource** [comment]
> I'm more than happy to submit a PR if you agree with this idea. 

Sure, go ahead.
