### ISSUE TITLE
Typeahead sugestions misplaced on screen

### ISSUE THREAD

**Issue by neo-xy** [ng-bootstrap/ng-bootstrap#2825]
.dropdown-menu for Typeahead suggestion window is misplaced on the screen, 
how can I fix that?
pakage.json:

` "@ng-bootstrap/ng-bootstrap": "^3.3.1",
    "bootstrap": "^4.1.3",`

**Comment by pkozlowski-opensource** [comment]
> .dropdown-menu for Typeahead suggestion window is misplaced on the screen,
how can I fix that?

Can't say without a minimal reproduce scenario: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment]
Closing for now as we haven't heard back with a reproduce scenario.
