### ISSUE TITLE
Angualr 7 prod build an expression of type void cannot be tested for truthiness

### ISSUE THREAD

**Issue by suresh2018** [ng-bootstrap/ng-bootstrap#2826]
production build show this issue .please verify below screen shot 

![image](https://user-images.githubusercontent.com/30258184/47428808-ff776c80-d7b1-11e8-9ae5-19e0f865899a.png)

**Comment by pkozlowski-opensource** [comment]
Closing as it is fixed in master

**Comment by sergiorslva** [comment]
Hi, I updated to this version and the problem was fix. But now the layout is broken.
![image](https://user-images.githubusercontent.com/29133355/57693872-a3c2e280-7620-11e9-8f93-d72cf699c936.png)

**Comment by pritammaity123456** [comment]
> its fixed after update ngb 3.3.1

It works for me. Thanks Suresh
