### ISSUE TITLE
the indent on the right does not disappear when you close the modal window

### ISSUE THREAD

**Issue by ilyshkafeed** [ng-bootstrap/ng-bootstrap#2828]
### Bug description:
When you open a modal window, a padding-right element is added to the body.
Do a lot of clicks. Open, close. 
Each time all the padding increases, and remains so.

### Link to minimally-working StackBlitz that reproduces the issue:

I was trying to separate a piece of code from mine. but it failed. 
By experiments I realized this was happening when I lay down inside another component that requires time for processing before showing. While the inner element is processing the data, you can see how the background moves to the left, then falls into place. If at some point quickly close, the indentation on the right will not disappear. (well visible if quickly to click)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7

ng-bootstrap: 2.0.0-alpha.0

Bootstrap: 4.0.0

and 
the component that has invested in the inside: Date Time Range
"ng-pick-datetime": "^7.0.0",

**Comment by pkozlowski-opensource** [comment]
Could you please provide a minimal reproduce scenario for:

> Do a lot of clicks. Open, close.
Each time all the padding increases, and remains so.

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't heard back with a reproduce scenario.
