### ISSUE TITLE
Module not found: Error: Can't resolve '@ng-bootstrap/ng-bootstrap/modal/modal-stack'

### ISSUE THREAD

**Issue by Lars-Axerrio** [ng-bootstrap/ng-bootstrap#2832]
### Bug description:
I'm getting: 
ERROR in ./src/app/modules/shared/services/modal.service.ts
Module not found: Error: Can't resolve '@ng-bootstrap/ng-bootstrap/modal/modal-stack' in 'C:\Workspace\afo-angular\afo\src\app\modules\shared\services'

In the service below

```
import { Injectable, ComponentFactoryResolver, Injector } from '@angular/core';
import {
  NgbModal,
  NgbModalOptions,
  NgbModalRef,
  NgbModalConfig
} from '@ng-bootstrap/ng-bootstrap';
import { BehaviorSubject } from 'rxjs';
import { NgbModalStack } from '@ng-bootstrap/ng-bootstrap/modal/modal-stack';

@Injectable()
export class ModalService extends NgbModal {
  modalOpened: BehaviorSubject<NgbModalRef> = new BehaviorSubject<NgbModalRef>(
    undefined
  );

  constructor(
    private moduleCFR: ComponentFactoryResolver,
    private injector: Injector,
    private modalStack: NgbModalStack,
    private config: NgbModalConfig
  ) {
    super(moduleCFR, injector, modalStack, config);
  }

  open(content: any, options: NgbModalOptions = {backdrop: 'static'}): NgbModalRef {
    const openedModal = super.open(content, options);
    this.modalOpened.next(openedModal);
    return openedModal;
  }
}
```

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.0.1

ng-bootstrap: 4.0.0

Bootstrap: 4.1.1

**Comment by pkozlowski-opensource** [comment]
* `NgbModalStack` is a private API and is not intended to be used by library users;
* you can only import from `@ng-bootstrap/ng-bootstrap` as this is the only available import namespace containing all the public API.

Not sure why you feel like you need `NgbModalStack` as once again, it is supposed to be private API. Could you elaborate on your use-case?

**Comment by pkozlowski-opensource** [comment]
Oh, I think I see - you are trying to extend the `NgbModal` but it is not intended for extension. Composition would be a better approach here, although I'm not sure what you are trying to achieve, functionally speaking, so hard to say for sure...

**Comment by Lars-Axerrio** [comment]
Ah I use the service as displayed in the stack to create modals. I updated from @ng-bootstrap/ng-bootstrap 2.2.2 where it was not a problem. I use the service to create modals troughout the application. This extra layer of abstraction helps me modify all of the modals at once without changing the implementations. But I'm still able to modify a specific implementation if I would want to do so. 

I'm sorry I listed it as a bug in that case.

**Comment by pkozlowski-opensource** [comment]
Right. As commented above you should rather use composition here, ex.:

```typescript
class MyCustomModalService {
   constructor(private _ngbModal: NgbModal) {}

   open(settingParameterId) {
      const modalRef = this._ngbModal.open(WebsiteSettingParameterEditComponent, { 
          size: 'lg',
          backdrop: 'static'
      });
      // Pass parameters to modal
      modalRef.componentInstance.settingParameterId = settingParameterId;  

      return modalRef;
   }
}```

In short: favour composition over inheritance

**Comment by danday74** [comment]
I upgrade from ng-bootstrap v1 to v4 - unit tests started failing because of NgbModalStack - I just removed all references to NgbModalStack and unit tests started working again
