### ISSUE TITLE
where is multiple datepicker ?

### ISSUE THREAD

**Issue by dotNetAthlete** [ng-bootstrap/ng-bootstrap#2835]
I'm trying to implement the multiple months version of the datepicker examples here:

https://ng-bootstrap.github.io/#/components/datepicker/examples.

But there is no clear example that will compile.

Here is my package.json:

{
  "name": "on-call-manager",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/cdk": "^6.4.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/material": "^6.4.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@ng-bootstrap/ng-bootstrap": "^2.2.2",
    "@ngx-pwa/local-storage": "^6.0.0-rc.1",
    "angular-font-awesome": "^3.1.2",
    "blob-util": "^2.0.2",
    "bootstrap": "^4.1.3",
    "buffer": "^5.2.0",
    "compass-mixins": "^0.12.10",
    "core-js": "^2.5.4",
    "cors": "^2.8.4",
    "events": "^3.0.0",
    "font-awesome": "^4.7.0",
    "formidable": "^1.2.1",
    "guid-typescript": "^1.0.7",
    "js-xlsx": "^0.8.22",
    "ng2-file-upload": "^1.3.0",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.2.1",
    "stream": "0.0.2",
    "timers": "^0.1.1",
    "websocket-extensions": "^0.1.3",
    "ws": "^3.3.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.8",
    "@angular/cli": "~6.0.8",
    "@angular/compiler-cli": "^6.0.3",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^8.10.24",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ngx-typeahead": "^6.2.0",
    "protractor": "^5.4.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2",
    "webpack-dev-server": "^3.1.4"
  }
}

Do I need to implement ngbd-datepicker-multiple myself ?
@Component({
  selector: 'ngbd-datepicker-multiple',
  templateUrl: './datepicker-multiple.html',
  styles: [`
    select.custom-select {
      margin: 0.5rem 0.5rem 0 0;
      width: auto;
    }
  `]
})

**Comment by pkozlowski-opensource** [comment]
You can use the `displayMonths` input to indicate number of months to display, ex.: `[displayMonths]="3"` to display3 months. Demo is here: https://ng-bootstrap.github.io/#/components/datepicker/examples#multiple

**Comment by pkozlowski-opensource** [comment]
You can also fork stackblitz examples from our demo page, ex.: https://stackblitz.com/edit/angular-dzvbqn?file=app/app.component.ts
