### ISSUE TITLE
NgbDatePicker Can't set DatePicker Date value on modal popup in Angular 6

### ISSUE THREAD

**Issue by JYeeRepo** [ng-bootstrap/ng-bootstrap#2836]
Hi,

I have been struggling to set the NgbDatePicker date value in my modal popup. I google but none of the examples are working.

Here is the component.html code

<ng-template #content let-modal>
    <div class="modal-header">
      <h4 class="modal-title" id="modal-basic-title">Add New Meeting</h4> 
      &nbsp;
      <i class="material-icons">schedule</i>
      <button type="button" class="close" aria-label="Close" (click)="modal.dismiss('Cross click')">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <form >
        <div class="form-group">
          <label for="meetingDate">Meeting Date:</label>
          <div class="input-group">
              <input type="datetime-local" id="meetingDate" class="form-control" placeholder="yyyy-mm-dd" name="dp1" #c2="ngModel" [(ngModel)]="meetingRequest.MeetingDt" ngbDatepicker #d1="ngbDatepicker">  
              <div class="input-group-addon" (click)="d1.toggle()" >  
                  <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> 
              </div>           
        </div>
      </form>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-outline-dark" (click)="modal.close('Close click')">Cancel</button>
      <input type="submit" value="Save" class="btn btn-primary" (click) ="saveMeeting()" >
    </div>
  </ng-template>

The following code is called to open the modal popup . As you can see, I tried a few methods but none are working. In the Add method, the date is saved to meetingRequest.meetingDt and the value is

"Sun Nov 11 2018 12:00:00 GMT-050) which looks like a date object.

When I set the  datepicker value with the code, 
this.meetingRequest.MeetingDt = selectedRow.meetingDt;
The UI datepicker is blank. If I commented out the code, the datepicker value shows up with the old value. I see alot of examples of setting the date to  { 'year': 2018, 'month': 10, 'day': 30}; but so far it is not working. 

Any help is greatly appreciated.

 public meetingRequest = {
    "MeetingDt":  { 'year': 1970, 'month': 11, 'day': 11 },
    };

  editModal(content, selectedRow) {

    this.meetingRequest.MeetingId = selectedRow.meetingId;

    const mdt = new Date(selectedRow.meetingDt);
 
  
    const mm = mdt.getMonth() + 1;
    this.meetingRequest.MeetingDt = { 'year': mdt.getFullYear(), 'month': mm, 'day': mdt.getDate()};

    //this.meetingRequest.MeetingDt = { 'year': 2018, 'month': 10, 'day': 30};

   // this.meetingRequest.MeetingDt = selectedRow.meetingDt;
   // this.meetingRequest.PublicDate = selectedRow.publicDate;
    this.displayMessage = selectedRow.type;
     
    //(this.meetingRequest.MeetingDt = new Date(selectedRow.modDt);

    //const mm = mdt.getMonth() + 1;
    //this.meetingRequest.MeetingDt = { 'year': mdt.getFullYear(), 'month': mm, 'day': mdt.getDate() };

    this.modalService.open(content, { centered: true });
  }

**Comment by pkozlowski-opensource** [comment]
Please provide a minimal reproduce scenario in a stackblitz as requested in the issue template: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't heard back with a reproduce scenario.
