### ISSUE TITLE
Missing export of NgbDate

### ISSUE THREAD

**Issue by dotNetAthlete** [ng-bootstrap/ng-bootstrap#2837]
I'm using Angular 6.0.3
ng-bootstrap-2.2.2.tgz

import { NgbDate, NgbCalendar } from '@ng-bootstrap/ng-bootstrap';

- has no exported member 'NgbDate'

Interestingly, if I open node_modules\@ng-bootstrap\ng-bootstrap\index.js in my app
NgbDate is nowhere to be seen! - shouldn't it be in here ?

I'm trying to implement datepicker.range so I need the following imports in my component:
import {NgbDate, NgbCalendar} from '@ng-bootstrap/ng-bootstrap';

**Comment by dotNetAthlete** [comment]
Ok, I couldn't find that issue in a search!

Interestingly, I can do this:
import { NgbDate } from '../../../node_modules/@ng-bootstrap/ng-bootstrap/datepicker/ngb-date';

The app will compile, but is there any implications with the above line ?

**Comment by pkozlowski-opensource** [comment]
> The app will compile, but is there any implications with the above line ?

Depends on the packager setup but you might pull some code twice into your app bundles and / or break certain build scenarios. Not recommended really, especially that we don't consider anything below `@ng-bootstrap/ng-bootstrap` as "public" URLs and we can change them even in minor releases.

Again, your best option is to update to 3.0.0 (or 4.0.0 and Angular 7 at this point).

**Comment by dotNetAthlete** [comment]
Ok, but I really don't want to risk breaking my app or getting into a package circular dependency hell (which has happened before).
I'm only just getting to grips with Angular 6 !

**Comment by pkozlowski-opensource** [comment]
ng-bootstrap 3.x is compatible with Angular 6: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#dependencies

**Comment by dotNetAthlete** [comment]
Will that work with bootstrap 4 css ?
I'm using:
https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css

**Comment by dotNetAthlete** [comment]
Ok
I have followed your advice and just as I suspected I have broken the app.

npm install @ng-bootstrap/ng-bootstrap@3.0.0
npm WARN bootstrap@4.1.3 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.3 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@3.0.0 requires a peer of @angular/common@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@3.0.0 requires a peer of @angular/core@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@3.0.0 requires a peer of @angular/forms@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by dotNetAthlete** [comment]
This is the build log following the above: (for security I have removed my windows username)

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\    \AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'ng-bootstrap@3',
1 verbose cli   '--save' ]
2 info using npm@6.4.1
3 info using node@v8.11.3
4 verbose npm-session ac172425ec371903
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/ng-bootstrap 937ms
8 silly registry:manifest no matching version for ng-bootstrap@3 in the cache. Forcing revalidation
9 http fetch GET 304 https://registry.npmjs.org/ng-bootstrap 68ms (from cache)
10 silly fetchPackageMetaData error for ng-bootstrap@3 No matching version found for ng-bootstrap@3
11 timing stage:rollbackFailedOptional Completed in 1ms
12 timing stage:runTopLevelLifecycles Completed in 2786ms
13 verbose type range
14 verbose stack ng-bootstrap: No matching version found for ng-bootstrap@3
14 verbose stack     at pickManifest \AppData\Roaming\npm\node_modules\npm\node_modules\npm-pick-manifest\index.js:65:11)
14 verbose stack     at fetchPackument.then.packument \AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:52:18)
14 verbose stack     at tryCatcher \AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
14 verbose stack     at Promise._settlePromiseFromHandler \AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
14 verbose stack     at Promise._settlePromise ...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
14 verbose stack     at Promise._settlePromise0 ....\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
14 verbose stack     at Promise._settlePromises ....\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
14 verbose stack     at Async._drainQueue ...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
14 verbose stack     at Async._drainQueues ......\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
14 verbose stack     at Immediate.Async.drainQueues .....\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
14 verbose stack     at runCallback (timers.js:810:20)
14 verbose stack     at tryOnImmediate (timers.js:768:5)
14 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
15 verbose cwd C:\Users\everettr\source\repos\on-call-manager
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" .......\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "ng-bootstrap@3" "--save"
18 verbose node v8.11.3
19 verbose npm  v6.4.1
20 error code ETARGET
21 error notarget No matching version found for ng-bootstrap@3
22 error notarget In most cases you or one of your dependencies are requesting
22 error notarget a package version that doesn't exist.
23 verbose exit [ 1, true ]

**Comment by dotNetAthlete** [comment]
YES, but upgrading to 6.1.0 breaks the app!
