### ISSUE TITLE
Typeahead: add support for changing the search function dynamically.

### ISSUE THREAD

**Issue by svegalopez** [ng-bootstrap/ng-bootstrap#2838]
Feature Request: Typeahead 

Enable the use of async pipe in [ngbTypeahead] directive like shown below:
```html
<input [ngbTypeahead]="search$ | async" />
```
The first emission is used by ngOnInit, but further emissions are not processed. Need to implement ngOnChanges on the directive.

### Link to minimally-working StackBlitz that reproduces the issue:

This stackblitz fork shows that the ngbTypeahead directive does not support changing the search function dynamically, and shows an idea of the type of the feature requested.  I expect after emitting a new resolver, the results should be based on the term 'javascript' regardless of what you type in the box. 
https://stackblitz.com/edit/angular-bvsbkh

### Proposed Solution

I think the problem is that the directive does not implement ngOnChanges. I experimented and changed the ng-bootstrap.js source file to add :

```javascript
NgbTypeahead.prototype.ngOnChanges = function(changes) {
        
        if(changes.ngbTypeahead && !changes.ngbTypeahead.firstChange ) {
    
            this.ngbTypeahead = changes.ngbTypeahead.currentValue;
            this._unsubscribeFromUserInput();
            this.ngOnInit();
        }
}
```
This actually makes it work! Now you can emit new resolvers dynamically.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 6.1.0

ng-bootstrap: 3.2.0

Bootstrap: 4.0.0

**Comment by svegalopez** [comment]
@arielpeinado

**Comment by MasteRoi** [comment]
Is there any update about this issue?
I'm trying to implement a switchable button to change also the "text-align:right;" to the 'dropdown-menu' css but can't find a way

**Comment by jhkueh** [comment]
I was able to achieve this by switching the `Observable` mid-way with `switchMap`.

Something like this in your template (`.component.html`):
```html
<input [ngbTypeahead]="search$ | async" />
```
And this in your component file (`.component.ts`):
```ts
search = (text$: Observable<string>) =>
    text$.pipe(
      debounceTime(300),
      switchMap(searchTerm => this.getSearchFunctionByType(this.searchType, text$)) 
    )
```
