### ISSUE TITLE
ngb-datepicker - cannot read property 'day' of undefined

### ISSUE THREAD

**Issue by dotNetAthlete** [ng-bootstrap/ng-bootstrap#2839]
I've been struggling with this for a couple of days now, had I had prior knowledge I would have gone for Angular material.

I am trying to implement a date range in an Angular 6 app as shown here:
https://stackblitz.com/angular/pdkqakgrpja?file=app%2Fdatepicker-range.ts
 but the model binding {{ date.day }} is the problem. 
Why is date not defined ?

**Comment by dotNetAthlete** [comment]
THANKS TO A TYPO:
https://ng-bootstrap.github.io/#/components/datepicker/examples

THIS HAS COST ME TWO DAYS OF DEVELOPMENT TIME :(

The html IS NOT:
<ng-template #t let-date let-focused="focused">

It is:

<ng-template #t let-date = date let-focused="focused">

**Comment by benouat** [comment]
Hi @dotNetAthlete 

Sorry to hear that. There ain't  no typo from the documentation.

This code is valid

```html
<ng-template #t let-date let-focused="focused">
```

It's just that it has been introduced in `v3.3.0` and we do not maintain versioned documentation.
So whenever you look at https://ng-bootstrap.github.io/ it is the documentation for the latest stable version.

Thus, I presume you are using an older version trying to apply the datepicker documentation to your example.

Will see if we should add a disclaimer somehow in the demos/examples stating that this short `$implicit` template context for `date` has been introduced in `3.3.0`

From the Api page it's clearly visible https://ng-bootstrap.github.io/#/components/datepicker/api#DayTemplateContext

<img width="705" alt="image" src="https://user-images.githubusercontent.com/1152740/47903685-4df8cb00-de84-11e8-966f-dccf71fd094b.png">

Once again, I apologise for the time lost here. 😞

**Comment by dotNetAthlete** [comment]
Thanks for the information.
I didn't understand implicit template properties !
Incidentally I updated to ng-bootstrap 4.0.0
