### ISSUE TITLE
Hi,It would be great if Today's date is always highlighted whether a date is chosen or not.Most of the datepickers works this way.

### ISSUE THREAD

**Issue by Tharma** [ng-bootstrap/ng-bootstrap#2840]
People would prefer to know the current date always.

**Comment by Tharma** [comment]
@razzildinho Thanks.I was suggesting a default mechanism instead of custom coding.

**Comment by benouat** [comment]
@Tharma @razzildinho If you have time and the will to do it, feel free to open a PR labeled as `Feature request` for that topic. That would be much appreciated.

**Comment by maxokorokov** [comment]
I'm going to close this as a duplicate of #1470. Please vote for issues.

---

@razzildinho you can also use calendar to get today's date:

```ts
export class NgbdDatepickerCustomday {
  private today: NgbDate;

  constructor(calendar: NgbCalendar) {
    this.today = calendar.getToday();
  }

  isToday(date: NgbDate) { return this.today.equals(date); }
}
```
