### ISSUE TITLE
Modal windows have outline around close buttons 

### ISSUE THREAD

**Issue by RomeroDiver** [ng-bootstrap/ng-bootstrap#2841]
### Bug description:
When opening a modal window, the close button(x) always has outline - the default bootstrap implementation doesn't have this outline. The outline should be seen only on focus

### Link to minimally-working StackBlitz that reproduces the issue:
You can see this behaviour on the official demo page https://ng-bootstrap.github.io/#/components/modal/examples

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:
latest
ng-bootstrap:
latest
Bootstrap:
latest

**Comment by pkozlowski-opensource** [comment]
> The outline should be seen only on focus

But this is precisely the case - the close button is initially focused. Related discussion in #2814

**Comment by RomeroDiver** [comment]
My bad, missed that issue
