### ISSUE TITLE
NgbPagination UI does not reload when changing page size

### ISSUE THREAD

**Issue by cipryd** [ng-bootstrap/ng-bootstrap#2846]
When changing the page size from configuration, the number of pages on the UI remains the same. Is this a bug or I'm doing something wrong?

**Comment by pkozlowski-opensource** [comment]
> Is this a bug or I'm doing something wrong?

Impossible to say till we see a minimal reproduce scenario as requested in the issue template: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment]
Nope, changes in the _global_ configuration are not meant to be tracked / observed. This setting is meant as a global / initial.

**Comment by cipryd** [comment]
Ok thank you.

**Comment by pkozlowski-opensource** [comment]
No pb. Going to close this one as it works as intended and we don't intend to change it.
