### ISSUE TITLE
Dropdown not closing and concluding when item is selected from it, (along with caller, callee and arguments errors)

### ISSUE THREAD

**Issue by dotNetAthlete** [ng-bootstrap/ng-bootstrap#2848]
The dropdown stays open.

I need to select from the list of items in the dropdown where these are generated (or retrieved) at the time that an item is selected from the typeahead:

 
    <div class="form-group search">
      <input (selectItem)="onSelectChange($event)" type="text" class="form-control"
        [ngbTypeahead]="searchClassifications" placeholder="Classification..." [inputFormatter]="classificationFormatMatches"
        [resultFormatter]="classificationFormatMatches">
        <label *ngIf="showSubTypes == true">{{ selectedLogName }}</label>
    </div>

    
    <div *ngIf="showSubTypes" ngbDropdown class="d-inline-block mb-2">
      <button class="btn btn-secondary btn-sm" ngbDropdownToggle data-toggle="modal" data-tooltip="true" data-placement="top"
              title="Select specific call log type.">Log Types
      </button>
      <div ngbDropdownMenu>
        <button type="button" *ngFor="let types of arrayForLogTypes" class="dropdown-item btn btn-secondary btn-sm"
                (click)="onSelectSubItem(types.id, types.logTypeName)">{{ types.logTypeName }}
        </button>
      </div>
    </div>

`onSelectChange(item): void {

    if (Object.values(item)[0]["EmployeeName"] == "No Matching Records") {

      this.addForm.controls['caller'].setValue('');
      this.addForm.controls['callerPhoneNo'].setValue('');
      this.nonBridgewayCaller = true;
      return;
    }
    else {
      this.nonBridgewayCaller = false;
    }

    if (Object.values(item)[0]["Mobile"]) {
      this.addForm.controls['callerPhoneNo'].setValue(Object.values(item)[0]["Mobile"]);
    }

    // show the call log types (sub items)
    if (Object.values(item)[0]["classification"]) {

      this.arrayForLogTypes = [];
      this.searching = false;

      for (let key in item)
        this.parentId = item[key];

      if (this.parentId) {
        var logTypeItems = item["item"].tblLogTypeLu;
        logTypeItems.forEach(logTypes => {
          this.arrayForLogTypes.push({ "id": logTypes.id, "logTypeName": logTypes.logTypeName });
        });
        this.showSubTypes = true;
      };
    }

    if (Object.values(item)[0]["PPSRef"]) {

      if (Object.values(item)[0]["PPSRef"] == "Invalid") {
        this.addForm.patchValue({ ppsRef: "N/A" });
        return;
      }

      this.addForm.controls['ppsRef'].setValue(Object.values(item)[0]["PPSRef"]);
      this.jobNo = Object.values(item)[0]["JobNo"];
      this.jobTitle = Object.values(item)[0]["JobTitle"];
      this.ppsTitle = Object.values(item)[0]["PPSTitle"];
      this.itemNo = Object.values(item)[0]["ItemNo"];
      this.showPPSdetail = true;
    }

    if (Object.values(item)[0]["DepartmentID"]) {
      this.addForm.controls['department'].setValue(Object.values(item)[0]["DepartmentID"]);
    }

  }

  onSelectSubItem(id, name): void {

    switch (id) {
      case 12: this.router.navigate(['AIR_Checklist']);
        break;
      case 19:
      case 20: window.open('https://swp.bridgeway.consulting', '_blank');
        break;
      default: this.selectedLogId = id;
        break;
    }

    this.selectedLogId = id;
    this.selectedLogName = name;
    console.log('onSubItemSelected ', this.selectedLogName);  
  }

`// incident classification...
  classificationFormatMatches = (value: any) => value.classification;

  searchClassifications = (text$: Observable<string>) =>
    text$.pipe(
      debounceTime(200),
      distinctUntilChanged(),
      tap(() => this.searching = true),
      switchMap(term => term.length < 2 ? [] :
        this.logTypes$.pipe(
          tap(() => this.searchFailed = false),
          catchError(() => {
            this.searchFailed = true;
            return of([]);
          }))
      ),
      tap(() => this.searching = false)
    );`

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we need a minimal reproduce scenario to be able to progress on this one, see: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by dotNetAthlete** [comment]
I would really like to crate a stackblitz, but my project is a work project containing potentially confidential information or code, I'll try and modify a fork from the existing example to as close as possible ...

**Comment by pkozlowski-opensource** [comment]
> I'll try and modify a fork from the existing example to as close as possible ...

Closing as we haven't heard back with a reproduce scenario. Please open a new issue with a minimal reproduce scenario in a stackblitz if this is still an issue for you.
