### ISSUE TITLE
Vertical Tabs Alignment issue

### ISSUE THREAD

**Issue by seanbotha123** [ng-bootstrap/ng-bootstrap#2849]
### Bug description:

When using vertical tabs / pills, the component does not follow the same layout as bootstrap has (i.e. tabs above, and not beside):

![image](https://user-images.githubusercontent.com/5496698/48129984-d23bbb80-e293-11e8-9984-80ea2cb60aa3.png)

### Link to minimally-working StackBlitz that reproduces the issue:

https://ng-bootstrap.github.io/#/components/tabset/examples#orientation / 
https://stackblitz.com/angular/aaadxgoxkrmq

VS

https://getbootstrap.com/docs/4.0/components/navs/#pills-with-dropdowns ('Vertical pills')

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.0.0

ng-bootstrap: 4.0.0

Bootstrap: 4.1

**Comment by benouat** [comment]
As @fbasso mentioned, our generated markup is somehow missing some parts from original Bootstrap in order to properly implement vertical tabs, so I'll flag this as feature request

**Comment by nisckis** [comment]
Good evening,
not sure if this would help anyone with the same problem, right now for vertical tabs I'm using something like this https://stackblitz.com/edit/angular-hvx9bl
Probably it is not the most clean way although it gets the work done.

**Comment by maxokorokov** [comment]
Was mistagged as `accordion`
Was fixed quite a while ago → https://ng-bootstrap.github.io/#/components/nav/examples#vertical
