### ISSUE TITLE
ngbdropdownToggle won't close after item is selected.

### ISSUE THREAD

**Issue by dotNetAthlete** [ng-bootstrap/ng-bootstrap#2852]
I have some html thus:

`<div *ngIf="showSubTypes" ngbDropdown class="d-inline-block mb-2">
      <button class="btn btn-secondary btn-sm" ngbDropdownToggle data-toggle="modal" data-tooltip="true" data-placement="top"
        title="Select specific call log type.">Log Types
      </button>
      <div ngbDropdownMenu>
        <button type="button" *ngFor="let types of arrayForLogTypes" class="dropdown-item btn btn-secondary btn-sm"
                (click)="onSelectSubItem(types.id, types.logTypeName)">{{ types.logTypeName }}
        </button>
      </div>
    </div>`

The drop down is only shown when the selected item of another directive is selected.
But the drop-down won't close.

In addition, as soon as the mouse is clicked on the un-opened dropdown, the following error occurs in the console:

`TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
CreateCallComponent.html:2
message:"'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them"
ngDebugContext:DebugContext_ {view: Object, nodeIndex: 3, nodeDef: Object, …}
component:CreateCallComponent
componentRenderElement:app-create-call
context:CreateCallComponent
elDef:Object {nodeIndex: 1, parent: Object, renderParent: Object, …}
elOrCompView:Object
elView:Object {def: Object, parent: Object, viewContainerParent: null, …}
injector:Injector_
nodeDef:Object {nodeIndex: 3, parent: Object, renderParent: Object, …}
nodeIndex:3
providerTokens:Array(4)
references:Object`
renderNode:form.ng-invalid.ng-dirty.ng-touched
view:Object {def: Object, parent: Object, viewContainerParent: null, …}
__proto__:Object {elOrCompView: <accessor>, injector: <accessor>, component: <accessor>, …}

This error is stopping the drop down closing.

Looking at the browser source seems to indicate that the click event hasn't been bound in time!

In the source, I see:
`<!-- bindings={"ng-reflect -ng-for-of": "[object Object],[object Object]"}-->`

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we need a minimal reproduce scenario for any potential bug reports: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by benouat** [comment]
It's been 12 days and as mentioned by @pkozlowski-opensource previously, without a reproducible scenario, we can't investigate.

So closing for now.
