### ISSUE TITLE
Modal - close 'x' button is selected

### ISSUE THREAD

**Issue by tomaszzmudzinski** [ng-bootstrap/ng-bootstrap#2853]
### Bug description:

Hi, after I've updated ng-bootstrap from 2.2.2 to 4.0.0 I have some problem with modal. I thought that this is my project specific problem, but it also exists in a library website: https://ng-bootstrap.github.io/#/components/modal/examples. When I open modal 'x' button has some strange border around (it looks like selected). Look at the screen:

<img width="1680" alt="image screen" src="https://user-images.githubusercontent.com/4519335/48159737-56169780-e2d6-11e8-82b2-16acf2a4cec6.png">

### Link to minimally-working StackBlitz that reproduces the issue:

This bug exists even on the library website so I will not put the link to StackBlitz

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.0.2

ng-bootstrap: 4.0.0

Bootstrap: 4.0.0

**Comment by pkozlowski-opensource** [comment]
Same as #2841 - this is by design.

**Comment by tomaszzmudzinski** [comment]
This outline looks really bad. Is there some way to remove it or make it transparent?

**Comment by benouat** [comment]
You could certainly tweak it by changing the `outline` css property.
Nonetheless, removing it, or making it transparent would really be bad in term of usability. Impaired users rely on this kind of outline to know what is focused.

I would not recommend removing it.

**Comment by MidhunPrakash96** [comment]
can solve this by adding ngbAutofocus to any other element
[https://ng-bootstrap.github.io/#/components/modal/examples#focus])
