### ISSUE TITLE
Leak tooltip dom nodes when container="body"

### ISSUE THREAD

**Issue by ChristosGeorgiou** [ng-bootstrap/ng-bootstrap#2859]
### Bug description:

It seems that tooltip has a leak in dom nodes when is placed in body

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-cpluci

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.0.1

ng-bootstrap: 4.0.0

Bootstrap: 4.0.0

**Comment by pkozlowski-opensource** [comment]
I'm sorry but it is not clear from the description / stackblitz what you mean exactly by:
> It seems that tooltip has a leak in dom nodes when is placed in body

Could you please elaborate?

**Comment by ChristosGeorgiou** [comment]
Try the following steps

1. Open the stackblitz page to a new chrome tab
2. Open both the `performance` and `performance monitor` panels
3. Force clear with the `collect garbage` button from the performance. The `DOM Nodes` counter of the `performance monitor` should drop to a minimum
4. Hover a few times on the tooltip button of the page and repeat the 3rd step

Detached nodes should be removed but it seems that tooltip binds the root elem and GC will not work. 

Note that, this will also happen:
- even if the tooltip is not placed in body, but instead the button has an *ngIf that toggles it on/off the page.
- there is a modal opened before the tooltip is shown. Every time the modal is opened, the "base" elem of the tooltip detached but not removed

I created this issue with a simple example because I believe that somehow is correlated

**Comment by pkozlowski-opensource** [comment]
@ChristosGeorgiou Are you running your application in AOT / production mode?

**Comment by ChristosGeorgiou** [comment]
I have also the following:
https://stackblitz.com/edit/angular-gtjb5u

In this example the tooltip is not placed in body but there is a modal. 

1. GC and the nodes drop to 62
2. hover once to tooltip and node increase to 71 (+9)
3. GC and the nodes drop to 65 (+3) (probably some placeholder remains)
4. open the modal and node increase to 91 (+26), close and GC

From now on every tooltip hover will permanently increase dom nodes. GC will remove the inner node but the +3 remains will stack.

**Comment by ChristosGeorgiou** [comment]
Hello,

Testing on Win10-1803, with Chrome 70.0.3538.110 (Official Build) (64-bit) in incognito 

On the official page a have the following results:
- When I fresh-open the (https://ng-bootstrap.github.io/#/components/tooltip/examples), I have 5042 nodes
- I hover on the basic tooltip and nodes are increased to 5049 (+7 nodes)
- I GC and the total is dropped to 5048 (+6 nodes)

So that +6 node are never gone. Actually if I hover the the next tooltip button there are another +4 nodes that are "stuck", and there are +4 for every "different" tooltip btn

You are correct that the append-to-body does not leave any node at all. That weird (in fact, I am pretty sure that wasn't the case when I submitted the issue).

However, If you run the stackblitz scripts you will see the leak (maybe this is a conflict with some other package :/ ). The project is just the default generated one from their scripts.

**Comment by maxokorokov** [comment]
I don't think there are any leaks, I've made a small demo (something along this lines: https://stackblitz.com/edit/angular-fq8x8l). Running locally in prod mode gives something like this:

![screen shot 2018-12-06 at 14 40 33](https://user-images.githubusercontent.com/8074436/49587985-ce1fbe00-f965-11e8-945e-519d88123d4e.png)

Everything is GC'ed eventually.
