### ISSUE TITLE
startDate is not setting date in Ngb 3

### ISSUE THREAD

**Issue by santhosh-ps** [ng-bootstrap/ng-bootstrap#2860]
### Bug description:
Setting startDate is only setting up to month level, date is not set now. It was working in version 2 and also working in version 4

### Link to minimally-working StackBlitz that reproduces the issue:
I am trying to set the startDate to nov 3 2018 in the following examples, working in ngb4, In ngb3 the first day of nov is selected instead of 3rd.

working ngb 4 test app : https://stackblitz.com/edit/angular-4pywuj-emrpvp
buggy ngb 3 test app: https://stackblitz.com/edit/angular-4pywuj

### Versions of Angular, ng-bootstrap and Bootstrap:
please refer stackblitz links above

**Comment by pkozlowski-opensource** [comment]
Sorry, we are not back-patching releases - if things work correctly in 4.0.0 we are not going to release 3.x patches. Your best shoot is to update to 4.0.0

**Comment by santhosh-ps** [comment]
@pkozlowski-opensource okay
