### ISSUE TITLE
(datepicker) disable past dates

### ISSUE THREAD

**Issue by beingbing** [ng-bootstrap/ng-bootstrap#2863]
I am working on a feature in which I give a due-date to a task present in a to-do list. For that I am using ng-bootstrap datepicker.

### Bug description:
My problem is I want to let user choose a date only from future, for that I want to disable all past dates from today, i.e., a user can choose today, tomorrow or any day in the future, but user should not be able to select any past date. I tried using [minDate] feature, but in that i need to pass a static value in that json, instead what i want is whatever date today is, all previous dates from today gets disabled.

Frankly, I don't know whether it is a bug or a feature requirement.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: v6

ng-bootstrap: ^3.2.0

Bootstrap: ^4.1.1

**Comment by pkozlowski-opensource** [comment]
You can use `markDisabled` for this effect: https://ng-bootstrap.github.io/#/components/datepicker/api

Please ask support questions like this one using a dedicated channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
