### ISSUE TITLE
ngbDatepicker (click) handler not working.

### ISSUE THREAD

**Issue by dotNetAthlete** [ng-bootstrap/ng-bootstrap#2865]
I need to write code in the d.toggle() event, but it is not being hit.
I'm using reactive forms instead of ngModel.

I'm implementing toggle() { } like that in the component, but it is not being hit.

**Comment by pkozlowski-opensource** [comment]
https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

**Comment by benouat** [comment]
It's been 7 days and as mentioned by @pkozlowski-opensource previously, without a reproducible scenario, we can't investigate.

So closing for now.
