### ISSUE TITLE
Accordion disabled  fieldset can't navigate (open, close)

### ISSUE THREAD

**Issue by AlexKhymenko** [ng-bootstrap/ng-bootstrap#2868]
Good day. 
In accordion header you have changed from` <a>` tag to `<button>`. And now when we have disabled fieldset it's not possible to close and open accordion . Is it possible to revert back to `<a>` tag, or somehow to enable accordion? 

And when user have like 5 its ok to make them open but when you have 20 its not good ux to leave them all open :-)
Thank You.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7 

ng-bootstrap: 4

Bootstrap: 4

**Comment by benouat** [comment]
Hi @AlexKhymenko , would you mind demonstrate the behaviour you are describing in a Stackblitz ? 
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by AlexKhymenko** [comment]
@benouat  Yes sure here https://stackblitz.com/edit/angular-sg6mry

**Comment by benouat** [comment]
Ohh I see!

Unfortunately we are compliant with what Bootstrap provide. We did the move from `<a>` to `<button>` to be more compliant in the first place. We won't roll it back.

Have a look at this [stackblitz](https://bootstrap-pjs-rwidyd.stackblitz.io) which is pure bootstrap, it's the same.

Closing for now as we won't do anything for that.

PS:  as a kind of hint if I would need to workaround myself these things, you can always use a template reference variable `<ngb-accordion #accordion>` and then use the `accordion.collapseAll()` imperatively whenever the fieldset move to disabled state.

**Comment by AlexKhymenko** [comment]
:-( Maybe bootstrap will change one day. :-)
