### ISSUE TITLE
Point ng-bootstrap.io to landing page

### ISSUE THREAD

**Issue by icfantv** [ng-bootstrap/ng-bootstrap#287]
ng-bootstrap.io need to point to our docs landing page in github.  Right now, that's http://ng-bootstrap.github.io/ng-bootstrap/core, but after #281 is implemented, it will need to be http://ng-bootstrap.github.io/ng-bootstrap/ng-bootstrap.

**Comment by wesleycho** [comment]
Just let me know what needs to be done, as I'm the domain owner.

Also, http://ng-bootstrap.github.io/ng-bootstrap/ng-bootstrap ? That's a weird url...

**Comment by icfantv** [comment]
it was just to match angular's way of structuring the projects....but now that you mention it, it is weird....i don't really have any other ideas though, unless GH let's us somehow point the top level org. URL to a sub project.

**Comment by pkozlowski-opensource** [comment]
We should have the address being and we should use https://help.github.com/articles/user-organization-and-project-pages/#user--organization-pages. This means that we need to create the `ng-bootstrap.github.io` repo if I'm reading this correctly.

We need to decide if `ng-bootstrap.github.io` will just redirect to `ng-bootstrap.github.io/ng-bootstrap` so we can keep generated docs in one repo. Or alternatively we can deploy generated docs to the `ng-bootstrap.github.io` repo.

**Comment by Foxandxss** [comment]
Yes, we can create that repo so we can use that url ourselves. We can tune up the gulp task that deploys the demo to deploy it in that repo.

**Comment by pkozlowski-opensource** [comment]
Created https://github.com/ng-bootstrap/ng-bootstrap.github.io. Going to push a dummy HTML page to it so we can see if gh-pages are fine and we can redirect the domain.

**Comment by pkozlowski-opensource** [comment]
@wesleycho I've pushed a simple index.html to https://ng-bootstrap.github.io/ - could you please do the necessary magic to point ng-bootstrap.io to this repo?

**Comment by wesleycho** [comment]
ng-bootstrap.io

**Comment by sirajc** [comment]
[ng-bootstrap.io](http://ng-bootstrap.io) is redirecting to https://ng-bootstrap.github.io/

I am not aware, but are there any plans to use Custom Domain https://help.github.com/articles/quick-start-setting-up-a-custom-domain/ and retain [ng-bootstrap.io](http://ng-bootstrap.io) and not redirect, but serve it from github.io

**Comment by wesleycho** [comment]
Thanks @sirajc - I now have it configured properly, so closing this issue!

**Comment by pkozlowski-opensource** [comment]
@wesleycho wasn't the whole point of the exercise to make https://ng-bootstrap.io/ work? It still doesn't work for me so re-opening.

**Comment by sirajc** [comment]
It is working for me

![snapsink](https://cloud.githubusercontent.com/assets/5340498/16611055/c98619ee-437c-11e6-9120-5bfa1e67468a.png)

**Comment by sirajc** [comment]
We can also configure cloudflare on top of ng-bootstrap.io
* We get CDN caching
* https
Both for free

**Comment by pkozlowski-opensource** [comment]
@sirajc did it work for you with HTTPS??? It works for me with HTTP but not with HTTPS

**Comment by sirajc** [comment]
it does not work with HTTPS

**Comment by sirajc** [comment]
We can use CloudFlare to support HTTPS and we can force HTTPS only

**Comment by wesleycho** [comment]
Looks like that is impossible currently: https://help.github.com/articles/securing-your-github-pages-site-with-https/

> HTTPS is not supported for GitHub Pages using custom domains.

**Comment by pkozlowski-opensource** [comment]
> HTTPS is not supported for GitHub Pages using custom domains.

Oh, bummer....

**Comment by sirajc** [comment]
Cloudflare can help solve this too. We can enfore HTTPS on CloudFlare, but the communication between CloudFlare and github will be http. End user will see HTTPS with green padlock
> Flexible SSL: There is an encrypted connection between your website visitors and CloudFlare, but not from CloudFlare to your server.
You do not need an SSL certificate on your server
Visitors will see the SSL lock icon in their browser

**Comment by pkozlowski-opensource** [comment]
Going to close this one as nothing happened for ~6 months. @wesleycho feel free to take over this one as soon as you / anyone has free cycles.
