### ISSUE TITLE
ngx typeahead: Don't select first value by default until the first up/down arrow keypress

### ISSUE THREAD

**Issue by Rajanusa** [ng-bootstrap/ng-bootstrap#2876]
Hi

When user type and it has many match. on TAB, it select the first and assign it to the text box. 
I don't want any default selection unless user select by using up/down arrow. 
Is there any way to overcome this behavior by setting any properties. 
if no option available, Can you implement it.

Thanks
Rajan

**Comment by pkozlowski-opensource** [comment]
We don't maintain `ngx-typeahead` in this repo, I guess you've meant to open this issue elsewhere.

But if you happen to use  https://ng-bootstrap.github.io/#/components/typeahead/examples please open a new issue following our issue template. The description in the current form is not actionable.

**Comment by Rajanusa** [comment]
Hi 
Please find the example given in the ngb bootstrap site.
https://stackblitz.com/angular/ggrreperjgn
if you type tex, iit highligt texas by default and press tab 
My use case is, I want user to enter the data which is not in the list and able to move to next control by pressing tab. but here it is not possible. we have to presss esc and then press tab.
Please let me know if this is not clear

Thanks
Rajan
