### ISSUE TITLE
NgbInputDatepicker: Clicking an "outside day" on previous month closes datepicker when displayMonths > 1

### ISSUE THREAD

**Issue by mafredri** [ng-bootstrap/ng-bootstrap#2879]
### Bug description:

When using displayMonths="2", outsideDays="visible" and autoClose="outside" the datepicker will automatically close when an "outside day" of the previous month is clicked (e.g. 29, 30 or 31 in the attached picture).

<img width="291" alt="image" src="https://user-images.githubusercontent.com/147409/48778863-fa3d0d00-ecde-11e8-9b2e-8a4a91614319.png">

**Note:** This is not reproducible when displayMonths is 1 or autoClose="never", etc.

### Link to minimally-working StackBlitz that reproduces the issue:

This is a fork of the date range selection example with minimal modifications for turning it into an input datepicker and showing outside days: https://stackblitz.com/edit/angular-rku1gf

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.0.4

ng-bootstrap: 4.0.0

Bootstrap: 4.1.3

**Comment by maxokorokov** [comment]
This is harder to fix than it seemed at the first glance, not sure it will make it in `4.0.1`.
Can't provide a better workaround at the moment than using `[autoClose]="false"` and handling outside click yourself...

**Comment by mafredri** [comment]
Thanks for looking into this @maxokorokov. I appreciate the workaround, although for the moment I've hidden the "outside days", which also circumvents the problem :).
