### ISSUE TITLE
ngb-Calendar - Extending the number of years shown 

### ISSUE THREAD

**Issue by sgokulnath** [ng-bootstrap/ng-bootstrap#2885]
Hi,

In the datepicker component, I am shown only 20 years (2008 - 2028) in the dropdown. Is there a possible way to extend the number of years to be shown. (1900-2100)

Thanks in advance.

**Comment by pkozlowski-opensource** [comment]
It is not supported but we've got a feature request for this already: #2412
Closing as duplicate of #2412
