### ISSUE TITLE
ngb typeahead: Don't select first value by default until the first up/down arrow keypress

### ISSUE THREAD

**Issue by Rajanusa** [ng-bootstrap/ng-bootstrap#2887]
### Bug description:
When user type and it has many partial match. on TAB, it select the first and assign it to the text box.
For instance if you type tex, it highlight texas by default and on tab, it select the texas (ie partial match) and assign it to the textbox.

My use case is, I want user to enter the data (ie either partial match /not in the list) and able to move to next control on tab. but here it is not possible. we have to presss esc and then press tab.

I don't want any default selection unless user select by using up/down arrow.
Is there any way to overcome this behavior by setting any properties.
if no option available, Can you implement it.

### Link to minimally-working StackBlitz that reproduces the issue:
Please find the example given in the ngb bootstrap site.
https://stackblitz.com/angular/ggrreperjgn

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 6.1.0

ng-bootstrap: 2.2.2

Bootstrap: v4.1.3

**Comment by pkozlowski-opensource** [comment]
I guess `focusFirst` is what you are looking for: https://ng-bootstrap.github.io/#/components/typeahead/api#NgbTypeahead

**Comment by maxokorokov** [comment]
Second that `focusFirst` fixes the issue, and will close as no response from the submitter

**Comment by Rajanusa** [comment]
Hi Pawel Kozlowski and maxokorokov

Thanks for solution. It works

**Comment by ehealthexperts-rk** [comment]
I need to use the "open on focus" scenario and was annoyed that by simply tabbing over the form the typeahead input field was assigned a value. I was here to create a feature request but actually this issue with the focusFirst option solves my issue. Thank you!
