### ISSUE TITLE
ng-bootstrap hijacking and "advanced usage"

### ISSUE THREAD

**Issue by moshmage** [ng-bootstrap/ng-bootstrap#2889]
I have a bit of a problem, I was using `"@ng-bootstrap/ng-bootstrap": "^1.1.2",` and we had some awesome liberties with it:

- we extended `NgbButtonsLabel` to remove the `{[class.btn] true}`
- we used `NgbModalBackdrop`, `ContentRef` from `popup` and even some utils from `utils` to create a Pane component

Upgrading to `"@ng-bootstrap/ng-bootstrap": "^4.0.0",` made this impossible. The classes are still there, they are simply not exported and we only have access to its typings.

Is there some way I can still make this (short of rolling out our ModalBackdrop, etc, etc)? It was handy knowing we could extend and implement ng-bootstrap to achieve some customizations that are otherwise troublesome to make.

**Comment by moshmage** [comment]
Heh, turns out I can import from the `umd` bundle. a little bit weird, but doable :)

**Comment by pkozlowski-opensource** [comment]
@moshmage we only export things from `@ng-bootstrap/ng-bootstrap` things that we consider to be public API. All the rest is consider private and subject to change without warning, hence not exported.

I'm sure that you can find clever ways of getting your hand on our non-public classes but again, this might break without warning from version to version. 

Designing a library for extensibility is not a small feat and we are very careful about what we consider public.  We might open up some of the classes you are mentioning in the future, but we are not ready for this yet. Your best move for now is to copy over the classes needed, as you did.
