### ISSUE TITLE
Can't resolve '@ng-bootstrap/ng-bootstrap/util/util" error

### ISSUE THREAD

**Issue by devrazka** [ng-bootstrap/ng-bootstrap#2892]
Hi,
 Using angular 7 version.

Have received the error "Module not found: Error: Can't resolve '@ng-bootstrap/ng-bootstrap/util/util" when used the statement for date picker related functionality
`'import { isNumber, toInteger, padNumber } from '@ng-bootstrap/ng-bootstrap/util/util''`

Tried to add the util file mentioned at 'https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/util/util.ts' path, butstill receiving the same error for util file.

Using windows 10 machine and surprisingly the same code is working fine on anohter
linux system.

The code was referred from this site:   https://seegatesite.com/tutorial-to-change-date-format-ng-bootstrap-datepicker-angular-5/

Please advise

**Comment by maxokorokov** [comment]
You can't do deep imports like this:

```ts
import { things } from '@ng-bootstrap/ng-bootstrap/A/B/C'
```

Only like this:

```ts
import { things } from '@ng-bootstrap/ng-bootstrap';
```

We only export things from `@ng-bootstrap/ng-bootstrap` that we consider to be public API. Everything else is considered private and is subject to change, you shouldn't use it in your code.

It might have been possible to do such imports before `v3.0.0` of ng-bootstrap, now you _should_ get the error in question.

**Comment by devrazka** [comment]
Hi Support,

Thanks for the update. One question,if we use like this
`import { isNumber, toInteger, padNumber } from '@ng-bootstrap/ng-bootstrap'`

then it shows error for the statement as 'has no exported member  isNumber'
for @ng-bootstrap/ng-bootstrap.

Is there any alternative for it to use the isNumber,toInteger property?

**Comment by benouat** [comment]
@devrazka as @maxokorokov stated:

> It might have been possible to do such imports before v3.0.0 of ng-bootstrap, now you should get the error in question.

You won't have any other choice than duplicated this code in your app.
