### ISSUE TITLE
ngb-rating swallows traps user keyboard navigation once focused

### ISSUE THREAD

**Issue by peterblazejewicz** [ng-bootstrap/ng-bootstrap#2895]
### Bug description:

Once `ngbRating` gets focused using keyboard navigation, it seems there is no reliable way to move focus to the next control and user navigation capabilities are lost - unless user clicks outside of the control to release focus

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-ng-rating-controls

- click within app to allow keyboard navigation
- move to Button via TAB so it gets focus outline
- move focus via TAB to next controls: rating control
- control gets focused
- try to get focus to next control using TAB

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.0.*

ng-bootstrap: 4.0.0

Bootstrap: 4.1.*

Thanks!

**Comment by maxokorokov** [comment]
FYI, this seems to be broken since `2.2.0`
