### ISSUE TITLE
How to disable previous  date and dates  are unaligned

### ISSUE THREAD

**Issue by PDhamodaran** [ng-bootstrap/ng-bootstrap#2897]
Hi,
I am using Date range picker in Angular 2 app.
I have some doubts
1. How to disable previous date in datepicker
2. If hide the outside Days  the date picker, the picker is unaligned
![screencapture-localhost-44300-clientapp-2018-12-03-17_26_37](https://user-images.githubusercontent.com/33417596/49372455-ba374a80-f720-11e8-8fdd-ed4ea65a9865.png)

**Comment by benouat** [comment]
Thank you @PDhamodaran for reporting a potential bug.

Nonetheless, according to our documentation [You think you've found a bug](
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug) could you please reproduce your scenario in a minimalist Stackblitz in order for us to start working on it ?

**Comment by maxokorokov** [comment]
@PDhamodaran a stackblitz would be helpful, won't be able to do anything with the screenshot.

Also please check the `[outsideDays]` input in the [docs](https://ng-bootstrap.github.io/#/components/datepicker/api#NgbDatepicker) and `outisde days` select box in this [demo](https://ng-bootstrap.github.io/#/components/datepicker/examples#multiple)

**Comment by pkozlowski-opensource** [comment]
Going to close this one for now as we haven't heard back with a reproduce scenario.
