### ISSUE TITLE
Feature request: change NgbModalRef's options after the modal is opened

### ISSUE THREAD

**Issue by EpaXapate** [ng-bootstrap/ng-bootstrap#2904]
It would be nice to be able to change the properties of the opened modal such as `backdrop or` `beforeDismiss.`
I need to change the `backdrop` based on a conditional promise so that the user cannot close the modal when such condition is true.

**Comment by benouat** [comment]
@EpaXapate I don't really see the added value to be able to update these values dynamically ....
Couldn't you simply consume your promise before calling `ngbModalService.open()` ?

**Comment by EpaXapate** [comment]
@benouat Not for my specific use case. What I need is to open the modal like you normalli would and once inside said modal I would make a post request. While that promise is resolving I need to disable the `backdrop` and `keyboard` click events so the user can't close the modal.

**Comment by EpaXapate** [comment]
@benouat Could this issue be addressed any time soon or would a pull request be more convenient?

**Comment by benouat** [comment]
If you already have a PR ready, or if you are willing to invest some time on it, feel free to do so.

Any contribution is always welcome.

**Comment by EpaXapate** [comment]
@Terrafire123 Yes that is one way to do it and considering the current codebase I believe there is no other way to do it without typescript complaining.

**Comment by EpaXapate** [comment]
@benouat You misunderstand my use case. I need to change the beforeDismiss() property inside the modal component's class.

**Comment by benouat** [comment]
@EpaXapate I know !! :) I was just commenting regarding the workaround that @Terrafire123 posted.

Nonetheless, if your post request could be done from outside the modal's component class (like maybe using observables and/or promises), it think it could work 👍

**Comment by EpaXapate** [comment]
@benouat Yes indeed I believe it would and it is a nice way of doing it aswell, unfortunately my post request must be done inside the modal aswell.

**Comment by benouat** [comment]
Another try :)

```typescript
import { Component, Input } from '@angular/core';
import { NgbActiveModal, NgbModal } from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'ngbd-modal-content',
  template: `
    <div class="modal-header">
      <h4 class="modal-title">Hi there!</h4>
      <button type="button" class="close" aria-label="Close" (click)="activeModal.dismiss('Cross click')">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <p>Hello, {{name}}!</p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-outline-dark" (click)="closeWithAnimation()">{{allowDismiss ? 'Close' : 'Please wait 5 seconds...'}}</button>
    </div>
  `
})
export class NgbdModalContent {
  @Input() name;

  allowDismiss = true;

  constructor(public activeModal: NgbActiveModal) {}

  closeWithAnimation() {
    if (this.allowDismiss) {
      console.log('preventing modal to be dismissed');
      this.allowDismiss = false;

      // Do your post request in here
      setTimeout(() => {
        this.allowDismiss = true;
        console.log('modal can be dismissed again');
      }, 5000);
    }
  }
}

@Component({
  selector: 'ngbd-modal-component',
  templateUrl: './modal-component.html'
})
export class NgbdModalComponent {
  constructor(private modalService: NgbModal) {}

  open() {
    const modalRef = this.modalService.open(NgbdModalContent, {
      beforeDismiss: () => modalRef.componentInstance.allowDismiss
    });
    modalRef.componentInstance.name = 'World';
  }
}
```

See live version here: https://stackblitz.com/edit/angular-6xqy8s-modal-prevent-dismiss

**Comment by EpaXapate** [comment]
@benouat Thank you for taking the time to make this demo, something like this does solve my problem without the need to access the ``NgbModalWindow`` instance. Closing the issue.
