### ISSUE TITLE
Previous version doc

### ISSUE THREAD

**Issue by ermamud** [ng-bootstrap/ng-bootstrap#2905]
Hi,

I am stuck with an old version of this package on a old project (v1.1.1) and I need access to the documentation for this specific version. Accessing https://ng-bootstrap.github.io/#/home only gives me the latest v4.0.0. Is there any way to access the previous version's doc ?

Thank you,

**Comment by benouat** [comment]
Hello,

We don't maintain live version of previous version of the documentation.

Nonetheless, you could clone locally the version you are interested in by grabbing it from a tag.

In your case you would need to grab [v1.1.1](
https://github.com/ng-bootstrap/ng-bootstrap/archive/1.1.1.zip), unzip it somewhere, and follow what is described in the `DEVELOPER.md` file (mostly '_Installing NPM Modules_' and '_Running demo locally_')

**Comment by ermamud** [comment]
Thanks @benouat. I will.

**Comment by sugoidesune** [comment]
That is incredibly frustrating. Clearly a reason to use other ui-kits.
Imagine I had to do this for every of the 20+ packages...
Especially since this UI kit stronglu depends on the Angular version, which isn't trivial to update for some projects.

**Comment by triamero** [comment]
If someone need, here is my compilation of all ng-bootstrap versions (except 7+ and alphas/betas):
https://triamero.github.io/ng-bootstrap-old-docs/v6.2.0/#/home
Version can be changed in the top-right corner

**Comment by jasonlloydprice** [comment]
@triamero thank you so much for compiling that documentation.
