### ISSUE TITLE
Datepicker FooterTemplate for pre-Angular 7

### ISSUE THREAD

**Issue by Sara-Cagle** [ng-bootstrap/ng-bootstrap#2906]
### Bug description:

Unable to access the FooterTemplate attribute for the Datepicker (also unable to access NgbCalendar) when using a version of Angular prior to Angular 7--specifically, Angular 5. The Datepicker has [clear documentation](https://ng-bootstrap.github.io/#/components/datepicker/examples#footertemplate), but there is no support for Angular 5.

### Link to minimally-working StackBlitz that reproduces the issue:

 [StackBlitz](https://stackblitz.com/edit/angular-ebriwp) Forked from the example StackBlitz on how to use the footer, and swapped the versions on `package.json`.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 5.2.9

ng-bootstrap: ^1.1.2

Bootstrap:

**Comment by pkozlowski-opensource** [comment]
`footerTemplate` was introduced in ng-bootstrap `3.3.0` as documented here: https://github.com/ng-bootstrap/ng-bootstrap.

ng-bootstrap `3.3.0` requires Angular `^6.1.0` as documented here: https://github.com/ng-bootstrap/ng-bootstrap#dependencies

You need to update your Angular / ng-bootstrap versions to take advantage of this new functionality. Angular 5.x is ~1 year old so it is a good idea to update anyway!

**Comment by Sara-Cagle** [comment]
Please consider that there are technical decisions made on products, including limiting which versions of code can be used, that are not available for negotiation for a number of reasons. By limiting which versions your tools are available on (especially if the version is only 1 year old), you're cutting out a large number of would-be users. 

We won't be upgrading; thanks for your response.
