### ISSUE TITLE
Dynamically changing local doesn't update labels in Datepicker

### ISSUE THREAD

**Issue by eLarocque** [ng-bootstrap/ng-bootstrap#2907]
### Bug description:
There is a great way to add languages using the NgbDatepickerI18n as shown in the Internationalization example in the NgBootstrap [doc page](https://ng-bootstrap.github.io/#/components/datepicker/examples#i18n).
However, the rendered datepicker labels don't change until an action is done in the datepicker when you are changing the language dynamically. (see StackBlitz example for details)

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/ng-bootstrap-datepicker-2907

### Versions of Angular, ng-bootstrap and Bootstrap:
Angular: 7

ng-bootstrap: 4

Bootstrap: 4

**Comment by maxokorokov** [comment]
Related to #1712

**Comment by gpolychronis** [comment]
A workarround on that is putting the datepicker inside a div and "flashing" it.

However, as of now, angular applications aren't meant to switch localization immediately. Is this issue still valid?

**Comment by shoebrizwanathar** [comment]
Hello @eLarocque
I was facing the same issue with the date picker that it does not change the labels of days, month,year until I do a action on date and finally I found a workaround to fix this.

I used navigateTo() function and reset the month and year and it worked for me.

**Comment by aleesaan** [comment]
@maxokorokov what do you think of providing an API to trigger change detection manually? It could be as simple as exposing a `detectChanges()` method, which would look like:

```ts
detectChanges() {
  this.changeDetectorRef.detectChanges();
}
```
I'd prefer this to using the [`navigateTo()`](https://github.com/ng-bootstrap/ng-bootstrap/issues/2907#issuecomment-642535294) workaround mentioned above.

**Comment by eLarocque** [comment]
To be honest, we have since dropped our usage of ng-bootstrap and are instead using @angular/material's datepicker, in combination with a date-fns DateAdapter. I will close this as as mentioned previously, supporting dynamic locales is not currently supported, which was the underlying use case for this request.
There might be other issues listed above, I recommend you open issues individually for those bugs.

Thanks for everyone's feedback!
