### ISSUE TITLE
Disable specific dates

### ISSUE THREAD

**Issue by gauravkadam** [ng-bootstrap/ng-bootstrap#2911]
Hi,

Actually i have one dates array and wanted to enable only those array in the date picker, can you please suggest me a solution for this. 
Below is the configuration am using.

Angular:6.1.9

ng-bootstrap: 4

Thanks in advance

**Comment by maxokorokov** [comment]
- if you believe that we've got a bug in this library than please provide a minimal reproduce scenario in a stackblitz or plunker: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug
- if you are unsure if this is a bug or not than please use an appropriate support channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help

@gauravkadam check the docs, please, https://ng-bootstrap.github.io/#/components/datepicker/overview#limiting-dates
