### ISSUE TITLE
datepicker : how to wrap months if showing 12 months all together 

### ISSUE THREAD

**Issue by hiramannan** [ng-bootstrap/ng-bootstrap#2916]
I am trying to display whole year in a single control using [displayMonth] feature but the months are only rendering in horizontally while i need to wrap them as per page width. if any one has any idea how to do it ?

**Comment by maxokorokov** [comment]
if you are unsure if this is a bug or not than please use an appropriate support channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help

@hiramannan at the moment there is no intention the 12-month view support and month wrapping. 
Try playing with css flexbox wrapping on `.ngb-dp-months` and `.ngb-dp-month` though, might work
