### ISSUE TITLE
ngbRadioGroup does not show selection when disabled

### ISSUE THREAD

**Issue by kleinph** [ng-bootstrap/ng-bootstrap#2918]
### Bug description:
A disabled ngbRadioGroup does not indicate the (pre)selcted value as other form fields do.

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-yj1a6e

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.0.0

ng-bootstrap: 4.0.0

Bootstrap: 4.1.3

**Comment by jnizet** [comment]
This looks like a Bootstrap CSS bug to me. Apparently, if disabled, an active button looks the same as an inactive one.

**Comment by kleinph** [comment]
The issue is more obvious if outline buttons are used:
https://stackblitz.com/edit/angular-yj1a6e-iy9jih

I am not sure if this is intended.

**Comment by maxokorokov** [comment]
Buttons were removed in v13 → https://ng-bootstrap.github.io/releases/12.x/#/components/buttons/overview
