### ISSUE TITLE
[minDate] and [maxDate] validation returns misleading error description

### ISSUE THREAD

**Issue by 03byron** [ng-bootstrap/ng-bootstrap#2922]
### Bug description:
Current [minDate] and [maxDate] validation returns misleading error description. 

E.g. When [minDate] is set to today and you enter yesterday, validate() returns:

`{'ngbDate': {requiredBefore: this.minDate}}`

but it should be 

`{'ngbDate': {requiredAfter: this.minDate}}`

Same applies for [maxDate]. When maxDate is set to today and you enter tomorrow you get:

`{'ngbDate': {requiredAfter: this.maxDate}}`

but it should be

`{'ngbDate': {requiredBefore: this.maxDate}}`

**Comment by maxokorokov** [comment]
Here is the stackblitz with the issue: https://stackblitz.com/edit/angular-snykrp.

```ts
date = 1 OCT 2018
minDate = 10 OCT 2018
```

I would expect the message to be along these lines:
- error: ngbDate is before 10 OCT 2010
- error: ngbDate must be after 10 OCT 2010

Currently it is:
- error: ngbDate required before 10 OCT 2010

```json
FC: {
  "ngbDate": {
    "requiredBefore": {
      "year": 2018,
      "month": 10,
      "day": 10
    }
  }
}
```

I'd prefer to change `requiredBefore` to `isBefore` or `mustBeAfter`.

I'll leave @pkozlowski-opensource decide. And it is a breaking change.
