### ISSUE TITLE
Can't import separate module from NgBootstrap 

### ISSUE THREAD

**Issue by Bulat94** [ng-bootstrap/ng-bootstrap#2933]
I was trying to resolve the problem with my bundle size, and I found that I can't import just separate module for example for popover or accordion, because when I import separate module. NgBootstrap import full library which takes 20% of my bundle size.
On get started page it says "Alternatively you could only import modules with components you need, ex. pagination and alert. The resulting bundle will be smaller in this case."  
https://ng-bootstrap.github.io/#/getting-started

I use webpack angular 7.0.0 and "@ng-bootstrap/ng-bootstrap": "4.0.0"

Best reagards

**Comment by benouat** [comment]
Hello @Bulat94 

Thanks for reporting what looks like an issue for you! Nonetheless could you please detail a bit more what you are doing, and more specifically how you do it ?

**Comment by maxokorokov** [comment]
Also please check comments in #2605 for similar issue for 3.0.0 release. There are some examples

**Comment by maxokorokov** [comment]
I've amended a comment to that issue with `4.0.1` release numbers: https://github.com/ng-bootstrap/ng-bootstrap/issues/2605#issuecomment-448186690

So please be more specific

**Comment by maxokorokov** [comment]
Might be related to #2883, but need info.

**Comment by maxokorokov** [comment]
Closing as no news from the submitter, feel free to reopen if necessary.
