### ISSUE TITLE
ng-bootstrap ivy-ngcc deps not yet supported

### ISSUE THREAD

**Issue by SEVCO** [ng-bootstrap/ng-bootstrap#2942]
### Bug description:
ivy-ngcc build causes:

Compiling @ng-bootstrap/ng-bootstrap - fesm2015 @ng-bootstrap/ng-bootstrap (dtsMapper creation): 1123.585ms Error: deps not yet supported

### Versions of Angular, ng-bootstrap and Bootstrap:
Angular: 7.1.4
ng-bootstrap: 4.0.1
bootstrap: 4.1.3

**Comment by pkozlowski-opensource** [comment]
It is _way_ too early to try to compile ng-bootstrap with ivy We will test ng-bootstrap compatibility when the known issues with the ivy compilation pipeline are resolved  - I'm actually part of the Angular core team and working on ivy every day, so believe, it is too early.

Closing for now, ng-bootstrap _will_ run on ivy at the same time as material (if not faster), but it won't be today nor tomorrow...

**Comment by brunojcm** [comment]
@pkozlowski-opensource what about know? :)

I'm just starting a new project that will take some time to ramp up, and ng-bootstrap in probably my only relevant dependency. Is it reasonable to start trying Ivy now?

**Comment by SEVCO** [comment]
@brunojcm Ivy works fine with ng-bootsrap (Im using Angular >=8)

https://angular.io/guide/ivy
