### ISSUE TITLE
Add Bootstrap 4.2.1 Support and New Components

### ISSUE THREAD

**Issue by omardoma** [ng-bootstrap/ng-bootstrap#2945]
A new version of bootstrap has been released with two new components, loading and toasts, which can be very useful for us, hope you guys support it soon.

Changelog: https://blog.getbootstrap.com/

**Comment by bastienmoulia** [comment]
Like in #2201, toast is a JS component but not spinners which are full HTML/CSS.

There is also a new modal size (xl) PR: #2943.

For the toast there is multiple solution to implement it:
- Like the modal, where we need to create a new component, which is more customizable
- Like [angular-toast](http://foxandxss.github.io/angular-toastr/), where we pass options, which is simpler to use

**Comment by changhuixu** [comment]
I am using https://github.com/scttcper/ngx-toastr which implements toast as a service, instead of component.
Btw: the css in ngx-toastr is not compatible with boostrap 4.2 due to name collapse.

It would be best to see ng-bootstrap has a similar implementation of toast service.
Also, Angular Material Snackbar is a good peer to compare with.

Thanks.

**Comment by vgrigory** [comment]
do you plan to support 4.2.1 in near future ?

**Comment by jameshmread** [comment]
Hello, ngx-toastr `v10.0.2` works properly with bootstrap `v4.2.1` :) I have tested this out in my own repo.

**Comment by DuhSokola** [comment]
Some news about that? It would be very nice to have Toast implemented

**Comment by djsiddz2** [comment]
Bootstrap v4.3.1 is the current version. Is it in the plans to be supported? If yes, when approximately?

**Comment by peterblazejewicz** [comment]
As first step, I believe the version could be bumped to 4.3.1 in `package.json` without much fuss. It does not brake unit test for us, not sure about SL tests. Many minor details are fixed upstream, like interaction behaviours/visual clues in components (cursor types/hovers - see eg. NG Bootstrap carousel missing basic interaction clues when using mouse as using 4.0.0).

**Comment by qqaimh** [comment]
The Spinners is pure css, Add Tosts is perfect
