### ISSUE TITLE
Ngb-tabset tabindex not setting

### ISSUE THREAD

**Issue by loantontk** [ng-bootstrap/ng-bootstrap#2949]
Please add
`'tabindex': [{ type: Input },],`

**Bug description:**
Can´t set the tabindex for ngb-tabset. When I have a tab menu includes many tabs and several other input fields, navigation bar, etc. I want to use tab button on the keyboard to go through all stuffs from the top to the bottom, from the left to the right.  But I could not go to the tab menu (ngb-tabset) as the desired order. It is always be final field that I reached by using tab key, because it is always setted as in tabset.js

`[attr.tabindex]="(tab.disabled ? '-1': undefined)"`

**Link to minimally-working plunker that reproduces the issue:**

Template:

```html
<div class="row tab-menu">
      <div class="col-12">
<ngb-tabset (click)="changeTab()">
<ngb-tab title="Main">
            <ng-template ngbTabContent>
            </ng-template>
          </ngb-tab>
<ngb-tab title="Contact">
            <ng-template ngbTabContent>
            </ng-template>
          </ngb-tab>
</ngb-tabset>
      </div>
    </div>
```

In tabset.js

```js
NgbTabset.decorators = [
        { type: Component, args: [{
                    selector: 'ngb-tabset',
                    exportAs: 'ngbTabset',
                    template: "\n    <ul [class]=\"'nav nav-' + type + (orientation == 'horizontal'?  ' ' + justifyClass : ' flex-column')\" role=\"tablist\">\n      <li class=\"nav-item\" *ngFor=\"let tab of tabs\">\n        <a [id]=\"tab.id\" class=\"nav-link\" [class.active]=\"tab.id === activeId\" [class.disabled]=\"tab.disabled\"\n          href (click)=\"!!select(tab.id)\" role=\"tab\" [attr.tabindex]=\"(tab.disabled ? '-1': undefined)\"\n          [attr.aria-controls]=\"(!destroyOnHide || tab.id === activeId ? tab.id + '-panel' : null)\"\n          [attr.aria-expanded]=\"tab.id === activeId\" [attr.aria-disabled]=\"tab.disabled\">\n          {{tab.title}}<ng-template [ngTemplateOutlet]=\"tab.titleTpl?.templateRef\"></ng-template>\n        </a>\n      </li>\n    </ul>\n    <div class=\"tab-content\">\n      <ng-template ngFor let-tab [ngForOf]=\"tabs\">\n        <div\n          class=\"tab-pane {{tab.id === activeId ? 'active' : null}}\"\n          *ngIf=\"!destroyOnHide || tab.id === activeId\"\n          role=\"tabpanel\"\n          [attr.aria-labelledby]=\"tab.id\" id=\"{{tab.id}}-panel\"\n          [attr.aria-expanded]=\"tab.id === activeId\">\n          <ng-template [ngTemplateOutlet]=\"tab.contentTpl.templateRef\"></ng-template>\n        </div>\n      </ng-template>\n    </div>\n  "
                },] },
    ];
    /** @nocollapse */
    NgbTabset.ctorParameters = function () { return [
        { type: NgbTabsetConfig, },
    ]; };
    NgbTabset.propDecorators = {
        "tabs": [{ type: ContentChildren, args: [NgbTab,] },],
        "activeId": [{ type: Input },],
        "destroyOnHide": [{ type: Input },],
        "justify": [{ type: Input },],
        "orientation": [{ type: Input },],
        "type": [{ type: Input },],
        "tabChange": [{ type: Output },],
```

**Version of Angular, ng-bootstrap, and Bootstrap:**
Angular: 5.2.0
ng-bootstrap: 1.0.0
Bootstrap: 4.0.0

**Comment by maxokorokov** [comment]
Could you please provide a minimal reproduction scenario in the stackblitz, by forking one of the existing ones from this page: https://ng-bootstrap.github.io/#/components/tabset/examples ?

Do you need to add a specific `tabindex` value here: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/tabset/tabset.ts#L97 instead of `undefined` ?

**Comment by maxokorokov** [comment]
Closing as no news from the submitter, feel free to reopen if necessary.

**Comment by Ciferlingvulo** [comment]
Hello,
I too think there should be a way to set the tabindex. In my case it would be 0, but I guess it's be better overall to let the user set whatever tabindex he/she wants.
I don't think any additonal stackblitz would be relevant here, the link to the code you provided is indeed what I'd like to change (more precisely the `nav-link`).

**Comment by mgarcos** [comment]
> Could you please provide a minimal reproduction scenario in the stackblitz, by forking one of the existing ones from this page: https://ng-bootstrap.github.io/#/components/tabset/examples ?
> 
> Do you need to add a specific `tabindex` value here: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/tabset/tabset.ts#L97 instead of `undefined` ?

Here's the stackblitz:  https://angular-b7r68q.stackblitz.io

and yes, we need to add a specific tabindex instead of undefined.
