### ISSUE TITLE
ngb-carousel loades hidden carousel-item images (data transfer waste)

### ISSUE THREAD

**Issue by stefanseeger** [ng-bootstrap/ng-bootstrap#2952]
### Bug description:
ngb-carousel is using `display:none` to hide `.carousel-item`. But `display:none` does not prevent browsers from loading images. Therefore, when having carousels with many images, all the images are loaded when the carousel is displayed. This is resulting into a huge amount of data send and blocking the browser for a few seconds.

Instead, not displayed carousel-items should not be added to the DOM at all.

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-zwdv1y
I added a ton of random images to your example that you can see how it is slowing down the browser.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.0.0 (does not matter)

ng-bootstrap: 4.0.1

Bootstrap: 4.0.0 (does not matter)

**Comment by bastienmoulia** [comment]
You can load only a few images at the start and then load new ones when you go next: https://stackblitz.com/edit/angular-zwdv1y-9tpjln

**Comment by maxokorokov** [comment]
@stefanseeger, we won't add features for the carousel based on the contents of your slides. It might be images, might be several images per silde or no images whatsoever.

I'd suggest you just implement your own preloading logic (it also might vary greatly depending on your use case), like so:
- generate all slides initially (12 in the example)
- display only two first images
- once you navigate, insert the next image

Here is the stackblitz: https://stackblitz.com/edit/angular-zwdv1y-yrzspf
