### ISSUE TITLE
Update NPM version

### ISSUE THREAD

**Issue by tomardern** [ng-bootstrap/ng-bootstrap#2958]
### Bug description:
The latest version of this package on npm is 3.1.4: https://www.npmjs.com/package/ngx-bootstrap

Please can the admin update the package on npm? Thanks!

### Link to minimally-working StackBlitz that reproduces the issue:
N/a - See link above

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: n/a

ng-bootstrap: n/a

Bootstrap: n/a

**Comment by maxokorokov** [comment]
@tomardern this is a different project, called `ng-bootstrap`, our home page is https://ng-bootstrap.github.io
