### ISSUE TITLE
bootstrap theming with ng-boostrap ?

### ISSUE THREAD

**Issue by tahir-jamil** [ng-bootstrap/ng-bootstrap#2959]
hey how can we change the color theme of ng-bootstrap?
as the offical way is to get the references from node_modules but we don't have them.
`https://getbootstrap.com/docs/4.2/getting-started/theming/`

this is my index.html
```
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>tu-shared-app</title>
  <base href="./">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />

  <!-- Latest compiled and minified JavaScript -->
</head>

<body>
  <tu-root></tu-root>
</body>

</html>
```

**Comment by moshmage** [comment]
set some variables in your theme.scss file,
```
$brand-primary:             #ff6702;
$brand-secondary:           #0154a0;
```
then import bootstraps variables,
```
@import "~bootstrap/scss/_variables";
```
then you import bootstrap scss,

```
@import "~bootstrap/scss/bootstrap";
```

finally, import your `theme.scss` file into your `main.scss` file.

---

ps: read `~bootstrap/scss/_variables` and hunt down the variable names

**Comment by benouat** [comment]
Thank you @moshmage for the explanation!
Should be more than enough for @tahir-jamil to start playing around with that.

Closing for now.

**Comment by maxokorokov** [comment]
@moshmage @tahir-jamil also please see this comment: https://github.com/ng-bootstrap/ng-bootstrap/issues/2989#issuecomment-458552870
