### ISSUE TITLE
where is "card" component

### ISSUE THREAD

**Issue by xxyyzz2050** [ng-bootstrap/ng-bootstrap#2966]
I checked your Docs, it seems that some bootstrap components are missing, such as cards.

**Comment by maxokorokov** [comment]
@xxyyzz2050 there is no need in an Angular `NgbCard` component in ng-bootstrap. Card is just html markup → https://getbootstrap.com/docs/4.2/components/card/, there is no logic there, but you can have many different content types on the other hand.

If you need to reuse cards in your application, you can easily wrap the necessary markup in your own component.

Also see #50

**Comment by xxyyzz2050** [comment]
actually, all components are HTML!
you can pass some attribute values and use some defaults to create a card view

`<card img="photo.jpg" title="card title" />`

@maxokorokov

**Comment by benouat** [comment]
@xxyyzz2050 

What @maxokorokov meant is that in Bootstrap you have 2 categories of components, the one with some JavaScript behaviour, and the one purely based on markup.

Card is one of the latest. It **only** rely on markup, it does not have any JavaScript.

Our components only replaces the JQuery JavaScript code by some Angular one :)

**Comment by xxyyzz2050** [comment]
@benouat 
Got it! now the answer is clear.
