### ISSUE TITLE
Datepicker jalali on jhipster  in not work for year start 1919

### ISSUE THREAD

**Issue by rezakhoy** [ng-bootstrap/ng-bootstrap#2968]
Hi 
i have a app on jhipster and use ng-bootstrap on jhipster
i want use alternative calendars support but its not good work

**Comment by maxokorokov** [comment]
@rezakhoy
- if you believe that we've got a bug in this library than please provide a minimal reproduce scenario in a stackblitz: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug
- if you are unsure if this is a bug or not than please use an appropriate support channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help

**Comment by maxokorokov** [comment]
Closing as no news from the submitter, feel free to reopen if necessary.
