### ISSUE TITLE
generateSelectBoxMonths is removing a month when minDate is set

### ISSUE THREAD

**Issue by ogbscoop** [ng-bootstrap/ng-bootstrap#2974]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
January is being removed from the Month dropdown when a minDate is set on an NgbDatepicker and I use the navigateTo() function.

Steps to Reproduce:
1.) Click on the 31st in the Planned Date NgbDatepicker. This will set the Scheduled Date NgbDatepicker to February 1st using the navigateTo() function. This will also set the Scheduled Date NgbDatepicker's minDate to February 1st.
2.) Click the Reset Calculation button below the NgbDatepickers.
Expected Result: Scheduled Date NgbDatepicker's visual should return to Jan 2019. The minDate should also be set to January 18th.
Actual Result: The Jan option is removed from the month drop down in the Scheduled Date NgbDatepicker. The visual is updated correctly, but the month dropdown is now broken

Appears to be due to the Array.slice call in generateSelectBoxMonths in src/datepicker/datepicker-tools.ts, see below.
![generateselectboxmonthsissue](https://user-images.githubusercontent.com/26575378/51354089-6d2dee80-1aaa-11e9-85c9-8ba2866d12cd.png)

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-otbenl

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.1.4

ng-bootstrap: 4.0.1

Bootstrap: 4.1.3

**Comment by maxokorokov** [comment]
Hey, @ogbscoop, I tried to understand your stackblitz, but it looks overly complex and far from the minimal reproduction scenario. I see several issues though with what you're doing:
- do not access and try writing to the private datepicker data, `this.schedDate.model` is not a public API
- use form controls you have instead, try starting from this:

```html
<ngb-datepicker formControlName='planned' [minDate]="minPlannedDate">
<ngb-datepicker formControlName='scheduled' [minDate]="minScheduledDate">
```

```ts
class Component {
  minPlannedDate: NgbDate;
  minScheduledDate: NgbDate;

  plannedControl = new FormControl(null, Validators.required);
  scheduledControl = new FormControl(null, Validators.required);

  ngOnInit() {
    this.calcFormGroup = this._fb.group({
      'planned': this.plannedControl,
      'scheduled': this.scheduleControl
    });

    // listen to date changes
    this.scheduledControl.valueChanges.subscribe(plannedDate => {
      // ...
    })
  }

  // update min date
  this.minPlannedDate = ...

  // read/write dates
  this.plannedControl.setValue(...)
  this.plannedControl.value;
}
```

Please try to apply this to simplify your code. It might either fix your code or provide a simple reproduction scenario.

**Comment by pkozlowski-opensource** [comment]
Closing for now as we haven't heard back.

**Comment by ogbscoop** [comment]
Sorry for not responding! I updated my attempt to not use the model API. The issue I reported went away. Thanks for the quick response and the help @maxokorokov!
