### ISSUE TITLE
focus issue ngb modal

### ISSUE THREAD

**Issue by vishnu283** [ng-bootstrap/ng-bootstrap#2975]
### Bug description:

I'm not able to access the browser navigation buttons with tab key when the ngb model popup is open, as the focus was locked inside the popup. I attached image for your reference.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:6

ng-bootstrap:2.0.0

<img width="1605" alt="screen shot 2019-01-17 at 9 53 00 pm" src="https://user-images.githubusercontent.com/39527020/51368067-7dda6680-1aa2-11e9-8d97-3ee93fc0bb41.png">

**Comment by benouat** [comment]
@vishnu283 this is done on purpose ! It is called _focus trap_
It's an accessibility feature, trapping the focus inside a modal as long as it is opened.

Thus, this is not an issue. I am closing it.
