### ISSUE TITLE
ngbTabset select method callback?

### ISSUE THREAD

**Issue by sushmit-oodles** [ng-bootstrap/ng-bootstrap#2985]
Does ngbTabset's select method support a callback method?

Say I click on a button from tab1 which changes the active tab to tab4 now if I need to scroll to a specific section on tab4.

Right now the `document.querySelector()` gives me 'null' in, since the tab4 doesn't exist in dom yet.

```
onClick(){
    this.myTabset.select(ngbTabId);

    let el = document.querySelector('.new-currency-pair-section');
    console.log('el :', el)      // ====>> null
    el.scrollIntoView();
}
```

**Comment by maxokorokov** [comment]
- if you believe that we've got a bug in this library than please provide a minimal reproduce scenario in a stackblitz: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug
- if you are unsure if this is a bug or not than please use an appropriate support channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help

---

However, @sushmit-oodles you should listen for the tab change on the tabset:
- a `(tabChange)` output → https://ng-bootstrap.github.io/#/components/tabset/api#NgbTabset
- `NgbTabChangeEvent` event payload → https://ng-bootstrap.github.io/#/components/tabset/api#NgbTabChangeEvent
- demo of how to listen for the event and prevent switching if necessary → https://ng-bootstrap.github.io/#/components/tabset/examples#preventchange
