### ISSUE TITLE
Dropdown does not autoClose on outside click (iOS only)

### ISSUE THREAD

**Issue by saimonsez** [ng-bootstrap/ng-bootstrap#2995]
### Bug description:

Dropdown does not autoClose on outside click (iOS only). Tested with an iPad Air 2, iOS 12.1.2.

### Link to minimally-working StackBlitz that reproduces the issue:

With your iOS device, visit
https://ng-bootstrap.github.io/#/components/dropdown/examples
Open the first Dropdown example and click outside of it. The Dropdown will not close.

### Versions of Angular, ng-bootstrap and Bootstrap:

See https://ng-bootstrap.github.io

**Comment by maxokorokov** [comment]
Actually looks like none of the popup widget autoclose works on mobile. cc @divdavem
