### ISSUE TITLE
Undismissable modal

### ISSUE THREAD

**Issue by xyrintech** [ng-bootstrap/ng-bootstrap#2996]
### Bug description:
Include something like Undismissable modal - https://biig-io.github.io/ngx-smart-modal/ in this package. This is a very common use.

**Comment by maxokorokov** [comment]
We probably should align modal with other widgets that use `[autoClose]` input:

Ex. dropdown, datepicker, tooltip and popver use
```ts
@Input() autoClose: boolean | "inside" | "outside";
```

**Comment by kukac7** [comment]
@xyrintech do you mean `backdrop: 'static'`?

**Comment by pkozlowski-opensource** [comment]
@maxokorokov as @kukac7 pointed out I also do think that this is just a case for ` backdrop: 'static'`

**Comment by maxokorokov** [comment]
@kukac7 @pkozlowski-opensource, indeed!

As a side note, it comes straight from the bootstrap API apparently → https://getbootstrap.com/docs/4.2/components/modal/#options

And it actually doesn't make much sense to have `[autoClose]` on the modal, so I'm going to close this one.
