### ISSUE TITLE
[Feature Request]  Add an option to set the value of page numbers start.

### ISSUE THREAD

**Issue by ydcode** [ng-bootstrap/ng-bootstrap#3003]
### Feature description:
As we know, 
Spring Boot JPA Page numbers start with 0. 
ng-bootstrap Pagination Page numbers start with 1. 

Could we add an option to set the value  0 or 1 ?

**Comment by maxokorokov** [comment]
Not sure if it will be a sufficient solution for you, but you'll be able to override **displayed** numbers once #2971 lands. `[(page)]` will still be bound to `[1...n]`, but you'll display `[0..n-1]`

**Comment by ydcode** [comment]
OK, thank you ~
