### ISSUE TITLE
ngbModal OnOpen event

### ISSUE THREAD

**Issue by sauravraj95** [ng-bootstrap/ng-bootstrap#3005]
would be great to have a event for modal opening.

**Comment by pkozlowski-opensource** [comment]
Modal opening is a synchronous action so it is "open" as soon as you call the `open` method on the modal service. Not sure what other type of event would you expect? When it should be fired? What would be the use of it?

**Comment by maxokorokov** [comment]
Also see https://github.com/ng-bootstrap/ng-bootstrap/issues/3039#issuecomment-467018018
