### ISSUE TITLE
How to change default active id when tabs title come from api ??

### ISSUE THREAD

**Issue by SimranChawla1995** [ng-bootstrap/ng-bootstrap#3009]
<ngb-tabset activeId="2" (tabChange)="onTabChange($event)" [justify]="currentJustify">
    <ngb-tab [title] ="tab.catName" *ngFor="let tab of tabs; let i=index;" [id]= "i">
    </ngb-tab>
  </ngb-tabset>

**Comment by maxokorokov** [comment]
- if you believe that we've got a bug in this library than please provide a minimal reproduce scenario in a stackblitz: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug
- if you are unsure if this is a bug or not than please use an appropriate support channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
