### ISSUE TITLE
Dynamic Tooltip

### ISSUE THREAD

**Issue by xyrintech** [ng-bootstrap/ng-bootstrap#3010]
Suggestion: There should be way to add tooltip on elementRef in component. I mean rather than specifying 
placement="top" ngbTooltip="Tooltip on top
there should be a way to add these 2 properties in component file or directive etc.

**Comment by maxokorokov** [comment]
@xyrintech please elaborate and provide an example / stackblitz. 
It is not clear what you're trying to do

**Comment by benouat** [comment]
Closing as old an inactive.
