### ISSUE TITLE
NgbModalOptions size option should not be typed to 'sm' or 'lg'

### ISSUE THREAD

**Issue by ashgibson** [ng-bootstrap/ng-bootstrap#3013]
### Bug description:

Currently the size property on the NgbModalOptions interface is strongly typed to accept only 'sm' or 'lg'.

I understand that these 2 options are the defaults in bootstrap but using bootstrap sass mixins like the following, custom sizes can be created.

```
@include media-breakpoint-up(xl) {
  .modal-xl { max-width: $modal-xl; }
} // actually exists in bootstrap 4.2

@include media-breakpoint-up(xxl) {
  .modal-xxl { max-width: $modal-xxl; }
}
```

I don't see the benefit to strongly typing this particular option and think it should just be typed as string.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.x

ng-bootstrap: 4.0.2

Bootstrap: 4.x

**Comment by maxokorokov** [comment]
FYI there is a #2943 opened for adding `xl`
Also see #1309 and #1448.

However, we probably should better type it as `size?: 'sm' | 'lg' | 'xl' | string`

**Comment by ashgibson** [comment]
I don't see the point in adding the size variants plus string as string effectively creates a wildcard and removes any benefits of strictly typing this option.

Definitely need string added though as this package is falling behind the official bootstrap package.

**Comment by maxokorokov** [comment]
> I don't see the point in adding the size variants plus string

Two examples:

1. code completion

![screen shot 2019-02-13 at 09 59 38](https://user-images.githubusercontent.com/8074436/52699546-46ae8680-2f76-11e9-8188-3f3a50268be2.png)

2. API documentation

![screen shot 2019-02-13 at 10 00 25](https://user-images.githubusercontent.com/8074436/52699589-5fb73780-2f76-11e9-95fb-c870db093beb.png)

**Comment by pkozlowski-opensource** [comment]
Agree with @maxokorokov - definitively there is an added value of keeping `"sm" | "lg"` - it is true that it doesn't matter from the type point of view, but helps from the user / documentation point of view.

**Comment by Senneseph** [comment]
If I were doing it, I'd just pass in the plain string of the CSS class to be used in the attribute for the HTML element underlying the modal.

`size?: string`
`this.modalService.open(content, { })`
`<div class="modal"></div>`

`this.modalService.open(content, {size: 'modal-xl'})`
`<div class="modal modal-xl"></div>`

**Comment by altso** [comment]
Stumbled upon this issue today and do not see any solutions posted here. I ended up with this one:
```ts
const modalRef = this.modalService.open(MyComponent, {
  size: 'xl' as any
});
```

**Comment by reduckted** [comment]
> However, we probably should better type it as `size?: 'sm' | 'lg' | 'xl' | string`

I just tried appending `| string` to the type and, unfortunately, it doesn't give the desired behavior for documentation.

With `size?: 'sm' | 'lg' | 'xl'`:
![image](https://user-images.githubusercontent.com/10321525/67377286-c7735700-f5c8-11e9-974a-61ad30e26e2f.png)

With `size?: 'sm' | 'lg' | 'xl' | string`:
![image](https://user-images.githubusercontent.com/10321525/67377725-731ca700-f5c9-11e9-8309-fb98026d1306.png)

**Comment by samuelt1** [comment]
It depends on your setup, but on mine it does help. Why has this not been done yet?
