### ISSUE TITLE
feat(modal): Add scrollable option

### ISSUE THREAD

**Issue by bastienmoulia** [ng-bootstrap/ng-bootstrap#3020]
Since Bootstrap 4.3 there is a new class to make the modal content scrollable.
https://getbootstrap.com/docs/4.3/components/modal/#scrolling-long-content

We can add `scrollable?: boolean` in NgbModalOptions to add the class `.modal-dialog-scrollable` to `.modal-dialog`.

**Comment by maxokorokov** [comment]
Hey, @bastienmoulia there is a PR for this, if I'm not mistaken: #2909

**Comment by bastienmoulia** [comment]
I miss that one...
