### ISSUE TITLE
Dropdown keyboard e2e tests

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#3021]
There are unit tests for the keyboard navigation in the dropdown in #2683
However as it would be preferable to have e2e tests as this deals with focus and keyboard.

**Comment by jaganlal** [comment]
This might help with the bug [3066](https://github.com/ng-bootstrap/ng-bootstrap/issues/3066) that i reported today.

**Comment by maxokorokov** [comment]
Fixed in #3086
