### ISSUE TITLE
calendar button not show

### ISSUE THREAD

**Issue by R-Savaj** [ng-bootstrap/ng-bootstrap#3023]
@calendar button not show when I use Datepicker in a popup

**Comment by maxokorokov** [comment]
- if you believe that we've got a bug in this library than please provide a minimal reproduce scenario in a stackblitz: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug
- if you are unsure if this is a bug or not than please use an appropriate support channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help

**Comment by benouat** [comment]
Closing as issue seems inactive and quite old.

**Comment by Balagii** [comment]
sounds like a duplicate of #1862
