### ISSUE TITLE
Server side rendering fails because of "navigator.userAgent" use in autoclose

### ISSUE THREAD

**Issue by orestisioakeimidis** [ng-bootstrap/ng-bootstrap#3025]
### Bug description:

The server side rendering fails with `ReferenceError: navigator is not defined`. It is caused by the following:

https://github.com/ng-bootstrap/ng-bootstrap/blob/3170f907c5fc2eac636d42eab4b8f76ba5372409/src/util/autoclose.ts#L11

### Link to minimally-working StackBlitz that reproduces the issue:

Not applicable because of server side rendering.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.2.4

ng-bootstrap: 4.0.3

Bootstrap: 4.3.1

**Comment by maxokorokov** [comment]
@orestisioakeimidis thanks for reporting, should be fixed in `4.0.4` next week. We'll set up SSR tests for CI to avoid this in future.
