### ISSUE TITLE
Unclear installation instructions

### ISSUE THREAD

**Issue by jcpc91** [ng-bootstrap/ng-bootstrap#3029]
### Bug description:
on documentation need specify if is necessary add bootstrap css to index.html because if you just follow the instrucción no work 

### Link to minimally-working StackBlitz that reproduces the issue:

on index.html add 
href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular Cli: 7.3

ng-bootstrap: 4.0.3

Bootstrap: 4.3.1

**Comment by bastienmoulia** [comment]
Hello @jcpc91 ,

There is already the line `This repository contains a set of native Angular directives based on Bootstrap's markup and CSS.` in the [Getting Started](https://ng-bootstrap.github.io/#/getting-started) page which implies that Bootstrap must be installed.

**Comment by maxokorokov** [comment]
Hi @jcpc91,

the only two dependencies are Angular and Bootstrap CSS, so yes, you need to include it manually.

Anyway, we were planning to update/clarify installation instructions, so I'll keep the issue opened until its done. Thanks.

**Comment by maxokorokov** [comment]
Should be clarified in #3045
