### ISSUE TITLE
ngbDropdownMenu wrong position on small device in navbar

### ISSUE THREAD

**Issue by mebibou** [ng-bootstrap/ng-bootstrap#3030]
### Bug description:

When using a `ngbDropdownMenu` inside a `navbar`, opening the menu on a large device will make it render as `position: absolute` and will display below the opening button. But when reducing the screen and the dropdown should appear in the hamburger menu, when opening it is still displayed using `position: absolute` which makes the menu look weird (not taking the full width).
Note: this issue does NOT happen on `4.0.2` but does on `4.0.3`. On `4.0.2` the `position` is not overridden by the library and it works. `4.0.3` is somehow adding `position: absolute` which is completely unnecessary and breaks the layout

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-gwm69f

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.0.0

ng-bootstrap: 4.0.3

Bootstrap: 4.2.0

**Comment by maxkorz** [comment]
I think `ng-bootstrap` should behave like the original Bootstrap.

In [Bootstrap Dropdown](https://getbootstrap.com/docs/4.3/components/dropdowns/#single-button) JS adds `position` and `transform` properties to `.dropdown-menu`. But when [Dropdown is in a Navbar](https://getbootstrap.com/docs/4.3/components/navbar/#supported-content), it does not add anything.

![image](https://user-images.githubusercontent.com/25089646/53085841-d58e4680-3514-11e9-8dea-f62dde36c0a3.png)

![image](https://user-images.githubusercontent.com/25089646/53085896-f8b8f600-3514-11e9-9958-ba8c6c9db8d8.png)

**Comment by ahmadmu** [comment]
I'm not sure it's related, but I'm currently having an issue where in dev mode the ngbDropdownMenu is positioned using `top: 38px`, and in prod mode it's positioned using `transform: translate(0, 38px)`, which is breaking my animations in production. Does someone know what might be the cause?
