### ISSUE TITLE
add focused text to input in typeahead

### ISSUE THREAD

**Issue by IAfanasovMob** [ng-bootstrap/ng-bootstrap#3037]
### Requested feature description:
Copy focused suggestion to the search field
When a suggestion receives focus while navigating with a keyboard or hovering with a mouse, its text should be copied to the input field. If the user begins typing, these characters should naturally be appended to the new search text. This way the user can further detail their input before submitting it.

### demo
Current:
![current](https://user-images.githubusercontent.com/44999963/53162682-d4205500-35cc-11e9-85cb-653c98c9bc1d.gif)

Wanted:
![wanted](https://user-images.githubusercontent.com/44999963/53162773-0c279800-35cd-11e9-83ab-1af7f739d99c.gif)

**Comment by pkozlowski-opensource** [comment]
This is already supported with the `showHint` property.

* docs: https://ng-bootstrap.github.io/#/components/typeahead/api
*example: https://stackblitz.com/edit/angular-xwyefv?file=app/typeahead-basic.html

**Comment by IAfanasovMob** [comment]
thanks so much @pkozlowski-opensource !
