### ISSUE TITLE
Preserve filenames on custom file fields

### ISSUE THREAD

**Issue by ggjersund** [ng-bootstrap/ng-bootstrap#3038]
### Bug description:
Filenames are currently not preserved when using [custom file input](https://getbootstrap.com/docs/4.3/components/input-group/#custom-file-input).

### Link to minimally-working StackBlitz that reproduces the issue:

[Stackblitz](https://stackblitz.com/edit/angular-6qxk5y)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.0.0

ng-bootstrap: 4.0.4

Bootstrap: 4.0.0

**Comment by maxokorokov** [comment]
@ggjersund, if you look at the documentation on the bootstrap site for custom file input:
https://getbootstrap.com/docs/4.3/components/input-group/#custom-file-input

You'll see that they use a custom plugin for this: https://github.com/Johann-S/bs-custom-file-input and it is not a part of the library.

I don't think we'll implement it either as a part of ng-bootstrap at the moment.

The workaround for you is quite simple:

```html
<div class="custom-file">
  <input type="file" class="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01" (change)="label.innerText = $event.target.files[0].name">
  <label class="custom-file-label" for="inputGroupFile01" #label>Choose file</label>
</div>
```

Here is a StackBlitz: https://stackblitz.com/edit/angular-6qxk5y-59ppn7?file=app/app.component.html as a starting point

**Comment by ggjersund** [comment]
Oh, I wasn't aware of this given the css worked out just fine. Thanks for making me aware of it. Great work on this library by the way 👍
