### ISSUE TITLE
Popover arrow placement can be incorrect when multiple placements are used

### ISSUE THREAD

**Issue by reduckted** [ng-bootstrap/ng-bootstrap#3040]
### Bug description:

When using multiple `Placement` values to position a popover, if none of them result in the popover being on screen, the first `Placement` is used to position the popover, but the _last_ `Placement` is used to control where the popovers arrow appears.

![image](https://user-images.githubusercontent.com/10321525/53392800-3a9ade00-39e6-11e9-99f1-422c4db03854.png)

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-ducwpd

Click on the button to open the popover. The popover will appear centered over the button, but the arrow will be to the right edge of the popover. 

If you change the `placement` order in `app.component.html` to `['top', 'top-right', 'top-left']`, the arrow will appear towards the left edge of the popover. If you change the placements to just contain `top`, the arrow is centered as you would expect.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.2.6

ng-bootstrap: 4.0.4

Bootstrap: 4.3.1

**Comment by reduckted** [comment]
I _think_ this was introduced in either #3017 or #2972 when some of the positioning logic was changed. When it's trying the different placements, if the placement doesn't result in the element being on screen, it removes the CSS classes it added _except if it's the last placement it's trying_. If the final placement didn't put the element on screen, then it applies the first placement, but it still has the last placement's CSS classes applied.

https://github.com/ng-bootstrap/ng-bootstrap/blob/0874fb1a64244778d1e6fe2de0e41d0ee1133161/src/util/positioning.ts#L237-L241

**Comment by fbasso** [comment]
Thanks for your issue and investigation @reduckted !

Your're right, this last test `testPlacement !== lastPlacement` should't be here. It has been there after some different tries/refactor on positioning.

I'll prepare a PR soon.

**Comment by reduckted** [comment]
Awesome! Thanks for the quick fix.
