### ISSUE TITLE
Date Picker: NgbCalendarGregorian is not in public api.

### ISSUE THREAD

**Issue by itayod** [ng-bootstrap/ng-bootstrap#3054]
### Bug description:

Hi, I am trying to use the `NgbCalendarGregorian`, but it seems to not be in your public api.
I need to use this class for a factory method that need to return `MyCustomCalendar` or `NgbCalendarGregorian` (as the default calendar).

I will be glad if it will be part of the public api or maybe show me some work around that I have maybe  missed.

p.s. I will be happy to create a pr for it 😄 

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.2.5

ng-bootstrap: 4.0.2

**Comment by maxokorokov** [comment]
`NgbCalendarGregorian` is the one used by default, so you shouldn't do anything special to use it. But  this is definitely an omission, we should add it to public exports in `src/index.ts` and `src/datepicker/datepicker.module.ts`

**Comment by itayod** [comment]
Thank you @maxokorokov ,

Actually I am using it inside a factory method that should return `CustomCalendar` or the default calendar,
and also my `CustomCalendar` extends `NgbCalendarGregorian`.

Anyway thanks for the quick fix 🎉🎉
