### ISSUE TITLE
The complete example of the table is not complete.

### ISSUE THREAD

**Issue by luisalcarasr** [ng-bootstrap/ng-bootstrap#3057]
### Bug description:

The complete example of the table is not complete.

```
Import error, can't find files:
./country.service
./sortable.directive
```

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/angular/dggyydjvdaa

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.0.0

ng-bootstrap: 4.1.0

Bootstrap: 4.3.1

**Comment by benouat** [comment]
Thank you to report that bug.
We are aware of it. Our internal stackblitz generator is not compliant with these samples.

We need to refactor it entirely to support this kind of demo containing extra files.

**Comment by luisalcarasr** [comment]
You're welcome, **thank you for the components**.

Where can I find the code of the service for this example? I need "inspiration" 😅

**Comment by benouat** [comment]
All `table` demos are located in here 👉  https://github.com/ng-bootstrap/ng-bootstrap/tree/master/demo/src/app/components/table/demos

**Comment by luisalcarasr** [comment]
Thanks @benouat! 👍🏾
