### ISSUE TITLE
 how to close other opened dropdowns in ngbootstrap

### ISSUE THREAD

**Issue by jagdishjadeja** [ng-bootstrap/ng-bootstrap#3060]
is there any solution to this problem ?

https://stackoverflow.com/questions/55126025/how-to-close-other-opened-dropdowns-in-ngbootstrap

**Comment by benouat** [comment]
Thank you @jagdishjadeja for reporting a potential bug.

Nonetheless, according to our documentation [You think you've found a bug](
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug) could you please reproduce your scenario in a minimalist Stackblitz in order for us to start working on it ?

**Comment by benouat** [comment]
Closing as no update regarding a reproducible scenario via Stackblitz
