### ISSUE TITLE
Z-index issue on ngb-dropdown with container="body"

### ISSUE THREAD

**Issue by shyamal890** [ng-bootstrap/ng-bootstrap#3061]
### Bug description:
- Z-index is wrong when ngb-dropdown is loaded in a modal and `container="body"`

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/ngb-dropdown-index

### Versions of Angular, ng-bootstrap and Bootstrap:
Angular: 7.0.0
ng-bootstrap: 4.1.0

**Comment by benouat** [comment]
Hello @shyamal890
Thank you to report this bug! You are right we might have introduce some discrepancies regarding the `z-index`

Nonetheless, when we consider your reproducible scenario in Stackblitz (I don't your original usage, it might be different) I don't really see the added value of defining `ngbDropdown` with `container="body" `... The modal itself is already a kind of container which is itself appended to the body. So it seems not needed at all to also enforce it on the dropdown.

**Comment by shyamal890** [comment]
@benouat Needed if you have a scrollable div in the modal!

**Comment by shyamal890** [comment]
@benouat Can you please mark this as bug and have someone look at it please.

**Comment by xyrintech** [comment]
Any update for this?

**Comment by shyamal890** [comment]
@benouat would really appreciate an update on this. We have been waiting for `container='body'` feature for so long. Was really excited to update our code when the feature was released. But this issue is really a show stopper.

**Comment by maxokorokov** [comment]
Related to #2686, #3133 and #2947.

Should set `z-index` for the dropdown when attached to body, probably same level as for the tooltip

cc @fbasso

**Comment by khasogi27** [comment]
.dropdown-menu {
  position: fixed !important;
  inset: unset !important;
  transform: unset !important;
}
