### ISSUE TITLE
Please take rounded/floor values of popovers translated positions to prevent fuzzy borders. (fractional pixels artifacts)

### ISSUE THREAD

**Issue by boltex** [ng-bootstrap/ng-bootstrap#3071]
### Bug description:
Popovers get their positions with a "translate". Their calculations often result on non-rounded (fractional) values such as "transform: translate(810.75px, 130.25px);" This makes anything that has high-contrast one-pixel wide borders (or other sharp and thin graphic elements) appear fuzzy and buggy. (some times the resulting position is very close to an integer value and it makes the result appear sharp and clear but its not consistent and depends on positions and widths of elements.) This should be vey easy to fix.

**Comment by benouat** [comment]
Thank you for reporting this issue!

> This should be very easy to fix.

Unfortunately, it's apparently not that simple. I'll let @fbasso deal with that as he led the corresponding refactor.

**Comment by boltex** [comment]
I want to thank you for considering my bug report even though I did not fill out all your requirements (making a plunker and giving you all the versions of my OS, angular, etc...) 
I was in a rush and I figured that I would still do it in a short, consice, detailed and clear fashion.
So thanks again for that. :)
