### ISSUE TITLE
Uncaught Error: Unexpected directive 'NgbTypeahead' imported by the module 'AppModule'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by slishnevsky** [ng-bootstrap/ng-bootstrap#3075]
### Bug description:
Followed the instructions on https://ng-bootstrap.github.io/#/getting-started
Installed ng-bootstrap:
`npm install --save @ng-bootstrap/ng-bootstrap`
Imported:
`import { NgbTypeahead } from '@ng-bootstrap/ng-bootstrap';`
Declared:
`@NgModule({
  declarations: [AppComponent],
  imports: [NgbTypeahead],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }`

When running the app I get an error:
**Uncaught Error: Unexpected directive 'NgbTypeahead' imported by the module 'AppModule'. Please add a @NgModule annotation.**

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular CLI: 7.3.5
Angular: 7.2.9
ng-bootstrap:4.1.0
Bootstrap:4.3.1

@NgModule annotation is there, not sure what is wrong! Thank you.

**Comment by pkozlowski-opensource** [comment]
> `imports: [NgbTypeahead]`

^ this is your problem. You are not supposed to import _directives_ but rather modules so you should have something like `imports: [NgbModule]`: https://ng-bootstrap.github.io/#/getting-started

**Comment by slishnevsky** [comment]
Not true, same documentation says, on the same page:

> Alternatively you could only import modules with components you need, ex. pagination and alert. The resulting bundle will be smaller in this case.

https://ng-bootstrap.github.io/#/getting-started

and provides sample code:

```
import {NgbPaginationModule, NgbAlertModule} from '@ng-bootstrap/ng-bootstrap';
@NgModule({
  ...
  imports: [NgbPaginationModule, NgbAlertModule, ...],
  ...
})
export class YourAppModule {
}
```

**Comment by pkozlowski-opensource** [comment]
> Please re-open, same documentation says

It never says `imports: [NgbTypeahead]` (!) - I guess you've meant `imports: [NgbTypeaheadModule]`

**Comment by slishnevsky** [comment]
Ok, its confusing since in other samples I saw imports: [NgbTypeahead].
Never mind. AS you said, I change my code to:
(removed all other components for simplicity)
what am i doing wrong? just followed the manual.

app.module.ts
------------------------
```
import { NgbTypeaheadModule } from '@ng-bootstrap/ng-bootstrap';
@NgModule({
  declarations: [ ],
  imports: [NgbTypeaheadModule],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```
navbar.component.html
------------------------------------
`<input id="typeahead-basic" type="text" class="form-control" [(ngModel)]="items" [ngbTypeahead]="search"/>`

But I still get error:

ERROR TypeError: Object(...)(...) is not a function
    at Observable.push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.pipe (Observable.js:91)
    at NgbTypeahead.push../node_modules/@ng-bootstrap/ng-bootstrap/fesm5/ng-bootstrap.js.NgbTypeahead.ngOnInit (ng-bootstrap.js:10998)
    at checkAndUpdateDirectiveInline (core.js:18537)
    at checkAndUpdateNodeInline (core.js:19801)
    at checkAndUpdateNode (core.js:19763)
    at debugCheckAndUpdateNode (core.js:20397)
    at debugCheckDirectivesFn (core.js:20357)
    at Object.eval [as updateDirectives] (NavbarComponent.html:17)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:20349)
    at checkAndUpdateView (core.js:19745)

**Comment by akhtar030** [comment]
Unexpected directive 'NgbTypeahead' imported by the module 'AppModule'. Please add a @NgModule annotation.

Can anyone have a proper and exact solution for this?
