### ISSUE TITLE
Scrollbar is not complied with Angular Universal

### ISSUE THREAD

**Issue by Omi0** [ng-bootstrap/ng-bootstrap#3077]
If you enable server side rendering. We need to check (isPlatformBrowser(this.platformId) prior trying accessing document.

https://github.com/ng-bootstrap/ng-bootstrap/blob/c9f847bc89ecb986963ea9442257aa13520690ef/src/util/scrollbar.ts#L52

Otherwise you will see following error:
`TypeError: this._document.body.getBoundingClientRect is not a function`

**Comment by maxokorokov** [comment]
@Omi0 could you please describe the use case in a bit more details? Are you trying to pre-preneder an opened modal?

**Comment by benouat** [comment]
Closing for now as issue seems inactive.

**Comment by kamilchlebek** [comment]
@maxokorokov I have the same issue. In may case I try to pre-render opened modal. That modal is shown when some crucial (required to bootstrap) backend request failed.

I'll try to redirect user to error page, but would be great to keep that modal.

**Comment by Omi0** [comment]
@kamilchlebek of course, this is predicted behaviour. 

> window, document, navigator, and other browser types - do not exist on the server

https://github.com/angular/universal/blob/master/docs/gotchas.md

Even though this thread is closed the issue is still active - unless document is gonna be wrapped in conditional statement.
