### ISSUE TITLE
DatePicker in popup - ios/safari - month navigation closes popup

### ISSUE THREAD

**Issue by fatboystring** [ng-bootstrap/ng-bootstrap#3079]
### Bug description:

When the date picker is displayed in a popup, attempting to navigate between months using the prev/next arrow links in the datepicker causes the popup to close therefore making it impossible to select anything outside of the current month.  

Tested with IPad/Safari 12.1.4 using the [official examples](https://ng-bootstrap.github.io/#/components/datepicker/examples#popup)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.2.4
ng-bootstrap: 4.0.2
Bootstrap: 4.1.1

**Comment by jlSites** [comment]
Got same issue on iPhone8(chrome+safari) on Angular7+ng-bootstrap 4.1.0+bootstrap 4.3.

But not an issue on Samsung phone's chrome(with Android system).

**Comment by anji0302** [comment]
Still having the same issue 
Any update?
