### ISSUE TITLE
Tooltip should always be inside window

### ISSUE THREAD

**Issue by MickL** [ng-bootstrap/ng-bootstrap#3080]
placement `auto` is great, but the default seems to be `top`. What if I want `auto` but default  `bottom`?

I think the auto-placement should also happen when definining a placement as soon as the tooltip is cut off by the window. In other words: The tooltip should always be visible and never go outside of the window.

**Comment by pkozlowski-opensource** [comment]
Wouldn't `['bottom', 'auto']` work ?

**Comment by fbasso** [comment]
Since the 4.1.0, placement="bottom auto" is another possibility.

**Comment by MickL** [comment]
Thats so great! Documentation needs to be updated.

**Comment by benouat** [comment]
@fbasso could you check please @MickL last statement ?

> Something else: Using `bottom auto` placement is of tooltip totally broken.

**Comment by fbasso** [comment]
I tried bottom auto in a local environment and everything if fine.

@MickL, could you check you well used the 4.1.0 of ng-bootstrap ? Otherwise, I need more information (stackblitz is better of course) to understand in which case it's broken.

**Comment by MickL** [comment]
Sorry but unfortunately i don't have the time to do that right now. Im using a flex layout and the placement never works when the container is not set to `body`. Also, placement `bottom auto` does is totally wrong all the time no matter what container is used.

**Comment by benouat** [comment]
Closing for now as issue seems inactive

**Comment by MickL** [comment]
@benouat Inactive does not mean the issue is fixed. Please reopen.

**Comment by benouat** [comment]
Sorry, but for us right now, the placement feature does not seems to be broken... I was just doing some backlog grooming on issue untouched for more a than a month.

We kindly asked you to open a SB to understand as none of us managed to reproduce, to which request you replied

> Sorry but unfortunately i don't have the time to do that right now.

Hence the closing. Feel free to reopen this issue when you will have more time to focus on it.

PS: don't take it personnaly, this is our policy "_more than a month without info when we ask for it_" &rarr; we close.
