### ISSUE TITLE
Translation of tooltips

### ISSUE THREAD

**Issue by temagr** [ng-bootstrap/ng-bootstrap#3081]
Hello.

Tell me please, is it planned to translate tooltips (Select month, Select year, Previous month, Next month) at the ngb-datepicker component, just as it did for its other entities using `{provide: NgbDatepickerI18n, useClass: CustomNgbDatepickerI18n}`?

I think that for those who do not use the standard translation method this is an important opportunity.

**Comment by maxokorokov** [comment]
Duplicate of #2977, please vote for issues
