### ISSUE TITLE
Dropdowns in 4.1.0 use inline styles?

### ISSUE THREAD

**Issue by smlombardi** [ng-bootstrap/ng-bootstrap#3082]
### Bug description:
After updating to ng-boostrap 4.1.0, we noticed that inline styles are being inserted into the dropdown menu.  You are using a `transform: translate`

This breaks the keyframe animation we were using on out regular Bootstrap menus.

menu closed:
```
<div aria-labelledby="navbarDropdownMenuLink" class="dropdown-menu" ngbdropdownmenu="" x-placement="bottom-left" style="top: 0px; left: 0px;">
<a class="dropdown-item" routerlink="" ng-reflect-router-link="" href="/">Menu Item 1</a> 
<a class="dropdown-item" routerlink="" ng-reflect-router-link="" href="/">Menu Item 2</a> 
</div>
```
and opened
```
<div aria-labelledby="navbarDropdownMenuLink" class="dropdown-menu fade show" ngbdropdownmenu="" x-placement="bottom-left" style="top: 0px; left: 0px; position: absolute; transform: translate(3.90625px, 69px);">
<a class="dropdown-item" routerlink="" ng-reflect-router-link="" href="/">Menu Item 1</a> 
<a class="dropdown-item" routerlink="" ng-reflect-router-link="" href="/">Menu Item 2</a> 
</div>
```

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.2.4

ng-bootstrap: 4.1.0

Bootstrap: 4.3.1

**Comment by benouat** [comment]
Hey @smlombardi !

You're right that in `4.1.0` we changed the way all the _popover_ are displayed.
We moved to use css `transform: translate()`.

We did that mostly for 2 reasons:
+ it helped us solved many issues we had with the previous system we had
+ we are now much more aligned with what Bootstrap themselves are doing via [Popper.js](http://popper.js.org/)

Thus I am bit afraid, that maybe, your keyframes based animation **would probably not** work either with raw Bootstrap...

**Comment by smlombardi** [comment]
True, I noticed that as well.  Back to the drawing board...
