### ISSUE TITLE
Size configuration 'md' for ng-bootstrap/modal

### ISSUE THREAD

**Issue by brunoleone** [ng-bootstrap/ng-bootstrap#3088]
### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: ^6.0.8

ng-bootstrap: 4.x.x

Bootstrap: 4.0.0-beta

**Comment by maxokorokov** [comment]
@brunoleone there is no `md` modal size in the bootstrap → https://getbootstrap.com/docs/4.3/components/modal/#optional-sizes, so we won't add it unless Bootstrap supports it

**Comment by brunoleone** [comment]
@maxokorokov true, I did not know. Thank you.
