### ISSUE TITLE
mximizing the panel/card/model on click of icon, is this possible?

### ISSUE THREAD

**Issue by rammohangowd** [ng-bootstrap/ng-bootstrap#3090]
I have panels/cards and models in my application, but displaying on fixed width and height. I wanted to maximize the panel/card or models on click of icon placed on right top corner of the panel. is it possible, please suggest me if any examples available.

**Comment by maxokorokov** [comment]
We don't provide the card component for many reasons as a part of ng-bootstrap. (ex. see #50). So for the cards, it's up to you to wrap them into your own component if necessary. We wouldn't help you with this.

- if you believe that we've got a bug in this library than please provide a minimal reproduce scenario in a stackblitz: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug
- if you are unsure if this is a bug or not than please use an appropriate support channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help

If you're talking about the accordion we have, you could take a look at [accordion header demo](https://ng-bootstrap.github.io/#/components/accordion/examples#header) and accordion implementation (based on cards). Might help you.
