### ISSUE TITLE
Bug: Iphone Datepicker in a popup select year/month

### ISSUE THREAD

**Issue by ronjb04** [ng-bootstrap/ng-bootstrap#3091]
Simply open https://stackblitz.com/angular/degedjrgvok in any iphone device and try selecting the year or month select option.. it doesn't open the default select in iphone. In android the select works fine.

**Comment by maxokorokov** [comment]
@ronjb04 thanks for reporting it, duplicate of #3079, should be fixed in `4.1.1` hopefully this week.
