### ISSUE TITLE
Feature request: custom datepicker's popup target for positioning

### ISSUE THREAD

**Issue by dzonatan** [ng-bootstrap/ng-bootstrap#3092]
### Feature request for datepicker

1. Make the target element that is used to determine the datepicker's popup position customisable (e.g. `positionTarget` input property), now [it's a hard-coded input](https://github.com/ng-bootstrap/ng-bootstrap/blob/5444d133d100c36a6f238c1e1f77972c427f3fcf/src/datepicker/datepicker-input.ts#L214);
2. Apply & update the corresponding css class (`.ngb-dp-bottom`, `.ngb-dp-top`, `.ngb-dp-left`, `.ngb-dp-right`) based on the actual datepicker's popup position.

### Motivation

This will let to achieve similar things to this (pay attention to the popup arrow and position):

![image](https://user-images.githubusercontent.com/5166666/55154067-99c24e80-515c-11e9-906e-ca5c948c34fe.png)

Maybe this is not very necessary for the original bootstrap but It can be useful for the themed versions (latter my case).

If agreed - I can make a PR for this.

**Comment by dzonatan** [comment]
@maxokorokov do these labels mean I can start working on it?

**Comment by maxokorokov** [comment]
Hey, @dzonatan !

There are two separate features here:

### 1. Positioning

> Make the target element that is used to determine the datepicker's popup position customisable (e.g. positionTarget input property)

Another option would be to have something like we do for the dropdown: `NgbDropdownAnchor` → `NgbDatepickerAnchor`.

On the other hand we have the `container` input that takes selector, so it might be more consistent to use something like the `positionTarget`.

- some ideas, let's think of Pros and Cons:

```html
<!-- 1. ngbDatepickerAnchor directive -->
<input type="text" ngbDatepicker #d="ngbDatepicker" />
<button [ngbDatepickerAnchor]="d" (click)="d.toggle()"></button>

<!-- 2. [positionTarget] with element -->
<input type="text" ngbDatepicker #d="ngbDatepicker" [positionTarget]="b" />
<button #b (click)="d.toggle()"></button>

<!-- 3. [positionTarget] with selector -->
<input type="text" ngbDatepicker #d="ngbDatepicker" positionTarget="#myButton" />
<button id="myButton" (click)="d.toggle()"></button>
```

I think I prefer the 2+3 with `@Input() positionTarget: string | ElementRef`

- also this API **might** apply to `Dropdown` and `Typeahead`, but not 100% sure

### 2. Arrow for the popup

> Apply & update the corresponding css class (.ngb-dp-bottom, .ngb-dp-top, .ngb-dp-left, .ngb-dp-right) based on the actual datepicker's popup position.

I'm not a fan of this arrow idea personally, to me datepicker is more like dropdown or typeahead. On the other hand I've seen datepickers with arrows out there :)

We might add classes like `.ngb-popup-top .ngb-popup-top-left`, etc. and align behaviour with bootstrap's tooltip/popover.

```html
<!-- datepicker popup today -->
<ngb-datepicker class="dropdown-menu show" style="..."></ngb-datepicker>

<!-- 1. just adding css classes -->
<ngb-datepicker class="dropdown-menu show ngb-popup-top ngb-popup-top-left" style="..."></ngb-datepicker>

<!-- 2. mimicking tooltip -->
<ngb-datepicker-window class="dropdown-menu show ngb-popup-top ngb-popup-top-left" style="...">
  <div class="arrow"></div>
  <ngb-datepicker></ngb-datepicker>
</ngb-datepicker-window>
```

Not sure 1 will be enough for styling, WDYT ?
---

Let's address these two features separately, please. Maybe start with 1 ?

**Comment by dzonatan** [comment]
@maxokorokov 

### 1. Positioning 

Obviously 2+3 looks more flexible because of the css selector. Other than that it's only API sugar.
I would go with 2+3, but I don't see a problem for `anchor` either. Just let me know which you prefer.

### 2. Arrow for the popup
Option 1 (only css classes) is enough to have the arrow by using :after, :before pseudo elements.
So not sure if it's worth implementing second option.

> Let's address these two features separately, please. Maybe start with 1 ?

Sounds good.

**Comment by maxokorokov** [comment]
@dzonatan thanks for the input. I agree that 2+3 is more flexible, let's try to do it then.

**Comment by kernyden** [comment]
`positionTarget `doesnt relates to element's choosed as `input `when it meets `'position-relative'` as a wrapper
