### ISSUE TITLE
ngbTooltip should use the same border technique as popover

### ISSUE THREAD

**Issue by httpete** [ng-bootstrap/ng-bootstrap#3095]
### Bug description:
My requirement is to theme the tooltip to have a border just as the popover does (around the body and the arrow) but you are using a different css technique . It should share the same technique.

**Comment by benouat** [comment]
Hi @httpete

I just checked from our sources, but we don't do anything special regarding `border` neither for tooltip, nor for popover. I am afraid that in this case, we are raw Bootstrap...

**Comment by httpete** [comment]
Ugh. Ya I see this, it's bootstrap not you.  Ill ask them. Thank you.
