### ISSUE TITLE
Demo layout is broken on Firefox

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#3108]
### Bug description:

The layout of examples in the demos is broken on Firefox (66.0.2). See the attached screenshots.

<img width="858" alt="Capture d’écran 2019-04-05 à 10 11 17" src="https://user-images.githubusercontent.com/1608223/55613552-3bfcba80-578b-11e9-9f18-572dde3a5672.png">

<img width="815" alt="Capture d’écran 2019-04-05 à 10 12 44" src="https://user-images.githubusercontent.com/1608223/55613604-6cdcef80-578b-11e9-9d83-aac0961977f7.png">

**Comment by benouat** [comment]
Crap! thanks @jnizet 

I knew it wouldn't be that easy. I trusted browserlist/autoprefixer to have my back on that one. I should not have :(

**Comment by benouat** [comment]
It should be fixed! I'll see if I can deploy to gh-page in between releases.

**Comment by maxokorokov** [comment]
@benouat in other news, it is still broken in IE11 :)
