### ISSUE TITLE
Pagination - Message

### ISSUE THREAD

**Issue by baloniet** [ng-bootstrap/ng-bootstrap#3112]
It would be very nice to have an option to show some predefined text instead of 'empty' pagination. We can solve this with *ngIf and it is totally fine that way but it will reduce some code.
Example:
`<ngb-pagination [message]="'The list is empty'" ... ></ngb-pagination>`

Thank you

**Comment by maxokorokov** [comment]
@baloniet thank you for the suggestion, but to me it's outside the scope of the library. 

You're not trying to configure pagination, you just want to replace it completely with something else. I'd say it's for the application to do so. Also its shouldn't be a text, but at least a template. 

And you're right, you could do it like this an even wrap in your own `<my-pagination>` component if necessary:

```html
<ngb-pagination *ngIf="myCollectionSize > 0; else nopages" [collectionSize]="myCollectionSize"></ngb-pagination>
<ng-template #nopages>
  <div>No pages</div>
</ng-template>
```

Essentially you're asking to replace `ngIf` with an `@Input()`, so we'll pass on this feature.

Cheers.
