### ISSUE TITLE
Carousel dynamic interval

### ISSUE THREAD

**Issue by deepakkoirala** [ng-bootstrap/ng-bootstrap#3116]
This is not a bug but I wanted to have a dynamic Carousel so that I can keep dynamic timing interval that a slide can live for multiple slides ? 

I am referring with respect to this feature.
https://ng-bootstrap.github.io/#/components/carousel/examples

**Comment by maxokorokov** [comment]
@deepakkoirala oh, I see, got it. It might a bit difficult and an overkill to implement it as a part of the library, but it's easy to do it on your own.

Take a look at this StackBlitz: https://stackblitz.com/edit/angular-bfeemv?file=app/carousel-basic.ts
