### ISSUE TITLE
Tooltip position incorrect when browser zoom != 100% (only Chrome)

### ISSUE THREAD

**Issue by NotANumber-Human** [ng-bootstrap/ng-bootstrap#3122]
### Bug description:
Tooltips are not rendered in direct proximity to the element that creates the tooltip as soon as the mouse is moved over it (hover).
Prerequisite for this bug is the use of the Chrome Browser (Version 73.0.3683.103 (Official Build) (64-Bit)) with a zoom level != 100% or a 15.6 inch display.

### Link to minimally-working StackBlitz that reproduces the issue:
//coming soon

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: ^°7.0.2

ng-bootstrap: ^19.0.0

Bootstrap: ~4.1.0

**Comment by maxokorokov** [comment]
@NotANumber-Human looks fine to me

Please see https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug
