### ISSUE TITLE
is it supports tags input multiselect and custome tags?

### ISSUE THREAD

**Issue by rammohangowd** [ng-bootstrap/ng-bootstrap#3123]
I am looking for tags input feature like when we enter some characters it will hit a service and form the response I will be going to select multiple items(drop down result should not close after selecting one item) from the drop down and also it should accept custom input tag as well like If I type some word after 4 seconds it should be automatically debounce and convert as tag if no response from the service. Please suggest me such kind of example or feature if have any. Thanks!

**Comment by pkozlowski-opensource** [comment]
https://ng-bootstrap.github.io/#/components/typeahead/examples is the closest thing to what you are looking for - one can build a tagged input based on typeahead, see https://github.com/ng-bootstrap/ng-bootstrap/issues/532 for more details.
