### ISSUE TITLE
is it supports dynamic(on demand load) treetable 

### ISSUE THREAD

**Issue by rammohangowd** [ng-bootstrap/ng-bootstrap#3124]
I am looking for a feature on table component like Treetable. If we expand parent row then it will hit a service and get children data and that should be appended to the parent and display as Treetable along with sorting functionality like if we click on table coloumn header then the the enitre table should be sorted coording to that coloumn of treetable. Please suggest me if we have this feature or any exmaple that would be great help. Thanks!

**Comment by pkozlowski-opensource** [comment]
Please check https://ng-bootstrap.github.io/#/components/table/overview

**Comment by rammohangowd** [comment]
Thanks @pkozlowski-opensource , but I could see in that only sorting and pagination type. I am looking for dynamic loading as tree. I did not find any treetable examples in the above link. Apologies If I have missed to see any feature. If you have any specific example for this please provide the link here. Thanks IN Advance!!
