### ISSUE TITLE
DatePicker is displayed behind Modal if datepicker container is set to body

### ISSUE THREAD

**Issue by llRandom** [ng-bootstrap/ng-bootstrap#3133]
### Bug description:

`NgbDatePicker` is displayed behind `NgbModal` if datepicker `container` is set to `body`

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-d5kbff

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.3.8

ng-bootstrap: 4.1.1

Bootstrap: 4.3.1

**Comment by maxokorokov** [comment]
@llRandom, bootstrap's modal has a z-index of 1050 by default (could be changed with theming)

We don't set any z-index values currently on the datepicker, but we should.
I guess it should be either the same as modal (1050), or as a tooltip (1070)

Related to #2686 and #2947 

cc @fbasso
