### ISSUE TITLE
dropdown cut / hiding behind

### ISSUE THREAD

**Issue by xyrintech** [ng-bootstrap/ng-bootstrap#3135]
### Bug description:
ngbdropdown is having a major issue as the dropdown hides behind the parent elements. Please see below:
![Screenshot 2019-04-22 at 11 57 36 AM](https://user-images.githubusercontent.com/7784136/56486631-e0099400-64f5-11e9-82d9-9bf3544d3a75.png)

### Versions of Angular, ng-bootstrap and Bootstrap:
Angular: 7.x
ng-bootstrap: 4.0.0
Bootstrap: 4.0.0

**Comment by benouat** [comment]
Hello @xyrintech 

Your parent element probably has an overflow, thus it's normal that the dropdown gets confined inside.
If you could migrate to `4.1.0` then maybe you could use [container="body"](https://ng-bootstrap.github.io/#/components/dropdown/api#NgbDropdown) to prevent that.

**Comment by xyrintech** [comment]
container="body" on modal? or dropdown?
actually its not dropdown but even typing inside the inputs (formcontrols) becomes slow. 
When we both this code on page rather than modal then there is no issue. 
The issue has not been there version 1.x for ng-bootstrap. 
I tried 4.0.1 and 4.1.1, same concern in both of them.

**Comment by benouat** [comment]
Ok, then it's not clear to me what you want to achieve.
Could you please reproduce your scenario in a minimalist Stackblitz in order for us to understand it ?

According to our documentation [You think you've found a bug](
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug), providing a SB is kind of pre-requisite. With only partial screenshot, we are bit help-less...

**Comment by xyrintech** [comment]
Its a bug, I will try to replicate on Stackblitz.

**Comment by k2ibegin** [comment]
I am facing similar issue. I have several dropdowns and several date fields inside ngbaccordions. Problem is that they are hiding behind ngbacoordion panels as mentioned here in the image. What is the way out of it ? My parent card body has overflow: auto.

I tried putting container  = body, but nothing happend, please let me know if i am doing something wrong ? 

```
<div class="col-md-4">
                <div class="d-flex">
                  <label for="startdate">Start Date :
                  </label>
                </div>
                <div class="form-group">
                  <div class="input-group">
                    <input class="form-control" id="startdate" placeholder="yyyy-mm-dd" name="dp1" [(ngModel)]="model1"
                      ngbDatepicker [container]="body" #d1="ngbDatepicker">
                    <div class="input-group-append">
                      <button class="btn btn-secondary calendar" (click)="d1.toggle()" type="button">
                        <fa-icon [icon]="faCalendar"></fa-icon>
                      </button>
                    </div>
                  </div>
                </div>
              </div>

```
Thanks

**Comment by benouat** [comment]
again...

According to our documentation [You think you've found a bug](
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug) could you please reproduce your scenario in a minimalist Stackblitz in order for us to start working on it ?

**Comment by k2ibegin** [comment]
[here ](https://stackblitz.com/edit/angular-xquumz-xbvdpc)you go. Please help !

**Comment by benouat** [comment]
@k2ibegin Thanks for the SB!

So in your case, the solution to your issue is the same as the same I already gave [above](#issuecomment-486153351) in this same thread.

You can use the `container="body"` input on both `ngbDatepickerInput` and `ngbDropdown` and it will fix your problem.

**Comment by k2ibegin** [comment]
@benouat thank you, It fixed the issue however, when i am scrolling my page the date popup is moving along with the scroll. I will try to put a Stackblitz for this too, but any pointers on why it possibly could be ? Thanks again !
![2019-12-17 10_26_40-](https://user-images.githubusercontent.com/13697894/70982812-efa6a000-20b7-11ea-9a6e-4c20a1faaece.png)

**Comment by fbasso** [comment]
Now popperjs is in charge of the positioning, this should be solved (popper options can be customized if needed).

Please try it with the latest version of ngBootstrap (13.1.0 as least), and re-open if it's not the case.
