### ISSUE TITLE
Typeahead adds dot symbol when you type two spaces into the text input

### ISSUE THREAD

**Issue by dKab** [ng-bootstrap/ng-bootstrap#3136]
### Bug description:

Type any letter followed by two spaces into typeahead text input input.

**Expected result**: two spaces are typed;

**Actual result**: on a second space a dot symbol appears.

### Link to minimally-working StackBlitz that reproduces the issue:

https://hehveh.run.stackblitz.io

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.0

ng-bootstrap: 4.1.1

Bootstrap: 4.0.0

**Comment by benouat** [comment]
Hello @dKab 

This is not related to ng-bootstrap 😄 
I would assume that you have a Mac, then there is an option, which is inherited from iOS, and activated by default, that **does exactly** that!

Have a look in your system preferences &rarr; _Add period with double-space_
![image](https://user-images.githubusercontent.com/1152740/56651004-71107480-6688-11e9-859f-107517dbd9c3.png)
