### ISSUE TITLE
Ngbmodal halt the entire software

### ISSUE THREAD

**Issue by xyrintech** [ng-bootstrap/ng-bootstrap#3137]
### Bug description:
Opening couple of NgbModals are hanging the web application. I mean lets say we have a form inside a modal and we submit the same form again and again by closing and opening the same modal then this raises the CPU usage and it halts the entire app in some time. 

### Versions of Angular, ng-bootstrap and Bootstrap:
Angular: 7.x
ng-bootstrap: 4.1.1

Bootstrap: 4

**Comment by maxokorokov** [comment]
Hey, @xyrintech

Please provide a reproduction scenario in the stackblitz.

If not possible, try recording Chrome performance timeline and analysing it.
You can export it if necessary as a json file and attach here if you still think its the modal causing it.

**Comment by xyrintech** [comment]
I will try my best to replicate this issue with stackblitz.
But i have tried without the forms and same issue is there with that too.

**Comment by pkozlowski-opensource** [comment]
Going to close this issue for now as we haven't heard back with a reproduce scenario.
