### ISSUE TITLE
Dropdown isn't closed when focus leaves menu or triggering element

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#3140]
### Bug description:

Dropdown menu should be closed when focus leaves either dropdown menu or triggering element.

### Link to minimally-working StackBlitz that reproduces the issue:

Stackblitz with both ng-bootstrap and bootstrap dropdowns to compare:

https://stackblitz.com/edit/angular-uahpzh?file=index.html

Scenario 1:

- Focus `ng-bootstrap` button with keyboard
- Press <kbd>ArrowDown</kbd> to open menu
- Press <kbd>Shift+Tab</kbd> to focus `Before` button
- Dropdown should be closed, but it's not

Scenario 2:

- Focus `ng-bootstrap` button with keyboard
- Press <kbd>ArrowDown</kbd> to open menu
- Press <kbd>Tab</kbd> until focus leaves dropdown menu and focuses `bootstrap` button
- Dropdown should be closed, but it's not

### Versions of Angular, ng-bootstrap and Bootstrap:

ng-bootstrap: 4.1.1

**Comment by dfvgbh** [comment]
Any updates?

**Comment by mendeza** [comment]
Also interested.

**Comment by GregoireLgt** [comment]
Still having this exact issue.
Angular 8.3.29
ng-bootstrap 5.1.0 

Any ideas on how to solve this ?

Thanks
