### ISSUE TITLE
Dropdown menu isn't closed on Enter / Space

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#3142]
### Bug description:

Dropdown should be closed when pressing <kbd>Enter</kbd> / <kbd>Space</kbd> and dropdown item is focused, but it's not

### Link to minimally-working StackBlitz that reproduces the issue:

Stackblitz with both ng-bootstrap and bootstrap dropdowns to compare:

https://stackblitz.com/edit/angular-uahpzh?file=index.html

To reproduce:
- Focus `ng-bootstrap` button with keyboard
- Press <kbd>ArrowDown</kbd> to open menu
- Press <kbd>ArrowDown</kbd> again to focus first item ('New around here? Signup')
- Press <kbd>Enter</kbd> / <kbd>Space</kbd>
- Dropdown menu should close, but it's not.

### Versions of Angular, ng-bootstrap and Bootstrap:

ng-bootstrap: 4.1.1

**Comment by dave0783** [comment]
FYI this fix breaks `(keyup.enter)` binding. `(keyup.enter)="handleSelect()"` is now never called. I had to change to `(keydown.enter)` to make this work.
