### ISSUE TITLE
Dropdown closes on scroll in iOS

### ISSUE THREAD

**Issue by laxu** [ng-bootstrap/ng-bootstrap#3145]
### Bug description:

When scrolling page in iOS, Ngbdropdown menu will close. This makes clicking items on dropdown menus that do not fit on screen impossible. Expected behavior would be keeping the menu open while scrolling and only closing it when either a menu item is selected or user clicks outside the menu. It seems that scroll event causes a click event or something.

Can be replicated even on NgBootstrap 4.1.1 examples.

**Comment by mikeekert** [comment]
@maxokorokov Are there any updates on this one?
