### ISSUE TITLE
Ivy: regression with dropdown position

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#3149]
### Bug description:

With Ivy, the first time a dropdown menu is clicked, the popover appears shifted to the right.

### Link to minimally-working StackBlitz that reproduces the issue:

No stackblitz since it's an Ivy issue., but the bug can easily be reproduced by cloning the following repo and following the instructions in the README (first bug): https://github.com/jnizet/valuechangesivy 

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.0.0-rc.1

ng-bootstrap: 4.1.1

Bootstrap: 4.0.0

**Comment by maxokorokov** [comment]
Same as #3151, closing
