### ISSUE TITLE
Ivy: regression on datepicker when the minDate input is set

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#3151]
### Bug description:

With Ivy, adding a `minDate` input on a datepicker that is part of a reactive form causes the form group to emit a valueChange event even though there has been no change.

### Link to minimally-working StackBlitz that reproduces the issue:

No Stackblitz since it's an Ivy issue, but the bug can easily be reproduced by cloning the following repo and following the instructions in the README (bug 3): https://github.com/jnizet/valuechangesivy

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.0.0-rc.1

ng-bootstrap: 4.1.1

Bootstrap: 4.0.0

**Comment by maxokorokov** [comment]
All three bugs were fixed on the Angular side. Just re-tested with the `9.0.0` and ng-bootstrap `6.0.0`

Closing, thanks!
