### ISSUE TITLE
Carousel in modal

### ISSUE THREAD

**Issue by tlebreton** [ng-bootstrap/ng-bootstrap#3172]
### Bug description:
Hi everybody

First thank you for this amazing lib.
I encounter a bug or maybe it's somethink i do bad.
If i put a carousel in a modal the carousel is shown but  i can't interact with it from my typescript with a ViewChild because  it return undefined.

But if i put the carousel outside the modal.
It's working perfectly i can interact with it without any problem

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-klbkjf

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:
7
ng-bootstrap:
4.1.2
Bootstrap:

**Comment by maxokorokov** [comment]
@tlebreton it has nothing to do with ng-bootstrap, you just can't use `@ViewChild` in this case. Please refer to Angular docs for more details.

I'd suggest you wrap your modal in a proper component, something like this → https://stackblitz.com/edit/angular-klbkjf-qsa6dq?file=app/modal-basic.ts

Cheers.
