### ISSUE TITLE
When using DatePicker.startDate, previous/next month navigation does not work

### ISSUE THREAD

**Issue by dstj** [ng-bootstrap/ng-bootstrap#3178]
### Bug description:
When setting `[startDate]` on a DatePicker as specified in the [doc](https://ng-bootstrap.github.io/#/components/datepicker/api#NgbDatepicker), the navigation the previous or next month no longer work.

When using the alternative `navigateTo()`, it works.

Note: I can't `navigateTo()` because I want the datepicker in a ngbPopover (also in the repro)

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-xtasaf

### Versions of Angular, ng-bootstrap and Bootstrap:
  "@angular/core": "^7.2.5",
  "@ng-bootstrap/ng-bootstrap": "^4.1.2",
  "bootstrap": "^4.3.1",

**Comment by maxokorokov** [comment]
Hey, @dstj!

As `[startDate]` is a binding and you're returning a new object every time from the `getStartDate()` method, you're forcing datepicker to go to this date every time change detection happens.

So if you were to return the same date object, you wouldn't have this issue:

https://stackblitz.com/edit/angular-r72dtz?file=src/app/app.component.ts

However I suppose we should compare the actual start date values inside the datepicker, not rely on object equality in this case.

**Comment by dstj** [comment]
@maxokorokov, right, I should have suspected that, my bad! I assumed somehow that there would be some kind of equality comparaison on the `NgbDateStruct` instead of a only reference check.

Thanks.
