### ISSUE TITLE
Modal NgbModalOptions option not wotking in IE11

### ISSUE THREAD

**Issue by youssefabc** [ng-bootstrap/ng-bootstrap#3185]
### Bug description:

I'am using ngbModalOptions when opening modal like this 
xxx.open(ModalComponent, ngbModalOptions);
and 
export const ngbModalOptions: NgbModalOptions = {
  backdrop : 'static',
  keyboard : false,
  size : 'lg',
  windowClass: 'modal-xl'
}

All of options(backdrop, keyboard, size and windowClass) are working fine with all browsers but not working with IE11!!?

Help please and best regards

### Versions of Angular, ng-bootstrap:

Angular:7.1.1

ng-bootstrap:4.1.2

**Comment by benouat** [comment]
Thank you @youssefabc for reporting a potential bug.

Nonetheless, according to our documentation [You think you've found a bug](
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug) could you please reproduce your scenario in a minimalist Stackblitz in order for us to start working on it ?

**Comment by benouat** [comment]
Hello would you mind having a look at my previous comment ?

**Comment by youssefabc** [comment]
Hello thank you for your response,
I'm sorry for the late response, it works well it's a problem in my code.
So there is no problem
