### ISSUE TITLE
One  Advice

### ISSUE THREAD

**Issue by qqaimh** [ng-bootstrap/ng-bootstrap#3187]
We all know the Material and Ant both have Drawer  Component.
In some cases, it`s necessary and usefull.
As a loyal fan of bootstrap , I hope  bootstrap also have the  Drawer  Component.

**Comment by benouat** [comment]
Hey @qqaimh !
Thanks to reach out, but I am not sure what to do with your issue. You are right, we don't have a drawer component. But as you said, neither has Bootstrap!

We are just a thin layer on top of Bootstrap. If you want Bootstrap to implement a drawer component, ask them by opening a [Feature request](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md#feature-requests).

Then we would probably implement it if they do. On top of it, I am pretty sure that experimenting to create it from scratch would only require a few lines of code with only a couple bindings.

Sorry, I am closing the issue for now.
