### ISSUE TITLE
After setting on pause and clicking on arrows navigation, the cycle restart Carousel

### ISSUE THREAD

**Issue by liyokuna** [ng-bootstrap/ng-bootstrap#3188]
Hello guys,

I created and defined a function to set on pause or play the carousel.
When setting on pause and clicking on one of the arrows navigation, the cycle restated by it own.

### Link to minimally-working StackBlitz that reproduces the issue:
Here is a link to a demo, i fork one of your [demo](https://stackblitz.com/edit/angular-sgw6iw).

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.0.0

ng-bootstrap: 4.1.2

Bootstrap: 4.2.3

**Comment by maxokorokov** [comment]
Hmm, looks like it's actually is a bug...

Currently pressing keyboard <kbd>ArrowRight/Left</kbd> or clicking on the navigation arrows / indicators restarts the interval. We should probably set a `paused` flag internally when calling `.pause()` and reset it when calling `.cycle()`

Anyway the workaround for you would be to reset the interval to `0` → https://stackblitz.com/edit/angular-sgw6iw-dycapw?file=app/carousel-config.ts

**Comment by liyokuna** [comment]
Thanks for the workaround :)
