### ISSUE TITLE
Display multiple images in one Carousel

### ISSUE THREAD

**Issue by shahzadthathal** [ng-bootstrap/ng-bootstrap#3189]
I'm using Anuglar 7 where I need to implement a Carousel which display 4 images in one row, I have been looking for other solution but no help and I came here.

Is it possible to display multiple images in one row i.e 4 images in one row and second is it possible to use our own Left and Right click buttons?

Thanks

**Comment by benouat** [comment]
> Carousel which display 4 images in one row,

Hey @shahzadthathal, could you please elaborate a bit more about that. I am sorry but I did not get exactly what you want to achieve... Would you have any _live_ demo, or equivalent, just to show me the idea ?

**Comment by shahzadthathal** [comment]
Hi

I have attached a image and code.

[Please see image](https://drive.google.com/file/d/1sOSoHwLSXv-pDYkQf4EEfAPiNyAL0cqN/view?usp=sharing)


```
<ngb-carousel *ngIf="images">
  <div class="row">
    <div class="related_product_slide">

      <ng-template ngbSlide *ngFor="let image of images">
        <div class="item col-md-3 active">
          <div class="related_product_item">
              <div class="related_product_pic">
              <img [src]="image" alt="Random first slide">
              <div class="new_product">New</div>
              </div>
              <div class="related_product_content">
                  <h4>iPhone 6S</h4>
                  <p>
                    Living in today's metropolitan
                    world of cellular phones
                  </p>
                  <h5>₩ 100</h5>
                  <h6>₩ <span class="through_line">680</span></h6>
              </div>
          </div>
        </div>
      </ng-template>
    </div>
  </div>
</ngb-carousel>

```
Component
import { NgbCarouselConfig } from '@ng-bootstrap/ng-bootstrap';
@Component({
  selector: 'mom-asset-details',
  templateUrl: './product-details.component.html',
  styleUrls: ['./product-details.component.css'],
  providers: [NgbCarouselConfig]
})
export class AssetDetailsComponent implements OnInit {


images = [1, 2, 3, 4].map(() => `https://picsum.photos/900/500?random&t=${Math.random()}`);


  constructor(private route: ActivatedRoute, private cartService: CartService, config: NgbCarouselConfig) { 
        config.interval = 10000;
        config.showNavigationIndicators = false;
        config.keyboard = true;
        config.pauseOnHover = false;
        config.showNavigationArrows = true;
  }

}
```

**Comment by benouat** [comment]
Oh I see!

Then to me, I don't think we would need to do any change to have that behaviour. It looks like a pure CSS-only type of customisation. In term of features, the widget remains the same, it just looks like different.
I would definitely recommend that you try experimentations in that direction!

**Comment by JonnyD** [comment]
Did you figure how to do this?

**Comment by yakshit15** [comment]
@shahzadthathal Did you find any fix for this?

**Comment by shahzadthathal** [comment]
Hi that was NgbCarouselConfig issue, it was not including properly after including properly it works.

**Comment by yakshit15** [comment]
Can you share the property name in config to display multiple slides?

**Comment by maxokorokov** [comment]
@shahzadthathal I'd say that this particular library implements components for bootstrap, in the case of the carousel it is this component → https://getbootstrap.com/docs/4.3/components/carousel/

What you want seems to be out of scope, unfortunately. However feel free to play with CSS as @benouat suggested
