### ISSUE TITLE
NgbTooltip not properly working on iOS devices

### ISSUE THREAD

**Issue by mzocco** [ng-bootstrap/ng-bootstrap#3192]
Hi to the community,
me and my team have detected an issue on the behavior of the ngbTooltip. 
In details, it properly works on all platforms and browser except from iOS (we tested on Safari browser on iPhone 6, we didn't test on Chrome) where the tooltip does not appear.

That is a snapshot of not working code:

```
<span [ngbTooltip]="'Example tooltip'" class="info-icon info-icon--group" >
   <i class="fas fa-info-circle"></i>
</span>
```

Thanks in advance.

We cannot reproduce on Stackblitz since it is a behavior detected on physical device (or simulator)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 6.0.3

ng-bootstrap: 2.0.0

Bootstrap: 4.1.1

**Comment by cwayfinder** [comment]
This might be related to https://github.com/ng-bootstrap/ng-bootstrap/issues/3199

**Comment by peterblazejewicz** [comment]
@mzocco 
Should the element be interactive on the iOS to get this working, shuldn't?

```html
<span [ngbTooltip]="'Example tooltip'"
  role="button"
  tabindex="0"
  class="info-icon info-icon--group">
  <i class="fa fa-info-circle"></i>
</span>
```

**Comment by AntoineBrunelle** [comment]
If someone needs it, works for me by doing this :
```
<span
  triggers="manual"
  #t="ngbTooltip"
  (click)="t.open()"
  ngbTooltip="test"
></span>
```
