### ISSUE TITLE
NgbDateParserFormatter

### ISSUE THREAD

**Issue by igorgiovannini** [ng-bootstrap/ng-bootstrap#3202]
(I'm just submitting the issue as hint for next version when Angular 8 is supported, I don't ask nobody to fix something for a version that's not yet official).

### Bug description:
Using Angular 8 with Ivy Renderer, a custom NgbDateParserFormatter is not working, it's simply ignored.
The default format is instead used (yyyy-mm-gg).

### Link to minimally-working StackBlitz that reproduces the issue:

At the moment StackBlitz doesn't officially support Ivy Renderer. I'll provide asap a git repo with a project.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8 RC4 + Ivy Renderer

ng-bootstrap: 4.1.3

Bootstrap: 4.3.1

**Comment by pkozlowski-opensource** [comment]
> I'll provide asap a git repo with a project.

Please do - we are already actively looking into supporting ivy and fixing any potential incompatibility issues. But in order to proceed on this one we need to see how do you override `NgbDateParserFormatter`, exactly.

> At the moment StackBlitz doesn't officially support Ivy Renderer

Still would be helpful to have a minimal scenario equivalent to what you've got in your app so we can add this as a unit test.

**Comment by LeandroHeidemann** [comment]
I have the same problem. It also occurs with NgbDateAdapter.

### How am i using:
```
import { Injectable } from '@angular/core';
import { NgbDateAdapter, NgbDateParserFormatter, NgbDateStruct } from '@ng-bootstrap/ng-bootstrap';
import { isUndefined, padStart } from 'lodash';

const regexDateISO8601 = new RegExp(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);
const regexDateBr = new RegExp(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);

@Injectable()
export class NgbDateBrParseFormatter extends NgbDateParserFormatter {

    parse(value: string): NgbDateStruct {
        if (regexDateISO8601.test(value)) {
            return toNgbDateStruct(value.trim().split('-'));
        }

        if (regexDateBr.test(value)) {
            return toNgbDateStruct(value.trim().split('/').reverse());
        }

        return null;
    }

    format(date: NgbDateStruct): string {
        if (!date) {
            return '';
        }
        return [
            isNumber(date.day) ? padStart(`${date.day}`, 2, '0') : '',
            isNumber(date.month) ? padStart(`${date.month}`, 2, '0') : '',
            date.year
        ].join('/');
    }

}

@Injectable()
export class NgbDateNativeOrStringAdapter extends NgbDateAdapter<string | Date> {

    fromModel(date: string | Date): NgbDateStruct {
        if (date instanceof Date && !isNaN(date.getTime())) {
            return {
                year: date.getFullYear(),
                month: date.getMonth() + 1,
                day: date.getDate()
            };
        }

        if (typeof date === 'string') {
            if (regexDateISO8601.test(date)) {
                return toNgbDateStruct(date.trim().split('-'));
            }

            if (regexDateBr.test(date)) {
                return toNgbDateStruct(date.trim().split('/').reverse());
            }
        }

        return null;
    }

    toModel(date: NgbDateStruct): string | Date {
        if (!date || !isInteger(date.year) || !isInteger(date.month) || !isInteger(date.day)) {
            return null;
        }
        const jsDate = new Date(date.year, date.month - 1, date.day, 12);
        jsDate.setFullYear(date.year); // Evita a conversão 30 -> 1930
        return jsDate;
    }

}

function toNgbDateStruct(dateParts: string[]): NgbDateStruct {
    const [ year, month, day ] = dateParts;

    if (!isNumber(year)) {
        return null;
    }

    return {
        year: toInteger(year),
        month: !isUndefined(month) && isNumber(month) ? toInteger(month) : null,
        day: !isUndefined(day) && isNumber(day) ? toInteger(day) : null
    };
}

function toInteger(value: any): number {
    return parseInt(`${value}`, 10);
}

function isNumber(value: any): value is number {
    return !isNaN(toInteger(value));
}

function isInteger(value: any): value is number {
    return typeof value === 'number' && isFinite(value) && Math.floor(value) === value;
}

```

**Comment by maxokorokov** [comment]
Closing not reproducible with Angular 9

**Comment by lleopardi** [comment]
> (I'm just submitting the issue as hint for next version when Angular 8 is supported, I don't ask nobody to fix something for a version that's not yet official).
> 
> ### Bug description:
> Using Angular 8 with Ivy Renderer, a custom NgbDateParserFormatter is not working, it's simply ignored.
> The default format is instead used (yyyy-mm-gg).
> 
> ### Link to minimally-working StackBlitz that reproduces the issue:
> At the moment StackBlitz doesn't officially support Ivy Renderer. I'll provide asap a git repo with a project.
> 
> ### Versions of Angular, ng-bootstrap and Bootstrap:
> Angular: 8 RC4 + Ivy Renderer
> 
> ng-bootstrap: 4.1.3
> 
> Bootstrap: 4.3.1

I have the same problem

**Comment by lleopardi** [comment]
@igorgiovannini you can guide yourself from this post, notice how instead of user useClass use useFactory, it worked for me.

[Here the post](https://stackoverflow.com/questions/39546645/is-it-correct-to-implement-a-custom-ngbdateparserformatter-to-change-the-format)
