### ISSUE TITLE
2 Sets of arrows on datePicker when using popup

### ISSUE THREAD

**Issue by fmpierce** [ng-bootstrap/ng-bootstrap#3205]
When using ng-bootstrap ngbDatepicker it is showing 2 sets of arrows in the month and year selectors of the popup.

It is associated with the class .custom-select and it manifests when using scss and importing the following bootstrap theme:

In _theme.scss
@import "node_modules/bootstrap/scss/custom-forms";

I can fix it with a hack by either overriding .custom-select:
.date-time .custom-select {
    -webkit-appearance: none !important;
}

or by removing the custom-forms import from _theme.scss.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 6.1.0

ng-bootstrap: 3.3.1

Bootstrap: 4.1.3

**Comment by maxokorokov** [comment]
@fmpierce, thanks for reporing an issue, but we won't be able to do anything without a reproduction scenario → https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

You could use this stackblitz with angular 6.1 and ng-bootstrap 3.3.1 as a starting point → https://stackblitz.com/edit/angular-bu18st?file=index.html

**Comment by fmpierce** [comment]
Here's a minimal representation:
https://angular-bu18st-fibk1i.stackblitz.io

The bug manifests when using the code in:
 app.component.ts
`this.stylesheetUrl = this.sanitizer.bypassSecurityTrustResourceUrl(`./assets/themes/styles.css`);`
 and app.component.html
`<link rel="stylesheet" [href]="stylesheetUrl">`

This code allows dynamic css during runtime.

It can be cleared by commenting out the bootstrap custom-forms import in styles.scss

Troubleshooting steps:
change scss import.
npm sass
npm start

This is my first attempt at stackblitz. Please let me know if I didi it wrong.

**Comment by benouat** [comment]
@fmpierce unfortunately your stackblitz seems to **not** be working.. I got an exception trying to run it.

**Comment by fmpierce** [comment]
Can you download the project, type 'npm i', and run it locally?

**Comment by benouat** [comment]
> Can you download the project, type 'npm i', and run it locally?

@fmpierce Which project are you talking about ? I don't see any repo link in here... What should I download

**Comment by benouat** [comment]
Looking a bit more deeply to your non-working Stackblitz, I can already see that you are mixing a lot of different things together! Things that might not coexist well.

+ You are loading `ng-bootstrap` and also `ngx-bootstrap`. They are not supposed to be used together.
+ You are also loading the `jquery` part of bootstrap. In case of using `ng-bootstrap` it's not needed. You can see that from our [documentation](https://ng-bootstrap.github.io/#/getting-started#dependencies).
+ You want to dynamically load bootstrap css, based on the file which is not dynamic at all, it's being processed at build time...

+ You are loading everything from bootstrap in an exploded way. you should always load bootstrap scss file using the shorter syntax `@import "~bootstrap/bootstrap";`, but the file `src/themes/styles.scss` is never used!

+ As this file `src/themes/styles.scss` is never used, it can't work. How did you generate the static css file you load from `assets/` ? The content of this file contains generated css code from bootstrap scss sources, but **it did not go through auto-prefixer**! The `appearance: none` for `.custom-select` is not vendor prefixed, **hence the bug**.

Finally, if I manually load the bootstrap generated css file in `angular.json` file, I don't see you visual artefact of the two set of arrows. Issue is then coming from your specific setup.

Thus you will understand that I am closing this issue, as it is not a real one.
