### ISSUE TITLE
autoclose="false" doesn't work on Dropdown

### ISSUE THREAD

**Issue by ganeshkantu** [ng-bootstrap/ng-bootstrap#3207]
### Bug description:
autoclose="false" doesn't work on Dropdown. Dropdown is closed on both inside and outside clicks. This used to work in a previous version.

### Link to minimally-working StackBlitz that reproduces the issue:
[Stackblitz](https://stackblitz.com/edit/angular-ft8kqr)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 6.1.1

ng-bootstrap: 4.1.3

Bootstrap: 4.0.0

**Comment by JaiKumaresh** [comment]
It's your solution
` [autoClose]="false"`
Becuase it's consiter string

**Comment by ganeshkantu** [comment]
Duh! Thanks!
