### ISSUE TITLE
How to find current index of ngbtypeahead custom template

### ISSUE THREAD

**Issue by JaiKumaresh** [ng-bootstrap/ng-bootstrap#3208]
Now result, term datas are avoidable in custom template. But, I need a current index of custom template result. For my style changes.
`[ngClass]="{'odd-value' : !(index%2==0)}"`

**Comment by benouat** [comment]
Hello @JaiKumaresh 

I would like to remind you that we don't use GH Issues for Support requests. On top of that it's not clear at all to me what you want to achieve!

Could you please then try to update your description, or even better try to reproduce your scenario into a Stackblitz.

**Comment by benouat** [comment]
Closing as no update regarding a reproducible scenario via Stackblitz.

Do not hesitate to re-open with a corresponding Stackblitz when ready.
