### ISSUE TITLE
Update for angular 8 support

### ISSUE THREAD

**Issue by mattiaskagstrom** [ng-bootstrap/ng-bootstrap#3213]
### Bug description:
Add support for Angular 8.
The current version works, but npm warns.

```
npm WARN @ng-bootstrap/ng-bootstrap@4.1.3 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@4.1.3 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@4.1.3 requires a peer of @angular/forms@^7.0.0 but none is installed. You must install peer dependencies yourself.
```

### Versions of Angular, ng-bootstrap and Bootstrap:
Angular 8.0.0
ng-bootstrap: 4.1.3
Bootstrap: 4.3.1

**Comment by mattiaskagstrom** [comment]
References same issue with earlier update:
#2764

**Comment by maxokorokov** [comment]
Thanks for reporting, we'll be releasing the `5.0.0-rc.0` soon with:
- minimal required deps on Angular 8.0 and Boostrap 4.3
- Toasts and some minor features from Bootstrap introduced since 4.0

Can't promise ivy support right from the beginning though.

**Comment by alfredobialo** [comment]
Good Job. Any Plans to Include Animations for Modals, Accordions etc?

**Comment by mendeza** [comment]
There's a lot of work to be done for v5; my team will try to assist. Hopefully others will step up as well.
https://github.com/ng-bootstrap/ng-bootstrap/milestone/73

**Comment by pl4yradam** [comment]
Out of curiosity guys, is it worth launching with v8.0.0 instead of 5?

**Comment by mattiaskagstrom** [comment]
> Out of curiosity guys, is it worth launching with v8.0.0 instead of 5?

That would certainly get rid of the need for a compatibility table between angular and ng-bootstrap.

**Comment by pl4yradam** [comment]
I agree. The stuff we do as its angular specific we align it with their version. It makes things so much simpler.

**Comment by mendeza** [comment]
Tying NGB's major version to Angular's major version would make it impossible for NGB to follow semantic versioning.

**Comment by pl4yradam** [comment]
Then you would have to look at wether you improve developer adoption by
referencing angular. Or have internal semantic versions.

For me now if i went into this project I would assume this only works on
v4. Then I have to go find apparently a compatibility table?

The project is named. Naturally this is the project owners decision.

**Comment by mendeza** [comment]
Well, your projects likely have tens, dozens, or scores of dependencies used in concert with Angular. Would you ask the same of them? Also, arguably there are two equally defining dependencies for this project: Angular and Bootstrap. Why privilege one over the other?

If it _really_ was desired to have a scheme that reflected version support of both these pillars, it might be possible to abuse npm prerelease tags for this purpose, but that's probably a really bad idea.

**Comment by neilsoult** [comment]
> Well, your projects likely have tens, dozens, or scores of dependencies used in concert with Angular. Would you ask the same of them?

Yes, of course. When a package depends on a library with 3/4 of their peerDeps that is all under the same, easily understandable versioning, then yea, I would think that it might be a good idea for them to align. 

> Also, arguably there are two equally defining dependencies for this project: Angular and Bootstrap. Why privilege one over the other?

Bootstrap is not a peer dependency. Seems like a pretty significant reason to privilege one over the other to me.
