### ISSUE TITLE
Angular 8

### ISSUE THREAD

**Issue by elvispdosreis** [ng-bootstrap/ng-bootstrap#3216]
Error angular 8 

ERROR in node_modules/ngx-bootstrap/timepicker/models/index.d.ts(2,38): error TS2307: Cannot find module '@angular/forms/s
rc/directives/control_value_accessor'.
node_modules/ngx-bootstrap/timepicker/models/index.d.ts(3,22): error TS2307: Cannot find module '@angular/core/src/type'.

**Comment by mendeza** [comment]
Different project!
https://github.com/valor-software/ngx-bootstrap

**Comment by elvispdosreis** [comment]
Sorry!
