### ISSUE TITLE
Angular 8 Error Compiler

### ISSUE THREAD

**Issue by elvispdosreis** [ng-bootstrap/ng-bootstrap#3217]
ERROR in ./node_modules/ngx-bootstrap/bundles/ngx-bootstrap.es2015.js 25634:9
Module parse failed: Identifier 'setAllStyles$$1' has already been declared (25634:9)
You may need an appropriate loader to handle this file type.
| }
|
> function setAllStyles$$1(data, renderer) {
|     const target = data.instance.target;
|     const offsets = getOffsets$1(data);

**Comment by mendeza** [comment]
Different project!
https://github.com/valor-software/ngx-bootstrap
