### ISSUE TITLE
DateAdapter is not applied to [maxDate]

### ISSUE THREAD

**Issue by deadmanswitch** [ng-bootstrap/ng-bootstrap#3223]
I use a custom `NgbDateAdapter`. I set it in `app.module` like this:

```
providers: [{provide: NgbDateAdapter, useClass: MyOwnDateAdapter}]
```

It works well with `ngModel`, but not with `[maxDate]`:

```
<input
    class="form-control" placeholder="yyyy-mm-dd"
    [(ngModel)]="selected_day"
    [maxDate]="today"
    ngbDatepicker #d="ngbDatepicker"
>
```

`[maxDate]` still requires an `NgbDateStruct` instance

**Comment by pkozlowski-opensource** [comment]
Yes, this is by design, see https://ng-bootstrap.github.io/#/components/datepicker/api

**Comment by deadmanswitch** [comment]
Do you plan to add this feature in the future? A lot of unnecessary workaround could be avoided, if the date adapter would be applied to `minDate` and `maxDate`

**Comment by pkozlowski-opensource** [comment]
> Do you plan to add this feature in the future?

No, not currently. We've tried and this wasn't great API so will pass on this suggestion for now.
