### ISSUE TITLE
value attribute not bind with ngx-material-timepicker input  in anuglar7?

### ISSUE THREAD

**Issue by kapilSoni101** [ng-bootstrap/ng-bootstrap#3227]
### Bug description:
Hi to all,
I have created a website in anuglar7 in which we are using ngx-material-timepicker for get the time value but before selecting the time we are showing time in the input field but problem is that is value is not bind with input.i am  not understand what the proble behind that.

**Steps to reporduce:**
I have already used both [value] and value={{data}} but not nothing worked for me.

`<input [ngxTimepicker]="picker" [(ngModel)]="date" value="{{data}}"  (ngModelChange)="selectChanged($event)" >
<ngx-material-timepicker #picker></ngx-material-timepicker><br>

<input [ngxTimepicker]="picker1" [(ngModel)]="date1" [value]="data"  (ngModelChange)="selectChanged($event)" >
<ngx-material-timepicker #picker1></ngx-material-timepicker><br>`

### Versions of Angular, ng-bootstrap and Bootstrap:
Angular: 7
Bootstrap:4.0.0

Pelease tell me anyone how to fix this?

**Comment by pkozlowski-opensource** [comment]
Wrong repo, `ngxTimepicker` is not part of this project.
