### ISSUE TITLE
*ngIf issue still exists

### ISSUE THREAD

**Issue by Highspeed7** [ng-bootstrap/ng-bootstrap#3229]
This still exists... it is easily reproducible. Create an element with an ngIf condition and a click event on that element that opens a new dialog. It doesn't work... Switch the ngIf to [hidden] and wahlah! it works. 

> I'm going to close this one as we don't have sufficient info to understand / reproduce and we haven't heard back from the opener. Happy to re-open when / if we've got a reproduce scenario.

_Originally posted by @pkozlowski-opensource in https://github.com/ng-bootstrap/ng-bootstrap/issues/1394#issuecomment-288665155_

**Comment by IAfanasov** [comment]
@Highspeed7 may you please provide a link to stackblitz with reproduction?

**Comment by Highspeed7** [comment]
Okay, so not so easy to reproduce as I thought. I tried, but no luck; however, considering myself and another had this problem... it exists. Closing, since I could not reproduce in stackblitz
