### ISSUE TITLE
DatePicker: (dateSelect) should emit an event when the form control updated

### ISSUE THREAD

**Issue by meness** [ng-bootstrap/ng-bootstrap#3235]
### Bug description:
[As described here](https://ng-bootstrap.github.io/#/components/datepicker/api#NgbInputDatepicker), `(dateSelect)` emits an event when a user selects a date using a keyboard or mouse. It should also emit an event when the form control updated programmatically.

```typescript
this.form.patchValue({
  //...
});
```

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.0.0

ng-bootstrap: 4.2.1

Bootstrap: ?

**Comment by benouat** [comment]
> It should also emit an event when the form control updated programmatically

**It should not**! It would be disturbing or worse would create side effect.

Easiest analogy is that the DOM API itself is not doing that. As example, mutating `input.value` on an `input[type=text]` does not fire any `input` event! We are conforming to this rule here.

So I am sorry but will close as invalid.

**Comment by meness** [comment]
> > It should also emit an event when the form control updated programmatically
> 
> **It should not**! It would be disturbing or worse would create side effect.
> 
> Easiest analogy is that the DOM API itself is not doing that. As example, mutating `input.value` on an `input[type=text]` does not fire any `input` event! We are conforming to this rule here.
> 
> So I am sorry but will close as invalid.

Thanks for your explanation.
