### ISSUE TITLE
NgbCalendarIslamicUmalqura's getToday() returns one day after the original date

### ISSUE THREAD

**Issue by fawadmukhtar** [ng-bootstrap/ng-bootstrap#3237]
Today Hijri date is 11 Shawal 1440 and Gregorian date is 14 June 2019

![image](https://user-images.githubusercontent.com/18648035/59504205-e3991600-8ebb-11e9-90d7-8011483e33e9.png)

When I select Today in the calendar its display wrong date. today should be 11 Shawal 1440 instead of 12 Shawal 1440. This issue produces on the live official documentation https://ng-bootstrap.github.io/#/components/datepicker/calendars and also on the local machine. 
 
![image](https://user-images.githubusercontent.com/18648035/59504401-51454200-8ebc-11e9-9469-cdd243db69da.png)

The problem is in this method `fromGregorian(new Date)`. Its return wrong date. When I invoke `this.calendar.getToday()` then it returns one day after the original date. I have tested it in chrome, IE and opera and faced the same issue. Maybe this is due to calculations in this method `fromGregorian(jsDate)`

**Reason of Issue**
Suppose today is 14 June 2019.  When I pass date like this `fromGregorian(new Date('Sat Jun 14 2019 11:00:00'))` then it's converting as expected But when I pass date like this `fromGregorian(new Date('Sat Jun 14 2019 13:00:00'))` then it's return with adding one day. It's mean this method change date after 12:00 pm (12 noon). 

Bootstrap Version 4.1.3
Angular Version 6.0.6

**Comment by benouat** [comment]
@divdavem could you have a look at this one please ?

**Comment by mdentremont** [comment]
Based on very limited testing @divdavem's fix does appear to resolve the issue
