### ISSUE TITLE
Can't use a template directive as a dropdown menu

### ISSUE THREAD

**Issue by nicolas-b12** [ng-bootstrap/ng-bootstrap#3246]
### Bug description:

When using a template directive on a ngbDropdownMenu, the menu is not placed correctly on first click. When clicking again, the menu is at the right place.

This is due to the fact that `offsetParent` is looking for a parent with a position attribute. This is normally solved by `_applyPlacementClasses` in `dropdown.ts` with the `dropdown` class. 

If you try to add a template to it, ngOnInit is called before the full template rendering. This causes  `NgbDropdown._menu` to be null and `dropdown` class is never applied.

A possible solution (not tested) could be ngAfterViewInit()

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/problem-template-dropdown

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7

ng-bootstrap: 4.2.1

Bootstrap: 4

**Comment by benouat** [comment]
@fbasso Could you please have a look at that one?
