### ISSUE TITLE
Demo: github and twitter buttons in navbar are sometimes broken

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#3254]
### Bug description:

When reloading the demo app, every now and then, the github and/or twitter buttons aren't rendered as they should be. This happens in Firefox and in Chrome.

See this screenshot:
<img width="279" alt="Capture d’écran 2019-06-25 à 22 03 45" src="https://user-images.githubusercontent.com/1608223/60129497-68761080-9795-11e9-949a-5bf62ddbb8a7.png">

**Comment by benouat** [comment]
I have noticed that as well.

Might be related that for both of them we are probably using super old integration code snippets.
I would not be surprised if the API we use are deprecated.

Maybe we should just replace them with stupid static links icons. WDYT ?

**Comment by pkozlowski-opensource** [comment]
> Maybe we should just replace them with stupid static links icons. WDYT ?

+1 - I don't think we are getting enough value from having the current integration scripts, but we still pay the performance price of those scripts.
