### ISSUE TITLE
Datepicker does't works properly with the new engine render Ivy of Angular

### ISSUE THREAD

**Issue by Corralini** [ng-bootstrap/ng-bootstrap#3257]
### Bug description:
Bootstrap datepicker doesn't works with Ivy, the new render engine for Angular, the header of datepicker doesn't bind properly. Without using Ivy, the header binds correctly with de date, but, if you use Ivy date looks doesn't bind with header

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-gz1w2s

There is the project in stackbiltz,  i don't know how can i run the same proyect with Ivy, for these reason to test it you should download it and build in your IDE. 
My recommendation, create a new Proyect with this: "ng new --enableIvy=true" to enable the render engine Ivy and "ng new" to run without Ivy, and see the project in both case.

I send you two picks, the ferst without Ivy and the second using Ivy

**Withou using Ivy**
![image](https://user-images.githubusercontent.com/45268422/60262074-a41bf200-98dd-11e9-8ec7-bf5713ef9007.png)

**Using Ivy**
![image](https://user-images.githubusercontent.com/45268422/60262199-e47b7000-98dd-11e9-9a85-3e75eb597295.png)

### Versions of Angular, Angular CLI, Node, ng-bootstrap, Bootstrap and OS:

Angular: 8.0.3

Angular CLI: 8.0.4

Node: 10.16.0

ng-bootstrap: 5.0.0-rc.0

Bootstrap: 4.3.1

OS: win32 x64

### Contact

You can contact with me through this email:
**acorralfdez@gmail.com**

**Comment by nospam94** [comment]
hi, i have the same problem and have found same trouble with enableIvy = true.

**Comment by Corralini** [comment]
Hi, i want to use Ivy with this datepicker and i search in web but i ddin't find any solution....I decided set this variable as false enableIvy = false, but there was other problem the lot of "shit" that this action implics when you run build. I'm waiting new versions of this datepicker and Ivy engine. I really want use both in the same proyect

**Comment by Corralini** [comment]
> hi, i have the same problem and have found same trouble with enableIvy = true.

Hi, i want to use Ivy with this datepicker and i search in web but i ddin't find any solution....I decided set this variable as false enableIvy = false, but there was other problem the lot of "shit" that this action implics when you run build. I'm waiting new versions of this datepicker and Ivy engine. I really want use both in the same proyect

**Comment by maxokorokov** [comment]
Closing as non-reproducible with Angular 9
