### ISSUE TITLE
NgbToastModule should be exported from ng-bootstrap/index

### ISSUE THREAD

**Issue by krischan1410** [ng-bootstrap/ng-bootstrap#3258]
### Bug description:
NgbToastModule should be exported from ng-bootstrap/src/index.ts
Currently it is not possible to import NgbToastModule from @ngb-bootstrap/ng-boostrap, which works for all other components.

### Link to minimally-working StackBlitz that reproduces the issue:
https://angular-vpwt12.stackblitz.io

The two lines in the StackBlitz are as following:
import {Component} from '@angular/core';
import {NgbToastModule} from '@ng-bootstrap/ng-bootstrap';

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: *

ng-bootstrap: 5.0.0-rc0

Bootstrap: *

**Comment by benouat** [comment]
Hey @krischan1410 ! Thanks to report this issue
How come have I missed such a big thing! 😆😆😆

I will it asap today, and release `5.0.0-rc-1`
