### ISSUE TITLE
Typeahead, Wikipedia search - Request canceled

### ISSUE THREAD

**Issue by z31fbras** [ng-bootstrap/ng-bootstrap#3264]
### Bug description:
On this example found in the docs: https://ng-bootstrap.github.io/#/components/typeahead/examples#http

Requests to Wikipedia get canceled when 
- Switching tabs
- Reducing window
- Resizing window

Do you have any idea on how to fix this?

### Link to minimally-working StackBlitz that reproduces the issue:
The demo can already be found on the website.
Connection throttling makes it easier to reproduce the bug.

**Comment by IAfanasov** [comment]
> * Switching tabs

component with demo destroyed - no need to process the web request, so it's canceled

> * Reducing window
> * Resizing window

cannot reproduce. simulated big latency in chrome network tab and tried to resize the window. the request was not canceled.
don't know how reducing and resizing the window is different.

**Comment by benouat** [comment]
Hey @z31fbras, I would need some clarifications regarding your issue.

+ When talking about `Switching tabs` are you talking about browser tabs? or simply our demo pages tabs (Examples/Api)?

+ Regarding the 2 other points `Reducing` & `Resizing` I can't  manage to reproduce.

**Comment by z31fbras** [comment]
@benouat Hi, I'm talking about switching browser tabs ;)
It's weird, would it be of any use to you if I recorded my computer while reproducing the bug?

**Comment by z31fbras** [comment]
I've been able to solve my own problem by adding a finalize operator in the switchMap operator.

```ts
search = (text$: Observable<string>) =>
    text$.pipe(
      debounceTime(300),
      distinctUntilChanged(),
      tap(() => this.searching = true),
      switchMap(term =>
        this._service.search(term).pipe(
          tap(() => this.searchFailed = false),
          catchError(() => {
            this.searchFailed = true;
            return of([]);
          }),
          finalize(() => {
            this.searching = false;
          })),
      ),
      tap(() => this.searching = false)
    )
```
