### ISSUE TITLE
Datepicker placement global settings

### ISSUE THREAD

**Issue by gurpalgwebs** [ng-bootstrap/ng-bootstrap#3273]
how to set datepicker placement for all elements.
like this:
config.placement = 'bottom-right'

**Comment by benouat** [comment]
Hey @gurpalgwebs,

Good catch! We apparently forgot to add it. It's available on `NgbTooltip`, `NgbPopover`, `NgbDropdown` and `NgbTypeahead`. We simply missed `NgbDatepicker`.

We will fix that asap. We should be able to land it in `5.1.0`

**Comment by gurpalgwebs** [comment]
Thanks

**Comment by benouat** [comment]
Re-opening so we can keep track of it !
