### ISSUE TITLE
Changing the autoHide of a Toast not working

### ISSUE THREAD

**Issue by BemHur** [ng-bootstrap/ng-bootstrap#3280]
### Bug description:

If i create a loop of objects to create Toast's and change the autohide input from true to false, the timer event that hide the Toast still fires.
I was trying to make a mouseenter event to stop the Toast from closing, but it still closed if if a set the autohide input to false. Looking into the Toast code i realized that the ngAfterContentInit event was beeing called two times:
```
  ngAfterContentInit() {
    if (this.autohide) {
      this._timeoutID = setTimeout(() => this.hide(), this.delay);
    }
}

```
With that there was two TimeOut events beeing created and only one ref beeing saved in the timeoutID variable, so even if i changed the autohide input to false and the code removing the timeout refered, it still had 1 TimeOut event active.
To fix this, simple add the clearTimeOut function every time the ngAfterContentInit fired, preventing multiple TimeOut events from being created.

```
  ngAfterContentInit() {
    if (this.autohide) {
      this._clearTimeout();
      this._timeoutID = setTimeout(() => this.hide(), this.delay);
    }
}
```

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.0.1

ng-bootstrap: 5.0.0-rc.0

Bootstrap: 4.3.1

Edit:
### Stackblitz :
https://angular-toast-bug.stackblitz.io
https://stackblitz.com/edit/angular-toast-bug

**Comment by benouat** [comment]
Hey @BemHur !
Thank you for reporting a potential bug.

Nonetheless, according to our documentation [You think you've found a bug](
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug) could you please reproduce your scenario in a minimalist Stackblitz in order for us to start working on it ?

**Comment by BemHur** [comment]
> 
> 
> Hey @BemHur !
> Thank you for reporting a potential bug.
> 
> Nonetheless, according to our documentation [You think you've found a bug](https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug) could you please reproduce your scenario in a minimalist Stackblitz in order for us to start working on it ?

No problem:
### Stackblitz :
https://angular-toast-bug.stackblitz.io
https://stackblitz.com/edit/angular-toast-bug
