### ISSUE TITLE
scrollable doesn't work on modals with component as content

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#3281]
### Bug description:

When using a component as the content of a modal rather than a template, with the scrollable option set to true, the modal body doesn't scroll.

The CSS magic apparently doesn't work when an additional element (the host element of the component) is inserted between the `.modal-content` and the `.modal-body`, but I'm so bad at CSS that I can't even find a workaround.

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-rekfnj?file=app/modal-component.ts

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.1
ng-bootstrap: 5.0.0-rc.1
Bootstrap: 4.3.1

**Comment by benouat** [comment]
Ohhh nice catch @jnizet !! 😎 👍 
This is indeed not working. The component host element is messing things around.

Quick fix to allow you to move on → add these 2 css properties on your component class:

```css
{
  display: flex;
  flex-direction: column;
}
```

---

On our side, I will open a PR asap in which we will add a CSS class containing these 2 properties on the component host element by the time we create it dynamically.

**Comment by jnizet** [comment]
Thanks @benouat , but I don't think adding these two styles on the modal content component fixes anything. Unless I miss something in your instructions. Could you provide an example where this workaround works?

Here's a workaround I found (but it's a bit fragile, and I suck at CSS):

Replace, in the template of my modal content component

```
[...]
<div class="modal-body ">
  [long content here]
</div>
```

by 

```
<div class="modal-body px-0">
  <div style="overflow-y: hidden; height: calc(100vh - 15rem);">
    <div class="px-2" style="overflow-y: auto; height: 100%;">
      [long content here]
    </div>
  </div>
</div>
```

**Comment by benouat** [comment]
> I don't think adding these two styles on the modal content component fixes anything

yes yes, they do!

Here is the modifed stackblitz: https://stackblitz.com/edit/angular-rekfnj-rydpk1?file=app/modal-component.ts

I basically just added that on your component decorator:

```typescript
@Component({
  /* ... */
  host: {
    '[style.display]': '"flex"',
    '[style.flex-direction]': '"column"'
  }
})
export class NgbdModalContent {
```

**Comment by benouat** [comment]
Ok! You're not alone and I apparently half **suck** at CSS 😆 my fix only works on Safari.

Stay tuned, I'll make it work, and post the solution here.

**Comment by benouat** [comment]
This is my **final** word 🤣 tested, and working on Safari, Chrome and Firefox.

I was missing the `overflow`, of course!
So

```typescript
@Component({
  /* ... */
  host: {
    '[style.display]': '"flex"',
    '[style.flex-direction]': '"column"',
    '[style.overflow]': '"hidden"'
  }
})
export class NgbdModalContent {
```

I also update the SB →  https://stackblitz.com/edit/angular-rekfnj-rydpk1?file=app/modal-component.ts

**Comment by jnizet** [comment]
Perfect @benouat ! You rock! Thanks a lot.

**Comment by benouat** [comment]
While working on a final fix for that one, it crosses my mind that a much simpler fix could be done

Here it is:

```typescript
@Component({
  /* ... */
  host: {
    '[class.modal-content]': 'true'
  }
})
export class NgbdModalContent {}
```

We basically just need to duplicate internal Bootstrap class on our man in the middle extra component wrapper. This `modal-content` class has basically all the needed properties I suggested in my previous fix.

The result markup would be someting like that:

With template
```html
<ngb-modal-window class="modal">
  <div role="document" class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header"></div>
      <div class="modal-body"></div>
      <div class="modal-footer"></div>
    </div>  
  </div>
</ngb-modal-window>
```

With component
```html
<ngb-modal-window class="modal">
  <div role="document" class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">

      <my-dialog-cpt class="modal-content">      

        <div class="modal-header"></div>
        <div class="modal-body"></div>
        <div class="modal-footer"></div>
    
      </my-dialog-cpt>

    </div>  
  </div>
</ngb-modal-window>
```

**Comment by melgish** [comment]
Since bootstrap wants the class, and the tag name is irrelevant, wouldn't a better fix be to remove the wrapping `<div class="modal-content">` and instead just add that class to the component itself.  

```html
<ngb-modal-window class="modal">
  <div role="document" class="modal-dialog modal-dialog-scrollable">
      <my-dialog-cpt class="modal-content">      

        <div class="modal-header"></div>
        <div class="modal-body"></div>
        <div class="modal-footer"></div>
    
      </my-dialog-cpt>
  </div>
</ngb-modal-window>
```

**Comment by benouat** [comment]
I don't think we could do that because of the 2 different code paths for supporting ng-template or Component based modal.
We would probably need to  duplicate some markup in a not very elegant/obvious way, that would make understanding of the code for maintenance harder if you are _not_ aware of this bug/specifity.

**Comment by umdstu** [comment]
I finally updated Angular from 7 -> 8 just to use `scrollable: true`, and it doesn't even work, 🗡.

Looking forward to the final fix, but thanks for the workaround in the meantime!

**Comment by benouat** [comment]
@umdstu the fix landed in [5.1.0](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#510-2019-07-17) which is tied to Angular 8.0.0

**Comment by umdstu** [comment]
@benouat thanks for taking the time to reply. According to my package.json I am now running Angular 8.2.14 and @ng-bootstrap/ng-bootstrap 5.3.0 and it wasn't working. But in an effort to really ensure I wasn't doing something stupid, I tried something and it now works. 

I was wrapping my components html in <form> </form> (so that the submit button in the footer works as expected), and that is what breaks it. The solution was to give the form an `id` and then in the submit buttin, set that the buttons form attribute to that value. Sorry to have bothered.

**Comment by muasif80** [comment]
@umdstu Your suggestion is great and solved it for me too. The form element should go inside the .modal-body div or whatever. But when I was wrapping modal-footer, modal-body and modal-header inside form the scroll was not appearing.

**Comment by luisVargasGu** [comment]
Guys 

> This is my **final** word 🤣 tested, and working on Safari, Chrome and Firefox.
> 
> I was missing the `overflow`, of course!
> So
> 
> ```ts
> @Component({
>   /* ... */
>   host: {
>     '[style.display]': '"flex"',
>     '[style.flex-direction]': '"column"',
>     '[style.overflow]': '"hidden"'
>   }
> })
> export class NgbdModalContent {
> ```
> 
> I also update the SB → https://stackblitz.com/edit/angular-rekfnj-rydpk1?file=app/modal-component.ts

This works, you just need to change '[style.overflow]': '"hidden"' to '[style.overflow]': '"auto"'

**Comment by tayambamwanza** [comment]
> Guys
> 
> > This is my **final** word rofl tested, and working on Safari, Chrome and Firefox.
> > I was missing the `overflow`, of course!
> > So
> > ```ts
> > @Component({
> >   /* ... */
> >   host: {
> >     '[style.display]': '"flex"',
> >     '[style.flex-direction]': '"column"',
> >     '[style.overflow]': '"hidden"'
> >   }
> > })
> > export class NgbdModalContent {
> > ```
> > 
> > 
> > I also update the SB → https://stackblitz.com/edit/angular-rekfnj-rydpk1?file=app/modal-component.ts
> 
> This works, you just need to change '[style.overflow]': '"hidden"' to '[style.overflow]': '"auto"'

100% that did it 

```ts
@Component({
  selector: '...',
  templateUrl: '...',
  styleUrls: [...],
  host: {
    '[style.display]': '"flex"',
    '[style.flex-direction]': '"column"',
    '[style.overflow]': '"hidden"'
  }
})
```

**Comment by fmalk** [comment]
Sorry to comment on a closed thread, but I got here via Google and I was dealing with this specific bug, albeit my case was more complicated due to injection of another Component inside the one component my modal opens up.
This thread showed me a simple fix, so I'll leave it here. Thanks everyone above for the help.

_Angular: 11.2.5
ng-bootstrap: 9.1.2
Bootstrap: 4.5.0_

Host component **just** needed that `[style.overflow]: "auto"`. The default `ngb-modal-window .component-host-scrollable` rule comes with `overflow: hidden`, which is not enough if I'm changing `modal-body` with new content after I already opened the modal with the host component.
So, my final host component becomes:

```
@Component({
  selector: 'app-modal',
  styleUrls: ['modal.component.scss'],
  host: {
    '[style.overflow]': '"auto"'
  },
  template: `
    <div modal>
      <div class="modal-header">
        <h1 class="modal-title">{{ dto?.title}}</h1>
        <button type="button" class="close" aria-label="Close" (click)="modal.dismiss()">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ng-container *ngComponentOutlet="item"></ng-container>
      </div>
      <div class="modal-footer">
        <button ngbAutofocus type="button" class="btn btn-primary" (click)="modal.close()">OK</button>
      </div>
    </div>
	`,
})
export class ModalComponent {
  @ViewChild(ModalDirective) modal;
  public item: Type<any>;
}

-----------------------------------

export class ModalService {
  constructor(private ngbModalService: NgbModal) { }
  (...)
  openModal(content: Type<any>) {
    const modalRef = this.ngbModalService.open(ModalComponent,  { scrollable: true });
    const compRef = modalRef.componentInstance as ModalComponent;
    compRef.item = content;
  }
```
