### ISSUE TITLE
NgbToastModule not supported

### ISSUE THREAD

**Issue by MrHuBz** [ng-bootstrap/ng-bootstrap#3284]
NgbToastModule dosen't download in bootstrap module 
i try to import it but couldn't find it in '@ng-bootstrap/ng-bootstrap';
i use in my packege.json    
 "@ng-bootstrap/ng-bootstrap": "^4.2.1",

**Comment by benouat** [comment]
Hey @MrHuBz !

Toast feature has only been delivered in `v5.0.0`. Try replacing your ng-bootstrap reference, then it should work.

**Comment by MrHuBz** [comment]
![Capture](https://user-images.githubusercontent.com/20802774/60970634-ab51ef80-a322-11e9-972d-198773d1716a.PNG)

i'm using angular 7

**Comment by benouat** [comment]
> i'm using angular 7

Any specific reason you are in `v7` ? You could simply migrate to `v8` it is quite straight forward. Not that much breaking changes....

Apart from that, we **can't make** it available to ng-bootstrap `v4.x`. Toast are only available with `v5.0`. They are part of Bootstrap `4.2` which itself is not compliant also with ng-bootstrap `v4.x`


**Summary**:  if you need toast, you have to do the migration. No other choice.
