### ISSUE TITLE
Incorrect tooltip arrow placement for nested tooltips

### ISSUE THREAD

**Issue by t-mog** [ng-bootstrap/ng-bootstrap#3285]
### Bug description:
The placement of the tooltip arrow and the arrow shape are incorrect when having nested tooltips with different placements (for example, bottom and right). Similarly to bug #2234 with popover component.

![image](https://user-images.githubusercontent.com/7684115/60969237-b3605e00-a327-11e9-83ff-91d27f8b0a3d.png)

### Link to minimally-working StackBlitz that reproduces the issue: 
https://stackblitz.com/edit/angular-wi2xah

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.0.0

ng-bootstrap: 5.0.0

Bootstrap: 4.3.1

**Comment by fbasso** [comment]
As explain in #2234, use autoClose="outside" on the first tooltip and container="body" (missing on the given stackblitz) on the second should work

**Comment by t-mog** [comment]
Thanks, it seems to help. Sorry, accidentally skipped it on the StackBlitz.

**Comment by benouat** [comment]
I am going to close that one as apparently the fix provided by @fbasso is working.

If needed do not hesitate to re-open!
