### ISSUE TITLE
pagination: collectionSize not changed after pageSize changed

### ISSUE THREAD

**Issue by nitishrajput01** [ng-bootstrap/ng-bootstrap#3290]
### Bug description:

when changing page size collection size not updating

let''s say i having drop-down for showing enteries in a table
. when i select pageSize = 5, pagination is working ok after i changed the pageSize from 5 to 10
which is working fine. but when i again change pageSize from 10 to 5 than on 2nd tab i'm having data length 7 instead of 5.

collectionSize = 12;

.ts file 
```
public pageSizeOptions = [5, 10, 15, 20];
public pageSize = 5;
public currentPage = 1;
selectPageSize(event) {
this.pageSize = event.target.value;
}

```
.html file 
```
<tr *ngFor="let item of devicesList | slice: (currentPage-1) * pageSize : (currentPage-1) * pageSize + pageSize">
</tr>

<label for="pageSize">show &nbsp;</label>
          <select name="pageSize" (change)="selectPageSize($event)">
           <option *ngFor = "let size of pageSizeOptions" [value]="size">{{size}}</option>
          </select>
          <label for="enteries">&nbsp;&nbsp;enteries</label>
        </div>
        <ngb-pagination class="pagination_class" [collectionSize]="devicesList.length" [pageSize]="pageSize" [(page)]="currentPage"
          aria-label="Default pagination"></ngb-pagination>
```

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 6.1.0

ng-bootstrap: 3.3.0

Bootstrap: 4.1.3

**Comment by benouat** [comment]
Thank you @nitishrajput01 for reporting a potential bug.

Nonetheless, according to our documentation [You think you've found a bug](
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug) could you please reproduce your scenario in a minimalist Stackblitz in order for us to start working on it ?

**Comment by maxokorokov** [comment]
Closing as no feedback

**Comment by issstine** [comment]
event.target.value is in string format. change to number, it will work.
