### ISSUE TITLE
NgbTab create Its content whenever selected.

### ISSUE THREAD

**Issue by abadakhshan** [ng-bootstrap/ng-bootstrap#3293]
NgbTab create Its content whenever selected.
This mechanism is not good for conditions that users don't want that their components
recreated.

please add options to prevent this condition.

**Comment by fbasso** [comment]
I don't get the point fo destroy/re-create components when tabs are not selected/selected. It's the purpose of a templating engine to remove elements when they are not in the display.

What's the issue to remove components in this case ?

**Comment by fbasso** [comment]
I didn't think about it, butit seems this option already exists : destroyOnHide

See https://ng-bootstrap.github.io/#/components/tabset/api#NgbTabset for more information.

**Comment by abadakhshan** [comment]
Thank you @fbasso 
That was exactly what I wanted.

I use it to create TabOutlet

You can  see an example here:

https://github.com/NarikMe/narik-ng-bootstrap-demo

**Comment by benouat** [comment]
Closing as @abadakhshan seems happy with the hint provided!
