### ISSUE TITLE
Blurry text in typeahead modal on Chrome with zoom

### ISSUE THREAD

**Issue by jdussouillez** [ng-bootstrap/ng-bootstrap#3294]
### Bug description:
On Chrome, when the zoom is not set to 100% the text in the typeahead modal looks blurry.

![blurry_text_2](https://user-images.githubusercontent.com/5428355/61200005-4f9bb380-a6e0-11e9-9f78-688bec0e163d.png)

I tested it on Linux (Linux Mint 19.1) and Windows 7 & 10, and reproduced it every time.

### Link to minimally-working StackBlitz that reproduces the issue:

- Open the [Stackblitz](https://stackblitz.com/edit/angular-ng-bootstrap-issue-3294) with Chrome 
- Set the zoom to 90% or 110%
- Click on the input to open the modal and type "test"
- The modal shows up but the text is blurry

It seems to come from the `transform: translate(x, y)` CSS property on the `ngb-typeahead-window`. If you toggle the comment ` transform: translate(0, 0) !important;` line 55 in the file `index.html` the text isn't blurry anymore.

I tried a few tricks to fix it but nothing worked (I disabled the hardware acceleration in the Chrome settings, played with the `-webkit-font-smoothing` and `transform` properties, ...)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.0.0

ng-bootstrap: 5.0.0

Bootstrap: 4.3.1

Chrome: 75.0.3770.100

**Comment by jdussouillez** [comment]
This bug exists in Bootstrap v4.3.1 too. It's possible to prevent it using two different solutions:

1. [Disabling Popper.js GPU acceleration](https://popper.js.org/popper-documentation.html#modifiers..computeStyle.gpuAcceleration)  ([JSFiddle](http://jsfiddle.net/hfsv31ec/)) 

2. Disabling Popper.js positionning ([see option `display` for Bootstrap dropdowns](https://getbootstrap.com/docs/4.1/components/dropdowns/#options), [JSFiddle](http://jsfiddle.net/z0gfx248/)).

These two solutions will position the dropdown using `top` & `left` CSS properties instead of `transform`.

---

But ng-bootstrap does not use Popper.js, it's a custom implementation. See [ng-boostrap - Positionning](https://ng-bootstrap.github.io/#/positioning) :

> Bootstrap uses popper.js library for positioning. We decided not to have any dependencies on 3rd party libraries, so we implement a subset of the same functionality ourselves. If something is missing or you have a very specific use case - please open an issue on GitHub and we'll discuss.

> Since version 4.1 we position the popup using position: absolute; transform: translate(x,y); to match Bootstrap.

**Comment by fbasso** [comment]
Thanks for your input @jdussouillez ! An option to disable gpu acceleration in an option to study indeed !

**Comment by AndreiShostik** [comment]
as @jdussouillez already mentioned the cause of the issue is `transform` property and if so someones workarounds: 

``` scss
  -webkit-font-smoothing: antialiased; /* subpixel-antialiased and others... */
  -webkit-filter: blur(0px);
  -webkit-perspective: 1000;
  filter: blur(0px);
  backface-visibility: hidden;
```

worked - https://stackoverflow.com/questions/14677490/blurry-text-after-using-css-transform-scale-in-chrome

for me it getting even worse: 

![](https://image.prntscr.com/image/jaliMLsxTXerlldJ5K27ow.png)

unfortunately will have to inject some js workaround

**Comment by zmirc** [comment]
Experiencing the same here with 4.2.2 when using zoom 90% on Chrome 81.
Disabling this inline CSS on ngb-typeahead-window seems to make it go away:
will-change: transform

P.S. Off topic: Can't update to a newer ngb because we're on Angular 7. A pity that we're totally in the dark now with ngb for the new releases, stuck with 4.2.2 for now.
P.P.S. Thanks for this useful library.

**Comment by theloserbm** [comment]
Inspired by @zmirc, fixed blurry text on dropdown-menu by adding following
```
.dropdown-menu {
  will-change: auto !important;
}
```

**Comment by poddarkhushbu07** [comment]
@zmirc @theloserbm I too have the same issue. Is there any side effect of using will-change?

**Comment by fbasso** [comment]
Now popperjs is in charge of the positioning, this should be solved (popper options can be customized if needed).

Please re-open if it's not the case.
