### ISSUE TITLE
Sorting of nested data not possible

### ISSUE THREAD

**Issue by hydrogen2oxygen** [ng-bootstrap/ng-bootstrap#3295]
### Bug description

First of all, I don't know if this is a bug or maybe a "missing feature".
The problem is that **sorting for a table** with **nested elements** inside a json does not work.

Example data:

```js
  {
    id: 1,
    name: 'Russia',
    flag: 'f/f3/Flag_of_Russia.svg',
    area: 17075200,
    details: {
      population: 146989754
    }
  }
```

The column details.population is not sortable.

### Link to minimally-working StackBlitz that reproduces the issue:

I modified [one of yours demo in stackblitz](https://stackblitz.com/edit/angular-hktvez?file=app%2Ftable-sortable.ts) and was so able to reproduce the "bug".

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.0.1

ng-bootstrap: 5.0.0

Bootstrap: 4.3.1

**Comment by IAfanasovMob** [comment]
FYI
Angular: 8.0.1 and Bootstrap: 4.3.1 r not compatible. probably not related to this issue but could save u some time (:

**Comment by hydrogen2oxygen** [comment]
> Angular: 8.0.1 and Bootstrap: 4.3.1 r not compatible. probably not related to this issue but could save u some time (:

Hello @IAfanasovMob ! Can you please explain why the CSS style version of Bootstrap 4.3.1 is important for this issue? Or do you mean the ng-bootstrap version? Because the sorting occurs in javascript and not inside a css style ;) right?

**Comment by IAfanasovMob** [comment]
> > Angular: 8.0.1 and Bootstrap: 4.3.1 r not compatible. probably not related to this issue but could save u some time (:
> 
> Hello @IAfanasovMob ! Can you please explain why the CSS style version of Bootstrap 4.3.1 is important for this issue? Or do you mean the ng-bootstrap version? Because the sorting occurs in javascript and not inside a css style ;) right?

sorry, my bad - confused ng-bootstrap and bootstrap version (%

**Comment by benouat** [comment]
hey @hydrogen2oxygen!

What you actually describe is **not** a bug. It's just how javascript is working.

Whenever you want to sort a collection of objects, you **must** implement your own comparator function. The native `sort()` function cannot infer which property inside the object to be used. (So if one of the property is even an sub-object itself, as in your example, it's even worst)

I would encourage you to read carefully the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) about sorting arrays. I hope it will be clearer for you afterward.
