### ISSUE TITLE
ngModel with ngbRadioGroup does not provide correct radio value in .ts

### ISSUE THREAD

**Issue by chrisplusplus** [ng-bootstrap/ng-bootstrap#3299]
### Bug description:
ngModel with ngbRadioGroup does not provide correct radio value in .ts file on console.log

It appears that console.log value is the previously selected value rather than the currently selected one.

Please note: I am not talking about the the value emitted in the html.  The value printed is there is correct.  Make sure to look at the console output to see the bug.

This bug prevents setting the active button programatically (or accurately).

###Stackblitz
[](https://stackblitz.com/edit/angular-wsu5qg)

Angular: ^7.0.2

ng-bootstrap: 4.2.1

Bootstrap: 4.1.3

**Comment by chrisplusplus** [comment]
oops forgot the Stack link: [https://stackblitz.com/edit/angular-wsu5qg](https://stackblitz.com/edit/angular-wsu5qg)

**Comment by maxokorokov** [comment]
Buttons were removed in v13 → https://ng-bootstrap.github.io/releases/12.x/#/components/buttons/overview
