### ISSUE TITLE
All Stackbliztes are not working with 5.1.0

### ISSUE THREAD

**Issue by benouat** [ng-bootstrap/ng-bootstrap#3300]
Since yesterday publication of `ng-bootstrap@5.1.0` all Stackblitzes are failing to load, because `5.1.0` is not recognised as an existing version.

I opened an issue on their side https://github.com/stackblitz/core/issues/1019 to follow up.

It might be related also to an NPM caching issue see https://github.com/stackblitz/core/issues/624

**Comment by jnizet** [comment]
Workaround to get the stackblitz examples working:
 
 - In Stackblitz, click on "Install missing dependencies" (it will ask to do that twice, do that twice)
 - Then stackblitz will complain about core.js. Open the package.json file. Replace the version of core-ja by `"2"`. Hit Ctrl-S  Cmd-S to save.

**Comment by benouat** [comment]
@jnizet half workaround only, as it will load `5.0.0` instead of latest semver compliant that should be `5.1.0`

**Comment by benouat** [comment]
Issue has been solved by creating a new ng-bootstrap release `v5.1.1`.
It basically unlocked the problem on Stackblitz itself, as for now `v5.1.0` is also finally working
