### ISSUE TITLE
A11y [Tabset]: tab count is announced incorrectly

### ISSUE THREAD

**Issue by asapach** [ng-bootstrap/ng-bootstrap#3302]
### Bug description:

When using Tabset component screens readers such as [NVDA](https://www.nvaccess.org/) announce the tab count incorrectly.

![image](https://user-images.githubusercontent.com/1755336/61142799-53a9b480-a4d9-11e9-94cd-bf93dffccf71.png)

In this example the following message is announced:
> Simple tab selected 1 of 1

The expected message is:
> Simple tab selected 1 of 3

The problem is that when `<ul>` is used with `role=tablist`, the list items retain their semantic role and `<li>` becomes the parent of the tab (`role=tab`) in the accessibility tree. Which means that the tab "doesn't know" about it's siblings:
![image](https://user-images.githubusercontent.com/1755336/61482347-0b8c0580-a9a3-11e9-8931-7f8b58dad670.png)

```html
<ngb-tabset>
  <ul role="tablist" class="nav nav-tabs justify-content-start">
    <li class="nav-item"> <!-- here -->
      <a class="nav-link active" href="" role="tab"... aria-selected="true" aria-disabled="false">
        Simple
      </a>
    </li>
    ...
</ul>
```

The fix is to add `role=none` to the `<li>` elements so that they are [excluded from the accessibility tree](https://www.w3.org/TR/using-aria/#presentation) and screen readers would ignore their semantic role:
![image](https://user-images.githubusercontent.com/1755336/61482517-7c332200-a9a3-11e9-9ae6-ae8fb3dd22a2.png)

```html
<ngb-tabset>
  <ul role="tablist" class="nav nav-tabs justify-content-start">
    <li class="nav-item" role="none"> <!-- here -->
      <a class="nav-link active" href="" role="tab"... aria-selected="true" aria-disabled="false">
        Simple
      </a>
    </li>
    ...
</ul>
```

### Link to minimally-working StackBlitz that reproduces the issue:

https://ng-bootstrap.github.io/stackblitzes/tabset/basic/stackblitz.html

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.x

ng-bootstrap: 5.1.x

Bootstrap: 4.x

**Comment by maxokorokov** [comment]
Related to #3134

**Comment by maxokorokov** [comment]
Since version `5.2.0` there is a new `NgbNav` set of directives that fix this issue. `NgbNav` is meant to replace the `NgbTabset` component (completely deprecated in version `6.0.0`) as a more flexible alternative.

There is a new `[roles]` input in the `NgbNav` → https://ng-bootstrap.github.io/#/components/nav/api#NgbNav

I suggest you migrate to it → https://ng-bootstrap.github.io/#/components/nav/overview
