### ISSUE TITLE
Demo isnt working on https://ng-bootstrap.github.io/ anymore

### ISSUE THREAD

**Issue by johnruck** [ng-bootstrap/ng-bootstrap#3304]
### Bug description:
Trying to use the Demo link on https://ng-bootstrap.github.io/ results in it jumping to the Alerts documentation page.

**Comment by johnruck** [comment]
In case you are wondering why I am looking for it, I was trying to get a navbar working with ng-bootstrap, stumbled across this ticket - https://github.com/ng-bootstrap/ng-bootstrap/issues/738 - and as part of that ticket they say you can look at the demo to see an example of a working navbar, and they show a code quote referencing ng-bootstrap/demo/src/app/app.component.html which I was trying to find where that is at on the website today and couldnt find it.

**Comment by pkozlowski-opensource** [comment]
Not sure what you mean - our demo page is up and alive at https://ng-bootstrap.github.io/#/home and it still has navbar in it.

**Comment by johnruck** [comment]
Sorry, I figured that might have been your intent later, I was just expecting a demo area to have small bits of samples with code built for the purpose of demoing instead of being part of another section of the website.
