### ISSUE TITLE
Tab documentation missing from homepage

### ISSUE THREAD

**Issue by kjrocker** [ng-bootstrap/ng-bootstrap#3311]
Not sure where else to put this, but [https://ng-bootstrap.github.io/#/components/tabs] leads nowhere, and tabs don't appear in the list of available widgets on the site.

I see issues around tab behavior, so I know they exist somewhere. Is this intentional?

**Comment by fbasso** [comment]
Where did you find this link ? [Tabset](https://ng-bootstrap.github.io/#/components/tabset) is not what you look for ?

**Comment by kjrocker** [comment]
Well I'm dumb. The link is from the homepage in the "Widgets" section. It points to tabs, when the link is tabset. I guess that's my actual issue report then. :)

**Comment by fbasso** [comment]
ok, good point !
