### ISSUE TITLE
When date is in first month of any year, the date ever down 1 day on update

### ISSUE THREAD

**Issue by GbDanielO** [ng-bootstrap/ng-bootstrap#3316]
When date is in first month of any year, the date ever down 1 day on update.

For other months the datepicker works fine.

my project:
https://github.com/GbDanielO/frontendses

thanks

**Comment by fbasso** [comment]
Thank you @GbDanielO for reporting a potential bug.

Nonetheless, according to our documentation [You think you've found a bug](https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug) could you please reproduce your scenario in a minimalist Stackblitz in order for us to start working on it ?

**Comment by maxokorokov** [comment]
Closing as no feedback form the reporter
