### ISSUE TITLE
dismiss and close is undefined of modal

### ISSUE THREAD

**Issue by lhf552004** [ng-bootstrap/ng-bootstrap#3320]
I followed the tutorial Modal with default options in 
https://ng-bootstrap.github.io/#/components/modal/examples#basic
But I got error "Cannot read property 'dismiss' of undefined"
![image](https://user-images.githubusercontent.com/10030850/62184242-bcc17100-b38f-11e9-8a81-b6025fe19859.png)

I think the object modal is not got. I don't know why the let modal doesn't work.
```
<ng-template #content let-modal>
  <div class="modal-header">
    <h4 class="modal-title" id="modal-basic-title">Profile update</h4>
    <button type="button" class="close" aria-label="Close" (click)="modal.dismiss('Cross click')">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
```

**Comment by fbasso** [comment]
Thank you @lhf552004 for reporting a potential bug, but I don't understand how you have this exception. The modal in https://ng-bootstrap.github.io/#/components/modal/examples#basic works well.

Could you please you please reproduce your scenario in a minimalist Stackblitz in order for us to start working on it ? (see  [You think you've found a bug](https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug))

**Comment by lhf552004** [comment]
@fbasso, Hi, thank you for ur help. I have submit to stackblitz:
https://stackblitz.com/edit/angular-qfavmw. Here you can find the modal couldnot be closed with an error occured in console.

Another thing I was confused that, why in my local I need to import NgbModule.forRoot(), while in stackblitz, only can import NgbModule
Local:
```
 imports: [
    BrowserModule,
    NgbModule.forRoot()
  ],
```
stackblitz:
```
 imports: [
    BrowserModule,
    NgbModule
  ],
```

**Comment by lhf552004** [comment]
@fbasso, Hi I have found the reason,  I used the old version of ng-bootstrap. sorry
