### ISSUE TITLE
ngbDropdown overflow not hidden on IE11

### ISSUE THREAD

**Issue by Zverit** [ng-bootstrap/ng-bootstrap#3324]
### Bug description:
ngbDropdown overflow not hidden on IE11.  Maybe this is a bug due to use transform on IE11.
![Screenshot_5](https://user-images.githubusercontent.com/1945239/62464738-106bfa00-b796-11e9-8d9e-ec21dd4b2e13.png)

### Link to minimally-working that reproduces the issue:
Can reproduce on demo site: https://ng-bootstrap.github.io/#/components/dropdown/examples

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.0.0

ng-bootstrap: 5.1.0

Bootstrap: 4.3.1

**Comment by maxokorokov** [comment]
cc @fbasso

**Comment by fbasso** [comment]
The same occurs on Bootstrap. As you said, it's an issue with ie (the test for the scrollbar display is done before the transform), and it's hard to workaround it internally.

If you really care about it for your case, just use container="body" on the dropdown.
