### ISSUE TITLE
Tabs are not accessibly via Left Arrow Right Arrow

### ISSUE THREAD

**Issue by constantincechina** [ng-bootstrap/ng-bootstrap#3327]
### Bug Description
Accordingly with [accessibility best practices](https://www.w3.org/TR/wai-aria-practices/#tabpanel) in regards to the Tabs - Keyboard Interactions
![image](https://user-images.githubusercontent.com/17467157/62827703-9e831e80-bba2-11e9-97d0-11998f6dc3bf.png)

### Solution
Implement listener for keydown.ArrowLeft and keydown.ArrowRight and perform the select operation to set the active tab. The activate automatically is a nice to have but not a must, hence we can have a flag exposed for it.

**Comment by maxokorokov** [comment]
We should implement this for the `NgbNav` directives

**Comment by maxokorokov** [comment]
Closed in #3612
