### ISSUE TITLE
Can't create dynamic TypeAhead well

### ISSUE THREAD

**Issue by xreign** [ng-bootstrap/ng-bootstrap#3328]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
I tried creating typeahead dynamically but when I used the 'tab' key to focus on a typeahead it pops all other typeahead.

### Link to minimally-working StackBlitz that reproduces the issue:

Here's the sample code https://stackoverflow.com/questions/57460910/how-to-dynamically-add-typeahead-in-ng-bootstrap-angular-7-8?

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.3.9

ng-bootstrap: 4.0.1

Bootstrap: 4.1.3

**Comment by benouat** [comment]
Thank you @xreign xreign for reporting a potential bug.

Nonetheless, according to our documentation [You think you've found a bug](
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug) could you please reproduce your scenario in a minimalist Stackblitz in order for us to start working on it ?

I know SB from our demos are still broken, but you could start from SB Angular scaffold, and then add ng-bootstrap@5.0.0

**Comment by benouat** [comment]
Hey @xreign 

Stackblitz is working again. So you could create one starting from one of the Typeahead demo.

**Comment by maxokorokov** [comment]
Closing as no feedback, please reopen if necessary.
