### ISSUE TITLE
Date picker is invalid by having '' as control value

### ISSUE THREAD

**Issue by MeMeMax** [ng-bootstrap/ng-bootstrap#3329]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
By passing '' (empty String) as value for the datepicker in a reactive form it is instantly marked as invalid. This causes ExpressionChangedAfterItHasBeenCheckedError in my dynamic forms.

The datepicker should accept '' as valid value.

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-rwtp85

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8

ng-bootstrap: 5

Bootstrap: 4

**Comment by jnizet** [comment]
Why shouldn't it be valid. An empty string is not a valid NgbDateStruct object. Why don't you just use `null` as the value of your form control?

https://stackblitz.com/edit/angular-tvdhqk?file=app/datepicker-popup.module.ts

**Comment by benouat** [comment]
Hey @MeMeMax thanks to report your issue,

but

I totally agree with @jnizet `''` is not a valid `NgbDateStruct` !
Please do use `null` as your default value, and meanwhile I will close as Invalid.
