### ISSUE TITLE
Dropdown does not conform to ARIA authoring practices

### ISSUE THREAD

**Issue by divyanshumehta** [ng-bootstrap/ng-bootstrap#3331]
TL;DR - Remove aria-haspop="true" from dropdown component

### Bug description:
Please follow the link to find the details of how the current Dropdown componet does not conform to ARIA practices. 
https://github.com/twbs/bootstrap/issues/28295

I think ng-bootsrap dropdowns should also be in line with this as it causes a great loss in accessibility.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 6.1.0

ng-bootstrap: 4.0.0

Bootstrap: 4.3.1

**Comment by divyanshumehta** [comment]
Hey @benouat can I go ahead and take up fix the issue?

**Comment by benouat** [comment]
Of course ! Please be our guest. Open a PR, we'll review it and merge it.

Contributions of any kind are always welcome!

**Comment by scavoola** [comment]
Just a note that I have the latest versions installed and am having trouble on the iPad and iPhone when using a dropdown that I have to hold the touch down on the dropdown-item for it to select the item. If I touch and release too quickly it does not fire the 'click'. I am wondering if it is related to this issue.
I will test after this PR has been released and raise an issue at that stage if I still have a problem.
thanks for the good work.

**Comment by divyanshumehta** [comment]
@scavoola No this issue does not seem to be related to your issue. Go ahead and open a new issue.

**Comment by scavoola** [comment]
ok thanks for the quick response divyanshumehta
