### ISSUE TITLE
Tooltip does not react on changes of `tooltipClass`

### ISSUE THREAD

**Issue by joergplewe** [ng-bootstrap/ng-bootstrap#3335]
### Bug description:

When changing `tooltipClass` programatically while tooltip is open, it does not reflect the change.

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-3azkna

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:
8.2.3

ng-bootstrap:
5.0.0

Bootstrap:
4

**Comment by joergplewe** [comment]
I found a workaround, doing a close()/open() in a setTimeout():

https://stackblitz.com/edit/angular-3azkna-rbbglf

```
  toggleError() {
    this.isError = !this.isError;
    setTimeout( () => {
      if ( this.tooltip.isOpen() ) {
        this.tooltip.close();
        this.tooltip.open();
      }
    }, 0);
  }
```

**Comment by peterblazejewicz** [comment]
@joergplewe
Covered by #3380
