### ISSUE TITLE
Cannot select the date on mouse click on ngbDatepicker when the container="body" is set

### ISSUE THREAD

**Issue by saiyaff** [ng-bootstrap/ng-bootstrap#3336]
### Bug description:
`<input type="text" ngbDatepicker container="body" (dateSelect)="onDateSelect($event)" />`
Setting the container to the body doesn't fire the dateSelect event when the date is selected over a mouseclick.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:
7.1.0
ng-bootstrap:
4.2.1

**Comment by peterblazejewicz** [comment]
Hey, it could be other problem like overlay preventing the event on the document body. Could you provide a basic demo of this?

**Comment by maxokorokov** [comment]
@saiyaff if you're still experiencing this issue, please provide a reproducible StackBlitz as stated in docs https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by maxokorokov** [comment]
Closing as no feedback
