### ISSUE TITLE
Pagination, pageChange not fired when directive [(page)] is changed

### ISSUE THREAD

**Issue by nmannaii** [ng-bootstrap/ng-bootstrap#3342]
when i change the [(page)] value from typescript the pageChange event won't fire. However the page is changed in the view.

**Comment by benouat** [comment]
Hey @nmannaii!
Could you be a bit more specific and detail what you mean by

> when i change the [(page)] value from typescript

**Comment by nmannaii** [comment]
I'll give you an example.
When i close a modal i want to go to the last page so i changed the [(page)] like this 
` this.lastPage = Math.round(data.totalUsers / this.elPerPage.value);`
And in the html i have the following:
`  <ngb-pagination  [(page)]="lastPage" [collectionSize]="totalUsers" [pageSize]="elPerPage.value" [size]="'sm'"
                      *ngIf="usersList.length > 0 && totalUsers/elPerPage.value > 1" (pageChange)="pageChange($event)">
      </ngb-pagination>`

**Comment by benouat** [comment]
@nmannaii Oh I see.
So unfortunately, our widget is not doing that on purpose.
We want to stay as close as possible to what exist in the _standard html_ world.

Let's. take as an example an `<input type="text">`
If you change programatically the value like `myInput.value = 'test'` *it won't emit* any of the standard `input` nor `change` event. Event handlers are only fired to react to user actions.

Thus, to come back to your problem, by the time you change the page to be set to the last one, you should also call manually whatever you are doing on `(pageChange)` output.

Is it clear for you ?

**Comment by nmannaii** [comment]
@benouat Loud and clear 😄, thank you for your explanation.
