### ISSUE TITLE
Bootstrap Modal

### ISSUE THREAD

**Issue by yakshit15** [ng-bootstrap/ng-bootstrap#3346]
I open the modal on click and manually change the URL.

Issue- Modal remains open

Expected behaviour - Modal should dismiss

**Comment by benouat** [comment]
Hey @yakshit15 

I am afraid this is something we don't handle at all, and that we won't handle anytime soon.
Our code has no dependancy to router at all. So any modal opened from our service will have to be closed one way or another.

Register yourself to be listening to router events, and manually close the modal.

Hence, I will close this issue, as `resolution: wontfix`.
