### ISSUE TITLE
NgbTabset not injected with @ViewChild

### ISSUE THREAD

**Issue by anbaran** [ng-bootstrap/ng-bootstrap#3356]
### Bug description:
I is not possible to inject NgbTabset into Angular compoment and thus select programatically active tab, see attached sample to reproduce the issue

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-7qzxrf?file=app%2Ftabset-selectbyid.ts

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:
8
ng-bootstrap:
5.11
Bootstrap:

**Comment by pkozlowski-opensource** [comment]
The problem in your stackblitz it the `{read: true}` option for the `ViewChild` query - `read` must point to an injectable token, putting `true` doesn't make sense... Here is a "fixed" example: https://stackblitz.com/edit/angular-7qzxrf?file=app%2Ftabset-selectbyid.ts

Note that selecting tab in the `ngAfterViewInit` is "too late" - the change dectection run already. 

In any case, neither of those issues is specific to ng-bootstrap but rather Angular usage so closing it here.
