### ISSUE TITLE
NgbToast `autohide` unused class name

### ISSUE THREAD

**Issue by peterblazejewicz** [ng-bootstrap/ng-bootstrap#3383]
In the metadata for NgbToast there is a declaration for the host binding for the `autohide` class:

```ts
 '[class.autohide]': 'autohide',
```
which seems to serve no purpose:
https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/toast/toast.ts#L44
It seems to be not a part of BS source code as well.

@benouat
Should this be removed?

Thanks!

**Comment by maxokorokov** [comment]
Doesn't look like `autohide` class is used anywhere in ng-bootstrap / bootstrap to me too.
