### ISSUE TITLE
Tooltip / popover: add support for the "container" @Input

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#339]
Ref.: http://v4-alpha.getbootstrap.com/components/popovers/#options

**Comment by wesleycho** [comment]
How would we approach this? Would we need a component ref to insert into and usage of the component resolver for a more restrictive version? We could require the user to pass the ref into the tooltip/popover for this feature.

**Comment by pkozlowski-opensource** [comment]
> Would we need a component ref to insert into and usage of the component resolver for a more restrictive version? 

Nope, since the target place could be outside of the bootstrapped ng2 app. The solution is to simply move DOM nodes to the target place. It is should be relatively  straightforward to implement.

**Comment by pkozlowski-opensource** [comment]
We've been supporting the `container` option for quite a while now, not sure while this one was left open :-/
