### ISSUE TITLE
ngbPopOver shake

### ISSUE THREAD

**Issue by softengi** [ng-bootstrap/ng-bootstrap#3407]
### Link to minimally-working StackBlitz that reproduces the issue: https://angular-v5nbkc.stackblitz.io
The reported behavior can also be seen here - https://gifyu.com/image/knIu

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 6.1.7

ng-bootstrap: 3.2.0

Bootstrap: 4.1.3

**Comment by fbasso** [comment]
Thanks for your issue @softengi, but I can't reproduce it with your stackblitz. More over, the stackblitz dependencies don't match the given ones.

Could you please re-check with the last version of angular, ng-bootstrap, ... ? A lot of works on positioning  has been done since the 3.2.

**Comment by softengi** [comment]
I guess I posted the wrong URL to stackblitz. I have updated the above stackblitz to the reported versions.
I was not able to reproduce the issue on the latest version. Also, the reported issue is random and is not reproducible consistently.
For my current project release, I would not be able to upgrade the angular version. Do you think the positioning work that has been done in the newer versions can be backported to the 3.X branch; or any particular fix that I can make locally to correct the reported issue?

**Comment by maxokorokov** [comment]
@softengi, thanks for reporting and creating a StackBlitz. Unfortunately there were too many changes to positioning logic since `3.x`, so wouldn't be able to backport. 

Please reopen if you're having issues with `5.x`. Cheers.
