### ISSUE TITLE
ngb-modal-backdrop did not cover all the the background in mobile view.

### ISSUE THREAD

**Issue by alwan93** [ng-bootstrap/ng-bootstrap#3408]
This thing happen to me when I was do the testing for my code. And I tried to fix the error. But I could not find it anywhere. So I decided to go to the Official angular bootstrap (modal) site and try to recreate my situation there. Unfortunately, the situation is same. 

### Bug description:
The backdrop did not cover all the background 

### To reproduce the issue:
1) Click the link below
https://ng-bootstrap.github.io/#/components/modal/examples
2) Inspect the page
3) Toggle device toolbar OR (Ctrl + Shift + M)
4) Choose iphone 6/7/8 at the dropdown.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8

ng-bootstrap: 5.1.0

Bootstrap: 4.3.1
![report bugs](https://user-images.githubusercontent.com/14266397/66622077-f7117f00-ec18-11e9-95a0-a7d34dc8642c.PNG)

**Comment by benouat** [comment]
Hey @alwan93 
Thanks for reporting the issue!

FYI the fact you can reproduce it on the demo website is **purely** related to a CSS layout issue.
The header `<h2>` used for each demo title, containing both buttons for `Code` and `StackBlitz` is missing a `flex-wrap: wrap` that would make the buttons go below.

I will fix the demo website, but on your side I would suggest that you look up for any layout issue as well.
The backdrop is _stupidly_ positioned as `position: fixed`. There is not that much we could do to it.

---
I'll wait a few days for any feedback from your side, and eventually close that issue after that.

**Comment by benouat** [comment]
Closing as no feedback

**Comment by kevin4dhd** [comment]
the same error

**Comment by EmiAguero1997** [comment]
Hello guys, i just find out the solution for this problem.

Results that ngb modal lets you use a custom backdrop class
<img width="597" alt="Screenshot 2022-10-21 122430" src="https://user-images.githubusercontent.com/84792585/197232286-7157cdb8-d670-4a9c-b839-c5d0c86d1f5b.png">

So it means that you can use width:100% and height:100% in your custom backdrop class, this fixes the problem (u have to set a background-color)
<img width="571" alt="Screenshot 2022-10-21 122505" src="https://user-images.githubusercontent.com/84792585/197232838-49e06631-df33-4235-9df7-38e529bb701d.png">

This is my custom backdrop class:
`.backdropCustom{
        background-color: rgb(79, 79, 79);
        width: 100%;
        height: 100%;
    }`

And this is how i open the modal:

`this.modalService.open(this.loginModal,{backdropClass:'backdropCustom', centered:true});`

This is the final result:

<img width="551" alt="Screenshot 2022-10-21 123123" src="https://user-images.githubusercontent.com/84792585/197233341-58b1948a-bde8-457d-9b23-5c00e6f82001.png">
