### ISSUE TITLE
Modal opened by extension events doesn't contain classes

### ISSUE THREAD

**Issue by Jeroen96** [ng-bootstrap/ng-bootstrap#3414]
### Bug description:
When listening for events from a chrome extension to open the modal, the classes are not applied correctly. This can be seen in the images down below. Opening the modal via a button click works fine but automatically opening one when the event fires does not.

The modal is displayed but is smeared across your screen. The classes get applied when you click on a button or hover over an item that has a tooltip.

Using [ApplicationRef.tick()](https://angular.io/api/core/ApplicationRef#tick) resolves it.

![modal_1](https://user-images.githubusercontent.com/10827065/66921460-8d80de80-f025-11e9-8151-fee58beccc9a.png)
![modal_2](https://user-images.githubusercontent.com/10827065/66921472-91146580-f025-11e9-9eb5-2aab3d3bf883.png)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.0

ng-bootstrap: 5.1.1

Bootstrap: 4.3.1

**Comment by peterblazejewicz** [comment]
> When listening for events from a chrome extension to open the modal, the classes are not applied correctly.

Can you expand on this? What's the code that triggers modal?
Thanks!

**Comment by Jeroen96** [comment]
The extension in question is [MetaMask](https://metamask.github.io/metamask-docs/API_Reference/Ethereum_Provider#ethereum.on(eventname%2C-callback))

The following code sits inside a Service (omitted unrelevant parts)

```typescript

constructor(private modalService: NgbModal, private appRef: ApplicationRef) {}

async init(){
    const metaMaskEthObject = window['ethereum'];
    metaMaskEthObject.on('accountsChanged', this.accountChange.bind(this));
    metaMaskEthObject.on('networkChanged', this.nwChange.bind(this));
}


nwChange(result) {
    this.$onNetwork.next(result);
    const provider = localStorage.getItem(this.WEB3_PROVIDER);
    if (provider === 'METAMASK' || provider === null) {
      if (result === this.requiredNetwork) {
        this.closeModal();
      } else {
        this.openModal('Wrong network is selected', true);
        // Currently resolves it by forcing a redraw of the component tree
        this.appRef.tick();
      }
    }
  }

openModal(message: string, locked: boolean) {
    const options: NgbModalOptions = {
      backdrop: 'static',
      size: 'lg',
      keyboard: true
    };
    if (locked) {
      options.keyboard = false;
    }
    if (!this.modalService.hasOpenModals()) {
      this.modalRef = this.modalService.open(MetamaskModalComponent, options);
    }
    this.modalRef.componentInstance.message = message;
    this.modalRef.componentInstance.locked = locked;
  }
```

**Comment by maxokorokov** [comment]
@Jeroen96 could you try opening the popup inside the Angular zone?
Looks like your `etherium` thing is running outside Angular.

Something like:

```ts
constructor(private modalService: NgbModal, private zone: NgZone) {}

  openModal(content) {
    this.zone.run(() => {
      this.modalService.open(content);
    });
  }
```

**Comment by Jeroen96** [comment]
@maxokorokov this seems to properly open and apply the classes to the modal. It however doesn't properly update the modal itself. The message doesn't appear inside the modal until i click on the modal. I can resolve this by adding ChangeDetectorRef.detectChanges() to the modal component.
```typescript
if (!this.modalService.hasOpenModals()) {
      this.zone.run(() => {
        this.modalRef = this.modalService.open(MetamaskModalComponent, options);
      });
    }
    this.modalRef.componentInstance.message = message;
    this.modalRef.componentInstance.locked = locked;
    this.modalRef.componentInstance.cdref.detectChanges();
```

**Comment by maxokorokov** [comment]
@Jeroen96, this has nothing with ng-bootstrap, but with the way Angular works. Looks like any code you execute in `nwChange` is not triggering change detection, because it is running outside of the zone.

I think better doing something along these lines should work:

```ts
metaMaskEthObject.on('networkChanged', () => this.zone.run(this.nwChange));
```

Or you have to manually trigger change detection with  `appRef.tick()` or `cdref.detectChanges()`.

Please refer to Angular docs for more details, ex. 
- https://angular.io/api/core/NgZone
- https://stackoverflow.com/questions/46284490/angular-change-detection-for-updates-within-a-callback/46286400#46286400

Anyway, it doesn't look to me that the issue is on ng-bootstrap side, but the way you work with external libraries with Angular.
