### ISSUE TITLE
ngb-modal-dialog dismiss should dismiss on esc press by default case fails after #3384

### ISSUE THREAD

**Issue by peterblazejewicz** [ng-bootstrap/ng-bootstrap#3415]
Not sure if that is related to updated OS (Mac OS Catalina), but the case for `ngb-modal-dialog` ESC press started to fails in most recent version, probably due to some timing problems. The change was added with #3384

Thanks!

### Bug description:

Run tests, e.g. `yarn ngb:tdd`
The case fails with timeout (test is asynchronous one):

```text
TOTAL: 1 FAILED, 1276 SUCCESS
Chrome 79.0.3941 (Mac OS X 10.15.0) ngb-modal-dialog dismiss should dismiss on esc press by default FAILED
	Error: Timeout - Async callback was not invoked within 2000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
	    at <Jasmine>
```

### Link to minimally-working StackBlitz that reproduces the issue:
n/a

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.4

ng-bootstrap: 5.1.1

Bootstrap: n/a

OS: Mac OS 10.15/ Chrome 79.0.3941.4

**Comment by maxokorokov** [comment]
I've seen it once on my machine as well (High Sierra), looks like it's a bit flaky :/
Anyway the idea was to test focus and keyboard support using e2e.

I'll have to cleanup unit tests, I think we have many use-cases covered.

Ex. closing on ESC

https://github.com/ng-bootstrap/ng-bootstrap/blob/2cf28f4fb4ab7f1ff04e64baf155c8f9de775a04/e2e-app/src/app/modal/focus/modal-focus.e2e-spec.ts#L17-L26
