### ISSUE TITLE
Unable to use scrollbar through keyboard up/down keys on Modal.

### ISSUE THREAD

**Issue by ShubhenduVaid** [ng-bootstrap/ng-bootstrap#3416]
### Bug description:
Unable to use scrollbar through keyboard up/down keys.

### Link to minimally-working StackBlitz that reproduces the issue:

https://ry5gky.run.stackblitz.io
Click on Modal scrollable Button

Could also be replicated at: 
https://ng-bootstrap.github.io/#/components/modal/examples#options
Click on Modal scrollable content Button

**Comment by fbasso** [comment]
Thanks for your report @ShubhenduVaid , but your stackblitz doesn't seem to work. If I use the url https://stackblitz.com/edit/angular-ry5gky, I have a 'page not found' response.

Could you please check it ?

**Comment by ShubhenduVaid** [comment]
> Thanks for your report @ShubhenduVaid , but your stackblitz doesn't seem to work. If I use the url https://stackblitz.com/edit/angular-ry5gky, I have a 'page not found' response.
> 
> Could you please check it ?

edited my question.

**Comment by fbasso** [comment]
Not sure again if I understand what's the issue (and if there is one in fact).

On the demo site, when I click on 'Modal scrollable content', the modal open and the close icon is focus. From here, I can't scroll the body, which is normal as the body is not focused. 

When I tab, the modal body is focused and the up/down arrows behave in the normal way.

Is it not what you expect ?

**Comment by ShubhenduVaid** [comment]
> Not sure again if I understand what's the issue (and if there is one in fact).
> 
> On the demo site, when I click on 'Modal scrollable content', the modal open and the close icon is focus. From here, I can't scroll the body, which is normal as the body is not focused.
> 
> When I tab, the modal body is focused and the up/down arrows behave in the normal way.
> 
> Is it not what you expect ?

Steps:
1) Focus Modal body.
2) Then when I long press, on keyboard arrow up/down keys, the scroll does not move.

**Comment by fbasso** [comment]
Hum... ok, I understand your point now. On my side I used only the keyboard, so the body container was focused first and the up/down arrows work in this case.

When we click inside the body, the focused element is not the modal-body, but the ngb-modal-window.

For information, bootstrap behaves the same (https://getbootstrap.com/docs/4.3/components/modal/) with Firefox, but is even worse with Chrome (not possible to focus the modal-body at all, so the arrows don't work).

**Comment by maxokorokov** [comment]
StackBlitz is still not working for me.

It's not magical and only focusable elements can be scrolled with the keyboard, so you should make your content focusable by adding `tabindex`.

Ex. https://stackblitz.com/edit/angular-sch21s?file=app%2Fmodal-options.ts

Current behaviour matches the bootstrap one from here: https://getbootstrap.com/docs/4.3/components/modal/#scrolling-long-content

**Comment by ShubhenduVaid** [comment]
> StackBlitz is still not working for me.
> 
> It's not magical and only focusable elements can be scrolled with the keyboard, so you should make your content focusable by adding `tabindex`.
> 
> Ex. https://stackblitz.com/edit/angular-sch21s?file=app%2Fmodal-options.ts
> 
> * default scroll works just fine - nothing to do
> * scrollable content scrolls when focused
> 
> Current behaviour matches the bootstrap one from here: https://getbootstrap.com/docs/4.3/components/modal/#scrolling-long-content
> 
> So I don't think we have anything to fix here

@maxokorokov Thanks for the update. That solves my issue.
