### ISSUE TITLE
ngbootstrap datepicker format display issue

### ISSUE THREAD

**Issue by cyrusgiri69** [ng-bootstrap/ng-bootstrap#3417]
Hi

In NgBootstrap datepicker we have same format as well to parse it NgbDateParserFormatter but how to display the format "mm/yyyy' (month and year alone) inside the datepicker input. there is no option to display that format alone inside the datepicker.

**Comment by maxokorokov** [comment]
@cyrusgiri69 check the default implementation and look at custom ISO one we have: 

https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/datepicker/ngb-date-parser-formatter.ts#L43-L64

We should probably add the formatter demo though.

**Comment by cyrusgiri69** [comment]
yeah @maxokorokov  would be more useful if there is a demo. i'll try to resolve format with this
