### ISSUE TITLE
Positioning placementVals.find(), never return null 

### ISSUE THREAD

**Issue by KrakenTyio** [ng-bootstrap/ng-bootstrap#3418]
Hi

This line is buggy, bc. `find` never return `null` value.

Its return `undefined` or `value<T>` of `T[]` array

https://github.com/ng-bootstrap/ng-bootstrap/blob/2cf28f4fb4ab7f1ff04e64baf155c8f9de775a04/src/util/positioning.ts#L210

I suggest replace this line with
```ts
if (!placementVals.find(val => val.search('^' + obj) !== -1)) {
```

**Comment by maxokorokov** [comment]
@KrakenTyio please do, however I don't see any big issues here. It's quite common to check `== null` for both `undefined` and `null`

![Screen Shot 2019-10-18 at 09 44 04](https://user-images.githubusercontent.com/8074436/67075634-d9e62e80-f18b-11e9-8d3a-7be730020929.png)

So, will close this unless you're motivated to open a PR.

---

On a side note I think the whole `auto` replacement could be simplified to be more readable.

**Comment by KrakenTyio** [comment]
Yes thats true, but for TSlint -> tripple-equals, its not so strict

Can be closed
