### ISSUE TITLE
DatePicker: dynamically updating [maxDate] doesn't get applied immediately.

### ISSUE THREAD

**Issue by dsuwirya** [ng-bootstrap/ng-bootstrap#3438]
Hello,

I'm trying to put a limit on date range selection to max 30 days from the [fromDate] by dynamically recalculating and updating [maxDate] each time user changing the [fromDate]. It doesn't seem the update to [maxDate] gets applied immediately. But only get applied if first I close the popup, and reopen the popup.

Thanks.

**Comment by maxokorokov** [comment]
@dsuwirya oops, missed this one. Could you please provide a StackBlitz, please?

---

Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz

**Comment by stevethemacguy** [comment]
I'm having a similar change detection issue with datepicker when building with IVY. I will submit a minimal repo on Monday, but here's the issue. If I dynamically add a class to a custom dayTemplate, the class is not added in the HTML until I trigger change detection on the datepicker in some other way (e.g. by hovering over the calendar).

**Comment by maxokorokov** [comment]
I think #3507 should have fixed this issue.
Please reopen if necessary and you have the StackBlitz
