### ISSUE TITLE
Component tab change is recreated

### ISSUE THREAD

**Issue by elvispdosreis** [ng-bootstrap/ng-bootstrap#3441]
I have an unwanted behavior, when I switch between tabs my component and recreated, disappoints the ngOnInit event

[demos](https://stackblitz.com/edit/angular-reactive-forms-d549c9)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.3

ng-bootstrap: 5.1.2

Bootstrap: 4.3.1

**Comment by benouat** [comment]
Hey @elvispdosreis 

I think you are looking for `destroyOnHide` input for the `<ngb-tabset>`. It is documented [here](https://ng-bootstrap.github.io/#/components/tabset/api#NgbTabset).
