### ISSUE TITLE
NgbCalendarIslamicUmalqura's getToday() returns one day after the original date

### ISSUE THREAD

**Issue by CoachMorta** [ng-bootstrap/ng-bootstrap#3442]
NgbCalendarIslamicUmalqura's getToday() returns one day after the original date

everything was working fine ,until today my Hijri Calendar returns one day after the original date
what can i do please ?

import {
  NgbDateStruct,
  NgbCalendar,
  NgbCalendarIslamicUmalqura,
  NgbDatepickerI18n
} from "@ng-bootstrap/ng-bootstrap";
const WEEKDAYS = ["ن", "ث", "ر", "خ", "ج", "س", "ح"];
const MONTHS = [
  "محرم",
  "صفر",
  "ربيع الأول",
  "ربيع الآخر",
  "جمادى الأولى",
  "جمادى الآخرة",
  "رجب",
  "شعبان",
  "رمضان",
  "شوال",
  "ذو القعدة",
  "ذو الحجة"
];
@Injectable()
export class IslamicI18n extends NgbDatepickerI18n {
  getWeekdayShortName(weekday: number) {
    return WEEKDAYS[weekday - 1];
  }
  getMonthShortName(month: number) {
    return MONTHS[month - 1];
  }
  getMonthFullName(month: number) {
    return MONTHS[month - 1];
  }
  // getDayAriaLabel(date: NgbDateStruct): string {
  //   return ${date.day}-${date.month}-${date.year};
  // }

  getDayAriaLabel(date: NgbDateStruct): string {
    return (
      date.day.toString() +
      "/" +
      date.month.toString() +
      "/" +
      date.year.toString()
    );
  }
}

// class HijrahDate {
//   constructor(date1: Date) {}
// }

@Component({
  selector: "app-burial-request",
  templateUrl: "./burial-request.page.html",
  styleUrls: ["./burial-request.page.scss"],
  providers: [
    { provide: NgbCalendar, useClass: NgbCalendarIslamicUmalqura },
    { provide: NgbDatepickerI18n, useClass: IslamicI18n }
  ]
})

**Comment by benouat** [comment]
Hey @CoachMorta 

Would you mind following the ISSUE template we are using, with proper information regarding your usage, trying to use code block for your code snippet ?

Also, this issue has already been opened #3237 a few months back, and had been fixed in [5.1.0](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#510-2019-07-17)
Does it correspond to the version you are using ?

**Comment by maxokorokov** [comment]
Closing as no feedback, please reopen if necessary
