### ISSUE TITLE
Bad scrollbar replacement on non-integer width windows

### ISSUE THREAD

**Issue by kremerd** [ng-bootstrap/ng-bootstrap#3448]
### Bug description:

When a modal is shown on a scrollable page, the scrollbar is hidden and the page body is padded to compensate for the lost width. Currently the decision, _whether_ padding should be applied for that reason, is sometimes taken incorrectly if the browser window has a non-integer width. In an extreme case this can lead to the same padding being applied over and over again (cf. StackBlitz).

Non-integer widths occur when zooming in on the page with the browser, or when scaling your display in system settings like [these in Windows](https://www.windowscentral.com/how-set-custom-display-scaling-setting-windows-10).

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/ngb-scrollbar-handling

Please make sure to follow the instructions on screen.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.13

ng-bootstrap: 5.1.2

Bootstrap: 4.3.1

### Resolution sketch:

Some rounding needs to be applied to [util/scrollbar.ts](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/util/scrollbar.ts#L53).

**Comment by maxokorokov** [comment]
@kremerd thanks for the StackBlitz
Can't reproduce on macOS in any of the browsers.
Can reproduce on Win 10 at least in Chrome.

**Comment by kremerd** [comment]
@maxokorokov Thanks for the confirmation. I only tested on Windows 10, but was able to reproduce the issue with Firefox, Chrome, Edge and Internet Explorer 11.

New finding: The same behavior also occurs with the default Bootstrap code (and for the same reason). I opened a ticket there as well.
