### ISSUE TITLE
Table data in modals ignore width of modal and run off the page

### ISSUE THREAD

**Issue by ar613** [ng-bootstrap/ng-bootstrap#3449]
### Bug description:
If I put a table in a modal with really long continuous text, it ignores the width of the modal and runs off the screen. It appears to not be aware of the width of the modal and thinks it's being created on the background page.

### Link to minimally-working StackBlitz that reproduces the issue:
Just launch the modal:
https://stackblitz.com/edit/angular-kpletn?embed=1&file=app/modal-options.html

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.13

ng-bootstrap: 5.1.2

Bootstrap: 4.3.1

**Comment by maxokorokov** [comment]
This has nothing to do with ng-bootstrap as bootstrap behaves exactly the same way:

![Screen Shot 2019-11-07 at 10 19 06](https://user-images.githubusercontent.com/8074436/68376008-20ee9080-0148-11ea-819f-3349020e22e9.png)

**Comment by ar613** [comment]
Ok, let's see what they say: https://github.com/ng-bootstrap/ng-bootstrap/issues/3449

**Comment by ar613** [comment]
In case anyone else has this problem, the solution proposed in the bootstrap issue is to use class text-break in the td elements to force line breaks in long strings, or use class table-responsive on the table to force a horizontal scrollbar if the content exceeds the width of the modal. Tested both in ng-bootstrap and both work.
