### ISSUE TITLE
Dropdown changed position to right, after scroll to top

### ISSUE THREAD

**Issue by martamoshkin** [ng-bootstrap/ng-bootstrap#3453]
### Bug description:
Dropdown changed position to right, after scroll to top.

Example:
![issue](https://user-images.githubusercontent.com/1945239/68365706-7758d080-0142-11ea-9bd3-7c547b23437d.gif)

```<div class="row">
  <div class="col text-right">
    <div ngbDropdown  class="d-inline-block">
      <button class="btn btn-outline-primary" id="dropdownBasic2" ngbDropdownToggle>Toggle dropup</button>
      <div ngbDropdownMenu aria-labelledby="dropdownBasic2">
        <button class="dropdown-item">Action - 1</button>
        <button class="dropdown-item">Another Action</button>
        <button class="dropdown-item">Something else is here</button>
      </div>
    </div>
  </div>
</div>
```

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.6
ng-bootstrap: 5.1.2
Bootstrap: 4.3.1

**Comment by maxokorokov** [comment]
@martamoshkin If you believe that we've got a bug in this library than please [provide a minimal reproduce scenario in a stackblitz](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug)

Changing the demo in question doesn't give me this result.

**Comment by benouat** [comment]
Closing as no update regarding a reproducible scenario via Stackblitz
