### ISSUE TITLE
How to enable disabled ngtab in angular's ts file..

### ISSUE THREAD

**Issue by HamsalekhaHR** [ng-bootstrap/ng-bootstrap#3456]
Please let me know how to enable disabled ngtab in .ts file of angular 7

**Comment by maxokorokov** [comment]
Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a minimal reproduction scenario in a StackBlitz
