### ISSUE TITLE
Datepicker's month and year drops up in Internet Explorer 11

### ISSUE THREAD

**Issue by aartsisheuskaya** [ng-bootstrap/ng-bootstrap#3463]
### Bug description:
When selecting NgbDatepicker's month or year it drops up in IE 11 instead of droping down as in other browsers.
![image](https://user-images.githubusercontent.com/57715884/68770433-2f9ce200-0637-11ea-894e-9231b2d02ac0.png)

### Link to minimally-working example that reproduces the issue:
Official site
https://ng-bootstrap.github.io/#/components/datepicker/examples

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.13

ng-bootstrap: 5.1.4

Bootstrap: 4.3.1

**Comment by maxokorokov** [comment]
Hey, @aartsisheuskaya!

Month and year are native `<select>` elements and styled by each browser differently. There is nothing we can do here in particular for IE 11 - it just displays any select element this way.

There **might** be some CSS hack specific to IE 11, but we won't change this on the ng-bootstrap side anyway.
