### ISSUE TITLE
New version is not compatible with noImplicitAny

### ISSUE THREAD

**Issue by nseni** [ng-bootstrap/ng-bootstrap#3464]
To reproduce:
1. Open https://stackblitz.com/edit/angular-qcxzee
2. Download Project
3. Do `npm install`
4. Do `ng build`. No errors ✔️ 
5. Edit `tsconfig.json`: add `"noImplicitAny": true,` to `compilerOptions`
6. Do `ng build`. Build fails ❌ 

Error:
```
ERROR in src/app/modal-component.ts(39,11): error TS7022: 'modalRef' implicitly
has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
```

7. Downgrade ng-bootstrap: `npm i @ng-bootstrap/ng-bootstrap@5.1.1`
8. Do `ng build`. No errors ✔️ 

The error is caused by this code:
```ts
const modalRef = this.modalService.open(NgbdModalContent, {
  beforeDismiss: () => modalRef.componentInstance.canDismiss(),
});
```

Which was originally inspired by https://github.com/ng-bootstrap/ng-bootstrap/issues/2904#issuecomment-452702708

**Comment by maxokorokov** [comment]
@nseni I guess the workaround for you should be... adding a type :)

I think this works for me:
```ts
const modalRef: NgbModalRef<typeof NgbdModalContent>
```

But we broke it in a minor `5.1.2` release, so I'll rollback the change in `5.1.5`.

**Comment by laserus** [comment]
Oh, no. You broke my type usage, now I cannot upgrade, it says `NgbModalRef` is not generic....
