### ISSUE TITLE
NgbRating - disabled state is broken in Template-driven forms

### ISSUE THREAD

**Issue by nseni** [ng-bootstrap/ng-bootstrap#3465]
### Bug description:
Use NgModel and set "disabled" attribute on ngb-rating. Rating will not be shown.
Moreover, click on the disabled ngb-rating, and bound value will be set to 0.

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-xwcmmq?file=app/rating-basic.html

### Versions of Angular, ng-bootstrap and Bootstrap:
Angular: 8.2.4
ng-bootstrap: 5.1.4

**Comment by maxokorokov** [comment]
@nseni, yikes, indeed. Disabled handling is completely broken with template-driven forms

Main reason:
- `writeValue` is called after `setDisabledState`
- in `writeValue` we call `update()` and for some reason check that the component is not disabled → https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/rating/rating.ts#L198

Need to: 
- [ ] add tests for template-driven forms (now we have only for reactive)
- [ ] ignore disabled state when writing value

**Comment by giaggianese** [comment]
Same issue income using reactive form.
