### ISSUE TITLE
possible issue with ngModel

### ISSUE THREAD

**Issue by jbiddulph** [ng-bootstrap/ng-bootstrap#3466]
Hi, I don't know if this is me or an actual issue but I am using the ngbootstrap datepicker 

When I try and add a minDate and maxDate this breaks my two way data binding: 

`<input type="text"
                                                           (click)="d.toggle()"
                                                           [minDate]="minDate"
                                                           [maxDate]="maxDate"
                                                           #dob="ngModel"
                                                           class="form-control"
                                                           name="dateOfBirth"
                                                           [class.is-invalid]="dob.invalid && dob.touched"
                                                           [(ngModel)]="userModel.dateOfBirth"
                                                           ngbDatepicker
                                                           #d="ngbDatepicker"
                                                           required>`

**Comment by peterblazejewicz** [comment]
@jbiddulph 
could you make the `stackblitz` demonstrating the problem? I've tried to repeat using documentation sample for no avail.

**Comment by maxokorokov** [comment]
@jbiddulph please do as @peterblazejewicz suggests.

Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a minimal reproduce scenario in a StackBlitz

**Comment by benouat** [comment]
Closing as no update regarding a reproducible scenario via Stackblitz
