### ISSUE TITLE
NgbTab display none option 

### ISSUE THREAD

**Issue by Anj21** [ng-bootstrap/ng-bootstrap#3467]
Please add NgbTab display or hidden property to hide the tab from menu. If we use *ngIf for this, then it cause several problems in the functionaltiy, Since *ngIf is a structural directive the tab is removed from DOM when set to 'false'. This means it's state is also deleted and this is a problem when the tab becomes visible again.

when i try to add the display none style using ngstyle ([ngStyle]="{'display': isDevModeFlag ? 'none' : 'block'}") property, then also it is now working, so if we are not able to add new feature then please provide support for ngStyle property.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.11

ng-bootstrap: 4.0.0

Bootstrap: 4.3.1

**Comment by PerezArmando** [comment]
I would like to work on this bug, in case the community agrees that this is a required feature. Could anybody assign it to me? Thanks.

**Comment by benouat** [comment]
Hello folks!

`ngb-tabset` is being [deprecated](https://ng-bootstrap.github.io/#/components/tabset/examples) in favour of a new set of directives -> `ngbNav`

Have a look at the [documentation](https://ng-bootstrap.github.io/#/components/nav/overview), you should totally be able to migrate to the new widget and implement your thing in your side.

I'll let you close the issue if it's working for you.

**Comment by maxokorokov** [comment]
Since version `5.2.0` there is a new `NgbNav` set of directives that fix this issue. `NgbNav` is meant to replace the `NgbTabset` component (completely deprecated in version `6.0.0`) as a more flexible alternative.

I suggest you migrate to it → https://ng-bootstrap.github.io/#/components/nav/overview
