### ISSUE TITLE
Issue when using ngbpopover with ngbtooltip

### ISSUE THREAD

**Issue by dhavalsolanki** [ng-bootstrap/ng-bootstrap#3472]
Hello,

On  a button when i am using ngbtool tip on hover and ngbPopover on click functionality ngb tooltip is not working

**Comment by maxokorokov** [comment]
Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz

**Comment by benouat** [comment]
Closing as inactivity and no update regarding a reproducible scenario via Stackblitz.
