### ISSUE TITLE
Ngb-Carousel showNavigationIndicators problem on div

### ISSUE THREAD

**Issue by jtan80813** [ng-bootstrap/ng-bootstrap#3486]
Angular: 8.0.3

ng-bootstrap: 5.1.1

Bootstrap: 4.3.1

i have added [showNavigationArrows]="showNavigationArrows & [showNavigationIndicators]="showNavigationIndicators" on the div to determine if the content's length is greater than 1 to show the indicators, if its less than or equal to 1 then don't show the indicators. The problem is when i put it on the div, its getting undefined. It should be put inside the <ngb-carousel>. If i put it inside the <ngb-carousel> then how can i determine the length of the content to show the indicators?

```
<ngb-carousel>
    <ng-template ngbSlide *ngFor="let content of post.contents">
        <div [showNavigationArrows]="showNavigationArrows" [showNavigationIndicators]="showNavigationIndicators">
            <img [src]="getImageUrl(content.content)" />
        </div>
    </ng-template>
</ngb-carousel>
```

**Comment by pkozlowski-opensource** [comment]
@jtan80813 it is not clear to me, from the provided description, as what you are trying to achieve here.. But one thing to notice is that both `showNavigationArrows` and `showNavigationIndicators` are `@Input()`s of the `ngbCarousel` directive and you _must_ put them on the `<ngb-carousel>` element - otherwise they will have no effect.

Could you please try to explain again what you are trying to achieve?

**Comment by jtan80813** [comment]
Hi @pkozlowski-opensource. Here i created a stackblitz . [CLICK THIS](https://stackblitz.com/edit/angular-szabzp?file=app%2Fcarousel-basic.ts)       

The post#2 has only one image. So how can i remove the showNavigationIndicators since its only one image?

**Comment by pkozlowski-opensource** [comment]
How about `<ngb-carousel [showNavigationArrows]="post.contents.length > 1" [showNavigationIndicators]="post.contents.length > 1">`? https://stackblitz.com/edit/angular-szabzp-u1ar1b?file=app/carousel-basic.html

In the future please use support channels for those types of questions: https://github.com/ng-bootstrap/ng-bootstrap#getting-help

**Comment by jtan80813** [comment]
@pkozlowski-opensource  Ok. Thank you
