### ISSUE TITLE
custom-sized modal

### ISSUE THREAD

**Issue by canbax** [ng-bootstrap/ng-bootstrap#3487]
### Feature request

Can I make a custom-sized modal. Why there are only 3 options (sm, md, lg) ?

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.13

ng-bootstrap:5.1.2

Bootstrap:4.3.1

**Comment by msqaddura** [comment]
@canbax  the library complies with Bootstrap's components. These are the allowed sizes in bootstrap
[https://getbootstrap.com/docs/4.3/components/modal/#optional-sizes](https://getbootstrap.com/docs/4.3/components/modal/#optional-sizes)

As per your case, you could use these options:
https://ng-bootstrap.github.io/#/components/modal/api#NgbModalOptions
and pass the `windowClass` for example and modify the modal the way you want



As per why in bootstrap:4 they dont have option to full screen, I know not.

**Comment by canbax** [comment]
Thank you.

ps: without `encapsulation: ViewEncapsulation.None,` added inside `@Component({ })` `windowClass` is not working
