### ISSUE TITLE
Problem Playing Video on NG-Boostrap Carousel

### ISSUE THREAD

**Issue by jtan80813** [ng-bootstrap/ng-bootstrap#3488]
Angular: 8.0.3

ng-bootstrap: 5.1.1

Bootstrap: 4.3.1

I need help in playing the video in the ng-bootstrap carousel. I have an image and a video in my post # 1. How do i play the video?  BTW, in the stackblitz, the video doesn't show up but in my local machine, it shows up.

BUT MY PROBLEM is i can't click the play/pause/control button of the video. It needs to be click on the center.  How do you fix this since i have a several videos and images on the same carousel? The images is ok BUT the videos are not since maybe it was overlap by the "navigationArrows" of the carousel so the play  button should be click on the center. What would be the solution to this? Thanks

Here's the stackblitz link
[**CLICK HERE**](https://stackblitz.com/edit/ng-bootstrap-indicators?file=app%2Fcarousel-basic.ts)

**Comment by msqaddura** [comment]
The problem is the styling 
```
		ngb-carousel .picsum-img-wrapper {
			position: relative;
			height: 0;
			padding-top: 55%;
			/* Keep ratio for 900x500 images */
		}
```
This has the height:0 which is causing them to not show

**Comment by jtan80813** [comment]
@msqaddura. Yes you got it. The picture you posted is my problem. So how would you fix this?

**Comment by msqaddura** [comment]
@jtan80813 
In order to edit the carousel first you need to change your component's encapsulation to None, as well ass add a css file to override the arrows;
```
import { Component } from "@angular/core";
import { ViewEncapsulation } from '@angular/core';

@Component({
  selector: "ngbd-carousel-basic",
  templateUrl: "./carousel-basic.html",
  styleUrls:["./carousel.css"], //added css file for you
  encapsulation: ViewEncapsulation.None, //to be able to use css file 
})
```

then in your css file you could do 
```
.carousel-control-prev { //bootstrap class name for prev arrow
  margin-bottom:75px; // i think this is default height of controls in html native
}
```

**Comment by jtan80813** [comment]
@msqaddura. Thank you.
