### ISSUE TITLE
Bootstrap 4.4 update with E2E tests

### ISSUE THREAD

**Issue by peterblazejewicz** [ng-bootstrap/ng-bootstrap#3504]
There is upgrade in the BS core:

https://blog.getbootstrap.com/2019/11/26/bootstrap-4-4-0/
https://blog.getbootstrap.com/2019/11/28/bootstrap-4-4-1/

When setup within the project the integration tests run with `yarn e2e` fail (Chrome/Mac OS) with errors:

```text
Datepicker Autoclose displayMonths = 1 should work when autoClose === true
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
....
✗ should work when autoClose === true
        - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```

To be investigated

Version:
5.1.4

**Comment by benouat** [comment]
@peterblazejewicz quick ping! Did you manage to investigate ?

**Comment by benouat** [comment]
@peterblazejewicz any news ?

**Comment by maxokorokov** [comment]
Seems like a fluke to me, works fine on my machine with `4.4.1`, will close and reopen if resurfaces
