### ISSUE TITLE
ngb-timepicker change width and height

### ISSUE THREAD

**Issue by saravanacs** [ng-bootstrap/ng-bootstrap#3512]
I use ngb-timepicker in my project. I need size of the timepicker is showing small size. I use size="small" attribute. But, i need very small size. My code here,

html,
<ngb-timepicker class="changeSize"  formControlName="ManufacturedTime" size="small"  (ngModelChange)="onTimeChange(element,$event)"    [meridian]="meridian" ></ngb-timepicker>

css,
.changeSize {
height: 10px !important;
padding: 2px !important;
font-size: 10px;
}
![image](https://user-images.githubusercontent.com/43574327/70517635-def9a580-1b5e-11ea-9f08-3fc6c53baf0f.png)

But, does not affect any css in this timepicker. Please anyone help me

**Comment by masoudDaliriyan** [comment]
use the following CSS to customize time picker 
for more customizing, find a class with inspect element and follow the following pattern 

```
ngb-timepicker.changeSize .ngb-tp-input-container {
  width: 2em;
}
ngb-timepicker.changeSize .ngb-tp-input{
  padding: 0;
  font-size: 10px;
}
```

**Comment by maxokorokov** [comment]
Looks like it was answered to me, but nevertheless:

Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz
