### ISSUE TITLE
Modal on Edge browser has strange line appear

### ISSUE THREAD

**Issue by xenogew** [ng-bootstrap/ng-bootstrap#3516]
### Bug description:
Please take a look at attached image, I capture it from official website demo page with Edge browser. And found it display with strange line on the middle of dialog, near border of button or other controller stuff when mouse over.
![2019-12-16](https://user-images.githubusercontent.com/756484/70881445-ed890680-200f-11ea-993e-4051c2ed6745.png)
![2019-12-16 (1)](https://user-images.githubusercontent.com/756484/70881448-f083f700-200f-11ea-8e5a-f80989ba6af2.png)

I tried to google for the issue, and found this one issue on Github [https://github.com/twbs/bootstrap/issues/22489](https://github.com/twbs/bootstrap/issues/22489#issuecomment-491470725) that has workaround by change the style as comment mentioned.

```
.modal-content { background-clip: border-box; border: none !important; }
```

But It can't help me solve it on the ng-bootstrap modal dialog stuff.

### Link to minimally-working StackBlitz that reproduces the issue:
It's on your official demo, I just click on your stackblitz link here: [https://stackblitz.com/run?file=app/modal-basic.ts](https://stackblitz.com/run?file=app/modal-basic.ts)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.14

ng-bootstrap: 5.1.4

Bootstrap: 4.4.1

Browser: Edge 
  -  Microsoft Edge 44.18362.449.0
  -  Microsoft EdgeHTML 18.18363

OS: Windows 10 version 1909 build 18363.535

**Comment by peterblazejewicz** [comment]
Thiscustom CSS snip worked for me. Are you sure these changes are applied correctly?

**Comment by xenogew** [comment]
@peterblazejewicz OK, now it worked, I put that snippet on "dialog css files" separately and it was overwrite by some style I didn't recognize where it from.
But now I can force overwrite to what I want. Thanks for your concern.
