### ISSUE TITLE
Modals dismissed by mouse release when trying to scroll the window

### ISSUE THREAD

**Issue by penguintheorem** [ng-bootstrap/ng-bootstrap#3518]
### Bug description:
When you try to scroll the modal window by clicking and dragging the scrollbar, the modal gets dismissed on mouse release. The following should clarify the issue:

![chrome-capture (21)](https://user-images.githubusercontent.com/17404725/70930426-723a4b80-2035-11ea-8622-8b447ec64b89.gif)

### Link to minimally-working StackBlitz that reproduces the issue:
[here the example](https://ng-bootstrap.github.io/stackblitzes/modal/basic/stackblitz.html)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.13

ng-bootstrap: 5.1.4

Bootstrap: 4.3.1

**Comment by benouat** [comment]
Hey @penguintheorem , thanks to reach out !

Regarding the issue you report, I am a little bit confused. Modal are designed to actually hide the window scrollbar when opened.

I can't even reproduce it on your stackblitz. As soon as modal is opened, I don't have any scrollbar I can grab to scroll around...

**Comment by peterblazejewicz** [comment]
@benouat 
Can you check below diff change?
```diff
diff --git a/src/modal/modal-window.ts b/src/modal/modal-window.ts
index 3554383..4a06d47 100644
--- a/src/modal/modal-window.ts
+++ b/src/modal/modal-window.ts
@@ -65,13 +65,10 @@ export class NgbModalWindow implements OnInit,
                        }
                      }));
 
-      const mouseDowns$ = fromEvent<MouseEvent>(this._elRef.nativeElement, 'mousedown')
-                              .pipe(
-                                  takeUntil(this.dismissEvent),
-                                  map(e => this.backdrop === true && this._elRef.nativeElement === e.target));
-
-      fromEvent<MouseEvent>(this._elRef.nativeElement, 'mouseup')
-          .pipe(takeUntil(this.dismissEvent), withLatestFrom(mouseDowns$), filter(([_, shouldClose]) => shouldClose))
+      fromEvent<Event>(this._elRef.nativeElement, 'click')
+          .pipe(
+              filter(e => this.backdrop === true && this._elRef.nativeElement === e.target),
+              takeUntil(this.dismissEvent))
           .subscribe(() => this._zone.run(() => this.dismiss(ModalDismissReasons.BACKDROP_CLICK)));
     });
   }
```
or something along those lines. The problem occurs when the cotnent of the modal upscale the modal body in such way, the scrollbars appears. When scrolled via scrollbars, current mouse-events are triggerred, dismissing the modal.

**Comment by benouat** [comment]
Yes this is it ☹️ 
`autoclose` in modal is a specific one, we do not reuse the one we have for popup (datepicker, dropdown and typeahead) and unfortunately the implementation rely on `mousedown`

So when the modal itself is bigger than the viewport, we do a scrollbar, a legit one, which leads to this bug. when you click it (you mousedown it...) so we think we are _outside_

It's a actual real bug that need a proper fix.
