### ISSUE TITLE
Progressbar: "animated" flag has no effect

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#352]
I think that the issue is on the BS 4 CSS side as I can see css class (`progress-animated`) added but no visual effect. To be investigated.

**Comment by icfantv** [comment]
This _may_ also be a bug in BS4.  The alpha 2 release is from early December and they've had nearly 1100 commits since then.

It _may_ be worth grabbing the latest from GH and seeing what breaks on our project?

**Comment by wesleycho** [comment]
This is broken on the Bootstrap 4 demo site as well: http://v4-alpha.getbootstrap.com/components/progress/#animated-stripes

**Comment by pkozlowski-opensource** [comment]
OK then, I guess it is not actionable till BS folks sort it out. Marking as blocked.

**Comment by jnizet** [comment]
The documentation of the component says:

> A flag indicating if a progress bar should be animated when the value changes.

But the only thing that the component does with this flag is that it sets the css class `progress-animated` on the progress element. And the documentation of bootstrap about that class says:

> The striped gradient can also be animated. Add .progress-animated to .progress to animate the stripes right to left via CSS3 animations.

So, either the component documentation is right, but the code doesn't do what it says it should do, or the documentation of the component is incorrect, and it should be modified to specify that the flag is only relevant if striped is true, and enables the animation of the stripes.

**Comment by wesleycho** [comment]
Bootstrap's own demo is broken - see comment above.

**Comment by jnizet** [comment]
Yes, I know it's broken, but that's irrelevant. Please read my comment again. Setting animated to true won't animate the progress when the value changes as the documentation claims. It will only (once bootstrap is fixed), animate the stripes.

**Comment by pkozlowski-opensource** [comment]
@jnizet yeh, the current state is unfortunate... What would be your call when it comes to the fix? I'm kind of thinking that we should just drop this functionality till it is fixed on the BS side...

**Comment by wesleycho** [comment]
The user can always write their own CSS though. It's just a class toggle at the end of the day, the user can always use it as the user wills.

**Comment by jnizet** [comment]
If the goal is just to enable the bootstrap behavior of animating the stripes, then the code can be left as it is, and the documentation fixed. bootstrap is in alpha version, and ng-bootstrap warns about it, so no problem.
If the goal is to actually animate the movement from value A to value B, then I wouldn't use the `progress-animated` CSS class, and I guess it could be possible to encapsulate a CSS rule in the CSS stylesheet of the component. But I suck at CSS, and even more at animations.

**Comment by pkozlowski-opensource** [comment]
Ref.: https://github.com/twbs/bootstrap/issues/17148

**Comment by pkozlowski-opensource** [comment]
This just got fixed by 7e4af877f89c50b947ee2cd108677a6538be6e50 and will be part of the next (alpha.18) release (expect today / tomorrow).
