### ISSUE TITLE
Proceed to Next User Content(Story) Like In Instagram In NG-Bootstrap Carousel

### ISSUE THREAD

**Issue by jtan80813** [ng-bootstrap/ng-bootstrap#3521]
Hi! Pls see this question in stackoverflow. Thanks. 
[https://stackblitz.com/edit/ng-bootstrap-carousel-instagram-story?file=app%2Fcarousel-basic.ts](https://stackblitz.com/edit/ng-bootstrap-carousel-instagram-story?file=app%2Fcarousel-basic.ts)
### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.4

ng-bootstrap: 5.1.4

Bootstrap: 4.3.1

**Comment by peterblazejewicz** [comment]
Hey, seems most imporant part (link) is missing.
Do not skip reading:
https://github.com/ng-bootstrap/ng-bootstrap/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by benouat** [comment]
Hey @jtan80813 would you mind trying to explain me with plain words what you want to achieve, so  I can better understand where the issue stands, if there is an issue.

Your stackblitz (even though it's a very big one 👏 !) does not really help me understand, nor the issue title...

**Comment by jtan80813** [comment]
@benouat. I just wanted to achieve how instagram story works. As you can see in instagram, when you have finished viewing the story of a person, it automatically proceeds to the next persons story. I just wanted to achieve this. Right now, in my code you need to exit the current person story modal and press another story modal of other person to view their story

**Comment by maxokorokov** [comment]
I don't see what is the issue with carousel here either, please explain what is wrong with carousel component itself / provide more focused stackblitz

**Comment by jtan80813** [comment]
@maxokorokov. Hi! Like instagram, is there way that it could proceed to the next carousel automatically? As you can see in my stackblitz above, it remains on the same carousel "`User# 1 Story(s)`".
It should proceed to the "`User# 2 Story(s)`" as soon as "`User# 1 Story(s)`" has finish.

**Comment by jtan80813** [comment]
@benouat @maxokorokov @peterblazejewicz Is my question clear?

**Comment by benouat** [comment]
@jtan80813 yes your requirement seems pretty clear. Nonetheless I won't lie to you, I did not have time to deep dive into your stackblitz as it is **quite huge** !

Yes, we are asking a lot ... but would it be possible for you to light it down a bit ? Just 2 flat carousels with no modal, no stores, no specific styling. Just some models, 2 widgets and trying to achieve what you want to do.

I am convinced that doing this, you'll spot right away what's going wrong in your app 💪 😃

**Comment by benouat** [comment]
@jtan80813 any news ?

**Comment by maxokorokov** [comment]
If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- **provide a **minimal** reproduction scenario in a StackBlitz**

**Comment by jtan80813** [comment]
@maxokorokov. I have provided a stackblitz on my question above. Here it is again [https://stackblitz.com/edit/ng-bootstrap-carousel-instagram-story?file=app%2Fcarousel-basic.ts](url)

**Comment by jtan80813** [comment]
Pls reopen this question. This is not fixed yet. Thanks

**Comment by jtan80813** [comment]
Hello. Any update on this?
