### ISSUE TITLE
Need an option to match Dropdown to width of hostElement

### ISSUE THREAD

**Issue by hughanderson4** [ng-bootstrap/ng-bootstrap#3523]
### Bug description:

Our application requires that the dropdown match the trigger's width.
We are using container="body" because we have dropdowns appearing in modals, these dropdowns have their content clipped unless we use container="body"

We have some CSS in place to match dropdown to width of the trigger (host) element.  However this CSS doesn't function anymore when we use container="body" since the dropdown is removed from the context of the document flow where the trigger is located.

We need a built-in Api option for the Dropdown to specify a behavior something like width="host" to use in conjunction with container="body".  When positioning the dropdown, it would use the host element's width instead of the target element's width in the layout computation.  Actually it would need to use whichever is the wider of the 2 values. (Math.max()).

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-vgxqlx

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.1.0

ng-bootstrap: 5.1.1

Bootstrap: 4.3.1

**Comment by hughanderson4** [comment]
I think it would be sufficient to set the width of the .dropdown div to the width of the host.  Right now it just sets the top and left of the .dropdown div that contains .dropdown-menu, but not the right, or width.  If the right or width was set to match the host's width, my existing CSS would work.  That would have minimal impact on existing Use Cases.

**Comment by hughanderson4** [comment]
I made a hack which can fix this but it has a brief flash on the screen where the dropdown is visible at a narrow width before my code can correct it.  Here is how I trigger it:

```html
<div ngbDropdown #dropdown="ngbDropdown" container="body" #hostElement (openChange)="fixDropdownWidth(hostElement)">
```

```ts
    fixDropdownWidth(hostElement: HTMLDivElement) {
        setTimeout(() => {
            let bodyDD: HTMLDivElement[] = <HTMLDivElement[]>Array.from(this._document.body.children).filter((child: HTMLDivElement) => child.className.indexOf('dropdown') >= 0);
            if (bodyDD && bodyDD.length) {
                bodyDD[0].style.width = hostElement.clientWidth + 'px';
            }
        }, 0);
    }
```

I must call setTimeout because the .dropdown is not added to DOM yet.
If .dropdown had width set to that of the trigger, by ng-bootstrap, this would eliminate the need for such hack, and it will take away the brief flash where dropdown is incorrect width.

Thank you for considering this small and important change.

**Comment by hughanderson4** [comment]
Final piece of the puzzle I just put in place is to control when to display the dropdown, with some CSS.

By default I make dropdown-menu have opacity: 0.  Then, after I have fixed the width, I fade it in.

```scss
.dropdown-menu {
    opacity: 0;
    transition: opacity 150ms ease-in-out;
    &.fixed {
        opacity: 1;
    }
}
```

See here in my "fix" routine I set the class "fixed" when I'm done tweaking the width how I want it:

```ts
    constructor(@Inject(DOCUMENT) private _document: any, private _renderer: Renderer2) {
    }

    fixDropdownWidth(hostElement: HTMLDivElement) {
        setTimeout(() => {
            let bodyDD: HTMLDivElement[] = <HTMLDivElement[]>Array.from(this._document.body.children).filter((child: HTMLDivElement) => child.className.indexOf('dropdown') >= 0);
            if (bodyDD && bodyDD.length) {
                this._renderer.setStyle(bodyDD[0], 'width', hostElement.clientWidth + 'px');
                this._renderer.addClass(bodyDD[0].children[0], 'fixed');
            }
        }, 0);
    }
```

Although this concludes the workaround, I still think it would be useful to have ngBootstrap make the dropdown's width match the hostElement's width.

**Comment by peterblazejewicz** [comment]
Hi,

the q&d solution via custom directive (the `dirty` here is lack of abstraction on how to get the `target`/`trigger` element ref, so this resorts to input binding to get ID):

```ts
@Directive({
  selector: "[ngbDropdownMenuFitWidth]"
})
export class NgbdDropdownFitWidth implements AfterViewInit, OnDestroy {
  private subscription: Subscription;

  @Input('ngbDropdownMenuFitWidth') _id: string;

  @ContentChild(NgbDropdownMenu, {read: ElementRef, static: false}) private menuElement: ElementRef;

  private dropdownNativeElement: HTMLElement;

  constructor(
    @Inject(forwardRef(() => NgbDropdown)) private dropdown: NgbDropdown,
    @Inject(DOCUMENT) private document: Document,
  ) {}
  ngAfterViewInit(): void {
    this.dropdownNativeElement = this.document.getElementById(this._id);
    this.subscription = this.dropdown.openChange.subscribe(() => {
      if (this.dropdown.isOpen() && this.dropdownNativeElement && this.menuElement) {
        this.menuElement.nativeElement.style.width = `${this.dropdownNativeElement.clientWidth}px`;
      }
    });
  }
  ngOnDestroy() {
    this.subscription.unsubscribe();
  }
}
```
```html
<div ngbDropdown #d id="some-id" ... container="body">
  ...
  <div ngbDropdownMenu aria-labelledby="dropdownBasic1" [ngbDropdownMenuFitWidth]="d.id">
    ...
  </div>
</div>
```
Forgive the `ngbd` prefix, suppose that's demo.

**Comment by maxokorokov** [comment]
@hughanderson4 here is a bit cleaned up @peterblazejewicz's idea:

https://stackblitz.com/edit/angular-hauhw5?file=app%2Fmatch-width.directive.ts

I don't think we'll be adding this to the library itself any time soon.

**Comment by benouat** [comment]
My $2c here, I would have used `offsetWidth` instead of `clientWidth` to align regardless of borders.

**Comment by benouat** [comment]
> I don't think we'll be adding this to the library itself any time soon.

I agree on that one.

**Comment by benouat** [comment]
Hey @hughanderson4 is the workaround proposed by @peterblazejewicz / @maxokorokov good enough for you ? If so I think we should close that issue.

**Comment by hughanderson4** [comment]
Thanks, I didn't try any of these other workarounds since mine is working fine.

I'm still unsure why the framework isn't able to set the width of the `.dropdown` container, but if that cannot be changed, then this issue may be closed.

Have a nice day.  🍻

**Comment by benouat** [comment]
> but if that cannot be changed

It could be changed! That is not the point. The widget here is a dropdown, the width of the list is not tied to the width of the button host. Bootstrap does not provide such an option. So we don't wan to embed that piece of logic.

Don't be confused with a select widget that in this case would need its list to be in sync with the host.

with that in mind, let's close...

**Comment by hughanderson4** [comment]
hi @benouat hi @peterblazejewicz hi @maxokorokov 
this solution is working well for dropdown.
i need to do the same thing for typeahead.
but typeahead does not have this `openChange` that i can subscrbe.

i see [somebody already requested to add `openChange` event on typeahead](https://github.com/ng-bootstrap/ng-bootstrap/issues/2378).
i am really needing that, would you please kindly add that to typeahead output events?
that way i can implement this same width matching technique on my typeaheads.

thanks so much!
