### ISSUE TITLE
bug(datepicker): [IE11, Edge] Arrow icon on month and year select disappears on focus

### ISSUE THREAD

**Issue by qf-jonathan** [ng-bootstrap/ng-bootstrap#3526]
### Bug description:
On IE11 and Edge, The arrow icon on month and year select disappear on focus.

![2019-12-30 13_13_16-Microsoft Edge](https://user-images.githubusercontent.com/1207421/71594539-54c1b300-2b06-11ea-83ec-adee7b1ff4a0.png)

### Reproduce the issue:
- On IE11 or Edge Browser open the [demo datepicker](https://ng-bootstrap.github.io/stackblitzes/datepicker/basic/stackblitz.html)
- Select any month
- The arrow icon disappears
- If the focus is changed to year with the TAB key, the arrow icon disappears on year and reappears on month

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.4

ng-bootstrap: 5.1.4

Bootstrap: 4.3.1

**Comment by peterblazejewicz** [comment]
@qf-jonathan 
Thanks for the report, the project uses SVG to render those details.
note: TBI SVG in CSS background in IE11/Edge

**Comment by qf-jonathan** [comment]
@peterblazejewicz
IE11 and Edge browsers use a pseudo-element to render the value of a select, the background of that element hides the arrow icon. I made a PR #3527 to fix that.
