### ISSUE TITLE
Datepicker returns focus to input on close

### ISSUE THREAD

**Issue by kurthamilton** [ng-bootstrap/ng-bootstrap#3534]
### Bug description:
When opening a datepicker from an input focus, the datepicker returns focus to the input, causing it to re-open.

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-ajzswx

(open console to see event output)

### Versions of Angular, ng-bootstrap and Bootstrap:
Angular: 8.2.14
ng-bootstrap: 5.1.5
Bootstrap: 4.4.1

### Desired behaviour
Open a datepicker popup on the input receiving focus, close datepicker popup as per the configurable behaviour (e.g. on click outside input / popup).

I have tried searching for an alternative way to achieve this, so apologies if this is a duplicate.

**Comment by peterblazejewicz** [comment]
@kurthamilton 
I think this is already tracked as #3483

**Comment by kurthamilton** [comment]
@peterblazejewicz Thanks. Obviously I didn't look hard enough...
