### ISSUE TITLE
Manual trigger dropdown can not focus on items

### ISSUE THREAD

**Issue by gpolychronisAmadeus** [ng-bootstrap/ng-bootstrap#3543]
On ng-bootstrap demo get at the "Manual and custom triggers" example of "Dropdown".

https://ng-bootstrap.github.io/#/components/dropdown/examples#manual

Try to focus an item of that example only via keyboard navigation. It's not possible.

I propose the following solution: When focus is upon dropdown button, user can navigate through items via up and down arrow keys.

**Comment by benouat** [comment]
You can navigate them with keyboard, it's just that something is really broken on this example.
On my Chrome/Edge (macOS) I can focus them by tabbing until after the Close button...

Then, once one of the buttons get focused, you can normally navigate with <kbd>up</kbd> and <kbd>down</kbd> (which is the default behaviour implemented)

I think the missing part here would be to put the focus on the first Item when opened via the imperative API.

**Comment by maxokorokov** [comment]
Closed in #3560
