### ISSUE TITLE
ngbTooltip not working for IE10/11

### ISSUE THREAD

**Issue by satyam-dev** [ng-bootstrap/ng-bootstrap#3544]
#2843

### Bug description:
ngbTooltip not working for IE 10 and 11 browser. Same code is working for Chrome browser.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular version - 7
Bootstrap version - 4.0.4

**Comment by peterblazejewicz** [comment]
We would love to see the use-case, can you pick one of those:
https://ng-bootstrap.github.io/#/components/tooltip/examples
and create blitz for this issue? Thanks! Apprieciated!

**Comment by maxokorokov** [comment]
As @peterblazejewicz has suggested, please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz

**Comment by maxokorokov** [comment]
Closing as no feedback, please reopen if necessary
