### ISSUE TITLE
Add tab at particular index in in ngbset 

### ISSUE THREAD

**Issue by dhavalsolankislk** [ng-bootstrap/ng-bootstrap#3558]
Hello, 

We are using ngbtabset in our application. So we have a requirement to add at particular tab to a particular index dynamically.
For example we have added three tab dynamically, now we are removing second tab and after removing we are adding same tab again dynamically, so that tab is added in the last index. But we want to add particular tab as our predefined index. So is that possible.

**Comment by benouat** [comment]
Hey @dhavalsolankislk thanks to report what you think is an issue!

Regarding the `nab-tabset` widget, we are in the process of deprecating it in favour of a new set of directives -> [ngb-nav](https://ng-bootstrap.github.io/#/components/nav/overview)

This new set of directives gives you much more control over the markup, and I think you should be able to implement your need with little difficulties.

Could you please try to migrate to this ? I'll close this issue for now, a s we won't fix/implement new features in tabset anymore.

Don't hesitate to open another one if you figure out something not working properly in navs.
