### ISSUE TITLE
NavChangeEvent is raised if activeId is not set

### ISSUE THREAD

**Issue by nseni** [ng-bootstrap/ng-bootstrap#3564]
### Bug description:
https://ng-bootstrap.github.io/#/components/nav/api#NgbNavChangeEvent

> The payload of the change event emitted right before the nav change happens on user click.
This event won't be emitted if nav is changed programmatically via [activeId] or .select().

But if I don't set the initial activeId, the event is emitted after plugin selects the first tab for me

![image](https://user-images.githubusercontent.com/47851128/73191887-4aacc780-4139-11ea-907d-75b9fd60fd60.png)

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-qqykku?file=app/nav-basic.html

**Comment by maxokorokov** [comment]
@nseni yep, thanks for this. This is the omitted use case due to the late refactoring before releasing navs... Should be fixed in `5.2.2`
