### ISSUE TITLE
Property does not exist on NgbModalConfig

### ISSUE THREAD

**Issue by taufiqahmed** [ng-bootstrap/ng-bootstrap#3568]
Getting Typescript error : `Property 'centered' does not exist on type 'NgbModalConfig'`.
Only 'backdrop' and 'keyboard' property is available to configure globally from NgbModalConfig.

Angular: 7.2
ng-bootstrap: 4.2.2
Bootstrap: 4.3.1

**Comment by maxokorokov** [comment]
I think this was fixed in a more recent version. With the latest works fine:

https://stackblitz.com/edit/angular-ikpvgw?file=app/modal-config.ts

**Comment by maxokorokov** [comment]
Duplicate of #3406
