### ISSUE TITLE
Can't use 0 as nav id

### ISSUE THREAD

**Issue by nseni** [ng-bootstrap/ng-bootstrap#3569]
### Bug description:
`<li [ngbNavItem]="0">`

In this case the plugin thinks there's no id and assigns internal ID (`ngb-nav-0`) instead.

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-adgxbn?file=app/nav-basic.html

**Comment by maxokorokov** [comment]
Thanks, also should be the part of `5.2.2`
