### ISSUE TITLE
NgbDropdownItem breaks activating a button with Enter/Space

### ISSUE THREAD

**Issue by nseni** [ng-bootstrap/ng-bootstrap#3570]
### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-prjmrz?file=app/dropdown-basic.html

### Bug description:
When NgbDropdownItem is applied, Enter or Space don't trigger `(click)` handler.

1. Use Tab to select first dropdown
2. Press Enter to open dropdown
3. Navigate to any dropdown item using arrow keys
4. Press Enter or Space. Nothing happens
____
1. Use Tab to select second dropdown
2. Press Enter to open dropdown
3. Navigate to any dropdown item using Tab key
4. Press Enter or Space. Function assigned to (click) handler is executed.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.4
ng-bootstrap: 5.2.1
Browser: Google Chrome

**Comment by maxokorokov** [comment]
Related to #3561 I guess

**Comment by maxokorokov** [comment]
Looks like for this particular case we still need to close the popup asynchronously using either `requestAntimationFrame` or `setTimeout`
