### ISSUE TITLE
The position of the popup is not updated for resizable textareas

### ISSUE THREAD

**Issue by 5te1n** [ng-bootstrap/ng-bootstrap#3575]
### Bug description:
Situation:
We have the ngbPopover directive on a resizable textarea. The popover has the default configuration ("autoClose=true").

Current behaviour: 
The position of the popover is not updated when the textarea is resized. In addition, the resizing is interpreted as a click, so the popover closes or opens after the resize. 

Desired behavior:
The position is updated when the text area is resized and the resizing does not trigger the open/close mechanism.

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-fr1ahy?embed=1&file=app/popover-basic.html

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.4

ng-bootstrap: 5.2.1

Bootstrap: 4.3.1

**Comment by gpolychronis** [comment]
Hello @5te1n .
Resizing the text area is an "outside" pointer action. So closing the popover during resizing makes sense to me.
I propose to customize the triggers and autoclose to achieve what you need, i.e.:

```
<textarea style="resize: both;" placement="bottom" [autoClose]="'inside'" triggers="mouseup:mousedown"
          ngbPopover="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." popoverTitle="Popover on bottom"
          #p="ngbPopover" (click)="p.open()">
  Popover on bottom
</textarea>
```
