### ISSUE TITLE
Upgrade to Angular 9 roadmap?

### ISSUE THREAD

**Issue by DanielChuDC** [ng-bootstrap/ng-bootstrap#3577]
Angular 9 just become stable  recently.

Any roadmap to update to 9?

**Comment by pkozlowski-opensource** [comment]
Yep, planning to cut RC early next week (Mon possibly) and the final few days after. Although the latest released version should work perfectly fine with Angular 9 (you will get semver warnings from npm / yarn but again, things should work just fine).
