### ISSUE TITLE
Add Popper 2 as a dependency

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#3579]
Giving the number of issues we have about positioning, lack of resources and the fact that we're kind of rewriting popper on our own, we'll be adding `@popper/core` as a peer dependency in 12.0.0.

We'll be able to flip, reposition arrow (tooltip, popover), consider viewport dimensions, different parent containers.
Two major downsides are It adds around 14-17Kb (minified, NOT compressed) to the final app bundle in our tests and a 3rd dependency for this project

Affected components at the moment are datepicker, dropdown, popover, tooltip and typeahead.

**Positioning Issues we have**

- [ ] #4012
- [ ] #3981 
- [ ] #3927 
- [ ] #3836 
- [ ] #3834 
- [ ] #3743 
- [ ] #3575 
- [ ] #3525 
- [x] #3495 
- [ ] #3382 
- [ ] #3337 
- [ ] #3310 
- [ ] #3294 
- [ ] #3046 

**Related PRs**
#4129

**Comment by bastienmoulia** [comment]
> check if/when bootstrap is going to use it

https://github.com/twbs/bootstrap/issues/29842

Not sure yet if Bootstrap 5 will:
- stay with popper 1
- use popper 2 with polyfill for ie11
- use popper 2 and drop support of ie11

**Comment by maxokorokov** [comment]
Bootstrap 5 should be dropping IE support altogether, so no need in polyfills for popper 2

cc @fbasso

**Comment by fbasso** [comment]
Close it, as ngBootstrap 13.1.0 has been released with feature
