### ISSUE TITLE
NgbDropdown adds vertical scrollbar when opened in table.

### ISSUE THREAD

**Issue by tomasszabo** [ng-bootstrap/ng-bootstrap#3580]
### Bug description:

`NgbDropdown` adds horizontal scrollbar when opened in table. Problem occurs in Chromium browsers (Chrome & New Edge) when `NgbDropdown` is in table row. In Safari & Firefox it works as expected.

It seems that problem is due to `transform` CSS property added to `NgbDropdownMenu` on dropdown open where negative values for translate (e.g. `transform: translate(-132px, 45px)`) are causing this problem. When `NgbDropdown` has position `static` (default is `relative`) then translate of `NgbDropdownMenu` has positive values (e.g. `transform: translate(82px, 37px)`) and everything works as expected. 

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-xhgz4p-biuuss

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.14

ng-bootstrap: 5.2.2

Bootstrap: 4.4.1

**Comment by gpolychronis** [comment]
It seems issue doesn't replicate in provided StackBlitz.

**Comment by tomasszabo** [comment]
@gpolychronis  For sure it does replicate.

See that horizontal scrollbar on bottom?

<img width="518" alt="Screenshot 2020-03-09 at 16 37 27" src="https://user-images.githubusercontent.com/6609558/76230809-8a7cc980-6224-11ea-9008-73779db4ac79.png">

With `position: static;` it's not there:

<img width="516" alt="Screenshot 2020-03-09 at 16 38 11" src="https://user-images.githubusercontent.com/6609558/76230835-97012200-6224-11ea-8c3e-6b77b78cd6eb.png">

**Comment by rleszczyk** [comment]
I have the same issue with scrollbar in Angular 10 with ng-bootstrap v8.0.4. Any ideas how can i fix it?
