### ISSUE TITLE
NgbModalStack doesn't support container selector existing within a shadowdom

### ISSUE THREAD

**Issue by drobins29** [ng-bootstrap/ng-bootstrap#3584]
### Bug description:
When providing the selector for the container option when opening a modal, it is impossible to specify an element that exists within a shadow dom. It would be nice to be able to pass a DOM object with the NgbModalOptions to the NgbModal open method. 

My use case is that we are embedding an angular app within an existing application and we do not want external styling to affect the styling of the embedded app. So the main component is using `encapsulation: ViewEncapsulation.ShadowDom` to get around the styling issues and importing the bootstrap css within the main app component's sass file in a parent selector.

If we could pass a DOM element instead of a selector that would allow the modal to pick up the correct styling.

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-wymgqp

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: >=8.2.4

ng-bootstrap: 5.2.2

**Comment by PabloPollono-Nexplore** [comment]
hey I have the same issue and the container option is not working for me, can you show me the fix for the shadow dom + container option?
