### ISSUE TITLE
how can i disable one column sorting table in angular powered bootstrap

### ISSUE THREAD

**Issue by harsh-pansuriya** [ng-bootstrap/ng-bootstrap#3586]
<table class="table table-striped">
                    <thead>
                      <tr>
                        <th>sr no</th>
                        <th scope="col" sortable="data" (sort)="onLSort($event)">Name</th>
                        <th scope="col" sortable="people" (sort)="onLSort($event)">Peaople</th>
                        <th scope="col" sortable="points" (sort)="onLSort($event)">Points</th>
                        <th scope="col" sortable="avg" (sort)="onLSort($event)">Avg</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td scope="row">1</td>
                        <td>user 1</td>
                        <td>people 1</td>
                        <td>Points</td>
                        <td>Avgs 1</td>
                      </tr>
                    </tbody>
                  </table>

**Comment by maxokorokov** [comment]
Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz

**Comment by peterblazejewicz** [comment]
Hey,
That's an extra, not part of regular library. So there is an example how to implement sorting based on the custom directvie (sort initiator) added to the column header which I believe you're referring to:
https://ng-bootstrap.github.io/#/components/table/examples#sortable
If you don't add this directive, column should not support sorting. You could just extend this directive to support 'disableSort' (or similary named) state, depending on your usage of the table.
Thanks!

**Comment by harsh-pansuriya** [comment]
Hello @peterblazejewicz  
Please let me know where can I exactly place disableSort for "sr no" column ?
