### ISSUE TITLE
Autoclose broken on iPad with iOS 13

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#3591]
See this comment → https://github.com/ng-bootstrap/ng-bootstrap/pull/3587#pullrequestreview-358137393

**Comment by kamilchlebek** [comment]
@maxokorokov Thanks for the fix. Tooltip opens on iOS 13. 

Just one more question. I'm not sure if this is expected or it's different issue. 
1. open https://ng-bootstrap.github.io/#/components/tooltip/examples on iPadOS 13
2. tap "tooltip on top" -> tooltip appears
3. tap the same button again -> tooltip disappears
4. tap again -> **tooltip doesn't appear** 
It will not open again until you tap some other tooltip

Similar thing happens on android. However you can tap anywhere on the page to remove focus form button, then tapping the same buton again will open the tooltip. (clicking anywhere on the page does not blur the button on iOS)
