### ISSUE TITLE
Angular 9 support

### ISSUE THREAD

**Issue by micobarac** [ng-bootstrap/ng-bootstrap#3592]
### Feature request:

Angular 9 support

### Versions of Angular, ng-bootstrap and Bootstrap:

<pre>
<code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.2
Node: 13.8.0
OS: linux x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cdk                      9.0.0
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

-----------------------------------------------------------
Bootstrap                         4.4.1
ng-bootstrap                      5.2.3

-----------------------------------------------------------
warning " > @ng-bootstrap/ng-bootstrap@5.2.3" has incorrect peer dependency "@angular/common@^8.0.0".
warning " > @ng-bootstrap/ng-bootstrap@5.2.3" has incorrect peer dependency "@angular/core@^8.0.0".
warning " > @ng-bootstrap/ng-bootstrap@5.2.3" has incorrect peer dependency "@angular/forms@^8.0.0".
</code>
</pre>

**Comment by peterblazejewicz** [comment]
Hey, it's already happening:
https://github.com/ng-bootstrap/ng-bootstrap/issues/3537
https://github.com/ng-bootstrap/ng-bootstrap/pull/3447
Thanks!

**Comment by micobarac** [comment]
That's some good news. Thanks. 😋
