### ISSUE TITLE
Ngb-Carousel increase dynamically in Angular 8

### ISSUE THREAD

**Issue by mokshadev** [ng-bootstrap/ng-bootstrap#3601]
Hi
I am current doing a project based on carousel
I want to display each row of data from mysql database on different slide.
And increase slides dynamically in case a new row of data has been added to the database.
Anyone knows how to do this?

Thanks

Angular: 8

**Comment by pkozlowski-opensource** [comment]
https://github.com/ng-bootstrap/ng-bootstrap#getting-help
