### ISSUE TITLE
Error when using ngbtooltip and ngbpophover

### ISSUE THREAD

**Issue by dhavalsolankislk** [ng-bootstrap/ng-bootstrap#3602]
Hello,
We have upgraded our project to angular 9. In some places in button we have implemented ngb tooltip and ngbpophover on same page so using this we get the below error
![Untitled](https://user-images.githubusercontent.com/59446200/74666296-3f443d80-51c7-11ea-9a54-75ab07e97357.png)

We have implemented in button as below

![Untitled](https://user-images.githubusercontent.com/59446200/74666438-7ca8cb00-51c7-11ea-820a-1fb16cf8705f.png)

Is there any solution to this problem ?

**Comment by peterblazejewicz** [comment]
can you somehow provide an excerpt of the template used to render that content?
The error you've seen is not listed in the *most common* Ivy related problems: 
https://angular.io/guide/ivy-compatibility-examples

**Comment by peterblazejewicz** [comment]
similar: angular/angular#35412

**Comment by dhavalsolankislk** [comment]
Hello,
our sample code is 
 **`<button type="button" class="btn btn-icon btn-icon-none"
              container="body" ngbTooltip="{{'Notes' | translate}}" placement="auto" [autoClose]="'outside'"
              #tooltip="ngbTooltip" (click)="onNoteBynClick()"
              #remarkPopHover="ngbPopover" [ngbPopover]="popContent" popoverClass='body popover-yellow'>
              <i class="micon-rx-chat {{getMultiExpenseArray()?.at(rowIndex)?.get('notes')?.value ? 'text-warning' : ''}}"></i></button>

<ng-template #popContent>
              <div class="container p-0 m-0" style="width: 300px;height: 180px;">
                <div class="d-flex flex-column">
                  <div class="text-large color-label-local p-2 pt-1">{{'AddaRemark' | translate}}</div>
                  <textarea class="form-control p-2" rows="4" formControlName="notes"></textarea>
                </div>
              </div>
</ng-template>`**

**Comment by benouat** [comment]
**Wild guess**
I have no clue yet what's going on, but would you mind trying to declare the `<ng-template>` before the button and not as a forward reference ?

**Comment by benouat** [comment]
@dhavalsolankislk you should also try to isolate if the issue comes from `ngb-tooltip`or `nib-popover`

**Comment by pkozlowski-opensource** [comment]
I can investigate this one if anyone can reproduce it in stackblitz / https://ng-run.com/

**Comment by AaronJTan** [comment]
Hi, did you find the solution to this?
