### ISSUE TITLE
Error to import NgbModule in my component module in angular 9 versión

### ISSUE THREAD

**Issue by fbellod1986** [ng-bootstrap/ng-bootstrap#3603]
I report this is knowing that they are not supporting angular 9 but the idea is to raise it.

**Comment by benouat** [comment]
hey @fbellod1986 did you test that using `v6.0.0-rc.0`?

**Comment by fbellod1986** [comment]
> hey @fbellod1986 did you test that using `v6.0.0-rc.0`?

Angular v6 or "@angular-devkit/build-angular" ??

**Comment by benouat** [comment]
I was just talking about `ng-bootstrap` 😄

**Comment by fbellod1986** [comment]
> I was just talking about `ng-bootstrap` 😄

Ahh ok, no i just down version to angular 8, waiting this issue fixed xD, thanks!

**Comment by benouat** [comment]
> waiting this issue fixed

But there is nothing to be fixed... the demo site is actually running on Angular `9.0.1` and everything is working fine...

I'll close for now. Don't hesitate to re-open if you have more context

**Comment by fbellod1986** [comment]
> > waiting this issue fixed
> 
> But there is nothing to be fixed... the demo site is actually running on Angular `9.0.1` and everything is working fine...
> 
> I'll close for now. Don't hesitate to re-open if you have more context

OK, thanks!
