### ISSUE TITLE
Avoid deploying demo website when the branch is rc or beta

### ISSUE THREAD

**Issue by bastienmoulia** [ng-bootstrap/ng-bootstrap#3605]
Actually the demo website is with **v6.0.0-rc.0**.

There is no difference with the stable release currently, but it could be in the future.

**Comment by benouat** [comment]
Thanks @bastienmoulia, you're right, we should not.

Nonetheless, we did it because we verified it was actually fully working and as you mentioned, there were no differences.

**Comment by maxokorokov** [comment]
@bastienmoulia that is a valid point. And as @benouat mentioned there were no changes for this one. 

But I'm not sure what you want to be done with this issue practically speaking? :)

**Comment by maxokorokov** [comment]
Once again we agree on this one. Also released `6.0.0`, so I'm going to close this one as non-actionable.
