### ISSUE TITLE
The problem continues when importing NgbModule in the component module

### ISSUE THREAD

**Issue by fbellod1986** [ng-bootstrap/ng-bootstrap#3608]
Hello everyone, when importing this dependency in the module of my component, the component is not repositioning the router-outlet, any ideas?

Thanks!

**Comment by pkozlowski-opensource** [comment]
> any ideas?

Nope, not without a reproduce scenario: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by fbellod1986** [comment]
In the module of my component I import the NgbModule and when saving the associated component does not load, it goes blank.

My package.json is:

{
  "name": "bodega",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "e2e:ci": "ng e2e --mode console"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.0.2",
    "@angular/common": "~9.0.2",
    "@angular/compiler": "~9.0.2",
    "@angular/core": "~9.0.2",
    "@angular/forms": "~9.0.2",
    "@angular/platform-browser": "~9.0.2",
    "@angular/platform-browser-dynamic": "~9.0.2",
    "@angular/router": "~9.0.2",
    "@ng-bootstrap/ng-bootstrap": "^5.3.0",
    "@ngchile/cypress-cucumber-schematics": "^1.0.0-rc.5",
    "@sentry/browser": "^5.12.1",
    "@types/jwt-decode": "^2.2.1",
    "angular-archwizard": "^5.0.0",
    "bootstrap": "^4.4.1",
    "jquery": "^3.4.1",
    "jwt-decode": "^2.2.0",
    "moment": "^2.24.0",
    "ngx-bootstrap": "^5.3.2",
    "ngx-pagination": "^5.0.0",
    "popper.js": "^1.16.0",
    "rxjs": "~6.5.4",
    "sweetalert2": "^9.6.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.2",
    "@angular/cli": "~9.0.2",
    "@angular/compiler-cli": "~9.0.2",
    "@angular/language-service": "~9.0.2",
    "@cypress/webpack-preprocessor": "4.1.1",
    "@fortawesome/fontawesome-pro": "^5.12.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "cypress-cucumber-preprocessor": "2.0.1",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-loader": "6.2.1",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.7.5"
  },
  "cypress-cucumber-preprocessor": {
    "step_definitions": "./e2e/step_definitions"
  }
}


![dqdqwdqwdqwdqwd](https://user-images.githubusercontent.com/13698871/74980413-2b8b1800-540f-11ea-9e66-3ac6cb6ee74f.png)

Thanks

**Comment by maxokorokov** [comment]
> In the module of my component I import the NgbModule and when saving the associated component does not load, it goes blank

@fbellod1986 this doesn't help at all and I can't understand what you mean unfortunately. 

Components can't have modules
Saving what? 
What goes blank?
Why do you think it's the ng-bootstrap's fault?
Do you have any exceptions?

Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz

**Comment by fbellod1986** [comment]
> > In the module of my component I import the NgbModule and when saving the associated component does not load, it goes blank
> 
> @fbellod1986 this doesn't help at all and I can't understand what you mean unfortunately.
> 
> Components can't have modules
> Saving what?
> What goes blank?
> Why do you think it's the ng-bootstrap's fault?
> Do you have any exceptions?
> 
> Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.
> 
> If you believe you've found a bug in this library then please:
> 
> * fill in the issue template correctly
> * provide a **minimal** reproduction scenario in a StackBlitz

Components can't have modules 

**This module ...**

![TYTDWEDWED](https://user-images.githubusercontent.com/13698871/75033583-012a7080-548a-11ea-8e11-f9083860ae48.png)

Saving what? 

**The changes**

What goes blank? 

**doesn't load the component in router outlet**

Why do you think it's the ng-bootstrap's fault?

**Cause' I import the NgbModule**

Do you have any exceptions?

**Nope, nothing in console**

**Comment by maxokorokov** [comment]
Once again, please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

As it was mentioned, we won't be able to do anything without the reproduction scenario. Please reopen when you have one.

All I can tell you from the `package.json` is that you shouldn't use ng-bootstrap 5 with Angular 9 → https://ng-bootstrap.github.io/#/getting-started#dependencies. You can try with `6.0.0-rc.0`, but I doubt that is the root issue here.
