### ISSUE TITLE
Add tab at particular index in in ngbnav

### ISSUE THREAD

**Issue by dhavalsolankislk** [ng-bootstrap/ng-bootstrap#3609]
Hello,

We are using ngbnav in our application. So we have a requirement to add at particular tab to a particular index dynamically.
For example we have added three tab dynamically, now we are removing second tab and after removing we are adding same tab again dynamically, so that tab is added in the last index. But we want to add particular tab as our predefined index. So is that possible.

**Comment by maxokorokov** [comment]
@dhavalsolankislk not 100% clear to me, have you tried playing with our [dynamic navs demo](https://ng-bootstrap.github.io/#/components/nav/examples#dynamic)?

Here is the stackblitz from this demo, I've added the 'swap' button:
https://stackblitz.com/edit/angular-9nx5h5?file=app/nav-dynamic.ts

I guess this should be enough. 

Also please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz
