### ISSUE TITLE
ng-bootstrap 5.3.0 autoclose datepicker not working

### ISSUE THREAD

**Issue by AnthonyLJ96** [ng-bootstrap/ng-bootstrap#3614]
In this last release not working autoclose in datepicker.

**Comment by pkozlowski-opensource** [comment]
Please provide a minimal reproduce scenario: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by Bogdanel** [comment]
Hello, this is the stackblitz link : https://stackblitz.com/edit/angular-kmnmwi

Bug is reproductible also on version 6.0

**Comment by maxokorokov** [comment]
PTAL at #3483 and #3539, this looks like a duplicate
