### ISSUE TITLE
Run StackBlitzes with ivy by default

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#3618]
At the moment our demo site StackBlitzes are using view engine.

Example of the StackBlitz working with ivy → https://stackblitz.com/edit/cdr-ivy-2

**Comment by benouat** [comment]
@gpolychronis could you have a look at that one please ?

**Comment by gpolychronis** [comment]
> 
> 
> @gpolychronis could you have a look at that one please ?

Yes

**Comment by maxokorokov** [comment]
This should be closed by #3681
