### ISSUE TITLE
bug(datepicker): Calender Month, Year Not Getting Displayed in Calender IE11

### ISSUE THREAD

**Issue by nagulapallinaveen** [ng-bootstrap/ng-bootstrap#3620]
**Bug description:**

ngb-datepicker not showing selected month, year on the calender dropdown until I click outside of the dropdown but inside the calender. This issue is only happening in IE 11. This is working perfectly in chrome but not in IE11.

I am using Angular 9 and ngbootstrap 5.3.0

Chrome: (Working Perfect)
![image](https://user-images.githubusercontent.com/28569915/75246151-2b1ac480-57f5-11ea-8ba1-8bd1092006cc.png)

IE: ( Not Working Fine)
![image](https://user-images.githubusercontent.com/28569915/75246729-6073e200-57f6-11ea-86a4-dd9687d1b593.png)

**Comment by pkozlowski-opensource** [comment]
You need to migrate to ng-bootstrap 6.x to use it with Angular 9: https://github.com/ng-bootstrap/ng-bootstrap#dependencies

**Comment by nagulapallinaveen** [comment]
> You need to migrate to ng-bootstrap 6.x to use it with Angular 9: https://github.com/ng-bootstrap/ng-bootstrap#dependencies

It is actually happening in the case of datepicker only and typeahead is working fine.I can say the problem is with the js.
Actually ng-bootstrap is working fine in my case, the issue is , it is not displaying the year or month in the dropdown after selecting the specific value. it is showing the  value in IE on blur out of the dropdowns in IE.

When I click outside of the dropdown but inside the calender then it is fine in IE.
The selected value of the dropdown is showing as blank until I click outside of the dropdown but inside the calender. ( Only in IE )

**Comment by maxokorokov** [comment]
@nagulapallinaveen, we'll need a reproducible scenario / StackBlitz, please. IE 11 is working fine for me on this demo (Angular 9, bg-bootstrap 6) → https://ng-bootstrap.github.io/#/components/datepicker/examples#popup

Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz

**Comment by nagulapallinaveen** [comment]
> @nagulapallinaveen, we'll need a reproducible scenario / StackBlitz, please. IE 11 is working fine for me on this demo (Angular 9, ng-bootstrap 6) → https://ng-bootstrap.github.io/#/components/datepicker/examples#popup
> 
> Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.
> 
> If you believe you've found a bug in this library then please:
> 
> * fill in the issue template correctly
> * provide a **minimal** reproduction scenario in a StackBlitz

I found the problem in my code, I am using bootstrap 3.3.7
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"> instead of bootstrap 4.4.1 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />

Actually, I can overcome the problem by using bootstrap 4.4.1 but i can't use this in my project  as we are already using bootstrap 3.3.7. This may affect the other css. So, what can i do in this scenario ?

**Comment by maxokorokov** [comment]
I'm glad you've figured it out!

Our library supports only bootstrap 4+ and I'm almost positively sure you should not use both BS3 and BS4 in the same application. This you should check with the Bootstrap project directly.
