### ISSUE TITLE
Unable to access documentation for past versions

### ISSUE THREAD

**Issue by swillisstudio** [ng-bootstrap/ng-bootstrap#3643]
### Bug description:

No way to access documentation for previous versions. This has made it difficult for me to work on some inherited code as I have no way of finding out how to correctly use v5 of ng-bootstrap.

Perhaps I have just missed the link to older docs?

### Link to minimally-working StackBlitz that reproduces the issue:

Access the demo site and view documentation/components. There is no way to toggle the documentation to show implementation for previous versions of the library.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8

ng-bootstrap: 5

Bootstrap: 4

**Comment by benouat** [comment]
hey @swillisstudio 

We do not provide online version for the documentation of past versions. :( sorry for that. It's something we might start to do, but for that it would involve rewriting most of our internal release process, and part of the demo itself too.

Nonetheless, if you are really stuck, what you could do is to checkout the "past version" (based on the corresponding release tag for example) and run it locally. This would work for sure.

Sorry for the inconvenience.
