### ISSUE TITLE
Dropdowns shown incorrectly

### ISSUE THREAD

**Issue by marriskleinert** [ng-bootstrap/ng-bootstrap#3646]
### Bug description:
My dropdowns won't work - neither the bootstrap-standard-dropdowns, nor the ng-bootstrap-dropdowns...
The dropdown is 'opened' from the beginning and is shown very uncommon.
If I press the toggle-button, nothing happens. The classes of the dropdown-items aren't even changed.

### Link to minimally-working StackBlitz that reproduces the issue:
That's the problem. I can't reproduce the problem. The stackblitz shows my scenario nonetheless...
https://stackblitz.com/edit/angular-pvq85f --> modal - in the modal is a dropdown

It looks like the script-side of ng-bootstrap isn't working, but I don't know why...
![image](https://user-images.githubusercontent.com/28430291/76764397-0c28a600-6795-11ea-95b2-c02ec1ad2192.png)

```
<div class="modal-content">
  <div class="modal-header">
    <div>
     TITLE
    </div>
    <button type="button" class="icon-button" (click)="activeModal.close()">
      <i class="icon icon-delete" aria-hidden="true"></i>
    </button>
  </div>
  <div class="modal-body">
    <div>
      <div class="form-group row">
        <p class="col-4 text">{{'Priority'|translate}}</p>
        <div class="col-8 no-padding">
          <div class="col">
            <div ngbDropdown class="d-inline-block">
              <button class="btn btn-outline-primary" id="dropdownBasic1" ngbDropdownToggle>Toggle dropdown</button>
              <div ngbDropdownMenu aria-labelledby="dropdownBasic1">
                <button ngbDropdownItem>Action - 1</button>
                <button ngbDropdownItem>Another Action</button>
                <button ngbDropdownItem>Something else is here</button>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer ">
    <button type="button" class="normal-button" (click)="submit()">
     FOOTER
    </button>
  </div>
</div>
```

### My angular.json
![image](https://user-images.githubusercontent.com/28430291/76765775-3e3b0780-6797-11ea-900e-1a517d35a89d.png)

## My index.html
![image](https://user-images.githubusercontent.com/28430291/76765789-42672500-6797-11ea-81c4-c3575ffcd26e.png)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 9.0.6

ng-bootstrap: 6.0.0

Bootstrap: 4.4.1

**Comment by benouat** [comment]
Hey  @marriskleinert! thanks to reach out.

> My dropdowns won't work - neither the bootstrap-standard-dropdowns, nor the ng-bootstrap-dropdowns...

I would strongly suggest that if none of these are working, then you most probably have an issue with the browser you are using, sounds like javascript is not executed maybe ?

**Comment by marriskleinert** [comment]
Hi @benouat, thanks for your answer.
I don't think so... Everything but this is working fine. 
The modals appear as expected, if I click on the button etc...
It's really weird, that some things work and others don't...

Can you think of anything different than the browser? (tested it on Firefox + Chrome, JavaScript enabled)

Thanks again :)

**Comment by benouat** [comment]
Ok, then
Next try, could you please downgrade Angular to `^8.0.0` and see if it behave differently ?

**Comment by marriskleinert** [comment]
I tried it first with Angular 8 and then upgraded to Angular 9, hoping it would solve the problem.
So yeah, the error occured in Angular 8 too...

**Comment by benouat** [comment]
Ok, then 😄 
Could you try to create a blank new project from Angular CLI, then manually (following our documentation) add ng-bootstrap, and finally try the broken pattern.

**Comment by marriskleinert** [comment]
Alright, so I did that and everything worked fine.
I think, something in my app is wrong or so.
It's been a while since it was created and there have been many updates etc..
But thank you anyways for helping out. I think I have to start from scratch in near future.
