### ISSUE TITLE
components animations

### ISSUE THREAD

**Issue by rruffer** [ng-bootstrap/ng-bootstrap#3651]
Your work is fantastic. I am using the components in several projects and I have nothing to complain about they work very well. But in most projects I used bootstrap and its animations. And the components have their animations. in ng-bootstrap the components have no animations. I know it sounds silly, but customers notice when I switched to an ng-bootstrap component for that reason. It would be interesting for the components to have animations as well as the bootstrap. Making each animation in the hand turns out to be very bad. You can dedicate part of the site to that as well. Or is there a place that teaches ng-boostrap components to have animations?

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 9

ng-bootstrap: 6

Bootstrap: 4.4.1

**Comment by fbasso** [comment]
Thanks, @rruffer  ! 

I'm going to close this one as we are working for the animations in PR #2817. We can't give a delivery date as there is still a lot of work to do to get everything working without any regression.

If you are interested, you get the PR code locally and test it (by activating a flag, as described in the PR's documentation) and give us feedback.
