### ISSUE TITLE
Popover arrows missing after 6.0.1

### ISSUE THREAD

**Issue by stedel** [ng-bootstrap/ng-bootstrap#3653]
### Bug description:

6.0.1 seems to break Popover arrows pointing to the attached element.
6.0.1 seems to still apply the class, as the border, where the arrow should be, is different from the rest of the popover, when the placement is set to _right_ or _left_.
6.0.0 seems to render the arrow fine.

### Link to minimally-working StackBlitz that reproduces the issue:
(both are forked from https://ng-bootstrap.github.io/#/components/popover/examples )
6.0.0 (working arrows): https://stackblitz.com/edit/angular-qzprf6 
![image](https://user-images.githubusercontent.com/4320826/77318975-4d2d3700-6d0e-11ea-8056-9f240a935ec1.png)

6.0.1 (broken arrows): https://stackblitz.com/edit/angular-feegdc
![image](https://user-images.githubusercontent.com/4320826/77318894-2838c400-6d0e-11ea-862a-596f852e1ed3.png)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 9.0.7
ng-bootstrap: 6.0.1
Bootstrap: 4.4.1

**Comment by Smoggy** [comment]
Seems like it's caused by https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/util/positioning.ts#L150
in order to fix [#3640](https://github.com/ng-bootstrap/ng-bootstrap/issues/3640)

**Comment by maxokorokov** [comment]
Yikes, what a miss... thanks for reporting. Will revert #3644 in `6.0.2`

**Comment by stedel** [comment]
Thanks for the quick fix!
