### ISSUE TITLE
NgbModule has not been processed correctly by ngcc

### ISSUE THREAD

**Issue by Abdulrahman-Falyoun** [ng-bootstrap/ng-bootstrap#3666]
I am working on a new angular application, I've installed `ng-bootstrap` by using:

```
npm install --save @ng-bootstrap/ng-bootstrap
```

After adding `NgbModule` to `app.module.ts` I am getting the following error:

> ERROR in node_modules/@ng-bootstrap/ng-bootstrap/index.d.ts:20:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
> This likely means that the library (@ng-bootstrap/ng-bootstrap) which declares NgbModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
> 20 export declare class NgbModule {

```
Angular CLI: 9.1.0
Node: 12.16.1
OS: win32 x64
Ivy Workspace: Yes
npm: 6.13.4
"@ng-bootstrap/ng-bootstrap": "^6.0.2"
```

**Comment by maxokorokov** [comment]
@Abdulrahman-Falyoun please look at #3628. Most likely a caching issue.

**Comment by Abdulrahman-Falyoun** [comment]
@maxokorokov It does not solve the issue, I had to create another project and it works perfectly, so I don't know what was the problem with the old project but turning `strictTemplates` to `false` did not work for me

**Comment by Abdulrahman-Falyoun** [comment]
@maxokorokov It does not solve the issue, I had to create another project and it works perfectly, so I don't know what was the problem with the old project but turning `strictTemplates` to `false` did not work for me

**Comment by maxokorokov** [comment]
@Abdulrahman-Falyoun I'm sorry, I didn't get whether any of this worked:
- removing and reinstalling just `@ng-bootstrap/ng-bootstrap`
- removing and reinstalling `node_modules` completely

Also see similar issue for material, the discussion might help → https://github.com/angular/components/issues/18637

**Comment by Abdulrahman-Falyoun** [comment]
@maxokorokov clearing the `cache` and removing `node_modules` solved it, many thanks.

**Comment by kirstenfrager** [comment]
I am still experiencing this issue even after the above steps.

**Comment by anand94a** [comment]
The order in which I executed the commands within the project created are as follows:

>> ng add @ng-bootstrap/ng-bootstrap

>> npm install --save @ng-bootstrap/ng-bootstrap

It worked for me.

**Comment by benouat** [comment]
Closing for now as workaround proposed by @maxokorokov seems to work.

**Comment by israr2018** [comment]
I also faced the same issue , which took me quiet long time,  and then I solve it  with two steps.
1. npm clear cache -force
2. npm install 
@maxokorokov  thank you.

**Comment by shinde-prasad** [comment]
#3216 
`NgxFreshdeskWebwidgetModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. #3
`
I am facing this issue. any help is much appreciated.

https://github.com/AlisonVilela/ngx-freshdesk-webwidget/issues/3

**Comment by dexluce** [comment]
> #3216
> `NgxFreshdeskWebwidgetModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. #3 `
> I am facing this issue. any help is much appreciated.
> 
> [AlisonVilela/ngx-freshdesk-webwidget#3](https://github.com/AlisonVilela/ngx-freshdesk-webwidget/issues/3)

A bad import was provoking this on my side.
I was using:
`import { NgxMaskModule } from 'ngx-mask/lib/ngx-mask.module';`
instead of
`import { NgxMaskModule } from 'ngx-mask';`

I did (as proposed by israr2018)
`
npm clear cache -force
`
`
npm install
`

before fixing this import, so I'm not sure if related.

**Comment by mkubdev** [comment]
@dexluce Be aware with `npm clear cache --force`. It can rewrite your import and path of `package.json`..

**Comment by joanQz** [comment]
> > #3216
> > `NgxFreshdeskWebwidgetModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. #3 `
> > I am facing this issue. any help is much appreciated.
> > [AlisonVilela/ngx-freshdesk-webwidget#3](https://github.com/AlisonVilela/ngx-freshdesk-webwidget/issues/3)
> 
> A bad import was provoking this on my side.
> I was using:
> `import { NgxMaskModule } from 'ngx-mask/lib/ngx-mask.module';`
> instead of
> `import { NgxMaskModule } from 'ngx-mask';`
> 
> I did (as proposed by israr2018)
> `npm clear cache -force`
> `npm install`
> 
> before fixing this import, so I'm not sure if related.

Changing the import solved the issue for me. Many thanks

**Comment by ahmadshkour** [comment]
1- delete node_modules
2- npm clear cache -force
3- npm install 

worked for me

**Comment by surajtambe** [comment]
Build at: 2021-11-22T04:39:01.521Z - Hash: 5f450226a7993b9b - Time: 62877ms

Error: node_modules/@nrwl/angular/src/runtime/nx/nx.module.d.ts:7:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved 
to an NgModule class.

This likely means that the library (@nrwl/angular) which declares NxModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

7 export declare class NxModule {
                       ~~~~~~~~




** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


× Failed to compile.

Above issue is facing after nx migrate to latest while migrating to nx 13.2.1

**Comment by kkansh** [comment]
To Fix this problem you need to clean your local node module cache.
Run this cmd to fix this:

npm cache clean --force

Then reinstall your npm modules 

npm install

**Comment by rajuvats39** [comment]
'NgbModule' does not appear to be an NgModule class.(-996002)
index.d.ts(56, 28): This likely means that the library (@ng-bootstrap/ng-bootstrap) which declares NgbModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
