### ISSUE TITLE
Button UI state not updating correctly in Firefox

### ISSUE THREAD

**Issue by jenswet** [ng-bootstrap/ng-bootstrap#3668]
I created a toggle switch with the Button component.
Please see this Stackblitz: https://stackblitz.com/edit/angular-eonmyu
When clicking the Toggle Switch the UI is not updated at the first toggle action. When clicking multiple times the UI is updated correctly.
I have this issue only in Firefox. In Chrome and Safari everything seems to work from the first click.

I'd be very happy if someone can have look what's causing this and if it's my mistake or a bug in the component. Thanks in advance!

Angular: 9.1.0

ng-bootstrap: 6.0.2

Bootstrap: 4.4.1

**Comment by ankitkm418** [comment]
toggleInput(data:any) {    if(typeof data == 'boolean') {      this.toggle = data;    }

**Comment by jenswet** [comment]
> toggleInput(data:any) {    if(typeof data == 'boolean') {      this.toggle = data;    }

Except the rename of $event to data, thats the same as my code? Doesn't seem to change anything.

I did a new version which fixes most of the FF bug. But still sometimes it's not updating correctly when clicking many times. Chrome and Safari don't have the issues.
See the second example stackblitz https://stackblitz.com/edit/angular-fzqiwj

**Comment by maxokorokov** [comment]
Buttons were removed in v13 → https://ng-bootstrap.github.io/releases/12.x/#/components/buttons/overview
