### ISSUE TITLE
ngPagination margin

### ISSUE THREAD

**Issue by joaconigro** [ng-bootstrap/ng-bootstrap#3672]
### Bug description:
ngb-pagination has a bottom margin in ul element that sometimes breaks vertical align. In the StackBlitz example I'm using a select element to select page size. Vertical align is broken if following lines in css file are commented:

`
ngb-pagination ::ng-deep ul {
  margin-bottom: 0px;
}
`

If you uncomment this lines, bottom margin of ul is set to zero and then align works fine. Since ::ng-deep is deprecated I prefer to not use it.

"align-items: baseline;" can be used to align items, but ul still got margin-bottom: 1rem, and box looks missaligned.

Can this margin be removed, so we have better control of alignment?

Thank you so much!

### Link to minimally-working StackBlitz that reproduces the issue:
[https://stackblitz.com/edit/angular-itmgjg](https://stackblitz.com/edit/angular-itmgjg)

Angular: 9.1.1
ng-bootstrap: 6.0.2
Bootstrap: 4.4.1

**Comment by ktriek** [comment]
As a work around you can pass `mb-0` marigin with size as it will be added to ul's class.
```
<ngb-pagination ... size="sm mb-0" ... ></ngb-pagination>
```

[demo](https://stackblitz.com/edit/angular-itmgjg-eyu9kh)

**Comment by joaconigro** [comment]
Thank you @ktriek! That work around works fine. It's not much intuitive, but does the work.

I don't know if must close this issue or leave it open, in order to find a better solution.

And thanks to the team for all your hard work in this project.

Best regards, joaco

**Comment by benouat** [comment]
hey there,

event though @ktriek workaround is working, as @joaconigro said, it's not very intuitive.

I would suggest 2 different fixes/workarounds:

## first one: using Bootstrap

```html
<ngb-pagination ... class="mb-n3" ... ></ngb-pagination>
```

In Bootstrap world, spacing `3` correspond to `1em` which is the default margin bottom added by the CSS reset. So adding a negative margin `mb-n3` will compensate.

## second one: pure css

The other solution would be to add some global styling. I insist on **global** here so you don't have to use `::ng-deep`

You can put in your `styles.css`

```css
/* Will reset all pagination of the entire application */
ngb-pagination .pagination {
  margin-bottom: 0;
}
```

or

```html
<ngb-pagination ... class="custom" ... ></ngb-pagination>
```

```css
/* Will reset only pagination with class .custom */
ngb-pagination.custom .pagination {
  margin-bottom: 0;
}
```
