### ISSUE TITLE
Bootstrap CSS installation doc is wrong for CSS

### ISSUE THREAD

**Issue by benouat** [ng-bootstrap/ng-bootstrap#3676]
![image](https://user-images.githubusercontent.com/1152740/79313423-9aad5600-7f00-11ea-9bb4-83b6619b1791.png)

This **can't** simply work. It's not valid CSS

**Comment by benouat** [comment]
The only ways to add Bootstrap CSS in a CSS context is
- reference it from `node_modules` directly in `angular.json` `styles` section
- host it on the static part: put the `bootstrap.min.css` somewhere that your web server can serve it, and add it to the `index.html` template by referencing a `<link>`.
- you can also do the same step as above, but not host it, and reference it from a CDN directly.

**Comment by benouat** [comment]
Should be fixed by #3669

**Comment by maxokorokov** [comment]
Closed in #3684
