### ISSUE TITLE
Need aria-describedby on modal container

### ISSUE THREAD

**Issue by woehlck** [ng-bootstrap/ng-bootstrap#3678]
### Feature request:
This feature request is similar to https://github.com/ng-bootstrap/ng-bootstrap/issues/2472, but specific to modals. I would like to be able to set the aria-describedby property on a modal in addition to the aria-labelledby property.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.1.0

ng-bootstrap: 5.1.0

Bootstrap: 4.3.1

**Comment by pkozlowski-opensource** [comment]
Related: #2049
