### ISSUE TITLE
Automatic throw error and not compiled

### ISSUE THREAD

**Issue by ankitkm418** [ng-bootstrap/ng-bootstrap#3688]
To disable this warning use "ng config -g cli.warnings.versionMismatch false".
An unhandled exception occurred: Cannot find module 'source-map'
Require stack:
- C:\Users\arvind madhu\Desktop\2nd_batch\admin mod\node_modules\@angular-devkit\core\src\utils\template.js
- C:\Users\arvind madhu\Desktop\2nd_batch\admin mod\node_modules\@angular-devkit\core\src\utils\index.js
- C:\Users\arvind madhu\Desktop\2nd_batch\admin mod\node_modules\@angular-devkit\core\src\experimental\jobs\create-job-handler.js
- C:\Users\arvind madhu\Desktop\2nd_batch\admin mod\node_modules\@angular-devkit\core\src\experimental\jobs\index.js      
- C:\Users\arvind madhu\Desktop\2nd_batch\admin mod\node_modules\@angular-devkit\core\src\experimental.js
- C:\Users\arvind madhu\Desktop\2nd_batch\admin mod\node_modules\@angular-devkit\core\src\index.js
- C:\Users\arvind madhu\Desktop\2nd_batch\admin mod\node_modules\@angular-devkit\architect\src\architect.js
- C:\Users\arvind madhu\Desktop\2nd_batch\admin mod\node_modules\@angular-devkit\architect\src\index.js
- C:\Users\arvind madhu\Desktop\2nd_batch\admin mod\node_modules\@angular-devkit\build-angular\src\dev-server\index.js    
- C:\Users\arvind madhu\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\Users\arvind madhu\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\index.js- C:\Users\arvind madhu\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js
- C:\Users\arvind madhu\AppData\Roaming\npm\node_modules\@angular\cli\commands\serve-impl.js
- C:\Users\arvind madhu\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\arvind madhu\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\arvind madhu\AppData\Roaming\npm\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\arvind madhu\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js
- C:\Users\arvind madhu\AppData\Roaming\npm\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\arvind madhu\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\arvind madhu\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
See "C:\Users\arvind madhu\AppData\Local\Temp\ng-twsBKj\angular-errors.log" for further details.

**Comment by benouat** [comment]
We obviously can't do much with no context, and just a stack trace!

Thus, please, could you follow our Guide [You think you've found a bug](https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug) to open issue  next time ? Thx
