### ISSUE TITLE
How to use it with an hybrid ng1/ng8 application.

### ISSUE THREAD

**Issue by nishantwrp** [ng-bootstrap/ng-bootstrap#3689]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
I have a large hybrid ng1/ng8 application. Previously we used ui.bootstrap, now we want to migrate to ng-bootstrap. But just including the module in the appmodule don't seem to work. Is there something else to do.
```javascript
imports: [
    BrowserModule,
    HttpClientModule,
    NgbModule
  ],
```

### Link to minimally-working StackBlitz that reproduces the issue:

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 1.79/8

ng-bootstrap: 6

Bootstrap: 4.3.1

**Comment by maxokorokov** [comment]
@nishantwrp, "don't seem to work" is a bit vague :)

Please look once again at the [getting started section]( https://ng-bootstrap.github.io/#/getting-started) and provide more details. Also with v8 of Angular, you should be using ng-bootstrap v5

**Comment by benouat** [comment]
Closing as no update regarding a reproducible scenario via Stackblitz
