### ISSUE TITLE
RestoreFocus on IE11

### ISSUE THREAD

**Issue by r-ising** [ng-bootstrap/ng-bootstrap#3690]
### Bug description:

Hello @maxokorokov,

I created a StackBlitz, it's a problem of ie11, the restoreFocus isn't working very well there:

User Story:
The user click in an input field and on focus the datepicker will open, if the user want to type the date by keyboard, the datepicker will close, if the user pick a date by datepicker, the date picker close too.. It's a very nice user experience, because the user has more options.

It works without any problems in Chrome, Safari and Firefox but not in IE11. In IE11 the user can't enter a date by keyboard.

Maybe you can improve the IE11 support on the restore focus feature that it works like in Chrome, Firefox, etc..

Thanks,
Ramon

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-cn1jsd?file=src%2Fapp%2Fdatepicker-positiontarget.html

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 9

ng-bootstrap: 6

Bootstrap: 4.4

### Pull-Requests:

#3680

**Comment by maxokorokov** [comment]
@gpolychronis, could you please check this ?

**Comment by gpolychronis** [comment]
> 
> 
> @gpolychronis, could you please check this ?

Yes, I will have a look.

**Comment by gpolychronis** [comment]
The bug seems to be the following.

`.input-group > .form-control`

has the flex attribute:

`flex: 1 1 0%;`

Which should be:

`flex: 1 1 auto;`

instead. Trying to figure out a solution.

**Comment by peterblazejewicz** [comment]
I believe CDK has a special snip to cover focus issue, let me dig this, thx!

**Comment by gpolychronis** [comment]
Also, I haven't replicated any focus issues on latest ng-bootstrap version. The only issue seems to be the input.

**Comment by benouat** [comment]
Hey @r-ising, @gpolychronis 

I am looking at both this issue, the closed PR #3680 and the currently open PR #3732 and I must admit I am quite lost somewhere.
The issue raised here initially is not clear at all to me... I think I am confused with the _wording/terms_ used...

@r-ising what exactly is not working ? You referenced everything using `restoreFocus`

[`restoreFocus`](https://ng-bootstrap.github.io/#/components/datepicker/api#NgbInputDatepicker) as introduced in `5.2.0`  is about restoring focus when datepicker is closed to the element initially focused before opening.

> If true, when closing datepicker will focus element that was focused before datepicker was opened.

Reading the initial description leads me to think that when the datepicker is open, the user can't use the keyboard to type a date manually. If so, then it has nothing to deal with `restoreFocus` feature.

Am I right ?
