### ISSUE TITLE
[Feature Request] Carousel indicator custom controls

### ISSUE THREAD

**Issue by AchithaR** [ng-bootstrap/ng-bootstrap#3710]
It would be good to have option to add play/pause control icons before carousel indicators. Is there any way we can place play/pause icons before indicators?

**Comment by benouat** [comment]
Hey @AchithaR !
Did you had a look at the [Pause/cycle](https://ng-bootstrap.github.io/#/components/carousel/examples#pause) examples in the demos ?

You could create your custom controls and put them over the Carousel with a few lines of CSS.
Adding such a feature would not be that valuable. It's already doable with no pain.

Would it be enough for you ?

**Comment by AchithaR** [comment]
Thank you!
