### ISSUE TITLE
Private APIs should not be used for the ng add schematic

### ISSUE THREAD

**Issue by SchnWalter** [ng-bootstrap/ng-bootstrap#3714]
### Bug description:

The `ng add` schematic imports code from `@schematics/angular/utility/project`, which is a private file that will be removed in https://github.com/angular/angular-cli/pull/17597

You can follow https://github.com/angular/angular/pull/36897 and https://github.com/angular/components/pull/19229, which provide fixes for similar issues with `ng add @angular/localize` and `ng add @angular/cdk`

**Comment by gpolychronis** [comment]
@SchnWalter Where have you found that? Can you please provide which command have you executed so that ng-bootstrap uses from file @schematics/angular/utility/project ? Is there any file or log I can see this import?
Kind regards,

**Comment by devoto13** [comment]
https://github.com/ng-bootstrap/ng-bootstrap/blob/master/schematics/ng-add/index.ts#L8

**Comment by SchnWalter** [comment]
In the 2nd comment from the first link you'll find this:
> https://github.com/ng-bootstrap/ng-bootstrap/blob/master/schematics/ng-add/index.ts#L8

It's the schematics for `ng add`, which is the fist command from the "Installation" section:
> https://github.com/ng-bootstrap/ng-bootstrap#installation
