### ISSUE TITLE
Version 6 breaks accordians with <div> tags

### ISSUE THREAD

**Issue by grosch** [ng-bootstrap/ng-bootstrap#3717]
### Bug description:

After upgrading to version 6 I'm no longer able to use a div tag inside the ngb-accordion.  I need to include a div because my ngb-panel are constructed from a `FormArray`, and I want to conditionally show them.  Since Angular won't let us put both an `*ngFor` and an `*ngIf` on the same element I need a div line in there.

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-xvehuq

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 9.1.4

ng-bootstrap: 6.1.0

Bootstrap: 4.3.1

**Comment by IAfanasovMob** [comment]
I see several possible solutions here.
This one should work for sure
```
<ngb-panel *ngFor="let subspace of formArray.controls.find(x=> /that if condition here/ ); index as i">
```

This one I'm not sure
```
<ng-container *ngFor="let subspace of formArray.controls.find(x=> /that if condition here/ ); index as i">
<ngb-panel *ngIf="condition here">
.....
</ngb-panel>
<ng-container>
```

I'm sorry, I can not test it now. Please let me know if this resolves you case.

**Comment by maxokorokov** [comment]
Looks more like an Angular issue to me. If you disable `ivy` in stackblitz settings your code works fine:

![Screen Shot 2020-05-05 at 12 17 47](https://user-images.githubusercontent.com/8074436/81056248-7bd02d00-8eca-11ea-935f-d153e7d3adbe.png)

Having said that, I agree with @IAfanasovMob that you should not use a `div` here. Why would you create an intermediate element for nothing?

I suggest you use `ng-template` or `ng-container`:

https://stackblitz.com/edit/angular-xvehuq-s5jjuz?file=src/app/accordion-basic.html

**Comment by pkozlowski-opensource** [comment]
> I don't think we will be fixing anything on our side, but still need to check why the behaviour is different.

It is a known change of behaviour in Angular v9 with ivy. The content children queries are shallow by default and a `<div>` is blocking a query from descending. Behaviour before Angular v9 is considered a bug.

There is no further action in ng-bootstrap nor Angular - we consider change of behaviour as a bug fix. Closing this issue given explanation.

**Comment by grosch** [comment]
@IAfanasovMob Thanks, that was how I solved it.
