### ISSUE TITLE
Carousel lacks sliding animation.

### ISSUE THREAD

**Issue by foo-baar** [ng-bootstrap/ng-bootstrap#3718]
### Bug description:
I know this has been logged and followed at multiple places however there isn't any good conclusion giving any sense of direction.

### Link to minimally-working StackBlitz that reproduces the issue:
https://ng-bootstrap.github.io/#/components/carousel/examples 
none of the example has details or implementation of slide-in effect/

### Versions of Angular, ng-bootstrap and Bootstrap:
Angular: ng-9
ng-bootstrap: 6.0.0
Bootstrap: 4.4 

If already resolved then please post a working sample link here so the seekers don't end up switching to other libraries.

**Comment by maxokorokov** [comment]
I'll leave this open, even there is a more generic issue open. 

The PR at works is #2817, it will be split in multiple smaller per-component PRs. I'll link it here, once the carousel one is available. Should be released in the next major release.

**Comment by foo-baar** [comment]
> I'll leave this open, even there is a more generic issue open.
> 
> The PR at works is #2817, it will be split in multiple smaller per-component PRs. I'll link it here, once the carousel one is available. Should be released in the next major release.

Thanks @maxokorokov, any idea on the timeline for next release?

**Comment by foo-baar** [comment]
While it's underdevelopment if anyone comes here looking for the same, this solution works well: https://stackoverflow.com/questions/57131765/customise-ng-bootstrap-carousel-in-angular/57134727?noredirect=1#comment108982927_57134727

**Comment by gotsanity** [comment]
I attempted to utilize that workaround and encountered an odd problem. The only slide that allows click events and mouseovers is the final slide so ymmv. I love the effect but it isnt going to work for me due to needing buttons and mouseovers in my slides.

**Comment by maxokorokov** [comment]
Closed by #3804
