### ISSUE TITLE
entryComponents + modals

### ISSUE THREAD

**Issue by ravtakhar** [ng-bootstrap/ng-bootstrap#3722]
Hey guys,

Sorry I have a question regarding the entryComponents and Angular 9. Is it still necessary to add modals to the entryComponents under your module(s) because everything seems to be working correctly when I take them out. 

I was looking through the examples on the main site; noticed they have been updated to utilize Angular 9 but are still using the entryComponents piece when dealing with modals.

Thanks!

**Comment by jnizet** [comment]
Good catch. No, it's not necessary if you use Ivy (which is the default in Angular 9).
I'll open a PR to improve the explanations.

**Comment by ravtakhar** [comment]
@jnizet just curious how are modals able to be referenced across modules and components need to be exports/imported cross module.

**Comment by SystemR** [comment]
I just noticed this myself when I forgot to add to entryComponents. This is awesome! I think it should be added in https://ng-bootstrap.github.io/#/components/modal/examples
> You can pass an existing component as content of the modal window. In this case remember to add content component as an entryComponents section of your NgModule.

and add a note that it's no longer necessary for ivy.
