### ISSUE TITLE
Can't customize month view month and day display without overriding whole month template

### ISSUE THREAD

**Issue by brandonpittman** [ng-bootstrap/ng-bootstrap#3728]
https://github.com/ng-bootstrap/ng-bootstrap/blob/ea59f8829f099801df34f15b77a9e06a51f2a110/src/datepicker/datepicker-navigation.ts#L29

For Japanese, the year needs to come before the date and currently, the only way to do that is to rewrite the whole month template.

**Comment by maxokorokov** [comment]
@brandonpittman indeed, looks like an unfortunate omission... thanks for reporting it.

I can't come up with a quick solution for this, apart from introducing another template similar to `[dayTemplate]` that will have `month` and `year` in the context.

```html
<ng-template #m let-year="year" let-month="month">
  <!-- generate the date string as necessary or just inverse the default one: -->
  {{ dp.i18n.getYearNumerals(year) }} {{ dp.i18n.getMonthFullName(month, year) }}
<ng-template>

<input #dp="ngbDatepicker" [monthNameTemplate]="m"></input>
```

Or maybe introduce another method in `NgbDatepickerI18n`...

**Comment by brandonpittman** [comment]
@maxjoehnk thanks. I’m really hoping to avoid rewriting a month template from scratch tomorrow at work.

**Comment by maxokorokov** [comment]
Also keep in mind that month template override won't work with the `NgbInputDatepicker` (the one with the popup) as of today, only for the inline. It **might** be fixed in the next feature release.

**Comment by brandonpittman** [comment]
@maxokorokov Yeah, that was what I was thinking. I’d have to override so much to use it the way I want to. 

And sorry about using the wrong handle.
