### ISSUE TITLE
multiple components with same ngbdatepicker

### ISSUE THREAD

**Issue by kernyden** [ng-bootstrap/ng-bootstrap#3733]
`.toggle()` doesnt close the previous opened datepicker window (working with multiple datepicker components)

**_to reporoduce_**:

1. click on left button - it opens first window 
2. click on right button - it opens second window and doesnt close the previous

[stackblitz](https://stackblitz.com/edit/angular-ivy-8mgnwf?embed=1&file=src/app/datepicker-adapter/datepicker-adapter.component.html)

**Comment by jnizet** [comment]
It does. But your two datepickers have the same `positionTarget` element, so they both open themselves exactly at the same place.

Here's your stackblitz with two different `positionTarget`: https://stackblitz.com/edit/angular-ivy-d8dprn?file=src/app/random-component/random-component.component.html

as you can see, one closes when the other is opened.

**Comment by kernyden** [comment]
@jnizet but i want to open em relative to the same parent component, and get link to parent as input..Is it possible?

**Comment by jnizet** [comment]
Well, you *are* opening them relative to the same parent. And that's precisely why they open at the same place. I'm not sure what you mean by "get link to parent as input".

**Comment by kernyden** [comment]
as i said, i need to open two separate datepicker components relative to 1 same single parent. But not what u did - 1 parent div for each component

```
-- parent #parent
   -- child date [ref]="parent"
   -- child date [ref]="parent"
```

**Comment by benouat** [comment]
@kernyden  Did you know we have a `positionTarget` input on `ngbInputDatepicker` ?

> A css selector or html element specifying the element the datepicker popup should be positioned against.
>
> By default the input is used as a target.

It might actually be what you are looking for. Try to reference your parent div in here.

**Comment by kernyden** [comment]
@benouat ye, i tried, but in some cases it "doesnt work well with" and looks like it very sensitive to higher position-relative containers. Im sure `cdk dnd` with it `pointer-events styles` the reason why.
