### ISSUE TITLE
Accessibility support for NgbDropdown in 2.0.0 version of ng-bootstrap

### ISSUE THREAD

**Issue by pradeepKaatnam-ms** [ng-bootstrap/ng-bootstrap#3734]
### Bug description:
We are currently using 2.0.0 version of ng-bootstrap in our project and there is no accessibility support (via up and down arrows) for NgbDropdown in that version. I know that the same is supported from 4.1.0 via NgbDropdownItem.

We are looking for that support in 2.0.0 itself as upgrading will require lot of effort than fixing this one bug.

Angular: All versions

ng-bootstrap: 2.0.0

Bootstrap: 4.1.1

**Comment by pkozlowski-opensource** [comment]
> We are looking for that support in 2.0.0 itself as upgrading will require lot of effort than fixing this one bug.

Sorry, we are not back-porting new features to such old version of this library. You will have to either upgrade or fork this library and cherry pick what you need.
