### ISSUE TITLE
Required parameter not working for button groups

### ISSUE THREAD

**Issue by andreas-aeschlimann** [ng-bootstrap/ng-bootstrap#3738]
### Bug description:

I would like to mark buttons as required. The `required` parameter for the input fields is ignored in a button group. I would expect that a form is invalid when a (radio) button is required and not selected (yet).

### Link to minimally-working StackBlitz that reproduces the issue:

Here you see an example that shows a radio button group with none selected. The form is valid even though the radio inputs are marked as required

https://stackblitz.com/edit/angular-9-starter-vxorrr

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 9.0
ng-bootstrap: 6.1

**Comment by jnizet** [comment]
The `required` attribute/directive must be put on the element that also has the `ngModel` directive. Not on each radio input. Here's your modified stackblitz: https://stackblitz.com/edit/angular-9-starter-enma4x?file=src/app/app.component.html, which works as expected.

**Comment by andreas-aeschlimann** [comment]
> The `required` attribute/directive must be put on the element that also has the `ngModel` directive. Not on each radio input. Here's your modified stackblitz: https://stackblitz.com/edit/angular-9-starter-enma4x?file=src/app/app.component.html, which works as expected.

Interesting, thanks for your input. I wasn't expecting that, while it indeed makes sense!

**Comment by benouat** [comment]
Closing as apparently there is no issue anymore! Thanks @jnizet

**Comment by andreas-aeschlimann** [comment]
> Closing as apparently there is no issue anymore! Thanks @jnizet

Yes, no worries. Is this something that should be in the docs? For normal forms, the required parameter would go to the input tag (I think).
