### ISSUE TITLE
Override popover's inline transform: translate() function's x-value

### ISSUE THREAD

**Issue by Gourav102** [ng-bootstrap/ng-bootstrap#3743]
I have an issue in positioning of popover. When I click on trigger button, it sets the `transform: translate(x, y)` using inline CSS. As displayed in the GIF below, y-value is set as required. But, for x-value, it is unnecessarily going inside the left panel. I want to override x-value with 0 and also want to set the popover arrow relevant to the trigger button and not at center.

**Angular**: 8.2.14

**Bootstrap**: 4.3.1

**ng-bootstrap**: 5.3.0

![popover-positioning-issue](https://user-images.githubusercontent.com/23277581/82643980-303db300-9c2e-11ea-8d7e-c164a37af521.gif)

**Comment by benouat** [comment]
Hey @Gourav102 

Can you tell me which `placement` are you using ? Playing with it might solve your issue.
You can also have a look at `container` and specify `[container]="'body'"`, hence the popover will be displayed on top of your panels.

**Comment by Gourav102** [comment]
Hi @benouat, I have added Angular, Bootstrap and ng-bootstrap library versions in the issue.

I was using `[placement]=" 'auto' "`, I changed it to `[placement]="['top-left', 'bottom-left']"`, it worked poperly. But it has lagging transform animation which first time aligns it at the top even though trigger is close to top of window and there is no place to display popover completely. But it somehow gets aligned properly on mousemove event.

I also face issues in nested popover. The child popover is behaving weirdly and does not gets aligned based on the available space. It's trigger button and it's tooltip triangle are not always close to each other. On scroll, the tooltip is moving to top while trigger button is at the bottom

**Comment by benouat** [comment]
> But it has lagging transform animation which first time aligns it at the top

First time I see this kind of _bug_. We need to figure out what's going on here.

> I am also facing issues in nested popover

I know it's not always doable, but I would strongly suggest **not** to use this pattern! It's bad in terms of UX and can lead to a lot of nasty side-effects as you can notice.

Did you also try `[container]="'body'" as I suggested ? For the nested situation, I think you would be forced to use it.

**Comment by NJDevel** [comment]
I have similar situation where the popover for tooltip is generating below css, pushing the tooltip offscreen, especially in smaller devices:

`position: absolute; top: 0px; left: 0px; will-change: transform; transform: translate(-67px, 656px);`

Angular: 11.2.0
Bootstrap: 4.3.1
ng-bootstrap: 4.1.0

I have tried `[container]="'body'"` and playing around with different placements (i.e. auto, bottom, top-right, etc.) as well, but have not been able to change the -67px automatically generated in the tooltip's `transfrom:translate(x,y).`

**Comment by geesalasandeep** [comment]
hello,
 I have similar situation where the popover for tooltip is generating default and in negative x axis in the transform, pushing the tooltip offscreen.
have get any solution for this bud ?

**Comment by fbasso** [comment]
@NJDevel, now we use popperjs to position elements, which fixed a lot of positioning issues.

Could you please try again with the latest version of ngBootstrap (13.1.0) ?

**Comment by maxokorokov** [comment]
Closing as no response, please reopen if necessary.

**Comment by Janatbek** [comment]
same issue here, 
![image](https://user-images.githubusercontent.com/16279325/213361550-9327ec5a-770a-4233-9ff3-18f82c196665.png)
the title and close button is under the header. 
should I create new issue?
