### ISSUE TITLE
TypeAhead need to trigger a function after select the item

### ISSUE THREAD

**Issue by naveenroy001** [ng-bootstrap/ng-bootstrap#3750]
I am working on Autosuggestion but after selecting the item, I need to push the selected item to the JSON Array. So is there any function that triggers after select the item?
I have used this but it's not permitting to call any function or push item to JSON Array

**HTML**
`
<input id="typeahead-prevent-manual-entry"  type="text" class="form-control" [(ngModel)]="searchUser"
                            [ngbTypeahead]="searchAttendee"  [inputFormatter]="inputFormat" [resultFormatter]="resultFormat"  />
`

**TS**
`inputFormat(value: User){
  this.searchUserList.push(this.searchUser);
  return "";
}`

**Comment by jnizet** [comment]
The NgbTypeahead directive has a `selectItem` output. See [the documentation](https://ng-bootstrap.github.io/#/components/typeahead/api#NgbTypeahead)

**Comment by naveenroy001** [comment]
Actually I was using only function without event parameter. I was thinking that data will assign on the model so It was not working 

Now it is working by this

**HTML**

`
<input id="typeahead-prevent-manual-entry"  (selectItem)="selectedItem($event)"  type="text" class="form-control" [(ngModel)]="searchUser"
                            [ngbTypeahead]="searchAttendee"  [inputFormatter]="inputFormat" [resultFormatter]="resultFormat"  />
`

**TS**
`selectedItem(item){
  let isSame = false;
  this.searchUserList.some(function(v) {if(v.id == item.item.id) isSame = true;});
  if(!isSame) this.searchUserList.push(item.item);
}`

Thanks, Team.
