### ISSUE TITLE
NgbDropdown attached to body tabindex issue

### ISSUE THREAD

**Issue by anton-gorbikov** [ng-bootstrap/ng-bootstrap#3758]
### Bug description:

NgbDropdown used in conjunction with `container="body"` breaks TAB keyboard navigation. Steps:

1. Get first toggle button focused using TAB button
1. Press ENTER to open the dropdown
1. Press TAB

Expected result: first item from the list should be focused
Actual result: the second dropdown toggle is focused

### Link to minimally-working StackBlitz that reproduces the issue:

[StackBlitz link](https://stackblitz.com/edit/angular-9prhp8) - this is fork of [basic dropdown demo](https://ng-bootstrap.github.io/stackblitzes/dropdown/basic/stackblitz.html) with only one attribute added

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 9.0.7

ng-bootstrap:

Bootstrap: 6.1.0

**Comment by benouat** [comment]
Hey @anton-gorbikov 

Thank you to report this issue.
You're right, this is something we don't handle at all. I am afraid it will impact all widgets using the `container` @Input where we can set `body`.

We should think about a fix that would work whatever the widget using it.

**Comment by benouat** [comment]
Hey @anton-gorbikov, sorry for the long time no response.

Would you mind testing again with a recent version ? We fixed some issues related to that in `v7`

**Comment by anton-gorbikov** [comment]
Hi @benouat , it looks like it's working fine in the most recent version! Thanks a lot!
