### ISSUE TITLE
ngb-toast doesn't work properly in Edge (Chromium edition)

### ISSUE THREAD

**Issue by arsalans** [ng-bootstrap/ng-bootstrap#3762]
### Bug description:
I have a service developed for sending toasts. Its working fine in Chrome, however when I use it in the latest Edge browser (chromium edition), there is a weird problem. The first toast seems to not show up at all. When you send the second toast, only then the first one appears, followed by the second one.

Note, I have seen this problem only when using EventSource. If I am using httpClient then toasts appear OK in Edge as well.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.14

ng-bootstrap: 5.3.1

Bootstrap: 4.3.1

**Comment by benouat** [comment]
Thank you @arsalans for reporting a potential bug.

Nonetheless, according to our documentation [You think you've found a bug](
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug) could you please reproduce your scenario in a minimalist Stackblitz in order for us to start working on it ?

**Comment by benouat** [comment]
Ok, I think I see something.
I am not sure at all that EventSource is actually patched by zonejs. It would though explain why it's not working as expected, or at least de-sync.

Could you try to run put your code in `zone.run()` ?
Like this

```typescript
const vinResponseObservable = new Observable((observer) => {
    this.eventSource = new EventSource("my url");
    this.eventSource.onmessage = (event) => {
        const json = JSON.parse(event.data);
        this._zone.run(() => {
            observer.next(json);
        });
    };

    this.eventSource.onerror = (error) => {
        if (this.eventSource.readyState === 0) {
            console.log("The stream has been closed by the server.");
        } else {
            this._zone.run(() => {
                observer.error("EventSource error: " + error);
            });
        }
    };
});
```

**Comment by arsalans** [comment]
Hi @benouat Thank you. I injected NgZone service and ran the observer under _zone.run and it solved the problem. Any insight as to what this bug is and who is supposed to fix this?

**Comment by benouat** [comment]
I don't know who is supposed to fix it. Probably Angular team as they are maintaining Zone.js
The bug is simply that Angular is not "aware" of the events coming from EventSource as it is not patched by Zone.js (zone is what is used internally for the entire change detection to work, hence for the UI to be refreshed...)

Hope it helped
Closing it.
