### ISSUE TITLE
ngbTooltip Hover is changing element properties (padding)

### ISSUE THREAD

**Issue by ricardosaracino** [ng-bootstrap/ng-bootstrap#3765]
### Bug description:

Tooltip collapsing padding

![image](https://user-images.githubusercontent.com/759253/84266373-6023fc00-aaf2-11ea-915c-aac6851d5ea6.png)

![image](https://user-images.githubusercontent.com/759253/84266416-703bdb80-aaf2-11ea-98b0-bdcfbeea49c1.png)

```
           <a class="btn btn-outline-primary" i18n-ngbTooltip ngbTooltip="Edit "
                 routerLink="/observation/{{observation.id}}" type="button">
                <i class="fa fa-edit"></i>
              </a>
              <a class="btn btn-outline-primary" i18n-ngbTooltip ngbTooltip="View "
                 routerLink="/observation/{{observation.id}}" target="_blank" type="button">
                <i class="fa fa-external-link"></i>
              </a>

```

### Link to minimally-working StackBlitz that reproduces the issue:

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:
    "@angular/core": "~9.1.3",

ng-bootstrap:
    "@ng-bootstrap/ng-bootstrap": "^6.1.0",

Bootstrap:

**Comment by benouat** [comment]
Hey @ricardosaracino 

Thanks to report what seems to be an issue! But unfortunately it's not :(
Let me explain, the _bug_ you are witnessing here is related to how white spaces are rendered as inline elements

When the tooltip is created it is appended as a sibling to the host element, hence removing (in terms of nodes) or inserting itself before white spaces (a line break between elements in the HTML source is a white space, and then treated as inline element).

We had this exact same issue by the past in the demo website itself. And for that, we had to think twice about how to design the demo to **not** have this weird behaviour.

Have a look at [Internet archive](https://web.archive.org/web/20170910221604/https://ng-bootstrap.github.io/#/components/tooltip/examples) just try to play with first demo, you'll see it right away.

Conclusion is that our widget **is not** eating space, **nor** changing properties, it's the browser itself that renders things in a way we might be aware of in the first place. (Try to google "browser line breaks as white space")

I'll then close the issue, hoping my explanations are clearing a bit things out!

**Comment by ricardosaracino** [comment]
Thanks, i did work around fine. 

```html
  <button class="btn btn-outline-primary mr-2" i18n-ngbTooltip ngbTooltip="Edit eSOR"
                      routerLink="/observation/{{observation.id}}" type="button">
                <i class="fa fa-edit"></i>
              </button>
              <button class="btn btn-outline-primary mr-2" i18n-ngbTooltip ngbTooltip="View eSOR"
                      (click)="openReportModal(observation.id)" type="button">
                <i class="fa fa-external-link"></i>
              </button>
              <a class="btn btn-outline-primary" href="{{apiUrl}}/api/observations/{{observation.id}}/pdf"
                 i18n-ngbTooltip ngbTooltip="Print eSOR" target="_blank">
                <i class="fa fa-file-pdf-o"></i>
              </a>
```
