### ISSUE TITLE
Typeahead z-index problem when used inside Modal

### ISSUE THREAD

**Issue by hughanderson4** [ng-bootstrap/ng-bootstrap#3778]
### Bug description:

When using `container="body"` on Typeahead, and placing Typeahead inside Modal, I am seeing the Typeahead's dropdpown appear behind the Modal in the z-index order. (Typeahead dropdown z-index is 1000 while Modal is 1050).

Please see the attached Stackblitz.

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-7dfepa

1. Open the modal by clicking "Launch Demo Modal"
2. Interact with the first Typeahead (type "te") - notice it works fine
3. Interact with the second Typeahead (type "te") - noticed there is no dropdown visible on the screen.  Using Chrome Element Inspector we can see that the `<ngb-typeahead-window>` appended to body has a class of `.dropdown-menu` setting the `z-index` of 1000 (below the modal of 1050).
4. Push down arrow key of keyboard, then enter key of keyboard, to select invisible 1st option of Typeahead.
5. Interact with the Dropdown, notice it works correctly, this also is using `container="body"`, I see a dynamically added z-index on the element style, presumably by ngb code.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 9.1.0

ng-bootstrap: 6.1.0

Bootstrap: 4.3.0

### Thanks

Thank you team, we ❤️ ng-bootstrap lib!

**Comment by hughanderson4** [comment]
As a temporary workaround, I am applying the following CSS at the global level
```css
ngb-modal-window + ngb-typeahead-window.dropdown-menu {
    z-index: 1051;
}
```

**Comment by benouat** [comment]
Thanks to report this issue.
Nonetheless, I am afraid we can't afford a fully dynamic `z-index` engine whenever we are using `container: body`. It's a kind of pandora box, with a never ending story outcome...

Your workaround seems fine to me for now.
Thus, I'll close the issue as we probably won't fix anything here. Sorry

**Comment by Jacobra93** [comment]
This workaround is not working for me, is there a different one or are y'all going to address this issue in the future? It seems pretty important to be able to use this inside a modal.

**Comment by dexluce** [comment]
> This workaround is not working for me, is there a different one or are y'all going to address this issue in the future? It seems pretty important to be able to use this inside a modal.

Hello @Jacobra93 
The `ngb-modal-window + ngb-typeahead-window` selector is: "Pick the first ngb-typeahead-window directly after ngb-modal-window". Which means this selector will apply only if you have this in your body:
```
<ngb-modal-window>....</ngb-modal-window>
<ngb-typeahead-window>...</ngb-typeahead-window>
```

If you have for example:
```
<ngb-modal-window>...</ngb-modal-window>
<div>...</div>
<ngb-typeahead-window>...</ngb-typeahead-window>
```
This selector won't work. For a few cases, I had to adapt my selector a little bit too:
```
body > ngb-typeahead-window.dropdown-menu.show {
  z-index: 1051;
}
```
This is "take all ngb-typeahead-window with a .dropdown-menu and a .show class, only if the ngb-typeahead-window is a direct child of body". This should work all the time if you add container="body" on your typeahead.

**Comment by eliprand** [comment]
@benouat would you consider adding an option for a custom CSS class to be applied to that `ngb-typeahead-window` ? similar to the `windowClass` on the Modal control. With that, we could set the z-index on the typeahead inside our modal as-needed without having to influence all typeaheads as is the case with the workaround.
I would be happy to work on the implementation if that's something that could be considered.
Merci ;)
