### ISSUE TITLE
Link in Accordion Title

### ISSUE THREAD

**Issue by projectX21** [ng-bootstrap/ng-bootstrap#3779]
Since the accordion panel title will always created as a button, it isn't possible to create a link inside it.
This works however in Chrome, FF and Edge, but not in IE 11. It isn't possible to get redirected to the link. Even though it isn't valid html anymore.

Is there any option to create a link inside the panel title?

**Comment by jnizet** [comment]
We have a demo showing how tocreate custom headers: you can choose to have anything you want in the header.
See https://ng-bootstrap.github.io/#/components/accordion/examples#header

**Comment by maxokorokov** [comment]
@projectX21 please check the demo @jnizet suggested and also you can check this issue → https://github.com/ng-bootstrap/ng-bootstrap/issues/3104#issue-429256214
