### ISSUE TITLE
Dropdown does not autoclose, throwing: Object doesn't support property or method 'closest'

### ISSUE THREAD

**Issue by Istanful** [ng-bootstrap/ng-bootstrap#3783]
### Bug description:
When I open a dropdown with autoclose and then click on the scrollbar in edge, an error is thrown in the console. It throws the error `Object doesn't support property or method 'closest'`. It is thrown because the element in `event.target` is `HTMLDocument` which does not support the `closest` method.

### Link to minimally-working StackBlitz that reproduces the issue:
StackBlitz: https://angular-dpdswh-r6tj5y.stackblitz.io

1. Open the StackBlitz in `Edge 44.18362.449.0`.
2. Open the dropdown by clicking on it. Click on the scrollbar.
3. The dropdown does not close. An error is thrown in the console.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.13

ng-bootstrap: 4.2.2

Bootstrap: 4.3.1

Browser: Edge 44.18362.449.0, EdgeHTML 18.18362

**Comment by benouat** [comment]
Hey @Istanful 
thanks to report this issue!

I we refer to [browser support](https://angular.io/guide/browser-support) page on angular.io for v8, only the 2 most recent major versions of Edge are supported.

With the release of Chromium based Edge back in January, I would say that we don't support EdgeHTML anymore...

**Comment by Istanful** [comment]
@benouat 

Thank you for the swift answer! Makes perfect sense. 

About 60% of the application I'm working on uses those old Edge versions, which of course is a shame. Because of that I will have to do some kind of workaround. Do you know of any specific settings I can use that will circumvent this issue?

The current solution would be to write a custom auto close strategy and disable yours entirely. :/

**Comment by benouat** [comment]
I would suggest to use a polyfill 🙂 Way much easier.

You can have a look at this [MDN](https://developer.mozilla.org/fr/docs/Web/API/Element/closest) page

**Comment by benouat** [comment]
oohhh my bad!
I did not read carefully your issue description!!

EdgeHTML actually do support closest 😄 It's only when you click on the scrollbar.
Right, then you might have spotted a bug in a sense, that we should discard doing the call to closest if `event.target` is `document`.

Sorry for that.
We'll have a look

**Comment by Istanful** [comment]
@benouat Cool! I will make an attempt on a PR if you don't get to it first. :)

**Comment by Istanful** [comment]
@benouat I made a pull request for this. The only different is that `closest` returns null for document. Apart from the automatic tests I tested in `44.18362.449.0` and `Chrome 83.0.4103.106`. :)
