### ISSUE TITLE
`ng add @ng-bootstrap/ng-bootstrap` fails in Angular CLI 10.0.0

### ISSUE THREAD

**Issue by chenfiona** [ng-bootstrap/ng-bootstrap#3788]
### Bug description:

> The system throws error during ng-bootstrap installation:
```
[error] Error: Cannot find module '@schematics/angular/utility/project'
Require stack:
- C:\angular\gis-semantics-framework\node_modules\@ng-bootstrap\ng-bootstrap\schematics\ng-add\index.js
- C:\angular\gis-semantics-framework\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\angular\gis-semantics-framework\node_modules\@angular-devkit\schematics\tools\index.js
- C:\angular\gis-semantics-framework\node_modules\@angular\cli\utilities\json-schema.js
- C:\angular\gis-semantics-framework\node_modules\@angular\cli\models\command-runner.js
- C:\angular\gis-semantics-framework\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\fiona\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\fiona\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\angular\gis-semantics-framework\node_modules\@ng-bootstrap\ng-bootstrap\schematics\ng-add\index.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at new ExportStringRef (C:\angular\gis-semantics-framework\node_modules\@angular-devkit\schematics\tools\export-ref.js:19:25)
    at NodeModulesEngineHost._resolveReferenceString (C:\angular\gis-semantics-framework\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:95:21)
    at NodeModulesEngineHost.createSchematicDescription (C:\angular\gis-semantics-framework\node_modules\@angular-devkit\schematics\tools\file-system-engine-host-base.js:174:34)
    at SchematicEngine.createSchematic (C:\angular\gis-semantics-framework\node_modules\@angular-devkit\schematics\src\engine\engine.js:220:38)
    at CollectionImpl.createSchematic (C:\angular\gis-semantics-framework\node_modules\@angular-devkit\schematics\src\engine\engine.js:70:29)
```

### Versions of Angular, ng-bootstrap and Bootstrap:
```
Angular CLI: 10.0.0
Node: 12.18.0
OS: win32 x64

Angular: 10.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.1000.0
@angular-devkit/build-webpack     0.1000.0
@angular-devkit/core              10.0.0
@angular-devkit/schematics        10.0.0
@ngtools/webpack                  10.0.0
@schematics/angular               10.0.0
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0
```

**Comment by Hypenate** [comment]
I think it's related to #3787

**Comment by chenfiona** [comment]
Problem of Angular CLI 10.0.0:

> _Severity_ -> **Warning**
`Experimental support for decorators is a feature that is subject to change in a future release. Set the ‘experimentalDecorators’ option to remove this warning.`
This warning pops up as soon as I import the Angular project into IDE.
_Workaround_ -> **tweak tsconfig.json**
`  "compilerOptions": {
    "experimentalDecorators": true,}`
This negates the stated: `Starting with version 10 you will see a new tsconfig.base.json. This additional tsconfig.json file better supports the way that IDEs and build tooling resolve type and package configurations.`

> _Severity_ -> **High**
`>**npm install @ng-bootstrap/ng-bootstrap**
npm WARN @ng-bootstrap/ng-bootstrap@6.1.0 requires a peer of @angular/common@^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@6.1.0 requires a peer of @angular/core@^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@6.1.0 requires a peer of @angular/forms@^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@6.1.0 requires a peer of @angular/localize@^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@6.1.0 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
`
_Workaround_ -> tweak the **package.json**, change 10.x.x to 9.x.x:
` 
 "dependencies": {
    "@angular/common": "~10.0.0",
    "@angular/compiler": "~10.0.0",
    "@angular/core": "~10.0.0",
    "@angular/forms": "~10.0.0",
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.0",
    "@angular/cli": "~10.0.0",
    "@angular/compiler-cli": "~10.0.0",
`
Result:   ng-bootstrap is **seemingly** installed, but the Ngb modules don't work.
_Further Workaround_ -> tweak the **polyfills.ts**:
_This is missing in CLI 10.0.0_ -> ` import '@angular/localize/init'; `

>  _**Severity**_ -> **Showstopper**
`ng-bootstrap` **seemingly** functioned, but all of the styling goes awry. UI looks like the aftermath of wreaked plastic surgery.  
_**Solution**_ ->  Complete uninstall and clean CLI 10.0.0, install CLI 9.1.8., migrate project.

**Comment by coderhh** [comment]
Got the same issue. Have to downgrade angular cli to 9.18.

**Comment by darielvicedo** [comment]
Not fixed in Angular CLI 10.0.1

**Comment by thanh-guong** [comment]
Same problem here :(

**Comment by parvezshah** [comment]
the problem has reappeared in
Angular CLI: 11.0.3
Node: 15.3.0
OS: Linux
[2020-12-07T19_22_21_021Z-debug.log](https://github.com/ng-bootstrap/ng-bootstrap/files/5654874/2020-12-07T19_22_21_021Z-debug.log)
 x64

**Comment by Oznaprazzi** [comment]
Same problem here

**Comment by JustBeingDylan** [comment]
I have the same problem. I started with a fresh project.

An unhandled exception occurred: npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: slets-go-christmas@0.0.0
npm ERR! Found: @angular/common@11.0.4
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^11.0.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^10.0.0" from @ng-bootstrap/ng-bootstrap@8.0.0
npm ERR! node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!   @ng-bootstrap/ng-bootstrap@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\extre\AppData\Local\npm-cache\eresolve-report.txt for a full report.

**Comment by parvezshah** [comment]
Ng-bootstrap is still not supported for angular 11 as per the GitHub page,
so had downgrade my cli to angular@10 to resolve my issue

**Comment by bmj99** [comment]
Same issue here. 

Angular CLI: 11.1.1
Node: 12.18.2
OS: Linux x64

Tried downgrading Angular CLI to 10.0.0 and got the same problem, downgraded further to 9.1.15 and was successful.

**Comment by gabrielbergoc** [comment]
I've got the same issue

Angular CLI: 13.3.8
Node: 16.14.2
Package Manager: npm 8.6.0
OS: win32 x64
