### ISSUE TITLE
Allow for responsive display of tabs in Nav component

### ISSUE THREAD

**Issue by zejji** [ng-bootstrap/ng-bootstrap#3789]
### Bug description:

Using the Nav component, I have been unable to reproduce a responsive behaviour which is easily implemented when using Vanilla Bootstrap 4. Specifically, it does not appear to be possible to:

-  display tabbed content on small screen sizes
-  at larger screen sizes, hide the tabs and display all of their content

See the pure html mockup [here](https://jsfiddle.net/t65hvogs/) of the behaviour I am trying to achieve. Try changing the output window size and note that the tabs disappear at larger screen sizes. This is achieved by (i) adding the ".d-sm-none" class to the ".nav-tabs" element and (ii) the ".d-sm-flex" class to the ".tab-pane" elements.

How it should look on a small screen:
![image](https://user-images.githubusercontent.com/3524191/85916714-4f41ed00-b84b-11ea-81c2-7dc6eaa64870.png)

How it should look on a large screen:
![image](https://user-images.githubusercontent.com/3524191/85916727-67197100-b84b-11ea-88a6-a55fe820b04e.png)

I am aware of the Nav component's [destroyOnHide]="false" option, but the limitation arises because, when using ng-bootstrap, the user is given no control over the styling applied to ".tab-pane" elements. Furthermore, in order to achieve an irregular column layout such as that shown in the second image above (i.e. ".col-sm-4" and ".col-sm-8" applied to the first and second tab pane respectively), the solution would need to permit styling specific to each tab pane.

My use case is that I am trying to create a rudimentary chap app which displays both (i) a list of threads and (ii) a message area on large screen sizes, but shows separate tabs for (i) and (ii) on small screen sizes.

If there are any workarounds in the interim, or if the use of predefined CSS classes is not how ng-bootstrap is intended to be used, that would also be helpful to know.

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-zy7cdd

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 9.1.8

ng-bootstrap: 6.1.0

Bootstrap: 4.5.0

**Comment by zejji** [comment]
Having now looked at the nav.ts source code, presumably implementing this would be fairly simple and just require the following?:

- adding an extra "tabPaneClass" string @Input() to the NgbNavItem directive; and
- modifying the NgbNavOutlet component to display that class (using NgStyle)

**Comment by benouat** [comment]
Hey @zejji !
Thanks to report what seems to be an issue for you!

**Comment by zejji** [comment]
@benouat - Thanks for the quick response!

As I needed to implement a fix, I actually got round the issue by:

- switching to Bootstrap SCSS;
- adding (i) `[destroyOnHide]="false"` and (ii) the ".d-sm-none" class to the ngbNav element;
- adding a custom ".my-chat-widget-outlet" class to the ngbNavOutlet element; and
- putting the following in my styles.scss for the chat widget component:

```
@import "~bootstrap-scss/functions";
@import "~bootstrap-scss/variables";
@import "~bootstrap-scss/mixins";

:host ::ng-deep .my-chat-widget-outlet {
    > .tab-pane {
        flex-direction: column;

        /* The following two "includes" are equivalent to the .col-12 class */
        /* This style will apply below "sm" size */
        @include make-col-ready();
        @include make-col(12);

        .active {
            display: flex;
        }

        /* Show the two tab panes as .col-4 and .col-8 from "sm" size upwards*/
        @include media-breakpoint-up('sm') {
            display: flex;
            &:nth-child(1) {
                @include make-col(4);
            }
            &:nth-child(2) {
                @include make-col(8);
            }
        }
    }
}
```
It seems to work fine for the moment, but if I run into any further issues I will do as you suggest and create a custom nav component.

Closing this issue on the basis that it doesn't require a fix.
