### ISSUE TITLE
Duplicate datepicker is displayed when ui-datepicker is included in html dynamically and append to body is true

### ISSUE THREAD

**Issue by AshwiniAJadhav** [ng-bootstrap/ng-bootstrap#3795]
When html having ui-datepicker is compiled and appended dynamically and clicks on calendar icon, it displays multiple datepickers.
This dynamically appended html is removed and appended again on each user click. It seems previously created instances are getting attached when re-append the html. Here append to body flag is true and i am using 
1. angular-ui-bootstrap 2.5.0 
2. jquery 3.1.0
3. angular 1.5.x
1. chromium version 71.0.3578.98. 
What would be the cause of this issue?

**Comment by pkozlowski-opensource** [comment]
Wrong project - we don't maintain angular-ui-bootstrap  here.
