### ISSUE TITLE
I am facing the issue to open multiple Modal in NgbActiveModal

### ISSUE THREAD

**Issue by jashsing** [ng-bootstrap/ng-bootstrap#3811]
### Bug description:
When I open two modal, it is working fine. 
When I open more than two modal the three modal not open...

Please help me with it.

Thanks
Jashvindra Singh

**Comment by benouat** [comment]
Thank you @jashsing for reporting a potential bug.

Nonetheless, according to our documentation [You think you've found a bug](
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug) could you please reproduce your scenario in a minimalist Stackblitz in order for us to start working on it ?

**Comment by maxokorokov** [comment]
Closing as no response, please reopen if necessary.
