### ISSUE TITLE
ng-bootstrap 4.2.1 update with latest fixes

### ISSUE THREAD

**Issue by sarahm7** [ng-bootstrap/ng-bootstrap#3814]
Any chance the latest fixes especially for issue #1950 can be implemented for the 4.x.x version? We're at Angular 7 and there are no plans to migrate soon to 8 due to external plugin issues. This is very critical to our user experience at the moment. Or is there any workaround I can do?

Angular: 7.3.9
ng-bootstrap: 4.2.1
Bootstrap: 4.3.1

**Comment by sarahm7** [comment]
hi, just like to inquire when could the patch be available or if there's a workaround for this, please? thanks!

**Comment by maxokorokov** [comment]
@sarahm7 we generally don't do this sorry. Checked just in case and too many conflicts if cherry-picking changes. You can always fork this repo and add the changes you need.

> no plans to migrate soon to 8 due to external plugin issues

Yep, be careful with 3rd party deps...
