### ISSUE TITLE
ngb-tabset redirects to homepage in Angular Universal 

### ISSUE THREAD

**Issue by DzmVasileusky** [ng-bootstrap/ng-bootstrap#3819]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
When SSR version of Angular Universal app is rendering clicking on any tab leads to redirect to homepage.
This probably happens because tabset markup has `<a href ...></a>` for tab buttons.

### Link to minimally-working StackBlitz that reproduces the issue:

Can't do it for Universal app.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 9.1.10

ng-bootstrap: 6.1.0

**Comment by maxokorokov** [comment]
Tabset is deprecated at this point, please use `Navs` instead
