### ISSUE TITLE
https://ng-bootstrap.github.io/ Is it not suitable for use in China? The official website can't be opened

### ISSUE THREAD

**Issue by 521707** [ng-bootstrap/ng-bootstrap#3821]
https://ng-bootstrap.github.io/ Is it not suitable for use in China? The official website can't be opened ？

**Comment by benouat** [comment]
Hello @521707 

I am not sure how we could fix that...

Meanwhile, what you could do instead is to retrieve the content of the repository (via git, or using GitHub is available) and then build the demo website locally.

Once you would have retrieved the source locally, you can execute these commands

```bash
yarn install
yarn demo
```

It will build the demo website that will be available on `http://localhost:4200`
Hope it helps!
