### ISSUE TITLE
ng-bootstrap is not found in NPM registry

### ISSUE THREAD

**Issue by ludovicderochethales** [ng-bootstrap/ng-bootstrap#3827]
#3649 # Bug description:
For about one hour, whenever I try to install ng-bootstrap v6.1.0 (also tried 6.2.0 and 7.0.0), I'm facing a 404 error on npm registry.
I already checked my registry address and also typed ```npm config set registry http://registry.npmjs.org``` to make sure I was using the right registry.
I tried from several networks including Azure DevOps Pipeline.

NPM info gives the following:
```
npm info @ng-bootstrap/ng-bootstrap@^6.1.0
npm ERR! code E404
npm ERR! 404 '@ng-bootstrap/ng-bootstrap' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! 404
npm ERR! 404  '@ng-bootstrap/ng-bootstrap@6.2.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```
Thanks and regards.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 9.1.0

ng-bootstrap: 6.1.0

Bootstrap: 4.4.1

**Comment by atthaphonkajit** [comment]
facing the same issue,

Angular: 8.2.14

ng-bootstrap: 4.2.2

Bootstrap: 4.4.1

**Comment by ludovicderochethales** [comment]
It seems working now. I close the issue

**Comment by maxokorokov** [comment]
looks like npm issue → https://status.npmjs.org/incidents/cksjqc1w11v5
