### ISSUE TITLE
nebular datepicker shows invalid input when trying after closing window

### ISSUE THREAD

**Issue by Kavyababu1794** [ng-bootstrap/ng-bootstrap#3833]
Hi I am using nebular theme for both window popup and datepicker input, On first time , trying to fill up form its working fine but when I try to fillup form , closing window and opens again datepicker field is showing invalid input.,Its really strange and I couldnot find the issue why it is happening.

Here is my code ,

 myForm = new FormGroup({
  Start_Date: new FormControl("",Validators.required),
});

@ViewChild('add_form') add_form: TemplateRef<any>;
openPopup()
{
  this.windowService.open(
      this.add_form,
      { 
       title: 'Add Exception Form',  
       context  : { action:'Add' }  ,
       hasBackdrop: true,
       closeOnBackdropClick: false    
      },    
      
    );
}

<ng-template #add_form let-data>
<div class="nb-window-body">
  <form [formGroup]="myForm">
  <div class="form-group row">
      <label for="start_date" class="col-md-3 col-form-label">Start Date : </label>
      <div class="col-md-9">
      <input class="form-control" formControlName="Start_Date" [ngClass]="{
        'is-invalid':
          myForm.get('Start_Date').touched &&
          myForm.get('Start_Date').invalid
      }"
    required [nbDatepicker]="formpicker">
            <nb-datepicker #formpicker format="MM-dd-yyyy"></nb-datepicker>
        <div class="invalid-feedback">
          <div>
            You must provide Exception Start Date before submitting.
          </div>
        </div>
      </div> 
    </div>
  </form>
</ng-template>
![error-picker](https://user-images.githubusercontent.com/33347747/89771455-f63dc800-db1d-11ea-9ece-3a1e0f5f157d.PNG)

**Comment by maxokorokov** [comment]
Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz

**Comment by benouat** [comment]
Closing as no feedback. Don't hesitate to re-open with proper information.
