### ISSUE TITLE
Tooltip goes beyond the page when the tooltip is bug

### ISSUE THREAD

**Issue by Vikki123** [ng-bootstrap/ng-bootstrap#3834]
### Bug description:
When the tooltip is lengthy and when the tooltip is attached to the 'body', if the target element is around the right/left most corner of the page, the tooltip is overflown from the page and there is no way to override/reposition the element.

### Link to minimally-working StackBlitz that reproduces the issue:

[Stackblitz Here](https://stackblitz.com/edit/angular-lu6d1r?file=app%2Fapp.component.html)

### Expected Behavior

There should be a way to set the boundary element or min/max (x,y) position when the container type is body or any other cleaner solutions.

### Versions of Angular, ng-bootstrap and Bootstrap:

**Angular:**
```
"@angular/animations": "~9.0.3",
    "@angular/common": "~9.0.3",
    "@angular/compiler": "~9.0.3",
    "@angular/cdk": "~9.0.x",
    "@angular/core": "~9.0.3",
    "@angular/forms": "~9.0.3",
    "@angular/localize": "~9.0.3",
    "@angular/platform-browser": "~9.0.3",
    "@angular/platform-browser-dynamic": "~9.0.3",
    "@angular/router": "~9.0.3",
```
    
**ng-bootstrap:**
`"@ng-bootstrap/ng-bootstrap": "^6.1.0`
 
**Bootstrap:**
`"bootstrap": "^4.4.0",`

**Comment by fbasso** [comment]
@Vikki123, as long as you specify a single value (right and left in your stackblitz), the popup will be placed at this specific value. 

Can you try "left auto" or "right auto" in your placements ? (from ngBootstrap 4.1.0, you can use space as a placement separator).

**Comment by Maazil** [comment]
@fbasso I have the same problem as @Vikki123, my tooltip gets under the nav-bar because it has a lot of text. Is there a way to limit the boundaries of the tooltip? If not should I create a feature-request issue?

**Comment by fbasso** [comment]
Now popperjs is in charge of the positioning, this should be solved (popper options can be customized if needed).

@Maazil , could you please check it and tell us if it works ?

**Comment by maxokorokov** [comment]
Closing as no response, please reopen if necessary.
