### ISSUE TITLE
date picker within scroll-able div - with zoom option

### ISSUE THREAD

**Issue by veenayp** [ng-bootstrap/ng-bootstrap#3836]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Link to minimally-working StackBlitz that reproduces the issue: https://stackblitz.com/edit/angular-nzm4ky?file=src/index.html

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8

ng-bootstrap: 5

Bootstrap: 4

**Comment by jnizet** [comment]
Hi @veenayp 

That's what the `container="body"` input allows solving. 
See https://stackblitz.com/edit/angular-nzm4ky-saqxwj?file=src%2Fapp%2Fdatepicker-popup.html

**Comment by veenayp** [comment]
Thanks @jnizet 

It work perfectly fine with [container="body"].
But I missed to add one scenario, my bad.

Popup is miss placed in case of zoom out. 
<div class="input-group" style="zoom:.5">
see: https://stackblitz.com/edit/angular-nzm4ky-eroyfq?file=src%2Fapp%2Fdatepicker-popup.html

Do let me know if you have workaround for this one as well.

Regards
Veenay

**Comment by jnizet** [comment]
I don't understand what you mean by "zoom out", sorry. Please describe the scenario to reproduce your issue.

**Comment by veenayp** [comment]
In our project there are individual sections with zoom & scroll options and that section contain date picker.

Refer below link to examine the issue:
https://stackblitz.com/edit/angular-nzm4ky-eroyfq?file=src/app/datepicker-popup.html

file: datepicker-popup.html
line no.: 3
**style="zoom:.5"**
or zoom level could be .75 or 1.5

**Important Note**: Parent div _overflow-x_ property is _scroll_
.form-inline{
  overflow-x: scroll;
}

**Comment by jnizet** [comment]
It's the first time I've heard about the zoom CSS property. [CSS Tricks](https://css-tricks.com/almanac/properties/z/zoom/) says that it's a non-standard property, implemented by IE, and not recommended for production sites. And indeed, Firefox doesn't seem to support it (hence why I didn't see any issue). 
I see the issue on Chrome though.

**Comment by benouat** [comment]
@veenayp If you would like to perform a CSS zoom, you should better be using `transform: scale()`. See [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale). As @jnizet mentioned, `zoom` should not be used at all.

**Comment by fbasso** [comment]
Now popperjs is in charge of the positioning, this should work, or it's something to report to popper itself.

Close this issue as there is nothing that we can do on our side.
