### ISSUE TITLE
Typeahead IE has a "X" to clear chrome/brave do not

### ISSUE THREAD

**Issue by ricardosaracino** [ng-bootstrap/ng-bootstrap#3838]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

![image](https://user-images.githubusercontent.com/759253/90160677-1bba1400-dd60-11ea-9166-7c0e34e09863.png)

### Link to minimally-working StackBlitz that reproduces the issue:

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:

ng-bootstrap:
    "@ng-bootstrap/ng-bootstrap": "^6.2.0",

Bootstrap:
 * Bootstrap v4.3.1 (https://getbootstrap.com/)

**Comment by bbarry** [comment]
This is a browser feature offered by IE and Edge (non-chromium? I haven't tested...) browsers that is not in Chrome or Firefox.

I would rather not see code added to emulate the feature in browsers and I'm not sure I like the idea of explicitly removing features that browsers add by default. If you want to remove the feature in your application you can possibly add something like:

```css
input::-ms-clear { display:none; }
```

to your global styles.

**Comment by ricardosaracino** [comment]
this is good to know.. i have added a "X" to clear and having 2 on IE looks bad. i will update my styles accordingly 

![image](https://user-images.githubusercontent.com/759253/90195049-930a9a80-dd96-11ea-8cdf-48474a46f1a8.png)

**Comment by ricardosaracino** [comment]
@bbarry i was wondering if you know how to clear the selection 


this only clears the value if its selected and not if its just random text

```typescript
 get facilityClear() {
    return () => {
      this.facilityControl.setValue(new Facility());
      this.facilityControl.markAsDirty();
      this.changed.emit(true);
    };
  }
```

**Comment by maxokorokov** [comment]
I'll agree with @bbarry on this one. Thanks for the explanation.
