### ISSUE TITLE
Searchahead example with notes

### ISSUE THREAD

**Issue by bigalnz** [ng-bootstrap/ng-bootstrap#3840]
I am looking at the helpful [typeahead with API ](https://stackblitz.com/run?file=app/typeahead-http.ts)call example.

Is it possible to get some comments in the code?

I have forked the stackbliz [here](https://stackblitz.com/edit/angular-5dya7d?file=src/app/typeahead-http.ts) to give suggested questions and areas that could have comments to help new users.

**Comment by benouat** [comment]
Hey @bigalnz 

Here are some responses to your questions:

> Most people know what params are but what is going on with fromObject and where does it from from

This an Angular API, not be mismatched with native `URLSearchParams`.

> Search service called by NgbTypeAhead component every type a key is type in input?

No, we are relying on observable here, and thus we use the `debounceTime` operator to make sure we only call the service 300ms after the last keystroke

> if search string empty return empty array ?

Yes, if search term is empty, we consider it as a reset (i.e. the input field is empty) and thus empty the result list. We also wrap this return call inside `of()` to transform it into an observable.
In the service, the `search` method signature is `search(term: string): Observable<string[]>`.
In the typeahead, the `search` method signature is `search(term$: Observable<string>): Observable<string[]>`

We never thought these things could cause issues. We could had these extra methods signatures though
Hope it clarifies things!
