### ISSUE TITLE
Use local relative units instead of root in datepicker styles

### ISSUE THREAD

**Issue by rlmestre** [ng-bootstrap/ng-bootstrap#3842]
### Bug description:
NgbDatepicker uses `rem` units to set font-sizes, widths, border-radius and more. Because of this, the possible solutions to change the size uniformly are to rewrite every single property down the road that relies on these OR to change the root font-size. In my case, the latter solution would require me to go through our entire applications refactoring styles.

I think the best solution for this would be to replace `rem`s with `em`s, thus allowing the sizes to be scaled locally. 

I am not sure if this problem affects other components, but ideally I would apply the same approach to everything.

#### A couple of links where people have encountered these issues in the past:
https://stackoverflow.com/questions/49854471/ng-bootstrap-datepicker-css-issue
https://stackoverflow.com/questions/47102363/change-size-of-ngbdatepicker-in-angular-4
https://github.com/ng-bootstrap/ng-bootstrap/issues/2781

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-nbiqzv

### Versions of Angular, ng-bootstrap and Bootstrap:
Angular: 10.x
ng-bootstrap: 7.0.0
Bootstrap: 4.5.2

**Comment by jnizet** [comment]
Random thoughts about this: 

- Bootstrap uses rem (for its buttons, dropdowns, etc.), so I think it would be weird not to be consistent
- AFAIU, using em would be a problem when `container="body"` is used on a NgbInputDatepicker, because the font size would then be computed relative to the font size of the body rather than the "local" font size.
- ng-boostrap components don't use `ViewEncapsulation.None`, so it is possible to override the CSS rules used by the components

**Comment by rlmestre** [comment]
- Bootstrap does use `em` when it is necessary, and I think this is one of those cases. However I do have to admit that although in the majority of cases this would behave the same, unless a parent has font-size set, this would be a breaking change. Maybe it could be under an input attribute?
- The "closest" font size when `container="body"` would be `<html>` or `<body>`, which would behave the same as it does now (with `rem`.)
- There's quite a few properties to override across `datepicker`, `datepicker-day-view`, `datepicker-month`, and so on. I'm just trying to justify making this easier for the possibly large number of people running into this (judging from SO views which is not a great metric but...)

**Comment by benouat** [comment]
Hey @rlmestre,
I am sorry but I don't see what's going wrong in the StakBlitz... could you make screen captures, or better record a gif ?

When I play with it (with Safari/ MacOSX) font size is changing

**Comment by rlmestre** [comment]
Yes, that's the only intended functionality of the StackBlitz. Basically when a project uses a root font-size below the default (16px), which is pretty common, the datepicker looks too small. It's intended to illustrate that if the `rem` size is changed, the other elements will (undesirably) shift as well.
