### ISSUE TITLE
NgbModalWindow  always focus the first element that can be focus.

### ISSUE THREAD

**Issue by codeWorldRookie** [ng-bootstrap/ng-bootstrap#3853]
at viewInit of NgbModalWindow  it will focus the first element if the page do not have auto focus, it will cause the close button often get focus when page no auto focus. whether provide a way to control this behavior?

`if (!nativeElement.contains(document.activeElement)) {
      const autoFocusable = nativeElement.querySelector(`[ngbAutofocus]`) as HTMLElement;
      const firstFocusable = getFocusableBoundaryElements(nativeElement)[0];

      const elementToFocus = autoFocusable || firstFocusable || nativeElement;
      elementToFocus.focus();
    }`

**Comment by jnizet** [comment]
Hi @codeWorldRookie 

The answer is in the question, isn't it? If you have any element with an `ngbAutofocus` attribute in the modal template, then that element will take the focus. So that's how you control this behavior: by deciding which element you want to focus, using the `ngbAutofocus` attribute. This is documented [here](https://ng-bootstrap.github.io/#/components/modal/examples#focus) by the way.

What else would you like to be able to do?

**Comment by codeWorldRookie** [comment]
> Hi @codeWorldRookie
> 
> The answer is in the question, isn't it? If you have any element with an `ngbAutofocus` attribute in the modal template, then that element will take the focus. So that's how you control this behavior: by deciding which element you want to focus, using the `ngbAutofocus` attribute. This is documented [here](https://ng-bootstrap.github.io/#/components/modal/examples#focus) by the way.
> 
> What else would you like to be able to do?
Sometimes the page doesn't have an element that needs focus, and most of the time the close button gets the focus, so I think it's weird to let the first element get focus

**Comment by jnizet** [comment]
You can simply add the ngbAutofocus attribute on a non-focusable element of the template.
Here's a demo: https://stackblitz.com/edit/angular-8mhynd?file=src/app/modal-basic.html

**Comment by codeWorldRookie** [comment]
> ngbAutofocus

ok i see, i will add it one by one, It's going to be a lot of work.

**Comment by wassimoo** [comment]
Hi,
I find this to be a little bit tricky, so maybe we should add such a use case to the docs.
Thank you! 🙏
