### ISSUE TITLE
ERROR Error: No component factory found for [object Object]. Did you add it to @NgModule.entryComponents?

### ISSUE THREAD

**Issue by alabanu** [ng-bootstrap/ng-bootstrap#3855]
### Bug description:
I'm getting when clicking the "test" button to open modal component :
ERROR
Error: No component factory found for [object Object]. Did you add it to @NgModule.entryComponents?
I am using ng-bootstrap 2.0.0 locally and the example working just fine but when upgrading ng-bootstrap to 4.0.0 I am getting the same error as the above. For some reason the Stackblitz produces the same error. In stackblitz, I tried to upgrade ng-bootstrap to 4.0.0 but I am getting error "Can't find package:@ng-bootstrap/ng-bootstrap".

### Link to minimally-working StackBlitz that reproduces the issue:

[https://stackblitz.com/edit/ngbootstrap-table-enn161?file=package.json](https://stackblitz.com/edit/ngbootstrap-table-enn161?file=package.json)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7

ng-bootstrap: 2.0.0

Bootstrap:  4.1.1

**Comment by jnizet** [comment]
You're trying to pass an instance of SingletonPopup (`this.currentGridControl`) to `modalService.open()`. What this service expects is either a `TemplateRef`, or the type of a component, as documented here: https://ng-bootstrap.github.io/#/components/modal/api#NgbModal.

Please read the documentation carefully and look at the examples. Also, ng-bootstrap 2.0, or even 4.0, are outdated. Please upgrade to the latest version of Angular and to the latest version of ng-bootstrap and Bootstrap CSS. in all cases, use compatible versions, as documented here: https://ng-bootstrap.github.io/#/getting-started.
