### ISSUE TITLE
Tooltip Transalate Message

### ISSUE THREAD

**Issue by CedLP** [ng-bootstrap/ng-bootstrap#3858]
Hello, i try to show tooltip with translation using ngx translator after initialise page with angular 8 but it's not work.

i have in html components 
`<a #tooltip="ngbTooltip" triggers="manual" ngbTooltip="{{'SHARED.tooltip_typeCourse' | translate}}">
`
in components.ts i have 
`  @ViewChild('tooltip', {static: false}) tooltip;`

inside afterviweinit i call this.tooltip.open(); but if i translate the message it's not work but if i don't translate this it's work.

Someone can help me please :'(

**Comment by jnizet** [comment]
Hi @CedLP. It works fine here (with Angular 10): https://stackblitz.com/edit/angular-onxodc?file=src%2Fapp%2Ftooltip-basic.html

although a better syntax would be `[ngbTooltip]="'SHARED.tooltip_typeCourse' | translate"`

This should be a question on StackOverflow, and it should come with a complete, minimal example reproducing the problem. I strongly advise not to stay on a more than one year old version of Angular, and to upgrade to the latest Angular version.

**Comment by pkozlowski-opensource** [comment]
Thnx @jnizet for helping out with the support - this indeed sounds like a support request and I hope it get resolved.
