### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by CharlyRdzMx** [ng-bootstrap/ng-bootstrap#3874]
### Bug description:

I implement ng-bootstrap in angular 10 project. i use a <ngb-accordion>, but not work, the explorer show the following error:

ERROR TypeError: Cannot read property 'indexOf' of undefined at ng-bootstrap.js:1398

![Captura](https://user-images.githubusercontent.com/19500930/96418630-b0098280-11b8-11eb-8a8a-12892c42c35a.PNG)

Is there an error or is something missing? Thank you.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 10.0.6

ng-bootstrap: 7.0.0

Bootstrap: 4.3.1

![Captura2](https://user-images.githubusercontent.com/19500930/96418977-1db5ae80-11b9-11eb-9cf8-a7f91c114f23.PNG)

**Comment by pkozlowski-opensource** [comment]
If you believe that there is something wrong on the ng-bootstrap side, please provide a minimal reproduction scenario, see.: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

If you are not sure if this is a bug in ng-bootstrap, please use an appropriate support channel: https://github.com/ng-bootstrap/ng-bootstrap#getting-help

**Comment by maxokorokov** [comment]
Closing as no response, please reopen if necessary.
