### ISSUE TITLE
Accordion: documented behavior vs implementation mismatch

### ISSUE THREAD

**Issue by bbarry** [ng-bootstrap/ng-bootstrap#3884]
### Bug description:

Accordion activeIds api documentation states:

> An array or comma separated strings of panel ids that should be opened **initially**.

However the activeIds property reacts to updates...

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-zgwcry?file=src%2Fapp%2Faccordion-toggle.html

This is the toggle example changed to manipulate the activeIds input member instead of invoking the toggle api on the accordion. As can be seen it gets out of sync from the actual state (example: click toggle first button then first panel then toggle first button again).

I'm not sure if the bug is that the documentation is wrong (it clearly reacts to updating this input member, not just initially) or if the implementation needs a separate variable to host the internal state so that it doesn't continue to react to updates after the initial configuration... 

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 10.2 (demo is 10.0; I expect it doesn't matter)

ng-bootstrap: 7.0

Bootstrap: 4.5?

**Comment by hillin** [comment]
Binding to the `activeIds` also prevents the panels to be manually expanded, which makes think it would be a good idea to make that property two-way bindable.

**Comment by maxokorokov** [comment]
Existing accordion will be deprecated in `14.1.0`, new one based on directives will not have `activeIds` at the moment → #3898, #4437
