### ISSUE TITLE
IE11 scrollIntoView causing Change Event to fire with placeholder 

### ISSUE THREAD

**Issue by ricardosaracino** [ng-bootstrap/ng-bootstrap#3886]
```
 if (isPlatformBrowser(this.platformId)) {
      this.router.events.pipe(
        filter(e => e instanceof NavigationEnd),
      ).subscribe(() => {
        const element = document.querySelector('#main-top');
        if (element !== null) {
          element.scrollIntoView();
        }
      });
    }
```

![image](https://user-images.githubusercontent.com/759253/97923267-b9076180-1d2b-11eb-965a-f71e8ec4fab7.png)

**Comment by maxokorokov** [comment]
Is this really ng-bootstrap related?

Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz
