### ISSUE TITLE
Tooltip on label immediately closing in iOS 14 Safari and Chrome

### ISSUE THREAD

**Issue by penfold** [ng-bootstrap/ng-bootstrap#3889]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
Adding a tooltip to the label of an input doesn't work on iOS 14 Safari.

When the label is touched, the tooltip momentarily appears before it is hidden. Then no other tooltips on the page then will open.

There is no issue with Chrome on Android 10.

### Link to minimally-working StackBlitz that reproduces the issue:
https://angular-bvaa3d.stackblitz.io

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 10

ng-bootstrap: 8

Bootstrap: (see stackblitz)

**Comment by maxokorokov** [comment]
I'm not sure what you expect here.
- you should use `<button type="button">`, not the `div`. Everything works fine there.
- for the label, there is no "hover" on mobile. Clicking the label should focus the related input. What would you expect in this case?

FYI, as a workaround you can always trigger tooltips manually whenever necessary → https://ng-bootstrap.github.io/#/components/tooltip/examples#triggers

**Comment by penfold** [comment]
Yes, you are spot one. There is a timing issue.

It looks to be a wider issue that also affects Windows touch in Chrome.

For now we're are using media queries to check if the primary input type is touch and swap the trigger to click from hover.
