### ISSUE TITLE
Conditional tabs are broken in 8.0.0

### ISSUE THREAD

**Issue by nseni** [ng-bootstrap/ng-bootstrap#3892]
### Bug description:
Conditional tabs (`<li [ngbNavItem]="1" *ngIf="canDisplay">`) do not display content in version 8.0.0

### Link to minimally-working StackBlitz that reproduces the issue:

7.0.0: https://stackblitz.com/edit/angular-twkfgy?file=src%2Fapp%2Fnav-basic.html
8.0.0: https://stackblitz.com/edit/angular-twkfgy-fv3y4b?file=src%2Fapp%2Fnav-basic.html

**Comment by maxokorokov** [comment]
A couple of things are broken internally with the way `active` and `show` classes are set when nav items are shown/hidden. We handled some of dynamic cases, but not all apparently.

I don't think we have quick and easy workarounds for this unfortunately, but this should be fixed in `8.0.1`
