### ISSUE TITLE
animation delegation in configs is fragile

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#3893]
I'm not absolutely sure if anything deserves to be changed, but anyway...

### Bug description:

In my tests, I import a TestingModule which intends to disable animations globally, the following way:

```typescript
class TestingModule {
  constructor(config: NgbConfig) {
    config.animation = false;
  }
}
```

And I have an actual module configuring the modals using something like

```typescript
class SharedModule {
  constructor(modalConfig: NgbModalConfig) {
    modalConfig.backdrop = 'static';
  }
}
```

The problem is that if Angular decides to instantiate the shared module first, then the NgbModalConfig is created *before* the NgbConfig has been customized, and thus *copies* the `animation` flag when it's still true. Disabling the animations globally in TestingModule thus doesn't have any effect for modals.

The workaround is simple enough: also inject NgbModalConfig in the testing module, and disable its animation flag too. But it's still a bit unintuitive to do that, and finding out why tests fail and why animations are not disabled is not trivial.

I was wondering if a better solution would not be to actually delegate to NgbConfig instead of copying its animation flag value at construction. Something like:

```typescript
export class NgbModalConfig implements Required<NgbModalOptions> {
  private _animation: boolean | undefined;

  constructor(private ngbConfig: NgbConfig) {}

  get animation(): boolean {
    return (this._animation === undefined) ? this.ngbConfig.animation : this._animation;
  }
  set animation(animation: boolean) {
    this._animation = animation;
  }

  // ...
}
```

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 10.2

ng-bootstrap: 8.0.0

**Comment by maxokorokov** [comment]
Hey, @jnizet, I think you're right, it might be better to change this.

I played with the setup similar to yours and I'm not happy that these two **might** provide different results:

```ts
{ imports: [AppModule, TestingModule] }
{ imports: [TestingModule, AppModule] }
```

I think the place of overriding animation (component vs component cfg vs global cfg) should be more important than the order in which things might be injected.
