### ISSUE TITLE
ngbAccordion should allow "opened" class to be added to ngbPanel

### ISSUE THREAD

**Issue by ebaker-degreed** [ng-bootstrap/ng-bootstrap#3895]
### Feature request description:
As things stand right now, only `ngbPanelHeader` has access to the `opened` property: https://ng-bootstrap.github.io/#/components/accordion/api#NgbPanelHeaderContext

It would be advantageous for a lot of layouts, including the one used by the demo, if this `opened` property was also available at the `ngbPanel` level, or if an `opened` class was just added to the `ngbPanel` element when open.

With such a class, the sibling selector could be used to show / hide borders when multiple panels are opened at once, instead of negative margins and border shadows needing to be used to give the illusion of collapsing borders.

As things stand, I believe I will have to use `isExpanded` + a template reference in the controller to manually add a class to the element. 😦 

### Versions of Angular, ng-bootstrap and Bootstrap:
ng-bootstrap: 8x

**Comment by maxokorokov** [comment]
This should be fixed by a new accordion directives in `14.1.0` → #4437
Here is the related issue → #3898
