### ISSUE TITLE
Angular 11 support

### ISSUE THREAD

**Issue by aksdevac** [ng-bootstrap/ng-bootstrap#3897]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
- Currently able to run v7.0.0 on Angular 11, but consider adding official support

### Link to minimally-working StackBlitz that reproduces the issue:

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 11.0.0

ng-bootstrap: 7.0.0

Bootstrap: 4.5.2

**Comment by maxokorokov** [comment]
A note that we'll be dropping IE9-10 support when bumping the dependency to Angular 11 → https://angular.io/guide/updating-to-version-11#new-breaking-changes

**Comment by huysentruitw** [comment]
> And we'll be dropping IE support completely

This is fantastic news! 🎉 😁

**Comment by DanielFran** [comment]
I have some issues with accordion on Angular v11, so waiting for the upgrade soon.
Thanks

**Comment by aksdevac** [comment]
> I have some issues with accordion on Angular v11, so waiting for the upgrade soon.
> Thanks

Can you share the issue?, I am using accordion with Angular 11 & ng bootstrap 8.0 without any issues

**Comment by khizarshujaat** [comment]
I am facing issue
Error: 'ngb-tab' is not a known element
Error: 'ngb-tabset' is not a known element
While using ng-bootstrap version 8.0.0 with Angular 11

**Comment by khizarshujaatzameen** [comment]
> I am facing issue
> Error: 'ngb-tab' is not a known element
> Error: 'ngb-tabset' is not a known element
> While using ng-bootstrap version 8.0.0 with Angular 11

According to [Documentation](https://ng-bootstrap.github.io/#/components/tabset/examples), ngb-tab & ngb-tabset removed from ng-bootstrap v8.0.0. So i have converted the tabs to nav-directives which resolved my issue

**Comment by khizarshujaat** [comment]
> I am facing issue
> Error: 'ngb-tab' is not a known element
> Error: 'ngb-tabset' is not a known element
> While using ng-bootstrap version 8.0.0 with Angular 11

According to [Documentation](https://ng-bootstrap.github.io/#/components/tabset/examples), ngb-tab & ngb-tabset removed from ng-bootstrap v8.0.0. So i have converted the tabs to nav-directives which resolved my issue

**Comment by maxokorokov** [comment]
Fixed by #3906 and #3923
