### ISSUE TITLE
switching nav scrolls to the top of the page

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#3900]
In a page where there is some text at the top, not filing the whole viewport height, and a nav at the bottom, large enough for the page to scroll, if you scroll down, then switch to another tab, the browser scrolls back to the top of the page.
This happens with or without animation, and with or without destroyOnHide. 

![bug-nav](https://user-images.githubusercontent.com/1608223/99065029-12cb1f80-25a7-11eb-819e-5c7fccb2c402.gif)

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-hyx6po?file=src%2Findex.html

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 10 / 11

ng-bootstrap: 8.0.0

Bootstrap: 4.5.3

**Comment by maxokorokov** [comment]
Indeed. Looks like for a brief period of time between fade out and fade in the outlet stays empty.

I suspect (just a guess) something is wrong around this `ngIf`:
https://github.com/ng-bootstrap/ng-bootstrap/blob/1f466edaa222812a15d233ab6a604ece68e3a58b/src/nav/nav-outlet.ts#L46-L48

and maybe this `reflow`:
https://github.com/ng-bootstrap/ng-bootstrap/blob/1f466edaa222812a15d233ab6a604ece68e3a58b/src/nav/nav-transition.ts#L9-L13

Need to investigate further
cc @fbasso

**Comment by jnizet** [comment]
Thanks for the fix @maxokorokov ❤️
