### ISSUE TITLE
ngbNav throwing error on tab click after version 8 upgrade

### ISSUE THREAD

**Issue by ravik3592** [ng-bootstrap/ng-bootstrap#3903]
Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: ''. Current value: 'loader'

This was working earlier with ngbtabset, but it was deprecated so i used ngbnav, but im getting this error on tab click.
I use 2 tabs,
1. Users list
2. Admin list

On tab change i will change the route and fetch data from API and render data in table

**Comment by pkozlowski-opensource** [comment]
We would need a minimal reproduce scenario to be able to progress on this one, see: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by maxokorokov** [comment]
Closing as no response, please reopen if necessary.
