### ISSUE TITLE
Carousel is not displaying when generating slides using ngFor

### ISSUE THREAD

**Issue by thampinox** [ng-bootstrap/ng-bootstrap#3905]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
When generating slides using ngFor after getting some API response carousel slide has **display:none** so the whole carousel is not displaying. I've noticed that this is happening when the array using in ngFor is initialized with an empty array and then reassigned with the new array after some period of time.

UPD:
It does not matter if you assign an empty array to the variable used in `ngFor` or leave it `undefined`.

### Link to minimally-working StackBlitz that reproduces the issue:
[Repro link](https://stackblitz.com/edit/angular-ngcarousel?file=src/app/hello.component.ts)

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 11.0.2

ng-bootstrap: 8.0.0

Bootstrap: 4.5.3

**Comment by jnizet** [comment]
Your outer array has a single element, which means that this carousel would have a single slide. It doesn't make much sense does it? If you introduce additional elements, it works as expected: https://stackblitz.com/edit/angular-ngcarousel-uupumm?file=src/app/hello.component.ts

But it's really weird to display a carousel without any slide for a second anyway. So I wouldn't display the carousel until it can actually display something, by adding an ngIf: https://stackblitz.com/edit/angular-ngcarousel-wgwvbw?file=src/app/hello.component.ts

**Comment by thampinox** [comment]
Thanks for the response @jnizet. 
I'm trying to build an image gallery for a product and the problem is that I do not know how many images were uploaded for it so I'm calculating slides count on the fly after receiving a list of images. Sometimes there are not too many images so the carousel has one slide and I'm hiding the arrows.

I also found that ngIf fixes the problem. But in my case carousel needed to be paused by default, so I needed to carousel ViewChild not to be null initially and didn't want to call **pause()** many times in ngAfterViewChecked. The solution in my case was to set a long interval.

**Comment by jnizet** [comment]
I think I understand. But you can simply use ViewChildren instead and pause the carousel as soon as it becomes visible if you only have one slide: https://stackblitz.com/edit/angular-ngcarousel-13d28p?file=src/app/hello.component.ts

**Comment by jnizet** [comment]
Oh, BTW, you can simply set the interval to 0 by default (which will prevent the carousel to switch slides) and set it to something else if you have more than one slide: https://stackblitz.com/edit/angular-ngcarousel-lc1h4h?file=src/app/hello.component.ts

**Comment by thampinox** [comment]
Zero works perfectly, thanks for the hint. 
This is not really obvious that setting 0 can disable carousel sliding, will be nice to have this somewhere noted.
