### ISSUE TITLE
'NgbCollapse' does not contain such a member

### ISSUE THREAD

**Issue by vadimt2** [ng-bootstrap/ng-bootstrap#3908]
(click)="collapse.toggle()"
Identifier 'toggle' is not defined. 'NgbCollapse' does not contain such a memberng

`imports: [CommonModule,AuthRoutingModule,FormsModule,HttpClientModule,ReactiveFormsModule, NgbModule, NgbPaginationModule, NgbAlertModule],`

**Comment by maxokorokov** [comment]
Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz

**Comment by vadimt2** [comment]
I have upgrade it to version 8 and it is working fine.
