### ISSUE TITLE
Odd behaviour with carousel items using ngFor directive

### ISSUE THREAD

**Issue by napei** [ng-bootstrap/ng-bootstrap#3911]
### Bug description:
When using `*ngFor` with an observable subscription that determines the content, sometimes the newly added content (images) will not load properly even though it's there (network tab). I'm not sure of the process behind the scenes however I would expect the carousel to always load properly and even re-render itself if the slides were to change. What I think is happening, is that the carousel is being changed mid-transition, and then it's waiting until the next slide to fix itself, which isn't always the best when I just want to change the contents of the carousel and start it again.

Production use case is runtime localisation that provides data from an observable. Same concept as the stackblitz just not on a timer.

### Link to minimally-working StackBlitz that reproduces the issue:

I have this issue currently on another site I'm working on which may cause differences, but to save complexity I have been able to repro it in a stackblitz and provide a demonstration of the behaviour as well.

https://stackblitz.com/edit/angular-49qw2x?file=src/app/carousel-basic.ts

https://www.youtube.com/watch?v=2cX3Q9dLumo

The reproduction is rather random, as it seems to happen when I click the force button, even though that's literally the same function being called on the 5 second interval.

Further to that I'm not sure of how the rendering happens at all, but should it be slide 400+? Should it not reset/recalculate based on the contents.

![image](https://user-images.githubusercontent.com/8946502/100093901-4a41a200-2eac-11eb-90f0-cfdea5353d6f.png)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: Stackblitz is 10.0.14, also present in v11

ng-bootstrap: 8.0.0

Bootstrap: 4 in stackblitz, 5-alpha in production (I don't think there's much difference with the carousel)

**Comment by maxokorokov** [comment]
Yeah, the "active" class is not being set. 

Here are the alternative versions (that also always keep the same slide ids):
- ng-bootstrap 8 (broken) → https://stackblitz.com/edit/angular-49qw2x-14qfvv?file=src%2Fapp%2Fcarousel-basic.html
- ng-bootstrap 7 (working) → https://stackblitz.com/edit/angular-49qw2x-gmw1uo?file=src%2Fapp%2Fcarousel-basic.html

Looks like we need to start a transition to set the active class here: https://github.com/ng-bootstrap/ng-bootstrap/blob/9dd3044d2019e0f4f6c30181d7497bc2c11aede6/src/carousel/carousel.ts#L283

And to handle case when this happens in the middle of already running transition.

cc @fbasso
