### ISSUE TITLE
Bundle includes all components, no tree shaking

### ISSUE THREAD

**Issue by acprince** [ng-bootstrap/ng-bootstrap#3919]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
Importing individual modules does not tree shake the unused modules. Importing `NgbDatepickerModule` (or any other module it seems) does not decrease the output bundle size compared to just importing `NgbModule`. The bundle contains references to components and modules not imported.

From the [documentation](https://ng-bootstrap.github.io/#/getting-started#imports), this should work and "The resulting bundle will be smaller in this case."

### Link to minimally-working StackBlitz that reproduces the issue:
I dont believe StackBlitz's features allow looking at bundle sizes. Instead I created a minimal repro here:

https://github.com/acprince/tree-shake-example

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 9.1.1

ng-bootstrap: 6.2.0

Bootstrap: 4.5.3

**Comment by maxokorokov** [comment]
Hey, @acprince thanks for the repo.
You should run `ng build --prod --source-map` and use `source-map-explorer` to check what's inside the final build.

If I remember correctly webpack bundle analyzer runs before tree-shaking.

Looks like everything is fine to me:

1. Your version:

![Screenshot 2021-01-05 at 11 31 23](https://user-images.githubusercontent.com/8074436/103636095-c9b19f00-4f49-11eb-86d0-7688454994c6.jpg)

2. When importing `NgbDatepickerModule` and adding `<ngb-datepicker></ngb-datepicker>` to the `app.component`

![Screenshot 2021-01-05 at 11 32 04](https://user-images.githubusercontent.com/8074436/103636133-da621500-4f49-11eb-9974-ec5f0df7773f.jpg)

3. When importing `NgbModule` and adding `<ngb-datepicker>`

![Screenshot 2021-01-05 at 11 34 31](https://user-images.githubusercontent.com/8074436/103636283-0b424a00-4f4a-11eb-8dbf-77c2cd1962c9.jpg)
