### ISSUE TITLE
Two different calendars in the same page not supported in v 1.0.0?

### ISSUE THREAD

**Issue by yaser2001m** [ng-bootstrap/ng-bootstrap#3921]
I need to use Gregorian and Hijri for two calendars each one with different inputs on the same page two of them for birth date in different calendars is this supported, and how?

Thanks.

**Comment by jnizet** [comment]
https://ng-bootstrap.github.io/#/components/datepicker/calendars is a page showing multiple calendars being used. If you click on the "Code" buttons, you'll see the code being used.
Of course, this page doesn't use version 1.0.0, which is completely obsolete. Don't use version 1.0.0.

**Comment by maxokorokov** [comment]
I concur with the last speaker, please don't use 1.0.0 :)
