### ISSUE TITLE
ng bootstrap installation with Angular 11.

### ISSUE THREAD

**Issue by tutu23** [ng-bootstrap/ng-bootstrap#3923]
I am unable to include ng bootstrap.
After running npm install --save @ng-bootstrap/ng-bootstrap.
I cannot see the module under node_modules.
I have deleted node_modules and tried npm install already.

**Comment by jnizet** [comment]
Hi.

There's not much we can do about that, and that is not an issue with ng-bootstrap, but rather an issue with your machine or node installation or npm installation or network. My guess is that

- you didn't look into the right place
- or you got an error. If that's the case, not posting it makes it impossible for us to help you.

**Comment by vickyrathee** [comment]
@jnizet Here is the error screenshot, it errors in installation when Angular 11 is used

![image](https://user-images.githubusercontent.com/6106479/103509177-86432c00-4e88-11eb-93ad-21d1cbe0e9f1.png)

**Comment by jnizet** [comment]
It says: "Retry this command with --force, or --legacy-peer-deps".
Have you tried that?
Have you tried the manual installation as described here? https://ng-bootstrap.github.io/#/getting-started
Which version of node and npm are you using?

**Comment by vickyrathee** [comment]
- Not working with --force
![image](https://user-images.githubusercontent.com/6106479/103510158-a2e06380-4e8a-11eb-910a-598ca15e456f.png)

- Not working with --legacy-peer-deps
![image](https://user-images.githubusercontent.com/6106479/103510184-b095e900-4e8a-11eb-8892-5927f8e21555.png)
- My NPM version is `7.0.15`
![image](https://user-images.githubusercontent.com/6106479/103510209-c2778c00-4e8a-11eb-9a3e-28350ad8f747.png)


I am trying the manual installation option...

**Comment by vickyrathee** [comment]
@jnizet The manual install option also errored unfortunately.

![image](https://user-images.githubusercontent.com/6106479/103510578-87298d00-4e8b-11eb-86d1-6e6fa0580473.png)

**Comment by jnizet** [comment]
I doubt the --force flag passed to ng add is passed to the internal npm
command it uses to install dependencies.
Use the manual installation with a 6.x version of npm (I don't reproduce
the issue with npm 6.14.8), or at least try the --force flag with the npm
command.

Le lun. 4 janv. 2021 à 08:16, Vikash Rathee <notifications@github.com> a
écrit :

**Comment by vickyrathee** [comment]
I tried to use `--force` in manual npm install as well, but nothing works.

```
npm install @ng-bootstrap/ng-bootstrap --force
```

**Comment by maxokorokov** [comment]
Same with npm 7 on my side.
Something changes with `peerDependenices` there I guess.

it works with `npm i --save @ng-bootstrap/ng-bootstrap --legacy-peer-deps` for me.
Also works fine with CLI 10.

We don't support Angular 11 officially yet, so deps we have in `8.0.0` are on Angular `^10.0.0`.

I would say either use earlier npm version or use Angular CLI 10 or use `--legacy-peer-deps`

**Comment by maxokorokov** [comment]
Just to keep the link, main Angular 11 issue is here → #3897

**Comment by vickyrathee** [comment]
@maxokorokov any ETA for Angular 11 support?

**Comment by amithakkar05** [comment]
> npm i --save @ng-bootstrap/ng-bootstrap --legacy-peer-deps

its working thanks
