### ISSUE TITLE
The navtab content DOM will NOT be destroyed if it is not active

### ISSUE THREAD

**Issue by javix** [ng-bootstrap/ng-bootstrap#3930]
### Bug description:
The tab content DOM will NOT be destroyed if it is not not active, when the component is using onPush change detection. It is very critical for me because I use components as content templates and I expect a new instance every time the tab is activated.

![screenshot](https://user-images.githubusercontent.com/5870244/103756350-8a4d8600-500f-11eb-9155-036d069ab562.png)

### Link to minimally-working StackBlitz that reproduces the issue:
https://angular-b2j9uy.stackblitz.io

If you switch between the tabs, the last two always stay in the DOM.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 11.0.5

ng-bootstrap: 8.0.1

**Comment by maxokorokov** [comment]
Yep, it's a regression, thanks for reporting.
It seems we need to mark nav outlet for check after the fade out transition is finished.
