### ISSUE TITLE
ngbDropdown not working with cdkDrag Angular 11.0.3

### ISSUE THREAD

**Issue by abhayciitizen** [ng-bootstrap/ng-bootstrap#3933]
`ngbDropdown` not closing when clicking on menu item. Its working fine outer side `cdkdrag` div but not inside cdkdrag. I tried remove cdkDrag then its working fine. I also tried to change version of `ngbDropdown` and `cdkDrag`.
It's also working fine when using manual installing `bootstrap` with `jQuery`.

**Comment by maxokorokov** [comment]
Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz
