### ISSUE TITLE
ngb-accordion tab not render in angular universal

### ISSUE THREAD

**Issue by toniperezfer** [ng-bootstrap/ng-bootstrap#3935]
### Bug description:
In angular ssr, accordion only render the content of activated panels. We need the content of all panels because we have links that are necessary for crawlers. On the other hand we don't want to activate all the panels because there are many and the user experience is not good.

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/github/toniperezfer/ngbootstrap-accordion

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 10.2.4

ng-bootstrap: 8.0.1

Bootstrap: 4.5.0

Thanks

**Comment by maxokorokov** [comment]
Hey, @toniperezfer, so you need something like [`[destroyOnHide]` we have for Nav](https://ng-bootstrap.github.io/#/components/nav/examples#keep-content), if I understand correctly? 
Note we also have #1584 for navs that might be related.

The new accordion corresponding to what [bootstrap is introducing in 5.0](https://getbootstrap.com/docs/5.0/components/accordion/) is planned in #3898. This should be a part of `10.0.0` release and we should include this feature to be on par with navs.

I'm not sure anybody will be able to tackle this before that.

**Comment by maxokorokov** [comment]
It will be a a part of a new accordion directvies (#3898, #4437) and released in `14.1.0`
There is a new `[destroyOnHide]` feature, I've just added SSR tests for it → #4483
