### ISSUE TITLE
Feature request: run datePicker markDisabled during validation

### ISSUE THREAD

**Issue by mattdistefano** [ng-bootstrap/ng-bootstrap#3948]
### Bug description:

The existing behavior is that NgbInputDatepicker's validator will validate manual input against minDate and maxDate. I apologize if I missed an earlier discussion about this (I searched, I swear), but IMO the markDisabled should also be validated against here. That is, any date date that is disabled for selection on the datepicker calendar should also be invalid when manually entered into the input. Right now, it seems that you can manually enter a date even when it has been disabled by markDisabled.

### Link to minimally-working StackBlitz that reproduces the issue:

https://angular-cd8tos.stackblitz.io

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 11

ng-bootstrap: 9

Bootstrap: n/a

**Comment by maxokorokov** [comment]
Hey, @mattdistefano, no pb!
But it seems like it's what #3182 is about ?

Anyway it's good to bring attention to this issue again. Looks like there is indeed an issue with validating disabled dates.
