### ISSUE TITLE
Popover event 'shown' is executed outside of angular zone if animation is disabled

### ISSUE THREAD

**Issue by javix** [ng-bootstrap/ng-bootstrap#3950]
### Bug description:
Popover event 'shown' is executed outside of angular zone if animation is disabled and inside of angular zone if animation is enabled.
I think, all events should be executed INSIDE of angular zone independent of animation.

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-gthjjm?file=src%2Fapp%2Fpopover-triggers.ts
Open the console log.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:
11.0.9

ng-bootstrap:
8.0.2
9.0.0

**Comment by maxokorokov** [comment]
Fixed in `8.0.3` and `9.0.1`
