### ISSUE TITLE
Multiple tables ( complete example ) doesn't work correctly

### ISSUE THREAD

**Issue by djamel2288** [ng-bootstrap/ng-bootstrap#3951]
### Bug description:
I discovered the ng-bootstrap table, and it was very awesome, I am using the full table example [(this](https://stackblitz.com/run?file=app/table-complete.ts)), it works fine, now I have to add a new table with other information (column), but when we run my code, it seems that there is a conflict between the tow table.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 10

ng-bootstrap: 6.1.0

Bootstrap: 4.5.0

**Comment by javix** [comment]
I think, you should create a full example in stackblitz and try the new version of ng-bootstrap, 8.0.2 or 9.0.0.

**Comment by djamel2288** [comment]
thanks I will try

**Comment by djamel2288** [comment]
solved, I upgrade my ng-bootstrap, I don't know if that is the problem or not, anyway thank you

**Comment by djamel2288** [comment]
i have this error msg
( Type '"test"' is not assignable to type 'SortColumn'.).......
even if I added the "test" field in my class and my json data

**Comment by jnizet** [comment]
@djamel2288 this should be a question on StackOverflow. And it should come with the code causing this error message. Github issues are meant to signal bugs in ng-bootstrap, not as a way to get help with your own code.
