### ISSUE TITLE
Modal's entry animations are missing in Angular production build

### ISSUE THREAD

**Issue by peruukki** [ng-bootstrap/ng-bootstrap#3952]
### Bug description:

I noticed that the modals are missing their entry animations (the downwards movement) when running the production build of an Angular 11 application:

![animation-missing](https://user-images.githubusercontent.com/1781172/104739343-45cc9380-574f-11eb-9661-c6877af19fff.gif)

The animation works correctly when running the development server:

![animation-works](https://user-images.githubusercontent.com/1781172/104739364-4b29de00-574f-11eb-89cd-a2017e25ea4e.gif)

Also, the exit animation (upwards movement) works in both cases.

### Link to minimally-working StackBlitz that reproduces the issue:

I can only reproduce the problem with Angular's production build, which StackBlitz doesn't support as far as I know. But I created a minimal example repository that contains ng-bootstrap's modal demo page, and where the problem can be reproduced: https://github.com/peruukki/ng-bootstrap-modal-example.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 11.0.9

ng-bootstrap: 9.0.0

Bootstrap: 4.5.3

**Comment by maxokorokov** [comment]
Fixed in `8.0.3` and `9.0.1`

**Comment by 4javier** [comment]
Same problem with ngbCollapse on ng-bootstrap 9.0.2 and Angular 11.1: no animation in prod build.

**Comment by maxokorokov** [comment]
@4javier, please open a separate issue for this filling the template and providing a reproduction scenario.
Demo site is built in production and animations are there → https://ng-bootstrap.github.io/#/components/collapse/examples#basic
