### ISSUE TITLE
Dropdown component failure - Menu stuck being shown, no showing or hiding.

### ISSUE THREAD

**Issue by redevill** [ng-bootstrap/ng-bootstrap#3953]
### Bug description:
Dropdown menus not dropping down or hiding in angular 10

### Link to minimally-working StackBlitz that reproduces the issue:
I attempted to create a stack blitz - initially after updating the package json I did see my error condition.
However, I could not save the stack blitz, because it then generated an ngcc error.
[angular-errors.log](https://github.com/ng-bootstrap/ng-bootstrap/files/5823526/angular-errors.log)

These are the angular dependencies I used in the stackblitz package json
 "@angular/animations": "10.2.2",
    "@angular/cdk": "^10.2.7",
    "@angular/common": "10.2.2",
    "@angular/compiler": "10.2.2",
    "@angular/core": "10.2.2",
    "@angular/forms": "10.2.2",
    "@angular/google-maps": "^10.2.7",
    "@angular/localize": "10.2.2",
    "@angular/material": "10.2.2",
    "@angular/platform-browser": "10.2.2",
    "@angular/platform-browser-dynamic": "10.2.2",
    "@angular/router": "10.2.2",
    "@ng-bootstrap/ng-bootstrap": "^8.0.2",
    "bootstrap": "^4.5.3",
[2pcjgr--run.zip](https://github.com/ng-bootstrap/ng-bootstrap/files/5823514/2pcjgr--run.zip)

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. 
I do understand, but when your chosen repro tool also chokes... not that easy...
I've done my due diligence in attempting to let you know - Also tried to attach the saved zip of the stackblitz where the ngcc occurred during the ng serve command.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: detailed as above

ng-bootstrap: detailed as above

Bootstrap:detailed as above

**Comment by jnizet** [comment]
I changed these lines in your package.json

```
    "@angular-devkit/build-angular": "~0.901.1",
    "@angular/cli": "~9.1.1",
    "@angular/compiler-cli": "~9.1.1",
    "@angular/language-service": "~9.1.1",
```

into these lines:

```
    "@angular-devkit/build-angular": "~0.1002.1",
    "@angular/cli": "~10.2.1",
    "@angular/compiler-cli": "10.2.2",
```

because the CLI 9.x is not compatible with Angular 10.x (as `ng serve`says when you execute it). 
Then I ran `ng serve`, clicked on the buttons displayed in your page, and the dropdowns appeared.
So I'm not able to reproduce your issue.

If you want help, you'll need to provide a stackblitz, or at the very least a zip file which we can simply unzip, then run npm/yarn install, then run ng serve and see the problem you're having.

Your zip doesn't compile without modification, and when it's fixed to compile, it doesn't reproduce your issue. So there's not much we can do.

**Comment by redevill** [comment]
@jnizet - thank you for the input. Been playing around with it, and found the mismatched versions - thank you.
But it appears that I had 2 issues: Mismatched versions and a missing import of NgbModule.

This is for posterity - for anyone having similar issue. 
As per the instructions, the NgbModule was installed as part of the "ng add" install process.
However, In my case, the scope in which the bootstrap components would work, was limited to only the app Module. SubModules loaded by the app Module, needed a separate import of the NgbModule, in order to use the bootstrap components in the submodules html pages.

Is this an expected scoping limitation? I was under the impression that once loaded (NgbModule) in the root of the application, bootstrap components would be available throughout the SPA.

**Comment by jnizet** [comment]
Yes, that's a global rule imposed by Angular, and valid for all comonents, pipes, and directives. 
If you want to use a directive (here, NgbDropdown) declared in a module (here, NgbDropdownModule), in any of your modules (here, YourAppSubModule), then your module (YourAppSubModule) **must** import the module where the directive is declared (NgbDropdownModule), or a module which exports (transitively) this module (for example NgbModule, which exports NgbDropdownModule).
