### ISSUE TITLE
No animation on ngbCollapse in Angular 11.1 in production build

### ISSUE THREAD

**Issue by 4javier** [ng-bootstrap/ng-bootstrap#3972]
### Bug description:
Since upgrade to Angular 11.1, ngbCollapse elements get no animation when built for production (ng build --prod).
Other directives like ngbTooltip work as usual.
Animation works regular in dev build even for ngbCollapse.

### Link to minimally-working StackBlitz that reproduces the issue:

Don't know how to issue a production build on StackBlitz

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular 11.1.0
ng-bootstrap 9.0.2

**Comment by maxokorokov** [comment]
We'll need the reproduction scenario please. Demo site works fine.

Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz

**Comment by 4javier** [comment]
@maxokorokov 
I think I narrowed down the problem: 
the issue arises when you import the standalone `NgbCollapseModule` instead of the whole `NgbModule`.
Considered the simplicty of repro, I avoid to link to you a repo just for this.

**Comment by 4javier** [comment]
Trying to debug a little, I find out that after optimization the value of NgbCollapsingTransition at this line results undefined
https://github.com/ng-bootstrap/ng-bootstrap/blob/74d3109d9d1c920973e73b8b6a8f5478cb7d8bfa/src/collapse/collapse.ts#L81
Hope it helps.

**Comment by maxokorokov** [comment]
Ok, this is caused by the Terser `pure_getters` optimization.

We have a `reflow` function:

```ts
export function reflow(element: HTMLElement) {
  return (element || document.body).offsetHeight;
}
```

In case of using ONLY `NgbCollapsingModule` it is used only once and is inlined.

```ts
// not inlined, if reflow is used in several places
classList.remove("collapse"),
classList.remove("collapsing"),
classList.remove("show"),
reflow(element),
classList.add("collapsing"),

// inlined, if used only once
classList.remove("collapse"),
classList.remove("collapsing"),
classList.remove("show"),
function(element) {
    element || document
}(element),
classList.add("collapsing"),
```

See https://github.com/angular/angular-cli/issues/15761 for more details.


On our side I'll fix it by using `.getBoundingClientRect()` instead of `.offsetHeight`
