### ISSUE TITLE
Tooltip closes immediately when hovered from tooltip direction

### ISSUE THREAD

**Issue by peruukki** [ng-bootstrap/ng-bootstrap#3997]
### Bug description:

In our application, tooltips triggered on hover don't open if the mouse enters the triggering element from the direction where the tooltip is placed. This doesn't happen always but most of the time. Hovering from any other direction works fine.

Looking at the DOM, the tooltip is shown but then immediately hidden.

### Link to minimally-working StackBlitz that reproduces the issue:

I'm able to reproduce the problem quite well on the [demo site](https://ng-bootstrap.github.io/#/components/tooltip/examples) when using Chrome, but not with Firefox or Safari. In our application it seems to occur in all browsers. Also, a Linux-using colleague reported that they can reproduce the problem more frequently when zooming the browser at e.g. 125%. However, I'm on a Mac and didn't notice any difference related to the zooming level.

It also reproduces in [StackBlitz](https://sk4r8k--run.stackblitz.io/) (I can't get a working editor URL, only an application URL):

https://user-images.githubusercontent.com/1781172/106900971-d586b180-66ff-11eb-879d-2fa78209f9c5.mp4

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 11.0.9

ng-bootstrap: 9.0.2

Bootstrap: 4.5.3

Chrome: 88.0.4324.96

macOS: 11.2

**Comment by peruukki** [comment]
Are you able to reproduce this problem, or do you need some more information? I can reproduce the problem easily in our application, so I can also try out things if you have some theories to test.

**Comment by peruukki** [comment]
I'm actually able to reproduce this problem quite easily with the demo page on Chrome if I move the mouse slowly enough on the triggering button. I got a bit more info on what happens by adding this logging:
```diff
diff --git a/src/util/triggers.ts b/src/util/triggers.ts
index 42a9d59b..2d7241ed 100644
--- a/src/util/triggers.ts
+++ b/src/util/triggers.ts
@@ -46,8 +46,8 @@ export function observeTriggers(
     renderer: Renderer2, nativeElement: HTMLElement, triggers: Trigger[], isOpenedFn: () => boolean) {
   return new Observable<boolean>(subscriber => {
     const listeners: Function[] = [];
-    const openFn = () => subscriber.next(true);
-    const closeFn = () => subscriber.next(false);
+    const openFn = (event: any) => { console.log('-> open event', event.type, event); subscriber.next(true); };
+    const closeFn = (event: any) => { console.log('-> close event', event.type, event); subscriber.next(false); };
     const toggleFn = () => subscriber.next(!isOpenedFn());
 
     triggers.forEach((trigger: Trigger) => {
@@ -73,9 +73,11 @@ export function triggerDelay(openDelay: number, closeDelay: number, isOpenedFn:
         map(open => ({open})), filter(event => {
           const currentlyOpen = isOpenedFn();
           if (currentlyOpen !== event.open && (!pending || pending.open === currentlyOpen)) {
+            console.log('   keeping event', currentlyOpen, event, pending);
             pending = event;
             return true;
           }
+          console.log('   rejecting event', currentlyOpen, event, pending);
           if (pending && pending.open !== event.open) {
             pending = null;
           }
```

Here you see the logs for both cases, first working OK and then closing immediately:
https://user-images.githubusercontent.com/1781172/115271380-f4fd7a00-a145-11eb-9e8f-7c3c70466d9c.mp4

So comparing the immediately closing scenario to the OK one, there are two extra trigger events (2nd and 3rd event):
1. `mouseleave`: the `target` is the button and `relatedTarget` is the tooltip window, i.e. the mouse exits the button and enters the tooltip window ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/relatedTarget))
2. `mouseenter`: the `target` and `relatedTarget` are the same, so the mouse exits the tooltip window and enters the button again

When the latter event is fired, it is rejected because the tooltip is deemed already open. Though, even if I return `true` from the filtering function nonetheless, the tooltip is still not shown.

I'm not sure if the fix would be to prevent these additional mouse events, or make the opening work even if they occur.

**Comment by peruukki** [comment]
One way to solve this would be disabling pointer events until the tooltip is shown:
```diff
diff --git a/src/tooltip/tooltip.scss b/src/tooltip/tooltip.scss
index d4ecc6df..c84ef5a6 100644
--- a/src/tooltip/tooltip.scss
+++ b/src/tooltip/tooltip.scss
@@ -2,6 +2,10 @@
 $arrow-size: 0.8rem;
 
 ngb-tooltip-window {
+  &:not(.shown) {
+    pointer-events: none;
+  }
+
   &.bs-tooltip-top .arrow,
   &.bs-tooltip-bottom .arrow {
     left: calc(50% - #{$arrow-size / 2});
diff --git a/src/tooltip/tooltip.ts b/src/tooltip/tooltip.ts
index 0eeca15c..4c44ea7a 100644
--- a/src/tooltip/tooltip.ts
+++ b/src/tooltip/tooltip.ts
@@ -232,7 +232,12 @@ export class NgbTooltip implements OnInit, OnDestroy, OnChanges {
           this._ngZone, this._document, this.autoClose, () => this.close(), this.hidden,
           [this._windowRef.location.nativeElement]);
 
-      transition$.subscribe(() => this.shown.emit());
+      transition$.subscribe(() => {
+        if (this._windowRef) {
+          this._windowRef.location.nativeElement.classList.add('shown');
+        }
+        this.shown.emit();
+      });
     }
   }
```

**Comment by peruukki** [comment]
Actually, just disabling pointer events for the tooltip window element seems to be enough:
```diff
diff --git a/src/tooltip/tooltip.scss b/src/tooltip/tooltip.scss
index d4ecc6df..d38de6f3 100644
--- a/src/tooltip/tooltip.scss
+++ b/src/tooltip/tooltip.scss
@@ -2,6 +2,12 @@
 $arrow-size: 0.8rem;
 
 ngb-tooltip-window {
+  pointer-events: none;
+
+  .tooltip-inner {
+    pointer-events: auto;
+  }
+
   &.bs-tooltip-top .arrow,
   &.bs-tooltip-bottom .arrow {
     left: calc(50% - #{$arrow-size / 2});
```

**Comment by fbasso** [comment]
Hi @peruukki. 

For information, we are going to revert partially the PR done, as it causes a noticeable regression (#4103). Note that the revert is done only for the popover for now, but unfortunately, another solution needs to be found.

**Comment by peruukki** [comment]
Oh, that's a shame. 🙁 Thanks for letting me know, @fbasso! 🙇

**Comment by woasry** [comment]
Any update? I have the same problem with "@ng-bootstrap/ng-bootstrap": "^12.1.2".

**Comment by peruukki** [comment]
No updates from me, but I've moved on to other projects since and haven't used ng-bootstrap in over a year, so I haven't followed its updates either. 🙂

**Comment by tryconmanjeet** [comment]
I'm still facing this issue in popover component.

Angular: 14.1.0
ng-bootstrap: 13.0.0
Bootstrap: 5.2.0
Chrome: Version 109.0.5414.119 (Official Build) (arm64)
macOS: 13.0

**Comment by woasry** [comment]
Same problem on me
@fbasso 

Angular: 14.2.7
ng-bootstrap: 13.1.1
Bootstrap: 5.1.3

**Comment by nrone** [comment]
Still a issue in latest version.

**Comment by sbanulescu** [comment]
This is an issue still :(

**Comment by kazamali110** [comment]
I have the same issue I have used [openDelay]="300" [closeDelay]="500" this resolved my problem.

**Comment by stealthAngel** [comment]
So will this be implemented?
