### ISSUE TITLE
 Can't bind to 'ngModel' since it isn't a known property of 'ngb-datepicker'.

### ISSUE THREAD

**Issue by ayoubkhan558** [ng-bootstrap/ng-bootstrap#3998]
Can't bind to 'ngModel' since it isn't a known property of 'ngb-datepicker'.

![image](https://user-images.githubusercontent.com/20210961/107186743-adb27a80-6999-11eb-9a53-70c9dec806f7.png)

**Comment by maxokorokov** [comment]
Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz
