### ISSUE TITLE
NgbAccordion Panel titles 

### ISSUE THREAD

**Issue by nanda18** [ng-bootstrap/ng-bootstrap#4003]
### Feature Request:
It would be better if the accordion panel header have left arrow , when the panel is collapsed and down arrow when the panel is opened

### Versions of Angular, ng-bootstrap:

Angular:9

ng-bootstrap:9.0.2

**Comment by jnizet** [comment]
Some people would like that, others would not. 
Some would want a `+ / -` icon, others would want a `> / \/` icon. 
So I think it's just preferrable to do it by yourself, which is doable right now, without changing anything to ng-bootstrap.

Here's a quick 'n dirty example: https://stackblitz.com/edit/angular-bptzj1?file=src/app/accordion-header.html

**Comment by maxokorokov** [comment]
I agree with @jnizet, we just have to provide a way to put anything in the header at the moment → https://ng-bootstrap.github.io/#/components/accordion/examples#header

However in bootstrap 5 arrows are there by default → https://getbootstrap.com/docs/5.0/components/accordion/
So when we switch to bootstrap 5 and implement the new accordion, arrows will be there by default → #3898.
