### ISSUE TITLE
'app-toasts' is not a known element?

### ISSUE THREAD

**Issue by ayoubkhan558** [ng-bootstrap/ng-bootstrap#4006]
![image](https://user-images.githubusercontent.com/20210961/107848878-edb79a00-6dab-11eb-9734-e932e2449937.png)

How to resolve this issue?

**Comment by jnizet** [comment]
This should be a Stackoverflow question, not an ng-bootstrap: it has absolutely nothing to do with ng-bootstrap.

You're just trying to use one of your components component, with the selector `app-toasts`, and, as the message says, it's not a known Angular component. So, either you haven't defined it at al, or you have defined it, but forgot to add it to the declarations of your module, or it's defined in another module which is not imported by the module where it's used, or it's defined in a module that you import, but is not exported by the module where it's defined.

Please read https://angular.io/guide/ngmodules, and please only use the ng-bootstrap issues for ng-bootstrap issues or enhancement requests. Not as a way to get help with Angular.

**Comment by purerosefallen** [comment]
I also met the same problem.
`app-toasts` should be exported in either `NgbModule` or `NgbToastModule`. But neither of them imported it.

**Comment by jnizet** [comment]
@purerosefallen `app-toasts`, as the `app` prefix shows, is not part of ng-bootstrap. All components of ng-bootstrap have an `ngb` prefix. Of course ng-bootstrap won't declare a component that is not part of ng-bootstrap.
You've probably seen `app-toasts` used in the guide about the toast component, which explains how your own application could define an app-toasts component if it needs to. It's just an example of an application. `app-toasts` still isn't part of ng-bootstrap.
