### ISSUE TITLE
Pagination is lacking responsive behaviour

### ISSUE THREAD

**Issue by FieteO** [ng-bootstrap/ng-bootstrap#4020]
### Bug description:
The pagination element does not responsively break into a new line, when the screen size decreases.  
![image](https://user-images.githubusercontent.com/41323592/108987233-5566c280-7693-11eb-8ffb-c27d7b1064ad.png)

Adding `flex-wrap` to the `<ul class="pagination">` would already improve the situation from my point of view:  
![image](https://user-images.githubusercontent.com/41323592/108989203-a081d500-7695-11eb-9ece-70ee4aa12ca8.png)

### Link to minimally-working StackBlitz that reproduces the issue:
The [Stackblitz Example](https://ng-bootstrap.github.io/stackblitzes/pagination/basic/stackblitz.html) on the [pagination examples page](https://ng-bootstrap.github.io/#/components/pagination/examples).

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 10.2.4

ng-bootstrap: 8.0.0

Bootstrap: 4.5.3

**Comment by pkozlowski-opensource** [comment]
Prior discussion in #2877

**Comment by maxokorokov** [comment]
Closing as wontfix → https://github.com/ng-bootstrap/ng-bootstrap/issues/2877#issuecomment-442810941 and https://github.com/ng-bootstrap/ng-bootstrap/issues/2877#issuecomment-556979149
