### ISSUE TITLE
Error cannot read property 'viewContainerRef' of undefined in loading dynamic component into a modal

### ISSUE THREAD

**Issue by vickyrathee** [ng-bootstrap/ng-bootstrap#4022]
I was testing `modal` to make a reusable modal in my app to load any component dynamically for quick-view.

But defining `ng-template` inside the `modal-body` doesn't work in bootstrap modal and throw `Cannot read property 'viewContainerRef' of undefined` error

```
<div class="modal-body">
      <ng-template quickView></ng-template>
</div>
```

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-quickview

**Comment by maxokorokov** [comment]
I'm sorry I have no idea why it is related to ng-bootstrap.
In your example `modal-component.html` doesn't contain `QuickviewDirective`, so `@ViewChild()` is `undefined`
