### ISSUE TITLE
Nav component's content part is not being rendered

### ISSUE THREAD

**Issue by AkbarKarshiev** [ng-bootstrap/ng-bootstrap#4026]
### Bug description:
When using Nav component as in documentation, content provided in ```<ng-template ngbNavContent></ng-template>``` is not being rendered. Even though I installed package using ng add (Angular CLI). Got the same issue locally and in stackblitz project.

Meanwhile, other components working properly

### Link to minimally-working StackBlitz that reproduces the issue:

[demo](https://stackblitz.com/edit/angular-ivy-bcvwyv?file=src/app/app.component.html)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 11.0.9(stackblitz), 11.2.0(locally)

ng-bootstrap: 9.0.2(stackblitz), 9.0.2(locally)

Bootstrap: 4.6.0(stackblitz), 4.5.0(locally)

**Comment by jnizet** [comment]
Hi.

You didn't include any `ngbNavOutlet` anywhere. That's where the tab content is displayed, as explained in the documentation and shown in all its examples.

Here's your fixed stackblitz: https://stackblitz.com/edit/angular-ivy-dacq4l?file=src%2Fapp%2Fapp.component.html

**Comment by AkbarKarshiev** [comment]
Thanks a lot, didn't notice ngbNavOutlet. My mistake)))
