### ISSUE TITLE
[destroyOnHide]="true" is just hiding the DOM(component), but I want to remove DOM(non-active nav content) completely

### ISSUE THREAD

**Issue by rammohangowd** [ng-bootstrap/ng-bootstrap#4029]
[destroyOnHide]="true" is just hiding the DOM(component), but I want to remove DOM(non-active nav content) completely. Any alternative way to do that or any attributes available.

 

I have observables and subscriptions and have an issue with this, because of hide the component  is still subscribing. so wanted to check any other attribute available, so that the component completely destroyed?

**Comment by maxokorokov** [comment]
I don't quite understand what you mean. For example take a look at this one → https://stackblitz.com/edit/angular-yvctys?file=src%2Fapp%2Fnav-keep-content.html where everything is destroyed.

Check the demo as well → https://ng-bootstrap.github.io/#/components/nav/examples#keep-content

But most importantly please fill the issue correctly, provide more info and and a stackblitz.
---

Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz
