### ISSUE TITLE
Animations not working at all

### ISSUE THREAD

**Issue by Zwergenpunk** [ng-bootstrap/ng-bootstrap#4033]
### Bug description:

When checking out the repository or on the demo page no animation is working. Should it work on the demo page?
Or do we have to add some custom code for the animation.

### Link to minimally-working StackBlitz that reproduces the issue:

https://ng-bootstrap.github.io/#/components/modal/examples

### Versions of Angular, ng-bootstrap and Bootstrap:

"master branch or 9.0.2"

**Comment by fbasso** [comment]
Yes, everything is fine on the demo site, the animations are there.

Does it work for you on the Bootstrap website ? Maybe it's related to your OS settings (see https://getbootstrap.com/docs/4.6/getting-started/accessibility/#reduced-motion).

**Comment by Zwergenpunk** [comment]
Thanks for the reply. I work since 1 year in an rdp window....
I just opened the website on the default computer and there were animations.
