### ISSUE TITLE
Accordion: decide what to do with panels

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#404]
Current accordion implementation is based on `.panel-...` css classes, that are already removed from the BS4.

Current markup:

```html
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">
      ...
    </h4>
  </div>
  <div class="panel-collapse">
    <div class="panel-body">
      ...
    </div>
  </div>
</div>
```

So there might be several solutions for the accordion:
- There are `card-` classes as alternatives, (but I don't see any benefit in creating a standalone `NgbCard` component from it)
- We might generate an empty markup and just stack user provided title and content templates
- Get rid of the accordion :)
- Something else ?

Will add a plunker link soon with examples

**Comment by Foxandxss** [comment]
The `card-` gives a much nicer accordion look, but I don't think we need a `NgbCard`, just use the needed classes.

Accordion won't away, is my favorite component :P

**Comment by pkozlowski-opensource** [comment]
Yeh, I'm voting for card-based markup as well at this point. Having plunks showing the alternative would help us to decide.

**Comment by maxokorokov** [comment]
Here is the plunker http://plnkr.co/edit/16PnAouHIsH4ACDNbpKH?p=preview

**Comment by pkozlowski-opensource** [comment]
> Here is the plunker http://plnkr.co/edit/16PnAouHIsH4ACDNbpKH?p=preview

I must say that I kind of like it! It is definitively more "accordeonish" than the look & feel we've got right now

**Comment by sendilkumarn** [comment]
this layout is really good than existing.
