### ISSUE TITLE
The month name in ngbDatepicker is not visible

### ISSUE THREAD

**Issue by DanAtkinson** [ng-bootstrap/ng-bootstrap#4052]
### Bug description:
The month name in ngbDatePicker no longer appears to be visible.

It also seems to be related to whether the `container="body"` attribute is set (see bottom of this issue). I was going to do a reproduction of this issue in Stackblitz using the ngbDatePicker but the months were not showing without me doing anything.

### Link to minimally-working StackBlitz that reproduces the issue:
https://angular-ymncqs.stackblitz.io/

**NB:** This is a fork of the 'basic datepicker' found on [examples page](https://ng-bootstrap.github.io/#/components/datepicker/examples). There are **no** differences to the templates whatsoever.

This is what it renders:
![image](https://user-images.githubusercontent.com/23440/113129627-06242c80-9213-11eb-9e40-b365e855081d.png)

That's different to what the [examples page](https://ng-bootstrap.github.io/#/components/datepicker/examples) shows however and I can't explain the discrepency:
![image](https://user-images.githubusercontent.com/23440/113129553-f1479900-9212-11eb-9b36-ed3a88b4a1ce.png)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 11.0.9

ng-bootstrap: 9.1.0

Bootstrap: 4.5.3

### Anything else:

This has been raised as an issue on our website and started occurring when the `container="body"` attribute was applied.
![image](https://user-images.githubusercontent.com/23440/113130286-d164a500-9213-11eb-82d9-e40da06903db.png)

If the attribute is removed then the months re-appear. However, this causes display issues as the datepicker renders _underneath_ other elements (not shown).
![image](https://user-images.githubusercontent.com/23440/113130499-0d980580-9214-11eb-8223-abd09d4cfdd0.png)

In our site, the versions are as follows:

Angular: 11.2.5
ng-bootstrap: 9.0.2
Bootstrap: 4.5.3

Thanks, Dan

**Comment by DanAtkinson** [comment]
Is there any further update on this?

Last I can see, it was moved to the 9.1.4 milestone but the current version is 11 beta and 10 stable.

Thanks
Dan

**Comment by ExFlo** [comment]
Hi @DanAtkinson I have not the issue with version 10.0.0 of ng-bootstrap

**Comment by DanAtkinson** [comment]
@ExFlo : I can confirm that this is not an issue with the following version:

Angular: 12.0.5
ng-bootstrap: 10.0.0
Bootstrap: 4.5.3

![image](https://user-images.githubusercontent.com/23440/145022760-018648d6-5f58-4883-af23-2971f350db55.png)

Thanks
Dan
