### ISSUE TITLE
Typeahead custom template

### ISSUE THREAD

**Issue by jloracudris** [ng-bootstrap/ng-bootstrap#4059]
### Bug description:
Not sure if its a bug, but is it possible to show typeahead results in a table? i have been trying to use it with the template but once inside the template you only have results and not able to set those results to a `tr` for example or use it on a table lib (like ng2-smart-table)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 11

ng-bootstrap: latest

Bootstrap: 4.xx

**Comment by pkozlowski-opensource** [comment]
I'm sorry but the problem description here is very vague and not actionable as-is. Please open a new issue with a minimal reproduce scenario if you still face problems in your project.
