### ISSUE TITLE
Dropdown opens on [Enter] keypress of another input field inside a form

### ISSUE THREAD

**Issue by RonnBlack** [ng-bootstrap/ng-bootstrap#4060]
### Bug description:
Dropdown menu shouldn't open when enter is pressed on a different input field in the same form group.
The problem only occurs if the drop-down is constructed with a button for the anchor and is the first button inside the form. 

### Link to minimally-working StackBlitz that reproduces the issue:

Stackblitz with examples inside and outside a form for comparison
https://stackblitz.com/edit/ng-bootstrap-enter-key-bug?file=src/app/dropdown-basic.html

#### To reproduce:
* Click into the input-field marked with **"<== Focus here and press [Enter]"**
* Press the Enter key
* Dropdown will open but it shouldn't

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 11.09
ng-bootstrap: 9.1.0

### Additional Information:
I've researched the problem pretty thoroughly and I am preparing a pull request to resolve the issue. 

The root cause is related to the native browser event handling shown in this HTML and JavaScript only:
https://stackblitz.com/edit/html-js-form-with-input?file=index.html

Following the instructions in this HTML & Javascript only example you see that when enter is pressed on the input field you get the following events (in order):
        1. Input[keypress]
        2. Form[keypress]
        3. Button[click] (On the first button even if there is button with type "submit")
        4. Form is submitted which causes navigation event.

The problem occurs because the ng-bootstrap directive ngbDropdownToggle directly ties the click event to dropdown.toggle()  which doesn't take into account if the anchor element has focus.

**Comment by jnizet** [comment]
The default type of a `<button>` is `submit` (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button). So, in both of your examples, pressing enter in a form field is equivalent to pressing the first button because its type is `submit`. You should explicitly set the button type to `button` is you don't want it. If you do it, in both of your demos, you'll see that the dropdown is not opened, and that the button that is clicked is `button#btn2`.

- to be clicked when the form is submitted by pressing enter in the input
- to submit the form when clicking it

We should fix the examples in the demos to add the `button` type on those buttons, even if they're not inside forms.

**Comment by RonnBlack** [comment]
Thanks for the clarification..
I guess I was mistakenly thinking that it defaulted to type of "button" if not specified.

I can change my pull request to change the demos if you like. Are there other places that would also be needed?

**Comment by RonnBlack** [comment]
I had a thought. Would it make sense for the directive to apply the type="button" automatically to the anchor element? I can't see why anyone would want the element that is toggling open/close to perform a submit.

**Comment by jnizet** [comment]
My *personal* opinion is that
- yes, it would be nice for the demos to have `type="button"` on the dropdown buttons
- no, I wouldn't like the directive to apply the type: it can be trivially done by the user, if someone really want a submit button, it would be harder, it would add complexity and hide things, and it can only be done on buttons, but a dropdown can also be triggered by a link, or by anyother clickable element.

**Comment by RonnBlack** [comment]
I was actually thinking about only applying it if the anchor was a button and the type wasn't specified. Not a big deal if you think it is a bad idea.

As for the demo's, does the CI also push updates to the Stackblitz demo's?

**Comment by jnizet** [comment]
Yes. The stackblitzes are automatically generated from the code of the demos.
