### ISSUE TITLE
Date range limits in NgbDatepickerConfig can't be reset during runtime

### ISSUE THREAD

**Issue by AlaaOthman98** [ng-bootstrap/ng-bootstrap#4070]
### Bug description:

I am trying to make limits for date range during runtime depending on some dates that I will get from my project API. I am using NgbDatepickerConfig to set minDate and maxDate, although the configuration object is changed, the date picker still wasn't affected by these updates even if it is reflected with the changes of configurations that are in the component's constructor during initialization. I searched in the previous issues but I didn't get a working solution and the issue still exist.

### Link to minimally-working StackBlitz that reproduces the issue:

Here is a demonstration link: [StackBlitz](https://stackblitz.com/edit/angular-d3cnrh)

### Versions of Angular, ng-bootstrap, and Bootstrap:

In my working project versions are:

Angular: 11.0.5

ng-bootstrap: 8.0.0

Bootstrap: 4.5.3

**Comment by jnizet** [comment]
Your demo changes the config *after* the datepicker has been constructed. The datepicker reads the config values at construction time, but doesn't watch the configuration changes. If you call `this.changeDateLimits();` in the constructor of your component, the datepicker wil see the correct limits when it's constructed and use them.

So, either make sure to avoid constructing he datepicker before its configuration is ready, or pass minDate and maxDate inputs to the datepicker directly.

**Comment by AlaaOthman98** [comment]
This is what I need, I want to change the configuration of the date picker and set the limits after constructing the date picker as the limits are not known until I got them from an API. So, is there any solution to perform this action after constructing date picker?

**Comment by AlaaOthman98** [comment]
#3438 
Here in this issue, the author describes the same problem that I face, and it is written that this issue was solved in #3507 but I am still facing it.

**Comment by jnizet** [comment]
I think I already provided a solution above. Changing the config is only useful for datepickers created **after** the change, because the config is used to **initialize** the datepicker inputs.
To change the inputs of existing datepickers, do just that: change the alue of their inputs: https://stackblitz.com/edit/angular-xlogwq?file=src%2Fapp%2Fapp.component.ts.

**Comment by AlaaOthman98** [comment]
@jnizet Awesome, thanks a lot for your help!
