### ISSUE TITLE
Can't set custom id on [ngbNavItem]

### ISSUE THREAD

**Issue by martinhschei** [ng-bootstrap/ng-bootstrap#4072]
![image](https://user-images.githubusercontent.com/21332243/115386638-eeb8dd80-a1d9-11eb-804a-d9c82310e161.png)

According to the documentation it should be possible to set the id for each tab and that the only limitation is that a empty string is not allowed; https://ng-bootstrap.github.io/#/components/nav/overview as described under the section "Selection / active nav".

But it seems to not be working (ref. the screen dump over).

Testing locally it seems to not accept any other id's that numbers.

Is this screendump i console.log the event on tab change.
![image](https://user-images.githubusercontent.com/21332243/115387126-89192100-a1da-11eb-86fa-35b64a42faf9.png)

```
  <li [ngbNavItem]="11"> 
    <a ngbNavLink>Test A</a>
    <ng-template ngbNavContent></ng-template>
  </li>

  <li [ngbNavItem]="12"> 
    <a ngbNavLink>Test B</a>
    <ng-template ngbNavContent></ng-template>
  </li>
  
  <li [ngbNavItem]="nav-foo"> 
    <a ngbNavLink>Test C</a>
    <ng-template ngbNavContent></ng-template>
  </li>
```

Is the documentation wrong or am i doing something wrong?

**Comment by peterblazejewicz** [comment]
Those are OK, but require to stick to the rules for template variable evaluation. Numbers evaluate always properly, but a string, so you need quotes IMO `nav-foo`, or this should be proper reference

**Comment by martinhschei** [comment]
Ah - haha - my bad! 

Doing this works perfect - thanks!

```
 <li [ngbNavItem]="'nav-foo'"> 
    <a ngbNavLink>Test C</a>
    <ng-template ngbNavContent></ng-template>
  </li>
```
