### ISSUE TITLE
No compilation error when NgbTooltipModule is not imported

### ISSUE THREAD

**Issue by david-bulte** [ng-bootstrap/ng-bootstrap#4074]
### Bug description:

Maybe this is some angular issue and not ng-bootstrap specific. Still, what I see is surprising. I am using ngbTooltip directive, but have forgotten to import the module (or any ng-bootstrap module for that matter). The tooltip is not working (what is expected behaviour) yet the build is succesfull. I would expect my build to fail in that case.

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-72wpu4?file=src/app/tooltip-basic.module.ts

(You can see I do not import any bootstrap modules in NgbdTooltipBasicModule)

**Comment by jnizet** [comment]
Indeed, i don't think there's anything ng-bootstrap can do. You can, however, replace `ngbTooltip="Tooltip on left"` by `[ngbTooltip]="'Tooltip on left'"`, ad that will cause a compilation error.
