### ISSUE TITLE
my hamburger side menu is not working

### ISSUE THREAD

**Issue by learning-goSlow** [ng-bootstrap/ng-bootstrap#4081]
<body>
			<div id="hamburger" class="sidenav">
				<a href="javascript:void(0)" class = "closebtn" onclick="closeNav()">&times;</a>
				<a href="MYCV.html">Home</a>
				<a href="MyStory.html">My Story</a>
				<a href="Career.html">Career</a>
				<a href="Education.html">Education</a>
				<a href="Contact.html">Contact</a>
				
			</div>
									
			<span style="font-size:30px;cursor:pointer" onclick =" openNav()">&#9776;</span>
			
			<script>
				function openNav(){
				document.getElementById("hamburger").style.display="block";
			
				function closeNav(){
				document.getElementById("hamburger").style.display="none";
			</script>

Have copied this from what was being taught in the class and i don't understand why is it not working for me
also the href of closebtn..don't understant what it links to? If it's right..
new to html and java 
Please help

**Comment by jnizet** [comment]
This doesn't seem like a bug report for ng-bootstrap, but rather like a question about some JavaScript code, that is unrealated to ng-bootstrap, and even to Angular. I'm thus closing it.

**Comment by learning-goSlow** [comment]
No problem 
It was just a missing bracket :)
