### ISSUE TITLE
The rating component's rateChange documentation is confusing. 

### ISSUE THREAD

**Issue by IAfanasov** [ng-bootstrap/ng-bootstrap#4084]
### Bug description:

[The documentation](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/rating/rating.ts#L118) for `NgbRating.rateChange` states:
> An event emitted when the user selects a new rating.

The event could be emitted without any actions from a user.

The good candidate would be: 

> An event emitted when the rating is changed.

### Link to minimally-working StackBlitz that reproduces the issue:

N\A

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: N/A

ng-bootstrap: 9.1.0

Bootstrap: N/A

**Comment by IAfanasov** [comment]
maybe a `Good First Issue`?

**Comment by maxokorokov** [comment]
Agreed!
