### ISSUE TITLE
Nav of ngbNavContent is not showing

### ISSUE THREAD

**Issue by linyihong** [ng-bootstrap/ng-bootstrap#4086]
When I Using Angular Over Version  11.2 

Using your Component of Nav  Sample Code

But It will not show ngbNavContent

[Demo app](https://stackblitz.com/edit/angular-ivy-uwhcai?file=src%2Fapp%2Fapp.component.html)

Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 11.2.13

ng-bootstrap: 9.1.0

Bootstrap: N/A

**Comment by linyihong** [comment]
I Found the problem. Thx.

**Comment by troddick** [comment]
I am having the same issue after upgrading angular to 12 and ng-bootstrap to 10. I am trying to change my nbg-tabset to ngbNav and am not able to see the content inside of <ng-template ngbNavContent> 
How did you fix the problem @linyihong  ?
