### ISSUE TITLE
An unhandled exception occurred: The target entry-point "ngx-bootstrap" has missing dependencies:

### ISSUE THREAD

**Issue by victorz-airsoft** [ng-bootstrap/ng-bootstrap#4088]
Hi guys, i have upgraded our Angular project from version 6 to version 11. My current Angular version is 11.2.13.
Tryed to integrate the latest @ng-bootstrap/ng-bootstrap version 9.1.0 in my project, and got the following error:

Compiling @ng-bootstrap/ng-bootstrap : es2015 as esm2015
An unhandled exception occurred: The target entry-point "ngx-bootstrap" has missing dependencies:
 - @angular/forms/src/directives/control_value_accessor
 - @angular/core/src/type
 
![ngx-bootstrap-compilation-error](https://user-images.githubusercontent.com/54435788/117852487-0989e980-b290-11eb-99df-d35fe29f2864.PNG)

Please advise

**Comment by maxokorokov** [comment]
You should try the usual first: clean npm cache, remove node_modules, update package lock file, etc.
And then probably see with ngx-bootstrap team, as the issue mentions that package.

**Comment by victorz-airsoft** [comment]
I have already tried the "usual" you have mentioned. I also have downgraded
the angular and ngx-bootstrap versions, still getting the same error.
Assume that i am "after usual staff", that's why had to open the issue

**Comment by victorz-airsoft** [comment]
The error, that has been thrown is caused by lack of dependencies in later angular/forms and angular/core code. Please reopen the issue and provide the solution

**Comment by bbarry** [comment]
@victorz-airsoft this project is for "ng-bootstrap", your error mentions "ngx-bootstrap" which is a different unrelated project. There is nothing to reopen here.

**Comment by victorz-airsoft** [comment]
Ok, my mistake. Thanks guys for help anyway 🙏
