### ISSUE TITLE
Angular 12 support

### ISSUE THREAD

**Issue by aksdevac** [ng-bootstrap/ng-bootstrap#4093]
### Feature description:
[Angular 12](https://github.com/angular/angular/releases/tag/12.0.0) is released & I have successfully upgraded one of my small project using ng-bootstrap `9.1.1` & Angular `12.0.0`, but having official support would be good & Thank you for this great library.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 12.0.0

ng-bootstrap: 9.1.1

Bootstrap: 4.6.0

**Comment by maxokorokov** [comment]
Hey, @aksdevac! Thanks for opening the issue.

FYI, the current plan is:
- `9.x.x` to continue support Angular 11 and Bootstrap 4
- `10.x.x` (not released yet) will support Angular 11 and Bootstrap 4
- `11.x.x` (`beta.1` released) will support Angular 12 and Bootstrap 5. However at the moment `beta.1` is still on Angular 11, this will change in future beta releases.

So main things to remember are:
- We'll do bugfixes for `10.x.x` a bit longer than usual as it is the last version to support Bootstrap 4
- Support for Bootstrap 5 will start with Angular 12

**Comment by r-ising** [comment]
Hey @maxokorokov,

what is the different between version 9 and 10? Is it a typo? Do you mean version 10 supports angular 12 and bootstrap 4?

Thanks

**Comment by maxokorokov** [comment]
@r-ising, yep you're right, sure it's an unfortunate typo. Sorry about that, fixed now.

**Comment by grunk** [comment]
Hi, 
can we safely upgrade to Angular 12 with ng-bootstrap 9 until the v10 is available ?
Or is it recommended to wait ?
Thanks

**Comment by jorde-sbss** [comment]
@grunk Looks like it worked for the TS, so it will likely work.

Unless you mean with Bootstrap 5 as well? Then you should try the 11.x beta.

**Comment by grunk** [comment]
Just finished a migration to angular 12 with bootstrap 4 and ng-bootstrap 9.
It seems to work perfectly fine. Just  had to --force the angular migration because ng-bootstrap was requiring Angular 11

**Comment by MRdNk** [comment]
Any chance of an official release soon? Would like to upgrade to Angular 12

**Comment by internalsystemerror** [comment]
I made available a PR #4099 which should add the necessary changes, when can we get this merged?

**Comment by CesarD** [comment]
With a PR submitted already a week ago, what is the wait to finally approve it??
Come on, we want to upgrade to Angular 12 for once! 😄

**Comment by optimistex** [comment]
Only this library does not let me upgrade my project to Angular 12. Is there any ETA for solving this?

**Comment by grunk** [comment]
> Only this library does not let me upgrade my project to Angular 12. Is there any ETA for solving this?

You can use ng bootstrap 9 with angular 12 , if you really need to upgrade.
It's working fine on every project of mine

**Comment by RogierVC** [comment]
> You can use ng bootstrap 9 with angular 12 , if you really need to upgrade.
> It's working fine on every project of mine
Yeah, by forcing the update, but that's not how it should work....

**Comment by skythomp16** [comment]
Any ETA on this?  Have a new project with Angular 12 and sitting at the point where we either need to downgrade to Angular 11 or force install of this as a dependency regardless of the conflicts.

**Comment by gauravshah27** [comment]
First of all thanks for all the work that you are doing to release this. we use ng-bootstrap exclusively for our applications and we have following combinations in our applications:
1) Angular 12 - bootstrap 4 (ng-bootstrap 10.x should address this as per comments above) 
2) Angular 12 - bootstrap 5

I do not see any branches/tags (alpha, beta, RC or release) for ng-bootstrap 10.x and so am using ng-bootstrap 9.1.3 for angular 12 upgrade with bootstrap 4.  is that something that is still in the works? Any ETA on this would be greatly appreciated @maxokorokov 

I have not seen any issues on our applications so far with ng-bootstrap 9.1.3 and angular 12.0.5 - but we also provide a shell project that is based off of ng-bootstrap that other developers can use to get started with angular projects and am concerned that there are components that might not be compatible with ng-bootstrap 9.1.3 for angular 12 - do you have some sort of a list of incompatible components for this combination?

**Comment by internalsystemerror** [comment]
@gauravshah27 there is a PR waiting (#4099) [and waiting ... ] which will (hopefully) be released as v10. The bootstrap v5 upgrade branch will then be rebased from this.

To corroborate your final comments. I can say that (at least for us where I'm working) there haven't been any issues using the current ng-bootstrap v9 on Angular 12 in production (which we rolled out a couple of weeks ago), but obviously YMMV.

**Comment by serenecloud** [comment]
We're in the same boat with having Angular 12. I've held off doing the forced install for as long as I can, today is the day we go for it.

I understand things can get busy and this might take a while to be merged. I appreciate the efforts of @internalsystemerror and the ng-bootstrap team for making all this possible. An estimate for review & merge might help some teams, including ours, plan their development.

**Comment by reflexdemon** [comment]
I know this team is extremely busy and actively working on getting the latest and greatest out for everyone. Can someone please provide a ballpark estimate of when we can expect Angular 12 Official Support for our `NG Bootstrap` be available?

This is putting our internal deadlines at jeopardy and often find it difficult to have that communicated to the leadership teams at organization.

Any light on when this would be very helpful?

Thanks for whatever you are doing. It is great library that not only us, a lot of people depend on.

**Comment by CesarD** [comment]
It's great that this got closed, but when is the new release being published into NPM?
This completed yesterday but I don't see the new version online.
Thanks.

**Comment by DouglasLapsley** [comment]
Yes please from me on Angular 12 support please.  This is the only package preventing my upgrade at the moment.

**Comment by reflexdemon** [comment]
NPM Publish? People are waiting!!!

![](https://media.giphy.com/media/RMhbmeqWeOBQIiQkS4/giphy.gif)

**Comment by Clashsoft** [comment]
Please stop spamming "when will this be published". I bet the maintainers are also keen to release this but it shouldn't be rushed. Spamming only gets this thread locked.

**Comment by DouglasLapsley** [comment]
Thank you for version 10.  Installed and works a charm with Angular 12.  Amazing and much appreciated.

**Comment by MRdNk** [comment]
> Thank you for version 10. Installed and works a charm with Angular 12. Amazing and much appreciated.

Genuinely appreciate the work gone into releasing this. Thank you for the hard work.

**Comment by AbhijithSugunan** [comment]
Still with version 10, am getting the follow error with angular 12

PS C:\workspace\Projects\deserv-angular> npm i @ng-bootstrap/ng-bootstrap
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: deserv-angular@1.0.0
npm ERR! Found: @angular/compiler@12.0.5
npm ERR! node_modules/@angular/compiler
npm ERR!   @angular/compiler@"~12.0.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@"12.2.3" from @angular/localize@12.2.3
npm ERR! node_modules/@angular/localize
npm ERR!   @angular/localize@"^12.0.5" from the root project
npm ERR!   peer @angular/localize@"^12.0.0" from @ng-bootstrap/ng-bootstrap@10.0.0
npm ERR!   node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!     @ng-bootstrap/ng-bootstrap@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\HN765CB\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HN765CB\AppData\Local\npm-cache\_logs\2021-08-28T12_37_35_213Z-debug.log
