### ISSUE TITLE
Please use GitHub Releases

### ISSUE THREAD

**Issue by ffes** [ng-bootstrap/ng-bootstrap#4094]
Right now new versions are tagged and the website is updated, but no [release](https://github.com/ng-bootstrap/ng-bootstrap/releases) is created. The big advantage of creating a release is that users who watch releases through GitHub get a [notification](https://github.com/notifications) on github.com and probably in their mail as well.

So could you please consider creating a release on GitHub as well?

It doesn't have to be packed full with a very detailed changelog (although that would be nice to have, just copy-paste the relevant part), but just a notification that a new version has been release would already be very helpful.

**Comment by maxokorokov** [comment]
Thanks, @ffes, I'm not sure why we haven't been doing it before.
I've done this for a couple of latest releases, but will leave the issue open to check what can be automated in this process.
