### ISSUE TITLE
Popover not scrollable anymore

### ISSUE THREAD

**Issue by Zwergenpunk** [ng-bootstrap/ng-bootstrap#4103]
### Bug description:

With the new changes to popover css (https://github.com/ng-bootstrap/ng-bootstrap/commit/58b60b41c4919892143c07e150d6876d962a39f4)  you broke scrollable popovers. When the css class on the popover adds the overflow-y you cannot scroll the popover anymore.

With version 9.1.0 it is perfectly scrollable.

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-rhgv44?file=src%2Fapp%2Fpopover-tplcontent.html

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 11

ng-bootstrap: 9.1.1

Bootstrap: 4

**Comment by fbasso** [comment]
Hi @Zwergenpunk, thanks for opening the issue.

Could you please explain more the issue ? I tried your stackblitz, and the popover is scrollable.

![Popover](https://user-images.githubusercontent.com/1152930/120444640-19c15000-c388-11eb-9587-4cee4750377b.gif)

**Comment by Zwergenpunk** [comment]
Thanks for the feedback

I'm super confused.
I will check it at work next week.

**Comment by Zwergenpunk** [comment]
You need to check which version is installed:
This is somehow the default, even though in the package.json is the correct version referenced.

![image](https://user-images.githubusercontent.com/7661170/120979847-46a1a880-c776-11eb-88f5-2c160e7504da.png)

When you change the version to 9.1.1 in the package.json it installs correctly and the scrolling is not possible

**Comment by fbasso** [comment]
Thanks for your clarification @Zwergenpunk.  In fact, I downloaded the stackblitz example and ran it locally, so I had the right version.

I quickly tried it on Firefox and saw it worked, but after a closer look now, it seems that the issue is only on Chrome.
It requires further investigations.
