### ISSUE TITLE
Consider releasing v10 in partial-Ivy format

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#4119]
Version 10 targets Angular 12, which allows releasing and consuming libraries in "partial-Ivy" format.

This format allows skipping the ngcc pre-compilation phase and thus makes builds faster. It's now the recommended format for libraries targeting Angular v12 or later, and the view engine format is now legacy.

See https://angular.io/guide/creating-libraries#building-libraries-with-ivy for details.

Is there any reason why the newly released v10 version of ng-bootstrap still uses the legacy format?

**Comment by maxokorokov** [comment]
@jnizet, I can't come up with any reasons at the moment :)
