### ISSUE TITLE
Node and NPM versions required in DEVELOPER.md seem incorrect

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#412]
The document says 

> Node.js, (version >=4.2.1 <5) which is used to run tests, and generate distributable files. We also use Node's Package Manager, npm (version >=2.14.7 <3.0)

but the CI build seems to use newer versions than that, so I guess these versions are outdated.

**Comment by Foxandxss** [comment]
Indeed. I will update it personally. I researched a lot on that to see which versions are OK.

**Comment by pkozlowski-opensource** [comment]
Fixed in 61e4649c13a2bbf7562e04b886d2b0b1e4579629
