### ISSUE TITLE
Importing specific modules in app.module ?

### ISSUE THREAD

**Issue by jspaeter** [ng-bootstrap/ng-bootstrap#4120]
### Bug description:
It seems like importing specific modules (eg: `NgbModalModule`) in `app.module` still loads all the lib. Not sure if my issue is related to #2883 as I don't have any lazy loading in my app.

### Link to minimally-working StackBlitz that reproduces the issue:

Sorry, I can't reproduce as the bundle analyzer don't work in StackBlitz

`app.module.ts`
```
import { NgbCarouselModule, NgbModalModule } from '@ng-bootstrap/ng-bootstrap';

imports: [
    NgbModalModule,
    NgbCarouselModule,
]
```
Result :

![image](https://user-images.githubusercontent.com/15154959/124250779-7cdc0900-db25-11eb-9b03-4a34313cd7a3.png)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 11.1.2

ng-bootstrap: 9.1.3

Bootstrap: 4.5.0

**Comment by maxokorokov** [comment]
Hey, @jspaeter, a Github repo with the minimal CLI project would do.
Also please check https://github.com/ng-bootstrap/ng-bootstrap/issues/3919

**Comment by jspaeter** [comment]
Hello, thanks for your reply. It seems like you where right, `webpack-bundle-analyzer` runs before optimisations so the bundle size is not correct.
Source : https://www.youtube.com/watch?v=-eH2gCGHcGs&t=995s

![image](https://user-images.githubusercontent.com/15154959/124439375-a1c8ba00-dd79-11eb-910d-a1104f4e7c17.png)

Thank you !
