### ISSUE TITLE
Typeahead displays "x result available" text (bootstrap5 and ng-bootstrap v10)

### ISSUE THREAD

**Issue by juliehoaas** [ng-bootstrap/ng-bootstrap#4121]
### Bug description:

The typeahead displays the "x result available" aria-text. Looks like the class on the div is `sr-only`, and not `visually-hidden`.

In the example, search for and select Oregon.

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-dxtjkh?file=src/index.html

(The only thing I changed was the reference to the Bootstrap CSS, to use version 5.0.2 instead)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 12.0.5

ng-bootstrap: 10.0.0

Bootstrap: 5.0.2

**Comment by fbasso** [comment]
Thanks for your report, @juliehoaas, but ng-Bootstrap 10 is designed to work with Bootstrap 4. Support for Bootstrap 5 is planned for the next version. 

You can try nb-Bootstrap 11 beta (with Angular 11 for now).

**Comment by juliehoaas** [comment]
Ah, my bad, I mis-read a comment on another issue, where it referenced the plans for the next version(s).
I can work around it for now, with ng-bootstrap 10 and Angular12 :)
Thank you for your reply! Feel free to delete this :)
