### ISSUE TITLE
Opened modal does not remove scrollbar of body (Bootstrap5)

### ISSUE THREAD

**Issue by Zwergenpunk** [ng-bootstrap/ng-bootstrap#4128]
When a modal is openend, the body scrollbar is still visible and the background is scrollable.

It looks like the `overflow:hidden` class for `body.modal-open` was removed and the stylings are applied in the js directly on the body

For an example, just run the demo on the bootstrap 5 branch an open any modal

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 12

ng-bootstrap: 11.0.0-beta.2

Bootstrap: 5.0.2

**Comment by kenma262** [comment]
a

**Comment by NickeManarin** [comment]
Also happens with me. Any news on fixing this issue?

**Comment by ShenZZ** [comment]
set overflow on body when modal is active,
then close the modal,  the container will scrall to top.
current position is changed!

**Comment by fbasso** [comment]
Closed by #4238
