### ISSUE TITLE
ngb-accordion not loading content

### ISSUE THREAD

**Issue by sb-developers** [ng-bootstrap/ng-bootstrap#4138]
### Bug description:
Hi,
The content of the ngb-accordion is not being seen in some cases. We have not been able to detect in which cases or why it is not shown, but you reload the page and you can see the content ((https://prnt.sc/1inaqtt)). 

https://drive.google.com/file/d/1LpFdL7D5rwP56N-21WzUK3PQ4CBPt5kI/view

Can you help us to fix this error?

Thanks

### Link to minimally-working StackBlitz that reproduces the issue:

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 11.0.2

ng-bootstrap: ^7.0.0

Bootstrap: ^4.5.0

**Comment by aksdevac** [comment]
it seems you are not using compatible versions, Angular 11 support was added in ng-bootstrap `9.x`.

**Comment by sb-developers** [comment]
Hi Akash,
We update ng-bootstrap versión, but didn't fix the error. 
Something more to try?
Thanks in advance,

**Comment by pkozlowski-opensource** [comment]
This sounds like a support request and we are not answering those on the issue tracker: https://github.com/ng-bootstrap/ng-bootstrap#getting-help

If you believe that there is a bug in the library itself please provide a minimal reproduce scenario: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by sb-developers** [comment]
Hi Pawel,
Excuse me, because we didn't told you that we found the problem.
It wasn't a bug. We use badly ng-accordion properties and it was working incorrectly.
Specifically, we are using "activateIds" property, but then we didn't assign id to the ng-templates.
Thanks for help,
