### ISSUE TITLE
Code in black background in demo is hard to read

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#414]
I have, like almost 10% of the male population, a (light) color vision deficiency.
This makes it quite hard for me to read the code in the demos, mainly because their background is black (the purple or pink or whatever color used for html elements, in particular, is hard for me to read).

I know JavaScript hipsters like their dark background :-) But in my experience, I and other people I know who have color vision deficiencies have much less problem reading code when it's more traditionally written in black or dark colors, on a white background.

Would you consider changing the color theme of the code, or providing a simple way to switch to a more traditional color theme?

**Comment by Foxandxss** [comment]
We were supposed to put a different color and we forgot. What do you think about solarized light?

**Comment by mendeza** [comment]
Yes, Solarized Light or Default.
This is good info to have - I didn't know the dark theme was problematic, even though my team does quite a bit of A11y work. We've been using the dark Okaidia theme in our project (internal Thomson Reuters), but will definitely change it now.

**Comment by Foxandxss** [comment]
The only part not accessible from that theme is the red with that BG.

**Comment by icfantv** [comment]
@Foxandxss we were?  i thought you _loved_ okaidia.

**Comment by pkozlowski-opensource** [comment]
+1 for changing to a lighter background. I had this feedback from a designer at my work-place

**Comment by jnizet** [comment]
Solarized light is better, but lacks contrast to make it really comfortable **for me**. OK for demo code, but I wouldn't make it the default for my IDE. To my eyes, the boring default mode is the best.

**Comment by sendilkumarn** [comment]
+1 for solarized light.
