### ISSUE TITLE
NgbCheckbox: cannot set the active property of the ngbButtonLabel

### ISSUE THREAD

**Issue by PierreKoung** [ng-bootstrap/ng-bootstrap#4144]
### Bug description:
Cannot access the active property of the ngbButtonLabel for set it !
the api allows us to modify the disable property but we cannot modify the focused property or the active property programmatically in either the component nor the template.

Angular: 12

ng-bootstrap: 11.0.0-beta.2

Bootstrap:5.0.2

**Comment by pkozlowski-opensource** [comment]
This is by design - the active property is set automatically in response to the `ngModel` binding change, see: https://github.com/ng-bootstrap/ng-bootstrap/blob/82e8b380c93cd79079329d1dc3cbc60a2c329e35/src/buttons/checkbox.ts#L73

Not sure what it your exact use case and why you would like to set "active" through the API call but the current widget works as designed. If you've got a particular use-case that is not covered please let us know.

**Comment by PierreKoung** [comment]
> This is by design - the active property is set automatically in response to the `ngModel` binding change, see:
> 
> https://github.com/ng-bootstrap/ng-bootstrap/blob/82e8b380c93cd79079329d1dc3cbc60a2c329e35/src/buttons/checkbox.ts#L73
> 
> Not sure what it your exact use case and why you would like to set "active" through the API call but the current widget works as designed. If you've got a particular use-case that is not covered please let us know.

My use case is the following : 
I set manualy the value of checkbox withoput using reactiveform or ngmodel. and i would like to also set manually the active state of the button label.
This is because i use reactive form an i cannot create a form control for each option in a checkbox group, so i had to use ids as value of checkbox. 

So please, do you know how i can set the active state of the button label without using **ngModel** or **reactiveform** ? just by using a css class or a typescript property ?

**NB** : i tried to set the active style by delete the **active** class of the ngbButtonLabel but i couldn't because the **active** class is not removable.

**Comment by pkozlowski-opensource** [comment]
> So please, do you know how i can set the active state of the button label without using ngModel or reactiveform ? just by using a css class or a typescript property ?

> This is because i use reactive form an i cannot create a form control for each option in a checkbox group

It is unclear to me why this would be problematic. Could you share a stackblitz that illustrate the problem of using buttons with reactive forms? 

ng-bootstrap buttons are really meant to be used with Angular forms - actually this is their main benefit. If you don't need Angular form integration I do not see much point in using ng-bootstrap buttons - in this case I would suggest creating your own directives that better suit you use-case.

**Comment by PierreKoung** [comment]
> > So please, do you know how i can set the active state of the button label without using ngModel or reactiveform ? just by using a css class or a typescript property ?
> 
> > This is because i use reactive form an i cannot create a form control for each option in a checkbox group
> 
> It is unclear to me why this would be problematic. Could you share a stackblitz that illustrate the problem of using buttons with reactive forms?
> 
> ng-bootstrap buttons are really meant to be used with Angular forms - actually this is their main benefit. If you don't need Angular form integration I do not see much point in using ng-bootstrap buttons - in this case I would suggest creating your own directives that better suit you use-case.

that's the thing i use ng-bootstrap buttons in this specific use case just for the style and the javascript but i implement my own logic on checkbox. that's why i want to be able to manually manage the active state. i tried to write my own directive, but even with it, i cannot set the active state of the label.

**Comment by maxokorokov** [comment]
Buttons were removed in v13 → https://ng-bootstrap.github.io/releases/12.x/#/components/buttons/overview
