### ISSUE TITLE
Radio button group doesn't support aria-describedby

### ISSUE THREAD

**Issue by smlombardi** [ng-bootstrap/ng-bootstrap#4146]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

Adding `aria-describedby` to a button group, the help text is not spoken with VoiceOver.

`aria-labelledby` works fine

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-cma3qe?file=src/app/buttons-radioreactive.html

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 12.10

ng-bootstrap: 10.0.0

Bootstrap: 4.6.1

**Comment by maxokorokov** [comment]
Buttons were removed in v13 → https://ng-bootstrap.github.io/releases/12.x/#/components/buttons/overview
