### ISSUE TITLE
ngb-accordion role=tab itself not interactive

### ISSUE THREAD

**Issue by alisakychen** [ng-bootstrap/ng-bootstrap#4158]
Hello,
This is an accessibility issue that came up in an older version but still persists, based on l[ine 194 of ngb-accordion
](https://github.com/ng-bootstrap/ng-bootstrap/blob/9598506dfcbb0112afe21a1d6157c4645fd47522/src/accordion/accordion.ts#L194)

Accessibility dev tool Axe complains when run on [the accordion example page](https://ng-bootstrap.github.io/#/components/accordion/examples) that there's a nested interactive control.

<img width="1440" alt="Screen Shot 2021-09-14 at 9 35 28 AM" src="https://user-images.githubusercontent.com/251333/133267598-f9c12bf1-811f-4f68-b343-a9bd4d32b090.png">

I think this could be fixed by making the whole header respond to clicking to collapse/expand. (since the ng-template for a custom header always renders inside another element with role='tab', there isn't a way to customise the header as a solution) This may be different from bootstrap's aesthetic though.

https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-2/tabs.html

**Comment by fernakr** [comment]
FYI the latest Bootstrap 5 code samples opt to get rid of the `role="tablist"` and `role="tab"` attributes which seems to prevent the accessibility flag from occurring on their accordions: https://getbootstrap.com/docs/5.0/components/accordion/

**Comment by maxokorokov** [comment]
Will be fixed by a new accordion based on directives in `14.1.0` → #4437
