### ISSUE TITLE
Error Modal in Angular 11

### ISSUE THREAD

**Issue by aparzi** [ng-bootstrap/ng-bootstrap#4162]
when I try to open a modal i get the following error:
**this._applicationRef.attachView is not a function**

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 11.0.0

ng-bootstrap: 9.0.0

Bootstrap: 4.5.0

**Comment by aparzi** [comment]
Hi @troddick,
any update? Do you still have the same problem?

**Comment by troddick** [comment]
I ended up switching my models to Nebular NbDialogService since I am already using Nebular as my ui framework.

**Comment by aparzi** [comment]
@troddick okay if you solved I'm happy for you, can I close the issue?
