### ISSUE TITLE
Problem with styiling datepicker in alpha version

### ISSUE THREAD

**Issue by Michazzz** [ng-bootstrap/ng-bootstrap#4167]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
There is no possibility to ovveride styles for datepicker for ng-dp-header and ng-dp-month even if we will copy whole scss file from nh-bootstrap datepicker and we will override some of the properties. 

When I switched version of ng-bootstrap to 10.0.0 (with bootstrap 5) then everything was worked fine (I was suprised!). When I came back to ^11.0.0-beta.2 there is no possibility to change styles for header. 

Steps to reproduce: 
1. Visit attached stackblizt, check the problem on default configuration. 
2. Change version of the library back to 10.0.0 
3. See the result in html preview - problem shouldn't occurs now. 

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-cjsz1n?file=package.json

### Versions of Angular, ng-bootstrap and Bootstrap:
Angular: 12
ng-bootstrap: 11.0.0-beta.2 vs 10.0.0
Bootstrap: 5

![Screenshot_1](https://user-images.githubusercontent.com/1652051/136533826-75ce2c86-6041-4bbb-9b2c-557e30ef3b69.png)
![Screenshot_2](https://user-images.githubusercontent.com/1652051/136533829-9bb17d31-38d5-4884-b5c7-d58670b53cfa.png)

**Comment by maxokorokov** [comment]
Looks like that's what changed in between:

![Screenshot 2022-04-05 at 10 27 09](https://user-images.githubusercontent.com/8074436/161711815-2af3211c-48b3-4e28-9c22-942d3cae2f9a.jpg)
