### ISSUE TITLE
No it works config scrollable in components

### ISSUE THREAD

**Issue by keiner98** [ng-bootstrap/ng-bootstrap#4169]
Scrollable does not work when called as external component, I have tried on the same page but when making the modal the external component does not work.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 11

ng-bootstrap: 10

Bootstrap: 5

**Comment by pkozlowski-opensource** [comment]
I'm sorry but it is not clear what is the problem that you are describing. Could you please provide a minimal reproduce scenario in a stackblitz?

**Comment by maxokorokov** [comment]
Closing as no response, please reopen if necessary.
