### ISSUE TITLE
How to set the offset of dropdown ?

### ISSUE THREAD

**Issue by darkcris1** [ng-bootstrap/ng-bootstrap#4173]
https://getbootstrap.com/docs/4.1/components/dropdowns/#dropdown-options

**Comment by maxokorokov** [comment]
I don't think it is possible at the moment, marking as feature request.
Most likely it will be added with Popper support after moving to Bootstrap 5

**Comment by ryanknittel-fdx** [comment]
I tried adding margin on the `ngbDropdownMenu` but Popper complains.

Being able to use the built-in Popper offset would be great.

```Popper: CSS "margin" styles cannot be used to apply padding between the popper and its reference element or boundary. To replicate margin, use the `offset` modifier, as well as the `padding` option in the `preventOverflow` and `flip` modifiers.```

**Comment by ryanknittel-fdx** [comment]
Perhaps exposing a way to pass in a custom Popper config in the NgbDropdown directive would be the easiest implementation that would handle a variety of use cases.

**Comment by fbasso** [comment]
This feature is being implemented, follow the PR #4323 (you will be able to customize the popper options).

**Comment by maxokorokov** [comment]
Closed in #4323
