### ISSUE TITLE
Error installing 12.0.0-beta.3 (use Yarn > 1.3 to install dependencies)

### ISSUE THREAD

**Issue by vkirienko** [ng-bootstrap/ng-bootstrap#4187]
### Bug description:
Hi, 

First of all thank you for added Bootstrap 5 and Angular 13 support.

But now I'm getting error below trying to install 12.0.0-beta.3. Nothing changed in my setup that worked for 11.0.0-beta.2 and earlier ng-bootstrap versions.

`
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node misc/preinstall.js                                                   
npm ERR! C:\Workspace\Projects\Compass\src\Fortress.Compass.Web\ClientApp\node_modules\@ng-bootstrap\ng-bootstrap\misc\preinstall.js:2                                                                                                                          
npm ERR!   throw new Error(`                                                                                                    
npm ERR!   ^                                                                                                                   
npm ERR!                                                                                                                        
npm ERR! Error:                                                                                                                 
npm ERR!                                                                                                                        
npm ERR!   ###################################################                                                                  
npm ERR!   #                                                 #                                                                  
npm ERR!   #  Please use Yarn > 1.3 to install dependencies  #                                                                  
npm ERR!   #                                                 #                                                                  
npm ERR!   #  1. Install yarn (https://yarnpkg.com/)         #                                                                  
npm ERR!   #  2. Run 'yarn' instead of 'npm install'         #                                                                  
npm ERR!   #                                                 #                                                                  
npm ERR!   ###################################################                                                                  
npm ERR!                                                                                                                        
npm ERR!     at Object.<anonymous> (C:\Workspace\Projects\Compass\src\Fortress.Compass.Web\ClientApp\node_modules\@ng-bootstrap\ng-bootstrap\misc\preinstall.js:2:9)                                                                                            
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)                                                      
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)                                        
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)                                                           
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)                                                 
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)                              
npm ERR!     at node:internal/main/run_main_module:17:47                                                                        `

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:
13.0.1

ng-bootstrap:
12.0.0-beta.3

Bootstrap:
5.1.3

**Comment by maxokorokov** [comment]
Thank you for reporting this, the release was corrupted, I've just republished `12.0.0-beta.4` and updated docs
