### ISSUE TITLE
Cannot import NgbCarousel and build is failing

### ISSUE THREAD

**Issue by niksbansode** [ng-bootstrap/ng-bootstrap#4189]
### Link to minimally-working StackBlitz that reproduces the issue:
**Env to reproduce:** https://stackblitz.com/edit/angular-sj3fii?file=src/app/carousel-basic.module.ts
I forked above env from https://ng-bootstrap.github.io/stackblitzes/carousel/basic/stackblitz.html and just replaced NgbModule with NgbCarousel and the compilation of the project is started to fail with the following error:

`This likely means that the library (@ng-bootstrap/ng-bootstrap) which declares NgbCarousel has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also, consider checking with the library's authors to see if the library is expected to be compatible with Ivy.`

Locally on my laptop, I tried the following combinations but still it's not working:
- npm clear cache -force
- removing and reinstalling @ng-bootstrap/ng-bootstrap
- removing and reinstalling node_modules completely

I don't want to introduce overhead by importing the whole NgbModule.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 12.0.0

ng-bootstrap: 10.0.0

Bootstrap: 4.5.0

**Comment by pkozlowski-opensource** [comment]
`NgbCarousel` is a type representing a component but Angular module `imports` accepts modules only,. You should be doing the following: 

```
@NgModule({
  imports: [BrowserModule, NgbCarouselModule],
``` 

See: https://stackblitz.com/edit/angular-sj3fii-e9phn7?file=src/app/carousel-basic.module.ts

Closing as a support request.
