### ISSUE TITLE
Api-doc generating wrong fileName

### ISSUE THREAD

**Issue by Foxandxss** [ng-bootstrap/ng-bootstrap#419]
Some of the API generated with our tool gives the full path instead of relative path:

```
{"NgbPanel":{"fileName":"src/accordion/accordion.ts"
```

That is good but:

```
"NgbPopover":{"fileName":"/Users/jesus/Programming/Angular2/bootstrap/core/src/popover/popover.ts"
```

This one is not.

If you go to the demo, you can see how tabset points to a path that doesn't exist.

I have debugged it a bit and seems that comes from:

```
this.program = ts.createProgram(fileNames, {});
// and then
var sourceFile = this.program.getSourceFile(fileName);
```

And that `ts` is the `typescript` library.

**Comment by pkozlowski-opensource** [comment]
Yeh, saw this once on my Ubuntu box. For now it looks for me as a TS thingy but we could easily normalize file names on our side. Will push a fix later today.
