### ISSUE TITLE
Dropdown menu position wrong

### ISSUE THREAD

**Issue by jchapelle** [ng-bootstrap/ng-bootstrap#4190]
### Bug description:
Menu position is wrong when dropdown is set with [open]=true and dropdown parent container is dynamically created with ngIf

### Code
```
<div
      *ngIf="SOME CONDITION"
      style="top: 0;"
      class="position-absolute d-flex w-100 h-100">
      <div
        class="w-100 position-relative"
        container="body"
        ngbDropdown
        [open]="true"
      >
        <div ngbDropdownToggle
             class="position-absolute d-flex w-100 h-100 cursor-pointer no-dropdown-toggle"></div>

        <div ngbDropdownMenu class="mt-1 min-width-inherit">
          <div
            class="p-2 pl-4 pr-4 cursor-pointer"
          >
            Some content
          </div>
        </div>

      </div>
    </div>
```

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 13

ng-bootstrap: latest

**Comment by maxokorokov** [comment]
Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly (notably provide an ng-bootstrap version)
- provide a **minimal** reproduction scenario in a StackBlitz

**Comment by pkozlowski-opensource** [comment]
Going to close this issue for now as we haven't heard back with a reproduce scenario.
