### ISSUE TITLE
Typeahead show 2 lines of words in each option

### ISSUE THREAD

**Issue by dekathomas** [ng-bootstrap/ng-bootstrap#4191]
Hello, this is not a bug, but I want to customize my typeahead. Right now, as far as I know, typeahead only allow 1 line sentence of each options.

My application need 2 lines of words. Can I achieve that? And how?
Thank you in advance.

### Versions of Angular, ng-bootstrap and Bootstrap:
Angular: 8
ng-bootstrap: 5.3.1

**Comment by jnizet** [comment]
You're free to format the options the way you want to using a custom template (as shown in [this example of the documentation](https://ng-bootstrap.github.io/#/components/typeahead/examples#template).

Here's a stackblitz made from that example and showing two lines for each option: https://stackblitz.com/edit/angular-g29whg-sqq9mc?file=src%2Fapp%2Ftypeahead-template.html

**Comment by pkozlowski-opensource** [comment]
Yep, @jnizet is totally right - a custom template is a way to go!
Closing as a support request.
