### ISSUE TITLE
Datepicker popup cannot be opened

### ISSUE THREAD

**Issue by mehmet-erim** [ng-bootstrap/ng-bootstrap#4192]
### Bug description:

Although the inline datepicker is working, the datepicker popup does not appear. See the error on the console:

![image](https://user-images.githubusercontent.com/34455572/143827797-04cd5b1d-a001-4758-8303-0a53c26991bd.png)

```
core.js:6498 ERROR TypeError: componentFactory.create is not a function
    at ViewContainerRef.createComponent (core.js:23191)
    at NgbInputDatepicker.open (ng-bootstrap.mjs:3557)
    at NgbInputDatepicker.toggle (ng-bootstrap.mjs:3639)
    at HomeComponent_Template_button_click_2_listener (home.component.html:1)
    at executeListenerWithErrorHandling (core.js:15327)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:15365)
    at HTMLButtonElement.<anonymous> (platform-browser.js:561)
    at ZoneDelegate.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.js:28679)
    at ZoneDelegate.invokeTask (zone.js:405)
```

The problem is related to 3557th line of `ng-bootstrap.mjs`

![image](https://user-images.githubusercontent.com/34455572/143827876-d4cce711-0fc9-403a-a476-c4370b68b632.png)

### Link to minimally-working StackBlitz that reproduces the issue:

I've created an app but it does not work on StackBlitz:
https://stackblitz.com/edit/angular-uufmfr?file=src%2Fapp%2Fdatepicker-popup.html

You can follow the steps below to reproduce:

- Install the `@ng-bootstrap/ng-bootstrap@12.0.0-beta.4`
- Import the `NgbDatepickerModule` to your feature module
- Place the code below to an HTML page:

```html
<input type="text" ngbDatepicker #d="ngbDatepicker" /> <button (click)="d.toggle()">Toggle</button>
```

- Click the "Toggle" button and see the console.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 12.2.13

ng-bootstrap: 12.0.0-beta.4

Bootstrap: 5.1.1

> It was working properly in `v11.0.0-beta.2`.

**Comment by pkozlowski-opensource** [comment]
ng-bootstrap: [12.0.0-beta.4](https://github.com/ng-bootstrap/ng-bootstrap/releases) is targeting Angular v13 and you seem to be trying it with Angular v12. There were some API changes between Angular v12 and v13 and thus you need to use proper combination of versions.  

Closing as a support request

**Comment by RobertVogt** [comment]
Why is this closed?  There is still an issue.  I am also experiencing the same thing with 
Angular version 12.2.14 and ng-bootstrap 10.0.0
