### ISSUE TITLE
multiple Accordion's build with ngFor ['Element': '#3.1' is not a valid selector.]

### ISSUE THREAD

**Issue by sysmat** [ng-bootstrap/ng-bootstrap#4195]
### Bug description:
- in template(html) I want multiple accordions buld with for lop, how to define them in typescript 
- in typescript I want for specific accordion to toggel specific panel

is this even possible?

- HTML:

```html
<div class="panel-group"
         *ngFor="let fqa of faqs, let i = index">

        <h5 [id]="fqa.id">{{fqa.section}}</h5>

        <ngb-accordion #acc="ngbAccordion"
                       [id]="fqa.id">
            <ngb-panel *ngFor="let q of fqa.qa"
            [id]="q.id"
                       title="V: {{q.question}}">

                <ng-template ngbPanelContent>
                    <span class="badge badge-primary">O:</span>&nbsp;
                    <span style="text-align: justify"
                          [innerHtml]="q.answer"></span>
                </ng-template>
            </ngb-panel>
        </ngb-accordion>
</div>
```
- typescript:
```typescript
@ViewChildren('acc')
  accordions: QueryList<NgbAccordion>;
```

- error:
```
Failed to execute 'querySelector' on 'Element': '#1.1' is not a valid selector.
    at NgbAccordion._getPanelElement (http://localhost:4200/vendor.js:1874:44)
```

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 13

ng-bootstrap:  10.0.0

Bootstrap:  4.6.0

**Comment by ExFlo** [comment]
Hi
First you shouldn't use the id at two points 
here <h5 [id]="fqa.id"> and <ngb-accordion #acc="ngbAccordion"
                       [id]="fqa.id">
                       
  Moreover id should not start with a number (1.1 not valid) --> this is the issue you have with the Panel --> start with a char will work.
Best regards
Florent

**Comment by sysmat** [comment]
- h5 id I need for scroll to an element
- I fix that start with char:
- but now I have strange error:
```typescript
const accordian = this.accordions.get(i);
console.log('accordian', accordion);  
// when trying to us it I get error 
accordian.activeIds = [`panel_${this.questionIdFragment}`];
```
- error: when calling `accordian.activeIds`  is undefined, but if remove call `accordian.activeIds`  I get NgbAccordion in log
- whatever I call in accordion it became undefined

**Comment by ExFlo** [comment]
Hi 
Maybe because const accordian is the var name and you use accordion var which is undefined in your examples.
I was able to get the accordion in my ex.
BR

**Comment by sysmat** [comment]
yes but why if I remove this `accordian.activeIds` accordion is present, but when I use `this.accordions.get(i).activeIds = [`panel_${this.questionIdFragment}`];` is undefined, very strange.

**Comment by ExFlo** [comment]
First: I open a PR to fix the issue with the number.
Second: I will try to reproduce :-)

**Comment by ExFlo** [comment]
As doc stated it you should use the activeIds at initialisation so maybe use other system to do your expand collapse and it may work

**Comment by sysmat** [comment]
```typescript
this.accordions.get(i).toggle(`panel_${this.questionIdFragment}`);
```
- the same error with toggle
- [**toogle example**](https://ng-bootstrap.github.io/#/components/accordion/examples#toggle) 
`(click)="acc.toggle('toggle-1')"`

I really don't know what is wrong (could be something with animation animationFrameScheduler with transitions of panel)

**Comment by sysmat** [comment]
```html
<div role="tab" class="card-header" id="panel_3_3-header"><button type="button" class="btn btn-link" ng-reflect-ngb-panel-toggle="[object Object]" aria-expanded="true" aria-controls="panel_3_3"> V: Kako pridobim AAI-račun?<!--bindings={
  "ng-reflect-ng-template-outlet": null
}--></button><!--bindings={
  "ng-reflect-ng-template-outlet-context": "[object Object]"
}--></div>

<div role="tabpanel" id="panel_3_3" aria-labelledby="panel_3_3-header" class="collapse show" style=""><div class="card-body"><span _ngcontent-yhg-c107="" class="badge badge-primary">O:</span>&nbsp; <span _ngcontent-yhg-c107="" style="text-align: justify;">Za pridobitev AAI-računa se obrnite na odgovorno osebo ali službo v domači organizaciji. V manjših organizacijah (posamezne šole, vrtci ...) za AAI-račune navadno skrbi informatik ali računalničar. V večjih organizacijah (šolski centri, univerze ...) pa to funkcijo po navadi opravljajo tajništva in študentske oz. dijaške pisarne.</span><!--bindings={
  "ng-reflect-ng-template-outlet": "[object Object]"
}--></div></div>
```

- ts:
```typescript
console.log('panel.id=', `panel_${this.questionIdFragment}`); // in log I see: panel.id=panel_3_3
this.accordions.get(i).toggle(`panel_${this.questionIdFragment}`);
this.accordions.get(i).expand(`panel_${this.questionIdFragment}`);
this.accordions.get(i).activeIds = `panel_${this.questionIdFragment}`;

// no console error but panel is not opend
// when I manually click it opens
```

**Comment by sysmat** [comment]
- sorry it was my mistake, I query the wrong accordion, and then there was no panel with the desired id, it works
- the only suggestion is when using toggle I get infinite times x msg in logs and reopening panel
