### ISSUE TITLE
How to add an ID to a modal?

### ISSUE THREAD

**Issue by FANMixco** [ng-bootstrap/ng-bootstrap#4197]
### Bug description:

I cannot find any documentation on how to add an ID to a modal. I am adding a custom CSS rule to a specific modal, but right now, it's altering all.

I cannot find anything in the documentation:
https://ng-bootstrap.github.io/#/components/modal/api

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 13

ng-bootstrap: 12.0.0-beta.X `npm install @ng-bootstrap/ng-bootstrap@bootstrap5`

Bootstrap: 5

**Comment by ExFlo** [comment]
Hi why do you need an ID to a modal ?

**Comment by jnizet** [comment]
Hi @FANMixco . It looks like what you're trying to do is customize the CSS. So do it with a custom class rather than an ID. As shown in the documentation: https://ng-bootstrap.github.io/#/components/modal/examples#options

**Comment by DDtMM** [comment]
One way you can accomplish this is by passing a component instance into `.open()`, and have a property on the component that is used as the id in the template:

**Component**
```
const modalRef = this.modalSvc.open(ModalComponent);
modalRef.componentInstance.idProp = 'someId';
```

**Template**
```
<div [attr.id]="'idProp'">
    <div class="modal-header" > <!-- .... -->
```
I don't really think this is an issue with ngBootstrap.

**Comment by maxokorokov** [comment]
Thanks for the support, closing, please reopen if necessary
