### ISSUE TITLE
Accordian/Card Bootstrap Color Options

### ISSUE THREAD

**Issue by danielmhair** [ng-bootstrap/ng-bootstrap#420]
I think it would be great if there was an option on the accordion to have a certain type. For example:

```html
<ngb-accordion [closeOthers]="true" type="success">
</ngb-accordion>
```
-- OR --
```html
<ngb-accordion [closeOthers]="true">
        <ngb-panel type="warning" title="Collapsible Group Item #1" [open]="true"></ngb-panel>
        <ngb-panel type="success" title="Collapsible Group Item #2"></ngb-panel>
        <ngb-panel type="info" title="Collapsible Group Item #3"></ngb-panel>
        <ngb-panel type="primary" title="Collapsible Group Item #4"></ngb-panel>
        <ngb-panel type="default" title="Collapsible Group Item #5"></ngb-panel>
</ngb-accordion>
```

This way we can easily utilize the different colors that bootstrap offers (with cards and panels)

Here is a plunker, started from another discussion (Issue #404) and adapted to this request (except it only shows the ngb-accordion example):
http://plnkr.co/edit/2IDH6VDXQsjDhk8l0lHj?p=preview

**Comment by pkozlowski-opensource** [comment]
Why not. We could even have both options (that is - a "global" one on the accordion level and panel having an ability to override this).

Should be an easy feature to implement once #403 lands

**Comment by danielmhair** [comment]
I like that idea. Thanks! I look forward to this feature.

**Comment by pkozlowski-opensource** [comment]
This one is no longer blocked. PRs welcomed.

**Comment by sendilkumarn** [comment]
If it is open, I will take it.

**Comment by pkozlowski-opensource** [comment]
> If it is open, I will take it.

It is all yours :-)

**Comment by sendilkumarn** [comment]
type in ngb-accordion will always override the type in ngb-panel

**Comment by pkozlowski-opensource** [comment]
> type in ngb-accordion will always override the type in ngb-panel

Other way around.
