### ISSUE TITLE
Tooltips and Popovers ... not working

### ISSUE THREAD

**Issue by gbardwell** [ng-bootstrap/ng-bootstrap#4205]
core.js:6498 ERROR TypeError: componentFactory.create is not a function
    at ViewContainerRef.createComponent (core.js:23191)
    at PopupService.open (ng-bootstrap.mjs:5562)
    at NgbPopover.open (ng-bootstrap.mjs:7566)
    at SafeSubscriber._next (ng-bootstrap.mjs:7429)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
    at SafeSubscriber.next (Subscriber.js:122)
    at Subscriber._next (Subscriber.js:72)
    at Subscriber.next (Subscriber.js:49)
    at MapSubscriber._next (map.js:35)
    at MapSubscriber.next (Subscriber.js:49)
defaultErrorLogger @ core.js:6498
handleError @ core.js:6546
next @ core.js:29303
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:25955
(anonymous) @ core.js:28718
invoke @ zone.js:372
run @ zone.js:134
runOutsideAngular @ core.js:28591
onHandleError @ core.js:28718
handleError @ zone.js:376
runTask @ zone.js:181
invokeTask @ zone.js:487
ZoneTask.invoke @ zone.js:476
data.args.<computed> @ zone.js:2541
setTimeout (async)
scheduleTask @ zone.js:2543
scheduleTask @ zone.js:393
onScheduleTask @ zone.js:283
scheduleTask @ zone.js:386
scheduleTask @ zone.js:221
scheduleMacroTask @ zone.js:244
scheduleMacroTaskWithCurrentZone @ zone.js:679
(anonymous) @ zone.js:2585
proto.<computed> @ zone.js:975
hostReportError @ hostReportError.js:2
__tryOrUnsub @ Subscriber.js:191
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
_next @ filter.js:33
next @ Subscriber.js:49
notifyNext @ mergeMap.js:70
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
_next @ filter.js:33
next @ Subscriber.js:49
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
_next @ Subscriber.js:72
next @ Subscriber.js:49
_next @ filter.js:33
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
openFn @ ng-bootstrap.mjs:7381
(anonymous) @ platform-browser.js:561
invokeTask @ zone.js:406
onInvokeTask @ core.js:28679
invokeTask @ zone.js:405
runTask @ zone.js:178
invokeTask @ zone.js:487
invokeTask @ zone.js:1600
globalZoneAwareCallback @ zone.js:1626
Show 30 more frames
core.js:6498 ERROR TypeError: componentFactory.create is not a function
    at ViewContainerRef.createComponent (core.js:23191)
    at PopupService.open (ng-bootstrap.mjs:5562)
    at NgbTooltip.open (ng-bootstrap.mjs:8820)
    at SafeSubscriber._next (ng-bootstrap.mjs:7429)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
    at SafeSubscriber.next (Subscriber.js:122)
    at Subscriber._next (Subscriber.js:72)
    at Subscriber.next (Subscriber.js:49)
    at MapSubscriber._next (map.js:35)
    at MapSubscriber.next (Subscriber.js:49)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 12.2.15

ng-bootstrap: 12.0.0-beta.4

Bootstrap: 5.1.3"

Note: I got compile errors until I installed: "@popperjs/core": "^2.11.0", which compiler said was missing.

**Comment by fbasso** [comment]
Hi @gbardwell, 

is it really Angular: 2.2.15? If yes, please upgrade, this version is too old!

We don't have such issue if we run the demo site locally.

**Comment by gbardwell** [comment]
;-) yes ... Angular 12.2.15

Same issue for me with ng-bootstrap: 11.0

Pre-11 it work for me.

**Comment by gbardwell** [comment]
So... I reverted back to  "@ng-bootstrap/ng-bootstrap": "11.0.0-beta.2".
Everything started to work again.

**Comment by aayushkh** [comment]
Hi @gbardwell !

I had the same issue. You will need to use bootstrap version 5.1.2, not 5.1.3. `ng-boostrap` v12.0.0-beta.4 uses 5.1.2.

Hope this helps.

**Comment by aayushkh** [comment]
@fbasso I think this can be closed

**Comment by ziaKhan1995** [comment]
> As a reminder, here is the compatibility table between versions of ng-bootstrap, Angular and Bootstrap CSS:
> 
> > ng-bootstrap
> > Angular
> > Bootstrap CSS
> > Popper
> > 
> > 
> > 
> > 
> > 10.x.x
> > 12.0.0
> > 4.5.0
> > 
> > 
> > 
> > 11.x.x
> > 13.0.0
> > 4.6.0
> > 
> > 
> > 
> > 12.x.x
> > 13.0.0
> > 5.0.0
> > 2.10.2
> 
> (cf https://ng-bootstrap.github.io/#/getting-started#dependencies)
> 
> ng-bootstrap 12.x.x does not support Angular 12
> 
> I am going to close this issue. @gbardwell Feel free to reopen the issue (with enough information for us to reproduce it) if you have the same problem with compatible versions of ng-bootstrap, Angular and Bootstrap CSS.

A solution that worked. Well Done
