### ISSUE TITLE
Demo: remove require(...) calls from our demo components

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#421]
It is important for 2 reasons:
* `require(...)` shows up in our demos and this is not great since `require(...)` ties us to one particular environment / build
* it blocks us from having proper offline compilation

We need to find a different way of pulling in components' templates and code snippets.

**Comment by pkozlowski-opensource** [comment]
With #422 require calls are gone from demo components, thnx @Foxandxss. I guess that now the only part that blocks offline compilation are require(s) for:
* API docs (it would be easy to turn those into a JS file to be imported "normally")
* code examples to be highlighted with prism

**Comment by pkozlowski-opensource** [comment]
API docs were taken care of in 371bde5fdaba14525be7a260419871616e95c0ce. The only remaining part are `require` calls for prism code highlighting.

**Comment by wesleycho** [comment]
What would this entail, moving the loader logic into `webpack.demo.js`?

**Comment by pkozlowski-opensource** [comment]
Based on investigations done in #542 we've got few more dependencies on WebPack _on top_ of `require` calls:

* import of a SCSS file [here](https://github.com/ng-bootstrap/ng-bootstrap/blob/3952d0cc54a9574d2efaeb381cec6856ad486691/demo/src/app/app.component.ts#L4)
* usage of `process.env` [here]() and [here](https://github.com/ng-bootstrap/ng-bootstrap/blob/3952d0cc54a9574d2efaeb381cec6856ad486691/demo/src/main.ts#L7).

**Comment by pkozlowski-opensource** [comment]
Based on https://github.com/ng-bootstrap/ng-bootstrap/issues/542#issuecomment-253971878 we are likely to stick with WebPack 2.0 in the future so removal of WebPack-specific constructs is not an issue.

If it turns out that we need to remove `require()` calls it will be handled as part of #542
