### ISSUE TITLE
ngbDatepicker [displayMonths] with previous months

### ISSUE THREAD

**Issue by mario45211** [ng-bootstrap/ng-bootstrap#4210]
Hello, 

Is there any option to make `[displayMonths]` in ngbDatepicker display previous months instead of the next ones ? I am using datepicker to select historical data date range and displaying previous and current months is better suited to my users.

Thanks in advance for any answer.

Best regards!

**Comment by mario45211** [comment]
Workaround found by me: `datepicker.navigateTo(yourMinDate)`

**Comment by maxokorokov** [comment]
Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz
