### ISSUE TITLE
No tree shaking applied in server bundle when using Angular Universal

### ISSUE THREAD

**Issue by bokklu** [ng-bootstrap/ng-bootstrap#4213]
### Bug description:

When using ng-bootstrap with Angular Universal, I noticed that there seems to be no dead code elimination in the server build.
I created a brand new angular universal app from scratch and added the NgbAccordionModule only and after I run source-map-explorer and analyze the produced server bundle, it seems to me like it is including the whole module in the chunk (around 290 KB, I think this is way too much for just importing the Accordion Module). I have tried using other ngb modules to check if there is the same behaviour, but the size remained the same. The optimization option in angular.json is set to true so I don't think it is something which has to do with an incorrect config.

![image](https://user-images.githubusercontent.com/26428189/148611550-2cf279bd-d628-4bd0-a6ca-8ffefb2fa54e.png)

On the other hand, when I analyzed the generated browser bundles, it seems like there was proper tree shaking applied (now around 11 KB):

![image](https://user-images.githubusercontent.com/26428189/148611659-2ebf67c3-711e-4b7b-9418-9e5110c5bcd3.png)

### Link to minimally-working StackBlitz that reproduces the issue:

https://github.com/bokklu/universal-tree-shake-repro

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 13.1.2

ng-bootstrap: 11.0.0

Bootstrap: 5.1.3

**Comment by devoto13** [comment]
IIRC Angular CLI does not remove dead code in the server builds at all, so it is not specific to the `ng-bootstrap`.

**Comment by bokklu** [comment]
You are right, I tried it with another package and I got the same behaviour, thanks for pointing me in the right direction. Do you know why dead code removal is not done on the server build? Is this something that I have to raise within the angular cli repo?

**Comment by devoto13** [comment]
No, I don't know why it is like that. I've read about it somewhere, but can't find it now. I would suggest searching for existing issues in the Angular CLI repo or opening a new one if it does not exist yet.

**Comment by bokklu** [comment]
Thanks again, following this up into the angular cli repo
