### ISSUE TITLE
Bug: NgbDropdown does not respond to autoClose changes while open

### ISSUE THREAD

**Issue by BistroStu** [ng-bootstrap/ng-bootstrap#4219]
### Bug description:
Changing the NgbDropdown autoClose input while it is open has no effect, only its initial state is taken into account.

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-prenvw?file=src/app/dropdown-basic.ts

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 13.0.3
ng-bootstrap: 11.0.0
Bootstrap: 4.6.1

### Possible solution

Maybe this is one of the motivations for #3014 (Re-implement AutoClose as a service) but there is also a simpler solution:
- inside _setCloseHandlers add
```ts 
this._close$.next() // to unsubscribe the previous closeHandler, may be a good idea to rename this _clearCloseHandler$
```
- inside ngOnChanges add the following:
```ts
if (changes.autoClose && this._open) {
  this._setCloseHandlers();
}
```
I would be happy to submit a pull request along those lines.

**Comment by maxokorokov** [comment]
@BistroStu please do open a PR if you're motivated.

It's just a missing feature for all components using autoclose I think.
You need to properly add e2e test here though → https://github.com/ng-bootstrap/ng-bootstrap/blob/master/e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.e2e-spec.ts

**Comment by janwidmer-work** [comment]
@BistroStu This seems to be broken again, any idea why? See my new bugticket, where I have the same problem as you had..
