### ISSUE TITLE
NGB Date Picker auto closed on every click

### ISSUE THREAD

**Issue by SkCodeRains** [ng-bootstrap/ng-bootstrap#4234]
### Bug description:
after importing localize Month and year selection is coming but on every click it get closed , don't know why but code is same from website Not changed , but it getting closed on every click 
 

Angular: 12

ng-bootstrap: 5

Bootstrap: 5

**Comment by maxokorokov** [comment]
Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz

**Comment by maxokorokov** [comment]
Closing as no response, please reopen if necessary.
