### ISSUE TITLE
Do you intend to support Angular 14 with Bootstrap 4

### ISSUE THREAD

**Issue by karptonite** [ng-bootstrap/ng-bootstrap#4248]
First, congratulations on the release of ng-bootstrap 12, with support for Bootstrap 5!

For planning purposes, it would be useful to know if there is any intention to make the ng-bootstrap 11 branch, with support for Bootstrap 4, compatible with Angular 14 when it releases in May. Are there plans that far out? It would help us understand how urgently we need to prioritize upgrading to the Bootstrap 5 branch.

Apologies if this is explained somewhere--I couldn't find anything definitive.

**Comment by terencehonles** [comment]
Historically you could force install ng-bootstrap against a newer version of Angular and there didn't seem to be any/many issues. Having that said this will depend on what breaking changes Angular 14 may include and if there are any breaking package format changes that have been made since the release of ng-bootstrap 11.

Not speaking with any authority I would assume there would _not_ be another release of ng-bootstrap that supports Bootstrap 4. This project has not seemed to support multiple bootstrap versions simultaneously and you can see that from the [compatibility matrix](https://github.com/ng-bootstrap/ng-bootstrap#dependencies). Even though that only shows minor versions I would assume the support would be the same for major versions.

I'll let someone with more authority speak to whether they'd consider releasing another version with Angular 14 support if a pull request was proposed that added such support.

**Comment by karptonite** [comment]
The compatibility matrix doesn't help as much as you might think. This is the first time there has been a major bootstrap update since the inception of this project. So there is no precedent on how to handle an angular upgrade vs bootstrap support in this case.

**Comment by terencehonles** [comment]
I'm speaking from my experience working with the library and with the capacity that seems to be available. Of course there is no precedent based on major version bumps, but unless you or someone is willing to help maintain the 4.x branch I doubt there will be capacity to support more than one bootstrap version. That is what I meant by:

> I'll let someone with more authority speak to whether they'd consider releasing another version with Angular 14 support if a pull request was proposed that added such support.

We're personally taking this opportunity to migrate to bootstrap 5 and we are evaluating how many issues are raised here or in our testing before finalizing the migration.

**Comment by karptonite** [comment]
I'm not sure how much work would be involved in doing bugfixes on the 11.0.x branch, but if they are doable, we would really appreciate it. We are in a position now where, if the 11.0.x branch isn't patched for Angular 14, we will definitely have some hard choices to make. A lot of our styles are just a bit too dependent on Bootstrap right now, and migrating to bootstrap 5 would be especially challenging.

**Comment by richard-ob** [comment]
I haven't seen this logged anywhere, but the z-index change on the modal backdrop means that modals are broken when using ng-bootstrap 12 against Bootstrap 4. The modal appears behind the backdrop, so can't be clicked. I think it relates to #4243 

So I guess this would be an example of the kinds of issues you might see. For now we are just using version 11 of ng-bootstrap.

**Comment by daniel-zero** [comment]
@maxokorokov to support ng14 with bootstrap v4 (ng-bootstrap@11) you only have to change the supported peerDeps of the package.

```json
  "peerDependencies": {
     "@angular/common": "^13.0.0 || ^14.0.0",
     "@angular/core": "^13.0.0 || ^14.0.0",
     "@angular/forms": "^13.0.0 || ^14.0.0",
     "@angular/localize": "^13.0.0 || ^14.0.0",
     "rxjs": "^6.5.3 || ^7.4.0"
   },
```

This should be anything. No breaking change for users remaining on Angular 13 but a big improvement for all who are still remaining on Bootstrap v4

**Comment by richard-ob** [comment]
> @maxokorokov to support ng14 with bootstrap v4 (ng-bootstrap@11) you only have to change the supported peerDeps of the package.
> 
> ```json
>   "peerDependencies": {
>      "@angular/common": "^13.0.0 || ^14.0.0",
>      "@angular/core": "^13.0.0 || ^14.0.0",
>      "@angular/forms": "^13.0.0 || ^14.0.0",
>      "@angular/localize": "^13.0.0 || ^14.0.0",
>      "rxjs": "^6.5.3 || ^7.4.0"
>    },
> ```
> 
> This should be anything. No breaking change for users remaining on Angular 13 but a big improvement for all who are still remaining on Bootstrap v4

As per my previous post, it would appear it does break modals, as there was a z-index change in one of the modal elements between Bootstrap v4 and v5. This manifests in the modal appearing behind the backdrop, essentially breaking modals, without a manual fix by a developer (overriding the z-index, or such).

So I don't think its as simple as you say, as the project could not say they support it without fixing this issue to a core component.

**Comment by penfold** [comment]
> @maxokorokov to support ng14 with bootstrap v4 (ng-bootstrap@11) you only have to change the supported peerDeps of the package.
> 
> ```json
>   "peerDependencies": {
>      "@angular/common": "^13.0.0 || ^14.0.0",
>      "@angular/core": "^13.0.0 || ^14.0.0",
>      "@angular/forms": "^13.0.0 || ^14.0.0",
>      "@angular/localize": "^13.0.0 || ^14.0.0",
>      "rxjs": "^6.5.3 || ^7.4.0"
>    },
> ```
> 
> This should be anything. No breaking change for users remaining on Angular 13 but a big improvement for all who are still remaining on Bootstrap v4

This looks like a super quick win for us on BS 4. Could we have this released as say v11.1.0 of the v11 branch?

**Comment by akolata** [comment]
For a big applications, migration from Bootstrap 4 to Bootstrap 5 might be time-consuming and challenging - same as migration to a newer Angular version. With ng-bootstrap it looks like you have to do both, if you want to use Angular 14.
For me it's a terrible news... I understand that the maintenance of both Bootstrap 4 and Bootstrap 5 might be challenging, but I'm not sure if a lot of companies have already switched to the newest version

**Comment by Tohnmeister** [comment]
> > @maxokorokov to support ng14 with bootstrap v4 (ng-bootstrap@11) you only have to change the supported peerDeps of the package.
> > ```json
> >   "peerDependencies": {
> >      "@angular/common": "^13.0.0 || ^14.0.0",
> >      "@angular/core": "^13.0.0 || ^14.0.0",
> >      "@angular/forms": "^13.0.0 || ^14.0.0",
> >      "@angular/localize": "^13.0.0 || ^14.0.0",
> >      "rxjs": "^6.5.3 || ^7.4.0"
> >    },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This should be anything. No breaking change for users remaining on Angular 13 but a big improvement for all who are still remaining on Bootstrap v4
> 
> As per my previous post, it would appear it does break modals, as there was a z-index change in one of the modal elements between Bootstrap v4 and v5. This manifests in the modal appearing behind the backdrop, essentially breaking modals, without a manual fix by a developer (overriding the z-index, or such).
> 
> So I don't think its as simple as you say, as the project could not say they support it without fixing this issue to a core component.

I think you are referring to different things. @daniel-zero is referring to officially supporting Angular 14 (and now 15) with ng-bootstrap 11. You are referring to using ng-bootstrap 12 with bootstrap 4.

If ng-bootstrap 11 works well with Angular 14 and 15, then it's just a matter of updating peer dependencies in ng-bootstrap 11 and releasing a minor update, so users don't get peer dependency errors when updating to a newer version of Angular.

**Comment by bytech-ca** [comment]
Just run into this one today, trying to use Bootstrap 4 with Angular 14. Has anyone found a solution to making these two compatible?

**Comment by bytech-ca** [comment]
> I've just upgraded with `--force` which ignores the peer dependency incompatibilities. Seems to work just fine.

I've had a similar experience... been running Angular 14 with Bootstrap 4 two weeks now. Modals mentioned as not working all work in our setup, and I've not noticed any other issues so far.
