### ISSUE TITLE
After update Popper.js problem

### ISSUE THREAD

**Issue by blueiceprj** [ng-bootstrap/ng-bootstrap#4249]
### Bug description:
After upgrade to last version its getting this error when project build.

./node_modules/@ng-bootstrap/ng-bootstrap/fesm2015/ng-bootstrap.mjs:9:0-88 - Error: Module not found: Error: Can't resolve '@popperjs/core' in '.............../node_modules/@ng-bootstrap/ng-bootstrap/fesm2015'

Angular:
13.2.2

ng-bootstrap:
12.0.0

Bootstrap:
5.1.3

**Comment by blueiceprj** [comment]
After npm install "@popperjs/core": "^2.11.2" working properly now.

**Comment by divdavem** [comment]
"@popperjs/core" is a new dependency of ng-bootstrap.
It is installed automatically when doing `ng add @ng-bootstap/ng-bootstrap` but it is not added automatically when updating with `ng update @ng-bootstap/ng-bootstrap`.
@maxokorokov Do you think we should add an update script?

**Comment by Henrryagc** [comment]
I solve this problem with `npm install "@popperjs/core",` then I can run my project, upgrading angular from 8 to 13 version...

**Comment by Codehustler9112** [comment]
I faced this error same after installing npm install "@popperjs/core"
