### ISSUE TITLE
ngbCarousel - showNavigationIndicators not working

### ISSUE THREAD

**Issue by kettunen** [ng-bootstrap/ng-bootstrap#4253]
### Bug description:

After updating to ng-bootstrap 12 navigation indicators not showing any more in ngbCarousel.

### Link to minimally-working StackBlitz that reproduces the issue:

Go to https://ng-bootstrap.github.io/#/components/carousel/examples and click "Toggle Navigation Indicators" and nothing happens.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 13.2.2

ng-bootstrap: 12.0.0

Bootstrap: 5.1.3

**Comment by divdavem** [comment]
This is the same issue as #4200
