### ISSUE TITLE
ButtonGroup/RadioGrup - no focused style

### ISSUE THREAD

**Issue by projectX21** [ng-bootstrap/ng-bootstrap#4257]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

The focused style for button groups doesn't work in the newest version anymore.

### Link to minimally-working StackBlitz that reproduces the issue:
https://ng-bootstrap.github.io/#/components/buttons/examples

After clicking any button, the focused style doesn't get displayed. In the Bootstrap 5 demo everything works as expected:
https://getbootstrap.com/docs/5.0/components/button-group/

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 12

ng-bootstrap: 12

Bootstrap: 5

**Comment by jnizet** [comment]
Actually, Bootstrap 5 checbox buttons and radio buttons don't need any JavaScript anymore. So using the markup from the Bootstrap documentation and adding ngModel or formControlName on the inputs is sufficient for checbox and radio buttons to work fine. I guess these directives from ng-boostrap should just be removed.

**Comment by projectX21** [comment]
I would say it's not that easy, because the ngbRadioGroup is a ControlValueAccessor with multiple inputs. If I would like to use the radio group implementation of the original Bootstrap example, I would have to implement the ControlValueAccessor for myself.

**Comment by jnizet** [comment]
@projectX21 Angular forms supports radio buttons out of the box. Here's the reactive forms example of ng-bootstrap using the bootstrap 5 markup and the native support for radios of Angular: https://stackblitz.com/edit/angular-rywzjc?file=src%2Fapp%2Fbuttons-radioreactive.ts

**Comment by maxokorokov** [comment]
Thanks for the stackblitz, @jnizet.
I don't think there is any value in having these directives now, they should have been removed in `12.0.0`. It is too late now, so I'll mark them as deprecated and will remove in `13.0.0`.

@projectX21 I don't think we're going to fix the focusing issue, it's not easy with updated markup/css. Please don't use ng-bootstrap for these.
