### ISSUE TITLE
Check BS5 `data-***` styles

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#4261]
In some cases with BS 5 they start to use `data-bs-*` and `data-popper-*` attributes in the style rules, that we didn't have previously (ex. it was the case with broken carousel indicators and missing `data-bs-target` → #4259 

I think we should double-check this these rules.

Looking at the CSS, I see the following:
```css
/* dropdown */
.dropdown-menu[data-bs-popper]

.dropdown-menu-start[data-bs-popper]
.dropdown-menu-end[data-bs-popper]

.dropdown-menu-sm-start[data-bs-popper]
.dropdown-menu-sm-end[data-bs-popper]
.dropdown-menu-md-start[data-bs-popper]
.dropdown-menu-md-end[data-bs-popper]
.dropdown-menu-lg-start[data-bs-popper]
.dropdown-menu-lg-end[data-bs-popper]
.dropdown-menu-xl-start[data-bs-popper]
.dropdown-menu-xl-end[data-bs-popper]
.dropdown-menu-xxl-start[data-bs-popper]
.dropdown-menu-xxl-end[data-bs-popper]

/* tooltip */
.bs-tooltip-auto[data-popper-placement^=top] // with various placement values

/* popover */
.bs-popover-auto[data-popper-placement^=top] // with various placements

/* carousel */
.carousel-indicators [data-bs-target] // this is fixed by #4259 
```

---

1. There several places in the dropdown where we mess with `data-`:

I'm not sure we need this at all:
https://github.com/ng-bootstrap/ng-bootstrap/blob/1425962d40aff923192abc5e203ef6a10f72309a/src/dropdown/dropdown.ts#L66

This is for the `static` case:
https://github.com/ng-bootstrap/ng-bootstrap/blob/1425962d40aff923192abc5e203ef6a10f72309a/src/dropdown/dropdown.ts#L514-L520

And we never set `data-bs-popper` anywhere.

Also, it looks like dropdown menu should be lower, no?

ng-bootstrap:
![Screenshot 2022-02-23 at 10 35 08](https://user-images.githubusercontent.com/8074436/155293386-fdaa50da-de63-402e-9c13-236d74c6721d.jpg)

bootstrap:
![Screenshot 2022-02-23 at 10 35 48](https://user-images.githubusercontent.com/8074436/155293620-c270390e-6382-47a3-9b7f-d179ac3a28cc.jpg)

2. For the tooltip/popover I can't find the case where we ever set `.bs-popover-auto` classes

@fbasso, could you take a look at it, as you've been working on dropdown most ?

**Comment by fbasso** [comment]
Hi @max, I've started to investigate. 

Regarding the dropdown placement, Bootstrap [uses the offset modifier](https://github.com/twbs/bootstrap/blob/main/js/src/dropdown.js#L301), with [0, 2] as the [default value](https://github.com/twbs/bootstrap/blob/main/js/src/dropdown.js#L70).

I tried the same in a branch, and got the right behavior.

I continue to investigate the other points.

**Comment by fbasso** [comment]
As mentioned, I didn't see any usage of .bs-tooltip-auto or .bs-popover-auto, so there is no impact on these ones. The Carousel has been fixed. So the only remaining thing is the dropdown.

I'll do a PR for the fix.
