### ISSUE TITLE
Popper customization

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#4263]
This is an umbrella issue to allow customizing popper configuration for components.

Bootstrap allows to customize certain options related to popper positioning, for example:
Tooltip → https://getbootstrap.com/docs/5.1/components/tooltips/#options

```
    container: selector | element | false
    placement: 'auto' | 'top' | 'bottom' | 'left' | 'right' | function
    fallbackPlacements: ['top', 'right', 'bottom', 'left']
    boundary: 'clippingParents' | element
    offset: array | string | function
    popperConfig: null | object | function
```

I think `placement` and `fallbackPlacements` are covered by ng-bootstrap already. We do not support the `function` use-case at the moment, but it might in future

I see at least 2 things to do in the nearest future (with issues linked):

- [ ] allow customizing our default popper configuration with something along the lines of `popperConfig` input (#4264)
- [ ] fix the `container` option that is limited only to `'body'` currently.

**Comment by peterheMP** [comment]
Any updates for this one since i would like to offset ngbTooltip position?
ngbTooltip position need to be offset when it is open from a parent container which has overflow-y: auto;

**Comment by NicolasRoehm** [comment]
Same for me here, I also need to add an offset.

I'm currently doing this with CSS margin, but Popper is complaining :
```Popper: CSS "margin" styles cannot be used to apply padding between the popper and its reference element or boundary. To replicate margin, use the `offset` modifier, as well as the `padding` option in the `preventOverflow` and `flip` modifiers.``` - `createPopper.js:110`

**Comment by peterheMP** [comment]
@NicolasRoehm I think next version of ngBootstrap should support popConfig according to this https://github.com/ng-bootstrap/ng-bootstrap/issues/4264

**Comment by fbasso** [comment]
ngBootstrap 13.1.0 has been released with the popper options customization feature. See https://github.com/ng-bootstrap/ng-bootstrap/issues/4345#issuecomment-1288719970 to find an example.

I close this issue, don't hesitate to re-open it if there is something wrong.
