### ISSUE TITLE
Documentation for latest Bootstrap 4 branch

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#4272]
Unless I missed something, the only available documentation now is for the v12 version , which is based on Bootstrap 5. But since there still is a branch for Bootstrap 4, and since I expect many projects are still on Bootstrap 4, it would be nice to have the documentation online for this branch too. 
Even if the ng-bootstrap API itself hasn't changed much, the HTML markup in the demos has changed.

**Comment by maxokorokov** [comment]
Having said that, I'll take a look if we can publish a static version under `https://ng-bootstrap.github.io/11.0.0/...`. My fears might be unfounded :)
