### ISSUE TITLE
Angular - issue in pagination using ngx-pagination

### ISSUE THREAD

**Issue by mcaprema** [ng-bootstrap/ng-bootstrap#4277]
Im trying to paginate cards with datatable in which each rows has model. 

*ngFor="let element of poHeader | paginate: { id :'moveNext', itemsPerPage: viewCount, currentPage: page } ; let i= index">

<pagination-controls id='moveNext' class="product-pagination"
                   (pageChange)="onPageChanged($event)"></pagination-controls>

But card datas can be paginated, but datatable for each card wont get paginated (In my case datatable which has model for each row). Please help me out to fix this issue. i have been trying all solutions provided over the net  .

**Comment by pkozlowski-opensource** [comment]
I guess you've meant to open this issue in https://github.com/michaelbromley/ngx-pagination/issues
