### ISSUE TITLE
[devex] Linting/formatting does not support some TS features

### ISSUE THREAD

**Issue by peterblazejewicz** [ng-bootstrap/ng-bootstrap#4284]
### Bug description:

This is for devex experience. Some settings, like formatting based on `clang-*` is not in sync in support TS 4.4 features

Example, this line:
```
.. = this._document.querySelector(options.container) ?? this._document.body;
```
is reformatted by project formatter to this:
```ts
... = this._document.querySelector(options.container) ? ? this._document.body;
```
and it breaks

it can be somehow mitigated (until fixed):
```ts
// clang-format off
new language features not supported by clang
// clang-format on
```

thanks!

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: n/a

ng-bootstrap: n/a

Bootstrap: n/a

Repo: current head

**Comment by peterblazejewicz** [comment]
same for optional chaining, it really shows it's age:
```ts
this._offcanvasRef?.dismiss(reason)
```
becomes:
```ts
this._offcanvasRef ?.dismiss(reason)
```

**Comment by jnizet** [comment]
I agree. I use prettier in most of my projects, and the output is way more readable than clang.
