### ISSUE TITLE
NgbModalOptions are ignored when passing a Component to the open function

### ISSUE THREAD

**Issue by SamShekhovtsov** [ng-bootstrap/ng-bootstrap#4287]
### Bug description:
when passing a Component parameter to the modalService.open function, the options are ignored.

### Link to minimally-working StackBlitz that reproduces the issue:

[https://stackblitz.com/edit/angular-gr86pa?file=src/app/modal-component.ts](https://stackblitz.com/edit/angular-gr86pa?file=src/app/modal-component.ts)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 13.0.3

ng-bootstrap: 12.0.0

Bootstrap: 5.1.3

**Comment by jnizet** [comment]
Your repro works fine. I changed it just a little in order to open modals with two different sizes: https://stackblitz.com/edit/angular-gr86pa-awb1m5?file=src%2Fapp%2Fmodal-component.html. Make sure to enlarge the stackblitz prreview window (so that it's large enough to hold an large modal), and then click the two buttons. You'll see that the sizes are honored.

**Comment by SamShekhovtsov** [comment]
> Your repro works fine. I changed it just a little in order to open modals with two different sizes: https://stackblitz.com/edit/angular-gr86pa-awb1m5?file=src%2Fapp%2Fmodal-component.html. Make sure to enlarge the stackblitz prreview window (so that it's large enough to hold an large modal), and then click the two buttons. You'll see that the sizes are honored.

it didn't work. please don't lie. It doesn't work on my local. What have you changed? Did you change any references?

**Comment by jnizet** [comment]
I just made it more obvious that the size option is honored. And your original stackblitz is still there, unmodified, and still works fine. Please don't call me a liar, that's rude.

**Comment by maxokorokov** [comment]
Can't reproduce, StackBlitz works fine for me too. 
@SamShekhovtsov, please let's stay professional here, especially when people are actually trying to help you.
