### ISSUE TITLE
ngbDatepicker - container body causes page to scroll to bottom

### ISSUE THREAD

**Issue by jecraig** [ng-bootstrap/ng-bootstrap#4290]
### Bug description:

When using ngbDatepicker with the container set as "body", opening the datepicker popup causes the screen to scroll to the bottom of the page.

### Link to minimally-working StackBlitz that reproduces the issue:

https://angular-ivy-q3pj7e.stackblitz.io

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 13.3.0
ng-bootstrap: 12.0.0
Bootstrap: 5.1.3

**Comment by maxokorokov** [comment]
Works with ng-bootstrap < 12, looks like focus is set before popup is positioned with popper
