### ISSUE TITLE
Little "twitch" when closing a modal

### ISSUE THREAD

**Issue by Steb95** [ng-bootstrap/ng-bootstrap#4293]
### Bug description:
When **closing** a modal, before the animation starts there is a little "twitch" (the modal moves on the left) probably due to the fact that the body scrollbar (that is the property overflow: hidden) is restored too early (before the end of the fade out animation). Is there a way to restore the normal scroll behavior only after the fade-out animation ended?

### Link to minimally-working StackBlitz that reproduces the issue:
You can reproduce this behavior in the official page: https://ng-bootstrap.github.io/#/components/modal/examples

I tried to emphasize the effect in the following screen:
![modal](https://user-images.githubusercontent.com/47389399/159238104-818ad2f4-375d-4461-af2b-86fe6331f1b9.gif)

### Versions of Angular, ng-bootstrap and Bootstrap:
See https://ng-bootstrap.github.io/#/components/modal/examples
Tested on Chrome desktop v.  99.0 and Firefox desktop v. 98.0.

**Comment by maxokorokov** [comment]
Most likely scrollbar restored too early:

https://github.com/ng-bootstrap/ng-bootstrap/blob/a414c75da1e2e57276509f7341c249eb33194afb/src/modal/modal-stack.ts#L77
