### ISSUE TITLE
Fullscreen Modal bootstrap 5

### ISSUE THREAD

**Issue by ldavidsp** [ng-bootstrap/ng-bootstrap#4298]
Add new size.

```
 fullscreen
 fullscreen-sm-down
 fullscreen-md-down
 fullscreen-lg-down
 fullscreen-xl-down
 fullscreen-xxl-down
```

Angular: 13.3.0

ng-bootstrap: 12.0.1

Bootstrap: 5.1

**Comment by maxokorokov** [comment]
We should think for a proper API for this maybe, but you can workaround it by using modal options `modalDialogClass` and adding the `modal-fullscreen-XXX` class yourself → https://ng-bootstrap.github.io/#/components/modal/api#NgbModalOptions
