### ISSUE TITLE
Making more accessible components

### ISSUE THREAD

**Issue by Anjmao** [ng-bootstrap/ng-bootstrap#430]
Just wanted to suggest add more requirements for components like accessibility and quality. Let takes buttons as example. Imagine I have form and I use angular bootstrap radio buttons or checkbox buttons. Currently it is not possible to use tab keyboard to navigate to buttons and select them, but this is very common scenario in normal applications.

**Comment by pkozlowski-opensource** [comment]
It is on our roadmap, see: https://github.com/ng-bootstrap/ng-bootstrap/wiki/Roadmap

Although it is going to happen only after we are done with modal, typaheads and date / time pickers.

Accessibility is rather large topic so proper support for screen readers, keyboard navigation etc. won't happen overnight. Unless someone sends us awesome PRs of course :-)

Lastly, could you elaborate what you mean by "more quality" here? Rather vague as a statement....

**Comment by pkozlowski-opensource** [comment]
Going to go ahead and close this one as we've got accessibility and keyboard navigation on roadmap and this issue doesn't provide more details / insights.

If you want to speed up things please _do_ send great PRs!
