### ISSUE TITLE
NgbDropdownItem [disabled] not working properly

### ISSUE THREAD

**Issue by chrosenau** [ng-bootstrap/ng-bootstrap#4301]
When I use `ngbDropdownItem` directive on a button element as suggested for keyboard navigation, the `disabled` option is not working properly. It just adds a `disabled` CSS class, but does not add the `disabled` button property. So the disabled option is not clickable or selectable via keyboard navigation, but is still accessible via `Tab` and selectable via `Space` or `Enter`. 
And while the directive is "catching" the disabled property I can't add them to the button by myself.

https://stackblitz.com/edit/angular-vwghsr?file=src/app/dropdown-basic.html

**Comment by jnizet** [comment]
Hi @chrosenau 

Until the bug is fixed, you can mitigate the issue by setting tabIndex="-1" if the item is disabled. That will prevent the item from being focusable with tab.

**Comment by maxokorokov** [comment]
`[attr.disabled]="true"` as well ?

**Comment by chrosenau** [comment]
@maxokorokov this is a working workaround. thanks.

**Comment by maxokorokov** [comment]
Also see this → https://github.com/ng-bootstrap/ng-bootstrap/pull/4303#issuecomment-1090414427
