### ISSUE TITLE
[Feature Request] make the activeIds property of ngbAccordion two-way bindable

### ISSUE THREAD

**Issue by hillin** [ng-bootstrap/ng-bootstrap#4307]
Per https://github.com/ng-bootstrap/ng-bootstrap/issues/3884 :

The current behavior of the `activeIds` property already mismatches with the documentation:
- setting this property will change the collapse state of panels
- expanding/collapsing a panel will change this property

I think it would be a good idea to also make this property two-way bindable, so we can manipulate collapse states with binding.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 13.1.1

ng-bootstrap: 12.0.0 beta 4

Bootstrap: 5.1.1

**Comment by maxokorokov** [comment]
Same comment as here → https://github.com/ng-bootstrap/ng-bootstrap/issues/3884#issuecomment-1480848188
