### ISSUE TITLE
Tooltip arrow color not changing

### ISSUE THREAD

**Issue by k2rta** [ng-bootstrap/ng-bootstrap#4310]
Issue with the tooltip colors, the container itself colors nicely, but the arrow remains black.

currently got it to this:
![image](https://user-images.githubusercontent.com/57257994/163185395-762d2488-eeec-4016-8721-1858c8a4ba4b.png)

with css (i have scss): 

```
.error-tooltip .tooltip-inner {
  background-color: colors.$primary-white;
  border: 1px solid colors.$input-grey;
  color: colors.$primary-black;
  font-size: 100%;
}

.error-tooltip .arrow::before {
  border-color: darkgreen;
}
```

the css is from the docs, it does not work there either 

any ideas on how to color the arrow too? or is this a bug?

**Comment by jnizet** [comment]
Here's the documentation showing what the markup is: https://getbootstrap.com/docs/5.1/components/tooltips/#markup.

As you can see, there is no CSS class `arrow`. It's named `tooltip-arrow`.

Regarding how to set the arrow color, it depends on its position. Look at the source code of bootstrap (in `_tooltip.scss`) to know how to set its color.

**Comment by k2rta** [comment]
Thanks! Finally got it 

The documentation should be updated i think

**Comment by jnizet** [comment]
Ah, now I understand that you copied and pasted this CSS from one of our demos. I just submitted a PR to update the demo.

**Comment by ahsinsiddique** [comment]
this works
.bs-tooltip-top .tooltip-arrow::before, .bs-tooltip-auto[data-popper-placement^=top] .tooltip-arrow::before {
  border-top-color: #0062A2 !important;
}
