### ISSUE TITLE
Left and right tooltip arrow position is moving 

### ISSUE THREAD

**Issue by guisaas** [ng-bootstrap/ng-bootstrap#4321]
### Bug description:
Left and right tooltip arrow is moving when hovering the button that triggers this tooltip instead of being directly centered

### Link to minimally-working StackBlitz that reproduces the issue:

You can reproduce the issue with your current version of the portal: https://ng-bootstrap.github.io/#/components/tooltip/examples#basic by just hovering the left or right tooltip. 

First the arrow is displayed not centered with the button. Then some time later, it moves to the center of the button

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 13

ng-bootstrap: 12.1.1

Bootstrap: 5

**Comment by maxokorokov** [comment]
![Tooltip](https://user-images.githubusercontent.com/8074436/166659214-0d066d0b-0c35-4b7d-b013-628456b0a473.gif)

Definitely something animation-related
