### ISSUE TITLE
How to install ng-bootstrap on an nx.dev project?

### ISSUE THREAD

**Issue by rkristelijn** [ng-bootstrap/ng-bootstrap#4326]
`npx nx g @ng-bootstrap/ng-bootstrap:ng-add --project=project-name` will result in:

```
Unable to resolve @ng-bootstrap/ng-bootstrap:ng-add
Cannot find module '@ng-bootstrap/ng-bootstrap:ng-add'
```

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 13.2.0
ng-bootstrap: tbd
Bootstrap: 4
@nrwl/cli: 13.8.3

documentation: https://nx.dev/packages/angular/generators/ng-add#nrwlangularng-add

**Comment by jnizet** [comment]
This is more of a question for nx than for ng-bootstrap. I was under the impression that you could use standard `ng` commands on an nx Angular projest. If that's the case, follow the thist part of the installation guide here: https://ng-bootstrap.github.io/#/getting-started#installation. If not, then follow the "Manual installation" part that follows, which is quite simple, and interesting to understand anyway.

**Comment by rkristelijn** [comment]
We fixed it by following the proper documentation https://ng-bootstrap.github.io/#/getting-started

'ng add @ng-bootstrap/ng-bootstrap --project myProject'

Thanks for the response
