### ISSUE TITLE
Popover classlist gets fludded with extra classes related to placement on document scroll

### ISSUE THREAD

**Issue by mis6ko13** [ng-bootstrap/ng-bootstrap#4327]
### Bug description:
Popover (ngb-popover-window) classlist gets fludded with extra classes during document scrolling if one of the placement options contains '-start', '-left', '-end' or '-right' prefix.

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-qmskoz?file=src/app/popover-basic.html

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 13.0.3

ng-bootstrap: 12.1.1

Bootstrap: 5

![image_2022_05_06T10_42_22_519Z](https://user-images.githubusercontent.com/16404558/167139423-15814f3d-b68e-492c-a7b3-84b203186a83.png)

**Comment by fbasso** [comment]
Thanks for reporting this issue @mis6ko13. 

In your stackblitz, I was not able to find so many `-end` classes on the `ngb-popover-window`. But I can see a single one, which is already enough to reproduce it.
