### ISSUE TITLE
Build: fail Travis CI build on TS errors

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#433]
See this build example: https://travis-ci.org/ng-bootstrap/ng-bootstrap/builds/144196306

This should be marked as build failure.

**Comment by icfantv** [comment]
@pkozlowski-opensource, IIRC, there's a known issue in webpack whereby it does not exit with a non-zero exit code on compiler failures.

**Comment by pkozlowski-opensource** [comment]
@icfantv we are not using WebPack on CI. The only compilation that happens is during test run and our error handling is less then ideal in there. 

#434 helps a bit in the sense that things will fail miserably when it doesn't compile. But there is further room for improvement (ex.: we should still emit during `tdd`). Will look into it some more tomorrow.

**Comment by icfantv** [comment]
Ahhhhh.  Right.

**Comment by Foxandxss** [comment]
I wanted to add that as a deal breaking but for some reason I decided not to. I will fix.
