### ISSUE TITLE
ngb-toast close button is a square not an x button

### ISSUE THREAD

**Issue by ngingihy** [ng-bootstrap/ng-bootstrap#4331]
### Bug description:
ngb-toast close button is messed up, it's displayed as a square not X button like in the document

### Link to minimally-working StackBlitz that reproduces the issue:

When i put it in stackBlitz it works fine, but when i have it running locally, it automatically hides and everything but the X close button is messed up when i put the header

I'm just running the below
```
<ngb-toast header="Notification header">
    Content of the notification
  </ngb-toast>

```

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 13.1.1

ng-bootstrap: ^12.0.1

Bootstrap:^4.6.1

**Comment by fbasso** [comment]
ngBootstrap 12 only works with Bootstrap 5, that's why you have this display issue.

**Comment by jnizet** [comment]
See the compatibility matrix here: https://ng-bootstrap.github.io/#/getting-started
