### ISSUE TITLE
Add .form-floating class support for typeahead

### ISSUE THREAD

**Issue by Stajor** [ng-bootstrap/ng-bootstrap#4332]
Angular: 13.0
ng-bootstrap: 12.1.1
Bootstrap: 5.1.3

I have feature request to add form-floating support to typeahead.

https://getbootstrap.com/docs/5.1/forms/floating-labels/

**Comment by jnizet** [comment]
Hi @Stajor 

It's already supported. Just make sure to respect the markup documented in the Bootstrap documentation.

**Comment by Stajor** [comment]
@jnizet 
Thank you, you are right. The placeholder attribute was missing in my code.
