### ISSUE TITLE
Ng Rating issue

### ISSUE THREAD

**Issue by sainimalkeet** [ng-bootstrap/ng-bootstrap#4339]
Ng rating starts not showing properly in version 11.0.1. Stars are blinking on hover

**Comment by maxokorokov** [comment]
Works fine for me → https://ng-bootstrap.github.io/releases/11.x/#/components/rating/examples

---

Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz

**Comment by maxokorokov** [comment]
Closing as no response, please reopen if necessary.
