### ISSUE TITLE
Add support to angular 14

### ISSUE THREAD

**Issue by mshima** [ng-bootstrap/ng-bootstrap#4340]
### Bug description:

We are tracking dependencies upgrade to angular 14 at https://github.com/jhipster/generator-jhipster/issues/18817.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 14

ng-bootstrap: any

**Comment by Zwergenpunk** [comment]
this is kinda blocking. (and should be released soon)
https://github.com/angular-eslint/angular-eslint/pull/1004

**Comment by javascriptcowboy** [comment]
Plus 1 for needing 14 support.

**Comment by AlphaRomeoMike** [comment]
Plus one for v14 support!

**Comment by EzekielaRakotoarijaona** [comment]
plus one

**Comment by hydrogen2oxygen** [comment]
This is super important!

**Comment by robinleathal** [comment]
Seriously needed v14 support ASAP

**Comment by rolanddeboer** [comment]
This is very needed!

**Comment by daniel-zero** [comment]
Will you also upgrade the the bootstrap v4 version of the library to support Angular 14? Would be great to know!

**Comment by devoto13** [comment]
@daniel-zero Based on https://github.com/ng-bootstrap/ng-bootstrap/issues/4248#issuecomment-1084245139, I don' think so.

**Comment by maxokorokov** [comment]
Just published beta for Angular 14 support under the `next` tag:
```
{
  latest: '12.1.2',
  next: '13.0.0-beta.1'
}
```

We'd like to do more tests + add some changes to the datepicker before doing the final `13.0.0`, so there will be a couple more beta releases.

**Comment by nbittich** [comment]
> Just published beta for Angular 14 support under the `next` tag:
> 
> ```
> {
>   latest: '12.1.2',
>   next: '13.0.0-beta.1'
> }
> ```
> 
> We'd like to do more tests + add some changes to the datepicker before doing the final `13.0.0`, so there will be a couple more beta releases.
Cool 👍🏼

**Comment by technologiesspatial** [comment]
> next

not working 

`ng add @ng-bootstrap/ng-bootstrap@next
ℹ Using package manager: npm
✔ Package information loaded.

The package @ng-bootstrap/ng-bootstrap@next will be installed and executed.
Would you like to proceed? Yes
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: angular-test@0.0.0
npm ERR! Found: @angular/core@14.0.1
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"14.0.1" from @angular/animations@14.0.1
npm ERR!   node_modules/@angular/animations
npm ERR!     peerOptional @angular/animations@"14.0.1" from @angular/platform-browser@14.0.1
npm ERR!     node_modules/@angular/platform-browser
npm ERR!       peer @angular/platform-browser@"14.0.1" from @angular/forms@14.0.1
npm ERR!       node_modules/@angular/forms
npm ERR!         @angular/forms@"^14.0.0" from the root project
npm ERR!       3 more (@angular/platform-browser-dynamic, @angular/router, the root project)
npm ERR!     @angular/animations@"^14.0.0" from the root project
npm ERR!   peer @angular/core@"14.0.1" from @angular/common@14.0.1
npm ERR!   node_modules/@angular/common
npm ERR!     peer @angular/common@"14.0.1" from @angular/forms@14.0.1
npm ERR!     node_modules/@angular/forms
npm ERR!       @angular/forms@"^14.0.0" from the root project
npm ERR!     peer @angular/common@"14.0.1" from @angular/platform-browser@14.0.1
npm ERR!     node_modules/@angular/platform-browser
npm ERR!       peer @angular/platform-browser@"14.0.1" from @angular/forms@14.0.1
npm ERR!       node_modules/@angular/forms
npm ERR!         @angular/forms@"^14.0.0" from the root project
npm ERR!       3 more (@angular/platform-browser-dynamic, @angular/router, the root project)
npm ERR!     3 more (@angular/platform-browser-dynamic, @angular/router, the root project)
npm ERR!   6 more (@angular/compiler, @angular/forms, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! @ng-bootstrap/ng-bootstrap@"13.0.0-beta.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/core@14.0.2
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"14.0.2" from @angular/forms@14.0.2
npm ERR!   node_modules/@angular/forms
npm ERR!     @angular/forms@"^14.0.0" from the root project
npm ERR!     peer @angular/forms@"^14.0.0" from @ng-bootstrap/ng-bootstrap@13.0.0-beta.1
npm ERR!     node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!       @ng-bootstrap/ng-bootstrap@"13.0.0-beta.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\ayogr\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ayogr\AppData\Local\npm-cache\_logs\2022-06-21T11_11_37_789Z-debug-0.log`

**Comment by karptonite** [comment]
> Will you also upgrade the the bootstrap v4 version of the library to support Angular 14? Would be great to know!

This is discussed in #4248. We've started the process of trying to upgraded to Bootstrap 5--it looks like it will be a significant job, and we'd love to be able to stay on Bootstrap 4 for a little longer.

**Comment by hpardess** [comment]
Not working...

https://github.com/ng-bootstrap/ng-bootstrap/issues/4178#issuecomment-1164080658

**Comment by Vijay-Nirmal** [comment]
> Not working...
> 
> [#4178 (comment)](https://github.com/ng-bootstrap/ng-bootstrap/issues/4178#issuecomment-1164080658)

Just do `ng update @angular/core` to resolve the conflicts

**Comment by hpardess** [comment]
> > Not working...
> > [#4178 (comment)](https://github.com/ng-bootstrap/ng-bootstrap/issues/4178#issuecomment-1164080658)
> 
> Just do `ng update @angular/core` to resolve the conflicts

Thank you... 

ng update @angular/core
ng add @ng-bootstrap/ng-bootstrap@next

**Comment by xxnickles** [comment]
Is there any target time frame for the stable version for Angular 14?

**Comment by SvenAtGit** [comment]
Can someone fix this? This is the only package that blocks my upgrade at the moment

npm ERR!   dev @angular-devkit/build-angular@"~13.3.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"~13.3.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/compiler-cli@13.3.11
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   peer @angular/compiler-cli@"^13.0.0 || ^13.3.0-rc.0" from @angular-devkit/build-angular@13.3.8
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~13.3.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!   @ng-bootstrap/ng-bootstrap@"^12.1.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Sven\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:

**Comment by wopian** [comment]
@SvenAtGit this is not related to ng-angular. Update your Angular ESLint packages to [`14.0.0`](https://github.com/angular-eslint/angular-eslint/releases/tag/v14.0.0)

**Comment by hellios49** [comment]
The package @ng-bootstrap/ng-bootstrap@12.1.2 will be installed and executed.
Would you like to proceed? Yes
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: admin-dashboard@0.0.0
npm ERR! Found: @angular/common@14.0.4
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^13.0.0" from @ng-bootstrap/ng-bootstrap@12.1.2
npm ERR! node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!   @ng-bootstrap/ng-bootstrap@"12.1.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/Coding/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/Coding/.npm/_logs/2022-07-03T13_20_12_263Z-debug-0.log
✖ Packages installation failed, see above.

is this error because of support issue ? 
i have wasted 10 hours trying to solve this problem , please add it as soon as possible .tnx to
 all working team

**Comment by bellash13** [comment]
I downgraded to Angular13... +2days lost because of lack of support to Angular14

**Comment by nbittich** [comment]
Following the crazy pace of angular is not that easy, so I can easily understand why it takes time.  thanks for the great work👏

**Comment by MikhaelGerbet** [comment]
+1 to support Angular 14

**Comment by daniel-zero** [comment]
You can just override your dependencies using the npm override feature.
Just add this in your package.json and you should be fine.

```json
"overrides": {
    "@ng-bootstrap/ng-bootstrap": {
      "@angular/common": "^13.0.0 || ^14.0.0",
      "@angular/core": "^13.0.0 || ^14.0.0",
      "@angular/forms": "^13.0.0 || ^14.0.0",
      "@angular/localize": "^13.0.0 || ^14.0.0"
    },
}
```

**Comment by mrafsyam** [comment]
Hi, +1 for the support as well. Thanks.

**Comment by Zwergenpunk** [comment]
They will not release a new version if all of you post +1. There is alread a working version released, and the final version will come sooner or later. Stressing about it will not change anything.

**Comment by chrestha** [comment]
+1

**Comment by John-Santacruz** [comment]
+1

**Comment by richokorn** [comment]
> You can override your dependencies using the npm override feature Just add this in your package.json and you should be fine.
> 
> ```json
> "overrides": {
>     "@ng-bootstrap/ng-bootstrap": {
>       "@angular/common": "^13.0.0 || ^14.0.0",
>       "@angular/core": "^13.0.0 || ^14.0.0",
>       "@angular/forms": "^13.0.0 || ^14.0.0",
>       "@angular/localize": "^13.0.0 || ^14.0.0"
>     },
> }
> ```
> 
> [docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides)

This needs to be higher up. Great workaround!

**Comment by abdo-host** [comment]
needed v14 support ASAP

**Comment by wopian** [comment]
> needed v14 support ASAP

The beta version added Angular 14 support a month ago if you need 14 now.

https://github.com/ng-bootstrap/ng-bootstrap/issues/4340

**Comment by soufiane-X** [comment]
@wopian how can i install it ?

**Comment by wopian** [comment]
@soufiane-X that is an error from `ng-clarity` depending on Angular 13 peer dependencies (https://github.com/vmware-clarity/ng-clarity)

**Comment by kalani96746** [comment]
+1.  I was able to bypass the issue with a --force..but please add angular 14 support so its not needed.

**Comment by msitruk** [comment]
Seems OK at install with next version :

`
ng add @ng-bootstrap/ng-bootstrap@next
i Using package manager: yarn
√ Package information loaded.

The package @ng-bootstrap/ng-bootstrap@next will be installed and executed.
Would you like to proceed? Yes
√ Packages successfully installed.
UPDATE package.json (1296 bytes)
√ Packages installed successfully.
Option "name" is deprecated: Use the "project" option instead.
UPDATE src/app/app.module.ts (923 bytes)
UPDATE angular.json (3010 bytes)
UPDATE src/polyfills.ts (2567 bytes)
`

But at ng serve got this warning : 
`
Build at: 2022-07-20T15:28:42.760Z - Hash: 458e74906d531dbf - Time: 19580ms

./node_modules/bootstrap/dist/css/bootstrap.min.css.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[2]!./node_modules/bootstrap/dist/css/bootstrap.min.css - Warning: Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
Warning

(6:30368) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
`

Finally it's not working, my text is not red  :(  
`
<p class="text-danger">blabla</p>
`

Thank for your work !

**Comment by wopian** [comment]
@msitruk Autoprefixer 10.4.6 deprecated `color-adjust` for `print-color-adjust`.

The change to the new name happened in Bootstrap 5.2.0 (this package is currently on 5.0.x or 5.1.x), you can follow https://github.com/ng-bootstrap/ng-bootstrap/issues/4354 for updates

In the mean time while waiting for the Angular Bootstrap Devs to support Bootstrap 5.2.x, you can pin your version of Autoprefixer to the version before the `color-adjust` deprecation with the following in `package.json`:

- Yarn
```json
"resolutions": {
  "autoprefixer": "10.4.5"
}
```

- npm
```json
"overrides": {
  "autoprefixer": "10.4.5"
}
```

**Comment by msitruk** [comment]
thank @wopian,  pinnin version of Autoprefixer resolve warning but my bootstrap still not working

**Comment by msitruk** [comment]
ok my bad .. in my case issue was because I used : encapsulation: ViewEncapsulation.ShadowDom in my component that I want to use a WebComponent with @angular/elements

Still trying to figure how to ship bootstrap in my WebComponent, the only way I found for now is to @import "~bootstrap/dist/css/bootstrap.css"; in the css component itself.

**Comment by bjornharvold** [comment]
> ok my bad .. in my case issue was because I used : encapsulation: ViewEncapsulation.ShadowDom in my component that I want to use a WebComponent with @angular/elements
> 
> Still trying to figure how to ship bootstrap in my WebComponent, the only way I found for now is to @import "~bootstrap/dist/css/bootstrap.css"; in the css component itself.

Bootstrap is not meant for embeddable Web Components for entire sites. Switch to Tailwind for that and you'll never look back.

**Comment by Aniketu** [comment]
ng add @ng-bootstrap/ng-bootstrap@next works fine with angular 14 version

**Comment by soufiane-X** [comment]
@Aniketu i tried it but the ng-bootstrap doesn't work no feature is working

**Comment by Aniketu** [comment]
> @Aniketu i tried it but the ng-bootstrap doesn't work no feature is working

@soufiane-X  It's working for me. Check below version details which I'm using in project.

Angular CLI: 14.1.0
Node: 16.16.0
Package Manager: npm 8.15.0
OS: win32 x64

Angular: 14.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.0
@angular-devkit/build-angular   14.1.0
@angular-devkit/core            14.1.0
@angular-devkit/schematics      14.1.0
@schematics/angular             14.1.0
rxjs                            7.5.6
typescript                      4.7.4

**Comment by AndreaDevBE** [comment]
It doesn't work for me

`Angular CLI: 14.1.0
Node: 16.16.0
Package Manager: npm 8.15.0
OS: win32 x64

Angular: 14.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.0
@angular-devkit/build-angular   14.1.0
@angular-devkit/core            14.1.0
@angular-devkit/schematics      14.1.0
@schematics/angular             14.1.0
rxjs                            7.5.6
typescript                      4.7.4
`

**Comment by ranieriprg** [comment]
> You can override your dependencies using the npm override feature. Just add this in your package.json and you should be fine.
> 
> ```json
> "overrides": {
>     "@ng-bootstrap/ng-bootstrap": {
>       "@angular/common": "^13.0.0 || ^14.0.0",
>       "@angular/core": "^13.0.0 || ^14.0.0",
>       "@angular/forms": "^13.0.0 || ^14.0.0",
>       "@angular/localize": "^13.0.0 || ^14.0.0"
>     },
> }
> ```
> 
> https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

That worked for me, thanks.

**Comment by AndreaDevBE** [comment]
It's resolved for me, i used bootstrap in version 5.2.0 and since i downgrade to 4.6.2 all the problems has been resolved. (without overrides and just with the next version)

**Comment by hosseinGanjyar** [comment]
> It's resolved for me, i used bootstrap in version 5.2.0 and since i downgrade to 4.6.2 all the problems has been resolved. (without overrides and just with the next version)

Do you think it's a suitable choice for this problem!!? Downgrade current version of  bootstrap and corrupt all of project design just for for example, a module of a library?!!!!    
  

**Unlike and  downvote!**

**Comment by hosseinGanjyar** [comment]
> 

**Error**: 
✖ Unable to fetch package information for '@ng-bootstrap/ng-bootstrap@next': No matching version found for @ng-bootstrap/ng-bootstrap@next.

```
"@angular/core": "^14.2.0",
"bootstrap": "^5.2.2"
```

**Comment by maxokorokov** [comment]
@hosseinGanjyar https://ng-bootstrap.github.io/#/getting-started#dependencies
