### ISSUE TITLE
'ComponentFactoryResolver' is deprecated

### ISSUE THREAD

**Issue by varun-av** [ng-bootstrap/ng-bootstrap#4343]
### Bug description:
With Angular 13, the `ComponentFactoryResolver` is deprecated. From the official docs:
`Angular no longer requires Component factories. Please use other APIs where Component class can be used directly.
'ComponentFactoryResolver' is deprecated.`

Can we please get a version which creates the components using the ViewContainerRef?

Deprecations: [https://angular.io/guide/deprecations](https://angular.io/guide/deprecations)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 13.3.0

ng-bootstrap: 11.0.0

Bootstrap: 4.6.1

**Comment by maxokorokov** [comment]
We will eventually when Angular provides an API to create components without attaching them.
See https://github.com/angular/angular/issues/45263#issuecomment-1082530357
