### ISSUE TITLE
Unsatisfied version 11.0.0 from central of shared singleton module @ng-bootstrap/ng-bootstrap (required ^12.0.0)

### ISSUE THREAD

**Issue by tavonanomn** [ng-bootstrap/ng-bootstrap#4344]
An error ocurred when update ng-bootstrap 11.0.0 to 12.0.0. In all version >12

### Versions of Angular, ng-bootstrap, and Bootstrap:

Angular: 13.1.1

ng-bootstrap: 12.0.0

Bootstrap: 5.1.3

**Comment by maxokorokov** [comment]
Could you please be more specific/attach error messages?
Also `@ng-bootstrap/ng-bootstrap@12.0.0` was not released yet, only the beta version

**Comment by maxokorokov** [comment]
Closing as no response, please reopen if necessary.
