### ISSUE TITLE
Popover positioning wrong when cdk-global-scrollblock present

### ISSUE THREAD

**Issue by benz-netapp** [ng-bootstrap/ng-bootstrap#4345]
### Bug description:

When an Angular Material dialog is opened over top of a page that contains a scrollbar, a `cdk-global-scrollblock` class and associated `top` and `left` values are automatically added to the root `<html>` element, which blocks scrolling of the occluded background page while the dialog is open.

![image](https://user-images.githubusercontent.com/90280648/176231637-0af66155-2cea-4212-817d-c6655dfe05f4.png)

If a popover with the `[container]="'body'"` option is then opened from the dialog, the vertical positioning of the popover will be wrong.

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-yybbck

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 13.3.6

ng-bootstrap: 12.1.2

Bootstrap: 5.1.3

**Comment by fbasso** [comment]
Thanks for reporting an issue, @benz-netapp,

After some investigations, it seems that depending on the popper container, a different 'strategy' must be used in the popper config : https://popper.js.org/docs/v2/constructors/#strategy. I tested the fix by forcing this option internally.

At the moment, there is no way to change the popper config, but it will come soon with the PR #4323, where it will be possible to override the default options.

**Comment by fbasso** [comment]
ngBootstrap 13 is out, so it's now possible to fix this issue by changing the popper options:

https://stackblitz.com/edit/angular-cyekyx?file=src%2Fapp%2Fpopover-container.html,src%2Fapp%2Fpopover-container.tss
