### ISSUE TITLE
Module not found: Error: Package path ./toast/toast is not exported

### ISSUE THREAD

**Issue by wokier** [ng-bootstrap/ng-bootstrap#4348]
### Bug description:
I have a angular build issue
./src/app/shared/components/type-toast.component.ts:1:0-66 - Error: Module not found: Error: Package path ./toast/toast is not exported from package /projects/my-web/node_modules/@ng-bootstrap/ng-bootstrap (see exports field in /projects/my-web/node_modules/@ng-bootstrap/ng-bootstrap/package.json)

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-ivy-damiwq?file=src%2Fapp%2Fshared%2Fcomponents%2Ftype-toast.component.ts
(connected to sample repository)

https://stackblitz.com/edit/angular-ivy-rnstmo?file=src%2Fapp%2Fshared%2Fcomponents%2Ftype-toast.component.ts,src%2Fmain.ts
(fork with Stackblitz adaptations but failed to make it work because it gives "ngcc failed to run on @angular/compiler@9.0.0." where i am with version 13)

or
https://github.com/wokier/ng-bootstrap-my-web
run command :
npm install && npm run-script build

### Versions of Angular, ng-bootstrap and Bootstrap:
Angular: 13.3.6

ng-bootstrap: 12.1.2

Bootstrap: 5.1.3

Node 14

**Comment by jnizet** [comment]
Your import is incorrect. You import from `@ng-bootstrap/ng-bootstrap/toast/toast` instead of importing from `@ng-bootstrap/ng-bootstrap`.

**Comment by wokier** [comment]
That's it! Thanks
