### ISSUE TITLE
Ng-popover close automatically when select date from date-picker

### ISSUE THREAD

**Issue by aj-hops** [ng-bootstrap/ng-bootstrap#4352]
When I am trying to use multiple ng-popover on one screen, when I open one pop-over and then open another popover on the same screen, the first ng-popover is closed by its default ng-popover functionality.

Using : popover-trigger="'outsideClick'" & popover-trigger="focus" 

with the same functionality,
when I am implementing a date-picker inside ng-popover, the ng-popover automatically closes when I am choosing a date from the date-picker.

angular : V11.0.4
bootstrap : V4.0.0

stackblitz : https://stackblitz.com/edit/angular-rfekrd-3igomv?file=src/app/popover-triggers.html

**Comment by maxokorokov** [comment]
Your tooltip arrow issue works fine with the latest version → https://stackblitz.com/edit/angular-paujwa?file=src%2Fapp%2Fpopover-triggers.html

Please provide a StackBlitz for your datepicker issue

**Comment by maxokorokov** [comment]
Closing as no response, please reopen if necessary.
