### ISSUE TITLE
Horizontal collapse missing

### ISSUE THREAD

**Issue by nik2208** [ng-bootstrap/ng-bootstrap#4353]
would be useful to collapse elements horizontally.
As far as I was able to investigate, there is no easy way to achieve this thru configs.
[here](https://stackblitz.com/edit/angular-rvbxrq) is a working stackblits

**Comment by maxokorokov** [comment]
Indeed, there is a horizontal collapse in Bootstrap → https://getbootstrap.com/docs/5.2/components/collapse/#horizontal

**Comment by nik2208** [comment]
wow..it works
