### ISSUE TITLE
Datepicker positions on top-left most of the page

### ISSUE THREAD

**Issue by argelj289** [ng-bootstrap/ng-bootstrap#4357]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
I upgraded our app from angular 10 into angular 14 and its bootstrap to version 12.1.2

I encountered a bug where when I toggle the button that will open the datepicker, the datepicker is not displaying near the input control. please see image below (datepicker is marked with red box)

UI:
![image](https://user-images.githubusercontent.com/40298377/179201967-30bce05b-e271-4752-ac69-b9b8dffe906f.png)

inspect element in chrome:

![image](https://user-images.githubusercontent.com/40298377/179202986-0c93501c-acf6-4154-ac6c-5e879e9b349d.png)

### Link to minimally-working StackBlitz that reproduces the issue:

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:

ng-bootstrap:

Bootstrap:

**Comment by argelj289** [comment]
Hi,

any updates here?

Thank you

**Comment by argelj289** [comment]
Hi,

I would like to know if this is still active

Thank you

**Comment by fbasso** [comment]
Hi @argelj289, thank you for reporting an issue,

Do you have more information about it ?

Starting from the the datepicker input example (https://ng-bootstrap.github.io/#/components/datepicker/examples#popup) on Stackblitz (https://ng-bootstrap.github.io/stackblitzes/datepicker/popup/stackblitz.html), everything works fine.

Some useful point to know:

- What is the popper version you use ? (popper is charge of the positioning),
- What is your code regarding the datepicker input (what are the options you use) ?
- Anything specific of your code that would lead to this issue ?

The best would be to have a Stackblitz to reproduce the issue.

**Comment by fbasso** [comment]
Close as no response, please reopen if necessary
