### ISSUE TITLE
NgbDatepicker Can not change mouse over text year and month

### ISSUE THREAD

**Issue by Ferhad-Karimli** [ng-bootstrap/ng-bootstrap#4358]
`[](url)`

I would like change mouseover text for year and month select. How can change it ? I have putted photo also for this issue. Could you help me ,plea
![WhatsApp Image 2022-07-15 at 15 09 28 (1)](https://user-images.githubusercontent.com/70895616/179218222-721c8378-0129-4942-a9ab-411f85b591c8.jpeg)
se ?

**Comment by maxokorokov** [comment]
Duplicate of #4359
