### ISSUE TITLE
Angular.js NgbDatepicker Can not change mouse over text year and month

### ISSUE THREAD

**Issue by Ferhad-Karimli** [ng-bootstrap/ng-bootstrap#4359]
I would like change mouseover text for year and month select. How can change it ? I have putted photo also for this issue. Could you help me ,please ?

![WhatsApp Image 2022-07-15 at 15 09 28 (1)](https://user-images.githubusercontent.com/70895616/179218378-6a5db858-7a35-4d96-806a-6ecd66c2cd0e.jpeg)

**Comment by maxokorokov** [comment]
You can use standard Angular i18n.

Please see https://angular.io/guide/i18n-overview and the source code → https://github.com/ng-bootstrap/ng-bootstrap/blob/9d80e66980b13b4bc330f0e588149f5a3d954b8a/src/datepicker/datepicker-navigation-select.ts#L26
