### ISSUE TITLE
Collapse does not work with negated variable

### ISSUE THREAD

**Issue by molnarm** [ng-bootstrap/ng-bootstrap#4362]
### Bug description:

The examples use `isCollapsed` and work perfectly.
However, if in my code I have an `isOpen` (or logically equivalent) and use that with ngbCollapse, the component is broken. After closing it for the first time, it always needs to be clicked **twice** to open/close again.

Note that replacing the toggle() call with `isOpen = !isOpen` works too.

### Link to minimally-working StackBlitz that reproduces the issue:

[https://stackblitz.com/edit/angular-nh4m5k?file=src/app/collapse-basic.html](https://stackblitz.com/edit/angular-nh4m5k?file=src/app/collapse-basic.html)

This is forked from the first Collapse example, the only change is that the variable was inverted.

### Versions of Angular, ng-bootstrap and Bootstrap:

Reproducible with the fork of the official example.
I have Angular 13.3, ngbootstrap 12.1.2 and Bootstrap 5.1.3.

**Comment by jnizet** [comment]
Hi @molnarm 

I'm even surprised this compiles. `[(ngbCollapse)]="foo"` is a shortcut for `[ngbCollapse]="foo" (ngbCollapseChange)="foo = $event"`. So, if you replace `foo` by `!isOpen`, then you're trying to execute the instruction `!isOpen = $event`, which doesn't make much sense: the left side must be assignable to the event.

**Comment by molnarm** [comment]
Yes, it's weird. I opened the issue because I thought maybe some magic was going on here in the library so this was almost working, but if not, it's OK for me to close this.
