### ISSUE TITLE
CHANGELOG.md link to page is broken

### ISSUE THREAD

**Issue by sysmat** [ng-bootstrap/ng-bootstrap#4365]
### Bug description:
- https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md
- in section https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#breaking-changes  in see [this page](https://ng-bootstrap.github.io/releases/12.x/#/components/buttons/overview) for more details. 
- link not working 404: https://ng-bootstrap.github.io/releases/12.x/#/components/buttons/overview

**Comment by maxokorokov** [comment]
Thanks, @sysmat, forgot to update demo site with documentation for v12. All good now.

**Comment by sysmat** [comment]
maybe as suggestion in the changelog:  we removed `NgbCheckBox, NgbRadio, NgbRadioGroup`

**Comment by cah-jay-roever** [comment]
> maybe as suggestion in the changelog: we removed `NgbCheckBox, NgbRadio, NgbRadioGroup`

Is there any documentation around this change?  This has broken all my radios and caught me off guard when upgrading to Angular 14.

**Comment by maxokorokov** [comment]
@cah-jay-roever https://ng-bootstrap.github.io/releases/12.x/#/components/buttons/overview
