### ISSUE TITLE
Some tooltip and popover placements are not working as intended

### ISSUE THREAD

**Issue by Seveilith** [ng-bootstrap/ng-bootstrap#4369]
### Bug description:

Placements other than `top`, `bottom`, `left` and `right` are not working as intended for the popover and tooltip components. 
For instance, if you specify `top-left`, then the placement will be the same as `top`.

Note, I've also tried other directional properties such `top-start` in favor of `top-left`, which also resulted in the same outcome as above.

It was last working in v11:
https://stackblitz.com/edit/angular-h4rwfs?file=src%2Fapp%2Ftooltip-basic.html

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-d7cxo4?file=src%2Fmain.ts,src%2Fapp%2Ftooltip-basic.html

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 14.1.0

ng-bootstrap: 13.0.0

Bootstrap: 5.20

Popper: 2.10.2

**Comment by fbasso** [comment]
Thanks for reporting an issue, @Seveilith.

Interesting. I didn't understand what's happen yet, but I noticed it works in this use case:
https://stackblitz.com/edit/angular-ab99w7?file=src%2Fapp%2Ftooltip-autoclose.html

**Comment by bamboechop** [comment]
Any update on this? Did some investigation happen? I've encountered this exact issue after updating from v11 to v14 during a big dependency update to get a project up to date again and now I get complaints that the tooltips look wrong.

**Comment by bastienmoulia** [comment]
When I run it in local, I have the tooltip placed correctly but without the margin:
<img width="901" alt="image" src="https://github.com/ng-bootstrap/ng-bootstrap/assets/686196/a69dce2d-582d-4636-85b4-8104486296bb">

When I use the stackblitz, I have the bug:
<img width="803" alt="image" src="https://github.com/ng-bootstrap/ng-bootstrap/assets/686196/972930bf-e6d6-4224-8c9c-3f6d41a02e98">
https://angular-pmqwdh.stackblitz.io
