### ISSUE TITLE
NgbTypeahead: select on exact value

### ISSUE THREAD

**Issue by mibart** [ng-bootstrap/ng-bootstrap#4371]
Hello,

I am missing the "select-on-exact" TypeAhead feature from ui-bootstrap. 
I can´t see how to replicate the behavior with the given directives. 

I also found no open or closed issues regarding this.

The user should be allowed to type the exact value, without the need to select it from the list if [editable]=false is set.

Angular: 14

ng-bootstrap: 13

Bootstrap: 5.2

**Comment by maxokorokov** [comment]
So I guess you mean it would select the model automatically if there is only one matching entered text without hitting <kbd>Enter</kbd> or clicking for selection. I'd say it is a missing feature.

For reference:
- https://angular-ui.github.io/bootstrap/#!#typeahead
- `typeahead-select-on-exact` $ (Default: false) - Automatically select the item when it is the only one that exactly matches the user input.

**Comment by mibart** [comment]
Is this still a thing?
