### ISSUE TITLE
Modal 'show' classes not added to modal triggered from third-party click event.

### ISSUE THREAD

**Issue by capesean** [ng-bootstrap/ng-bootstrap#4376]
### Bug description:
I'm using Angular Fusion Charts to create a chart, and then want to open a modal window when the user clicks on an item in the chart. However, when the modal opens, it doesn't have the `show` classes applied to the window nor the backdrop. See:

![image](https://user-images.githubusercontent.com/642609/184339790-118355fe-327f-4238-8b80-d7acbe86ebc2.png)

I have tracked this down to this point of the ngbootstrap code:

![image](https://user-images.githubusercontent.com/642609/184343694-9cae727d-4946-4670-adbb-19ba2c18bad6.png)

When the click event is triggered from within the FusionChart, the `zone` is **stable**, but when it's triggered normally from outside, the `zone` is not stable. In the first case, this presumably means that the `onStable` EventEmitter will not fire, and thus not add the `show` modal classes. 

I don't know if this is an issue with ngbootstrap or fusioncharts but I had to post somewhere to start. I'm trying to dig deeper but am not sure what else to do from here - if someone could guide me that would be great.

### Link to minimally-working StackBlitz that reproduces the issue:

I have tried getting a StackBlitz/CodeSandbox to work but it's incredibly temperamental with package versions and whatnot. Here are some attempts (that need tweaking):

https://codesandbox.io/s/vigorous-moon-ebi7s6?file=/package.json

https://stackblitz.com/edit/angular-ivy-pfjafu?file=package.json

Here's a StackBlitz forked from the modal demo, but as soon as I add the fusioncharts then I get a CORS issue:
https://stackblitz.com/edit/angular-gkv5fq
 
### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 13.3.11

ng-bootstrap: 12.1.2

Bootstrap: 5.1.3

**Comment by jnizet** [comment]
My guess is that the problem is that since Angular FusionCharts creates the chart outside of the Angular zone (see https://github.com/fusioncharts/angular-fusioncharts/blob/develop/src/angular-fusioncharts/src/fusioncharts.component.ts#L476). 

Try changing your event handling code from

```ts
doSomething()
```

to 

```
this.zone.run(() => doSomething());
```

If that doesn't work, providing a repro (as an attached zip file for example) would help.

**Comment by capesean** [comment]
That works perfectly, thank you.
