### ISSUE TITLE
ngb-accordion not applying type

### ISSUE THREAD

**Issue by ianfd** [ng-bootstrap/ng-bootstrap#4383]
### Bug description:

ngb-accordion component is not applying the type attribute to the style. None of the in the code mentioned types are working on the accordion. (Tried this with a fresh version of angular as well, no luck there either.) (only had the possibility to test this on macOS)

### Link to minimally-working StackBlitz that reproduces the issue:

https://angular-d3xtzv.stackblitz.io

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 14.1.0

ng-bootstrap: 13.0.0

Bootstrap: 5.2.0

**Comment by maxokorokov** [comment]
This is broken at the moment, we missed this during Bootstrap 5 migration.
However, we will not fix this one, there will be a new accordion based on directives in `14.1.0` → #4437
