### ISSUE TITLE
Rating component with  Custom decimal template does not work in Android Chrome

### ISSUE THREAD

**Issue by johnxjcheng** [ng-bootstrap/ng-bootstrap#4391]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
I found the rating component not working in my code when testing on Android Chrome. So, I used the same Android Chrome browser to open this demo page https://ng-bootstrap.github.io/#/components/rating/examples. Go to the section that demos 
Custom decimal rating. I found it's not working. It shows full red hearts, and won't allow clicking. 

### Link to minimally-working StackBlitz that reproduces the issue:
https://ng-bootstrap.github.io/#/components/rating/examples.

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 13.3.0

ng-bootstrap: 10.0.0

Bootstrap:

**Comment by maxokorokov** [comment]
Hey, two points:
1. It's normal that it is only readable, you cannot set a decimal rating
2. maybe try using some kind of icon, instead of the `hearts` symbol in the demo. Here is an example with font-awesome → 
https://stackblitz.com/edit/angular-ydx1ms?file=src%2Findex.html,src%2Fapp%2Frating-decimal.html,src%2Fapp%2Frating-decimal.ts

**Comment by maxokorokov** [comment]
We should probable update demos to use some icons instead. Maybe inline, maybe bootstrap icons

**Comment by johnxjcheng** [comment]
Hey,
I just want to bring to your attention that the reported bug is in the Android version of Chrome only. On PC it works fine.
________________________________
