### ISSUE TITLE
Open modal with specific size in pixels

### ISSUE THREAD

**Issue by jorgearmandooc** [ng-bootstrap/ng-bootstrap#4392]
exists a method to pass specific size in pixels to de modal service to open? Now only allow sm, lg etc, but not in pixels

**Comment by maxokorokov** [comment]
You can always use a custom modal class, like this → https://stackblitz.com/edit/angular-ohdgpk?file=src%2Fapp%2Fmodal-basic.ts,src%2Fapp%2Fmodal-basic.html,src%2Findex.html
