### ISSUE TITLE
Ability to have an Accordion panel as a child Component

### ISSUE THREAD

**Issue by PinkDraconian** [ng-bootstrap/ng-bootstrap#4405]
### Feature request description:
I'd like to have an accordion that has panels, which are child components. 
The reason is that I want to easily be able to change the title and contents based on certain events.

I see that in the source, the accordion only looks for the children down one level, and adding a component in between adds a level. Is this something that can somehow be overcome?

**Comment by maxokorokov** [comment]
We've been redoing the accordion based on directives, it will be a part of `14.1.0`.
However I don't understand why you need components and StackBLitz doesn't really illustrate the need in components. The part with `I want to easily be able to change the title and contents based on certain events` is not clear at all.

You can just use the data model for the display. Could you please either provide a more detailed explanation or a different stackblitz?

**Comment by maxokorokov** [comment]
Closing as no response, please reopen if necessary.

**Comment by ShaCP** [comment]
I am trying to do this as well. I'm on ng-bootstrap 11 and bootstrap 4.6 (cannot upgrade currently). I am currently refactoring a massive component and would like to make each panel its own separate component. The thread creator's example illustrates what I'm trying to do, it doesn't work for me with either. Any ideas how this might be done?
