### ISSUE TITLE
Ngb modal backdrop does not fit the screen on mobile

### ISSUE THREAD

**Issue by EmiAguero1997** [ng-bootstrap/ng-bootstrap#4407]
Hello guys, i just find out the solution for this problem.

This is how the problem looks: 
<img width="389" alt="Screenshot 2022-10-21 123650" src="https://user-images.githubusercontent.com/84792585/197234448-e36684ff-26c1-4135-a37c-d2bf5b2091fe.png">

SOLUTION:

Results that ngb modal lets you use a custom backdrop class
<img width="597" alt="Screenshot 2022-10-21 122430" src="https://user-images.githubusercontent.com/84792585/197232286-7157cdb8-d670-4a9c-b839-c5d0c86d1f5b.png">

So it means that you can use width:100% and height:100% in your custom backdrop class, this fixes the problem (u have to set a background-color)
<img width="571" alt="Screenshot 2022-10-21 122505" src="https://user-images.githubusercontent.com/84792585/197232838-49e06631-df33-4235-9df7-38e529bb701d.png">

This is my custom backdrop class:
`.backdropCustom{
        background-color: rgb(79, 79, 79);
        width: 100%;
        height: 100%;
    }`

And this is how i open the modal:

`this.modalService.open(this.loginModal,{backdropClass:'backdropCustom', centered:true});`

This is the final result:

<img width="551" alt="Screenshot 2022-10-21 123123" src="https://user-images.githubusercontent.com/84792585/197233341-58b1948a-bde8-457d-9b23-5c00e6f82001.png">

_Originally posted by @EmiAguero1997 in https://github.com/ng-bootstrap/ng-bootstrap/issues/3408#issuecomment-1287127067_

**Comment by maxokorokov** [comment]
Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz

**Comment by maxokorokov** [comment]
Closing as no response, please reopen if necessary.
