### ISSUE TITLE
Incorrect tooltip position when CSS zoom property is not 1

### ISSUE THREAD

**Issue by MichalJakubeczy** [ng-bootstrap/ng-bootstrap#4415]
### Bug description:
Tooltip is incorrectly positioned when page has CSS property zoom level different than 1 and tooltip has container set to body.

### Link to minimally-working StackBlitz that reproduces the issue:
https://angular-17dnbc.stackblitz.io/
https://stackblitz.com/edit/angular-17dnbc

Scroll a bit in working example to see that tooltip which has container set to body is misplaced.

### Versions of Angular, ng-bootstrap and Bootstrap:
Angular: 14.2.9

ng-bootstrap: 13.1.0

Bootstrap: 5.2.0

**Comment by jnizet** [comment]
Here's the first thing MDN says about zoom:

> Non-standard: This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

**Comment by MichalJakubeczy** [comment]
@jnizet yes, I am aware of this. 

Anyway, in our application not accessible to the world-wide audience it is good solution to use zoom. So the question is whether you're planning to deal with this somehow in ngbtooltip? 

If not, I understand your reasons and choose another tooltip provider. If yes, it would be good to us and we'll stay with ngbtooltip.

**Comment by maxokorokov** [comment]
At this point we use popper for positioning. I would suggest fix it with popper, but the suggested solution on their side is https://github.com/floating-ui/floating-ui/issues/496#issuecomment-565826889

So fixing the offset yourself with [popper options api](https://ng-bootstrap.github.io/#/components/popover/examples#options) would be the solution to me.
