### ISSUE TITLE
ERROR TypeError: this._applicationRef.attachView is not a function

### ISSUE THREAD

**Issue by RaghavendraNK** [ng-bootstrap/ng-bootstrap#4426]
### Bug description:
Getting ERROR TypeError: this._applicationRef.attachView is not a function

Angular: 13.2.7

ng-bootstrap: 11.0.1

Bootstrap: 5.2.3

Even tried with: ng-bootstrap [12.0.1](https://www.npmjs.com/package/@ng-bootstrap/ng-bootstrap/v/12.0.1)
[12.0.0](https://www.npmjs.com/package/@ng-bootstrap/ng-bootstrap/v/12.0.0) but the same issue exist.

![image](https://user-images.githubusercontent.com/8822120/203285459-17eda6f3-8531-4acf-9836-2943c8eec7f3.png)

**Comment by maxokorokov** [comment]
Doesn't look like an issue with ng-bootstrap, you're literally the first person to report this issue.

Will need a minimal reproduction scenario in some form, please.

**Comment by maxokorokov** [comment]
Closing as no response, please reopen if necessary.
