### ISSUE TITLE
ng-bootstrap is not supported by angular version 14.2.0

### ISSUE THREAD

**Issue by Mohammadhussain257** [ng-bootstrap/ng-bootstrap#4429]
### Bug description:

**While doing npm i @ng-bootstrap/ng-bootstrap I got this following error:**

```
npm ERR! Could not resolve dependency:
npm ERR! @ng-bootstrap/ng-bootstrap@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/core@14.2.12
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"14.2.12" from @angular/forms@14.2.12
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Versions of Angular, ng-bootstrap:

Angular: 14.2.0

ng-bootstrap:13.1.1

**Comment by hugo1707** [comment]
Same problem

**Comment by Mohammadhussain257** [comment]
I hope they will fixed soon

**Comment by benmesza** [comment]
Same problem

**Comment by rottifant** [comment]
I had the same problem, but when I installed it anyway (with npm i --force) it works just fine. ;)

**Comment by maxokorokov** [comment]
We have `^14.1.0` as a peer dependency → https://github.com/ng-bootstrap/ng-bootstrap/blob/13.1.1/src/package.json#L43-L48

Everything works fine if you do `ng new` we cli `14.2.10` and then `ng add @ng-bootstrap/ng-bootstrap@13.1.1` on my side. With node `16` and npm `8.5`.

Doesn't look like an ng-bootstrap issue, please check your package.json, clean the cache, reinstall, the usual...
