### ISSUE TITLE
Change background color of calendar header for dark mode

### ISSUE THREAD

**Issue by bastienmoulia** [ng-bootstrap/ng-bootstrap#4438]
### Bug description:

I'm testing ng-bootstrap with the dark mode of bootstrap 5.3.

There is an issue in the calendar header because the style is `background-color: var(--bs-light);` and the bs-light variable is not override in dark mode.

We can use `background-color: rgba(var(--bs-body-color-rgb), 0.03);`

It's not exactly the same color: #f8f9fa => #f8f8f8

### Link to minimally-working StackBlitz that reproduces the issue:

Original: https://stackblitz.com/edit/angular-yhzr1g-sr7ahd?file=src%2Findex.html,src%2Fmain.ts

Proposal fix: https://stackblitz.com/edit/angular-yhzr1g?file=src/index.html

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 15.0.2

ng-bootstrap: 14.0.0-rc1

Bootstrap: 5.3.0-alpha1

**Comment by maxokorokov** [comment]
Fixed in #4554 → https://github.com/ng-bootstrap/ng-bootstrap/pull/4554/files#diff-d4928ee38d802a7c9cb2e222a9624a3009640378648828715d00740edf5a7776
