### ISSUE TITLE
If the Modal content is a class that injects a service in Ang15, modals fail with NullInjectorError

### ISSUE THREAD

**Issue by crumhorn** [ng-bootstrap/ng-bootstrap#4444]
### Bug description:

If the modal content is a class, and that class injects a service. The modal will not open and the console shows:

ERROR NullInjectorError: R3InjectorError(Environment Injector)[TestService -> TestService]:
  NullInjectorError: No provider for TestService!

The only way I've gotten it to work is if the service declares @Injectable({providedIn: 'root'}). Which I do not want. 

Setting the providers on a module level doesn't seem to matter as the service is not found.

### Link to minimally-working StackBlitz that reproduces the issue:

[https://stackblitz.com/edit/angular-rx7799](https://stackblitz.com/edit/angular-rx7799)

Press the first button to see a modal that works, the supplied content does not inject a service.
Press the second button to see the failure, look in the console for the error.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:
15.0.3

ng-bootstrap:
14.0.0

Bootstrap:
5.2.3

**Comment by crumhorn** [comment]
I realized if the bootstrapApplication supplies the service in the options under providers it works, for some reason it still doesn't work in my project, will reopen when I have better details.

**Comment by liuyankit** [comment]
+1, documentation is uncleared. I follow exact step to inject the modal `modal = inject(NgbActiveModal)` but got this error
