### ISSUE TITLE
Injected services in content get re-instantiated in Ang 15 (Modal dialogs)

### ISSUE THREAD

**Issue by crumhorn** [ng-bootstrap/ng-bootstrap#4445]
**Bug description:**
If the modal content is a class, and that class injects a service. That service will be re-created regardless of its "scope".

**Link to minimally-working StackBlitz that reproduces the issue:**

https://stackblitz.com/edit/angular-rx7799

Open the console, just loading the application you should see "Service created. I should only exist once.".

Press the second button and look at the console. The message that the service is created comes again.

**Versions of Angular, ng-bootstrap and Bootstrap:**
**Angular:**
15.0.3

**ng-bootstrap:**
14.0.0

**Bootstrap:**
5.2.3

**Comment by MoxxiManagarm** [comment]
I believe my issue connected to this issue.

When upgrading to ng-bootstrap 14.0.0 (Angular 15) I get static injection errors for the services. Those services are not provided in root, which is different to the stackblitz example above. Changing all services to `providedIn: 'root'` is not an option for me.

**Comment by crumhorn** [comment]
@MoxxiManagarm My finding to this bug was also based on [lazy loaded] modules with "local" services (I believe that's providedIn: 'any' under the new Ang15 changes), which has exactly the same problems. It took some time to figure out what was going on, and then I narrowed it down to that even with providedIn: 'root', it's still an issue as the service is re-created when the content that injects it is somehow managed by the Modal service.

**Comment by MoxxiManagarm** [comment]
@crumhorn  I think I found a solution. I digged a little bit in the code and I found this 

![image](https://user-images.githubusercontent.com/45840741/207929525-27eb1613-ff41-4dd5-bd35-5f82c6414ced.png)

Have a look on line 99. I actually tried extending the options in your stackblitz and it seems to work

https://stackblitz.com/edit/angular-rx7799-setfqo?file=src/app/modal-options.ts

Can you confirm?

**Comment by crumhorn** [comment]
@MoxxiManagarm Indeed, that does seem to work on stackblitz, and then the providedIn: 'root' can be taken out. However, on my large project it doesn't work (I use lazy modules), I need to figure out what the difference is. The Injector is from angular so it's not a singleton, so if that was a problem it would definitely show up on stackblitz as well. I'll update when I find out more.

Does it work on your project with lazy loaded modules as well?

**Comment by crumhorn** [comment]
Ok, an update.

So it seems something is not correct with where the provider is defined under Ang15 or I'm going crazy. Up to now on my big project, I've been using providers on the module level for each lazy module, that "provides" all my services, providers: [blah, blah blah]. That doesn't work in conjunction with providing the injector to the Modal opener once inside the lazy module in the views, but, if I move the provider up to the view class that opens the dialog rather than declaring it on the module, then it works... 

Considering the module should be the "root" level place to provide a provider declaration, rather than on a sub-level, this seems like a bug somehow. I have to do a deep think. I'm also curious why this suddenly changed from Ang14->Ang15 or with ng-bootstrap.

**Comment by MoxxiManagarm** [comment]
> I'm also curious why this suddenly changed from Ang14->Ang15 or with ng-bootstrap

Yes, indeed. It makes the update really breaking. It would be helpful to have a note on that in the change notes.

> Does it work on your project with lazy loaded modules as well?

I am just done with upgrading ng-bootstrap again on my branch to update the app, including the injector changes. I am not getting injection errors, everything seems to be fine, at least for now ;-) I am injecting the injector in every component or service calling NgbModal::open.

**Comment by crumhorn** [comment]
I'm gonna close this as not a bug. It seems my understanding of providedIn: 'root' was probably insufficient. Essentially, from what I gather, Angular (at least latest version(s)) will figure out that if your service is declared as 'root' under a lazy module, and is only used there, then that sercvice will only be the root for that lazy module, and not global. This also makes the "bug" work. 

The other option, as @MoxxiManagarm pointed out, is that you can supply your injector to the creation of the modules. For me, this worked for a single dialog, but if that dialog opened a content-based sub-dialog that also injects the service, I would need to supply the same injector onwards or I would again run into issues.

Thus, TL;DR. Use providedIn: 'root' for your "global services even if just in one lazy module" or pass the Injector along.

**Comment by JohnnyDevNull** [comment]
@crumhorn every lazy loaded modul has it's own root injector. That's the default.
So if you provide a service on a lazy loaded module you would even get a separate instance if you set it to provided in root but still provide it in the modules providers array.
