### ISSUE TITLE
Regression: modal components don't have the correct injector

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#4447]
### Bug description:

Since version 14, a component used as the modal content doesn't have the correct injector anymore.

If a lazy loaded module defines a provider for a service and a component from that module is used as a modal content and tries to get the service via DI, a `NullInjectorError` is thrown when opening the modal.

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/github/jnizet/modal-repro/tree/ngb14

This repro is also available on github: https://github.com/jnizet/modal-repro

The `main` branch shows the code working with ng-bootstrap 13, and the `ngb14` branch shows the same code not working with ng-bootstrap 14.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 15.0.4

ng-bootstrap: 14.0.0

Bootstrap: 5.2.3

**Comment by stefanwaldhauser** [comment]
I have the same problem. Does somebody know of a hotfix for this problem?

**Comment by krusche** [comment]
We have the same problem and would appreciate a fix

**Comment by egdw-nipra** [comment]
This really needs more attention. v.14.0.0 is currently completely broken for anyone using lazy loaded modules.

**Comment by maxokorokov** [comment]
Indeed, I think I've screwed up two things:

1. Modal content creation

https://github.com/ng-bootstrap/ng-bootstrap/blob/7f2146d84822eb1870f5a141626f261d1ecc5799/src/modal/modal-stack.ts#L234-L241

I think `environmentInjector` should be `contentInjector.get(EnvironmentInjector, null) || this._applicationRef.injector` (not 100% sure about this)

2. NgbModalModule

https://github.com/ng-bootstrap/ng-bootstrap/blob/7f2146d84822eb1870f5a141626f261d1ecc5799/src/modal/modal.module.ts#L8-L9

It should provide `NgbModal`, so `@NgModule({providers: [NgbModal]})`


I'll open a PR ASAP

**Comment by jnizet** [comment]
If NgbModal needs to be provided by NgbModalModule for this bug to be fixed, does it mean that standalone components should have it in their `providers` if they don't import the `NgbModalModule`? If so, it would be worth documenting it.

**Comment by jcalijurio** [comment]
I have the same problem here too.

**Comment by maxokorokov** [comment]
@jnizet I've opened the PR
I think we should simply provide `NgbModal` both in `NgbModalModule` and in `'root'`. I didn't manage to reproduce this issue with standalone components

**Comment by jnizet** [comment]
Thanks for the fix and for the release @maxokorokov. Works fine here.

**Comment by dkaczor97** [comment]
@maxokorokov I think the same problem still exists in Offcanvas, I cannot inject services provided by lazy loaded module
