### ISSUE TITLE
Bootstrap 5.3 and dark mode for docs

### ISSUE THREAD

**Issue by bastienmoulia** [ng-bootstrap/ng-bootstrap#4450]
Bootstrap 5.3 alpha 1 was release https://blog.getbootstrap.com/2022/12/24/bootstrap-5-3-0-alpha1/ so it will be nice to have a doc with dark mode to test the components.

[EDIT] Bootstrap 5.3 is out of alpha now https://blog.getbootstrap.com/2023/05/30/bootstrap-5-3-0/

**Comment by vladkasianenko** [comment]
Looking forward to see it in action!

**Comment by flavianoredressa** [comment]
Any news about it? bs 5.3 was released
