### ISSUE TITLE
NgbNavbar is not documented

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#4462]
### Bug description:

For dropdowns to look correctly inside a collapsed navbar, the `NgbNavbar` directive is necessary. It's automatically applied when importing `NgbDropdownModule` (because its selector is simply `.navbar`), but when using standalone components, it's far from obvious that this directive needs to be imported, since it's not even documented.

**Comment by bastienmoulia** [comment]
Demo: https://stackblitz.com/edit/angular-pzelbe?file=src%2Fapp%2Fdropdown-navbar.ts

Should we  import `NgbNavbar` in `NgbDropdown`?

**Comment by maxokorokov** [comment]
Maybe simply replace it with `closest()`?

This is literally the only place it is used for:

https://github.com/ng-bootstrap/ng-bootstrap/blob/25f23198b936c54b9cf75bca1cb141189ae5c8c3/src/dropdown/dropdown.ts#L260
