### ISSUE TITLE
Schematic creates import with tilde (~) path by default

### ISSUE THREAD

**Issue by janopae** [ng-bootstrap/ng-bootstrap#4463]
The first thing I encountered after installing ng-bootstrap was the following error:

```
./src/styles.scss - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
4 │ @use '~bootstrap/scss/bootstrap';
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/styles.scss 4:1  root stylesheet

```

After searching about this on the Internet I found that Angular seems to have stopped supporting tilde paths: https://github.com/angular/components/commit/f2ff9e31425f0e395e6926bcaf48f876688000d8

According to https://webpack.js.org/loaders/sass-loader/#resolving-import-at-rules, you can just remove the tilde, and it will still work. I removed the tilde in my project, and it works now.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 15.0.4

ng-bootstrap: 14.0.0

Bootstrap: 5.2.3

**Comment by maxokorokov** [comment]
Thanks for reporting this, will be fixed with `14.0.1`
