### ISSUE TITLE
StackBlitz Demo Links on Documentation Page are not running on StackBlitz 

### ISSUE THREAD

**Issue by pvlastaridis** [ng-bootstrap/ng-bootstrap#4470]
### Bug description:
StackBlitz Demos are not running

### Link to minimally-working StackBlitz that reproduces the issue:

Just visit any StackBlitz link on Ng-Bootstrap page

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 15.1.0

ng-bootstrap: 14.01

Bootstrap: 5.2.3

**Comment by bastienmoulia** [comment]
Looks like something change with `@angular/compiler-cli@15.1.0`. It's working when using `@angular/compiler-cli@15.0.0`.
