### ISSUE TITLE
Page freeze when modal close

### ISSUE THREAD

**Issue by jantvb** [ng-bootstrap/ng-bootstrap#4493]
When the modal is closed the entire page freezes. This happens from the ng-bootstrap version 8.0.0 for Angular

**Comment by maxokorokov** [comment]
Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz

Also please try a newer `ng-bootstrap` version

**Comment by maxokorokov** [comment]
Closing as no response, please reopen if necessary.
