### ISSUE TITLE
Is this component library not able to be loaded on demand? 

### ISSUE THREAD

**Issue by Huansheng1** [ng-bootstrap/ng-bootstrap#4495]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

Is this component library not able to be loaded on demand? In order to reduce the package size, I got an error when referencing it as follows

```ts
import { NgbAlertModule } from '@ng-bootstrap/ng-bootstrap/alert/alert.module';
import { NgbDatepickerModule } from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module';
import { NgbDateStruct } from '@ng-bootstrap/ng-bootstrap/datepicker/ngb-date-struct';
import { NgbDatepickerI18n } from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-i18n';
```

error，eg:
```bash
./src/app/shared/date-picker/date-picker.component.ts:8:0-78 - Error: Module not found: Error: Package path ./timepicker/timepicker.module is not exported from package C:\Users\ ted\Desktop\code\ui-mobile-mall\node_modules\@ng-bootstrap\ng-bootstrap (see exports field in C:\Users\ted\Desktop\code\ui-mobile-mall\node_modules\@ng-bootstrap\ng-bootstrap\package.json)
```

### Link to minimally-working StackBlitz that reproduces the issue:

 [demos](https://stackblitz.com/edit/angular-3uqnka?file=src/app/accordion-basic.module.ts)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:13.3.11

ng-bootstrap:12.1.2

Bootstrap:5.0.0

**Comment by maxokorokov** [comment]
@Huansheng1, it can be, just import from `@ng-bootstrap/ng-bootstrap`

https://ng-bootstrap.github.io/#/getting-started#imports
