### ISSUE TITLE
No directive found with exportAs 'NgbAccordion'.

### ISSUE THREAD

**Issue by vladkasianenko** [ng-bootstrap/ng-bootstrap#4504]
![image](https://github.com/ng-bootstrap/ng-bootstrap/assets/14053728/02e29ee2-3290-4007-8678-4a4e7f211811)
![image](https://github.com/ng-bootstrap/ng-bootstrap/assets/14053728/a962defd-255d-488f-a0be-01df5d819007)

Angular 15.2.2
NGB: 14.1.0

**Comment by maxokorokov** [comment]
Should be `ngbAccordion`:

https://github.com/ng-bootstrap/ng-bootstrap/blob/c52438414368d7806a4b327975ed683d8ea3625e/src/accordion/accordion.directive.ts#L313-L318

Is there a question here?

**Comment by vladkasianenko** [comment]
Yes, it helps, thank you!
