### ISSUE TITLE
dont work ng add @ng-bootstrap/ng-bootstrap command

### ISSUE THREAD

**Issue by Drelaky** [ng-bootstrap/ng-bootstrap#4513]
### Bug description:
When I enter this code:
ng add @ng-bootstrap/ng-bootstrap

how to solve my problem?

Then I get this error message:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: karma-jasmine-html-reporter@2.0.0
npm ERR! Found: jasmine-core@5.0.0
npm ERR! node_modules/jasmine-core
npm ERR! dev jasmine-core@"~5.0.0" from the root project
npm ERR!
npm ERR! Failed to resolve the dependency:
npm ERR! peer jasmine-core@"^4.0.0" from karma-jasmine-html-reporter@2.0.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR! dev karma-jasmine-html-reporter@"~2.0.0" from the root project
npm ERR!
npm ERR! Conflicted codependency: jasmine-core@4.6.0
npm ERR! node_modules/jasmine-core
npm ERR! peer jasmine-core@"^4.0.0" from karma-jasmine-html-reporter@2.0.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR! dev karma-jasmine-html-reporter@"~2.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict or try again.
npm ERR! this command with --force or --legacy-peer-deps.
npm ERR! to accept an incorrect (and potentially incorrect) dependency resolution.
npm ERR!
npm ERR! For the full report, see C:\Users\Drelaky\AppData\Local\npm-cache\resolve-report.txt.

npm ERR! The full log of the run can be found at:
npm ERR! C:\Users\Drelaky\AppData\Local\npm-cache_logs\2023-05-28T13_50_15_849Z-debug-0.log
✖ Installation of packages failed, see above.

![image](https://github.com/ng-bootstrap/ng-bootstrap/assets/53569746/dcd55b09-cc14-4422-848c-d4bcb09fb2f7)
![image](https://github.com/ng-bootstrap/ng-bootstrap/assets/53569746/897a8648-eaa2-4716-8056-d5e12c9b3901)
![image](https://github.com/ng-bootstrap/ng-bootstrap/assets/53569746/75108a3b-13c7-4422-947c-c6f7535f42d9)

### Link to minimally-working StackBlitz that reproduces the issue:

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 16.0.3

ng-bootstrap: v15.0.0

Bootstrap: latest

**Comment by Drelaky** [comment]
Update:
If I don't update jasmine-core everything is perfect. Everything else is on the latest version.

**Comment by maxokorokov** [comment]
Not sure we can do anything, please see something like #4454 or similar.
Looks like npm versioning issue with jasmine. We don't even have it as a dependency in ng-bootstrap → https://unpkg.com/browse/@ng-bootstrap/ng-bootstrap@15.0.0/package.json
