### ISSUE TITLE
refactor: stick to one flavours of form / migrate to new forms

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#454]
As of today we are importing from the old forms and the PR in progress for the typeahead is using new ones. We need to switch the whole thing to the new forms.

**Comment by maxokorokov** [comment]
> the typeahead is using new ones

Not really, all includes are from `@angular/common`, not from `@angular/forms` and I tested it with old forms

On the topic I think it might be more logical to migrate to new forms by default once the `rc.5` is out

**Comment by pkozlowski-opensource** [comment]
> On the topic I think it might be more logical to migrate to new forms by default once the rc.5 is out

@maxokorokov makes sense, let's delay it till after rc.5

**Comment by pkozlowski-opensource** [comment]
Fixed via 0707a772668f3f01e53cb14bded62db91c9443c6
