### ISSUE TITLE
NgbAccordionDirective: [destroyOnHide]="false" not working

### ISSUE THREAD

**Issue by gman56** [ng-bootstrap/ng-bootstrap#4541]
### Bug description:
Setting [destroyOnHide]="false" on the ngbAccordion directive does not prevent the items from being removed from the DOM.

### StackBlitz:
https://stackblitz.com/edit/angular-cj5vcs?file=src%2Fapp%2Faccordion-basic.html

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 16.0.6

ng-bootstrap: 15.1.0

Bootstrap: 5.2.3

**Comment by maxokorokov** [comment]
@ValentinNelu, can you take a look at this if you have some time before I do?

I don't see how this can work, this should at least be in `ngOnInit`, better as a dynamic getter in places where we actually need the value:

https://github.com/ng-bootstrap/ng-bootstrap/blob/107bbbd41c6d2c837ef1d80dcd07f42719b194a0/src/accordion/accordion.directive.ts#L232

And clearly we're missing some tests for `destroyOnHide` combinations.

@gman56, indeed, we'll fix it in `15.1.1`, meanwhile the workaround is to apply this to individual items as it is done in the demo → https://ng-bootstrap.github.io/#/components/accordion/examples#keep-content
