### ISSUE TITLE
*ngIf inside `ngbAccordionBody` prints multiple times

### ISSUE THREAD

**Issue by anuj9196** [ng-bootstrap/ng-bootstrap#4544]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
Adding `*ngIf` inside `ngbAccordionBody` prints the same content multiple times.

```html
<div ngbAccordion>
    <div ngbAccordionItem *ngFor="let filter of filterConfiguration">
        <h2 ngbAccordionHeader>
	    <button ngbAccordionButton>{{filter.label}}</button>
        </h2>
        <div ngbAccordionCollapse>
            <div ngbAccordionBody>
                <ng-container *ngIf="filter.type == 'input-select'">
                    Hello
                </ng-container>
                <ng-container *ngIf="filter.type == 'input-date'">
                    World
                </ng-container>
            </div>
        </div>
    </div>
</div>
```

<img width="960" alt="Screenshot 2023-07-30 at 3 47 45 PM" src="https://github.com/ng-bootstrap/ng-bootstrap/assets/6560085/34a28691-66a4-4dab-803d-f509c65b3961">

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-4ekn3t?file=src%2Fapp%2Faccordion-basic.html

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 16.1

ng-bootstrap: 15.1

Bootstrap: 5.2.3

**Comment by maxokorokov** [comment]
@anuj9196, you're missing `<ng-template>` in the markup:

```html
<div ngbAccordionBody>
  <ng-template>
    <ng-container *ngIf="filter.type == 'input-select'">
      Hello
    </ng-container>
    <ng-container *ngIf="filter.type == 'input-date'">
      World
    </ng-container>
  </ng-template>
</div>
```
