### ISSUE TITLE
Does Bootstrap support Angular 16.1.7?

### ISSUE THREAD

**Issue by jeffwji** [ng-bootstrap/ng-bootstrap#4546]
I'm trying to install the latest version of Bootstrap to my Angular project. but when I run the command:

```
ng add @ng-bootstrap/ng-bootstrap
```

It failed with:

```
npm ERR! Conflicting peer dependency: @angular/core@16.1.7
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"16.1.7" from @angular/forms@16.1.7
npm ERR!   node_modules/@angular/forms
npm ERR!     @angular/forms@"^16.1.0" from the root project
npm ERR!     peer @angular/forms@"^16.0.0" from @ng-bootstrap/ng-bootstrap@15.1.0
npm ERR!     node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!       @ng-bootstrap/ng-bootstrap@"15.1.0" from the root project
```

I checked the support list, Bootstrap 15 only supports to Angular 6.0.x. I'm wondering what impact will be encountered if i force to apply it?

**Comment by imaksp** [comment]
you can use any 16.x version.

**Comment by maxokorokov** [comment]
Please see earlier issues about this.

It does support `16.x`, here is the actual `package.json` → https://unpkg.com/browse/@ng-bootstrap/ng-bootstrap@15.0.0/package.json

Here is it is in the source code → https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/package.json

Closing as duplicate #4498, #4454, #4419, #4404, etc
