### ISSUE TITLE
Scrollbars for Offcanvas opening a component

### ISSUE THREAD

**Issue by guethb** [ng-bootstrap/ng-bootstrap#4549]
### Bug description:
When using offcanvas to open a component directly, there is no scrollbar displayed, even if the content exceeds the space on the offcanvas-body.

An offcanvas opened by using an ng-template shows up with scrollbars on the offcanvas-body.

### Link to minimally-working StackBlitz that reproduces the issue:
No scrollbars by passing a component
https://stackblitz.com/edit/angular-f6ldj9

Scrollbar when passing a template
https://stackblitz.com/edit/angular-bqblp1

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 16.0.4

ng-bootstrap: 15.0.0

Bootstrap: 5.3.0

**Comment by jnizet** [comment]
See https://github.com/ng-bootstrap/ng-bootstrap/issues/4397
