### ISSUE TITLE
Cannot set default Time Zone for ngbDatePicker

### ISSUE THREAD

**Issue by Joroooo** [ng-bootstrap/ng-bootstrap#4559]
### Bug description:

ngbDatePicker always adapts to current user TimeZone. So it might show different dates for different users from different countries

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 15.0.2

ng-bootstrap: 14.2.0

Bootstrap: 14.2.0

expected behavior : Should include some Native Adapter to ignore user local Time zone and use the one provided in the adapter

**Comment by jnizet** [comment]
This adapter already exists. See https://ng-bootstrap.github.io/#/components/datepicker/api#NgbDateAdapter

**Comment by Joroooo** [comment]
It does, but it returns only in Local Time Zone, not UTC

**Comment by jnizet** [comment]
https://ng-bootstrap.github.io/#/components/datepicker/api#NgbDateNativeUTCAdapter
