### ISSUE TITLE
Accordion directive has bug when attempting to break into sub components

### ISSUE THREAD

**Issue by stevensroczynski** [ng-bootstrap/ng-bootstrap#4561]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

ngb according directive gives bug when attempting to break into sub-components: TypeError: Cannot destructure property 'ngbCollapse' of 'this._collapse' as it is undefined.

for example: 

Parent component: 

<div ngbAccordion>
  <my-sub-component-accordion-item ngbAccordionItem"></my-sub-component-accordion-item >
</div>

Child component:

<div class="according-item">
  <h2 ngbAccordionHeader>
    <button class="accordion-button" ngbAccordionButton>Card Title</button>
  </h2>
  <div ngbAccordionCollapse>
    <div ngbAccordionBody>
      <ng-template>
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon
        officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf
        moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim
        keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur
        butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably
        haven't heard of them accusamus labore sustainable VHS.
      </ng-template>
    </div>
  </div>
</div>

### Link to minimally-working StackBlitz that reproduces the issue:

I can't even get a stackblitz to run this far as it gives me an error:

Error in /~/src/my-accordion-item//my-accordion-item.component.ts (15:19)
Unexpected token '<'

https://stackblitz.com/edit/stackblitz-starters-gvlsff?file=src%2Fmy-accordion-item%2Fmy-accordion-item.component.ts

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:

ng-bootstrap:

Bootstrap:

**Comment by maxokorokov** [comment]
Look, you're not even importing `ng-bootstrap` anywhere in the StackBlitz, I don't think your issue comes from the library. Your StackBlitz doesn't come from our docuementation site. And unfortunately I can't understand very much from your description either.

Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz

**Comment by maxokorokov** [comment]
Please reopen if you have a reproduction scenario and if still necessary.
