### ISSUE TITLE
Unable to upgrade ng bootstrap from 7 to version 14.0.0

### ISSUE THREAD

**Issue by akash91102** [ng-bootstrap/ng-bootstrap#4562]
### Bug description:
Here is my package.json. I am using angular version 15 but my bootstrap version is 7. when i am trying to upgrade to version 14, it is throwing error and tabs are not working properly if I use --force

### Versions of Angular, ng-bootstrap and Bootstrap:
"dependencies": {
    "@angular/animations": "^15.2.9",
    "@angular/cdk": "^15.2.9",
    "@angular/common": "^15.2.9",
    "@angular/compiler": "^15.2.9",
    "@angular/core": "^15.2.9",
    "@angular/forms": "^15.2.9",
    "@angular/platform-browser": "^15.2.9",
    "@angular/platform-browser-dynamic": "^15.2.9",
    "@angular/router": "^15.2.9",
    "@ng-bootstrap/ng-bootstrap": "^7.0.0",
    "@ng-select/ng-select": "^10.0.4",
    "@ngx-loading-bar/core": "^6.0.2",
    "@ngx-loading-bar/http-client": "^6.0.2",
    "@ngxs/logger-plugin": "3.7.2",
    "@ngxs/store": "3.7.2",
    "@popperjs/core": "^2.9.2",
    "ag-grid-angular": "^25.2.0",
    "ag-grid-community": "^25.2.1",
    "angular-split": "^5.0.0",
    "angular-user-idle": "^2.2.7",
    "bootstrap": "^5.0.1",
    "bootstrap-icons": "^1.5.0",
    "crypto-js": "^4.1.1",
    "file-saver": "^2.0.5",
    "jquery": "^3.6.0",
    "jqueryui": "^1.11.1",
    "moment": "^2.29.1",
    "moment-timezone": "^0.5.31",
    "ng-inline-svg": "^13.1.2",
    "ng2-pdf-viewer": "^7.0.2",
    "ngx-bootstrap": "^6.2.0",
    "rxjs": "~6.6.3",
    "source-map-explorer": "^2.5.2",
    "sweetalert2": "^11.3.0",
    "tslib": "^2.0.3",
    "uuid": "^8.3.1",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.2.8",
    "@angular/cli": "^15.2.9",
    "@angular/compiler-cli": "^15.2.9",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "^2.0.9",
    "@types/node": "^12.20.13",
    "codelyzer": "^0.0.28",
    "gzipper": "^7.1.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.4.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.6.0",
    "protractor": "^7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "4.9.5"
  },

**Comment by akash91102** [comment]
![image](https://github.com/ng-bootstrap/ng-bootstrap/assets/139742791/ac0e891a-4f66-4548-adea-645fbbcc87e1)
 show and active classes are not getting appended while navigating between tabs.

**Comment by maxokorokov** [comment]
I'm not sure how to help with this one. Going 7 → 14 at once has way too many breaking changes. Follow the release notes and go it gradually.

Please reopen if you have concrete issues with ng-bootstrap library itself.

---

Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz
