### ISSUE TITLE
Offcanvas opened via Component - Body doesn't scroll

### ISSUE THREAD

**Issue by majora2007** [ng-bootstrap/ng-bootstrap#4571]
### Bug description:

When opening an offcanvas drawer with a body that overflows, the scrollbar never appears. The images below were created on the demo site. Note: This only occurs when using a component, likely due to the extra node. 

![image](https://github.com/ng-bootstrap/ng-bootstrap/assets/735851/c7fd0639-491e-4a88-beb0-d1df43496272)
![image](https://github.com/ng-bootstrap/ng-bootstrap/assets/735851/ad237e2e-f76c-4d73-ada8-52ef874c6129)

### Link to minimally-working StackBlitz that reproduces the issue:

I took your example, changed what we pass in to induce a scroll. 
[https://stackblitz.com/edit/angular-rdhvry?file=src%2Fapp%2Foffcanvas-component.ts](https://stackblitz.com/edit/angular-rdhvry?file=src%2Fapp%2Foffcanvas-component.ts)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 16.2.7

ng-bootstrap: 15.1.1

Bootstrap: 5.3.1

**Comment by jnizet** [comment]
See https://github.com/ng-bootstrap/ng-bootstrap/issues/4397

**Comment by majora2007** [comment]
Thanks @jnizet that does work. Not sure how I missed that when searching for offcanvas issues. 

Would it be applicable to add this information to the documentation site?

**Comment by jnizet** [comment]
Yes, we should add it. But you could too. Would you be willing to open a PR?

**Comment by majora2007** [comment]
Yup, I'll take care of it. Was just asking if you'd be fine. I'll get it raised shortly.
