### ISSUE TITLE
Offset problem in tooltip using bootstrap 5.3.0

### ISSUE THREAD

**Issue by Edminsson** [ng-bootstrap/ng-bootstrap#4574]
### Bug description:
If i choose the first of the tooltip examples in Stackblitz and change the bootstrap version from 5.2.3 to 5.3.0 or 5.3.2 there seems to be a problem with the offset of the tooltips.
I think bootstraps made some changes in the padding for the .tooltip class in version 5.3.0.
But I guess that's why the recommended version of bootstrap is 5.2.3. for versions of ng-bootstrap >= 14.x.x 
It is not simply a question of appearence, if the element has a tooltip to the right and the cursor enters from the right then the tooltip does not always work properly.

[Example](https://stackblitz.com/edit/angular-sqovmg?file=src%2Findex.html)

**Comment by maxokorokov** [comment]
Yes, the offests have changed indeed in 5.3
We'll support Agnular 17 and Bootstrap 5.3 with next major version → ng-bootstrap 16

The fix for the mouse enter was done, just not released yet → https://github.com/ng-bootstrap/ng-bootstrap/pull/4564
