### ISSUE TITLE
ngbmodal Dragging feature not works inside iframe

### ISSUE THREAD

**Issue by maliniFrenzy** [ng-bootstrap/ng-bootstrap#4576]
HI,
If inside modal body, I have iframe. then I am unable to drag it.
Dragging only works on the modal header.

**Comment by jnizet** [comment]
Out of curiosity, which dragging feature are you talking about? I can't find anything in the NgbModal documentation about dragging modals. So if you use something other than ng-bootstrap to makes its dialogs draggable, the issue should probably be filed against that other thing.

**Comment by maxokorokov** [comment]
Closing as no response, please reopen if necessary.
