### ISSUE TITLE
timepicker: support disabled and readonly states

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#458]
We need to find right semantics (shell we disable _all_ controls? what is the difference between disabled and readonly?).

Tests are essentials. 

Refs:
* https://github.com/angular-ui/bootstrap/issues/1113
* https://github.com/angular-ui/bootstrap/issues/2219

**Comment by sendilkumarn** [comment]
we will have both. 👍 

> shall we disable all controls?

We can wrap this inside `fieldset`  only for `disable` and for `readonly` we can go for individual elements in that picker

> disable / readonly

the difference will be in the value of ng-model will be
