### ISSUE TITLE
ngbDatepicker with MatDialog doesn't overflow into main body resulting in scrolling dialog

### ISSUE THREAD

**Issue by bhalicki** [ng-bootstrap/ng-bootstrap#4585]
When using ngbDatepicker with MatDialog, if the dialog isn't large enough for the ngbDatepicker control, the MatDialog component implements scrolling rather than the ngbDatepicker overflowing into the main body.

**Comment by maxokorokov** [comment]
Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a **minimal** reproduction scenario in a StackBlitz
