### ISSUE TITLE
timepicker: add support for arrowkeys and mousewheel

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#459]
Ref: http://angular-ui.github.io/bootstrap/#/timepicker

It should be trivial to implement but needs tests (as always!)

**Comment by sendilkumarn** [comment]
will take this one 👍

**Comment by deeg** [comment]
@pkozlowski-opensource, just tested this, it seems to work on the demo. Can probably be closed.

**Comment by jdhines** [comment]
Looks like this has been in the pipeline for months. Is the PR still in limbo?

**Comment by jnizet** [comment]
@pkozlowski-opensource is there a chance at least keyboard support is added to the timepicker? You chose to close #1334 with the comment "We will pass on this one for now till we figure out what to do with the timepicker...", but I'm not sure what you meant by that.

**Comment by Orodan** [comment]
Is there any reason to keep the issue opened ? From what I can see in the documentation the arrow keys support is working :)

**Comment by maxokorokov** [comment]
Last piece closed in #2053. I don't think implementing mouse wheel is a good idea, for example because of accidental scrolls it might introduce.
