### ISSUE TITLE
Angular 17 on Nav Component is Not supported

### ISSUE THREAD

**Issue by ct-dixit** [ng-bootstrap/ng-bootstrap#4594]
**Angular 17 on Nav Component is Not supported**

Nav Component Get Multiple Directive elements so get an error please fix

Directive NgbNavLinkBase matches multiple times on the same element. Directives can only match an element once.

![Screenshot 2023-11-01 165452](https://github.com/ng-bootstrap/ng-bootstrap/assets/106728438/957647ff-24af-4714-897a-173f685fcd0f)

### Versions of Angular, ng-bootstrap, and Bootstrap:

Angular: 17.0.0-rc.1

ng-bootstrap: 15.1.2

Bootstrap:5.2.3

**Comment by e-oz** [comment]
As a workaround, you can set `"optimization": true` in your `development` configuration of `build` in `project.json` or `angular.json`.

> [!IMPORTANT] 
> It's not a solution; it is only a workaround, and it will work really slowly. Only use it if you desperately need to make it run.

**Comment by phoenixcoded20** [comment]
How can I get this in release? I try to update local package with "angular-17-rc3" but no luck. What release should I refer to get these changes from ng-bootstrap package?

**Comment by FiniteLooper** [comment]
I had this same issue and updating after upgrading to Angular 17.

Updating this packge to the v16 release candidate fixes it for me. good enough to make my 300+ unit tests pass now, and the app works again just like it did on Angular 16 + ng-bootstrap 15.

Add this in your `package.json` until the full version is released
```json
"@ng-bootstrap/ng-bootstrap": "16.0.0-rc.0",
```
