### ISSUE TITLE
NG0203 error while using ngbTooltip directive as manual trigger in custom qtip directive

### ISSUE THREAD

**Issue by Gods-Favorite-Idiot** [ng-bootstrap/ng-bootstrap#4603]
### Bug description:
I have a directive `dewQtip` in qtip.directive.ts which basically does the same thing as ngbTooltip directive along with some customizations that are to be maintained in the entire organization ecosystem. In the directive, I am manually triggering the tooltip to open :
`      this.ngbToolTip.open();`

But right above this I am setting the `ngbToolTip` as:
```
this.ngbToolTip = new NgbTooltip(
        this._elementRef,
        this._renderer,
        this.injector,
        this.viewContainerRef,
        this.ngbTooltipConfig,
        this.ngZone,
        document,
        this._cdRef,
        this._appRef
      );
```

And this is where the error generates from.

### Error:
Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`.  Find more at [here](https://angular.io/errors/NG020)

### Call Stack
The error seems to stem from 
```
export function ngbPositioning() {
	const rtl = inject(NgbRTL);
```
[](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/util/positioning.ts#L215)

So it goes from,

```
export function ngbPositioning() {         
	const rtl = inject(NgbRTL);
```
 in [positioning.ts](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/util/positioning.ts#L215)
^
^
`private _positioning = ngbPositioning();`  in [tooltip.ts](https://github.com/ng-bootstrap/ng-bootstrap/blob/ade9e4fc33411b2cecf38263839706a8128b369d/src/tooltip/tooltip.ts#L179)
^
^
`this.ngbToolTip = new NgbTooltip(.....)`  in /qtip.directive/

### Link to minimally-working StackBlitz that reproduces the issue:

Have created a minimal reproduction with the custom directive in question. 
[Reproduction Link](https://stackblitz.com/edit/angular-byokwg?file=src%2Fmain.ts)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 16.1.7

ng-bootstrap: 15.1.2

Bootstrap: 5.2.3

### Workarounds:

Still investigating.

**Comment by maxokorokov** [comment]
Tooltip is a not a service, model or a simple TS class. It is an Angular directive, it is not meant to be instantiated with `new NgbTooltip`, it is meant to be applied on the existing elements via the selector. You should not rely on constructor as a public API for it.

Having said that...

1. You can use `hostDirectives` to apply it, this is probably the best way → https://stackblitz.com/edit/angular-3fn6z5?file=src%2Fapp%2Fwrapper.directive.ts,src%2Fapp%2Ftooltip-basic.ts,src%2Fapp%2Ftooltip-basic.html
2. You can create tooltip at the construction time (ex. in the constructor)
3. You can always use `injector.runInInjectionContext(() => {  tooltip = new NgbTooltip  })` as a quick workaround
4. With the level of customization that you have, it might be simpler to do your own tooltip :)

Also on a sidenote in v17 constructor will change as we'll use `inject` everywhere → https://github.com/ng-bootstrap/ng-bootstrap/commit/5ae69e128cc548cf7e604f76e9c386b92bec0561#diff-984156c78a32f0840952c38cef71d0bf4b23097bf38a680f3b45cdad4ed2e316L179

**Comment by maxokorokov** [comment]
Also I'm not sure I understand all these things you're doing with position fallbacks in your directive. What is that all about? Can't it be done purely with popper API?

**Comment by maxokorokov** [comment]
Closing as no response, please reopen if necessary.
