### ISSUE TITLE
16.0.0-rc.0: datepicker `startDate` type breaking change

### ISSUE THREAD

**Issue by cexbrayat** [ng-bootstrap/ng-bootstrap#4616]
### Bug description:

The following commit https://github.com/ng-bootstrap/ng-bootstrap/commit/30dc67c40b819652890262346eef4ffb04c2cc0f#diff-46903bc1acb49e5dd30ed8bf9f24552a5abcb647a97043a2bea97cde5cbe1cfbL399-R406 changed the type of `startDate` from `{ year: number; month: number: day?: number }` to the inferred type `{ year: number; month: number }` from the config.

When updating to rc.0, we are seeing compilation errors when trying to pass an object with a day property to `startDate`.

I suppose that the type should still have an optional `day` as it is used by the `navigateTo` method.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: v17.0.2

ng-bootstrap: v16.0.0-rc.0

Bootstrap: v5.3.2

**Comment by maxokorokov** [comment]
Thanks, @cexbrayat! Will be fixed in `rc.1`
