### ISSUE TITLE
[16.0.0-rc.1] [ngbAccordionBody]: Cannot get a TemplateRef from a template variable inside ngbAccordionBody

### ISSUE THREAD

**Issue by Valentin-MF** [ng-bootstrap/ng-bootstrap#4623]
### Bug description:

I use [NgBoostrap accordion](https://ng-bootstrap.github.io/#/components/accordion/overview).

And I'm trying to retrieve a TemplateRef that is in an ng-template with @ViewChild . The ng-template is an embedded view created by the ngbAccordionBody directive.

See NgBootstrap GitHub for embedded view creation: [ngbAccordionBody](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/accordion/accordion.directive.ts#L73)

I created a [StackBlitz](https://stackblitz.com/edit/angular-ngbdaccordionbasic-viewchild?file=src%2Fapp%2Faccordion-basic.html) to present my problem.

You'll see that I've found a workaround to my problem.

But I'd like to know if using @ViewChild is possible in this situation. If not, I'd like to know why not.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 17.0.2

ng-bootstrap: 16.0.0-rc.1

Bootstrap: 5.3.2

**Comment by maxokorokov** [comment]
Looks like a bug to me, I think it's because it is attached with this:

https://github.com/ng-bootstrap/ng-bootstrap/blob/6c3570b1897181569f6c8ed4107250e861c507dd/src/accordion/accordion.directive.ts#L75

Should be attached with the `ViewContainerRef instead I think.

**Comment by Valentin-MF** [comment]
This worked when using ngbAccordion as a component.
