### ISSUE TITLE
Datetime picker range selection issue

### ISSUE THREAD

**Issue by prajapatipravin** [ng-bootstrap/ng-bootstrap#4636]
i've given a filter to the user for fetching records in between dates, but the user wants to see only single-day data. in that case, the user should able to select the same date with two clicks. see the below-attached images for more....

### Bug description:
i can't select the same date for from and to both https://prnt.sc/GY6Pzir2Nz7n

### Reference, what's needed:
 needs to select the same date in the range selection like this https://prnt.sc/S9I3UMyD1Pd-

### Versions of Angular, ng-bootstrap, and Bootstrap:

Angular: 15.0

ng-bootstrap: 14.2

Bootstrap: 5.3

**Comment by harshbaleswaria** [comment]
Yes, i am facing same issue in my projects.

**Comment by HaiFish** [comment]
to achieve this, you need to change the onDateSelection method on sample code from this: 
```
onDateSelection(date: NgbDate) {
  if (!this.fromDate && !this.toDate) {
    this.fromDate = date;
  } else if (this.fromDate && !this.toDate && date && date.after(this.fromDate)) {
    this.toDate = date;
  } else {
    this.toDate = null;
    this.fromDate = date;
  }
}
```
to this:
```
onDateSelection(date: NgbDate) {
  if (!this.fromDate && !this.toDate) {
    this.fromDate = date;
  } else if (this.fromDate && !this.toDate && date && (date.equals(this.fromDate) || date.after(this.fromDate))) {
    this.toDate = date;
  } else {
    this.toDate = null;
    this.fromDate = date;
  }
  if (this.fromDate && this.toDate) {
    this.enviarDatas();
  }
}
```

Then it will allow you to select the same date.
Hope it helps

**Comment by prajapatipravin** [comment]
It works for me.

thanks @HaiFish
