### ISSUE TITLE
16.0.0: Cannot destructure property 'ngbCollapse' of 'this._collapse' as it is undefined.

### ISSUE THREAD

**Issue by sysmat** [ng-bootstrap/ng-bootstrap#4647]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

- Cannot destructure property 'ngbCollapse' of 'this._collapse' as it is undefined. Item are coming async
- degradation from ng-bootstrap14

```
ypeError: Cannot destructure property 'ngbCollapse' of 'this._collapse' as it is undefined.
    at NgbAccordionItem.ngAfterContentInit (ng-bootstrap.mjs:690:17)
    at callHookInternal (core.mjs:3523:14)
    at callHook (core.mjs:3550:13)
    at callHooks (core.mjs:3505:17)
    at executeInitAndCheckHooks (core.mjs:3455:9)
    at refreshView (core.mjs:13431:21)
    at detectChangesInView (core.mjs:13615:9)
    at detectChangesInViewIfAttached (core.mjs:13578:5)
    at detectChangesInEmbeddedViews (core.mjs:13535:13)
    at refreshView (core.mjs:13414:9)
```

### Link to minimally-working StackBlitz that reproduces the issue:

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 17.0.6

ng-bootstrap: 16.0.0

Bootstrap: 5.3.2

**Comment by sysmat** [comment]
- **StackBlitz(forked from accordian basic)**  https://stackblitz.com/edit/angular-ambrax?file=src%2Fapp%2Faccordion-basic.html

**Comment by bastienmoulia** [comment]
> * **StackBlitz(forked from accordian basic)**  https://stackblitz.com/edit/angular-ambrax?file=src%2Fapp%2Faccordion-basic.html

`<div ngbAccordionCollapse>` is missing from your exemple.

**Comment by sysmat** [comment]
@bastienmoulia thx, I added but open/close still not working

**Comment by sysmat** [comment]
aha, missing `ngbAccordionButton`

**Comment by sysmat** [comment]
I think if something is essential for component to work it should be compile error not runtime error
