### ISSUE TITLE
Wrong Title in Modal documentation

### ISSUE THREAD

**Issue by vishal-s-patel** [ng-bootstrap/ng-bootstrap#4648]
### Bug description:
Modal's documentation page displays **Dropdown** as Title, which should be **Modal**

### Link to minimally-working StackBlitz that reproduces the issue:
https://ng-bootstrap.github.io/#/components/modal/examples

**Comment by jnizet** [comment]
It's not just the title. All the example snippets are badly typed and their stackblitz point to the incorrect demo.

**Comment by vishal-s-patel** [comment]
Duplicate Issue
