### ISSUE TITLE
Accordion / Tabset: adding close button in a tab header

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#465]
It is quite common to have a little close button on each tab of a tabset to close a given tab. Unfortunately we can't easily add such a button today since content of the `ngTabTitle` tab is added _inside_ header's link (`<a>` element). This setup limits what users can put in a tab header.

Potential solutions:
- have users provide the whole link as part of the `ngTabTitle` template - the downside here is that users would have to manage the `active` and `disabled` states as well as a selection logic;
- add a new directive (`ngTabHeader`) - if provided its content would be added _after_ a link. The downside here is that there might be someone coming and saying that I want to insert sth _before_ a link...

Not sure what is the best course of action here, to be discussed.

**Comment by tsm91** [comment]
This is not valid html, but works fine.

```html
<a class="nav-link active" href="#">
  Active
  <button class="close" type="button">×</button>
</a>
```

Another solution would be (if nesting templates is possible in ng2):

```html
<ngb-tabset>
  <ngb-tab>
    <template ngbTabHeader>
      <!-- prepend something -->
      <template ngbTabTitle><b>Fancy</b> title</template>
      <!-- append something -->  
    </template>
    <template ngbTabContent>content</template>
  </ngb-tab>
</ngb-tabset>
```

**Comment by pkozlowski-opensource** [comment]
Ref: https://github.com/twbs/bootstrap/issues/518

**Comment by pkozlowski-opensource** [comment]
Another use-case to take into account: http://stackoverflow.com/questions/41767571/how-to-give-style-to-ngb-bootstrap-tab

**Comment by sh977218** [comment]
Is this issue/improvement/suggestion being resolving or still in discussing?

**Comment by sklipnoty** [comment]
Any updates? This is relatively easy in "normal" bootstrap => Yet I'm struggling with this ...

**Comment by AbakumovAlexandr** [comment]
Instead of adding a Close `button` as a child of an `a` element, you can consider adding a styled `span` instead. A basic example is in this [Stackblitz](https://stackblitz.com/edit/ng-bootstrap-tab-set-issues).

**Comment by maxokorokov** [comment]
Since version `5.2.0` there is a new `NgbNav` set of directives that fix this issue. `NgbNav` is meant to replace the `NgbTabset` component (completely deprecated in version `6.0.0`) as a more flexible alternative.

I suggest you migrate to it → https://ng-bootstrap.github.io/#/components/nav/overview
