### ISSUE TITLE
Button groups and split buttons example lacks border-radius on right due to incorrect markup order

### ISSUE THREAD

**Issue by shmert** [ng-bootstrap/ng-bootstrap#4652]
### Bug description:

The [example](https://ng-bootstrap.github.io/#/components/dropdown/examples#split) for split buttons has sharp right corners on the "Split Me" button. Moving some tags around fixes this.

<img width="320" alt="image" src="https://github.com/ng-bootstrap/ng-bootstrap/assets/85100/525f0656-88a3-4984-99ff-8845ca53cb05">

### Link to minimally-working StackBlitz that reproduces the issue:

https://angular-f1ubcd.stackblitz.io

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 17.0.8

ng-bootstrap: 16.0.0

Bootstrap: Not sure?

**Comment by jnizet** [comment]
Good catch.

Would you fancy opening a pull request to fix this?
