### ISSUE TITLE
footerTemplate does not customize by NgbDatepickerConfig

### ISSUE THREAD

**Issue by GiovaneRobertiTafine** [ng-bootstrap/ng-bootstrap#4653]
### Bug description:
I'm trying to globally customize the footerTemplate by injecting NgbDatepickerConfig, but there is no effect, only for other properties like firstDayOfWeek.

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/stackblitz-starters-e5q9o1?file=src%2Ftemplate.ts

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 17.0.8

ng-bootstrap: 16.0.0

Bootstrap: 5.3.2

**Comment by jnizet** [comment]
This is an issue with your code, not with ng-bootstrap.
Please ask this sort of question on StackOverflow or elsewhere.
Here's an example of correct code initializing the footer template: https://stackblitz.com/edit/stackblitz-starters-mryoys?file=src%2Fmain.ts,src%2Findex.html
