### ISSUE TITLE
In component example section Modal and Dropdown has a same header 

### ISSUE THREAD

**Issue by udithaprasads** [ng-bootstrap/ng-bootstrap#4661]
### Bug description:

This is a UI issue in ng-bootstrap app
https://ng-bootstrap.github.io/#/components/modal/examples

Here when I click on Modal under Components in left navigation Page header show as "Dropdown"

![image](https://github.com/ng-bootstrap/ng-bootstrap/assets/92226463/e33e474c-9a10-46f9-9422-c42f90b2d670)

Angular:

ng-bootstrap:

Bootstrap:

**Comment by rotan-hanrahan** [comment]
It's not just the title, so far more than just a simple UI issue. The StackBlitz URLs associated with the buttons next to each modal example contain "dropdown" where they should contain "modal".

This makes is VERY difficult for people to learn how to use Modal.
