### ISSUE TITLE
Accordion directive ignores Input Id

### ISSUE THREAD

**Issue by TheCell** [ng-bootstrap/ng-bootstrap#4668]
### Bug description:
I think this is a bug. The new ngbAccordion is a directive. We usually set our own unique Ids for ngbAccordionItems (previously panels) but with the new system the Input for id is overwritten.

It seems as if line 193 in https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/accordion/accordion.directive.ts  ```private _id = `ngb-accordion-item-${nextId++}`;``` is ignoring whatever ```@Input('ngbAccordionItem') set id(id: string)``` has as input at the start.

### Link to minimally-working StackBlitz that reproduces the issue:
[Working Example](https://stackblitz.com/edit/angular-w3pmud?file=src%2Fapp%2Faccordion-static.html)
You can see that I set a custom Id in the template but it's ignored when I log it to the console or display it in the template.

![image](https://github.com/ng-bootstrap/ng-bootstrap/assets/3481579/a56b5326-927d-402d-87ed-19f3e193dcb9)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 17.1.1
ng-bootstrap: 16.0.0
Bootstrap: 5.3.2

**Comment by abrahampe** [comment]
This was solve on ng-bootstrap: 16.0.0 or I have to upgrade to another version? My id is not set yet:

`  <div
    ngbAccordionItem
    [collapsed]="!openPanelList.includes(facet.id)"
    *ngFor="let facet of listaFacets"
    [id]="facet.id"
  >`

Generates an id like  "ngb-accordion-item-24"
