### ISSUE TITLE
ngb-offcanvas: container option not working

### ISSUE THREAD

**Issue by nik2208** [ng-bootstrap/ng-bootstrap#4682]
### Bug description:
![Screenshot 2024-03-07 at 14 43 39](https://github.com/ng-bootstrap/ng-bootstrap/assets/28157038/eb06dea2-df58-4862-93ef-b9302f7e899f)
is this working? am I doing something wrong?

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/stackblitz-starters-enbq7h?file=src%2Fmain.ts

### Versions of Angular, ng-bootstrap and Bootstrap:
Angular:
17
ng-bootstrap:

16
Bootstrap:
5.3

**Comment by jnizet** [comment]
The three buttons in your stackblitz all call the same method: `openWorking()`.

Fix the event binding, click on the button, and inspect the DOM, and you'll see that the offcanvass and backdrop elements are indeed attached to the expected location.

Note that this only changes the structure of the DOM. The backdrop will still cover the whole screen and the backdrop will still appear at the bottom of the page. That's expected.

**Comment by nik2208** [comment]
Hey there.. Thank u for ur reply. I've quickly filed a project to demonstrate the issue. After copy pasting (quickly.. Very quickly) the code, I've forgot at last to modify functions refs.
I've filed the project after having tested the issue on the real project.
The issue in the stackblitz is just a typo.

Coettecting the error actually does not solve the problem.
 Unless I've misunderstood the feature.

**Comment by nik2208** [comment]
the way i found that makes it work is also adding both `panelClass`and `::ng-deep`
![Screenshot 2024-03-10 at 02 04 24](https://github.com/ng-bootstrap/ng-bootstrap/assets/28157038/26e58a9f-0010-47a2-9b2d-5c1d29d95a4f)

**Comment by jnizet** [comment]
You have misunderstood the feature. As I said in my previous answer:

> Note that this only changes the structure of the DOM. The backdrop will still cover the whole screen and the backdrop will still appear at the bottom of the page. That's expected.

**Comment by nik2208** [comment]
ok thank u
