### ISSUE TITLE
NgbDatePicker does not follow Internationalization format for firstDayOfWeek 

### ISSUE THREAD

**Issue by fabiendv** [ng-bootstrap/ng-bootstrap#4685]
### Bug description:

Following the successful configuration of locale settings in the project, in line with the instructions on the [NG Bootstrap Datepicker documentation](https://ng-bootstrap.github.io/#/components/datepicker/examples#i18n), translations for months, days, etc., are correctly implemented. However, there appears to be an issue with the firstDayOfWeek parameter: it does not automatically adjust to match the customary first day of the week for the selected locale. This misalignment means the first day of the week does not reflect the typical country-specific standard.

### Illustration

Set up with English locale:

<img width="274" alt="Screenshot 2024-03-20 at 2 28 36 PM" src="https://github.com/ng-bootstrap/ng-bootstrap/assets/37407695/fa46aefe-a900-49a2-bd96-d4e3578974aa">

### Expected behavior

The week should start on Sunday.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: ^17.1.3

ng-bootstrap: ^16

Bootstrap: ^5.3.1

**Comment by jnizet** [comment]
That is intentional, to follow the ISO rules. The NgbDatepicker and NgbInputDatepicker component, and well as their respecting Config interfaces which allow configuring default options, have a `firstDayOfWeek` that you can set if you want to use a different default.

**Comment by fabiendv** [comment]
> That is intentional, to follow the ISO rules. The NgbDatepicker and NgbInputDatepicker component, and well as their respecting Config interfaces which allow configuring default options, have a `firstDayOfWeek` that you can set if you want to use a different default.

Thanks for the update.

I'll handle the input `firstDayOfWeek` depending on the locale that is used.

Closing this issue.
