### ISSUE TITLE
Investigate compatibility with reactive forms

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#469]
Today several directives (buttons, timepicker, typeahead) are assuming presence of the `ngModel` directive. But for reactive forms people are not going to use `ngModel` so we need to see how we could support both template-driven and model-driven forms.

**Comment by crooksey** [comment]
If this issue is now closed, is there any documentation to support reactive forms?

**Comment by jasonhjohnson** [comment]
@crooksey Were you able to get this working correctly with reactive forms?

**Comment by crooksey** [comment]
Yes I had/have this working, 

```
this.oForm = this.fb.group({
    oHForm: this.fb.group({ // create nested formgroup to pass to child
        selectTypeahead: ['', Validators.required],
        ohDatePicker: [],
        }),	
})
```
Shows how to setup a form group for typeahead and datePickers

Template, datepicker:
```
<input class="form-control" placeholder="dd-mm-yyyy"
     id="oh_date_picker"
     formControlName="ohDatePicker"
     name="dp"  
     ngbDatepicker #d="ngbDatepicker">
```

Template typeahead:
```
<input type="text" class="form-control" 
    formControlName=" selectTypeahead"
    [ngbTypeahead]="search" 
    
    (selectItem)="taMatch($event)"
    [resultTemplate]="rt" [inputFormatter]="formatter" autofocus tabindex="0" #msgFocous/>
```

Hope this helps someone.

**Comment by rajeshmahendran41** [comment]
How to use time picker with reactive forms ?
