### ISSUE TITLE
skip 17 to align with angular 18

### ISSUE THREAD

**Issue by MuhAssar** [ng-bootstrap/ng-bootstrap#4715]
I suggest to name the next release of ng-bootstrap as 18 to better align it with angular 18

**Comment by markusberg** [comment]
I don't think that's as easy as it sounds. NgBootstrap is dependent on both Bootstrap and Angular, so there will likely be major version bumps whenever either of those projects release a major version.

When Bootstrap 5 was released there were two concurrent versions of ngBootstrap for Angular 13. ngBootstrap v11 supported Angular 13/Bootstrap 4.6.0 while ngBootstrap v12 supported Angular 13/Bootstrap 5.

The same situation is likely to occur when Bootstrap 6 is released.

**Comment by maxokorokov** [comment]
Just a note that we'll think about it, but not for the current major.
@markusberg is right that we have 2 dependencies, but on the other hand bootstrap doesn't release that often, so we'll see that when versions align either with Bootstrap 6 or with our own breaking changes ;)
