### ISSUE TITLE
Demo page of ngbModal: wrong title and stackblitz links

### ISSUE THREAD

**Issue by ihusnja4** [ng-bootstrap/ng-bootstrap#4719]
### Bug description:

The issues on [https://ng-bootstrap.github.io/#/components/modal/examples](https://ng-bootstrap.github.io/#/components/modal/examples) :
- title of the page is "Dropdown" instead of "Modal"
- all the links for stackblitz examples are pointing to Dropdown examples not Modal

### Link to minimally-working StackBlitz that reproduces the issue:

N/A

### Versions of Angular, ng-bootstrap and Bootstrap:

N/A

Angular:

N/A

ng-bootstrap:

N/A

Bootstrap:

N/A

**Comment by maxokorokov** [comment]
I think this is fixed in main branch, will check before next release, thanks!

**Comment by maxokorokov** [comment]
checked, should be ok now
