### ISSUE TITLE
Support for angular 18.1 & (@let)

### ISSUE THREAD

**Issue by kle-pra** [ng-bootstrap/ng-bootstrap#4744]
### Bug description:
In latest version of angular, 18.1.0, there is a support for @let syntax, but it will not work with ng bootstrap 17.0.0 which uses Angular 18.0.0.

There seem to be a problem with ngb pagination component and usage of @let synthax (ie. inside template for loop, that is paginated), there is an error.

`Error: ASSERTION ERROR: Expected [Text|Element|Container|ElementContainer|Projection|IcuContainer] but got LetDeclaration.
`
### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/~/github.com/kle-pra/ngb_let

Check the browser console from preview window when changing pagination.

Example code that causes error from example:

```html
  <h1>Example Ngb pagination and let variable</h1>
  <table
  class="table table-striped">
  <tbody>
    @for (person of persons | slice: page * pageSize:(page + 1) * pageSize; track person.id) {
      @let a = 1;

      <tr>
        <td>{{ person.name }}</td>
        <td>{{ person.surname }}</td>
      </tr>
    }
  </tbody>
</table>
  <ngb-pagination
  [collectionSize]="persons.length"
  [(page)]="page"
  [maxSize]="10"
  [pageSize]="pageSize"
 /> 
```

```sh
chunk-EY6GRXGT.js?v=8e7cd676:8549 ERROR Error: ASSERTION ERROR: Expected [Text|Element|Container|ElementContainer|Projection|IcuContainer] but got LetDeclaration.
    at throwError2 (chunk-EY6GRXGT.js?v=8e7cd676:5003:9)
    at assertTNodeType (chunk-EY6GRXGT.js?v=8e7cd676:7828:5)
    at getFirstNativeNode (chunk-EY6GRXGT.js?v=8e7cd676:10831:18)
    at getBeforeNodeForView (chunk-EY6GRXGT.js?v=8e7cd676:10889:14)
    at addLViewToLContainer (chunk-EY6GRXGT.js?v=8e7cd676:12069:24)
    at LiveCollectionLContainerImpl.attach (chunk-EY6GRXGT.js?v=8e7cd676:18734:5)
    at reconcile (chunk-EY6GRXGT.js?v=8e7cd676:18460:24)
    at Module.ɵɵrepeater (chunk-EY6GRXGT.js?v=8e7cd676:18786:5)
    at PaginationEx_Template (pagination-ex.component.ts:17:5)
    at executeTemplate (chunk-EY6GRXGT.js?v=8e7cd676:11225:5)
```

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 18.1.1
ng-bootstrap: 17.0.0
Bootstrap: 5.3.3

Best regards

**Comment by sysmat** [comment]
- I have the same error  
- this lib just need to update to ng 18.1.x to new @let expression to work

**Comment by kle-pra** [comment]
I updated the description with minimally-working StackBlitz that reproduces the issue.

**Comment by jnizet** [comment]
I don't think this has anything to do with ng-bootstrap (which supports Angular 18.1 just fine).
See https://github.com/angular/angular/issues/57160

**Comment by JeanMeche** [comment]
Yes, this is an angular bug, unrelated to ng-bootstrap.

**Comment by kle-pra** [comment]
Thanks, latest angular update to 18.1.3 fixes this bug, closing this issue.
