### ISSUE TITLE
$localize is not defined after upgrading to Angular 18

### ISSUE THREAD

**Issue by dahool** [ng-bootstrap/ng-bootstrap#4745]
After upgrading to Angular 18.1.1 and ng-boostrap 17, pagination module is broken and the following error shows in console "$localize is not defined"

@angular/localize is installed

**Comment by dahool** [comment]
nevermind, I had to add localize to angular.json after removing polyfills

**Comment by garciajasminejoy** [comment]
Hi @dahool, adding "localize" caused a 500 internal server error (nginx). Did you encounter that? what exactly did you remove from polyfills? we have import '@angular/localize/init'

**Comment by dahool** [comment]
> Hi [@dahool](https://github.com/dahool), adding "localize" caused a 500 internal server error (nginx). Did you encounter that? what exactly did you remove from polyfills? we have import '@angular/localize/init'

No error 500.

I'm on angular 19 now, but what I can see from the commits logs, what I did was:

* Remove polyfills.ts and all references to it
* Add the following section to angular.json

```json
"polyfills": [
    "zone.js",
    "@angular/localize"
],
```

**Comment by garciajasminejoy** [comment]
> > Hi [@dahool](https://github.com/dahool), adding "localize" caused a 500 internal server error (nginx). Did you encounter that? what exactly did you remove from polyfills? we have import '@angular/localize/init'
> 
> No error 500.
> 
> I'm on angular 19 now, but what I can see from the commits logs, what I did was:
> 
> * Remove polyfills.ts and all references to it
> * Add the following section to angular.json
> 
> "polyfills": [
>     "zone.js",
>     "@angular/localize"
> ],

All good now thanks! We didn't have to add @angular/localize to the polyfills tho, I left it empty (since we don't really utilize i18n). 
Aside from that what fixed it for us was adding `@angular/localize` to tsconfig.app.json under compilerOptions.types :D 
Figured it out by creating a new angular 17 project from scratch, this seems to be the default setup! :D

**Comment by RonStShufersal** [comment]
We had a similar issue with angular 19.2, and adding 
```javascript
"polyfills": [
// ...
"@angular/localize/init"
// ...
],
```
solved it.

**Comment by Razei** [comment]
> We had a similar issue with angular 19.2, and adding
> 
> "polyfills": [
> // ...
> "@angular/localize/init"
> // ...
> ],
> solved it.

In 2026, I've encountered this and this advice did not work for me, but I did find something that worked. Hopefully this can help any future readers Googling/ AI debugging this problem as well (assuming it's a correct assessment/solution).

There seems to be a [builder optimization in the angular builder that explicitly removes the $localize polyfill](https://github.com/angular/angular-cli/blob/a712a821734d89aa3cd8cf123d97df7061cd0be0/packages/angular/build/src/tools/esbuild/application-code-bundle.ts#L690)

```ts
polyfills = polyfills.filter((path) => !path.startsWith('@angular/localize'));
```

Once translations are inlined, Angular assumes the runtime localize polyfill is no longer needed. That assumption is fine for many apps, but it breaks when a library still expects a callable global $localize at runtime, which is exactly what ng-bootstrap ends up doing.

When ng-bootstrap tries to call it at runtime it crashes with error "ERROR TypeError: $localize is not a function".

My solution

What solved it for me is to include a script in the polyfills config instead:

```json
{
  "polyfills": [
    "src/polyfills.ts"
  ]
}
```

```ts 
// polyfills.ts
import '@angular/localize/init';
```
The polyfill does not start with @angular/localize, so it survives bundling and still imports the same runtime.

**Comment by Makaopior** [comment]
Hi @Razei , thanks for the workaround!
Polyfill script solved the problem.

However, this problem still persists in version 20.x (Angular 21.x), maybe this ticket should be reopened?
Or are we supposed to fix polyfills manually every time?
My environment: 
```
Angular CLI       : 21.2.16
Angular           : 21.2.17
Node.js           : 22.14.0
Package Manager   : npm 10.9.2
Operating System  : win32 x64

"@ng-bootstrap/ng-bootstrap": "^20.0.0"
```
