### ISSUE TITLE
Navbar not working with Angular 18 and ng-bootstrap 17

### ISSUE THREAD

**Issue by r0main** [ng-bootstrap/ng-bootstrap#4747]
### Bug description:

1. I generated a simple App with ng-cli (18.1.3) : `ng new my-first-project`
2. I added ng-bootstrap with : `ng add @ng-bootstrap/ng-bootstrap`
3. I copied/pasted the navbar example from bootstrap 5.3 documentation https://getbootstrap.com/docs/5.3/components/navbar/
```html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
```

The burger menu displays correctly on small screen :
![image](https://github.com/user-attachments/assets/b47528b1-8fbb-4461-9f34-c6119de47669)

But the click on the burger is not dropping dwon the menu... No error in the console. It seems like the click has no effect...

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-d7s2vy?file=src%2Fmain.ts

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 18.1.3

ng-bootstrap: 17.0.0

Bootstrap: 5.3.3

(note that the stack of the StackBlitz  is juste a little bit different but the same problem apply)

**Comment by r0main** [comment]
Maybe I am mislead by the installation documentation : https://ng-bootstrap.github.io/#/getting-started which says not to include Bootstrap JS files : 
![image](https://github.com/user-attachments/assets/d53dd551-b7fe-40fb-8aae-c66af3e84a27)

Indeed if we don't include the Bootstrap JS files it means some of the bootstrap components won't work. Only the one you rewrited will work ?

To create a navbar with ng-boostrap, the clean solution is to use the navbar example from Bootstrap an use [ngbCollabse ](https://ng-bootstrap.github.io/#/components/collapse/examples#navbar) directive to handle the show/hide ?

**Comment by mjhandy** [comment]
I have something similar. With a small browser window, after ng serve, the nav is visible, but the toggle works. Desktop view seems fine.

I also did the same, cut and pasted the HTML from the example, and same issue.

**Comment by jnizet** [comment]
The bootstrap examples using attributes such as `data-bs-toggle` are meant to be used with the native Bootstrap JS. The point of ng-bootstrap is to replace this JS with Angular components and directives. 

So if you want a navbar that collapses, use the bootstrap examples for the HTML and CSS parts, but use ng-bootstrap'd documentation to know how to get the behavior you want. In this case, you want something to collapse when clicking on a button. ng-bootstrap has a directive for that: [collapse](https://ng-bootstrap.github.io/#/components/collapse/examples). 
One of its examples is precisely about a responsive navbar: https://ng-bootstrap.github.io/#/components/collapse/examples#navbar.
