### ISSUE TITLE
Difficulties non localizing the datepicker varying LOCALE_ID at runtime

### ISSUE THREAD

**Issue by evilaliv3** [ng-bootstrap/ng-bootstrap#4755]
Hello!

In @GlobaLeaks we use ng-boostrap with angular 18 and we are having some difficulties changing the LOCALE_ID dynamically.

We are using the following code, but it seems that ng-bootstrap continue to use the initial value of the LOCALE_ID instead of using the up-to-date actual value.

Would you please advice?

```import { NgModule, LOCALE_ID } from '@angular/core';
import { TranslationService } from './translation.service';

export function localeFactory(translationService: TranslationService) {
  return translationService.getLang(); // Return the current language from TranslationService
}

@NgModule({
  providers: [
    {
      provide: LOCALE_ID,
      useFactory: localeFactory, // Use the factory for LOCALE_ID
      deps: [TranslationService]  // The factory depends on TranslationService
    }
  ],
  // Other module metadata...
})
export class AppModule {}
```

Thank you!

**Comment by evilaliv3** [comment]
@maxokorokov: Which is the best way to make ng-bootstrap to reload / communicate that a different locale should be used?

**Comment by jnizet** [comment]
This doesn't have aything to do with ng-bootstrap. A factory-based provider in the Angular root module is only called once, at startup. You must reload the application if you want a new LOCALE_ID to be provided.
