### ISSUE TITLE
Accordion: destroyOnHide is not respected and component content is present in the DOM with OnPush strategy

### ISSUE THREAD

**Issue by nemasmisal** [ng-bootstrap/ng-bootstrap#4758]
### Bug description:
When `destroyOnHide` is set to `true` or not (which according documentation is `true` by default), after collapsing accordion, the body (NgbAccordionBody) still contains its content a.k.a none of the elements are removed from the DOM. I've experience this issue with `OnPush` change detection strategy. I decide to fork and clone the repo, then work it out and found that regardless of which change detection strategy I have choose, DEMO components still present their content of the body, when accordion is collapsed. I have experience this problem with v.16 then decide to clone and test the latest 17, issue is still present.

### Link to minimally-working StackBlitz that reproduces the issue:
Fork/clone the project -> go to : `demo/src/app/components/accordion/demos/basic/accordion-basic.ts` and change the strategy to `OnPush` -> yarn demo -> navigate to : components/accordion/examples -> inspect first basic example and its DOM content while expand/collapse the accordion.
Expecting result: DOM elements/content from body (NgbAccordionBody) to be remove from the DOM, once its collapsed.
Actual result: DOM elements/content of the body are present in the DOM, when accordion is collapsed.

I woud like to provide fix for this issue.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 17, 18

ng-bootstrap: 16,17

Bootstrap:5.3.*

**Comment by quentinderoubaix** [comment]
thanks @nemasmisal for raising the issue and opening the initial PR !
