### ISSUE TITLE
API docs: text overlaps for long property or type names 

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#476]
As an example check http://localhost:9090/#/components/popover for which `ngbPopover` has a longish type specification (`string | TemplateRef<any>`) and creates very unpleasant look & feel (text is wrapped in an ugly way). The problem is even more visible as soon as we land typeahead.

The only idea I've got so far is to have 2 rows for each property:
* name, type and default value in the first row
* description in the second row.

But all the options are on the table...

**Comment by maxokorokov** [comment]
I was playing a bit too with it. What about this layout?

![screen shot 2016-07-26 at 16 16 09](https://cloud.githubusercontent.com/assets/8074436/17141431/51cb70d6-534c-11e6-8356-f1de8f76eea6.png)

**Comment by pkozlowski-opensource** [comment]
> What about this layout?

I think I like better than my proposal :+1: 

Both are similar but yours look better to me. But I would probably keep table header.

Could you send an alternative PR so I can play with it?

**Comment by maxokorokov** [comment]
@pkozlowski-opensource just replace your table with the one I added in the PR. I have only played with inputs section

**Comment by pkozlowski-opensource** [comment]
Solved via 30902bc
