### ISSUE TITLE
Support Angular 19

### ISSUE THREAD

**Issue by mshima** [ng-bootstrap/ng-bootstrap#4779]
Angular 19 has been [released](https://github.com/angular/angular/releases/tag/19.0.0)

**Comment by Govind85** [comment]
@mshima When are we planning to release the version which will support Angular v19?

**Comment by dementeddevil** [comment]
I forked the repo and while everything can then be updated, there is one dependency that needs to release a compatible update before a clean build can be achieved; `@angular-builders/custom-webpack`

**Comment by mshima** [comment]
`@angular-builders` released a beta version, this should allow a clean install.

**Comment by maxokorokov** [comment]
Will publish RC ASAP, final release W51

**Comment by quentinderoubaix** [comment]
18.0.0-rc.0 RC has been published, see [Release Notes](https://github.com/ng-bootstrap/ng-bootstrap/releases/tag/18.0.0-rc.0)

**Comment by cbaca01** [comment]
> Angular 19 has been [released](https://github.com/angular/angular/releases/tag/19.0.0)

Are there any dependencies we have to update as well?
I am having an issue with this dependency when I try to install 18.0.0-rc.0:
`peer @angular/core@"^17.0.0 || ^18.0.0" from apollo-angular@7.2.0`

**Comment by quentinderoubaix** [comment]
> > Angular 19 has been [released](https://github.com/angular/angular/releases/tag/19.0.0)
> 
> Are there any dependencies we have to update as well? I am having an issue with this dependency when I try to install 18.0.0-rc.0: `peer @angular/core@"^17.0.0 || ^18.0.0" from apollo-angular@7.2.0`

ng-bootstrap does not depend on apollo-angular. you can check the list of dependencies [in our README](https://github.com/ng-bootstrap/ng-bootstrap?tab=readme-ov-file#dependencies) or in the demo site.
most likely the project you are trying to upgrade also uses apollo-angular.

**Comment by donald23onno** [comment]
> 18.0.0-rc.0 RC has been published, see [Release Notes](https://github.com/ng-bootstrap/ng-bootstrap/releases/tag/18.0.0-rc.0)

when using npm or ng update, neither can't seem to find the rc. When explicitly editing package.json, it also states it cannot find that version.
Will this rc be pushed to be installable via npm or do I need to wait a version (or two)?

**Comment by quentinderoubaix** [comment]
18.0.0 has been released, see [Release Notes](https://github.com/ng-bootstrap/ng-bootstrap/releases/tag/18.0.0)
