### ISSUE TITLE
Upgrade to BS4 Alpha 3

### ISSUE THREAD

**Issue by icfantv** [ng-bootstrap/ng-bootstrap#487]
Upgrade the library for BS4 Alpha 3.

Running the demos revealed several issues:
- [x] Side nav moved to the left side of screen
- [x] Pager is borked (**UPDATE**: pager component will be removed)
- [x] Font size in HTML source view is at 75% due to `.tag` class overriding `.code` class' `font-size` property.
- [x] Outline buttons changed style names, see https://github.com/twbs/bootstrap/pull/20391/files
- [x] Link styling in tabset, pager, etc... is all black due to missing `href` attribute.

**Comment by icfantv** [comment]
So, the `.pager` class [was removed](https://github.com/twbs/bootstrap/pull/18782/files) entire due to it being "...little more than customized outline buttons"

That link has the removed CSS which we can add back in and get our component back, or we'll need to switch to our own styling.  I'm ok pulling the CSS back in so long as the user is able to override.

**Comment by icfantv** [comment]
I don't love the hack to get the HTML source looking correct, but if we're considering pulling prisimjs and switching to CSS, then I'm ok with this for now.

**Comment by pkozlowski-opensource** [comment]
How about dropping pager altogether?

**Comment by icfantv** [comment]
I have zero sense of how many people use it on UIBS, but if Bootstrap ditched it entirely then that gives us something to point to as justification.

**Comment by icfantv** [comment]
Crap, didn't mean to close this...

**Comment by pkozlowski-opensource** [comment]
Re-opening this one as there are more items to take care of.

**Comment by pkozlowski-opensource** [comment]
Regarding pager my vote goes to axing it for now.

**Comment by pkozlowski-opensource** [comment]
I believe that this is done now.
