### ISSUE TITLE
Scrollspy

### ISSUE THREAD

**Issue by BobbieBarker** [ng-bootstrap/ng-bootstrap#5]
Recreate BS3 Scrollspy with ng2 component.

**Comment by pkozlowski-opensource** [comment]
There was a good attempt at scrollspy in #185 but we still need to sort out few things (see comments in the PR).

**Comment by sendilkumarn** [comment]
@wesleycho are you working on this or I will give a shot at this.

**Comment by wesleycho** [comment]
Feel free to take a stab, this one eluded me.

**Comment by pkozlowski-opensource** [comment]
@sendilkumarn if you going to take on this one please make sure that you read through discussion in #185. Would be awesome to have a short design doc with main API / impl ideas before you dive into coding.

**Comment by sendilkumarn** [comment]
something like this

http://plnkr.co/edit/kpzeCYcFcRY5m29TvOBo?p=preview

PTAL. 

Seems to work fine. I think I need to add click function for spies. I will add that too.

**Comment by sendilkumarn** [comment]
Do we need to handle the navigation on clicking the spy or enforce it via href attribute?

**Comment by sendilkumarn** [comment]
updated plunk 
http://plnkr.co/edit/kpzeCYcFcRY5m29TvOBo?p=preview

**Comment by iBasit** [comment]
when this will be released?

**Comment by balteo** [comment]
I am looking forward to this feature!

**Comment by virtualSharif** [comment]
any tentative release date for this feature?

**Comment by dneeleman** [comment]
Any updates?

**Comment by bluecaret** [comment]
Looks like @sendilkumarn had something working pretty good. Can we get this added in? One of the big features missing still.

**Comment by code-dabbler** [comment]
Any updates on when this will be released?

**Comment by tetianakh** [comment]
Any updates on this please?

**Comment by ThePredators** [comment]
Any update on this ?

**Comment by n4j1Br4ch1D** [comment]
no updates yet?

**Comment by sannyjacobsson** [comment]
Any update?

**Comment by maxokorokov** [comment]
Please look at the ScrollSpy RFC, if you have some time → #4503
