### ISSUE TITLE
chore: changelog task generates wrong links

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#506]
see https://github.com/ng-bootstrap/ng-bootstrap/pull/505

**Comment by maxokorokov** [comment]
Not sure how to generate a `changelog`, but in angular they do this:
https://github.com/angular/angular/blob/master/gulpfile.js#L149-L154

**Comment by pkozlowski-opensource** [comment]
@maxokorokov check `gulp changelog` in our gulpfile

**Comment by maxokorokov** [comment]
@pkozlowski-opensource that I figured out :) doesn't generate anything for me, will take a look later
