### ISSUE TITLE
timepicker: impossible to enter a two-digit number

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#511]
Using the demo, if I try to enter, for example, `10` in the hour input field, the timepicker immediately formats the entered `1` as `01`, and then doesn't let me enter the `0`.

**Comment by pkozlowski-opensource** [comment]
Yeh... It is possible but "tricky"... But I totally agree. I guess we shouldn't format as long as the field has focus. To be fixed.
