### ISSUE TITLE
timepicker: make the component invalid if wrong input

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#513]
Using the demo with custom validation, if I enter something invalid (like `aa`, for example) in one of the fields, or if I clear one of the fields, I would expect a validation error other than "It's a bit too early", and the model to become null, since `aa:<blank><blank>` is not a valid input and should thus not, IMO, be saved as `00:00` in the model.

**Comment by pkozlowski-opensource** [comment]
Makes sense. Will look into those scenarios as part of alpha.2.
