### ISSUE TITLE
typeahead: wikipedia search broken on the live site

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#514]
Mixed Content issue, here is the resume:

- the page at 'https://ng-bootstrap.github.io/#/components/typeahead' was loaded over HTTPS 
- requested an insecure script 'http://en.wikipedia.org/w/api.php'

**Comment by pkozlowski-opensource** [comment]
BTW: it also shows that we are not correctly handling errors in observables - when sth like this fails we should remove the searching notification...

**Comment by pkozlowski-opensource** [comment]
Fixed in master and pushed an update to the demo site as well.
