### ISSUE TITLE
typeahead: add autocomplete="off" to the host

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#520]
An input field on which we are setting a typeahead should have those attributes added automatically to the host:
* `autocomplete="off"` 
* `autocapitalize="off"`
* `autocorrect="off"`

**Comment by pkozlowski-opensource** [comment]
Tests are mandatory

**Comment by jnizet** [comment]
BTW, I really appreciate that you're encouraging external contributors like you're doing by filing issues and tagging them with the effort tag. It probably took you longer to file the issue than to just fix it in the first place, but it's a great opportunity for me to learn and be useful at the same time. 👍

**Comment by pkozlowski-opensource** [comment]
> BTW, I really appreciate that you're encouraging external contributors like you're doing by filing issues and tagging them with the effort tag

Sure, we definitively want to grow a pool of contributors. So thnx once again for stepping in and helping out!
