### ISSUE TITLE
demo site: improve home page

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#521]
Our most important home page could use some improvements:
* The first link sends people _out_ of this site - we should restructure it so the fist link leads to the components demo
* There is text only in there - can we make it more "sexy"?
* There is not much content in there and the footer looks wired

**Comment by pkozlowski-opensource** [comment]
While speaking about the demo site, we should probably improve how it displays on small factors (mobile devices). Currently there is to much "white" on the sides.

**Comment by Foxandxss** [comment]
I agree on point 2 and 3 (I don't see a problem with the ui-bs link being first).

But I agree that the main page is as dull as it can get.
