### ISSUE TITLE
typeahead template mouse click event not firing

### ISSUE THREAD

**Issue by Basewq** [ng-bootstrap/ng-bootstrap#523]
On Chrome (Version 52.0.2743.82 ~latest version, Windows 10) I've noticed the typeahead template on the demo (https://ng-bootstrap.github.io/#/components/typeahead) doesn't always select the item when you click with the mouse.
If you aim specifically at the flag (the img element), nothing happens. I played around and tried wrapping the entire template in a span, and clicking anywhere on the span means it won't select the item.
Clicking outside of the wrapped element (ie directly on the button element) will work.
Trying it on Firefox, there's no issue.
Is this a ng-bootstrap issue or an Angular2 issue?

**Comment by pkozlowski-opensource** [comment]
Sound more like a pb on our side since I can't reproduce it with pure Angular, see: https://plnkr.co/edit/b5KLqIsunwf6SdKcZA8I?p=preview

To be investigated / fixed. Thnx for reporting!

**Comment by pkozlowski-opensource** [comment]
I was trying to replicate it in a standalone plunker and can't find isolated conditions under which it happens. What I can see for now that when a bug occurs we are getting `mouseenter` events instead of `click`. Interestingly event mousemoves are interpreted as `mouseenter` (!).

At this point it can't say much more. It could either an angular bug with dynamically inserted components or sth else. To be investigated further (not the highest priority though...).

BTW, could reproduce the same PB in Safari, so likely not a browser bug.

**Comment by Basewq** [comment]
Ok, I played around a little more, and this is what I noticed in Chrome:
If you click on the img, the button becomes in focus (and the textbox loses focus).
If you don't move the mouse and try clicking again, nothing happens.
If you move the mouse completely out of the select item, you'll see the button style (and it being focused).
If you move the mouse back to the item (anywhere), the click event works and the item is selected.

On a side note, if just move outside of the img, but still stay within the button, it becomes clickable. So what I assume is happening is the inner element only brings the button in to focus, and if you stay in that element, further clicks are prevented (some feature to prevent overclicking? Is the browser doing this, or the code, or Angular2?).

**Comment by maxokorokov** [comment]
So in general case looks like this works:

```html
<template #rt let-r="result">
  {{r.name}}
</template>
```

and this doesn't:

```html
<template #rt let-r="result">
  <anyelement>{{r.name}}</anyelement>
</template>
```

And also there is no difference whether it is a `<button>` or previously `<a>` element for dropdown items.

Somethings apparently happens with the focus handling in Chrome and breaks things (maybe with the combination with #526, as I can't reproduce it with simple examples). So the `(click)` is never executed until there is a focus inside the dropdown.

On the other hand we do not care if the item gets focused or not upon click, so I suggest we replace `(click)` with the `(mousedown)` and `preventDefault()` it → this way browser will never try to focus on the dropdown item at all. 

Will open a pull request for this, so it will be more clear.

**Comment by akr-optimus** [comment]
I am using the @ng-bootstrap/ng-bootstrap@1.0.0-alpha.28. Tried replacing the 'click' with 'mousedown'. Still doesn't work. Chrome Version: Version 57.0.2987.133 (64-bit). Also tried using 'pointerdown' as read about the Chrome moving away for mouse* events to pointer* events (https://developers.google.com/web/updates/2016/10/pointer-events) but still didn't work

**Comment by danielflippance** [comment]
FWIW - I noticed that curiously, a style accidentally applied globally: ` .dropdown-menu { display: none } ` caused the typeahead to show the dropdown menu with correct matches, but clicking those items didn't update the model.

I was applying the style for some D3 elements:
`d3.selectAll('.dropdown-menu').style('display', 'none');`

Adding a parent selector fixed the typeahead:
`d3.selectAll('.the-parent .dropdown-menu').style('display', 'none');`
