### ISSUE TITLE
typeahead: constant dropdown items re-rendering

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#526]
On the demo site the whole suggestion list for typeahead gets re-rendered on any event. For example on arrow up, arrow down, hovering mouse over items, etc.

![screen shot 2016-08-01 at 15 26 47](https://cloud.githubusercontent.com/assets/8074436/17295441/6e3e565c-57fc-11e6-82dd-46677f24906d.png)

I would expect only the `active` css class to change

**Comment by pkozlowski-opensource** [comment]
We should probably add trackBy to ngFor and see if this helps.

**Comment by pkozlowski-opensource** [comment]
Hmm, actually @maxokorokov you were right - it is due to the template context being re-created all the time... Not sure what is the best way of fixing this... Can think of:
* don't use templates for the "default" scenario (this is not a real fix, rather sth that will make issue less apparent for "typical" cases)
* maintain a map of result => context objects - the downside here is that we are trading memory for DOM operations... 

We should also check what ngFor is doing in this case.

**Comment by wesleycho** [comment]
Could we override the change detection used in this case with ngFor?

**Comment by pkozlowski-opensource** [comment]
So, ngFor is maintaining a map of item => context and updates this map in response to the changes in the collection being iterated over. I guess we need to do the same if we want to limit number of DOM changes.

**Comment by Basewq** [comment]
I think the issue can be solved by inlining the ngOutletContext object, ie.
`<template [ngTemplateOutlet]="resultTemplate || rt" [ngOutletContext]="_prepareTplCtx(result)"></template>`
to
`<template [ngTemplateOutlet]="resultTemplate || rt" [ngOutletContext]="{result:result, term: term, formatter: formatter}"></template>`

Excuse the messy plunker: https://plnkr.co/edit/yHFIDu7xKhISlGzoDY39?p=preview
I changed tested the line in file src/typeaheadwin.ts

Can someone test this is the case?

If this is indeed the fix, can we try reverting back the mousedown event to click (#527), as most people expect the selection to occur on mouse up.

**Comment by maxokorokov** [comment]
@Basewq I just tested it and this removes both excessive rendering and `(click)` issues inside the template. Indeed, looks like the issue was doing `new ResultTplCtx()` each time. Simple enough fix for me, thanks! Opened a pull request.
