### ISSUE TITLE
NPM Install Issue

### ISSUE THREAD

**Issue by jadav1982** [ng-bootstrap/ng-bootstrap#533]
ng-bootstrap-master>npm install
npm WARN package.json ng-bootstrap@1.0.0-alpha.2 license should be a valid SPDX
license expression

> ng-bootstrap@1.0.0-alpha.2 install C:\Users\Tarun\Downloads\ng-bootstrap-maste
r
> node misc/validate-commit.install.js

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\Tarun\Downloads\ng-boot
strap-master\.git\hooks\commit-msg'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at Object.<anonymous> (C:\Users\Tarun\Downloads\ng-bootstrap-master\misc\val
idate-commit.install.js:10:6)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! ng-bootstrap@1.0.0-alpha.2 install: `node misc/validate-commit.install.
js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng-bootstrap@1.0.0-alpha.2 install script 'node misc/vali
date-commit.install.js'.
npm ERR! This is most likely a problem with the ng-bootstrap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node misc/validate-commit.install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng-bootstrap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls ng-bootstrap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Tarun\Downloads\ng-bootstrap-master\npm-debug.log

**Comment by pkozlowski-opensource** [comment]
Are you sure that you are following [install instructions](https://github.com/ng-bootstrap/ng-bootstrap#installation)? It looks for me like you are trying to npm-install this repo instead of `@ng-bootstrap/ng-bootstrap` (notice `@` in front). Or maybe you are just have an old npm version.

Share your package.json but I don't think there is anything wrong with the package we are publishing - you are probably installing the wrong thing.
