### ISSUE TITLE
Adjust visibility of fields / methods accessed by templates

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#541]
As of today we are accessing fields / methods in templates where those fields / methods are marked as `private`. This won't work with offline compilation which means that we need to make sure that all fields / methods accessed from templates are not private

**Comment by pkozlowski-opensource** [comment]
Here are some more details on what need to be done for each and every component:
* [ ] - make sure that all fields accessed from templates are public and not prefixed with `_`
* [ ] - make sure that all methods called from templates are public and not prefixed with `_`
* [ ] - if a directive is not exported all public methods called from a template need to be annotated with `@internal` in JSDoc
* [ ] - if a directive is exported all public methods not meant to be part of the public API need to be made private or annotated with `@internal` in JSDoc if used from templates.

At the end of the day the only private fields / methods need to be the ones that are _not_ accessed in a template.

**Comment by Foxandxss** [comment]
I can start by removing the underscores everywhere.

**Comment by pkozlowski-opensource** [comment]
> I can start by removing the underscores everywhere.

IMO it is better to do it on the widget-per-widget basis. Easier to review. I'm just sending an example PR for a carousel.

**Comment by pkozlowski-opensource** [comment]
#565 is an example of this for a carousel. Would be great if people could help out with other widgets.

**Comment by jnizet** [comment]
I'm on typeahead

**Comment by jnizet** [comment]
tooltip looks fine to me. I'm on timepicker.

**Comment by pkozlowski-opensource** [comment]
Components to take care of:

- [ ] Accordion
- [ ] Alert 
- [ ] Buttons
- [ ] Carousel 
- [ ] Collapse
- [x] Dropdown 
- [ ] Modal
- [ ] Pagination 
- [ ] Popover 
- [ ] Progressbar
- [ ] Rating 
- [ ] Tab 
- [ ] Timepicker 
- [ ] Tooltip 
- [x] Typeahead

**Comment by pkozlowski-opensource** [comment]
I believe that this one is fixed now. Thnx for all the awesome help @jnizet and @chenyuzhcy !
