### ISSUE TITLE
Progressbar: broken in IE11 with value always = 1

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#543]
Always generates progressbars with value=1

Screenshot from the demo:
![progress](https://cloud.githubusercontent.com/assets/8074436/17403768/75655d68-5a59-11e6-82b8-d69c28abd77d.png)

Generated html:
```html
<progress value="1" max="100" ng-reflect-value="50" ng-reflect-max="100"> ... </progress>
```

From ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress)):
- if the `max` is not set `value` should be between 0 and 1
- if the `max` is set `value` should be between 0 and `max`

So looks like this template causes the issue (from `progressbar.ts`):

```html
<progress [value]="getValue()" [max]="max" ... >
```

Because this seem to work:

```html
<progress [max]="max" [value]="getValue()"  ... >
```

Apparently after setting `value` to, say 50, IE limits it to 1, because `max` is not yet there.

Not sure if it's the best solution though

**Comment by pkozlowski-opensource** [comment]
Are you saying that order of attributes matter???

**Comment by maxokorokov** [comment]
@pkozlowski-opensource yep, it this case yes... so that's why I'm not sure what to do with this information yet :)

**Comment by pkozlowski-opensource** [comment]
Sight... IE... So it seems like it has some internal state and fails to update it properly.... If swapping order makes IE happy and doesn't hurt other browsers, let's make this change. I'm not sure we've got other way of controlling order of bindings...
