### ISSUE TITLE
Tab(Components) Nothing shows up

### ISSUE THREAD

**Issue by masaanli** [ng-bootstrap/ng-bootstrap#546]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
I added  the directive and precompile to my main component app.component.ts.

Then i added in 1 component this, but nothing shows up. I can see the HTML if i 'Inspect Element':
`<ngb-tabset>
  <ngb-tab title="Simple">
    <template ngbTabContent>
      <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth
      master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh
      dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum
      iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
    </template>
  </ngb-tab>
  <ngb-tab>
    <template ngbTabTitle><b>Fancy</b> title</template>
    <template ngbTabContent>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid.
      <p>Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table
      craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl
      cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit. Keytar helvetica VHS salvia
      yr, vero magna velit sapiente labore stumptown. Vegan fanny pack odio cillum wes anderson 8-bit, sustainable jean
      shorts beard ut DIY ethical culpa terry richardson biodiesel. Art party scenester stumptown, tumblr butcher vero
      sint qui sapiente accusamus tattooed echo park.</p>
    </template>
  </ngb-tab>
  <ngb-tab title="Disabled" [disabled]="true">
    <template ngbTabContent>
      <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth
      master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh
      dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum
      iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
    </template>
  </ngb-tab>
</ngb-tabset>`

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
rc4

ng-bootstrap:
alpha 1
Bootstrap:
alpha 3

P.s. im using the Angular CLI, but that doesn't matter in this one I think.

**Comment by pkozlowski-opensource** [comment]
Did you list relevant directives in the `directives` section of your component? You should have something like his:

```
@Component({
  selector: '...',
  template: '...',
  directives: [NGB_DIRECTIVES]
})
export class MyComponent { }
```

Make sure that you check code on our demo pages.

**Comment by masaanli** [comment]
@pkozlowski-opensource Yes having that only declared in my main app.component. I was thinking if I added the NGB_DIRECTIVES there it must be accesible everywhere right?

I added the NGB_DIRECTIVES to the component directives and it worked. 

But what is the purpose of the app.component.ts NGB_DIRECTIVES and NGB_PRECOMPILE then?
Because if I deleted them from my app.component.ts it still works.

`
import { Component } from '@angular/core';
import { ROUTER_DIRECTIVES} from '@angular/router';
import { NGB_DIRECTIVES, NGB_PRECOMPILE } from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.scss'],
  directives: [ROUTER_DIRECTIVES, NGB_DIRECTIVES],
  precompile: [NGB_PRECOMPILE],
})
export class AppComponent {
  title = 'app works!';
}
`

**Comment by pkozlowski-opensource** [comment]
> I was thinking if I added the NGB_DIRECTIVES there it must be accesible everywhere right?

Nope, this is not how Angular2 works - in rc.4 you need to list used directives in each and every component. This will change in rc.5 - as soon as it is out we will be releasing alpha.2 with updated installation / usage instructions. The good news is that it is going to get simpler!

> But what is the purpose of the app.component.ts NGB_DIRECTIVES and NGB_PRECOMPILE then?
Because if I deleted them from my app.component.ts it still works.

It is kind of a longer story and more of an Angular 2 question rather than this lib question. But it all doesn't matter too much since things are going to change in rc.5, as hinted above.

> I added the NGB_DIRECTIVES to the component directives and it worked.

Glad you got it working. I'm going to close it then. Stay tuned for alpha.2 release and updated install instructions.
