### ISSUE TITLE
boolean inputs: handle them all the same way

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#550]
Maybe I'm missing something. If so, pardon me.

Reading the source code of NgbProgressbar, I noticed that the boolean inputs are of type `boolean | string`, and that a method is used to transform this value to a boolean (where the empty string is returned as true) to use it in the template.

My guess is that it's designed this way to allow using 

    <ngb-progressbar striped></ngb-progressbar>

instead of the more verbose 

    <ngb-progressbar [striped]="true"></ngb-progressbar>. 

But the boolean inputs in the other components don't use the same strategy, making the library inconsistent.

If there is no reason for progress bar to be different from all the other ones, then it should be modified. Otherwise, all the other ones should be modified. Anyway, a comment on the `toBoolean` method would be helpful to understand what's going on.

If my guess on the rationale of this design is correct, my vote would be to use boolean everywhere. It makes the usage a bit more verbose, but also clearer. It makes the component code simpler, lighter and more obvious. And there is less chance of introducing another incoherence in future components.

**Comment by pkozlowski-opensource** [comment]
> Maybe I'm missing something. 

You are not!

> My guess is that it's designed this way to allow using ... instead of the more verbose...

Correct.

> But the boolean inputs in the other components don't use the same strategy, making the library inconsistent.

Yes, we've got the same issue for numbers, BTW.

As for question regarding what we should do to be consistent - I don't know. My hope was that we can get some sort of solution from the core, see: #8968. BTW, material folks got the same problem and hence this issue.

> my vote would be to use boolean everywhere. It makes the usage a bit more verbose, but also clearer.

I'm fine with removing all the type conversion "magic" till we've got a good pattern for this in the Angular2 itself.

**Comment by jnizet** [comment]
Regarding the numbers, there are several issues:

1. some components (like rating) accept a `number`, others (like pagination) accept a `number | string`, and use `toInteger()` to coerce the value to an integer
2. `toInteger()` actually does two things: transform strings to numbers, and transform decimal numbers to integers. The intent is not always very clear. For example, the intent in pagination seems to have both transformations applied, whereas in NgbTime, the intent seems to just transform the potentially decimal or null numbers into integers. 
3. In the components, like rating or progressbar, which have inputs of type number, the spec and/or the demo *sometimes* uses `value="50"` instead of `[value]="50"` to provide the input. The actual value of the input in the component, which is supposed to be a number, is thus a actually a string. 

Even if it happens to work, I think we should discourage the use of `value="50"` and promote the use of `[value]="50"`, for two reasons:

 - changing the code to use a variable instead of a literal value is easier
 - that happens to work fine with numbers, but it fails if done with booleans, because the string `'false'` is truthy. 

I would thus only use `value="..."` without brackets for string inputs, and use brackets everywhere else. 

The changes would thus be:

- use boolean for boolean inputs, and remove the string to boolean magic
- use `[foo]="true"` or `[foo]="false"`, and not `foo` or `foo="true"`
- use number for number inputs, and don't rely on the string to integer magic
- use `[foo]="50"` and not `foo="50"`
- keep using toInteger() in places where we really have string inputs that must be transformed to integers, and where we have number inputs that must be integers.

Do you guys agree with that?

**Comment by wesleycho** [comment]
I'm in favor of all these changes. Simplifies the internals, and simplifies the API.

**Comment by pkozlowski-opensource** [comment]
@jnizet agreed with the proposed changes. Let's remove all the magic around boolean / number handling

**Comment by pkozlowski-opensource** [comment]
Fixed in 190b7ecc680cf077896acc7b4347a9c801aced8a and f49fb089cf8aa29f783a409dd6cf96e42fd8468a
