### ISSUE TITLE
Custom.scss

### ISSUE THREAD

**Issue by masaanli** [ng-bootstrap/ng-bootstrap#551]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Link to minimally-working plunker that reproduces the issue:
**-**

### Version of Angular, ng-bootstrap, and Bootstrap:
There is an custom.scss added where u can place the variables but then customized. But the problem here is, that this is a strange approach right, because normally you will use a reference to a node_modules file.

What i mean is, the custom.scss file is inside a node_modules, node_modules aren't checked in in Source Control / Repository.

Is there any other way to, suggested way?

Future, is there a Gitter or Slack channel for Questions?

Angular:
**RC4**

ng-bootstrap:
**Alpha 1**

Bootstrap:
**Alpha 3**

**Comment by pkozlowski-opensource** [comment]
We don't have any `custom.scss` file in this repo. Even more - we don't have any `.scss` other than `app.scss` - but this one is for our demo app, not for library users.

I think that you are miss-directing your question.
