### ISSUE TITLE
error TS7006: Parameter 'result' implicitly has an 'any' type for typeahead directives

### ISSUE THREAD

**Issue by bassjobsen** [ng-bootstrap/ng-bootstrap#553]
I got the following error when using `1.0.0-alpha.1`; commenting out the typeahead directives or switiching back to `1.0.0-alpha.1` solves it:

> ] node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead-window.d.ts(6,17): error TS7006: Parameter 'result' implicitly has an 'any' type.
> [1] node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead-window.d.ts(7,56): error TS7006: Parameter 'result' implicitly has an 'any' type.
> [1] node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead.d.ts(22,22): error TS7006: Parameter 'value' implicitly has an 'any' type.
> [1] node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead.d.ts(31,23): error TS7006: Parameter 'value' implicitly has an 'any' type.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.0.0-rc.4

ng-bootstrap: ^1.0.0-alpha.1

Bootstrap: 4.0.0-alpha.3

**Comment by bassjobsen** [comment]
@pkozlowski-opensource thanks!

**Comment by pkozlowski-opensource** [comment]
All the credit goes to @jnizet !

**Comment by hswolf** [comment]
@pkozlowski-opensource @jnizet  Hi, and thank you, I see that this issue is fixed, but wonder when it will be on npm?

**Comment by icfantv** [comment]
@hswolf, I believe we intend to release tomorrow.  That said, please exercise patience as we are all volunteers.

**Comment by hswolf** [comment]
@icfantv I got it, thank you.
