### ISSUE TITLE
Tests: migrate to TestBed

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#563]
`TestComponentBuilder` is deprecated and will be removed in rc.6. We need to migrate to  `TestBed`. Check https://github.com/angular/angular/pull/10621 for more details.

**Comment by pkozlowski-opensource** [comment]
I've just opened a PR that can serve as an example for migration: #566

If anyone from the community would like to help out here please send a single PR per component. Thnx!

**Comment by sendilkumarn** [comment]
I will take components from 
Accordion / Alerts / Buttons / Carousel / Collapse and Dropdown. 

@wesleycho let me know if you already started in any of these.

**Comment by wesleycho** [comment]
I'm recovering from coming back home from Europe (9 hour time difference), so don't wait on me :) .

**Comment by pkozlowski-opensource** [comment]
Components to take care of:

- [x] Accordion
- [ ] Alert 
- [ ] Buttons
- [ ] Carousel 
- [ ] Collapse
- [ ] Dropdown 
- [ ] Modal
- [ ] Pagination 
- [ ] Popover 
- [x] Progressbar
- [ ] Rating 
- [ ] Tab 
- [ ] Timepicker 
- [ ] Tooltip 
- [ ] Typeahead

**Comment by jnizet** [comment]
I started working on typeahead, but it's a big one, and it's time to go to bed now :-)
Bad news: I was hoping to be able to get rid of the `whenStable()` calls, but tests still don't pass without them.

**Comment by sendilkumarn** [comment]
Lets me finish off the remaining three.

**Comment by pkozlowski-opensource** [comment]
@sendilkumarn I'm on tabs atm. Let me push a PR for this as there is an even simpler pattern :-)

**Comment by sendilkumarn** [comment]
Okay then let me wait for that.

**Comment by pkozlowski-opensource** [comment]
@sendilkumarn see #579

**Comment by sendilkumarn** [comment]
got it 👍

**Comment by sendilkumarn** [comment]
Why can't we move `createTestComponent` into `util.ts` file and then use it.

I will also remove `async` from other tests. leave only `fakeAsync`. This will `standardize` the list

**Comment by wesleycho** [comment]
It cannot be moved to util.ts, that is a script of utils bundled into the library itself. We would need to create a separate testUtil.ts or something like that. We should abstract that out, although I think @pkozlowski-opensource mentioned something about having a better pattern in mind.

**Comment by pkozlowski-opensource** [comment]
Yep, we need to have a set of test utils. But let's think of it after we are done with migration to `TestBed`.

**Comment by pkozlowski-opensource** [comment]
> I will also remove async from other tests. leave only fakeAsync

Please do @sendilkumarn

**Comment by sendilkumarn** [comment]
Can you merge tabset into master ?

**Comment by pkozlowski-opensource** [comment]
> Can you merge tabset into master ?

@sendilkumarn done

**Comment by sendilkumarn** [comment]
@pkozlowski-opensource done

**Comment by sendilkumarn** [comment]
@wesleycho Agree, that makes sense. 

But that part is redundant as of now.

**Comment by pkozlowski-opensource** [comment]
@sendilkumarn @jnizet thnx so much for helping out with this issue, you guys did awesome job here! I wouldn't expect that we can this sorted out so fast. Thnx!

I'm going to do another pass on all the test tomorrow with a fresh eye and will close this issue then.

**Comment by sendilkumarn** [comment]
Thanks @pkozlowski-opensource  👍
