### ISSUE TITLE
Move to NgModule in demo

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#564]
As of today some of our demo components are still using `directives` property of the `@Component` decorator. Ex.: https://github.com/ng-bootstrap/ng-bootstrap/blob/906624f28b335e3ccf2a36ba27cf360918072b00/demo/src/app/components/accordion/accordion.component.ts#L29

This will be illegal in RC6 so we need to come up with a good modules layout for our demo site.

**Comment by Foxandxss** [comment]
I can do that today.
