### ISSUE TITLE
demo page steals the back button

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#577]
Not sure if it's a bug with the demo or with Angular, but when we land on the demo web site using the root URL (https://ng-bootstrap.github.io/) and not the home page URL (https://ng-bootstrap.github.io/#/home), there is no way to use the back button anymore: it goes back to the root URL, which immediately redirects to the home page URL.

**Comment by pkozlowski-opensource** [comment]
I would say this is sth router + redirect specific since I can see the same effect with https://ng-bootstrap.github.io/#/components

**Comment by jnizet** [comment]
I filed https://github.com/angular/angular/issues/10706 on angular

**Comment by pkozlowski-opensource** [comment]
This was fixed upstream, I've tested this with the latest version from angular master repo. We will get the fix as soon as rc6 is out.
