### ISSUE TITLE
Dropdown Missing Features

### ISSUE THREAD

**Issue by scttcper** [ng-bootstrap/ng-bootstrap#584]
Howdy,

Dropdown is missing some features from the jquery bootstrap library
- [ ] Support input/textarea in dropdown (click without closing)
- [ ] Arrow key navigation, ui-bootstrap handles this incorrectly and the page still scrolls when using arrows.
- [ ] Not close when clicking a disabled dropdown element
- [ ] Close on outside touch/tap (mobile). Current document:click is mouse only and IMO not a great option as it fires for every click for every dropdown active on your page. It also makes it more difficult to control what to auto close for as it loses track of where clicks are happening inside the dropdown vs outside.

I've got some of these features on my own implementation that I no longer want to maintain and would rather use this project.
https://scttcper.github.io/ng2-bs-dropdown

I can make a pull request, but pretty much all of them require moving away from document:click towards another solution. I've placed a div with .dropdown-backdrop (like jquery bootstrap) that captures both taps and clicks when the dropdown is open, however this also catches the click and prevents clicks on lower levels from happening. So on 

``` html
<button>Outside</button><div ngbDropdown [open]="true"></div>
```

the button won't be clicked because the dropdown-backdrop captures the click,  so button requires two clicks to activate. It could be possible to show the backdrop only when a touchstart is detected that way it's only shown for mobile users.

Let me know your thoughts.

**Comment by pkozlowski-opensource** [comment]
@scttcper glad to hear that you are up to the contributing here, I think this is a win-win solution.

Now, all the points you are raising are valid and I would be more than happy to work with you on addressing those. Making this directive more robust was on my TODO list anyway.

As for the technical solution - I didn't spend enough time on this directive to know what would work best. Maybe we should start iterating on small bits to get the ball rolling? For example I would be really curious what you propose for the `disabled` items as currently those are just `CSS` classes and pretty much user-driven.

My biggest worry is to make sure that this directive is flexible enough so users have full control over dropdown menu content.

**Comment by scttcper** [comment]
Splitting clicks into inside and outside would be first step.
Disabled clicks I had on a handleInsideClick checked for the classname disabled on the element clicked. This feature could be optional for sure, users could capture click and stop propagation themselves.

Arrow keys requires knowledge of child elements from the dropdown.

bootstrap v4 has it defined here as a jquery selection inside dropdown
https://github.com/twbs/bootstrap/blob/3a0fed1590c8abc166bb8ed2c3853396dbe3801d/js/src/dropdown.js#L54-L55

ui-bootstrap selects their dropdownMenu directive and then selects the `<a>` elements under that.
https://github.com/angular-ui/bootstrap/blob/6bad7592b9d7838099d920c98cddc7cb13933c9c/src/dropdown/dropdown.js#L156-L158

so a dropdown menu directive could help there.

**Comment by marcalj** [comment]
@scttcper  Please add ```dropdown-append-to-body``` to the list :)

**Comment by PEsteves8** [comment]
I have autoClose=false and I'm using .toggle and .close to manually so that I can enter other sections of the dropdown and only close in the section that I have to. However, I still want to make it close if the click is outside the component.

So to be able to do that, I'm using:
```
host: {
        '(document:click)': 'onClick($event)',
    }
```

and

```
onClick(event:any) {
        if (!this._elementRef.nativeElement.contains(event.target))
            this.ngbDropdownRef.close()
    }
```

Ideally something like [autoClose]="'onClickOutside'", would probably be best than having to had this code. Just another suggestion. :)

**Comment by scttcper** [comment]
As far as I can tell everything I wanted is now supported or can be added on top of the dropdown component. append-to-body is still not supported, but I don't understand the use case for that. Should open a separate task for that since multiple elements need append to body for people coming from angular-ui. I'll close this task.

**Comment by MrCroft** [comment]
Does this mean that it now also offers the option to auto close on outside click only?

**Comment by scttcper** [comment]
@MrCroft I think https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/dropdown/dropdown.ts#L26-L29 does that.
Or you can capture the event on elements inside your dropdown.
(click)="$event.stopPropagation()"

**Comment by MrCroft** [comment]
@scttcper nope, that's still just a boolean. Meaning it doesn't close at all when set to false.
I know it's something very easy to do ourselves, it's not a deal breaker... it would have just been nice to be offered as an option out of the box. Like ng 2-bootstrap does. However, ng2-bootstrap has other issues, and people from the angular gitter room advised me to use @ng-bootstrap/ng-bootstrap.

**Comment by pkozlowski-opensource** [comment]
@scttcper thnx for coming back to us on this one - glad to hear that things work for you. Feel free to open separated, focused issues if you feel like we could add more.

@MrCroft feel free to open a separate issue for an additional option to distinguish outside vs. internal clicks. This should be easy to add.

More generally we want to have this library shine so if you guys see any glitches or things to improve please open issues (or better yet - send PRs :-))

**Comment by forrestab** [comment]
@MrCroft I couldn't find it, but did you create a separate issue this yet?

**Comment by MrCroft** [comment]
@forrestab 
Sorry, it seems that I actually didn't create one.
Did it now: #1022

**Comment by forrestab** [comment]
@MrCroft, glad I saw your response in time, I was in the process of creating one too.

**Comment by koshevy** [comment]
> Splitting clicks into inside and outside would be first step.
> Disabled clicks I had on a handleInsideClick checked for the classname disabled on the element clicked. This feature could be optional for sure, users could capture click and stop propagation themselves.
> 
> Arrow keys requires knowledge of child elements from the dropdown.
> 
> bootstrap v4 has it defined here as a jquery selection inside dropdown
> https://github.com/twbs/bootstrap/blob/3a0fed1590c8abc166bb8ed2c3853396dbe3801d/js/src/dropdown.js#L54-L55
> 
> ui-bootstrap selects their dropdownMenu directive and then selects the `<a>` elements under that.
> https://github.com/angular-ui/bootstrap/blob/6bad7592b9d7838099d920c98cddc7cb13933c9c/src/dropdown/dropdown.js#L156-L158
> 
> so a dropdown menu directive could help there.

[Here](https://github.com/ng-bootstrap/ng-bootstrap/issues/631) I found mention of this ticket sounds as "Yes, this is already tracked in #584". But there is no actually results of **"Arrow key navigation"** feature proposal. And both issues are closed.

What is result? Is this feature has to be supported, or not?

**Comment by maxokorokov** [comment]
@koshevy hmm, I suppose there is an #1998 that matches. And as for PRs #2785 and #2683

**Comment by koshevy** [comment]
> @koshevy hmm, I suppose there is an #1998 that matches. And as for PRs #2785 and #2683

@maxokorokov Thank you for your answer! Now it's all clear.
