### ISSUE TITLE
Analytics + router broken

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#591]
It looks like I've broken Google analytics when we navigate between rotues. Probably happened as part of the RC5 migration.

**Comment by icfantv** [comment]
I'd be willing to bet that it's angulartics

**Comment by pkozlowski-opensource** [comment]
> I'd be willing to bet that it's angulartics

Yes and no... The problem is that it is not updated to modules / RC5 and we are hacking around it anyway... So I'm less and less excited about using it at all...

Anyway, the root cause is that it seems like in RC5 providers specified on a module level are not instantiated until those are injected _somewhere_. In this sense providers are lazy-instantiated... I don't recall exactly how it worked in RC4 but here we are with the change... 

I'm going to send a PR that injects `Angulartics2GoogleAnalytics` into the `AppComponent` so it is instantiated. But I believe that in the longer run we need to update to a new version of angulartics or drop its usage altogether.

**Comment by icfantv** [comment]
@pkozlowski-opensource, ok, i'll investigate that on my end.

**Comment by pkozlowski-opensource** [comment]
@icfantv I've sent a PR with a work around - #599

**Comment by icfantv** [comment]
They have not cut a new release yet and are still building against RC2.
