### ISSUE TITLE
Drag and Drop feature

### ISSUE THREAD

**Issue by ufoscout** [ng-bootstrap/ng-bootstrap#595]
Hi everybody,

I wonder if you would mind adding drag and drop support to this library.
We have it implemented in our angular dart UI library (https://github.com/akserg/angular.dart.ui) and, even if not strictly related to bootstrap, it proved to be a lovely and nice to have feature for a UI library.
The implementation is based on HTML5 features with no external dependencies.
If you agree with it, I could prepare a PR. 

PS: unluckily the drag&drop demo of the dart implementation is not available any more :(

**Comment by icfantv** [comment]
@ufoscout, this is probably going to be far above and beyond what we would be able to support and beyond the scope of this library.  As with the ng1 version, we try to stick with the same components supported by Bootstrap (calendar and a few others notwithstanding).

There are DnD libraries out there for ng2 - but I cannot speak to their level of activity.  I can say that there have been some fairly significant changes in the ng2 RCs as they've been released so one would really need to be on top of things to ensure any ng2 library is implemented correctly.

I'll defer to @pkozlowski-opensource to make the final decision here, but I'm pretty sure I know what he's going to say.

**Comment by wesleycho** [comment]
A drag and drop widget should probably be a standalone library - the purpose of this library is for supporting components that make use of Bootstrap for CSS, and dragging and dropping is not something unique to users of Bootstrap.

If someone doesn't happen to do it in the next couple of months, it may be something that I am interested in doing and open sourcing, as I have been working in this realm recently & anticipate having to create if we indeed start a serious ng2 project at work in the next month or two.

Going to close this as out of scope.
