### ISSUE TITLE
Hello, how to use NgbdModal? any demo? thx

### ISSUE THREAD

**Issue by bolota** [ng-bootstrap/ng-bootstrap#605]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:

ng-bootstrap:

Bootstrap:

**Comment by pkozlowski-opensource** [comment]
Modal is not finished yet: #3.

Hopefully we are going to land support for modals early next week.

**Comment by JunusErgin** [comment]
Here is my workaround until the modal is finished:

Include `NgbModalWindow` to your directives and import it `import {NgbModalWindow} from '@ng-bootstrap/ng-bootstrap/modal/modal_window';`

Now, you can use the modal with its directive and trigger it with *ngIf:
```
<ngb-modal-window *ngIf="showModal">
   <h1>Hello</h1>
   <button (click)='showModal=false;'>Close</button>
</ngb-modal-window>
```

Keep in mind that you have to init `showModal` somewhere.

**Comment by pkozlowski-opensource** [comment]
@JunusErgin thnx for sharing your tip with the rest of the library users!

FYI I'm on the modal as we speak, we are a couple of days away from having a nice modal as service :-)

**Comment by bolota** [comment]
thanks, it s working, have a nice day!!!!
