### ISSUE TITLE
Install ng-bootstrap for rc.5 Visual Studio

### ISSUE THREAD

**Issue by tomcrusader** [ng-bootstrap/ng-bootstrap#607]
I'm trying to decipher if ng-bootstrap is ready for Angular RC 5 or not - looks like the latter.

Using Visual Studio I've tried to add ng-bootstrap to my package.json. Two major versions show up: 

- 0.46.0
- 1.0.0-beta.2

But none of these install properly:

> npm ERR! No compatible version found: @ng-bootstrap/ng-bootstrap@0.46.0
> npm ERR! Valid install targets:
> npm ERR! 1.0.0-alpha.2, 1.0.0-alpha.1, 1.0.0-alpha.0

So where are we at with RC 5 in reality? Is there no pre-version I can try out through npm or elsewhere?

**Comment by Foxandxss** [comment]
You need to use `1.0.0-alpha.2`. Is not 0.46.0 nor beta.2.

**Comment by pkozlowski-opensource** [comment]
@Foxandxss is right. Here is what you get by running `npm info @ng-bootstrap/ng-bootstrap`:

> { name: '@ng-bootstrap/ng-bootstrap',
  description: 'Angular 2 powered Bootstrap',
  'dist-tags': { latest: '1.0.0-alpha.2' },
  versions: [ '1.0.0-alpha.0', '1.0.0-alpha.1', '1.0.0-alpha.2' ],
  maintainers: [ 'ng-bootstrap <foxandxss@gmail.com>' ],
  time: 
   { modified: '2016-08-10T11:46:32.412Z',
     created: '2016-07-07T17:44:48.756Z',
     '1.0.0-alpha.0': '2016-07-07T17:44:48.756Z',
     '1.0.0-alpha.1': '2016-07-29T10:21:16.716Z',
     '1.0.0-alpha.2': '2016-08-10T11:46:32.412Z' },
  homepage: 'https://github.com/ng-bootstrap/ng-bootstrap#readme',
  keywords: [ 'Angular 2 Angular2 Bootstrap autocomplete accordion alert buttons carousel collapse dropdown pagination popover progressbar rating tabset timepicker tooltip typeahead' ],
  repository: 
   { type: 'git',
     url: 'git+https://github.com/ng-bootstrap/ng-bootstrap.git' },
  author: 'https://github.com/ng-bootstrap/ng-bootstrap/graphs/contributors',
  bugs: { url: 'https://github.com/ng-bootstrap/ng-bootstrap/issues' },
  license: 
   { type: 'MIT',
     url: 'https://raw.githubusercontent.com/ng-bootstrap/ng-bootstrap/master/LICENSE' },
  readmeFilename: 'README.md',
  version: '1.0.0-alpha.2',
  main: 'index.js',
  'jsnext:main': 'esm/index.js',
  peerDependencies: 
   { '@angular/core': '^2.0.0-rc.5',
     '@angular/common': '^2.0.0-rc.5',
     '@angular/forms': '^0.3.0' },
  scripts: {},
  dist: 
   { shasum: '5f5ed69fd1cd1c16f4ab8abf3b193947340982a0',
     tarball: 'https://registry.npmjs.org/@ng-bootstrap/ng-bootstrap/-/ng-bootstrap-1.0.0-alpha.2.tgz' },
  directories: {} }

Check our install instructions: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#installation

And yes, we are fully compatible with angular 2.0.0-rc.5 (and even 2.0.0-rc.6 when it is out :-))
