### ISSUE TITLE
Documentation for modal

### ISSUE THREAD

**Issue by rolandoldengarm** [ng-bootstrap/ng-bootstrap#619]
There is no documentation for the [modal component](https://github.com/ng-bootstrap/ng-bootstrap/tree/master/src/modal). It is not listed on the demo site.

**Comment by wesleycho** [comment]
It is not ready for prime time yet - keep an eye out for #609.

**Comment by pkozlowski-opensource** [comment]
Closing as modal progress is tracked in #3 and we've got a WIP PR already in #609.
