### ISSUE TITLE
Cannot load ng-bootstrap using systemjs

### ISSUE THREAD

**Issue by kpociecha** [ng-bootstrap/ng-bootstrap#623]
# Bug in ng-bootstrap
Version: 1.0.0-alpha.2
In generated js files in index.js we have require('./accordion'); and this should point to ./accordion/index,js
and in the file ./accordion/index,js we have again require('./accordion'); and it should point to /accordion.js.

# My problem
By default systemjs resolves require('./accordion'); as accordion.js and it fails because there is no file ng-bootstrap/accordion.js. When I add mapping require('./accordion'); -> ng-bootstrap/accordion/index.js I have circular dependency because require('./accordion'); is used in  ./accordion/index,js to load ./accordion.js. file.

**Comment by pkozlowski-opensource** [comment]
It sounds like you are trying to use SystemJS with loading individual files and it is never a good idea. If you just experimenting use the UMD bundle that we are providing.

Unless you are using SystemJS builder? In this case what wold be your suggestion for "fixing" it? I can think of using `require('accordion/index')` in our top-level `index.js`, not sure if this would fix your problem though....

In any case we can't investigate issues with all the possible bundlers as the scene is quite fragmented and in the miserable state atm. Of course we are open to "fixing" things on our end if there is anything to fix and someone investigates pb / sends a PR.

**Comment by kpociecha** [comment]
Thanks for fast response. 
Changing imports in top-level index.js to require('./accordion/index') solves the problem so I will be more than happy if that change will be included in next release. For now I downgraded ng-bootstrap to version 1.0.0-alpha.1 and in the future I am planning to use Webpack.

**Comment by Ks89** [comment]
I lost more than an hour to trying to fix this problem. Finally, I found this post. Thank you fixed...But this was really really annoying and I though also to move to another library.
