### ISSUE TITLE
 Hide some tabs dynamically in the ngOnInit

### ISSUE THREAD

**Issue by masaanli** [ng-bootstrap/ng-bootstrap#632]
### Bug description:

Hide some tabs dynamically in the ngOnInit
I can already disable them but I want to hide them, is there a workaround for that or is it on planning?

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: RC5

ng-bootstrap:
Alpha 1

Bootstrap:
Alpha 3

**Comment by pkozlowski-opensource** [comment]
Just put `ngIf` around tabs you want to hide with whatever dynamic criteria you would like to have.
