### ISSUE TITLE
NgbModule bug (resolve)

### ISSUE THREAD

**Issue by Podkekette** [ng-bootstrap/ng-bootstrap#634]
Hi,

I want to use Ng Bootstrap to put some components on my Angular2 app.

When I add the "NgbModule"  in my main module and run the app the console tell me : 
"error: SyntaxError: Unexpected token <" 

I just add 2 directives in to diffrent tags.

Than you,
Laurent.

**Comment by ravipunjwani** [comment]
Hi Laurent,

Can you provide the stack trace provided in the console.

Probably anyone of your static files (which can be usually seen from the stack trace) are not being served correctly, instead your server would send out a decorated HTML response with some error message (like an ASP .Net server default error page).

In turn, angular would try to parse that file and find an HTML content, throwing an error on console and crashing the app.

**Comment by Podkekette** [comment]
Hi, thank you !

`Error: SyntaxError: Unexpected token <(…)(anonymous function) 
@ monitor:26ZoneDelegate.invoke 
@ zone.js:332Zone.run 
@ zone.js:225(anonymous function)
 @ zone.js:591ZoneDelegate.invokeTask 
@ zone.js:365Zone.runTask 
@ zone.js:265drainMicroTaskQueue 
@ zone.js:497ZoneTask.invoke 
@ zone.js:437`
This is the stack provided by the console.

**Comment by ravipunjwani** [comment]
Can you try clicking on (...) as I have noticed that sometimes it gives another level of stack trace which is different than this one, where you can see what app-files angular tried to load.

**Comment by Podkekette** [comment]
Oups sorry, I forgot ;). 

`Error: SyntaxError: Unexpected token <
	    at Object.eval (http://localhost:4672/js/app.module.js:17:22)
	    at eval (http://localhost:4672/js/app.module.js:56:4)
	    at eval (http://localhost:4672/js/app.module.js:57:3)
	Evaluating http://localhost:4672/@ng-bootstrap/ng-bootstrap
	Evaluating http://localhost:4672/js/app.module.js
	Evaluating http://localhost:4672/js/main.js
	Error loading http://localhost:4672/js/main.js(anonymous function) @ (index):26ZoneDelegate.invoke @ zone.js:332Zone.run @ zone.js:225(anonymous function) @ zone.js:591ZoneDelegate.invokeTask @ zone.js:365Zone.runTask @ zone.js:265drainMicroTaskQueue @ zone.js:497ZoneTask.invoke @ zone.js:437`

**Comment by ravipunjwani** [comment]
I think you are using systemjs. If yes, you have forgotten to add systemjs package.

Try adding following values in your systemjs.config.js:
1. '@ng-bootstrap': '../node_modules/@ng-bootstrap', in "map" variable.
2. '@ng-bootstrap/ng-bootstrap': { main: 'index.js', defaultExtension: 'js' } in "packages" variable

Hopefully it should work.

**Comment by Podkekette** [comment]
Yes I'm using systemJs. You were right, i didn't add ng-bootstrap in this file. I just did it : 404 errors for Bootstraps components :( 
`zone.js:101 GET http://localhost:4672/lib/@ng-bootstrap/ng-bootstrap/buttons.js 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:345Zone.scheduleMacroTask @ zone.js:282(anonymous function) @ zone.js:122send @ VM1370:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:607(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:332Zone.run @ zone.js:225(anonymous function) @ zone.js:591ZoneDelegate.invokeTask @ zone.js:365Zone.runTask @ zone.js:265drainMicroTaskQueue @ zone.js:497ZoneTask.invoke @ zone.js:437
(index):26 Error: Error: XHR error (404 Not Found) loading http://localhost:4672/lib/@ng-bootstrap/ng-bootstrap/buttons.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:4672/lib/zone.js/dist/zone.js:794:30)
	    at ZoneDelegate.invokeTask (http://localhost:4672/lib/zone.js/dist/zone.js:365:38)
	    at Zone.runTask (http://localhost:4672/lib/zone.js/dist/zone.js:265:48)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4672/lib/zone.js/dist/zone.js:433:34)
	Error loading http://localhost:4672/lib/@ng-bootstrap/ng-bootstrap/buttons.js as "./buttons" from http://localhost:4672/lib/@ng-bootstrap/ng-bootstrap/index.js(anonymous function) @ (index):26ZoneDelegate.invoke @ zone.js:332Zone.run @ zone.js:225(anonymous function) @ zone.js:591ZoneDelegate.invokeTask @ zone.js:365Zone.runTask @ zone.js:265drainMicroTaskQueue @ zone.js:497ZoneTask.invoke @ zone.js:437
zone.js:101 GET http://localhost:4672/lib/@ng-bootstrap/ng-bootstrap/collapse.js 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:345Zone.scheduleMacroTask @ zone.js:282(anonymous function) @ zone.js:122send @ VM1370:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:607(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:332Zone.run @ zone.js:225(anonymous function) @ zone.js:591ZoneDelegate.invokeTask @ zone.js:365Zone.runTask @ zone.js:265drainMicroTaskQueue @ zone.js:497ZoneTask.invoke @ zone.js:437
zone.js:101 GET http://localhost:4672/lib/@ng-bootstrap/ng-bootstrap/alert.js 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:345Zone.scheduleMacroTask @ zone.js:282(anonymous function) @ zone.js:122send @ VM1370:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:607(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:332Zone.run @ zone.js:225(anonymous function) @ zone.js:591ZoneDelegate.invokeTask @ zone.js:365Zone.runTask @ zone.js:265drainMicroTaskQueue @ zone.js:497ZoneTask.invoke @ zone.js:437
zone.js:101 GET http://localhost:4672/lib/@ng-bootstrap/ng-bootstrap/dropdown.js 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:345Zone.scheduleMacroTask @ zone.js:282(anonymous function) @ zone.js:122send @ VM1370:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:607(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:332Zone.run @ zone.js:225(anonymous function) @ zone.js:591ZoneDelegate.invokeTask @ zone.js:365Zone.runTask @ zone.js:265drainMicroTaskQueue @ zone.js:497ZoneTask.invoke @ zone.js:437
zone.js:101 GET http://localhost:4672/lib/@ng-bootstrap/ng-bootstrap/accordion.js 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:345Zone.scheduleMacroTask @ zone.js:282(anonymous function) @ zone.js:122send @ VM1370:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:607(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:332Zone.run @ zone.js:225(anonymous function) @ zone.js:591ZoneDelegate.invokeTask @ zone.js:365Zone.runTask @ zone.js:265drainMicroTaskQueue @ zone.js:497ZoneTask.invoke @ zone.js:437
zone.js:101 GET http://localhost:4672/lib/@ng-bootstrap/ng-bootstrap/pagination.js 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:345Zone.scheduleMacroTask @ zone.js:282(anonymous function) @ zone.js:122send @ VM1370:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:607(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:332Zone.run @ zone.js:225(anonymous function) @ zone.js:591ZoneDelegate.invokeTask @ zone.js:365Zone.runTask @ zone.js:265drainMicroTaskQueue @ zone.js:497ZoneTask.invoke @ zone.js:437
zone.js:101 GET http://localhost:4672/lib/@ng-bootstrap/ng-bootstrap/popover.js 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:345Zone.scheduleMacroTask @ zone.js:282(anonymous function) @ zone.js:122send @ VM1370:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:607(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:332Zone.run @ zone.js:225(anonymous function) @ zone.js:591ZoneDelegate.invokeTask @ zone.js:365Zone.runTask @ zone.js:265drainMicroTaskQueue @ zone.js:497ZoneTask.invoke @ zone.js:437
zone.js:101 GET http://localhost:4672/lib/@ng-bootstrap/ng-bootstrap/progressbar.js 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:345Zone.scheduleMacroTask @ zone.js:282(anonymous function) @ zone.js:122send @ VM1370:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:607(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:332Zone.run @ zone.js:225(anonymous function) @ zone.js:591ZoneDelegate.invokeTask @ zone.js:365Zone.runTask @ zone.js:265drainMicroTaskQueue @ zone.js:497ZoneTask.invoke @ zone.js:437
zone.js:101 GET http://localhost:4672/lib/@ng-bootstrap/ng-bootstrap/timepicker.js 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:345Zone.scheduleMacroTask @ zone.js:282(anonymous function) @ zone.js:122send @ VM1370:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:607(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:332Zone.run @ zone.js:225(anonymous function) @ zone.js:591ZoneDelegate.invokeTask @ zone.js:365Zone.runTask @ zone.js:265drainMicroTaskQueue @ zone.js:497ZoneTask.invoke @ zone.js:437
zone.js:101 GET http://localhost:4672/lib/@ng-bootstrap/ng-bootstrap/tabset.js 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:345Zone.scheduleMacroTask @ zone.js:282(anonymous function) @ zone.js:122send @ VM1370:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:607(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:332Zone.run @ zone.js:225(anonymous function) @ zone.js:591ZoneDelegate.invokeTask @ zone.js:365Zone.runTask @ zone.js:265drainMicroTaskQueue @ zone.js:497ZoneTask.invoke @ zone.js:437
zone.js:101 GET http://localhost:4672/lib/@ng-bootstrap/ng-bootstrap/carousel.js 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:345Zone.scheduleMacroTask @ zone.js:282(anonymous function) @ zone.js:122send @ VM1370:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:607(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:332Zone.run @ zone.js:225(anonymous function) @ zone.js:591ZoneDelegate.invokeTask @ zone.js:365Zone.runTask @ zone.js:265drainMicroTaskQueue @ zone.js:497ZoneTask.invoke @ zone.js:437
zone.js:101 GET http://localhost:4672/lib/@ng-bootstrap/ng-bootstrap/rating.js 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:345Zone.scheduleMacroTask @ zone.js:282(anonymous function) @ zone.js:122send @ VM1370:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:607(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:332Zone.run @ zone.js:225(anonymous function) @ zone.js:591ZoneDelegate.invokeTask @ zone.js:365Zone.runTask @ zone.js:265drainMicroTaskQueue @ zone.js:497ZoneTask.invoke @ zone.js:437
zone.js:101 GET http://localhost:4672/lib/@ng-bootstrap/ng-bootstrap/typeahead.js 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:345Zone.scheduleMacroTask @ zone.js:282(anonymous function) @ zone.js:122send @ VM1370:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:607(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:332Zone.run @ zone.js:225(anonymous function) @ zone.js:591ZoneDelegate.invokeTask @ zone.js:365Zone.runTask @ zone.js:265drainMicroTaskQueue @ zone.js:497ZoneTask.invoke @ zone.js:437
zone.js:101 GET http://localhost:4672/lib/@ng-bootstrap/ng-bootstrap/tooltip.js 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:345Zone.scheduleMacroTask @ zone.js:282(anonymous function) @ zone.js:122send @ VM1370:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:607(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:332Zone.run @ zone.js:225(anonymous function) @ zone.js:591ZoneDelegate.invokeTask @ zone.js:365Zone.runTask @ zone.js:265drainMicroTaskQueue @ zone.js:497ZoneTask.invoke @ zone.js:437`

**Comment by ravipunjwani** [comment]
You need to configure each module inside ng-bootstrap to support fully in your systemjs. Just add the below code in the systemjs.config.js.

```
  var ngBPackageNames = [
    'accordion',
    'alert',
    'buttons',
    'accordion',
    'carousel',
    'collapse',
    'dropdown',
    'modal',
    'pagination',
    'popover',
    'progressbar',
    'rating',
    'tabset',
    'timepicker',
    'tooltip',
    'typeahead'
    ];

    function packIndexNgB(pkgName) {
        packages['@ng-bootstrap/ng-bootstrap/' + pkgName] = { main: 'index.js', defaultExtension: 'js' };
    }

    ngBPackageNames.forEach(packIndexNgB);

```

Add the above given code right before this config declaration.
```
var config = { 
        map: map,
        packages: packages
    };
```

**Comment by Foxandxss** [comment]
We will release soon and make this easy again

**Comment by Podkekette** [comment]
Oh I did not realize I have to declare them like the angulars packages. Thank you ! I'll try now

**Comment by Podkekette** [comment]
It's working, thank you very much.. (My dropdown doesn't display :p)

**Comment by ravipunjwani** [comment]
Please change the issue status if works well!
Cheers! Happy angular/bootstrapp-ing

**Comment by Podkekette** [comment]
Hmmmm dropdown is not droping down

**Comment by Podkekette** [comment]
Any idea  ?

**Comment by ravipunjwani** [comment]
It's better creating another issue with description about dropdown problem. This issue suggests problem in loading app after installing `ng-bootstrap`.

In general, please add general support questions on stackoverflow, tagged with ng-bootstrap.
[https://github.com/ng-bootstrap/ng-bootstrap#getting-help]

**Comment by pkozlowski-opensource** [comment]
@Podkekette it is really hard to help with env-setup without full code example. I would say it is next to impossible to do it effectively. 

The best I can offer here is a plunker using SystemJS with working dropdown: https://plnkr.co/edit/98a7paMX9gB6rnPTtmhv?p=preview. This plunker uses a freshly-released alpha.3 but should work equally well with alpha.2. Have a look at this plunker and our demo site to compare to what you've got in your project. 

I'm afraid this is all we can say based on the information given so I'm going to close this one as a support request. Feel free to come back to us if / when you've got more info.
