### ISSUE TITLE
npm start ( demo error compilation )

### ISSUE THREAD

**Issue by webmobiles** [ng-bootstrap/ng-bootstrap#637]
### Bug description:
I've move the content of  ng-bootstrap/demo/src/  to  /src  angular2 project and when i run npm start: i get these errors:

ERROR in ./src/app/components/shared/api-docs/api-docs.component.ts
(2,18): error TS2307: Cannot find module '../../../../api-docs'.

ERROR in ./src/app/components/shared/api-docs/api-docs-class.component.ts
(2,18): error TS2307: Cannot find module '../../../../api-docs'.

ERROR in ./src/app/components/modal/demos/basic/modal-basic.ts
(3,9): error TS2305: Module '"/Users/myuser/dircrm-app/node_modules/@ng-bootstrap/ng-bootstrap/index"' has no exported member 'NgbModal'.

ERROR in ./src/app/components/modal/demos/basic/modal-basic.ts
(3,19): error TS2305: Module '"/Users/myuser/dircrm-app/node_modules/@ng-bootstrap/ng-bootstrap/index"' has no exported member 'ModalDismissReasons'.

ERROR in ./src/vendor.ts
Module not found: Error: Cannot resolve module 'prismjs/themes/prism.css' in /Users/myuser/dircrm-app/src
 @ ./src/vendor.ts 13:0-35

ERROR in ./src/app/components/accordion/demos/index.ts
Module not found: Error: Cannot resolve module 'prismjs' in /Users/myuser/dircrm-app/src/app/components/accordion/demos
 @ ./src/app/components/accordion/demos/index.ts 9:14-74

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2 rc5

ng-bootstrap: 1.0.0-alpha.2 

Bootstrap: ^4.0.0-alpha.3

**Comment by Foxandxss** [comment]
And why are you doing that?

**Comment by webmobiles** [comment]
I'm just trying to see demo page in action with the components in my local web

**Comment by Foxandxss** [comment]
Clone the repo itself, build the demo (there is a command in the gulp for that) and then grab `demo/dist` and use it locally.

**Comment by webmobiles** [comment]
thanks ; i've understood;  i ll try frist with gulp, the reason was i had a starter with webpack, i'm was trying to merge it ,  the starter: https://github.com/preboot/angular2-webpack

**Comment by Foxandxss** [comment]
Thanks for using my starter btw.

The reason that won't work is because the demo app needs to be built using the library sources as well, so you can't "cut" half of it and move it elsewhere.

**Comment by webmobiles** [comment]
ah you're the author , thanks, after got a crazy with angular-cli version webpack, i've found the starter for webpack that is working very well. I dont use anymore angular-cli.

**Comment by webmobiles** [comment]
sorry but i've got this error , after to do npm install,  and gulp build:demo
( what does mean exactly: grab demo/dist ?  maybe i need that)

ts-loader: Using typescript@1.8.10 and /Users/myuser/ng-bootstrap/tsconfig.json                                                                       30% 1/3 build modulesModuleBuildError: Module build failed: Error: Typescript emitted no output for /Users/myuser/ng-bootstrap/demo/src/polyfills.ts
    at Object.loader (/Users/myuser/ng-bootstrap/node_modules/ts-loader/index.js:456:15)

**Comment by Foxandxss** [comment]
Ok, that is a weird error.

**Comment by webmobiles** [comment]
I don't need really poly fill   , i use just modern browser, where i can commet that line , in order to not load polyfills.ts ?

**Comment by Foxandxss** [comment]
You need that. Is not about Browsers, those are polyfills that angular 2 needs.

**Comment by webmobiles** [comment]
can this be produced for my version of node and npm?  sometimes I suspect is that; what about if i install same version node and npm you use ?  i'd like to advance with ng-bootstrap, thanks

**Comment by pkozlowski-opensource** [comment]
@webmobiles I'm not sure what you are trying to do :-( If you want to just build our demo page locally you should check it out and follow our dev instructions: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/DEVELOPER.md - this includes node / npm version.

I'm going to close this now as a support question but feel free to continue the discussion in there if you need further info.

**Comment by webmobiles** [comment]
thanks  with the guide is working good.
