### ISSUE TITLE
Use template URL for modals

### ISSUE THREAD

**Issue by natcohen** [ng-bootstrap/ng-bootstrap#638]
How can I open a modal of a different template URL/TS?

I'm sure it's possible but I can't find how in the documentation...

**Comment by pkozlowski-opensource** [comment]
In Angular 2 there is no such thing as "free flying markup snippet". The only markup can be embedded as part of a component's template or inside a `<template>`  tag. Moreover pointing to an arbitrary markup string would mean that one can't effectively use offline compilation as a compiler would have to shipped to a browser. 

So this is sth that is not supported in Angular 2 itself and as such we can't support it here.

**Comment by natcohen** [comment]
@pkozlowski-opensource Wow that's a very bad news! Does it mean that the template as to be part of the same template/TS?

All angular2's recommendations point to more fragmentation (number of files) so how can we achieve that?

**Comment by Foxandxss** [comment]
You can't.

**Comment by natcohen** [comment]
@Foxandxss Can't we reuse modal code and have separate component? I thought it was the main goal of modals (code reuse, separate component, ...)!

**Comment by pkozlowski-opensource** [comment]
> All angular2's recommendations point to more fragmentation (number of files) so how can we achieve that?

If you've got a very large template to be displayed in a modal you can create a dedicated component for this. Then you can open a template like `<template #modalContent><my-component-with-content></my-component-with-content></template>`

In the future we might open API where you could pass a component type to be opened but it gets complicated for situations where components got inputs / outputs.

**Comment by natcohen** [comment]
@pkozlowski-opensource Thanks! With the dedicated component, how can I pass variables?

**Comment by pkozlowski-opensource** [comment]
> With the dedicated component, how can I pass variables?

Like so? Templates capture context of the owning component so you've got access to all members defined on a component.

```html
<template #modalContent>
    <my-component-with-content [var1]="val1Exp"></my-component-with-content>
</template>
```

Unless I'm misunderstanding question...

**Comment by natcohen** [comment]
@pkozlowski-opensource I think you got it right... Will try that later! Thanks again

**Comment by natcohen** [comment]
Closing it as it seems impossible in Angular 2

**Comment by natcohen** [comment]
@pkozlowski-opensource I'm having difficulties using another component with templateURL (inside the component). Whenever I use this:

```
<template #modalContent>
    <my-component-with-content></my-component-with-content>
</template>
```

and in my component:

```
@Component({
    selector: 'my-component-with-content',
    templateUrl: 'components/my-component-with-content.html'
})
```

The component gets initialized but nothing shows up in the modal!

**Comment by pkozlowski-opensource** [comment]
@natcohen please share a plunker with a reproduce scenario. There is not enough info in your pb description to be able to help. My wild guess would be that you are not adding the component to declarations of your module etc.

**Comment by natcohen** [comment]
Got it working [here](https://plnkr.co/edit/tDa0DJKzgw3olwIT0Ltq?p=preview) so my problem is somewhere else...

**Comment by natcohen** [comment]
@pkozlowski-opensource Thanks again for the solution... I'm trying to use `@Input` with component but can't figure out how to send the variable when I click to open the modal. For example, I have the following template:

```
<template #modalContent>
    <my-component-with-content [var1]="val1Exp"></my-component-with-content>
</template> 
```

And when I click to open the modal:

`<button type="button" (click)="open(modalContent)" class="btn btn-default">Open</button>`

So my question is how can I send the `var1` when I click?

**Comment by natcohen** [comment]
Oh and also how do you pass the close function?

I've tried:

```
<template #modalContent let-close='close'>
    <my-component-with-content></my-component-with-content>
</template>
``` 

and in `my-component-with-content`  when I try to call `(click) = close("close")` I get the following: `self.context.close is not a function`

Sorry if it is all very obvious for you but Typescript/Angular2 is quite disorienting compared to Javascript/Angular1
