### ISSUE TITLE
Modal: content shifts to the right

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#641]
Same as https://github.com/angular-ui/bootstrap/issues/6125

For the ref it is still a pb in the BS itself...

**Comment by Martin-Wegner** [comment]
Workaround:

`<body style="overflow-y: visible !important;">`

**Comment by 555ea** [comment]
@pkozlowski-opensource Any progress on it ? 

It should be fixed by adding padding to the body and the modal, as in bootstrap. Take a look at your examples page https://ng-bootstrap.github.io/#/components/modal/examples and bootstrap modal demo https://getbootstrap.com/docs/4.0/components/modal/
