### ISSUE TITLE
Unable to open a simple modal

### ISSUE THREAD

**Issue by natcohen** [ng-bootstrap/ng-bootstrap#647]
I'm using version 1.0.0-alpha3 of ngbootstrap and I'm having trouble displaying the content of a modal (I get the backdrop but not the modal).

I have the following PUG:

    template#modal(let-c="close" let-d="dismiss")
        .modal-header
            button.close(type='button', aria-label='Close')
                span(aria-hidden='true') ×
            h4.modal-title Modal title
        .modal-body
            p Hey
        .modal-footer
            button.btn.btn-secondary(type='button') Close
    button.btn.btn-default(type='button', (click)='open(modal)') Open

And below the `body` tag, I have added the modal container:

    template(ngbModalContainer)

The open function triggers the following:

    open(content) {
        console.log(content);
        this.modalService.open(content).result.then((result) => {

        }, (reason) => {

        });
    }

The problem is that `console.log(content);` prints `undefined` meaning that the button doesn't find the template...

I don't really understand how `open(modal)` is supposed to know what modal is, I never define it. In [the example](https://ng-bootstrap.github.io/#/components/modal) it just uses the same name as the template id `#content` (at least that how I understand it).

I think documentation could be more explicit...

**Comment by jnizet** [comment]
I'm not familiar with that template syntax. Could you please post the actual generated HTML?

What I suspect is that

    template#modal

doesn't generate

    <template #modal ...>

but generates

    <template id="modal" ...>

It must be 

    <template #modal ...>

That defines a local template variable referring to the template, and that you later pass to the `open()` method.

Also, the ngbModalContainer template must be inside your root component, not below the body tag.

**Comment by natcohen** [comment]
Thanks! You were right about generating an `id`! It was my misunderstanging of the html...
