### ISSUE TITLE
Typeahead: selectItem Event does not fire

### ISSUE THREAD

**Issue by JanHuege** [ng-bootstrap/ng-bootstrap#651]
Selecting a result does not seem to do trigger the selectItem Event. 

`<input type="text" class="form-control" [(ngModel)]="model" [ngbTypeahead]="search" (selectItem)="console.log("test")"/>`

Angular: rc5

ng-bootstrap: alpha2

Bootstrap: v4 alpha3

**Comment by pkozlowski-opensource** [comment]
You can't just reference console.log like this: `(selectItem)="console.log("test")`. What you need is a method _on your component_. Check our unit test: https://github.com/ng-bootstrap/ng-bootstrap/blob/46435235541d471de73c75ca97f932f077848d56/src/typeahead/typeahead.spec.ts#L373

Closing as invalid.
