### ISSUE TITLE
ngb-accordion : Click event for ngb-panel to call component method?

### ISSUE THREAD

**Issue by irshadmalek11** [ng-bootstrap/ng-bootstrap#657]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:

ng-bootstrap:

Bootstrap:

**Comment by pkozlowski-opensource** [comment]
I'm sorry but your question is not clear... You need to provide more details and a reproduce scenario in a plunker. Makes sure to check our documentation as well: https://ng-bootstrap.github.io/#/components/accordion

**Comment by irshadmalek11** [comment]
I am using ngb-accordion and when I click on ngb-panel I need to call method in component, do we have that feature?
<ngb-panel  (click)="comMethod()">
I did not find anything related this in documentation.

**Comment by pkozlowski-opensource** [comment]
We've got a `change` event on the accordion itself and you can use it to execute any code when a panel gets toggled. It is documented on https://ng-bootstrap.github.io/#/components/accordion and we even have a demo for its usage (ex.: "Prevent panel toggle").

Please provide a plunker with your use-case if you need more info.

**Comment by pkozlowski-opensource** [comment]
@irshadmalek11 haven't heard from you so going to close this one. Hopefully the info I've provided is enough for you to move forward. If not please share a plunker with what you are trying to do.

**Comment by JoeOwner** [comment]
To be more specific, and probably a bit more helpful for anyone looking for an answer:

HTML:
<ngb-accordion (panelChange)="toggleAccordian($event)">

TS:
public toggleAccordian( props:NgbPanelChangeEvent ): void{
    props.nextState // true === panel is toggling to an open state 
                              // false === panel is toggling to a closed state
   props.panelId    // the ID of the panel that was clicked
   props.preventDefault(); // don't toggle the state of the selected panel
}
