### ISSUE TITLE
Any CDN availability in the future?

### ISSUE THREAD

**Issue by kraighamady** [ng-bootstrap/ng-bootstrap#658]
I am building an Angular 2 front end with BS3 in .Net Core 1.0.  I am running into the issue that when I use NPM to get ng-bootstrap the .net site doesn't have access to the package so I have to gulp it over to an accessible folder.  Once I serve the files to the client, the load fails due to JS' inability to recognize 'require'.  While I could load and configure patches to fix this (which creates some other conflicts), or write bundling scripts (which still don't work as there are require statements in each component's js file) , a CDN version would be great!

Any chance of providing one?

**Comment by pkozlowski-opensource** [comment]
We are already deploying UMD-bundled version to npm and you can easily access this file via https://npmcdn.com/@ng-bootstrap/ng-bootstrap@1.0.0-alpha.3/bundles/ng-bootstrap.js 

Given the above I don't think there is anything more for us to do here so I'm going to close this issue.
