### ISSUE TITLE
[alert] custom alert demo is broken

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#659]
On master, the custom alert demo is broken: the custom CSS styles are not applied anymore.
<img width="838" alt="capture d ecran 2016-09-02 a 10 00 51" src="https://cloud.githubusercontent.com/assets/1608223/18196862/48ab9b14-70f4-11e6-9fce-f8aec7896fc8.png">

**Comment by pkozlowski-opensource** [comment]
Probably a side-effect of the RC6 changes in the CSS shimming. We could fix this but my vote would go to removing this demo.

**Comment by icfantv** [comment]
For reference, [here](https://github.com/angular/angular/commit/af63378fa09a0b50e7e2f0b215ad487ac569dc37) is the ng2 commit that caused this along with the right way to fix - which I'm doing.
