### ISSUE TITLE
[alert] rename NgbDismissibleAlert, make it non-dismissible

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#660]
NgbDismissibleAlert has a strange name: it implies that regular alerts, i.e. NgbAlerts, are not dismissible, although they are. And bizarrely, NgbDismissibleAlert is always dismissible with a close button, even though the whole point of the directive is to have an alert that self-closes itself after a while, rendering the close button redundant.

We're still in alpha version, so renaming a component is not a big deal.

What I propose:

 - rename NgbDismissibleAlert to NgbSelfClosingAlert
 - add a boolean dismissible input to NgbSelfClosingAlert, aligning it with NgbAlert
 - set its default value to false

The last point is more debatable than the others. I typically use such alerts for sort-lived success messages where the close button is redundant. Maybe others use it for long-lived messages where having the close button by default is better. But anyway, since the default values will soon be customizable globally, that's not a big deal.

**Comment by pkozlowski-opensource** [comment]
I agree that we need to clean-up our alerts offering.
