### ISSUE TITLE
Rating does not support half stars

### ISSUE THREAD

**Issue by rolandoldengarm** [ng-bootstrap/ng-bootstrap#669]
The rating component only supports full stars, no half stars, e.g. 4.5 stars.

**Comment by rolandoldengarm** [comment]
ng2-rating does, some of that logic could be re-used?
I'm happy to submit a PR if necessary?

**Comment by pkozlowski-opensource** [comment]
Sure, PRs welcomed.

**Comment by rolandoldengarm** [comment]
@pkozlowski-opensource glyphicons are no longer included in Bootstrap v4 as far as I know. Best alternative is font-awesome, but that will add a dependency. It will be a major change. Or is there an alternative?

**Comment by pkozlowski-opensource** [comment]
@rolandoldengarm yes, we've been debating replacement for glyphicons and at this point are not quite ready to add dependency on font-awesome... 

> Or is there an alternative?

* UTF symbols
* custom SVG - I'm sure that it wouldn't be too hard to find SVGs with a proper license

I'm sure that there are other solutions but can't think of anything better atm

**Comment by rolandoldengarm** [comment]
This fix can only be implemented when there's a decision...

**Comment by icfantv** [comment]
@rolandoldengarm I think the only decision that needed to be made here was that we were not ready to require Font Awesome as a dependency.  Invariably, if we were to chose Font Awesome, someone would want to use a different font set.

There's _plenty_ of examples on the web of implementing this so I would start there and assume the use of UTF or SVG as the characters.  [Here's something](http://jsfiddle.net/M8UAy) to get you started.

**Comment by rolandoldengarm** [comment]
Hi @icfantv thank you. Sorry, but due to timing constraints we had to find a quick alternative and we're using ng2-rating instead. If we've met the deadline, I'll try to get a PR for ng-bootstrap. But anyone else is free to submit a PR in the meantime.

**Comment by pkozlowski-opensource** [comment]
I believe that it got fixed by 964d8cf625fe105379f62d40558cbcc4d7a93275

**Comment by Hongbo-Miao** [comment]
Please update the doc too, thanks for the great work!

**Comment by pkozlowski-opensource** [comment]
> Please update the doc with a demo too, thanks for the great work!

Demo is updated, check the commit I've linked. It is just not up yet as we didn't cut the new release.
