### ISSUE TITLE
Build: exclude test artifacts from bundling 

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#670]
Currently the https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/util/tests.ts file is not excluded from bundling and it should.

My take on this would be to create a separate folder for test-specific stuff so we don't keep bumping into this - file by file exclusion as we do in https://github.com/ng-bootstrap/ng-bootstrap/blob/925a3cfc9a19b5125fe627b732b3a96c0289f16a/gulpfile.js#L45-L58  is just too brittle.

**Comment by jnizet** [comment]
While we're at it, we switched to TypeScript 2.0.2, but gulp-typescript actually uses its own bundled 1.8 version unless we tell it to use another specific version.

**Comment by pkozlowski-opensource** [comment]
> gulp-typescript actually uses its own bundled 1.8 version unless we tell it to use another specific version.

Oh, we should fix it then!
