### ISSUE TITLE
Modal as encapsulated component

### ISSUE THREAD

**Issue by masaanli** [ng-bootstrap/ng-bootstrap#680]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
It's nice to have the Modal as Component now.

But what I'm missing or maybe don't know is how to make it as external Component.

So I got a Component with HTML and a Controller with the functions for that modal inside it.
And from another Component I then open that Modal.

What I did now was the HTML template inside the Component HTML where I wanna open the Modal.
Like the example is doing, but what I really want is an excapsulated Modal. 
What if you need to open the same Modal at 5 places?
What if you wanna lazy load the modal?

### Link to minimally-working plunker that reproduces the issue:
-

### Version of Angular, ng-bootstrap, and Bootstrap:

**Angular:**
RC5

**ng-bootstrap:**
Alpha 3

**Bootstrap:**
Alpha 3

**Comment by pkozlowski-opensource** [comment]
@masaanli see discussion in there: https://github.com/ng-bootstrap/ng-bootstrap/issues/3#issuecomment-241186590

it is more of a work-around than the ideal API we would like to have so I will keep this issue open as a feature request to support component types as arguments to the `open` method (on top of the `TemplateRef` and `string` we are supporting today).

**Comment by PEsteves8** [comment]
Currently I created a myModals.component that holds the modals templates and open methods, just like in the example.

Then I created a myModals.service that other components can use and whose methods emit events that myModals.component subscribes to.

Then by using @ViewChild('content) content: string in myModals.component, I just run (after an event), this.open(this.content);

It works well. Not sure if, it's not advisable to be using observables to emit notifications to open modals, though.

**Comment by pkozlowski-opensource** [comment]
For anyone interested in this issue, here is the design doc for introducing components as arguments to the `open` method: https://docs.google.com/document/d/1puwnSknaW3bLg_Ww2ewuILneCom1wbMTArvfFq0YFV8/edit?usp=sharing

**Comment by maxokorokov** [comment]
After reading the doc my vote goes for doing the following:

1. pass the `ComponentType` to the `open` method
2. remove the `string` argument for the `open` method
3. make the `modalRef.component` instance accessible, so a user will do the setup of inputs and outputs

The other solutions for the last point look like sugar over it, so `.open(ComponentType)` might become `.open(ComponentType, { inputs: ..., outputs: ...})` or whatever later (ex. inputs could be observables or simple values)

**Comment by pkozlowski-opensource** [comment]
Huge thnx to everyone who took time to comment on the design doc. After going trough all the comments and thinking about it some more here are the conclusions (pretty much in-line with what @maxokorokov proposed):

1. pass the `ComponentType` to the `open` method
2. make the `modalRef.component` instance accessible, so a user will do the setup of inputs and outputs
3. remove documentation for the `string` argument to the `open` method (still, keep the functionality for testing)

We can always add more sugar on top later on (convenience for binding to inputs / outputs, injection of ModalRef etc.) but the current proposal allows us to have basic infrastructure and evolve it in the future.

**Comment by pkozlowski-opensource** [comment]
Change of plans :-) After working the whole day on various prototypes and demos I've realized that just returning a component instance creates very poor user experience - simple task of closing a modal from inside of a component becomes verbose.

As such I've sent an alternative proposal in #846:

1. pass the `ComponentType` to the `open` method
2. inject `NgbActiveModal` (a class with `close` / `dismiss` methods) into component's instance
3. remove documentation for the `string` argument to the `open` method (still, keep the functionality for testing)

#846 doesn't expose instance of a component being used as content so it is not possible to interact with `@Input`s and `@Output`s. This is the same limitation as in router and we can always add it to the API if there is enough interest.

**Comment by EtiAggarwal** [comment]
How to interact with Outputs of a component used in the Modal

**Comment by vincenthu-audax** [comment]
How can I add options when the content is a componentType?  The open api doesn't take a second parameter when the content is a componentType
