### ISSUE TITLE
How to get count of pages from pagination?

### ISSUE THREAD

**Issue by kolkov** [ng-bootstrap/ng-bootstrap#682]
I can't find any possibility to get count of pages from pagination... (((
How can I get it?
https://ng-bootstrap.github.io/#/components/pagination

**Comment by icfantv** [comment]
@kolkov, yea, this isn't exposed right now but probably should be.  In the interim, you can do what we're doing internally and calculate it yourself via `Math.ceil(this.collectionSize / this.pageSize);`

**Comment by icfantv** [comment]
@kolkov, I'm going to close this and open a new issue for tracking.  Thanks.

**Comment by icfantv** [comment]
@kolkov, my apologies, but my ng2 skills are rusty from not being put to use as of late.  This is easily done (and I will update the demo to show how), but you need to add a reference in your `ngb-pagination` component usage to access:

`<ngb-pagination #pagination ...></ngb-pagination>`

and then, in your template, e.g.,:

`<pre>{{ pagination.pageCount }}</pre>`

**Comment by kolkov** [comment]
@icfantv Thanks! Than worked!

**Comment by icfantv** [comment]
@kolkov, cool, glad to hear.

**Comment by pkozlowski-opensource** [comment]
@kolkov see my additional comments in https://github.com/ng-bootstrap/ng-bootstrap/pull/685#issuecomment-245212750

**Comment by omostan** [comment]
@icfantv Thanks! Your solution worked for and I have since posted my complete implementation on one of my answers to such questions in stack**overflow** [here](https://stackoverflow.com/questions/41223400/how-to-implement-bootstrap-4-for-angular-2-ngb-pagination/53418465#53418465)
