### ISSUE TITLE
Opens several drop-down lists

### ISSUE THREAD

**Issue by kolkov** [ng-bootstrap/ng-bootstrap#687]
Is this a bug o new feature?
![image](https://cloud.githubusercontent.com/assets/3740898/18257523/c71dad08-73cd-11e6-9434-7b53bc5baff4.png)
How to disable it?

**Comment by wesleycho** [comment]
Can you post a reproduction in Plunker?

**Comment by jnizet** [comment]
This is reproduced in our new (not deployed yet) basic demo for dropdowns. Despite autoClose being true by default, the first dropdown doesn't close when clicking on the "toggle dropup" button.

**Comment by pkozlowski-opensource** [comment]
This is definitively a bug but a proper fix requires a bit more thinking to also properly address some of the issues raised in #584. Let's schedule it for alpha.5.

**Comment by PEsteves8** [comment]
I have a navbar with two dropdowns. A given dropdown A closes if I click on one of its links or outside of both dropdowns. However,  if after opening dropdown A, the next click opens dropdown B, they both stay open. Is this the behavior described in this issue? Or is it another issue?

**Comment by pkozlowski-opensource** [comment]
@PEsteves8 it is the same issue.

**Comment by kolkov** [comment]
In alpha7 bug was appeared again ((

**Comment by pkozlowski-opensource** [comment]
@kolkov I can't reproduce on our demo page. Please open a new issue with a plunker if you think that it is not fixed.

**Comment by kolkov** [comment]
Thanks! It's from new bootstrapping too! ))
