### ISSUE TITLE
Add JavaScript examples

### ISSUE THREAD

**Issue by mindej** [ng-bootstrap/ng-bootstrap#700]
Add JavaScript examples to a project

**Comment by jnizet** [comment]
Hi @mindej. Could you please clarify and elaborate a little. https://ng-bootstrap.github.io has demos with code samples for each widget. 
Are you asking to provide examples in JavaScript in addition to TypeScript in the demos?

**Comment by pkozlowski-opensource** [comment]
Closing as it is not clear what the question is all about.
