### ISSUE TITLE
Tooltip - Bug spacing added

### ISSUE THREAD

**Issue by PEsteves8** [ng-bootstrap/ng-bootstrap#704]
Using a button group it seems the tooltips cause the classic problem described here:

http://stackoverflow.com/questions/13268361/bootstrap-tooltip-and-popover-add-extra-size-in-table

I have a table with a button group and I'm unable to add the tooltip to the actual buttons. I have to add them to the <span> element that is inside the buttons (which are icons). This is a known issue in bootstrap 3, so maybe you already know about it.

Edit: Also described here: http://stackoverflow.com/questions/14364079/bootstrap-tooltip-causing-buttons-to-jump

I just assumed this would be solved in BS4. Since I'm using the ng-bootstrap plugin, I'm not sure if it's just a bug or something.

Angular: RC6

ng-bootstrap: Alpha-4

Bootstrap: Alpha-4

**Comment by pkozlowski-opensource** [comment]
This will be solved by #339 where you will be able to choose a container to which we append the tooltip element. Closing as a duplicate.

**Comment by PEsteves8** [comment]
Great! Thanks. I didn't find the issue, because I was looking specifically for the work tooltip.
