### ISSUE TITLE
Accordion Feature Request - Title Content that does not cause expand/collapse

### ISSUE THREAD

**Issue by jhuntoo** [ng-bootstrap/ng-bootstrap#717]
Hi Guys, nice work on the library, it's really starting to take shape! Thanks for your all your effort!

I have a feature request that I'd like to run by you and discuss. From what I can tell, when the `ngbPanelTitle` directive is used with the accordion, all the content is wrapped in an `<a>` element and as such all content will toggle the collapse state of the panel.

I have a use case where I'd like to have content in the panel header/title which does not toggle the collapse state.

For example...

``` html
<ngb-accordion>
  <ngb-panel>
    <template ngbPanelTitle>
      <span>Click on me to toggle panel</span>
      <span>Non toggle text</span>
      <input placeholder="Should not cause expand/collapse">
    </template>
    <template ngbPanelContent>
        Some Settings
    </template>
  </ngb-panel>
</ngb-accordion>
```

So with the present implementation, both  `<span>` and the `<input>` elements will cause the toggling to occur.

Is there a way to achieve this with the current implementation ?

The first idea that comes to mind is to have another directive, say `ngbPanelHeader` for argument's sake, that is the same as `ngbPanelTitle`, but does not get wrapped in the `<a>` element.

So the above example would now look something like this

``` html
<ngb-accordion #acc="ngbAccordion">
  <ngb-panel id="1">
    <template ngbPanelHeader>
      <span (click)="acc.toggle('1')">Click on me to toggle panel</span>
      <span>Non toggle text</span>
      <input placeholder="Should not cause expand/collapse">
    </template>
    <template ngbPanelContent>
        Some Settings
    </template>
  </ngb-panel>
</ngb-accordion>
```

I realise that this would introduce another way to virtually do the same thing, but I can't see another  way to allow my particular use case, and keep the simplicity of the existing  `ngbPanelTitle` directive for the 95% of use cases.

I'd be happy to help with a contribution if this is something you'd consider supporting in ng-bootstrap.

**Comment by pkozlowski-opensource** [comment]
This sound _very_ similar to #465 - and yes, we want to support this use-case

> I'd be happy to help with a contribution if this is something you'd consider supporting in ng-bootstrap.

Awesome. Could you try to think of all / different solutions, list them here with the pros and cons? I will try to do the same. Then we can weight different options & implement the most reasonable one(s).

**Comment by jhuntoo** [comment]
@pkozlowski-opensource ok I've just jotted this down, sorry if it's incoherent!

# 1. ngbPanelHeader directive with manual click event handling
```html
<ngb-accordion #acc="ngbAccordion">
  <ngb-panel id="1">
    <template ngbPanelHeader>
      <span (click)="acc.toggle('1')">Click on me to toggle panel</span>
     <input placeholder="Should not cause expand/collapse">
    </template>
    <template ngbPanelContent>
        Some Settings
    </template>
  </ngb-panel>
</ngb-accordion>
```

Pros: 
- Preserves the simplicity of `ngbPanelTitle`

Cons: 
- Manual event handling is required. 
- Slightly more complex implementation of `ngb-panel`, it needs to support both `ngbPanelHeader` and `ngbPanelHeader` and validate that only one is present.

# 2. Nested header/title directives (Taken from #465)

```html
<template ngbPanelHeader>
      <!-- prepend something -->
      <template ngbPanelTitle><b>Fancy</b> title</template>
      <!-- append something -->  
</template>
```
Pros: 
- ??

Cons: 
- ties the concept of a panel title, to something that is both descriptive text and an action source (panel toggling in this case.) Which makes sense for when `ngbPanelTitle` is used alone, but *could* be restrictive when using the more free-form `ngbPanelHeader` directive.

# 3a. new ngbAction directive. 1 instance supported
`ngbPanelHeader` is aware of `ngbAction` and knows that it should perform toggling. 
`ngbAction` adds click event binding to template element. Should this be within the template element??
```html
<template ngbPanelHeader>
       <template ngbAction><b>Fancy</b> title with toggle Action</template>
      
</template>
```
Cons:
- it's not immediately obvious what the action does

Pros:
- ngbAction serves as a marker & event binding directive, that can be used elsewhere like in Tabset

# 3b. ngbAction directive. Multiple instances supported with targeting
`ngbPanelHeader` supports mutiple theoretical actions, and so targeting must be used like so.
If no targeting is applied, the parent directive will either use a default action, or raise an error.
```html
<template ngbPanelHeader>
       <template ngbAction="toggle"><b>Fancy</b> title with toggle Action</template>
      <template ngbAction="someOtherAction">Secondary Action</template>
      
</template>
```
Cons:
- more complexity in supporting multiple actions within a containing directive

Pros:
- opens up many more use-cases, though not sure how likely they are to be needed.


# 3c. ngbAction directive. Multiple instances supported with targeting and custom event binding
Same 3b, but it with an additional directive for changing which event to bind to.
```html
<template ngbPanelHeader>
   <template ngbAction="toggle" ngbActionTrigger="onBlur"><input placeholder="this toggles on blur"></template>
      
</template>
```
Cons:
- more complexity in configuring the event bindings via another directive

Pros:
- opens up many more use-cases, though not sure how likely they are to be needed.


Without a lot of control library experience, I couldn't come up with a lot of pros & cons, let me know if you think of anything.

My personal preference would actually be 3c, which is the most complex in terms of library implementation, but IMO the most flexible for users, allowing for arbitrary actions to be define in a template, for any ngb component.

**Comment by jhuntoo** [comment]
Basically `ngbAction` is a generic way of defining actions within templates.

`ngbAction` could be utilised in..
1. Alert - define a template with an element that dismisses the alert.
2. Carousel - define actions within `<template ngbSlide>` for things like next,prev, go to end/beginning.

I'm sure there are more similar examples in ngb-bootstrap.

**Comment by jnizet** [comment]
I like the first solution. It's simple enough, and lets the template do whatever it wants to decide when and how to toggle the panel (it could be a link, a button, a click, a double click, etc.). It's also quite easy to implement (I just did it, so that's a hint!). 

We can additionally pass a context to the template. This template can contain the panel itself, and maybe a `toggle()` method that would toggle the panel. 

The result could thus look like that:

```
  <ngb-panel [disabled]="someComplexCondition">
    <template ngbPanelHeader let-panel="panel">
      <a href (click)="!!acc.toggle(panel.id)" [class.text-muted]="panel.disabled">This toggles</a>
      <span>This doesn't toggle</span>
    </template>
    <template ngbPanelContent>
      Content
    </template>
  </ngb-panel>
```

or, if a toggle method is passed in addition to the panel in the context:

```
  <ngb-panel [disabled]="someComplexCondition">
    <template ngbPanelHeader let-panel="panel" let-toggle="toggle">
      <a href (click)="!!toggle()" [class.text-muted]="panel.disabled">This toggles</a>
      <span>This doesn't toggle</span>
    </template>
    <template ngbPanelContent>
      Content
    </template>
  </ngb-panel>
```

If the panel is never disabled (which I guess, is the most frequent case), it can boil down to

```
  <ngb-panel>
    <template ngbPanelHeader let-toggle="toggle">
      <a href (click)="!!toggle()">This toggles</a>
      <span>This doesn't toggle</span>
    </template>
    <template ngbPanelContent>
      Content
    </template>
  </ngb-panel>
```

**Comment by jhuntoo** [comment]
Looks good, it's much more flexible and it uses native angular constructs (which I wasn't really aware of).

@jnizet Do you know of any documentation/ reference example of passing context objects within templates?

**Comment by jnizet** [comment]
@jhuntoo See https://angular.io/docs/ts/latest/api/common/index/NgTemplateOutlet-directive.html 

We already use this directive to include the NgbPanelTitle template into the accordion, but we do not pass a context.

**Comment by jhuntoo** [comment]
@jnizet Thanks! I just started looking at the implementation, but you've beaten me to it!

Your proposal looks decent.

**Comment by jnizet** [comment]
Oh, sorry. I forgot you wanted to contribute on this one. I wanted to experiment and learnt on my side, but didn't want to prevent you from doing so. Confused I am.

**Comment by jhuntoo** [comment]
Not an issue at all - given the alpha status of this project i'm sure I'll get more opportunities 😉. And  I'm learning from just reviewing your PR!

**Comment by jnizet** [comment]
#698 would be a good opportunity to start contributing :-)

**Comment by amitjindal** [comment]
Hi, I was looking for this feature too as I needed to show 3 icon buttons in the collapsed header (Edit/Clone/Delete). Came across this. I understand this is not yet available. However I was able to implement this as a hack with angular events. Posting it in case it helps anyone:

**Step 1: Pass $event to handler**
```html
    <template ngbPanelTitle>
      <span>&#9733; <b>Fancy</b> title &#9733;</span>
      <button (click)="clicked($event)">Cool</button>
    </template>
```
**Step 2: Bypass default and use your code in handler**
```ts
  clicked(event:Event) {
    event.preventDefault();
    console.log("Clicked");
    event.stopPropagation();
  }
```

http://plnkr.co/edit/y9Iy7pk9Zj6hQ9rQmbWb?p=preview

This is kind of a hack but for now I could not find any other solution that works.

**Comment by jogelin** [comment]
Hello, I am starting using ngb and I also need both of those features:
- Expand/Collapse on header
- Having action buttons

I see some codes about a possible ngbPanelHeader directive but nothing in the code or in the documentation.

 What is the status of this issue ? 

Thx for your work, this library is amazing ;) !

**Comment by Xstoudi** [comment]
Up?

**Comment by bjornharvold** [comment]
The hack worked for me. We had the same use case. We had an action button in the panel title. If users clicked anywhere except for the button, they see more details. But if they wanted to execute the action without looking at the details, the should be able to click on the button without any more work on the side of the accordion.

**Comment by jonathanignacio** [comment]
Since this is not yet implemented, I have used another 'hack' that involves just a little custom css. First, set 'margin: 0' and 'padding: 0' for card-headers. Then, inside the accordion use something like this for the panels:
```
<ngb-panel>
  <!--Panel titles clickable by replacing them with a fluid container div that fill the entire panel-->
  <ng-template ngbPanelTitle>
    <div class="container-fluid>
      <h5>My Panel Title</h5>
    </div>
  </ng-template>

  <!-- The body of the panel -->
  <ng-template ngbPanelContent>
    <p>Some body content.</p>
  </ng-template>
</ngb-panel>
```

This should cause clicking the content inside the ngbPanelTitle template to control collapsing and expanding. 

The directive adds the content to anchor that when clicked, expands/collapses the corresponding panel. It may take a little more css tweaking, but this was a reasonable way to make the entire panel title clickable (and as a bonus, allow more control over the styling of the panel title).

**Comment by lucasklaassen** [comment]
Thanks @amitjindal hack works well.

**Comment by guntram** [comment]
The ngbPanelTitle still wraps the content in 3.0.0, but the <a> was changed to <button> :'D

**Comment by pvelez-bp3** [comment]
Now that the content is wrapped in a button not even this kind of solution will work http://plnkr.co/edit/y9Iy7pk9Zj6hQ9rQmbWb?p=preview

**Comment by mohit-deshpande** [comment]
Thanks @amitjindal the solution works! I racked my brain for a long time before stumbling upon this.
