### ISSUE TITLE
typeahead: blur / esc / enter doesn't un-subscribe

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#723]
There is a bug in the current implementation of the typeahead which might be exposed using a (relatively) long-running async operation. To reproduce go to our WIKIPEDIA search demo and:
- type any letter
- immediately after (before results arrive) press TAB

You will see that the result window gets opened even if a user is not interested in those any more (moved focus to a different field already).

**Comment by pkozlowski-opensource** [comment]
There is one more interesting corner case: say we are dealing with an async data source and:
* a user types `a` -> server responds, results shows
* a user types `b` (so we've got `ab` now) -> request fires but _before_ server responds a user select an item from a list for `a` -> popup window gets closed
* after some time a response for `ab` arrives and the popup re-opens :-)

So it is not only about `blur` and ESC - we can get race condition with an item selection as well!

**Comment by alex321** [comment]
@pkozlowski-opensource 
Item 1: Does it make sense to make the signature of the ngbTypeAhead : string -> Observable<any[]> in order to apply switchMap to it? 
Item 2: Does it make sense to just close the dropdown once the user has decided that they want to look at a different term?
