### ISSUE TITLE
Modal: string argument to the open method is confusing

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#727]
See http://stackoverflow.com/q/39464345/1418796

Really, the string argument is only good for unit-testing but not for any real-life applications. We should  remove it altogether or at least clarify in the docs.

On top of this we need to support components as arguments to the `open` method, see #680

**Comment by felixfbecker** [comment]
How about something like
```ts
ngbModal.open(MyModalComponent).then(value => ...
```
where the component is passed the `modal` instance as an `@input`?

to avoid having to specify `@Input` it could also be possible to subclass a `ModalComponent`:
```ts
import {ModalComponent} from '@ng-bootstrap/ng-bootstrap'

@Component({})
class MyModalComponent extends ModalComponent {
  ngOnInit() {
    this.modal.close(value) // or
    this.modal.dismiss(value)
  }
}
```
where `ModalComponent` is something like:
```ts
abstract class MyModalComponent {
  @Input()
  public modal: ModalInstance
}
```

**Comment by felixfbecker** [comment]
Actually it would be very ng1-ish to pass the modal instance as an _input_. Better would be to have two _outputs_, `close` and `dismiss`.

**Comment by felixfbecker** [comment]
This here does something similar: http://plnkr.co/edit/ZAZqZu?p=preview

**Comment by SanderElias** [comment]
My vote would go on removing the string argument completely, as it's just utterly confusing. 
Adding the component support to the `open` method makes a lot of sense. This will take out quite some boileplate code that is now needed to support the usecase of #680

**Comment by pkozlowski-opensource** [comment]
For anyone interested in this issue, here is the design doc for introducing components as arguments to the `open` method: https://docs.google.com/document/d/1puwnSknaW3bLg_Ww2ewuILneCom1wbMTArvfFq0YFV8/edit?usp=sharing
