### ISSUE TITLE
index.js should export the individual modules

### ISSUE THREAD

**Issue by PEsteves8** [ng-bootstrap/ng-bootstrap#729]
### Feature request:

We're expected to import NgbModule in any module that uses any component of Ngb. Shouldn't we be allowed to import specific modules individually like this:
`import { NgbAlertModule } from '@ng-bootstrap/ng-bootstrap'`, instead of `import { NgbAlertModule } from '@ng-bootstrap/ng-bootstrap/alert/alert.module'` ?

Thanks

Angular: RC7

ng-bootstrap: 4-alpha4

Bootstrap: alpha4

**Comment by pkozlowski-opensource** [comment]
Yeh, we can do it! Our long-term plan is to have a separate npm package for each directive but there are few considerations before it can work well in practice.

>  instead of import { NgbAlertModule } from '@ng-bootstrap/ng-bootstrap/alert/alert.module' ?

Yeh, don't do this as it might break in the next release with certain WebPack configurations. The reasons for this is that we are going to publish es5 + es2015 modules from the next release - as Angular does.

**Comment by pkozlowski-opensource** [comment]
Out of curiosity - why do you prefer to import individual modules instead of the `NgbModule`? Is it that you are just using a small subset of all directives?

In any case PRs welcomed!

**Comment by PEsteves8** [comment]
Hi. Thanks, for the answer. The main reason to want to import isolated modules is that I frequently create custom versions of these components. For instance, I made a custom modal component with specific styling in the template and yes/no buttons with callbacks, that gets called through a service available app wide. That custom module is used in other applications within the company. Its only ng-bootstrap dependency is the NgbModalModule, so for organization and isolation purposes there would be no need to import anything else to this module.

As far as I know, index.js could just reexport those modules right? I'm still somewhat of a beginner in programming (first job a couple of months ago, after self learning), but eventually I would be glad to help out)

**Comment by sendilkumarn** [comment]
@pkozlowski-opensource when this will be released ?

**Comment by pkozlowski-opensource** [comment]
> when this will be released ?

@sendilkumarn no particular plans. I think that we are going to land few more fixes and have a release by the end of this week for sure.
