### ISSUE TITLE
Consider creating an interface for the model of NgbDatepicker and NgbTimepicker

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#731]
Instead of using `{year: number, month: number, day: number}`, creating an interface (`NgbDateStruct`, for example) would make the code less verbose and more readable, and the client code more type-safe. It would also allow documenting the interface (for example to specify if the month is 0-based or 1-based).

**Comment by jnizet** [comment]
I'm willing to do these refactorings. Any opinion on the name? NgbTime and NgbDate are already used for something else. So NgbDateStruct? NgbDateModel? DateStruct? DateModel? Something else?

**Comment by pkozlowski-opensource** [comment]
`NgbDateStruct` sounds good to me. We should do the same for `NgbTime`

**Comment by pkozlowski-opensource** [comment]
This was fixed via adb329d2e2fb9792bb7c895500ab45597ceddfe2 and 64eca2d4df317ce211e32f8e5357dc6df0d02b2c
