### ISSUE TITLE
datepicker: consider renaming startDate to startMonth

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#732]
The value that the input expects is effectively a month, and it would disambiguate with `minDate`.

**Comment by pkozlowski-opensource** [comment]
cc @maxokorokov

**Comment by pkozlowski-opensource** [comment]
Note: this would be a BC (we are still in alpha so that's fine)

**Comment by maxokorokov** [comment]
I'm neutral on this one, it doesn't bother me personally. My initial thinking that if we do 'infinite' navigation with 'zoom' later (as in angular UI), you could open calendar either with year or with month → hence `startDate`

If we want to change it though I would rename to something neutral and probably make month optional:

`startDate='{year, month}'` → `openWith='{year, ?month})'` or `startWith='{year, ?month}'`

**Comment by pkozlowski-opensource** [comment]
Given @maxokorokov explanations I think that we are good for now.
