### ISSUE TITLE
Datepicker & Timepicker as a popup

### ISSUE THREAD

**Issue by natcohen** [ng-bootstrap/ng-bootstrap#735]
We should be supporting datepicker and timepicker as a popup, otherwise this feature is almost useless...

If it's already possible, we should add that to the documentation

**Comment by pkozlowski-opensource** [comment]
Support for datepickers in popup landed via  390935bc88e79bde785170c9d69bb58ef5cbca36 and was just released alpha.5. You can see it in action here: https://ng-bootstrap.github.io/#/components/datepicker 

Timepicker in popup is on the roadmap and will be tackled via #512
