### ISSUE TITLE
Bug with Angular 2 final

### ISSUE THREAD

**Issue by natcohen** [ng-bootstrap/ng-bootstrap#740]
I'm getting the following error with the final Angular 2:

```
Error: SyntaxError: Unexpected token <
	Evaluating http://localhost:3000/traceur
	Error loading http://localhost:3000/traceur
	Error loading http://localhost:3000/node_modules/@ng-bootstrap/ng-bootstrap/index.js as "@ng-bootstrap/ng-bootstrap" from http://localhost:3000/app/app.module.js
```

**Comment by pkozlowski-opensource** [comment]
You are using deep imports, most probably somewhere in your code. What are you using for building / bundling?  `traceur` looks suspicious here....

**Comment by natcohen** [comment]
I'm using systemJS and everything worked with Angular RC7 and Bootstrap alpha 3

**Comment by pkozlowski-opensource** [comment]
> I'm using systemJS 

Then you need to configure your systemjs to use a bundle (bundles/ng-bootstrap.js) instead of individual files. Have a look at the changelog.

**Comment by natcohen** [comment]
Thanks! I'm not an expert in SystemJS... Can you tell me what to change?

**Comment by Technohacker** [comment]
this might seem dumb but how should i use the bundle? because when i do, it says that NgbModule is unexpected

**Comment by pkozlowski-opensource** [comment]
@Technohacker depends on your setup, really. If you are on WebPack you should have, normally, nothing to do. If you are on SystemJS you can use this plunker as an inspiration. Not sure we can help more without seeing your build. If you can create a _minimal_ repo with a reproduce scenario I _might_ take a look.

**Comment by natcohen** [comment]
Where is the plunker?

**Comment by Technohacker** [comment]
Sorry i really was dumb, i kept the NgbModule in declarations instead of imports ****facedesk****

Cheers! :)
