### ISSUE TITLE
Tabset (change) event gets fired in non-related situations.

### ISSUE THREAD

**Issue by PEsteves8** [ng-bootstrap/ng-bootstrap#741]
### Bug description:

Basically what happens is that if an <input type="text"> is inside a tab, any method associated with the tabset's (change) event will get fired if the input's value changes (and the input loses focus).

So the event gets triggered if either a selected tab changes or if an input field's value changes inside the tab changes.

My personal case is the following. On a (change) event I run code that changes the route to include the open tab in the parameters. One of the tabs has a form. By changing a form input value in that form, the route change function runs and another tab opens.

To make it work I'm using this hack:
```
onTabSelect(data: NgbTabChangeEvent) {
if (data.hasOwnProperty('nextId')) { 
            this._router.navigate(...);
        }   
}
```

Angular: 2.0.0

ng-bootstrap: 1.0.0.alpha-4

Bootstrap: 4.0.0.alpha-4

EDIT: I now realize I probably should have replied here instead: #594

**Comment by pkozlowski-opensource** [comment]
@PEsteves8 I'm sorry but it is not clear from your description what the root cause is. Please provide a plunker so we can investigate. Otherwise it is hardly actionable... (well, in reality this is not actionable as-is...).

**Comment by PEsteves8** [comment]
I don't really know all that well how to make plunkr with external dependencies (as in where to I get ng-bootstrap from?)

Here's what I can show using a changed version of the live demo of Angular2 forms:

http://plnkr.co/edit/otcmE7Ne2OOMAHtaONDC?p=preview

If you open the console you can see that if you change a field (and then switch to another field), the (change) event attached to the containing div in hero-form.component.ts is triggered. This means that any form inside a tab will constantly trigger the same eventHandler that is supposed to be run when a tab changes. So the (change) event isn't specific to the tabs at all. It gets triggered from other non related sources.

**Comment by pkozlowski-opensource** [comment]
Oh, I see @PEsteves8 , thnx. Based on your description it seems like the `change` event fired on the input form bubbles up and for some reason having `(change)` on the tabset picks up this event. This sounds like a super corner-case in the framework as I don't think it should subscribe to _both_ directive _and_ DOM events.

I will discuss this with other in the core team and will either fix upstream in angular 2 or rename the event here (might be a good idea anyway). Thnx for reporting.

**Comment by PEsteves8** [comment]
Great. So for now if I have a form in a tab and use the (change) event, I'll just keep using that little condition to check if the payload is from ng-bootstrap. Thanks :)

PS. I just reread my first message and you're right. It wasn't clear at all (I actually forgot to type some words). :D Sorry about that.

**Comment by jnizet** [comment]
@pkozlowski-opensource so, is your change a workaround for an angular issue, or is it expected behavior? If it's expected behavior, that means that we should be very careful never to name an output as a standard dom event for directives that wrap content. BTW, the same bug probably also exists in accordion, which also has a `change` output.

**Comment by pkozlowski-opensource** [comment]
> is your change a workaround for an angular issue, or is it expected behavior?

I expect it to be debated :-) And I think that it actually makes sense to have a specific event name so it stands out in a template, hence the PR.

> we should be very careful never to name an output as a standard dom event for directives that wrap content.

At least for events that bubble, yes.

> BTW, the same bug probably also exists in accordion, which also has a change output.

Yes. I was just waiting for the reaction to my 1st PR :-)

**Comment by pkozlowski-opensource** [comment]
@jnizet ref: https://github.com/angular/angular/issues/11666
