### ISSUE TITLE
Prevent auto select of first item in typehead

### ISSUE THREAD

**Issue by doorman02** [ng-bootstrap/ng-bootstrap#748]
Is it possible to prevent auto select of the first item in the typehead component? I need this because I want the user to be able to press enter if he wants to search normally and only if an item in the list is selected by the user e.g. using the mouse or arrow keys he should navigate to the item.

**Comment by pkozlowski-opensource** [comment]
Yes, we should add an option for this. It would be rather easy to implement so PRs welcomed (would be wise to wait till #746 lands otherwise you are looking for funny rebases).

**Comment by kjartanvalur** [comment]
Here is a pull request for this issue
https://github.com/ng-bootstrap/ng-bootstrap/pull/767
