### ISSUE TITLE
Typeahead: SelectItem Event doesn't fire

### ISSUE THREAD

**Issue by JanHuege** [ng-bootstrap/ng-bootstrap#752]
`
input type="text" class="form-control" [(ngModel)]="searchQueryCountry" [ngbTypeahead]="searchCountry" [resultTemplate]="rt"
                        [inputFormatter]="formatter" (keyup)="filter()" (selectItem)="onSelectTypeahead($event.item)" 
`

`
public onSelectTypeahead(eventItem: any) {
        console.log(eventItem);
...
    }
`

Event is not triggered selecting an item by Mouseclick

**Comment by pkozlowski-opensource** [comment]
Please provide a reproduce scenario in plunker otherwise it is not actionable and will be closed. You need to fill in the issue template when reporting potential bugs.

**Comment by github-mayur** [comment]
Hello.

You can set (change)="function()" event. That will work as onblur for you.
