### ISSUE TITLE
datepicker: customize styling cells based on cell date ("i.e. customClass datepicker-options")

### ISSUE THREAD

**Issue by david-bulte** [ng-bootstrap/ng-bootstrap#761]
### Bug description:

In the "Ui Bootstrap" datepicker, it was possible to customize the look and feel of a single cell, based on a callback method. From the `[documentation](https://angular-ui.github.io/bootstrap/#/datepicker)`:

> datepicker-options $ - An object to configure the datepicker in one place. 
    customClass ({date: date, mode: mode}) - An optional expression to add classes based on passing an object with date and current mode properties.

I'd like this functionality, so as to use the datepicker component as a sort of 'minimal' calendar, where certain kind of events are displayed in a certain color. Clicking that date would then show more details of that event.

**Comment by pkozlowski-opensource** [comment]
It is possible currently by providing a template via the `dayTemplate` attribute, see docs: https://ng-bootstrap.github.io/#/components/datepicker

We've got just a default template for a day view here: https://github.com/ng-bootstrap/ng-bootstrap/blob/63350eef415dca1f2734afe0d547ca125e2bb297/src/datepicker/datepicker.ts#L25-L27 but you can provide your own. 

I know that it is not easy to figure those things out. The biggest issue we've got right now that we've got super-awesome API in place that is very flexible and cover most of use-cases. But we are not doing great job at showing them off :-/ 

I'm going to keep this ticket open so we can provide a demo for a custom day template.

**Comment by Krisa** [comment]
I'd like to leverage the custom template possibility too, but just in order to tweak the original one a little, not to change it completely. Problem is that as we can see in the link you've provided: https://github.com/ng-bootstrap/ng-bootstrap/blob/63350eef415dca1f2734afe0d547ca125e2bb297/src/datepicker/datepicker.ts#L25-L27, `ngbDatepickerDayView` is used for building the template, but it's not part of the exported array: https://github.com/ng-bootstrap/ng-bootstrap/blob/63350eef415dca1f2734afe0d547ca125e2bb297/src/datepicker/datepicker.module.ts#L26 and thus throw an error when trying to reuse this component. Could we add it to the array?

**Comment by maxokorokov** [comment]
Hey, @Krisa. Just want to get your use case. Will having more precise styling like say `ng-bootstrap-datepicker-day`, `ng-bootstrap-datepicker-day-selected` help?

**Comment by Krisa** [comment]
My use case is actually to slightly extent the default template, by specifying a custom class. I've managed to replicate the previous template by doing so:

```
<template #dtcustom let-date="date" let-currentMonth="currentMonth" let-selected="selected" let-disabled="disabled">
  <div [class.bg-primary]="selected"
      [class.text-white]="selected"
      [class.text-muted]="disabled"
      [class.reservation]="hasReservations(date)"
      class="btn-secondary">
    {{ date.day }}
  </div>
</template>
```

and yes, as you can see I've added class.reservation which is not part of the original template.

Also, I had to specify some CSS rules for .btn-secondary which are not defined in the base CSS bootstrap, but in `ngbDatepickerDayView`:

```
.btn-secondary {
  text-align: center;
  padding: 0.185rem 0.25rem;
  border-radius: 0.25rem;
}
```

All in all it works now,  but I was hoping for something more straightforward for my use case, which was nothing more than adding a conditional CSS class to the day template.

**Comment by maxokorokov** [comment]
Thanks for the response, @Krisa. As we're thinking of ways to easier customize look-and-feel any feedback is valuable.

**Comment by AntoninoBonanno** [comment]
@maxokorokov I would like to customize the day class based on a condition (add a class based on a condition), this to indicate if that day the structure is closed or open. If I use the dayTemplate as recommended by @0cv I lose many default behaviors such as onHover animations and I have to check that all the conditions are correct to have the default behavior.

Isn't it possible to have an easier way to customize the day class? For example pass a callback function to the ngbDatepicker to retrieve additional classes to apply to the day?
