### ISSUE TITLE
activeId is not updated

### ISSUE THREAD

**Issue by akram1905** [ng-bootstrap/ng-bootstrap#762]
I'm not sure if this is a bug or "_by design_", the `activeId` is not updated automatically when client click any tab!
This will force developer to add `change` event to keep track of the `activeId` with something like:

```
beforeChangeTab(e) {
    this.selectedTab = e.nextId;
  }
```

You can see this in your demo('Select an active tab by id'), for example try:

1. Open [Tabs demo](https://ng-bootstrap.github.io/#/components/tabs).
2. Scroll to 'Select an active tab by id' demo.
3. Click on 'Fancy title' tab.
4. Click 'Toggle selected tab'. **This should select 'Simple' tab, but in reality nothing happens.**

**Comment by akram1905** [comment]
**Suggestion:**
Change the demo to use `select` method instead!

**Comment by pkozlowski-opensource** [comment]
Yes, this is by design. See more info in #594. 

> Change the demo to use select method instead

Yup, going to send a PR for this.

**Comment by akram1905** [comment]
Thanks!
