### ISSUE TITLE
ngbDropdown not recognizing methods

### ISSUE THREAD

**Issue by doorman02** [ng-bootstrap/ng-bootstrap#765]
I am trying to call the open and close methods on the ngbDropdown  component but it gives me the error close is not a function. Wondering if I am doing something wrong with the # reference, is this code not correct?

```
<div #mydropdown ngbDropdown class="d-inline-block" (window:mouseup)="mydropdown.close()">
      <button class="btn btn-outline-primary" id="dropdownMenu1" ngbDropdownToggle>Toggle dropdown</button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
        <button class="dropdown-item">Action - 1</button>
        <button class="dropdown-item">Another Action</button>
        <button class="dropdown-item">Something else is here</button>
      </div>
    </div>
```

**Comment by doorman02** [comment]
Hi @jnizet unfortunately I get Template parse errors:There is no directive with "exportAs" set to "ngbDropdown"

**Comment by doorman02** [comment]
Hi again @jnizet  actually works previously I removed ngbDropdown from the node
so this works <div #mydropdown="ngbDropdown" ngbDropdown class="d-inline-block" (window:mouseup)="mydropdown.close()">

**Comment by pkozlowski-opensource** [comment]
Sounds like a support question that got resolved.
