### ISSUE TITLE
ngbDatepicker popup shows no directive with exportAs set to ngdatepicker

### ISSUE THREAD

**Issue by beckmeindia** [ng-bootstrap/ng-bootstrap#771]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: latest rc6

ng-bootstrap: latest

Bootstrap: latest

**Comment by pkozlowski-opensource** [comment]
@beckmeindia please follow the issue template when reporting potential issues (most importantly provide a plunker with a reproduce scenario). This issue is not actionable as-is.

**Comment by makafsal** [comment]
How to do this? Please update docs or provide example. Latest version still has the same problem.

**Comment by pkozlowski-opensource** [comment]
> Please update docs or provide example. Latest version still has the same problem.

@makafsal what problem exactly? The issue was closed since there was _no_ way of knowing what the issue is. Follow our template issue, provide reproduce scenario and we can help. No reproduce scenario = no actionable.

**Comment by makafsal** [comment]
We're trying to render datepicker inside ng-bootstrap modal. But then this error is thrown saying there is no exported directive.

**Comment by jnizet** [comment]
@makafsal Start from one of the modal demos at https://ng-bootstrap.github.io/#/components/modal. 

Click on the plunkr icon link at the top-right of the demo, and reproduce the problem you're having by forking the plunkr and adapting the code. 

When you have reproduced the bug, then post the URL of your forked plunkr, and explaining precisely what the expected behavior is, and what the actual behavior is.

**Comment by makafsal** [comment]
It is working on plunkr demo http://plnkr.co/edit/uTADFZrOUPPczn0U7ctJ?p=preview. But this error is being displayed when we use it in our project.

There is no directive with "exportAs" set to "ngbDatepicker" ("   <input class="form-control" placeholder="yyyy-mm-dd" name="dp" [(ngModel)]="model" ngbDatepicker [ERROR ->]#d="ngbDatepicker">

**Comment by sreedharbukya** [comment]
I am also getting same error. aot build  is successful but datepicker is not showing up in UI.

**Comment by ashnashamim** [comment]
I'm facing the same issue , please help

**Comment by tzwickl** [comment]
Same issue here, please help

**Comment by RLTmultimedia** [comment]
+1, please help

**Comment by pkozlowski-opensource** [comment]
@sreedharbukya @ashnashamim @tzwickl @RLTmultimedia please stop commenting on closed issues without any additional info. If you believe that you are facing "the same issue" (how can you know without reproduce scenario???) than please open a new issue following our submission guidelines: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

If you are unsure if this is a bug in this library and need support please use an appropriate channel: https://github.com/ng-bootstrap/ng-bootstrap#getting-help

I'm going to lock this issue as it accumulated quite a bit of noise without any actionable details.
