### ISSUE TITLE
dropdown how to call open or close mthod

### ISSUE THREAD

**Issue by faisalloe** [ng-bootstrap/ng-bootstrap#774]
trying to find an example where i can learn how can i bind dropdown with angular2 component so that i can call open or close methods.. any help is appreciated

**Comment by pkozlowski-opensource** [comment]
I've answered this on SO here: http://stackoverflow.com/questions/39603711/ng-bootstrap-example-calling-method-from-component/39610607#39610607

What we should do in this issue is to add a demo showing how to open / close a dropdown from "outside".

**Comment by pkozlowski-opensource** [comment]
Hmmm, actually it looks like we've got a but in the impl - as soon as you try to open a dropdown from "outside" [this line](https://github.com/ng-bootstrap/ng-bootstrap/blob/667833c7af0bfb465e547b65d9eadc15bdbcb218/src/dropdown/dropdown.ts#L15) comes into play and closes the dropdown immediately... So currently it is pretty much impossible to open a dropdown from outside without too much gymnastic (calling `preventDefault()`  on a click event or disablig autoclose)....

We start to pile up issues on dropdown where inside / outside clicks are getting in a way so we might need spending a bit more time on this widget...
