### ISSUE TITLE
[FR] ngbPopover sample with TemplateRef

### ISSUE THREAD

**Issue by wendro** [ng-bootstrap/ng-bootstrap#776]
### Feature Request description:

Please add sample with using TemplateRef instead of simple (string) popup content. 
Content with image and text would be great (rich html content - template driven vs simple string content).

**Comment by pkozlowski-opensource** [comment]
But we've got one already... What do you miss from "HTML and bindings in popovers" in https://ng-bootstrap.github.io/#/components/popover ?

**Comment by wendro** [comment]
Damn, spent some time trying to figure out how to use the TemplateRef and the answer was served upfront. Mea-culpa - time to think about vacations. Keep up the good work! closing.

**Comment by vikrantsahoo** [comment]
Please find sample from Plunker -
[](http://plnkr.co/edit/Zxt1Cs1QDvuKYl5vzQh3?p=preview)
