### ISSUE TITLE
Alert won't self close using OnPush strategy 

### ISSUE THREAD

**Issue by Hongbo-Miao** [ng-bootstrap/ng-bootstrap#793]
### Bug description:
Alert won't self close using OnPush strategy. It works well without using it.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/oHLExL?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:
- Angular 2.0.0
- ng-bootstrap 1.0.0-alpha.6
- Bootstrap 4 Alpha 4

**Comment by Hongbo-Miao** [comment]
@pkozlowski-opensource Like the issue https://github.com/ng-bootstrap/ng-bootstrap/issues/775, guess need similar way to handle it.

**Comment by pkozlowski-opensource** [comment]
@Hongbo-Miao why do you think it should be handled on the alert side?

**Comment by Hongbo-Miao** [comment]
I guess most people would think it just should self close automatically. They may spend some time find the issue until they find it is because of OnPush.
What is your suggestion, we'd better manually trigger the change detection or not using OnPush?

**Comment by Hongbo-Miao** [comment]
Another reason is before the breaking change, the old self closing alert works well with OnPush.

**Comment by pkozlowski-opensource** [comment]
So `OnPush` means kick off change detection on:
* input change
* event _subscribed to from a component_

In your particular situation there is an observable with time component (equivalent of `setTimout` for the purpose of this discussion) and this obviously doesn't kick off CD. If we follow the logic of adding call to CD in the `close` method we would have to add it to **each and every method call in all components** which obviously doesn't make sense. 

More than this - any component from any library would behave as ngb-alert does now.

I don't think we are going to do anything in this lib to "fix" this use-case.

**Comment by Hongbo-Miao** [comment]
Kind of make sense, thanks. I will close it now
