### ISSUE TITLE
pagination: pageChange not fired after collectionSize change

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#800]
Simple pagination use case with 10 items per page, 3 pages:
```javascript
<ngb-pagination [collectionSize]="collectionSize" [(page)]="page"></ngb-pagination>
```
`[1, 2, *3]` → three pages, `page` = 3, `collectionSize` = 30

If you reduce `collectionSize` to 20, `page` should become 2 → `[1, *2]`
But actually in this case `pageChange` event is not emitted at all

**Comment by maxokorokov** [comment]
Actually the fix should be quite straightforward → do the `pageChange.emit()` from `ngOnChanges`, but it won't work, because it gives `Expression has changed after it was checked` exception for the `page`. 

So the two options I see now (that are the same actually):
- make `pageChange` an asynchronous `EventEmitter` → uses `setTimeout()` internally
- replace `page` with `ngModel` → uses `Promise.resolve(null)` internally

P.S. Must be the same issue for the rating component, haven't checked though

**Comment by wesleycho** [comment]
We should probably use something like
```ts
@Input() set _collectionSize(size: number): number {
  this.collectionSize = size;
  // update page then call this.pageChange.emit(...)
}
```

**Comment by wesleycho** [comment]
Hm, if we do that approach, we would have to rethink our approach with using ngOnChanges.
