### ISSUE TITLE
Rating: allow stars customisation and fine-grained ratings

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#801]
The rating component currently has two issues:
- it uses hardcoded &#9733; and &#9734; symbols
- it doesn't allow half- and fine-grained ratings like `3.75 / 5`

I think that default solution should stay the same as now → hardcoded html symbols

My suggestion to fix problems above is threefold:

- [x] Allow an optional template to display a star and `3.75`rating the way user wants
- [x] Allow decimal numbers as model values via `[(rate)]` binding
- [x] Allow `<template>` to be a child of `<ngb-rating>`
- [ ] Allow optional mouse selection of half-stars via the `[halfStars]` flag (as in #669)

So a user would be able to select either `1, 2, 3 (default)` or `1, 1.5, 2, 2.5, 3 (halfStars=true)` with the mouse and display any rating he wants like `4.06`. It will also allow using external libs like glyphicons or font awesome for star display.

The proposed API is:

```html
<template #t let-fill="fill">
  <!-- fill is a number between 0-100 to represent how the star is filled -->
</template>

<ngb-rating [(rate)]="currentRate" [starTemplate]="t" [halfStars]="true"></ngb-rating>
```

Let me know what you think. I might start with adding custom templates.

**Comment by pkozlowski-opensource** [comment]
I believe that with #833 landed we are done here.

**Comment by Hongbo-Miao** [comment]
@pkozlowski-opensource I think "allow optional mouse selection of half-stars" it still not implemented.

**Comment by joaopgrassi** [comment]
Yes.. the half-stars only works in a "read-only" way. You cannot hover the mouse and select half of a start. Would be really nice feature to have.

**Comment by mpaolor** [comment]
> Yes.. the half-star only works in a "read-only" way. You cannot hover the mouse and select half of a star. Would be really nice feature to have.. is this going to come any time?

yeah it would be awesome! is it gonna come?
