### ISSUE TITLE
Carousel should have _getSlideIdxById as public function

### ISSUE THREAD

**Issue by wesleycho** [ng-bootstrap/ng-bootstrap#802]
I was going through programmatic selection of slides in the carousel with a co-worker, and it turns out that for programmatically setting the current slide, the `_getSlideIdxById` function would be very useful for getting the information needed to pass into the `carousel.select` function. Currently we ended up having to rewrite that functionality on the user side, and I see this being a common problem.

Conversely, it can be useful to get the information on what is the currently selected slide from the carousel - if not by making public `_getSlideById`, at the least having an appropriate output that emits the new value every time it changes.

**Comment by icfantv** [comment]
I have no issue with this.

**Comment by wesleycho** [comment]
Adding comment here - the problem apparently is that the `select` function in the carousel has its argument misnamed. It should be `slideId`, not `slideIdx`.
