### ISSUE TITLE
ngbDropdownToggle double triggers on child element

### ISSUE THREAD

**Issue by karptonite** [ng-bootstrap/ng-bootstrap#803]
### Bug description:
When you have the ngbDropdownToggle on a button element, and a span inside that button element, clicking on the span (inside the button) does not toggle the dropdown (or, more specifically, I think it double-toggles it back to its original state).

This bug is new as of alpha 6--it may be related to the change from HostListener to (click) for handling the event. The bug was observed using chrome version 53.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/TyaAkbqHeLq7HidFzpNf?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.0.0? whatever the sample plunker defaults to--it does not specify

ng-bootstrap: 1.0.0-alpha.6

Bootstrap: 4.0.0-alpha.4

**Comment by pkozlowski-opensource** [comment]
@karptonite thnx for reporting, this is indeed a bug on our side (luckily with an easy fix!). What needs changing is [this line](https://github.com/ng-bootstrap/ng-bootstrap/blob/a173e403c93d1bdf02c154034f03419380a9b488/src/dropdown/dropdown.ts#L107) to listen for child elements as well (`this._toggleElement.contains`).

A new test should be added, similar to the existing one: https://github.com/ng-bootstrap/ng-bootstrap/blob/a173e403c93d1bdf02c154034f03419380a9b488/src/dropdown/dropdown.spec.ts#L167-L191

PRs welcomed!

**Comment by JNKielmann** [comment]
Is anyone working on this? Otherwise I would try to make a PR.

**Comment by pkozlowski-opensource** [comment]
@JNKielmann looks like we've got a PR for this one already #810
