### ISSUE TITLE
Modal doesn't call ngOnDestroy when closing

### ISSUE THREAD

**Issue by natcohen** [ng-bootstrap/ng-bootstrap#806]
When using modal with an external component like this:

```
<template #addEntity="" let-c="close">
  <add-entity [close]="c"></add-entity>
</template>
```

`ngOnInit` is being called but `ngOnDestroy` is never called (backdrop close or close function...).

**Comment by wesleycho** [comment]
This sounds potentially more like an Angular bug than an ng-bootstrap one - @pkozlowski-opensource what do you think? NgbModalRef is removing the modal elements by calling viewContainerRef.remove, this seems like a deficiency in ViewContainerRef.

**Comment by pkozlowski-opensource** [comment]
Agree with @wesleycho that it looks like a bug / sth missing in the Angular itself. I will try to reduce the scenario to sth that is not using ngb and report / fix it upstream. 

Of course if anyone else has free cycles to provide a simpler reproduce scenario (not involving ng-bootstrap) and report issue upstream - this would be much appreciated!

**Comment by pkozlowski-opensource** [comment]
Looked into this one a bit and I can't reproduce this with Angular only: https://plnkr.co/edit/AiqvW2yzAgY7LFXjwMWG?p=preview

At the same time I can clearly reproduce this with ng-bootstrap + modal: http://plnkr.co/edit/i3ajJvZ3bjQyk2I3rDmy?p=preview

Finally it might be an issue on our side and I think that I know what is going on. I need to investigate further to confirm.

**Comment by meshubh** [comment]
Is this issue fixed.

I still face the issue where in I try to close the modal using the .hide method on the dialogRef but I still see the ngOnDestroy not being called.

bootstrap: 3.0.1
angular: 7.2.2

**Comment by deepabalasundaram** [comment]
I see the same issue as well.

bootstrap: 4.1.3
angular: 8.0.1

**Comment by vasnakos** [comment]
Any news?
I have the same issue with: 

bootstrap: 5.2.3
angular: 15.2.2

**Comment by Draxare** [comment]
Seeing same issue 

bootstrap: 5.3.3
angular: 17.3.11
