### ISSUE TITLE
Typeahead demo: show usage of the catch operator to handle server errors

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#816]
Our wikipedia search demo should illustrate correct usage of the `.catch` operator to handle errors in `http` calls.

**Comment by jnizet** [comment]
I was also wondering if it shouldn't illustrate the use of the `.finally` operator to hide the loading indicator whether the http call succeeds or not.

**Comment by maxokorokov** [comment]
If anybody is going to do that, see the #538 just in case

**Comment by pkozlowski-opensource** [comment]
If I'm not mistaken we need to change:

`.switchMap(term => term === '' ? Observable.of([]) : this._service.search(term))`

to 

`.switchMap(term => term === '' ? Observable.of([]) : this._service.search(term).catch(_ => Observable.of([])))`

@jnizet with my current (very limited) understanding of observables `.finally` won't help as propagating errors down the observable chain would make this observable "dead" so we rather want to "catch" server errors. But this is an interesting point, we should investigate further.

**Comment by jnizet** [comment]
I'm on it, and arrived at the same conclusion. We could chain `finally()` to the `catch()` in your example, but it would be equivalent to a `do()`, and we can thus leave the do() as is.

I also suggest moving the empty string exceptional case handling to the service, to make the code more readable.

**Comment by maxokorokov** [comment]
As you can see I arrived to the same conclusions for now too :)
