### ISSUE TITLE
Modal is not opening even with "ngbModalContainer"

### ISSUE THREAD

**Issue by piernik** [ng-bootstrap/ng-bootstrap#820]
alpha-6

I'm using Your modal example. I have `<template ngbModalContainer></template>` in html but still I have `Missing modal container, add <template ngbModalContainer></template> to one of your application templates.` error.

**Comment by pkozlowski-opensource** [comment]
Sorry, there is not enough info for this to be actionable. Check https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug to see what info we need to be able to investigate. Most importantly we need a live reproduce scenario with plunker or similar.

Nothing is going to happen with this issue without a reproduce scenario in a plunker.

**Comment by piernik** [comment]
Ok.
On Your page https://ng-bootstrap.github.io/#/components/modal
 is example - is there a complete source code for it?

**Comment by pkozlowski-opensource** [comment]
> is example - is there a complete source code for it?

Sure: https://github.com/ng-bootstrap/ng-bootstrap/tree/master/demo/src/app/components/modal although this is probably _not_ what you are looking for. You can use this minimal plunk http://plnkr.co/edit/i3ajJvZ3bjQyk2I3rDmy?p=preview as the base for yours (BTW it was linked from the issue template).

**Comment by wesleycho** [comment]
The template element must be contained in an Angular component somewhere, and not outside the root element used to bootstrap the application.

I believe this should be closed as a support issue, as we have it working in our application on my team at work.

**Comment by pkozlowski-opensource** [comment]
> I believe this should be closed as a support issue, as we have it working in our application on my team at work.

Yep, agreed. @piernik happy to re-open if / when you've got a plunker demonstrating the issue. On top of what @wesleycho said the other potential issue might be one described in #784 (already fixed in master but not released yet).

**Comment by michaelrgalloway** [comment]
@piernik I had the same 'issue' whereas the modal wouldnt open even with the template directive present. My problem was I was missing the entryComponents array in my module that listed the content component. Adding my content in this array fixed the issue. This may or may not be your issue as well.

**Comment by narainsagar** [comment]
I got a fix. I was importing NgbModule in different / wrong module. Make sure you import it in module where you've declared the components (in which you're using modals, etc) **OR** import in the parent i.e., AppModule

Cheers,
9
