### ISSUE TITLE
typeahead: editable false

### ISSUE THREAD

**Issue by c1rus** [ng-bootstrap/ng-bootstrap#829]
I have typeahead input with editable option set to false. 

First I pick something, then i change or clear the value and the model is still there.

http://plnkr.co/edit/iibmbN6xWqRR6GLhCiFG?p=preview

Angular: 2.0.0

ng-bootstrap: 1.0.0-alpha.6

Bootstrap: 4-alpha 4

**Comment by pkozlowski-opensource** [comment]
> I have typeahead input with editable option set to false. First I pick something, then i change or clear the value and the model is still there.

Not sure I understand what you are trying to do. Could you try to actually reproduce your scenario in plunker? It is good that you've linked one but it just seems to be code from our demo page. I can't see editable option being used nor the "then i change or clear the value and the model is still there" part.

Did you forget to save the plunker? 

I _feel_ like you might be trying to do sth similar to what is described here: http://stackoverflow.com/questions/39783936/how-to-clear-the-typeahead-input-after-a-result-is-selected. But yeh, stabbing in the dark...

**Comment by c1rus** [comment]
Oh, sorry, i forgot to save it.

The problem is, when i clear the input, i would expect  that the model will be cleared too.

![capture](https://cloud.githubusercontent.com/assets/11233730/19036950/989a859e-8973-11e6-8198-8fbbfdc8c5e0.PNG)

**Comment by pkozlowski-opensource** [comment]
@c1rus thnx for coming back with more info, I see now. I understand what are you saying but your plunker made me realize that there are few more interesting use-cases around `editable` and user input. I would like to consider them together so this issue requires a bit more thinking / design.

**Comment by StdVectorBool** [comment]
In ui-bootstrap w/ typeahead-editable=false, if you selected "Alabama" but then went back to the input field and started hitting backspace the model would be cleared to correctly put the form into an invalid state.  In ng-bootstrap w/ editable=false the model remains at Alabama which is confusing because it doesn't match the input field.

https://plnkr.co/edit/xezlrdfNvC94xIKhczxw?p=preview
http://plnkr.co/edit/KpiFz2lYieQUFIzIuQUv?p=preview

**Comment by pkozlowski-opensource** [comment]
Yep. I'm planning to work on all the remaining typeahead issues in the coming week, should get to this one as well.

**Comment by c1rus** [comment]
This is now fixed, but i would expect that input will be also cleared (on blur), when i dont select any item.

**Comment by c1rus** [comment]
@pkozlowski-opensource should i open new issue for this?
