### ISSUE TITLE
Simple Modal Error 

### ISSUE THREAD

**Issue by alaa-bourouissi** [ng-bootstrap/ng-bootstrap#831]
I have just copied the simple example of Modal , i get error : caused by: Missing modal container, add <template ngbModalContainer></template> to one of your application templates. 

this is the example : https://gist.github.com/alaa-bourouissi/49a5be4a25db4d4a41955eeb54fa9618

**Comment by pkozlowski-opensource** [comment]
See https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help and https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug.

Most probably you are missing the `<template ngbModalContainer></template>` somewhere in your template (warning to add this is well present on our demo page: https://ng-bootstrap.github.io/#/components/modal)
