### ISSUE TITLE
How to provide custom model for modal

### ISSUE THREAD

**Issue by fedotxxl** [ng-bootstrap/ng-bootstrap#832]
Hello. When I open modal I've got data which is related to this modal and should be accessed by it. There is no property `model` right now. Is it correct?

**Comment by pkozlowski-opensource** [comment]
The template that you pass to the `open()` method of the modal service captures data from the component. So in this template you can use any data from a component. As such the `model` property is not needed.

Send a minimal plunk if you need more info. In any case it is a support question and as such would be better targeted at a support channel, see: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help

**Comment by fedotxxl** [comment]
This is not enough. There are situations where data should live only with modal. When modal dies it should also die.

**Comment by pkozlowski-opensource** [comment]
> This is not enough. There are situations where data should live only with modal. When modal dies it should also die.

In this case you might be looking for https://github.com/ng-bootstrap/ng-bootstrap/issues/680. There is a design doc [linked in this issue](https://github.com/ng-bootstrap/ng-bootstrap/issues/680#issuecomment-250736399) so feel free to comment on it as we are about to start implementation.
