### ISSUE TITLE
Patches are not backwards compatible 

### ISSUE THREAD

**Issue by realappie** [ng-bootstrap/ng-bootstrap#838]
Why are patches not backwards compatible, do you know how semver works?

**Comment by pkozlowski-opensource** [comment]
From http://semver.org/, point 9:

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. **Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version**. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

**Comment by pkozlowski-opensource** [comment]
Also check our roadmap and progress towards stable 1.0.0 release: https://github.com/ng-bootstrap/ng-bootstrap/wiki/Roadmap
