### ISSUE TITLE
Popover: Detect When Popover is Open

### ISSUE THREAD

**Issue by colinmorelli** [ng-bootstrap/ng-bootstrap#841]
See #837 for original issue and some early commentary

Would be great to have the capability to detect when the popover is open. An example use case would be to apply a class to the element that triggers the popover.

### Expose `@Outputs` for `close` and `open` events

**Pros**
 - Components can react to popover state changes more easily (additional customization opportunities)

**Cons**
 - Increases the API footprint

**Example Implementation**

```
<button [ngbPopover]="template" [class.open]="opened" (open)="opened = true" (close)="closed = true"></button>
```

===

### Expose an `isOpen()` method on the popover instance

**Pros**
 - Simplest way to attack the proposed use case, and more declarative in nature

**Cons**
 - Limited customization, and/or more difficult to implement other behavior aside from the proposed use case

**Example Implementation**

```
<button [ngbPopover]="template" #popover="ngbPopover" [class.open]="ngbPopover.isOpen()"></button>
```

===

### Other Considerations

Certainly for the initially proposed use case, the latter is easiest to understand and implement, and makes the most sense. But as soon as you think outside of that use case, the first option is certainly more flexible. For example, if the component wants to react by performing some action when the popover is opened (analytics, maybe, or changing some other part of the page?). The latter aims for a declarative approach, which makes it harder to detect _when it changes_, but easier to detect _what it changed to_. 

Note that a workaround for receiving events when the popover is opened/closed can be accomplished through the use of a child component:

```
class TestComponent implements OnInit, OnDestroy {

  @Output('init')
  init = new EventEmitter();

  @Output('destroy')
  destroy = new EventEmitter();

  ngOnInit() {
    this.init.emit();
  }

  ngOnDestroy() {
    this.destroy.emit();
  }

}
```

```
<template #template>
  <test-component (init)="opened()" (destroy)="closed()"></test-component>
</template>

<button [ngbPopover]="template" #popover="ngbPopover" [class.open]="ngbPopover.isOpen()"></button>
```

**Comment by pkozlowski-opensource** [comment]
How about we do both? 

Regarding event names - what do you think of following BS naming (`shown` / `hidden`: http://v4-alpha.getbootstrap.com/components/popovers/#events)?

Other question - would the same make sense for tooltips?

**Comment by colinmorelli** [comment]
Doing both makes the most sense to me. I can definitely understand not wanting the API for these things to explode, but IMO that's more applicable when talking about exposing customization options than when simply exposing the intended behavior of the components.

As for the event names, I think it makes perfect sense to align them closely with the bootstrap equivalents. Though - and this is admittedly a bit nipicky - it's a little strange that standard DOM event names are in the infinitive form of the verb, but these proposed names are past tense. `(click)="foo()" (shown)="bar()"` feels weird.

As for the last question - I think so. IMO popovers are tooltips with a title and the ability to have compiled content in them. The rest of their behavior is basically the same and should be reflected in their APIs.

**Comment by pkozlowski-opensource** [comment]
@colinmorelli I think that we are in the agreement now :-) PR(s) would be more than welcomed! (as always tests are critical). Thnx for stepping in.

**Comment by EcoFreak** [comment]
Is it possible to use these events application wide?
I need to implement a behavior when tooltips are shown anywhere in the application

thanks
H
