### ISSUE TITLE
Datepicker and months with only 5 rows needed (instead of 6 in most cases)

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#847]
Check this plunk: http://plnkr.co/edit/Z9tecsJTv7tnintVJ3gU?p=preview (or navigate to August 2016 using our demo site).

You will notice that the last row has all days belonging to September 2016 so we could safely drop / not display it. But it would mean that for some months we would have 5 rows only instead of usual 6 so it might create an unpleasant flickering effect in the UI... 

Not sure if we should change this or not but opening so we can discuss / decide.

**Comment by pkozlowski-opensource** [comment]
For the record, both kayak and booking.com would drop the last row in this case.

**Comment by maxokorokov** [comment]
See my comment https://github.com/ng-bootstrap/ng-bootstrap/issues/753#issuecomment-252188117
It's doable now, but we might hide it behind a flag

**Comment by maxokorokov** [comment]
Added an example of how to hide these days in the pull request above. 
Now the question is: do we need to hide this functionality behind a flag in the API or leave like this?

**Comment by pkozlowski-opensource** [comment]
> Now the question is: do we need to hide this functionality behind a flag in the API or leave like this?

Let's put it on a back-burner till we've got more feedback on the current API.
