### ISSUE TITLE
NgbCarousel compile wrong interval _startTimer 

### ISSUE THREAD

**Issue by TkachenkoAptem** [ng-bootstrap/ng-bootstrap#848]
In file [carousel/carousel.ts](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/carousel/carousel.ts#L181)
`if (this.interval > 0) `
`     this._slideChangeInterval = setInterval(() => { this.cycleToNext(); }, this.interval);`
`}`
But compile
`NgbCarousel.prototype._startTimer = function () {`
`   var _this = this;`
`   this._slideChangeInterval = setInterval(function () { _this.cycleToNext(); }, this.interval);`
`};`

Within a couple of days I have to create a query to pull to fix it. While I hard code function
TypeScript try to fix the context of loss of setInterval and removes inspection interval.
`NgbCarousel.prototype._startTimer = function () {`
`  var _this = this;`
`  if ( this.interval > 0 ) {`
`    this._slideChangeInterval = setInterval(function () { _this.cycleToNext(); }, this.interval);`
`  }`
`};`

**Comment by pkozlowski-opensource** [comment]
Uh, effectively, seems like TS is dropping check for `this.interval` :-)

> Within a couple of days I have to create a query to pull to fix it.

In TypeScript? Or are you seeing an work-around in this project?

**Comment by pkozlowski-opensource** [comment]
Wait, actually all is good :-) The if statement in question was only introduced in c5625e8d8197ef989507cdc1a9675f943b346599 that landed in master but wasn't released yet. So the bundle you've got from the latest release version doesn't have this `if` statement and this is normal. Check the TS code from the latest release: https://github.com/ng-bootstrap/ng-bootstrap/blob/1.0.0-alpha.6/src/carousel/carousel.ts#L180-L182

The support for `interval` equals to `0` will be part of alpha.7 (to be released today on early next week).

**Comment by TkachenkoAptem** [comment]
Excellent. Thank you :)
