### ISSUE TITLE
Tooltip / popover - support more positioning options

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#857]
In addition to the default `top`, `bottom`, `left` and `right` we should add support for `top-left`, `top-right`, `bottom-left` and `bottom-right`.

The positioning service is already capable of calculating proper coordinates, the only remaining part is to take care of proper arrows positioning. In angular-ui/bootstrap we were doing this directly in the positioning service but IMO we should try to do it directly in the popover / tooltip window directives (add more CSS rules).

**Comment by pkozlowski-opensource** [comment]
Bonus: if we do this we could use popovers to display date / time pickers in popups.

**Comment by pkozlowski-opensource** [comment]
https://github.com/twbs/bootstrap/commit/8ef66df6d793afbda487c1a4505d0a6576252ec4 might change things for us in respect to this issue.

**Comment by intellix** [comment]
Tried using these as there's nothing stopping me and saw that bottom-left works but not bottom-right is a bit wappy: http://plnkr.co/edit/PoZ8fBskiCkcKeZ1Chvt?p=preview
