### ISSUE TITLE
Feature request: Support Injection of inputs to Modal

### ISSUE THREAD

**Issue by deepu105** [ng-bootstrap/ng-bootstrap#861]
Related to https://github.com/ng-bootstrap/ng-bootstrap/pull/846
Its a good start that now Modal dialogs can use components, but its still not enough if the component cant be passed some content which can be displayed/used inside the dialog.

We are using ui-bootstrap with[ JHipster](https://jhipster.github.io) With ng1 version there was resolve which solved this and it enabled us to open Modal dialogs right from onEnter of a route which was nice. But now we dont see a way to do [this here](https://github.com/jhipster/generator-jhipster/blob/angular-2/generators/client-2/templates/src/main/webapp/app/admin/user-management/_user-management.state.ts#L81)

This is becoming a blocker for our Angular2 migration would appreciate a fix/timeline/workaround or advice

**Comment by pkozlowski-opensource** [comment]
> This is becoming a blocker for our Angular2 migration would appreciate a fix/timeline/workaround or advice

It is trivial to add support for interactions with inputs / outputs, we just can't decide on the API :-) Here is the design doc: https://docs.google.com/document/d/1puwnSknaW3bLg_Ww2ewuILneCom1wbMTArvfFq0YFV8/edit?usp=sharing

It should be resolved as part of alpha.8 but API decision is important here, so if you can help us by reviewing the design doc and contributing your opinion, it would be helpful.

**Comment by deepu105** [comment]
I'm not an Ng2 expert, it still feels like a brand new framework to me 😉 Anyways from the proposals the resolve mechanism seems better. Even ui-router-ng2 does the same for for similar usecase. also it makes migration from ui-bootstrap routers a tad bit easier

**Comment by alexweber** [comment]
I was just about to open this same issue... @pkozlowski-opensource I've reviewed the doc and my 2 cents is that using the resolve/router is the better approach, for the reasons @deepu105 mentioned and also api consistency the router api and with v1 (not that it matters but it's nice)

**Comment by pkozlowski-opensource** [comment]
To help everyone between options presented in the design doc, here is a quick recap of possible options (code from the API / user perspective). The list of options goes as follows:

1. Expose an instance of a component
2. Use `resolve` and expose resolved values on an instance of `NgbActiveModal`
3. Use `resolve` and bind resolved values to component's inputs.

To see how those options would play in practice let's assume that we've got the following components that we want to use as content:

```typescript
class MyContent {
    @Input() foo;
    @Input('bar') _bar;
    @Output() out = new EventEmmiter(); 
    
    constructor(private activeModal: NgbActiveModal) {}  
    
    someMethod() {
       // I need value of foo and _bar here for some reason...
    } 
}
```

### Option 1: Expose an instance of a component

```typescript
  const contentComponentInstance = modalService.open(MyContent).component;
  contentComponentInstance.foo = 'Foo value';
  contentComponentInstance._bar = 5;

  //I can even subscribe to outputs!
  contentComponentInstance.out.subscribe(() => {
    // do sth with output
  });
```

### Option 2: Use `resolve` and expose resolved values on an instance of `NgbActiveModal`

```typescript
  modalService.open(MyContent, {
     resolve: {
         'foo': 'Foo value',
         '_bar': 5
     }  
  });
```

and inside `MyContent` component:

```typescript
someMethod() {
     // I need value of foo and _bar here for some reason...
     console.log(this.activeModal.resolve.foo);
} 
```

In this case:
* speaking about outputs doesn't make sense really
* inputs are not used at all
* we are close to how router works (although working _exactly_ like router would be an overkill IMO)

### Option 3: Use `resolve` and bind resolved values to component's inputs

```typescript
  modalService.open(MyContent, {
     resolve: {
         'foo': 'Foo value',
         '_bar': 5
     }  
  });
```

and inside `MyContent` component:

```typescript
someMethod() {
     // I need value of foo and _bar here for some reason...
     console.log(this.foo);
} 
```

In this case:
* speaking about outputs doesn't make sense really
* one can bind to any instance variable and not only inputs so modal is "forced" to break encapsulation

**Comment by alexweber** [comment]
@pkozlowski-opensource thanks for the detailed break-down!  My vote is for option 2...

**Comment by giniedp** [comment]
definitely option 2. The caller makes only one call, i like that and it looks familiar.
option 1 could coexist. There might be good usecases for having a reference to the component.

option 3 shouldnt exist without an option to disable that behavior. Maybe with another key, like `bind` instead of `resolve`. Not sure if i would use that.

**Comment by deepu105** [comment]
I would also vote for option 2 and if possible co exist with option 1.

Option 2 lets the user decide how to use the resolve and would suffice for
most use cases. Option 1 would work for complex and advanced use cases
which requires more control.

Thanks & regards,
Deepu

**Comment by pkozlowski-opensource** [comment]
@deepu105 and All - after _loooooong_ deliberation I've decided to go with option (1). Here is the reasoning:
* (2) and (3) is too limiting in the sense that it doesn't allow interactions with `@Output`s, methods and lifecycle hooks
* It is not immediately obvious how async and changing outputs should be handled in case of (2) and (3)
* Material design is doing (1) and I would love to work on / share ui-toolkit with them
* (1) is the most flexible, simplest to code and doesn't close doors to having more sugar in the future.

Thnx to all who taken time to review / comment on this issue. PR is here: #903

**Comment by kotmatpockuh** [comment]
@pkozlowski-opensource 
Hi, how can I use `ng-content` with NgbModal ?

**Comment by nasht00** [comment]
Is there an example of this?

**Comment by DerJP** [comment]
The example site features some lines showing this. https://ng-bootstrap.github.io/#/components/modal/examples

**Comment by xyrintech** [comment]
There is an issue with Option 1, the issue is that the view has already been rendered and and lets say if we have use Forms in this then passing the data after initialisation is of no use. 
We might need to configure something in constructor or ngOnInit method.

Please suggest how you can address this concern.

**Comment by shaddyz** [comment]
I agree with @xyrintech, typically you will want to set the inputs of a component before it is initialized. Option 1 doesn't support this.

**Comment by MickL** [comment]
This is working fine: 

```
 const contentComponentInstance = modalService.open(MyContent).component;
  // Set input
  contentComponentInstance.foo = 'b';

  // Subscribe to outputs
  contentComponentInstance.out.subscribe(() => {
    // do sth with output
  });
```

Anyway setting an Input() does not trigger ngOnChanges() which is a crucial feature of Angular components. Any workaround?

**Comment by jim-verys** [comment]
In the case of forms, you could create a method on the modal component that builds your form and then call it from the parent after assigning any needed inputs.
```
// ParentComponent.ts
const modalComponentInstance = modalService.open(ModalComponent).componentInstance;
// Set input
modalComponentInstance.initialFormValues = {...yourInitialFormValues}
modalComponentInstance.buildMyForm();

// ModalComponent.ts
myForm: FormGroup;
buildMyForm() {
  this.myForm = new FormGroup({....})
}

**Comment by jimperris** [comment]
In the case of forms, you could create a method on the modal component that builds your form and then call it from the parent after assigning any needed inputs.
```
// ParentComponent.ts
const modalComponentInstance = modalService.open(ModalComponent).componentInstance;
// Set input
modalComponentInstance.initialFormValues = {...yourInitialFormValues}
modalComponentInstance.buildMyForm();

// ModalComponent.ts
myForm: FormGroup;
buildMyForm() {
  this.myForm = new FormGroup({....})
}

**Comment by woodm1** [comment]
> There is an issue with Option 1, the issue is that the view has already been rendered and and lets say if we have use Forms in this then passing the data after initialisation is of no use.
We might need to configure something in constructor or ngOnInit method.

Please suggest how you can address this concern.

Is there any way of doing this yet? I'd like to call a service from the modal on initialisation using data passed from the parent component. Not possible?

**Comment by giniedp** [comment]
@woodm1 you can pass an injector into the modal options, from there you should have all the freedom you need.

```ts
@Component({ ... })
class MyComponent {
  constructor(private injector: Injector, private modal: NgbModal) {
  }

  open() {
    // simply pass the injector of MyComponent
    this.modal.open(MyModal, { injector: this.injector }) 
  }
}

@Component({ ... })
class MyModal {
  constructor(private comp: MyComponent) {
  }
}
```

**Comment by giniedp** [comment]
yes, this will lead into circular dependency. What you need is the forwardRef, see
https://angular.io/api/core/forwardRef

**Comment by giniedp** [comment]
Another useful technqiue is to create a custom injector
https://angular.io/api/core/Injector

```ts
this.modal.open(MyModal, {
  injector: Injector.create([{
    provide: MyModalOptions, useValue: { foo: "bar" }
  }], this.injector)
}) 

@Component({ ... })
class MyModal {
  constructor(private options: MyModalOptions) {
  }
}
```

**Comment by woodm1** [comment]
> yes, this will lead into circular dependency. What you need is the forwardRef, see
> https://angular.io/api/core/forwardRef
> 
> Edit: wont fix the circular dependency warning though

Is it a recommended solution anyway then?

All I want to do is pass a string to my modal that I can use within the component from initialisation. 

I'll try that custom injector approach, thanks for that. Is it really necessary though to have to create a separate class definition just so I can pass and use a string?

**Comment by woodm1** [comment]
Ah, got it now with the custom injector.

Thanks for your help, much appreciated.

**Comment by alexandis** [comment]
How to pass variable to `NgbModal` markup which is `ng-template`, not a separate `Component`?
