### ISSUE TITLE
core.umd.js:3464 ORIGINAL EXCEPTION: this.modalService.open is not a function

### ISSUE THREAD

**Issue by kolkov** [ng-bootstrap/ng-bootstrap#865]
Angular: 2.0.0

ng-bootstrap: alpha7

Bootstrap: alpha4

Try to use 2nd exemple in my code:
![image](https://cloud.githubusercontent.com/assets/3740898/19250337/6e086efc-8f42-11e6-967d-cc301b523eae.png)

**Comment by pkozlowski-opensource** [comment]
@kolkov we need a reproduce scenario, see: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

I _think_ that you've missed https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#breaking-changes:

> The NgbModule module must now import using the forRoot() static method. Check the updated installation instructions for more details.

More info on https://github.com/ng-bootstrap/ng-bootstrap#installation (watch out for `NgbModule.forRoot()`)

**Comment by kolkov** [comment]
Oh-ah! You are changed bootstrapping for NgbModule:
```
@NgModule({
  declarations: [AppComponent, ...],
  imports: [NgbModule.forRoot(), ...],
  bootstrap: [AppComponent]
})
export class AppModule {
}
```

**Comment by pkozlowski-opensource** [comment]
>  You are changed bootstrapping for NgbModule

Yes, this was done to properly support lazy loading. You should really be checking our breaking changes section, it is still alpha :-)

**Comment by kolkov** [comment]
Thanks! ))

**Comment by kolkov** [comment]
What caused this error?
`core.umd.js:3464 ORIGINAL EXCEPTION: No component factory found for NgbdModalContent`

**Comment by pkozlowski-opensource** [comment]
@kolkov I'm sorry, we really can't help without a minimal plunker with a reproduce scenario....

**Comment by pkozlowski-opensource** [comment]
> core.umd.js:3464 ORIGINAL EXCEPTION: No component factory found for NgbdModalContent

You need to add it to `entryComponents` in your module.

**Comment by kolkov** [comment]
Thanks! Now I see this instruction))

**Comment by kolkov** [comment]
That's worked! )
![image](https://cloud.githubusercontent.com/assets/3740898/19253646/3e7b4a2a-8f55-11e6-9d26-6008c9e6ba7d.png)
