### ISSUE TITLE
Component reference does not work inside Tabset 

### ISSUE THREAD

**Issue by Basewq** [ng-bootstrap/ng-bootstrap#866]
As seen in this [plunker](http://plnkr.co/edit/57ey6Sukb6KHEXFfAKWh?p=preview) a component reference inside a tabset does't appear in the main component (press the button and view the console log). I suspect it's because it's in a template, however I'm unsure if there's some way for angular to detect that it now exists.

**Comment by pkozlowski-opensource** [comment]
Hmm, I was expecting that ng2 can't query through template boundaries but it seems like `ngIf` is doing the right thing here: https://plnkr.co/edit/UefhnTEnNzPwryuIFwhe?p=preview

Need to investigate more and eventually open an issue upstream.

**Comment by pkozlowski-opensource** [comment]
This is the limitation of the Angular itself. Closing based on angular/angular#12284 (comment) - I will raise it with others in the Angular team but I don't think that this limitation can be relaxed in the near future.
