### ISSUE TITLE
Document how to use NgButtonGroup with ReactiveFormsModule

### ISSUE THREAD

**Issue by ufoscout** [ng-bootstrap/ng-bootstrap#869]
The documentation of the buttons ( **https://ng-bootstrap.github.io/#/components/buttons** ) shows how to use the radio button group with ngModel; however, Reactive Forms are quite common in Angular 2, in this case the formControlName directive is used instead of the ngModel one. The issue is that it is not clear how to set the "active" status of the buttons when using the formControlName directive.
Could you please provide an example?

**Comment by pkozlowski-opensource** [comment]
@ufoscout we've got [a bunch of unit tests](https://github.com/ng-bootstrap/ng-bootstrap/blob/d1a22c007888d96c97c4c8671724b2560e8fbc08/src/buttons/radio.spec.ts#L299-L339) that can serve as the usage example for now.

When you figure things out on your side you could send us a PR to add demo. Button demos are located [here](https://github.com/ng-bootstrap/ng-bootstrap/tree/master/demo/src/app/components/buttons/demos).

**Comment by ufoscout** [comment]
@pkozlowski-opensource thanks for your help! Could you also provide an example for the check-box buttons? The documentation says that no specific directives are needed; however, in the following example, how can the [class.active] be set to the correct value when using reactive forms?

Template driven:
```
<div class="btn-group" data-toggle="buttons">
  <label class="btn btn-primary" [class.active]="model.left">
    <input type="checkbox" [(ngModel)]="model.left"> Left (pre-checked)
  </label>
</div>
```

Model driven:
```
<form [formGroup]="model">
  <div class="btn-group" data-toggle="buttons">
    <label class="btn btn-primary" [class.active]="????????"> <!-- 'model.left' does not work here -->
      <input type="checkbox" formControlName="left"> Left (pre-checked)
    </label>
  </div>
</form>
```

**Comment by maxokorokov** [comment]
Hey, @ufoscout. I guess you just need to access the control and its value like:

```html
<form [formGroup]="model">
  <div class="btn-group" data-toggle="buttons">
    <label class="btn btn-primary" [class.active]="model.get('left').value"> <!-- or simply model.value.left  should work too -->
      <input type="checkbox" formControlName="left"> Left (pre-checked)
    </label>
  </div>
</form>
```

**Comment by granella** [comment]
ngRadioGroup does not work with formControlName

**Comment by dmytroyarmak** [comment]
@granella Can you please provide more details? 
I've added a demo of using `ngRadioGroup` with `formControlName` and it looks fine: https://github.com/ng-bootstrap/ng-bootstrap/pull/1299/files

**Comment by granella** [comment]
@dmytroyarmak please ignore my comment rsrsrs
