### ISSUE TITLE
Support Yarn

### ISSUE THREAD

**Issue by wesleycho** [ng-bootstrap/ng-bootstrap#872]
We should add [Yarn](https://yarnpkg.com/) support - this appears to be as simple as generating a `yarn.lock` file and checking it into Git.

**Comment by pkozlowski-opensource** [comment]
Yep, we should test / add yarn support as soon as angular is doing it.

**Comment by pkozlowski-opensource** [comment]
So to generate lock file we should update our dependencies across the board. We should do it in 2 steps:
* [ ] bump up all versions that are simple to update
* [ ] move to WebPack 2.0
