### ISSUE TITLE
"No provider for NgbModalStack" error when using the modal

### ISSUE THREAD

**Issue by h284611** [ng-bootstrap/ng-bootstrap#875]
### Bug description:

I was trying to add the simplest modal dialog to my app (see the bottom of https://github.com/h284611/ng2BootstrapTest/blob/master/app/components/work-order/work-order.component.html), and getting the following error:

core.umd.js:3370 EXCEPTION: Uncaught (in promise): Error: Error in http://localhost:9001/app/components/work-order/work-order.component.js class WorkOrderComponent_Host - inline template:0:0 caused by: No provider for NgbModalStack!

I looked into the bootstrap code and found the NgbModalStack is not exported.

Is this a bug, or did I do anything wrong in my code?

Thank you.

### Link to minimally-working plunker that reproduces the issue:

https://github.com/h284611/ng2BootstrapTest

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.0.1

ng-bootstrap: tried both 1.0.0-alpha.6 and 7 

Bootstrap: 4.0.0-alpha.4

**Comment by pkozlowski-opensource** [comment]
You need to bootstrap your module as `NgbModule.forRoot()` when using alpha.7. See: https://ng-bootstrap.github.io/#/getting-started

Here is a minimal plunker showing a modal in action: http://plnkr.co/edit/i3ajJvZ3bjQyk2I3rDmy?p=preview

If you need further help, please ask questions on one of the support forums: https://github.com/ng-bootstrap/ng-bootstrap#getting-help
