### ISSUE TITLE
Feature (Typeahead): Lose focus when arrow up key on first item

### ISSUE THREAD

**Issue by kjartanvalur** [ng-bootstrap/ng-bootstrap#876]
It would be really nice when you press arrow up on first item the focus would disappear instead of going to last item. It´s really the default behaviour in most cases I think. E.g. search box on http://www.imdb.com
At least have an option for this

Thanks

**Comment by pkozlowski-opensource** [comment]
File to be changed: https://github.com/ng-bootstrap/ng-bootstrap/blob/21de54c523c408ff5317ae2318383f7a4b6b7d76/src/typeahead/typeahead-window.ts#L77-L79

**Comment by pkozlowski-opensource** [comment]
Most test should be done on the https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/typeahead/typeahead-window.spec.ts level + just one more high-level test in https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/typeahead/typeahead.ts
