### ISSUE TITLE
Feature (Typeahead): SelectedItem data binding

### ISSUE THREAD

**Issue by kjartanvalur** [ng-bootstrap/ng-bootstrap#881]
Use case:
Instead of having to configure event handling to get selected value, databinding is more the Angular way. It is also more cleaner code.

Solution:
New output for SelectedItem that you can databind to and if you set it to null then you can clear selected value.

**Comment by pkozlowski-opensource** [comment]
> Instead of having to configure event handling to get selected value, databinding is more the Angular way. It is also more cleaner code.

I assume that you are talking about `selectItem` and if so I will respectfully disagree... There is a no 2-way data binding in Angular 2 really and even the existing sugar like `[(ngModel)]` comes with all sort of corner cases with unidirectional data flow. 

Thnx for the suggestion but we are going to pass on this one.
