### ISSUE TITLE
Typeahead "this._valueChanges.do(...).let is not a function"

### ISSUE THREAD

**Issue by brandoncollins** [ng-bootstrap/ng-bootstrap#887]
http://plnkr.co/edit/iqS2qysDf3CujEIInTYX?p=preview

As of alpha 7, typeaheads no longer work for me. In the plnkr I copied the "Simple Typeahead" example from the demo page. On init the typeahead will throw a ""this._valueChanges.do(...).let is not a function" error.

This may have to do with the way I am bundling rxjs? I believe it is related to #860

**Comment by pkozlowski-opensource** [comment]
Yeh, this is a side-effect of #860, sorry about this. The good news is that I've fixed it today via 53115da1729bbaea6f352ea3912ce147c1e660da. Will cut a release tomorrow.

Closing as this is already fixed in master.
