### ISSUE TITLE
Pagination in Table or Collection

### ISSUE THREAD

**Issue by ialex90** [ng-bootstrap/ng-bootstrap#897]
Hi there, not sure if this is a good place to ask for this, if not, I'll move it and sorry.

I am trying to implement the ngPagination and make it work with a table of values, values coming from a collection, So I am using another plugin for this feature and it looks like this:

```
<tbody>
   <tr *ngFor="let person of people | paginate: { itemsPerPage: 5, currentPage: page }">
         <td>{{person.id}}</td>
         <td>{{person.name}}</td>
     </tr>
</tbody>
```

That's the way your binding the pagination and the table by the collection, How does it work in ng-bootstrap pagination?

I did not find any info on the documentation: https://ng-bootstrap.github.io/#/components/pagination
and honestly, if I personally have to care about the collection, how to render how to limit it by the pageChange event that is triggered after changing the number of page in the pagination component, I'll not use it.

Thanks! :-)

**Comment by pkozlowski-opensource** [comment]
> Hi there, not sure if this is a good place to ask for this, if not, I'll move it and sorry.

Yeh, this is not the greatest place for general support questions: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help

**Comment by ialex90** [comment]
Should I write a question on StackOverFlow about if this library has implemented a way to bind a table and the pagination component? What I think is people will vote my down because they will redirect me to the documentation, as it's the place where it should be that information.

I am not having a code error, compile issues or related to that, it's just to know if you have this feature implemented, or not, if there is a plan to do it and if it is, a sample code for it, as there is nothing about this in the doc.

Thanks,

**Comment by pkozlowski-opensource** [comment]
The pagination has documentation for all the functionality it provides. It is general control that can be used in any context (tables, lists etc.). There are no plans to make this control table-specific.
