### ISSUE TITLE
ngb-accordion not working as expected with *ngIf

### ISSUE THREAD

**Issue by jcb982** [ng-bootstrap/ng-bootstrap#906]
The Following code results in an exception: 'core.umd.js:3370 EXCEPTION: Error in http://localhost:3000/coaching_dashboard/saved-responses/saved-responses-list.component.html:10:8 caused by: Cannot read property 'toggle' of undefined'.

![screen shot 2016-10-18 at 5 56 26 pm](https://cloud.githubusercontent.com/assets/10036935/19497849/369b9ee2-955c-11e6-94a6-91769f0d4b01.png)

This code does not:

![screen shot 2016-10-18 at 5 57 03 pm](https://cloud.githubusercontent.com/assets/10036935/19497873/4bf9780e-955c-11e6-86da-fdd4a14cf5f5.png)

The only difference between the two is that one includes an *ngif statement for ngb-accordion and the other does not.

I'm somewhat new to using Angular. Is this behavior expected?

**Comment by jcb982** [comment]
A little more info. I was able to get this working by moving the button inside a div. So it looks like a scoping issue. 

![screen shot 2016-10-18 at 6 00 29 pm](https://cloud.githubusercontent.com/assets/10036935/19497989/d195740e-955c-11e6-814e-1275eabda15b.png)

**Comment by pkozlowski-opensource** [comment]
> Is this behavior expected?

Yes, you can observe the same behavior in the Angular without involvment of the ng-bootstrap library:
http://plnkr.co/edit/qvs5NhnnuwyYKOLXE3I9?p=preview

> I'm somewhat new to using Angular

Please use a dedicated support forum if you are not sure if you are hitting a bug or not: https://github.com/ng-bootstrap/ng-bootstrap#getting-help

**Comment by anvaya** [comment]
Well, a roundabout way of getting the reference will be add a custom event "onCreate" in your component, and send itself as the argument.

In your main code ts file, declare the variable:
==============
`public componentInsideTab:MyCustomComponent;`

In your HTML file
=============
`<MyCustomComponent (onCreate)="componentInsideTab = $event"></MyCustomComponent>`

In your custom Component
=====================
```
export class MyCustomComponent implements OnInit {

@Output() onCreate = new EventEmitter<MyCustomComponent>();  

ngOnInit() {
      this.onCreate.emit(this);    
}


```
This gets you the reference to the component. You can change the event from onInit to any of the custom property sets as well as per requirements.
