### ISSUE TITLE
Tooltip with container="body" doesn't get removed after host element is destroyed

### ISSUE THREAD

**Issue by PEsteves8** [ng-bootstrap/ng-bootstrap#910]
### Bug description:

If a tooltip with container="body" is currently open and its host element gets destroyed, the tooltip remains open. In my use case the button with the tooltip navigates to another section destroying the current component. In this plunker I used a simple ngIf which creates the same effect.

### Link to minimally-working plunker that reproduces the issue:

Just play around with destroying the component with each of the two buttons.

http://plnkr.co/edit/r73FWAtVxhcbRO4ea00i?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.1.0

ng-bootstrap: alpha-8

Bootstrap: alpha-4

**Comment by pkozlowski-opensource** [comment]
Oh dear, this is a bug indeed... Fixing.

**Comment by PEsteves8** [comment]
Great. Thanks :)
