### ISSUE TITLE
Datepicker input doesn't get `touched` and `ng-touched` properties when choosing a date

### ISSUE THREAD

**Issue by llekn** [ng-bootstrap/ng-bootstrap#918]
### Bug description:
When choosing a date on an input with the `ngbDatepicker` directive on a Reactive Form the corresponding FormControl doesn't get the `touched` property set to `true` nor the input field get the `ng-touched` class.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.0.2

ng-bootstrap: 1.0.0-alpha.8

Bootstrap: 4.0.0-alpha.4

**Comment by pkozlowski-opensource** [comment]
@llekn yup, we are not propagating this info to a control, sadly. It is a bug. The good news is that is should be very easy to fix. The only "real" work in this case will be in writing tests :-) Would you be up to sending a PR?

**Comment by llekn** [comment]
Hi @pkozlowski-opensource  Yes, I've already have a proposed [fix](https://github.com/llekn/ng-bootstrap/commit/19718bb4687247684a06246e283206eedb249d15) and now I'm falling down on the testing rabbit hole.

As soon as I get the test working will send the PR!

**Comment by pkozlowski-opensource** [comment]
> As soon as I get the test working will send the PR!

Awesome! I hope you will manage with tests looking at the existing ones. It shouldn't be _too_ difficult, but feel free to ping us if you hit roadblocks.

**Comment by llekn** [comment]
Hey @pkozlowski-opensource ! I was able to add a test for change of `ng-touched` on input blur [commit](https://github.com/llekn/ng-bootstrap/commit/7587c949dc473de9730d1c9b9cca225ff2f9f321), but I'm struggling to test for `ng-touched` when a date is entered using the datepicker.

Any ideas about how to test that?
