### ISSUE TITLE
Modal Component guide and example throw exceptions

### ISSUE THREAD

**Issue by jgr3go** [ng-bootstrap/ng-bootstrap#921]
### Bug description:

The Modal as a component plnkr linked from the guide doesn't work when you click the button. It throws the exception:

`Error in src/modal-component.html:3:47 caused by: No component factory found for NgbdModalContent` 

I'm actually getting the same error in my own code, not experienced enough with Angular2 yet to be able to figure out how to fix it. 

### Plnkr:

https://ng-bootstrap.github.io/app/components/modal/demos/component/plnkr.html

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.0.2

ng-bootstrap: 1.0.0-alpha.8

Bootstrap: 4.0.0-alpha.4

**Comment by jgr3go** [comment]
On second thought, I did figure it out.  The modal needs to be declared and added to the entryComponents of the module:

```
import { NgbdModalComponent, NgbdModalContent } from './modal-component';

...

@NgModule({
  imports: [BrowserModule, FormsModule, ReactiveFormsModule, JsonpModule, NgbModule.forRoot()], 
  declarations: [App, NgbdModalComponent, NgbdModalContent],
  entryComponents: [NgbdModalContent],
  bootstrap: [App]
}) 
```

starts working again.

**Comment by sersart** [comment]
I added NgbdModalContent to declaration, but it is does not work. Can you please fix Plnkr

**Comment by jgr3go** [comment]
It needs to be added to `entryComponents` as well.  Here's a working plnkr:

http://plnkr.co/edit/3ldNkfXPjZCI7g2QK0xK?p=preview

**Comment by sersart** [comment]
Yes, working. Thanks

**Comment by Syes-K** [comment]
did the entryComponents must be added to the root module?
i add it to the lazy loaded module , but it`s not working

**Comment by jgr3go** [comment]
Yeah, needs to be on the app module.  Haven't quite figured out why.

**Comment by Syes-K** [comment]
crying in the rain

**Comment by pkozlowski-opensource** [comment]
Sounds like a support request that go resolved. If anyone still facing any problems (I hear something about lazy-loaded modules) please open a new issue following the issue template (we _really_ need a minimal reproduction scenario to be able to take meaningful steps, see: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug).

**Comment by Syes-K** [comment]
in the lazy module. we need reimport the NgbModule,just like root module.
```
@NgModule({
    imports: [
        CommonModule,
        FormsModule,
        NgbModule.forRoot(),
        routing
    ],
    providers: [I18nService],
    declarations: [I18nComponent,
        ListComponent, StartComponent, ProjectComponent, ModuleComponent,
        CustomModalContent],
    entryComponents:[CustomModalContent]
})
export class I18nModule {
}
```
then it is working

**Comment by jgr3go** [comment]
Wait, what? The whole reason I opened this was because the docs and official example are broken (I just didn't happen to know how to fix them when I opened it). Those should be updated to use code that actually works.

**Comment by pkozlowski-opensource** [comment]
> Wait, what? The whole reason I opened this was because the docs and official example are broken (I just didn't happen to know how to fix them when I opened it). Those should be updated to use code that actually works.

Could you please provide more info? Specifically, which examples are broken? Just checked https://ng-bootstrap.github.io/#/components/modal and they seem to work correctly. You can even fork a plunker to see a standalone, running example. I would _love_ to fix all the issues but I just can't see it atm... Pleae provide more info so we can make this actionable.

**Comment by pkozlowski-opensource** [comment]
> in the lazy module. we need reimport the NgbModule,just like root module.

@Syes-K this shouldn't be needed and in child components you should just add `NgbModule` instead of `NgbModule.forRoot()`. If this doesn't work could you please open a separate issue for lazy-loaded modules? Just please add a minimal reproduce scenario in a plunker, see: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug)

**Comment by jgr3go** [comment]
The plnkr I linked in the first comment (the one linked from the docs) is what's broken. 

https://ng-bootstrap.github.io/app/components/modal/demos/component/plnkr.html

**Comment by pkozlowski-opensource** [comment]
> The plnkr I linked in the first comment (the one linked from the docs) is what's broken.

@jgr3go oh, I see! So this is a plunker only, I see. I've opened a separate issue to address it: #929
Thnx for reporting and bearing with us :-).

**Comment by jgr3go** [comment]
Sorry, should have been more specific, my mistake -- that's originally what I was trying to convey when I opened it, and then got clouded by me trying to figure out exactly what needed changing, trying to be helpful. :-/

Thanks
