### ISSUE TITLE
Components inside template ngbTabContent are not reachable/usable

### ISSUE THREAD

**Issue by Wandang** [ng-bootstrap/ng-bootstrap#923]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
Using a nested component inside of ngbTabContent is not reachable/usable via ViewChild/locale var.
(I wanted to nest two ngb-tabsets into each other and control the childtabset. Therefore I created another component which hosts the 2nd tabset and from outside I wanted to control it's methods)

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/ulZt1X8UCNEWDPDfb2wP?p=preview
As you can see, after AfterViewInit "testus" is undefined
You can use this template as a starting point: http://plnkr.co/edit/i3ajJvZ3bjQyk2I3rDmy?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:
plnkr Versions (newest I guess)

**Comment by pkozlowski-opensource** [comment]
This is roughly the same as #906 - tl;dr; is that this is not supported in the Angular itself. See https://github.com/ng-bootstrap/ng-bootstrap/issues/906#issuecomment-254757803 for more details.
