### ISSUE TITLE
Problem during build.

### ISSUE THREAD

**Issue by lubkoKuzenko** [ng-bootstrap/ng-bootstrap#940]
```
C:/.../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-ref.d.ts(33,14): error TS1005: '=' expected.
C:/.../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-ref.d.ts(33,31): error TS1005: ';' expected.
```

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:~2.0.2

ng-bootstrap:^1.0.0-alpha.9

Bootstrap:4.0.0-alpha.4

**Comment by lubkoKuzenko** [comment]
the problem was on my build config
good:
`'@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js',`
bad
`'@ng-bootstrap/ng-bootstrap',`

**Comment by pkozlowski-opensource** [comment]
@lubkoKuzenko I _presume_ that you are using TypeScript 1.8 and we've got a pb where we use TS 2.0 syntax (and we should not). I'm going to re-open this issue to fix TS 1.8 compatibility.

**Comment by lubkoKuzenko** [comment]
tsc -version
Version 2.0.3

**Comment by lubkoKuzenko** [comment]
Hi, i've fixed this issue with 
`var project = ts.createProject('tsconfig.json',  {
    typescript: require('typescript')
});`
