### ISSUE TITLE
Don't focus accordion panel title

### ISSUE THREAD

**Issue by cmckni3** [ng-bootstrap/ng-bootstrap#942]
Should the `tabindex` be set to `-1` [here](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/accordion/accordion.ts#L97)?

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.1.0

ng-bootstrap: 1.0.0-alpha.9

Bootstrap: 4.0.0-alpha.5

**Comment by pkozlowski-opensource** [comment]
I think that we shouldn't have `tabindex` there at all and allow natural (order-defined) tab order. Honestly I've got no idea how `tabindex="0"` made it into the template (the only thing to test is if we get right tab order with an empty `href`)

**Comment by cmckni3** [comment]
Removing the tabindex appears to maintain the correct tab order. It also fixed my issue with the input being focused.

See PR #943

**Comment by pkozlowski-opensource** [comment]
> See PR #943

Thnx! I will review / merge as soon as internet & Travis infrastructure is back :-)
