### ISSUE TITLE
Missing animations?

### ISSUE THREAD

**Issue by syrys** [ng-bootstrap/ng-bootstrap#946]
Is it just me or all the animations that come from bootstrap is missing when using this library?

I just tested the demo pages. For example, [go here](https://ng-bootstrap.github.io/#/components/modal), then click one of the "Launch Demo Modal" buttons at the bottom of the page, and you see a modal **instantly** popup. 

In comparison, if you goto the main bootstrap 4 demo page for modals [here](http://v4-alpha.getbootstrap.com/components/modal/), and find and click "Launch demo modal" button under the Live demo section, you see a generic slide down animation.

Is there any reason why these are missing in this library? Or is there some way to enable this that i couldn't find through the documentation? _(if its simply not documented, please consider documenting this, or alternatively make it the default behaviour)._

Also, same applies to all other modules/components that are usually animated, like accordion, toggle/collapse etc.

Cheers.

**Comment by pkozlowski-opensource** [comment]
> Is there any reason why these are missing in this library? 

Animations are work in progress, see: #295

**Comment by syrys** [comment]
@pkozlowski-opensource oh oops, sorry about that. i subscribed to that thread and will keep an eye on it :)
