### ISSUE TITLE
ngb-pagination with query-parameters, when refreshing , always redirect to the first page

### ISSUE THREAD

**Issue by keryhu** [ng-bootstrap/ng-bootstrap#951]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

ngb-pagination with query-parameters, when refreshing , always redirect to the first page

### Link to minimally-working plunker that reproduces the issue:

My test App uses ng-bootstrap and angular2 .

url is : "/show-users"
I get the user data from back server . 
Implemented function is : 

A:  --it works fine 

> a black page ,when click button("show"),it will show
> 4  pages of user datas .corresponding routing are 
> "/show-users?page=0","/show-users?page=1",
> "...page=2","...page=3",

B: --it works fine 

> if i click different page num ,it will rediret to 
> corresponding page . e.g click pageNum=2, it will redirect wo url: "/show-users?page=3"

C: --has problems

when i refresh the page , e.g. refresh "/show-users?page=2", the page will show datas of the third page  . and page num is "3".

The problems is when i refresh page ,e.g."/show-users?page=2" or "3","1", the url is becaming "/show-users?page=2" or "3","1" , 

but it **always redirect to the first page "/show-users?page=0" why ?** , 

html code :

	<button md-icon-button [disabled]="" (click)="startQuery() ">
	  <md-icon class="md-24">search</md-icon>
	</button>
	
	<hr>
	<ul class="list-group">
	  <li class="list-group-item list-group-item-action"
	      *ngFor="let m of user|async"
	      (click)="clickUser(m)">{{m.email}}
	  </li>
	</ul>
	
	<hr>
	
	<div *ngIf="user">
	  <ngb-pagination [collectionSize]="totalPages"
	                  [(page)]="currentPage"
	                  [maxSize]="5" [rotate]="true" [boundaryLinks]="true"
	                  (pageChange)="pageChange()">
	
	  </ngb-pagination>
	</div>

angular2 component: 

	export class RechargeComponent implements OnInit {
	  private url= Constant.adminQueryUserWithPage;
	  private currentPage:number=1;
	  private user: Observable<any>;
	  private totalPages:number=0
	
	  constructor( private http: Http, private request: RequestService,
	              private location: Location, private convert: Convert,
	              private route: ActivatedRoute) { }
	
	  ngOnInit() {
	       if( this.route.snapshot.queryParams){
	      const m=JSON.parse(JSON.stringify(this.route.snapshot.queryParams));
	      console.log(m);
	      if(m['page']){
	
	        this.currentPage=+m['page']+1;
	
	        const r = this.queryUserWithPages();
	        this.user = r.map(e=>e.content);
	
	        this.queryUserWithPages().subscribe(
	          e=>{
	            this.totalPages= e['totalPages']*10
	          }
	        )
	      }
	
	      else{
	        this.user=undefined;
	      }
	    }
	
	    else {
	      this.user=undefined;
	    }
	
	  }
	
	  startQuery(){
	    const result = this
	      .queryUserWithPages();
	    this.user = result.map(e=>e.content);
	    this.queryUserWithPages().subscribe(
	      e=>{
	        this.totalPages= e['totalPages']*10
	      }
	    )
	  }
	
	  pageChange() {
	
	   const result = this
	      .queryUserWithPages();
	    const m={
	      page:this.currentPage-1
	    }
	
	    this.user = result.map(e=>e.content);
	  
	    this.location.replaceState('/show-users',
	      this.convert.serializeToQueryParam(m));
	
	  }
	
	
	
	  // query server data 。
	  queryUserWithPages() {
	    const p = new URLSearchParams();
	    p.set('page', (this.currentPage-1).toString());
	
	    return this.http.get(this.url, this.request.getAuthOptions(p))
	      .map(res=>res.json());
	
	  }
	
	}

You can use this template as a starting point: http://plnkr.co/edit/i3ajJvZ3bjQyk2I3rDmy?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.1.0

ng-bootstrap:1.0.0-alpha.9

Bootstrap:4.0.0-alpha.5

**Comment by pkozlowski-opensource** [comment]
Please provide a _minimal plunker_ demonstrating the issue, otherwise it is not actionable and will be closed:  https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by keryhu** [comment]
sorry,unfamiliar with plunker，```
constructor(private route: ActivatedRoute) {
  }
```
not work

**Comment by kesarion** [comment]
@pkozlowski-opensource 

The pageChange event fires when the set input page is not a number (e.g. when it's a string, undefined or NaN). I also experience the bug described by @keryhu where the pageChange fires with page 1, but I am not able to reproduce this particular issue in plunker.

Here's a [plunker](http://plnkr.co/edit/TDm5rv4RmxIKoWYWp8Qa?p=preview) (console) logging the page being set to a string value of '2' from the route queryParams and the pageChange event firing with the correct value, when it shouldn't fire at all (as with regular numbers).

The issues might be related in some way.

**Comment by pkozlowski-opensource** [comment]
@keryhu commenting on closed issues doesn't make much sense... If you believe that there is a bug that we should fix, please one a new issue. Thnx!

**Comment by kesarion** [comment]
Sure, I wasn't certain what the issue was; now I am.

This is the first and only relevant result on google on the issue. Since people will be landing here, I'll explain the issue and offer a workaround:

When the collectionSize (list total) value is loaded asynchronously, the ngb-bootstrap component resets the page to 1, normally it should stay at the currently set page or switch to the last possible page, if any.

To work around this issue, use `*ngIf="total"` on the pagination component or a parent, so the component will have the current page and collectionSize at the same time and won't reset to 1.

I'll create an issue for it when I have the time if it doesn't exist already. The [plunker](http://plnkr.co/edit/TDm5rv4RmxIKoWYWp8Qa?p=preview) is updated to reflect the issue precisely.

**Comment by MrAlexand0r** [comment]
@keryhu thank you very much!

**Comment by jtan80813** [comment]
Hello! Is this issue fix? I have the same problem too

**Comment by Abd-Alrahman** [comment]
Thanks @kesarion for your answer.
Unfortunately after discovering what the problem was, I found this dicussion.
Wrapping the pagination code with `*ngIf="total"` is the solution.
I refused to apply it at first, but it's the only workaround.

**Comment by aayushpant96** [comment]
@Abdulrahmanh95
@kesarion 
Hey, I tried adding *ngIf = "totalItems" to the parent div of <ngb-pagination> tag where totalItems is my current size. However, even after that when I change the url from lets say 1 to 2, it doesnt work i.e it redirects to 1st page.

Please let me know if I am doing anything wrong.

**Comment by Abdulrahmanh95** [comment]
@aayushpant96 
Can you share some code in order to detect the problem?

**Comment by aayushpant96** [comment]
Hey..Look slike I have solved the problem. We can use ngx-pagination module instead. It simply does the job.

Moreover, I had already posted the entire problem [here](https://stackoverflow.com/questions/54824662/handling-components-inside-another-component-in-angular/57603496#57603496).

**Comment by RandikaNonis** [comment]
> Sure, I wasn't certain what the issue was; now I am.
> 
> This is the first and only relevant result on google on the issue. Since people will be landing here, I'll explain the issue and offer a workaround:
> 
> When the collectionSize (list total) value is loaded asynchronously, the ngb-bootstrap component resets the page to 1, normally it should stay at the currently set page or switch to the last possible page, if any.
> 
> To work around this issue, use `*ngIf="total"` on the pagination component or a parent, so the component will have the current page and collectionSize at the same time and won't reset to 1.
> 
> I'll create an issue for it when I have the time if it doesn't exist already. The [plunker](http://plnkr.co/edit/TDm5rv4RmxIKoWYWp8Qa?p=preview) is updated to reflect the issue precisely.

Thank You very much

**Comment by sunilmondal4you** [comment]
> @Abdulrahmanh95
> @kesarion
> Hey, I tried adding *ngIf = "totalItems" to the parent div of tag where totalItems is my current size. However, even after that when I change the url from lets say 1 to 2, it doesnt work i.e it redirects to 1st page.
> 
> Please let me know if I am doing anything wrong.

Your solution works for me, I used like this
<div *ngIf="totalItems">
                        <ngb-pagination [collectionSize]="totalItems" [(page)]="page" [pageSize]="itemsPerPage" [maxSize]="5" [rotate]="true" [boundaryLinks]="true" (pageChange)="loadPage(page)"></ngb-pagination>
                    </div>

**Comment by Mansimran7** [comment]
Thank you so much, resolved my issue after working on it for days!
