### ISSUE TITLE
Show the rating value in readonly mode

### ISSUE THREAD

**Issue by Hongbo-Miao** [ng-bootstrap/ng-bootstrap#952]
### Bug description:
Right now it shows the value your mouse hovered, even the rating component is readonly.

For readonly rating component, I think it will make sense to show the value that this rating component stands for. In this case, it should be 3.14

OR just provide the choice not showing the "tooltip".

![image](https://cloud.githubusercontent.com/assets/3375461/19634161/86e5ef28-9986-11e6-9460-3885282091f4.png)

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/V6VdESRFzbCobOnfcHvd?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 2.1.1
ng-bootstrap: 1.0.0-alpha.9
Bootstrap: 4.0.0-alpha.5

**Comment by maxokorokov** [comment]
@pkozlowski-opensource is there any particular reason of having `title` set for each span? 

I think I would 

- either move both `title` and `aria-valuetext` to the span that contains all the star templates (next to `aria-valuenow`)
- or remove both of them completely as they're apparenlty redundant to `aria-valuenow` https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuetext_attribute

**Comment by pkozlowski-opensource** [comment]
@maxokorokov maybe @Foxandxss will remember. But yeh, I agree that we should do review of accessibility here.

**Comment by pkozlowski-opensource** [comment]
Fixed by 9b5f99937b7ad06fac461dad8a269e591da8a451
