### ISSUE TITLE
dropdown.ngfactory missing / AOT bug

### ISSUE THREAD

**Issue by JohannesRudolph** [ng-bootstrap/ng-bootstrap#953]
### Bug description:

I've tried to create an AOT build using angular-cli and ng-bootstrap. However, there appears to be an issue during AOT compilation generating an ngfactory for the dropdown component (see below). 

Is anyone else able to AOT build with ng-bootstrap?

```
> ng build --target=${TARGET:-development} --environment=${ENVIRONMENT:-dev} --aot=${AOT:-false}

Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
 13% building modules 28/113 modules 85 active ...rap/ng-bootstrap/dropdown/dropdown.jsresolve '../node_modules/@ng-bootstrap/ng-bootstrap/dropdown/dropdown.ngfactory' in '/Users/jr/dev/console/console/src/app'
  using description file: /Users/jr/dev/console/console/package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/jr/dev/console/console/package.json (relative path: ./src/app)
    using description file: /Users/jr/dev/console/console/package.json (relative path: ./src/node_modules/@ng-bootstrap/ng-bootstrap/dropdown/dropdown.ngfactory)
      as directory
        /Users/jr/dev/console/console/src/node_modules/@ng-bootstrap/ng-bootstrap/dropdown/dropdown.ngfactory doesn't exist
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/jr/dev/console/console/src/node_modules/@ng-bootstrap/ng-bootstrap/dropdown/dropdown.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/jr/dev/console/console/src/node_modules/@ng-bootstrap/ng-bootstrap/dropdown/dropdown.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/jr/dev/console/console/src/node_modules/@ng-bootstrap/ng-bootstrap/dropdown/dropdown.ngfactory.js doesn't exist

/Users/jr/dev/console/console/node_modules/webpack/lib/Compiler.js:220
					if(err) return callback(err);
                    ^
TypeError: Cannot read property 'hash' of undefined
    at /Users/jr/dev/console/console/node_modules/angular-cli/tasks/build-webpack.js:35:26
```

### Link to minimally-working plunker that reproduces the issue:
Not applicable

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.1

ng-bootstrap: 1.0.0-alpha.9

Bootstrap: 4.0.0-alpha.5

angular-cli: 1.0.0-beta.18

**Comment by pkozlowski-opensource** [comment]
@JohannesRudolph I can't seem to reproduce based on the info given (please note that we _do_ have another bug in the AoT support (details in #959) but it is not what you are reporting...

On top of this I don't see `angular-cli: 1.0.0-beta.18` in the npm repository:

> npm ERR! No compatible version found: @angular/compiler-cli@1.0.0-beta.18
npm ERR! Valid install targets:
npm ERR! 2.2.0-beta.0, 2.1.1, 2.1.0, 2.1.0-rc.0, 2.1.0-beta.0, 0.6.4, 0.6.3, 0.6.2, 0.6.1, 0.6.0, 0.5.0, 0.4.1, 0.4.0, 0.3.0, 0.2.0

Could you please put together a _minimal_ repository that would illustrate the problem? Otherwise it is hard to progress on that one...

**Comment by sgybas** [comment]
@pkozlowski-opensource Thanks for your great work. I think you mixed up ```angular-cli``` and ```@angular/compiler-cli```.

I got the same error message today when I tried angular-cli so I created a repository to illustrate the problem: https://github.com/sgybas/ng-bootstrap-953
However, I'm not sure that this as actually a problem in ng-bootstrap. It could also be a bug in angular-cli.

**Comment by JohannesRudolph** [comment]
awesome work @sgybas 

To determine whether this is a bug in angular-cli or ng-bootstrap it would help to know whether others have successfully used ng-bootstrap with AOT before (and in particular the dropdown). Depending on that outcome, we should file the issue over at angular-cli.

**Comment by pkozlowski-opensource** [comment]
@sgybas thnx for the reproduce. I _think_ that what you are guys hitting is a bug in ng itself that was just fixed via a838aba756df510daa3899f73c3732ef4fc571f2. Let's wait for the next ng release (it should be released today).

**Comment by spock123** [comment]
Dropdown factory also missing in my aot builds...

**Comment by pkozlowski-opensource** [comment]
I was able to reproduce with Angular 2.1.1 using https://github.com/pkozlowski-opensource/ng-bootstrap-aot

There is a mix of Angular bugs that we can work-around as well as few things that we've messed up... Sent #973 to fix both...
