### ISSUE TITLE
Feature request (?) ngModel for Dropdown

### ISSUE THREAD

**Issue by rolandoldengarm** [ng-bootstrap/ng-bootstrap#960]
I've looked through the issues, looked at the source code, the demo, but the dropdown doesn't seem to support ngModal? I want to be able to set a model value when somebody selects an element. 

E.g. Rating component does support this

**Comment by pkozlowski-opensource** [comment]
@rolandoldengarm I'm not sure I see how ngModel is relevant to dropdowns... You don't really have any functionality typically present in controls (validation, touched / pristine state etc.), you don't want to use it as part of a form etc. So no, I don't think `ngModel` is relevant here.

It _feels_ like you've got a use case that we haven't thought about (?) but it doesn't _feel_ like `ngModel` is the right answer. 

Maybe you should elaborate more on your exact use-case?

**Comment by rolandoldengarm** [comment]
My use case is pretty simple: I've got a drop down with sort options. I want to keep track of the currently selected sort option in my variable, and trigger an event when the value changes (i.e. sort the data).
Right now I've implemented it manually, 

I don't understand why you do *not* want to keep track of the selected value in a drop down? When would you use it? Just as a menu maybe?

See another example of the MS Office UI Fabric dropdown, it has ngModel: http://ngofficeuifabric.com/demos/uifDropdown/

**Comment by jnizet** [comment]
It seems to me that you rather want a `<select>` box rather than a dropdown, which indeed typically serves as a menu.

**Comment by rolandoldengarm** [comment]
Okay, I thought a select == a dropdown...? At least that's my understanding of a dropdown, and that's how it's working in [Material](https://material.angularjs.org/latest/demo/select) and [Office UI Fabric](http://ngofficeuifabric.com/demos/uifDropdown/)?

**Comment by jnizet** [comment]
bootstrap uses standard (but styled) form controls for selects. Note that the page you linked to in material is titled "Select". The equivalent in material to a bootstrap dropdown (which I don't know well), seems to be what they call a [menu](https://material.angularjs.org/latest/demo/menu). It's typically used as a set f buttons or links, to navigate elsewhere or to trigger an action.

**Comment by rolandoldengarm** [comment]
Confusing that dropdown is used for different reasons, but it makes sense now. 

For reference, [select in bootstrap v4.](http://v4-alpha.getbootstrap.com/components/forms/#select-menu)
