### ISSUE TITLE
Can't not query NgForm from NgbAccordion panel

### ISSUE THREAD

**Issue by CSchulz** [ng-bootstrap/ng-bootstrap#965]
### Bug description:

I have noticed that there is an issue which querying NgForm from an active panel.

```
export class AppComponent implements AfterViewInit {
    @ViewChild('form') private _form;
    @ContentChildren('form', {descendants: true}) private _formList: QueryList<NgForm>;
```

```
<ngb-accordion [closeOthers]="true" activeIds="1" #accordion="ngbAccordion">
    <ngb-panel id="1">
        <template ngbPanelTitle>
            <span>First panel</span>
        </template>
        <template ngbPanelContent>
            <form #form="ngForm">
            </form>
        </template>
    </ngb-panel>
```
### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/lQOd02qEiVx9kf06YVtS?p=preview

Blur the input to see the console output.
### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.1.1

ng-bootstrap: 1.0.0-alpha.9

Bootstrap: 4.0.0-alpha.5

**Comment by pkozlowski-opensource** [comment]
I believe that this is a limitation in Angular 2 itself where you can't query through the boundaries of dynamically inserted templates.

**Comment by pkozlowski-opensource** [comment]
Relevant discussion: https://github.com/angular/angular/issues/12284#issuecomment-256423264

**Comment by pkozlowski-opensource** [comment]
Closing based on https://github.com/angular/angular/issues/12284#issuecomment-256423264 - I will raise it with others in the Angular team but I don't think that this limitation can be relaxed in the near future.
