### ISSUE TITLE
ngb-tabset justified="true" is not supported?

### ISSUE THREAD

**Issue by anvesh48** [ng-bootstrap/ng-bootstrap#967]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Link to minimally-working plunker that reproduces the issue:

You can use this template as a starting point: http://plnkr.co/edit/i3ajJvZ3bjQyk2I3rDmy?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:

ng-bootstrap:

Bootstrap:

**Comment by anvesh48** [comment]
I am having trouble using justified= "true" in ngb-tabset.  Can you please let me know how to use justified="true".

**Comment by anvesh48** [comment]
# @jiverson @icfantv @robwormald @pra85 @cmckni3 
Do you guys know how to use justified="true" in ngb-tabset. It is used for full-width tabs...

**Comment by icfantv** [comment]
hey, @anvesh48 a couple of nits:

1. In the case of your issue, please be respectful of our team and its processes by adhering to the issue template as it will assist us in assisting you.  By you taking the time to create a working plunker, it allows us to immediately dig in to your issue.

2. Please be respectful of people's time and do not tag people in issues or PRs unless you are addressing a concern or question raised by them or you need to make a potentially interested third party aware of something you've filed.

Finally, the justified feature has not been implemented as indicated by its lack of presence in the documentation or in the source code.

**Comment by jnizet** [comment]
@anvesh48 I must add that, AFAIK, justified tabs don't exist anymore in bootstrap 4, on which ng-bootstrap is based. ng-bootstrap most probably won't have justified tabs if bootstrap doesn't have them.

**Comment by icfantv** [comment]
I have created issue #968 for tracking.

**Comment by icfantv** [comment]
Actually, after reading https://github.com/twbs/bootstrap/issues/17723, it's not clear that justified tabs are or are not going to be supported.

**Comment by anvesh48** [comment]
Sorry, guys i respect your time. And thanks for replying back...

**Comment by justforuse** [comment]
You can just add `.nav-fill` class to ngb-tabset, and it is already supported in bootstrap 4:http://v4-alpha.getbootstrap.com/components/navs/#fill-and-justify
here is the plnkr: http://plnkr.co/edit/4q7RdiwhTMPtbjnq9leW?p=preview
