### ISSUE TITLE
Tabset missing full justification option

### ISSUE THREAD

**Issue by icfantv** [ng-bootstrap/ng-bootstrap#968]
We need to add the ability to allow users to specify full justification for tabs.

**Comment by pkozlowski-opensource** [comment]
@icfantv do you have any reference to the justified option being part of Bootstrap 4? I can't seem to find it here: http://v4-alpha.getbootstrap.com/components/navs/#tabs

**Comment by icfantv** [comment]
@pkozlowski-opensource all I can find [is this](https://github.com/twbs/bootstrap/issues/17723) which, unfortunately does not indicate an intention, either way, as to whether or not justified tabs will be supported.

That said, until and unless Bootstrap 4 supports this, I don't think there's anything to do here and I'm happy to close this until then.
