### ISSUE TITLE
Popover content overflows if width is over 260px

### ISSUE THREAD

**Issue by cquillen2003** [ng-bootstrap/ng-bootstrap#971]
HTML content 260px wide or greater overflows the Popover component.

http://plnkr.co/edit/5eHQYoqrmkx00o3ka81s?p=preview

Angular: v2.0.0
ng-bootstrap: v1.0.0-alpha.9
Bootstrap: 4.0.0-alpha.4

**Comment by pkozlowski-opensource** [comment]
This is not specific to this library but rather to Bootstrap's CSS: http://plnkr.co/edit/XM4mZmy1UaVQTxDt7xJJ?p=preview

Indeed, Bootstrap popovers are setting `max-width: 276px`

I'm not sure what would be your expectation in this case but if you believe that this is a bug, please report at https://github.com/twbs/bootstrap

**Comment by cquillen2003** [comment]
Thank you for the info.

My expectation would be to have more control over the popovers width.  I realize that there must be a limit, but a popover roughly 1/4 to 1/3 the width of the screen seems reasonable.  Do you agree?  If so, I'll open a Bootstrap issue.

As an example, consider an app being displayed on a large monitor or TV.  276px is probably too small in that case, even for simple text.

**Comment by pkozlowski-opensource** [comment]
>  I realize that there must be a limit, but a popover roughly 1/4 to 1/3 the width of the screen seems reasonable

You can always override this on your side by modifying Sass variables. In any case yes, this is more of the Bootstrap's CSS concern rather than sth specific to this library.
