### ISSUE TITLE
Syntax Errors while compile time

### ISSUE THREAD

**Issue by ankurkoul92** [ng-bootstrap/ng-bootstrap#972]
![image](https://cloud.githubusercontent.com/assets/23091778/19755085/a17da572-9c30-11e6-8650-79ab09151766.png)

These are some syntax errors that I get. Just wanted to know it it with me or other people are also getting these errors at compile time. If this could be treated as bug would be a lot of help.

**Comment by pkozlowski-opensource** [comment]
Impossible to say anything based on just info provided. We are missing essential info like angular / library version used, TS version etc. See: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

It is not actionable as-is and will be closed without a minimal reproduce scenario (plunker or minimal Github repo for AoT related issues).

**Comment by pkozlowski-opensource** [comment]
It looks like the compilation on your end is failing on usage of string literal types (ex.: ` placement: 'top' | 'bottom' | 'left' | 'right';`) which in turn makes me suspect that you are using an old version of TypeScript. We, as Angular, support TS 1.8+ so make sure that you are compiling with TS version 1.8+.

Going to close for now as based on the info info provided it sounds like a TS version mismatch. Feel free to open with more info if you still believe that this is a bug on our end.

**Comment by ankurkoul92** [comment]
Thanks, for reply. my TS version is 2.0.2.
It looks like I had some dependencies issue, so I updated my devDependencies and dependencies. And my problems were fixed.
