### ISSUE TITLE
Define (HTML and bindings) popover width

### ISSUE THREAD

**Issue by natcohen** [ng-bootstrap/ng-bootstrap#975]
This is a feature request...

It should be possible to define the width of the (HTML and bindings) popovers - fixed and dynamic width (col-sm-X)

**Comment by pkozlowski-opensource** [comment]
You can do this in CSS so I don't think there is a need to involve Angular bindings here: http://plnkr.co/edit/qJy83oAoRhC8GI8adqOl?p=preview

Closing as won't fix since achievable by simpler / more performant means.
