### ISSUE TITLE
Cannot use lazy loaded services in components as content for modals

### ISSUE THREAD

**Issue by TVrijdag** [ng-bootstrap/ng-bootstrap#982]
### Bug description:

In this version an issue has been fixed to open components as content for modals in lazy loaded modules. Unfortunately I have just encountered an issue related to using lazy loaded services within such modal component. Luckily there is no issue with services provided by the main module.

The plunker below throws the error: No provider for LazyService!
### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/G0PBVwHAN7zgOHscCAax?p=preview
### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.1.0

ng-bootstrap: 1.0.0-alpha.10

Bootstrap: 4.0.0-alpha.5

**Comment by pkozlowski-opensource** [comment]
@TVrijdag I'm sorry for missing this one, should have thought that we need pass down the `Injector` as well :-/. This is a _very_ easy fix, will send a patch & cut a new release over the weekend. 

Thnx for bearing with us....
