### ISSUE TITLE
Dynamic content (such as a tooltip) does not get attributes for Angular 2 CSS scoping

### ISSUE THREAD

**Issue by avbentem** [ng-bootstrap/ng-bootstrap#984]
### Bug description:

For the default `ViewEncapsulation.Emulated`, when a component defines either `styles` or `styleUrls`, Angular 2 adds extra attributes for CSS scoping, [like](https://angular.io/docs/ts/latest/guide/component-styles.html#!#inspect-generated-css) `_nghost-pmm-5`, `_nghost-pmm-6` and `_ngcontent-pmm-6` in:

```
<hero-details _nghost-pmm-5>
  <h2 _ngcontent-pmm-5>Mister Fantastic</h2>
  <hero-team _ngcontent-pmm-5 _nghost-pmm-6>
    <h3 _ngcontent-pmm-6>Team</h3>
  </hero-team>
</hero-detail>
```

It then also rewrites the CSS to scope it to those attribute names.

However, dynamic ng-bootstrap content such as a tooltip does not include such scope. This implies:
- One needs to include the Twitter Bootstrap CSS to the global scope (like in `index.html` rather than using `styleUrls`), for otherwise the tooltip is not styled. Such global scope might affect the layout of other parts of the application.
- Additional styling defined in a component is not applied to dynamic content, as Angular rewrites the CSS to scope it, but that rewritten CSS does not match the non-scoped dynamic HTML.

I'm sorry, I don't know if Angular even supports rewriting of dynamic content.
### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/IJhqSqGTaE6vAJq0LlDD?p=preview
### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.0.0 - 2.1.2

ng-bootstrap: 1.0.0-alpha.10

Bootstrap: v4-alpha

**Comment by PEsteves8** [comment]
You can use :host /deep

Here your plunker with it: http://plnkr.co/edit/KFe4IdtuoGQurm9ws9uJ?p=preview

I think it has been recently added to the docts on "Component Styles". I don't think it was there a while ago.

However, I'm guess it won't work if tooltip's container is set to body (container="body")

**Comment by avbentem** [comment]
Using `:host /deep/` indeed solves the 2nd bullet (though indeed not for `container="body"`), for styling defined in `styles` or `styleUrls`. (For future readers: Angular will then not rewrite the CSS to `.tooltip-inner[_ngcontent-xxx]{ ... }`, but to `[_nghost-xxx] .tooltip-inner{ ... }`. Nice.)

To use `:host /deep/` to solve the 1st bullet (if one does not want to include the Bootstrap styling to the global scope), one needs to add `:host /deep/` to all of the vendor's http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css and then load that using `styleUrls`. That would need some pre-processing, but I guess it's doable. (Maybe some [loader for webpack's `require`](https://webpack.github.io/docs/loaders.html) already exists.)

I don't know if Angular supports scope when creating elements, so I don't know if `:host /deep/` is a workaround, or is the documented preferred solution. But I think I will need to use this trick for NPM packages that are not aware of Angular at all (such as OpenLayers, which I don't want to load in global scope either), so it's a good solution for me. Thanks!

**Comment by avbentem** [comment]
The same problem [seems to occur with PrimeNG](https://stackoverflow.com/questions/38599491/primeng-element-not-scoped-cant-be-styled-with-default-angular-2-viewencapsula) so I guess it's not a bug, or might be a bug in Angular core? Fine to close, but I'll let you decide.

And just for future reference: one can easily use Sass and `styleUrls` to include a scoped version of the Bootstrap CSS:

In `my.component.ts`:

```typescript
@Component({
    selector: '...',
    // Use Sass to preprocess the SCSS, and scope the result before adding the final CSS
    // to the <head> of the page:
    styleUrls: ['./my.component.scss']
})
```
...and in `my.component.scss`:

```css
/**
 * Use Sass to prefix ":host /deep/" to all Twitter Bootstrap CSS selectors. Next, when
 * including the resulting CSS using a component's "styleUrls" configuration, Angular will
 * scope it, which nicely limits the CSS to just that component.
 */
:host /deep/ {
    @import '../../node_modules/bootstrap/scss/bootstrap';
}
```

**Comment by pkozlowski-opensource** [comment]
@avbentem as you've observed Angular doesn't re-write CSS rules for the dynamically created content and IMO this makes sense since a dynamically inserted component is ... a component with its own boundaries. So in fact _we_ should be importing Bootstrap CSS in _our_ components. With what you are trying to do it would be necessary to duplicate Bootstrap CSS in _each and every component_ that is using our widgets.... 

We believe that as today including Bootstrap CSS globally is the way to go as this library is targeted at users that already use Bootstrap as their styling framework for the entire website. I understand you desire to encapsulate things properly but I don't think it is technically possible nor practical today.

Anyway, this turns into a discussion that is outside of ng-bootstrap scope so I'm going to close this issue. Feel free to open an issue in the Angular repository if you believe that new facilities shell be added to the framework.
