### ISSUE TITLE
Feature Request: Remove / Simplify / Minimize bootstrap dependency

### ISSUE THREAD

**Issue by Krisa** [ng-bootstrap/ng-bootstrap#988]
### Feature description:
Ultimately, it would be good to not have any dependency at all because:
- bootstrap CSS minimized is about 100KB and for some modules, the styling is really minimal. 
- the getting started is made harder, especially with complex module bundler like Webpack, where it's necessary to add extra configuration, support SCSS or something like this. I.e. it's more than just adding the CSS file.
- View.Encapsulation must remain on NONE to be able to share the CSS file across the whole project

**Comment by pkozlowski-opensource** [comment]
I'm sorry but our goal is to provide directives based on Bootstrap's CSS. Our target audience are people who already use Bootstrap. As such we are not planning to drop Bootstrap as a dependency.

Closing as won't fix.
