### ISSUE TITLE
Modal backdrop to false is not working

### ISSUE THREAD

**Issue by vieillecam** [ng-bootstrap/ng-bootstrap#989]
Actually, when I'm launching the official documentation Plunker for modals, everything is ok. When I change the actual `backdrop: 'static'` to `backdrop: false` as the documentatin says to disable the backdrop, I've got this error : 
`zone.js:390 Error: Uncaught (in promise): Error: Error in ./LoginPageComponent class LoginPageComponent_Host - inline template:0:0 caused by: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.`

There is a plunker showing this issue : 
http://plnkr.co/edit/UnQzhJ7ZC46MQgVy7kL4?p=preview

Angular: `v2.1.0`
ng-bootstrap: `v1.0.0-alpha.10`
Bootstrap: `v3.3.7`

**Comment by pkozlowski-opensource** [comment]
Thnx for reporting. For now it looks like a bug in Angular itself and one that was made visible by 20ad4574aea96fd9acf7f7265eacb8678cad2280. The good news is that we can easily work-around this bug on our end and I've sent a PR #990 as a temporary solution. It will be part of the next release.

I will follow up in the Angular repo to have a proper fix in the long run.

**Comment by vieillecam** [comment]
Amazing. thanks a lot.

**Comment by pkozlowski-opensource** [comment]
@vieillecam reported in Angular as https://github.com/angular/angular/issues/12660
