### ISSUE TITLE
feature request: carousel from data set.

### ISSUE THREAD

**Issue by figuerres** [ng-bootstrap/ng-bootstrap#991]
### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:  2

ng-bootstrap: alpha 10

Bootstrap: 4 alpha 5

carousel:
first if this is already doable sorry i am new at angular 2 and trypescript.
i would like to make one template for a set of slides and feed  the carousel data from a service.

if this can be done now please show how to do it.

thank you !

**Comment by jnizet** [comment]
This could have been a Stackoverflow question, but anyway, here's a plnkr showing an example of what you want to achieve (hopefully): http://plnkr.co/edit/gpyFnORsYfDqNGGWz9bN?p=preview

**Comment by figuerres** [comment]
thanks that is exactly what I needed!!
