### ISSUE TITLE
1:1 Mapping to Bootstrap Components

### ISSUE THREAD

**Issue by briantopping** [ng-bootstrap/ng-bootstrap#993]
This is a general request after reading #738. I believe I am correct in summarizing the closing of it as there being a more flexible way to solve for not having a 1:1 relationship between Bootstrap components and ng-bootstrap components.

Something to consider when you thinking about flexibility: There are a lot of people like myself that are good enough to cobble a site together with these components but actually not very good with front end (at least compared to my backend skill) in general. And while you're absolutely right that not including many components where there is a better path for a skilled user, not-so-skilled users like myself don't really understand why the menu bar is "missing" until digging through tickets.

So while I really regret signing anyone up for additional work, a 1:1 relationship serves some purpose, even if the resultant components are not ideal. 

To the end that this is still a bad idea (it probably is :) ), I might offer that a documentation section demonstrating how to construct the "missing" components would be really awesome. Maybe even more awesome because people like myself can get to that "aha!" moment more rapidly. The bulk of the documentation right now is API doc and to what I could find no actual demo code.

I hope this doesn't come across the wrong way. I'm definitely not lazy, just trying to pass along the experience of someone who isn't a front-end pro and providing a glimpse of what people like me can use.

Thanks for your consideration, please close away if it's not appropriate.

**Comment by pkozlowski-opensource** [comment]
> I might offer that a documentation section demonstrating how to construct the "missing" components would be really awesome. Maybe even more awesome because people like myself can get to that "aha!" moment more rapidly. The bulk of the documentation right now is API doc and to what I could find no actual demo code.

@briantopping yes, we want to have documentation examples for things that have some dynamic behavior bud don't require a dedicated directive (navbar is a good example here). But our focus not is to get to beta and final releases so we are going to focus on directives that _do_ require custom directives in the coming weeks.

Of course documentation updates are always appreciated and I would love to review / merge PRs that are improving docs.

Going to close this one as improving examples in the doc is on our road-map already.

**Comment by briantopping** [comment]
@pkozlowski-opensource Yep, just pointing it out. I'd be happy to contribute if I knew what I was doing. Catch 22. :)
