### ISSUE TITLE
Error when compiling ngBootstrap 1.0.0-alpha.10; Component : Rating

### ISSUE THREAD

**Issue by franko21c** [ng-bootstrap/ng-bootstrap#995]
@ng-bootstrap/ng-bootstrap/rating/rating.d.ts(51,14): error TS1005: '=' expected.

@ng-bootstrap/ng-bootstrap/rating/rating.d.ts(51,27): error TS1005: ';' expected.

My dependencies :

 "dependencies": {
    "@angular/common": "~2.1.1",
    "@angular/compiler": "~2.1.1",
    "@angular/core": "~2.1.1",
    "@angular/forms": "~2.1.1",
    "@angular/http": "~2.1.1",
    "@angular/platform-browser": "~2.1.1",
    "@angular/platform-browser-dynamic": "~2.1.1",
    "@angular/router": "~3.1.1",
    "@angular/upgrade": "~2.1.1",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-alpha.10",
    "angular2-in-memory-web-api": "~0.0.21",
    "angular2-infinite-scroll": "~0.2.6",
    "core-js": "^2.4.1",
    "ng2-translate": "2.4.4",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.39",
    "tether": "1.3.4",
    "zone.js": "^0.6.25"
  },

**Comment by pkozlowski-opensource** [comment]
You seem to be using Typescript 1.8 and we've introduced a non-backward compatible change in alpha.10 that is requiring TS 2.0+. I will push a PR shortly that restores TS 1.8 compatibility. You can switch to TS 2.0+ as a work-around.
